### ISSUE TITLE
seeInDatabase does not match float field

### ISSUE THREAD

**Issue by andrew-semenov** [Codeception/Codeception#1010]
Hello. I have a next issue when check values in database through "seeInDatabase" action 
```
There was 1 failure:
---------
1) purchase/suppliers/SupplierCreationDeletionCept.php
Sorry, I couldn't see in database "Supplier",{"code":"ABC2","name":"NEWsupplier","profit":"1.01","comment":"test comment","isUse":0,"isPricing":0}:
No matching records found
Failed asserting that '0' is greater than 0.

Scenario Steps:
17. I see in database "Supplier",{"code":"ABC2","name":"NEWsupplier","profit":"1.01","comment":"test comment","isUse":0,"isPricing":0}
16. I wait 1
15. I click "Ок"
14. I fill field "Комментарии","test comment"
13. I fill field "Наценка","1.01"
12. I fill field "Название","NEWsupplier"
11. I fill field "Код","ABC2"

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```
If I change 1.01 to 1 value for profit then all will be OK. 

The same behavior with "grabFromDatabase" action.

Codeception version is 2.0.0-alpha

Thank in advance for any help.

**Comment by fakegod** [comment]
try Expression
```
        $I->seeRecord(
            'frontendmarket\models\Order',
            [
                'total' => new Expression('5469.92'),
            ]
        );
```

**Comment by andrew-semenov** [comment]
@pastuhov
thank you for trying to help. In my "functional.suite.yml" I have "PhpBrowser and Db" but "seeRecord" is unavailable  in tests but I found "seeNumRecords" and have next result. The test failed on step 
```
 $I->seeNumRecords(1.1,"Supplier",{"id":10000})
```
and result is
```
 Step  I see num records 1.1,"Supplier",{"id":10000}
 Fail  The number of found rows is not consistent with the asserting
Failed asserting that 1 matches expected 1.1000000000000001.
```

**Comment by Naktibalda** [comment]
Why would you use a floating point number as an expected number of rows?

**Comment by andrew-semenov** [comment]
@Naktibalda 
it is a mistake. I should use there int number. But my main question still not resolved.

**Comment by Naktibalda** [comment]
a) you shouldn't be using float for storing money.
b) if you really need to compare float values, you could grabFromDatabase and use PhpUnit method assertEquals(float $expected, float $actual[, string $message = '', float $delta = 0]) for comparison.

**Comment by andrew-semenov** [comment]
Ok. Thanks. I got you that grabFromDatabase won't be fixed for work with float. Also thanks for solution with PhpUnit.

**Comment by Naktibalda** [comment]
Nothing can match float number exactly.

Short read: http://php.net/manual/en/language.types.float.php
Long read: http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by andrew-semenov** [comment]
Thank you.
