### ISSUE TITLE
fillField fills empty text inside iframe that has body that is contenteditable

### ISSUE THREAD

**Issue by crlaksh** [Codeception/Codeception#1017]
fillField fills empty text inside iframe that has body that is contenteditable

<b>Details of the issue:</b>

Codeception 2.0.0 WebDriver & Codeception 1.6.0.4 Selenium2
<b>Selenium Server:</b> 2.41.0
<b>Browser with issue:</b> firefox 28 & 29 (works in firefox 27 & chrome) 
<b>OS:</b> Linux & Windows
Please note that this issue occurs only in iframe, when filled in comment.html there is no issue.

<b>Html that produces this issue:</b>

<b>Page under test:</b> index.html
&lt;iframe src="comment.html" name="commentFrame"&gt;&lt;/iframe&gt;

<b>iFrame source:</b> comment.html
&lt;!DOCTYPE html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml"&gt;
&lt;head&gt;
	&lt;title&gt;Comment&lt;/title&gt;
&lt;/head&gt;
&lt;body contenteditable="true"&gt;Comment Here...&lt;/body&gt;
&lt;/html&gt;

<b>Teststeps that reproduces this issue:</b>
<b>Testcase file:</b> cept.php
<?php

    $I = new WebGuy($scenario);
    $I->wantTo(' Write a comment ');
    $I->switchToIFrame('commentFrame');
    $I->fillField('body', 'Hello world');

?>

**Comment by cerw** [comment]
I am having same problem with CKEditor is there solution?

**Comment by ixisandyr** [comment]
@cerw for ckeditor it's possible to use the ck editor API to fill the value. This is an example method in a Helper class:

```php
    /**
     * Fill a CK Editor field.
     *
     * @param $value
     *   The value to enter into CK Editor.
     * @param string $selector
     *   A CSS (only) selector to identify the <textarea> element.
     */
    public function fillCkEditor($value, $selector)
    {
        $id = $this->getModule("WebDriver")->executeJs("return document.querySelector('$selector').id");
        $this->getModule("WebDriver")->executeJs("CKEDITOR.instances['$id'].setData(".json_encode($value).")");
    }
```

**Comment by Naktibalda** [comment]
It is browser-specific, so it isn't an issue of Codeception.
It is an issue of Selenium.
