### ISSUE TITLE
 Use of undefined constant CURLOPT_CERTINFO - assumed 'CURLOPT_CERTINFO'

### ISSUE THREAD

**Issue by sooners87** [Codeception/Codeception#1037]
php vendor/codeception/vendor/bin/codecept run
Codeception PHP Testing Framework v1.8.0
Powered by PHPUnit 3.7.37 by Sebastian Bergmann.

  [ErrorException]
  Use of undefined constant CURLOPT_CERTINFO - assumed 'CURLOPT_CERTINFO'

when in run just unit test i don't see this error

**Comment by Naktibalda** [comment]
CONNECTTIMEOUT issue has been reported in #1116
and it contains comment that the issue has been fixed.
