### ISSUE TITLE
$scenario->skip and ->incomplete are respected even when commented out

### ISSUE THREAD

**Issue by pfaocle** [Codeception/Codeception#1050]
Just stumbled on an odd one... using Codeception 2.0-RC2. A test is marked as to skip or incomplete even if the `$scenario->...` declaration is commented out.

To reproduce, start a clean Codeception set-up and add a Cest:

```
codecept.phar generate:cest acceptance Test
```

Then edit the outputted Cest file, adding a single commented line to the example `tryToTest()` method:

``` php
<?php
use \WebGuy;

class TestCest
{
    public function _before()
    {
    }

    public function _after()
    {
    }

    // tests
    public function tryToTest(WebGuy $I)
    {
        /* $scenario->incomplete('Wat.'); */
    }
}
```

Run it - expected behaviour (I guess?!) is to run the test. Actual behaviour:

![1__bash](https://cloud.githubusercontent.com/assets/216767/3132694/72f1e864-e812-11e3-87c1-078696706e90.png)

This seems to behave similarly for single- and multi-line comments, as well as docblock style comments starting with `/**`:

``` php
/** $scenario->incomplete('Wat.'); */
/* $scenario->incomplete('Wat.'); */
// $scenario->incomplete('Wat.');
```

Both `->incomplete(...)` and `->skip(...)` behave the same way.

**Comment by shtrih** [comment]
Try this:
```php
<?php
if (false)
    $scenario->skip();

$I = new ApiTester($scenario);
$I->wantTo('Do nothing and pass!');
```

It's skips regardless of any conditions (2.0.11).

**Comment by eugene-manuilov** [comment]
@shtrih same for me... Chime in @DavertMik

**Comment by DavertMik** [comment]
Well, I must admit that we can't handle all cases without writing own PHP parser or reparsing code with PHP hooks. `$scenario->skip` instructions should be executed before the test launch, right now they are parsed with regex.

If you have ideas how to run PHP script withou actually running it, please go on )
Right now I don't recommend using conditionals in `skip`, probably you can replace them with environments

**Comment by eugene-manuilov** [comment]
This is not cool... What if `skip` method will throw an exception instead of instantiating a blocker step? That exception will be caught during test run and a test will be interrupted with appropriate status. Would it work?

**Comment by DavertMik** [comment]
Not really, the issue here that we need to bypass before/after callbacks for skipped tests. That would save time (and dramatically save time in case of WebDriver). Probably `$scenario->skip()` can be replaced with annotation or better to say php comment. However, this should be preparsed before the test was executed
