### ISSUE TITLE
Динамическая смена домена

### ISSUE THREAD

**Issue by TrustNik** [Codeception/Codeception#1086]
Есть тест:
1. С первого домена сабмитим форму на второй домен (POST)
2. Проверяем что урл верный.
3. Проверяем что для второго домена установились куки.

В старой версии тест работал (1.6.7), в новой не работает, т.к. при сабмите формы на другой домен codeception не переключает у себя внутри настройки на этот новый домен. И когда происходит проверка кук - идет проверка этих кук по имени на первом домене.

**Comment by Naktibalda** [comment]
Is it still relevant a year later?

**Comment by TrustNik** [comment]
Sorry, can't test that now. Probably could be closed
