### ISSUE TITLE
FATAL ERROR. TESTS NOT FINISHED. Call to a member function request() on a non-object 

### ISSUE THREAD

**Issue by mikeerickson** [Codeception/Codeception#1093]
Receiving the following error when call the REST post routine sendPOST (see associated test)

```
    $I->am('developer');
    $I->sendPOST('companies', ['name', 'CodeDungeon'], null);
    $I->canSeeResponseIsJson();
```

<code>
FATAL ERROR. TESTS NOT FINISHED.
Call to a member function request() on a non-object 
in /Users/mikee/Documents/Projects/rangladex/vendor/codeception/codeception/src/Codeception/Module/REST.php:377
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Call to a member function request() on a non-object","file":"\/Users\/mikee\/Documents\/Projects\/rangladex\/vendor\/codeception\/codeception\/src\/Codeception\/Module\/REST.php","line":377}}%
</code>

**Comment by sandinosaso** [comment]
Can you share your fix, having same problem here. Thank you
