### ISSUE TITLE
Upgrading 2.0 Symfony2 and RedirectResponse

### ISSUE THREAD

**Issue by judgedim** [Codeception/Codeception#1100]
**code:**
```php
new RedirectResponse("/index.php?ln=test@gmail.com&sn=testnumber");
```

**access.log:**

*before upgrade (v1.8.6)*
"GET /index.php?ln=test%40gmail.com&sn=testnumber"

*after upgrade*
"GET /index.php?ln=test%40gmail.com&amp%3Bsn=testnumber"

Problem with "&".  In Symfony convert special characters to HTML entities in this place: 
https://github.com/symfony/symfony/blob/v2.4.6/src/Symfony/Component/HttpFoundation/RedirectResponse.php#L100

Do you have any idea how fix it (used PhpBrowser)?

**Comment by mattbit** [comment]
I've added the `htmlspecialchars_decode` in `Codeception\Lib\Connector\Guzzle6`. This should fix the problem with the html entities in the meta url attribute.

**Comment by mattbit** [comment]
I've added the same fix in `Codeception\Lib\Connector\Guzzle` since php 5.4 does not support guzzle 6.
If it's ok I can squash the commits.
