### ISSUE TITLE
Save reports for each test run in a separate directory.

### ISSUE THREAD

**Issue by ghost** [Codeception/Codeception#1101]
After each test run, all reports are stored in the `output` directory. 
Can I make it so that they were kept in a separate subdirectory?

For example:

16-06-2014-00-12 /
16-06-2014-01-12 /
17-06-2014-09-00 /
etc...

**Comment by longnd** [comment]
@DavertMik, as you said
> You can specify the exact name of destination file when using xml, html or coverage-* options
how can I do it exactly?
I don't see an option to specify the destination file for reports.

btw, can we specify different reports for each kind of test (unit, functional, acceptance ...) since they're all writing to the same file.
Thank you
