### ISSUE TITLE
HELP!  FATAL ERROR. TESTS NOT FINISHED.

### ISSUE THREAD

**Issue by mikeerickson** [Codeception/Codeception#1111]
I have been battling this issue for weeks and until now, I have just worked around it (ignored testing this part of application) but I have to face it head on now and dont know what to do.

I am simply trying to perform a simple test POST using API suite.  

If there are any suggestions, it would be greatly appreciated!

Error

FATAL ERROR. TESTS NOT FINISHED.
Call to a member function request() on a non-object 

Test method causing error

	public function it_should_create_new_resource(ApiTester $I)
	{
		$I->sendPOST($this->baseUrl().'companies', ['name', 'CodeDungeon'], null);
		$I->canSeeResponseIsJson();
	}

api.suite.yml

class_name: ApiTester
modules:
  enabled: [REST, ApiHelper, PHPBrowser]
  config:
    PHPBrowser:
      url: http://rangladex.app:8000/
  REST:
    url: http://rangladex.app:8000/api/v1/

**Comment by zbateson** [comment]
Should be fixed now with #1834
