### ISSUE TITLE
не кажет кирриллицу в консоль

### ISSUE THREAD

**Issue by xowirun** [Codeception/Codeception#1117]
добрый день, проблема с выводом кириллицы в консоль, не нашёл такой проблемы здесь.
$i = new ApiTester($scenario);
$i->wantTo('видель кириллицу в консоли');
при ошибке получаем:
1) Failed to �������� �������������� �����������������������in ...
Убунта 14, кроме данного случая кириллица всегда отображается в консоли исправно.

**Comment by andkirby** [comment]
Did you check your file in UTF-8?

**Comment by sergeyklay** [comment]
![screenshot at jun 07 01-44-53](https://cloud.githubusercontent.com/assets/1256298/15840267/777b6d44-2c51-11e6-98ab-a0648ac40efa.png)

**Comment by xowirun** [comment]
рад, что за два года проблема решилась) вопрос закрыт.
