### ISSUE TITLE
Module Connection Issue which brings Fatal Error

### ISSUE THREAD

**Issue by TrustNik** [Codeception/Codeception#1119]
I have this test:
```
$I->sendGET('/url/', $getParams);
$I->seeResponseCodeIs(200);
$I->see('Text', '.selector');
```
This test works perfectly fine at old version of codeception -1.6.7. But has fatal error at new version 2.0.
Fatal error occured here https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/InnerBrowser.php#L560
And thanks to @DavertMik because of @ it was really hard to debug that :)
Error:
```
Call to a member function filterXPath() on a non-object
```

I have found this issue https://github.com/Codeception/Codeception/issues/945
I cant explain why we use sendGET instead of amOnPage. But my point is - there shoud be appropriate handling of this situation.

**Comment by DavertMik** [comment]
Codeception 2.1 introduces dependent module concept to fix such issues.
Starting from 2.1 you should explicitly specify dependency of REST module.
