### ISSUE TITLE
Xpath expressions failing to select correct node when node has no 'id' attribute

### ISSUE THREAD

**Issue by onshop** [Codeception/Codeception#1139]
Here is an example of how the multi-select checkbox group is rendered in Zend Framework 2 using the FormMultiSelectCheckbox Element. Note the abscence of id attributes:

    <label>
        <input id="task_types" type="checkbox" value="6" name="task_types[]">
        Capability
    </label>
    <label>
        <input type="checkbox" value="4" name="task_types[]">
        Defect
     </label>
    <label>
        <input type="checkbox" value="5" name="task_types[]">
        Optimisation
    </label>

If I use a browser-based XPath expression validator, the following expressions are valid and identify the desired element:

    //input[@name='task_types[]' and @value='4']
    //label[contains(text(),'Capability')]/input
    (//input[@name='task_types[]'])[2]

However, if I use the same expressions in Codeception it clicks on either the first or last match and not the one indexed. For example:

    $I->checkOption(//input[@name=\'task_types[]\' and @value=\'4\'] );

...clicks on the the last checkbox.with value 5 instead of 4.

These Xpath expressions will work if each checkbox has an id attribute,

Zend Framework 2's formmulticheckbox element provides an id for the first checkbox but doesn't for each subsequent checkbox. I therefore had to implement a workaround to create an id attribute for each of the checkboxes in order for the Xpath expressions to work.

**Comment by Naktibalda** [comment]
I tested this issue with PhpBrowser and WebDriver,
in both cases checkOption worked correctly.
```php
$I->checkOption("//input[@name='task_types[]' and @value='4']");
```
