### ISSUE TITLE
How to build codeception.phar?

### ISSUE THREAD

**Issue by pablopaul** [Codeception/Codeception#1197]
How can I build codeception.phar from current branch?
I saw in commit log that the interactive console will be fixed in 2.0.3 but want to test it before 2.0.3 now if possible.

Thanks

**Comment by onshop** [comment]
In 2.0.10, if I go into the vendor/codeception/codeception folder and run robo build:phar I get:

    ERROR: require_once(): Failed opening required '/Users/user1/extranet.local/vendor/codeception/codeception/vendor/autoload.php' (include_path='.:') 
    in /Users/user1/sites/extranet.local/vendor/codeception/codeception/RoboFile.php:2

It is calling

    require_once __DIR__.'/vendor/autoload.php';

Which suggests that I should running it from the root folder above vendor but I cannot run it from the command from the root folder. I am either missing something in the install instructions or something else.

If I point it to a relative path it builds codecept.phar but then cannot compile it.

**Comment by Naktibalda** [comment]
clone this repo and run robo.phar in the main directory of it.

**Comment by onshop** [comment]
@Naktibalda . Thanks. Will try that.

**Comment by onshop** [comment]
Robo will still be looking for __DIR__.'/vendor/autoload.php'; in RoboFile.php and this path does not exist relative to the main directory. Have I completely missed something fundamental here?

**Comment by Naktibalda** [comment]
composer install

**Comment by onshop** [comment]
Codeception was installed using 'composer install' into the /vendor directory but, as I wrote in the original post, RoboFile,.php is trying to load relative path __DIR__.'/vendor/autoload.php'.
