### ISSUE TITLE
utf-8 support problems

### ISSUE THREAD

**Issue by gennadiylitvinyuk** [Codeception/Codeception#120]
Hi

I want to report some little problems.

If I make tests with utf-8 characters, for example with ü

I see "wu00fcrstchen" instead of "würstchen" in html-reports

The checks themself are ok, only the output has problems.

**Comment by githubjeka** [comment]
## FIX for Windows

You need to use Lucida console fonts.

You can set code page before going to work with cmd.

```
$I->seeInTitle('Система учёта');
I see in title "╨б╨╕╤Б╤В╨╡╨╝╨░ ╤Г╤З╤С╤В╨"
```

set new code page 

```
chcp 65001
```

```
$I->seeInTitle('Система учёта');
I see in title "Система учёта"
```
