### ISSUE TITLE
Functional Testing with Laravel4 Module and Stripe

### ISSUE THREAD

**Issue by bretterer** [Codeception/Codeception#1221]
I have run into an issue when testing a registration form in Laravel that is using stripe.  My form input field is as follows

```
<div class="form-group">
    {{ Form::label( 'credit-card', 'Credit Card Number', ['class'=>'col-sm-3 control-label'] ) }}
    <div class="col-sm-7">
        {{ Form::text( null, null, ['class'=>'form-control card-number', "data-stripe"=>"number", 'placeholder'=>'Card Number' ]) }}
    </div>
</div>
```

The issue I believe is when I am running 

```
$I->fillField('input[data-stripe=number]','4242424242424242');
```

which causes me to get a `InvalidArgumentException: Malformed field path ""` response from my test.  I am sure this is because the textfield does not have a name attribute.  It does not use a name attribute because i use stripe.js to pass a token and do not want the input field to be sent.  I have confirmed this is the case by only changing my Form::text to have a name attribute.  Once that is there, everything works as expected.

**Comment by dwenaus** [comment]
I'm having the same issue where codeception cannot see or fillfield an input text field without a name attribute.

**Comment by janhenkgerritsen** [comment]
Is your issue specific to the Laravel module? If so we can reopen this issue. But I suspect the issue is not specific to the Laravel module, and in that case you can better open a new issue.

**Comment by t202wes** [comment]
I have issues with this too. It won't select the field if there is no name attribute on the input. I even try different selectors and it just fails when running through laravel server. If I use browser it's ok.

**Comment by jaumeavila** [comment]
It happens the same to me.

Any solution???

**Comment by janhenkgerritsen** [comment]
I traced the issue with input fields without a name attribute, see #3133.
