### ISSUE TITLE
canSee isn't working properly

### ISSUE THREAD

**Issue by hlorofos** [Codeception/Codeception#1229]
bash-3.2$ bin/codecept --version
Codeception version 2.0.0

UpdaterCept.php - acceptance test:

$I->amOnPage("update?os=mac&version=6.2.0.666"); 
$I->canSee('some stuff');

fatal error:
Trying to Check old updater.php scenarios (UpdaterCept.php)                                                    [F]PHP Fatal error:  Call to a member function getHistory() on a non-object in /Applications/XAMPP/htdocs/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php on line 184

**Comment by bazo** [comment]
this error is still present. even in the deve version. 

it occurs for me when the url contains a query string or at least a ?
which makes canSee and others quite useless

**Comment by zbateson** [comment]
Should be fixed with #1834 - please let us know if there's still an issue.
