### ISSUE TITLE
Webdriver subdomains after redirect

### ISSUE THREAD

**Issue by urgor** [Codeception/Codeception#1236]
Hi. Is there way to get and check sub domain(s) after redirect? E.g. when i go to mysite.com it redirects to en.mysite.com, or to de.mysite.com . I need to check that final language sub domain is "en".

**Comment by Naktibalda** [comment]
It can be achieved by using a helper method:

```php
public function seeFullUrlEquals($expected)
{
  $actual = $this->getModule('WebDriver')->webDriver->getCurrentURL();
  $this->assertEquals($expected, $actual);
}
```
