### ISSUE TITLE
Module DB parsing issue?

### ISSUE THREAD

**Issue by Salvner** [Codeception/Codeception#1245]
My code requires some sql to be on multiple lines as having them on the same line results in errors due to weird reasons, this works fine when run as a query through sql, but is counted as a syntax error when run through codeceptions db, my current workaround is to use HaveInDataBase but thats a bit annoying as the form is different to that of my database dumps.
Is there something I could alter to change this?

**Comment by gammamatrix** [comment]
If you have your semicolon delimiter on a separate line, you will get a syntax error if there are subsequent queries in your dump.sql file.

For example, this fails:

```sql
REPLACE INTO `Contacts` (`created`, `modified`, `status`, `contact`, `first`, `last`) VALUES
(NOW(), NOW(), 1, 'Bob Ross', 'Bob', 'Ross'),
(NOW(), NOW(), 1, 'Fred Flintstone', 'Fred', 'Flintstone')
;

DELETE FROM `Order`;
```

Moving the semicolon to the last data row does not fail:

```sql
REPLACE INTO `Contacts` (`created`, `modified`, `status`, `contact`, `first`, `last`) VALUES
(NOW(), NOW(), 1, 'Bob Ross', 'Bob', 'Ross'),
(NOW(), NOW(), 1, 'Fred Flintstone', 'Fred', 'Flintstone');

DELETE FROM `Order`;
```

Is this the same issue you had @Salvner ?
