### ISSUE TITLE
Running functional suite results in exception, running all tests separate and they all pass.

### ISSUE THREAD

**Issue by megawubs** [Codeception/Codeception#1247]
For detailed explanation of the bug see: [stack-overflow](http://stackoverflow.com/questions/24971083/codeception-functional-tests-fail-when-run-together-succeed-when-run-seperatly/24974455#24974455)

It's a 2.0.3 specific bug.

**Comment by Naktibalda** [comment]
I think that it was fixed in 2.0.4
