### ISSUE TITLE
Get current running test name

### ISSUE THREAD

**Issue by marcioAlmada** [Codeception/Codeception#1251]
Is there a way to get current running test from the test runner being on a Cest context? Something like:

```php
$someHelper->getCurrentRunningTest();
```

**Comment by DavertMik** [comment]
Now you can get it with `$scenario->current('name')`

**Comment by marcioAlmada** [comment]
:+1:

**Comment by petrisorionel** [comment]
public $testName = null;

    public function _before(TestInterface $test) {
        parent::_before($test); // TODO: Change the autogenerated stub
        $this->testName = $test->getMetadata()->getName();
    }

**Comment by CJDennis** [comment]
OK, so it took ages, but I found you can get the name of a plain unit test (not a cest) with `$this->getName()`.
