### ISSUE TITLE
[PHPUnit_Framework_ExceptionWrapper] json_encode(): Invalid UTF-8 sequence in argument

### ISSUE THREAD

**Issue by Sepuka** [Codeception/Codeception#1253]
When i trying to run some tests i get the following error:
[PHPUnit_Framework_ExceptionWrapper] json_encode(): Invalid UTF-8 sequence in argument

It happen when i call "amOnPage" functionion, for example i want to "/". Later i check result url and i going to next case, for example "/otherAddr", and i got error.

Code example
$I->amOnPage('/');
$I->seeCurrentUrlEquals('/site/login');
// correct work
// now i going to other page
$I->amOnPage('/otherExistsPage');
$I->seeCurrentUrlEquals('/site/login');
// now i see error

If i interchange addr (first '/otherExistsPage', and second '/') then first case passed, but second case failed.
Codeception version 2.0.4

On my localhost computer problem is not appear, problem is appear on prepoduction machine.

**Comment by chetanakambad** [comment]
HI,
I am new in yii and i have problem in codeception like below:
Couldn't fill field "Username","admin":
Form field by Label or CSS 'Username' was not found on page.

Scenario Steps:
2. I fill field "Username","admin"
1. I am on page "/login"


FAILURES!
Tests: 1, Assertions: 0, Failures: 1.
