### ISSUE TITLE
PhantomJS and weird selector with canSeeElement

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#1254]
Hi

I am using PageObjects to configure some elements, I have one element named: 

```
#knowEnergyUsage

public static $KnowEnergyUsage = '#knowEnergyUsage';
```

When I run my tests, with something like:

```
$I->canSeeElement(TestPage::$KnowEnergyUsage);
```

I get the following error:

```
Sorry, I couldn't see element "#know energy usage":
```

I'm using PhantomJS to run my tests.

The CSS selector definitely exists as I can target it when using Selenium

Is this a possible bug?

Thanks

**Comment by ssfinney** [comment]
I have many issues looking for CSS selectors with Codeception in general.

**Comment by Naktibalda** [comment]
PhantomJS is dead https://github.com/ariya/phantomjs/issues/15344
