### ISSUE TITLE
Test code or tested code did not (only) close its own output buffers

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#1262]
I am getting this error now and then in combination with Yii2. I drilled the issue down to the occurence of an error NOTICE.

When I change error_reporting(E_NOTICE) to error_reporting(E_ERROR), the code continues.

It took quite a while to traverse through the code to get to this error. Isnt there a better response than "Test code or tested code did not (only) close its own output buffers"?

I prefer maximal insights. Why not outputting errors to the log area? Or to the console?

thanx

**Comment by samdark** [comment]
Seems to be fixed.
