### ISSUE TITLE
Laravel4 Module: multiple functional tests failing

### ISSUE THREAD

**Issue by bretterer** [Codeception/Codeception#1275]
I am running a couple Cepts, LogoutCept and SignUp Cept.  When I run each of them on their own, they work just fine, but when I run them as a group `codecept run functional` the last cept fails.  
Here are my cepts

LogoutCept.php

     <?php 
     $I = new FunctionalTester($scenario);
     $I->am('a member');
     $I->wantTo('log out of Application');
        
    $user = $I->haveRecord('users', [
      'first_name'=>'test',
      'last_name'=>'account',
      'email'=>'test@test.com',
      'password'=>'testaccount'
    ]);

    Auth::loginUsingId($user);

    $I->assertTrue(Auth::check());

    $I->amOnPage('/');
    $I->click('Logout');

    $I->seeCurrentUrlEquals('');
    $I->see('You have been logged out!');
    $I->assertFalse(Auth::check());

SignUpCept.php

    <?php 
    $I = new FunctionalTester($scenario);
    $I->am('a guest');
    $I->wantTo('sign up for a License WP account');
    
    $I->amOnPage('/');
    $I->click('Register');
    $I->seeCurrentUrlEquals('/register');
    
    $I->fillField('first_name', 'Test');
    $I->fillField('last_name', 'Account');
    $I->fillField('email', 'test@test.com');
    $I->fillField('password', 'testaccount');
    $I->fillField('password_confirmation', 'testaccount');
    $I->click('Register', '#registration-form');
    
    $I->seeCurrentUrlEquals('');
    $I->see('Welcome to Application!');
    
    $I->seeRecord('users',[
      'first_name' => 'Test',
      'last_name' => 'Account',
      'email' => 'test@test.com'
    ]);
    
    $I->assertTrue(Auth::check());

The error I am getting is:

    1) Failed to sign up for a license wp account in SignUpCept (/home/vagrant/application/app/tests/functional/SignUpCept.php)
    Can't be on page "/":
    ErrorException: Route [register_path] not defined. (View: /home/vagrant/application/app/views/partials/nav/loggedout.blade.php) (View: /home/vagrant/application/app/views/partials/nav/loggedout.blade.php)

However register_path is defined as it works when i run SignUpCept on its own.

**Comment by mabasic** [comment]
I can confirm that changing `require_once` to `require` solves this issue for me.

**Comment by samdark** [comment]
@mabasic do you mean adjustments to Laravel application code or adjustments to Codeception code?

**Comment by mabasic** [comment]
@samdark Adjustements to Laravel application. I think that this has nothing to do with Codeception, but with Laravel. Using `require` instead of `require_once` in `routes.php` in Laravel solves this.

**Comment by samdark** [comment]
OK. Closing the issue then.

**Comment by cjaoude** [comment]
This thread saved my sanity. This was driving me nuts for hours. But, for the record, it might still be FUBAR with Laravel 5.1.

Switching to `require` only would cause Laravel to hang. Make sure you put your route partials in a sub-folder then call to avoid any issues.
```
foreach (File::allFiles(__DIR__.'/partials') as $file) {
    require $file;
}
```
