### ISSUE TITLE
TestCase::getTestSignature() is not "resolved correctly" when Cept lives in a subfolder and is not called directy

### ISSUE THREAD

**Issue by pablopaul** [Codeception/Codeception#1289]
Hei guys, 
I have a sample Cept which __failes intentionally__ and I put the following hook in `AcceptanceHelper.php`

```php
public function _failed(\Codeception\TestCase $test, $fail)
{
    $filename = str_replace(['::','\\','/'], ['.','',''], \Codeception\TestCase::getTestSignature($test)).'.fail.png';
    $this->debug($filename);
    $this->_saveScreenshot(codecept_output_dir($filename));
    $this->debug("Screenshot was saved into '_output' dir");
}
```

Calling the Cept directly produces the expected screenshot `php codecept.phar run acceptance "subFolder/SnippetsCept.php" --debug -vvv`

__Debug Output:__
```terminal
subFolderSnippetsCept.fail.png
Screenshot was saved into '_output' dir
```

But calling the Cept "indirectly" by just passing the containing folder name generates a "invalid" filename and therefore an empty file is stored in `_output` dir `php codecept.phar run acceptance "subFolder/" --debug -vvv`

__Debug Output:__
```terminal
U:Automatisierte Testscodeception_snippetstestsacceptancesubFolderSnippetsCept.fail.png
Screenshot was saved into '_output' dir
```
![Image](http://s15.postimg.org/6qf4bci5n/screenshotname.png)

My best guess is that `\Codeception\TestCase::getTestSignature($test)` is not "resolved correctly" when Cept lives in a subfolder and is not called directy via filename.

----
`Codeception version 2.0.3`
`Windows 7`

**Comment by Naktibalda** [comment]
`Codeception\TestCase` class no longer exists in 2.2
