### ISSUE TITLE
How to print additional information to console in the AcceptanceHelper class

### ISSUE THREAD

**Issue by sorbing** [Codeception/Codeception#1295]
I am implementing a custom tests methodand I can not write text message in console. I need to show in the console log the number found DOM elements. How can I display the text to the console? Thanks.

**Comment by ksiv** [comment]
@Sorbing, thanks for a solution, I adopted it and use widely. Unlike codecept_debug, it works everywhere.  :-)

**Comment by vedro-compota** [comment]
@Sorbing thanks! I use your idea in log() method: https://github.com/it-for-free/rusphp/blob/master/Testing/Codeception/Acceptance/IFFAcceptanceTester.php
