### ISSUE TITLE
Console colors

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#1310]
@DavertMik, any Ideas on the issue that the colors you are setting in Codeception\Lib\Console\Output are not connected (i.o.w. not working in Run.php?)

**Comment by DavertMik** [comment]
I remember I fixed something like that in recent releases. Reopen if I'm wrong

**Comment by Maxlive-Dev** [comment]
@DavertMik same problem in 2.2.2 - i.e. --no-colors isn't supported:
>   [Symfony\Component\Console\Exception\RuntimeException]
>  The "--no-colors" option does not exist.

And what is worse - **colors: false** doesn't work too, though it works in 1.8.3 with the same config.

How to make colors off in 2.2.2?
Please, reopen.

**Comment by Maxlive-Dev** [comment]
PS: that's true for both Win and *nix.
On Windows console became unreadable.

**Comment by Naktibalda** [comment]
Try to use `--no-ansi` option.

**Comment by InputOutput** [comment]
I have a red FAIL always: 
./codecept run acceptance --env=testrunner --no-colors -q --report --no-ansi Accounts

colors: false in codeception.yml also ...
