### ISSUE TITLE
Yii2 module ajax POST request

### ISSUE THREAD

**Issue by Ragazzo** [Codeception/Codeception#1316]
It would be great if we will implement for `Yii2` module its own implementation for post ajax requests `Yii2::sendAjaxPostRequest()` since they should include `csrf` token, that can be taken from `meta` tag of the page. Will work on PR on this one later, or one can make it if have time ;)

**Comment by samdark** [comment]
Closed since CSRF is disabled for tests by default in current Yii project templates.
