### ISSUE TITLE
method seeFileContentsEqual failed if the files contain Enter key ( line-break)

### ISSUE THREAD

**Issue by liucf** [Codeception/Codeception#1318]
I use seeFileContentsEqual method to compare two files,  if these files do not include Enter key( line-break ) character, it is pass. 
BUT, if have any  Enter key( line-break )  in the files, it will be failed.

I test it in both windows and MAC OS.
any problem? can you please help me?

thanks

**Comment by krukru** [comment]
seeFileContentsEqual should remove newlines before doing comparison, but looking at the code it removes just "\r". As far as I know, "\r" is no longer a newline delimiter for any platform. Maybe this should be removing PHP_EOL, and not "\r"?

**Comment by ruudboon** [comment]
I don't see this happening in v4 anymore.
