### ISSUE TITLE
Yii2 - seeResponseCodeIs

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#1326]
seeResponseCodeIs does not seem very practical (see https://github.com/Codeception/Codeception/issues/1262#issuecomment-51221626): when a Http error is thrown. the current test stops.

How could we make seeResponseodeIs working for functional tests? Currently I have to use acceptance tests for it. I assume it once worked, as it is part of the Yii connector. Where to look? Where to fix?

**Comment by bixuehujin** [comment]
It is shouldn't be a problem now, #1693 is already fixed this
