### ISSUE TITLE
Db Module Initialization

### ISSUE THREAD

**Issue by TroyRudolph** [Codeception/Codeception#1328]
Hello.  We have just started to the the Db module in our acceptance tests.  It is working as designed and is quite useful.

We do have one challenge, however.

In our acceptance suite, the first test creates the "client site" to be tested.  Therefore the client database does not yet exist.  The Db module wants to connect to the client database as soon as the suite starts and, of course, it fails because we haven't yet created the client and therefore the client database does not exist yet.

We have been getting around the challenge by manually creating the client site.  This is not a good solution for us, for IT-related reasons.

Would it make any sense to modify the Db module to do lazy initialization?  That is, to initialize it only upon first use?

Could I do this in a wrapper for the Db module?

Thank you
Troy

**Comment by Naktibalda** [comment]
No work is necessary for this issue.
