### ISSUE TITLE
The concept of Cest's

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#1335]
@DavertMik, I would like to discuss the concept of the Cests and how it should or should not be applied. 

Questions to be answered:
* Is Cest to be extended? 
* Why should one use Cest & not extend from PhpUnits Test?
* Is Cest naming handy with repect to lack of support by IDE (Netbeans does not support it so you cannot use nice functions like "run focused test method" etc.)

thanx

**Comment by Naktibalda** [comment]
This ticket is a discussion, not an issue.
