### ISSUE TITLE
Add option to Yii2 module to enable log targets

### ISSUE THREAD

**Issue by Ragazzo** [Codeception/Codeception#1342]
I find it useful to check some debug request data with `yii2 - debug` module that is collected from logs when tests are run. So we can add `enableLogs` option to `Yii2` module to enable this log [targets](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/Connector/Yii2.php#L72)

**Comment by samdark** [comment]
Won't be implemented till more people will request it. Closing.
