### ISSUE TITLE
Curl Exception On Redirect

### ISSUE THREAD

**Issue by parhamdoustdar** [Codeception/Codeception#1348]
I'm trying to test a page that the currently logged-in user doesn't have access to. When this user opens this page, he is redirected to an "access denied" page. So, the page that he is trying to access has an empty response, but the headers have a "location:" entry, which should make Curl (and hence the test) go to the new page.

However, when I run my tests, I get this:

```
Guzzle\Http\Exception\CurlException: [curl] 52: Empty reply from server [url] localhost/elf/system/resource/requestForm
```

The exception is correct – the response is indeed empty, but this shouldn't matter when it's a redirection. Also, I've looked at Guzzle's documentation, and it says that Guzzle automatically follows redirections. So why does:

```php
$I->amOnPage('system/resource/requestForm');
```

throw this exception?

**Comment by Naktibalda** [comment]
We no longer support Guzzle 3.
