### ISSUE TITLE
Yii2 - Functional testing - Too many connections 

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#1363]
Im getting an explosion of db-connections when running functional tests with Yii2. If the test sequence is long enough, it will reach its maximum allowed connections.

Is this normal behavior?

**Comment by anders-akero** [comment]
I had the exact same problem and adding 
```
            'attributes'=>[
                PDO::ATTR_PERSISTENT => true
            ]
```
helped me.

**Comment by adamdry** [comment]
I had the same problem on the unit (integration) tests and adding PDO::ATTR_PERSISTENT => true to my config worked too!

**Comment by hmphu** [comment]
@anders-akero  thank you so much, this helped me

**Comment by DanaLuther** [comment]
I ran into the same issue today - setting the persistent attribute solved it beautifully. Thank you!!!
