### ISSUE TITLE
Test Failure should contain additional information

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#1366]
Currently test failure is indicated by `PHPUnit_Framework_AssertionFailedError` exception thrown. 
It contains description of failure from the PHPUnit's point of view. Codeception may provide additional valuable information into it, like

* screenshot
* steps
* html page 

In order to achieve this, Codeception should wrap `PHPUnit_Framework_AssertionFailedError` in its own failure class, and rethrow it on failure. `_failed` hooks on modules, helpers, should be able to attach additional info into failure exception.

This will be useful for extensions, for error display, for report tools, etc.

**Comment by atorian** [comment]
other side of this bug is:
exceptions ContentNotFound and ElementNotFound does not extend ConditionalAssertionFailed
thats why "catch" can't handle it.

**Comment by DavertMik** [comment]
Well, it should not print the failure in case of conditional exception. This part of code is just to record the failure and go on. So the failed method is not called

**Comment by DavertMik** [comment]
I don't think this issue is really important for 2.1 release. Wrap all PHPUNit framework assertions in own classes is a good idea, however it may lead to replacing PHPUnit assertions with our own. We are not ready for that )
