### ISSUE TITLE
Broadcast an event before initializing modules

### ISSUE THREAD

**Issue by grantlucas** [Codeception/Codeception#1370]
I'm currently maintaining [Phantoman](https://github.com/site5/phantoman) which is responsible for starting and stopping PhantomJS around test runs. In its current form, it will start PhantomJS when the extension is constructed and then will stop it when it is destructed.

This works alright but presents some problems. In the destruction phase, I can't throw any `Extension\Exception`. There are some cases where I'm unable to shutdown PhantomJS properly and thus would like to throw an exception.

I *can* shutdown just fine in the `after.suite` event, checking that it was the `acceptance` suite that just finished so that we don't shut it down pre-maturely.

I'd like to be able to start PhantomJS only for `acceptance` suite runs. Right now if you run a unit test suite, it will start and then stop PhantomJS when it's not needed.

If I try to start PhantomJS in `suite.init` or `suite.before` I get

```
[WebDriverCurlException]
  Curl error thrown for http POST to http://127.0.0.1:4444/wd/hub/session with params: {"desiredCapabilities":{"browserName":"phantomjs"}}
  couldn't connect to host at 127.0.0.1:4444
```

Which is created when the WebDriver module is initialized. It makes sense that it'd throw an error since PhantomJS isn't reachable.

It would be great if there was an event thrown right before [initializing modules](https://github.com/Codeception/Codeception/blob/eb0273ec6a3af817c2b8e9ff3fbd35fdaa31d215/src/Codeception/SuiteManager.php#L60). Then I could start and stop PhantomJS only for acceptance tests.

Do you see any issues with adding a new event?

**Comment by Laykou** [comment]
I'm also starting to use Phantoman now and I would really appreciate to have this feature - to load phantoman only for acceptance tests. Is there any progress yet?

**Comment by grantlucas** [comment]
:tada: Thanks @DavertMik!
