### ISSUE TITLE
Codeception 1.8.7 via Composer - wrong path to autoload.php

### ISSUE THREAD

**Issue by szoper** [Codeception/Codeception#1371]
I've just installed version 1.8.7 via Composer and I'm unable to run vendor/bin/codecept, as it tries to include ``vendor/bin/autoload.php`` instead of ``vendor/codeception/codeception/autoload.php``.
You might want to patch it :-)
```
vagrant@precise64:/vagrant$ php vendor/bin/codecept bootstrap
PHP Warning:  require_once(/vagrant/vendor/bin/autoload.php): failed to open stream: No such file or directory in /vagrant/vendor/bin/codecept on line 7
```

**Comment by J-Fricke** [comment]
My solution was simply to link to `./vendor/codeception/codeception/codecept` instead of the one in `./vendor/bin/codecept` for my alias which works without modifying any code.
