### ISSUE TITLE
Unable to interact with window popups using PhantomJS

### ISSUE THREAD

**Issue by grantlucas** [Codeception/Codeception#1372]
**I'm not 100% sure if this is a Codeception issue but I figured this would be a good place to start**
## Issue

I came across an issue where I'm unable to interact with a `window.confirm` when using PhantomJS with the WebDriver module.

Using the exact same test with a manually started Selenium server and Firefox works as expected.
## Example

I've set up a repository for Codeception tests and have a branch, [failingPopup](https://github.com/grantlucas/codeception_testing/tree/failingPopup) that has everything set up to reproduce the issue. It also mirrors the setup I'm using in my project.

The [Popup acceptance test](https://github.com/grantlucas/codeception_testing/blob/54d06ac29b4e11b1cf0c63a0b6aee69d233f181c/tests/acceptance/PopupCept.php) manually creates a `window.confirm` popup and tries to confirm text within and then accepts the popup.

This test works as expected with Firefox+Selenium but fails when using PhantomJS

---

Any help on this is greatly appreciated. Since you know what exactly Codeception is doing behind the scenes you may think that this issue is better suited for one of the other parts involved, like PhantomJS or WebDriver. Please let me know if this is should be posted elsewhere. I just wanted to check if it might be a Codeception issue first.

**Comment by janeberets** [comment]
Can You help me to write "executeJs" action for accept popup using phantomJS?

**Comment by animaster** [comment]
This is how I wrote it on the scenario: When the delete button is clicked, it will display a Javascript confirm popup and User needs to click on OK to proceed with the deletion.
`...
$I->executeJS("window.confirm = function(msg){return true;};");
$I->click('.btn-delete', 'table.items tbody td.button-column');
...`

**Comment by janeberets** [comment]
Thank you! It works!

**Comment by cletsimon** [comment]
@animaster @janeberets 
I had the same issue but still can't fix using the scenario you wrote. What is the version of phantomjs and  codeception you are using?
Thank you.

**Comment by janeberets** [comment]
phantomjs 2.1.1 and codeception 2.1.4

**Comment by cletsimon** [comment]
@janeberets thank you

**Comment by edno** [comment]
Maybe a Webdriver or PhantomJS limitation. It seems working with PhantomJS 1.9.7, see #1372
