### ISSUE TITLE
codeception: grabAttributeFrom don't grab

### ISSUE THREAD

**Issue by dthuermann** [Codeception/Codeception#1375]
I have a command like: $name = $I->grabAttributeFrom('#name', 'title');

This worked fine for a while. But now at retesting it have a wrong behaviour. Any time the grabbed string is empty, even though in attribute 'title' is content. Yes, I checked the correctness of the css selector and the attribute exist. The test don't fail at this row. It fails if the (empty) string will be compared with an other ($I->see..).

Please help if someone knows the answer!

**Comment by Naktibalda** [comment]
Which module were you using? PhpBrowser, REST and WebDriver has grabAttributeFrom methods.

I tested PhpBrowser, grabAttributeFrom works correctly.
