### ISSUE TITLE
Running certain tests based on a group

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#1377]
Hi

I have a functional test that does a couple of things regarding checking text on screen and database values.

What I'm looking to be able to do, is to be able to run specific assertions based on what group is running, this is because I'm hooking up the running of tests upon git push and some of these tests take time to run, therefore I'd like to only run 'basic' tests

For example:

    $scenario->group('full');
    $scenario->group('basic');

    if (group is full) {
    // run everything
    // based on ./codecept run functional -g full
    }

    if (group is basic) {
    // run certain tests here
    // based on ./codecept run functional -g basic
    }

**Comment by DavertMik** [comment]
On second thought I don't think this is a useful idea. 
Groups by themselves are used to run tests based on a criteria. 
If test belongs to group `slow`, don't run it at all on git push
