### ISSUE TITLE
Add environment tags/labels for attaching to tests using annotation

### ISSUE THREAD

**Issue by dharkness** [Codeception/Codeception#1393]
We have two orthogonal sets of configurations which it seems would normally be handled using environments:

* browser
    * chrome
    * firefox
    * ie
* setting (determines hostname; what we actually call "application environment")
    * qa
    * staging
    * production

Currently, we must define nine Codeception environments (`chrome-qa`, `chrome-staging`, . . ., `ie-production`). In order to skip a test in production we have to apply 6 annotations:

    /**
     * @env chrome-qa
     * @env chrome-staging
     * @env firefox-qa
     * @env firefox-staging
     * @env ie-qa
     * @env ie-staging
     */

## Solution: Environment Tags

I'd love to be able to assign tags or labels to each environment and use those tags in the annotations instead of the full environment name.

    env:
        chrome-qa:
            tags: [chrome, qa]
            modules: ...
        chrome-staging:
            tags: [chrome, staging]
            modules: ...
        ...
        ie-production:
            tags: [ie, production]
            modules: ...

    /**
     * @env qa
     * @env staging
     */

Bonus would be to allow a `-` prefix to an annotation to negate it which would come in handy when adding a new setting or browser:

    /**
     * @env -production
     */

## Solution: Environment Groups

Another option which would make configuration *and* annotating tests easier would be to model environment groups as I did at the top:

    env:
        browser:
            chrome:
                modules: ...
            firefox:
                modules: ...
            ie:
                modules: ...
        setting:
            qa:
                modules: ...
            staging:
                modules: ...
            production:
                modules: ...

The command line would then need to allow combining environments from different groups:

    codecept run ... -env chrome/qa

or

    codecept run ... -env browser:chrome -env setting:qa

This would allow doing cool stuff like "run chrome tests in all settings"

    codecept run ... -env chrome:*

This would be a lot of work I expect, but I think many people work in environments such as these. How have others handled this type of multi-level configuration?

**Comment by DavertMik** [comment]
Already implemented:


> It’s also possible to merge multiple environments into one configuration by using comma as a separator:

$ php codecept run acceptance --env dev,phantom --env dev,chrome --env dev,firefox

from http://codeception.com/docs/07-AdvancedUsage#Environments
