### ISSUE TITLE
How i can run one suite in "Multiple Applications" mode?

### ISSUE THREAD

**Issue by maxgu** [Codeception/Codeception#1400]
http://codeception.com/docs/08-Customization
how i can run only, for example, frontend.unit tests?

**Comment by zmilan** [comment]
php codecept.phar run unit -g tests -c tests/frontend
- unit is name of suite
- g with its parameter is name of gruop that u wish to test on that suite
- c with path to that application codeception.yml file mean test only that one application

**Comment by DavertMik** [comment]
Thanks, @zmilan added your points to docs https://github.com/Codeception/Codeception/commit/57eb02387f6b5e008414e6d4dd593ab3d93e71db
