### ISSUE TITLE
Auth::id() returns null.

### ISSUE THREAD

**Issue by Mecit** [Codeception/Codeception#1423]
Whereas my tests pass when I use Auth::user()->id in my controller, they fail when I change it to Auth::id() because it returns null. Everything works perfectly fine when tested in browser with Auth::id(), though.

**Comment by janhenkgerritsen** [comment]
I just added a test to confirm this issue, but from my test it seems the module works as expected: 

https://github.com/Codeception/sample-l4-app/blob/master/tests/unit/AuthTest.php.

Am I missing something @Mecit?

**Comment by Mecit** [comment]
I don't know whether that was caused by something on Codeception's end or Laravel's, but, if that's working for you (I no longer have the environment to test since I took a break from PHP overall), then, whatever had been causing it seems to have been fixed. 

Thanks for your concern.

**Comment by janhenkgerritsen** [comment]
Ok clear, thanks for responding.
