### ISSUE TITLE
 Test using attachFile fails with PHPbrowser but succeeds with WebDriver, help

### ISSUE THREAD

**Issue by gunfrank** [Codeception/Codeception#1466]
The test below runs without issue and does as expected using WebDriver (with firefox), yet with PHPBrowser it has some issue with submitting the form. Using --debug I found out that the execution fails and stays on the same page of the form, when it should submit it and go to another one.

Any ideas?

$I->amOnPage();
$I->selectOption('select#type', '1');
$I->fillField('first', 'a');
$I->fillField('last', 'b');
$I->fillField('number', '333');
$I->attachFile('one', 'a.png');
$I->attachFile('two', 'b.png');
$I->attachFile('three', 'c.png');
$I->click('.btn');

for the following html - > http://pastebin.com/ZBtQTgEA

**Comment by DavertMik** [comment]
Nope (
