### ISSUE TITLE
Codeception not working with HTTPS

### ISSUE THREAD

**Issue by drodil** [Codeception/Codeception#1474]
I am trying to run acceptance tests with codeception on server that forces SSL. I am getting the following exception:

```
 [exec]   [ErrorException]                                                                   
 [exec]   file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:     
 [exec]   error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed  
```

Here is the stack trace of the problem: http://pastebin.com/dX2iJ6nP

The server has self signed certificate which causes this problem. Would it be possible to set some option to skip the certificate checks? I am using PHP version 5.6.1-1. 

More reading:
http://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-and-more
http://php.net/manual/en/migration56.openssl.php

**Comment by saiedtrife** [comment]
@DavertMik  the link you provide is not available any more , can you please re posted
