### ISSUE TITLE
Class Codeception\Configuration not found, codecept.phar

### ISSUE THREAD

**Issue by davidsoderberg** [Codeception/Codeception#1479]
Hi, I try to run tests with c3.ph. included and with --coverage on and I get "Fatal error: Class 'Codeception\Configuration' not found in" in all error reports. I run Codeception from phar file. 

How can I solve the error?

**Comment by dxhans5** [comment]
I am receiving this error, but I have codeception installed globally...there is no codecept.phar in my root directory. Can C3 only run with this file?

**Comment by Naktibalda** [comment]
c3.php requires codecept.phar or local composer installation.
