### ISSUE TITLE
Auth::user persists between requests

### ISSUE THREAD

**Issue by jshou** [Codeception/Codeception#1488]
I am having an issue where the object returned by Auth::user() persists between multiple requests in the same test, which is a problem where I'm testing updates to the model. 

I found a past resolved issue https://github.com/Codeception/Codeception/issues/1205 where the value for Auth::user() was persisted between tests, is there a way to have the value cleared between requests as well?

**Comment by jnye** [comment]
A workaround is to call Auth::setUser(null) before any step that will trigger a new request. This will not log you out but will force Laravel to reload the user from the database, etc.

**Comment by jnye** [comment]
I'm using Laravel 5 but this might work for Laravel 4 also. I created a middleware class to reload the Auth::user() if in the testing environment.

https://gist.github.com/jnye/b6da5497eb5c30de9cd4

**Comment by janhenkgerritsen** [comment]
I just merged a rewrite of the Laravel 4 module into the 2.0 branch: 132f3af48550910338fee08fedb1a078724cc2d6. I also added a test to the [sample Laravel 4 application](https://github.com/Codeception/sample-l4-app) that covers this issue: [EditProfileCept](https://github.com/Codeception/sample-l4-app/blob/master/tests/functional/EditProfileCept.php). This test fails for the Laravel 4 module in Codeception 2.13 but it succeeds with the rewrite of the Laravel 4 module I just merged into the 2.0 branch.

You can use the latest version of the 2.0 branch in your application by specifying the following version in your composer.json require statement: `"Codeception/Codeception": "2.0.*@dev"`.
