### ISSUE TITLE
Notice: Use of undefined constant C3_CODECOVERAGE_MEDIATE_STORAGE

### ISSUE THREAD

**Issue by elazar** [Codeception/Codeception#1495]
The `C3_CODECOVERAGE_MEDIATE_STORAGE` constant is potentially used on [this line](https://github.com/Codeception/c3/blob/ce8fd70e2f88198ad76f0722d176cd7dec811b00/c3.php#L36) before it's defined on [this line](https://github.com/Codeception/c3/blob/ce8fd70e2f88198ad76f0722d176cd7dec811b00/c3.php#L80), resulting in a notice if `__c3_error()` ends up being called on [this line](https://github.com/Codeception/c3/blob/ce8fd70e2f88198ad76f0722d176cd7dec811b00/c3.php#L53), [this line](https://github.com/Codeception/c3/blob/ce8fd70e2f88198ad76f0722d176cd7dec811b00/c3.php#L63), or [this line](https://github.com/Codeception/c3/blob/ce8fd70e2f88198ad76f0722d176cd7dec811b00/c3.php#L68).

**Comment by jkovacs618** [comment]
Is there an ETA on this bug being solved?  It makes the c3.php file unusable, and Acceptance testing code coverage impossible.

**Comment by DavertMik** [comment]
Fixed in https://github.com/Codeception/c3/pull/14
