### ISSUE TITLE
[PHPUnit_Framework_ExceptionWrapper] Constant DOMPDF_ENABLE_AUTOLOAD already defined

### ISSUE THREAD

**Issue by ctrlaltdylan** [Codeception/Codeception#1501]
I've had problems with the DEV constant as well. The DOMPDF is a package I need for pdf rendering. I know there's not defined constants in the Codeception library, especially for DOMPDF. I'm assuming codeception must run the setting of the DOMPDF constant twice somehow. That's what's causing every constant loading to fail.

http://puu.sh/cy7u4/30742cf95d.png

**Comment by janhenkgerritsen** [comment]
@B1nTree Is this still an issue? The link to the image in your original description does not work anymore.
