### ISSUE TITLE
Laravel4 Add $I->amOnSubdomain()

### ISSUE THREAD

**Issue by llaski** [Codeception/Codeception#1505]
This method is incredibly useful when an app has several domains so wondering if this could be added to the Laravel4 module.

**Comment by janhenkgerritsen** [comment]
@llaski Could you provide an example of how you would expect this functionality to work?

And can't you just use the `$I->amOnRoute()` method? If the subdomain is hardcoded into the route this will visit the correct URL with subdomain. If you use wildcard subdomains you can just pass the subdomain as a route parameter like so: `$I->amOnRoute('route', 'subdomain')`.

**Comment by janhenkgerritsen** [comment]
Closing issue because I am not convinced I should add this enhancement because there is a good alternative based on the current functionality of the module.

If I am missing a use case feel free to reopen the issue by commenting with an example of it.
