### ISSUE TITLE
How to make see* methods of WebDriver module case-sensitive?

### ISSUE THREAD

**Issue by neoascetic** [Codeception/Codeception#1536]

**Comment by DavertMik** [comment]
I think you can use seeElement method with Xpath for matching inner text of element.

**Comment by mirao** [comment]
I used this: `$I->assertEquals("Adminer", $I->grabTextFrom(['css' => 'div>h1>a']));`
It reads the text from CSS element and compares with expected value ("Adminer"). This allows you to perform exact match.
But I needed to enable Assert module in the acceptance suite. Is it correct approach how to use acceptance testing ?

**Comment by mirao** [comment]
As for `see()` it would be handy to have optional parameters for case sensitivity and also for exact string search (or regexp).

E.g. if you have HTML header with text "Login - Adminer", then `$I->see("Login", "h1")` matches, but IMHO its inaccurate. Only `$I->see("Login - Adminer", "h1")` should match in this case.

**Comment by Naktibalda** [comment]
If you want to be strict, you could use `$I->seeInPageSource('<h1>Login</h1>);`

**Comment by mirao** [comment]
Thanks for tip. But I rather have one command which finds element by CSS and at the same time verifies text in the element. Something like verifyText in [Selenium IDE](http://www.seleniumhq.org/docs/02_selenium_ide.jsp#commonly-used-selenium-commands).
