### ISSUE TITLE
CodeCoverage with ReflectionMethod

### ISSUE THREAD

**Issue by leventmenekse** [Codeception/Codeception#1544]
First of all because of some obvious reason, i have to use codeception 1.8. I use rest api and have custom framework that was built in house. We have 3 controllers and all of them are included in index.php (also models). Tests work with no problem but i can't cover code. I add c3.php in my index.php and enable remote. I suspect reflectionmethod that can't work with codecoverage. We call something like
```php
$function -> invokeArgs(new $class($param1, $param2, $param3, $param4);
```

When i run tests, according to codecoverage result, there is no class covered. Any help would be appreciated.

Lastly, i tried disabling remote and still no luck.

**Comment by DavertMik** [comment]
Sorry, can't help (

**Comment by leventmenekse** [comment]
It's ok. I forgot this issue :) I solved it that i wrote something like to c3.php now it works :)
