### ISSUE TITLE
Need Db driver that does not quote names in select()

### ISSUE THREAD

**Issue by draculus** [Codeception/Codeception#1548]
I am working with DB2 in Codeception. The backquote character is *not* used as quoting character in DB2.

The connection string for PDO starts with `odbc:...` which in current implementation returns the default `Db` driver (see `src/Codeception/Lib/Driver/Db.php::create()`) which in turn quotes the `select()` statement table name. That breaks the statement for DB2.

There are two possible solutions:

1. remove the quoting from `Db` driver or
2. add new `DB2` driver which has to be detected by general `odbc` connection string prefix. I am not sure if that would not affect some other `odbc` drivers that might use the same prefix.

I am afraid there is no other way how to detect DB2 usage from connection string.

Votes or better solution proposals are welcome.

**Comment by Naktibalda** [comment]
Default identifier quoting character was changed to double quote " by ddf33bc9630b944fb9ff8b1ac41527fbc9ddda01
Double quote should be fine with DB2 in most cases according to http://doc.ispirer.com/sqlways/Output/SQLWays-1-035.html (the first search result)

@draculus what is a status of your DB2 driver?

**Comment by draculus** [comment]
I have asked my colleague to send a pull request since I cannot get to that.
