### ISSUE TITLE
No namespace for Cest class

### ISSUE THREAD

**Issue by codemedic** [Codeception/Codeception#1568]
I was playing with creating Cest tests today and just found out that it seems impossible to have a namespace for these classes. Basically I noticed that only because I have a PSR-2 phpcs compliance checking on my commits. It really didnt like a class with no namespace. So are the function names/methods with `_` prefix.

Is that a user-error, if not please can you make it possible to have a namespace for Cest tests.

Thanks

**Comment by Patabugen** [comment]
Hey,

I'm having trouble adding Namespaces to my Cest files, could you post an example of how you made it work please?

**Comment by codemedic** [comment]
@Patabugen in my case, I had an issue with the autoloading setup ( composer config ). Once I resolved that, all started working.

As I understand it, you can have your Cest classes in any namespace. It is not an issue as the codeception runner finds these files by filename, not by fully qualified class name.
