### ISSUE TITLE
Detecting current Codeception Environment.

### ISSUE THREAD

**Issue by ing200086** [Codeception/Codeception#1570]
I am new to codeception. I have a case where I am trying to test a legacy site and a newly modified site with codeception. I want the same tests to be run on both (verify the expected results return from the legacy, then begin modeling the newly modified site). Codeception offers environments which is perfect for testing the two URLs, but the new site will be designed with REST and therefore will have different start or end pages ($I->amOnPage(X)).

My first idea is to have a function which given a generic name will return the correct URL based on environment ($this->pageFor('splash') returns X in legacy and Y in modified). The problem I run into is detecting which environment the current test is running. I haven't been able to find any documentation on detecting the current codeception environment.

Anyone have any ideas?

**Comment by FelikZ** [comment]
Solution from @ing200086 should exist by default.

**Comment by Naktibalda** [comment]
http://codeception.com/docs/07-AdvancedUsage#Current-values

```php
// retrieve current environment
$scenario->current('env'); 
```

**Comment by FelikZ** [comment]
@Naktibalda but this is not achievable in Cest suits, because there is no access to scenario.

**Comment by Naktibalda** [comment]
We need to build a table detailing all the differences between test formats.

**Comment by rogoit** [comment]
This is null by me ;(
