### ISSUE TITLE
InvalidArgumentException: Unreachable field "" Error

### ISSUE THREAD

**Issue by yuriymyrosh** [Codeception/Codeception#1585]
In my html form I have an <textarea name="captions[]" class="capt"> element
When I am trying to make next Functional Test:

```
$I = new FunctionalTester($scenario);
$I->fillField('textarea[name="captions[]"]', 'test');
```

I have an error
InvalidArgumentException: Unreachable field "" Error

The same issue is when I'm trying to search field by class

```
$I->fillField('.capt', 'test');
```

When i change my textarea name wirhout "[" parser find that, but it is a problem because i wont to take array in my controller

version: ~2.0
module: Laravel4

**Comment by quantum-x** [comment]
Hi @DavertMik 
I'm still getting this on Codeception PHP Testing Framework v2.1.2

```
        <form action="/clients/register" id="ClientRegisterForm" method="post" accept-charset="utf-8">
                   ...

                                    <td><div class="form-group required"><input name="data[User][0][first_name]" class="form-control" maxlength="50" type="text" id="User0FirstName" required="required"/></div></td>
                                </tr>
                    ...
        </form>
```

In the test:
```
$I->fillField('data[User][0][first_name]', $firstName);
```
or
```
$I->fillField('#User0FirstName', $firstName);
```

Both return:

```
  [InvalidArgumentException] Unreachable field "User"
Scenario Steps:

 1. $I->fillField("#User0FirstName","Roberto")
```

Seems the bug is still present.
This is NOT using Symphony.

**Comment by quantum-x** [comment]
@DavertMik This seems to be a separate issue, so I'm opening a new bug.
