### ISSUE TITLE
Add feature to remove code coverage output from console

### ISSUE THREAD

**Issue by Ragazzo** [Codeception/Codeception#1592]
Would be great to have ability to remove code coverage dump from console, option like `--coverage-console` to dump coverage to console would be useful. Will handle this one, once i have  more time

**Comment by EspadaV8** [comment]
Just wondering if any work was started on this? If not I might be able to look at it, but I have no experience with the Codeception code base.

**Comment by sergeyklay** [comment]
It seems it would be enough extend `--quiet` option. Something like this:
```sh
$ vendor/bin/codecept run --coverage-html --quiet


Time: 217 ms, Memory: 5.25Mb

HTML report generated in coverage
OK (33 tests, 144 assertions)
```

**Comment by Ragazzo** [comment]
Currently i am not working on this issue, and dont think that i will have any free time in nearest future, so feel free to handle this one

**Comment by EspadaV8** [comment]
@sergeyklay Implemented it using `--quiet` but as mentioned in the PR not sure if that's really the 'right' way or not, since ideally I'd like to see the testing progress, just not see the coverage report in the console.
