### ISSUE TITLE
Suite run order depends on a YML files creation order

### ISSUE THREAD

**Issue by TriAnMan** [Codeception/Codeception#1607]
See https://github.com/yiisoft/yii2/pull/6634#issuecomment-67984017 and https://github.com/yiisoft/yii2/pull/6634#issuecomment-67985811
Maybe the suite run order should follow a YML file names order, shouldn't it?

**Comment by DavertMik** [comment]
Currently suite order is alphabetical but you can set your order like:

```
codecept run run unit,functional,acceptance
```
