### ISSUE TITLE
HTML Report lacks information

### ISSUE THREAD

**Issue by Patabugen** [Codeception/Codeception#1613]
I feel like the HTML report could be more useful, I'd like to see it including:
1. Screenshots of failed tests
2. Test names & file names being clickable (to launch a code-editor)
3. Filters at the top to hide successful tests

I'm happy to attempt to implement these changes, any advice or other thoughts are welcome.

**Comment by DavertMik** [comment]
That would be awesome to have them implemented :+1: 
You can learn from https://github.com/Codeception/Codeception/pull/1672 how to do that

**Comment by Ardem** [comment]
+1. Screenshots are extremely helpful

**Comment by MariannaMartynova** [comment]
Screenshots of failed tests will be really useful!

**Comment by philipp82bln** [comment]
+1 for screenshots!!!

**Comment by MartinHoehne** [comment]
+1

**Comment by danielintloop** [comment]
+1 Screenshots please!

**Comment by yeclense** [comment]
+1 screenshots

**Comment by greentopsecret** [comment]
+1 screenshots

**Comment by Patabugen** [comment]
In case any of the above +1ers are not aware, screenshots are already generated - just not linked to in the HTML output.

**Comment by DavertMik** [comment]
Done in 2.2.6

**Comment by Patabugen** [comment]
Wonderful - thanks @DavertMik !

Here's a preview for anyone who's interested:

![image](https://cloud.githubusercontent.com/assets/196795/22062298/f25cfcbe-dd70-11e6-8bf4-407f9c16c663.png)
