### ISSUE TITLE
Codeception use uncorrect timezone db

### ISSUE THREAD

**Issue by Sepuka** [Codeception/Codeception#1614]
Why in my unit tests codeception use wrong timezone offset? For example my current timezone is +03:00 but code enveronment detect +04:00. If i print my php console (and apache too) timezone info, i see correct +03:00 data, but if i run codeception tests than i see +04:00. In all case, string timezone value is correct (Europe/Moscow), but different time offset.

I use yii2 framework and 2.1.0 version codeception
I wrote this question in [stackoverflow](http://stackoverflow.com/questions/27703528/why-yii2-codeception-not-use-timezonedb-extension)

**Comment by DavertMik** [comment]
I don't know why it happens (it is up to your configuration) but you can override timezone setting in global bootstrap file.
