### ISSUE TITLE
Running a specific functional test: Allowed memory size of 25165824 bytes exhausted

### ISSUE THREAD

**Issue by nsanden** [Codeception/Codeception#1615]
PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Allowed memory size of 25165824 bytes exhausted (tried to allocate 305708 bytes)

codeception.yml says 
    memory_limit: 512M

php.ini says
    memory_limit=512M

ini_get('memory_limit') confirms 512M

Here is my test: https://gist.github.com/nsanden/35ea7457bf3c4e9078b5
Here is my codecept run debug https://gist.github.com/nsanden/5ee34b54376f066b9331

Seems codeception won't allow my test to run because its using more than 25MB... Can't seem to allow it more memory.

**Comment by DavertMik** [comment]
@nsanden probably Yii resets memory limit... 
I don't have any other ideas
