### ISSUE TITLE
Is it possible to create a phpunit crap4j.xml report with codeception?

### ISSUE THREAD

**Issue by pietervogelaar** [Codeception/Codeception#1627]
Is it possible to create a phpunit crap4j.xml report with codeception?

**Comment by DavertMik** [comment]
Nope :(
Only JUnit XML

**Comment by mauriciopiber** [comment]
Please add this feature to us!
Is important at all.

**Comment by thaddeusmt** [comment]
This would be pretty slick if Codeception could generate the PHPUnit crap4j report as well as the junit and clover coverage reports. 

It seems like just passing the `--coverage-crap4j` flag to PHPUnit is all it would take? I'm not sure how the current PHPUnit reports are being generated via Codeception, but it should be similar.

https://phpunit.de/manual/current/en/textui.html
