### ISSUE TITLE
Deprecated error when loading config file because of Symfony\Yaml 2.5+

### ISSUE THREAD

**Issue by freezy-sk** [Codeception/Codeception#1628]
Because of `"symfony/yaml": "~2.4"` every `build` and `run` command shows `PHP Deprecated:  Constant ENCODING in class Symfony\Component\Yaml\Unescaper is deprecated since version 2.5 and will be removed in 3.0.`

**Comment by DavertMik** [comment]
Sorry, this commit can't be accepted as it is a very rough hook around runner.
Is there a way I can reproduce this issue on the latest changes of 2.0 branch?
I'm using Symfony 2.6
