### ISSUE TITLE
Codeception:Message

### ISSUE THREAD

**Issue by Sandipon** [Codeception/Codeception#1630]
After run test project by this command  php codecept.phar run api  LoginCest.php --steps I get the following output:

* am trying  to login.........
* I have http header "Content-Type","application/x-www-form-urlencoded"
* I send post "?",{"operation":"login","username":"xyz@abc.com","accessKey":"xyz"}
* I grab data from json response 
* see test status:Passed.

But I get only this output:

 * am trying  to login.........
 * see test status:Passed.

**Comment by Sandipon** [comment]
Here is my code:

    $I->comment(" am trying  to login.........");
    $postData = array(
        'operation' => 'login',
        'username' => $username,
        'accessKey' => $password
    );
    $url = "?";
    $I->haveHttpHeader('Content-Type', 'application/x-www-form-urlencoded');
    $I->sendPOST($url, $postData);
    $outputData = $I->grabDataFromJsonResponse();

    if ($outputData['success'] == true) {
        $I->comment("see test status:Passed.");
    } else {
        $I->comment("see test status:Failed.");
    }
get only this method output:

 $I->comment();

**Comment by Sandipon** [comment]
Here is my code:

    $I->comment(" am trying  to login.........");
    $postData = array(
        'operation' => 'login',
        'username' => $username,
        'accessKey' => $password
    );
    $url = "?";
    $I->haveHttpHeader('Content-Type', 'application/x-www-form-urlencoded');
    $I->sendPOST($url, $postData);
    $outputData = $I->grabDataFromJsonResponse();

    if ($outputData['success'] == true) {
        $I->comment("see test status:Passed.");
    } else {
        $I->comment("see test status:Failed.");
    }
get only this method output:

 $I->comment();

**Comment by freezy-sk** [comment]
If you need more verbosive output from your tests, you must increse level of verbosity from normal to verbose with `-vv`.
```--verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.```
