### ISSUE TITLE
Feature request: add option to exit silently in case of missing test

### ISSUE THREAD

**Issue by etki** [Codeception/Codeception#1631]
Hi.
I know this feature won't be used by many people, but anyway i want to open discussion for it.
I love things like autotests that run everytime class is saved. This is easily achieved by running `vendor/bin/codecept run Unit /relative/path/to/fileTests.php`. The problem is, that Codeception always exits with exit code 1 if test doesn't exist, so any file watchers will report this file as broken, and probably file doesn't need tests at all. So, basically, this is a request for option that will make Codeception return 0 on missing file, but still return 1 on failed test.

**Comment by DavertMik** [comment]
There is `--no-exit` option in console. Please should use it )

**Comment by etki** [comment]
@DavertMik yes, i know about it, it behaves opposite of what i want: returns 1 on missing test and returns 0 on test errors, so IDE would mention all missing tests but no of failed ones.
