### ISSUE TITLE
console command: PHP Catchable fatal error: Argument 1 passed to Codeception\TestCase\Cept::__construct() must be of the type array

### ISSUE THREAD

**Issue by cgeisel** [Codeception/Codeception#1632]
Running the console command throws a fatal error. The constructor signature for Cept seems to have changed, but the console command wasn't.

`./codecept console unit`

Details:

`./codecept --version
Codeception version 2.0.0`

`php -v
PHP 5.5.18 (cli) (built: Oct 16 2014 20:56:12)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans`

Error:

`... (Deprecated warnings from Symfony Yaml component removed) ...
PHP Catchable fatal error:  Argument 1 passed to Codeception\TestCase\Cept::__construct() must be of the type array, object given, called in /src/<redacted>/vendor/codeception/codeception/src/Codeception/Command/Console.php on line 66 and defined in /src/<redacted>/vendor/codeception/codeception/src/Codeception/TestCase/Cept.php on line 20
PHP Stack trace:
PHP   1. {main}() /src/<redacted>/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /src/<redacted>/vendor/codeception/codeception/codecept:27
PHP   3. Symfony\Component\Console\Application->doRun() /src/<redacted>/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /src/<redacted>/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /src/<redacted>/vendor/symfony/console/Symfony/Component/Console/Application.php:878
PHP   6. Codeception\Command\Console->execute() /src/<redacted>/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   7. Codeception\TestCase\Cept->__construct() /src/<redacted>/vendor/codeception/codeception/src/Codeception/Command/Console.php:66`

**Comment by DavertMik** [comment]
Please use latest stable Codeception
