### ISSUE TITLE
No easy way to switch between database connections

### ISSUE THREAD

**Issue by codemedic** [Codeception/Codeception#1634]
When working with multiple databases, it seems not possible to switch between database connections (DSNs).

A typical use case would be in situations where you have two databases which are differently tuned; for the kind of data they deal with. One for configuration lookup, i.e high performance, almost all coming from memory, and the other database server for huge tables, say for example logs or financial transaction history.

If one needs to write a test that would talk to multiple databases, it would be handy to be able to switch between DSNs at will during the test.

**Comment by codemedic** [comment]
Example test script would look like ... 

```
$I->amConnectedToDb('Database1');
$I->haveInDatabase(...);

$I->amConnectedToDb('Database2');
$I->haveInDatabase(...);
...
```

**Comment by codemedic** [comment]
Please can one of you experienced souls review this issue/feature request and the PR

**Comment by plista-mp** [comment]
Would be very helpful. Thanks for report @codemedic!

**Comment by sangar82** [comment]
+1! I need this feature!

**Comment by sharpless512** [comment]
+1

**Comment by codemedic** [comment]
I have kicked off an extension https://github.com/natterbox/Codeception-MultiDb
Comments and bug reports most welcome.

**Comment by gilbitron** [comment]
+1

**Comment by kpascal** [comment]
+1

**Comment by codemedic** [comment]
@gilbitron and @kpascal 
Guys, please can you have a look at the package `natterbox/codeception-multidb` on packagist.
More details at https://github.com/natterbox/Codeception-MultiDb

**Comment by olleharstedt** [comment]
:+1:

**Comment by rogoit** [comment]
+1

**Comment by tomotomo** [comment]
Nice Idea

**Comment by raistlin** [comment]
I haven't done a deep review on @codemedic code, but seems ok.
Could you create a PR on this repository to add a brief info of your extension, a simple text line on the readme or other more appropriate file is more than enough.

**Comment by rogoit** [comment]
I use sqlite connection and switch with _reconfigure on a helper...so i can also read db settings from .env file

**Comment by kpascal** [comment]
its great that we all use this and this but how about a working copy example so others can be successful with "this and this" configurations

**Comment by rogoit** [comment]
We do not have all the same settings because everybody has a special usecase

**Comment by codemedic** [comment]
@raistlin Please can you point me in the right direction.
Where do I add that? Please can you let me know the location within the repo.

Ta

**Comment by goffyara** [comment]
+

**Comment by raistlin** [comment]
You should create a PR against Codeception web https://github.com/Codeception/codeception.github.com
I think the best place to add the information is on the "Extensions" section.

**Comment by Naktibalda** [comment]
Db module has this functionality since 2.5.0

https://codeception.com/docs/modules/Db#Example-with-multi-databases
https://codeception.com/docs/modules/Db#amConnectedToDatabase
https://codeception.com/docs/modules/Db#performInDatabase
