### ISSUE TITLE
REST module throws execeptions after using "canSeeResponseContainsJson"

### ISSUE THREAD

**Issue by russellsimpkins** [Codeception/Codeception#1647]
I created a simple test to call a URL and then test if I can:
```php
$I->canSeeResponseContainsJSON(array('status'=>'OK'));
```
When I test for that, and the response contains the array('status'=>'OK') everything is OK

BUT, if I change the code to be:
```php
$I->canSeeResponseContainsJSON(array('status'=>'OK2'));
//OR
$I->canSeeResponseContainsJSON(array('status1'=>'OK'));
```
REST.php throws an exception the next time I try to issue a $I->sendGET
```bash
PHP Fatal error:  Call to a member function request() on a non-object in vendor/codeception/codeception/src/Codeception/Module/REST.php on line 380
```
Here is my test
```
    $params['url'] = 'http://localhost.com/2010/06/01/travel/escapes/dan_is_testing.html';
    $I->sendPOST("http://$host/svc/bitly/shorten", $params);
    $I->canSeeResponseIsJson();
    $I->canSeeResponseContainsJSON(array('status'=>'OK2'));
    unset($params);
    $params['url'] = 'http://localhost.com/2010/06/01/travel/escapes/dan_is_testing.html';
    $params['start_date'] = '2010-06-02';
    $params['end_date'] = '2010-06-02';
    $I->sendGET("http://$host/svc/bitly/urlstats", $params); // **THOWS ERROR HERE**
    $I->seeResponseIsJson();
    $I->seeResponseContainsJSON(array('status'=>'OK'));
```
I'm using codeception 2.0.9
> php -v
PHP 5.5.13 (cli) (built: Sep  8 2014 14:41:26) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
> composer -V
Composer version 1.0-dev (c58b7d917c65692eeb00c22b2fbaaa251cb390dc) 2015-01-05 16:31:16

**Comment by schmunk42** [comment]
I have the same problem, also with the REST client. Codeception 2.0.11
