### ISSUE TITLE
run --no-colors throws PHPUnit_Framework_Exception

### ISSUE THREAD

**Issue by ThePeach** [Codeception/Codeception#1652]
Tried to add the `--no-colors` to the command line (specifically for a jenkins build) and got the following error:

```
$ ../vendor/bin/codecept run --no-colors
Codeception PHP Testing Framework v2.0.9
Powered by PHPUnit 4.6-dev by Sebastian Bergmann and contributors.

  [PHPUnit_Framework_Exception]
  Argument #3 (No Value) of PHPUnit_TextUI_ResultPrinter::__construct() must be a value from "never"  
  , "auto" or "always"
```

without that flag everything runs fine.

**Comment by DavertMik** [comment]
Looks like you are using @dev version of PHPUnit. Codeception relies on 4.4.* as a dependency
Please downgrade PHPUnit to 4.4.*
Once 4.6 goes stable we will move into it

**Comment by ThePeach** [comment]
thanks @DavertMik 
my project has minimum stability `@dev` and I'm going to blame on Composer here: even if I specify `"codeception/codeception": "@stable"`it will pull in PHPUnit from `dev-master`.
I've now specified `"phpunit/phpunit": "~4.4.0@stable"` as well.
As you said, I don't get any error message any more.
