### ISSUE TITLE
Setting $_SERVER['HTTP_X_CODECEPTION_CODECOVERAGE']

### ISSUE THREAD

**Issue by parhamdoustdar** [Codeception/Codeception#1653]
Hi,

I'm trying to test a Phalcon application. The code coverage doesn't work unless I explicitly set `$_SERVER['HTTP_X_CODECEPTION_CODECOVERAGE']` to 1 at the very beginning of c3.php.

My question is, why isn't mine set? What sets this variable so I can investigate?

**Comment by samdark** [comment]
Try updating from Composer. It was fixed quite some time ago but we forgot to make c3 release. Was rolled out today thanks to @Ragazzo reminder.
