### ISSUE TITLE
Why not codeception/verify in phar file?

### ISSUE THREAD

**Issue by netyum** [Codeception/Codeception#1658]
rt

**Comment by Ragazzo** [comment]
it is a separated repo , that is made so `codeception.phar` will be light since it is already includes a lot of files from others repos

**Comment by netyum** [comment]
Well, I build. Thanks.

**Comment by DavertMik** [comment]
@netyum actual reason is that verify introduces global functions. In order to avoid possible conflicts we didn't include that into phar.
