### ISSUE TITLE
Getting shebang line in responses while using c3

### ISSUE THREAD

**Issue by etki** [Codeception/Codeception#1673]
Hi.
I'm getting weird error - as soon as coverage is enabled and c3 is imported in my index.php, i start receiving simple shebang line(`#!/usr/bin/env php`) as a response. I also see shebang line on any Codeception command ran (with or without coverage enabled), for example `codecept build` will result in shebang output, while Symfony's built-in `codecept list` won't.
I've tried to backtrace it, but got stuck in commands.

Used versions: Codeception - 2.1.x-dev, c3 - 2.0.3 (dev-master couldn't install itself).

**Comment by Naktibalda** [comment]
@etki are you still experiencing this issue?

**Comment by etki** [comment]
@Naktibalda i'm terribly sorry, i'm switched language a while ago
