### ISSUE TITLE
Interactive fails without --colors flag

### ISSUE THREAD

**Issue by FnTm** [Codeception/Codeception#1674]
If I launch interactive console without `--colors` flag, this is the output:
```
  [PHPUnit_Framework_Exception]                                                                    
  Argument #3 (No Value) of PHPUnit_TextUI_ResultPrinter::__construct() must be a value from "nev  
  er", "auto" or "always"  
```

Codeception version: 2.1.0

**Comment by DavertMik** [comment]
I think because you use unstable `dev` version of Codeception. 
Please switch to latest stable which is 2.0.10 (not 2.1.0) or to 2.0 branch.
