### ISSUE TITLE
How to extend variable output?

### ISSUE THREAD

**Issue by jaspernbrouwer** [Codeception/Codeception#1677]
Is there a way to hook into the process that serializes/formats a variable for the output?

Let's say I have a User object, and when a login test fails, I see the output:
```txt
Failed to log in as "User"
```

I would very much like to have output like this:
```txt
Failed to log in as "User(123)"
```

Of course this is an over-simplified example, but I have lots of test that work with objects and cannot clearly determine _which_ object a failure relates to (only its classname).

Is this possible?
If so, how do I go about it?

**Comment by DavertMik** [comment]
Please provide more details. Is that functional, acceptance, or unit test?

Right now I can suggest you to use `codecept_debug` method to print any debug output to screen.

**Comment by jaspernbrouwer** [comment]
In this case it's functional tests, but the same goes for acceptance tests.

An example Cept (in this case) would be:
```php
$I = new FunctionalTester($scenario);

$user = // provides a User object

$I->wantTo('be logged in');
$I->amAuthenticatedAs($user);
$I->amOnPage('/dashboard');
$I->see($user->getName());
```

When it fails, I see output like this:

```txt
1) Failed to be logged in in AuthenticateCept (/path/to/tests/functional/AuthenticateCept.php)
Can't be on page "/dashboard":

...

Scenario Steps:
2. I am on page "/dashboard"
1. I am authenticated as "User"
```

My issue is about those Scenario Steps. I presume the text between quotes (`"/dashboard"` in step 2, `"User"` in step 1) are produced by some sort of variable dumper.

I'd like to hook into that variable dumper to add some extra info when certain objects are dumped. So in stead of just `"User"`, I'd like to add the id of that User object:

```txt
1. I am authenticated as "User(123)"
```

I hope this makes my question clear!

**Comment by DavertMik** [comment]
You can implement `__toString` of your class to hook into output. 

See: https://github.com/Codeception/Codeception/blob/2.0/src%2FCodeception%2FStep.php#L55
