### ISSUE TITLE
Customize testing reports

### ISSUE THREAD

**Issue by zmilan** [Codeception/Codeception#1678]
Is there any way to customize testing reports in current version of codeception (2.0.9), or there is only plan for that for version 2.1 (as I saw in open issues)? 
I will need some way to add more information to existing testing reports or to create totally new template based on our need. For example we have a lot of different checkout scenarios in our application and we separate them in few codeception groups. Each of that group is represented with one test file and in each of that file we dynamically create all possible checkout scenarios for that group. It can be 32 scenarios per group or even few hundred. What we wish is to be able to log our scenario details, than order id what we get with success checkout and similar. It not need to be in existing xml format for JUnit, we can have our own xml format and we will make our own parser for it.

**Comment by DavertMik** [comment]
I think this is something [Extensions](http://codeception.com/docs/08-Customization#Extension-classes) are all about. You can implement your hooks and collect all the information about tests than use it as you need. 

To get a group of test it belongs to, you can use:

```
$test->getScenario->getGroups();
``` 

Also please check out [Group classes](http://codeception.com/docs/08-Customization#Group-Classes). Maybe that's what will fit you best.
