### ISSUE TITLE
Merge multiple coverage reports

### ISSUE THREAD

**Issue by raistlin** [Codeception/Codeception#1679]
I did not find how to do, and even I don't know if its possible at all, but I will need to merge some coverage reports.

My scenario is that I run in different nodes each test suite (codecept run unit, codecept run functional,  codecept run rest, ...) to speed up testing. My problem is that I can't merge coverages from all nodes in a single coverage.html report file, I have no problems with tests results, as they are all in xml format, so they are pretty easy to merge.

So question is: Is there a way to build coverage.html from many coverage.xml files?

**Comment by DavertMik** [comment]
There is utility [phpcov](https://github.com/sebastianbergmann/phpcov) for that purposes

**Comment by delatbabel** [comment]
phpcov requires coverage reports that are generated in PHP_CodeCoverage *.cov files.  Running codeception with the --coverage-php option reports:

    [RuntimeException]
    The "--coverage-php" option does not exist.
