### ISSUE TITLE
Grabbing page source

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#1685]
Hi

Is there a way to grab the HTML page source at any given time?

I have a fancybox popup that will display various radio buttons depending on others that are checked.

As it is in the fancybox, making a screenshot only displays the current view in the popup. The radio buttons are further down and thus hidden.

What I want to do is grab the page source to check which radios are present. 

The reason for this is, even when I use `seeElementInDom('#radio_element')` when i then call `checkOption('#radio_element')` always fails

**Comment by DavertMik** [comment]
Maybe you could use `waitForElement` thigs?

**Comment by craigwillis85** [comment]
I have tried that.

There is, in the webdriver 'getPageSource()' (which is what grabTextFrom() uses)

It would still be nice if there was a `grabPageSource()` method though in Codeception

**Comment by Naktibalda** [comment]
It is easy to make your own helper method:

```php
public function grabPageSource()
{
    return $this->getModule('WebDriver')->webDriver->getPageSource();
}
```
