### ISSUE TITLE
Method 'grabCookie' does not return the cookie with given name

### ISSUE THREAD

**Issue by xapon** [Codeception/Codeception#1687]
After 2.0.10 release, AcceptanceTester::grabCookie always returns the first available cookie, regardless the name provided to this method.

**Comment by DavertMik** [comment]
Ups. You are right.

**Comment by DavertMik** [comment]
FIxed in this commit
https://github.com/Codeception/Codeception/commit/da7d9912fbddb7254bdcc8c3fe3dc73dd3d1f920

I think I will need to repack the release.

**Comment by DavertMik** [comment]
Please update. I published new phar and new 2.0.10.1 tag. 
Internal version not changed.
