### ISSUE TITLE
can't get haveHttpHeader() send Authorization header

### ISSUE THREAD

**Issue by ThePeach** [Codeception/Codeception#1688]
This seems quite odd, I'm trying to authenticate using Http Basic Auth on my REST interface build with Yii2 but I keep receiving an "invalid credentials" error.
Replicating the test in Postman seems to be working without issues, so I'll exclude a problem on Yii side.

I have the following test:
```php
$I->amGoingTo('authenticate to search for my own user');
$I->haveHttpHeader(
    'Authorization',
    'Basic ' . base64_encode($user['username'] . ':' . $userPassword)
);
$I->sendGET('users/search/'.$user['username']);
$I->seeResponseCodeIs(200);
```

by running it I get:

```
../vendor/bin/codecept run functional UserAPICept.php --debug
Codeception PHP Testing Framework v2.0.10
Powered by PHPUnit 4.4.5 by Sebastian Bergmann.

Functional Tests (1) -----------------------------------------------------------------------------------------------
Modules: Filesystem, Yii2, REST, FixtureHelper
--------------------------------------------------------------------------------------------------------------------
Test the user REST API (UserAPICept) 
Scenario:
* I get fixture "user"
* I am going to authenticate to search for my own user
* I have http header "Authorization","Basic dXNlcjpzb21ldGhpbmc="
* I send get "users/search/user"

  [Request] GET http://basic-dev.yii2.sandbox/v1/users/search/user
 ERROR 

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
--------------------------------------------------------------------------------------------------------------------


Time: 6.06 seconds, Memory: 16.25Mb

There was 1 error:

---------
1) Failed to test the user rest api in UserAPICept (/mnt/workspace/yii2-book/tests/codeception/functional/UserAPICept.php)
Couldn't send get "users/search/user":
yii\web\UnauthorizedHttpException: You are requesting with an invalid credential.

Scenario Steps:
4. I send get "users/search/user"
3. I have http header "Authorization","Basic dXNlcjpzb21ldGhpbmc="
2. I am going to authenticate to search for my own user
1. I get fixture "user"

                                                                                      
  [yii\web\UnauthorizedHttpException] You are requesting with an invalid credential.  
                                                                                      
#1  /mnt/workspace/yii2-book/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:56
#2  /mnt/workspace/yii2-book/vendor/yiisoft/yii2/base/ActionFilter.php:71
#3  yii\base\ActionFilter->beforeFilter
#4  /mnt/workspace/yii2-book/vendor/yiisoft/yii2/base/Component.php:538
#5  /mnt/workspace/yii2-book/vendor/yiisoft/yii2/base/Controller.php:259
#6  /mnt/workspace/yii2-book/vendor/yiisoft/yii2/web/Controller.php:108
#7  /mnt/workspace/yii2-book/vendor/yiisoft/yii2/base/Controller.php:149
#8  /mnt/workspace/yii2-book/vendor/yiisoft/yii2/base/Module.php:455
#9  /mnt/workspace/yii2-book/vendor/yiisoft/yii2/web/Application.php:83
#10 /mnt/workspace/yii2-book/vendor/symfony/browser-kit/Symfony/Component/BrowserKit/Client.php:327
                                   
FAILURES!                          
Tests: 1, Assertions: 0, Errors: 1.
```

I'm currently using CodeCeption 2.0.10 (updated just moments ago).

**Comment by Ragazzo** [comment]
can you dump data that is in place where exception is thrown , i mean in filter ?

**Comment by ThePeach** [comment]
Hi @Ragazzo I've done the dump of the request and the content is the following:

```
class yii\web\Request#432 (28) {
  public $enableCsrfValidation =>  bool(false)
  public $csrfParam =>  string(5) "_csrf"
  public $csrfCookie =>  array(1) {
    'httpOnly' =>    bool(true)
  }
  public $enableCsrfCookie =>  bool(true)
  public $enableCookieValidation =>  bool(true)
  public $cookieValidationKey =>  string(32) "zryNPMoxHjU7WTTT8iLCttLvtT9Fqtdi"
  public $methodParam =>  string(7) "_method"
  public $parsers =>  array(0) {
  }
  private $_cookies =>  NULL
  private $_headers =>  NULL
  private $_rawBody =>  NULL
  private $_bodyParams =>  NULL
  private $_queryParams =>  NULL
  private $_hostInfo =>  NULL
  private $_baseUrl =>  string(0) ""
  private $_scriptUrl =>  string(15) "/index-test.php"
  private $_scriptFile =>  NULL
  private $_pathInfo =>  string(20) "v1/users/search/user"
  private $_url =>  string(21) "/v1/users/search/user"
  private $_port =>  NULL
  private $_securePort =>  NULL
  private $_contentTypes =>  array(0) {
  }
  private $_languages =>  NULL
  private $_csrfToken =>  NULL
  private $_isConsoleRequest =>  NULL
  private $_events =>  array(0) {
  }
  private $_behaviors =>  NULL
  private $_scriptFile =>  NULL
}
```

**Comment by ThePeach** [comment]
hi @Ragazzo and @DavertMik, I don't want to put any pressure on you guys, but it would be great to have an idea on when someone could have a look at this, either to identify it as a bug or if it's a problem on my end. I'm currently holding up a chapter of the book I'm writing on Yii and CodeCeption due to this.
Thanks!

**Comment by RogerRussel** [comment]
Same problem hear, haveHttpHeader doens't work.

$Tokken = new ApiTester($scenario);
$Tokken->wantTo('Ask a tokken');
$Tokken->haveHttpHeader('app_tokken', $app_tokken);
$Tokken->sendGET("/account/{$usr_id_on_app}/tokken");
$Tokken->seeResponseCodeIs(200);
$Tokken->seeResponseIsJson();
$Tokken->seeResponseContainsJson(['Tokken']);

**Comment by nodgesoft** [comment]
I have the same issue, RogerRussel's code is very similar to mine. 
--debug shows

[Request headers] {"app_tokken":"4j98f349fj4"}

However the server never gets it.

**Comment by RogerRussel** [comment]
@nodgesoft, 

The header fields should be written with first capital letter and the words separated by "-".

Codeception is normalizing "app_tokken" to "App-Tokken" and then sending it to the server as "App-Tokken" insted "app_tokken".

Because the application which I was make tests was made long time, my boss don't allow correct the name because as too much clients using it, perheps to make my test work I changed my code to look at first for "app_tokken" and if it was not found, then look for "App-Tokken".

It will be great if Codeception allow set it we wanna normalize or not Headers vars.

Sorry for my english.

**Comment by nodgesoft** [comment]
@RogerRussel Thanks, that at least let me work around the issue.

**Comment by Naktibalda** [comment]
Have you tried to use `amHttpAuthenticated` method? it sets `PHP_AUTH_USER` and `PHP_AUTH_PW` properties in $_SERVER in functional tests (including Yii).
https://github.com/Codeception/Codeception/blob/6f30eeb1032cff54ffcf99a87b01d8d6c839450b/src/Codeception/Module/REST.php#L245

**Comment by RogerRussel** [comment]
@Naktibalda thanks for you replay, but unfortunately amHttpAuthenticated is used to authenticate into HTTP Login, therefore, it sets PHP_AUTH_USER and PHP_AUTH_PW, but it does not have much to do with HEADERs.

Anyway if it is a new system, it should by writen with the RFC to headers, Apache server allow be non-standard, but Nginx require it was writen by RFC, otherwise, it will not be accept too.

**Comment by Naktibalda** [comment]
What do you mean by "RFC"?

I though that you are using Yii2 module, if you are using PhpBrowser, amHttpAuthenticated sets a header.

**Comment by RogerRussel** [comment]
@Naktibalda, I'm really sorry, I see now the problem, I understand wrong the title and write my problem here too, but the true is it not should be here. LoL, Thanks, I will look for a Issue more apropriated, or create a new one. Any way my mistake help @nodgesoft, which is good too.

**Comment by Naktibalda** [comment]
Your issue: https://github.com/Codeception/Codeception/issues/1801
