### ISSUE TITLE
Cest dependencies fail because test result uses wrong class name

### ISSUE THREAD

**Issue by ghost** [Codeception/Codeception#1691]
Looking at TestResult https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestResult.php#L348

The class name is added to tests passed, but this prevents referencing tests in this format:
 * @depends Admin\Bundle\Tests\APageLoaderCest::tryStudentRegister
because the actual class being checked is \Codeception\TestCase\Cest::

The best solution I could find is the search for the correct test based on test name, and ignore the class name except to tell codeception that it isn't in the same class that is currently running.

I retract my previous statement.  Something else is causing me to not be able to run my tests.  Following the stack a little closer I see it is replacing the correct names.

Looks like it is replacing the passed tests with the name of the current testing class instead of the class that the test was executed in.

**Comment by Naktibalda** [comment]
I can't understand what your issue was.

**Comment by bjcullinan** [comment]
Dang, this was a while ago. I believe it has something to do with loading
multiple cest classes and something to do with naming those classes wasn't
showing up when it went to fullfill dependencies for a test. It was trying
to find the function to run but it was attaching the wrong class to the
function and therefore not finding it and failing the test. I will have to
look at the history I mad have just modified the library at the time and
not updated.

**Comment by bjcullinan** [comment]
Ok, now I remember.  Something was causing TestResult to prepend the class that the test was start in, instead of the class containing the dependency that was called.  So if you chain dependencies together the second might fail if it is in a different Cest class than the original test.  But it could also be because I wrote a helper test that calls another test.  Looks like these lines have changed and I didn't attach a specific revision to the link.

**Comment by Naktibalda** [comment]
Could you reproduce the issue and attach the files to this ticket?

**Comment by ashnazg** [comment]
If @bjcullinan was trying to depend _across classes_, then I bet the issue was the same as what I'm seeing on #2696 ...

**Comment by Naktibalda** [comment]
Implemented in 2.2  https://github.com/Codeception/Codeception/pull/2711#issuecomment-173057161
