### ISSUE TITLE
codeception get_browser

### ISSUE THREAD

**Issue by BadreddineFodha** [Codeception/Codeception#1694]
i try to make difference between browser and i use get_browser (php function) and it working in localhost but when i test codeception i get this error:

Failed to login form in DashboardCept (/Users/badreddinefodha/Documents/web/goldfinger-acceptance-tests/tests/goldfinger-client/DashboardCept.php)
Couldn't click "#FormUserLogin input[type='submit']":
PHPUnit_Framework_Exception: get_browser(): browscap ini directive not set

please any help????

**Comment by samdark** [comment]
Codeception runs in console so most probably you have separate `php.ini` for it which is missing directive mentioned in error message.

**Comment by BadreddineFodha** [comment]
you have idea how can i do that? or another solution to get browser name

**Comment by samdark** [comment]
No.

**Comment by BadreddineFodha** [comment]
thankx
