### ISSUE TITLE
Move codeception.yml to tests/ dir

### ISSUE THREAD

**Issue by o5** [Codeception/Codeception#1696]
Hi, 

I would like to move the main config file <code>codeception.yml</code> into <code>tests/</code> folder. I've changed <code>paths.*</code> in main config file. 

So, if I want to run all tests 
```
php vendor/bin/codecept run --debug --config="tests/codeception.yml"
``` 
it's ok, but if I want to run only one tests 
```
php vendor/bin/codecept run --debug --config="tests/codeception.yml" tests/acceptance.suite.yml tests/acceptance/SignInCept.php
```
it doesn't work, ends with <code>Suite acceptance.suite.yml was not loaded</code>.

Where I do a mistake?
Thanks

**Comment by DavertMik** [comment]
> it's ok, but if I want to run only one tests php vendor/bin/codecept run --debug --config="tests/codeception.yml" tests/acceptance.suite.yml tests/acceptance/SignInCept.php, it doesn't work, ends with Suite acceptance.suite.yml was not loaded.

yeah, there is no such syntax as 

```
php vendor/bin/codecept run ... tests/acceptance.suite.yml
```

You should provide suite name, and not suite config. You can skip this argument. 
Also I'm not sure but probably you should use `acceptance/SignInCept.php` instead of `tests/acceptance/SignInCept.php`. As I said I'm not sure in this point )

**Comment by zbateson** [comment]
Yeah - basically would be enough to say 'acceptance' instead of tests/acceptance.suite.yml.  @DavertMik tests/acceptance/SignInCept.php would now work with the changes we made so 'tabbing' in a terminal would work.

@o5 actually because you're pointing to the cept you want to run you shouldn't have to mention which suite you want to run either.  You should be able to just say ``` php vendor/bin/codecept run --debug --config="tests/codeception.yml" tests/acceptance/SignInCept.php ```.

**Comment by o5** [comment]
@zbateson it doesn't work, the error is same as I posted in first topic.
```
php vendor/bin/codecept run --debug --config="tests/codeception.yml" tests/acceptance/SignInCept.php
Codeception PHP Testing Framework v2.0.10
Powered by PHPUnit 4.4.5 by Sebastian Bergmann.

[RuntimeException]
Suite 'tests/acceptance/SignInCept.php' could not be found
```

**Comment by zbateson** [comment]
Hmm, interesting.  It seems specifying the config file to be somewhere else messes that up a bit.  With the config file specified to be under the tests dir I was able to run with what would be the equivalent of ```php vendor/bin/codecept run --debug --config="tests/codeception.yml" acceptance tests/acceptance/SignInCept.php``` and ```php vendor/bin/codecept run --debug --config="tests/codeception.yml" acceptance SignInCept.php``` but it didn't work if I said 'acceptance acceptance/SignInCept.php'.

Anyway, if you continue to play with it for a bit it should work for you as well.  May be an easy fix to get it working more dynamically.
