### ISSUE TITLE
GrabFromDatabase - no data

### ISSUE THREAD

**Issue by mnabialek** [Codeception/Codeception#1698]
I have the following piece of code:

```
$a1 = array_merge($this->getAddressExpectedData(0), ['person_id' => $id]);
$I->seeRecord('address',$a1);
$address1Id = $I->grabFromDatabase('address', 'address_id', $a1);
var_dump($address1Id);
die();
```

As you see it's very simple. `seeRecord` test passes, but when I try to get id of record using exact same data to get from database in the next line I get `false` as `$address1Id`

**Comment by mnabialek** [comment]
I forgot to mention I use it for Laravel. It seems that `grabRecord` it works fine but `grabFromDatabase` doesn't

**Comment by CristianGiordano** [comment]
It looks like you are using the laravel4 module? Try the config `cleanup: false`. It uses transactions and i've had a problem with this which I am looking into resolving.

**Comment by janhenkgerritsen** [comment]
@CristianGiordano is right, the Laravel modules use transactions if cleanup is enabled, so the Db module cannot see the database changes of the application. You can use the `grabRecord` method of the Laravel modules or disable cleanup if you want to keep using the Db module.
