### ISSUE TITLE
fillField not working for IE11 but working for chrome, firefox, safari 

### ISSUE THREAD

**Issue by badjina** [Codeception/Codeception#1699]
this my code :

        $I->wantTo('Login form');
        $I->amOnPage('/user/login');

        $I->fillField("#FormUserLogin input[name='email']", $username);
        $I->fillField("#FormUserLogin input[name='password']", $password);
        
        $I->checkOption("#FormUserLogin input[name='remember_login']");
        $I->seeLink('Forgot password?','/user/passwordResetRequest');
        
        $I->click("#FormUserLogin input[type='submit']");

and i try it xpath and css selector

anyone have idea?

**Comment by Naktibalda** [comment]
It is browser-specific, so it isn't an issue of Codeception.
It is an issue of Selenium, maybe this one: https://github.com/SeleniumHQ/selenium/issues/1931
