### ISSUE TITLE
yii2 clear events in _before

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#1703]
Hi ragazzo & samdark,

Isnt it a good idea to reset all the events before each test run? Otherwise, events will sum up during functional testing causng a lot of issues during a long run. 

Ive fixed this in my own central before function, but in my opnion this should be part of the core.

Thanks

**Comment by Ragazzo** [comment]
what events you are talking in particular ?

**Comment by dynasource** [comment]
Static events property in yii\base\Event

**Comment by Ragazzo** [comment]
Ok , fine by me , however i am not sure if it should be left to the developer , @samdark what is your thoughts on this one ?

**Comment by samdark** [comment]
Yes, it should be reset.

**Comment by dynasource** [comment]
script to do it:

```php
        $reflectedClass = new \ReflectionClass('\yii\base\Event');
        $reflectedProperty = $reflectedClass->getProperty('_events');
        $reflectedProperty->setAccessible(true);
        $reflectedProperty->setValue([]);  
```        

Related subject:
https://github.com/yiisoft/yii2/pull/6981

**Comment by Ragazzo** [comment]
should be done as `Event::clearAll()`

**Comment by dynasource** [comment]
yes, that would be even better

**Comment by samdark** [comment]
Anyone have time to prepare a pull request?

**Comment by Ragazzo** [comment]
@samdark it is now `Yii 2` issue

**Comment by samdark** [comment]
Well, closing it here then.
