### ISSUE TITLE
sendAjaxRequest is not using the url specified in the PhpBrowser module config.

### ISSUE THREAD

**Issue by glumb** [Codeception/Codeception#1705]
I'm using `$I->sendPOST($entityUrl)` from the REST module, which results in a request to  `[Request] GET /entity`. `$I->sendAjaxRequest('DELETE', $entityUrl)` results in a request to `[Request] DELETE http://127.0.0.1:8888/entity`. But this is not correct, since the webroot is in a subfolder, specified in the PhpBrowser config.

I'm not sure what is causing this.

**Comment by Naktibalda** [comment]
It appears that this issue is fixed already. sentAjaxRequest appends url to baseUrl unless protocol or port is specified.
