### ISSUE TITLE
Laravel5 Module - Could not be found

### ISSUE THREAD

**Issue by Everon** [Codeception/Codeception#1708]
Hi all,

The newly released Laravel5 module fails to load when included as a module in the test suite YAML configuration files. I'm currently on the 2.1.*@dev bleeding edge where the module is shown as available in the Codeception vendor folder.

Am I missing some thing?

Sample config file:    
    
    # Codeception Test Suite Configuration
    
    # suite for unit (internal) tests.
    class_name: UnitTester
    modules:
        enabled: [Asserts, UnitHelper, Laravel5]

**Comment by DavertMik** [comment]
Use 2.0 branch, not dev-master.
However I will merge 2.0 to master now

**Comment by DavertMik** [comment]
done. Laravel5 module is available in `dev-master` now

**Comment by DavertMik** [comment]
But I don't recommend using dev-master now. There are planned BC changes, so things may go unstable in next weeks

**Comment by Everon** [comment]
Understood, keep up the great work.

**Comment by mabasic** [comment]
Hi, I am using `codeception/codeception": "~2.0`. But Laravel5 is missing. Is there a way to include it in the next release?
