### ISSUE TITLE
@before and @after annotations break _before and _after hooks 

### ISSUE THREAD

**Issue by EVODelavega** [Codeception/Codeception#1709]
Given the fact that `@dataProvider` test methods can't be used with the `@depends` annotation, I'm currently using a property (array) to which I add all of the data I want to use in the next test. I'm using the `_before` and `_after` hooks to mock some stuff, only to find that I have to call it manually in the second test case (the one with the `@after` annotation).

An example to replicate this behavior/issue:

```php
<?php
use Codeception\TestCase\Test;

class SimpleTest extends Test
{
    /**
     * @var array
     */
    protected $tempArr = array();

    /**
     * @var \DateTime
     */
    protected $mocked = null;

    protected function _before()
    {
        $this->mocked = new DateTime();
    }

    /**
     * @param string $string
     * @dataProvider fooProvider
     */
    public function testFoo($string)
    {
        if ($string{0} === strtolower($string{0})) {
            $this->tempArr[] = $string;
        }
        $this->assertInstanceOf('\DateTime', $this->mocked);
    }

    /**
     * @after testFoo
     */
    public function testBar()
    {
        foreach ($this->tempArr as $string) {
            $this->assertFalse(
                $string === strtoupper($string)
            );
        }
        $this->assertInstanceOf('\DateTime', $this->mocked);//<== FAILS
    }

    /**
     * @return array
     */
    public function fooProvider()
    {
        return array(
            array(
                'string'
            ),
            array(
                'String'
            )
        );
    }

    protected function _after()
    {
        $this->mocked = null;
    }
}
```

This test will fail, the `instanceOf` assertion seems to be to blame:

```
Test foo with data set #0 (SimpleTest::testFoo)                                                                                 Fail
Test foo with data set #1 (SimpleTest::testFoo)                                                                                 Fail
Test bar (SimpleTest::testBar)                                                                                                  Fail
--------------------------------------------------------------------------------------------------------------------------------------


There were 3 failures:

---------
1) SimpleTest::testFoo with data set #0
Failed asserting that null is an instance of class "\DateTime".

#1 SimpleTest.php:43

---------
2) SimpleTest::testFoo with data set #1
Failed asserting that null is an instance of class "\DateTime".

#1  SimpleTest.php:43

---------
3) SimpleTest::testBar
Failed asserting that null is an instance of class "\DateTime".

#1  SimpleTest.php:43
```

However, remove the `@after` annotation, and all works just fine. Is this to be expected? Is this a known issue, or am I just doing something wrong here?

**Comment by DavertMik** [comment]
@EVODelavega it needs a deeper investigation from my side. However, I can tell that this is probably a conflict of Codeception and PHPUnti apis. `@after` was introduced in Codeception before PHPUnit 4.0 released, they implemented this annotation in their own way. `@dataProvider` is also part of PHPUnit. So, yeah, please try to avoid using `@after` in your case. I hope this will be fixed soon.

**Comment by EVODelavega** [comment]
I've been looking into the issue more closely. There are in fact several things contributing to thisproblem: 

- the `@dataProvider` annotation is implemented by PHPUnit in a way that makes it really quite difficult to intercept return values/control the order. That's not something that is very likely to change any time soon
- The `@after` annotation skips the `Events::TEST_BEFORE` event (should be a doable fix)
- Tests with an `@after` annotation that refers to an `@dataProvider` seem to get invoked both as `@after` methods, and regular test cases (if their name starts with `test`, obviously). 

Though there already are a ton of annotations, one could argue that there might be room for one more. Something along the lines of `@returnsTo dependentTestMethod` or something...
Again, I might be getting too drowsy here, but I'll go ahead and clone this repo to hopefully contribute something useful

**Comment by DavertMik** [comment]
That would be great if you will make all those annotations playing together. Waiting for your PR!
