### ISSUE TITLE
Local acceptance tests show 0% coverage

### ISSUE THREAD

**Issue by stephencroberts** [Codeception/Codeception#1719]
Hi, I'm working with codeception to test a Joomla! extension I'm developing. I've written a simple acceptance test (which was incredibly easy to do) and am running it locally with phpbrowser, and I've confirmed it's working as expected. However, I'm having issues where the code coverage report is showing that no code is being touched by the acceptance test. 

In codeception.yml I have this:

```
coverage:
    enabled: true
    include:
        - testapp/index.php
```

I'm including index.php in the coverage because it should always be executed for every request. I've included c3.php in index.php and I know it's being loaded. When I run `codecept run acceptance --coverage-html`, the report gets generated, but it looks like this:

![b0747277691f221b1a1616ea7e606657](https://cloud.githubusercontent.com/assets/5873529/6200957/7a138dee-b456-11e4-84d9-2a606a17167c.png)

I've confirmed xdebug is installed and remote_enabled is on. I've also tried setting the `remote: true` config option, but that generates the same result. Nothing obvious shows in apache logs (my site is running the traditional LAMP stack). Any ideas? It would be great to have a combined report of all code coverage between unit and acceptance tests. Thanks!

**Comment by ThePeach** [comment]
I've had a similar problem (see #1621 and #1622) which was related to the unstable version of CodeCeption being installed. Could you please ensure you're running the stable version?

**Comment by stephencroberts** [comment]
Yeah, I'm using 2.0.10.1 (the latest release). Any ideas what else I can try?

**Comment by Ragazzo** [comment]
did you set correct `remote_config` right ?

**Comment by stephencroberts** [comment]
Which `remote_config` are you referring to? I tried setting `remote: true` in codeception.yml. But if I understand it correctly, since I'm running it locally with phpbrowser, I don't need to connect to it as a remote. Locally is the only way to get a combined report of coverage for all types of tests. Correct?

**Comment by Ragazzo** [comment]
Check guide for `[yii2-basic](https://github.com/yiisoft/yii2/blob/master/apps/basic/tests/README.md#remote-code-coverage)`

**Comment by DavertMik** [comment]
@stephencroberts sorry, this kind of things are really hard to debug in discussion mode )
What I recommend to do is to put series of var_dumps into c3.php to see if it is actually gets executed in requests. Because it should.

**Comment by stephencroberts** [comment]
Yeah, I've tried all the recommendations so far and did some fairly extensive debugging through c3.php and into the code coverage part of codeception. The only interesting thing I noticed is that the requests sent by phpbrowser don't actually have the codeception headers. There are a couple of other requests being made that do have the correct headers, but since I don't have a working example to compare it to yet, I'm not sure if that's a problem or not. 

I'll create a simple project on GitHub exhibiting the behavior I'm seeing so you guys can take a look as well. Hopefully I'm missing something really simple.

**Comment by DavertMik** [comment]
Sure, please do it. I will try to help you

**Comment by acedude** [comment]
Got the same issue while testing a Laravel-based REST API. Code coverage reports only Class coverage. Using CC 2.0.11. Tried 2.0.9 with the same result.

**Comment by FnTm** [comment]
Any progress on this? I have a project using ZF2 and CC 2.1.0 and I am having the exact same result. HTML files are being generated, but no tests are added to them, line coverage is at 0%, and not even 1 test is showing up anywhere.

**Comment by forsaken17** [comment]
i assume you have `fastcgi_finish_request();` in your application. codeception cannot find appropriate remote coverage to merge because your application provides HTTP response to early. file **codecoverage.serialized** simply doesn't exists yet. so solution is either you put sleep to Codeception\Coverage\Subscriber\LocalServer::afterSuite simply to wait for that file *or*, which is much better, create an extra cookie or header or variable env=test and wrap fastcgi_finish_request();

**Comment by neronmoon** [comment]
@timtkachenko 
> create an extra cookie or header or variable env=test and wrap fastcgi_finish_request();

Can you give example?
