### ISSUE TITLE
Asserts module greater/less than documentation is opposite of functionality

### ISSUE THREAD

**Issue by apkostka** [Codeception/Codeception#1721]
In the [Asserts Module documentation](http://codeception.com/docs/modules/Asserts#assertGreaterThan), it is claimed that when using `assertGreaterThan($expected, $actual)`, the expression `$expected > $actual` should evaluate to `true`. The order of parameters is the same for `assertGreaterThanOrEqual`, `assertLessThan`, and `assertLessThanOrEqual`.

However, this is the opposite of actual functionality, as documented in [PHPUnit](https://phpunit.de/manual/current/en/appendixes.assertions.html). This can be tested with the following Cest code:

    public function test_asserts(ApiTester $I)
    {   
        $I->assertLessThan(2,1);
        $I->assertLessThanOrEqual(2,1);

        $I->assertGreaterThan(1,2);
        $I->assertGreaterThanOrEqual(1,2);
    }

Each of these pass, although they contradict the documentation.

**Comment by venyii** [comment]
@DavertMik IMO this can be closed as it was fixed in 379a3f1a818955b4bd9c665ea4a0efc722f77d71
