### ISSUE TITLE
WebDriver config being ignored

### ISSUE THREAD

**Issue by CWSpear** [Codeception/Codeception#1726]
Using this `acceptance.suite.yml` config:

```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
        - Laravel5
    config:
        Laravel5:
            environment_file: .env.testing
        WebDriver:
            browser: phantomjs
            port: 4444
            url: 'http://projectname.dev/'
            wait: 3
```

and the relevant `Cept` code:

```php
$I = new AcceptanceTester($scenario);
$I->wantTo('log into the website');

$I->amOnPage('/login');

$I->fillField('#email', 'testuser@example.com');
```

when I run `codecept run acceptance -vvv` I get this output:

```
Codeception PHP Testing Framework v2.1.0
Powered by PHPUnit 4.4.5 by Sebastian Bergmann.

  Rebuilding AcceptanceTester...

Acceptance Tests (1) --------------------------------------------------------------------------------------------
Modules: WebDriver, AcceptanceHelper, Laravel5
-----------------------------------------------------------------------------------------------------------------
Log into the website (LoginCept) 
Scenario:
* I am on page "/login"

  [Response] 200
  [Page] http://localhost/login
  [Cookies] []
  [Headers] {"cache-control":["no-cache"],"date":["Tue, 17 Feb 2015 23:40:14 GMT"],"content-type":["text/html; charset=UTF-8"],"Set-Cookie":[{},{}]}
* I fill field "#email","testuser@example.com"
  Screenshot and HTML snapshot were saved into '_output' dir
 FAIL 

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-----------------------------------------------------------------------------------------------------------------


Time: 648 ms, Memory: 25.25Mb

There was 1 failure:

---------
1) Failed to log into the website in LoginCept (/Users/cameron/Sites/legacyglobal.cam/tests/acceptance/LoginCept.php)
Couldn't fill field "#email","testuser@example.com":
Form field by Label or CSS '#email' was not found on page.

```

The most noteworthy part is that it says `[Page] http://localhost/login`, which I would expect it to be `[Page] http://projectname.dev/login`. The screenshot is blank, but the HTML (as placed in `_output/LoginCept.fail.html`) is the results of `curl` on the *correct* URL. Again, something really weird is happening, because even if I change the config to `url: https://www.google.com`, the output of the HTML is *still* the `curl` results of http://projectname.dev... so I'm obviously doing something wrong!

In addition, the test takes `648 ms` to complete, which makes me believe it's ignoring the `wait: 3` option in the config as well.

But it gets upset if I try to run the test without phantomjs running, or if I remove `url` altogether, so it is *reading* the config, just not using it in all the places? Or something else really weird is going on?

Same results on Codeception versions `2.0.9`, `2.0.10.1` and `2.1`. I tried on Chrome (selenium + chromedriver), Firefox (selenium) and PhantomJS (a la `--webdriver`), all with similar results. I've tried directly on my Mac and inside a Vagrant VM (well, just PhantomJS in VM), all will the same results!

I've used Codeception before and had zero issues like this... I tried to make everything as close as possible to the environment where it worked to no avail.

Other possibly relevant version numbers:

* PhantomJS `1.9.8`
* Chrome `40.0.2214.111`
* ChromeDriver `2.14.313457`
* Firefox `33.0.1`
* Selenium `no clue (the CLI tool didn't say)`

**Comment by CWSpear** [comment]
I doubt the rest of the output is relevant, but in case, the full output is here: https://gist.github.com/CWSpear/046ec01533112cedba55

**Comment by DavertMik** [comment]
You shouldn't mix Webdriver and Laravel modules in one suite. At least I don't see any reason to do so. If you are running acceptance tests, please disable Laravel module

**Comment by CWSpear** [comment]
@DavertMik I guess I don't know what the `Laravel5` module is for then... it looks to me to add a bunch of stuff, mostly for Acceptance tests: http://codeception.com/docs/modules/Laravel5

There are lots of helpers such as `$I->logout()` that you could use in an Acceptance test, and establish Artisan commands to make sure the DB is set up and seeded (i.e. so that I could test login).

**Comment by CWSpear** [comment]
Specifically, this is a SPA. So I can't really interact with anything without JavaScript enabled.

**Comment by CWSpear** [comment]
However, disabling the `Laravel5` module (and tweaking the code to not rely on that module and to make sure to manually seed the test DB ahead of time) *did* work.

**Comment by janhenkgerritsen** [comment]
@CWSpear You should use the Laravel5 module for functional tests, not for acceptance tests. With acceptance tests you interact with your application over http, while you interact with the application code directly in functional tests.
