### ISSUE TITLE
Line number of fails

### ISSUE THREAD

**Issue by xendk** [Codeception/Codeception#1731]
Apparently Codeception doesn't print the line number, but only the filename, of a failing assertion?

For instance:
```
1) Failed to see that frontpage is correct in FrontpageCept (/var/www/ereolen/tests/api/FrontpageCept.php)
Couldn't see response code is 203:
Failed asserting that 200 matches expected 203.
```

This becomes increasingly frustrating as the test grows.

Just adding ":10" to the filename above would save the day.

**Comment by DavertMik** [comment]
Actually it does: it prints step trace as well as stack trace. Please run with `--debug` if somehow this info is not displayed

**Comment by xendk** [comment]
No it doesn't, at least not in 2.0.11:

```
Codeception PHP Testing Framework v2.0.11
Powered by PHPUnit 4.4.5 by Sebastian Bergmann.

Api-claymore Tests (1) ---------------------------------------------------------------------------
See that frontpage is correct (FrontpageCept)                                               Fail
--------------------------------------------------------------------------------------------------


Time: 365 ms, Memory: 11.00Mb

There was 1 failure:

---------
1) Failed to see that frontpage is correct in FrontpageCept (/var/www/ereolen/tests/api/FrontpageCept.php)
Couldn't see response code is 203:
Failed asserting that 200 matches expected 203.

Scenario Steps:
4. I see response code is 203
3. I expect a success response and XML data
2. As a Random client
1. I send get "ebook/frontpage.xml"

                                     
FAILURES!                            
Tests: 1, Assertions: 1, Failures: 1.
```

For reference, the error is in line 10 of FrontpageCept.

It shows step numbers, but they only have a vague relation to line numbers, throw in empty lines for grouping and comments, and there pretty useless (you're down to counting the `$I`s).

Neither does `--debug`, and it can't be right you have to rerun a failing test in debug mode to figure out where it went wrong.

**Comment by DavertMik** [comment]
Ok, this is done in Codeception 2.1,
you can switch to master branch to check it )

**Comment by xendk** [comment]
Excellent, just what I was looking for. Thanks. :-)

**Comment by mindplay-dk** [comment]
I only see the location when the failure is an actual, failed assertion - when it's an unexpected exception, I don't see a line-number.

For example, in a `Cest`, forcing a failure produces no useful output:

```
throw new \RuntimeException("KER-BAM!");
```

Produces:

```
There was 1 error:

---------
1) KodusHelperCest: Can get class loader
 Test  tests\unit\\KodusHelperCest.php:canGetClassLoader
                               
  [RuntimeException] KER-BAM!  
                               

Scenario Steps:

 2. $I->assertInstanceOf("Compo...","Compo...","Could...") at tests\unit\KodusHelperCest.php:33
 1. $I->getClassloader() at tests\unit\KodusHelperCest.php:31

#1  Kodus\Test\Test\Unit\KodusHelperCest->canGetClassLoader

FAILURES!
Tests: 4, Assertions: 5, Errors: 1.
```

Could we have something like:

```
1) KodusHelperCest: Can get class loader
 Test  tests\unit\\KodusHelperCest.php:canGetClassLoader
 File  tests\unit\KodusHelperCest.php:36
                               
  [RuntimeException] KER-BAM!  
```

Or maybe:

```
1) KodusHelperCest: Can get class loader
 Test  tests\unit\\KodusHelperCest.php:canGetClassLoader
                               
  [RuntimeException] KER-BAM!  
  in tests\unit\KodusHelperCest.php:36
```

Either way, something that tells me where the actual error occurred.

Turning on full-on debugging produces immense amounts of noise - the file and line-number (and possibly stack-trace?) should be displayed when your tests fail for any reason, not only when you're trying to debug a test.

I mean, a failing test *always* needs to be debugged, right? I shouldn't need to switch on a special feature to get the information necessary to fix a failing test - should I?
