### ISSUE TITLE
[LogicException] The page history is empty.

### ISSUE THREAD

**Issue by mlanin** [Codeception/Codeception#1732]
I am preparing acceptance tests for my SOAP API methods. I've already made two of them and if I launch each of them separately, they pass without any problems. But if I call them together using `codecept run acceptance`, second always fails with `[LogicException] The page history is empty` on `$I->see();` method. Why is it so?
I'm using codeception v2.0.11

**Comment by Naktibalda** [comment]
It is probably too late to respond to this issue.
`see` method throws that exception if `amOnPage` method wasn't called before it
