### ISSUE TITLE
The @ operator hides fatal errors

### ISSUE THREAD

**Issue by xendk** [Codeception/Codeception#1735]
The `@` operator on class_exists in Configuration::createModule() hides fatal errors in modules (like, say, redefining requiredFields to static), and makes build and run exit without any indication of error.

This is very unfortunate as it makes Module development quite a challenge.

I traced it back to this: https://github.com/Codeception/Codeception/commit/12179ed802427d6c389da023a6a5c8364c284298

Any chance that there's another was to fix that issue? Alternatively add a "developer mode" that'll disable the `@s`

**Comment by DavertMik** [comment]
The same issue was created a few weeks ago. Actually there is no real need for making `@` there, except the way Yii1 autoloader works. I can't change this in stable 2.0 branch as it can be possible breaking change. However, `@` is removed in Codeception v 2.1 which will be ready in March

See: https://github.com/Codeception/Codeception/pull/1676
