### ISSUE TITLE
attachFile seems to fail in Functional test

### ISSUE THREAD

**Issue by lexasngrv** [Codeception/Codeception#1736]
Hello,

here is a piece of my functional test in a Yii2 project which gives an error:

``` php
$I->attachFile('//form//input[@type="file"]', 'picture.jpg');
```

The error is UPLOAD_ERR_NO_FILE.

It seems that `\Codeception\Lib\InnerBrowser::attachFile($field, $filename)` passes the correct value in `$formField->upload($path);`, but `\Symfony\Component\DomCrawler\Field\FileFormField::setValue($value)` gets `NULL` in `$value`.

I use `Yii2`, advanced app template and latest version of `yiisoft/yii2-codeception` extension.

**Comment by wilwade** [comment]
Also having this issue. Doesn't always happen. Depends on what is called first? I'll try some more testing to see if I can narrow it down tomorrow.

**Comment by wilwade** [comment]
If I do a functional test with just:
```php
$I->amOnPage('/run');
$I->attachFile('#file', 'file.csv');
$I->click('#button');
```
It works but if I try to test for the form error...
```php
$I->amOnPage('/run');
$I->click('#button');
$I->see('needs file');

$I->amOnPage('/run');
$I->attachFile('#file', 'file.csv');
$I->click('#button');
```
It will fail.

Debugging the ```\Symfony\Component\DomCrawler\Field\FileFormField::setValue($value)``` will get null twice for the initialize, but then it does set the correct data in the ```$this->value```.

**Comment by lexasngrv** [comment]
Yes, I also have this issue after sending form with validation errors. Perhaps page reloading causes the problem.
