### ISSUE TITLE
DB cleanup don't work

### ISSUE THREAD

**Issue by patto-sk** [Codeception/Codeception#1740]
My config: 

populate: true
cleanup: true

When I run acceptable tests: populate run correctly but DB cleanup don't work. Created test user remain in DB.

Codeception v2.0.11

**Comment by DavertMik** [comment]
This could be a regression from the latest update. Could you try the same
on Codeception 2.0.10?
24 лют. 2015 13:42, користувач "patto-sk" <notifications@github.com>
написав:

**Comment by atorian** [comment]
it only works if you provide a dump. 
Db module line 122

**Comment by patto-sk** [comment]
Don't work neither 2.0.10.

I've set dump file correctly. Cleaning database before test works but cleaning after test don't work.

But I found solution for me. I've set a gulp task to cleanup database.

**Comment by atorian** [comment]
But that make sense, espetially if you want to check DB if test fails.
