### ISSUE TITLE
fillField fails occasionally

### ISSUE THREAD

**Issue by lucknerjb** [Codeception/Codeception#1749]
Hello,

From time to time, my acceptance tests will fail because part of the content of fillField gets cut off and the assertion can't match the proper text. I'm not sure why this happens exactly. This doesn't seem to happen when I run the tests with Selenium and an actual Firefox browser, only with phantomjs (in ghostmode) and webdriver.

Here is an example of the test that is run:

```
/**
    * @param AcceptanceTester $I
    * @test
    */
   public function edit_a_valid_personal_interest(\AcceptanceTester $I)
   {
      $I->addPersonalInterest($I);

      // Store the ID
      $interestId = $I->grabAttributeFrom('#personal-interests-list tbody tr:last-child .edit-interest-btn', 'data-id');

      // Edit a personal interest
      $newInterestContent = 'New Personal Interest - edited';
      $I->click('.edit-interest-btn[data-id="' . $interestId . '"]');
      $I->waitForElementVisible('.interest-content');
      $I->fillField('.interest-content', $newInterestContent);
      $I->click('Save Interest');
      $I->wait(1);

      $I->see($newInterestContent, '#personal-interests-list tbody tr:first-child td:first-child');
   }
```

**addPersonalInterest** looks like this in my acceptance helper file

```
public function addPersonalInterest($I, $newInterestContent = 'new content') {
      $I->click('#add-personal-interest-btn');
      $I->waitForElementVisible('.interest-content');
      $I->fillField('.interest-content', $newInterestContent);
      $I->click('#save-interest');
      $I->wait(1);
   }
```

and here is an example of the failure output:

```
1) Failed to add and edit a personal interest in PersonalInterestsCest::edit_a_valid_personal_interest (/some/path/PersonalInterestsCest.php)
Couldn't see "New Personal Interest - edited","#personal-interests-list tbody tr:first-child td:first-child":
Failed asserting that any element by '#personal-interests-list tbody tr:first-child td:first-child' on page /s/me/edit
Elements:
+ <td> New Pe
contains text 'New Personal Interest - edited'

Scenario Steps:
22. I see "New Personal Interest - edited","#personal-interests-list tbody tr:first-child td:first-child"
21. I wait 1
20. I click "Save Interest"
19. I fill field ".interest-content","New Personal Interest - edited"
18. I wait for element visible ".interest-content"
17. I click ".edit-interest-btn[data-id="1"]"
16. I grab attribute from "#personal-interests-list tbody tr:last-child .edit-interest-btn","data-id"


FAILURES!
Tests: 12, Assertions: 45, Failures: 1.
```

Checking the output files shows that the text indeed gets cut off. The issue is this only happens here and there. For now, I run the tests manually so I can re-run them but I'm working toward using these with Jenkins but can't until they are reliable...

I've tried on both v2.0.9 and 2.0.11 and the issue still happens.

Any help / insight is greatly appreciated!

**Comment by lucknerjb** [comment]
I forgot to mention that these fields are in a bootstrap 3 modal window if that is of any consequence.

**Comment by M1ke** [comment]
I have the same problem, also in a modal (but using a custom JS to generate). Sadly I've not been able to generate much additional data which would help debug, I receive

>  [Facebook\WebDriver\Exception\ElementNotVisibleException] Element is not currently visible and so may not be interacted with
> Build info: version: '2.49.0', revision: '365eeb4', time: '2016-01-13 18:37:00'
> System info: host: 'm1ke-laptop', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-26-generic', java.version: '1.7.0_91'
> Driver info: driver.version: unknown 

I can see the item in the screenshot.

**Comment by klandaika** [comment]
This issue still seems to exist. We did a test with bootstrap modal opened via bootstrap JS and by creating a full modal markup without the JS. So basically when the modal is open by bootstrap the DOM would be identical to that of our modal without JS (with exception of have the bootstrap modal JS events attached).

Results:

1. Without JS `fillField` works correctly every time.
2. With JS generated modal, `fillField` randomly cuts of the end of the input string at different position.

We went one step further and extended the web-driver, to try to debug this further. Seems like the issue could be on the selenium side. From Selenium log we see that it receives the entire input string from the call to `sendKeys()` but does not add them all to the input field.

We are running this with docker image `selenium/standalone-chrome:3.4` on `Ubuntu 16.04`

**Comment by Naktibalda** [comment]
chromedriver has many issues related to sendKeys: https://bugs.chromium.org/p/chromedriver/issues/list?can=2&q=sendKeys&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by WooDzu** [comment]
I randomly hit this with Puppeter too. Does anyone have any solution?
It fails on of the text fields in the middle of a modal form that does not stand up from other text fields.

**Comment by Naktibalda** [comment]
PhantomJS is dead https://github.com/ariya/phantomjs/issues/15344

**Comment by davidyell** [comment]
I am having this issue too. I am trying to input an email field and every time I run the test, it seems to input only partial input.
