### ISSUE TITLE
seeResponseJsonMatchesJsonPath always validating true - WithFix

### ISSUE THREAD

**Issue by rodrigoglispa** [Codeception/Codeception#1751]
Firts of all amazing job with this project !!!

You must be busy so i will go directly to the point. 

The assert function for JsonPath (seeResponseJsonMatchesJsonPath) is always validating to true because there is always an object Flow\JSONPath\JSONPath being returned (either the JsonPath match something or not).
Class: \Codeception\Module\REST
Function: seeResponseJsonMatchesJsonPath
Line: 687

EasyFix:
it is necesary to add to the new instance of JsonArray a call to "data" function of the JSONPath class, to explicity get the content of what is being matched by the JsonPath.

Before: 
 public function seeResponseJsonMatchesJsonPath($jsonPath)
    {
        $this->assertNotEmpty((new sonArray($this->response))->filterByJsonPath($jsonPath),
            "Received JSON did not match the JsonPath provided\n".$this->response);
    }

 
After: 
 public function seeResponseJsonMatchesJsonPath($jsonPath)
    {
        $this->assertNotEmpty((new sonArray($this->response))->filterByJsonPath($jsonPath)->data(),
            "Received JSON did not match the JsonPath provided\n".$this->response);
    }

**Comment by josille** [comment]
Line is 693, Function seeResponseJsonMatchesJsonPath

**Comment by Naktibalda** [comment]
This issue had been fixed on 6th of February 37af30da1566a31e00dcdf76e1b0046153dced61
