### ISSUE TITLE
Turning off backupGlobals

### ISSUE THREAD

**Issue by PatrickRose** [Codeception/Codeception#1752]
I'm currently porting over some tests to use Codeception since we're about to start adding Acceptance tests. However, the current codebase include a lot of leftovers from PHP4 days, meaning there's liberal use of global etc.

Is it possible to turn off the use of backupGlobals?

**Comment by Naktibalda** [comment]
It is possible to disable backupGlobals by setting `backup_globals: false` in codeception.yml since 2.1.9
