### ISSUE TITLE
amOnSubdomain - wierdness

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#1757]
Hi

I have a URL, such as `dev.mysite.co.uk`. This is the top level website, i.e. `mysite.co.uk` will redirect to `dev.mysite.co.uk`

I also have `admin.mysite.co.uk`

In my functional tests, I define the URL (using PhantomJS) as follows:

`url: 'http://dev.mysite.co.uk'`

If I run the main tests, all is good, until I get to testing the admin

I have something along the following:

```
$I->amOnSubdomain('admin')
$I->amOnPage('login');
```

Pretty straight forward, until I get an exception and a failed image.

It seems that Codeception, thinks that becuase I am using `admin` as the subdomain (and .co.uk) it thinks I want `admin.co.uk` which is wrong.

I'm using version `1.8.7` (due to using an older version of PHP)

Has anyone else seen this?

**Comment by Naktibalda** [comment]
My first attempt was backwards incompatible for anyone who is currently using $I->amOnSubdomain('admin.mysite');

A backwards compatible way to solve this issue would be to leave the default behaviour unchanged,
but introduce a new optional configuration option for people who want to use a new behaviour.

The option could be named domain or baseDomain:

domain - used as base for subdomain navigation.

If domain is not set, __construct would set it to the last 2 segments of hostname from url.

The new amOnSubdomain method would look like this:
```
    public function amOnSubdomain($subdomain)
    {
        $url = $subdomain . '.' . $this->config['domain'];
        $this->_reconfigure(['url' => $url]);
    }
```

I can implement this change, if it is approved. @DavertMik

**Comment by ghostal** [comment]
While being a _little_ awkward, this does sound like it would work in a backwards compatible way, which is obviously important. I can't think of a better backwards compatible solution.

The configuration/usage approach could then be revised to something more intuitive/less redundant in a major version change.

It seems important to resolve this in the current release though, as currently it seems that any domain not registered directly under a TLD (so, for example, any `.co.uk` or `.ac.uk` domains) will suffer from the issue.

**Comment by DavertMik** [comment]
Yeah, the issue still here :(

Sorry I don't know what could be a better way for this. Probably we should specify current behavior in docs and force users to switch to `amOnUrl`.

**Comment by eXorus** [comment]
Thank you for contributing to this issue. As it has been 4 years since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please feel free to either reopen this issue or open a new one. 

The new repository is: https://github.com/Codeception/module-webdriver

We will be more than happy to look at it again!
