### ISSUE TITLE
Problem with sending SOAP request with multiple tags without parent tag

### ISSUE THREAD

**Issue by Kofriv** [Codeception/Codeception#1758]
Hi,
I've got an issue while sending SOAP request by codeception with multiple tags in the request content.

In the past, I was able to send SOAP request to the 3rd party webservice like:

`$I->sendSoapRequest('GetCustomerByApplication','<Application>123456789</Application>');`

But now, that 3rd has just deployed a new change and I should send a partner code as well for verification. But after I add another tag to the request and I get an error said that:

`1) testCept (C:\codeception2\tests\acceptance\testCept.php) Couldn't send soap request "GetCustomerByApplication","<Application>123456789</Application><partnerSecretKey>abc-xyz</partnerSecretKey>": ErrorException: DOMDocument::loadXML(): Extra content at the end of the document in Entity, line: 1`

Here is my code:

`$I->sendSoapRequest('GetCustomerByApplication','<partnerSecretKey>abc-xyz</partnerSecretKey>');`

Here is the template that I get when connect to the WSDL:

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<SOAP-ENV:Body>
    <GetCustomerByApplication>
        <Application>String</Application>
        <partnerSecretKey>String</partnerSecretKey>
    </GetCustomerByApplication>
</SOAP-ENV:Body>`

Any help could be great appreciated.

Regards,

Khoa N

**Comment by peterfrench** [comment]
I'm having the same issue. It appears to be a problem with Codeception\Module\SOAP::sendSoapRequest() on line 143:
```php
...
 public function sendSoapRequest($action, $body = "")
    {
        $soap_schema_url = $this->config['schema_url'];
        $xml = $this->xmlRequest;
        $call = $xml->createElement('ns:' . $action);
        if ($body) {
            $bodyXml = SoapUtils::toXml($body); // ** Starts here
            if ($bodyXml->hasChildNodes()) {
                foreach ($bodyXml->childNodes as $bodyChildNode) {
                    $bodyNode = $xml->importNode($bodyChildNode, true);
                    $call->appendChild($bodyNode);
                }
            }
        }
...
```

If the $body passed to SoapUtils::toXml is a string, it uses DOMDocument::loadXml() to parse it which results in an error, `ErrorException: DOMDocument::loadXML(): Extra content at the end of the document in Entity, line: 1`, since having multiple tags not enclosed by a root tag is invalid XML.

```php
namespace Codeception\Util;

class Soap
{
...
public static function toXml($xml)
    {
        if ($xml instanceof XmlBuilder) {
            return $xml->getDom();
        }
        if ($xml instanceof \DOMDocument) {
            return $xml;
        }
        $dom                     = new \DOMDocument();
        $dom->preserveWhiteSpace = false;
        if ($xml instanceof \DOMNode) {
            $xml = $dom->importNode($xml, true);
            $dom->appendChild($xml);
            return $dom;
        }
        if (is_array($xml)) {
            return self::arrayToXml($dom, $dom, $xml);
        }
        // ** String gets parsed by DOMDocument
        if (!empty($xml)) {
            $dom->loadXML($xml);
        }
        return $dom;
    }
...
```

**Comment by peterfrench** [comment]
@Kofriv To get around this issue with strings, you could pass in a `DOMDocument` object instead of a string for your `sendSoapRequest()` call:

```php
$dom = new \DOMDocument();
$dom->appendChild($dom->createElement('Application','123456789'));
$dom->appendChild($dom->createElement('partnerSecretKey','abc-xyz'));

$I->sendSoapRequest('GetCustomerByApplication',$dom);
```

This worked for me. I hope that helps a bit.

**Comment by dkir72** [comment]
Hi all 
I also have problem with this, and I am not shure that it is possible to solve via $dom

$I->sendSoapRequest('timeTable',
    '<auth>
          <login>login</login>
          <psw>psword</psw>
          <terminal>test</terminal>
          <represent_id>123</represent_id>
    </auth>
    <travel_info><from>200</from>
           <to>2060</to>
           <day>20</day>
           <month>11</month>
           <time_sw>0</time_sw>
           <time_from>0</time_from>
           <time_to>0</time_to>
    </travel_info>
    </timeTable>
    ');

and I get [PHPUnit_Framework_Exception] DOMDocument::loadXML(): Extra content at the end of the document in Entity, line: 7 

Is there any method for solve problem?

**Comment by eXorus** [comment]
You can also use DOMDocument to manage this kind of request.

I'm closing the issue.
