### ISSUE TITLE
Codeception with Codeigniter -- run tests from PHP script

### ISSUE THREAD

**Issue by dtirer** [Codeception/Codeception#1760]
I have a Codeigniter project that uses Codeception for acceptance testing.  I have a 'tools' controller setup in Codeigniter, which I use to store command line methods that perform various utility functions.

I'm looking to create a method to wrap the build and execution of tests, so that I can change environments and databases all in one command.

However, Codeception becomes unresponsive when I try to run the tests as follows:

```public function run_tests()
 {
        $this->load->database('testing');
        echo shell_exec("cd ..; php codecept.phar build");
        echo shell_exec("cd ..; php codecept.phar run");
 }```

from the terminal, I then execute the controller methods:

`php index.php tools run_tests`

The Codeception `build` seems to execute fine, but the `run` command just hangs up with no errors

**Comment by DavertMik** [comment]
Sorry no ideas to help you. You can ask your question at http://phptest.club
