### ISSUE TITLE
Acceptance tests coverage not merged into functional and unit tests coverage reports

### ISSUE THREAD

**Issue by ThePeach** [Codeception/Codeception#1762]
I'm posting this here as I failed to see any reference anywhere and wasn't sure whether this was already known.

When I'm running codeception to generate coverage reports, I get the unit and functional reports merged together within the `_output/coverage` directory, while the acceptance end up in a separate directory in `_output/acceptance.remote.coverage`.

I don't know if that's meant to be working like that, and I'm assuming that's mainly due to the way the coverage information is captured when running the acceptance tests.

**Comment by Ragazzo** [comment]
yes, they are not meant to be merged together maybe later this feature will be added . Note that it is for true for `remote` acceptance code coverage for `local` acceptance code coverage they will be merged together, however there is no any scence in `local` acceptance code coverage since you will not be able to use `Selenium 2.*` with it, check docs for more info

**Comment by ThePeach** [comment]
Thanks @Ragazzo I was aware of the local acceptance coverage, and everything works well. I just noticed there is no reference of the aggregation of the reports in the documentation, so it might be worth highlighting that.

On that subject, due to the fact that the coverage is separate, if I have a `@codeCoverageIgnore` directive, it will be ignored for any kind of tests: would it be worth suggesting being able to specify which suite is should be applied to (and leave it for all by default)?

**Comment by Ragazzo** [comment]
i dont think i understand your suggestion about code coverage . As for highlighting code coverage reports merge feel free to submit PR to docs

**Comment by ThePeach** [comment]
regarding the merge on the docs I'll do that this weekend as soon as I have some spare time.

The `@codeCoverageIgnore` directive is excluding the coverage inspection of that piece of code in any suite. I was wondering if it was possible to exclude it only on certain suites by passing some optional arguments to it, e.g. `@codeCoverageIgnore unit,functional` ... I don't know the internals well enough so I don't know if it's feasible.

**Comment by Ragazzo** [comment]
You cant do it currently , not sure if this will be implemented

**Comment by ThePeach** [comment]
I'll try to open a feature request and see what will come out of it.

Closing down this one in the meantime. Thanks for the help!
