### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 145:

### ISSUE THREAD

**Issue by oriceon** [Codeception/Codeception#1763]
Hello there, i`m trying to playing with laravel 5 codeception but i`m stuck into that NotFoundHttpException.

Could you have a look at http://stackoverflow.com/questions/28947685/laravel-5-codeception and tell me where i`m wrong?

Thanks!

**Comment by janhenkgerritsen** [comment]
Does the problem persist if you use the latest version of the Laravel 5 module? You can find it at https://github.com/janhenkgerritsen/codeception-laravel5. 

But make sure you use a version of Codeception before 2.0.11 if using this package, otherwise the wrong files get loaded.

**Comment by junaidnasir** [comment]
Same problem here. @janhenkgerritsen i am using latest version of laravel5 module

**Comment by oriceon** [comment]
Do you use some require_once în route.php?

**Comment by junaidnasir** [comment]
no, you can see my setup details over here https://github.com/janhenkgerritsen/codeception-laravel5/issues/16
