### ISSUE TITLE
When --steps is set, --coverage does not take effect

### ISSUE THREAD

**Issue by mipon** [Codeception/Codeception#1765]
This does not generate coverage files.

```
php codecept.phar run unit --steps --coverage
```

However, this does.
```
php codecept.phar run unit --coverage
```

This also applies to `--coverage-xml` and `--coverage-html`.

**Comment by nsossonko** [comment]
This should go in release notes, it was a very confusing issue to debug...

**Comment by Naktibalda** [comment]
Duplicate of #2620  Fixed today.
