### ISSUE TITLE
What does actor: Tester represent in codeception.yml?

### ISSUE THREAD

**Issue by mipon** [Codeception/Codeception#1772]
Hello,

I'd like to know what `actor: Tester` means in the configuration file generated when the `bootstrap` command is performed. I tried changing it to something else and even removed the option but tests seem to work.

Is it something critical and should not be removed or changed?

**Comment by DavertMik** [comment]
This defines how actors for new suites are called. You can bootstrap empty project, change Tester to Ninja and have a ninjas testing your website =)

**Comment by mipon** [comment]
Thanks for the reply.

So is it okay to remove?

**Comment by DavertMik** [comment]
in this case new suites will be named `*Guy` (for BC compatibility)
i don't know why you'd need to remove that

**Comment by mipon** [comment]
I was fixing some problems of my tests and trying different combinations of options. Then I wondered what it was for.

So it sounds I don't have to care it. Thank you.
