### ISSUE TITLE
suggestion: directive to exclude coverage only for specific suites

### ISSUE THREAD

**Issue by ThePeach** [Codeception/Codeception#1774]
This is just a suggestion: as currently the code coverage is aggregated only for unit and functional tests while remote code coverage is kept separate, it would be nice to have a way to exclude the coverage of certain methods only for certain suites: e.g. 

```
@codeCoverageIgnore unit,functional
```

will have the coverage calculated only for the acceptance tests.

Hope this makes sense.

**Comment by Naktibalda** [comment]
It is possible to disable code coverage for specific suite by adding
```yml
coverage:
    enabled: false
```
to functional.suite.yml file.
