### ISSUE TITLE
How to best use Friends in Cests

### ISSUE THREAD

**Issue by codemedic** [Codeception/Codeception#1778]
Just came across the Friends trait and its implementation in Actor.
I wonder how to best make use of friends, with a seconf Actor type.
The [example here](http://codeception.com/docs/04-AcceptanceTests#Multi-Session-Testing) only shows how to use it without specifying the second option for `Actor::haveFriend($name, $actorClass = null)`.
Is it possible to have multiple actors in one suit?

**Comment by DavertMik** [comment]
You can pass a StepObject as second parameter, but you can't access actor from another suite
