### ISSUE TITLE
throw exceptions for notices

### ISSUE THREAD

**Issue by akleiber** [Codeception/Codeception#178]
From phpunit we now:

> By default, PHPUnit converts PHP errors, warnings, and notices that are triggered during the execution of a test to an exception.

But with codeception notices are not converted to exceptions as we can see here:

https://github.com/Codeception/Codeception/blob/master/src/Codeception/Subscriber/ErrorHandler.php#L22

https://github.com/Codeception/Codeception/blob/master/src/Codeception/Subscriber/ErrorHandler.php#L31

http://www.php.net/manual/en/errorfunc.constants.php

Notices == 8 and the error handler here only throws exceptions for errors higher than notices.

To be sure to have good code you should change the default error handler to throw exceptions for notices as well.

**Comment by delboy1978uk** [comment]
Is it possible to configure this on and off? for instance, we have a passing test suite so long as they *aren't* thrown. We are working through our `error_log` removing these notices, but previously using phpunit we just had to add a property in the xml, so we could deploy without problems, and re-throw them in dev time, so we could slowly work to get rid of them all.

**Comment by delboy1978uk** [comment]
ah cool, just found this https://github.com/Codeception/Codeception/commit/76f1bac5bb93da73b0b55c57d97f41b2b4641394
