### ISSUE TITLE
Still receiving errors when using Laravel5 helper with latest Codeception dev build 

### ISSUE THREAD

**Issue by mikeerickson** [Codeception/Codeception#1780]
So far as I can see (updated to latest version of Codeception along with rebuilding the modules so I pull in latest Laravel5 module) this is still having issues.

http://d.pr/i/DcQj

This is the same issue referenced at https://github.com/Codeception/Codeception/issues/1748

**Comment by jonathantorres** [comment]
That issue was fixed. But it hasn't been released yet :disappointed: It should be available on `2.0.12`

**Comment by mikeerickson** [comment]
Well, that explains it.  I have applied to quick fix to get things working again for the time being
