### ISSUE TITLE
Do not run test scripts from different suites as a single script

### ISSUE THREAD

**Issue by mipon** [Codeception/Codeception#1781]
Hello,

When `php codecept.phar run` is performed, it seems included scripts in different suites are still alive. For example, if one of functional tests includes file A and one of unit tests includes the same file A and file A declare a function, the overall tests fail by throwing a fatal error, `Fatal Error: Fatal error: Cannot redeclare...`.

To produce the problem,

In `_bootstrap.php` of functional tests, insert the following code. And add the same code to the `_bootstrap.php` file of unit tests.

```php
function _myTest() {}
```

Then 

```
$ php codecept.phar run
```

It gives 

```
Fatal error: Cannot redeclare _myTest() (previously declared in ...
```

I can do something like

```
$ php codecept.phar run acceptance
$ php codecept.phar run functional
$ php codecept.phar run unit
```

But when generating a coverage file, I guess it does not produce an accurate report. 

Is there a workaround?

**Comment by DavertMik** [comment]
Yes, this is typical behavior of PHP. Please put your function inside if function_exists block

**Comment by mipon** [comment]
Thanks for the reply. 

I'd like to mention that it means unit tests get affected by included scripts in the bootstrap of a different test suite. If tests are simple like the one illustrated above, it might be okay. But when it becomes complex, it might not be a good idea to let them mixed.

What I understand about unit tests is that they should be done in isolation, therefore, called _unit_ tests. If variables such as $_GET, $_POST are set in the bootstrap of functional tests, with the current design, unit tests also inherit those values, which can cause unexpected test results. 

It would be great if each test suite starts new script and each of their bootstraps doesn't interfere with each other by simply doing `php codecept.phar run`.

For now, I'll run tests separately for each suite. But code coverage can produce results for one suite as far as I know. Is there a way to combine coverage results from different suites?

**Comment by DavertMik** [comment]
Yes, the reality is cruel, so PHP can't unload things. Sure we could start process per each test, but this is slower and much harder to manage. 

You can take a look at Parallel Execution guide, there are some ideas how to run tests separately
