### ISSUE TITLE
Report time for individual steps

### ISSUE THREAD

**Issue by FnTm** [Codeception/Codeception#1787]
While doing some acceptance testing I noticed that a specific test was executing rather slowly. Even though it seems quite simple, there are a couple of Helper methods being called, which take some time. I want to see how long.

### Proposal
Add `--time` cli parameter and/or config parameter, which would report the amount of time a specific step has taken. This should be quite easy to implement. 

It is quite possible that you won't use this most of the times, but for debugging this would be quite handy.

**Comment by DavertMik** [comment]
This can be done via Extension if you write it)

**Comment by shahidmau** [comment]
Why it is closed without a solution? It is really helpful for debugging purpose. Please share me if you created any Extension for this.

**Comment by FnTm** [comment]
This is still something I plan on doing, will post updates here when I come up with something

**Comment by FnTm** [comment]
@DavertMik I took your comments to heart, and checked out extensions and accompanying code to make timing a specific test possible. 
Even though I agree, that creating an Extension for this would be easy, it would require modifying the [StepEvent](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Event/StepEvent.php)  to add `$time` the same way its added to [TestEvent](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Event/TestEvent.php). 

If this is something that could/should be done, please reopen this issue and I will get to work making such an Extension a reality.

**Comment by javigomez** [comment]
I did a tutorial for building this extension here: http://phptest.club/t/how-to-create-a-codeception-extension-to-check-your-tests-performance/374 

I hope is useful for you.

I plan to move to a module someday

**Comment by FnTm** [comment]
@javigomez that is really cool. I think that it should be made into a module and the sooner the better. Thanks a lot for sharing!

**Comment by javigomez** [comment]
@FnTm I just moved it to an extension https://github.com/redCOMPONENT-COM/teststatistics#teststatistics in case you have the time to help testing. thanks
