### ISSUE TITLE
Strict mode for REST module seeResponseContainsJson

### ISSUE THREAD

**Issue by atorian** [Codeception/Codeception#1788]
It might be useful to have strict mode flag for this kind of methods.
Json might contain:

    ['key'=> '1'] // string value

and it could be compared to: 

    ['key' => 1]

Currently this check will fail. Strict mode by default is good, but sometimes we'd like to disable it.

**Comment by DavertMik** [comment]
If you can implement non-strict matching for JSON that would be great)

**Comment by mrmarkfrench** [comment]
It's actually even worse than this, as numeric comparisons will fail even in cases where the JSON is a character-for-character match. If, for example, my JSON response is:
{"number":5}

This test will pass:
$I->seeResponseContainsJson(array('number'=>(int)5));
But this one will fail:
$I->seeResponseContainsJson(array('number'=>(float)5));

Comparing a float with the same numeric value to the one returned in the JSON only passes when the JSON text contains a decimal point, and if there are no non-zero digits after the decimal point, json_encode() will not write 5.0, it will just write 5.

**Comment by atorian** [comment]
fixed
