### ISSUE TITLE
Adding grabOptionsFrom to InnerBrowser/WebDriver

### ISSUE THREAD

**Issue by zbateson** [Codeception/Codeception#1793]
Many a time I've had a need for a 'grabOptionsFrom' type function in my testing, which will return all available options from a combo box.  I've been adding it to a helper, and was thinking of submitting it as it may help others as well.

I need some input, however, on how best to return the options.  My preference would be to return an array of DOMNode objects - which would mean manually creating DOMElement objects in WebDriver - so all properties related to each option can be returned.  I've noticed however, that grab* functions return simple types or strings, and am wondering if my idea would go against some rule somewhere.

Any thoughts?

**Comment by DavertMik** [comment]
Yes, the idea is to return the same values no matter what module is used. Also we don't encourage to use Webdriver internal classes directly in tests. This should go to Helper, as I think of it. 

Maybe you can do a 3rd party module like WebdriverExtra for that?

**Comment by zbateson** [comment]
Hi @DavertMik 

It is possible for WebDriver and PhpBrowser/Frameworks to all return DOMNodes.  The DOMNodes would have to be created manually in WebDriver and returned, but I'm okay with that, it shouldn't be too difficult to achieve.

Another option could be to return an array with one element named "text" and another "value" - but I'd prefer an object over an array like that - this to me would be ugly.

Otherwise, no issues - may look at creating a 3rd party module, but for a single function may be a bit much :)

Thanks

**Comment by DavertMik** [comment]
I think we should add methods to return plain array values from WebDriver.
For instance list all options as array. But this is idea for new issue
