### ISSUE TITLE
How to fill a rich text editor field for an Acceptance test

### ISSUE THREAD

**Issue by mattyh88** [Codeception/Codeception#1794]
I'm trying to fill a rich text editor field (TinyMCE) within my acceptance test.

Using the fillField() function doesn't work as this 'field' isn't really an input field. It's an iframe, styled to look like a fancy text area.

My question is, how can I set some text into the body of the tinyMCE box? I think I'm looking for the addition of a $I->setContent(xpathOrCSS) function. Or does something else already exists to do this?

Thanks.

**Comment by atorian** [comment]
Which module do you use for browsing?
If you want to check JavaScript - you have to use WebDriver with Selenium.

**Comment by mattyh88** [comment]
I'm using WebDriver with Selenium. The question is, I don't really know which function to use in the AcceptanceTester class to set contents in the TinyMCE 'box'

**Comment by atorian** [comment]
if you have iframe - take a look to $I->switchToIFrame("another_frame"); first and then fillField().
But i'm not sure if you really want to check if 3rd party library script works in this way. 
It might be enough to check if final element exists on the page and use submitForm to provide a value.

**Comment by mattyh88** [comment]
Aha yes, I will be able to execute the test by using submitForm. 

The first option (using $I->switchToIframe) won't work as there isn't an input field in that iFrame. Only a <p> tag inside a <body> tag

**Comment by DavertMik** [comment]
Probably you can delegate this to JavaScript. Use executeJS to do the trick. I can't propose any better solution

**Comment by DavertMik** [comment]
You can ask similar questions at http://phptest.club
