### ISSUE TITLE
submitForm doesn't work with checkbox arrays

### ISSUE THREAD

**Issue by Kesarion** [Codeception/Codeception#1797]
Say you have the following checkbox inputs on a page:
```html
<input name="array[]" value="1" type="checkbox">
<input name="array[]" value="2" type="checkbox">
<input name="array[]" value="16" type="checkbox">
```

Checking them manually works just fine:
```php
$I->checkOption('#form input[type=checkbox][value="1"]');
$I->checkOption('#form input[type=checkbox][value="2"]');
$I->checkOption('#form input[type=checkbox][value="16"]');
```

However, the equivalent using submitForm does absolutely nothing when using an array, yet it does work when using just one simple value:
```php
$I->submitForm('#form', array(
            'array[]'    => "[1,2,16]" // array value is NULL, server side
        ));
```
```php
$I->submitForm('#form', array(
            'array[]'    => "2" // adds value 2 as if the second checkbox had been checked
        ));
```

Of course, I can't add another array key with the same name and another value...
What would be the solution here? Could this be a bug?

**Comment by DavertMik** [comment]
@zbateson could you take a look please?

**Comment by zbateson** [comment]
Hi @Kesarion - it's just a matter of getting the right syntax :)

```php
$I->submitForm('#form', [
    'array' => [1,2,16]
]);
```

The '[]' part in the field name for "array[]" shouldn't be set, instead the name is "array".  Setting the value to an array works - shouldn't be any quotes around the array you send though.  Probably just a typo in your example - "[1,2,16]" - should be [1,2,16].

All the best

**Comment by Kesarion** [comment]
It only works with the '[]' unfortunately :(

```
1) Failed to send form in MyCoolClass::aTestyTest (/var/www/tests/acceptance/MyCoolCest.php)
Couldn't submit form "#form",{"username":"MrTesty","password":"123","email":"testy@example.com","array":[2,16]}:
'array' was not found on page.
```

Also, it doesn't matter if it's directly json like "[1,2,16]" or a php 5.4 array [1,2,16], it's still converted to a json array as you can see above, it looks like that either way, yields a NULL server side when I use 'array[]' => [1,2,16], but it works with just one value like 'array[]' => '16', yielding an array with one value, 16, server side.

**Comment by zbateson** [comment]
Hi @Kesarion 

The update that fixes this was only released in 2.0.11 with this commit: https://github.com/Codeception/Codeception/commit/1c17eb11f857612e1ad7973e5441fdfe3196c67e

Can you confirm that you're on 2.0.11 or 2.0 "dev"?  It should work with "array" on 2.0.11 or greater (or there's a bug).

You may be right about it being either an array or a string - the implementation uses Symfony's BrowserKit... I haven't tested so can't say for sure either way.

**Comment by Kesarion** [comment]
Hi @zbateson
It doesn't work on 2.0.11, unfortunately, or on any of the lower versions I tried. I'm curious about the current development version 2.1.0, but I've hit some other issues with that that may be resolved once a prebuild phar comes out.

**Comment by zbateson** [comment]
Hmm... testing it, it's working fine for me on current 2.0 (dev).  It won't work on anything before 2.0.11 as it was only fixed in 2.0.11.

Can you post the output of running 'codecept --version', and the full contents of your aTestyTest function if it's not too long?  The error seems strange anyway because the function doesn't look up parameters on the page... you can send any arbitrary name with a value and it should be fine:

```php 
$I->submitForm('#someForm', ['aFieldThatDoesn'tExist' => 'SomeValue']);
```
Works fine for me as well.

**Comment by Kesarion** [comment]
Look at this part in the submitForm function:
```php
foreach ($params as $param => $value) {
            $els = $form->findElements(\WebDriverBy::name($param));
            if (empty($els)) {
                throw new ElementNotFound($param); // parent::__construct($message . " '$selector' was not found on page.");
            }
```
I guess it makes sense in a way, since 'array' != 'array[]'. Unless the findElements function is smart enough to figure it out, which in my case it isn't. Where can I see the implementation of the 'findElements' function? 

I used the newest version of codeception 2.0 this time:
```
php Codeception/codecept --version
Codeception version 2.0.12
```
Can't imagine why it's not working for me if it is for you (and possibly others), something's definitely different.

I can't share the actual code, but I've simplified it to what I've written here and I'm fairly certain it's not related to the code but to the tools involved (codeception & company). Can you think of anything different on my side, that could cause this?

Thanks for taking the time to test it out, though, at least I know it can work :)

**Comment by zbateson** [comment]
Ooh, I see the confusion.  You're using WebDriver and I hadn't caught on to that (I thought you were using PhpBrowser for some reason).  Yes, this does in fact look like a bug.

I'm not sure how easy/difficult this will be to fix because of how submitForm works for WebDriver.  I'll play with it today anyway and see if it's possible to have it work the same in WebDriver as it does in PhpBrowser for array values :)

**Comment by wasmithee** [comment]
The fix for this bug breaks the submitForm function for me.  I have a select with the name of: 'Departments[dept_name][]'.  Stripping off the last '[]' causes the option to not be selected.
