### ISSUE TITLE
codeception run - ugly output

### ISSUE THREAD

**Issue by DexterHD** [Codeception/Codeception#1798]
There is ugly output on some screen resolutions when you have tests with long path
```
codeception run
```
I have this problem on 1280x800 px display with full screen terminal
![img](https://cloud.githubusercontent.com/assets/1532188/6784849/2e940cc2-d193-11e4-831d-fb361ffa7990.png)

**Comment by DavertMik** [comment]
is there a way to discover the terminal size?

**Comment by DexterHD** [comment]
Yes it is. In screenshot above the terminal size is 149x33. In screenshot below I have terminal size 181x38. As I sad this bug can be discovered only if you have tests with long names and path.
![bash-181x38](https://cloud.githubusercontent.com/assets/1532188/6794856/d64f5b6a-d1e8-11e4-9027-b55bf260f7a8.png)

**Comment by DavertMik** [comment]
I mean, is there a way to get this size in PHP?

**Comment by DexterHD** [comment]
I think it possible via `exec('tput')` as explained here http://stackoverflow.com/a/263900/1228432

**Comment by DavertMik** [comment]
Thanks,  at least bash version looks easy to implement

**Comment by Naktibalda** [comment]
Fixed by https://github.com/Codeception/Codeception/commit/af2fdf8c47114825f63086637d9fdc7826673352#diff-e7dc03741ac5d635b6fcb6a4b6907f89
