### ISSUE TITLE
Colors not working anymore

### ISSUE THREAD

**Issue by rafaelbdb** [Codeception/Codeception#1799]
Console colors has always worked for me, but suddently I'm getting texts like:
```
←[1mAcceptance Tests (1) ←[22m--
```
without any colors, even if I use --colors in console AND set colors:true in codeception.yml (or any combination of them).

I'm using version 2.0.11.

**Comment by DavertMik** [comment]
Probably your terminal does not support color output. I saw this characters when executed tests in Jenkins Console Output.

**Comment by rafaelbdb** [comment]
Indeed, something was wrong with my console.

I was using "Console2" in Windows 7 (colors have been working for a long time, and suddently disapeared), but now I'm using "ConEmu" (much better), and that solved the problem.
