### ISSUE TITLE
Feature Request: Show JSON response data on -vv 

### ISSUE THREAD

**Issue by schmunk42** [Codeception/Codeception#1808]
I tried to patch  the code to be able to see less output from failed JSON responses.
But I could not access the OutputStream from there:
https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/REST.php#L510

Would be nice if the full output is only shown with -vv or -vvv.

**Comment by Ragazzo** [comment]
better to use `$this->debugSection()` for this puprose, then it will be available via `--debug` flag

**Comment by schmunk42** [comment]
So, I'd request to move the response output to a debug section.

**Comment by Ragazzo** [comment]
will you submit PR ?

**Comment by DavertMik** [comment]
I think this issue is non relevant. There were some fixes to REST and output which could have solved that. If it is still a thing please create new issue and probably add some screenshots with output that you don't like

**Comment by Naktibalda** [comment]
This is not an issue but a feature request.

Here is an example of failed test:

```
 Step  See response contains json {"result":"success","state":"active"}}
 Fail  Response JSON does not contain the provided JSON

- Expected | + Actual
@@ @@
Array (
'result' => 'success'
-    'state' => 'active'
+    'state' => 'inactive'
'last_page' => 'payment_confirmation'
'actions' => Array (...)
)
```

@schmunk42 wants to display JSON only in verbose mode.
I think that this is less relevant now, because improved diff output hides unimportant bits.

https://github.com/Codeception/Codeception/commit/bb26aa08fdeef10089465566a9ec0041590e6015
