### ISSUE TITLE
Codeception not honoring protected routes in Laravel 4.2

### ISSUE THREAD

**Issue by aligajani** [Codeception/Codeception#1810]
If I go on app.com/engage, I get a 401 unauthorized, but while writing this in my functional test:

$I->amOnPage('/engage');
$I->canSeeResponseCodeIs(401);

It says it expected a 200 and what's more interesting is, the _output shows the HTML of the page in the dump, where as if you browse to app.com/engage from the browser, you just get "Unauthorized". 

What's happening?

More details on error:

Failed to browse the site after logging in as a member in 013-ScopeMemberCept (/Users/aligajani/Dropbox/Work/Code/CommunityFT/forum/tests/functional/013-ScopeMemberCept.php)
Couldn't see response code is 401:
Failed asserting that 200 matches expected 401.

**Comment by janhenkgerritsen** [comment]
There was an issue with the behavior of the filters. I confirmed it with the `requireAuthenticationForRoute` test in the sample application: [AuthCest](https://github.com/Codeception/sample-l4-app/blob/master/tests/functional/AuthCest.php). The commit referenced above fixes this issue.
