### ISSUE TITLE
Fatal error: \Codeception\TestCase\Test must be abstract

### ISSUE THREAD

**Issue by zdenekdrahos** [Codeception/Codeception#1812]
I upgraded to *v2.0.11* (Windows, PHP 5.5.6) and I get fatal error because `\Codeception\TestCase\Test` is not marked as abstract class:

```php
Fatal error: Class Codeception\TestCase\Test contains 2 abstract methods and must therefore be
declared abstract or implement the remaining methods (PHPUnit_Framework_SelfDescribing::toString,
Codeception\TestCase\Interfaces\Descriptive::getName) in
...\vendor\codeception\codeception\src\Codeception\TestCase\Test.php on line 87
```

It happens when I include a test, but I don't run the test (I know I shouldn't do it :) Marking class as abstract worked for me.

```php
abstract class Test extends TestCase implements
    Interfaces\Descriptive,
    Interfaces\Configurable
{
```

**Comment by gdscei** [comment]
I've had this error pop up in my IDE (Windows) as well in one project. Not that it actually affects my tests (although I do run them in a Linux env) I will try and make a reproducable case. 

Seems like it might be an OS problem
