### ISSUE TITLE
Exception when bootstrap file is not found

### ISSUE THREAD

**Issue by zdenekdrahos** [Codeception/Codeception#1813]
Codeception [throws ConfigurationException](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Subscriber/Bootstrap.php#L27) when bootstrap file is not found. Is that behavior necessary? I probably never used suite's bootstrap ([and I am not alone](https://github.com/search?l=php&q=filename%3A_bootstrap.php+language%3Aphp+%2F%2F+Here+you&ref=searchresults&type=Code&utf8=%E2%9C%93)). Maybe simple information message about unused bootstrap could be good enough. Then users could delete empty bootstrap files.

**Comment by DavertMik** [comment]
Actually the issue I see here is that `settings['bootstrap']` can't be disabled in configuration. If only you could unset it... I think the exception should be thrown (as you may rely on bootstrap file) but by default Codeception should not require `_bootstrap` option in settings

**Comment by zdenekdrahos** [comment]
That's good change. But can I enable only global bootstrap? I need only global bootstrap, but I had to create empty bootstrap file in every suite.

It's fair point about reliability. But strictly speaking I don't rely on bootstrap, I rely on test results. If tests failed I would search why that happened (missing bootstrap is obvious error even without exception).

**Comment by DavertMik** [comment]
You should put `bootstrap: false` inside suites where you don't want bootstrap to be loaded. 
This also should work for global bootstrap config...

My previous proposal of removing `bootstrap` setting at all is not valid anymore

**Comment by zdenekdrahos** [comment]
Great. Thanks.

If suite is able to override options, it should be mentioned in [documentation](http://codeception.com/docs/reference/Configuration). I didn't know about it, maybe it's written somewhere and I just missed it.
