### ISSUE TITLE
Database procedures are not cleaned

### ISSUE THREAD

**Issue by oytuntez** [Codeception/Codeception#1815]
Hi all,

We are making use of MySQL procedures on our database and when we use Db module to dump and cleanup the database in every test run, it fails to remove the procedures, while dropping the tables. Just checked the related driver, it doesn't have the code piece to do this.

For now I will put a database drop on the dump file, however this feature may be worth looking at.

**Comment by DavertMik** [comment]
@oytuntez please join our discussion on improving cleanup of Db module here
https://github.com/Codeception/Codeception/pull/1831

**Comment by eXorus** [comment]
Hello,

I'm cleaning the old issues, I guess you already found a workaround ;)
or you can use the configuration key `initial_queries`.

Otherwise you can reopen the issue on the new repository of the module:
https://github.com/Codeception/module-db
