### ISSUE TITLE
pushToExchange doesn't allow sending a route key for topics

### ISSUE THREAD

**Issue by jistok** [Codeception/Codeception#1816]
can't send messages with routing keys - something like this would help a ton:

    public function pushToExchange($exchange, $message, $route)
    {
        $message = $message instanceof AMQPMessage
            ? $message
            : new AMQPMessage($message);
        $this->connection->channel()->basic_publish($message, $exchange, $route);
    }

**Comment by DavertMik** [comment]
Please send a pull request

**Comment by DavertMik** [comment]
merged
