### ISSUE TITLE
Codeception PhpBrowser and code for testing doesn't work on the same PC

### ISSUE THREAD

**Issue by Shkarbatov** [Codeception/Codeception#1820]
Codeception PhpBrowser and code for testing doesn't work on the same PC

my acceptance.suite.yml

    class_name: AcceptanceTester
    modules:
        enabled:
            - PhpBrowser
    AcceptanceTests#Selenium
        config:
            PhpBrowser:
                url: 'http://transfer.ll'

My TestCept.php

    $I = new AcceptanceTester($scenario);
    $I->wantTo('perform actions and see result');
    $I->amOnPage('/admin');
    $I->see('Test');

If I using another url, on another pc, it work fine, but at the same machine not work.

I use Apache and Ubuntu. In /etc/hosts I have record:

    127.0.0.1 transfer.ll

If I make ping in terminal by transfer.ll it's ok, showing ip 127.0.0.1

When I try to run tests, I receive an error:

    <div id="titles"><h1>ERROR</h1>
    <h2>The requested URL could not be retrieved</h2></div>
    <pre>Name Error: The domain name does not exist.</pre>

**Comment by zbateson** [comment]
Hi @Shkarbatov 

If you change the PhpBrowser url config to 'http://127.0.0.1', or 'http://localhost' does it work?  Unfortunately issues with /etc/hosts and networking are a bit beyond our project here :smile: it could be any number of things.

**Comment by Naktibalda** [comment]
Is isn't an issue of Codeception.

**Comment by zored** [comment]
Partially it can be solved with config:
```yaml
- PhpBrowser:
   url: https://example.com/
   curl:
       CURLOPT_RESOLVE: ['example.com:443:172.20.0.7']
```
Or `example.com:80` for `http://`.
