### ISSUE TITLE
attachFile does not work with PhantomJS

### ISSUE THREAD

**Issue by schmitzc** [Codeception/Codeception#1823]
I've tracked down the issue to this line in the WebDriver module:

```
$el->setFileDetector(new \LocalFileDetector);
```

If I remove this line, attachFile works in PhantomJS. Is this something that only works in Selenium?

**Comment by Jaironlanda** [comment]
How to fix it?

**Comment by natenolting** [comment]
@schmitzc what's the error your getting? I'm running PhantomJs also. Mine is:

```
 [Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: 'Error - incompatible type of argument(s) in call to _uploadFile(); candidates were
    _uploadFile(QString,QStringList)’

$I->attachFile({"name”:"file_field"},”image.png”)
```

**Comment by friparia** [comment]
I meet this error too. I found it a bug in [phantomjs 2.0](https://github.com/ariya/phantomjs/issues/12506), but my version is `2.0.1-development`, still have this problem

**Comment by natenolting** [comment]
@friparia I had to switch to Selenium to make file uploads work, no way around it I could see.

**Comment by friparia** [comment]
@natenolting thanks, but my test environment doesn't have graphic interface, so i find no way to install firefox or chrome..

**Comment by natenolting** [comment]
@friparia you can run Selenium headless, I set Selenium and Firefox up it inside a vagrant box with this script https://gist.github.com/natenolting/ed2bf2abfe444776aad4

**Comment by friparia** [comment]
@natenolting it works! thanks!

**Comment by natenolting** [comment]
Great!

**Comment by Naktibalda** [comment]
It was an issue of PhantomJS and it appears to be fixed in PhantomJS 2.1.0

**Comment by agarzon** [comment]
I'm running PhantomJS version 2.1.1 and the issue with codeception still existing. Not able to use attachFile.

**Comment by agarzon** [comment]
Thank you @Naktibalda .

In order to provide more info:
```
  [Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: 'Error - incompatible type of argument(s) in call to _uploadFile(); candidates were
    _uploadFile(QString,QStringList)'
```

Going back for Selenium, yes it works... but that does fix the issue with PhantomJS.

**Comment by pivulic** [comment]
I have the same problem as @natenolting and @agarzon, even after updating to 2.1.1.

**Comment by Naktibalda** [comment]
https://github.com/ariya/phantomjs/issues/13302#issuecomment-158628631
There is another suggestion to use `UselessFileDetector` instead of `LocalFileDetector`.

Could you modify [attachFile method](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/WebDriver.php#L1121) and see if it solves the issue?

**Comment by pivulic** [comment]
@Naktibalda, thanks, that solves my problem :)

**Comment by Naktibalda** [comment]
@DavertMik @zbateson 

When LocalFileDetector is used, WebDriver uploads file to remote instance of Selenium or PhantomJS,
When UselessFileDetector is used, WebDriver does not upload the file, so it only works when Selenium or PhantomJs is running on the same server as Codeception.

File upload to PhantomJS is broken, so we have to use UselessFileDetector,
but some of our users need LocalFileDetector, because they are using remote Selenium servers.

Codecetion doesn't know if remote instance is PhantomJS so we can't do something like `if (isPhantom)`.

The simplest solution I can image is  
```
if ($this->config['host'] === '127.0.0.1' || $this->config['host'] === 'localhost') {
    $el->setFileDetector(new UselessFileDetector);
} else {
    $el->setFileDetector(new LocalFileDetector);
}
```

Have you got any better ideas?

**Comment by DavertMik** [comment]
> Codecetion doesn't know if remote instance is PhantomJS so we can't do something like if (isPhantom)

Actually, we can do it like:

```
if ($this->config['browser'] == 'phantomjs')
```
I think we need to have such detection, probably there will be a need for other phantom-specific patches.

**Comment by pivulic** [comment]
Thanks @DavertMik for fixing this, but can you release a new tag, i.e. 2.1.6, where this fix is included?

**Comment by Naktibalda** [comment]
I haven't had time to test it, but I want to make a note that browser setting has no effect on phantomjs, so the users will have to set it specifically to avoid this file upload issue.

When I tested phantomjs, I ran tests with `browser: firefox`

WebDriver module documentation does not tell to set `browser: phantomjs`.
@DavertMik Please update documentation, if you think that this issue can be solved by configuration.

**Comment by paulsheldrake** [comment]
I tested what @Naktibalda suggested by change the browser to firefox and that didn't work

**Comment by DavertMik** [comment]
> Thanks @DavertMik for fixing this, but can you release a new tag, i.e. 2.1.6, where this fix is included?

Yes, that's what I'm aiming for at the moment. I will also need to update docs.

> I tested what @Naktibalda suggested by changing the browser to firefox and that didn't work

That's not what he suggested. Please get the latest release from 2.1 branch and change your browser to `phantomjs` to get a hotfix.

**Comment by DavertMik** [comment]
Updated docs, and more importantly added PhantomJS to our CI suite! https://semaphoreci.com/codeception/codeception/branches/2-1
+ Chrome tests as well )

Looks almost ready for a new release

**Comment by paulsheldrake** [comment]
@pivulic  This has been release in 2.1.6

**Comment by acidjazz** [comment]
anyone looking to do this in Laravel Dusk

```php
$file_input = $browser->driver->findElement(\Facebook\WebDriver\WebDriverBy::cssSelector('.input-image > input'));
$file_input->setFileDetector(new \Facebook\WebDriver\Remote\LocalFileDetector());
$file_input->sendKeys(__DIR__.'/images/logo.png');
```
