### ISSUE TITLE
group listener not working

### ISSUE THREAD

**Issue by litpuvn** [Codeception/Codeception#1830]
Hi,

I generate Admin group using generate:group command. This will create AdminGroup listener with event handling method: _before and _after

then i enabled it in global config codeception.yml as suggested in the doc.
Then i made a simple cest class with a test method annotated to Admin group.

When i run test, i didn't see the even handling methods invoked.

Any reason for it please? I tried to follow internal codeception code with debug but i haven't found the cause.

thanks,

-Hoang Long

**Comment by torkiljohnsen** [comment]
Seems like the same problem as I'm having: http://phptest.club/t/cest-cept-groups-and-before-after-issues/465

**Comment by eXorus** [comment]
Hello,

I can't reproduce anymore on Codeception 4.1.9.

The listeners works.
