### ISSUE TITLE
Laravel functional testing: mutators not working

### ISSUE THREAD

**Issue by lowerends** [Codeception/Codeception#1833]
When using mutators in a model for setting the value of an attribute, Codeception doesn't seem to pick them up well. Here's an example that's working fine in a browser, but not within a functional test:

````
public function setColorAttribute($value)
{
    if ( ! $this->has_specific_color)
    {
        $this->attributes['color'] = "Default";
    }
    else
    {
        $this->attributes['color'] = $value;
    }
}
````

No matter what value is sent in the POST data for ```has_specific_color```, ```$this->has_specific_color``` always returns that value that is stored in the database when running the tests. In the real world, ```$this->has_specific_color``` returns the POST value of ```has_specific_color```.

**Comment by DavertMik** [comment]
Laravel4 or Laravel5?

**Comment by lowerends** [comment]
That would be Laravel5.

**Comment by janhenkgerritsen** [comment]
Could you provide the code of your functional test and the code that is tested by this functional test? That way I can try to reproduce the problem. Now I don't have much to go on.

**Comment by janhenkgerritsen** [comment]
Closing this issue because there is no response. I also suspect this issue is not related to Codeception and the Laravel 5 module since I never ran into similar issues myself.
