### ISSUE TITLE
PostgreSQL: need column name quotes

### ISSUE THREAD

**Issue by akireikin** [Codeception/Codeception#1836]
This code does not work:
```
$I->seeInDatabase(
    'photo',
    ['order' => 5]
);
```
This code works:
```
$I->seeInDatabase(
    'photo',
    ['"order"' => 5]
);
```
It seems, that column name quotes should be implemented in Codeception's DB module at least for PostgreSQL.

**Comment by Naktibalda** [comment]
Fixed by https://github.com/Codeception/Codeception/commit/0b61557c4c2d6815e13d0581d7fbaf444ebaad0c
