### ISSUE TITLE
FYI, composer requirements

### ISSUE THREAD

**Issue by alcohol** [Codeception/Codeception#1842]
phpunit version `4.6.1` is the latest stable
codeception version `2.0.11` and `2.0.12` allow `~4.5.0` (only allows 4.5.x, so not the current stable)
codeception `2.0.10` allow phpunit `4.4.*` (self evident)
codeception `2.0.9` allow phpunit `~4.0` (allows everything from 4.x up to but not including 5.x)

Is there any reasoning behind this chaos? Or you guys just like mixing things up?

**Comment by DavertMik** [comment]
we are really restricted to PHPUnit version. Codeception highly relies on PHPUnit internals. so any minor change can break the things. And that happened when PHPUnit 4.6 appeared. So we are specifying exact version for each Codeception release to be sure new version of PHPUnit won't break things. Probably we should have updated dependencies for 2.0.12... I think we will move to 4.6 in next release 

You are right in case we need to track PHPUnit stable releases and upgrade each time new major release comes out.
