### ISSUE TITLE
Grab array values from page

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#1844]
We should have grabber that may return array methods for all matched element. Here are use cases for that.

* we could return `value` attributes from all option elements in select. 
* we have grid with data. Each line have `data-id` attribute, using this method we can receive all ids of elements

...

**Comment by zbateson** [comment]
I like it :+1: 

How about a modification to grabTextFrom and grabAttributeFrom to return an array of values if the selector matches more than one element?  It may throw off some existing code though...

**Comment by DavertMik** [comment]
Yeah, because of this I'd like to make a new method... Or maybe add some array flag.
Anyway separate methods could be better

**Comment by DavertMik** [comment]
@zbateson I think it is better to have one new method. I'm not really sure for its name. What do you say for `grabMultiple`. Can be used to grab attributes or inner text of element, depending on the second parameter:

```
$I->grabMultiple('.user'); // grab array of innertText of .user elements
$I->grabMultiple('.user', 'name'); // grab array of name attributes of .user elements
```

**Comment by zbateson** [comment]
Cool, looks good @DavertMik :)

**Comment by Naktibalda** [comment]
Please document it.

**Comment by DavertMik** [comment]
Yes!
