### ISSUE TITLE
The latest version of the JSONPath library causes issues with REST Json methods.

### ISSUE THREAD

**Issue by pmxjason** [Codeception/Codeception#1845]
Principally the `seeResponseJsonMatchesJsonPath()` method always returns true regardless of whether the json matches the path or not. 

It seems the way the JSONPath library works changed in 0.2.0 based on this issue:
https://github.com/FlowCommunications/JSONPath/issues/2

I am not sure the best way to resolve this. It is likely that a fix to make it 0.2.x compatible will cause issues with anyone running an older version of library. For the short term a good solution would be to update the REST documentation to note the problem and ensure people grab the last version which is compatible with codeception. 0.1.1

**Comment by DavertMik** [comment]
Sure we should get it fixed for 0.2.0 and use it as strict dependency for 2.0.13
