### ISSUE TITLE
haveInDatabase() does not work for PostgreSQL

### ISSUE THREAD

**Issue by akireikin** [Codeception/Codeception#1846]
I have a regular table (without prefix, with pk). It seems that:
```
SHOW KEYS FROM category WHERE Key_name = "PRIMARY"
```
called from `Codeception\Lib\Driver\Db::getPrimaryColumn()` does not work for `postgres`. As a temp workaround, we can override it in `Codeception\Lib\Driver\PostgreSql` like it is done for `Sqlite`.

Relates to #1761

**Comment by Naktibalda** [comment]
I fixed this https://github.com/Codeception/Codeception/commit/0e47c4c722c2b79a1c82f93da7e69b02356b3691#diff-829cd8f854ada40f4b26b4d531aa38dfL131
