### ISSUE TITLE
Issues in formating .txt when generating scenarios

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#1847]
I found that if you do use double quotes for surrounding a string like:

``` php
$I->waitForText("Congratulations! Joomla! is now installed.", 30);
```

When you generate a scenario you will get this:

```
I wait for text ""Congratulations! Joomla! is now installed.""," 30"
```

If you use single quotes instead:

```
$I->waitForText('Congratulations! Joomla! is now installed.', 30);
```

You will get the right expected result:

```
I wait for text 'Congratulations! Joomla! is now installed.'," 30"
```

Also If you do this:

``` php
$I->waitForText('Main Configuration', 10, 'h3');
```

you get:

```
I wait for text 'Main Configuration'," 10," 'h3'
```

to get the right output you need to remove the spaces:

```
$I->waitForText('Main Configuration',10,'h3');
```

Would it be possible to make the Humanize function smarter to avoid the addition of double quotes?

I checked the code but not sure where to start. If I get advise I could probably send a fix.

And finally, regarding formatting if you see: http://phptest.club/t/using-executeinselenium-function-in-acceptance-tests/149

you get in the console `lambda function` due to this:
https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Step.php#L58

Can we change that `lambda function` text for other thing more?

**Comment by javigomez** [comment]
Also mention that if the .txt file already exist Codeception do not overwrite it. It just does nothing. However it should overwrite the old .txt file with the new updated one.

**Comment by javigomez** [comment]
Also if you do:

```
		$I->pressKey(['id' => 'filter_search'],WebDriverKeys::ENTER);
```

you get:

![screen shot 2015-06-09 at 13 21 24](https://cloud.githubusercontent.com/assets/1375475/8056568/b640da3a-0ea9-11e5-9f04-cbbf814bc725.png)

I don't know if it has sense, but maybe we could allow this functions to get an array with an alias:

$I->pressKey(['id' => 'filter_search'],[WebDriverKeys::ENTER, 'ENTER key']);

So any method can get an array(element, aliasOfTheElement). The alias is used in the Output instead of the name. It will actually steal a responsibilty that now is at PageObjects, but it will definitely make our tests much more readable.

I imagine commands like:
```
// Test:
$I->click(['id' => 'cb0', 'first checkbox in the list']);
// or
$I->click(['id' => 'cb0', 'alias' => 'first checkbox in the list']);

// Shell output:
I click first checkbox in the list
```

Is just an idea, how does it sound @DavertMik? others?

**Comment by eXorus** [comment]
Thank you for contributing to this issue. As it has been 4 years since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please feel free to either reopen this issue or open a new one. 

The new repository is: https://github.com/Codeception/module-webdriver 

We will be more than happy to look at it again!
