### ISSUE TITLE
Rebuilding helpers on every run with parallel testing

### ISSUE THREAD

**Issue by gdscei** [Codeception/Codeception#1849]
We're trying to run our acceptance tests using parallel testing, after we have endured waiting for 30 minutes every time for a few weeks. This is great, but we are having an inconsistent issue.

When we run our parallel tests, in 1/5 times at least one of the groups we have fails immediately. The error returned is "Bus Error" and with verbose option (-vvv) it seems as such this is happening when it's rebuilding our acceptance helper class. 

So, my obvious conclusion is that two groups are trying to rebuild the helper at the same time, causing this error. Is there maybe a possibility to add an option to not rebuild the helper? We can do this manually if necessary.

**Comment by michaelestrin** [comment]
+1

Ran into this issue a while back and ended up removing the STAMP comment at the top of the generated WebGuy.php script.  This prevents the rebuild attempts (and thus, the Bus Error race condition).

**Comment by gdscei** [comment]
@michaelestrin As a temporary solution, I just override Robo's ParallelExec->run method to sleep for a little bit when it is starting a process, so that Codeception has enough time to rebuild. 
Still, not the right solution though.

**Comment by DavertMik** [comment]
I didn't encounter such issue as I run parallel tests in cloned dirs, but yes, AutoRebuild thing is hard to catch. What I can propose to run `codecept build` before the parallel processes.

I think I will add an option in Codeception 2.1 to disable AutoRebuild subscriber. If I find a clear way to do that without breaking things, I will implement it in 2.0.13

**Comment by DavertMik** [comment]
Added option `no-rebuild` in 2.0.13
