### ISSUE TITLE
c3 install in symfony2

### ISSUE THREAD

**Issue by tvogt** [Codeception/Codeception#1850]
I find it impossible to get c3 working in Symfony2.

I'm following the instructions, and I get 500 errors. Tracing them shows that it can't seem to find the codeception.yml file and it can't figure out where to write this error message to, either (because of circular dependencies - the log path is defined in the config file).

However, even if I copy the config file everywhere just to make sure it finds it, it still fails with 500 errors. It complains about bootstrap not run (it was run), or even without error messages at all.

Also because Symfony traps paths in .htaccess, the /c3/report/clear (and other) paths fail because they run through the router in Symfony, which of course doesn't know them. So it needs a seperate setup to recognize this path, which is not explained anywhere.

A better documentation on how to get it working nicely is desperately needed. Right now I'm just hacking around here and there and it's frustrating and will probably fail again the next time I look at it funny.

**Comment by raistlin** [comment]
Could you explain what are you trying? I have c3 working perfectly with instructions on https://github.com/Codeception/c3
