### ISSUE TITLE
got 0% coverage of functional case

### ISSUE THREAD

**Issue by JunelanMe** [Codeception/Codeception#1851]
I following the codeception's guide --chapter Code Coverage step by step as following
1.check the codeception.yml
coverage:
    enabled: true
    remote: true
    c3_url: 'http://forms.vagrant.foxitcloud.com/index-test.php/&#39;
    blacklist:
          include:
              - ./*
              - ../vendor/*
2.check the xdebug  ,the xdebug.remote_enable is turn on
![image](https://cloud.githubusercontent.com/assets/11918045/7109442/1929890a-e1d0-11e4-8471-73c9bd7f24c4.png)

3.check  the c3.php
following the guide on https://github.com/Codeception/c3
  a.a.install c3 Via Composer

![Uploading composer.png . . .]()

b.include c3.php in  front script, index-test.php
  

4.check the functional.suite.yml config
 coverage:
            enabled: true
            remote: true
            c3_url: 'http://forms.vagrant.foxitcloud.com/index-test.php/&#39;

5.5.then i run

 [root@testserver tests]# php codecept.phar run functional a2/LoginCest.php --coverage --coverage-html

as the pic display ,I get the 0 coverage

this is the _output directory

**Comment by JunelanMe** [comment]
![composer2](https://cloud.githubusercontent.com/assets/11918045/7109546/98dd8cb2-e1d2-11e4-8009-c869289d9807.png)
![output](https://cloud.githubusercontent.com/assets/11918045/7109544/98bec75a-e1d2-11e4-9643-1ad896be75dc.png)
![run](https://cloud.githubusercontent.com/assets/11918045/7109545/98c0c140-e1d2-11e4-9872-5c19fba9472d.png)

**Comment by JunelanMe** [comment]
I moved all the fuctional case to the acceptance suite that depends on the webdriver . then run some case that not depends on the browser(webdriver,phpbrowser), I got the nice coverage ,but when I run the case depends on the remote server, always 0% coverage.

**Comment by Naktibalda** [comment]
@JunelanMe I think that your problem was that you haven't whitelisted any files.

**Comment by JunelanMe** [comment]
@Naktibalda  , a issue quite long ago . I think it was bcz i was not so familiar with codeception then . Now I  can get the right coverage of functional case now .

**Comment by JunelanMe** [comment]
@Naktibalda  Thanks , This  issue  is really quite long  time ago . It was bcz i was not so familiar with codeception then . Now I can get the right coverage of functional case now .
