### ISSUE TITLE
Add getter for Codeception\TestCase in Scenario

### ISSUE THREAD

**Issue by sameg14** [Codeception/Codeception#1852]
In regards to the REST module.

The ```Scenario``` class has a protected property 
```php
    /**
     * @var    \Codeception\TestCase
     */
    protected $test;
```

I need a getter on this class for this property so I can run custom assertions like assertNotEmpty() etc... in a Cest test.

```php
/**
 * @return \Codeception\TestCase
 */
public function getTest()
{
    return $this->test;
}
```

**Comment by DavertMik** [comment]
I'm not sure you actually need it. What are you trying to assert? 
If you operate with responses you should add `Asserts` module and use http://codeception.com/docs/modules/REST#grabResponse method

**Comment by sameg14** [comment]
I just figured out ```Asserts``` module, sorry about the PR and thank you for taking the time to comment. I'll be sure to do more homework before making a PR and keep up the good work!
