### ISSUE TITLE
PhantomJS fails while Selenium works

### ISSUE THREAD

**Issue by drodil** [Codeception/Codeception#1855]
Hi,

I was trying to speed up acceptance tests by running them on top of PhantomJS. The tests start ok and run until there is one point in the test where a table is filled asynchronously (using jQuery) from API return values. I am trying to find the row from the table with 

```
$I->waitForElementVisible( 'td[@class="tableButton"]' );
```

but I am getting the following error from PhantomJS:

```
[ERROR - 2015-04-14T12:37:07.328Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1429015027311
```

This works OK when I run the test on top of the selenium. What could be wrong? Here is the PhantomJS capabilities:

```
[INFO  - 2015-04-14T12:35:00.211Z] Session [aa8f87f0-e2a2-11e4-8286-83d152d3ba4f] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.0.0","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
```

**Comment by Naktibalda** [comment]
The error that you got was a timeout,
try to use a longer timeout, e.g. `$I->waitForElementVisible( 'td[@class="tableButton"]', 30 );`

Please report an issue to PhantomJS:  https://github.com/ariya/phantomjs/issues
