### ISSUE TITLE
[Documentation Request] Framework Integration Guide (Laravel, Yii2, etc.)

### ISSUE THREAD

**Issue by bkuhl** [Codeception/Codeception#1857]
After doing some Googling trying to get coverage generated **while running acceptance tests** for our Laravel application it seems there's a lot of questions that at the end of the day boil down to understanding the moving parts of integrating into frameworks.  Once I've been able to get coverage generated reliably I'll submit a pull request to the **c3** docs that discusses integration there, but I haven't been able to get it working myself.

If you know of examples where people have posted working configurations/guides it may be good to start by compiling them in the project readme.

**Comment by samdark** [comment]
- https://github.com/Codeception/Codeception/issues/1611
- https://github.com/Codeception/Codeception/issues/1622
- https://github.com/Codeception/Codeception/issues/1024

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-test-overview.html
