### ISSUE TITLE
codeception custom test directory structure

### ISSUE THREAD

**Issue by mattvb91** [Codeception/Codeception#1859]
I am in the process of trying to implement codeception in a fairly large project at the moment and the default flat directory layout that codeception uses is not viable as we will have too much tests squashed into one directory.

Codeception uses the following structure:

<pre>
tests/
- _data
- _output
- _support
- acceptance
- functional
- unit
</pre>

We are trying include the tests in our mvc application structure so we could have the following:

<pre>
application/
-  controllers/
       - folder1/
            - controller1.php
            - test.php
       - folder2/
            - controller2.php
            - test.php
-  views/
      - view1/
            - view1.php
            - test.php
      - view2/
            - view2.php
            - test.php
</pre>

This way the structure makes it a bit easier to follow for us as otherwise we will end up with 1000s of tests in one folder. I am aware that we can define sub namespaces within the main codeception.yml however it still uses the same flat directory layout which we don't want to use.

What would a codeception bootstrap look like to get it to look into the top level folder and just run any test within directories below it and include it in the main runner?

**Comment by gdscei** [comment]
Matt, we are running a fairly large application here as well, and what we do is the following:

```
tests/
 - acceptance
    - controllers
        - ControllerCept.php
 - unit
    - controllers
        - ControllerTest.php
```

Basically, you leave the same directory structure as you do in the source of the application, and keep the same filename with -Cept or -Test added (depending on unit or accp tests). This works great for us and works fine with the current Codeception version.

**Comment by Naktibalda** [comment]
Tests files in codeception must have have Test, Cest or Cept suffix.

Since 2016 it is possible to have suites configured in codeception.yaml and tests path can be set to . to make Codeception scan entire directory structure for test files.

```yaml
suites:
    unit:
        path: .
paths:
    tests: .
    output: tests/_output
    support: tests/_support
    data: tests/_data
