### ISSUE TITLE
Goutte\Client vs Guzzle\Http\Client issue.

### ISSUE THREAD

**Issue by devcflynn** [Codeception/Codeception#1865]
Getting the below error when running acceptance tests on a brand new Ubuntu 14.04 LAMP environment. May be an issue with the system, but php5-curl is installed and enabled and we cannot figure out what could be the issue here. 

[ErrorException] Argument 1 passed to Goutte\Client::setClient() must be an instance of GuzzleHttp\ClientInterface, instance of Guzzle\Http\Client given, called in /var/www/[project]/vendor/codeception/codeception/src/Codeception/Module/PhpBrowser.php on line 123 .

**Comment by DavertMik** [comment]
What version do you use? 
Looks like a pretty old one because you use Goutte which was dropped in 2.0

**Comment by devcflynn** [comment]
So, I looked into it, the other developers machine had 2.0 in the composer.json file, but for some reason was not updating to 2.0, it was staying on 1.8. I managed to find the conflict and resolve and it looks like it fixed that issue. Thanks for the help!
