### ISSUE TITLE
seeResponseCodeIs() returns N/A

### ISSUE THREAD

**Issue by lukyer** [Codeception/Codeception#1867]
Hello, 
i try to use $I->seeResponseCodeIs(...) in my Acceptance test, but this call everytime ends with "N/A" response. No matter what response code is actually returned by server. I use Selenium server (2.45.0) with Chrome driver on Window 8 64b.

Could you please confirm this behaviour?

Thank you,
Lukáš S.

**Comment by DavertMik** [comment]
Selenium does not provide return code of request
