### ISSUE TITLE
acceptance tests using phantomjs: jquery is not being loaded

### ISSUE THREAD

**Issue by hgraca** [Codeception/Codeception#1868]
Hi,

Im using phantomjs to create acceptance tests, and I have a DIV that I need to click to trigger some javascript.

I tried the regular $I->click() method but it seems it only works with links and buttons.

So I need to use javascript/jquery to do it like: $I->executeJS("$('a css selector').click();"); 

However, it is giving me this error:
[UnknownServerException] Error Message => 'Can't find variable: $'

Which I assume it means the jquery is not being loaded in phantomjs.

Any idea how I can overcome this issue?

Tkx

**Comment by drmikecrowe** [comment]
Ditto

**Comment by Naktibalda** [comment]
It isn't an issue of Codeception,
I found similar issue of PhantomJS: https://github.com/ariya/phantomjs/issues/13450
