### ISSUE TITLE
Code Coverage Curly Brackets Problem

### ISSUE THREAD

**Issue by strebl** [Codeception/Codeception#1869]
Hi guys!
Maybe someone can help me.
If I run codeception with code coverage, all of my opening brackets and some of my closing brackets are counting as not covered.
![screenshot 2015-04-25 04 56 30](https://cloud.githubusercontent.com/assets/6151204/7331207/a7732118-eb07-11e4-97fe-02705dbaa673.png)

I ran it locally (phpunit 4.5.1 and 4.6.4, xdebug 2.2.5 and 2.3.2, codeception 2.0.12 and 2.0.13) and with Travis CI - same issue.

Do I miss something?

Let me know if you need more information.

Thanks!

**Comment by DavertMik** [comment]
Probably it is not an issue of Codeception, but PHPUnit CodeCoverage or xdebug.
Please try to run the similar test with latest PHPUnit only to narrow down the problem

**Comment by strebl** [comment]
I ran it on latest stable, 4.6.4. I'll try on 4.7 and 4.8 too and come back.

**Comment by strebl** [comment]
PHPUnit 4.7.x-dev - same issue.
PHPUnit 4.8.x-dev - same issue.
PHPUnit 4.8.x-dev with Code Coverage dev-master 1678cee - same issue.

**Comment by DavertMik** [comment]
Sure, there are not much changes in unstable 4.7 and 4.8 )
So do you confirm it's the issue of PHPUnit?

**Comment by strebl** [comment]
I have no idea... Tried different versions of
* xdebug
* codeception
* phpunit
* php
* code coverage
* operating system

**Comment by andruha** [comment]
It's the issue of PHP_CodeCoverage 2.0.16. With 2.0.15 all is well

**Comment by andruha** [comment]
https://github.com/sebastianbergmann/php-code-coverage/issues/326

**Comment by strebl** [comment]
@andruha Thank you very much!
I can confirm, the issue belongs to PHP_CodeCoverage.
Just downgraded to 2.0.15 and all works fine now.
