### ISSUE TITLE
Missing font on version 2.0.13

### ISSUE THREAD

**Issue by sas05** [Codeception/Codeception#1874]
failed to open stream: phar error: "vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/Template/fonts/glyphicons-halflings-regular.woff2" is not a file in phar

still having the same problem Codeception version 2.0.13

https://github.com/Codeception/Codeception/issues/931

**Comment by DavertMik** [comment]
Good point. Looks like it is related to update to PHPUnit 4.6. 
Will try to rebuild and publish new phar ASAP
