### ISSUE TITLE
seeRecord not working

### ISSUE THREAD

**Issue by rpg999** [Codeception/Codeception#1875]
I wrote a simple code for testing my crud module. When i try to check if the record has been added to the Database , its fail, even though after adding new record and redirecting to the list i called function see() and it works fine. Here is my code below:

$test_title = 'RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy';

$I->click('Add');
$I->fillField('Title', $test_title);
$I->click('Save');

// If i remove this part, the test will return green
$I->seeRecord('tips', [
    'title_tip' => $test_title 
]);

$I->seeInCurrentUrl('/tips');
$I->see($test_title);

**Comment by DavertMik** [comment]
Which module do you use?

**Comment by rpg999** [comment]
I use Filesystem, FunctionalHelper, Laravel4, Asserts

**Comment by rpg999** [comment]
I user Rapyd( http://www.rapyd.com/) for creating crud, cant it be the reason why the test doesn't work ?

**Comment by DavertMik** [comment]
Please attach output of failing test and we will try to help you

**Comment by rpg999** [comment]
```
{
    "event": "suiteStart",
    "suite": "functional",
    "tests": 1
}{
    "event": "testStart",
    "suite": "functional",
    "test": "Want to add new tip (AddTipCept)"
}{
    "event": "test",
    "suite": "functional",
    "test": "Want to add new tip (AddTipCept)",
    "status": "fail",
    "time": 0.4919261932373,
    "trace": [
        {
            "function": "seeRecord",
            "class": "Codeception\\Module\\Laravel4",
            "type": "->",
            "args": [
                "tips",
                {
                    "title_tip": "RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy"
                }
            ]
        },
        {
            "file": "\/home\/huy\/www\/script_sales.home\/tests\/_support\/_generated\/FunctionalTesterActions.php",
            "line": 791,
            "function": "runStep",
            "class": "Codeception\\Scenario",
            "type": "->",
            "args": [
                {
                    "executed": true
                }
            ]
        },
        {
            "file": "\/home\/huy\/www\/script_sales.home\/tests\/functional\/Tip\/AddTipCept.php",
            "line": 21,
            "function": "seeRecord",
            "class": "FunctionalTester",
            "type": "->",
            "args": [
                "tips",
                {
                    "title_tip": "RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy"
                }
            ]
        }
    ],
    "message": "Couldn't find tips with {\"title_tip\":\"RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy\"}",
    "output": ""
}
```

Here is the output

**Comment by rpg999** [comment]
```
Scenario:
* As a An admin
* I login to backend 

  [Response] 200
  [Page] http://localhost/login
  [Cookies] []
  [Headers] {"cache-control":["no-cache"],"date":["Mon, 27 Apr 2015 20:37:46 GMT"],"content-type":["text/html; charset=UTF-8"]}
  [Uri] http://localhost/login
  [POST] {"email":"admin@admin.ru","password":"111111"}
  [Response] 200
  [Page] http://localhost
  [Cookies] []
  [Headers] {"cache-control":["no-cache"],"date":["Mon, 27 Apr 2015 20:37:46 GMT"],"content-type":["text/html; charset=UTF-8"]}
* I click "Подсказки"
  [Response] 200
  [Page] http://localhost/tips
  [Cookies] []
  [Headers] {"cache-control":["no-cache"],"date":["Mon, 27 Apr 2015 20:37:46 GMT"],"content-type":["text/html; charset=UTF-8"]}
* I see in current url "/tips"
* I click "Добавить"
  [Response] 200
  [Page] http://localhost/tips/edit
  [Cookies] []
  [Headers] {"cache-control":["no-cache"],"date":["Mon, 27 Apr 2015 20:37:46 GMT"],"content-type":["text/html; charset=UTF-8"]}
* I fill field "Название","RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy"
* I click "Сохранить"
  [Uri] http://localhost/tips/edit?insert1=1
  [POST] {"_token":"","title_tip":"RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy","save":"1"}
  [Response] 200
  [Page] http://localhost/tips/edit?insert1=1
  [Cookies] []
  [Headers] {"cache-control":["no-cache"],"date":["Mon, 27 Apr 2015 20:37:46 GMT"],"content-type":["text/html; charset=UTF-8"]}
* I see in current url "/tips"
* I see "RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy"
* I see record "tips",{"title_tip":"RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy"}
 FAIL 
```

А это дебаг, as you can see , i see the entry when i was redirected back to the list, but i dont see it in my DB.

**Comment by DavertMik** [comment]
Ok, can you track if record was indeed saved in database? 
Please add `cleanup: false` to module configuration

```
modules:
    enabled: [Laravel4]
    config:
        Laravel4:
            cleanup: false
```

In this case data will be kept in database after test run. You can review the "tips" table and check that record is actually there or not.

**Comment by rpg999** [comment]
It seems to be that there is no record has been added to the DB, but why ?

**Comment by DavertMik** [comment]
I think you can enable debugger, insert a breakpoint and run this test step-by-step to see why the latest step is not saving anything to Db.

**Comment by rpg999** [comment]
if i use haveInDatabase , the entry will be saved correctly.

**Comment by janhenkgerritsen** [comment]
If you call `haveInDatabase` the test will add the record you specify to the database, so that's not the method you want to use.

As for the failing `seeRecord` call, are you sure you are using the correct database table name and attribute names?

Could you maybe provide some code samples of code that should run for this test? For example the controller method, the view, etc?

**Comment by rpg999** [comment]
Thank you , i know that `haveInDatabase` is not what i need . I do have 2 database, 1 for testing, another one for development. When i call `haveInDatabase` the entry will be added to the testing one.
What confuse me is that when i call funtion `$I->see()` , it return true, but right after that i call `seeRecord` and it fail.

Here is my code from controller, I use rapyd (rapyd.com) for creating crud:

```
public function anyEdit()
    {
        $id_entry = Input::get('modify');
        if ($id_entry)
        {
            $edit = DataEdit::source(Tip::findOrFail($id_entry));
        }
        else
        {
            $edit = DataEdit::source(new Tip);
        }
        $edit->link("tips", "Вернуться в списку", "TR")->back();

        $edit->add('title_tip', 'Название', 'text')->rule('required');

        return $edit->view('backend.tips.form', compact('edit'));
    }
```

After clicking `Save`, i make echo and here is what i receive

```
Array
(
    [_token] => 
    [title_tip] => RU2I2XyusNGK7ZAZ27hfMqISxku9F1gy
    [save] => 1
    [] => Сохранить
    [insert1] => 1
)
```

**Comment by janhenkgerritsen** [comment]
I am not familiar with Rapyd. But from your controller code it seems like you are passing a DataEdit object to your view. It is possible that the new value is set in this object, but not yet stored in the database, and that will make your `see` call work and your `seeRecord` call fail. Because I don't see a call to actually store the data to the database. But maybe this happens elsewhere with Rapyd?

**Comment by rpg999** [comment]
I think that Rapyd cause nothing , because when i try to create new entry manually, everything works.
The issue repeats even if i use pure Laravel functions for crud.

**Comment by janhenkgerritsen** [comment]
I am not sure if I understand you correctly. But are you saying you think this is an issue with Rapyd, because if you actually create a new entry manually it works as expected? And what do you mean with pure Laravel functions?

FYI, I have to leave now, but I try to come back to this issue later today.

**Comment by rpg999** [comment]
Sorry for my bad english. I think that this is an issue with Rapyd. 
I wrote a crud with only php , without any js and the test works like a charm. So i suppose that the problem is ajax request that Rapyd send to the server, the test can't handle it . 

Can you tell me please , what i have to do to test modules with JS ? 

Thank you.

**Comment by janhenkgerritsen** [comment]
You can use a testing tool like Selenium which supports Javascript. If you Google for it I am sure you can work it out :)
