### ISSUE TITLE
Update to 2.0.13 broke redirects in Wordpress

### ISSUE THREAD

**Issue by ryandury** [Codeception/Codeception#1877]
Following steps worked in  2.0.12, but it is now broken:

$I->amOnPage('/wp-admin');
        $I->fillField('#user_login', 'admin');
        $I->fillField('#user_pass', 'admin');
        $I->click('#wp-submit');
        $I->see('Dashboard');

**Comment by zbateson** [comment]
Hi @ryandury 

Is that using the PhpBrowser module?  What line does it fail on, and with what message?  If you revert to 2.0.12 does it still work now?

**Comment by ryandury** [comment]
Yes, using PhpBrowser --  It fails on $I->see('Dashboard');  -- The log file shows that it returns to the login page.   Reverting to 2.0.12 works

**Comment by zbateson** [comment]
There has been some work done in that area to bring together ``` $I->submitForm ``` and ``` $I->fillField ``` functionality that probably broke it.  I'll have a look, thanks for the report.

**Comment by zbateson** [comment]
Hi @ryandury - I've not been able to reproduce this in either 2.0.13 or 'current'.  Could you run the test with ```--debug``` on both 2.0.12 and 2.0.13 and post them here?

Also, how are you running codeception? (from phar, globally installed with composer, or 'vendor' install for a project?) and have you updated codeception's dependencies?

**Comment by daniel-mc** [comment]
This might be related to yiisoft/yii2#8288. The click function is broken in these tests when using 2.0.13.

**Comment by xt99** [comment]
I think this bug is also related to the next case. 

Having HTML code:
```html
<input name="BannersBanner[title]" id="BannersBanner_title" type="text" value="FunctionalTesterBanner">
```

I grab value from this field : 
```php
$op = $I->grabValueFrom('#BannersBanner_title');
var_dump($op);
```

Output is : 
```
string(22) "FunctionalTesterBanner"
```

When trying to see this value in this field:
```php
$I->seeInField('#BannersBanner_title', 'FunctionalTesterBanner');
```

There is an error:
```
Couldn't see in field "//input[@name='BannersBanner[title]']","FunctionalTesterBanner":
Failed testing for 'FunctionalTesterBanner' in BannersBanner[title]'s value:
Failed asserting that an array contains 'FunctionalTesterBanner'.
```

Next code produces the same error:
```php
$I->seeInField('#BannersBanner_title', $I->grabValueFrom('#BannersBanner_title'));
```

In `2.0.12` all works as expected.

**Comment by zbateson** [comment]
This may have been fixed by https://github.com/Codeception/Codeception/commit/500dd6eae456cdcbd73f33152b1fb52cfd00a6b5

Can you confirm if this is still an issue?

Thank you

**Comment by zbateson** [comment]
Closing pending more info.
