### ISSUE TITLE
Empty password field

### ISSUE THREAD

**Issue by montogeek** [Codeception/Codeception#1879]
Hi!

I am trying to integrate Travis CI in my project, according to [Travis CI MySQL Database documentation](http://docs.travis-ci.com/user/database-setup/#MySQL) you need to setup an empty password.
I have already tried with a empty string (`''`), null value (`null`), even remove completely the field from the configuration.

How can I do this?

https://gist.github.com/montogeek/0356837ce62a745da7b7

Thanks!

**Comment by DavertMik** [comment]
Null or empty value should work. According to official twitter of Travis there were some issues recently with MySql setup. Maybe that's the problem?

**Comment by javigomez** [comment]
Yup, today is a bad day to start with Travis. 
We use Travis often, and since today there are issues. But all the rest of the days this have worked to us: https://github.com/redCOMPONENT-COM/redCORE/blob/develop/tests/acceptance.suite.dist.yml#L33-L34

https://github.com/redCOMPONENT-COM/redCORE/blob/develop/.travis.yml#L39

**Comment by DavertMik** [comment]
Yeah, my yesterday builds failed for some mystical reasons as well (

**Comment by montogeek** [comment]
Thanks! They published a status update about rollback https://www.traviscistatus.com/incidents/h91j8ft0qs2l

**Comment by montogeek** [comment]
I am still getting the same errors, with `null` or an emtpy `''`.

**Comment by montogeek** [comment]
Solved, it just remembered that Laravel4 module set the environment to testing, and I created a different environment only for travis.
Just adding
```yaml
Laravel4:
                    environment: travis
```

To the travis environment on the functional.suite.yml solved it.

Thanks!
