### ISSUE TITLE
phpBrowser selectOption/seeOptionIsSelected not working correctly

### ISSUE THREAD

**Issue by alexwhitman** [Codeception/Codeception#1889]
With a simple html page:
```html
<!doctype html>
<html>
	<head>
		<title>Select Test</title>
	</head>
	<body>
		<form method="get" action="/test">
			<input type="radio" name="simple-radio-input" value="1" />
			<input type="radio" name="simple-radio-input" value="2" />
			<input type="submit" value="submit" />
		</form>
	</body>
</html>
```
The following test fails at the `seeOptionIsSelected` step:
```php
    public function testSimpleRadio(WebGuy $I)
    {
        $I->wantTo('get this thing working');
        $I->amOnPage('resources/index.html');
        $I->seeElement('input[name="simple-radio-input"]');
        $I->selectOption('input[name="simple-radio-input"]', 2);
        $I->seeOptionIsSelected('input[name="simple-radio-input"]', 2);
    }
```
Also, if I remove the `seeOptionIsSelected` step and instead submit the form, no value for `simple-radio-input` is submitted.

**Comment by zbateson** [comment]
Hi @alexwhitman 

What version of Codeception are you using for this?  ```selectOption``` is working for me in 2.0.13.  Also could you try ```seeInField``` instead of ```seeOptionIsSelected```?  ```seeOptionIsSelected``` only checks the DOM value, I don't think it'll work for a value you set if I recall correctly... should probably be changed or possibly be removed entirely since ```seeInField``` does exactly that.

**Comment by alexwhitman** [comment]
@zbateson I'm using 2.0.13.  Using `seeInField` instead of `seeOptionIsSelected` works.  It might be worth adding some documentation saying that `seeOptionIsSelected` works on the DOM but `seeInField` works on modified forms.

This has led me on to another possible bug but I'll put together a test case and create a new issue.
