### ISSUE TITLE
Class 'Prophecy\Prophet' not found in phar

### ISSUE THREAD

**Issue by CDaigneaux** [Codeception/Codeception#1890]
When I use $this->prophesize, I have this error:
```
PHP Fatal error:  Class 'Prophecy\Prophet' not found in phar://[...]/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php
```
In RoboFile.php I found this:
```
->exclude('phpspec')
```
To fix it I commented this line and rebuilded the phar then it works.
Is it necessary to exclude this directory as Prophecy can be useful in some tests.

**Comment by DavertMik** [comment]
There is file limit in phar when phar can't be compressed. We are trying to include everything needed, and remove less used things. Prophecy is not mentioned in our documentation. 

In your case you can install codeception and prophecy via composer
