### ISSUE TITLE
Date at site front page

### ISSUE THREAD

**Issue by sergeyklay** [Codeception/Codeception#1892]
![selection_042](https://cloud.githubusercontent.com/assets/1256298/7430226/549f9e38-f018-11e4-9980-5a0c7bcbe219.png)

**Comment by zbateson** [comment]
LOL :) I believe it's intentional.

**Comment by sergeyklay** [comment]
Rly? ;)

**Comment by zbateson** [comment]
Yeah, it's even HTML encoded :P https://github.com/Codeception/codeception.github.com/blob/master/_layouts/bootstrap.html#L185 @DavertMik wins he he

**Comment by sergeyklay** [comment]
Oops :smiley_cat:

**Comment by sergeyklay** [comment]
@DavertMik :+1:
