### ISSUE TITLE
WebDrive, Chrome and HTTP Basic Auth

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#1898]
Hi

I have, by default configuration for PhantomJS for my functional tests, using the following:

`phantomjs.page.customHeaders.Authorization: "Basic base64_encoded_user_password_here"`

This works, but I also have configuration where I can run my tests in Chrome / Firefox etc, using the the following syntax

    env:
        chrome:
             modules:
                config:
                    WebDriver:
                        url: 'https://my.url.com'
                        browser: 'chrome'
                        port: 4444
                        wait: 0
                        restart: true

I'd like, in this config to be able to pass the HTTP Auth username and password, rather than entering it manually each time a functional test runs

Is this even possible as I cannot find any documentation for it.

Thanks

**Comment by zbateson** [comment]
Hi @craigwillis85,

I've not used PhantomJS unfortunately, so I'm not sure if there's a native way to configure that (I wouldn't think so though)... however you could certainly create your own Helper extending WebDriver with a hook to authenticate in _before.  See http://codeception.com/docs/03-ModulesAndHelpers#Hooks

**Comment by craigwillis85** [comment]
@zbateson This is an issue with WebDriver in relation to Chrome/Firefox etc

PhantomJS uses the `phantomjs.page.customHeaders.Authorization` config to pass in the HTTP Basic Auth, but it seems there is no way, when using Chrome (i.e. Selenium/browser via WebDriver) to use HTTP Basic Auth.

I'll see about extending WebDriver to include the basic auth details

**Comment by mkudenko** [comment]
Are there any updates on that?

I could get chrome to work with basic auth on the build server by setting the URL to `http://username:password@testing-domain.com`, but sometimes it fails in the middle of the session, because the authorization dialog pops up. That also happens when manually testing in a GUI browser.
