### ISSUE TITLE
Testing Modal Windows Codeception

### ISSUE THREAD

**Issue by tiagoleal25** [Codeception/Codeception#1900]
i'm using modal forms module to call webforms on a website builded using Drupal. Some days ago i had started to build my tests stack (for now, just acceptance tests). I started with codeception and, for now, PhpBrowser and MailCatcher modules are enough. On my website i have some popup forms and i want test his content. As we can see on the official documentation, PhpBrowser doesn't support modal forms, http://codeception.com/docs/04-AcceptanceTests. I had tried Webdriver too but this module just provide support for native javascript popup windows, not modal windows as we can read here, http://codeception.com/docs/modules/WebDriver.

It's possible to test this modal windows's content, there is some module to do that?

**Comment by zbateson** [comment]
Hello,

It is true that elements created in JavaScript wouldn't show but you may still be in luck depending on how your form/page are built... if the form is on the page but merely hidden with CSS you may be good to go... if the form is loaded dynamically from a separate HTML page you may be able to test it that way.

If the form is completely built in JS with a JS string of HTML elements or using createElement, then yes, you wouldn't be able to test the form as easily.

Although I haven't specifically tried I don't see why WebDriver would have any issues testing a form in a modal js/CSS "window".  If you trigger the JS that shows the form you should be able to work with it in your tests as far as I'm aware :)

Good luck!

**Comment by tiagoleal25** [comment]
Hi @zbateson, first thank you for you answer.

The form is built completely in javascript. I started use WebDriver module, but after installation i read the documentation one more time and i discovered that and then, i had tried get some help. For those reasons i asked if there is any other available module to handle that or if i have to move to an alternative framework and not codeception.

Best regards!

**Comment by zbateson** [comment]
No problem @tiagoleal25 - yeah, give WebDriver a try... the only thing that shouldn't work is 'acceptPopup' for use with a JavaScript/CSS-based "modal window."  (that function is specifically for use with actual modal window popups like prompt, etc...)

With WebDriver/Selenium, a browser window is opened for your tests.  So long as you can trigger the JavaScript through an action on the page with Codeception and the form is displayed, you should be able to then submit that form.  I haven't used PhantomJs though, so I can't help with that.

I didn't notice anything else in the documentation referring to modal windows - was that the bit that concerned you, under acceptPopup?

**Comment by tiagoleal25** [comment]
It could be my approach that was not properly. On the documention appear two mentions at modal windows. 
On the PhpBrowser module, that says: "you can't work with JavaScript interactions: modal windows, datepickers, etc."

And on WebDriver module says that acceptPopup fuction supports native popup window and not modal window.

**Comment by zbateson** [comment]
Okay - yeah, you should be good to go then :)

**Comment by tiagoleal25** [comment]
Hi @zbateson , i'm sorry to open the question again.

This is the situation:

The referred modal window appears when a button is clicked. This form is obtained after a post request (yes it's a post request, don't ask why because it wasn't me that did it :) ). When the form is submitted, it's performed other post request. When a i was reading the PhpBrowser module documentation, i saw that we could perform ajax callbacks and perform http requests. 
So, i thought that, getting the form with the first "post", fill and submit it, this modal window could be tested. 
The problem is that, after the first request, the all html and javascript code of the modal window appears on the page but encoded.
Do you know why this happen?

Best reggards

**Comment by zbateson** [comment]
Hi @tiagoleal25 

Unfortunately I don't know why your form returns encoded data... I would assume because that's how the server is built to respond :smile:
