### ISSUE TITLE
Bearer Authenticated multiple times

### ISSUE THREAD

**Issue by Squeezya** [Codeception/Codeception#1902]
So i am having this issue, i need to authenticate a USER 1 to make ACTION 1 and then authenticate USER 2 to make ACTION 2. But when i execute:
$I->amBearerAuthenticated($token); 
with the token of USER 2 it assumes i am with USER 1, although the token is different. If i separete the test in 2 it will work but then ACTION 1 will not be persisted. 
I think this is an issue, if not forgive me :P

**Comment by Squeezya** [comment]
So I forgot to tell it here but i think i found the issue but i'm not quite sure yet. The problem is that when i loggin the amBearerAuthenticated function push an array "headers" with the values i passed in but there is no way to remove/clear that array. Therefore when i add 2 times the header "Authorization" i think both will be kept and the module will only use the first or last...
there should be a way to clear those headers like this:
$I->clearAuthorizationHeaders(); 
$I->amBearerAuthenticated($token);

**Comment by reksc** [comment]
Assuming that in your case it's absolutely reasonable to test two authenticated users doing two requests to different actions in a single cept :), you can easily add the requested method via helper.

Just place it in a helper class which you included in your ``*.suite.yml`` file.

```php
public function clearAuthorizationHeaders()
{
    if(isset($this->getModule('REST')->headers['Authorization'])) {
         unset($this->getModule('REST')->headers['Authorization']);
    }
}
```

**Comment by Squeezya** [comment]
Well i think its necessary because the DB resets at each test and i need USER1 to make an action before the USER2 make his action. I resolved another way. I change user permissions in the test and do it...
I could do like in other tests. I made a db:seed for tests with some actions made so i can make tests not depending on other actions. But i ddnt had the seed before and the migrations are changing still, making it difficult to mantain a seed for production and another for tests

**Comment by Naktibalda** [comment]
@Squeezya Could you show the test code which fails.

I have tried to reproduce your issue with this code, but failed.
```
        $I->amBearerAuthenticated('token 1');
        $I->amBearerAuthenticated('token 2');
```

https://github.com/Codeception/Codeception/blob/6f30eeb1032cff54ffcf99a87b01d8d6c839450b/src/Codeception/Module/REST.php#L275
```
    public function amBearerAuthenticated($accessToken)
    {
        $this->haveHttpHeader('Authorization', 'Bearer ' . $accessToken);
    }

    public function haveHttpHeader($name, $value)
    {
        $this->headers[$name] = $value;
    }
```

It sets header by name so REST module can't send 2 headers with the same name.

**Comment by callistino** [comment]
I'm having the same issue with headers being reused. If I make a request, the headers never get cleared for future requests in the same Cest file.

Example:

```
    public function testPost(ApiTester $I)
    {
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->haveHttpHeader('X-Api-Key', 'SomeKey');
        $I->haveHttpHeader('X-Signature', 'SomeSignature');
        $I->haveHttpHeader('X-Timestamp', time());
        $I->sendPOST('/session');
        $I->seeResponseCodeIs(HttpCode::CREATED);

        // save session
        $this->idSession = ltrim($I->grabHttpHeader('Location'), '/session/');
    }

    public function testGet(ApiTester $I)
    {
        // Do not set any headers.
        //$I->haveHttpHeader('Content-Type', 'application/json');
        //$I->haveHttpHeader('X-Api-Key', 'SomeKey');
        //$I->haveHttpHeader('X-Signature', 'NewSignature');
        //$I->haveHttpHeader('X-Timestamp', time());
        $I->sendGET('/session', ['id_session' => $this->idSession]);
        $I->seeResponseCodeIs(HttpCode::OK);
    }
```

I run my tests with `codecept run -vvv` and this is what I get:

```
SessionCest: Test post
Signature: SessionCest:testPost
Test: tests/api/SessionCest.php:testPost
Scenario --
I have http header "Content-Type","application/json"
 I have http header "X-Api-Key","SomeKey"
 I have http header "X-Signature","SomeSignature"
 I have http header "X-Timestamp",1470348106
 I send post "/session"
  [Request] POST http://localhost/session
  [Request Headers] {"Content-Type":"application/json","X-Timestamp":1470348106,"X-Api-Key":"SomeKey","X-Signature":"SomeSignature"}
  [Page] http://localhost/session
  [Response] 201
  [Request Cookies] []
  [Response Headers] {... "Location":["/session/sessionkey"], ... }
  [Response] {...}
 I see response code is 201
 I grab http header "Location"

SessionCest: Test get
Signature: SessionCest:testGet
Test: tests/api/SessionCest.php:testGet
Scenario --
 I send get "/session",{"id_session":"sessionkey"}
  [Request] GET http://localhost/session?id_session=sessionkey
  [Request Headers] {"Content-Type":"application/json","X-Timestamp":1470348102,"X-Api-Key":"SomeKey","X-Signature":"SomeSignature"}
  [Page] http://localhost/session?id_session=sessionkey
  [Response] 401
  [Request Cookies] []
  [Response Headers] {...}
  [Response] {...l}
 I see response code is 200
 FAIL
```

As you can see, the headers for the `GET` request are the same that were sent with the previous `POST` request even when not setting any headers. Of course, there are workarounds like clearing the headers for every test but it seems very counter productive.

**Comment by Naktibalda** [comment]
@callistino I agree that not clearing headers between tests is a bug.
I will investigate it later.

Which module (PhpBrowser, WebDriver, specific framework module) are you using in your tests?

**Comment by callistino** [comment]
@Naktibalda thanks for taking a look. 

I started from the guide here http://codeception.com/docs/10-WebServices with minor additions to my `api.suite.yml`:

```
class_name: ApiTester
modules:
    enabled:
        - Helper\Api
        - Asserts
        - Db:
        - REST:
            url: http://localhost
            depends: PhpBrowser
```

**Comment by Naktibalda** [comment]
@callistino I have tried to reproduced your issue and failed.
Request headers do not persist between test methods in Cest file.

You should not be using ltrim to remove a prefix of the string,
the result of `ltrim("/session/sessionkey", "/session/")` is "key"

**Comment by callistino** [comment]
You are right about the ltrim, the key is not actually 'sessionKey' but a generated session token I was just trying to make it more readable. 

Thank you for your time, I will keep investigating to figure out the issue with my setup. Although without much testing, I can almost see the issue now. It must be from the `_before()` method where I'm authenticating a user before every test. The residual headers may come from there.
