### ISSUE TITLE
submitForm is valid even when field does not exist

### ISSUE THREAD

**Issue by montogeek** [Codeception/Codeception#1904]
Hi!

I am using submitForm, like this:
```php
$faker = Faker\Factory::create('es_ES');

        $usuario = array(
            'nombreddd' => $faker->firstName,
            'apelldddido' => $faker->lastName,
            'cedddddula' => $faker->numberBetween(30000000, 1119000000),
            'emadddil' => $faker->email,
            'direcdddcion' => $faker->address,
            'telefddddono' => $faker->numerify('##########')
        );

$I->submitForm('#registro', $usuario, 'Registrarme');
```

It _correctly_ submit the form, but shouldn't because those fields does not exist.

**Comment by zbateson** [comment]
Hi @montogeek,

Yes, that's intentional - consider fields that aren't immediately available on a page but shown via JS for instance.  If you want to test for field existence or test/fill each field you can use ```fillField``` and ```selectOption```

**Comment by montogeek** [comment]
Thank you! It would be great to have a fourth option to check if the input really exist on the page.

**Comment by zbateson** [comment]
Feel free to submit a pull request :smile: I would recommend another function though perhaps instead of building more into submitForm - submitFormFields or something.  All it would need to do is loop over the passed array before calling submitForm.  I may get to it at some point.

**Comment by montogeek** [comment]
I just used Laravel4 module method `seeInFormFields` with the same results, there is not values in the input but the method returns true.
Why?

Should I use `seeInField`?

**Comment by montogeek** [comment]
I tried with `seeInField` and it still returns true. I manually tried in the browser and verify that inputs has no values.

**Comment by montogeek** [comment]
This is just weird:

```php
$I->click('Registrarme');
//        $I->amOnPage('/registro');
        $I->seeSessionHasErrors();
        foreach ($usuario as $dato => $valor) {
            $I->seeInField($dato, $valor);
        }
        $I->seeOptionIsSelected('programa_id', $programa);
        $I->see('Hay errores en tus datos. Corrigelos.');
```

If I remove/comment ` $I->amOnPage('/registro');`, ` $I->seeInField` returns `true`, even when the data is not there!!

Adding ` $I->amOnPage('/registro');` method make ` $I->seeInField` fails, as should it do.

Why?

**Comment by zbateson** [comment]
Hi @montogeek 

Sounds like a mystery to me - did you figure it out?  What page output do you get without the $I->amOnPage?  Perhaps something isn't initialized correctly...

May be related to Laravel4 in this case I'm not sure.

**Comment by montogeek** [comment]
Not, I used `$I->amOnPage` and it's working
