### ISSUE TITLE
Should cleanup option in Db module prevent all cleanup?

### ISSUE THREAD

**Issue by ashnazg** [Codeception/Codeception#1905]
I expected the Db module option of `cleanup: false` in codeception.yml to **prevent** the cleanup step that deletes all database objects (in my case, the Oracle schema drops all tables).  While I wait for my schema to be rebuilt by our DBA, looking over the code in the Db module and drivers seems to tell me that this config flag only prevents the cleanup step from running _before each test_, and that **nothing** can prevent the cleanup step from running once at the beginning, before the tests begin..  Am I seeing this correctly?  Is there no way to prevent the destroy-it-all cleanup step?

**Comment by zbateson** [comment]
Hi @ashnazg,

I'm only seeing cleanup() called in _before and _initialize in the Db module.  Setting cleanup to false should prevent it from running.

In _after, removeInserted is called.  Those are records inserted with haveInDatabase.

**Comment by ashnazg** [comment]
</headscratch>... looks like what I meant by "after each test" was actually the "before testsuite starts".  I've edited my OP to correct its wording.

It looks like the `cleanup: false` is enough to prevent the _before-each-test_ cleanup (`_before()`), but that the setting is not even considered for the _before-testsuite-begins_ (`_initialize()`) cleanup.  If `populate: true` is set, then `_initialize()` calls `cleanup()` before `loadDump()`, always.  So I think this is where my broken expectation lies.

I had set `populate: true` and `cleanup: false`, thinking that would let me be more specific in my control of populate/cleanup by putting only the exact SQL in the dump file that I wanted performed (DELETE setup SQL from previous iteration, now INSERT setup for a test run).  What resulted was that as soon as my first test started, my schema was completely empty.

Would it be an unreasonable expectation going forward to let `cleanup: false` control *all* calls to `cleanup()` in the Db module?  If so, I can put together a PR.

**Comment by zbateson** [comment]
No worries - yeah, populate expects the database to be emptied/created.  If all you need is to execute some SQL for tests, I would recommend a Helper.  The documentation at http://codeception.com/docs/modules/Db says:

```
In order to have your database populated with data you need a raw SQL dump. Just put it in tests/_data dir (by default) and specify path to it in config. Next time after database is cleared all your data will be restored from dump. Don't forget to include CREATE TABLE statements into it.
```

It's expecting 'dump' to be a full dump of your database, not a script performing a few operations.  I'm not sure creating a configuration for running an SQL script at the start would be useful to many others but I'm not against it.

**Comment by ashnazg** [comment]
Insisting that the dump.sql be a full recreation of your database is an ideal scenario, as it's an indication of a strong level of control around your process.  Thus, it's probably good to keep that and not add flexibility for less rigorous workflow.

Until I get my own workflow to that point, I can use PDO in the AcceptanceHelper::_before() hook to do the specific SQL that my current workflow needs.

Thanks for the help with understanding this functionality, @zbateson.
