### ISSUE TITLE
Switch to Interactive Console at Runtime

### ISSUE THREAD

**Issue by cjhille** [Codeception/Codeception#1911]
While debugging some longer scenarios (20 seconds+) I make frequent use of the Webdriver pauseExecution() Method to inspect the current selenium session and to analyze some broken XPath locators. Letting the test scenario run automatically is quite a lot easier than repeating the steps manually (logging in, entering data and so on).

I would love to be able to switch to the interactive console at runtime $I->switchToConsole() to try out a few assertions before rerunning the scenario, just to make sure that it works before waiting another minute to find out that it doesn't.
Also having to ability to jump into any test at any point and bounce off a few assertions would improve the test development workflow greatly. In conjunction with #1876 this would make for a really powerful debugging tool.

**Comment by Naktibalda** [comment]
This feature was implemented in 3.0 https://codeception.com/04-24-2019/codeception-3.0.html
