### ISSUE TITLE
sendPOST and urlencoded data

### ISSUE THREAD

**Issue by bmtKIA6** [Codeception/Codeception#1914]
It seems that I am unable to execute a POST with the form-urlencoded data, and my parameters
are always converted to json regardless of the content-type header

        $data = [
            'client_id' => OAuthTestSeeder::CLIENT_ID,
            'client_secret' => OAuthTestSeeder::CLIENT_SECRET,
            'grant_type'    => 'password',
            'username'      => OAuthTestSeeder::USER_EMAIL,
            'password'      => OAuthTestSeeder::USER_PASSWORD
        ];
        
        $I->wantTo('Try to obtain access token w credentials');
        $I->haveHttpHeader('Content-Type','application/x-www-form-urlencoded');
        $I->sendPOST('oauth2/access_token', $data);

* I have http header "Content-Type","application/x-www-form-urlencoded"
* I send post "oauth2/access_token",{"client_id":"test-client-id","client_secret":"test-client-secret","grant_type":"password","username":"pdpp@dssdpdpd.com","password":"pdpassword"}

  [Request headers] {"Content-Type":"application/x-www-form-urlencoded"}
  [Request] POST /v1/oauth2/access_token {"client_id":"test-client-id","client_secret":"test-client-secret","grant_type":"password","username":"pdpp@dssdpdpd.com","password":"pdpassword"}
 
and w/o the headers

  [Request headers] []
  [Request] POST /v1/oauth2/access_token {"client_id":"test-client-id","client_secret":"test-client-secret","grant_type":"password","username":"pdpp@dssdpdpd.com","password":"pdpassword"}

./vendor/bin/codecept -V
Codeception version 2.0.13

**Comment by reksc** [comment]
Headers are always converted to json when passed to debug log.

See ``Codeception/Module/REST.php``, lines 384:389

```php
if($method == 'GET') {
    $this->debugSection("Request", "$method $url");
} else {
    $this->debugSection("Request", "$method $url ".json_encode($parameters));
}
```

**Comment by Naktibalda** [comment]
Not a bug.

**Comment by shivavuppala** [comment]
Hi @Naktibalda is there a work around for this ? How can we send non json format as part of post request (x-www-form-urlencoded) ?

**Comment by Naktibalda** [comment]
@shivavuppala You want a workaround for non-bug, it was an issue of visual representation.

Don't set content-type header to application/json.

**Comment by shivavuppala** [comment]
@naktibalda my request has a header of content type as (application/x-www-form-urlencoded).

**Comment by shivavuppala** [comment]
@Naktibalda Below is the Request and Response
**Request:**
et auth = await I.sendPostRequest('https:/XXX/oktaauth/token',
  {'grant_type': "password",
  redirect_uri: "http://localhost:4200/implicit/callback",
  username: "123@test.com.au",
  password: “Password@1”,
  scope: "openid"},
  {
  Authorization: "Basic",
  "Content-Type": "application/x-www-form-urlencoded",
  "Ocp-Apim-Subscription-Key": "d40dd258808b449ba1b61f4baf510d4e"
  });

  console.log("Auth = " + auth.data.access_token);

**Response:**
[Response] Response error. Status code: 400
› [Response] {"error":"invalid_request","error_description":"The token request must specify a 'grant_type'. Valid values: [authorization_code, password, refresh_token]"}

**Comment by shivavuppala** [comment]
Where as it works fine with additional parameter type when tried using mocha
Mocha Request:
api.post('/oktaauth/token')
       .set('Authorization', 'Basic')
       .set('Ocp-Apim-Subscription-Key', subscriptionKey)
       .type('form') --- The additional parameter

**Comment by Naktibalda** [comment]
What has your code got to do with Codeception?

**Comment by shivavuppala** [comment]
Am getting error on codeceptjs for 'sendPostRequest'. Is it different from codeception?

**Comment by Naktibalda** [comment]
CodeceptJS is a different project.

https://github.com/Codeception/CodeceptJS
