### ISSUE TITLE
State of support for raw request body in framework connectors

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#1928]
REST module sends JSON encoded parameters in request body if request method is not GET and Content-Type header is set to application/json

Encoding:
https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/REST.php#L407

Client request:
https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/REST.php#L393

If $parameters is not an array(it is a JSON string now), REST sets $parameters to empty array and passes string as 6th argument ($content).

A lot of framework connectors do not expect to get parameters in request body.

Guzzle - OK,
Kohana - no support for request body,
Laravel4 - OK,
Laravel5 - OK,
Phalcon1 - OK,
SocialEngine - no support, but it uses ZF1, so I will patch it,
Symfony - OK,
Universal - no support and  there is no way to mock php://stdin for it, $HTTP_RAW_POST_DATA could provide a partial cover, but its' use is discouraged,
Yii1 - no support,
Yii2 - OK,
ZF1 - I submitted a patch for it,
ZF2 - partial support, does not match the logic of REST module.

**Comment by DavertMik** [comment]
according to your list all major frameworks support parameters. 
Kohana as SocialEngine are not actively maintained and planned to be removed in 2.1.
Yii1 is really hard to maintain and I hope most of Yii users already switched to Yii2.

I think ZF2 support is the only important here.

**Comment by Naktibalda** [comment]
One problem with my patches was that there were no tests for ZF1 module in Codeception.

Today I created a testcase https://github.com/Naktibalda/codeception-rest-testcase
and a minimal ZF1 app to run these tests in https://github.com/Naktibalda/codeception-zf1-tests

master branch of codeception-zf1-tests uses 2.0.13 version of Codeception and 3 tests fail

Make get request with custom request header (REST/GetMethodWithRequestHeaderCept)                                                                                  Fail
Make post request with raw body (REST/PostMethodWithRawBodyCept)                                                                                                   Fail
Make put request with raw body (REST/PutMethodWithRawBodyCept)                                                                                                     Fail

develop branch uses codeception with all my patches and all tests pass.

I will run these tests against ZF2 app next.

**Comment by DavertMik** [comment]
@Naktibalda Thank you, this is awesome! ZF tests will be really helpful

**Comment by Naktibalda** [comment]
https://github.com/Naktibalda/codeception-zf2-tests

I implemented the test app for ZF2 and tested it with Codeception 2.0.13,
ZF2 connector has the same request issues as ZF1 - headers and raw body(called Content in ZF2) are not passed and one additional - request uri is not set.

Functional Tests (12) ---------------------------------------------------------------------------------------------------------------------------------------------------
Make get request (REST/GetMethodCept)                                                                                                                              Fail
Make get request with query string (REST/GetMethodWithQueryStringCept)                                                                                             Ok
Make get request with custom request header (REST/GetMethodWithRequestHeaderCept)                                                                                  Fail
Make post request (REST/PostMethodCept)                                                                                                                            Ok
Make post request with form data (REST/PostMethodWithFormDataCept)                                                                                                 Ok
Make post request with query string (REST/PostMethodWithQueryStringCept)                                                                                           Ok
Make post request with raw body (REST/PostMethodWithRawBodyCept)                                                                                                   Fail
Make put request (REST/PutMethodCept)                                                                                                                              Ok
Make put request with query string (REST/PutMethodWithQueryStringCept)                                                                                             Ok
Make put request with raw body (REST/PutMethodWithRawBodyCept)                                                                                                     Ok
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

"Make get request" failed because I put a request uri assertion in it. (I will rename this test)
