### ISSUE TITLE
event that triggers before webdriver runs

### ISSUE THREAD

**Issue by PommeVerte** [Codeception/Codeception#1940]
Hey guys. I might be missing something but how would I dynamically modify the webdriver configuration before it connects to the selenium server?. I'm trying to do this via an extension but is that even possible? `suit.before` doesn't seem to work and `test.before`/ `test.start` run after.

Is it possible any other way than through an extension?

Thanks

**Comment by Naktibalda** [comment]
Webdriver can be restarted with different configuration using _restart method: https://codeception.com/docs/modules/WebDriver#_restart
