### ISSUE TITLE
Environment config file ignored

### ISSUE THREAD

**Issue by monkeymon** [Codeception/Codeception#1944]
Hi,

Not sure its the generation having issue or the Finder object filtering bug,
In Codeception/Configuration.php line 289 to 293

`
        $envFiles = Finder::create()
            ->files()
            ->name('*{.dist}.yml')
            ->in($path)
            ->depth('< 1');
`
It will only return files that suffix *.dist.yml and not *.yml. And the codeception generate:env will create file name *.yml.  

I'm renaming the environment config file after I generated it for the time being.

I'm using codeception 2.1.*

Cheers,
Chris Sim

**Comment by Dalamar** [comment]
Hi,
Have the same question.
Is it made by design or by mistake?

**Comment by Naktibalda** [comment]
Documentation says "(e.g. chrome.yml or chrome.dist.yml for environment named chrome). "

The pattern should look like this: ->name('*{,.dist}.yml')

**Comment by sascha-egerer** [comment]
thing or dist" does bot make sense. What is the benefit checking for ".dist"?

**Comment by sascha-egerer** [comment]
IMHO the pattern "anything or dist" does bot make sense. What is the benefit checking for ".dist"?
