### ISSUE TITLE
PHP Fatal error:  Call to protected method Symfony\Component\DomCrawler\Crawler::getNode() from context 'Codeception\Lib\InnerBrowser'

### ISSUE THREAD

**Issue by strietzel** [Codeception/Codeception#1951]
When I use "$I->fillField" method, I get this error:

PHP Fatal error:  Call to protected method Symfony\Component\DomCrawler\Crawler::getNode() from context 'Codeception\Lib\InnerBrowser' in ......\vendor\codeception\codeception\src\Codeception\Lib\InnerBrowser.php on line 542

But the Symfony\Component\DomCrawler\Crawler::getNode() is public!

I'm confused... how can this happen? What am I missing?

PHP 5.4.17

**Comment by zbateson** [comment]
Hmm... how are you running codeception and what version of codeception are you running?  Is it possible you upgraded and forgot to run 'composer update' or something?

**Comment by strietzel** [comment]
Sorry..for lack of information.
I'm using codeception 2.0.13.
I want to run a functional test with the symfony2 module.

Here's my functional.suite.yml:

class_name: FunctionalTester
modules:
    enabled:
        - Symfony2
#        - Doctrine2
#        - Filesystem
#        - FunctionalHelper
    config:
      Symfony2:
         app_path: '/../../../app/'
         var_path: '/../../../app/'
         environment: 'prod'

error_level: "E_ALL & ~E_STRICT & ~E_DEPRECATED"

**Comment by zbateson** [comment]
Also how are you running codeception? (phar, clone, composer) and have you run composer update if applicable?

**Comment by DavertMik** [comment]
Probably there is Symfony version mismatch. You should use Symfony > 2.4 for your application. I recommend you to install Codeception via composer to get dependencies issue solved

**Comment by Naktibalda** [comment]
@strietzel have you solved this issue?

**Comment by DavertMik** [comment]
Symfony >=2.7 is required )
I think this can be closed
