### ISSUE TITLE
c3

### ISSUE THREAD

**Issue by EagleMoor** [Codeception/Codeception#1961]
Hi! I try do codecept rest test with `--coverage` on yii2, it's not work, test is ok, but nothing in coverage file. 
Then i try create clear small project and test remote `codecept run acceptance --coverage` test.

I have 2 problem with it: 
- I can't use c3.php and don't understand how it's work.
- Coverage all time empty

Can you help me with it? 

You can use my empty project https://github.com/EagleMoor/codecept

**Comment by Ragazzo** [comment]
https://github.com/yiisoft/yii2-app-basic/tree/master/tests#code-coverage-support

**Comment by EagleMoor** [comment]
How i need setup nginx for `/c3/`?
Example nginx setting — https://github.com/EagleMoor/codecept/blob/master/nginx.conf

**Comment by Ragazzo** [comment]
all you need to do is to include `c3.php` file in your `index-test.php` as said in docs, it does not matter what server you are using

**Comment by EagleMoor** [comment]
In example i don't use yii2. Can you help me on this? In Yii2 i do as you say, not job.
