### ISSUE TITLE
issue when generating:scenarios in Cest files

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#1962]
Generating scenarios with Cest files don't work.

I have this Cest file with two methods:

![screen shot 2015-05-25 at 12 08 56](https://cloud.githubusercontent.com/assets/1375475/7795514/28719c6e-02d6-11e5-82cf-3da850e0afc2.png)

if you do:

````

$ vendor/bin/codecept generate:scenarios acceptance
* 01-Install_Weblinks generated
* Administrator_Categories generated
* Administrator_Categories generated
```

As you see the Administrator_Categories is generated twice, but the file only contains the latest method. I just overwrites the first one.

It should loop on every function and generate one file per function.

Also if you use the --single-file option:

```
vendor/bin/codecept generate:scenarios acceptance --single-file
```

It works but the resulting .txt file has only one title in capital letters. The first $I->wantToTest that finds. However it should have one title per each  $I->wantToTest.

**Comment by mkudenko** [comment]
Codeception 2.1 has that issue as well. Tests within the same file are being overwritten.

As for the single option, that works fine in 2.1 and every `$I->wantToTest` is generated in capital letters. If there's no `$I->wantToTest`, a method name is used to generate the statement.
