### ISSUE TITLE
2.1-beta -  REST module requirements are not met!

### ISSUE THREAD

**Issue by dominiquedutra** [Codeception/Codeception#1966]
Hey guys,

Updated to 2.1-beta using composer. I guess the next step would be to codecept build right?

Getting this error:

```
[Codeception\Exception\ModuleRequireException]
  REST module requirements are not met!
  This module depends on Codeception\Lib\InnerBrowser

  Example configuring PhpBrowser as backend for REST module.
  --
  modules:
      enabled: REST:
          depends: PhpBrowser
          url: http://localhost/api/
  --
  Framework modules can be used for testing of API as well.
```

Thanks :)

**Comment by DavertMik** [comment]
Did you try to follow instructions in error message? ;)
And specify dpendent module via `depends` config param

**Comment by dominiquedutra** [comment]
Davert,
Thank you very much. All I really did was follow the upgrade instructions, should have payed more attention.
I'll try again tomorrow and close this.

Thanks!

**Comment by dominiquedutra** [comment]
Davert,

Works flawless (except for all the reeed I need to get rid off hahaha).
Now if I understand correctly now to use REST module you must enable the PhpBrowser. What was used before and do you care to explain very briefly why has it changed (for curiosity sake).

Best regards.

**Comment by maxgu** [comment]
But i not use REST module,
i have same error.

my config:
    # Codeception Test Suite Configuration

    class_name: AcceptanceTester
    modules:
        enabled:
            - PhpBrowser
            - AcceptanceHelper
        config:
            PhpBrowser:
                url: 'http://localhost:8080/'

i try edit my config:
    # Codeception Test Suite Configuration
    
    class_name: AcceptanceTester
    modules:
        enabled:
            - PhpBrowser
            - AcceptanceHelper
            - REST:
                depends: PhpBrowser
                url: http://localhost:8080/
        config:
            PhpBrowser:
                url: 'http://localhost:8080/'

i have same error
P.S. in composer v2.0.15 all works

**Comment by umang-ranium** [comment]
I have the same error as well

**Comment by umang-ranium** [comment]
@DavertMik I have the same error as well
when i try to run build

**Comment by Frandango** [comment]
Hello,

Just getting started with codeception and ran into the same error message.  Updating yml didn't fix.  Can you kindly post an example of what the yml should look like for the dependency:

Codeception\Lib\InnerBrowser

Thanks!

**Comment by Naktibalda** [comment]
You can't use InnerBrowser directly, use PhpBrowser or one of framework modules.

Configuration example from ticket #2149 

```yaml
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost:9000
            proxy: localhost:8081
        - REST:
            url: http://localhost:9000
            depends: PhpBrowser
```

**Comment by Frandango** [comment]
That did it, thank you!
