### ISSUE TITLE
Improve DB dump restore performance

### ISSUE THREAD

**Issue by mnabialek** [Codeception/Codeception#1970]
The question is - are there any ways to improve restoring DB dump performance? I have almost 500 API tests (there will be more) and at the moment each test take at least 1.4s (first test takes less than 0.4s) so probably 1s for each test takes restoring DB dump. I use DB so I need to have fresh data for each test but maybe something could be done to make it much quicker

**Comment by DavertMik** [comment]
Sure, just write a helper class of your own which will execute command like this

```
mysql test_database < dump.sql
```

Db module is not best solution in case you need performance

**Comment by cdarken** [comment]
How can I make that helper run only for some tests and not for an entire suite?
