### ISSUE TITLE
WebDriver submitForm with multi-dimensional 'array' field names

### ISSUE THREAD

**Issue by zbateson** [Codeception/Codeception#1976]
On behalf of @wasmithee commented on #1802 

> The fix for this bug breaks the submitForm function for me. I have a select with the name attribute of: 'Departments[dept_name][]'. Stripping off the last '[]' causes the option to not be selected.
> 
> How do you suggest we make it so it will work for both cases?

And, with an example HTML document:

```html
<div class="row">
    <label for="Departments_dept_name" class="required">Department Name <span class="required">*</span>
    </label>
    <select size="5" multiple="multiple" name="Departments[dept_name][]" id="Departments_dept_name">
        <option value="65">BTT</option>
        <option value="68">BTT Demo2</option>
        <option value="70">Demo Companies</option>
        <option value="71">Demo Company</option>
    </select>
</div>
```html

**Comment by zbateson** [comment]
@wasmithee

Would you also be able to provide your submitForm function?  How submitForm is now used has changed to be compatible with how it's done in PhpBrowser/InnerBrowser - I suspect it's just an update to your call that's needed.

**Comment by wasmithee** [comment]
Here's the debug output for the submitForm function call:
````console
* I submit form "#content form",{
	"User[username]":"_QA_AUTO_BTTAdmin",
	"User[password]":"foobar",
	"User[resellerID]":"BTT",
	"Departments[dept_name][]":"BTT Demo2",
	"User[email]":"selenium_CreateUser_BTTAdmin@gmail.com",
	"User[status]":"Active",
	"Profile[firstname]":"First Name Text",
	"Profile[lastname]":"Last Name Text",
	"Profile[timezone_id]":"America/New_York",
	"Profile[granularityDefault]":"1.0",
	"Profile[access_level]":"BTT Admin",
	"Profile[whitelabel_id]":"BTT"
},"submitButton"
````
It is the name of the `id="Departments_dept_name"` select which is causing the issue.  It has the extra `'[]'` at the end of the name attribute which is being truncated by the `getSubmissionFormFieldName` function in `\Codeception\Module\WebDriver.php`:
````php
    protected function getSubmissionFormFieldName($name)
    {
        if (substr($name, -2) === '[]') {
            return substr($name, 0, -2);
        }
        return $name;
    }
````

**Comment by zbateson** [comment]
The reason that doesn't work anymore is because it doesn't allow submitting multiple values for the same field... e.g. a checkbox with 5 options, all named "myCheckbox[]" - the array you pass to submitForm may only contain a single value for a key with that name.

Anyway, the workaround is to use an array value for a field ending in '[]', so your submitForm would be more like:

```php
$I->submitForm('#content form', [
    "User[username]":"_QA_AUTO_BTTAdmin",
    // ...
    'Departments[dept_name]' => ['BTT Demo2'],
    // ...
]);
```

Note that this is only for numerically indexed 'array' form values where you don't want to specify the key (like User[username] or Departments[dept_name]).  This would also allow the following (but would result in a different request as it would include [0] in the POSTed value, unlike submitting multiple fields all named SomeField[]):

```php
$I->submitForm('#myform', [
    'SomeField[0]' => 'Some Value',
    'SomeField[1]' => 'Some Other Value'
]);
```

Hope that helps.  I am updating the documentation to better address this (it currently contains a mistake and is incomplete).
