### ISSUE TITLE
Colors not working in gitBash

### ISSUE THREAD

**Issue by cloudEdwards** [Codeception/Codeception#1982]
Hi, I can't get the colors working with a git bash shell.  I had them working before when I installed codeception into laravel.

But now I added a composer.phar to my testing folder, but this folder is already prebuilt with all the default codecept folders and files like codeception.yml. Maybe this is why the color isn't working. It is set to true in the yml.  But I never ran bootstrap on this build.  When I try it says, already installed in "."

using --colors option also doesn't work. Any ideas?

**Comment by dolmen** [comment]
> Hi, I can't get the colors working with a git bash shell.

Do you mean you are on Windows in a bash from msysgit?

**Comment by cloudEdwards** [comment]
Yeah it doesn't work on Windows using gitBash. But it does work running tests from inside vagrant

**Comment by carltondickson** [comment]
For others looking for a solution to this...

I downloaded Ansicon, added it to my path and ran the following in a new git-bash window

```
ansicon -p
```

As long as you have the following in codeception.yml the colors should display correctly

```
settings:
    colors: true
```

At first this wasn't a permanent change meaning I had to run the command each time I opened the window via the git bash shortcut ("C:\Program Files\Git\git-bash.exe")

I was playing around with creating a new shortcut which may have made this ansicon permanent, no idea!

```
"C:\Windows\SysWOW64\cmd.exe" /K C:\Users\carlton\Desktop\dev\ansicon_x64\ansicon.exe -p && "C:\Program Files\Git\bin\bash.exe" --login -i
```

credit: https://gist.github.com/jaugustin/6172767
