### ISSUE TITLE
Escape Print pop up in codeception

### ISSUE THREAD

**Issue by mkatuah** [Codeception/Codeception#1989]
i am using codeception in my case when i click on next BTN there is a print pop up apear and can not complite my test i try to use the below code : 
 $I->click('next');  
$I->wait('5');  
$I->cancelPopup('window.print');
  but dose not work also i try to use cancelPopup function as below :  
   1- $I->cancelPopup();  
2- $I->cancelPopup('window.print()');
    3- $I->cancelPopup('window.print'); 
 but same case can anyone tell me how can i escape the print popub ?

**Comment by Naktibalda** [comment]
> Window.print creates an OS level dialogue that no drivers should be allowed to interact with.

Drivers don't support such functionality and it isn't defined in WebDriver protocol, so there is nothing Codeception can do about it.
https://github.com/w3c/webdriver/issues/1090
