### ISSUE TITLE
[Yii2 - Connector] Enable easier App overrides on a per functional test basis

### ISSUE THREAD

**Issue by acorncom** [Codeception/Codeception#1991]
I'm trying to change app behavior for one particular functional test (to emulate app behavior when moved to a different environment and to mock a Redis connection).  I've found it pretty difficult to handle and noticed that other people are experiencing the same issues:
- https://github.com/Codeception/Codeception/issues/1342
- https://github.com/Codeception/Codeception/pull/1539
### Work-around

My solution ended up being to use a singleton object to help control app config (as follows for a Yii2 advanced template app).  Can we make this easier?

In `tests/codeception/config/backend/functional.php`, adding the below line:

``` php
    require(__DIR__ . '/config.php'),
    [
+        'bootstrap' => [
+            ['tests\codeception\backend\functional\config\ConfigHijacker', 'getInstance'],
+        ],
    ]
```

Create a `ConfigHijacker` singleton object that optionally allows for a public `callable` to be set on it.

In a specific functional test, run things as follows:

``` php
$configHijacker = ConfigHijacker::getInstance();
$configHijacker->callable = function() {
    $mock = \Mockery::mock('\yii\redis\Connection');
    $mock->shouldReceive('get')->andReturn('<html>from redis</html>');
    \Yii::$app->set('redis', $mock);
};

// now run your functional test and the above settings will apply
```

@samdark @Ragazzo @TriAnMan Any feedback on ways we could make this simpler?  If not, I'd be happy to send in a pull request with my ConfigHijacker (renamed if you want) if we want to include this as part of the functional test system.  I'd love for other folks to not have to reinvent this wheel, it's a pain! ;-)

interested in your thoughts ...

**Comment by SamMousa** [comment]
@acorncom You can now alter app settings inside a test and they will be persisted for that test only.

Note that this excludes the `request` and `response` components.

**Comment by acorncom** [comment]
@SamMousa Sweet. So I can just do a `Yii:$app->set('redis')` and it will reset to base config after the test run is over?

**Comment by SamMousa** [comment]
Yes, after every test the application will be fully reset regardless of what you do to it.
But during a single test only a few components get refreshed.

https://codeception.com/docs/modules/Yii2

**Comment by acorncom** [comment]
Thanks, I'll go ahead and close this then
