### ISSUE TITLE
Behavior in REST when POST JsonSerializable and __toString

### ISSUE THREAD

**Issue by andersonamuller** [Codeception/Codeception#1992]
Because of dcfc8e3#diff-d8e5babfee3fd0e8675337cf8ff58b50, when I post/put/patch a `JsonSerializable` object that also implements a `__toString` method passing a custom `Content-Type` in headers, the request is always sent without body.

**Comment by andersonamuller** [comment]
See PR #1993 for tests.

**Comment by Naktibalda** [comment]
I don't see anything wrong with specified commit.

Your issue is that REST module does not json_encode automatically, when content type is application/*+json, right?

**Comment by Naktibalda** [comment]
I am looking into it.

The issue with existing tests is that jsonSerialize method of class JsonSerializedItem returns a JSON string,
which is incorrect, because it should "return data which can be serialized by json_encode(), which is a value of any type other than a resource."

**Comment by andersonamuller** [comment]
No @Naktibalda, the issue is that I was relying in the fact that if you use a object that implements a `__toString` the request calls the method to use the result as body. But because the object also implements `JsonSerializable`, it does not POST at all. See this test: https://github.com/Codeception/Codeception/pull/1993/files#diff-30d550aeffc03d3e3b70dbf41db888f2R222

If the `ResourceJsonRepresentation` didn't implement the `JsonSerializable` the test would pass.

**Comment by Naktibalda** [comment]
OK, I got you.

Before the change all objects were passed to
https://github.com/Codeception/Codeception/blob/dcfc8e303b1260a9b6937448be991620d20e5a64/src/Codeception/Module/REST.php#L397
$this->client->request($method, $url, array(), $files, array(), $parameters);

It looks like an unintended behaviour, but @DavertMik change breaks backwards compatibility and should be reverted.

**Comment by andersonamuller** [comment]
Because if this change https://github.com/Codeception/Codeception/commit/dcfc8e303b1260a9b6937448be991620d20e5a64#diff-d8e5babfee3fd0e8675337cf8ff58b50R358

**Comment by Naktibalda** [comment]
Yes, just delete that code and add to your pull request.

**Comment by Naktibalda** [comment]
@DavertMik I still think that the code that you added to improve scrutinizer's score should be removed.
```php
        if ($parameters instanceof \JsonSerializable) {
            $parameters = $parameters->jsonSerialize();
        }
```
https://github.com/Codeception/Codeception/commit/dcfc8e303b1260a9b6937448be991620d20e5a64#diff-d8e5babfee3fd0e8675337cf8ff58b50R358

Improving a score is a weak motivation for such change,
it breaks backwards compatibility for some users and makes this line of code in encodeApplicationJson inaccessible.
https://github.com/Codeception/Codeception/blob/dcfc8e303b1260a9b6937448be991620d20e5a64/src/Codeception/Module/REST.php#L416
