### ISSUE TITLE
save the test result in data base 

### ISSUE THREAD

**Issue by mkatuah** [Codeception/Codeception#1995]
can i save the codeception result in database  ?

**Comment by ianldgs** [comment]
I also need something like that. Not necessarily in the database, but somehow execute the tests when code is pushed to github and save what went wrong.

**Comment by Naktibalda** [comment]
Test results can be saved in XML, TAP and JSON formats using these options:
```
--xml[=XML]                      Generate JUnit XML Log [default: "report.xml"]
--tap[=TAP]                      Generate Tap Log [default: "report.tap.log"]
--json[=JSON]                    Generate Json Log [default: "report.json"]
```
