### ISSUE TITLE
How to test jQuery template content on codeception

### ISSUE THREAD

**Issue by tiagoleal25** [Codeception/Codeception#1996]
Is it possible test content generated by jQuery template? The problem is that the browser used by codeception cannot render this content, and, with that, i cannot test this html content. 
PhpBrowser was the first "browser" used it's not possible test with it. I thought that with phantomjs this problem could be solved but i have the same problem.

Any idea?

**Comment by zbateson** [comment]
Hi @tiagoleal25,

Yes, that's correct - you'll need to use the WebDriver module instead of PhpBrowser.  WebDriver can either use a real browser (like Firefox or Chrome) or run PhantomJS.  Please check out the documentation on http://codeception.com and particularly http://codeception.com/docs/modules/WebDriver

Best of luck!

**Comment by tiagoleal25** [comment]
Hi @zbateson,

first of all, thank you for answering.

I forgot to say that i'm using vagrant, and all the tests are running inside of the virtual machine (without graphical environment). I had tried phantomjs (headless browser) and for now, jquery template html still not render by the browser. 

Do you have an idea if it's possible test this content running this tests inside of vagrant virtual machine?

Best regards!

**Comment by zbateson** [comment]
Hi @tiagoleal25 -

I'm not specifically familiar with Vagrant, but as an example we're running all our tests on Travis for commits to this project, and running with selenium headlessly.

If vagrant is just a standard VM, I can't see a reason why it can't be made to work.

**Comment by tiagoleal25** [comment]
Hi @zbateson, this question was solved with module webdriver.
Btw thanks for you help :)

Best regards.
