### ISSUE TITLE
when i use codeception for too long, i start getting this message

### ISSUE THREAD

**Issue by ghost** [Codeception/Codeception#2003]
[Thu Jul  2 14:23:34 2015] Failed to accept a client (reason: Too many open files)

**Comment by wasmithee** [comment]
Do your test(s) open files?

**Comment by OussamaDEV** [comment]
no, i just run normal acceptance tests.

**Comment by zbateson** [comment]
@OussamaDEV - could you provide some more information? e.g. OS, type of tests (unit/functional/acceptance), what you mean by "too long" (single instance running too many tests, long single test, repeatedly running codecept for a long time, something else entirely), what you're testing (files, databases code, website) and any other hints you may think would be helpful in determining what may be happening.

**Comment by OussamaDEV** [comment]
- local webdevelopment
- codeception version - 2.0.14
- laravel5 - am not using homestead
- php 5.6.9
- OS i686 3.18
- too long ~16 hour
- how i fix the issue, i stop the php server, and rerun it again, i use xdebug.
- acceptance and unit test

am using now the built-in test in laravel TestCase, for codeception i just run the command from codecept console, and everyting seems to work just fine.

suggestion from stackoverflow sayed that i should increase the number of files, but i don't want to, if an application is not closing the files properly, then ...

i don't have time to debug the problem myself, any hints will be appretiated.
