### ISSUE TITLE
Set HTTP_HOST for Laravel5 module for better error output

### ISSUE THREAD

**Issue by CristianGiordano** [Codeception/Codeception#2004]
With the introduction of the Laravel5 module, we no longer got error outputs with the correct hostname. This meant harder debugging views.

The proposed fix is to set the HTTP_HOST of the client connector. 

Pull request here #2005

**Comment by CristianGiordano** [comment]
Pull request here #2005

**Comment by janhenkgerritsen** [comment]
Fixed this issue with commit 82ee3b3ece71f357d672c0b0d47a6fa19c317d36.
