### ISSUE TITLE
I'm Getting a 500 response code in debug mode every time i run the test..

### ISSUE THREAD

**Issue by aldrin1777** [Codeception/Codeception#2011]
can you give me some guide to where to check..it seem's that the config in yml is correct.
im using laravel5 module

**Comment by janhenkgerritsen** [comment]
We can't help you without more info. Please provide at least your configuration and the output you get.

**Comment by aldrin1777** [comment]
ok thanks..
actually i was trying to use acceptance test just to see if the page is loading.

So this is my acceptance.suite.yml

class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
        - Laravel5
    config:
        PhpBrowser:
            url: 'http://myapp.app:8000'



then i create a TestAllPagesCept.php

$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');

$I->amOnPage('/dashboard');
$I->seeResponseCodeIs(200);

just a simple test if i'm on the page.

when i run it
codecept run acceptance --debug

i get

[Response] 500
[Page] http://localhost/dashboard
[Cookies] [] 
[headers]

ahh but i use 
$I->amOnUrl('http://localhost/dashboard'); which is a phpbrowser module
 it works

**Comment by janhenkgerritsen** [comment]
Are you trying to test pages on a server you have running locally? Because then you should use the Webdriver module instead of the PhpBrowser module.

**Comment by aldrin1777** [comment]
ok. ahh by the way it's a laravel project so i use a laravel module as well..

thanks..i will try it and let you know.

**Comment by aldrin1777** [comment]
ahh is it possible to get response code using webdriver....?

**Comment by janhenkgerritsen** [comment]
I am not familiar with the WebDriver module, so I don't know. I would have expected to see a method like `seeResponseCodeIs` like with the PhpBrowser module, but there isn't.

**Comment by aldrin1777** [comment]
yeah..i know this working now but what i really want is to display the response code...i hope there's a way...by the way thanks fro the help....

**Comment by OussamaDEV** [comment]
that mean that your application is failing internally, access `http://localhost/dashboard` to see the exception message.

why do you want to get the response code, its already displaying, anyhow this is a more in depth on how codeception get the response status code, just mimik this function behavior, or make it public and use it

```
    // codeception 2.0.14
    protected function getResponseStatusCode()
    {
        // depending on Symfony version
        $response = $this->client->getInternalResponse();
        if (method_exists($response, 'getStatus')) {
            return $response->getStatus();
        }
        if (method_exists($response, 'getStatusCode')) {
            return $response->getStatusCode();
        }
        return "N/A";
    }

``̀`

**Comment by aldrin1777** [comment]
yes @OussamaDEV you're right, it fails internally, 
i already getting the correct response code...
my problem now is it doens't run all the middleware functions i add in kernel.php ..

by the way..thanks for your suggestion..i'll try to mimic that in webdriver.
