### ISSUE TITLE
More symfony deprecations

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2012]
https://travis-ci.org/Codeception/Codeception/jobs/65330598

"Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.

1) GenerateStepObjectTest::testBasic

PHPUnit_Framework_Exception: "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.

#1  Codeception\Subscriber\ErrorHandler->errorHandler

#2  /home/travis/build/Codeception/Codeception/vendor/symfony/console/Helper/HelperSet.php:82

#3  /home/travis/build/Codeception/Codeception/tests/unit/Codeception/Command/GenerateStepObjectTest.php:17

#4  GenerateStepObjectTest->testBasic

---------

2) GenerateStepObjectTest::testNamespace

PHPUnit_Framework_Exception: "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.

#1  Codeception\Subscriber\ErrorHandler->errorHandler

#2  /home/travis/build/Codeception/Codeception/vendor/symfony/console/Helper/HelperSet.php:82

#3  /home/travis/build/Codeception/Codeception/tests/unit/Codeception/Command/GenerateStepObjectTest.php:34

#4  GenerateStepObjectTest->testNamespace

---------

3) GenerateStepObjectTest::testCreateInSubpath

PHPUnit_Framework_Exception: "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.

#1  Codeception\Subscriber\ErrorHandler->errorHandler

#2  /home/travis/build/Codeception/Codeception/vendor/symfony/console/Helper/HelperSet.php:82

#3  /home/travis/build/Codeception/Codeception/tests/unit/Codeception/Command/GenerateStepObjectTest.php:48

#4  GenerateStepObjectTest->testCreateInSubpath

I'm sorry for breaking 2.0 branch builds, it was caused by this pull request.
https://github.com/Codeception/Codeception/pull/2009

Please fix the tests or restore composer.lock.
I can't fix it myself today.

**Comment by Naktibalda** [comment]
I replaced DialogHelper with QuestionHelper in 3 commands, but I had no time to manually test SelfUpdate and Bootstrap, so I will not create a pull request today.

https://github.com/Naktibalda/Codeception/tree/DialogHelperDeprecation

**Comment by Naktibalda** [comment]
I tested all commands manually.

**Comment by igorsantos07** [comment]
This seems to be causing deprecation warnings even on stable releases. I've installed 2.0.14 and that happened when I tried to generate a step object.
