### ISSUE TITLE
Cannot generate multiple scenarios from one function

### ISSUE THREAD

**Issue by DanTalash** [Codeception/Codeception#2014]
I need to test the lifecycles of certain objects in my code. The objects have various properties which decide how they behave.

If I were to write tests which would cover all possible combination of object properties, and all the possible paths through the lifecycles of these objects, then I would have to write several hundred tests. I would have to hope I didn't miss any combinations, and would need to keep them updated as the system changes.

Instead I decided to write some code that would loop through the possible options, and for each one figure out what sets of API requests must be made. This functions well, and covers all possible combinations.

The issue I am having, is that now I have one scenario which has hundreds of steps, and it is difficult to identify what exactly failed without reading the request/response data.

The code is similar to the simplified version below:

``` PHP
class ObjectTestCest {
    private $types = [1,2];
    private $states = [1,2];

    public function checkObjectLifecycles(ApiTester $I) {
        foreach ($this->types as $objType) {
            foreach ($this->states as $objState) {
                $I->wantTo("Check the object lifecycle for $objType ($objState)");
                //Some generated requests and assertions.
            }
        }
    }
}
```

The problem is that multiple `wantTo()` do not generate extra scenarios, and just update the scenario text, so the text of the scenario ends up being the last `wantTo()` call.

As far as I understand, my options for overcoming this are either:
- Change my code so that it generates functions for all combinations required with the appropriate data/calls. Then, run codeception on the generated code.
- Fork codeception to add this functionality.

I would prefer to use a third option if one were available, and am open to suggestions.

**Comment by DavertMik** [comment]
Use [examples or dataproviders](http://codeception.com/docs/07-AdvancedUsage#Examples) for such cases. Added since 2.2.3
