### ISSUE TITLE
Symfony2 include problem

### ISSUE THREAD

**Issue by skillberto** [Codeception/Codeception#2016]
Hello!

I tried to figure how can I run my unit & functional tests from Symfony2 bundles, and acceptance tests from global directory, but I can't solve this.
Could you please tell me the best solution?

The old way:

```
include:
   - src/*/*Bundle
```
have looked good, but now I have to create a lot's of row for each bundle..

Or do you have a good solution?
Neither understand I the *.dist files, why they are good?
In my opinion, Configuration class should be rewritten with a polished structure.

Best regards,
Norbert

**Comment by raistlin** [comment]
Should be fixed by #2189 , could you provide feedback ?

**Comment by raistlin** [comment]
ping @skillberto

**Comment by skillberto** [comment]
Yes, I think so. #2189 fixed this issue too.
