### ISSUE TITLE
WebDriver : cannot attach multiple files with attachFile()

### ISSUE THREAD

**Issue by Gyoo** [Codeception/Codeception#2017]
Hello,

I am currently writing acceptance tests in which I need to attach multiple files to a File Selector form that has the `multiple` tag set to true.
As `$I->attachFile()` works great to attach a single file, is there a way to attach multiple files to a single file selector ? I tried these 2 things:
```
$I->attachFile('//input[@type="file"]', '1.jpg');
$I->attachFile('//input[@type="file"]', '2.jpg');
$I->attachFile('//input[@type="file"]', '3.png');
```
And
```
$files = array();
array_push($files, '1.jpg');
array_push($files, '2.jpg');
array_push($files, '3.png');
$I->attachFile('//input[@type="file"]', $files);
```
But none of them work. First snippet only selects the third element, and the second one returns an error "array to string conversion"

By the way, my version of Codeception is 2.0.14

Any solution is welcomed, thanks by advance :)

**Comment by Naktibalda** [comment]
It isn't an issue of Codeception.
Selenium does not support multiple files upload.
https://code.google.com/p/selenium/issues/detail?id=2239

**Comment by Gyoo** [comment]
I see... so there's no way at all to do that I assume ?

**Comment by kkochanski** [comment]
```
