### ISSUE TITLE
2.0.14 update breaks Laravel4 module amLoggedAs

### ISSUE THREAD

**Issue by ivanhosgood** [Codeception/Codeception#2023]
Executing the following test client code (using the Laravel4 and RESTful modules:

$I->amLoggedAs($user);
$I->sendGET($testUrl);

the associated Laravel controllers are unable to resolve the user using the code: Auth::user();
Instead NULL is returned

I can confirm this functionality works in 2.0.13 but breaks in 2.0.14

**Comment by janhenkgerritsen** [comment]
Can you show me your suite configuration? I will explain why below.

The REST module has a dependency on another module for actually carrying out requests. This should be a module that extends the InnerBrowser class. But if your suite configuration enables multiple modules that extend InnerBrowser (for example Laravel4, PhpBrowser, WebDriver, etc) you cannot know for sure which module is used by the REST module to actually make the requests. And if the requests do not use the Laravel4 module the `amLoggedAs` functionality will not work.

If your suite configuration is OK I'll have to look for some other issue.
