### ISSUE TITLE
Guzzle version conflicts

### ISSUE THREAD

**Issue by igorsantos07** [Codeception/Codeception#2030]
I've just installed Codeception in an old Symfony 2.1 project, to run some acceptance tests - so maybe we can upgrade this beast.

However, as soon as I tried to run the empty suits an error came in, related to `GuzzleHttp` and `Guzzle\Http`. As far as I can remember that's the different namespaces between Guzzle 2 and 3?

>  **[ErrorException]**
>  Argument 1 passed to Goutte\Client::setClient() must be an instance of GuzzleHttp\ClientInterface, instance of Guzzle\Http\Client given, called in /home/igorsantos/dev/myapp/vendor/codeception/codeception/src/Codeception/Module/PhpBrowser.php on line 82 and defined

**Comment by DavertMik** [comment]
We are trying migrate to Guzzle 6 and you are bringing us back to Guzzle 3 :)

Codeception not uses Goutte since version 2.0. Looks like because of low Symfony version you can't install new Codeception... :(

As far as I remember you can fix this issue by lowering Goutte version to `1.x`:

```
"fabpot/goutte": "1.*"

```

**Comment by igorsantos07** [comment]
hahaha I said "as far as I can remember". I didn't said my memory was good :))

**Comment by igorsantos07** [comment]
Changing to Goutte 1.* solved the issue. I guess that's because of old Symfony dependencies, right?
Thanks!
