### ISSUE TITLE
$scenario->env('firefox'); doesn't work

### ISSUE THREAD

**Issue by amoxyc** [Codeception/Codeception#2032]
I'm trying to use http://codeception.com/docs/07-AdvancedUsage#Environments
block "For Cept you should use $scenario->env():"
But it doesn't work for me. I saw the same problem on  phptest club.
http://phptest.club/t/environment-help-with-cept/384
Running from comand line with --env firefox works good.

**Comment by gunfrank** [comment]
Anyone please take a look at this. This issue has been present on PHPTestClub for months now.

Setting specific environment for a given Cept isn't working with setting `$scenario->env('example');`, nor with annotations `// @env example`, as suggested in the terminal output when using the first way.

> DEPRECATION: $scenario->env() is deprecated in favor of annotation: // @env

**Comment by gunfrank** [comment]
The suggested fix does not work for me.

If I change the code as suggested, and pass specific environment for a given Cept (again, tried both ways described above) no tests will be run - `No tests executed!`.

**Comment by gunfrank** [comment]
Any other suggestions?

**Comment by mightyknite** [comment]
try this: https://github.com/mightyknite/Webception/commit/c9146580ff91136609df5a0c068defb158cde753

**Comment by gunfrank** [comment]
Only the change in `App/Lib/Codeception.php` ?

**Comment by gunfrank** [comment]
I'm not using Webception. The changed files in the commit do not exist in the Codeception code base. Can you elaborate on how do I "try this"?
