### ISSUE TITLE
SelectOption cannot match option text when one of the option values is "0" (2.0.14)

### ISSUE THREAD

**Issue by onshop** [Codeception/Codeception#2033]
I have the following select:

    <select id="has_business_case" required="required" name="hasBusinessCase">
        <option value="">Select Below</option>
        <option value="1">Yes</option>
        <option value="0">No</option>
    </select>

In the test I need to select 'No':

    $I->selectOption( 'select[id=has_business_case]', 'No');

When I run the test I get:

    InvalidArgumentException: Input "hasBusinessCase" cannot take "No" as a value (possible values: , 1, 0).

I suspect the issue is in  Codeception\Lib\InnerBrowser in the matchoption method on line 711.

    if ($options->first()->attr('value')) {

Is evaluating the 0 value to false. If I change this to:

    if ( $options->first()->attr('value') !== false ) {

Then the selectOption command is successfully able to select the option.

**Comment by zbateson** [comment]
Yes, your change makes sense to me - could you submit it as a pull request? (without the spaces in the if statement as per PSR-2 specs if possible :wink: )

Thank you

**Comment by onshop** [comment]
Will do. Thanks for point out the PSR-2 use of spaces. I have been adding spaces for readability but better comply.

**Comment by onshop** [comment]
I have come across a similar problem:

    $I->selectOption( 'select[id=users]', 'Cedric');

Gives me:

    InvalidArgumentException: Input "users" cannot take "Cedric" as a value (possible values: 6, 4, 11, 13, 3, 7, 1, 10, 2, 14, 12, 9, 8, 5).
