### ISSUE TITLE
$I->see() cannot find strings containing single quotes (2.0.14)

### ISSUE THREAD

**Issue by onshop** [Codeception/Codeception#2034]
If I search for a string and that string contains a single quote then then $I->see() cannot find it:

    $I->see( "Please reset your password by clicking on the 'Forgotten your password?' link below" );

if I chop out the part of the string that contains the single quotes then it can find the string:

    $I->see( "Please reset your password by clicking on the" );

The 1.x version of Codeception could handle the single quote.

There is no issue with double quotes.

To fix the issue I got round it by editing line 1148 Codeception\Lib\InnerBrowser in the assertPageContains() method. I changed:

    htmlspecialchars_decode(strip_tags($this->client->getInternalResponse()->getContent())),
to:

    html_entity_decode(htmlspecialchars_decode(strip_tags($this->client->getInternalResponse()->getContent())), ENT_QUOTES ),

**Comment by zbateson** [comment]
Also a good and needed change, could you submit pull request?

**Comment by zbateson** [comment]
Do we need both htmlspecialchars_decode and html_entity_decode? Maybe it's enough to just have html_entity_decode, no?

**Comment by onshop** [comment]
I will try to submit a pull request. html_entity_decode() maybe sufficient.

**Comment by zbateson** [comment]
Looks good, thank you
