### ISSUE TITLE
Variables from _bootstrap are not accessible on tests

### ISSUE THREAD

**Issue by igorsantos07** [Codeception/Codeception#2035]
I'm not sure if this is a bug or a behaviour change from 1.* to 2.*, but the variables I define in my suite's bootstrap file are not acessible in my tests anymore.

That was very useful for defining custom components such as a `Faker` instance or custom data about users that's shared among many tests.

**Comment by GawainLynch** [comment]
[Fixtures](http://codeception.com/docs/reference/Fixtures) are what you're wanting.

**Comment by igorsantos07** [comment]
Boo, thanks. Testing noob here :stuck_out_tongue_closed_eyes:
