### ISSUE TITLE
-sg Skip Group doesn't seem to work!

### ISSUE THREAD

**Issue by puneet0191** [Codeception/Codeception#2036]
Hi, 

I followed the instruction given over here http://codeception.com/docs/07-AdvancedUsage#Group-Files and created a group Array named them as installation group in my codeception.yml file and it looks like this:
```
installation: [tests/acceptance/1stInstallJoomla3TestCept.php, tests/acceptance/2ndInstallJoomla3ExtensionCept.php]
```
Now when I execute the following command in my project root
```
php vendor/bin/codecept run acceptance --steps -g installation
```
it seems to work and run only these two test that I mentioned in the array.

I don't want to create any other group..all the other test, other than the two mentioned in installation group can be executed together, I don't want to create a separate group for them so I thought of sending this command on my CI.
```
php vendor/bin/codecept run acceptance --steps -sg installation
```
Assuming it would skip all the tests which belong to the Installation group and run rest of them, but to my surprize I see this error msg on the console

![image](https://cloud.githubusercontent.com/assets/3048593/8089242/4b85c6a8-0fc4-11e5-9cfb-0cde596aefdd.png)

I am not sure if this is the correct and expected behaviour, Codeception should consider a group as a group even if it is declared as an array. 

Thanks

**Comment by puneet0191** [comment]
We also found an update on this issue, when we are not using the short form command so instead of:
```
php vendor/bin/codecept run acceptance --steps -sg installation
```
we are using this
```
php vendor/bin/codecept run acceptance --steps --skip-group=installation
```
It seems to work just fine and solve the problem. 

Hence issue is with the short form. -sg

**Comment by sascha-egerer** [comment]
I can also confirm that issue. Looks like the short version does not work as soon as it has more then 1 character. So all short parameters with one character work but not those with two characters.

**Comment by dominiquedutra** [comment]
Can confirm this.

**Comment by teeencho** [comment]
+1

**Comment by Naktibalda** [comment]
@DavertMik I think that we have to change the shortcut.

http://symfony.com/doc/current/components/console/introduction.html#using-command-options
>  you can also declare a one-letter shortcut that you can call with a single dash like -y

Option parser checks only the first character for shortcut:
`if ($this->definition->hasShortcut($name[0]) `
https://github.com/symfony/console/blob/a2c98b8fa4dbf72980178da8f609431727d0d9cd/Input/ArgvInput.php#L103

**Comment by Naktibalda** [comment]
Which one do you prefer - `-x` or `-S`?
