### ISSUE TITLE
Problem with switchToIFrame(null)

### ISSUE THREAD

**Issue by torkiljohnsen** [Codeception/Codeception#2037]
**Scenario:** I have an iframe on a page. I want to switch to the iframe, verify that it contains an element, then switch back to the main window.

**Issue:** I can successfully switch to the named iframe, with `$I->switchToIFrame('foobar')`, but I can't switch back to the main window with `$I->switchToIFrame()`.

I get the following error:

    [WebDriverException] JSON decoding of remote response failed.
    Error code: 4
    The response: 'SyntaxError - JSON Parse error: Unexpected EOF'

I have worked my way around this by, instead of doing `$I->switchToIFrame()`, I get and store the window handle in `$window_handle` before I go into an iframe, and then when I want to leave the iframe I call `$I->switchToWindow($window_handle)`.

**Comment by Naktibalda** [comment]
`$I->switchToIframe()` appears to be working now.
it probably was an issue of Selenium.
