### ISSUE TITLE
selectOption can no longer match a substring of an option's text (2.0.10)

### ISSUE THREAD

**Issue by onshop** [Codeception/Codeception#2039]
I have a select:

    <select id="users" multiple="multiple" name="users[]">
        <option value="1">Borthwaite, Chaning</option>
        <option value="2">Crumb, Phileas</option>
       <option value="3">Ocramius, Cedric</option>
    </select>

In version 1.8.7 you could use selectOption to search for just part of the option's text:

    $I->selectOption( 'select[id=users]', 'Cedric');

However in 2.0.10 I get

    InvalidArgumentException: Input "users" cannot take "Cedric" as a value (possible values: 1 , 2, 3).

If I enter the full string it works:

    $I->selectOption( 'select[id=users]', 'Ocramius, Cedric');

**Comment by DavertMik** [comment]
Yes, that's right. Non-strict matching of select options could cause to unpredictable results. 

```
<option>My phone</option>
<option>My email</option>
``` 

```
$I->selectOption('#contacts', 'My') // what will be selected then???
```

I see current behavior to be more valid
