### ISSUE TITLE
checkoption() cannot identify selector when HTML is rendered using variables in MVC view (2.0.14)

### ISSUE THREAD

**Issue by onshop** [Codeception/Codeception#2040]
I am using Zend Framework 2.3 with TWIG (1.18.2) . In my TWIG template I have the following check box bounded by TWIG conditionals:

    {% if ( tempBusinessCase != null ) %}
        <input type="checkbox" value="{{ tempBusinessCase.getId() }}" id="remove_temp_business_case" name="removeTempBusinessCase" 
        <label for="remove_temp_business_case">Remove</label>
    {% endif %}

When I updated to 2.0.14 the following test failed:   

    $I->checkOption( '//input[@id=\'remove_temp_business_case\']' );

I got the following error:

    Couldn't check option "removeTempBusinessCase":
    InvalidArgumentException: Unreachable field "removeTempBusinessCase"

The following test preceding it passes so it is not a problem with the selector:

    $I->seeElement( '//input[@id=\'remove_temp_business_case\']' );

The test worked in 1.8.7 and stopped working when I moved to 2.0.14. I then changed to 2.0.10 and the test works again.

When the test fails the checkbox is shown in the output so it is there but checkOption cannot see it. It has something to do with the variable tempBusinessCase which is an instance of a class. It is passed to the template via the controller:

    $parameters = array(
        'form'                => $form
      , 'tempBusinessCase'    => $tempBusinessCase );

    $view = new  ViewModel( $parameters );
    $view->setTemplate( 'requests/form.twig' );
    return $view; 

If I pass in other hardcoded variables set to true and use those as the conditional then selectOption() will check the box.

I have tried to troubleshoot but I am not sure in which layer to look in. It would appear that $tempBusinessCase is not being evaluated before the  page is rendered and parsed and yet...

   {{ dump(tempBusinessCase) }}

outputs the class and the checkbox is also rendered.

As I say the test passes in 2.0.10 but not 2.0.14. Something introduced between those versions has changed the behaviour of selectOption().

**Comment by DavertMik** [comment]
Can you attach a complete HTML of a failed page?
