### ISSUE TITLE
uncheckOption do not work in some scenarios

### ISSUE THREAD

**Issue by aniolekx** [Codeception/Codeception#2043]
<input name="test"  type="hidden" value="off">
    <input name="test" type="checkbox" checked>
    <input type="submit" value="save" name="submit">

in above scenario hidden field is not sent (v.2.1.0-beta)

I want to uncheck checkbox, so this means I will send hidden filed value, this is how it works when user will submit it, but under codeception, hidden field value is not submitted, I think it is removed by input name instead of id (or argument from function definition)

**Comment by DavertMik** [comment]
Right now it is outdated and hard to reproduce. 
Please comment and reopen if it is still relevant, please attach your suite config on reopening.
Thx
