### ISSUE TITLE
Silent crash when loading module with method definition error

### ISSUE THREAD

**Issue by Yrwein** [Codeception/Codeception#2044]
Commit 12179ed80242 introduced ignoring errors when loading module class. This means that all tests can fail and there'll be no meaningful error - or the whole suite just crashes silently (for example if the module is implementing interface in the wrong way - error "Fatal error: Declaration of SomeModule::method must be compatible with SomeInterface::method" would be displayed in normal circumstances).

I would send pull with just removing "@"-sign but I don't want to reintroduce error "fixed" by the original commit. Could somebody (who is actually using Yii framework - @DavertMik ? :]) look at the fix once more or just remove the error control operator (so it can be fixed properly)?

**Comment by DavertMik** [comment]
This was fixed in master branch, but for backwards compatibility will stay in 2.0
