### ISSUE TITLE
Codeception crash when using $this->tester in Test (master branch)

### ISSUE THREAD

**Issue by jonphipps** [Codeception/Codeception#2045]
When using a test generated using TestCase\Test, an error in the test results in a fatal crash of Codeception. 

It crashes on [line 99 of TestCase\Shared\Actor](https://github.com/Codeception/Codeception/blob/master/src/Codeception/TestCase/Shared/Actor.php#L99) with an error: 
```Fatal error: Call to a member function addFailure() on null in Actor on line 99```

This is because only the Cept and Cest TestCases initialize ```$this->testResult``` by calling ```$this->prepareActorForTest()```

I ran into this when I encountered an error using ```$this->tester->canSeeInDatabase(...) in a TestCase\Test test.

**Comment by sergeyklay** [comment]
Hm! I thought that this problem only for me
