### ISSUE TITLE
Bus error (core dumped) error

### ISSUE THREAD

**Issue by saiger** [Codeception/Codeception#2054]
Sometimes I got "Bus error (core dumped)" message, my steps:
- Split tests and run it by Robo using your manual(http://codeception.com/docs/12-ParallelExecution),
  sometimes one of thread is terminating wth next output info:

"[ParallelExec] Output for  vendor/bin/codecept run --group p8 --env p8 acceptance 
[12:07:45][Step 3/4] Codeception PHP Testing Framework v2.0.12
[12:07:45][Step 3/4] Powered by PHPUnit 4.5.1 by Sebastian Bergmann and contributors.
[12:07:45][Step 3/4] [Groups] p8 
[12:07:45][Step 3/4] 
[12:07:45][Step 3/4] Bus error (core dumped)"

Codeception version: 2.0.12

**Comment by aleksandrzen** [comment]
+1

**Comment by jiexaspb** [comment]
+1

**Comment by aleksandrzen** [comment]
@DavertMik, hello, do you have any news about this bug?

**Comment by saiger** [comment]
Fixed

I started run from one folder, need to do next:
cd folder1 && codecepction run p1
cd folder2 && codeception run p2

**Comment by EvgeniySpinovSell** [comment]
I'm having the same issue with robo + codeception 2.1.1

But I didn't get the fix. I need to enter random directories before starting codeception? What if I have 20 parallel threads?

**Comment by ivanfetischev** [comment]
You need run every thread from its directory

**Comment by EvgeniySpinovSell** [comment]
That is like workaround, but not sure it is a proper fix. In my case tests doesn't have spare directories. So I'm like should traverse through folder tree and just enter any random directory of the project?

And is it a codeception or robo issue?

**Comment by ivanfetischev** [comment]
> just enter any random directory of the project
No

> And is it a codeception or robo issue?
It is not trouble of codeception or robo.

When you running codeception in many threads, every thread trying to create file AcceptanceTester.php, if you running 20 parallel threads in one directory, 20 processes trying to create one file. If you create directory for every thread and run every thread from its directory, it helps to solve problem

**Comment by EvgeniySpinovSell** [comment]
Thanks for detailed explanation, Ivan. Will have to workaround it with temp directories during tests. Probably this case should be reflected in docs for parallel testing.

**Comment by EvgeniySpinovSell** [comment]
Suggested solution doesn't seems to be working. Let me describe the setup a bit:
- I create a folder p1, p2, p3 .... for each test group
- I go to this directory for every test and invoke codeception. The way I invoke is ../vendor/codeception/codeception/bin/codecept ARGS

Sometimes I'm still getting errors about bus error:
```
[13:25:07][Step 11/14]  [ParallelExec] cd p3 && ../../vendor/codeception/codeception/codecept run --group p3 -c ../../codeception.yml --env env3 --xml result_p3.xml acceptance
[13:25:08][Step 11/14]  [ParallelExec] Output for  cd p3 && ../../vendor/codeception/codeception/codecept run --group p3 -c ../../codeception.yml --env env3 --xml result_p3.xml acceptance 
[13:25:08][Step 11/14] Codeception PHP Testing Framework v2.2.4
[13:25:08][Step 11/14] Powered by PHPUnit 4.8.27 by Sebastian Bergmann and contributors.
[13:25:08][Step 11/14] [Groups] p3 
[13:25:08][Step 11/14] 
[13:25:08][Step 11/14]   Rebuilding AcceptanceTester...
[13:25:08][Step 11/14] 
[13:25:08][Step 11/14] Bus error (core dumped)
```

Is there anything else I can do to tackle this one?

Thanks in advance.

**Comment by pitpit** [comment]
got the same issue with `Codeception version 2.2.7`

**Comment by Naktibalda** [comment]
@pitpit Please find the core dump file and provide a gdb backtrace:

https://bugs.php.net/bugs-generating-backtrace.php

**Comment by pitpit** [comment]
I'm not able to provide you a core dump file (it fails randomly on a remote CI server) or provide you a backtrace for now.

But look @ironsmile issue here https://github.com/Codeception/robo-paracept/issues/28. Seems to be related

**Comment by ironsmile** [comment]
Somehow I haven't found this issue before. Anyway, I have a coredump file from such a failure. Here it is:
[php-52752.tar.gz](https://github.com/Codeception/Codeception/files/929954/php-52752.tar.gz)
It was generated while running Codeception with robo-parallel. On PHP 5.5.38 which binary is also included in the archive so that one can inspect it with gdb.

I am not sure whether changing directories is a viable workaround. Aren't the generated files created relative to the configuration (yml) file? Would give it try though. Randomly failing tests are not fun at all! @pitpit, thank you for steering me into this issue :D

**Comment by pitpit** [comment]
I worked on this very empirical bugfix https://github.com/Codeception/Codeception/pull/4148.

Please give me some feedbacks if you can

**Comment by DavertMik** [comment]
Please help @pitpit to test it

**Comment by maxgorovenko** [comment]
@pitpit Your solution looks not stable. The thing is that every `codecept run` (and, while we use robo, in my case its 20-30 times) script generates some files. But we already have command that generates this files, here it is: `codecept build`. Why don't you disable generating at `run` if files exist?

**Comment by maxgorovenko** [comment]
But I should admit, this is much better than without. Now I'm going to try this PR harder

**Comment by pitpit** [comment]
@maxgorovenko 

> Why don't you disable generating at run if files exist?

I did not check the code but I think codeception needs to check that files generated by `codecept build` are up to date with tests (you could commit tests without running  `codecept build` before)

**Comment by maxgorovenko** [comment]
@pitpit But there could be a way to run tests without generating at all. For that case if I am really sure, that I want to run tests at previously generated files. And I agree, that failing tests would be my problem, if some files were outdated..

This could really fix the problem

**Comment by maxgorovenko** [comment]
Implemented --no-rebuild in Robo. Waiting in PR https://github.com/consolidation/Robo/pull/603
