### ISSUE TITLE
guzzle 6 incompatibility issue

### ISSUE THREAD

**Issue by somuraijoe** [Codeception/Codeception#2055]
Codeception doesn't work with the latest version of guzzle 

- codeception/codeception 2.0.14 requires guzzlehttp/guzzle ~4.0|~5.0 -> satisfiable by guzzlehttp/guzzle[5.3.x-dev].

**Comment by DavertMik** [comment]
Latest version of Codeception works with latest version of Guzzle :)
Please use Codeception from master branch. We recently implemented Guzzle6 connector https://github.com/Codeception/Codeception/pull/2026

It's pretty new, so feedback is welcome
