### ISSUE TITLE
Redirect URIs relative to the previous URI break

### ISSUE THREAD

**Issue by firejdl** [Codeception/Codeception#2057]
According to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.2), relative redirect URIs (e.g. not beginning with a /) should be "computed by resolving it against the effective request URI."

"The [effective request URI](https://tools.ietf.org/html/rfc7230#section-5.5) is the same as the request URI in most cases." ([source](http://stackoverflow.com/a/25643550))

In other words, if a server returns a `Location` header containing `edit.php`, and the request URI was `/admin/index.php`, the final URI should be `www.domain.com/admin/edit.php`.

WordPress uses these relative redirect URIs in some cases. When submitting the form to create a new user, you submit to `/wp-admin/user-new.php`, which redirects via the header: `Location:users.php?update=add&id=2`, which should send you to `/wp-admin/users.php?update=add&id=2`. With the current code, you get redirected to `/users.php?update=add&id=2`.

**Comment by zbateson** [comment]
Hi @firejdl - what version of Codeception are you using and what module(s)?  I seem to remember fixing this, at least for links on a page specifically... in general the Location header should be treated with the same code IIRC.

**Comment by firejdl** [comment]
I am running Codeception 2.0.14 and having the issue with PhpBrowser. I couldn't find any code related to this issue. There is a slightly different, but unrelated, issue at #1510.

**Comment by firejdl** [comment]
Should I continue with my plan to create a pull request? I've already committed my code on my fork. The test I added fails without my changes.

**Comment by zbateson** [comment]
Yes, absolutely :smile:
