### ISSUE TITLE
Issue in Codecept command when ussing --skip-group

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#2067]
See details of the issue at http://phptest.club/t/how-do-i-pass-an-array-of-groups-to-skip/488/2

**Comment by Naktibalda** [comment]
The question was:

> I'm trying to pass an array of groups to skip:
> 
> vendor/bin/codecept run --skip-group=group1 group2 acceptance
> 
> But of course that becomes an error:
> 
>   [Exception] Suite group2 was not loaded
> 
> This does not work neither:
> 
> vendor/bin/codecept run --skip-group=group1,group2 acceptance
> 
> I know you can pass an array since --skip-groups is expecting an array, see: https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Command/Run.php#L1032
> 
> But checking the examples at Symfony Console did not got the answer http://symfony.com/doc/current/components/console/introduction.html

> 
> 
> According to this (see http://symfony.com/doc/current/components/console/introduction.html#using-command-arguments2):
> 
>     InputArgument::IS_ARRAY The argument can contain an indefinite number of arguments and must be used at the end of the argument list
> 
> This --skip-group can't be used by codecept command, because is not the last argument, being the last argument the suite/test. Therefore you can't pass an array.

**Comment by Naktibalda** [comment]
@javigomez You incorrectly thought that --skip-group is an argument, actually it is an option.

http://symfony.com/doc/current/components/console/introduction.html#using-command-options

> InputOption::VALUE_IS_ARRAY 	This option accepts multiple values (e.g. --dir=/foo --dir=/bar)

Correct usage: `php codecept run cli --skip-group reports --skip-group coverage --skip-group core
`
