### ISSUE TITLE
2.0.14 Call to undefined method

### ISSUE THREAD

**Issue by PaulWeb** [Codeception/Codeception#2072]
After update to 2.0.14 I've gotten issue Call to undefined method Codeception\Lib\Console\Message::cut() in /www/xxx/protected/vendor/codeception/codeception/src/Codeception/Subscriber/Console.php on line 442. Then I've set in composer.json 2.0.13 and now all work fine

My enviroment:
Yii 1.16 + YiiBridge
Php 5.4.16
Debian 7

full stack:
HP Fatal error:  Call to undefined method Codeception\Lib\Console\Message::cut() in /www/xxx/protected/vendor/codeception/codeception/src/Codeception/Subscriber/Console.php on line 442
PHP Stack trace:
PHP   1. {main}() /www/xxx/protected/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /www/xxx/protected/vendor/codeception/codeception/codecept:27
PHP   3. Symfony\Component\Console\Application->doRun() /www/xxx/protected/vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /www/xxx/protected/vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /www/xxx/protected/vendor/symfony/console/Application.php:878
PHP   6. Codeception\Command\Run->execute() /www/xxx/protected/vendor/symfony/console/Command/Command.php:259
PHP   7. Codeception\Command\Run->runSuites() /www/xxx/protected/vendor/codeception/codeception/src/Codeception/Command/Run.php:192
PHP   8. Codeception\Codecept->run() /www/xxx/protected/vendor/codeception/codeception/src/Codeception/Command/Run.php:263
PHP   9. Codeception\Codecept->runSuite() /www/xxx/protected/vendor/codeception/codeception/src/Codeception/Codecept.php:158
PHP  10. Codeception\SuiteManager->run() /www/xxx/protected/vendor/codeception/codeception/src/Codeception/Codecept.php:175
PHP  11. Codeception\PHPUnit\Runner->doEnhancedRun() /www/xxx/protected/vendor/codeception/codeception/src/Codeception/SuiteManager.php:158
PHP  12. PHPUnit_Framework_TestSuite->run() /www/xxx/protected/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:100
PHP  13. PHPUnit_Framework_TestCase->run() /www/xxx/protected/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
PHP  14. PHPUnit_Framework_TestResult->run() /www/xxx/protected/vendor/phpunit/phpunit/src/Framework/TestCase.php:699
PHP  15. PHPUnit_Framework_TestCase->runBare() /www/xxx/protected/vendor/phpunit/phpunit/src/Framework/TestResult.php:609
PHP  16. Codeception\TestCase\Test->setUp() /www/xxx/protected/vendor/phpunit/phpunit/src/Framework/TestCase.php:739
PHP  17. Codeception\TestCase\Test->fire() /www/xxx/vendor/codeception/codeception/src/Codeception/TestCase/Test.php:31
PHP  18. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /www/xxx/vendor/codeception/codeception/src/Codeception/TestCase/Shared/Actor.php:49
PHP  19. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /www/xxx/protected/vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP  20. call_user_func:{/www/xxx/protected/vendor/symfony/event-dispatcher/EventDispatcher.php:164}() /www/xxx/protected/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP  21. Codeception\Subscriber\Console->before() /www/xxx/protected/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP  22. Codeception\Subscriber\Console->writeCurrentTest() /www/xxx/protected/vendor/codeception/codeception/src/Codeception/Subscriber/Console.php:106
PHP  23. Codeception\Subscriber\Console->getTestMessage() /www/xxx/protected/vendor/codeception/codeception/src/Codeception/Subscriber/Console.php:455

**Comment by Naktibalda** [comment]
I have looked at the code and my best guess is that you managed to do an incomplete upgrade to 2.0.14.

Message::cut method was introduced in 2.0.14,
your issue could happen if you had (Codeception\Subscriber\Console)[https://github.com/Codeception/Codeception/blob/2.0.14/src/Codeception/Subscriber/Console.php#L442] from 2.0.14
and  (Codeception\Lib\Console\Message)[https://github.com/Codeception/Codeception/blob/2.0.14/src/Codeception/Lib/Console/Message.php] from 2.0.13 or earlier.

**Comment by PaulWeb** [comment]
I've installed(before jenkins removed all) on pre production server and gotten the same issue. on my local server I've set 2.0.14, updated, run unit tests and gotten issue

**Comment by Naktibalda** [comment]
Have you solved this issue?
