### ISSUE TITLE
Accessing modules with Unit Cest

### ISSUE THREAD

**Issue by Gyoo** [Codeception/Codeception#2085]
Hi,

I'm facing a problem using Unit Cests. By reading the [doc](http://codeception.com/docs/06-UnitTests#Testing-Database) I should be able to access the Symfony2 module with this line : `$container = $this->getModule('Symfony2')->container;`, however it only works with a class that extends `\Codeception\TestCase\Test`.

If I try to extend `\Codeception\TestCase\Test` to my class, I get this error at execution : 
`PHP Fatal error:  Cannot access protected property AgentsCest::$env in /home/mavintern/PhpstormProjects/php-smobilpay-agent-tracker/vendor/codeception/codeception/src/Codeception/TestCase/Cest.php on line 177`

How can I correctly access the Symfony2 module using a Unit Cest ?

**Comment by DavertMik** [comment]
For classical unit testing please have your tests extended from `Codeception\TestCase\Test`, they work as regular PHPUnit tests with ability to access Codeception parts like `getModule`.

Cest is better suited for scenario-driven tests where all actions are described from an actor perspective. Cest by itself is an empty class only with test methods in it. In each test method an actor object is passed, so Symfony can be accessed the way you could do it in functional tests

``` php
function checkService(UnitTester $I)
{
    $I->grabServiceFromContainer('...');
}
```
If you need to access container directly you can implement that action in Helper and use it in your scenario tests. 

Also you can access UnitTester class inside `Codeception\TestCase\Test` tests by calling `$this->tester`. Cest format is better when you need to see step-by-step output of execution.
