### ISSUE TITLE
Codeception keeps working with the first form in a multi-step form

### ISSUE THREAD

**Issue by Revisor** [Codeception/Codeception#2087]
We want to test a multi-step form, but Codeception keeps working with the first form.

Edit: As we found out below, the bug appears if the forms share the same `action` parameter.

The simplest example looks like this:

        $I->amOnPage('http://website.dev/8'); // GET the first page
        $I->click('#acceptbinbutton'); // POST the first form, arrive at the second step
        $I->submitForm('#vbpas_form_newbid', []); // POST the second form, finish the process

This is what the debug looks like (to shorten the output, I removed cookies and headers)

    * I am on page "http://website.dev/8"
      [Response] 200
      [Page] http://website.dev/8
    * I click "#acceptbinbutton"
      [Uri] http://website.dev/showthread.php?t=8
      [Method] POST
      [Parameters] {"s":"","securitytoken":"1435150503-a86a2304e5e9b2b0a275aeb1c14fe6e52a0f8255","do":"acceptbin","binprice":"999","private":"1"}
      [Response] 200
      [Page] http://website.dev/showthread.php?t=8
    * I submit form "#vbpas_form_newbid",
      [Uri] http://website.dev/showthread.php?t=8
      [Method] POST
      [Parameters] {"s":"","securitytoken":"1435150503-a86a2304e5e9b2b0a275aeb1c14fe6e52a0f8255","do":"acceptbin","binprice":"999","private":"1"}
      [Response] 200
      [Page] http://website.dev/showthread.php?t=8

The forms look like this.

First form

    <form id="vbpas_form_placebin" class="vbpas_form" method="post" action="showthread.php?t=8">
        <input type="hidden" value="" name="s">
        <input type="hidden" value="1435147272-05af65f5d60dba3942c65d63e3847ba7ba7d16b1" name="securitytoken">
        <input type="hidden" value="acceptbin" name="do">
        <input type="hidden" value="999" name="binprice">
        <input type="hidden" value="1" name="private">
        <input id="acceptbinbutton" class="button ui-state-default ui-corner-all ui-button ui-widget" type="submit" value="Buy now for 999" role="button">
    </form>

Second form

    <form id="vbpas_form_newbid" class="vbpas_form" method="post" action="showthread.php?t=8">
        <input type="hidden" value="" name="s">
        <input type="hidden" value="1435147272-05af65f5d60dba3942c65d63e3847ba7ba7d16b1" name="securitytoken">
        <input type="hidden" value="acceptbin" name="do">
        <input type="hidden" value="999" name="binprice">
        <input id="bidConfirmed" type="checkbox" name="bidConfirmed">
        <input class="button ui-state-default ui-corner-all" type="submit" value="Confirm the bid">
    </form>

As you can see they differ only in the last item, input[name="private"] vs input[name="bidConfirmed"]

However if we submit the second form with Codeception, the properties of the first form are submitted. The same error appears when trying to check the checkbox in the second form.

    // This works
    $I->seeElement('#bidConfirmed');
    // This doesn't work, throws InvalidArgumentException: Unreachable field "bidConfirmed"
    $I->checkOption('#bidConfirmed'); 

Are we doing something wrong? How can we work properly with the second form?

Edit: We use the PhpBrowser module.

**Comment by Revisor** [comment]
Ok, so we dove deeper into the code and found what we think is a bug in `Codeception\Lib\InnerBrowser`. Everytime the property `$crawler` is reassigned - that is a new page is loaded - the property `$forms` is cleared.

See the method `_after()`

    $this->crawler = null;
    $this->forms   = [];

Method `amOnPage()`

    $this->crawler = $this->client->request('GET', $page);
    $this->forms = [];

Method `click()`

    $this->crawler = $this->client->click($anchor->first()->link());
    $this->forms = [];

Method `clickByLocator()`

    $this->crawler = $this->client->click($nodes->first()->link());
    $this->forms = [];

However the property `$forms` is not cleared in `proceedSubmitForm()` which ends like this

    $this->crawler = $this->client->request(
        $form->getMethod(),
        $url,
        $requestParams,
        $form->getPhpFiles()
    );
    $this->debugResponse();

If the form on page 1 has the same action as the form on page 2 in one test, the form from page 1 is used. See the final lines of the method `getFormFor()`

    $action = $this->getFormUrl($form);
    if (!isset($this->forms[$action])) {
        $this->forms[$action] = $this->getFormFromCrawler($form, $action);
    }
    return $this->forms[$action];

Thus the old form is returned and the test of a multi-step form fails.

The fix should be very simple, just clear `$this->forms` at the end of `proceedFormSubmit()`.

Please confirm.

**Comment by zbateson** [comment]
That sounds correct.  I'll push a fix in a few hours when I get in front of a computer unless someone else gets to it first :smiley:

**Comment by Revisor** [comment]
Thank you very much.
