### ISSUE TITLE
Using the Laravel4 module, Test suite cleanup conflicts with Laravel ORM transactions

### ISSUE THREAD

**Issue by ivanhosgood** [Codeception/Codeception#2092]
Test Setup:
Laravel4 module loaded
cleanup: true

Test creating Laravel User:

    DB::beginTransaction();
        $user = new User();
        $user->save();
        DB::rollback();

        $user = User::find($user->id);

        $I->assertNull($user);

Result: Fail

If we change the cleanup field to false, the test passes. I suspect there is nesting of transactions happening when cleanup is enabled, causing this error

**Comment by janhenkgerritsen** [comment]
You are correct, `cleanup` uses database transactions to rollback the modifications made by the tests. So if your code uses transactions you should not use the `cleanup` option. You can use the functionality in the [DB](http://codeception.com/docs/modules/Db) module to set the database to a known state before each test.

**Comment by ivanhosgood** [comment]
Thanks for the rapid response. I will explicitly do my own cleanup for this test then
