### ISSUE TITLE
[2.1-rc1] Helper traits are not loaded

### ISSUE THREAD

**Issue by enumag** [Codeception/Codeception#2094]
Codeception now generates the following code for functional actor trait:

```php
<?php  //[STAMP] a8ca79d6eeaf3e7789f1dd1ed0a91213
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
```

As you can see, the trait `Helper\Functional` is not actually used because the use clause is outside of the trait. Same goes for other suites.

**Comment by DavertMik** [comment]
`Helper\Functional` is not a trait, it is a class. I.e. it is old known FunctionalHelper )

**Comment by enumag** [comment]
Oh, sorry. My mistake.
