### ISSUE TITLE
What's the best approach for handling acceptance test bifurcation?

### ISSUE THREAD

**Issue by igorsantos07** [Codeception/Codeception#2097]
Is there a best approach for acceptance testing when you have a test splitting in some part?
Example: a signup form where the user is presented with an option in the end, and each decision gives him a different interface for further interaction.
Those options are not presented otherwise, so they must follow the signup procedure.

**Comment by janhenkgerritsen** [comment]
Just write multiple tests covering all different paths through the signup procedure. In the [Advanced usage](http://codeception.com/docs/07-AdvancedUsage) section of the documentation you can find some techniques to refactor out duplicated code.

**Comment by micaweb** [comment]
`saveSessionSnapshot` from `webDriver` module is also an option. http://codeception.com/docs/modules/WebDriver#saveSessionSnapshot
