### ISSUE TITLE
fatal error in 2.1rc using REST module

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#2098]
I'm running my API tests that works on 2.0. but using 2.1rc (https://github.com/Codeception/Codeception/pull/1878#discussion_r33347344), but I get this:

```
FATAL ERROR. TESTS NOT FINISHED.
Call to a member function setRefreshMaxInterval() on a non-object 
in /joomla-vagrant/vendor/codeception/codeception/src/Codeception/Module/PhpBrowser.php:251
```

**Comment by DavertMik** [comment]
Should be fixed in master. Reopen if not

**Comment by DavertMik** [comment]
Also if it persists please post a full stack trace
