### ISSUE TITLE
Run multiple tests

### ISSUE THREAD

**Issue by junichi11** [Codeception/Codeception#2106]
Hi,

I would like to support Codeception in NetBeans IDE.

I want to implement a feature to run failed tests in it. We can run a single test(e.g. `codecept run tests/unit/FooTest.php` ), then we can get a xml log. If there are many failed tests, many xml logs are created. But I want to get the results as a single xml log.
Could you add a feature to run multiple tests with a single command?

Thanks.

**Comment by javigomez** [comment]
I'm not sure to understand your issue. What happens if you run the tests as a suite: `codecept run unit`? you will run all the tests and get one error report. Isn't it?

**Comment by junichi11** [comment]
NetBeans can rerun only failed tests. So I want to specify only them.  (Isn't a suite or a directory)

#### Steps
- `codecept run unit`
- Some tests failed
- Rerun failed tests

![nb-codeception-2106-1](https://cloud.githubusercontent.com/assets/738383/8429611/6105403a-1f64-11e5-9e69-3a1579e6b674.png)

For example, Two files failed as above. I want to run them at the same time, then I want to get one xml log file.

**Comment by DavertMik** [comment]
There is `RunFailed` extension which is enabled by default in Codeception 2.1. It stores all failed tests into text file and assigns them to group `failed`. So you can rerun failed tests by running `codecept run -g failed`

**Comment by junichi11** [comment]
@DavertMik Thanks! I'll try it.

**Comment by junichi11** [comment]
I've implemented the feature to run failed tests in NetBeans :) `RunFailed` extension works fine!
![nb-codeception-run-failed-1](https://cloud.githubusercontent.com/assets/738383/8596801/61236b80-268c-11e5-9b9b-876f169e7cfe.png)

![nb-codeception-run-failed-2](https://cloud.githubusercontent.com/assets/738383/8596819/7e6ddfcc-268c-11e5-91e7-69a80a83515b.png)

Thanks a lot!
