### ISSUE TITLE
Absolute url problem with REST

### ISSUE THREAD

**Issue by tmp77** [Codeception/Codeception#2117]
There is a problem with hosts using absolute url
$I->sendGET('http://example.com/123/');

```modules:
    enabled: [PhpBrowser, REST]
    config:
        PhpBrowser:
            url: http://example.local
        REST:
            depends: PhpBrowser
            url: http://example.local
```

Real request is sent to http://example.local/123/. See Util\Uri::mergeUrls()

**Comment by withremote** [comment]
I'm having a similar issue with Acceptance tests. Tests with absolute urls that passed in 2.0.15 return 404s in 2.1. Mine are all https urls if that would make a difference.

**Comment by DavertMik** [comment]
@withremote please could you be more specific. I was trying to reproduce something like this in acceptance tests, but I didn't see any issues in acceptance tests.

@tmp77 test for your issue was written and it was fixed
