### ISSUE TITLE
Can not run codecept from phar (v 2.1)

### ISSUE THREAD

**Issue by DexterHD** [Codeception/Codeception#2118]
In `tests/codeception/_bootstrap.php` I have a composer autoloader for use some libraries in tests:

`require_once(__DIR__ . '/../../vendor/autoload.php');`

When I trying to run codeception from `codecept.phar` I have an error:

```
codecept run
PHP Fatal error:  Cannot redeclare GuzzleHttp\Psr7\str() (previously declared in phar:///Users/dexter/Software/console/codecept.phar/vendor/guzzlehttp/psr7/src/functions.php:17) in /Users/dexter/Projects/fix/site-core/vendor/guzzlehttp/psr7/src/functions.php on line 39
```

**Comment by DavertMik** [comment]
I don't think there is a solution for that. Probably you should switch to composer version of Codeception if you already use composer.

**Comment by DexterHD** [comment]
Hmm. Ok. But in 1.x it works fine.
