### ISSUE TITLE
Should I ignore tests/_suport/_generated folder from GIT ?

### ISSUE THREAD

**Issue by chungth** [Codeception/Codeception#2119]
Hi 

I've upgraded codeception into 2.1 . 
In `tests/_support/_generated` folder, there are some  files which auto generated. 
Should I ignore theme from GIT ? 
Because It is often conflicted.

**Comment by javigomez** [comment]
Not checked yet, but I guess we can do like with old *Tester files

**Comment by chungth** [comment]
@javigomez   What did you do with old *Tester files ?

**Comment by javigomez** [comment]
sorry I forgot the link http://phptest.club/t/gitignore-acceptancetester-functionaltester-unittester/244

**Comment by chungth** [comment]
@javigomez  Thanks !

**Comment by mahone3297** [comment]
Can someone describe how to solve the problem in detail?
Becasuse I come across the problem, too.

**Comment by gnumoksha** [comment]
This is (more or less) what I am doing:
```
echo "/src/tests/_support/_generated/" >> .gitignore
echo "!.gitignore" >> .gitignore
touch src/tests/_support/_generated/.gitkeep
git add -f src/tests/_support/_generated/.gitkeep
```
