### ISSUE TITLE
Flash message and session error messages

### ISSUE THREAD

**Issue by umang-ranium** [Codeception/Codeception#2123]
Hi,
I am unable to see session error message using see function nor seefrorm erro or session error fuction returns true, the output html donesn't show flash messages

**Comment by DavertMik** [comment]
Is that for Laravel module? Which version?
Can you provide more details?

**Comment by umang-ranium** [comment]
Yes this is for laravel, Codeception PHP Testing Framework v2.1.0
Powered by PHPUnit 4.7.6 by Sebastian Bergmann and contributors.

**Comment by umang-ranium** [comment]
acceptancesuite.yml

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
        - Laravel4
        - Db
        - REST:
              depends: PhpBrowser
              url: http://localhost/api/
        # - MailCatcher
        # - Asserts
    config:
        # PhpBrowser:
        #     url: 'http://eg.dev'
        REST:
            url: 'http://eg.dev/api/v1/'
        WebDriver:
            url: 'http://eg.dev/'
            browser: phantomjs
            window_size: 1440x768
            capabilities:
                javascriptEnabled: true
                webStorageEnable: true
        Laravel4:
            cleanup: true
            start: bootstrap/start.php
        # MailCatcher:
        #      url: 'http://eg.dev'
        #      port: 1080
    coverage:
        enabled: true
        remote: false

codeception.yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 60G
coverage:
    enabled: true
    remote: false
    c3_url: 'http://eg.dev/c3.php'
    include:
        - app/*.php
    exclude:
        - app/libraries/*
        - app/config/*
        - app/assets/*
        - app/database/*
        - app/lang/*
        - app/output/*
        - app/storage/*
        - app/tests/*
modules:
    config:
        Db:
            # dsn: 'sqlite3:tests/_data/dump.sqlite'
            dsn: 'mysql:host=127.0.0.1;port=3306;dbname=eg_testing'
            user: 'root'
            password: ''
            dump: tests/_data/eg.sql
            populate: true
            cleanup: true

**Comment by umang-ranium** [comment]
@DavertMik Any update on this.

**Comment by janhenkgerritsen** [comment]
If you use the Laravel4 module you should not use the Webdriver and PhpBrowser modules. Try updating your config to something like:

    modules:
        enabled:
            - AcceptanceHelper
            - Laravel4:
                cleanup: true
                start: bootstrap/start.php
            - DB
            - REST:
                depends: Laravel4
                url: 'http://eg.dev/api/v1/'

Note that I set the Laravel4 module as a dependency of the REST module.

Furthermore you can inline your config block into the enabled block, as I did with the config for the Laravel4 and REST modules in the snippet above.

**Comment by umang-ranium** [comment]
@janhenkgerritsen  Thanks but still error message bag is empty for test

**Comment by janhenkgerritsen** [comment]
Do you have the correct session driver set for your testing environment? If you use the array driver session data gets lost between requests.

Otherwise, could you give an example of a test that fails?

**Comment by umang-ranium** [comment]
@janhenkgerritsen here is the test, i don't know about session driver for test it was working previously but after updating the module test are failling
$I->wantTo('Submit empty amenity type create page');
        $I->amOnpage('/admin/accounts/create');
        $I->see('Create New Account');
        $I->click("input[type=submit]");
        $I->see('The name field is required.');
ouput :-1: 
1) Failed to submit empty amenity type create page in AcceptanceAdminAccountCest::submitEmptyAccountCreatePage (tests/acceptance/AcceptanceAdminAccountCest.php)

 Step  I see "The name field is required."
 Fail  Failed asserting that   /admin/accounts/create

**Comment by janhenkgerritsen** [comment]
Ok I will look into it, but can't say exactly when.

**Comment by umang-ranium** [comment]
@janhenkgerritsen Thanks for your help

**Comment by janhenkgerritsen** [comment]
I just tested the Laravel 4 sample application with the latest 2.1 release of Codeception but everything seems to work fine. 

You can find the sample application at https://github.com/Codeception/sample-l4-app. There are branches for the 2.0 and 2.1 release for Codeception, but both branches contain the same tests.

I believe the [FormErrorsCept](https://github.com/Codeception/sample-l4-app/blob/codeception-2.1/tests/functional/FormErrorsCept.php) covers the same scenario as your sample testcase. Do you agree? If so, you should  try to find the differences between your application and the sample application.

Also, have you looked at the output of the failed test in the _output directory? Maybe the generated HTML contains an error message?

**Comment by umang-ranium** [comment]
@janhenkgerritsen  thanks for you help problem was with session drivers it was using array and i didn't knew about it, thanks onces again

**Comment by janhenkgerritsen** [comment]
No problem.

**Comment by umang-ranium** [comment]
@janhenkgerritsen when i try to run ./codecept run unit i get this 
  [Codeception\Exception\ConfigurationException]    
  UnitTester class doesn't exists in suite folder.  
  Run the 'build' command to generate it 

Then when i try to run ./codeception build it gives this

[Codeception\Exception\ModuleRequireException]              
  REST module requirements are not met!                       
  This module depends on Codeception\Lib\InnerBrowser         
                                                              
  Example configuring PhpBrowser as backend for REST module.  
  --                                                          
  modules:                                                    
      enabled:                                                
          - REST:                                             
              depends: PhpBrowser                             
              url: http://localhost/api/                      
  --                                                          
  Framework modules can be used for testing of API as well.

**Comment by umang-ranium** [comment]
acceptance.yml 
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
        - Laravel4
        - Db
        - REST:
              depends: PhpBrowser
              url: http://localhost:8000/api/
        # - MailCatcher
        # - Asserts
    config:
        # PhpBrowser:
        #     url: 'http://eg.dev'
        #REST:
            #url: 'http://localhost:8000/api/v1/'
        WebDriver:
            url: 'http://localhost:8000/'
            browser: phantomjs
            window_size: 1440x768
            capabilities:
                javascriptEnabled: true
                webStorageEnable: true
        Laravel4:
            cleanup: true
            start: bootstrap/start.php
        # MailCatcher:
        #      url: 'http://eg.dev'
        #      port: 1080
    coverage:
        enabled: true
        remote: false

api.suite.yml
class_name: ApiTester
modules:
    enabled:
        - PhpBrowser
        - REST:
              depends: PhpBrowser
              url: http://localhost:8000/api/
        - ApiHelper
        - Laravel4
        - Db
        - Asserts
    config:
        Laravel4:
            cleanup: true
            start: bootstrap/start.php
        PhpBrowser:
            url: http://localhost:8000/
        REST:
            url: http://localhost:8000/api/v1/
    coverage:
        remote: true


functional.suite.yml
class_name: FunctionalTester
modules:
    enabled:
        # - PhpBrowser
        - Filesystem
        - FunctionalHelper
        - Db
        - Asserts
        - Laravel4Sentinel
    config:
        Laravel4:
            cleanup: true
            start: bootstrap/start.php
        # PhpBrowser:
        #     url: 'http://eg.dev'
    coverage:
        enabled: true
        remote: false


unit.suite.yml
# Codeception Test Suite Configuration

# suite for unit (internal) tests.
class_name: UnitTester
modules:
    enabled: [Asserts, UnitHelper, Laravel4, Db]

**Comment by janhenkgerritsen** [comment]
If you use a framework module like the Laravel4 module, the REST module should depend on that module. So the suite config should contain something like:

    modules:
        enabled:
            - Laravel4
            - REST:
                depends: Laravel4

On a side note, if you post your config files could you make sure the formatting is correct? Its not really easy for me to look through your post directly above this one. Furthermore, YAML configuration relies on whitespace, so now I can't really see if you have errors related to whitespace or not.

For some details about formatting code you can look at https://guides.github.com/features/mastering-markdown/.

**Comment by umang-ranium** [comment]
@janhenkgerritsen Thanks for the quick reply, i will do that can you please let me know can i call controller method through unit test

**Comment by janhenkgerritsen** [comment]
If you can instantiate a controller in your test case you can call methods on it. Whether you should actually do that is another question, for which the answer totally depends on the code in your controller. Most of the time a controller has a lot of dependencies which makes unit testing hard, so in those cases it is probably better to use functional tests.

**Comment by umang-ranium** [comment]
@janhenkgerritsen Its a api call  Route::post('users/batch', [
            'as' => 'users/batch',
            'uses' => 'UsersController@store']); and i want to pass an array to it

**Comment by janhenkgerritsen** [comment]
I would probably use a functional test for that, with the `sendPOST` method of the REST module.

**Comment by umang-ranium** [comment]
@janhenkgerritsen Thanks for the help, that means i can't use unit test in this condition

**Comment by janhenkgerritsen** [comment]
If you really want you can probably make that work, but a functional test is the easy way in this case.

**Comment by umang-ranium** [comment]
@janhenkgerritsen 
Just for the information sake how to call controller function and pass data to it

**Comment by janhenkgerritsen** [comment]
Something like this:

```
function testStore() {
    $data = [];
    $controller = new UsersController();
    $response = $controller->store($data);

    // Make your tests assertions
}
```

But whether this will work or not depends on the dependencies of your controller.

If you need more help with your testing you should go to a site like http://phptest.club/, here we should only focus on issues with Codeception itself. This discussion is not really relevant for other users that might end up here.

**Comment by umang-ranium** [comment]
@janhenkgerritsen Thanks for your help, you are always a saviour

**Comment by umang-ranium** [comment]
@janhenkgerritsen  i am trying to write functional test as suggested by you but now i am getting 
PHP Fatal error:  Class 'Codeception\Exception\ModuleConfig' not found in /Users/umang/Sites/groupsync/vendor/jorisnoo/codeception-laravel-sentinel-module/src/Laravel4Sentinel.php on line 13

 public function editMyApiClient(\FunctionalTester $I)
    {
        $I->wantTo('edit my api client');

        $user = FunctionalCommons::logMeIn($I);
        // This should be in the dump we start with
        $client = $I->grabRecord('oauth_clients', ['id' => 'FIRST_APP']);
        $I->amOnPage('/admin/users/'.$client->user_id);
        $I->see($client->name);
        $I->amOnPage('/admin/oauth_clients/'.$client->name.'/edit');
        $I->fillField('input[name=redirect_uri]', 'http://google.com');
        $I->click('input[type=submit]');

        $I->seeRecord('oauth_client_endpoints', ['client_id' => $client->name, 'redirect_uri' => 'http://google.com']);
        $I->see('Success');
        $I->seeCurrentUrlEquals('/admin/oauth_clients/'.$client->name.'/edit');
    }

**Comment by umang-ranium** [comment]
@janhenkgerritsen My data is saving to site db not in test db

**Comment by janhenkgerritsen** [comment]
That is most likely a configuration problem, for example the wrong environment is used for your tests.

But as stated before, this is not the right place to look for help with your tests, only to report issues with Codeception. For help with your tests you should go to a site like http://phptest.club/.

**Comment by umang-ranium** [comment]
@janhenkgerritsen I have posted all the 3 question at php test but none were answered thank full you have answered 2 of them

**Comment by umang-ranium** [comment]
@janhenkgerritsen can you please let me know how to disable filters in acceptances tests i.e Route::group(['prefix' => 'api/v1', 'before' => 'oauth'], function () {

**Comment by janhenkgerritsen** [comment]
You can't disable filters in acceptance tests through the Laravel module, because acceptance tests don't have access to the application code. If you really need to disable the filters you should make a special environment for acceptance tests in your application and disable the filters in this environment.

**Comment by umang-ranium** [comment]
@janhenkgerritsen  i have made testing environment but can't disable filters

**Comment by NupurGoel28** [comment]
[Codeception\Exception\ConfigurationException]
AcceptanceTester class doesn't exist in suite folder.
Run the 'build' command to generate it

I am getting this error

**Comment by janhenkgerritsen** [comment]
Have you done what the error message suggests? That is, run the `codecept build` command.

If that is not the solution, please open your own issue instead of commenting on an already closed issue. And provide more details, for example the version you use and your config files.

**Comment by NupurGoel28** [comment]
I ran codecept build command but nothing happens.

The issue is resolved now. I have created a new project and change the environment variables accordingly.

Still not aware the root cause of this issue. :(

Thanks
