### ISSUE TITLE
Problem with Guzzle on php 5.4

### ISSUE THREAD

**Issue by MAXakaWIZARD** [Codeception/Codeception#2124]
Codeception 2.1.x requires php >=5.4.0
But when running `codecept.phar` on php 5.4, I see such error:
`Call to undefined function GuzzleHttp\Handler\curl_reset() `
Function `curl_reset` was added in php 5.5, so it seems that we have guzzle >=6.0.0 in phar archive (maybe phar was built on php 5.5+). I think phar should be built on php 5.4, as per Codeception requirement.

**Comment by atmoz** [comment]
+1

Got the same issue. Codeception 2.1.0 does not work with PHP 5.4.

**Comment by DavertMik** [comment]
Ok, to clarify the issue: Codeception Phar is not working with PHP 5.4 
If you install it via Composer you will have it working

**Comment by delboy1978uk** [comment]
i was about to say something until I saw the EOL is soon. I think I'll just drop testing for 5.4

**Comment by Naktibalda** [comment]
I solved this issue by installing Guzzle 5.x with composer.

**Comment by Glutexo** [comment]
The fact, you found a solution does not mean that the bug does not exist any more. Even though the EOL of PHP 5.4 is comming really soon, the Codeception website states that it is compatible with PHP 5.4, which it actually isn’t. At least not the PHAR package.

**Comment by webfacer** [comment]
i have also on ovh server the 5.4 PHP version. Inpossiple to use the 6.x version of Guzzle. Please reopen this issue.

**Comment by Naktibalda** [comment]
If it helps.

**Comment by Naktibalda** [comment]
@DavertMik I believe that not providing a build for PHP 5.4 hurts our adoption on PHP 5.4.
It wouldn't be that hard to make 2 builds for every release.

For everyone else:

Here are instructions how to make your own build of Codeception with Guzzle 5.

git clone https://github.com/Codeception/Codeception/
cd Codeception
composer require guzzlehttp/guzzle 5.3.*
wget http://robo.li/robo.phar
php -d phar.readonly=0 robo.phar build:phar

Result: http://s000.tinyupload.com/index.php?file_id=05032114061555932630

**Comment by Naktibalda** [comment]
Codeception 2.1.3 for PHP 5.4: http://s000.tinyupload.com/index.php?file_id=05304194827543980861

**Comment by aniebiet** [comment]
Thanks @Naktibalda

**Comment by agarzon** [comment]
Thank you @Naktibalda it works.

**Comment by Naktibalda** [comment]
Codeception 2.1.4 for PHP 5.4: http://s000.tinyupload.com/index.php?file_id=08748651056616693478

**Comment by Naktibalda** [comment]
I made a new build for 2.1 branch: http://s000.tinyupload.com/index.php?file_id=22702907805444068981

**Comment by Naktibalda** [comment]
Codeception 2.1.5 for PHP 5.4: http://s000.tinyupload.com/index.php?file_id=60736526137179927144

**Comment by Naktibalda** [comment]
Separate build for PHP 5.4 is provided since 2.1.6
http://codeception.com/releases/2.1.6/php54/codecept.phar

http://codeception.com/quickstart
