### ISSUE TITLE
ExecuteInSelenium method is marked as failed in the HTML report

### ISSUE THREAD

**Issue by Allex1337** [Codeception/Codeception#2126]
It seems that executeInSelenium method is marked as failed in the HTML report:

http://screencast.com/t/MtLDjlB1rF

**Comment by DavertMik** [comment]
And what do you have in console output? (please run with `-vvv` option)

**Comment by Allex1337** [comment]
Hello Davert,

They aren't showing as failed in the console output (running with both -vvv and --debug). 

As an example:

  I click "css#locator"
  I wait 1
  I execute in selenium "lambda function"
  I am on page “/page”
 PASSED

OK (53 tests, 87 assertions)

So the scenario reports as OK at the end and as well in the HTML report (Codeception Results OK) but when viewing each detail step, the methods "executeInSelenium" have the red thick borders (as shown in the previously attached image)

Please let me know if you need any other info.
