### ISSUE TITLE
Using code coverage command switches actually causes a change in database used in tests

### ISSUE THREAD

**Issue by joelsaxton** [Codeception/Codeception#2129]
When running "codeception run unit" my sqlite testing database is used, which is desired. When running the same command with code coverage: "codeception run unit --coverage-html 'coverage/' --coverage-xml 'coverage/coverage.xml'" all of a sudden it uses my production database. 

More details: http://stackoverflow.com/questions/31253043/codeception-laravel-5-1-uses-wrong-database-when-code-coverage-command-switche

**Comment by janhenkgerritsen** [comment]
Can you provide your config files?

The most likely explanation is that for your coverage the Laravel module is not used, but for example the PhpBrowser or WebDriver module. And these do not pick up the configuration settings of the Laravel module.

**Comment by joelsaxton** [comment]
Here are what I think are the relevant files. These are just unit tests so I am not using PhpBrowser or WebDriver.


.env file (relevant parts):

DB_DEFAULT=mysql
HOST=localhost
DATABASE=local_db
USERNAME=user
PASSWORD=password



config/database.php:

'default' => env('DB_DEFAULT', 'mysql'),    
'connections' => [
    'mysql' => [
        'driver'    => 'mysql',
        'host'      => env('HOST'),
        'database'  => env('DATABASE'),
        'username'  => env('USERNAME'),
        'password'  => env('PASSWORD'),
        'charset'   => 'utf8',
        'collation' => 'utf8_unicode_ci',
        'prefix'    => '',
        'strict'    => false,
    ],

    'sqlite_testing' => [
        'driver' => 'sqlite',
        'database' => ':memory:',
        'prefix' => ''
    ]    
],


TestCase.php, which the unit tests extend:

class TestCase extends Illuminate\Foundation\Testing\TestCase {
    protected $baseUrl = 'http://localhost';
    /**
     * Default preparation for each test
     */
    public function setUp()
    {
        parent::setUp();
        $this->prepareForTests();
    }

    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        putenv('DB_DEFAULT=sqlite_testing'); 
        $app = require __DIR__ . '/../bootstrap/app.php';
        $app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
        return $app;
    }

    /**
     * Migrates the database and set the mailer to 'pretend'.
     * This will cause the tests to run quickly.
     */
    private function prepareForTests()
    {
        Artisan::call('migrate:reset');
        Artisan::call('migrate');
        Artisan::call('db:seed');
        Mail::pretend(true);
        Eloquent::reguard();
    }

    public function tearDown()
    {
        parent::tearDown();
    }
}



unit.suite.yml:

# Codeception Test Suite Configuration
# suite for unit (internal) tests.
class_name: UnitTester
modules:
    enabled: [Asserts, UnitHelper]



One of the test files (I am only showing one of its tests):

class CSVUpdateTest extends TestCase
{

    use DispatchesJobs;

    /**
     * @var \UnitTester
     */
    protected $tester;

    protected function _before()
    {
    }

    protected function _after()
    {
    }

    public function testDb()
    {
        $user = User::find(1); // jon@somecompany.com
        $this->assertEquals('Jon', $user->first_name);
        $company = $user->company;
        $this->assertEquals('somecompany', $company->name);
    }

}


I hope this information is helpful. It's 1AM where I am so it may be several hours before I reply again. Thanks for your help.

**Comment by janhenkgerritsen** [comment]
One obvious problem I see is that you are mixing Laravel test classes with Codeception. You should not be using `Illuminate\Foundation\Testing\TestCase` with Codeception, instead you should use the test classes you can generate with Codeception, for example `\Codeception\TestCase\Test`.

And if you use the Laravel5 module with Codeception you can set your environment by setting the `environment_file` configuration option, for example to `.env.testing`.

Maybe you can take a look at the Laravel 5 sample application at https://github.com/janhenkgerritsen/codeception-laravel5-sample. It does not use code coverage, but if you have everything configured correctly it will probably work.

**Comment by joelsaxton** [comment]
Ok, thank you very much.

**Comment by jdq22** [comment]
Hi all,

Actually, I'm confused when you say to look at your sample code at https://github.com/janhenkgerritsen/codeception-laravel5-sample because you're extending Illuminate\Foundation\Testing\TestCase in your TestCase.php... Your above comment is contradictory. Can you clarify?

I'm also having the same issue with the database switching whenever I use the coverage tags.

Thanks,
Jenna

**Comment by janhenkgerritsen** [comment]
The 'TestCase.php' and 'ExampleTest.php' files in the 'tests/' directory come with a new Laravel installation, but they are not used in my Codeception tests. But I agree they can be confusing, I will remove them tomorrow.

**Comment by jdq22** [comment]
Okay, so I implemented it the way you mentioned in your comments. I'm extending the Codeception class and using the .env.testing file, like you recommended. When I run the unit tests without the coverage tags, I get the tests to run, no problem. When I run the tests with the coverage tags, the tests just hang.

**Comment by janhenkgerritsen** [comment]
Ok I will look into it tomorrow, it's bedtime over here :)

**Comment by jdq22** [comment]
Thanks!

**Comment by joelsaxton** [comment]
I followed your advice and I was able to get the tests to run with the testing database and with the coverage switches. The problem seems to be in parsing the codeception yml file. If I set coverage to true and set whitelists/blacklists/etc it hangs. Even if I just set coverage to true like so:

coverage:
   enabled: true

...the tests hang and never complete. When I remove all the coverage stuff from the yml it works, but of course my coverage report shows zero percent. I will spend the rest of the time troubleshooting why the yml is breaking my testing. The good news is this is the final problem (hopefully).

**Comment by janhenkgerritsen** [comment]
I implemented code coverage for the [sample Laravel 5 application](https://github.com/janhenkgerritsen/codeception-laravel5-sample) and I got it working. Please compare your own configuration files (`codeception.yml` and suite configs, e.g. `unit.suite.yml`) with the configuration files of the sample application. 

I also ran into the problem of the wrong database being used, which I fixed by updating my suite config file. The problem was that the wrong .env file was being loaded because I had an invalid config file.

I implemented code coverage for Codeception 2.0 and 2.1 in the sample application, so make sure you select the correct branch for the version of Codeception you are using. The default branch of the repository is for Codeception 2.1.

**Comment by joelsaxton** [comment]
Ok. Thank you for your help.
