### ISSUE TITLE
Class `Codeception\Extension\Logger` is not defined.

### ISSUE THREAD

**Issue by MinkinD** [Codeception/Codeception#2135]
есть проблема с этим классом. 
Почему в phar файл лежит в папке src, а в репозитории в ext?
Из-под phar не удается запустить тесты, ругается на отстутствие этого класса.
При запуске из-под codecept, выдает новую ошибку:
Fatal error: Call to undefined method Codeception\Step\Action::getHumanizedAction() in tests\codecept\ext\Logger.php on line 118, в Step.php я не вижу такого метода вообще

**Comment by DavertMik** [comment]
Phar was broken, extensions were not loaded. Sorry for those issues. Please redownload phar, it should be available now
