### ISSUE TITLE
Local unit tests show 0% line coverage but x% class coverage

### ISSUE THREAD

**Issue by jdq22** [Codeception/Codeception#2136]
Hi,

I'm running the unit tests with the coverage tags (codecept run unit --coverage-html 'coverage/' --coverage-xml 'coverage/coverage.xml'). All the tests are passing, but when I pull up the coverage report in the browser, everything is at 0% except for Classes and Traits. The line coverage should be at least 5%.

Here's a screenshot of the coverage report:
https://www.dropbox.com/s/2vcbe4guv5kf6gh/Screenshot%202015-07-07%2015.46.56.png?dl=0

My codeception.yml file looks like the following:
https://www.dropbox.com/s/evj4rgnxopji071/Screenshot%202015-07-07%2015.49.33.png?dl=0

**Comment by janhenkgerritsen** [comment]
Which version of Codeception are you using? And can you show your suite configuration files?

**Comment by jdq22** [comment]
I'm using version 2.1.

unit.suite.yml
https://www.dropbox.com/s/ick003sh6rncql2/Screenshot%202015-07-08%2010.17.53.png?dl=0

.env.testing
APP_ENV=testing
APP_DEBUG=true
APP_KEY=someRandomString
DB_DEFAULT=sqlite_testing

**Comment by janhenkgerritsen** [comment]
I don't see anything wrong with the configuration. Can you try to run the  sample application and see if code coverage works for that? 

https://github.com/janhenkgerritsen/codeception-laravel5-sample

**Comment by jdq22** [comment]
Just tried it, and got back line coverage at 1%. So line coverage in general is definitely working... The weird thing is that I added everything in the repo to the whitelist, include property, and line coverage is still at 0%.

Not sure what to try next.

**Comment by janhenkgerritsen** [comment]
I'm not really sure either. But I have to admit I don't use code coverage very much.

**Comment by jdq22** [comment]
I believe I figured it out. We're using a namespace for the app folder, so because everything is namespaced by projectName and not by the actual path, I believe the codeception.yml file can't find the files to calculate the number of executed lines.

Arrived at this conclusion by cloning the example,copying and pasting the tests and the classes I'm testing, and following the structure word for word. Only difference between projects is that mine uses a namespace.
