### ISSUE TITLE
Please help me with logger

### ISSUE THREAD

**Issue by MinkinD** [Codeception/Codeception#2138]
1. the test fails with the exception: Call to undefined method Codeception\Step\Action::getHumanizedAction() in ...\tests\codecept\ext\Logger.php on line 118
In the class Step i do not see such a function.

2. Раньше в phar была папка с файлами vendor/monolog, сейчас нет ее там. Соответственно тест также падает с ошибкой [Codeception\Exception\ConfigurationException] Logger extension requires Monolog library to be installed. Т.е. если я запускаю через phar, то мне тоже надо как-то композером подтянуть monolog? если следовать указаниям в https://github.com/Codeception/Codeception/tree/master/ext#codeceptionextensionlogger.
Заранее спасибо.

**Comment by cjhille** [comment]
I'm having the same issue with the Logger extension
```
Fatal error: Call to undefined method Codeception\Step\Action::getHumanizedActio
n() in D:\xampp\htdocs\webception\vendor\codeception\codeception\ext\Logger.php
on line 118
```

Replacing line 118 with 
```
$this->logger->info($e->getStep()->getHumanizedActionWithoutArguments());
```
did the trick for me.

**Comment by mrwaim** [comment]
Same problem, the getHumanizedActionWithoutArguments worked.

**Comment by tomtomsen** [comment]
Its seems, that it got replaced by __toString in commit 28d6c9ea69f4a1302c11f45533e431d0635b4d37

**Comment by MinkinD** [comment]
how soon will be fixed?
