### ISSUE TITLE
Codeception 2.1.0 Laravel 4.1 : InvalidArgumentException Unknown getter 'date'

### ISSUE THREAD

**Issue by chungth** [Codeception/Codeception#2144]
I'm testing an Api using Api Suite of Codeception. 
My App was built basing on Laravel 4.1　
In Model I configure Eloquent Date Mutators (http://laravel.com/docs/4.2/eloquent#date-mutators) for 'paid_at' attribute. 
When I prepare data for testcase using  Laravel Eloquent object and save() method. 
I faced the error below: 

<img width="840" alt="unknown_getter_date" src="https://cloud.githubusercontent.com/assets/2556644/8610428/f1654f28-26ec-11e5-9929-daaacbacf00a.png">

When I used  Codeception 2.0.15 It was worked as normal. 
I'm not sure it's Codecetion 2.1.0 problem or not.

**Comment by janhenkgerritsen** [comment]
There should be no differences between the L4 module for Codeception 2.0 and 2.1.

Could you provide the code of your failing test and  possibly the code that is tested by this test? The exception in your screenshot does not really provide any info.

**Comment by chungth** [comment]
Sorry, I downgraded Codeception into 2.0 an everything work as normal.
