### ISSUE TITLE
Highlight step in console output

### ISSUE THREAD

**Issue by micaweb** [Codeception/Codeception#2147]
When I use `codecept run acceptance --steps`, is it possible to highlight a step other than `$I->wantTo()`?

Such as actions from `AceptanceTester` and `PageSteps` which are highlighted as yellow.

**Comment by DavertMik** [comment]
Step which includes substeps are highlighted. So if you create an action `login` in AcceptanceTester - it will be highlighted.

**Comment by micaweb** [comment]
Ok. Sometimes, even in a Cest, a test can have too many tasks.

So when I'm using comment helpers such as `$I->amGoingTo()`, `$I->expectTo()`, etc, they are not highlighted and end up being mingled with common tasks.

**Comment by DavertMik** [comment]
Yes, probably they should be some special highlighting for comment tasks as well...

> Sometimes, even in a Cest, a test can have too many tasks.

Group your actions and move them to Actor, PageObject or StepObject classes
There is a new chapter in guides: Reusing test code about this

**Comment by micaweb** [comment]
> There is a new chapter in guides: Reusing test code about this

It has been my dopamine reactor in the last 10 days. I thought I was done getting excited after Laravel.

**Comment by javigomez** [comment]
As far as I have seen the `$I->wantTo`, `$I->wantToTests` 
 
![screen shot 2015-07-12 at 18 55 43](https://cloud.githubusercontent.com/assets/1375475/8638805/b7d77dc2-28c6-11e5-92a9-e6505beeb422.png)

do not goes to the --steps but become the `title` of the tests. They are removed from being a step. In my example is the one in `pink`:

![screen shot 2015-07-12 at 18 54 55](https://cloud.githubusercontent.com/assets/1375475/8638808/c0e87376-28c6-11e5-8522-4d5a1e7e7960.png)

They do not appear as step because they are in fact the title of the scenario. If you want to show in the steps do `$I->comment`

In my previous example the `step` is in `white`, while the `substeps` appear in `blue`.

I don't see the lack of hightlight that you mention.

**Comment by micaweb** [comment]
I'm aware that `$I->wantTo()` becomes the title of the tests, but this behavior is incorrect, I wont be able to combine `$I->am()` with `$I->wantTo()`.

> I don't see the lack of hightlight that you mention.

Then why all steps of your scenario are in blue?

**Comment by javigomez** [comment]
You are right, the way it works now avoid to combine $I->am with $I->wantTo. If I would have to take the decission I would avoid to use it as a title and return them as normal steps.

Regarding steps/substeps, in my previous example:

Step:
- I install joomla
Substeps of $I->installJoomla:
- I open configuration page
- ...


The blue ones are Substeps of the $I->installJoomla Step. But I'm using a Codeception Module. So if you could show screen capture of what you have it will help a lot for me to understand what you mean.

**Comment by micaweb** [comment]
![ceptscreen-modified](https://cloud.githubusercontent.com/assets/3322806/8639039/f497629a-28a3-11e5-8a25-94d6b1164ced.jpg)

Ok. Please notice the lines with green arrows to its left in the captured screen.

They should be in a color different from white or the color from modules, helpers and steps.

So the eye can easily discern it and comfortably follow the test flow.

The `Herkin` language methods, `wantTo`, `expectTo`, `amGoingTo`, `lookForwardTo` and all the others bring a ton of clarity to the code.

**Comment by micaweb** [comment]
@javigomez  Can you show me a snippet of one of your modules please? From the docs, helpers and modules are identical.

**Comment by DavertMik** [comment]
We already use many colors in output ) Not sure I have a nice idea how to style comments better

**Comment by micaweb** [comment]
Mr. Bodnarchuk, if I use a helper, the action is white without steps, if I use a page/stepobject, the action is white and steps are in yellow. How do I make the action in blue without steps like in javigomez screenshot above?

**Comment by micaweb** [comment]
@DavertMik I believe light green is fine, I haven't seen it yet in `--steps` in my 50 tests and 400 assertions.

**Comment by micaweb** [comment]
> I believe light green is fine, I haven't seen it yet in `--steps` in my 50 tests and 400 assertions.

Actually my statement is incorrect, `haveFriend` will output a header and footer in light green.
