### ISSUE TITLE
Uncaught TypeError: chart.scatter.onlyCircles is not a function

### ISSUE THREAD

**Issue by dutchiexl** [Codeception/Codeception#2157]
I get a javascript error. Probably, the javascript dependency was updated

**Comment by DavertMik** [comment]
Can you specify *where* do you get this error?

**Comment by dutchiexl** [comment]
I got in on the homepage(dashboard) the last weeks, now after last update it's gone but I get a new error

```2nv.d3.min.js:2 nvd3 warning: `tooltips` has been deprecated.  use chart.tooltip.enabled() instead
2nv.d3.min.js:2 nvd3 warning: `tooltipContent` has been deprecated.  use chart.tooltip.contentGenerator() instead
2d3.min.js:2 Uncaught TypeError: Cannot read property 'x' of null
d3.min.js:2 Uncaught TypeError: Cannot read property 'x' of nullQr @ d3.min.js:2Ir @ d3.min.js:2iu @ d3.min.js:2t @ d3.min.js:4ta.geom.voronoi @ d3.min.js:4N @ nv.d3.min.js:7
dashboard.html:1297 Uncaught TypeError: Cannot read property 'point' of undefined````

When I hover over the points in the chart new errors pop up:

```Uncaught TypeError: Cannot read property 'point' of undefined```
