### ISSUE TITLE
Generating Cest in namespace generates invalid PHP code.

### ISSUE THREAD

**Issue by roland-jungwirth** [Codeception/Codeception#2163]
When generating a test using the command 
```
codecept generate:cest --config="points-to-include-directory" acceptance Test
```
the resulting code adds this to the TestCest.php:
```
use backend\\AcceptanceTester;
```
This is invalid code, resulting in a PHP error
> PHP Parse error:  syntax error, unexpected '\' (T_NS_SEPARATOR)

This is version 2.1.0 running inside a Symfony 2.6 project.

**Comment by Naktibalda** [comment]
You are using 2.1.0-beta release,
This issue has been fixed in 2.1.0-rc1 release.

Download the final 2.1.0 build and use it.

**Comment by roland-jungwirth** [comment]
I have updated (via composer) to version 2.1.1 and the same is reproducible. It still creates the line
```
use backend\\AcceptanceTester
```
which throws the above error.

**Comment by roland-jungwirth** [comment]
I have now tested this on different platforms (Ubuntu and iOS), with and without namespace and with and without custom directory using both Composer and phar (both v 2.1.1). In both cases these are the steps to recreate this issue:

1. create a new directory
2. download codecept.phar and put in new directory -- success
4. Initialise codeception in root directory -- success
  * php codecept.phar bootstrap --namespace frontend
5. Run tests -- success
  * php codecept.phar run
6. Create cest -- success
  * php codecept.phar generate:cest acceptance Issue
9. Run tests -- fail
  * php codecept.phar run
  * Parse error: parse error, expecting `"identifier (T_STRING)"' in /tests/acceptance/IssueCest.php on line 3

**Comment by roland-jungwirth** [comment]
tomtomsen, this
```
$ns .= "use $namespace\\$actor;";
```
makes it more readable?
If manually changed the code and confirm that it generates the correct code now.

**Comment by mauriciopiber** [comment]
I did a fork from codeception and fix it for me. I don't know to much about contributions and pull requests, I can help to work with the generators (scaffolding) but first I need to know what are the rules to make a pull request "the right way", anyone has this answer?

Appreciate.

**Comment by Naktibalda** [comment]
The only important rule is "make a pull request to current branch, which is 2.1 now"
I've looked at your repository and noticed that you modified composer.json file, that change can't be merged, so you need to revert it.
