### ISSUE TITLE
Database queries only allow equals

### ISSUE THREAD

**Issue by bendauphinee** [Codeception/Codeception#2164]
When running testing, I want to use a LIKE condition in my parameters, but cannot.

**Comment by DavertMik** [comment]
You can extend Db module and write your own assertion. You can also access `dbh` object from your Helper class using `$this->getModule('Db')->dbh`. We can't include all possible cases and create ORM from a Db module )

**Comment by bendauphinee** [comment]
While you can't create an ORM, it would make sense that LIKE be a condition that testing support by default. For example, in testing a database write that uses NOW() for a date field, I don't want to have to retrieve that record to see if it exists, when I could do a LIKE to match it.
