### ISSUE TITLE
Add amOnRoute and seeCurrentRouteIs to Symfony2 module

### ISSUE THREAD

**Issue by Yanncha** [Codeception/Codeception#2171]
Hi all !

Adding functions such as amOnRoute and seeCurrentRouteIs to Symfony2 module could make route testing easier (I've seen that such functions exist in other modules e.g. Laravel5).

**Comment by DavertMik** [comment]
Yeah. Unfortunately we don't have a Symfony module maintainer :( A person who will guide development of Symfony2 module, fix bugs, and introduce features like those.  

Maybe you are interested? ;)

**Comment by Yanncha** [comment]
Well, as for now, I'm not sure my programming skills may be enough to do so.

**Comment by DavertMik** [comment]
@raistlin hey, do you feel you can get this implemented? That would be really cool

**Comment by raistlin** [comment]
Ok, just give me some time ;)
