### ISSUE TITLE
[PHPUnit_Framework_Exception] - on the second API test run - Codeception 2.1.1

### ISSUE THREAD

**Issue by ognezdyonova** [Codeception/Codeception#2177]
Good evening,

My REST API tests worked fine in Codeception 2.0.13 version. I updated framework to 2.1. Run the first API test - passed successful. I ran the second time and got the following error:

```
C:\Users\ognezdyonova\workspace\IC_New>.\vendor\bin\codecept.bat run tests/apico
nnect/InvoiceCentralUnsubscribeCept.php
Codeception PHP Testing Framework v2.1.1
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

←[1mApiconnect Tests (1) ←[22m--------------------------------------------------
--------------------------------------------------------------------------------
------------
←[35;1mTest Scenario BTC API - InvoiceCentralUnsubscribe←[39;22m (InvoiceCentral
UnsubscribeCept)


  [PHPUnit_Framework_Exception]
  mkdir(): File exists



run [-c|--config CONFIG] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]]
[--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--co
verage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-X
ML]] [--coverage-text [COVERAGE-TEXT]] [--no-exit] [-g|--group GROUP] [-s|--skip
 SKIP] [-sg|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild]
 [--] [<suite>] [<test>]
```
If I restart the laptop and re-run test - the first one passes and the second one failed with the same error.

Thank you in advance!

**Comment by DavertMik** [comment]
Please execute tests with `-vvv` options. Looks like some directory is trying to be created twice. Afaik test execution by itself is not trying to create dir.

**Comment by ognezdyonova** [comment]
Michael, please messages below:

C:\Users\ognezdyonova\workspace\IC_New>.\vendor\bin\codecept.bat run tests/apico
nnect/InvoiceCentralUnsubscribeCept.php -vvv
Codeception PHP Testing Framework v2.1.1
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

←[36m  Rebuilding ApiconnectTester...←[39m

←[1mApiconnect Tests (1) ←[22m--------------------------------------------------
--------------------------------------------------------------------------------
------------
Modules: ←[32mREST, PhpBrowser, Db, Asserts, ApiconnectHelper←[39m
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
---
←[35;1mTest Scenario BTC API - InvoiceCentralUnsubscribe←[39;22m (InvoiceCentral
UnsubscribeCept)
Scenario:



  [PHPUnit_Framework_Exception]
  mkdir(): File exists



Exception trace:
 () at C:\Users\ognezdyonova\workspace\IC_New\vendor\codeception\codeception\src
\Codeception\Subscriber\ErrorHandler.php:48
 Codeception\Subscriber\ErrorHandler->errorHandler() at n/a:n/a
 mkdir() at C:\Users\ognezdyonova\workspace\IC_New\vendor\codeception\codeceptio
n\ext\Recorder.php:207
 Codeception\Extension\Recorder->before() at n/a:n/a
 call_user_func() at C:\Users\ognezdyonova\workspace\IC_New\vendor\symfony\event
-dispatcher\EventDispatcher.php:164
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at C:\Users\ogn
ezdyonova\workspace\IC_New\vendor\symfony\event-dispatcher\EventDispatcher.php:5
3
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at C:\Users\ognez
dyonova\workspace\IC_New\vendor\codeception\codeception\src\Codeception\PHPUnit\
Listener.php:114
 Codeception\PHPUnit\Listener->fire() at C:\Users\ognezdyonova\workspace\IC_New\
vendor\codeception\codeception\src\Codeception\PHPUnit\Listener.php:90
 Codeception\PHPUnit\Listener->startTest() at C:\Users\ognezdyonova\workspace\IC
_New\vendor\phpunit\phpunit\src\Framework\TestResult.php:325
 PHPUnit_Framework_TestResult->startTest() at C:\Users\ognezdyonova\workspace\IC
_New\vendor\phpunit\phpunit\src\Framework\TestResult.php:541
 PHPUnit_Framework_TestResult->run() at C:\Users\ognezdyonova\workspace\IC_New\v
endor\phpunit\phpunit\src\Framework\TestCase.php:702
 PHPUnit_Framework_TestCase->run() at C:\Users\ognezdyonova\workspace\IC_New\ven
dor\phpunit\phpunit\src\Framework\TestSuite.php:738
 PHPUnit_Framework_TestSuite->run() at C:\Users\ognezdyonova\workspace\IC_New\ve
ndor\codeception\codeception\src\Codeception\PHPUnit\Runner.php:89
 Codeception\PHPUnit\Runner->doEnhancedRun() at C:\Users\ognezdyonova\workspace\
IC_New\vendor\codeception\codeception\src\Codeception\SuiteManager.php:149
 Codeception\SuiteManager->run() at C:\Users\ognezdyonova\workspace\IC_New\vendo
r\codeception\codeception\src\Codeception\Codecept.php:200
 Codeception\Codecept->runSuite() at C:\Users\ognezdyonova\workspace\IC_New\vend
or\codeception\codeception\src\Codeception\Codecept.php:172
 Codeception\Codecept->run() at C:\Users\ognezdyonova\workspace\IC_New\vendor\co
deception\codeception\src\Codeception\Command\Run.php:184
 Codeception\Command\Run->execute() at C:\Users\ognezdyonova\workspace\IC_New\ve
ndor\symfony\console\Command\Command.php:259
 Symfony\Component\Console\Command\Command->run() at C:\Users\ognezdyonova\works
pace\IC_New\vendor\symfony\console\Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at C:\Users\ognezdyonova\
workspace\IC_New\vendor\symfony\console\Application.php:195
 Symfony\Component\Console\Application->doRun() at C:\Users\ognezdyonova\workspa
ce\IC_New\vendor\symfony\console\Application.php:126
 Symfony\Component\Console\Application->run() at C:\Users\ognezdyonova\workspace
\IC_New\vendor\codeception\codeception\codecept:28


run [-c|--config CONFIG] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]]
[--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--co
verage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-X
ML]] [--coverage-text [COVERAGE-TEXT]] [--no-exit] [-g|--group GROUP] [-s|--skip
 SKIP] [-sg|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild]
 [--] [<suite>] [<test>]

**Comment by Naktibalda** [comment]
It is clear that the error happens [here](https://github.com/Codeception/Codeception/blob/4f8d3b5cce0c5742defa1f979ddd45255167b2bc/ext/Recorder.php#L207).

But I can't figure out how it is possible to get a duplicate directory name on the second run.
Directory name includes timestamp, so the only way to get a duplicate is to run it twice in the same second.

**Comment by Anahkiasen** [comment]
Same error here

**Comment by Anahkiasen** [comment]
Dumping the directory it's trying to create I'm getting this:

```
/vagrant/tests/codeception/_output/record__ForgeCommandsCommandsArtistsDeduplicateCommandTest.testCanDeduplicateArtists"
```

No timestamp.

**Comment by DavertMik** [comment]
> But I can't figure out how it is possible to get a duplicate directory name on the second run.
Directory name includes timestamp, so the only way to get a duplicate is to run it twice in the same second.

> No timestamp.

It isn't clear for me either why nothing is inserted in a place where timestamp is expected:

```
$this->dir = codecept_output_dir() . "record_{$this->seed}_$testName";
```

Where `$this->seed` == time().

**Comment by DavertMik** [comment]
Probably I got the fix
