### ISSUE TITLE
Queue module clearQueue function not working with Beanstalk queue

### ISSUE THREAD

**Issue by oblogic7** [Codeception/Codeception#2179]
I would like to verify that the correct number of jobs is being submitted to a queue.  However, it appears that the clearQueue function is not working with my beanstalk queue.  

```
$I->clearQueue('queue_name');
$I->seeEmptyQueue('queue_name');
```

The code above fails every time if there are existing jobs on the queue.  is this not supported for beanstalk queues?

**Comment by Naktibalda** [comment]
Fixed by #2917
