### ISSUE TITLE
Can't get multi sessions to work in Cest tests

### ISSUE THREAD

**Issue by mkudenko** [Codeception/Codeception#2180]
Using Codeception 2.1, phantomjs 1.9.7 and that [example](http://codeception.com/docs/03-AcceptanceTests#Multi-Session-Testing).

My test method:

```php
public function testMessagesWorkCorrectly(\Step\Acceptance\Admin $I)
{
    $I->loginAsAdmin();

    $I->click('Close Voting');

    $voter = $I->haveFriend('voter');
    $voter->does(function(AcceptanceTester $I) {
        $I->see('Voting closes in');
    });
}
```
**Result:** the voter isn't getting a new session.

Am I doing something wrong? Any suggestions?

**Comment by micaweb** [comment]
Same thing here:

        $visitor = $I->haveFriend('visitor');

        $visitor->does(function(AcceptanceTester $I) use ($category)
        {
            $I->amOnPage('/');

            $I->logout();

            $I->click($category->parent->name);
            $I->click($category->name);

            $I->see($category-name, 'h2');
        });

Here I have to logout as admin to test as a visitor a modification made by the admin.

Codeception 2.1 and PhpBrowser.

**Comment by mkudenko** [comment]
Apparently that's a phantomjs issue. Multi sessions work fine with Selenium and Chrome.

**Comment by DavertMik** [comment]
Yes, we multisession testing in PhantomJS is not supported. At least by us
