### ISSUE TITLE
cURL error 7: couldn't connect to host when page is under HTTPS

### ISSUE THREAD

**Issue by petrjirasek** [Codeception/Codeception#2186]
Hello,

I have a problem with acceptance test (I am using PhpBrowser) when page is under https. I have simple test:

```php
$I = new AcceptanceTester($scenario);
$I->wantTo('log in user');
$I->amOnPage('/');

$I->click('Log in');
$I->see('Log in');
$I->submitForm("#frm-signInForm", array(
    "email"     =>  "mail@example.com",
    "password"  =>  "123456"
));
$I->see('My profile', "h1");
$I->seeInCurrentUrl('my-profile');
```

When tha page doesn't require https, the test passes. But then I changed the settings in my application route to require https on log in page and then the test fails with this:

```
[GuzzleHttp\Exception\ConnectException] cURL error 7: couldn't connect to host  
                                                                                  

Scenario Steps:

2. $I->click("Log in")
1. $I->amOnPage("/")
```

Other tests which not works with pages under https works well too.

Am I wrong? Any suggestions?

Thank you for your help
Petr

**Comment by DavertMik** [comment]
Which version are you using?

**Comment by Jirda** [comment]
I am using v2.1.0.

Thanks.

**Comment by DavertMik** [comment]
Please try upgrading to 2.1.1 and tell if it was fixed

**Comment by Jirda** [comment]
It doesn't help. Problem is the same with 2.1.1.

**Comment by Naktibalda** [comment]
Are you using a self-signed SSL certificate?

Try setting verify option to false

http://codeception.com/docs/modules/PhpBrowser#Configuration
http://docs.guzzlephp.org/en/latest/request-options.html#verify

**Comment by petrjirasek** [comment]
Sure, I have. I tried this and it didn't help to set verify option to false.

**Comment by Naktibalda** [comment]
Are you able to connect to that page using curl in command line or PHP curl functions?

**Comment by debashisdeb** [comment]
Was this resolved ?

**Comment by Naktibalda** [comment]
No, have you got a public website to demonstrate this issue?
