### ISSUE TITLE
Fatal error when calling Stub::makeEmpty on interfaces

### ISSUE THREAD

**Issue by EnricoGsell** [Codeception/Codeception#2195]
Until version 2.0.15 I was able to stub `interfaces` via 
`Stub::makeEmpty('MyInterface', array('methodStub' => 'stuff'));`
When updating to 2.0.15 (also 2.1) I do now get the following error:
```
PHP Fatal error:  Call to a member function hasMethod() on a non-object in /vagrant/vendor/codeception/codeception/src/Codeception/Util/Stub.php on line 505
```
This seems to be due to the changes done in #2082 . At least after I removed those lines, the tests were running again.

**Comment by Naktibalda** [comment]
Fixed
