### ISSUE TITLE
can't take screenshot when use the extension recorder

### ISSUE THREAD

**Issue by rannk** [Codeception/Codeception#2209]
Codeception version 2.1
Browser: chrome
when my test going to this step

```
$I->executeInSelenium(function (\Facebook\WebDriver\RemoteWebDriver $webdriver) {
            $handles=$webdriver->getWindowHandles();
            $last_window = end($handles);
            $webdriver->switchTo()->window($last_window);
});
```

The test will be failed, and have this error

```
[UnknownServerException] unknown error: cannot take screenshot
from unknown error: Failed to capture tab: unknown error
JavaScript stack:
Error: Failed to capture tab: unknown error
    at checkForExtensionError    (chromeextension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:37:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:72:7)
  (Session info: chrome=44.0.2403.89)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 52 milliseconds
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'WIN-A1G4V3OTFF2', ip: '10.7.133.169', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.7.0_51'
Session ID: 57f1570e72020349efcc3b97d88c000f
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=WIN8, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\ADMINI~1\AppData\Local\Temp\2\scoped_dir4880_19663}, rotatable=false, locationContextEnabled=true, version=44.0.2403.89, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]  
```

**Comment by DavertMik** [comment]
Do you have ideas how to solve this issue? Looks like we need to catch this exception, or to handle switching windows somehow...

**Comment by rannk** [comment]
I think it's hard to catch the snapshot exception on codeception code. I wish could we have a switch to control which step we can skip to capture a screenshot. like I add a code in the afterstep function of Record, I can skip the snapshot of switching windows

if(stripos($e->getStep(), "lambda function") == true){
        return;
}

**Comment by reinholdfuereder** [comment]
@DavertMik
I may miss the point due to my lack of (insider) Codeception knowledge, but this

> I wish could we have a switch to control which step we can skip to capture a screenshot. like I add a code in the afterstep function of Record, I can skip the snapshot of switching windows

... was IMHO actually implemented mid of last year: see `ignore_steps` from https://github.com/Codeception/Codeception/commit/51b8cba4be0589e632aaf3ea01d7e1e9a4594858 or https://github.com/Codeception/Codeception/pull/5015

=> Does that solve this issue?

**Comment by Naktibalda** [comment]
Recorder catches screenshot exceptions since Codeception 2.5.1 https://github.com/Codeception/Codeception/pull/5221
