### ISSUE TITLE
Issues with Recorder and Logger extension

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#2216]
I'm having two issues that are preventing me to use Recorder and Logger extension. 

## Issue with Recorder: Folder exists
The first one is when a folder that recorder wants to record exist you get:

<img width="783" alt="screen shot 2015-07-27 at 13 32 06" src="https://cloud.githubusercontent.com/assets/1375475/8904840/229d4e14-3463-11e5-9b18-e16e59e2cd21.png">

This happens if you run it once and generates the folder `/tests/_output/record__tagCest.create`. Then the second time you run it, the folder exists and it doesn't run.

Shouldn't `Recorder extension` remove the existing folder in case it exists at https://github.com/Codeception/Codeception/blob/2.1/ext/Recorder.php#L207?

I have just removed by hand the folders. But wonder if should be Recorder the one who does it.

## Issue with Logger: Call to undefined getHumanizedAction()
The second issue I'm getting is (have tried to build, with no success): 

```

Acceptance Tests (3) -----------------------------------------------------------
Trying to test Product creation in Frontend (productCest::create)... 
Fatal error: Call to undefined method Codeception\Step\Action::getHumanizedAction() in /vendor/codeception/codeception/ext/Logger.php on line 118



FATAL ERROR. TESTS NOT FINISHED.
Call to undefined method Codeception\Step\Action::getHumanizedAction() 
in /vendor/codeception/codeception/ext/Logger.php:118
```

**Comment by javigomez** [comment]
If I dump the step:

<img width="485" alt="screen shot 2015-07-27 at 13 52 06" src="https://cloud.githubusercontent.com/assets/1375475/8905337/b6bcb1dc-3465-11e5-9994-8cb821b4657d.png">

I get:

<img width="360" alt="screen shot 2015-07-27 at 13 52 26" src="https://cloud.githubusercontent.com/assets/1375475/8905340/c144f376-3465-11e5-8c25-ab523baac220.png">


If I do:

```php
$step = $e->getStep();
$message = $step->getHumanizedAction();
var_dump($message);die;
```

I get: string(19) "As an Administrator"

The problem seems to be with this type of step:

`$I->am('Administrator');`

**Comment by javigomez** [comment]
Also mention that with recorder I just get empty folders:

<img width="329" alt="screen shot 2015-07-27 at 16 35 30" src="https://cloud.githubusercontent.com/assets/1375475/8908486/a5c1b136-347c-11e5-8b8a-4b85df55c66a.png">

No matter that I set configuration not to delete:

<img width="625" alt="screen shot 2015-07-27 at 16 37 10" src="https://cloud.githubusercontent.com/assets/1375475/8908508/c2a0bf36-347c-11e5-8af2-f025ab7a7d09.png">

**Comment by DavertMik** [comment]
> This happens if you run it once and generates the folder /tests/_output/record__tagCest.create. Then the second time you run it, the folder exists and it doesn't run.

It is expected that those folder names are unique. Strange that there is no `seed` value inside your filder name.

**Comment by javigomez** [comment]
I found my issue, my configuration needs to be like this:

```
config:
        Codeception\Extension\Recorder:
            delete_successful: false
            module: JoomlaBrowser
```

Because I'm using the JoomlaBrowser Extension http://codeception.com/addons#Extensions

Solved. Thanks

**Comment by javigomez** [comment]
By the way. Recorder rocks!!! is really cool.
