### ISSUE TITLE
Laravel Event Listeners Not Registering For Functional Tests

### ISSUE THREAD

**Issue by oblogic7** [Codeception/Codeception#2218]
I have a group of functional tests that I am using to test a Laravel 4 Artisan command.  The group will execute successfully when called on its own `-g group-name`.  However, when executing the entire Functional suite, this particular group of tests fail.

The artisan command simply fires an event which is handled by a listener for processing.  I have debugged the test execution and found that the event listeners are only registered when executing the test group.  They are nowhere to be found when executing the suite.  This is what is causing the tests to fail.

I cannot figure out why the listeners are not registering properly.  Any ideas as to what could cause this behavior?

Here is my Functional.suite.yml file...
```
# Codeception Test Suite Configuration

# suite for functional (integration) tests.
# emulate web requests and make application process them.
# (tip: better to use with frameworks).

# RUN `build` COMMAND AFTER ADDING/REMOVING MODULES.

class_name: TestGuy
modules:
    enabled: [Filesystem, TestHelper, Laravel4, Db, Queue]
```

And my main codeception.yml file...
```
paths:
    tests: tests
    log: tests/_log
    data: tests/_data
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
modules:
    config:
        Laravel4:
            cleanup: false
            filters: false
        Queue:
            type: 'beanstalkd'
            host: '127.0.0.1'
            port: 11300
            timeout: 120
        Db:
            dsn: 'mysql:host=localhost;dbname=test_database'
            user: 'db_user'
            password: 'SECRET'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
extensions:
    enabled:
        - Codeception\Extension\Phantoman
    config:
            Codeception\Extension\Phantoman:
                port: 4444
                debug: true
```

**Comment by janhenkgerritsen** [comment]
What version of Codeception are you using?

**Comment by oblogic7** [comment]
Running version 2.1.1.

**Comment by janhenkgerritsen** [comment]
Can you show the relevant tests and code? With that I can try to reproduce the issue myself.

**Comment by oblogic7** [comment]
Here is the base of the code.  Some non-essential code has been removed but you should be able to get the idea of what is happening.  Other tests exist and execute in the suite before the tests included in the gist.

https://gist.github.com/oblogic7/b1cdd4032c18dccfdcc6

**Comment by janhenkgerritsen** [comment]
I tried to reproduce the issue in the Laravel 4 sample application, but all seems to work fine.

The code I wrote to reproduce the issue can be seen in the  `artisan-event` branch of the Laravel 4 sample application at https://github.com/Codeception/sample-l4-app/tree/artisan-event. All changes are contained in commit codeception/sample-l4-app@4d8f9a31a638e9b81dadb7bd7f3aceda13a8c7ce.

The event listener I created simply writes a message with the Codeception debug helper, when running tests you can view this output by adding the `-vv` flag. I ran the following commands, and with all these test runs I saw the expected output:

```
codecept run functional -vv
codecept run functional -g event -vv
codecept run tests/functional/CommandWithEventCest.php -vv
codecept run tests/functional/CommandWithEventCest.php -g event -vv
```

Do you agree this is a very basic implementation of your issue?

One question I still have for you, where do you register your event listeners? In the implementation above I register the listener in the `app\start\global.php` file. Maybe you use another location?

**Comment by oblogic7** [comment]
That is a good generalization of the scenario being tested.  

The events are registered via a BaseListener class that is called from global.php.  That should not make a difference though.  

I'm wondering if it has something to do with the module combination in the codeception configuration.  I'm going to debug the listener registration during tests and see if I can tell why they aren't registering correctly.

**Comment by oblogic7** [comment]
After further troubleshooting, I have been able to identify that the other tests are somewhat responsible for the issue, but have been unable to reproduce my findings on the branch you created on the sample app.

The problem appears if any kind of HTTP request is made in any test before the group that is failing.  Both of these commands cause the group to fail if called in any preceding tests.

```$I->amOnPage('/')
$I->sendAjaxRequest('/route')```

I'm still digging around to see what is different from my setup and the sample app.  Maybe this info will give you an idea of what is happening.

**Comment by janhenkgerritsen** [comment]
The Laravel4 module bootstraps the Laravel application when it is constructed, but it also bootstraps the application on each request. So your comment made me think, do you by any chance register the listeners in a file you call with `require_once`? I implemented that in Codeception/sample-l4-app@ef74657ccf6906f8d76852f6efc2d3dbf9113734 in the artisan-event branch of the sample Laravel 4 application, and that does reproduce your issue.

**Comment by oblogic7** [comment]
BINGO! That is probably exactly what is happening.  

`require_once app_path() . '/events/BaseListener.php';`

I will change that over and test.  I will let you know how it goes.

**Comment by oblogic7** [comment]
Changing the require_once to require is allowing the event to fire, but the listener is being called twice.  Any ideas about that or should I open a new issue?

**Comment by janhenkgerritsen** [comment]
Yeah I ran into that same problem, that is probably due to the fact the file that registers the listeners is included twice. Once on construction of the Laravel module and once before a request. I solved this by simply calling `Event::forget('event-name')` before calling `Event::listen()`.

**Comment by oblogic7** [comment]
Interesting... This project already has over 100 event listeners.  Is there a better way to clear all instead of each individual listener?

**Comment by janhenkgerritsen** [comment]
There is no method to clear all registered listeners as far as I know. But you could try to instantiate a new `Illuminate/Events/Dispatcher` instance in your container. Take a look at `Illuminate/Events/EventServiceProvider` to see how it's done by Laravel.

**Comment by oblogic7** [comment]
Will look into that thanks.
