### ISSUE TITLE
View composer only runs for first test

### ISSUE THREAD

**Issue by janhenkgerritsen** [Codeception/Codeception#2219]
I received the following email of a possible issue with the Laravel 4 module:

Hello,

I'm working with L4 module, and running codeception 2.0.
I testing acceptance, and run into this issue. Maybe you have insights/suggestion?

In Laravel, I define a view composer. And set it up via ServiceProvider 

```
View::composer('profile', function($view)
{
    $view->with('navMenu', 'xyz');
});
```

And in my test case I have a few functions that use that view in this form: 

```
$I->amOnPage('/preview/placement/362');
```

The issue is that   ONLY the first test function the 'navMeu' variable is defined. For any other test function I get an exception that $navMenu is not defined. 

Any ideas? thaks,

aner

Here is more code
In Cest file:

```
//First function 'ses' the $value variable and renders correctly 
public function testMRFormatting(\AcceptanceTester $I) 
    {   

        $I->am('SiteOwner');
        $I->wantTo('placement html output: non-breaking of membership rewards');

        $I->amOnPage('/preview/placement/362');

    }       

//Second  function Failes to see $value variable 
    public function testDaggerEntityConversion(\AcceptanceTester $I)
    {   
        $I->am('SiteOwner');
        $I->wantTo('make sure daggers get converted to plaintext ** and ***');
$I->amOnPage('/preview/placement/363');

    }
```

Exception:

```
can't be on page "/preview/placement/363":
ErrorException: Undefined variable: navMenu (View: /home/aner/www/emailstudio/app/views/layouts/navbar-bs3.blade.php)
```

**Comment by Aner-Git** [comment]
Jan-Henk,

Thanks for putting this up. I use codeception 2.07. 

However, I believed I traced the issue, and its related to using static variables. 
I don't think its a codeception per-se issue, or Laravel. Its a problematic scenario that happens. 

As a reminder:  static variables are initialize once in any PHP script. 

So here is what was happening: From my serviceProvider I was calling the build function:

```php
class MenuBuilder{
//....
 public static function build($user){

   //  ISSUE HERE. Once $menu is set in the PHP runtime
   //  it is not reinitialized and subsequent code not called. 
   //  And hence $navMenu is only set once for first test

        if(is_null(static::$menu)){     
            static::$menu = new static($user);
           static::$menu->compose();  //this function set the views. Not shown. 
        }   
    }  
   
private compose(){
View::composer(['layouts.login',
                        'layouts.master',
                        'layouts.public',
                        'layouts.admin',
                        'layouts.master-bs3'],
                        function($view)use($menu){
                $view->with('navMenu', $menu);   //navMenu was ONLY defined for first test.
            // end main nav menu
            });

}

 //....
}
```
The build function WAS called correctly every time from the ServiceProvider. But, (!!!) once the static was set, subsequent call were not 'reinitialize' the view. 

Possible fix: 
Running each function of testXXX in its own process, but that can be costly.

**Comment by janhenkgerritsen** [comment]
OK, so it was a problem with your application code. To be sure I ran some tests with view composers but everything works as it should.
