### ISSUE TITLE
Can't replicate dependency injection example from docs

### ISSUE THREAD

**Issue by micaweb** [Codeception/Codeception#2222]
I'm following the example from http://codeception.com/docs/07-AdvancedUsage#Dependency-Injection

Currently I have this in my Cest:

    /**
     * @var Helper\MyHelper
     */
    protected $myHelper;
 
    protected function _inject(\Helper\MyHelper $myHelper)
    {
        $this->myHelper = $myHelper;
    }

And generates the following error: 

`Failed to inject dependencies in instance of 'HomeCest'. Failed to create instance of 'Helper\MyHelper'. Failed to
create instance of 'Codeception\Lib\ModuleContainer'. Parameter 'config' must have default value.`

This is my `Helper`:

	<?php
	namespace Helper;

	class MyHelper extends \Codeception\Module
	{
	    public function login($email, $password = '')
	    {
			$I = $this->getModule('PhpBrowser');

			$I->fillField('email', $email);
			$I->fillField('password', $password);
			$I->click('Ok!');
	    }
	}

My goal is, if I can get this working, would be to create a BaseCest where I can inject all helpers, pageobjects and stepobjects.

The helper is properly loaded in acceptance.suite.yml.

**Comment by cajones17** [comment]
I've also had this issue, is this going to be triaged soon, or should I plan on working around this?

**Comment by DavertMik** [comment]
I'm working on it. Patch will be released soon

**Comment by micaweb** [comment]
I have pushed my `codeception` to `9af9b54` (Aug 1), and when I try this again, the helper methods play silently, nothing is show when in `--steps`. And it won't work at all with `page/stepobjects`.

The injection of pages and steps is far more important, since naturally `codeception` injects helpers into `$I`.

The deeper I get into acceptance tests in my current app, the less and less code I have to write, thanks to the page object approach.

That being said, the moment I can get to inject pages and steps into a `BaseCest`, it will be an onslaught.

**Comment by cajones17** [comment]
@DavertMik thanks!

**Comment by micaweb** [comment]
@cajones17 Were you able to properly replicate this? If yes can you please show me your helper and cest?

**Comment by janbogdanski** [comment]
Hello,
We tried inject into Cest _inject method (v2.1.5)
    public function _inject(Step\Acceptance\User $user)

Which causes
```
 [Codeception\Exception\InjectionException]
  Failed to inject dependencies in instance of 'GuiCest'. Failed to create instance of 'Step\Acceptance\User'. Failed to create instance of 'Codeception\Scena
  rio'. Failed to resolve dependency 'Codeception\TestCase'.
```
Injecting into _before, _after, or any public test method works properly, can you check?
