### ISSUE TITLE
Avoiding static methods where possible

### ISSUE THREAD

**Issue by nzod** [Codeception/Codeception#2226]
Static methods don't help testability. The alternatives' (singletons, simple functions) usage could be sometimes less elegant to type out, but would immensely aid writing tests for them.

**Comment by DavertMik** [comment]
Ok, please point to specific issues where static methods are available. Except `Configuration` class

**Comment by nzod** [comment]
There are other static methods but mainly I mean this for Configuration. I would need to mock the Finder usage to test wildcard includes (pull #2192) but ran into a wall with this.

Maybe I'm missing something but I want to properly test it and don't see how it could be done in isolation in the presence of static functions (except using AspectMock, but would like to avoid that).

Perhaps I rushed with filing this issue, could you please give me a pointer on how to approach this?

**Comment by nzod** [comment]
Ah, now I did RTFM... so a *cli* test should be created.
