### ISSUE TITLE
Early-checked include paths

### ISSUE THREAD

**Issue by a-acs** [Codeception/Codeception#2227]
I feel that a test run shouldn't start with any invalid include paths. I propose checking for validity of include paths early on configuration load.

I'm not aware of any issue this fail-early method would cause, please correct me if I'm wrong. Also, I'm not aware of any benefit of allowing tests to run before an include failure.

Failure should also include information on exactly which include is the culprit.

**Comment by DavertMik** [comment]
Could you be more specific about include paths? What do you mean? (better to point to line of code you actually refering to)

**Comment by nzod** [comment]
Sorry, I mean checking existence & readability of include paths given in codeception.yml configs.
[Link to commit](https://github.com/nzod/Codeception/commit/b80ac8612327e2340fc35289b405e0cb253a27cc)

**Comment by Naktibalda** [comment]
@DavertMik How do you like this proposal?
