### ISSUE TITLE
2.1.1 - Cannot inject Helpers: Injection Exception - Parameter 'config' must have default value.

### ISSUE THREAD

**Issue by pohnean** [Codeception/Codeception#2230]
I'm facing an issue when injecting a Helper class into a Cest class.

`[InjectionException] Failed to inject dependencies in instance of 'tests\codeception\backend\DemoCest'. Failed to create instance of 'tests\codeception\backend\Helper\DemoHelper'. Failed to create instance of 'Codeception\Lib\ModuleContainer'. Parameter 'config' must have default value.`

This issue has also been mentioned by someone else on stackoverflow: http://stackoverflow.com/questions/31687299/cant-replicate-codeception-dependency-injection-example-from-docs

**Comment by DavertMik** [comment]
Just fixed it. Get the latest Codeception from `2.1` branch or wait for `2.1.2` to be released

**Comment by pohnean** [comment]
Wow. That's fast!
