### ISSUE TITLE
No way to wait for a field to get focus

### ISSUE THREAD

**Issue by rawevolution** [Codeception/Codeception#2233]
I'm having a problem with loading a form via AJAX. I wait for the form element to appear and then submit the form. The problem is that once the form is loaded the username gets focus and this interrupts the webdriver whilst it is in the middle of filling out another field.
I tried $I->waitForJS("$('#register-form-username').is('focus')", 30); but that didn't work.
I'm currently using a regular wait method but would prefer something that doesn't waste time.
This only seems to be a problem with PhantomJS so far and not Selenium.

**Comment by Naktibalda** [comment]
PhantomJS is dead https://github.com/ariya/phantomjs/issues/15344
