### ISSUE TITLE
Tests run on all environments when annotating a Cest class with @env

### ISSUE THREAD

**Issue by adinnaplus** [Codeception/Codeception#2236]
**Pre-requisites**: at least 2 environments created, e.g I have in my .yml

``` php
env:
    google:
         modules:
            config:
                WebDriver:
                    url: 'http://google.com'
env:
    bing:
         modules:
            config:
                WebDriver:
                    url: 'http://bing.com'
```

**Steps**:
1. Create a Cept with at least 1 test. 
2. Annotate the class with the environment, e.g

``` php
/**
* @env google
*/
class GoogleSearchCest
{
    public function _before(AcceptanceTester $I)
    {
        $I->amOnPage('/');
    }

    // tests
    public function search1(AcceptanceTester $I)
    {
        $I->search('codeception');
        $I->checkThatFirstResultContains('codeception');
    }

    public function search2(AcceptanceTester $I)
    {
        $I->search('php require');
        $I->checkThatFirstResultContains('php');
    }
```

**Expected Result**: the tests search1 and search2 **only** run on environment google. They don't run on bing!

**Actual Result**: the  tests search1 and search2 run on both google and bing environments. I'm unsure if this is a bug or a missing feature. I'm more inclined to see it as a bug because I've seen examples where a class can be annotated, e.g with @ guy.

**Comment by eXorus** [comment]
The env feature doesn't work like this. You have to use `@env` before the test and not before the cest. Something like that:

```php
class GoogleSearchCest
{
    public function _before(Member $I)
    {
        $I->amOnPage('/');
    }
    /**
     * @env google
     */
    public function search1(Member $I)
    {
        $I->comment('here1');
    }
    /**
     * @env bing
     */
    public function search2(Member $I)
    {
        $I->comment('here2');
    }
}
```

I'm closing this issue, feel free to reopen if it is not resolved.
