### ISSUE TITLE
Old commit breaks SubmitForm

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#2238]
This commit https://github.com/Codeception/Codeception/commit/2af62a181de6810815f45b39b362c52a955a2fd2 breaks up the SubmitForm function. It prevents additional params to be supplied in:
https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/InnerBrowser.php#L488

it should be reverted

**Comment by dynasource** [comment]
great. How can this one be merged in the 2.1 branch?

**Comment by samdark** [comment]
https://github.com/Codeception/Codeception/commit/ed6c3500b97e5f21c89be58a08b8a88ff2ed4963
