### ISSUE TITLE
seeLink does not match exactly

### ISSUE THREAD

**Issue by cbojar** [Codeception/Codeception#2239]
When writing tests with `seeLink` does not perform exact pattern match on the URL path. It matches a link that simply _contains_ the pattern, rather than looking for a link that matches exactly. So for example, if we have `<a href="/about/">About</a>` (and that is the only link with the content "About"), `$I->seeLink('About', '/');` will match.

The documentation states that [the pattern will match exactly](http://codeception.com/docs/modules/PhpBrowser#seeLink). The [XPath only does a `contains` match](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/InnerBrowser.php#L207), though. I'm not sure if this is the intended behavior, and the documentation is wrong, or vice-versa.

(PHP 5.5.9, Codeception 2.1.1)

**Comment by Naktibalda** [comment]
Fixed by  #3170
