### ISSUE TITLE
unable to get the data from database in laravel5 using codeception

### ISSUE THREAD

**Issue by karunakarkarna** [Codeception/Codeception#2248]
I am writing acceptance test cases in codeception webdriver,In that
am trying to get the data from DB, for that am writing some test cases in db helper, but its showing an error like "The use statement with non-compound name 'DB' has no effect"

i tried like this
MY testing code :

here is testing code:
```
<?php
use \AcceptanceTester;

/**
 *@actor AcceptanceTester\helperSteps 
*/

class sampleCest 
{
 public function sampleCourse(AcceptanceTester $I)
   {  
     require '_bootstrap.php';
     $J = new DbHelper();
     $kk = $J->selectRecord('table_name','id','91','required_colum');
     print_r($kk);
     exit;

  }
}


DB helper:
<?php
use DB;
class DbHelper 
 {
    /**
     * Connecting Larvel Framework with Codeception
     * In following we are considering environment as Testing .. So you should set environment as testing
     * @return Symfony\Component\HttpKernel\HttpKernelInterface
     */

    public function __construct()
    {
        $unitTesting = true;

        $testEnvironment = 'testing';

        require __DIR__ . '/../../../../vendor/autoload.php';

        return require __DIR__ . '/../../../../bootstrap/autoload.php';

    }
    
    public static function selectRecord($tablename,$where_fld,$record,$reqd_column)
    {

      $select_record = DB::table($tablename)->where($where_fld, '=', $record)->select($reqd_column)->orderby($reqd_column,'desc')->first();
      $record= $select_record->$reqd_column;
      print_r($record);
      exit;
    }
 }
```
 I want to get the database from db in LARAVEL5 using codeception, can you please any one can help me in this issue.

**Comment by janhenkgerritsen** [comment]
Can you show me your suite configuration?

The problem probably comes from the fact that acceptance tests don't have access to the application code, they interact with the application via the WebDriver or PhpBrowser modules. If you want to access the database in these tests you should use the Db module.

**Comment by micaweb** [comment]
When dealing with acceptance tests and Laravel, you should require the Laravel module in this way:
```
- Laravel5:
    part: ORM
```
This will give you access to all Laravel and Eloquent methods. No need for hacks.

**Comment by janhenkgerritsen** [comment]
That will instantiate a Laravel Application object in the Laravel module that is different from the Application object used by the system under test. Using this method for database checks will probably be OK, but it will be inefficient, since it will instantiate the whole Laravel application for eacht test. If you only need database checks you are better of using the DB module.

**Comment by micaweb** [comment]
Understood!

But please consider the following:

```
// After a successful payment transaction.

$order = Order::latest();

$I->see($order->number, 'h2');
$I->see($order->transactions->first()->paymentType->name);
$I->see('$'. $order->transactions->first()->amount);
```

Imagine if I don't have Eloquent in this situation.

**Comment by janhenkgerritsen** [comment]
Yeah I can imagine you take the tradeoff of slower tests versus easier to write tests in this case. And I have never actually tested the impact on performance, so maybe it is not even noticable in a significant way :)

**Comment by karunakarkarna** [comment]
this is my acceptance.suit.yml file:


class_name: AcceptanceTester
modules:
    enabled:
            - AcceptanceHelper
            - Sequence
            - Cli
            - Filesystem
            - Db
            - WebDriver

    config:
      WebDriver:
         url: 'http://www.google.com/' 
         browser: chrome
         restart: false
         wait: 2
         clear_cookies: false
         window_size: false
         capabilities:
             unexpectedAlertBehaviour: 'accept'

**Comment by janhenkgerritsen** [comment]
Removing the `use DB;` statement from your DbHelper file will fix the `The use statement with non-compound name 'DB' has no effect`. 

For more information on this error read the answers to the following StackOverflow questions:
- http://stackoverflow.com/questions/9317022/troubleshooting-the-use-statement-with-non-compound-name-has-no-effect 
- http://stackoverflow.com/questions/23745050/laravel-composer-the-use-statement-with-non-compound-name.
