### ISSUE TITLE
$I->see fails with html entities and inline elements

### ISSUE THREAD

**Issue by alexwhitman** [Codeception/Codeception#2249]
Using Codeception 2.1 the following acceptance tests fail
```php
    public function encodedEntityTest(AcceptanceTester $I)
    {
        $I->amOnPage('/');
        $I->see('"something entity quoted"');
    }

    public function inlineElementTest(AcceptanceTester $I)
    {
        $I->amOnPage('/');
        $I->see('Test string with bold text.');
    }
```
on this sample
```html
<!doctype html>
<html>
	<head>
		<title>Entity test</title>
	</head>
	<body>
	<p>Test string with &quot;something entity quoted&quot;.</p>
	<p>Test string with nothing entity quoted.</p>
	<p>Test string with <b>bold text</b>.
	</body>
</html>
```
This used to work in 2.0 (after #1873) but no longer works in 2.1.  This is presumably because the InnerBrowser (https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/InnerBrowser.php#L1179) uses a PageContstraint (https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/PHPUnit/Constraint/Page.php) which extends `\PHPUnit_Framework_Constraint_StringContains` (https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Constraint/StringContains.php).  In no part of that chain that I can see does HTML entities or elements get taken into account.

**Comment by zbateson** [comment]
Hi @alexwhitman - my best guess is the code that fixed this in 2.1 wasn't merged correctly or was overwritten (possibly with the upgraded Guzzle).  In any case, should be good with this fix :)
