### ISSUE TITLE
InvalidCookieDomainException when (automatically) adding a 3rd-party cookie via a session snapshot

### ISSUE THREAD

**Issue by venyii** [Codeception/Codeception#2250]
When loading a session snapshot, **every** previously saved cookie will be added individually. When adding, let´s say a 3rd-party ad cookie with the domain ```.foo.com``` (and my configured URL is ```.bar.com```), an ```InvalidCookieDomainException``` will be thrown since the cookie domain does not match the current site url. The [HttpCommandExecutor](https://github.com/facebook/php-webdriver/blob/community/lib/Exception/WebDriverException.php#L139) throws a ```\Facebook\WebDriver\Exception\WebDriverException``` based on the return code ```24```.

I´m not sure what to do here. Am I misunderstanding something or should the [WebDriver](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/WebDriver.php#L2144) only accept Cookies that match the host part of the configured URL? The [WebDriverOptions](https://github.com/facebook/php-webdriver/blob/community/lib/WebDriverOptions.php#L42-L43) class documents to only add cookies with a domain value of ```null``` or the same host as the configured URL.

In my case the ad cookie prevents me from loading session snapshots. Please let me know what you think about this, I would gladly create a PR if something I wrote here makes any sense :)

**Comment by dazorni** [comment]
+1

**Comment by adrian7** [comment]
Ideally, when calling loadSessionSnapshot we should have third-party cookies queued, and automatically applied when loading the domain(s) applicable.
