### ISSUE TITLE
Make getScenerio public

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#2263]
@DavertMik, is there a reason for $actor->getScenario to be protected? Can it be made public?

**Comment by DavertMik** [comment]
It is protected as you shouldn't access it in tests. However, you can do whatever you like with it as tester classes are now not generated, so you can extend them with your own methods and access `getScenario` if you need it

**Comment by dynasource** [comment]
I am using it to get extra information out of $scenario. Because I am passing the primarely $I (actor) through different parts of my own test software, it would be nice to get to the $scenario. Its vital for me, but Iam using Reflection to get to it.
