### ISSUE TITLE
Module::scalarizeArray() returns empty string for null value

### ISSUE THREAD

**Issue by artaommahe** [Codeception/Codeception#2264]
While using REST module for testing api back-end i found that null values in request array are sent as empty strings. It's because of `is_scalar()` check in Module::scalarizeArray() method, that invokes by REST::encodeApplicationJson(). This condition fails for null values and after they converts to sting by `(string)$v`

I hope there must be smth like this
```php
if (!is_scalar($v) && !is_null($v)) { ... }
```

code line link
https://github.com/Codeception/Codeception/blob/b5af3aac061ffaeb65ed023534b3c50558e90d07/src/Codeception/Module.php#L203

**Comment by witsu** [comment]
I've noticed same problem

**Comment by fbidu** [comment]
I'll give it a try

**Comment by artaommahe** [comment]
Thx ;)
