### ISSUE TITLE
15% speedloss

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#2267]
hi @DavertMik 

Between v2.1.2 and v2.0.10 Im getting a significant speedloss of at least 15% on my tests (parallel 8 threads). Is this something you are aware of when changing to the latest branch and what would you advise on action to be taken? Should research be done on specific dependencies or something like that?

**Comment by DavertMik** [comment]
I had some changes in the internal architecture, however I didn't measure the speed (
I didn't do any inspections on that, so I'd really glad to get any additional information on that

**Comment by dynasource** [comment]
Alright. Ill post some benchmarks soon.

**Comment by Naktibalda** [comment]
It is a time for report about speed loss in 2.2
