### ISSUE TITLE
InvalidArgumentException: Unreachable field "" Error

### ISSUE THREAD

**Issue by quantum-x** [Codeception/Codeception#2270]
Hi @DavertMik 
On Codeception PHP Testing Framework v2.1.2 - with field names that have multiple-depth numerically indexed arrays:

```
        <form action="/clients/register" id="ClientRegisterForm" method="post" accept-charset="utf-8">
                   ...

                                    <td><div class="form-group required"><input name="data[User][0][first_name]" class="form-control" maxlength="50" type="text" id="User0FirstName" required="required"/></div></td>
                                </tr>
                    ...
        </form>
```

In the test:
```
$I->fillField('data[User][0][first_name]', $firstName);
```
or
```
$I->fillField('#User0FirstName', $firstName);
```

Both return:

```
  [InvalidArgumentException] Unreachable field "User"
Scenario Steps:

 1. $I->fillField("#User0FirstName","Roberto")
```

Seems the bug is still present.

**Comment by quantum-x** [comment]
@zbateson @DavertMik @dynasource 
Apologies to pull you into this thread, but you'd all previously commented on this issue before.
Digging around, it seems that the issue is from: Codeception\Lib\InnerBrowser.php
It would seem (from first glance) that the nested array isn't created, so the values can't be populated in the 'model' / form, hence the error.
Thoughts would be appreciated, thanks!

**Comment by dynasource** [comment]
No problem

* What page did you open before you filled the Field?
* What is the full HTML of this page (to be found in _output)

**Comment by quantum-x** [comment]
Hi @dynasource 
Thanks for the update.
Code + HTML + Errors are as follows:

https://gist.github.com/quantum-x/80c9ec063e5743a656ef

**Comment by dynasource** [comment]
I assume the issue lies within the support for [user][0][x] compared to [user][x][0].
If thats the case, some piece of the software should be updated as it should be supported. Dont know which piece, could be the Codeception\Lib\InnerBrowser.php

**Comment by quantum-x** [comment]
@dynasource - Seems it's in InnerBrowser.php, method 'fillField'
What is curious is that this file had been previously extended to start support for this behaviour ( 9fb68c2802ab394d3b6eb4d80f5c0963cf9d3af6 ) but this code was revoked in the current 1.2.1 version.

I've tried 1.2.1, and the modification in the 9fb68c2802ab394d3b6eb4d80f5c0963cf9d3af6 commit, but neither seems to work for this example.

BTW, I am developing on the Cake Framework, so this may be a bug that others will bump into as well.

**Comment by zbateson** [comment]
Hi @quantum-x 

Can you please confirm what version of Codeception you're using?  Your example is working fine for me in current 2.1 and I'm not seeing any difference in fillField between 2.1.2 and current.

**Comment by quantum-x** [comment]
Hi @zbateson 
Thanks for your assistance.
I just went and double checked my gist / source, and noticed that I have a double-nested <form> tag.
This is where the problem is coming from. Apologies for the distraction, but I appreciate your assistance in getting to the bottom of the problem.

**Comment by zbateson** [comment]
No problem - glad it worked out :smiley:
