### ISSUE TITLE
Show variable value instead of variable name when running generate:scenarios.

### ISSUE THREAD

**Issue by mkudenko** [Codeception/Codeception#2277]
That applies to variables defined in the test class and variables coming from PageObjects.

When generating scenarios:

`$I->see(Login::$loginButton);`

becomes

`I see "Login::$loginButton"`

Works correctly when running the tests:

`$I->see(Login::$loginButton);`

becomes

`I see "Login and access dashboard"`

**Comment by oparoz** [comment]
I was about to report this :) . Sounds like a bug to me.

**Comment by eXorus** [comment]
I can't reproduce anymore.
I'm closing this issue, feel free to reopen if it is not resolved.
