### ISSUE TITLE
Error using the default SPL autoloader

### ISSUE THREAD

**Issue by feamsr00** [Codeception/Codeception#2286]
Hi,
When attempting to use `spl_autoload_register();` in `_bootstrap.php` I have found that Codeception is unable to find the required application classes. However, executing `>tests\_bootstrap.php`directly yields no problems. Upon further investigation I have noticed that this  is specifically a problem with the PHAR file in this project.

I was able to correct the problem by [entering this code](https://nxsys.assembla.com/spaces/onx/snippets/29413) in to `_bootstrap.php` (followed by `spl_autoload_register();` of course).

Considering that the default implementation of SPL Autoload should the implementation of first (last?) resort, this shim should be installed sometime before `_bootstrap.php`.

-Thanks!

Environment
PHP 5.6.9
Codeception 2.1.1

**Comment by Naktibalda** [comment]
@feamsr00 was it an issue of Codeception or of your application?

**Comment by feamsr00** [comment]
Truthfully it's an issue of PHP (#49625 to be precise). However, since is affects PHARs and Codeception is distributed as a PHAR, Codeception would be best positioned to deal with it. This is going to be an issue for *anyone* testing code that relies on the native behaviour of spl_autoload.

The workaround is simple, just shove that shim near the call of the bootstrap (or any such early initialization facility before testing code is called).

**Comment by feamsr00** [comment]
Hi @DavertMik. Whats the reason for close? Has there been a fix?
