### ISSUE TITLE
Configuration and Test Runner sugestions

### ISSUE THREAD

**Issue by atorian** [Codeception/Codeception#2291]
Hi!
It might be 2 different items, but they are somehow related:
1st of all - i wasn't able to find Codeception roadmap or at least a draft of plan, so i don't know where Codeception is going, but there are 2 things i'd like to aks about:
- it would be VERY nice to have a possibility to run tests without passing a suite.
Every day i see like my colleagues try to guess test name, because suite name should be passed separately - path autocomplete doesn't work. So the suggestion is **make suit optional, probably use 1 parameter in run command - either path to tests, either suit name, or completely remove it**
- there are configs for suits and for envs. Wouldn't it be useful, to get rid of "suit name" and instead use folder structure + "suit.yml" file with configuration with possibility to override part of current config? There is a real life example - apache .htaccess files and hierarchy. **The "suit" name will be just a folder name, and env config - just a conf file in subfolder**.

And last small thing - **make run command default**, so __*codecept* will run tests__ just like phpunit or behat. What do you think about it?

**Comment by DavertMik** [comment]
> make suit optional, probably use 1 parameter in run command - either path to tests, either suit name, or completely remove it

already in it: 

```
./codecept run tests/unit/Relative/Path/To/UnitTest.php
```

> The "suit" name will be just a folder name, and env config - just a conf file in subfolder.

Looks like an interesting idea, however, for historical reasons it is done the way it is. Suite is conceptual thing for separating tests by levels. Environments - for changing configuration on the fly.

> And last small thing - make run command default

Personally, I don't find its convenient. I'd prefer to see all commands listed instead of guessing how to execute them.

**Comment by atorian** [comment]
> already in it

Thanks for your work. In which version will this change appear? Maybe you already have some plans?

> Looks like an interesting idea, however, for historical reasons it is done the way it is. Suite is conceptual thing for separating tests by levels. 

It is interesting what other contributors think about configuration topic? Is there any internal discussion i can follow?

> Personally, I don't find its convenient. I'd prefer to see all commands listed instead of guessing how to execute them.

i'm totally fine with your opinion.

**Comment by DavertMik** [comment]
> Thanks for your work. In which version will this change appear? 

```
./codecept run tests/unit/Relative/Path/To/UnitTest.php
```

I was using this almost everyday for the last few years ) 

> It is interesting what other contributors think about configuration topic? Is there any internal discussion i can follow?

Please create another issue just for this topic so we could have discussion going.
