### ISSUE TITLE
Codeception (or Guzzle?) does not appear to correctly send a cookie if the name contains square brackets

### ISSUE THREAD

**Issue by SimonEast** [Codeception/Codeception#2293]
Loving Codeception so far, but have run up against this issue:

**Codeception (or Guzzle?) does not appear to correctly send a cookie if the name contains square brackets**

Take the following simple PHP file (`a.php`):

```
<?php
setcookie('A', '123');
setcookie('B[C]', '456');

echo "A=" . $_COOKIE['A'];
echo "B=" . $_COOKIE['B']['C'];
```

Running it in a browser (twice) shows the correct result: `A=123 B=456`.

But for some reason this PhpBrowser Codeception test fails:

    $I->amOnPage('/a.php');
    $I->amOnPage('/a.php');
    $I->seeCookie('A');         // Pass
    $I->seeCookie('B[C]');      // Pass
    $I->see('A=123');           // Pass
    $I->see('B=456');           // Fail

Is this a bug in Codeception or possibly Guzzle?

**Comment by SimonEast** [comment]
If it's helpful, here's the debug output...

```
Scenario:
* I am on page "/a.php"

  [Response] 200
  [Page] http://ames.dev/a.php
  [Cookies] []
  [Headers] {"Date":["Thu, 20 Aug 2015 04:48:11 GMT"],"Server":["Apache/2.2.25 (Win32) mod_ssl/2.2.25 OpenSSL/0.9.8zb"],"X-Powered-By":["ZendServer 7.0.0"],"Set-Cookie":["A=123","B[C]=456"],"Transfer-Encoding":["chunked"],"Content-Type":["text/html"]}
* I am on page "/a.php"
  [Response] 200
  [Page] http://ames.dev/a.php
  [Cookies] {"A":"123","B[C]":"456"}
  [Headers] {"Date":["Thu, 20 Aug 2015 04:48:12 GMT"],"Server":["Apache/2.2.25 (Win32) mod_ssl/2.2.25 OpenSSL/0.9.8zb"],"X-Powered-By":["ZendServer 7.0.0"],"Set-Cookie":["A=123","B[C]=456"],"Transfer-Encoding":["chunked"],"Content-Type":["text/html"]}
* I see cookie "A"
  [Cookies] [{},{}]
* I see cookie "B[C]"
  [Cookies] [{},{}]
* I see "A=123"
* I see "B=456"
 FAIL
```

**Comment by Naktibalda** [comment]
It's not a bug, it's a Guzzle's feature.
```
Cookie name must not contain invalid characters: ASCII Control characters (0-31;127), space, tab and the following characters: ()<>@,;:\"/[]?={}
```

I will make a PR later.

**Comment by Naktibalda** [comment]
Accepted, wait for the next release of Guzzle.

https://github.com/guzzle/guzzle/pull/1237

**Comment by SimonEast** [comment]
Awesome! Thank you so much @Naktibalda :-) :+1:
