### ISSUE TITLE
Recorder extenstion does not create Slideshow

### ISSUE THREAD

**Issue by anilkonsal** [Codeception/Codeception#2298]
Hi,

I am using codeception with PhantomJS web driver and recorder extensions. When the tests fail, I cannot see the record_\* folders in _output directory. There are screenshots with the name of Test which failed (one for each test suite). But I need to see the journey of Tests with Steps as shown in extension page.

I am  using Yii2 with codeception 2.1 on MacOS Yosemite with special build of PhantomJS (regular one is Killed as soon as I start).

What I am missing?

**Comment by DavertMik** [comment]
I think extension is not enabled in this case. When recorder is enabled you should see notification in console:

```
⏺ Recording ⏺ step-by-step screenshots will be saved to <path>
```
