### ISSUE TITLE
Call to undefined function Codeception\Lib\codecept_debug()

### ISSUE THREAD

**Issue by cboy868** [Codeception/Codeception#2312]
$ php codecept run
Codeception PHP Testing Framework v2.1.2
Powered by PHPUnit 4.8.6 by Sebastian Bergmann and contributors.

Fatal error: Call to undefined function Codeception\Lib\codecept_debug() in /data/htdocs/thinkphp/vendor/codeception/codeception/src/Codeception/Lib/GroupManager.php on line 78

**Comment by cboy868** [comment]
Is that right?

<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/guzzlehttp/psr7/src/functions_include.php',
    $vendorDir . '/guzzlehttp/promises/src/functions_include.php',
    $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',

    $vendorDir . '/codeception/codeception/autoload.php',    // HERE
);

**Comment by Naktibalda** [comment]
Loading autoload.php is the first action performed by codecept file

https://github.com/Codeception/Codeception/blob/2.1/codecept#L7

**Comment by cboy868** [comment]
thank you :+1:
