### ISSUE TITLE
[Question]: Is there any ability to use helpers from suite within dataProvider for some tests?

### ISSUE THREAD

**Issue by hanovruslan** [Codeception/Codeception#2313]
For now methods with @dataProvider annotations run before any other methods so its unable to put entity creation code into suite helpers.

Is there any ability or plans to use helpers from suite within dataProvider

For example:

Some\Helper\DataProvider:

```
namespace Test\Some\Helper;

class DataProvider extends \Codeception\Module
{
    public function getSome()
    {
        return new \stdClass;
    }
}
```

some.suite.yml

```

class_name: SomeTester
modules:
    enabled:
        - \Test\Some\Helper\DataProvider

```

Some test with @dataProvider and helper

```
    /**
     * @param Some $some
     *
     * @dataProvider dataSome
     */
    public function testSome($some)
    {
        $this->assertInstanceOf('stdClass', $some);
    }

    /**
     * @return array
     */
    public function dataSome()
    {
         return [
            [$this->tester->getSome(),],
        ];
    }
```

**Comment by Morjodrom** [comment]
Why have you closed the ticket? Did you find the solution?

**Comment by hanovruslan** [comment]
@Morjodrom yep. thats right

**Comment by Morjodrom** [comment]
So, can you share it, please?

**Comment by hanovruslan** [comment]
As you can see i've closed this ticket year and a have ago. I suppose that this framework for now has a lot more features and my solution (basically not to use data providers as is but add specific extension and use it instead ) would be unlikely useful

But i will try not to forget to read release notes from that date. And maybe tutorial and docs about features. If i will find some interesting that belongs to this ticket i would try not to forget to share my opinion  ))

**Comment by Morjodrom** [comment]
Unfortunately, no solution is provided, also, an addon I've found is discouraged to be used as it doesn't work properly with the last versions of the framework.
Thanks for your reply!
