### ISSUE TITLE
Suggesstion: Add option to amOnPage() for using POST

### ISSUE THREAD

**Issue by YasserHassan** [Codeception/Codeception#2319]
This is to simulate browser link clicks that result in a POST requests. The REST module's `sendPost()` function could be used as a workaround to that but I believe logically it's not the logical approach besides it would not work right if both an API with a different root URL need to be tested too (e.g. the website is at `http://localhost/` while the REST API is at `http://localhost/api/`). The type could be a second function parameter that defaults to `GET`.

**Comment by DavertMik** [comment]
I don't like this specific idea (as you can't do this thing in browser), however this can be implemented as hidden method, which can be used in Helpers.

**Comment by Naktibalda** [comment]
Can't http://codeception.com/docs/modules/PhpBrowser#sendAjaxPostRequest be used for this purpose?

**Comment by YasserHassan** [comment]
Ajax is different from a user's perspective. The target is to handle the action when of a user clicks such links. If Ajax is used, you'd be testing something different from the real thing.

**Comment by DavertMik** [comment]
This method is already implemented: https://github.com/Codeception/Codeception/blob/2.1/src%2FCodeception%2FLib%2FInnerBrowser.php#L98

**Comment by Naktibalda** [comment]
This method is not equivalent to to amOnPage, because response is not loaded to DomBrowser.

**Comment by DavertMik** [comment]
Oh. You are right. Should we have 2 methods?

**Comment by DavertMik** [comment]
What about method `_loadPage`:

```
function _loadPage($method, $url, ....)
{
   $this->crawler->_request($method, $url, ...)
}
```

**Comment by DavertMik** [comment]
I think I will create a new issue for a discussion on this. Please wait 5 minutes

**Comment by Naktibalda** [comment]
amOnPage contains everything what _loadPage should do.
To avoid code duplication, amOnPage could call _request.

```php
public function _request($method, $uri, array $parameters = [],  array $files = [], array $server = [], $content = null)
{
    $this->crawler = $this->clientRequest($method, $uri, $parameters, $files, $server, $content);
    $this->forms = [];
}

public function amOnPage($page)
{
    $this->_request('GET', $page);
}
```

**Comment by Naktibalda** [comment]
yep, this method doesn't look like _request, it should be called _loadPage.

**Comment by DavertMik** [comment]
probably we should have both...
one for general requests that may go to API for instance, and one for loading pages. Actually not sure. Maybe we can have one

**Comment by Naktibalda** [comment]
Suggestion was rejected, but helpers methods were provided for DIY helpers,
