### ISSUE TITLE
Select radio button by label with PhpBrowser

### ISSUE THREAD

**Issue by micaweb** [Codeception/Codeception#2322]
If I have a dropdown like the following:

```
<label for="gender">Gender</label>
<select name="gender" id="gender">
    <option value="female">Female</option>
    <option value="male">Male</option>
</select>
```

When writing a test and using PhpBrowser I can select an option by the label as follows:

```
$I->selectOption('Gender', 'Female');
```

How could I do the same with radio buttons?

If I was able to do this, I believe PhpBrowser and WebDriver can share the same code if there are no js interactions.

**Comment by reinholdfuereder** [comment]
Naive question: is that maybe related to #4516?

**Comment by Naktibalda** [comment]
Closing in favour of #4516
