### ISSUE TITLE
Root URL trailing slash

### ISSUE THREAD

**Issue by mikefrancis** [Codeception/Codeception#2324]
I've created a functional test which checks for the following:

    $I->seeCurrentRouteIs('projects.index');

However when I run this test I get the following:

    1) Failed to user can delete project in ProjectsTestCest::userCanDeleteProject (tests/functional/ProjectsTestCest.php)
    
     Step  I see current route is "projects.index"
     Fail  Failed asserting that two strings are equal.
    --- Expected
    +++ Actual
    @@ @@
    -'/'
    +''

If I change my test to check for:

    $I->seeCurrentUrlEquals('');

This test passes. If possible I'd still like to check for the current route as it keeps my testing more dynamic.

Have tried setting `root` the following in `tests/functional.suite.yml` to no avail:

    class_name: FunctionalTester
    modules:
        enabled:
            - Helper\Functional
            - Asserts
            - Laravel5:
                environment_file: .env.testing
                root: /

Route is defined as follows:

    Route::get('/', [
        'as'   => 'projects.index',
        'uses' => 'ProjectController@index'
    ]);

**Comment by janhenkgerritsen** [comment]
Why don't you just define your route as `Route::get('', [ /* args */])`? You don't have to add the first slash in Laravel routes.

**Comment by mikefrancis** [comment]
@janhenkgerritsen Thanks for replying. Just tried your suggestion with and without the `root: /` config option and get the same test failure.

**Comment by janhenkgerritsen** [comment]
I forgot to mention, but you should not be changing the root configuration value. That settting has nothing to do with URLs of your application, it has to do with the path to the root of your application on the filesystem.

**Comment by mikefrancis** [comment]
Ok thanks, have removed that. Tests still failing though - has to be a bug?

**Comment by janhenkgerritsen** [comment]
I think so. I don't have time to look into it right now, but will do as soon as possible.

**Comment by mikefrancis** [comment]
Awesome - thank you. Might I suggest the `bug` label is added so people arriving from Google can see this is in hand?

**Comment by janhenkgerritsen** [comment]
I just added a test to a new branch of the sample Laravel5 application at https://github.com/janhenkgerritsen/codeception-laravel5-sample/tree/trailing-slash in commit https://github.com/janhenkgerritsen/codeception-laravel5-sample/commit/23305ae75e8a60a0e834bc19167b487483e623ff. But everything seems to be working ok.

Some questions:
- What version of Codeception are you using?
- Do you agree this test covers your use case? 
- What does your complete test look like?

**Comment by mikefrancis** [comment]
* Using CodeCeption version 2.1.2
* Yes, that looks to cover the use case.
* [Link to a complete test](https://gist.github.com/mikefrancis/98544bbb2a859254a473)

**Comment by mikefrancis** [comment]
I have just set up a fresh install and your code is working fine for me.

I think I've managed to recreate the issue though - if there are the following routes:

```
Route::get('/redirect', [
    'as'   => 'redirect',
    'uses' => 'PageController@homeRedirect'
]);

Route::get('/', [
    'as'   => 'projects.index',
    'uses' => 'ProjectsController@index'
]);
```

and you have the following controller:

```
class PageController extends Controller
{
    public function homeRedirect()
    {
        return redirect()->route('projects.index');
    }
}
```

Then the following test will fail:

```
class HomeTestCest
{
    public function tryToTest(FunctionalTester $I)
    {
        $I->amOnPage('/redirect');
        $I->seeCurrentRouteIs('projects.index');
    }
}
```

Seems to be a problem with redirects?

**Comment by mikefrancis** [comment]
@janhenkgerritsen Just checking you've seen the above?

**Comment by janhenkgerritsen** [comment]
Yeah I saw it but I don't have time to look into it right now.

**Comment by janhenkgerritsen** [comment]
I updated my tests and reproduced the problem in commit janhenkgerritsen/codeception-laravel5-sample@760ea4d442ca0bdc195252ed99b57869910bfc13.

The problem comes from the fact that Laravel strips trailing slashes for redirects. I have a fix, but this fix should probably also be implemented for other modules. I will first discuss this with the Codeception team before I implement it.
