### ISSUE TITLE
[InnerBrowser] Gracefully handle redirecting to external sites

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2328]
Related to #2327 

When the framework module is used for functional testing, redirecting to external sites fails like this one:

[Zend_Controller_Dispatcher_Exception] Invalid controller specified (http:)

Links and form submission ought to fail in the same way.

I see 2 possible solutions:
a) don't follow redirect, but provide some methods for inspecting it.
b) transparently replace framework client with PhpBrowser.

**Comment by DavertMik** [comment]
> transparently replace framework client with PhpBrowser.

NOOOOOOOOOOOOOOOOOOOOOOOOOOO

>  don't follow redirect, but provide some methods for inspecting it.

sounds like a plan to me. Looks like we need to add methods for inspecting redirects (we didn't have them before, as `seeCurrentUrl*` methods are about that.

**Comment by Naktibalda** [comment]
How about throwing exception?

**Comment by DavertMik** [comment]
Probably this can be a simple solution. To create new `ExternalRedirectException` and use it with InnerBrowser
