### ISSUE TITLE
Open codecept using babun

### ISSUE THREAD

**Issue by Jaironlanda** [Codeception/Codeception#2330]
Could not open input file: /cygdrive/c/Users/Myusername/AppData/Roaming/Composer/vendor/codeception/codeception/codecept

How to fix it?

**Comment by Naktibalda** [comment]
It looks like a babun issue to me.

Does that file exist?
How do you run it?

**Comment by Jaironlanda** [comment]
i can run composer through babun, codecept and laravel is not available.

**Comment by Naktibalda** [comment]
What do you mean by "codecept and laravel is not available"?

**Comment by Rufflesaurus** [comment]
If you are using babun, use vendor/bin/codecept,bat instead of vendor/bin/codecept

Same thing with phpunit, phpspec and even homestead, use .bat at the end.

**Comment by BillyPurvis** [comment]
I had a similar issue on MacOS. Symfony Docs state to use bin/codecept, where as the path is vender/bin/codecept, tried from reading @davidcochrum above answer.
