### ISSUE TITLE
Adding "current environment" functionality to Codeception 1.8

### ISSUE THREAD

**Issue by chocowoko** [Codeception/Codeception#2332]
Hello, I'm new to Codeception. I'm using version 1.8.7 and need to add there ability to detect current environment. I know that in version 2.1 there is method current() which is right what I need and I have tried to add this function in Scenario class, but it didn't work.
Also I see that in construct function of class SuiteManager there is something similar to what I need:
$this->env = $settings['current_environment']; but I don't know, how to use it.

@DavertMik @wyhmichael @tiger-seo , would be thankful if you could help.

**Comment by DavertMik** [comment]
Yeah, the simplest would be to upgrade to 2.1. We are not planning to add new features to 1.8 by ourselves, however If you add that by yourself, I will merge your pull request )
