### ISSUE TITLE
Display provided data in test report

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2334]
When PhpUnit uses data provider, it displays parameters in test result,
```
1) DataTest::testAdd with data set #3 ('1', '1', '3')
Failed asserting that 2 matches expected '3'.
```
https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers

When Codeception uses data provider, it displays this:
```
1) Test add  |  #3  (DataTest::testAdd))   Fail
Failed asserting that 2 matches expected '3'.
```
It would be useful to see parameters in report.

**Comment by DavertMik** [comment]
I disabled showing data on test running: sometimes text with data was to long to display, also it is not readable when we use complex data structures: array or objects. But yes, we can improve that for results

**Comment by Naktibalda** [comment]
Since then I learned that the key of data provider array is displayed in the test result.
Giving meaningful names test items is good enough to me.
