### ISSUE TITLE
Redirect to URL without protocol fails

### ISSUE THREAD

**Issue by mrmarkfrench** [Codeception/Codeception#2338]
When a test loads a page which then sends a redirect, it is often desirable for the redirect to not specify a protocol (HTTP vs HTTPS), but to leave the user on the protocol they used to load the page issuing the redirect. However, the test errors out with a malformed URL message when it sees this type of redirect:
```
Codeception\Exception\TestRuntime: URI '//localhost/overview' is malformed
```

We're using version 2.0.9, and the problem seems to have begun in the last several days.

**Comment by Naktibalda** [comment]
Upgrade to 2.0.16 and try again.
Which module are you using?

**Comment by mrmarkfrench** [comment]
Sorry for the lack of detail. This occurs using the PhpBrowser module.

It appears that version 2.0.16 does not have this problem. When do you anticipate that a version that resolves this issue will be promoted to stable? I've forced Composer to install 2.0.16, but long term I'd much prefer to be able to set it to "latest stable" and worry less about what might change in a dev branch.

**Comment by Naktibalda** [comment]
All normal releases, except alpha/beta/RCx, are stable.
2.0.16 is the latest and probably the last release of the 2.0 branch.
Upgrade to 2.1 and set your composer to 2.1.* to get stable releases.

The next unstable release will be in 2.2 or 3.0 branch (it isn't happening any time soon)

**Comment by mrmarkfrench** [comment]
The last package marked as stable in Packagist (where Composer pulls packages from) is version 2.0.9. The 2.0.16 is still flagged as a development version, as are all 2.1.* versions. If the more recent versions are stable, they should be flagged as stable (which might require you to create new tags).

**Comment by mrmarkfrench** [comment]
I take that back. I was pinned to an older version of your package due to an issue with a package dependency having been pinned to an older version of the required package. I've updated some other packages to resolve that older-version dependency, and it's pulled Codeception along for the ride.
