### ISSUE TITLE
"PASSED" color is too similar to "ERROR"

### ISSUE THREAD

**Issue by NikolayS** [Codeception/Codeception#2348]
In terminal, the color of "PASSED"  is very similar to "ERROR":
![screenshot 2015-09-08 11 57 42](https://cloud.githubusercontent.com/assets/1345402/9730687/d88d90f6-5620-11e5-9afd-ede5bbdf9e49.png)
![screenshot 2015-09-08 11 57 28](https://cloud.githubusercontent.com/assets/1345402/9730688/d8b0710c-5620-11e5-862b-5d525109be95.png)

So "PASSED" is almost red and it's hard to quickly understand how many failures do you have – everything is reddish.

I propose changing color of "PASSED" – maybe to green.

**Comment by NikolayS** [comment]
Worth to mention that I'm using Solarized Light color scheme with iterm2 on mac.

**Comment by NikolayS** [comment]
And in case of Macbook nonRetina if you look on your screen on some angles - i.e. from bottom - those 2 colors look absolutely the same. It's much better if you look from upper hemisphere though. Anyway green would be much better for `PASSED`.

**Comment by Naktibalda** [comment]
This is no longer issue with Codeception 2.2
