### ISSUE TITLE
[question] How to install newest 2.1 version

### ISSUE THREAD

**Issue by mnabialek** [Codeception/Codeception#2351]
Hello

How can I install the latest 2.1 version? When I put in `composer.json` only:

```
"codeception/codeception": "*"
```

as suggested, I'm getting `b5af3aac061ffaeb65ed023534b3c50558e90d0` commit which is quite old and have some issues that have been fixed in later commits.

**Comment by DavertMik** [comment]
`"codeception/codeception": "~2.1"`

probably you are getting verison from dev-master. You need to adjust your stability settings to require only stable versions

**Comment by mnabialek** [comment]
The issue here was facebook/webdriver that I also had in composer.json that blocked getting latest codeception version
