### ISSUE TITLE
Codeception error while running acceptance tests: Unable to find executable for: taskkill

### ISSUE THREAD

**Issue by learntech123** [Codeception/Codeception#2362]
Hi, 

I am executing acceptance test cases in codeception using selenium web driver.

My test cases are getting passed. But I am getting below error message 

[Facebook\WebDriver\Exception\UnknownServerException] Unable to find executable for: taskkill

How do I resolve this error. And I am trying generate HTML report. it's getting saved in output folder. But it is empty. Is it because of the above error? Anyone could you pl advise on this?

But if I run my test case with phpBrowser, I am not getting any error and even my report.html file is generating fine.

Here I have attached my screenshot

![error](https://cloud.githubusercontent.com/assets/14229462/9807603/bc6a4f32-58a9-11e5-847a-bd2af9ed5a8a.png)

**Comment by Naktibalda** [comment]
What version of Windows are you using?
taskkill is a Windows utility which is missing in your computer

**Comment by DavertMik** [comment]
This is not related to Codeception, probably it is an issue of selenium
server. You should install it so selenium could start and stop browser
process
11 вер. 2015 08:23, користувач "learntech123" <notifications@github.com>
написав:
>
> Hi,
>
> I am executing acceptance test cases in codeception using selenium web
driver.
>
> My test cases are getting passed. But I am getting below error message
>
> [Facebook\WebDriver\Exception\UnknownServerException] Unable to find
executable for: taskkill
>
> How do I resolve this error. And I am trying generate HTML report. it's
getting saved in output folder. But it is empty. Is it because of the above
error? Anyone could you pl advise on this?
>
> But if I run my test case with phpBrowser, I am not getting any error and
even my report.html file is generating fine.

**Comment by learntech123** [comment]
@ Naktibalda,

I am using windows 8.1. 
64 bit os
x64 - based processor

**Comment by learntech123** [comment]
@DavertMik,

DavertMik, I am sorry. I did not get the comment. What should I install.
Could you please explain bit more.

And below are some details which might help to answer the query
I am using latest selenium-server-standalone-latest.jar file

I am using Fireforx 4.0.3 And I have tried with fireforx lower than 40 versions as well.

**Comment by Naktibalda** [comment]
https://github.com/SeleniumHQ/selenium/issues/768

This ticket suggests that you need to add the directory c:\windows\system32 to PATH environment variable.
