### ISSUE TITLE
How to run 1 same test case with 10 different set of inputs

### ISSUE THREAD

**Issue by learntech123** [Codeception/Codeception#2365]
Hi,

In codeception acceptance testing,

Anyone could you pl tell me how to run 1 same test case with 10 different set of inputs 

Thanks

**Comment by DavertMik** [comment]
The thing you are asking is data driven testing. Unfortunately Codeception doesn't provide any means for that.

**Comment by learntech123** [comment]
Hi Michael,

Thank you very much for your response.
I have small clarification.

I tried to pass inputs from an array. I am repeating the test case in
foreach loop by passing different parameters, But in that case, my test
case is running as 1 test case with different assertions.

But if the test case fails for any input, subsequent assertions/input are
not running.

Is these any at least to make my test case continue running even if any of
the assertion fails in for loop.

Thanks,

Bhavya

**Comment by Naktibalda** [comment]
Data providers are supported in Test format.
http://codeception.com/11-15-2013/codeception-18-phalcon-environments-dataproviders.html#DataProviders

Example:

```php
class NumberValidatorTest extends \Codeception\TestCase\Test
{
    protected $validator;

    protected function _before()
    {
        $this->validator = new \Validate_Number();
    }

    /**
     * @dataProvider provideNumbers
     */
    public function testValidateNumber($number, $isValid)
    {
        $this->assertSame($isValid, $this->validator->isValid($number));
    }

    public function provideNumbers()
    {
        return [
            ['1', true],
            ['1000, true],
            ['CN4598195', false], 
       ];
}
```

**Comment by learntech123** [comment]
Thanks for your response Naktibalda.

1 clarification. I am checking for acceptance testing.

I have generated loginCept.php file code is 

<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');
$I->login($I);
?>

And my Acceptance.php file code is (generated page object)

<?php
namespace Helper;
use Page\login;
class Acceptance extends \Codeception\Module
{
	//login 
	public function login($I)
	{
		$I->amOnPage(login::$homePage);
		$I->click(login::$loginButton);
		$I->fillField(login::$userName,'bhavyamrangegowda@gmail.com');
		$I->fillField(login::$password,'doordie123');
		$I->click(login::$submitButton);
		$I->amOnPage(login::$dashBoard);
		$I->click(login::$logoutLink);
		$I->amOnPage(login::$logoutIndex);
	}
?>

Could you pl tell me can I use same test case login $I->login($I); for multiple set of inputs??

**Comment by Naktibalda** [comment]
Pass inputs as parameters instead of using Page object properties.

**Comment by learntech123** [comment]
I  tried passing inputs in an array by calling the test case in for loop by passing array values as input parameter. In acceptance.php, multiple set of inputs can be passed using if loop.

This runs my test as only 1 test case with different assertions. 
But, it runs the test case until it fails for any inputs/assertion. 
(for ex: 
1) if it fails for the inputs which I have passed in first if case, it stops executing further and terminates browser. And result says 
FAILURES!
Tests: 1, Assertions: 1, Failures: 1. )

2)If the inputs in both the if loops are fine, then the result is
OK (1 test, 2 assertions)


<?php 
$I = new AcceptanceTester($scenario);
for ($m=1;$m<=2;$m++) 
{
          $I->wantTo('perform actions and see result');
	  $I->login($I,$count);
}
?>

<?php
public function login($I,$k)
{
		if($k==1)
		{
		$u="test@gmail.com";
		$p="test123";
		}
		if($k==2)
		{
		$u="learn@gmail.com";
		$p="learn";
		}
		$I->amOnPage('dayshire/admin/');
                $I->fillField('#username',$u);
                $I->fillField('#password',$p);
                $I->click('#login');
                $I->amOnPage('/dayshire/admin/subpage.php');
                $I->see('Administrator');
                $I->click('Logout');
}

**Comment by SSyar** [comment]
@learntech123 need help regarding 
`<?php 

$I = new AcceptanceTester($scenario);

for ($m = 1; $m <= 2; $m++) {
    $I->wantTo('perform actions and see result');
    $I->login($I, $count);
}

?>

<?php

public function login($I, $k)
{
    if ($k == 1) {
        $u = "test@gmail.com";
        $p = "test123";
    }

    if ($k == 2) {
        $u = "learn@gmail.com";
        $p = "learn";
    }

    $I->amOnPage('dayshire/admin/');
    $I->fillField('#username', $u);
    $I->fillField('#password', $p);
    $I->click('#login');
    $I->amOnPage('/dayshire/admin/subpage.php');
    $I->see('Administrator');
    $I->click('Logout');
}`
regarding this case

**Comment by bvigneshk** [comment]
Hi Davert, I am also looking for this feature of data driven testing, since it makes the testers life easy "automate once and pass different input values" and report should get generated for different inputs as different testcase.

Kindly work on this implementation and update when this feature will be ready.

Thanks,
Vignesh.

**Comment by Naktibalda** [comment]
@bvigneshk There is a new functionality called "Examples" in 2.2
It provides an alternative to DataProvider but works in Cest format only:
http://codeception.com/03-10-2016/even-more-features-of-codeception.html#examples

**Comment by bvigneshk** [comment]
Thanks a lot for your quick response, let me give a try.

On Thu, Apr 28, 2016 at 9:18 PM, Gintautas Miselis <notifications@github.com

**Comment by bvigneshk** [comment]
Functionality "Examples" is a great thing to work with for data driven,
 /**
   * @example(filename="test1")
   * @example(filename="test2")
   */ 

1) How do I make this to run for stress or load test ?
Example : I want to run the test1 for 1000 times and test2 for 500 times.

2) I have the list of data files present in a directory called "datafiles"
How do I make the Examples feature to read the directory and pickup the filenames dynamically ?
(so that if tomorrow I add 10 more datafiles, automatically my test will pickup those)


Thanks,
Vignesh.

**Comment by Naktibalda** [comment]
1) Codeception is not a stress testing tool.
2) Use Test format with data providers.

**Comment by bvigneshk** [comment]
Thanks a lot for your support and reply.

**Comment by javigomez** [comment]
@bvigneshk regarding: `Example : I want to run the test1 for 1000 times and test2 for 500 times.`

Not sure if it will help but I use robo.li scripts for doing this kind of tasks. Check: http://robo.li/tasks/Testing/#codecept

**Comment by Naktibalda** [comment]
Running test 1000 times in a row is not load/stress testing, but it could serve as benchmarking tool.
Sebastian Bergman used `phpunit --repeat 1000` to compare performance of PHP 5.6 and PHP 7.0.

If you actually wanted to do stress/load testing, use a proper tool like [Gattling](http://gatling.io/) or [Jmeter](http://jmeter.apache.org/).

**Comment by bvigneshk** [comment]
Thank you for your support I will give a try on the ideas what you gave and
update you.
