### ISSUE TITLE
How to customise report.html in acceptance testing

### ISSUE THREAD

**Issue by learntech123** [Codeception/Codeception#2366]
Could you please tell me is there any way can we customise report.html in codeception? 
i.e., instead of showing xpath and is's in report, can we show any meaningful variable to make it user friendly.

My client is asking more readable user friendly report.

**Comment by Naktibalda** [comment]
There is no way to customize assertion messages in Codeception, but many individual messages could be improved. 

Improve messages and make a pull request.

**Comment by DavertMik** [comment]
Starting from Codeception 2.1 you can extend and customize HTML reporter to whatever you like:
This feature is not documented yet, so you will need to check its code. At first you can specify override formatter in `codeception.yml`: https://github.com/codeception/codeception/blob/2.1/src%2FCodeception%2FConfiguration.php#L77

```
reporters:
    html: Your\Formatter\Class
```

then you should take a look into https://github.com/codeception/codeception/blob/2.1/src%2FCodeception%2FPHPUnit%2FResultPrinter%2FHTML.php and extend it to fit your needs. Templates can be found at https://github.com/codeception/codeception/blob/2.1/src%2FCodeception%2FPHPUnit%2FResultPrinter%2FHTML.php

**Comment by learntech123** [comment]
@ DavertMik, 

could you pl explain bit more about override formatter in codeception.yml  with an example.

Sorry I am new to codeception/phpunit.

If you could give some more info/steps, I can check the code to customise my report

**Comment by jltoo** [comment]
@DavertMik

I'm also new to Codeception. Is there any steps or guide for this? It's really nice to have a way to customized the report.

**Comment by DanielRuf** [comment]
> There is no way to customize assertion messages in Codeception, but many individual messages could be improved.

This could be really helpful.

**Comment by Naktibalda** [comment]
If you want human readable reports, you should be using Gherkin tests: https://codeception.com/docs/07-BDD
