### ISSUE TITLE
Are Helpers deprecated

### ISSUE THREAD

**Issue by lackovic10** [Codeception/Codeception#2369]
hello!

Are the Helper classes deprecated or should they be used in a different way, the [docs here](http://codeception.com/docs/03-ModulesAndHelpers#Helpers) don't seem to exist anymore.
I've tried something similar like described [here](http://codeception.com/docs/10-WebServices) under `Testing JSON Responses` but it didn't work.
Then i injected the `$scenario` into my helper testing method and did this:
```php
<?php

namespace Helper;

class ApiHelper extends \Codeception\Module
{
    public function seeIsSuccessResponse($scenario)
    {
        if ($scenario->running()) {
            $response = json_decode($this->getModule('REST')->response);
            \PHPUnit_Framework_Assert::assertTrue(isset($response->status));
            \PHPUnit_Framework_Assert::assertEquals('success', $response->status);
        }
    }
}
```
and this worked for me. is something like this the desired way, or am i taking the wrong approach ?
i appreciate the answers, thank you!

**Comment by Ragazzo** [comment]
They are [supported](https://github.com/yiisoft/yii2-app-advanced/blob/master/tests/codeception/common/_support/FixtureHelper.php)

**Comment by lackovic10** [comment]
what about my test, why don't it work without the scenario and the `$scenario->runnning()` method call ?

**Comment by Naktibalda** [comment]
Current link to the same page is http://codeception.com/docs/06-ReusingTestCode#Modules-and-Helpers

**Comment by lackovic10** [comment]
thanks guys
