### ISSUE TITLE
seeInField doesn't see value of disabled form fields

### ISSUE THREAD

**Issue by lowerends** [Codeception/Codeception#2378]
Using the `seeInField` function on a disabled form field or a form field within a disabled field set always leads to an empty value for that form field. This makes it impossible to test for a given value in a disabled field. This did work in version 2.0.12 but is not working anymore in the latest version 2.1.2.

**Comment by Naktibalda** [comment]
Related PR #2252

**Comment by Naktibalda** [comment]
Actually my change doesn't look related, seeInField doesn't call getFormValuesFor directly or indirectly.

I found a major refactoring of proceedSeeInField which was made in 2.0.13 version https://github.com/Codeception/Codeception/commit/c048980e318850c154d789d5ce5d69952a6cef60#diff-fde80abc0dc33fc4bca3b43f571f8934L321 by @zbateson

**Comment by lowerends** [comment]
Indeed, I first thought your PR was related but then I noticed the problem remained after reverting this PR. After some more testing, I can indeed confirm that the problem originates in version 2.0.13.
