### ISSUE TITLE
Bug in seeInRepository when using @Embedded in Doctrine Mapping

### ISSUE THREAD

**Issue by jachim** [Codeception/Codeception#2380]
I have Embedded objects in my doctrine mapping and I`m trying to use seeInRepository:

 $I->seeInRepository('MyEntity', [
            'embeddedObject.field1' => 'val1',
            'embeddedObject.field2' => 'val2'    
]);

This is causing an error: 
[Doctrine\ORM\Query\QueryException] [Syntax Error] line 0, col 107: Error: Expected end of string, got '.' 

I`ve found a solution. 
Fix this in Doctrine Module by replacing this lines:

$paramname = "s__$key";
$qb->andWhere("s.$key = :$paramname");
$qb->setParameter($paramname, $val);

with:

$paramname = str_replace(".", "_", "s__$key");
$qb->andWhere("s.$key = :$paramname");
$qb->setParameter($paramname, $val);

**Comment by DavertMik** [comment]
> I`ve found a solution. 

Sounds good, could you submit it as pull request?
