### ISSUE TITLE
Autoload issue when running from vendor/bin directory.

### ISSUE THREAD

**Issue by oblogic7** [Codeception/Codeception#2390]
On version 2.1.2 I am getting the following error.

```
PHP Warning:  require_once(/vagrant/vendor/bin/autoload.php): failed to open stream: No such file or directory in /vagrant/vendor/bin/codecept on line 7
PHP Stack trace:
PHP   1. {main}() /vagrant/vendor/bin/codecept:0
PHP Fatal error:  require_once(): Failed opening required '/vagrant/vendor/bin/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/vendor/bin/codecept on line 7

```

The codecept command is looking for the autoload.php file inside the bin directory instead of up one level in the vendor directory.  Not sure when this changed, but it used to work.

**Comment by Naktibalda** [comment]
What's the output of `ls -l vendor/bin/codecept`

For me it prints: vendor/bin/codecept -> ../codeception/codeception/codecept

It looks like you have a copy instead of symlink.
Your error happens in this line of code: https://github.com/Codeception/Codeception/blob/2.1.2/codecept#L7

**Comment by oblogic7** [comment]
Deleting the vendor/codeception folder and running composer install corrected the issue.  Still not sure what was causing the problem.
