### ISSUE TITLE
[Feature request] get HTTP Response code with WebDriver

### ISSUE THREAD

**Issue by JarJak** [Codeception/Codeception#2392]
It would be nice if I could do:
```
$I->seeResponseCodeIs(404);
```
Like I would do with PhpBrowser, but in WebDriver (Selenium or PhantomJS).

**Comment by DavertMik** [comment]
It is impossible due to limitations of Webdriver protocol
22 вер. 2015 14:10, користувач "Jarek Jakubowski" <notifications@github.com>
написав:
