### ISSUE TITLE
Foreign key ON DELETE doesn't seem to be triggered by tests

### ISSUE THREAD

**Issue by jpjakprints** [Codeception/Codeception#2393]
My database has several tables that are linked via foreign keys. For example I have a users table with an "id" column and a printers table also with an "id" column. The users table also has a column called "printer_id" which corresponds to the "id" column on the printers table.

I have a foreign key set with ON DELETE SET NULL so that when you delete a row from the printers table it will set the "printer_id" column on the users table to null for all records that were set to the id of the deleted printers row.

I've confirmed that the foreign key is setup and working properly through my Laravel 4 app and also through the database directly. When I open MySQL Workbench and delete a row from printers it will in fact set the printer_id column to null for users who had that printer_id as it should. 

However, when I run my test everything appears to work, except when I check to see that the user no longer has the printer_id column set to the delete row id and instead it is null, it fails and says that the printer_id column is still set to the printer id.

Here is my test:
```php
$I->wantTo('Use the API to delete a printer');
$printer = Printer::where('id', '=', 2)->firstOrFail();  
$user = User::where('printer_id', '=', 2)->firstOrFail();
$I->sendDELETE($this->endpoint.$printer->id);
$I->seeResponseCodeIs(200);
$I->dontSeeRecord('printers', array('id' => $printer->id));   
// make sure the foreign key on delete is working properly
$I->dontSeeRecord('users', array('id' => $user->id, 'printer_id' => '2')); 
```
The last line is the one that fails and this is what it says:
```
 Step  I don't see record "users",{"id":2,"printer_id":"2"}
 Fail  Unexpectedly managed to find users with {"id":2,"printer_id":"2"}
```
I've also tried changing that last line to this, but this fails as well as it isn't found:
```php
$I->seeRecord('users', array('id' => $user->id, 'printer_id' => NULL)); 
```
The other steps all pass as do the 200+ other tests I have so I know it isn't an issue with configuration. I have one or two other tests similar to this that also fail for the exact same reason. 

Has anyone else run into this issue or have any ideas why it is happening? It is important for my to test that the foreign keys in my database are working properly to prevent integrity constraint violations or possible issue with future migrations. Plus I don't want the database to have a bunch of junk data in it. 

Thanks in advance and if you need anymore details or have any questions please let me know.

**Comment by Naktibalda** [comment]
Could you add configuration of your suite?

**Comment by jpjakprints** [comment]
Sure. I created a custom suite called API. Here is the api.suite.yml:

class_name: ApiTester
modules:
    enabled:    
        - Db
        - Cli
        - \Helper\Api
        - Asserts    
        - Laravel4
        - REST:
            url: http://laravelpod.localhost:80/
            depends: Laravel4

**Comment by jpjakprints** [comment]
By the way, the formatting of my suite config got messed up when I copy & pasted it, but it is correct so the formatting isn't the issue.

**Comment by janhenkgerritsen** [comment]
I don't see anything wrong on first glance, so I have some additional questions:

- Which version of Codeception are you using? 
- Did this error occur after upgrading Codeception?
- Is it possible there is more than one user with a `printer_id` of 2?
- Is your test database the same vendor as your dev/production database?
- What code is executed in your application to delete the printer?
- Have you tested the `dontSeeRecord` method with the ids as both strings and actual integers? In your sample test code the `$user->id` is probably an integer while you pass the `printer_id` as a string.

**Comment by jpjakprints** [comment]
Thanks for your reply janhenkgerritsen. Here are the answers to your questions... any ideas you have would be much appreciated as I am completely stumped and the other 2 devs working on this app have no ideas either.

Question: Which version of Codeception are you using?
Answer: I am using Codeception version 2.1.1 & PHPUnit 3.7.28. Here are the lines from my composer file in case that helps: 
Codeception: "codeception/codeception": "@stable"
PHPUnit: "phpunit/phpunit": "4.7.*"

I'm also using code coverage and the C3 addon. Here are the other applicable composer lines:
"codeception/c3": "2.*"
"phpunit/php-code-coverage": "^2"
"ext-xdebug": ">=2"

Question: Did this error occur after upgrading Codeception?
Answer: No.

Question: Is it possible there is more than one user with a printer_id of 2?
Answer: Yes, but there are supposed to be as it isn't a unique or primary key or index. The concept behind this is that users can print directly from the app and have the ability to set their default printer and then change printers if need be. The printers table holds records for each of the printers and the id corresponds to the users table printer_id column. Therefore multiple users can have the same printer_id set. I have tested this scenario though and even if more than one user has the printer_id of "2", when I go and delete the record with id "2" from the printers table the ON DELETE works fine and will update each and every user with printer_id = 2 to printer_id = NULL. I've even tried modifying my seeds so that my test database only had one user with the printer_id instead of multiple users with the same printer_id, but it made no difference.

Question: Is your test database the same vendor as your dev/production database?
Answer: No. I have a separate database for testing. The database is kept current by running migrations before any tests are executed and also running the seeds to populate the test database with the necessary data for the tests to use.

Question: What code is executed in your application to delete the printer?
Answer: Here is the function that is called when the delete printer route is called:
public function removePrinter($printerId)
    {
        $printer = Printer::findOrFail($printerId);
        $printer->delete();
        return $this->index();
    }

Also, here is the up() function for my migration that creates the foreign key with the ON DELETE:
Schema::table('users', function(Blueprint $table){
                    $table->dropForeign('users_printer_id_foreign');
                    $table->foreign('printer_id', 'fk_Printer_id1')->references('id')->on('printers')->onUpdate('NO ACTION')->onDelete('SET NULL'); 
            });   


Question: Have you tested the dontSeeRecord method with the ids as both strings and actual integers? In your sample test code the $user->id is probably an integer while you pass the printer_id as a string.
Answer: Yes. I've tried all of the below combinations and they all fail.
$I->dontSeeRecord('users', array('id' => $user->id, 'printer_id' => '2'));
$I->dontSeeRecord('users', array('id' => $user->id, 'printer_id' => 2));
$I->dontSeeRecord('users', array('id' => $user->id, 'printer_id' => $printer->id));
$I->seeRecord('users'. array('id' => $user->id, 'printer_id' => NULL));

The first three results in a failure because it says it unexpectedly found the record. The fourth one fails because it says it can't find the record.

**Comment by jpjakprints** [comment]
A little more info regarding your one question...

Question: Is your test database the same vendor as your dev/production database?
Answer: Both the local dev & production database are running MySQL and so is my test database. The test database is configured identically to my local dev database and the production database. The only differences with the test database is the name, username & password. 

As a side note, I have forced my tests to use the local dev database instead by changing the environment and executed just the test in question and got the same result.

**Comment by janhenkgerritsen** [comment]
I don't see anything wrong with your code or what you tell me with your other answers. I'll just write down some other things I can think of.

One thing you should try is in your calls to `$I->dontSeeRecord()` is casting `$user->id` to a string:

```
$I->dontSeeRecord('users', array('id' => ((string) $user->id), 'printer_id' => '2'));
```

And what happens if you use the `dontSeeInDatabase` method from the `DB` module instead of the `dontSeeRecord` of the `Laravel4` module?

If those two suggestions don't help can you inspect the data in your test database right before you make the assertion? You could try to use the `grabRecord` method, but maybe it is better to just grab all the records in the table by creating your own `PDO` connection and query through that connection, and then dump the results.

I can't think of anything more right now, but maybe something comes to mind at a later time.

**Comment by jpjakprints** [comment]
Ok thanks for your feedback and suggestions. I will give those things a try and let you know if I have any luck getting it to work properly.

**Comment by jpjakprints** [comment]
Well... I tried all of your suggestions to no avail. None of those things worked and I am still having the same issue. I also tried inspecting the database after making the call before my assertions and the record is deleted from the printers table as it should be, but the users table is not update to set the printer_id column(s) to null. I am at a complete loss here because as you said everything seems to be setup correctly and I know the foreign key is setup properly and working because like I said before when I go through my app or the database directly and delete a printer record then the one or more users who had that printer_id set are updated to null. 

If anyone has any other ideas or suggestions I'd greatly appreciate them! Could this potentially be an issue with Codeception? Thanks in advance for your help and for the previous suggestions and ideas.

**Comment by janhenkgerritsen** [comment]
Normally I would say this probably is an issue with the application code, but in this case I don't see anything wrong with that. So it really could be anything at this point.

If you really need to fix this issue I would suggest you try to reproduce the issue with the minimal amount of code necessary. So for example a clean Laravel installation and a fresh installation of Codeception with the minimum amount of modules and tests necessary. If that does not reproduce the issue you can start adding other things to try to determine the culprit, for example Codeception modules, test coverage or features of you current application that could possibly interfere.
