### ISSUE TITLE
Fatal error: Call to a member function setBaseUri() on a non-object

### ISSUE THREAD

**Issue by hancc** [Codeception/Codeception#2397]
## codeception version : dev-master
![image](https://cloud.githubusercontent.com/assets/4936114/10044153/0a7f98d2-622b-11e5-8f5b-66fb86483c88.png)

##### tests/api.suite.yml
![image](https://cloud.githubusercontent.com/assets/4936114/10043496/2e7f575e-6226-11e5-9357-d6ae23e4762f.png)

##### vendor/phpunit/phpunit/src/Framework/TestSuite.php
![image](https://cloud.githubusercontent.com/assets/4936114/10044431/8fa52d68-622d-11e5-88dc-fdb504ea8ecf.png)
##### $this->tests
![image](https://cloud.githubusercontent.com/assets/4936114/10044052/334c8640-622a-11e5-98dd-6b11b1dced2f.png)

## when loop index = 0 
![image](https://cloud.githubusercontent.com/assets/4936114/10043591/e6a545e6-6226-11e5-8007-0dffa27fdaba.png)
##### $test->scenario->currents['modules']['PhpBrowser']->client
![image](https://cloud.githubusercontent.com/assets/4936114/10043532/72e9558e-6226-11e5-9784-63ee81da4851.png)

##### vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php
![image](https://cloud.githubusercontent.com/assets/4936114/10043784/48169f72-6228-11e5-9635-54031b773849.png)

## when loop index = 1
![image](https://cloud.githubusercontent.com/assets/4936114/10043591/e6a545e6-6226-11e5-8007-0dffa27fdaba.png)
![image](https://cloud.githubusercontent.com/assets/4936114/10043561/b2b0c8c8-6226-11e5-991c-136724bbc4e6.png)

#### Go on .....

![image](https://cloud.githubusercontent.com/assets/4936114/10044199/86a90092-622b-11e5-90e0-2d3bbaee4b30.png)

### vendor/codeception/codeception/src/Codeception/Module/PhpBrowser.php
![image](https://cloud.githubusercontent.com/assets/4936114/10044243/e254b918-622b-11e5-9ea7-be1e0ae9a76f.png)
#### TO
![image](https://cloud.githubusercontent.com/assets/4936114/10044239/d82323a8-622b-11e5-97dd-6751aafd5860.png)
##### Function '_initialize'
![image](https://cloud.githubusercontent.com/assets/4936114/10044293/44ab49d8-622c-11e5-8cda-6ebf906f22ce.png)

#### THAN 
![image](https://cloud.githubusercontent.com/assets/4936114/10044266/1894ffec-622c-11e5-9ffb-05e4f9bc7729.png)

## Is this a bug of codeception ?

**Comment by Naktibalda** [comment]
Don't use master, it is way behind 2.1 version

**Comment by Naktibalda** [comment]
This issue was fixed in 2.1.2 https://github.com/Codeception/Codeception/commit/cf8f7d3314695d3da786d933edaa923f5120e51a

**Comment by hancc** [comment]
thx

**Comment by hancc** [comment]
thx
