### ISSUE TITLE
[Feature Request] Iframe support for InnerBrowser

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2398]
I just discovered that I need to test website which uses an iframe and it seems that this feature is missing in InnerBrowser.

**Comment by Naktibalda** [comment]
WebDriver has switchToIFrame method, so it seems like a good choice for a name.

The simplest implementation could operate in a manner similar to click() or amOnPage().
Switching to another frame or back to parent frame would involve keeping multiple responses in memory.

**Comment by DavertMik** [comment]
We have `sendAjaxRequest` methods that switch contexts as well. After you send a request the context is changed and now you work with ajax response. The original idea was to work with ajax-popups - to receive them and interact. However, there is no way to switch back to original page. 

So I think it is a good idea to have implemented the mechanism for context switching.
