### ISSUE TITLE
Request methods in InnerBrowser

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#2407]
We need to a better organization of request methods. Right now we have

* `amOnPage`
* `sendAjaxGetRequest`
* `sendAjaxPostRequest`

And there is a need for more: https://github.com/Codeception/Codeception/issues/2319
So I added a hidden `_request` method which should be used from Helpers only. But looks like we also need `_loadPage` method which is similar to `_request` but will set response to crawler.

@tiger-seo proposed to implement `submitAjaxForm()` method.

I don't like the mess we've got here. After adding **hidden methods** concept which should be actively used in Helpers we could hide some methods which are about technical implmentation and not specification. So we won't allow users to send POST requests from inside tests, as it is not an action that can be performed by end-user, not it is a part of specification.

So I think that raw request methods should moved to Helpers:

* `_request`
* `_loadPage` <- actually this can be merged with `_request`? Discuss?
* `_ajaxRequest` <- to perform any ajax request

But have these actions:

* `amOnPage`
* `submitAjaxForm`

These means that `sendAjaxRequest` methods will be deprecated in favor of hidden `_ajaxRequest` method.

**Comment by tiger-seo** [comment]
IMHO, from semantic POV form has to be submitted, not sent

**Comment by DavertMik** [comment]
Agreed

**Comment by Naktibalda** [comment]
_request doesn't add anything to clientRequest, it would be better to rename clientRequest to _request and make it public.

_loadPage should be:
```php
public function _loadPage($method, $uri, array $parameters = [],  array $files = [], array $server = [], $content = null)
{
    $this->crawler = $this->clientRequest($method, $uri, $parameters, $files, $server, $content);
    $this->forms = [];
}

public function amOnPage($page)
{
    $this->_loadPage('GET', $page);
}
```

ajaxRequest should have $changeHistory parameter set to false.

I don't get the point of hidden helper functions.
If I have to create a helper class and tightly couple it with PhpBrowser or framework module, I could as well extend that module.

Hidden Helper way:
```php
class Helper\PostPage extends \Codeception\Module
{
    public function postPage($uri, $params)
    {
        $this->getModule('PhpBrowser')->_loadPage($uri, 'POST', $params);
    }
}
```
Extension way:
```php
class Module\PhpBrowserWithPostPage extends \Codeception\Module\PhpBrowser
{
    public function postPage($uri, $params)
    {
        $this->crawler = $this->clientRequest('POST', $uri, $params);
        $this->forms = [];
    }
}
```

**Comment by DavertMik** [comment]
> If I have to create a helper class and tightly couple it with PhpBrowser or framework module, I could as well extend that module.

Yes, but I discovered that extending modules may be harder for beginners, especially the fact that Helper == Module. Also I think it is a good idea to separate user and vendor code so we are sure that no changes in user code would affect the vendor code. And Helpers accessing module is a good one-way bridge to our vendor code.

---

I will add `_request` and `_loadPage` to 2.1.3

**Comment by DavertMik** [comment]
> _request doesn't add anything to clientRequest, it would be better to rename clientRequest to _request and make it public.

On second thought I decided to have `clientRequest` and `_request` separated. It would be useful to have `_request` method to be used for accessing APIs and return raw response body on it instead of Crawler instance. At least it is not clear how to use Crawler object instance.
