### ISSUE TITLE
customize the html report 

### ISSUE THREAD

**Issue by shabfactor** [Codeception/Codeception#2409]
hi,
what i want is after i run report for a test e.g login i donot want to show the login id and password in action steps or second thought i want to hide the steps in report.
how can i do that?

**Comment by Alexhha** [comment]
The same thing, is it possible to hide (replace with *) sensitive data from the report?

**Comment by raistlin** [comment]
AFAIK, its not possible.

Either way, reports are generated from testing environments. And data you use on these testing environments are intended to be fixtures and fake data.
If you are using real data in your testing environment, I **strongly** advise you to stop using it or at least transform the data before launching tests. You could change passwords for users you need and set to something silly that doesn't bother you to be displayed on html reports, like *my_silly_password*

**Comment by Alexhha** [comment]
And what about live environment?

It would be great to have something similar to this plugin for jenkins -
https://wiki.jenkins-ci.org/display/JENKINS/Mask+Passwords+Plugin

**Comment by raistlin** [comment]
What's your use case to launch TESTS on a live environment?

**Comment by Alexhha** [comment]
I need to be sure that everything (at least some basic things) works fine
after deployment. For example right now I'm using something like the
following

   $I = new AcceptanceTester($scenario);
   $I -> wantTo('Ensure that UserAdmin works');
   $I -> amOnUrl('http://staging.example.net');
   $I -> amOnPage('/UserAdmin');
   $I -> seeInTitle('UserAdmin Login');
   $I -> seeResponseCodeIs('200');
   $I -> seeCookie('JSESSIONID');

   $I -> fillField('input[name="user"]', '123456789');
   $I -> fillField('input[name="password"]', '123567');
   $I -> fillField('input[name="secureCode"]', '7654321');
   $I -> click('input[type="submit"]');

   $I -> amOnPage('/UserAdmin.jsp');
   $I -> seeResponseCodeIs('200');
   $I -> seeInTitle('Main menu');
   $I -> see('Account ID: 123456789');

**Comment by raistlin** [comment]
If I were in your shoes I would write a script that will:
- enable your testing user (or create if the user doesn't exists)
- launch tests
- disable testing user

You can also develop your needs and make a pull request ;-)

**Comment by Naktibalda** [comment]
Password hiding feature was implemented in 3 years ago in Codeception 2.3 https://github.com/Codeception/Codeception/pull/4743
