### ISSUE TITLE
Update Facebook Driver for Facebook SDK v5

### ISSUE THREAD

**Issue by JarJak** [Codeception/Codeception#2415]
Facebook Driver needs to be updated because its not working anymore...
For now it's compatible only with SDK v4:
https://github.com/Codeception/Codeception/commit/8993ccbc1548da28ef90d0b4170972c3889c2e92
which is not working anymore and new version of SDK is incompatible with what we have there, for example there is no FacebookSession class anymore.

**Comment by JarJak** [comment]
any news about this issue?

**Comment by Naktibalda** [comment]
No, would you like to do it?

**Comment by JarJak** [comment]
i'm not sure how

**Comment by orhan-swe** [comment]
I have created a pull request for this: #2722 but my changes will break support for version 4 of sdk

**Comment by Naktibalda** [comment]
Hi @tiger-seo,

When you wrote
`@orhan-swe please, resend your PR to branch Codeception:feature/facebook-upgrade, so that we can finish it and merge to the 2.1. thanks`, did you mean that you are going to finish it yourself?

I think that it would be better to merge this change to master branch.

**Comment by tiger-seo** [comment]
yea, let's merge it https://github.com/Codeception/Codeception/pull/2828
