### ISSUE TITLE
selectOption issue in innerBrowser

### ISSUE THREAD

**Issue by rannk** [Codeception/Codeception#2416]
If I want to check the radio input that the value is "0", the selectOption step will failed.
I get the error message like this
[InvalidArgumentException] Input "....." cannot take "" as a value (possible values: 0, 1, 2).

I check the code in innerBrowser, line 722.
```
if ($options->first()->attr('value')) {
    return $options->first()->attr('value');
}
```
The code could change like this, that could resolve this issue
```
if (!($options->first()->attr('value') === false)) {
    return $options->first()->attr('value');
}
```

**Comment by Naktibalda** [comment]
Duplicate of https://github.com/Codeception/Codeception/issues/2033
Fixed by https://github.com/Codeception/Codeception/commit/faa5fb331eb15760bc88f284183f367df5a26a39

Wait for 2.1.3 release (it should come out very soon).
