### ISSUE TITLE
autoload laravel 5.0 framework classes in Acceptance testing (WebDriver)

### ISSUE THREAD

**Issue by aditya-** [Codeception/Codeception#2429]
Hi Team,

its been many days after posting here. I have laravel 5.0 app . I am just trying to write acceptance test using WebDriver module. everything ok except DB class .. i wish to use laravel DB Class for writing sql quires in my test cases.. earlier in laravel 4.2 i have initialized the app by calling

```
        $unitTesting = true;
        $testEnvironment = 'testing';

        require __DIR__ . '/../../../../vendor/autoload.php';
        return require __DIR__ . '/../../../../bootstrap/autoload.php';
```
Above code will initializes all the laravel 4.2 classes in Test Cases but where as i am unable to autoload  all the laravel 5.0 classes . i tried like this 

```
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades;
use DB;

```
its giving me ' The use statement with non-compound name 'DB' has no effect  ' error

 how i can autoload these classes for WebDriver module ?  any suggestions ? 

@DavertMik @wyhmichael @Ragazzo @codeception ?

Thanks

Regards
Aditya

**Comment by aditya-** [comment]
Any ideas??

**Comment by wyhmichael** [comment]
@aditya- not quite sure about this issue, you probably have already googled that it's might be something related to the way you are using the namespace.

**Comment by janhenkgerritsen** [comment]
For some more information about the error message look at http://stackoverflow.com/questions/9317022/troubleshooting-the-use-statement-with-non-compound-name-has-no-effect.

To use the database facade you should actually use the following use statement:
```
Illuminate\Support\Facades\DB
```

You still need to bootstrap the Laravel application though to initialize the dependency injection container. Something like this will probably work, but I haven't tested it:

```
require 'bootstrap/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make('Illuminate\Contracts\Http\Kernel')->bootstrap();
```
