### ISSUE TITLE
Does this need command line interface to work? 

### ISSUE THREAD

**Issue by HallofFamer** [Codeception/Codeception#2431]
Well I downloaded the .phar file for codeception, and I actually managed to use a service to extract the contents inside it, and the upload the folder to my site through ftp. The extracted folder structure looks like this: /ext, /src, /vendor, autoload.php, codecept. 

I read from the documentation and it seems that I need to run commands like "$ php codecept.phar run acceptance --steps" to run the tests. If I have a linux PC I would be able to use the terminal, but what if I do not have access to run the commands? Or if I do not know how to run these commands anyway since my site/application is on a webhost? 

Is there a way for me to run the tests without using command line prompt? I do see that the file codecept contains some php code. So if I turn it into a .php file an access it from the url of my website, will it run my tests? Or is running tests through command line the only option?

**Comment by Naktibalda** [comment]
Use [WebCeption](https://github.com/jayhealey/Webception)
