### ISSUE TITLE
Could we send Raw HTTP body using sendPost? [REST module]

### ISSUE THREAD

**Issue by parisqian-misa** [Codeception/Codeception#2433]
Regarding https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/REST.php

**Comment by Naktibalda** [comment]
Yes, simply pass a string as second parameter.

```php
$I->sendPOST('/api', 'raw body');
```

**Comment by parisqian-misa** [comment]
It works! Thank you so much!
