### ISSUE TITLE
$I->setCookie(); works not like changing cookie value in browser

### ISSUE THREAD

**Issue by jepster** [Codeception/Codeception#2436]
If I change the cookie value in my browser (chrome) the cookie can be re-set then from my application. If I do it with $I->setCookie(); I cannot. Is there any issue with "$I->setCookie()"?

**Comment by Naktibalda** [comment]
@jepster What exactly is an issue to you? 
Is the wrong value sent in the following requests? Do you get a wrong value from some inspection method?

Which module do you use? PhpBrowser, WebDriver or Yii2?

**Comment by jepster** [comment]
I've used PhpBrowser and WebDriver. I'm clearing now the cookies at every test, because the cookie's value couldn't be set during the test.

**Comment by Naktibalda** [comment]
PhpBrowser and WebDriver manage cookies in absolutely different ways.

Your issue description is not sufficient, please describe it better.
Test code and some application code to support it would make your issue easier to understand too.

**Comment by Naktibalda** [comment]
@jepster Please provide more information or this issue will be closed.
