### ISSUE TITLE
Using --tap when executing Api suite executes Acceptance suite

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#2437]
Hi, I have found an issue when using --tap option

If you do:

`vendor/bin/codecept run --fail-fast api`

executes the Api suite tests:

![screen shot 2015-10-09 at 11 29 48](https://cloud.githubusercontent.com/assets/1375475/10390461/1889d74e-6e79-11e5-9233-c2e2f72a1247.png)

However if you do:

`vendor/bin/codecept run --fail-fast --tap api` (adding --tap)

It runs the `Acceptance` suite! 

Instead it should run the Api suite generating the Tap report. isn't it?

**Comment by Naktibalda** [comment]
--tap parameter has an optional value,
`--tap api` is requivalent to `--tap=api`

http://symfony.com/doc/current/components/console/console_arguments.html

If you want to use --tap before suite name, give it a value, e.g. `vendor/bin/codecept run --fail-fast --tap=TAP api`

Also you can put it before another parameter `vendor/bin/codecept run --tap --fail-fast api`
or at the end of command `vendor/bin/codecept run --fail-fast api  --tap`

**Comment by DavertMik** [comment]
Yes, @javigomez in when running with the params you provided it runs all suites and saves tap report to file named `api`.
