### ISSUE TITLE
codecept clean command does not delete directory if there is a .gitignore file in it

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2444]
`PHP Warning:  rmdir(/Project/tests/_output/sites/test_5617e447ddefc): Directory not empty in phar:///Project/codecept.phar/src/Codeception/Util/FileSystem.php on line 28`

It happens because there is a special exception for .gitignore in https://github.com/Codeception/Codeception/blob/f11bfe981c0a945a9b541ef177a72429adf129db/src/Codeception/Util/FileSystem.php#L23

It was introduced by this pull request https://github.com/Codeception/Codeception/pull/597

My suggestion is to check if it is _output/.gitignore specifically and delete all .gitignore files in subdirs.

**Comment by eXorus** [comment]
We still have the issue it's pretty easy to replace:

```php
            if ($basename === '.' || $basename === '..' || $basename === '.gitignore') {
                continue;
            }
```

by

```php
            if ($basename === '.' || $basename === '..') {
                continue;
            }
            if ($basename === '.gitignore' && $path->getPathInfo()->getBasename() === Configuration::outputDir()) {;
                continue;
            }
```

But it doesn't look good because we are in `Util\FileSystem.php`.

Any others idea?
If I have a folder within _output/myFolder/.gitignore, I guess we don't want to clean it.

**Comment by Naktibalda** [comment]
I have almost opposite issue now - I don't like that `clean` command deletes `.gitkeep` files in output directories, so I will add another exception for .gitkeep files.

**Comment by Naktibalda** [comment]
I raised PR to keep .gitkeep files: #6118

**Comment by eXorus** [comment]
Great so we can close this issue, it's not relevant anymore, what do you think?

**Comment by Naktibalda** [comment]
I don't remember why it was an issue to me any more.
