### ISSUE TITLE
Multiple support folders

### ISSUE THREAD

**Issue by AlterEgo7** [Codeception/Codeception#2447]
The ability to set an array of folders as support folders. The main reason for this is to have 'global' folders for page objects, step objects and helpers.

For example, I have written several drupal modules each of which has its own tests. In the root drupal directory I have a codeception.yml that includes the tests from each module and runs them together. I would like to be able to add a global support folder (along with the existing in each module) so that all the tests can share the same page objects, step objects and helpers.

**Comment by Naktibalda** [comment]
Have you seen Codeception [Autoload](http://codeception.com/docs/reference/Autoload) class?

Add `Autoload::addNamespace('', '/path/to/pageobjects');` to _bootstrap.php file.

**Comment by AlterEgo7** [comment]
I can confirm The above works fine.

Thanks
