### ISSUE TITLE
$I-see($xml) is broken in 2.1.3

### ISSUE THREAD

**Issue by nsossonko** [Codeception/Codeception#2461]
One of our Cest tests checks for an XML response by calling `$I->see($xml)` where `$xml` is just a string of XML that the response is suppose to contain. In all previous versions of Codeception this worked without a problem, now, however, it is broken. The message given is:

Step  I see `"<foo><![CDATA[foo]]></foo><bar>1</bar>"`
 Fail  Failed asserting that   /main/api
--> 1
--> contains `"<foo><![cdata[foo]]></foo><bar>1</bar>"`.

It seems the values are now what's being compared instead of the actual content of the response and within that, only the non-CDATA enclosed values.

**Comment by Naktibalda** [comment]
1. In which version did it work?
2. Why don't you use REST module for testing API?

**Comment by nsossonko** [comment]
1. Up until version 2.1.2 (the version we are currently using).
2. We do, but for our structure we have a simple general test in which we don't want to test individual properties rather overall working condition of different features of the API.

**Comment by Naktibalda** [comment]
I can confirm that it was broken by this commit https://github.com/Codeception/Codeception/commit/474b0959fb935392b567b5f9d06d350b390d8d8a

**Comment by Naktibalda** [comment]
It is a conflict between users who want to match text and users who want to match tags.
@zbateson @DavertMik

**Comment by nsossonko** [comment]
Shouldn't there be the option for both ways? There is no way to check CDATA enclosed strings now with this method, btw.

**Comment by Naktibalda** [comment]
Proposal. Strip tags from content only if there are no tags in $needle.

**Comment by zbateson** [comment]
I vote for a second method... $I->seeInSource for instance.  I'm not a big fan of auto stripping because someone looking for a tag on the page's displayed content may have a tough time understanding why it doesn't work.

$I->see was changed to align it more with how it works in WebDriver - as in what it can "see" on the page.

**Comment by DavertMik** [comment]
Yes, `see` was not supposed to check the source code. 
@zbateson can we have `seeInSource` to work in both InnerBrowser and WebDriver?

**Comment by nsossonko** [comment]
Wait, so I didn't understand the original question about why not use the REST module. Did you mean that I should use seeResponseContains from the REST module? I never noticed that function and I think that would do the trick for us.

**Comment by nsossonko** [comment]
Confirmed that seeResponseContains works perfectly for me, and I changed my test already so this can be closed as far as I'm concerned...

**Comment by zbateson** [comment]
Hmmm... nice.

@DavertMik I'll have to look into that.  I'll try push something in the next couple of days either just for InnerBrowser or if possible for both InnerBrowser and WebDriver.
