### ISSUE TITLE
seeInField doesn't return value for textarea

### ISSUE THREAD

**Issue by CodyCodeman** [Codeception/Codeception#2464]
seeInField invokes `getText()` on the `Facebook\WebDriver\Remote\RemoteWebElement` Object and the documentation for that method states it returns innerText which is nothing on some (all?) textarea elements.  Seems like it should be invoking `$el->getAttribute('value');` instead of `$el->getText();`

**Comment by nsanden** [comment]
Does this just need a pull request for `$el->getAttribute('value')` or is it more complicated than that?

**Comment by Naktibalda** [comment]
Yes, just that.

But it would be better if you added a test for your issue to https://github.com/Codeception/Codeception/blob/2.1/tests/unit/Codeception/Module/WebDriverTest.php

There are some tests testing some other functionality of textarea,
so you can reuse /form/textarea page which displays https://github.com/Codeception/Codeception/blob/2.1/tests/data/app/view/form/textarea.php

**Comment by nsanden** [comment]
Think I got it, thanks for explaining

**Comment by nsanden** [comment]
@Naktibalda - I found another bug that i've fixed now and created a test for... I can't remember how to run the damn test for the life of me though. Can you help me out?

**Comment by Naktibalda** [comment]
Get robo.phar, run it, there is a command to run WebDriver tests

**Comment by nsanden** [comment]
Thanks, I got some errors when running robo (I think my environment isnt well suited for virtualization) but never the less it got me on the right track (in the output of the robo command it listed the `./codecept run tests/unit/Codeception/Module/WebDriverTest` which is what i needed).

I'll look into the robo error later and see if I can update the README with better instructions on running tests with and without robo.phar

**Comment by artyfarty** [comment]
It doesn't work anymore. Old getText() does though.
