### ISSUE TITLE
Symfony2 Command Testing

### ISSUE THREAD

**Issue by vgross** [Codeception/Codeception#2468]
I have a lot of different commands in my project which is doing some work on the DB.

I would like to test those ones but I can't find anything on the documentation neither on the internet about how to launch a command on the test? It seems the "Process" component from symfony doesn't work on my local environnement (Mac Book pro), maybe it's not the good approach ?

Is anyone can give me advice about that ?

**Comment by DavertMik** [comment]
We don't use Symfony/Process component. Actually you can try [Cli](http://codeception.com/docs/modules/Cli) module for testing commands. At least Codeception itself [uses it to test its commands](https://github.com/Codeception/Codeception/tree/2.1/tests/cli)

**Comment by raistlin** [comment]
I also had some commands at my project.

My solution is quite simple and efficient: I have moved all code from the command to a service and only left at command code related in parsing command arguments.

**Comment by bratok** [comment]
May be it will be useful. If you use Symfony module, that you can add method to Helper class. You can get instance of Symfony module in the method. Instance has a public property $kernel. You   can return it and write test for command like describe in symfony docs.

```
 namespace App\Tests\Helper;
 // here you can define custom actions
 // all public methods declared in helper class will be available in $I
 class Cli extends \Codeception\Module
 {
     public function getKernel()
     {
         $symfonyModule = parent::getModule('Symfony'); 
 
         return $symfonyModule->kernel;
     }
 }
```
