### ISSUE TITLE
Test is run twice

### ISSUE THREAD

**Issue by sbrauwers** [Codeception/Codeception#2469]
I'm having this issue, that I struggle to solve. I'm using Codeception 1.8.7, because we need to use PHP 5.3.

As you can see in the code below, its a very simple test to explain the issue.
I declare a counter and display it. When the method "tryToTest" is run, I increment the counter;
Then I display the counter; Once with echo() and once with amGoingTo() method.

```
<?php
use \ApiGuy;

class debugCest
{

    public $testCounter = 0;

    public function _before()
    {
        echo "Before 1";
    }

    // tests
    public function tryToTest(ApiGuy $I) {
        $this->testCounter++;
        echo "\n COUNTER A: " . $this->testCounter;
        $I->amGoingTo('show COUNTER B: '. $this->testCounter);
        
    
    }

}
```

Now, when we run the test. We expect the method tryToTest(), to be run only once, right?

So when we run
```
php codecept run api debugCest.php
```

This should be our expected output:
```
Codeception PHP Testing Framework v1.8.7
Powered by PHPUnit 3.7.37 by Sebastian Bergmann.

 COUNTER A: 1
Api Tests (1) -----------------------------------------
Trying to try to test (debugCest.tryToTest)
Scenario:
* I am going to show COUNTER B: 1
 PASSED

-------------------------------------------------------

Time: 844 ms, Memory: 7.75Mb

OK (1 test, 0 assertions)
```

But for some reason this is my output, it seems that the method "TryToTest" is run twice??
```
Codeception PHP Testing Framework v1.8.7
Powered by PHPUnit 3.7.37 by Sebastian Bergmann.

 COUNTER A: 1
Api Tests (1) -----------------------------------------
Trying to try to test (debugCest.tryToTest)
Scenario:
* I am going to show COUNTER B: 2
 PASSED

-------------------------------------------------------

Time: 844 ms, Memory: 7.75Mb

OK (1 test, 0 assertions)
```

**Comment by Naktibalda** [comment]
@tomtomsen has never made a pull request to Codeception,
Apply his patch to your Codeception and see if it helps.

**Comment by Naktibalda** [comment]
I was wrong about that, his patch was merged and released with 1.8.2.

**Comment by samdark** [comment]
So is there still an issue?

**Comment by sbrauwers** [comment]
I guess not, since I cannot replicate it in 2.1
