### ISSUE TITLE
Fix module conflicts functionality

### ISSUE THREAD

**Issue by janhenkgerritsen** [Codeception/Codeception#2470]
Currently the conflicts functionality for modules does not work because the framework modules do not implement the `Codeception\Lib\Interfaces\ConflictsWithModule` interface. So the code in the [`validateConflicts`](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/ModuleContainer.php#L185) method in the `Codeception/Lib/ModuleContainer` class never finds a conflict.

The code in the `validateConflicts` method needs another fix. In the second for loop the `$inspectedModule` should be compared to the `$currentModule`, and if they are same it should skip the checks, otherwise modules can conflict with themselves.

**Comment by janhenkgerritsen** [comment]
Also look into allowing certain parts of modules. As an example, you can now include the ORM part of the Laravel module when you are using WebDriver, this will let you do some database asserts, but more importantly it also allows you to use Laravel models to do for example test data setup.

But using the Laravel module for this is actually a bit overkill. You can also add the code to bootstrap Laravel to your test suite `_bootstrap.php` file and have access to the Laravel functionality. That's only 4 lines of code. But maybe we should provide some easier method to do this?

**Comment by Naktibalda** [comment]
@DavertMik @janhenkgerritsen was it fixed?

**Comment by janhenkgerritsen** [comment]
No this is not fixed yet. We decided to do this for 2.2, since it will probably generate a lot of errors for people who are using conflicting modules together.

We also need to determine which modules conflict with each other, but I haven't really thought about that yet.

**Comment by Naktibalda** [comment]
Is it more complicated than all functional testing modules conflict with each other?

**Comment by Naktibalda** [comment]
Original intention was that PhpBrowser and WebDriver conflicts with each other and all frameworks.
They both implemented _conflicts method:
```
    public function _conflicts()
    {
        return 'Codeception\Lib\Interfaces\Web';
    }
```

I see that it is no longer possible to implement the original intention, because many framework modules have `ORM` part (Symfony2 has `services` part) as a workaround for solving conflicts.

Conflict checker has to check if only a part of module is loaded.
Or we could extract ORM modules out of framework modules.

**Comment by janhenkgerritsen** [comment]
Is it easy to determine if only parts of a module are loaded?

It would be nice to have this functionality working, because a lot of issues are reported by users that are for example using the Laravel module with the Webdriver module.

What do you think @DavertMik?

**Comment by DavertMik** [comment]
> It would be nice to have this functionality working, because a lot of issues are reported by users that are for example using the Laravel module with the Webdriver module.

Yes. that's why I started to implement it

> Is it easy to determine if only parts of a module are loaded?

Nut sure for now. I need to investigate deeper to find out the best way to make conflicts work with parts. Sure you can use Laravel.ORM with WebDriver as they are not in conflict

**Comment by DavertMik** [comment]
I will work on it in next days. This **must** be in 2.2
