### ISSUE TITLE
Add JSON Schema assertions

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#2472]
REST module shoould also provide JSON matches my [JSON Schema](http://json-schema.org/). This would be something like JSON Type but more strict and universal. This libraries can be used:
- https://github.com/justinrainbow/json-schema
- https://github.com/hasbridge/php-json-schema
- https://github.com/geraintluff/jsv4-php

**Comment by ruudboon** [comment]
This would be awesome if this can be added

**Comment by ruudboon** [comment]
I think this library could work as well. https://github.com/opis/json-schema
