### ISSUE TITLE
Make Codeception compatible with Incenteev ParameterHandler

### ISSUE THREAD

**Issue by marcverney** [Codeception/Codeception#2477]
Hello,

_Note: for the sake of simplicity I will focus on codeception.yml but the same applies to *.suite.yml files._

When you work in a team, your `codeception.yml` is likely to differ from your coworkers'. Codeception solves this by proposing "you put shared settings into `codeception.dist.yml` and personal settings into `codeception.yml`", Which is great.

I think this system could be improved by making it compatible with the [ParameterHandler](https://github.com/Incenteev/ParameterHandler) script for Composer (widely used in Symfony, for instance). This would allow the user to be literally asked for their parameters on the first composer install/update after each change in the dist file. The script then automatically generates the `codeception.yml` based on their answers.
This way you wouldn't need to go and tell your coworkers they have to create a `codeception.yml` there and there, and what parameters they would have to specify in it. Everything would happen automatically.

Implementing this would require at least (and maybe "only"):
- ~~using `.yml.dist` as extension instead of `.dist.yml`~~ (edit: it's configurable)
- using a top level Yaml key in the dist file (ideally `parameters`, as this is the default in ParameterHandler, but this can be changed in `composer.json`)

I think this would be a great new feature for teams working with Codeception.

**Comment by DavertMik** [comment]
We have implemented [Params](http://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Params) in slightly different way. Probably you can define params file and maintain it using Incenteev ParameterHandler
