### ISSUE TITLE
# hashtag or pound symbol is removed from webdriver url

### ISSUE THREAD

**Issue by sbrauwers** [Codeception/Codeception#2499]
For my website I need the # symbol in the url, otherwhise it will not work.
Acceptance.suite.yml
```
- WebDriver:
    url: 'http://www.example.com/learner.html#'
```

testCept.php
```
$I->amOnPage('/login');
```

But when I run the test, it removes the # from the url.
So instead of 
```
* I am on page "/login"

  [GET] http://www.example.com/learner.html#/login
```
I see, which does not work for my application
```
* I am on page "/login"

  [GET] http://www.example.com/learner.html/login
```

**Comment by Naktibalda** [comment]
url parameter is a starting URL, not a base for all other requests.

Try this:
```php
$I->amOnPage('#/login');
```

**Comment by Naktibalda** [comment]
I was wrong about the base thing, but this code should open http://www.example.com/learner.html/#/login.

**Comment by sbrauwers** [comment]
http://www.example.com/learner.html/#/login does not work for me, note the / before the #

http://www.example.com/learner.html#/login only works

**Comment by Naktibalda** [comment]
OK, WebDriver handles amOnPage in a completely different way than InnerBrowser: https://github.com/Codeception/Codeception/blob/deba99e48ee5799fc9305ada6a8a53256376594e/src/Codeception/Module/WebDriver.php#L490

A simple fix would be to modify https://github.com/Codeception/Codeception/blob/c01a19f337e1afb06c926ee2cfc60d4e5eca20d4/src/Codeception/Util/Uri.php#L91

to check if $path starts with '#' and don't add '/' between $url and $path if it does.

@sbrauwers Would you like to beat me to it and make a pull request?

**Comment by sharpless512** [comment]
Yeah pls do that

**Comment by sharpless512** [comment]
yes, please change that.

**Comment by sbrauwers** [comment]
yes please change that. i'm not sure how to do a pull request

**Comment by Naktibalda** [comment]
If you need a quick fix, set configuration to:
```yaml
- WebDriver:
    url: 'http://www.example.com/'
```

And your test code to
```php
$I->amOnPage('learner.html#/login');
```

**Comment by sbrauwers** [comment]
Alright thanks!

**Comment by sbrauwers** [comment]
Thanks!
