### ISSUE TITLE
\Codeception\Util\JsonType filter delimiter ":" does not allow to use ":" in regex filter

### ISSUE THREAD

**Issue by vslovik** [Codeception/Codeception#2501]
`````` $I->seeResponseMatchesJsonType([
"created_at" => "string:regex(~\d{2}\/\d{2}\/\d{4} \d{2}:\d{2}:\d{2}~)"
]);```

will cause an error for {"created_at":"29/10/2015 08:15:44"}
because of explode by ":" that will break regex pattern,
but it's wrong.

I can use custom filter like a workaround, but the documentation confuses
me hiding the fact that ":" can not be used in regex.
``````

**Comment by niclopez** [comment]
Hi,

I've not been able to use the "|" symbol, too inside a regular expression. In my case, the problem is located around line 120: (\Codeception\Util\JsonType)
...
$matchTypes = explode ('|', $type);
...

I'm trying to do something similar to this with no success:

$I->seeResponseMatchesJsonType(array(
  'code' => 'integer:regex(/100|300/)', // unable to use '|' inside regex...
));

Thanks Davert for your great job!!

**Comment by niclopez** [comment]
Hi again Davert & Vslovik,

I found a solution for this issue. Replacing "explode" statement for "preg_split" alternative works well, too. Doing this, string located inside regex() parenthesis is excluded and regex patterns does his job.

To solve this, just replace following lines at "\Codeception\Util\JsonType" file:

line 120 (pipe character):
// $matchTypes = explode('|', $type);
$matchTypes = preg_split("#(?![^]\(]*\))\|#", $type);

line 127 (colon character):
// $filters = explode(':', $matchType);
$filters = preg_split("#(?![^]\(]*\))\:#", $matchType);


NLopez

**Comment by niclopez** [comment]
My bad, I copy/paste the wrong regex version:

line 120 (pipe character):
// $matchTypes = explode('|', $type);
$matchTypes = preg_split("#(?![^]\(]*\))\|#", $type);

line 127 (colon character):
// $filters = explode(':', $matchType);
$filters = preg_split("#(?![^]\(]*\))\:#", $matchType);

Sorry

**Comment by niclopez** [comment]
Hi @DavertMik,

is there any option to include this fix in your repository code?

thanks¡

**Comment by Naktibalda** [comment]
Make a pull request.

https://github.com/Codeception/Codeception/blob/2.1/CONTRIBUTING.md

**Comment by Naktibalda** [comment]
@niclopez your patch is an improvement, but it doesn't solve all issues.

Test code:
```
$jsonType = new JsonType(['code' => 'xyz']);
$this->assertTrue($jsonType->matches(['code' => 'string:regex(~((xyz)|(abc))~)']));
```

Result:
`[PHPUnit_Framework_Exception] preg_match(): No ending delimiter '~' found`

**Comment by DavertMik** [comment]
I agree with @Naktibalda here, JsonType should be rewritten to handle such cases.

**Comment by ellisgl** [comment]
Here's another regex fail:
    
    $jsonType = new \Codeception\Util\JsonType(['time' => '21:00']);
    $this->assertTrue($jsonType->matches(['time' => 'string:regex(~^([0-1]\d|2[0-3]):[0-5]\d$~)']));

**Comment by ellisgl** [comment]
Here's some stuff I'm working on for a fix. 

```
$regexCnt = 0;
$regexes = [];
$subject = 'string:regex(~^([0-1]\d|2[0-3]):[0-5]\d$~)|string:regex(#^([0-1]\d\|2[0-3]):[0-5]\d$#)';

preg_match_all('/:regex\((.*?[!"#$%&\'*+,.\/:;=?@^_`|~-])\)/', $subject, $regexes);

$subject = preg_replace_callback('/:regex\((.*?[!"#$%&\'*+,.\/:;=?@^_`|~-])\)/', function($m)
{
    static $count = 0;

    return ':regex($$' . $count++ .')';
}, $subject);
```

**Comment by ellisgl** [comment]
This should fix it: https://github.com/Codeception/Codeception/pull/5273

**Comment by ellisgl** [comment]
@DavertMik You OK. Haven't seen any activity from you in about a week.

**Comment by ellisgl** [comment]
@Naktibalda I noticed you have been commenting. What's up?
