### ISSUE TITLE
CURL exceeds timeout if Xdebug is on

### ISSUE THREAD

**Issue by jepster** [Codeception/Codeception#2510]
I would like to use the xdebug debugger while my acceptance test runs with PhpBrowser or WebDriver. Xdebug is connected to the CURL request, but does not allow me to step through the code. The debugging session hangs. 

If I set the debugger to break at the first line of executed php code, then I get only into the codeception runner php code.

I'm using PhpStorm as IDE. Is there any chance to debug the php code of my application with xdebug while the acceptance test runs in the headless browser or is that not possible during CURL?

**Comment by Naktibalda** [comment]
You have to start xdebug session in the code of your application.

**Comment by jepster** [comment]
How can I do that? xdebug.remote_autostart is set to 0, but if I turn my ide PhpStorm into listening for incoming debug connections, the acceptance tests run hangs. Like described above.

**Comment by DavertMik** [comment]
Sorry, no ideas (
