### ISSUE TITLE
Webdriver does multiple implicit waits per one click() action

### ISSUE THREAD

**Issue by sustmi** [Codeception/Codeception#2511]
When you do eg.:

``` php
$I->click('Send');
```

`Webdriver` calls `findClickable()` method which progressively tries to match `Send` as:
- CSS or xpath
- narrow search in HTML content
- wide search in HTML content

If you have `config.WebDriver.wait` setting set to eg. 10 seconds, it waits 10 seconds several times. First when it tries to match `Send` as CSS or xpath, then when it does narrow search and so on.

That means even if the `Send` text is present on the page immediately, Codeception waits 20 seconds before it finds the text using wide search match.

This unacceptably slows down the tests.

**Comment by javigomez** [comment]
This not solves your comment gives an alternative:

**Comment by DavertMik** [comment]
Config `wait` behavior changed. See SmartWait http://codeception.com/docs/03-AcceptanceTests#SmartWait
