### ISSUE TITLE
Reading acceptancesuite.yml configuration details from Excel file

### ISSUE THREAD

**Issue by learntech123** [Codeception/Codeception#2513]
Hi,

Anyone pl tell me is there any way to read the configuration details form Excel spread sheet.

That is instead of acceptancesuite.yml file, is there any way to read this details from excel file??

Or anyway acceptancesuite.yml file can read the contents from excel file.??

**Comment by javigomez** [comment]
Would this work for you? http://stackoverflow.com/questions/3364850/convert-from-database-excel-csv-to-yaml-data-fixtures

**Comment by Naktibalda** [comment]
There is no way to load configuration details from excel file.
