### ISSUE TITLE
Unreachable field error because of brackets in form action

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#2514]
I am getting an error:
*Unreachable field "status"

The form:
```php
       <form id="w12" action="/dmn/lw/5/userend/web/index-test.php?r=article%2Farticle%2Fupdate&amp;id=1&amp;ids=[2]" method="post">
<div id="QQ" class="switch-input">

 <input type="radio" name="Article[status]" value="0" checked> 
 <input type="radio" name="Article[status]" value="1">
</div>
</form>
```

I drilled the error down and it seems that it occurs because of the "ids=[2]" in the action parameter. When removing this part, it works ok.

**Comment by Naktibalda** [comment]
Please add your test code.
Have you tied to reach it as "Article[status]" ?

Your HTML is invalid, one <label> tag is missing.

**Comment by dynasource** [comment]
its because of the brackets in the action parameter of the form.

**Comment by Naktibalda** [comment]
URL parameters must be URL encoded, change ids=[2] to ids=%5B2%5D

Use `url_encode `function if url is generated dynamically

**Comment by dynasource** [comment]
well, something strange is going on over here. Closing this one till I found out why. Thx..

**Comment by dynasource** [comment]
the issue seems to be related with having multiple forms on a page and the 'selectOption' changing the focus on these forms.
