### ISSUE TITLE
DataProvider for codeception.

### ISSUE THREAD

**Issue by Asera** [Codeception/Codeception#2515]
Tried to use PHPUnit DataProvider for Codeception Acceptanse Cest and got couple of errors. I have a lot of similar tests with different incoming data so some kind of DataProvider will be quite usefull. Instead of getting parameters with DataProvider DI try to inject AccepTanceTester in arrays with data. Is there any way to use PHPUnit DataProvider in Cest? Maybe there are any alternatives similar to it?
Here's the example of error I've got:
Cannot use object of type AcceptanceTester as array in file /path/to/project/tests/acceptance/LoginCest.php on line 40

**Comment by DavertMik** [comment]
It is impossible to use data providers with acceptance tests in Cest. Unfortunately no alternatives for now :(

**Comment by codemedic** [comment]
+1 

It would make a huge difference if Data Providers can be implemented, somehow, in Codeception.
It definitely would help reduce test code, and would help maintainability.

**Comment by iborodikhin** [comment]
Possible hack to simulate data-providers in acceptance tests. Add following to _support/Helper/Acceptance.php:
```
    /**
     * Runs test with data-provider emulation.
     *
     * @param  \AcceptanceTester $I
     * @param  callable          $test
     * @param  callable          $provider
     * @throws \Exception
     */
    public function executeWithDataProvider(\AcceptanceTester $I, callable $test, callable $provider)
    {
        $i     = 0;
        $fails = [];
        $data  = call_user_func($provider);

        foreach ($data as $item) {
            try {
                $I->amGoingTo('Execute scenario with data provider | #' . ++ $i);
                array_unshift($item, $I);
                call_user_func_array($test, $item);
            } catch (\PHPUnit_Framework_Exception $e) {
                $I->comment("!!!> " . $e->getMessage());

                $fails[] = $e;
            }
        }

        if (count($fails) > 0) {
            throw array_shift($fails);
        }

        $this->assertEquals(0, count($fails));
    }
```

Then in tests use like this:
```
public function testMe(AcceptanceTester $I) 
{
        $I->executeWithDataProvider($I, function (AcceptanceTester $I, $url, $code) {
            $I->amOnPage($url);
            $I->seeResponseCodeIs($code);
        }, [$this, 'provideTestData']);
}

    /**
     * Data-provider for test.
     *
     * @return array
     */
    public function provideTestData()
    {
        return [
            ['/', 200],
            ['/protected', 401],
            ['/not-found-url', 404],
            ['/faulty', 500],
        ];
    }
```

**Comment by codemedic** [comment]
@iborodikhin that looks very nice approach indeed. I like the fact that the data provider aspect appears in the steps output as well.

Wonder if it is feasible to have a similar feature provided by the framework.

**Comment by eXorus** [comment]
+1

**Comment by DavertMik** [comment]
Implemened in #2846
