### ISSUE TITLE
multiple 'sendGet' from REST Module doesn't use base url

### ISSUE THREAD

**Issue by Vishnja** [Codeception/Codeception#2521]
Hello. If I use sendGET for the second time in test:
$I->sendGET('api/get_app', ...);
Url isn't formed like 'base url' + 'uri from request'. 
So, for the second call of $I->sendGET('api/get_app', ...) url will be like 'www.example.com/api/api/get_app'. ('api' segment adds once more).
Base url is setted in functional.suite.yml.
Is it expected behavior?

**Comment by Naktibalda** [comment]
Try starting 'uri from request' with /

**Comment by Vishnja** [comment]
Thank you! This helps.
