### ISSUE TITLE
Laravel5 Module: disable cleanup

### ISSUE THREAD

**Issue by devinfd** [Codeception/Codeception#2525]
@janhenkgerritsen @DavertMik 

I've run into a situation where I need to temporarily disable the cleanup functionality for a few of my unit tests. I need this because some of the database fields have full text search indexing on them and per mysql "The FULLTEXT search only returns a result after the inserted lines are committed" https://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html#idm139848296124192

Is there a way to do this? If not I can send a PR to add this functionality but I am not familiar with Codeceptions inner workings.

It would be great if there were `$I->disableCleaUp()` and `$I->enableCleaUp()` methods.

**Comment by janhenkgerritsen** [comment]
The `$config` variable of the Laravel 5 module is public, so you can change the `cleanup` entry in this array yourself by adding a helper. That will work for you now. And I will add the proposed methods to the module when I have some time.

**Comment by devinfd** [comment]
Ok.  I'll see what I can do.

**Comment by devinfd** [comment]
As a follow up. I created a trait `SudoDatabaseTransactions` that stopped the cleanup/transaction functionality but still "cleaned" the written data.

Basically this trait has a `_before` method that counteracts the laravel5 module _before method and an `_after` method that truncates the tables. And to get this behavior I just use the trait in my test class.

```php
namespace Helper;

trait SudoDatabaseTransactions
{
    /**
     * Database tables to clean
     *
     * @var array
     */
    protected $tables = [
        'users',
        'posts',
        'comments'
    ];

    /**
     * @before
     */
    public function _beginSudoDatabaseTransaction()
    {
        $this->getModule('Laravel5')->getApplication()['db']->rollback();

        $this->getModule('Laravel5')->config['cleanup'] = false;
    }

    /**
     * @after
     */
    public function _endSudoDatabaseTransaction()
    {
        $laravel = $this->getModule('Laravel5');
        $db = $laravel->getApplication()['db'];

        $db->statement('SET FOREIGN_KEY_CHECKS=0');

        foreach ($this->tables as $table) {
            $db->table($table)->truncate();
        }

        $db->statement('SET FOREIGN_KEY_CHECKS=1');

        $laravel->config['cleanup'] = true;
    }
}
```

**Comment by janhenkgerritsen** [comment]
Thanks for your follow up, maybe it will help others with a similar problem.

After some thinking I decided not to add methods to the module to disable/enable cleanup. The use case is pretty rare in my opinion, and if you do run into it, you can easily change the behavior with a helper.
