### ISSUE TITLE
Call to undefined function Codeception\Util\json_last_error_msg()

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2535]
Codeception\Util\JsonArray constructor uses json_last_error_msg() function which is not available in PHP 5.4

**Comment by sergeyklay** [comment]
http://wpseek.com/function/json_last_error_msg/

**Comment by Naktibalda** [comment]
Should it go to autoload.php ?

**Comment by sergeyklay** [comment]
It seems before. 
```php
if (!function_exists('json_last_error_msg')) {
    function json_last_error_msg()
    {
        // ...
    }
}
````

**Comment by sergeyklay** [comment]
For example https://github.com/m42e/ttrss_plugin-feediron/blob/b7f9a824c574819bf3be4bebd7ed85ef4d9dd2db/Functions.php

**Comment by Naktibalda** [comment]
Failed on PHP 5.4 with error message: Fatal error: Call to undefined function Codeception\Util\json_last_error_msg() in /home/travis/build/Codeception/Codeception/src/Codeception/Util/JsonArray.php on line 33
