### ISSUE TITLE
lambda function

### ISSUE THREAD

**Issue by neronmoon** [Codeception/Codeception#2537]
If i pass any array with 2 elements codeception step will be:
I blabla "lambda function".

I see, that Step class checks only syntax. 
```php
if (is_callable($argument, true)) {
    return 'lambda function';
}
```

Why?

**Comment by Naktibalda** [comment]
Why would you prefer to get instead?

**Comment by Naktibalda** [comment]
Put is_array check first, make a pull request.

**Comment by Naktibalda** [comment]
Answer - because nobody reported an issue before.

I think that changing that condition to `if ($argument instanceof \Closure)` would be the best solution.

**Comment by Naktibalda** [comment]
I have a crazy issue (maybe two) with "Lambda function".

My test code is:
`$I->seeResponseContainsJson(['08712222233', '08712222244']);`

The step output is:
`* I see response contains json "lambda function"`

Then I added `codecept_debug(is_callable(['08712222233', '08712222244']));` before assertion
and got this error: `[PHPUnit_Framework_Exception] include_once(08712222233.php): failed to open stream: No such file or directory`

It actually tries to autoload the first item as a class.
I can explain why I got warning in second case, but I can't explain "lambda function" in the first one.

**Comment by Naktibalda** [comment]
Ah, the difference was in the second argument - is_callable($array, true) returns true for any array containing two strings, is_callable($array, false) tries to load the class.

I was actually using an older version of Codeception than I expected, 2.1.0 prints "lambda function", 2.1.5 kills my tests.

I will change it to return "lambda function" only if the first item of array is an object, in other cases it is better to output content of array (and avoid using is_callable).

**Comment by Naktibalda** [comment]
I changed "lambda function" to "Closure" and "callable function" to content of array (object replaced with class name) for 2.2: https://github.com/Codeception/Codeception/pull/2777/files#diff-c1176bf119a1fb6370de596de823689eL20

I will backport this change to 2.1

**Comment by Naktibalda** [comment]
https://github.com/Codeception/Codeception/pull/2778
