### ISSUE TITLE
Several Step Objects in one Cest

### ISSUE THREAD

**Issue by austenc** [Codeception/Codeception#2543]
In the documentation section for 'Re-using Test Code', under 'Step Objects', there is a line that reads:

`If you have complex interaction scenario you may use several step objects in one test.`

Would it be possible to include an example of such usage in the docs?

In my past experience with Codeception (I believe it was 1.9.*), I simply put all my common actions such as `loginAsAdmin()` or `createUser()` in a common file/class as static methods and included them via `_bootstrap.php` in the tests. It appears this has now been split into StepObjects, PageObjects, and Helpers for better separation?

I was amidst refactoring my initial test suite using the latest version of Codecept and made `\Steps\Functional\Admin` and `\Steps\Functional\User` StepObjects and then realized I wasn't sure how to utilize them in my test. For example, if I'm testing that an admin can edit other users, how would I utilize both in a single Cest? Or is the solution to refactor the methods to a helper? While I like the idea of the new code re-use structure, I'm a bit confused on the implementation.

In this case, I was trying to do a test like so:

```php
public function editUser(\Step\Functional\Admin $I)
{
    // Login as admin user
    $I->loginAsAdmin();

    // ensure there is a user in the database to edit
    // $userStepObject->createUser(); 
    // the above is an example -- it feels unnatural to have two actors and/or initialize a 2nd one?

    // In the past, I'd have done something like this:
    // TestBase::loginAsAdmin($I); // passing in the actor ($I)
    // TestBase::createUser($I);
}
```

Any help is much appreciated to help me wrap my head around the differences and how I should accomplish this in the latest version of codecept! Thanks!

**Comment by DavertMik** [comment]
You can use them like 

```
public function editUser(\Step\Functional\Admin $I, \Step\Functional\User $user)
```

Both actors will share same scenario, so executing `$user->` won't switch a context to regular user, it will continue the current flow. But you can split actions between different contexts step objects to keep them separated.

**Comment by austenc** [comment]
Very helpful, thank you!
