### ISSUE TITLE
JsonType is all wrong

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2544]
Naming is wrong, API is wrong, configuration is wrong - please delete it and start from scratch.

https://github.com/Codeception/Codeception/blob/aef2dab253a67f49d87c6d6902d8f405ebdb89ee/src/Codeception/Util/JsonType.php

JsonType has nothing to do with Json (it validates a structure of array) and it evolved from TypeChecker to Validator.

JsonType filters are not filter, but validators too. 

`public function __construct($jsonArray)`
`public function matches(array $jsonType)`

It would make a lot more sense if type specification was passed as a constructor argument and data as an argument of validation method.
`matches` method returns `TRUE` if data matches and a string describing error if it doesn't.

 Field configuration is unnecessary restricted to being a string - configuration is always defined in the test code, so complex data structures or instances of validation classes could be used instead.

In my opinion it would be the best to use an existing validation library and implement type validators if they are missing.

**Comment by DavertMik** [comment]
Thanks for the feedback!

> JsonType has nothing to do with Json (it validates a structure of array) and it evolved from TypeChecker to Validator.

Agreed. Yes, this can be a `StructureType` however it is designed to work with JSON and not with XML-like structures. Maybe that can be renamed to smth like ArrayType or on other side optimized for JSON-only structures. Actually I don't know what may be better for now

> JsonType filters are not filter, but validators too.

There is no rational reason I called them "filters" :) Probably they looked like Angular filters to me )
But yes, naming is bad.

> Field configuration is unnecessary restricted to being a string - configuration is always defined in the test code, so complex data structures or instances of validation classes could be used instead.

Can you provide an example for it? 
Actually I did Swagger validation recently and it was pretty easy to get it done with JsonType, I just converted Swagger definitions to JsonType structures and added missing validators. 

> It would make a lot more sense if type specification was passed as a constructor argument and data as an argument of validation method.

Yes, makes sense

> In my opinion it would be the best to use an existing validation library and implement type validators if they are missing.

I'd like to keep it without new dependencies whenever it is possible. Currently I don't see why would we need another library. It is better to have some basic validators and mechanism for adding new ones. And that's enough for now. 

---

As I see it - JsonType was the thing I implemented in one evening and I'd like to have it improved. I don't want to make it a complex Schema-based validator, but something easy and flexible to use.

Probably we can create a new properly named class with properly named methods and add it to REST.

**Comment by Naktibalda** [comment]
> > Field configuration is unnecessary restricted to being a string - configuration is always defined in the test code, so complex data structures or instances of validation classes could be used instead.
> 
> Can you provide an example for it?

#2501 - we need a complex string parser for regex, when we could simply use `new RegexValidator('~((xyz)|(abc))~')`

**Comment by DavertMik** [comment]
Yes, I absolutely agree on parsing strings... If you have time and opportunity to make it right, I'd be glad to help.

**Comment by Naktibalda** [comment]
I wish that we had something like this for PHP: https://github.com/hapijs/joi/blob/v6.10.1/API.md

This is how I described a rather complicated schema using joi and express-validation

```js
var Joi = require('joi');

module.exports = {
  params: {
    id: Joi.number().integer().required().positive()
  },
  body: {
    service_id: Joi.number().integer().required().positive(),
    name: Joi.string().required(),
    active: Joi.boolean().required(),
    items: Joi.array().required().min(1).items(
      Joi.object().keys({
        itemId: Joi.number().integer().required().positive()
      })
    )
  }
};
```

**Comment by Naktibalda** [comment]
It is too late to change what JsonType is :)
