### ISSUE TITLE
Cept: using $I from function raises exception

### ISSUE THREAD

**Issue by sunfreakz** [Codeception/Codeception#2546]
We are using Cept format for API tests in order to make them as simple as possible.

However doing similar API requests I also want to validate response the same way. In order to avoid code duplication I created `_func.php` file with `validateCommonResponseFields(ComponentTester $I)` function to make common assertions.

The problem is that calling any method on `$I` inside this function raises exception:
```
[PHPUnit_Framework_Exception] Undefined index: class

/path/vendor/codeception/codeception/src/Codeception/Step.php:232
/path/vendor/codeception/codeception/src/Codeception/Step.php:63
/path/vendor/codeception/codeception/src/Codeception/Step.php:40
/path/suites/_support/_generated/ComponentTesterActions.php:824
/path/suites/component/Endpoint/Get/_func.php:5
/path/suites/component/Endpoint/Get/Ok_GetEndpointsForAccountCept.php:15
...
```

The problem is this line (232) in Codeception\Step:addMetaStep:
`            if (!(new \ReflectionClass($step['class']))->isSubclassOf('Codeception\Actor')) {`

Since I'm not calling `$I` from class file, `$step` looks like this:
```
array(4) {
  'function' =>
  string(17) "validate_response"
  'file' =>
  string(108) "/media/sf_html/gw3-component-tests/suites/keystone/component/Endpoints/Get/Ok_GetEndpointsForAccountCept.php"
  'line' =>
  int(14)
  'params' =>
  array(1) {
    'I' =>
    string(0) ""
  }
}
```

I don't want to move this kind of functions to Module, since validation logic is different everywhere.

Thanks for reading! :)
Any ideas?

**Comment by DavertMik** [comment]
> I don't want to move this kind of functions to Module, since validation logic is different everywhere.

why? I don't know why you would want to achieve this through function but recommended way is to create custom logic in Helper, in Actor or StepObject. Just choose one way from http://codeception.com/docs/06-ReusingTestCode and don't reinvent the wheel )

**Comment by sunfreakz** [comment]
Ok, I see your point :) We end up using Helpers. These functions did not felt right from the beginning.
Thank you!
