### ISSUE TITLE
Unable to use unsafe characters in params : REST module

### ISSUE THREAD

**Issue by niclopez** [Codeception/Codeception#2547]
Hi @DavertMik,

working with REST module I try to get the following GET request:
```
http://foo.com/api?param1=foo#bar&param2=other
```
doing this way:

```
$I->sendGET('/api', array(
  'param1' => 'foo#bar',
  'param2' => 'other'
  )
);
```
and the result is:

```
http://foo.com/api?param1=foo%23bar&param2=other
```

The test fails because is not the desired url. Is there any trick to get an exact url with no encoding unsafe characters?

Watching at module's code, the encoding is done around line 472:
```
if (!empty($parameters) && $method === 'GET') {
  $url .= '?' . http_build_query($parameters);
}
```

Just to say thanks four your great effort and your contributors, too.

**Comment by Naktibalda** [comment]
Why do you want to send unescaped hash to the server?
Browsers don't send anchor to the server - if you open `http://foo.com/api?param1=foo#bar&param2=other`, browser makes request to `http://foo.com/api?param1=foo` and scrolls down to `<a name="bar&param2=other">` or `<div id="bar&param2=other">`

Try `$I->sendGET('/api?param1=foo#bar&param2=other');`

**Comment by niclopez** [comment]
Hi @Naktibalda,

thanks for the trick! Really I don't like to send any unescaped hashed to server but I must to replicate a real scenario for a mobile carrier client; they use those kind of params in urls.
