### ISSUE TITLE
Avoid code generation

### ISSUE THREAD

**Issue by mindplay-dk** [Codeception/Codeception#2549]
Please give this some serious thought, guys: stop using code generation.

There are too many problems with code generation, and it's usually unnecessary.

For one, the code generator currently doesn't copy doc-blocks - which means, no matter how well-documented your helpers are, you're "coding blind" in an IDE.

For another, my colleague just asked me "okay, so how do I find usages of this helper method?" - erm, yeah...

Code generation should be an absolute last resort, when the language itself really doesn't cut it - that is rarely the case, and in this instance, php as of 5.4 has traits, which are basically the language way of doing (more or less) the sort of multiple inheritance you're implementing with code generation.

You require php 5.4 anyway.

Give it some thought, please? I might be able to help out.

**Comment by DavertMik** [comment]
> Please give this some serious thought, guys: stop using code generation.

Already had one, however it is impossible to do that in nearest future, as well as there are no serious reasons to do that. Generated actor classes are used for 

* autocompletion
* wrapping helper methods into steps

These things can't be achieved with traits or magic methods.

> For one, the code generator currently doesn't copy doc-blocks - which means, no matter how well-documented your helpers are, you're "coding blind" in an IDE.

Actually it does. Do you use PHAR version of Codeception? Can you copy-paste the source of your generated file?

**Comment by mindplay-dk** [comment]
Oh, you're right, it does copy the comments - below a comment that says "method is generated...".

It's still clunky to navigate the codebase via the extra generated layer - it's also peculiar when, between changes, your IDE highlights calls to helpers in red, or indicates errors on methods whose signature has changed, etc.

Anyways, go ahead and close this, since I can't off the top of my head propose a simpler alternative...
