### ISSUE TITLE
JsonType url filter is incomplete

### ISSUE THREAD

**Issue by dogawaf** [Codeception/Codeception#2555]
The filter `url`in JsonType fails to validate correctly url with a query string like `http://example.com?foo=bar`.

Here is the actual regex used: `/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/`.
I suggest to use php `filter_var` builtin function, with the flag `FILTER_VALIDATE_URL`.

What do you think?

**Comment by dogawaf** [comment]
It seems that filter_var and FILTER_VALIDATE_URL validate only absolute url. So we need a custom regex to validate both relative and absolute url.

**Comment by DavertMik** [comment]
Url is expected to be absolute in case of JSON response. At least I'd suppose it to be this way

**Comment by dogawaf** [comment]
I am good (for my testcases) to work only with absolute url, but it would be a breaking change.

**Comment by DavertMik** [comment]
...or a bug fixes :) Anyway, please add your change, I think it is ok. If anyone needs to validate relative url they can add their own filter `:uri`, for instance, and use it. Filters are really easy to add

**Comment by dogawaf** [comment]
Nice, you were faster than me :)
