### ISSUE TITLE
One Db configuration for all application ( modules ) 

### ISSUE THREAD

**Issue by sanglnv** [Codeception/Codeception#2557]
I'm applying codeception to project that has multi modules, but each module need same Db config on each moduleXXX/codeception.yml eg.

Db:
            dsn: 'mysql:host=localhost;dbname=xxx'
            user: 'xxx'
            password: 'xxx'
            dump: tests/_data/dump.sql

Because it's same on each module so anyone has way to make all module read the Db configuration on main codeception.yml on project root

Thanks

**Comment by Naktibalda** [comment]
This functionality was implemented in Codeception 2.4.2 by https://github.com/Codeception/Codeception/pull/4984
