### ISSUE TITLE
Laravel tests failure after upgrading from 2.0.15 to 2.1.2

### ISSUE THREAD

**Issue by mnabialek** [Codeception/Codeception#2559]
I have over 1400 codeception tests for Laravel 5.1 application I develop at the moment. I've been used Codeception 2.0.15. But today I've moved to Codeception 2.1.2. I've updated `api.suite.yml` and other suite configuration files but many tests are failing now.

First thing I've noticed is that data in memcached are no longer cleared after tests so tests at the moment affect each other. But it's not only that. In one of tests I run something like that:

```php
    public function tryToCompareClient(UnitTester $I)
    {
        $data = [
            'client1' => [
                'id' => 500,
                'option1' => 'yes',
            ],
            'client2' => [
                'id' => 600,
                'option2' => 'no',
            ],
        ];

        Config::set('crm_settings.clients', $data);

        $crm = App::make('crm');

        $I->assertTrue($crm->isClient('client1', $data['client1']['id']));
        // ...
```

When I run only this test it's working fine but when I run multiple a group of tests, this test will fail because `crm` is singleton in my application and it seems that when I set new config in above tests, this class is not loading data from config each time but only when it's not set. It seems that something has been changed in Codeception/Laravel5 module so `App` instance is being reused between tests.

At the moment I assume those problems are affected by refactor in [this commit][1] but the question is - is there any easy way to make Codeception to work as before 2.1.2 or maybe the only way is using old 2.0 branch for such functionality?

  [1]: https://github.com/Codeception/Codeception/commit/c356f391bbf97d9ed772db04b9f6841987f3373e

**Comment by Naktibalda** [comment]
Upgrade to 2.1.4

**Comment by janhenkgerritsen** [comment]
Can you retry running your tests with `2.1.x-dev` specified as your version for Codeception in your `composer.json` file? I did a refactoring of the Laravel modules for another issue, but it is possible that this refactoring also fixes your issue. Let me know if it works or not.

**Comment by strebl** [comment]
I had a problem too. I have a sqlite in memory setup. After the update to 2.1, my tests failed because I got duplicate entries in my db. After the 2.1.x-dev update, the db gets cleared before each test as expected.

**Comment by mnabialek** [comment]
@Naktibalda 2.1.4 doesn't help

@janhenkgerritsen This version (2.1.x-dev) fixes this issue but there are some more:

- memcached  (Laravel cache) is not now cleared after each test so when I restart memcached test passes, but when I run it again it doesn't pass because data is in memcached
- Again SQL Too many connections error occured. I've already fixed it a long time ago in this commit: https://github.com/janhenkgerritsen/codeception-laravel5/commit/508b9f5100026610f0a6bba885dc1135778ae196

**Comment by MrGrygson** [comment]
Adding Memcache module to suite config helps, but this isn't a solution as I think Laravel5 module should use Cache::flush() method to be independent of cache driver.

**Comment by janhenkgerritsen** [comment]
@mnabialek @MrGrygson I added calls to flush the cache and disconnect from the database in the `_after` method of the Laravel modules in #2619. I merged this PR into `2.1.x-dev`, can you let me know if this fixes your problems?

**Comment by mnabialek** [comment]
@janhenkgerritsen Thanks, it seems everything is working now after update

**Comment by janhenkgerritsen** [comment]
Ok great.
