### ISSUE TITLE
can fillField with text, but seeInField cant see text - selenium acceptance

### ISSUE THREAD

**Issue by nsanden** [Codeception/Codeception#2565]
```php
$text = 'This is a test. So is this.';
$I->fillField('#box', $text);
$I->wait(1);
$I->seeInField('#box', $text);
```

 Step  I see in field "#box","This is a test. So is this."
 Fail  Failed testing for 'This is a test. So is this.' in 's value:
Failed asserting that an array contains 'This is a test. So is this.'.

**Comment by nsanden** [comment]
So in debugging this, I found out 2 interesting things.

1) If I change line 722 of /Module/WebDriver.php:

FROM
```php
                $currentValues[] = $el->getText();
```
TO
```php
                $currentValues[] = $el->getAttribute('value');
```
It works (for some reason?) Not that my textarea HAS a `value` attribute. So not sure why it works.

2) The reason it said `in 's value:` is because my textarea had no "name" attribute.

**Comment by Naktibalda** [comment]
Duplicate of https://github.com/Codeception/Codeception/issues/2464

**Comment by nsanden** [comment]
Thanks, closing then
