### ISSUE TITLE
seeResponseIsJson is retrieving json decoding error #4

### ISSUE THREAD

**Issue by katmel98** [Codeception/Codeception#2570]
Good morning, I'm using CodeCeption to test a REST API.

Now I'm running this test:

<?php 
$I = new ApiTester($scenario);
$I->wantTo('Discard create an user via API because bad JSON format');
$I->haveHTTPHeader('Content-Type', 'application/json');
$I->sendPOST('patient/',badObject);
$I->seeResponseCodeIs(400);
$I->seeResponseIsJson();
$I->seeResponseContains('"app_error_code":1001');

The test is working fine until "$I->seeResponseIsJson();" line. When the test gets into this line it outputs an error: 

>Step  I see response is json 
> Fail  json decoding error #4, see http://php.net/manual/en/function.json-last-error.php
>Failed asserting that 4 matches expected 0.

The json returned by the REST API is:

{"app_error_code":1001,"app_error_messages":["El objeto paciente enviado no es válido"]}

It's a valid json so I don't understand why it's failing.

Could you help me on this?

Thanks in advance.

p.d.: I've been investigating over here and it seems that this behavior have been reported before but it is still giving me this error.

**Comment by Naktibalda** [comment]
Run the test with -vv flag to check what output you actually get.

**Comment by katmel98** [comment]
Thnx for your quick response, I supose -vv is equal to --debug, this is the output:

1) Failed to discard modify an user via api because bad json format in DiscardPatientModifyBadFieldCept (tests/api/DiscardPatientModifyBadFieldCept.php)

 Step  I see response is json 
 Fail  json decoding error #4, see http://php.net/manual/en/function.json-last-error.php
Failed asserting that 4 matches expected 0.

Scenario Steps:

 4. $I->seeResponseIsJson()
 3. $I->seeResponseCodeIs(400)
 2. $I->sendPOST("patient/","{
    "type": "100",
    "dni": "295674837L",
    "paort": null,
    "first_name": "Luisa",
    "last_name1": "Perez",
    "last_name2": "Perollo",
    "gender": "F",
    "birth_date": "01-01-1990",
    "address": "CalleEjemplo, 1, 1B",
    "postal_code": "28932",
    "community": "Municipio",
    "province": "Madrid",
    "country": "País",
    "email": "ejemplo@email.com",
    "phone1": "674546345",
    "phone2": null,
    "doctor_id": "P000001",
    "nuhsa": "000001",
    "nhc": "000000",
    "ss": "000000",
    "exitus": "N",
    "exitus_date": "01-01-1990"
}")
 1. $I->haveHttpHeader("Content-Type","application/json")


FAILURES!
Tests: 1, Assertions: 2, Failures: 1.

**Comment by katmel98** [comment]
Sorry my mistake closing it :-(

**Comment by Naktibalda** [comment]
What I actually wanted to see was "Response" line in debug output.

**Comment by katmel98** [comment]
Sorry, this is the output:

Discard modify an user via API because bad JSON format (DiscardPatientModifyBadFieldCept)
Scenario:
* I have http header "Content-Type","application/json"
* I send post "patient/","{
    "type": "100",
    "dni": "295674837L",
    "paort": null,
    "first_name": "Luisa",
    "last_name1": "Perez",
    "last_name2": "Perollo",
    "gender": "F",
    "birth_date": "01-01-1990",
    "address": "CalleEjemplo, 1, 1B",
    "postal_code": "28932",
    "community": "Municipio",
    "province": "Madrid",
    "country": "País",
    "email": "ejemplo@email.com",
    "phone1": "674546345",
    "phone2": null,
    "doctor_id": "P000001",
    "nuhsa": "000001",
    "nhc": "000000",
    "ss": "000000",
    "exitus": "N",
    "exitus_date": "01-01-1990"
}"

  [Request headers] {"Content-Type":"application/json"}
  [Request] POST http://192.168.56.101:8090/integrator/patient/ {
      "type": "100",
      "dni": "295674837L",
      "paort": null,
      "first_name": "Luisa",
      "last_name1": "Perez",
      "last_name2": "Perollo",
      "gender": "F",
      "birth_date": "01-01-1990",
      "address": "CalleEjemplo, 1, 1B",
      "postal_code": "28932",
      "community": "Municipio",
      "province": "Madrid",
      "country": "País",
      "email": "ejemplo@email.com",
      "phone1": "674546345",
      "phone2": null,
      "doctor_id": "P000001",
      "nuhsa": "000001",
      "nhc": "000000",
      "ss": "000000",
      "exitus": "N",
      "exitus_date": "01-01-1990"
  }
  [Response] <html>
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>Error 400 Bad Request</title>
  </head>
  <body><h2>HTTP ERROR 400</h2>
  <p>Problem accessing /integrator/patient/. Reason:
  <pre>    Bad Request</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>
  
  </body>
  </html>
  
  [Headers] {"Date":["Mon, 23 Nov 2015 10:24:56 GMT"],"Content-Type":["text/html; charset=ISO-8859-1"],"Cache-Control":["must-revalidate,no-cache,no-store"],"Content-Length":["307"]}
  [Status] 400
* I see response code is 400
* I see response is json 
 FAIL 

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-------------------------------------------------------------------------------------------------------------------------------------------------


Time: 5.54 seconds, Memory: 12.25Mb

There was 1 failure:

**Comment by Naktibalda** [comment]
I edited your post to make HTML visible.

Is it clear that it isn't a Codeception issue?

**Comment by katmel98** [comment]
Thanks, I don't understand the question. The issue here is that it seems to not been identifying correctly a valid json string like this:

{"app_error_code": 1001,"app_error_messages": ["El objeto paciente enviado no es válido"]}

It's interesting that another json similar from another response:

{"app_error_code":1003,"app_error_messages":["Este objeto paciente no existe."]}

Is correctly identified by the function seeReponseIsJson()

The only difference between them is the blank space after the colon char. Could it be possible the origin of the error?

**Comment by Naktibalda** [comment]
Your problem is that the service returned HTML.

Maybe your proxy server overrides error responses.

**Comment by katmel98** [comment]
OK, let me check, thanks for your help on this issue
