### ISSUE TITLE
Error running PhpUnit tests

### ISSUE THREAD

**Issue by manofearth** [Codeception/Codeception#2573]
We have an error, when running PhpUnit tests through Codeception:
```
[PHPUnit_Framework_Exception]       
implode(): Invalid arguments passed
```
And no more info. 
This error interrupts tests execution.
Strange, but when we tried to debug it, we didn't catch one.

**Comment by Naktibalda** [comment]
Do you get more information if you run codeception with `-vvv` flag?

**Comment by Naktibalda** [comment]
@manofearth Please provide more information.

**Comment by manofearth** [comment]
>Do you get more information if you run codeception with  -vvv  flag?

`-vvv` flag helped to find problem in our custom extension class

@Naktibalda thank you!
