### ISSUE TITLE
$scenario->skip() does not stop execution of Cept

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2576]
```
<?php 
$I = new FunctionalTester($scenario);
$I->wantTo('skip this test');

$scenario->skip();
sleep('10');
```

My expectation is that the skip() will be parsed before execution and the test will not be executed.
Changelog of 2.1.1 says `Skipped and Incomplete tests won't fire test.before and test.after events. `
Do I have to use `return` after `$scenario->skip()`?
```
$scenario->skip();
return;
```

**Comment by DavertMik** [comment]
Actually it should work on parsing:

https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Parser.php#L60

I don't know why it doesn't work in your case.

**Comment by DavertMik** [comment]
Anyway, I'd rather close this issue, as $scenario->skip is about to be removed in 2.2 and is deprecated now

**Comment by Naktibalda** [comment]
Update: $scenario->skip() was not removed and it works in a better way now, because it throws exception, so the code below it is not executed.
