### ISSUE TITLE
$scenario->skip() has no effect in Cest and Tests formats

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2577]
Would it be possible to make skip() and incomplete() work in other formats?
Or at least throw an exception that these methods are not supported if test format is not Cept.

**Comment by DavertMik** [comment]
We'd better move out of using `scenario->skip` and `incpomplete` in favor of annotations. At least we have deprecation messages when you use them in Cest

**Comment by DavertMik** [comment]
Scenario->skip won't work in tests at all (another reason for not using it)

For now, deprecation notice is enough I think (for not to break working tests)
In 2.2 such exception will be thrown
