### ISSUE TITLE
JsonType: add in() validator

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2581]
I tried this:
`periodType => "string:=DAY|string:=WEEK"` it worked when value was 'WEEK', but it failed when the function started returning DAY.

Possible solutions:
a) allow multiple declarations of the same type,
b) implement `in` validator,
c) start from scratch :stuck_out_tongue:.

**Comment by DavertMik** [comment]
a) it is allowed, but can be buggy =) Let me investigate why it doesn't work for you
b) nice idea
c) please do, I don't mind :)

**Comment by DavertMik** [comment]
a) is fixed

b+c is up to you )
