### ISSUE TITLE
Symfony2 seeEmailIsSent() method

### ISSUE THREAD

**Issue by benr77** [Codeception/Codeception#2587]
Thanks for the awesome Codeception! 

I'm trying to use Symfony2 module seeEmailIsSent() but it keeps failing the test. However:

 - in my dev environment, I redirect all mail to a test email address using the `delivery_address` parameter
 - I also have different SMTP servers set up - i.e. multiple swiftmailer mailers defined.

How does the seeEmailIsSent() method actually detect the mail being sent?

Thanks

**Comment by benr77** [comment]
To clarify, I have the following in my environment config.yml

```
framework:
  profiler:
    only_exceptions:    false
    enabled:            true
    collect:            true
```

This should enable the required fx to detect emails being sent surely?

**Comment by DavertMik** [comment]
> How does the seeEmailIsSent() method actually detect the mail being sent?

Only by using profiler and swiftmailer collector
https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/Symfony2.php#L237

**Comment by benr77** [comment]
Thanks for your response. As you say enabling `collect: true` is needed.

It is also required to enable logging in Swiftmailer config - the logging defaults to `%kernel.debug%` but you might need to explicitly set it depending on your environment and set up. 

If you are in a testing environment you might also have `disable_delivery: true` but it seems to pretend to send the email just fine (presumably the inhibited delivery happens after the profiler collects the data).

In your `config.yml` file.
```
framework:
  profiler:
    only_exceptions: false
    enabled: true
    collect: true

swiftmailer:
  logging: true
  disable_delivery: true
```

## Counting emails sent after an HTTP redirect

The problem then is that if you are doing a form submission and using a standard Symfony HTTP redirect, you lose the profiler information as it looks for emails sent in the current request, whereas the emails were sent in the previous request.

To fix this, I've hacked together the following to go in a helper class - in my case `helper/Functional.php`:

```
<?php

namespace Helper;

/**
 * Functional Helper Class
 */
class Functional extends \Codeception\Module
{
	/**
	 * Get the Symfony kernel
	 *
	 * @return Kernel
	 */
	private function getKernel()
	{
		return $this->getModule('Symfony2')->kernel;
	}

	/**
	 * Get the Symfony profiler
	 *
	 * @return Profiler
	 */
	private function getProfiler()
	{
		return $this->getKernel()->getContainer()->get('profiler');
	}

	/**
	 * See email is sent before redirect.
	 *
	 * This function adds to the seeEmailIsSent() method provided by Codeception,
	 * and extracts the number of emails send in the PREVIOUS request.
	 *
	 * @param string $path The path of the request to look for (simple string fragment of URL)
	 *
	 * @return int The number of emails sent
	 */
	private function countEmailsSentOnPreviousRequest($path)
	{
		// Find the last request matching the specified path and using POST.
		$lastRequest = reset($this->getProfiler()->find('', $path, 10, 'POST', '', ''));

		// Now we have the token of the previous request, use it to load the profile data for that request
		$profile = $this->getProfiler()->loadProfile($lastRequest['token']);

		// Finally get the Swiftmailer collector and ask it how many messages were sent
		return $profile->getCollector('swiftmailer')->getMessageCount();
	}

	/**
	 *  Convenience method for utilising the above method. Requires "- Asserts" in functional.suite.yml
	 * 
	 * @param string $path     The path of the request to look for (simple string fragment of URL)
	 * @param int    $expected The number of emails we expect to see sent
	 */
	public function assertEmailsSentOnPreviousRequestCount($path, $expected)
	{
		$this->assertEquals($this->countEmailsSentOnPreviousRequest($path), $expected);
	}

}
```

This seems to work quite well for me. Hopefully it will help someone else looking at the same issue, or indeed you could incorporate it in to Codeception's Symfony2 module if you like.

**Comment by toby-griffiths** [comment]
@benr77 Thanks for this. Was struggling with this myself today.

Perhaps a PR to add this in, when I have a moment.
