### ISSUE TITLE
Problem when trying to implement amLoggedWithSentryAs helper

### ISSUE THREAD

**Issue by sileence** [Codeception/Codeception#2596]
Hello. I am working on a project in Laravel 4 that uses Sentry instead of the Laravel native authentication. I wrote this small Codeception module:

```
<?php

namespace Codeception\Module;

use Codeception\Module;

class Sentry extends Module
{

    /**
     * @return mixed
     * @throws \Cartalyst\Sentry\Sentry
     */
    protected function sentry()
    {
        $app = $this->getModule('Laravel4')->getApplication();
        return $app['sentry'];
    }

    public function amLoggedWithSentryAs($user)
    {
        $this->sentry()->login($user);
    }

    public function seeSentryAuthentication()
    {
        $this->assertTrue(
            $this->sentry()->check(),
            '[Sentry] The user is not authenticated'
        );
    }

    public function dontSeeSentryAuthentication()
    {
        $this->assertFalse(
            $this->sentry()->check(),
            '[Sentry] The user is authenticated'
        );
    }

}
```

The only problem is that the test environment doesn't seem to share the same instances than the test scenario. 

I mean, inside the test, this works:

`$I->amLoggedWithSentryAs($user);`

`$I->seeSentryAuthentication(); //returns true!` 

Inside the Laravel application (controllers, routes, etc.) `Sentry::check()` returns false. 

A similar problem is described here: https://laracasts.com/discuss/channels/testing/ioc-container-mocks-and-codeception-integration-testing

I have avoided this as much as possible when using Codeception, but in this scenario I need to implement this.

Thank you for your help.

**Comment by Naktibalda** [comment]
Please add the configuration of this test suite.

**Comment by janhenkgerritsen** [comment]
What version of Codeception are you using? And can you provide a sample of a test that fails? 

As for now, I have one idea of what could be causing your issue. The Laravel modules reload the Laravel application object on each request, so if you call `$I->amLoggedWithSentryAs($user)` and then execute a request with for example `$I->amOnPage` the Laravel application will be reloaded. In that case calls to `Sentry::check()` in your application will be on a new Sentry instance, one that does not have a user logged in.

This was also a problem with the `$I->amLoggedAs` methods of the Laravel modules. In the Laravel 5 module I have fixed this by checking if a user is logged in before reloading the application. If there is a user logged in, I store this in a temp variable and log the user back in after reloading the application. You can see this code at https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Connector/Laravel5.php#L82. If there was a user logged in, this user is logged back in at line 122.

This is not implemented in the Laravel 4 module, but it is possible your problem is caused by the same issue. If that is the case, can you check if a similar solution works for your problem? If so I have to look for a solution that works without you having to edit the Codeception source code :)

**Comment by sileence** [comment]
@janhenkgerritsen  codeception version is 2.1.4, but we have had this problem since always. I am not the only one, colleagues and other developers as well have faced the same issue.

Is it possible to call a method that creates the Laravel application before I call the amLoggedWithSentryAs or is it possible that it just get called before even calling `omOnPage` to avoid this issue?

at this point I knew it was the problem but I still don't know exactly how to prevent that.

**Comment by sileence** [comment]
@Naktibalda in this case it is kind of irrelevant, this issue has to be with the way codeception Laravel module is built and it's not specific of one configuration, it has happened in very different projects / scenarios.

**Comment by sileence** [comment]
My thoughts about this: the container should be deleted after the test finishes, and it should be instatiate as soon as the test starts, or as soon as you call getApplication() you get a new IoC container and you delete that in the `_after` method (after the test ends) That way you can mock components etc. before you will be able to update the same container.

**Comment by janhenkgerritsen** [comment]
I don't want to change the current implementation where a new Laravel application is instantiated for each request. Before it was implemented as you describe, with the `_before` and `_after` methods, but that implementation had several issues with tests that span multiple requests. So we have to look at another solution for this issue. Currently I have two ideas.

The first idea is to provide hooks before and after initializing the Laravel application. This could be done with events, just like the events described at http://codeception.com/docs/08-Customization#Events. You can hook into these hooks with a custom extension and do whatever you need. In your case you could store the logged in user in the before initalize hook and log the user back in in the after initialize hook.

The other idea is to provide some configuration option in which you specify the IoC container bindings that need to persist between requests. The Laravel module can use this configuration option to handle this for you, in a similar way is it currently already does for the authenticated user in the Laravel 5 module. I don't know how feasible this is though, I have to test it out first to be sure if it is possible.

Personally I like the second idea best. But what do you think is the best/nicest approach?  Do you maybe have some other ideas? @DavertMik what do you think?

**Comment by sileence** [comment]
@janhenkgerritsen both options seem ok for me.

Other options could be a @persist annotation or a persist method for the Codeception modules and optionally the FunctionalTest

`$I->persist('sentry')` or `$this->persist('sentry')`

A method like 'getContainerThatWillBeUsedInTheNextRequest` could work as well (well, maybe with a better name)

**Comment by janhenkgerritsen** [comment]
I have been thinking about this issue some more, and I don't think persisting container bindings between requests through Codeception is a good idea. I also think there is a simpler solution. 

Currently the Laravel application is initialized when the module is first loaded, but then the Laravel application is initialized again before the first request. So all interaction with the Laravel application in tests before the first test method that executes a request is lost. If I just add a check that does not initialize the Laravel application again before the first request this problem should be solved.

I am going to try this out today.

**Comment by sileence** [comment]
@janhenkgerritsen +1 I really like that solution, if you could avoid re instantiating the application that'd be perfect and in my opinion, more intuitive, it's really hard to understand/know that the IoC container is being reset as soon as you call the method `amOnPage`

**Comment by janhenkgerritsen** [comment]
I added the fix to the Laravel modules. You can try it out by using `2.1.x-dev` as the version for Codeception in your `composer.json` file. Let me know if it works.

**Comment by sileence** [comment]
Thank you very much, I'll check this as soon as I can.

**Comment by janhenkgerritsen** [comment]
@sileence Did you have time to check this yet?

**Comment by sileence** [comment]
@janhenkgerritsen sorry Jan, the company assigned me another project and I didn't continue with the project involving Codeception + Sentry but as soon as I am back to it, I will confirm. Thank you very much for taking the time to fix this.

**Comment by jaumeavila** [comment]
It happens the same to me!
Has it been resolved in any stable version for Laravel 4?
