### ISSUE TITLE
Form is incomplete when containing tag <script type="text/template">

### ISSUE THREAD

**Issue by JulienHenchoz** [Codeception/Codeception#2597]
Hi,
I'm using PhpBrowser and Codeception 2.1.1.

I've reduced the HTML code to the minimum :
```html
<form id="myForm" action="/">
	<div>
		<label for="field1">
			Field 1
		</label>
		<input name="field1" type="text" />
	</div>
	<script type="text/template" id="myTemplate">
		<div class="qq-uploader-selector qq-uploader">
			Some code
		</div>
	</script>
	<script type="text/javascript">
		Some javascript
	</script>
	<div>
		<label for="field2">
			Field 2
		</label>
		<input name="field2" type="text" />
	</div>
</form>
```

I can fill "field1" using $this->fillField('field1', 'myValue'); without problems.
But $this->fillField('field2', 'myValue'); throws an error "Unreachable field 'field2'".

I've digged into the code and found that call to getFormFor($field)" in function "fillField" (src/Codeception/Lib/InnerBrowser.php) returns an incomplete form. The HTML code of the returned form stops after "Some javascript", so logically field2 can't be found.

Any ideas ?

**Comment by Naktibalda** [comment]
Hi @JulienHenchoz ,

I apologize for late response.

I have tried to reproduce your issue, but it filled both fields successfully, maybe your HTML code was different?
When I made HTML invalid by removing &lt;/script> tag, I got this error: `Form field by Label or CSS element with 'field2' was not found.`
