### ISSUE TITLE
What is the @internal param?

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2599]
https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Interfaces/Web.php

```
    /*
     * @param null $uri
     *
     * @internal param $url
     * @return mixed
     */
    public function grabFromCurrentUrl($uri = null);

    /*
     * @param $cssOrXpath
     * @param $attribute
     * @internal param $element
     * @return mixed
     */
    public function grabAttributeFrom($cssOrXpath, $attribute);
```

**Comment by DavertMik** [comment]
To be honest, I don't know. I suppose it is added by PHPStorm somehow. I may miss the generated docblocks when they are created by IDE

**Comment by Naktibalda** [comment]
Oops, I submitted too quickly, I added the link and the code the first comment.

**Comment by marcverney** [comment]
I've just submitted #2600 to fix this.

**Comment by DavertMik** [comment]
Thank you!
