### ISSUE TITLE
grabAttributeFrom is defined in InnerBrowser and in REST module

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2604]
http://stackoverflow.com/questions/34051563/are-some-codeception-modules-incompatible/34062008#34062008

InnerBrowser's grabAttributeFrom method becomes inaccessible if XML part of REST module is enabled.

**Comment by Naktibalda** [comment]
Another conflicting method is amHttpAuthenticated

**Comment by Naktibalda** [comment]
And seeResponseCodeIs

**Comment by DavertMik** [comment]
I'd like not to have REST+InnerBrowser to be enabled both.
We are either testing web interaction or REST API. In case of second we can use

```
REST:
  depends: PhpBrowser
```

The only case I see where this modules will work both is where we are using API to manipulate data on a tested page:

```php
$I->sendPOST('/user', ['name' => 'davert']);
$I->amOnPage('/users');
$I->see('davert');
```

So IMHO it is pretty minor case If we will encourage users not to enabled InnerBrowser modules in cases they are not needed.

**Comment by Naktibalda** [comment]
I don't get your last statement. PhpBrowser is an InnerBrowser module.

**Comment by marcverney** [comment]
If both modules are not meant to be used together, it could be a good idea to mention it in the docs (and maybe Codeception should even throw a clean error when both are enabled by the user).

**Comment by marcverney** [comment]
So is there a recommended way to test my website's ajax calls using:
- Symfony routes (as with SF2 module)
- ready-to-use JSON processing/testing methods (as with REST module) ?

**Comment by DavertMik** [comment]
grabAttribute of REST was renamed to grabAttributeFromXml
