### ISSUE TITLE
Lumen module not loading Service providers

### ISSUE THREAD

**Issue by NeokamiCode** [Codeception/Codeception#2607]
Hi, 

I am trying to load a validation service provider that extends the validator facade but none of the extensions are found when the tests are run. The bootstrap/app.php is registering the provider and the logic works just fine out of Codeception.

Any ideas? 
Thanks!

**Comment by janhenkgerritsen** [comment]
Can you provide some code samples of what you are doing? And what versions of Lumen and Codeception are you using?

**Comment by NeokamiCode** [comment]
Lumen is version 5.1.6 and Codeception 2.1.4
So under app/Providers there is this class
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class ValidationServiceProvider extends ServiceProvider {

	public function register() {}

	public function boot() {
		\Validator::extend('alpha_dash_spaces', function($attribute, $value)
		{
			return (bool) preg_match( '/^[a-z0-9 .\-]+$/i', $value );
		});

		\Validator::extend('is_array_of_strings', function($attribute, $values, $parameters)
		{
			$checkStrings = function($carry, $string){
				return $carry && is_string($string) !== false;
			};
			if(!is_array($values)) return false;
			return  array_reduce($values,$checkStrings,true);
		});
	}
}
```

The problem is that the provider seems to not to be registered so the extension methods are not available and a BadMethodCallException is thrown while running the test. 

On the app.php file under app/bootstrap there is this line to register the provider:
```php 
$app->register('App\Providers\ValidationServiceProvider');
```

**Comment by NeokamiCode** [comment]
The following happened: 
It threw the exception when I was running the test like that
```shell 
vendor/bin/codecept run tests/api/ProvidersCest.php:test_it_configures_provider
```
But I don't have the described problem if I run it without specifying a test function. So just
```shell 
vendor/bin/codecept run tests/api/ProvidersCest.php
```

**Comment by janhenkgerritsen** [comment]
I cannot replicate your issue. But how do you use your validator? I tested it with the following code after adding your validator definition to the `AppServiceProvider::register()` method:

```
$data = ['test' => 'abcde%'];
$rules = ['test' => 'alpha_dash_spaces'];
$validator = \Validator::make($data, $rules);
$validator->fails(); // or $validator->passes()
```

Everything worked as expected when doing it like this.
