### ISSUE TITLE
Click does not work on label

### ISSUE THREAD

**Issue by sbrauwers** [Codeception/Codeception#2612]
http://codeception.com/docs/modules/PhpBrowser#click

Only performs a click on a link or a button. But I need to press on a label.

How do I click on the label with codeception? The position of the correct answer is random, so sometimes it can be first or second.

My idea was to use
```
$I->click('0', "#radioSelect");
```
But that does not work

![screenshot_4](https://cloud.githubusercontent.com/assets/14904671/11627466/c5473a72-9cea-11e5-8f1f-0a76d73508cd.png)

It would be nice if the click() also works on other elements than Buttons or links

**Comment by DavertMik** [comment]
In case of PhpBrowser you can't do the real click. You are simulating POST ot GET request which will be sent to server. Click just opens a link behind the `a`, so it can't be used with label. Use WebDriver to have real clicks working. 

You actually can select radio by `checkOption('0')` which will match element by label as well.
As an alternative you can use `submitForm`
