### ISSUE TITLE
Symfony3 compatibility

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#2613]
Looks like to make Codeception compatible with Symfony3 we just need to update dependencies restrictions to include versions >2.4 <4.0 ....

**Comment by dkorsak** [comment]
+1

**Comment by drewclauson** [comment]
:+1:

**Comment by javigomez** [comment]
:smile:  :+1:

**Comment by raistlin** [comment]
I was going to make travis work with syfmony demo of 3.0 ... but symfony demo still uses 2.7 !!

**Comment by DavertMik** [comment]
Not so easy as it seemed. Looks like we will need to make strict restriction to symfony >= 2.8 to achieve 3.0 compatibility. Not sure if everyone agrees with that change

**Comment by drewclauson** [comment]
@DavertMik, why is that? Tests failing?

**Comment by Naktibalda** [comment]
Unrelated pull request failed with "Fatal error: Redeclared method Codeception\Module\Symfony2::getRouter in /home/travis/build/Codeception/Codeception/src/Codeception/Module/Symfony2.php on line 198"

https://travis-ci.org/Codeception/Codeception/jobs/97106685#L953

**Comment by raistlin** [comment]
Bad merge or something?

**Comment by DavertMik** [comment]
Yes, bad automatic merge.
Also Symfony 2.8 had deprecations in CssSelector and changed its syntax in 3.0
So we need to update its usage. And also check for other notable changes in 2.8 and 3.0
