### ISSUE TITLE
Adding --steps parameter removes the code coverage output

### ISSUE THREAD

**Issue by mhightower** [Codeception/Codeception#2620]
I have a build script that calls
`bin/codecept run --coverage --coverage-html --steps`
does not create `tests/_output/coverage`
`bin//codecept run --coverage --coverage-html`
produces `tests/_output/coverage`

The first call I wanted so that the developers will have a nice command line output and HTML report.

**Comment by Naktibalda** [comment]
Is it the same issue as #967 or a different one?

**Comment by mhightower** [comment]
I forgot I opened that one.  Found it, forgot it, found it again. It is the same issue but for the latest 2.1.4 version.

**Comment by legionmaster** [comment]
Still the same in version 2.1.7
@mhightower thanks for pointing to the error, I searched for hours and could not understand why there is no code coverage output.

**Comment by Naktibalda** [comment]
I can't believe how simple the fix is.
