### ISSUE TITLE
Codeception execution ends early since an exit is called within the code

### ISSUE THREAD

**Issue by fc** [Codeception/Codeception#2626]
I am using the ZF1 module although others may be affected.  I'm 100% new to any kind of code testing tools so forgive me if I've overlooked anything.

I run codeception from the command line (not doing blackbox testing or running headless, etc).

codeception will run code and then suddenly stop at a line like this:
```
* I someaction {...}
```

Okay... so I had to poke around in the code until finding that the code runs runs an 'exit' after sending JSON to the browser.

My workaround (hack) is as follows.  Modify the Codeception/Lib/Connector/ZF1.php
```
--- a/vendor/codeception/codeception/src/Codeception/Lib/Connector/ZF1.php
+++ b/vendor/codeception/codeception/src/Codeception/Lib/Connector/ZF1.php
@@ -70,9 +70,11 @@ public function doRequest($request)
             $this->bootstrap->run();
             $_GET = $_POST = [];
         } catch (\Exception $e) {
-            ob_end_clean();
             $_GET = $_POST = [];
-            throw $e;
+            if ($e->getMessage()!='SAFE_EXIT') {
+                ob_end_clean();
+                throw $e;
+            }
         }
         ob_end_clean();
```
then replacing the exit with this:
```
-        exit;
+               if ( Zend_Session::$_unitTestEnabled ) {
+                       throw new Exception('SAFE_EXIT');
+               } else {
+                       exit;
+               }
```

Something feels totally wrong about trying to fix it in this way... so either there is a better way to do it, or perhaps there is an existing method within codeception that does this?
And, certainly, the Json helper in ZF1 not exiting would also be a fix but that would require code changes that I don't want to make at this time.

What do you think?

**Comment by Naktibalda** [comment]
[Using `exit` makes your code untestable](http://phpmd.org/rules/design.html).

Multiple alternatives are given in this StackOverflow thread: http://stackoverflow.com/questions/1347794/how-do-you-use-phpunit-to-test-a-function-if-that-function-is-supposed-to-kill-ph

Particularly interesting is the one which suggests that `exit` can be overloaded.
Link to current repository of PHP extension: https://github.com/krakjoe/uopz#overload-example

Codeception can't overload `exit`.
