### ISSUE TITLE
No error given when having a conflicting helper method name when multiple modules are loaded

### ISSUE THREAD

**Issue by fc** [Codeception/Codeception#2627]
I had both the ZF1 and REST module enabled in my functional.suite.yml.

In my FunctionalTester helper class in \Helper\Functional.php I had a method called `sendPOST`.  When calling `sendPOST` from my *Cest class it would execute the sendPOST in the REST module.  After renaming sendPOST to something else it worked.  

It's true I probably don't need to load both the ZF1/REST module at the same time (still new to this codeception thing), but even so it never triggered an error that there was a duplicate sendPOST method and led to confusion.  Ideally it'll throw an exception about the duplicate methods.

**Comment by Naktibalda** [comment]
Related issue: #2604

**Comment by Naktibalda** [comment]
I think that this issue was overlooked earlier.

Fixing it will cause a backwards compatibility break - `amHttpAuthenticated` and `grabAttributeFrom` methods must be renamed either in `REST` module or in `InnerBrowser`.
Custom helpers could be affected too.

**Comment by fc** [comment]
For maintaining backwards compatibility, perhaps it could at the very least throw a warning messaging but only when it is calling a method that has been marked as a duplicate.

**Comment by Naktibalda** [comment]
@DavertMik What's your opinion about this issue?

**Comment by DavertMik** [comment]
Starting from 2.2 Codeception is strict about conflicts and makes modules with possible conflicts to throw the error. However, REST+Zend are not considered to be conflictful. It is still possible to have duplicate methods in order you want to override them from helpers.

On methods mentioned by @Naktibalda:

* `grabAttributeFrom` from REST is renamed to `grabAttributeFromXmlElement`
* `amHttpAuthenticated` are both in REST and PhpBrowser but they work on the same client so there shouldn't be problems.
