### ISSUE TITLE
CC 2.1.4 with Selenium - Cannot communicate with browser.

### ISSUE THREAD

**Issue by TroyRudolph** [Codeception/Codeception#2628]
Hello, 

We are trying to upgrade from Codeception 2.0.14 to Codeception 2.1.4.  Our testing configuration is Windows 7, PHP 5.6.7, Firefox 42, and Selenium standalone server.  

With Codeception 2.0.14, the tests run successfully.  With Codeception 2.1.4, every test fails as soon as it touches the browser.  In every test, it logs into the app, so it is the $i->amOnPage() call that is failing.  I can see the browser running during the test. The browser does start, but it never reacts to the $i->amOnPage() call.  We have been using Selenium 2.46.0 for our tests.  I have also tried Selenium 2.48.2. I got the same result.

I have attached log produced by one of the failing tests.

To me, this seems like some sort of configuration issue, but I'm not sure where to start with it.  Do any of you have any ideas?

Thank you
Troy Rudolph
Bridge360
[test_log.txt](https://github.com/Codeception/Codeception/files/59580/test_log.txt)

**Comment by Naktibalda** [comment]
@TroyRudolph have you solved this issue?

**Comment by Naktibalda** [comment]
This is a very old issue and it was likely caused by configuration or infrastructure, so it isn't a bug of Codeception.
