### ISSUE TITLE
Can't debug Exceptions (with xdebug)

### ISSUE THREAD

**Issue by mindplay-dk** [Codeception/Codeception#2632]
The global exception-handler seems to prevent xdebug from trapping the exception - this prevents me from debugging an unexpected exception.

Is there any way to disable the global exception handler? I checked the manual, I can't find it.

**Comment by mindplay-dk** [comment]
Okay, I can see why this would be near-impossible to fix - this codebase is littered with global exception handlers, at every layer of the framework, starting with Symfony's console command class, through php-unit, I count a total of *seven* global exception-handlers:

```
\Codeception\Step::run()
\Codeception\TestCase\Shared\Actor::runStep()
\Codeception\TestCase\Cest::testCodecept()
\PHPUnit_Framework_TestCase::runTest()
\PHPUnit_Framework_TestCase::runBare()
\PHPUnit_Framework_TestResult::run()
\Symfony\Component\Console\Application::run()
```

That's more than I've ever seen in a single stack-trace.

So basically there is no hope of ever being able to debug anything here?

It's `codecept_debug()` all the way?

**Comment by mindplay-dk** [comment]
For the record, also tried

```
xdebug.show_exception_trace = 1
xdebug.show_error_trace = 1
```

I was hoping this would make xdebug pause despite the global exception handlers, but no such luck.

I give up. If anyone figures out a work-around, please post.

**Comment by DavertMik** [comment]
> this codebase is littered with global exception handlers, at every layer of the framework, starting with Symfony's console command class, through php-unit, I count a total of seven global exception-handlers:

Yes, now you understand my pain :)

However, I don't understand why your exceptions may not be handled. Can you provide at least a test you are working on. As generally exceptions should be catched and wrapped by PHPUnit and shown in results

**Comment by mindplay-dk** [comment]
Could be any test, that's besides the point.

The test-framework is trapping the exception and showing a stack trace - it works as intended, I guess, but it also blocks xdebug from trapping the exception and pausing execution, so I can inspect the state of variables, objects, etc. and try to find out what caused the exception. A stack trace, in some cases, doesn't help you find the source of the error, which is sometimes a side-effect, an object in an invalid state, and a stack trace doesn't tell you what caused this state to begin with.

If the exception gets handled by a `catch` anywhere, xdebug doesn't pause - it only pauses on unhandled exceptions, and there's no way to bypass the global exception handlers...

Some debuggers have a setting that causes them to pause on any `throw`, even when there's a `catch` up the stack, but I can't find that option in xdebug.

**Comment by jonphipps** [comment]
Have you tried changing the [xdebug remote mode](http://xdebug.org/docs/all_settings#remote_mode)?
From the an older [PhpStorm post](http://blog.jetbrains.com/phpstorm/2013/12/just-in-time-debugging-and-php-exception-breakpoints-with-phpstorm-and-xdebug/) on jit debugging:
> "...PhpStorm will break when an Exception has been thrown. If it is handled, the debugger will break at the first line of the catch block if there is one, or the finally block when using PHP 5.5:"

**Comment by Naktibalda** [comment]
There is nothing we can do about it.
