### ISSUE TITLE
Undefined variable: proxyConfig

### ISSUE THREAD

**Issue by JarJak** [Codeception/Codeception#2636]
PHP Notice:  Undefined variable: proxyConfig in /vendor/codeception/codeception/src/Codeception/Module/WebDriver.php on line 373

**Comment by Naktibalda** [comment]
It was caused by https://github.com/Codeception/Codeception/pull/2614

I've looked at the code https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/WebDriver.php#L356
$proxyConfig is undefined if both http_proxy and ssl_proxy settings are missing.

**Comment by Naktibalda** [comment]
It broke every single WebDriver test in this latest build: https://travis-ci.org/Codeception/Codeception/jobs/97106681

**Comment by DavertMik** [comment]
Fixed for latest build
