### ISSUE TITLE
Provide a way to check if debug mode is active for modules

### ISSUE THREAD

**Issue by FractalizeR** [Codeception/Codeception#2638]
I'm writting some module helper and I have a heavy operation, which makes sense only if CodeCeption is run in debug mode.

`\Codeception\Util\Debug` class has its `$output` property not null only in debug mode, but there is no getter for it. And this check is indirect.

Could you please provide a better way to do that?

**Comment by jefersonralmeida** [comment]
It makes sense since sometimes you inject an external library that can have a debug mode, and just makes sense to enable it when debug is enabled.

**Comment by jefersonralmeida** [comment]
Working on a PR to implement it.

**Comment by jefersonralmeida** [comment]
PR created: https://github.com/Codeception/Codeception/pull/5494

**Comment by Naktibalda** [comment]
`\Codeception\Util\Debug::isEnabled()` method was implemented in 2.5.0 

https://github.com/Codeception/Codeception/commit/1d4bb38d1a5ac852ddb8a35f7aa88c18180176df#diff-259b7eb57d4f5a6c3e125568a2989589R55
