### ISSUE TITLE
Recorder extension: make slideshow configurable

### ISSUE THREAD

**Issue by vml-rmott** [Codeception/Codeception#2655]
I am submitting a patch which provides a flag `animate_slides` that defaults to `true` (the current behavior).  When set to `false`, the left-right sliding animation of the carousel in the output HTML is disabled and screenshot slides are replaced instantly on click or keypress.

While the default behavior is pretty, disabling the animation can make navigating very long test runs easier.

**Comment by vml-rmott** [comment]
https://github.com/Codeception/Codeception/pull/2656

**Comment by DavertMik** [comment]
THanks
