### ISSUE TITLE
Tests in specific path do not load!

### ISSUE THREAD

**Issue by Teszy** [Codeception/Codeception#2662]
I tried Codeception in windows platform. When I started to run a test the following error occurred: 
[Codeception\Exception\TestParseException]
Couldn't parse test 'C:\Program Files\...
Could not open input file: C:\Program

The problematic line was on Parser.php:129 where the exec got a param without escaping.
That might be a security issue as well as in my case stopped running my tests.

How I solved the problem was simply added a like at the top of the exec function call like this:
$file = escapeshellarg($file);
exec("php -l $file 2>&1", $output, $code);
...

**Comment by Naktibalda** [comment]
Thanks for report,
but it is a duplicate of #2647
