### ISSUE TITLE
Feature Request: Profile every test and step with a '--profile' flag

### ISSUE THREAD

**Issue by saada** [Codeception/Codeception#2663]
To show time taken by of every test in the suite.
```bash
codecept run --profile
```
To show time taken by of every test in the suite as well as time taken by every step in each test.
```bash
codecept run --profile --steps
```

It would even better if we could get some sort of summary table sorted by most time consuming tests / steps.

In addition to "time" we could also show a "memory" breakdown.

Sample Benchmark Output

Suite | Test | Step | Time
------- | ------ | ------ | -------
acceptance| test6 | step1 | 2.56
acceptance| test1 | step4 | 1.32
acceptance| test1 | step1 | 0.16
acceptance| test4 | step2 | 0.13
acceptance| test1 | step7 | 0.02
TOTAL TIME        | | | 4.19

**Comment by DavertMik** [comment]
Actually I think you can implement an extension which will do that

**Comment by sergeyklay** [comment]
:+1:

**Comment by saada** [comment]
Would love to work on this if someone could perhaps give me guidelines? Are there perhaps some events that are triggered that I can capture?

**Comment by Naktibalda** [comment]
Codeception 2.2 displays execution time of each test.
