### ISSUE TITLE
Db module: Postgres cleanup() does not delete all types

### ISSUE THREAD

**Issue by airdrummingfool** [Codeception/Codeception#2666]
Hello,
Currently, the Postgres module cleanup() only deletes `enumerated` types. This ignores other kinds of types, including `composite` and `base` ([kinds of types can be seen here](http://www.postgresql.org/docs/current/static/sql-createtype.html)).

I am brand new to Postgres - so I don't want to create a PR before this gets some scrutiny - but I found that if you change the `$types` query (around line 65 of the Postgres driver) to the following, cleanup() is able to delete `composite` and `base` types as well:
`"SELECT 'DROP TYPE IF EXISTS \"' || t.typname || '\" cascade;' FROM pg_catalog.pg_type t LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE (t.typrelid = 0 OR (SELECT c.relkind = 'c' FROM pg_catalog.pg_class c WHERE c.oid = t.typrelid)) AND NOT EXISTS(SELECT 1 FROM pg_catalog.pg_type el WHERE el.oid = t.typelem AND el.typarray = t.oid) AND n.nspname <> 'pg_catalog' AND n.nspname <> 'information_schema' AND pg_catalog.pg_type_is_visible(t.oid);"`

The above query is adapted from the psql that powers the `\dT` command ([source](http://stackoverflow.com/a/17778566/627772)).

cc/ @DavertMik (Db module maintainer)

**Comment by Naktibalda** [comment]
@airdrummingfool You know more about the topic than I or @DavertMik 

You are welcome to make a PR, but it would be good if you implemented a test for cleanup of other kinds of types in https://github.com/Codeception/Codeception/blob/2.1/tests/unit/Codeception/Lib/Driver/PostgresTest.php (if you need to load something from the sql dump, add it to  https://github.com/Codeception/Codeception/blob/2.1/tests/data/dumps/postgres.sql file)
