### ISSUE TITLE
Headers settings consistency

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#2667]
PhpBrowser and REST provide different mechanisms on setting headers. In REST we have `headers` array which is parsed and sent with request, in PhpBrowser we use `setHeader` and `deleteHeader` methods which pass headers settings to Guzzle connectors (and probably don't work correctly).

In case of REST we don't have a way to unset headers.
In case of PhpBrowser they are probably not even set properly.
We have inconsistent namings: `haveHttpHeader` in REST vs `setHeader` in PhpBrowser.

I think we can move everything header-related to InnerBrowser and solve the issue by unifying the mechanism.

**Comment by DavertMik** [comment]
@Naktibalda I'd like to see your suggestions here. I don't work with REST and PhpBrowser regularly, so probably I don't know the best options here.

**Comment by Naktibalda** [comment]
REST module bypasses InnerBrowser and uses Connector directly.

I have tried to make REST::execute consume InnerBrowser::_request to improve and make more consistent debug output, but got stuck. I think that it is a necessary step before making InnerBrowser responsible for setting headers.

**Comment by Naktibalda** [comment]
Having different method names actually is a workaround for conflicting method name issue: https://github.com/Codeception/Codeception/issues/2627 https://github.com/Codeception/Codeception/issues/2604

Making naming consistent makes this issue bigger.

**Comment by DavertMik** [comment]
I think all connectors should have an interface for setting headers. Setting headers from REST should go to those connectors. 

There will be no conflict in names as equal methods of different modules will do equivalently the same: passing headers to connectors. 

Not sure, maybe I can get it implemented in 2.1 branch without BCs...
