### ISSUE TITLE
REST: check response code

### ISSUE THREAD

**Issue by kopaygorodsky** [Codeception/Codeception#2669]
Hi everyone,
I'm trying to test different response codes:

$tokenAdmin = $i->login('admin');
$i->amBearerAuthenticated($tokenAdmin);
$i->sendGET('/api/v1/users');
$i->seeResponseCodeIs(200);

and I get exception:
[ModuleException] Symfony2: Page not loaded. Use `$I->amOnPage` (or hidden API methods `_request` and `_loadPage`) to open it

Does anyone know how to fix it?

**Comment by Naktibalda** [comment]
Let me guess - you have Symfony2 and PhpBrowser modules enabled in this suite and REST depends on PhpBrowser.
The solution is to chose one of Symfony2 and PhpBrowser and disable another.

**Comment by kopaygorodsky** [comment]
If I understood you correctly, my file should be like this, but still not working.

class_name: ApiTester
modules:
    enabled:
        - REST:
            url: http://127.0.0.1:8000
            part: Json
            depends: PhpBrowser
        - Symfony2:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'

**Comment by Naktibalda** [comment]
Change `depends: PhpBrowser` to `depends: Symfony2`

**Comment by kopaygorodsky** [comment]
if I change PhpBrowser to Symfony2 I get 500 error (file_put_contents(/var/cache/test/sessions/e477ddd353acc08566d9f13e7567c812096604ff92c0be31028cf73209fc349d.mocksess): failed to open stream: No such file or directory (500 Internal Server Error)
suite file:
class_name: ApiTester
modules:
    enabled:
        - REST:
            url: http://127.0.0.1:8000
            part: Json
            depends: Symfony2
        - Symfony2:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'

Seems symfony2 configs are not working.
I I tried this one
class_name: ApiTester
modules:
    enabled:
        - REST:
            url: http://127.0.0.1:8000
            part: JSON
            depends: Symfony2
        - Cli
    config:
        Symfony2:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'

but error the same and in this case I can't use symfony2 module functions.

**Comment by Naktibalda** [comment]
Does `/var/cache/test/sessions` directory exist?

**Comment by kopaygorodsky** [comment]
no, cache is generated by symfony2, so I can't change anything. 
Stack trace :
``
 ErrorHandler ->errorHandler ('2', 'file_put_contents(/Users/kopaygorodsky/Development/www/mustr/var/cache/test/sessions/6a1fb141aea240b80a1f31defc6e8b788a86aa5f8f7aceda7309e5a6df949e81.mocksess): failed to open stream: No such file or directory', '/Users/kopaygorodsky/Development/www/mustr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/MockFileSessionStorage.php', '99', array()) 
``
As I understood: instead of BrowserKit from PhpBrowser Codeception uses HttpFoundation

**Comment by Naktibalda** [comment]
Instead of BrowserKit, Symfony2 module uses `\Symfony\Component\HttpKernel\Client`

This is no longer the REST issue, I can't help you to make Symfony2 run.

**Comment by kopaygorodsky** [comment]
Fixed by moving Symfony2 before REST module in suite file. I think we can close issue, doesn't it?
Thank you!
