### ISSUE TITLE
XML Code Coverage and PhpStorm

### ISSUE THREAD

**Issue by oblogic7** [Codeception/Codeception#2671]
I am running a coverage report for my unit test suite using the --xml option.  However, when I select the generated report in PhpStorm, the coverage does not display correctly.  Is there a difference in the codeception XML file vs what php unit creates that PhpStorm doesn't like?  Is there any way to get the coverage data to work properly in PhpStorm?

**Comment by bbrala** [comment]
Can we have any update on this?

**Comment by axelitus** [comment]
You have to use the `--coverage-xml` option to get the coverage in clover format.

**Comment by ilyar** [comment]
I created the report `tests/_output/coverage.xml`  with a command `codecept run --coverage-xml`, after added to the PhpStorm `Ctrl + Alt + 6`, but the coverage is not displayed, maybe another format of XML is needed?

**Comment by ilyar** [comment]
All ok, I did not notice that the paths to the files are not correctly specified because report created inside the container docker. Fixed to relative paths, everything works great.

**Comment by dreanmer** [comment]
@ilyar how did you changed the paths? manually direct on `coverage.xml`?

**Comment by ilyar** [comment]
@dreanmer yes, if report generated in container docker.

**Comment by ilyar** [comment]
also, see:
1. https://stackoverflow.com/questions/39262331/phpstorm-auto-update-code-coverage-data-from-codeception
2. Actual Codeception support ticket: youtrack.jetbrains.com/issue/WI-16350
3. Coverage auto-refresh: youtrack.jetbrains.com/issue/WI-25513
4. https://twitter.com/mindplaydk/status/955855791814266880

**Comment by dreanmer** [comment]
What a deception :/ thx anyway

Em seg, 29 de jan de 2018 18:15, Ilya Rogov <notifications@github.com>
escreveu:

**Comment by ilyar** [comment]
I came to the conclusion that the matter is in the priorities, everyone is controlled by an all-powerful big finger: Fix versions 2018.1 https://youtrack.jetbrains.com/issue/WI-34962#comment=27-2687311

**Comment by dreanmer** [comment]
such a great news!! BTW did you managed to get this work explicitign the configurations like he said in the ticket? cuz it wont worked for me...

**Comment by ilyar** [comment]
it is in build 181.3281 toolbox downloaded  build 181.3007.10. I do not know how to get the right build, I think we should wait a little longer.

**Comment by dreanmer** [comment]
![image](https://user-images.githubusercontent.com/5880810/35637674-0c844138-069c-11e8-8d71-71c280e8bd7e.png)
Updated today, but don't reached 181.3281 ;(

**Comment by dreanmer** [comment]
@iliyav Its arrived 100% working!!! 🎊
EAP Version 181.3494.16. Already available in toolbox!

**Comment by ilyar** [comment]
@dreanmer yes and in snap
