### ISSUE TITLE
Laravel 4 module, what is the minimum Laravel 4 version required?

### ISSUE THREAD

**Issue by sameernyaupane** [Codeception/Codeception#2679]
I am on Laravel 4.0 on an old application which I cannot upgrade currently.

I pulled in the latest codeception  "codeception/codeception": "2.1.5"

But I get the following error on Laravel 4 module on running a functional test:

 [ReflectionException]
  Method Illuminate\Foundation\Application::getStackedClient() does not exist

Is there a minimum Laravel 4 version required to use the L4 module?

Thanks

**Comment by Naktibalda** [comment]
getStackedMethod was added to version 4.1.0 https://github.com/laravel/framework/commit/18e1aecb69897b9533968d4c9f291f3a522ef98f

**Comment by sameernyaupane** [comment]
Thanks a lot for the reply, so there  is no way to run it with 4.0 other than upgrade to 4.1.0?

**Comment by sameernyaupane** [comment]
I upgraded to Laravel 4.1.0 finally and now I get a different error.

It seems to submit the login form fine, and redirects back to homepage too, but there is no login successful message or anything. Dosen't Laravel4 module support sessions? The redirect works but the main page still shows a login/register button instead of welcome message. Checked it from '_output' folder.

```
Scenario Steps:

 7. $I->see("You have successfully logged in.")
 6. $I->seeCurrentUrlEquals("/")
 5. $I->click("#signinForm button[type="submit"]")
 4. $I->fillField("#signinForm input[name="password"]","y5t5!PG00v0$5dqD")
 3. $I->fillField("#signinForm input[name="email"]","sameernyaupane@outlook.com")
 2. $I->see("User Login panel")


FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
```

Any suggestion would be helpful, thanks.

**Comment by janhenkgerritsen** [comment]
I don't have time to look into this right now, but you should probably install an older version of Codeception. You should probably try some something in 2.0.X. If I recall correctly I started maintaining the module from 2.0.10, so after that version most of the changes occurred to the Laravel modules.

**Comment by sameernyaupane** [comment]
Thanks a lot for the reply. I upgraded my app all the way to Laravel 4.2 now. Would that change the required version, maybe 2.1.X?  I'll try 2.0.16, the last 2.0.X tag for now.

**Comment by janhenkgerritsen** [comment]
If your app runs Laravel 4.2 you should be able to use the latest 2.1.x version of Codeception.

**Comment by sameernyaupane** [comment]
I still seem to have the same issue even on Laravel 4.2.17 on Codeception 2.1.5 tag. Thanks for the suggestion though.

**Comment by janhenkgerritsen** [comment]
Can you provide me with you suite configuration, your test code, the code you test and the actual errors you get? Without some more information I cannot help you.

**Comment by sameernyaupane** [comment]
Sure, here are my details.

Functional Suite Config
```
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - Laravel4
        - \Helper\Functional
```

LoginCest.php

```
public function tryToTest(FunctionalTester $I)
    {
        $I->amOnRoute('home');
        $I->see('Login', 'button');
        $I->click('button[data-target="#login-panel"]');
        $I->fillField('form#loginModal input[name="email"]', 'sameernyaupane@outlook.com');
        $I->fillField('form#loginModal input[name="password"]', 'xxxxxxxxx');
        $I->click('.modal-footer input[value="Login"]');
        $I->seeCurrentUrlEquals('/');
        $I->see('Welcome, Sameer');
    }
```

Here is the route that I am testing:

```
$frontend_fn = function() {
    Route::get('/', array('as' => 'home', 'uses' => 'BlogController@getIndex'));
}

/**
 * Assign the frontend routes as a single group.
 */
Route::group(['domain' => 'www.'. Config::get('app.url')] , $frontend_fn);
```

The home route has the login bootstrap modal, which appears onclick, then the form is filled and submitted. The login should redirect back to same home page and show a Welcome message.


Here is the error I am getting:

```
Functional Tests (1) ---------------------------------------------------------------------------------------
Try to test (LoginCest::tryToTest)                                                                     Fail
------------------------------------------------------------------------------------------------------------


Time: 10.62 seconds, Memory: 29.50Mb

There was 1 failure:

---------
1) Failed to try to test in LoginCest::tryToTest (app/tests\functional\LoginCest.php)

 Step  I see "Welcome, Sameer"
 Fail  Failed asserting that
-->

  BLACKEYE Journeys - Nepal's leading travel brand

function addchildages(elm){
  previouschildrennumber=0;
  if($(elm).parent().nextAll().length!='undefined'){

[Content too long to display. See complete response in '_output' directory]
--> contains "welcome, sameer".

Scenario Steps:

 8. $I->see("Welcome, Sameer")
 7. $I->seeCurrentUrlEquals("/")
 6. $I->click(".modal-footer input[value="Login"]")
 5. $I->fillField("form#loginModal input[name="password"]","xxxxxxx")
 4. $I->fillField("form#loginModal input[name="email"]","sameernyaupane@outlook.com")
 3. $I->click("button[data-target="#login-panel"]")
```

It seems to work until the redirect, but the session is not being saved? I.e the system dosen't show the welcome message after login.

On the other note, I got this same test(with amOnRoute swapped with amOnPage) to work fine with acceptance test using Selenium webdriver module.

Let me know if you need any more info. 

Thanks

**Comment by janhenkgerritsen** [comment]
It looks like your code depends on Javascript, but that is not supported in functional tests with the Laravel module. That also explains why the test does work fine with acceptance testing using the Webdriver module and Selenium.

**Comment by sameernyaupane** [comment]
I modified the code to use normal login form, but I still have issue seeing persistence, i.e Welcome message instead of Login button.

The session doesn't seem to stay.

**Comment by janhenkgerritsen** [comment]
What session driver do you have configured in your Laravel application?

**Comment by sameernyaupane** [comment]
I have the default native session driver. The files are stored in the app/storage/sessions directory.

```
	'driver' => 'native',
	'files' => storage_path().'/sessions',
```

**Comment by janhenkgerritsen** [comment]
Sorry for my late response, but I have been very busy with other obligations. But is this still an issue?

**Comment by sameernyaupane** [comment]
Yes, apparently I still have an issue getting L4 module to work with Laravel 4.2. I am guessing it is because I'm using subdomain wildcard routing? Is that causing the issue?

**Comment by janhenkgerritsen** [comment]
You are still talking about the same problem with session persisting?

**Comment by sameernyaupane** [comment]
Yea, I'm a bit confused if the routing is not working due to subdomain, or if the session has issue. I'm guessing session, but then I'm on the default session driver

**Comment by janhenkgerritsen** [comment]
Can you try to change the routing and see if that fixes the problem?

You can also take a look at the [sample Laravel 4 application](https://github.com/Codeception/sample-l4-app) and see what is different in your code. [LoginCept](https://github.com/Codeception/sample-l4-app/blob/codeception-2.1/tests/functional/LoginCept.php) shows a basic login scenario that works.

Without actual code it is very difficult for me to determine what the cause of your issue is.
