### ISSUE TITLE
Problem with Phalcon integration

### ISSUE THREAD

**Issue by Lipathor** [Codeception/Codeception#2685]
I got PHP Fatal error:  Declaration of Codeception\Lib\Connector\PhalconMemorySession::setOptions() must be compatible with Phalcon\Session\AdapterInterface::setOptions($options) in /home/pawel/work/pozamiatane/src/vendor/codeception/codeception/src/Codeception/Lib/Connector/Phalcon.php on line 141
I repaired it locally when I changed PhalconMemorySession::setOptions method from public function setOptions(array $options) to public function setOptions($options)

**Comment by Naktibalda** [comment]
@Lipathor What version of Phalcon are you using?
The signature of setOptions was changed in v2.0.0 https://github.com/phalcon/cphalcon/commit/ad113bae4d760ef4da4963e6bd9604bef0850f03#diff-96f9ab45c0367402eabaf8e01dcc97c4L42

**Comment by Lipathor** [comment]
1.3.4

**Comment by Naktibalda** [comment]
Thanks, setOptions method was added to Phalcon connector in Codeception 2.1.4, the alternative to manually modifying Codeception is staying with 2.1.3 until this issue is fixed.

**Comment by Lipathor** [comment]
thanx, for current project i'll stay with modified, but i'll remember that.

**Comment by sergeyklay** [comment]
https://github.com/Codeception/Codeception/pull/2641
