### ISSUE TITLE
XML with namespaces (clarification of documentation, please?)

### ISSUE THREAD

**Issue by Muzical84** [Codeception/Codeception#2688]
I'm testing a WSDL (per chapter 10 of Codeception's documentation,) and the expected XML return starts thus:
```xml
    <?xml version="1.0" encoding="UTF-8"?>
       <ParentNode xmlns="http://www.w3.org/2009/XMLSchema/XMLSchema.dtd">
```
I'm trying to create an "expected" XML node, via http://codeception.com/docs/reference/XmlBuilder , thus:

```php
    $expectedXML = new \Codeception\Util\XmlBuilder();
    $expectedXML->getDom()->version = '1.0';

    $expectedXML->ParentNode
            ->InstanceOfParentNode
               ->attr("key","value")
//etc.
```

So I'm not sure, but I think the reason that ```$I->seeXmlResponseIncludes($expectedXML->__toString());``` is blowing up is because the namespace is missing?  I don't know, and the error is not helpful, (just tells me a test failed,) but I would like to make the namespace the same just to make sure that the two are as alike as possible so I can know whether or not my test is even valid.  (BTW, exact same failure with same message even without __toString(), so I don't think that's my problem.)

The error is: `[RuntimeException] Call to undefined method ApiTester::seeXmlResponseIncludes` but I literally copied that from http://codeception.com/docs/modules/REST so I wouldn't make a typo.

Am I doing something wrong or misunderstanding something?  I'm not used to wrangling XML in PHP, so please forgive any rookie errors contained herein.

**Comment by Naktibalda** [comment]
It seems that you mixed up 2 questions here:
1) something about SOAP namespaces,
2) undefined method.

I can try to help you with the second question.

Where did your copy the seeXmlResponseIncludes method to?
It should go to ApiHelper or \Helper\Api (in 2.1) class.

Have you enabled the helper containing that method in api.suite.yml?

**Comment by Muzical84** [comment]
The api.suit.yml is literally copy-pasted from Codeception's documentation, except with Phpbrowser obviously pointing to where I need it to go and I specified that I only needed the XML part.

I'm using REST, not SOAP, with the Slim framework (not by choice on the framework,) for the API.

Also, the file I'm writing is procedural because the example on Codecepion's website is procedural.

Did I misunderstand or fail to answer any questions?  ^_^;;;

**Comment by Naktibalda** [comment]
Please attach the api.suite.yml and attach or paste the code of test which fails.

**Comment by Muzical84** [comment]
api.suite.yml

```yml
class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - REST:
            url: TheDevServer.redacted.com
            depends: PhpBrowser
            part: Xml
```

And a somewhat-censored (taking out my jabbering comments,) version of the file:

```php
<?php
require_once 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

$I = new ApiTester($scenario);
$I->wantTo('Get the API result');
$I->sendGET('/complete/all');
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();

$expectedXML = new \Codeception\Util\XmlBuilder();

$expectedXML->Terms
    ->Term
        ->attr('kId', '454')
        ->attr('shortName', 'something')
        ->attr('longName', 'something longer')
        ->attr('letterCode', 'somethingElse')
        ->attr('automatedShortName', 'shortName')
        ->attr('automatedLongName', 'Longer Name')
        ->attr('automatedLongDescription', 'A description of moderate size')
        ->attr('status', 'ACTIVE')
        ->attr('statusReason', '')
        ->attr('statusText', '')
        ->attr('changeType', '')
        ->attr('changeReasonPublic', '')
            ->ComponentTerms
                ->RTerm
                    ->attr('id', '260')
                    ->attr('attributeName', '2letterThing')
                    ->attr('abbreviation', 'xx')
                    ->attr('id', '10312')
                    ->attr('attributeId', '7')
                ->parent()
                ->RTerm
                    //etc...
                ->parent()
                ->RTerm
                   //etc...
        ->parents('Terms');

$I->seeXmlResponseIncludes($expectedXML->__toString()); //This breaks whether I call toString or not

```

**Comment by Naktibalda** [comment]
Oh, it is a silly bug:

https://github.com/Codeception/Codeception/blob/033830f75f4c87e6c69d96ae236998758d2429fb/src/Codeception/Module/REST.php#L1056

seeXmlResponseIncludes has no `@part xml` annotation.

Use a whole REST module and submit a patch.

**Comment by Muzical84** [comment]
That still doesn't fix the lack of being able to handle namespaced XML :(  Because the XML returned, after the <?xml version="1.1" encoding="UTF-8"?> line, is <Term  xmlns="http://www.w3.org/2009/XMLSchema/XMLSchema.dtd"> etc. as above.

**Comment by Muzical84** [comment]
Pull request 2695 addresses the annotation issues ^_^

**Comment by Naktibalda** [comment]
XmlBuilder does not support namespaces.

I have tried to add namespace support to XmlBuilder (it was easy),
but DomDocument registers namespace at the lowest level tag which uses it,
so XML does not match when multiple namespaces are used in the document.

Failed asserting that `<ns1:users xmlns:ns1="http://www.example.com/XFoo"><ns1:user>1<ns2:email xmlns:ns2="http://www.example.com/XBar" valid="true">davert@mail.ua</ns2:email><ns2:cart xmlns:ns2="http://www.example.com/XBar" empty="false"><ns2:items><ns2:item>useful item</ns2:item></ns2:items></ns2:cart><ns2:active xmlns:ns2="http://www.example.com/XBar">1</ns2:active></ns1:user></ns1:users>` contains `<ns1:users xmlns:ns1="http://www.example.com/XFoo" xmlns:ns2="http://www.example.com/XBar"><ns1:user>1<ns2:email valid="true">davert@mail.ua</ns2:email><ns2:cart empty="false"><ns2:items><ns2:item>useful item</ns2:item></ns2:items></ns2:cart><ns2:active>1</ns2:active></ns1:user></ns1:users>`.

My advice is to hardcode expected XML in the test.
