### ISSUE TITLE
Webdriver does not go to the specified url (Laravel 5.1)

### ISSUE THREAD

**Issue by brazenvoid** [Codeception/Codeception#2692]
Since a composer update after 2 weeks on our servers, our Acceptance cest tests are failing indiscriminately. All of them throw;
[ModuleException] WebDriver: Current url is blank, no page was opened

This happens when we call amOnUrl and then check whether it went to that url with canSeeCurrentUrlEquals. We tried a simple test with only two steps with same results, like so;

```php
public function test(AcceptanceTester $I) 
{
    $I->amOnUrl('http://swaggable.com');
    $I->canSeeCurrentUrlEquals('/');
}
```
We ran it on an intact machine where it passed. 
```
composer.json

"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.1.*",
    "barryvdh/laravel-ide-helper": "^2.0",
    "sboo/multiauth": "4.0.*",
    "dingo/api": "0.10.*",
    "doctrine/dbal": "2.3.*",
    "rtconner/laravel-kint": "~2.0",
    "factual/factual-php-driver": "dev-master",
    "weblee/mandrill": "dev-master",
    "barryvdh/laravel-debugbar": "^2.0",
    "laravel/envoy": "~1.0",
    "jeremeamia/superclosure": "~2.0",
    "illuminate/html": "~5.0",
    "predis/predis": "^1.0",
    "guzzlehttp/guzzle": "~5.3|~6.0",
    "laravelcollective/html": "5.1.*",
    "exeu/apai-io": "dev-master",
    "codeception/codeception": "*"
},
"require-dev": {
    "mockery/mockery": "0.9.*",
    "phpunit/phpunit": "~4.0",
    "phpspec/phpspec": "~2.1",
    "fzaninotto/faker": "~1.0"
},
```

**Comment by janhenkgerritsen** [comment]
What does your suite configuration file look like?

In case you are using the Laravel5 module, you should not use it for acceptance tests. It is not compatible with the WebDriver module.

**Comment by brazenvoid** [comment]
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed

**Comment by brazenvoid** [comment]
Installed selenium just to check and it works so maybe its phantomJS / ghost-driver which has conflict.

**Comment by DavertMik** [comment]
Probably so. I feel its more like PhantomJS issue and not Codeception's, so I'm closing it.
