### ISSUE TITLE
@depends doesn't work when extended from other Cest class

### ISSUE THREAD

**Issue by RobQuistNL** [Codeception/Codeception#2693]
In order to fix my code duplication I've tried to create 1 main Cest that contains a login method. I've extended my other tests from it like so;

MainCest.php
```php
class MainCest {
    /** @var  string */
    public $cookie;

    public function login(AcceptanceTester $I)
    {
        // logging in
        $I->wantTo('Login as admin');
        $I->amOnPage('/login');
        $I->fillField('email', 'info@example.org');
        $I->fillField('password', 'correct horse battery staple');
        $I->click('Log in');
        $this->cookie = $I->grabCookie('PHPSESSID');
    }
}
```

OtherCest.php
```php
class OtherCest extends MainCest
{
    public $url = '/properties/types';

    /**
     * @depends login
     */
    public function canDeleteExistingType(AcceptanceTester $I) {
        $I->setCookie('PHPSESSID', $this->cookie);
        $I->amOnPage($this->url);
        $I->see('Manage product types');
        //...
    }
}
```

Now the issue is that the $this->login() is available (when I call ``$this->login()`` in the first test, the test works) but it looks like the @depends isn't doing anything (I'm guessing the reflectionclass isn't finding the method "login" in the OtherCest class...)

Am I doing something terribly wrong? Or is this in fact a bug? What I'm trying to accomplish is that I don't have to;

- Log in for every test
- Log in for every cest

So far i've fixed the first but still haven't fixed the latter.. Any ideas are welcome as well if they pop in to mind :)

**Comment by RobQuistNL** [comment]
I've been fiddling around and managed to make the MainCest work like so;

```php
class MainCest {
    /** @var  string */
    public $cookie;

    public function _before(AcceptanceTester $I) {
        $this->login($I);
    }

    private function login(AcceptanceTester $I)
    {
        // logging in
        if ($this->cookie != null) {
            $I->setCookie('PHPSESSID', $this->cookie);
        } else {
            $I->amOnPage('/login');
            $I->fillField('email', 'info@seavalue.eu');
            $I->fillField('password', '100%Koffie');
            $I->click('Log in');
            $this->cookie = $I->grabCookie('PHPSESSID');
        }
    }
}
```

This way all other tests always happen in a logged in state. I could also remove the setCookie in the other cests, and remove the @depends. Allthough, this still doesn't solve the 2nd issue, and this isn't the prettiest :( Suggestions?

**Comment by DavertMik** [comment]
Depends is going to be dramatically improved in 2.2
https://github.com/Codeception/Codeception/pull/2711#issuecomment-173057161
You will get stable and flexible way to define dependencies. And yes, good news, we won't rely in PHPUnit in it.

**Comment by Naktibalda** [comment]
great  news.

**Comment by rafaelbdb** [comment]
@RobQuistNL you have no idea how your code helped me... Now my tests are 3 to 4 times faster, and files are smaller. Thanks!
@DavertMik some kind of "keep session between tests" (at least as an option) is a MUST HAVE for Codeception!

**Comment by DavertMik** [comment]
> some kind of "keep session between tests" (at least as an option) is a MUST HAVE for Codeception!

already there!
http://codeception.com/docs/03-AcceptanceTests#Session-Snapshots

**Comment by RobQuistNL** [comment]
> already there!
> http://codeception.com/docs/03-AcceptanceTests#Session-Snapshots

Problem is that this does not work with the PHPBrowser - and i really prefer the PHPBrowser for simple checks as its much faster than using any "real" webdriver like Selenium or PhantomJS.

I've currently setup Selenium for the pages that require JS functionality and am using a PHPBrowser testsuite for the more simple checks (such as simple forms and stuff).

Also for the general testing of the application i've just disable authentication. As i'm using bcrypt it takes quite a while to log in so this method speeds it up a lot. So, on my automated test environment, the visitor is automatically logged in. Might help you out a bit too @rafaelbdb
