### ISSUE TITLE
Should @depends annotation work **across** Cest classes?

### ISSUE THREAD

**Issue by ashnazg** [Codeception/Codeception#2696]
Should Codeception's `@depend` annotation allow a testcase in one class to depend on the pass status of a testcase in **different** Cest class?

```
class One {
    public function testOne() {}
}
class Two {
    /**
     * @depends One::testOne
     */
    public function testTwo() {}
}
```

When I run something like this, there are no errors (e.g. no indication that the depends resolution fails to work), but the testTwo() case will always be skipped, regardless of if testOne() passes or fails.

If these testcases were in the _same_ class, it works fine when using these syntaxes:
```
@depends testOne
@depends One::testOne
```
It does not work in the same class using these syntaxes:
```
@depends testOne()
@depends \One::testOne
@depends \One::testOne()
```

Thus, it is the `@depends One::testOne` syntax that I would expect to work across classes.  Since it does _not_ work (v2.1.4), and the docs do not explicitly say you can depend across classes, then perhaps such a capability is intentionally not available.  Hence, my question here.

**Comment by DavertMik** [comment]
Depends is going to be dramatically improved in 2.2. The issue here is that PHPUnit does not maintain order of dependent tests. Codeception starting from 2.2 will do that: https://github.com/Codeception/Codeception/pull/2711#issuecomment-173057161
