### ISSUE TITLE
Common functions in Cest files

### ISSUE THREAD

**Issue by JonoB** [Codeception/Codeception#2698]
We have a few methods that we run in `_before` function in Cest acceptance tests. These methods in `_before` method return values that we need in the tests.

So far what we have is the following:

```
class AcceptanceTester extends \Codeception\Actor
{
    use _generated\AcceptanceTesterActions;

    public function setupModels()
    {
       return $this->setupCompany();
    }
```

And then our Cest file looks like this:
```
class CategoryCest
{
    protected $companyId;

    public function _before(AcceptanceTester $I)
    {
        $this->companyId = $I->setupModels();
    }

    public function canDoSomething(AcceptanceTester $I)
    {
        $companyId = $this->companyId;
        ...
    }
```

However, using `$I->setupModels()` seems a bit strange. Is there a better way to get this common functionality working where we can just inject required setup into `_before` method or even into individual test without using `AcceptanceTester $I`?

**Comment by tbartolucci** [comment]
Couldn't you write a base class for the Cest files that have those methods?  It would become $this->setUpModels();

**Comment by JonoB** [comment]
@tbartolucci Cest classes can't extend a base class. Actually, they can, but because of the way the cest files are loaded, the base class will not be found.

**Comment by Naktibalda** [comment]
put `require_once __DIR__ . '/BaseCept.php';` to the top of the file

**Comment by JonoB** [comment]
Sure, I know I can do that :)

Just wondering if there is any other accepted/recommended way of including common functionality in cest classes.

**Comment by DavertMik** [comment]
There are lots of options to do so. Except mentioned, you can create a StepObject or any other class (which can be autoloaded) and use its name in a test or in `_before`.

```php
<?php
    public function _before(\DataMaker $data)
    {
        $this->companyId = $data->setupModels();
    }
```

if you need companyId in every cest you have nothing other than copy it over files, use traits or inheritance.
