### ISSUE TITLE
RunFailed extension in 2.1 does _not_ seem to be enabled by default

### ISSUE THREAD

**Issue by ashnazg** [Codeception/Codeception#2699]
The docs for 2.1 indicate that the RunFailed extension is enabled by default (http://codeception.com/addons#.Vo1sjPkrKHs).  As such, I removed it from being explicitly listed in my codeception.yml file.  WIthout it, I found that the tests/_output/failed file is _not_ being generated, so it would seem that it is actually _not_ enabled by default.

If it is "enabled by default", is the explicit enable line in codeception.yml still required to be there?

I tested in 2.1.4 and 2.1.0 (can't use 2.1.5 due to #2684 and #2651).

**Comment by DavertMik** [comment]
>  As such, I removed it from being explicitly listed in my codeception.yml file.
> so it would seem that it is actually not enabled by default.

:dizzy_face: no, it is. A bootstrap generator creates `codeception.yml` file with that extension enabled, that's what enabled by default means. But yes, you can disable it.

**Comment by ashnazg** [comment]
Ah, so then the explicit line in codeception.yml is indeed required.  Thanks for confirming, @DavertMik
