### ISSUE TITLE
Code coverage not compatible Jenkins Content Security Policy update

### ISSUE THREAD

**Issue by Nemmo** [Codeception/Codeception#2701]
In case of the Jenkins update few days ago described [here](https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy#ConfiguringContentSecurityPolicy-HTMLPublisherPlugin) now I have troubles with all reports generated by the Codeception framework.  I have just updated all plugins and Jenkins to the lates versions, but it is still not working. Could you help me with that issue?
[Screenshot](http://i.imgur.com/2qFtHdq.png)

**Comment by Naktibalda** [comment]
Code coverage report is generated by https://github.com/sebastianbergmann/php-code-coverage
Please report an issue there.

To fix this issue:
> Add or modify following parameter in /etc/sysconfig/jenkins file..
> 
> JENKINS_JAVA_OPTIONS=" -Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"\" "
> 
https://github.com/jenkinsci/cucumber-reports-plugin/issues/7#issuecomment-182815496
