### ISSUE TITLE
Nesting level too deep - recursive dependency?  in codeception/src/Codeception/PHPUnit/Listener.php:55

### ISSUE THREAD

**Issue by JarJak** [Codeception/Codeception#2702]
Nesting level too deep - recursive dependency? 
in codeception/src/Codeception/PHPUnit/Listener.php:55

Related to https://github.com/Codeception/Codeception/commit/b6ec4fd6ff4171a42be8457c9e74bd344d8bbff8

this change should be done also in line 55

**Comment by DavertMik** [comment]
Yes, thanks for the fix. I think marking test skipped or incomplete is too complicated now so causing a recursion. Looks like a room for improvement to me )

**Comment by JarJak** [comment]
Problem still exists in master branch

**Comment by Naktibalda** [comment]
2.1 is merged to master regularly.
