### ISSUE TITLE
codeceptJS / webdriverIO exits script with grab commands

### ISSUE THREAD

**Issue by tduncklee** [Codeception/Codeception#2707]
I'm new to codeceptJS but best I can tell it simply does not work with yield.

```
'use strict';
Feature('Testing Begins');
Before((I) => {
  I.resizeWindow(1500, 1000);
  I.amOnPage('http://absolutenet.com');
});

Scenario('ANI testing', function*(I){
  I.waitForText('bring your site to life');
  I.amOnPage('http://www.absolutenet.com/');
  let title = yield I.grabTitle();
  console.info(title);
  I.see('bogus text that is not there');
});
```

I have tried several of the grab commands as well as executeScript. I know the commands are working because for some reason one or two lines do execute after the yield so I can output the variable I am assigning. However, I can never use it because the browser closes and the script terminates. Even worse, I can put in a test that is obviously invalid (I.see('some bogus non existent text');) and the Scenario exits with a Success!

The above is live so you can execute it to see the problem. This happens with Firefox and Chrome on Linux and Mac.

Is anyone able to use a grabber and have the code continue to execute?

Also, the documentation has an error at http://codecept.io/helpers/WebDriverIO/#grabattribute The example has "grabAttributeFrom" and it should be "grabAttribute"

**Comment by arsa666** [comment]
same thing happened to me!

**Comment by Naktibalda** [comment]
I'm closing this issue, because @tduncklee already reported it to the right place: https://github.com/Codeception/CodeceptJS/issues/47
