### ISSUE TITLE
PHP 7.0 / PHPunit 5.1 support

### ISSUE THREAD

**Issue by oparoz** [Codeception/Codeception#2712]
I couldn't find an issue tracking progress on making Codeception compatible with PHP7.0.
What's missing to make it run with PHPunit 5.1?

> - codeception/codeception 2.1.5 requires phpunit/phpunit ~4.8.0 -> no matching package found.

Related issue: #2730

**Comment by DavertMik** [comment]
Codeception if PHP7 supported. Did you see our badge? ;) [![PHP 7 ready](http://php7ready.timesplinter.ch/Codeception/Codeception/badge.svg)](https://travis-ci.org/codeception/codeception}) 

We don't plan to support PHPUnit >= 5.0 as we are going to keep PHP5.4 compatibility and actually we don't see any rational reason for that. Is there any specific feature of PHPUnit 5.0 or 5.1 you are missing?

**Comment by oparoz** [comment]
I did see the badge and it didn't make sense to me because of the PHPUnit 4 requirements ;)

The problem I'm having is that the web services tests fail on PHP 7 (on Travis)

```
 [GuzzleHttp\Exception\ConnectException]  
  cURL error 7: couldn't connect to host   
```

I assumed it was because PHPUnit wasn't updated to the version which supports PHP 7 because the exact same tests run fine on 5.4-5.6

**Comment by oparoz** [comment]
And I just want to add that the web server is up and running, because before that I run acceptance tests and they pass.

**Comment by Naktibalda** [comment]
PhpBrowser tests pass on PHP 7 https://travis-ci.org/Codeception/Codeception/jobs/101954490

**Comment by DavertMik** [comment]
So we narrowed issue to PhpBrowser can't connect to webserver. 
I don't have a clue how can we find the cause of it

**Comment by oparoz** [comment]
I can see one difference in the composer.lock. You're on guzzle ~6 and I'm on ~5

**Comment by Naktibalda** [comment]
That shouldn't make a difference, it is still a curl issue.

**Comment by oparoz** [comment]
I think I've identified the problem and that it's unrelated. It's a problem I have on my instance as well when testing.

Guzzle is already installed in `core` and the version installed locally by composer is ignored.

``` 
GuzzleHttp\RequestFsm->__invoke() at /home/travis/build/owncloud/core/3rdparty/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Client->send() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Lib/Connector/Guzzle.php:193
```

And the full trace

```
Make sure my test users have  (CheckTestUsersCest::testTestUsersCreation)
Scenario:
  [Page] /
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/7.0.0"],"Set-Cookie":["ocps0v5isx8e=nl1kifrpds4152ecd45bgddfg3; path=/; HttpOnly","oc_sessionPassphrase=IM%2BCyi%2FEef1LkmkCT8FD7Ks2n%2Bxcs8zU7sVocZ8Arf%2FZodhL10le7q9hunn8v5iuJ615Mb1DXqx088RfAW0iEkW5wayA%2F5Mah%2Bt6Mmc2ZEu1JEnOa%2BJsCA%2BFzWu5DT8C; path=/; HttpOnly"],"Expires":["Thu, 19 Nov 1981 08:52:00 GMT"],"Cache-Control":["no-store, no-cache, must-revalidate"],"Pragma":["no-cache"],"Content-Security-Policy":["default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *"],"X-XSS-Protection":["1; mode=block"],"X-Content-Type-Options":["nosniff"],"X-Frame-Options":["Sameorigin"],"X-Robots-Tag":["none"],"Content-type":["text/html; charset=UTF-8"]}
  [Cookie Jar] ["ocps0v5isx8e=nl1kifrpds4152ecd45bgddfg3; domain=localhost; path=/; httponly","oc_sessionPassphrase=IM%2BCyi%2FEef1LkmkCT8FD7Ks2n%2Bxcs8zU7sVocZ8Arf%2FZodhL10le7q9hunn8v5iuJ615Mb1DXqx088RfAW0iEkW5wayA%2F5Mah%2Bt6Mmc2ZEu1JEnOa%2BJsCA%2BFzWu5DT8C; domain=localhost; path=/; httponly","CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testTestUsersCreation%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; path=/; httponly"]
* I am http authenticated "admin","admin"
  [Cookie Jar] ["ocps0v5isx8e=nl1kifrpds4152ecd45bgddfg3; domain=localhost; path=/; httponly","oc_sessionPassphrase=IM%2BCyi%2FEef1LkmkCT8FD7Ks2n%2Bxcs8zU7sVocZ8Arf%2FZodhL10le7q9hunn8v5iuJ615Mb1DXqx088RfAW0iEkW5wayA%2F5Mah%2Bt6Mmc2ZEu1JEnOa%2BJsCA%2BFzWu5DT8C; domain=localhost; path=/; httponly","CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testTestUsersCreation%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; path=/; httponly"]
* I send get "/ocs/v1.php/cloud/users/tester"
  [Request headers] []
  [Request] GET http://localhost:8000/ocs/v1.php/cloud/users/tester
  [Cookie Jar] ["ocps0v5isx8e=nl1kifrpds4152ecd45bgddfg3; domain=localhost; path=/; httponly","oc_sessionPassphrase=IM%2BCyi%2FEef1LkmkCT8FD7Ks2n%2Bxcs8zU7sVocZ8Arf%2FZodhL10le7q9hunn8v5iuJ615Mb1DXqx088RfAW0iEkW5wayA%2F5Mah%2Bt6Mmc2ZEu1JEnOa%2BJsCA%2BFzWu5DT8C; domain=localhost; path=/; httponly","CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testTestUsersCreation%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; path=/; httponly"]
 ERROR 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception trace:
 () at /home/travis/build/owncloud/core/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php:49
 GuzzleHttp\Exception\RequestException::wrapException() at /home/travis/build/owncloud/core/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php:103
 GuzzleHttp\RequestFsm->__invoke() at /home/travis/build/owncloud/core/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php:132
 GuzzleHttp\RequestFsm->GuzzleHttp\{closure}() at /home/travis/build/owncloud/core/3rdparty/react/promise/src/FulfilledPromise.php:25
 React\Promise\FulfilledPromise->then() at /home/travis/build/owncloud/core/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
 GuzzleHttp\Ring\Future\CompletedFutureValue->then() at /home/travis/build/owncloud/core/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
 GuzzleHttp\Message\FutureResponse::proxy() at /home/travis/build/owncloud/core/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php:134
 GuzzleHttp\RequestFsm->__invoke() at /home/travis/build/owncloud/core/3rdparty/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Client->send() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Lib/Connector/Guzzle.php:193
 Codeception\Lib\Connector\Guzzle->doRequest() at /home/travis/build/owncloud/core/apps/gallery/vendor/symfony/browser-kit/Client.php:317
 Symfony\Component\BrowserKit\Client->request() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:158
 Codeception\Lib\InnerBrowser->clientRequest() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:201
 Codeception\Lib\InnerBrowser->_loadPage() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:245
 Codeception\Lib\InnerBrowser->amOnPage() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Coverage/Subscriber/LocalServer.php:151
 Codeception\Coverage\Subscriber\LocalServer->startCoverageCollection() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Coverage/Subscriber/LocalServer.php:89
 Codeception\Coverage\Subscriber\LocalServer->beforeTest() at n/a:n/a
 call_user_func() at /home/travis/build/owncloud/core/3rdparty/symfony/event-dispatcher/EventDispatcher.php:158
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /home/travis/build/owncloud/core/3rdparty/symfony/event-dispatcher/EventDispatcher.php:46
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:121
 Codeception\PHPUnit\Listener->fire() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:92
 Codeception\PHPUnit\Listener->startTest() at /home/travis/build/owncloud/core/apps/gallery/vendor/phpunit/phpunit/src/Framework/TestResult.php:327
 PHPUnit_Framework_TestResult->startTest() at /home/travis/build/owncloud/core/apps/gallery/vendor/phpunit/phpunit/src/Framework/TestResult.php:552
 PHPUnit_Framework_TestResult->run() at /home/travis/build/owncloud/core/apps/gallery/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
 PHPUnit_Framework_TestCase->run() at /home/travis/build/owncloud/core/apps/gallery/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
 PHPUnit_Framework_TestSuite->run() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:89
 Codeception\PHPUnit\Runner->doEnhancedRun() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/SuiteManager.php:153
 Codeception\SuiteManager->run() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Codecept.php:203
 Codeception\Codecept->runSuite() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Codecept.php:172
 Codeception\Codecept->run() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Command/Run.php:262
 Codeception\Command\Run->runSuites() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/src/Codeception/Command/Run.php:189
 Codeception\Command\Run->execute() at /home/travis/build/owncloud/core/apps/gallery/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /home/travis/build/owncloud/core/apps/gallery/vendor/symfony/console/Application.php:840
 Symfony\Component\Console\Application->doRunCommand() at /home/travis/build/owncloud/core/apps/gallery/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /home/travis/build/owncloud/core/apps/gallery/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at /home/travis/build/owncloud/core/apps/gallery/vendor/codeception/codeception/codecept:28
```

**Comment by DavertMik** [comment]
Why don't you use Guzzle6 then? Pleas try to update

**Comment by oparoz** [comment]
I tried already with ` "guzzlehttp/guzzle": "~5.0|~6.0",` but 5.3 still get installed on 7.0. My understanding is that this way of defining versions would let PHP 5.5+ pick version 6.0

**Comment by DavertMik** [comment]
what if you try to specify: `"guzzlehttp/guzzle": "~6.0"`?

**Comment by oparoz** [comment]
Same problem with 6, it's still using the libs in `core`. I probably need to fix this first and need to look for a solution.

**Comment by DavertMik** [comment]
We are not testing PHP7 + Guzzle5, so maybe problem is that...

**Comment by Naktibalda** [comment]
It passed

https://travis-ci.org/Codeception/Codeception/jobs/102064328#L1864

 - Updating guzzlehttp/guzzle (6.1.1 => 5.3.0)

```
There were 2 skipped tests:

---------

1) PhpBrowserTest::testArrayFieldSubmitForm

Not for Guzzle <6

---------

2) PhpBrowserTest::testCookiesForDomain

Not for Guzzle <6

OK, but incomplete, skipped, or risky tests!

Tests: 168, Assertions: 395, Skipped: 2.
```

All PhpBrowserRest tests passed.

**Comment by oparoz** [comment]
The test I'm using is very simple 

```
		$I->wantTo('make sure my test users have been created');
		$I->amHttpAuthenticated('admin', 'admin');
		$I->sendGET($this->baseUrl . '/users/' . $this->userId);
		$I->seeResponseCodeIs(200);
		$I->seeResponseIsXml();
```

And the result 

```
* I send get "/ocs/v1.php/cloud/users/tester"
  [Request headers] []
  [Request] GET http://localhost:8000/ocs/v1.php/cloud/users/tester
  [Cookie Jar] ["oc7szjowh6a3=1fl061cbukgqj623vqcn9eb031; domain=localhost; path=/; httponly","oc_sessionPassphrase=O2I5pCkRz%2BTZ7HoM6EXeiBh7DnvpGM7zs6IehguFEhutTackbuSImXRu1Dwl2VX8u5WeVgQWpfYZJGzZrKvvF10ksDydwTvjvOezx0eH8g5UQ1EI6KZS3spBbfbPC69A; domain=localhost; path=/; httponly","CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testTestUsersCreation%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; path=/; httponly"]
 ERROR 
```

**Comment by Naktibalda** [comment]
how do you start the http daemon?

**Comment by oparoz** [comment]
```
class_name: ApiTester
modules:
    enabled:
        - Asserts
        - \Helper\Api
        - \Helper\DataSetup
        - REST:
            url: http://localhost:8000
            depends: PhpBrowser
```

but it's an open source project, so you can get all the details here:
https://github.com/owncloud/gallery/tree/master/tests

**Comment by oparoz** [comment]
I have additional info. It only fails if I enable coverage

I have a branch where I test PHP7
https://github.com/owncloud/gallery/pull/473

In the latest push, I asked to test both without and with coverage and only the one with coverage failed.

https://travis-ci.org/owncloud/gallery/jobs/102081832

**Comment by Naktibalda** [comment]
Probably your http daemon crashes.
Print the logs or add some action to check if it is still alive.

**Comment by oparoz** [comment]
OK, the log ends with this:

```
[Wed Jan 13 14:36:32 2016] Failed to listen on localhost:8000 (reason: Address already in use)
[Wed Jan 13 14:36:40 2016] ::1:48142 [200]: /c3/report/clear
```

**Comment by oparoz** [comment]
That's the command used to run the tests:

`php vendor/bin/codecept run api,integration,unit -vvv --coverage --coverage-xml --coverage-html`

**Comment by Naktibalda** [comment]
It could be caused by https://github.com/sebastianbergmann/php-code-coverage/issues/416

**Comment by oparoz** [comment]
I'm not sure since the problem seems to be that the server has not been shutdown in the previous test run. I've had that in the command line sometimes, there is a ghost webserver which tests connect to and which will then lead to erroneous results.

**Comment by bassrock** [comment]
Isn't it possible to change the PHPUnit dependency to >=4.8.0  so that we can use newer versions of PHPUnit with Codception?

**Comment by Naktibalda** [comment]
Blacklist functionality is removed from PHP_Code_Coverage 3.* so it must be removed from http://codeception.com/docs/11-Codecoverage

@DavertMik can it be done in 2.2 or 3.0?

**Comment by githubjeka** [comment]
>  Is there any specific feature of PHPUnit 5.0 or 5.1 you are missing?

https://github.com/sebastianbergmann/phpunit/issues/1859#issuecomment-141621409

**Comment by derokorian** [comment]
> Is there any specific feature of PHPUnit 5.0 or 5.1 you are missing?

Also this: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/283

**Comment by githubjeka** [comment]
> There was 1 error:                                                                                             
                                                                                                               
> ---------                                                                                                      
> 1) tests\codeception\common\AssortmentTest::testTryCreateModel                                                 
TypeError: Argument 1 passed to PHPUnit_Framework_TestCase::onNotSuccessfulTest() must be an instance of Exception, instance of Error given, called in C:\codecept\vendor\phpunit\phpunit\src\Framework\TestCase.php on line 851                                                                                                             

I'm so tired of this error and the search for its cause causes pain.

**Comment by parsingphase** [comment]
I'm getting some incredibly hard-to-trace crashes, segfaults, and just exiting with errorcode 1 after an apparently successful run when testing code that uses a SOAP client (said code works fine under browser and web driver testing)… will see if I can reduce this to anything usefully reproducible, but it seems to tie into the thread of guzzle/curl/http issues above.

It does seem a little optimistic to claim PHP7 support when you're tied to PHPUnit < 5. @sebastianbergmann, can you tell us how reliably PHPUnit 4.8 runs/passes testing on PHP7?

**Comment by Naktibalda** [comment]
We had no "guzzle/curl/http issues above!", xdebug code coverage does not work on PHP 7:
https://github.com/Codeception/Codeception/issues/2730#issuecomment-173726148

**Comment by DavertMik** [comment]
I think this getting more and more important. Sure, I'd like to have PHP 5.4 builds, but If we have vice versa situation, maybe we need to reconsider and ship 2.2 with PHPUnit 5.x support?

PHPUnit evolves faster and faster and by sticking to 4.8 we are keeping its old bugs.

---

As a compromise solution we can keep modules development in 2.1 branch and merge them into 2.2. 
Anyway, let's dicusss that.

**Comment by Naktibalda** [comment]
Bugs can be fixed, 4.8 is LTS release

**Comment by sebastianbergmann** [comment]
I do not support PHPUnit 4.8 on PHP 7, as is clearly stated on the website.

**Comment by DavertMik** [comment]
> Bugs can be fixed, 4.8 is LTS release

> I do not support PHPUnit 4.8 on PHP 7

I'm not sure what the magical letters "LTS" mean in this case, but what I'm sure that having strong dependency on PHPUnit 4.8 makes Codeception an obsolete shit.

**Comment by raistlin** [comment]
Just keep Codeception 2.x with PHP5.4 and start Codeception 3.x with PHP7 and PHPUnit 5+

**Comment by Naktibalda** [comment]
Codeception 2.2 will support PhpUnit 5.

https://github.com/Codeception/Codeception/pull/2792

**Comment by oparoz** [comment]
Thank you.
