### ISSUE TITLE
REST + Laravel4: session gets lost when DOM quering in assertions is employed

### ISSUE THREAD

**Issue by HongKilDong** [Codeception/Codeception#2716]
This test runs OK. While last 4 assertions definitely inconsistent and shouldn't pass.
```php
$I = new FunctionalTester($scenario);

$I->amOnPage('/user/logout');
$I->see('SignUp');

$I->fillField('email', 'testuser');
$I->fillField('password', 'testuser');
$I->click('SignIn'); // this will post to '/user/login'

$I->see('Logout');
$I->see('Logout', 'a'); // for later reference
$I->dontSee('SignUp');
$I->dontSee('SignUp', 'a'); // for later reference

$I->amOnPage('/user/logout');
$I->see('SignUp');

$I->sendPOST( // same URL, same credentials
    '/user/login',
    array(
        'email' => 'testuser',
        'password' => 'testuser',
    )
);
$I->see('Logout');
$I->dontSee('SignUp');
// things get weird when we employ DOM quering
$I->dontSee('Logout', 'a'); // compare with lines we've marked earlier
$I->see('SignUp', 'a'); // compare with lines we've marked earlier

// P.S. All elements are visible
```
So what happens here, when I get response with Laravel4 module's methods only everything works fine but when I use REST module's method sendPOST things get weird - If I provide second param (DOM selector) to see assertion I get content as if I haven't logged so it seems DOM crawler fails to employ Laravel's session. So we actually have simultaneously 2 responses under examination here, one for assertions without DOM selectors (which is session-aware) and other for assertions with DOM selectors(without session). By the way _output/XXXX.fail.html always provide session-aware results even if assertion employing DOM quering fails on session-unaware response. Later confuses above all when you try to find out why your assertion fails and see that according to XXXX.fail.html content it definitely should have passed.

Here is my functional.suite.yml:
```
class_name: FunctionalTester
modules:
    enabled:
        - Laravel4:
            cleanup: false
        - \Helper\Functional
        - Db
        - REST:
            depends: Laravel4
        - Asserts
```
codeception 2.1.5
laravel 4.1.31

**Comment by Naktibalda** [comment]
sendPOST is REST method, it is not aware of your cookies and does not send any.

Use click() or submitForm() to logout.

**Comment by HongKilDong** [comment]
OK I got it.
Then is there other way to inspect response of an ajax requst ? I've tried Laravel4 method sendAjaxPostRequest but assertions following it operate on response of step preceding sendAjaxPostRequest.

**Comment by HongKilDong** [comment]
Naktibalda
By the way, in my functional tests if I log with sendPOST I can fulfill following post requests with sendPOST to restricted area of my app, which will be impossible without session awareness

PS I enable file driver in session config for testing environment

**Comment by HongKilDong** [comment]
I played a little to employ Laravel4's method sendAjaxPostRequest instead of sendPOST for testing my ajax requests but it seems same trouble with 2 simultaneous response realms happens here, for example this runs OK
```php
$I = new FunctionalTester($scenario);
$I->amOnPage('/user/logout');
$I->see('SignUp');

$I->fillField('email', 'super');
$I->fillField('password', 'super');
$I->click('Submit');

$I->see('Logout');

$I->amOnPage('/playlists/manage');
$I->see('Playlists', 'h3');

$I->sendAjaxPostRequest(
    '/ajax/get-available-tracks',
    array(
       ...
    )
);

$I->see('Duration'); // this can be true only for '/ajax/get-available-tracks' but not for `/playlists/manage`
$I->see('Playlists', 'h3'); // this can be true only for `/playlists/manage` but not for '/ajax/get-available-tracks'
```
Considering this runs OK we can conclude that `see` method here when called without DOM selector examine response of `sendAjaxPostRequest` method, but when called with second param examine response of `amOnPage` method

**Comment by janhenkgerritsen** [comment]
Is this still an issue with Codeception 2.6?

If it still is, could you create a test project in which you reproduce the problem with as little code as possible and share that with me? That way I can take a look at some actual code.

**Comment by janhenkgerritsen** [comment]
I am closing this issue, if it is still a problem it can be reopened.
