### ISSUE TITLE
Codeception group files bug on windows

### ISSUE THREAD

**Issue by klokovas** [Codeception/Codeception#2720]
I try to group my cept tests and execute them on Windows but i met a problem with "/" chars.They are duplicated in path.

I suggest to fix this problem with this code:
```
 public function loadTests()
    {
        $finder = Finder::create()->files()->sortByName()->in($this->path)->followLinks();

        foreach (self::$formats as $format) {
            $formatFinder = clone($finder);
            $testFiles = $formatFinder->name("*$format.php");
            foreach ($testFiles as $test) {
                $pathname = str_replace(DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR, DIRECTORY_SEPARATOR, $test->getPathname());
                call_user_func([$this, "add$format"], $pathname);
            }
        }
    }
```

Replace `"/"` with `DIRECTORY_SEPARATOR`.

**Comment by Naktibalda** [comment]
I merged one bug fix yesterday - https://github.com/Codeception/Codeception/pull/2718
have you found a different issue?

**Comment by klokovas** [comment]
Thanks!

Ok, sorry. I have not seen pull request before i opened issue.
Bug has fixed.
Can you tell me about next release date with this fix?

**Comment by klokovas** [comment]
I was writing about TestLoader::loadTests, but your fix in GroupManager works too.
