### ISSUE TITLE
Add warning when tester classes need to be rebuilt

### ISSUE THREAD

**Issue by schmunk42** [Codeception/Codeception#2724]
We upgraded from 2.0 to 2.1 and needed to rebuild the tester classes.

I think this is mentioned in the docs, but the errors you get are rather non-obvious, maybe there could be a warning if you need to rebuild tester classes. Or kind of a minimum version setting.

**Comment by eXorus** [comment]
We are now at 4.1 and soon 5.0.
I'm closing this issue, feel free to reopen if it is not resolved on the next version.
