### ISSUE TITLE
  [Facebook\WebDriver\Exception\UnknownServerException] Could not find ephemeral port to use

### ISSUE THREAD

**Issue by freinn** [Codeception/Codeception#2726]
class_name: AcceptanceTester
    modules:
        enabled:
            - \Helper\Acceptance
            - WebDriver:
                url: 'https://www.forocoches.com' # proyecto-real.localhost/
                browser: chrome
                # http_proxy: direct # solves the proxy error on this version
                window_size: 1366x768
                wait: 10
                # http_proxy_port: '4444'

    env:
        chrome:
            modules:
                config:
                    WebDriver:
                        browser: 'chrome'

My /tests/_bootstrap.php is empty, but days ago my test were working. I've updated the chrome version to 47.0.2526.106 (64-bit), but I don't find enough information about that error. Also I'm using the last chromedriver and calling selenium this way:

    java -jar selenium-server-standalone-2.49.0.jar -Dwebdriver.chrome.driver=browser_drivers/chromedriver

**Comment by Naktibalda** [comment]
It is an issue of Selenium, please report it in https://github.com/SeleniumHQ/selenium/issues
