### ISSUE TITLE
WebDriver should close remote connections in error cases

### ISSUE THREAD

**Issue by oehlschl** [Codeception/Codeception#2728]
It looks like the WebDriver only closes remote connections on completed tests (thankfully both success and failure), but not in the case of an uncaught exception or fatal error. Unfortunately, many \Facebook\WebDriver\Exceptions go uncaught by default, making this a not uncommon problem.

As a result, remote Selenium Grid browser instances don't always get killed, and nodes fill up with zombie processes. And though there are settings to help mitigate this problem on the grid, it would be easier just to call WebDriver->quit() even in the case of error.

**Comment by Naktibalda** [comment]
#3534 will catch more WebDriver exceptions

**Comment by oehlschl** [comment]
Circling back to close since #3534 has been merged.
