### ISSUE TITLE
Segmentation fault when running with pthread. 

### ISSUE THREAD

**Issue by 24hours** [Codeception/Codeception#2729]
```php
<?php

class My extends Thread{
    function run(){
        for($i=1;$i<2;$i++){
            echo Thread::getCurrentThreadId();
            sleep(1);
        }
    }
}

class PtheadTest extends PHPUnit_Framework_TestCase
{
    public function testMe()
    { 
        $a = new My();
        $a->start();
        $a->join(); 
    }
}
```

Console output
> ..... 
> Unit Tests (1) ----------------------------------------------------
> PtheadTest ::testMe
> Segmentation fault

Has anyone encounter segmentation fault when running codeception with pthread ? Same code run fine with phpunit 4.8.21.

PHP Version : 5.6 
Pthread Version: 2.1.0
OS : Debian Jessie 
Codecept version: 2.1.5

**Comment by Naktibalda** [comment]
I reproduced the issue with Pthreads 3.1.5 on PHP 7.0.2

**Comment by Naktibalda** [comment]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f17a8edfd30 in pthreads_preparation_copy_trait_alias (alias=0x7f17a8af9858, thread=0x7f17a8befc00) at /tmp/pear/temp/pthreads/src/prepare.c:723
```
`pthreads_preparation_copy_trait_alias` - I know where we used trait aliases and I removed them already because they didn't work with HHVM. https://github.com/Codeception/Codeception/commit/24951e72ec96bef38bad340bd678717d7e2c3027

Your test passes with the latest code from 2.1 branch.

```
Codeception PHP Testing Framework v2.1.5
Powered by PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

Unit Tests (1) ------------------------------
PtheadTest::testMe                     Ok0656
---------------------------------------------


Time: 1.23 seconds, Memory: 8.00Mb
```

Use 2.1 branch or wait for the next release.

**Comment by Naktibalda** [comment]
I raised an issue with pthreads: https://github.com/krakjoe/pthreads/issues/551

**Comment by 24hours** [comment]
2.1 branch solve the crash
