### ISSUE TITLE
PHP 7 + coverage tests using C3 on Travis = Segmentation fault

### ISSUE THREAD

**Issue by oparoz** [Codeception/Codeception#2730]
Extracted from #2712 

I launch 2 commands in a row on Travis

```
$ php vendor/bin/codecept run acceptance --env firefox
$ php vendor/bin/codecept run api,integration,unit -vvv --coverage --coverage-xml --coverage-html 
```

The second one will fail with this error message

>[GuzzleHttp\Exception\ConnectException]  
  cURL error 7: couldn't connect to host  

 in tests/_output/phpbuiltinserver.errors.txt, I get:

> [Wed Jan 13 14:36:32 2016] Failed to listen on localhost:8000 (reason: Address already in use)
[Wed Jan 13 14:36:40 2016] ::1:48142 [200]: /c3/report/clear

or 

>[Wed Jan 20 11:28:02 2016] ::1:50413 [200]: /index.php/apps/gallery/files/list?location=&mediatypes=image%2Fpng%3Bimage%2Fjpeg%3Bimage%2Fgif%3Bapplication%2Fpostscript&features=&etag
[Wed Jan 20 11:28:10 2016] ::1:50425 [200]: /c3/report/clear

This does not happen on older version of PHP

**Comment by Naktibalda** [comment]
`[Wed Jan 13 14:36:32 2016] Failed to listen on localhost:8000 (reason: Address already in use)`

This is not a failure of Codeception, please look for a real cause.

**Comment by oparoz** [comment]
Well, Codeception launches and closes the web server to be able to run tests, so if it doesn't close it properly on PHP7, it is a problem with Codeception imo.

**Comment by Naktibalda** [comment]
It doesn't do that.

**Comment by oparoz** [comment]
It does through an extension: https://github.com/tiger-seo/PhpBuiltinServer

**Comment by Naktibalda** [comment]
put `sleep 5` between runs. (if it don't help, try longer intervals).

**Comment by oparoz** [comment]
Thanks, I've tried 15 seconds and it still didn't work. Maybe it's a C3 or xdebug issue.
Looking at the logs, there isn't the "Address already in use" error any more. I can see the browser being launched and that's it.

>::1 2016-01-20T12:03:01+00:00 "GET /c3/report/clear HTTP/1.0" - -
::1 2016-01-20T12:03:01+00:00 "GET / HTTP/1.1" - Symfony2 BrowserKit
::1 2016-01-20T12:03:01+00:00 "GET /ocs/v1.php/cloud/users/tester HTTP/1.1" http://localhost:8000/ Symfony2 BrowserKit

**Comment by Naktibalda** [comment]
Then don't use extension, start `php -S` yourself.

This is how Codeception does it:
`php -S 127.0.0.1:8000 -t tests/data/app >/dev/null 2>&1`

**Comment by oparoz** [comment]
Same error

**Comment by oparoz** [comment]
But more info

> /home/travis/build.sh: line 45: 12400 Segmentation fault      (core dumped) php -S localhost:8000 -t ../.. > /dev/null 2>&1

**Comment by Naktibalda** [comment]
Could you reproduce it in another machine and get the core dump file?

Then run `gdb php core.file`

**Comment by oparoz** [comment]
It's frustrating as I can't reproduce locally, although I'm not loading Firefox for the acceptance tests.

```
sudo -utest MAGICK_TMPDIR=build /usr/local/php70/bin/php70 -dzend_extension=xdebug.so vendor/bin/codecept run acceptance &&
sudo -utest MAGICK_TMPDIR=build /usr/local/php70/bin/php70 -dzend_extension=xdebug.so vendor/bin/codecept run api --coverage --coverage-xml --coverage-html
```

**Comment by sergeyklay** [comment]
I'm not 100% sure but you can try for travis something like this:

**.travis.yml**
```yaml
before_install:
    - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern # change dump path

after_failure:
    - bash tests/after_failure.sh
```

**after_failure.sh**
```sh
#!/usr/bin/env bash

shopt -s nullglob
export LC_ALL=C
for i in /tmp/core_*.*; do
	if [ -f "$i" -a "$(file "$i" | grep -o 'core file')" ]; then
		gdb -q $(file "$i" | grep -oE "'[^ ']+" | sed "s/^'//g") "$i" <<EOF
set pagination 0
backtrace full
info registers
x/16i \$pc
thread apply all backtrace
quit
EOF
	fi
done
```

**Comment by oparoz** [comment]
Many thanks for the script! I'll try ASAP. I did try a `gdb -q -n -ex bt -batch`, but haven't got the results yet as Travis is broken again.

**Comment by Naktibalda** [comment]
it doesn't work in container based infrastructure,
you have to remove `sudo: false` from .travis.yml

**Comment by oparoz** [comment]
@sergeyklay Unfortunately, it's not possible to change the core pattern on Travis. We'll have to wait for them to change that since piping to `apport` doesn't make sense in a CI env.

**Comment by oparoz** [comment]
Also, the Travis team seems to suggest that segfaults are expected when running PHP 7 tests on PHPunit 4.8.

**Comment by Naktibalda** [comment]
Bullshit, Codeception tests pass on PHP 7,
Guzzle's tests pass too: https://travis-ci.org/guzzle/guzzle/jobs/103813457

**Comment by oparoz** [comment]
Sure, but that's Codeception and Guzzle tests. Apps running on Travis will have different code and dependencies.

**Comment by Naktibalda** [comment]
So you can't say that `segfaults are expected when running PHP 7 tests on PHPunit 4.8`.
Something else is segfaulting, good example: https://github.com/Codeception/Codeception/issues/2729 it was a fault of pthreads extension.

**Comment by oparoz** [comment]
I think so too, but I can't see what :( 

Is there a way to use the Webdriver with phpdbg? When I tried (by simply replacing php on the command line), it couldn't connect.

**Comment by Naktibalda** [comment]
And it wasn't PHPunit or Codeception that caused the segfault,
it was your app launched via `php -S`

**Comment by oparoz** [comment]
Same problem with `phpdbg`, so it's not the debugger which is making php crash.

**Comment by oparoz** [comment]
And now it's working... I think the only thing I've changed is remove the `if (extension_loaded('xdebug')`

**Comment by oparoz** [comment]
Ah, my bad, the reason it works is because C3 wasn't included any more...

So as soon as you need coverage using C3, PHP will crash.

**Comment by Naktibalda** [comment]
I just realized that we don't run coverage suite on PHP 7.0 - that's one way to make it pass.

I upgraded PHP to 7.0.2 in my computer and got core dump on the first coverage test.
Segmentation fault happens in xdebug.

I found an existing bug report: http://bugs.xdebug.org/view.php?id=1246

**Comment by oparoz** [comment]
Ah, thanks. I wonder why I can't reproduce locally... Maybe because I'm on FreeBSD.

@sergeyklay - I did give it another go (there was a typo earlier), but it didn't work. The core file is not in the right format...

```
$ bash build/after_failure.sh
"/tmp/core_php.8916": not in executable format: File format not recognized
(gdb) (gdb) No stack.
(gdb) The program has no registers now.
(gdb) No registers.
(gdb) (gdb) 

```

**Comment by oparoz** [comment]
I've modified the script for gdb use the proper php binary and got a full trace:

https://travis-ci.org/owncloud/gallery/builds/103986265#L1541

**Comment by sergeyklay** [comment]
Yea. The executable is 64-bit (x86-64) and the debugger is a 32 bit (i686-pc-linux) build. You may need to install a 64-bit (x86-64) version of the debugger.

**Comment by oparoz** [comment]
>Yea. The executable is 64-bit (x86-64) and the debugger is a 32 bit (i686-pc-linux) build. You may need to install a 64-bit (x86-64) version of the debugger.

I think it's more because the `php` in the path is a shell script and not the real binary, so you have to track it down to the real binary. I used `/home/travis/.phpenv/versions/`php-config --version`/bin/php`

**Comment by sergeyklay** [comment]
:+1:

**Comment by Lansoweb** [comment]
Hi! I've been debugging a Segmentation Fault during remote code coverage today and finally got it working. I just disabled the opcache extension (not just enable_cli, but enable too). Maybe can help someone facing the same problem.

Probably related to this bug in xdebug:
https://bugs.xdebug.org/view.php?id=1263

**Comment by oparoz** [comment]
Yes, sorry, I forgot to report back. Was confirmed in https://bugs.xdebug.org/view.php?id=1246
