### ISSUE TITLE
I got error function nesting level after update composer

### ISSUE THREAD

**Issue by tuanvu-se** [Codeception/Codeception#2731]
Hi, I got this error after update composer

> /var/www/html/myproject/tests$php ../vendor/bin/codecept run unit 
> Codeception PHP Testing Framework v2.1.5
> Powered by PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

> Unit Tests (43) -----------------------------------------------------------------------------------------------------------------------------------------------
Trying to test file found (tests\codeception\unit\components\utils\FileUtilTest::testFileFound)... PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /var/www/html/myproject/vendor/codeception/aspect-mock/src/AspectMock/Core/Mocker.php on line 15
PHP Stack trace:
PHP   1. {main}() /var/www/html/myproject/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/html/myproject/vendor/codeception/codeception/codecept:28
PHP   3. Symfony\Component\Console\Application->doRun() /var/www/html/myproject/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Component\Console\Application->doRunCommand() /var/www/html/myproject/vendor/symfony/console/Application.php:186
PHP   5. Symfony\Component\Console\Command\Command->run() /var/www/html/myproject/vendor/symfony/console/Application.php:787
PHP   6. Codeception\Command\Run->execute() /var/www/html/myproject/vendor/symfony/console/Command/Command.php:256
PHP   7. Codeception\Command\Run->runSuites() /var/www/html/myproject/vendor/codeception/codeception/src/Codeception/Command/Run.php:189
PHP   8. Codeception\Codecept->run() /var/www/html/myproject/vendor/codeception/codeception/src/Codeception/Command/Run.php:262
PHP   9. Codeception\Codecept->runSuite() /var/www/html/myproject/vendor/codeception/codeception/src/Codeception/Codecept.php:172
PHP  10. Codeception\SuiteManager->run() /var/www/html/myproject/vendor/codeception/codeception/src/Codeception/Codecept.php:203
PHP  11. Codeception\PHPUnit\Runner->doEnhancedRun() /var/www/html/myproject/vendor/codeception/codeception/src/Codeception/SuiteManager.php:153
PHP  12. PHPUnit_Framework_TestSuite->run() /var/www/html/myproject/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:89
PHP  13. PHPUnit_Framework_TestCase->run() /var/www/html/myproject/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
PHP  14. PHPUnit_Framework_TestResult->run() /var/www/html/myproject/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
PHP  15. PHPUnit_Framework_TestCase->runBare() /var/www/html/myproject/vendor/phpunit/phpunit/src/Framework/TestResult.php:612
PHP  16. PHPUnit_Framework_TestCase->runTest() /var/www/html/myproject/vendor/phpunit/phpunit/src/Framework/TestCase.php:768
PHP  17. ReflectionMethod->invokeArgs() /var/www/html/myproject/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  18. tests\codeception\unit\components\untils\FileUtilTest->testFileFound() /var/www/html/myproject/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  19. tests\codeception\unit\components\untils\FileUtilTest->specify() /var/www/html/myproject/tests/codeception/unit/components/utils/FileUtilTest.php:39
PHP  20. tests\codeception\unit\components\untils\FileUtilTest->specifyCloneProperties() /var/www/html/myproject/vendor/codeception/specify/src/Codeception/Specify.php:48
PHP  21. DeepCopy\DeepCopy->copy() /var/www/html/myproject/vendor/codeception/specify/src/Codeception/Specify.php:197
PHP  22. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:57
PHP  23. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  24. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  25. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  26. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  27. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  28. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  29. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  30. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  31. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  32. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  33. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  34. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  35. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  36. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  37. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  38. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  39. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  40. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  41. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  42. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  43. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  44. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  45. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  46. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  47. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  48. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  49. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  50. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  51. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  52. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  53. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  54. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  55. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  56. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  57. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  58. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  59. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  60. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  61. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  62. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  63. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  64. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  65. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  66. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  67. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  68. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  69. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  70. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  71. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  72. DeepCopy\DeepCopy->copyObject() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:97
PHP  73. DeepCopy\DeepCopy->copyObjectProperty() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:145
PHP  74. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:182
PHP  75. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  76. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  77. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  78. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  79. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  80. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  81. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  82. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  83. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  84. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  85. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  86. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  87. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  88. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  89. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  90. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  91. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  92. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  93. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  94. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  95. DeepCopy\DeepCopy->copyArray() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:90
PHP  96. array_map() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  97. DeepCopy\DeepCopy->DeepCopy\{closure}() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:111
PHP  98. DeepCopy\DeepCopy->recursiveCopy() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:108
PHP  99. __amock_before() /var/www/html/myproject/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:78
> <pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Maximum function nesting level of &#039;100&#039; reached, aborting!&#039;

This is my bootstrap config file 

```php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

defined('YII_TEST_ENTRY_URL') or define('YII_TEST_ENTRY_URL', parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_PATH));
defined('YII_TEST_ENTRY_FILE') or define('YII_TEST_ENTRY_FILE', dirname(dirname(__DIR__)) . '/web/index-test.php');
defined('VENDOR_DIR') or define('VENDOR_DIR', dirname(dirname(__DIR__)) . '/vendor');

require_once(__DIR__ . '/../../vendor/autoload.php');

// Load AspectMock for unit test
$kernel = \AspectMock\Kernel::getInstance();
$kernel->init([
    'debug'        => true,
    'excludePaths' => [
        VENDOR_DIR . '/phpunit',
    ],
]);
$kernel->loadFile(VENDOR_DIR . '/yiisoft/yii2/Yii.php');
$kernel->loadFile(VENDOR_DIR . '/yiisoft/yii2/base/UnknownClassException.php');
$kernel->loadFile(VENDOR_DIR . '/yiisoft/yii2/base/ErrorException.php');

$_SERVER['SCRIPT_FILENAME'] = YII_TEST_ENTRY_FILE;
$_SERVER['SCRIPT_NAME'] = YII_TEST_ENTRY_URL;
$_SERVER['SERVER_NAME'] = parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_HOST);
$_SERVER['SERVER_PORT'] =  parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_PORT) ?: '80';

Yii::setAlias('@tests', dirname(__DIR__));

\Codeception\Util\Autoload::registerSuffix('Page', __DIR__.DIRECTORY_SEPARATOR.'_pages');
```
I don't know why it happen. Could you please help me to fix it?

**Comment by lisachenko** [comment]
This message is raised from XDebug, so you need to increase this max level in php.ini or programmatically:

```php
// Prevent an error about nesting level
ini_set('xdebug.max_nesting_level', 500);
```

**Comment by tuanvu-se** [comment]
Thank you. I also have fixed like that. But I think it just should be a temporary solution. Because you have to walk over the limit. 

I just got this error when I use codeception (including specify, verify) in newer version (2.0.16) with phpunit version 4.7.7.  When I use codeception in version 2.0.12 with phpunit 4.5.0, everything is work fine.

**Comment by Naktibalda** [comment]
Codeception 2.0 is no longer supported,
Please upgrade to the latest version.

**Comment by KonstantinKolodnitsky** [comment]
Set xdebug.max_nesting_level to higher value is not a solution.
I've set it to 1500 and still have this error

**Comment by Naktibalda** [comment]
Have you got the same issue with deepCopy or something else? Please provide a stacktrace.

**Comment by Naktibalda** [comment]
Original issue was reported in a wrong location, that error was caused by `Codeception/Specify`.
I don't use `Codeception\Specify`, but documentation says that
> Isolation is achieved by cloning object properties for each specify block. By default objects are cloned using deep cloning method. This behavior can be customized in order to speed up test execution by preventing some objects from cloning or switching to shallow cloning using clone operator. Some properties can be ignored from cloning using either global or local config settings.

Please read more about [configuration settings](https://github.com/Codeception/Specify#isolation) and don't deep clone the object which has circular references or whatever is causing that issue.

**Comment by KonstantinKolodnitsky** [comment]
Hi. I don't use deepCopy.

Here is me stack trace

    PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /var/www/html/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 78
    PHP Stack trace:
    PHP   1. {main}() /var/www/html/vendor/codeception/codeception/codecept:0
    PHP   2. Codeception\Application->run() /var/www/html/vendor/codeception/codeception/codecept:33
    PHP   3. Symfony\Component\Console\Application->run() /var/www/html/vendor/codeception/codeception/src/Codeception/Application.php:103
    PHP   4. Symfony\Component\Console\Application->doRun() /var/www/html/vendor/symfony/console/Application.php:117
    PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/html/vendor/symfony/console/Application.php:186
    PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/html/vendor/symfony/console/Application.php:794
    PHP   7. Codeception\Command\Run->execute() /var/www/html/vendor/symfony/console/Command/Command.php:256
    PHP   8. Codeception\Codecept->run() /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php:281
    PHP   9. Codeception\Codecept->runSuite() /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php:178
    PHP  10. Codeception\SuiteManager->run() /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php:209
    PHP  11. Codeception\PHPUnit\Runner->doEnhancedRun() /var/www/html/vendor/codeception/codeception/src/Codeception/SuiteManager.php:162
    PHP  12. PHPUnit_Framework_TestSuite->run() /var/www/html/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:98
    PHP  13. PHPUnit_Framework_TestCase->run() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php:753
    PHP  14. PHPUnit_Framework_TestResult->run() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
    PHP  15. PHPUnit_Framework_TestCase->runBare() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:701
    PHP  16. PHPUnit_Framework_TestCase->runTest() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php:954
    PHP  17. ReflectionMethod->invokeArgs() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php:1103
    PHP  18. EloquentStreamRepositoryTest->isReferenceStreamTrue() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php:1103
    PHP  19. Illuminate\Foundation\Application->make() /var/www/html/tests/unit/repo/EloquentStreamRepositoryTest.php:344
    PHP  20. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  21. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  22. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  23. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  24. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  25. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  26. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  27. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
    PHP  28. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:849
    PHP  29. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  30. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  31. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  32. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  33. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  34. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  35. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  36. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
    PHP  37. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:849
    PHP  38. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  39. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  40. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  41. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  42. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  43. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  44. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  45. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
    PHP  46. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:849
    PHP  47. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  48. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  49. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  50. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  51. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  52. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  53. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  54. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
    PHP  55. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:849
    PHP  56. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  57. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  58. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  59. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  60. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  61. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  62. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  63. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
    PHP  64. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:849
    PHP  65. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  66. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  67. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  68. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  69. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  70. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  71. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  72. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
    PHP  73. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:849
    PHP  74. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  75. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  76. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  77. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  78. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  79. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  80. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  81. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
    PHP  82. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:849
    PHP  83. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  84. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  85. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  86. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  87. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  88. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  89. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  90. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
    PHP  91. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:849
    PHP  92. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  93. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  94. Illuminate\Container\Container->Illuminate\Container\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    PHP  95. Illuminate\Foundation\Application->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
    PHP  96. Illuminate\Container\Container->make() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    PHP  97. Illuminate\Container\Container->build() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    PHP  98. Illuminate\Container\Container->getDependencies() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
    PHP  99. Illuminate\Container\Container->resolveClass() /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:804

And so on. Looks like the problem is in Laravel. But there was no problem just two days ago.

**Comment by KonstantinKolodnitsky** [comment]
Sorry, it's a laravel problem

**Comment by besrabasant** [comment]
Yeah, It's a laravel problem... I solved it by deleting all the cache created by `Aspectmock` and the running `composer dump-autoload`
