### ISSUE TITLE
[Yii2Module] tests fail using subdomain rule

### ISSUE THREAD

**Issue by djeux** [Codeception/Codeception#2732]
Before 2.1.5 codeception release all of my tests worked fine.
I have rules configured which use the subdomain part as a client name

```
    [
        'class' => 'frontend\components\web\PublicUrlRule',
        'pattern' => 'r/<token>/<value:\d{1,2}>',
        'route' => 'public/response',
    ],
```

frontend\components\web\PublicUrlRule

```
$host = Yii::$app->params['clientDomain'];

if (($pos = strpos($host, '://')) !== false) {
    $this->host = substr($host, 0, $pos + 3) . '<client>.' . substr($host, $pos + 3);
} else {
    throw new InvalidConfigException("Invalid host provided, must include http(s)://");
}

parent::init();
```

So a real URL would look like this:

```
http://client-name.example.com/r/djwk123bdb2u3dawd123/5
```

It can be accessed from Web, but now fails using tests
Generated pattern:

```
#^http://(?P<client>[^\/]+)\.example\.com/r/(?P<token>[^\/]+)/(?P<value>\d{1,2})$#u
```

**Comment by Naktibalda** [comment]
How does it fail?

**Comment by djeux** [comment]
```
[ExternalUrlException] Codeception\Module\Yii2 can't open external URL: http://schinner-group.example.com/frontend/web/index-test.php/r/yh0AzOb7AMYKURstuPmGG7qP9Ix73fXp/5
```

**Comment by Naktibalda** [comment]
Yii2 modules uses host property of the rule to match domains:
https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/Yii2.php#L275

I don't see the host property in your rule.

**Comment by djeux** [comment]
Host property is defined in the rule class. Basicly if I remove the '-' from all the client name slugs in the subdomain part, then there's no exception.

**Comment by djeux** [comment]
Most likely the culprit is in this method

```
private function getDomainRegex($template)
    {
        if (preg_match('#https?://(.*)#', $template, $matches)) {
            $template = $matches[1];
        }
        $parameters = [];
        if (strpos($template, '<') !== false) {
            $template = preg_replace_callback(
                '/<(?:\w+):?([^>]+)?>/u',
                function ($matches) use (&$parameters) {
                    $key = '#' . count($parameters) . '#';
                    $parameters[$key] = isset($matches[1]) ? $matches[1] : '\w+';
                    return $key;
                },
                $template
            );
        }
        $template = preg_quote($template);
        $template = strtr($template, $parameters);
        return '/^' . $template . '$/u';
    }
```

**Comment by Naktibalda** [comment]
Can you fix it?

**Comment by djeux** [comment]
The fix should be relatively easy (as I see now) by just replacing '\w+' with '[\w_-]+' but requires testing.

**Comment by samdark** [comment]
@djeux when you'll confirm it, let us know.

**Comment by djeux** [comment]
Second issue that came with the 2.1.5 is that the first call to
```
$I->amOnPage() 
```

Is failing with a 404 error. 
Going deeply into it showed that the \yii\web\UrlManager is failing to parseRequest on the first go with
```
if (($result = $rule->parseRequest($this, $request)) !== false) {
             return $result;
       }
```

but succeeding in a 2nd+ test run. 
The patterns and hosts are the same

**Comment by Naktibalda** [comment]
@djeux Why does $_SERVER matter to getInternalDomains?
