### ISSUE TITLE
Codeception 2.1 Default selected option dropdown not submitted

### ISSUE THREAD

**Issue by vaanholtje** [Codeception/Codeception#2733]
When i fill a form and leave the dropdown with the default selected option.
Then this option wil not be posted when i submit the form.

Even when i try to see if the option is selected codeception tells me the dropdown doesn't exist.
$I->seeOptionIsSelected('origin_id', 'Instrumentaal');

Step  I see option is selected "origin_id","Instrumentaal"
 Fail  Element located either by name, CSS or XPath element with 'selected option' was not found.

But when i select an option from the dropdown before the seeIfSelected then it works fine.

Looks like the select inputs are not initialized when the test starts or something?

**Comment by Naktibalda** [comment]
I can't reproduce your issue.

Codeception has a test which verifies that seeOptionIsSelected can see the default option:
https://github.com/Codeception/Codeception/blob/59dd51e89b3bf9929a53d1116c2d159c95ccc9ba/tests/unit/Codeception/Module/TestsForWeb.php#L190
HTML: https://github.com/Codeception/Codeception/blob/2.1/tests/data/app/view/form/select.php

Please provide HTML that you are testing, test code, and *.suite.yml of your test suite.

**Comment by Naktibalda** [comment]
This issue happens then there is no selected option in the dropdown.
Expected behaviour is that the first option is selected by default.

**Comment by Naktibalda** [comment]
I fixed `seeOptionIsSelected`, form submission was working as expected.
