### ISSUE TITLE
[FR] Make it possible to run API tests with phpdbg

### ISSUE THREAD

**Issue by oparoz** [Codeception/Codeception#2734]
If I'm not mistaken, test which require the webdriver don't run when using `phpdbg -qrr`. It seems the REQUEST env variables are not set.

Would it be possible to make Codeception work with `phpdbg` or is it just not possible? The main reason to do it is the large speed difference when running tests.

**Comment by kornrunner** [comment]
Are there any plans on supporting code coverage via `phpdbg`? It's quite faster than `xdebug` for the same thing, and it's code is included in PHP code, at least with newer releases.

I don't know if codeception is using `xdebug` for other purposes, but if it's only for code coverage - then `phpdbg` sounds as a better choice, at least to me.

Thank you!

**Comment by Naktibalda** [comment]
Codeception does not do code coverage itself.
Code coverage report is generated by `php-code-coverage` library which is used by PHPUnit.
https://github.com/sebastianbergmann/php-code-coverage

**Comment by kornrunner** [comment]
Yeah, my bad about that. Thanks!

**Comment by oparoz** [comment]
@Naktibalda - Does it means that on PHP,  if we simply ask for coverage without loading the xdebug extension, we'll get coverage reports created by `phpdbg`?

**Comment by kornrunner** [comment]
@oparoz you need to wrap codeception call with `phpdbg`, something like:

```
$ phpdbg -qrr vendor/bin/codecept run --coverage
```

**Comment by oparoz** [comment]
@kornrunner - I misunderstood @Naktibalda's answer.
Code coverage works for unit tests, but it doesn't for API test, but that may be a problem with c3.
