### ISSUE TITLE
[FR] Filter Cept tests by name

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2736]
Situation: I have 30 Cept files in a directory and I want to run 5 of them sharing the same prefix.
I don't want to run all tests every time because functional tests are slow.

Current options:
a) run each test manually
b) implement a deeper hierarchy and run a subdirectory.

It would be nice to be able to run  `codecept run tests/functional/module/ :create` and get only matching tests executed.

**Comment by oehlschl** [comment]
FYI, I think this can be closed since #3482 was merged.

You should be able to run all tests containing "create" in dir tests/functional/module/ via `codecept run tests/functional/module/:create`, or `codecept run tests/functional/module/:^create` for tests beginning with "create".
