### ISSUE TITLE
C3.php fails to write CodeCoverage report

### ISSUE THREAD

**Issue by jostauf** [Codeception/Codeception#2737]
The following code:
```php
if (!file_exists(dirname($current_report))) { // verify directory exists
    mkdir(dirname($current_report), 0777, true);
} else {
    __c3_error("Can't write CodeCoverage report into $current_report");
}
```
creates an error situation if the directory exists, and then nothing works.
Removing the "else" clause fixed the problem for me.

**Comment by Naktibalda** [comment]
Thanks,
c3 has a separate repository: https://github.com/Codeception/c3

**Comment by DavertMik** [comment]
Looks like it was fixed recently
