### ISSUE TITLE
Dependency on composer-plugin-api 1.0.0

### ISSUE THREAD

**Issue by iainfogg** [Codeception/Codeception#2745]
I have 2.0.5 of c3 installed, and every time I run composer I now get the following error:

The "codeception/c3" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

**Comment by DavertMik** [comment]
Thanks. We need to update it

**Comment by chrisx84** [comment]
oh so it is a bug? just started getting this error when i updated my laravel project from 5.1 to 5.2 tonight.

**Comment by RyanHavoc** [comment]
@iainfogg Does your code coverage still work regardless of this warning?

**Comment by DavertMik** [comment]
should work. It's not about c3 itself, it's about the package on packagist. Basically c3.php is just one file which should be placed into root. We use Composer API plugin to put it there automatically.

**Comment by iainfogg** [comment]
@RyanHavoc yes, the code coverage still works fine - it's just that it (the composer install / update process) will stop working at some point in the future if it's not sorted, but @DavertMik has it on the list to sort before that happens
