### ISSUE TITLE
I don't want to call "__phpunit_verify" manually when use Stub method

### ISSUE THREAD

**Issue by neoascetic** [Codeception/Codeception#2747]
See #440 and especially [this comment](https://github.com/Codeception/Codeception/issues/440#issuecomment-159893647).

Currently, there is a need to call `$mock->__phpunit_verify()` manually at the end of the test. In case if it is impossible to do this automatically, codeception need to have documentation on this nuance .

Thank you!

**Comment by Naktibalda** [comment]
I've been looking into this recently.

To make verification working automatically you have to pass an instance of PhpUnit_Framework_TestCase as the last argument to Stub::makeX() method.
`$this` works in all test formats in Codeception 2.1.

It could get worse in 2.2
