### ISSUE TITLE
Internet Explorer unbelievably slow.

### ISSUE THREAD

**Issue by beedge72** [Codeception/Codeception#275]
I know this is probably more of a selenium issue than codeception as such, but thought Id ask anyway.

I hav e recently started to try running my tests on IE. This is what I have done on my Windows 7 machine.

Downloaded https://code.google.com/p/selenium/downloads/detail?name=IEDriverServer_x64_2.32.3.zip&can=2&q=
put it in my directory with selenium
put IE in my PATH variable
set my acceptance.yml like so:

class_name: WebGuy
modules: 
   enabled: [Selenium2]
   config:
      Selenium2:
         url: 'http://localhost:1616' 
         browser: 'internet explorer'
         capabilities:
             unexpectedAlertBehaviour: 'accept'

when I run my tests, IE starts up ok, so far so good. The problem is with the speed. when I try to ->fillfield there is about a 7 second gap between each character in a string being input. This makes the log in process, which is needed in all my tests take at least 1 minute. This wont work!

Has anyone else gotten (and overcome) these issues using IE?

My browser version is IE 10.

Thanks in advance.

**Comment by Alexhha** [comment]
The same issue on win 7 x64/ie 11/IEDriverServer_2.53.1. Have I correctly understood that if we are using 32-bit of IEDriverServer it will call 32-bit of IE?
