### ISSUE TITLE
No Symfony3 support in 2.1.5 release

### ISSUE THREAD

**Issue by ujhgj** [Codeception/Codeception#2753]
In changelog I see Symfony3 support declared. It's not true, actually.
Probably, bug in composer.json.

app@core12-app:/application$ composer require --dev "codeception/codeception:2.1.5"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v3.0.1
    - Conclusion: don't install symfony/symfony v3.0.1
    - don't install symfony/symfony v3.0.1|remove symfony/css-selector v2.8.2
    - don't install symfony/css-selector v2.8.2|don't install symfony/symfony v3.0.1
    - don't install symfony/css-selector v2.8.2|don't install symfony/symfony v3.0.1
    - Installation request for symfony/symfony == 3.0.1.0 -> satisfiable by symfony/symfony[v3.0.1].
    - Installation request for symfony/css-selector == 2.8.2.0 -> satisfiable by symfony/css-selector[v2.8.2].

**Comment by ujhgj** [comment]
My fix:
https://github.com/Codeception/Codeception/pull/2754

**Comment by ujhgj** [comment]
#2754

**Comment by Naktibalda** [comment]
Why does it try to install symfony/css-selector[v2.8.2] ?

**Comment by ujhgj** [comment]
Wrong composer notation, I guess. Check changes I made in the pull request.

**Comment by Naktibalda** [comment]
Current syntax works just fine,
on PHP 5.6 composer installs
```
  - Removing symfony/finder (v2.8.2)
  - Installing symfony/finder (v3.0.1)
    Loading from cache

  - Removing symfony/console (v2.8.2)
  - Installing symfony/console (v3.0.1)
    Loading from cache

  - Removing symfony/event-dispatcher (v2.8.2)
  - Installing symfony/event-dispatcher (v3.0.1)
    Loading from cache

  - Removing symfony/yaml (v2.8.2)
  - Installing symfony/yaml (v3.0.1)
    Loading from cache

  - Removing symfony/dom-crawler (v2.8.2)
  - Installing symfony/dom-crawler (v3.0.1)
    Loading from cache

  - Removing symfony/browser-kit (v2.8.2)
  - Installing symfony/browser-kit (v3.0.1)
    Loading from cache

  - Removing symfony/css-selector (v2.8.2)
  - Installing symfony/css-selector (v3.0.1)
    Loading from cache
```

On PHP 5.4:
```
  - Removing symfony/finder (v3.0.1)
  - Installing symfony/finder (v2.8.2)
    Loading from cache

  - Removing symfony/console (v3.0.1)
  - Installing symfony/console (v2.8.2)
    Loading from cache

  - Removing symfony/event-dispatcher (v3.0.1)
  - Installing symfony/event-dispatcher (v2.8.2)
    Loading from cache

  - Removing symfony/yaml (v3.0.1)
  - Installing symfony/yaml (v2.8.2)
    Loading from cache

  - Removing symfony/dom-crawler (v3.0.1)
  - Installing symfony/dom-crawler (v2.8.2)
    Loading from cache

  - Removing symfony/browser-kit (v3.0.1)
  - Installing symfony/browser-kit (v2.8.2)
    Loading from cache

  - Removing symfony/css-selector (v3.0.1)
  - Installing symfony/css-selector (v2.8.2)
    Loading from cache
```

As you can see, all components have the same version.
I can only guess that your project has some other dependency which restricts version of symfony/css-selector to 2.8.2

**Comment by ujhgj** [comment]
But why it should use version 2.8.2 and remove 3.0.1?
Doesn't "symfony/css-selector": ">=2.4|<3.1" mean that lib compatible with 3.0.1 version of dependency?

**Comment by Naktibalda** [comment]
I experimented with composer platform setting.

**Comment by ujhgj** [comment]
Re-checked the issue. I had to remove vendor folder, but after that install was succeed. Probably, you're right.
