### ISSUE TITLE
Yii2 connector bug in handling redirects

### ISSUE THREAD

**Issue by TimNZ** [Codeception/Codeception#2756]
In testing the classic Login form in a functional test, $_SERVER['REQUEST_URI'] is set to null in Yii2.php:doRequest() on a 302 response from Yii where there is no path, just a host e.g. 'http://test.dev'.

This results in yii\web\Request::resolveRequestUri() throwing an InvalidConfigException('Unable to determine the request URI.')

Spent hours tracing down what was happening only to click now to set the home url to 'http://test.dev/' (not trailing slash) as a work-around.

You possibly can't just set $_SERVER['REQUEST_URI'] to / if null as it could result in too many redirects.

**Comment by samdark** [comment]
Can you reproduce it with Yii's basic app template?

**Comment by samdark** [comment]
Got no info since January. Can't proceed with the issue.
