### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by Nemmo** [Codeception/Codeception#2759]
Ohhh, that infinite problems with charsets!
I have one another issue about cyrilic charset when I use the Db module. The code below not working cause of hieroglyhs. PHP file in utf8, database too. Codeception version 2.0.16, Yii 2

``` php
$I->canSeeInDatabase('member', [
    'name' => 'Светлана'
]);
```

The log:

``` console
* I see in database "member",{"name":"��������"}
��"}

  [Query] select count(*) from `member` where `name` = ?
 FAIL
```

**Comment by Naktibalda** [comment]
I will try to reproduce it later.

**Comment by Naktibalda** [comment]
I blame encoding of your test file.
Your output clearly has one byte per character.

I created the cept file in utf-8 and got this output:
`* I see in database "users",{"name":"Светлана"}`

**Comment by Nemmo** [comment]
```mysql
SHOW FULL COLUMNS FROM member;
```
![default](https://cloud.githubusercontent.com/assets/5058015/12738533/b1335d54-c98b-11e5-9a7c-5aae8f592bdd.PNG)

Cest file:
![1](https://cloud.githubusercontent.com/assets/5058015/12738535/b3bafa78-c98b-11e5-85e9-913f3286ae33.PNG)

**Comment by Naktibalda** [comment]
Your test code.

**Comment by Nemmo** [comment]
```php
public function myTest(FunctionalTester $I) {
    $I->canSeeInDatabase('member', [
        'name' => 'Светлана'
    ]);
}
```

**Comment by Naktibalda** [comment]
Can your terminal display UTF-8 characters?

Test with `$I->wantTo("see Светлана");`

Yesterday I tested on Ubuntu in Konsole.

Now I tried to run above test via Putty and got this crap:

`1) Failed to see ð¡ð²ðµñð»ð°ð½ð° `

**Comment by Nemmo** [comment]
Yes, of course. If I print Debug::debug('Светлана') I see the name clear. One more thing: I am using Vagrant as server environment.

**Comment by Naktibalda** [comment]
This has nothing to do with Db module, "I see in database" output is printed in the same way as debug output.

@DavertMik you should know more about cyrilic charset issues.

**Comment by Nemmo** [comment]
Maybe the problem is when we encode and decode objects with json inside the db module?

**Comment by InVeX** [comment]
Can confirm having the same issue. Occurs on both Win and Linux machines. Problem occur only in the log. When using webception this causes fatal error but for the webception there is a workaround to avoid fatal error.

**Comment by AlexKR** [comment]
Same issue for PostgreSQL.
For MySQL you can try to set "charset=utf8" in dsn

**Comment by luizgama** [comment]
I have the same problem on windows, with latin characters like ê, à, ç

**Comment by nicholascus** [comment]
The problem is in [Codeception\Step::humanize()](https://github.com/Codeception/Codeception/blob/master/src/Codeception/Step.php#L239) function
``` 
    protected function humanize($text)
    {
        $text = preg_replace('/([A-Z]+)([A-Z][a-z])/', '\\1 \\2', $text);
        $text = preg_replace('/([a-z\d])([A-Z])/', '\\1 \\2', $text);
        $text = preg_replace('~\bdont\b~', 'don\'t', $text);
        return strtolower($text);
    }
```
It screws utf8 strings. Solution is to fix it there, e.g. by extending return statement as below
```
        if (!preg_match('!!u', $text)) {
            return strtolower($text);
        } else {
            return mb_strtolower($text);
        }
```
