### ISSUE TITLE
Autoload Cest Classes

### ISSUE THREAD

**Issue by B4rb4ross4** [Codeception/Codeception#2764]
Hey Guys,
I'm writing some tests for a versionized webservice. I decided to put the tests for each version in a  own suite, because the tests for each version will contain tests for about 20 endpoints with ~350 steps each. 

Now I don't want duplicate code and I would like to extend Cest-classes from the suite of the next lower Version:

suite34
MobileServiceTests\MobileService\V34\TestCest
suite35
MobileServiceTests\MobileService\V35\TestCest extends MobileServiceTests\MobileService\V34\TestCest
and so on.

 Now I ran into the problem, that the test suites are not autoloaded normally. (Why would they. Codeception knows where to find them). I need an easy way to register all Cests from specific suites to my Autoloader.

The Autoloader does this for the path of the 34 Cest in the 35 Cest file:
suite35\MobileServiceTests\MobileService\V34\TestCest.php

Anyone got a heads up? You would be the hero of the day!

**Comment by DavertMik** [comment]
you can name your class in PSR-4 manner and register them in Composer
or you can use our autoloader http://codeception.com/docs/reference/Autoload

**Comment by B4rb4ross4** [comment]
Thanks for the heads up. I used the composer way. Now works like a charm.
