### ISSUE TITLE
Support for Slim Framework

### ISSUE THREAD

**Issue by jasny** [Codeception/Codeception#2765]
[Slim Framework](http://www.slimframework.com/) is a popular PHP micro framework.

A Slim module should work similar to other framework modules.

**Comment by Naktibalda** [comment]
You have to implement the module yourself.

**Comment by DavertMik** [comment]
Yep, that's not hard to get such implementation. You can look at ZendExpressive or Lumen modules, they are microframeworks as well

**Comment by devartbvba** [comment]
Did anyone make such a module already? Was it shared on Github?

**Comment by Naktibalda** [comment]
For Slim Framework? No.

**Comment by herloct** [comment]
@jasny @devartbvba 
I'm doing it myself, [here](https://github.com/herloct/codeception-slim-module).
I'm not sure if I'm doing it right, but atleast it works on my project.

Is there any example of how to test framework module(s)?

**Comment by DavertMik** [comment]
Thanks @herloct it looks good! I already added your module to [Addons Page](http://codeception.com/addons) and tweeted about it. Please keep the good work!
