### ISSUE TITLE
DbModule cleanup in _initialize()

### ISSUE THREAD

**Issue by PaulWeb** [Codeception/Codeception#2767]
in version 2.0

``` php
      if ($this->config['populate']) {
            $this->cleanup();
            $this->loadDump();
            $this->populated = true;
        }
```

but  since version 2.1

``` php
      if ($this->config['populate']) {
           if($this->config['cleanup']){
                $this->cleanup();
          }
            $this->loadDump();
            $this->populated = true;
        }
```

Could you add new option **cleanupInit** because in most cases it is necessary to clear database before loadDump and I do not need the database to be cleaned after each test.

**Comment by srigi** [comment]
I'm in this too. I don't see the point of cleaning the database before every test. In my acceptance tests I need clearing only at the beginning of the testing run.

**Comment by eXorus** [comment]
We're closing this issue as it has gone 4 years without activity. In our experience if an issue has gone 4 years without any activity then it's unlikely to be addressed.

If it is still relevant then we encourage you to open it again as a new issue in the new module repository:
https://github.com/Codeception/module-db
