### ISSUE TITLE
seeResponseJsonMatchesXpath fails if JSON contains ampersand

### ISSUE THREAD

**Issue by gunfrank** [Codeception/Codeception#2775]
Trying to match JSON with "xpath" (jsonpath?) via seeResponseJsonMatchesXpath fails if the asserted JSON contains an element with ampersand in it.

JSON example:
`
{  
   "product":[  
      {  
         "category":[  
            {  
               "comment":"something & something"
            }
         ]
      }
   ]
}`

Error:
`[PHPUnit_Framework_Exception] Codeception\Util\JsonArray::arrayToXml(): unterminated entity reference something`

**Comment by javigomez** [comment]
@gunfrank I had issues with `seeResponseJsonMatchesXpath` instead it ended up being much more easier using arrays. Try: 

```
$I->seeResponseContainsJson(
			[
			     'product'            => [ "category" => [ "comment" => "something & something" ]
			]
);
```

```
