### ISSUE TITLE
Add polyfills to composer.json in master branch

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2790]
https://github.com/Codeception/Codeception/pull/2784/files#diff-e7dc03741ac5d635b6fcb6a4b6907f89
I increased usage of mb_strlen and mb_substr
and removed `if (function_exists('mb_strlen')) {` 
because @DavertMik advised me that symfony/polyfill-mbstring is included in composer.lock

symfony/polyfill-mbstring is a dependency of symfony/console 2.8+, so we need a direct dependency to get it installed for PHP 5.4.

Also I noticed that polyfill-mbstring is using iconv functions, would it be beneficial to require polyfill-iconv? 
A growing number of symfony components is depending on polyfill-mbstring, but none of them depends on polyfill-iconv.

**Comment by raistlin** [comment]
polyfill-iconv is a fallback for when php-iconv functions are not installed on the system. I think decision of installing iconv or polyfill-iconv should be left to developer.

**Comment by DavertMik** [comment]
I think It's a good idea to require mb-string polyfill.
As for iconv, so these functions should be enabled in PHP distributions. So I don't see reason to use this polyfill by default.
