### ISSUE TITLE
[L5] Authentication doesn't persist between requests

### ISSUE THREAD

**Issue by Anahkiasen** [Codeception/Codeception#2795]
Using `$I->amLoggedAs(User::find(1))` will execute the following code:

```php
if ($user instanceof Authenticatable) {
    $guard->setUser($user);
    return;
}
```

However this just calls `AuthManager::setUser` which just sets the authenticated user _for the current request_. Instead I believe `AuthManager::login` should be called, which remembers the user in session, for future requests as well.

Without this if in your functional tests you submit a form or click on a link, you'll be back to the login form. Or was this intended behavior and if so how do I work around this?

**Comment by janhenkgerritsen** [comment]
This was not intended behavior, thanks for reporting the issue!
