### ISSUE TITLE
Modify AMQP module to use php-amqplib/php-amqplib

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2797]
Composer displays this warning:
`Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.`

**Comment by xlight** [comment]
+1

**Comment by tiger-seo** [comment]
We can update it, there is no BC, AFAIK

**Comment by Naktibalda** [comment]
Completed by 65971b0dee4972710365b6102154cd412a9bf7b1
