### ISSUE TITLE
Db module reconnects even if reconnect = false

### ISSUE THREAD

**Issue by thanpa** [Codeception/Codeception#2801]
After having many functional tests running I ended up with the error:

`An exception occured in driver: SQLSTATE[08004] [1040] Too many connections`

I am using symfony2 where I have a call to end the connection in _after method.

I made some digging and realised that the Db module calls connect with every run of a test, even if my setting reconnect is set to false. This is creating new connections with every test run and with the PDO disability to disconnect this creates many connections and results in failing my suite.

**Comment by Naktibalda** [comment]
@thanpa wrote:
`Hm looks like it's my bad, some debug code I left called it many times. sorry pls ignore the pull request.`
