### ISSUE TITLE
Couldn't parse test 'Feature file can only be parsed with Behat\Gherkin library. Please install `behat/gherkin` with Composer'

### ISSUE THREAD

**Issue by geebengs** [Codeception/Codeception#2807]
Hello, I am trying to use codeception in yii2. I installed codeception using composer.

I used codeception bootstrap. I have successfully done codeception build. However, when I tried to do codeception run it gives me the following error:

[Codeception\Exception\TestParseException]
  Couldn't parse test 'Feature file can only be parsed with Behat\Gherkin library. Please install `behat/gherkin` with Composer'.

Kindly help resolve this.

Thanks

**Comment by Naktibalda** [comment]
Don't use master branch.

**Comment by geebengs** [comment]
Kindly tell me how else to install it without using master branch. 

Thanks.

**Comment by Naktibalda** [comment]
`"codeception/codeception": "2.1.*"`

**Comment by geebengs** [comment]
OK. Thanks so much. I used 2.5 initially.

I'll try this out.

**Comment by DavertMik** [comment]
Looks I need to add gherkin into `require` section of `composer.json`

**Comment by sasha-ch** [comment]
+1
