### ISSUE TITLE
[Help]fillField using various options but not working

### ISSUE THREAD

**Issue by SSyar** [Codeception/Codeception#2809]
`<div class="uname-block">
  			<span class="login-icon"><i class="fa fa-user fa-fw"></i></span>
  			<input type="text" id="LoginForm_username" name="LoginForm[username]" value="" class="input input-block-level" placeholder="Confirm your email">
</div>`

In the above code i have tried,, the following three option and none of them are working for me

> $I->fillField('LoginForm_username', 'test@email.com');

> $I->fillField(['name' => 'LoginForm[username]'], 'test@email.com);

> $I->fillField(['class' => 'input-block-level'], 'test@email.com');

what am i doing wrong, can someone help

**Comment by SSyar** [comment]
updating the dev code, may be this will help

**Comment by kerimovaa** [comment]
always use CssPath . Try this:
`$I->fillField("div.uname-block > input#LoginForm_username", "test@email.com")`

**Comment by SSyar** [comment]
Although i figure out the issue.,., but Thanks for the reply.
