### ISSUE TITLE
Bad encoding in HTML report

### ISSUE THREAD

**Issue by kerimovaa** [Codeception/Codeception#2810]
I met problem with encoding test's name in HTML report . Tests' names on russian language (Windows 10). 
For example , a piece of test: 

1. `$I = new AcceptanceTester\MainPageSteps($scenario);
2. $I->am('Клиент PROFI.RU'); 
3. $I->wantToTest('PROFI-4:Проверка отправки email');
4. $I->lookForwardTo('Создал заказ и отправил свой email');

`   

Launch of test : 
`codecept run testname -- html report.html`

And a piece of html report:
`<td>
     <h3>Acceptance Tests</h3>
 </td>
</tr>   <tr class="scenarioRow scenarioSuccess">
    <td>
     <p class="scenarioSuccess" onclick="showHide('1', this)">[+] Test profi-4:�������� �������� email (PROFI-4_Cept) <span style="color: #34495e; font-size: 70%;">83.19s</span></p>
    </td>
   </tr>`

And screenshot : https://yadi.sk/i/6bBAWKsgp4GUG

**Comment by pejaycz** [comment]
Same problem with czech language

![problem](https://cloud.githubusercontent.com/assets/3164102/13214839/24fba388-d952-11e5-99e5-d4fe5be70225.png)

**Comment by Naktibalda** [comment]
@pejaycz: Can this ticket be closed now? #2831

**Comment by pejaycz** [comment]
@Naktibalda I think you can close it. I am not experiencing any problem with encoding, so i think its fixed for @kerimovaa too.

**Comment by kerimovaa** [comment]
Ok,thanks! Close.
