### ISSUE TITLE
Codecept silently terminate on exit() in application code

### ISSUE THREAD

**Issue by sasha-ch** [Codeception/Codeception#2815]
My case is:
Some yii2 application code has `exit(1)` inside (it is a bug).
When it used by SomeCest::_before(), `codecept run` is silently terminated:
```bash
sasha-ch@ubuntu:/var/www/<project>/tests$ ../vendor/bin/codecept run acceptance SomeCest:firstTestExample
Codeception PHP Testing Framework v2.1.5
Powered by PHPUnit 4.8.22 by Sebastian Bergmann and contributors.
Acceptance Tests (16) --------------------------------------------------------------------------------------------------
Trying to do something (tests\acceptance\SomeCest::firstTestExample)... sasha-ch@ubuntu:/var/www/<project>/tests$
```
I think it will better to write something like "Codecept immediately terminated" in cli.
Possible way is to add `static $finished = false|true` property to (may be) Codeception\Command\Run
and enhance Codeception\Subscriber\ErrorHandler::shutdownHandler() to use it.
And may be replace `exit(1);` in Codeception\Command\Run:208 with some `soft_exit(1)`.

How do you about it?
PS: I am newbie in Codeception.

**Comment by DavertMik** [comment]
There is nothing we can do to wrap exit operator. If it is called somewhere it will end up application. This should not be used in your application.
