### ISSUE TITLE
jQuery - auto populate drop down country list selection

### ISSUE THREAD

**Issue by SSyar** [Codeception/Codeception#2829]
can some one please let me know how to select this jQuery dropdowns

http://phppot.com/demo/jquery-dependent-dropdown-list-countries-and-states/

This is what i am trying

```
<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('Check Drop Down');
$I->amOnPage('http://phppot.com/demo/jquery-dependent-dropdown-list-countries-and-states/');
$I->see('Demo jQuery Dependent DropDown List - Countries and States');
$I->selectOption('country-list', '1');
$I->selectOption('state-list', '16');
?>
```

**Comment by Naktibalda** [comment]
Are you using WebDriver?

**Comment by SSyar** [comment]
No!,, i am not using WebDriver...,

**Comment by SSyar** [comment]
there isn't any workaround without WebDriver ?

**Comment by SSyar** [comment]
ok,, the above case works,, simply installing by WebDriver :)
