### ISSUE TITLE
SQLite driver uses different paths for the same config

### ISSUE THREAD

**Issue by mcustiel** [Codeception/Codeception#2830]
Hi. I have a tests suite running that uses a sqlite file for the testing database.
I had fails when running the cleanup of the database or the loading data into it regarding the file name, if I change the file name to make it run on cleanup and load, then it fails before reaching those actions.
I gave a look at the SQLite connector and I noticed that the constructor of sqlite creates a connection using the exact same path given in config, and then it rewrites the path prepending the codeception tests file. 
As a result I have two different paths for connections based in the same configuration.
I created a fix for this problem to have always the same path for any connection made using the same config: https://github.com/Codeception/Codeception/pull/2812
Please let me know if you agree with it.

**Comment by Naktibalda** [comment]
I merged your pull request #2812
