### ISSUE TITLE
Friend killed after Suite

### ISSUE THREAD

**Issue by eXorus** [Codeception/Codeception#2836]
Hello,

When I use haveFriend/does in a test case of Cest File the new window is closing at the end of the suite.

My conf is restart: true so I'm expected to kill all the windows after each test case.

```
    public function testFriend1(AcceptanceTester $I)
    {
        $toto = $I->haveFriend('toto', $I);
        $toto->does(function($I) {
            $I->amOnUrl('http://localhost/toto-friend');
        });

        $I->amOnUrl('http://localhost/toto-nofriend');
    }

    public function testFriend2(AcceptanceTester $I)
    {
        $titi = $I->haveFriend('titi', $I);
        $titi->does(function($I) {
            $I->amOnUrl('http://localhost/titi-friend');
        });
        $I->amOnUrl('http://localhost/titi-nofriend');
    }
```
### Actual behaviour (order by closed windows) :

At the end of the test case testFriend1
1. toto-nofriend

At the end of the test case testFriend2
2. titi-nofriend

At the end of the test suite
3. toto-friend
4. titi-friend
### Expected behaviour (order by closed windows) :

At the end of the test case testFriend1
1. toto-nofriend
2. toto-friend

At the end of the test case testFriend2
3. titi-nofriend
4. titi-friend

**Comment by DavertMik** [comment]
Sorry for your friend... :)

**Comment by eXorus** [comment]
So what I suspect is that friend is killed when Actor is killed because this is Actor that have friends.

Unfortunately, all actors injected in the test case are killed at the end of the test suite. I'm not sure it's good for performance.
