### ISSUE TITLE
could PHP LINT validation become optional ?

### ISSUE THREAD

**Issue by firodj** [Codeception/Codeception#2837]
We are using HHVM 3.9.1 which are defined as PHP_MAJOR_VERSION=5.
As our tests is growing, the start up time when running tests also increasing significantly.
After investigated we found that the lint validation took up about ~120 ms per test file, and 4 minutes total for all files just for linting.

Can this validation as optionally disabled?

**Comment by DavertMik** [comment]
Well, that was my first choice to not use validation on HHVM. Probably you are right, this should be configurable.

**Comment by firodj** [comment]
ok thanks @DavertMik

**Comment by Naktibalda** [comment]
It needs a better documentation than Changelog.

**Comment by DavertMik** [comment]
Yes. We have configuration reference, and we can put it there
