### ISSUE TITLE
WebDriver see method does not allow Strict locator

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#2839]
The see function in Codeception 2.0 do not allow passing a strict locator like: `$I->see(['link' => 'login']);`

You get: `[PHPUnit_Framework_Exception] Array to string conversion`

see: https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/WebDriver.php#L382-L389

**Comment by Naktibalda** [comment]
a) this is a feature request.
b) 2.0 is no longer supported, please use 2.1.

**Comment by DavertMik** [comment]
Yes it is. `see` expects first parameter to be text which user sees.
In your case you should use `seeElement` method which checks elements and may use strict locators
