### ISSUE TITLE
Webdriver module missing moveToElement

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#2840]
Long story short: since Selenium 2.48 there is a new addition causing a lot of trouble. Is the known error:

```
[UnknownServerException] Element is not clickable at point (XXX.XXXXXXXX, YY.YYYYYY). Other element would receive the click:
```

this happens when you have a floating element over the element that you want to click:

![capture 2016-02-03 at 17 43 53](https://cloud.githubusercontent.com/assets/1375475/13292989/33831c4c-db1e-11e5-95bf-7ce48043ac2b.png)

You can seen the whole issue described at: https://github.com/SeleniumHQ/selenium/issues/1202

I have tried with this suggestion (https://github.com/SeleniumHQ/selenium/issues/1202#issuecomment-159909722):

![screen shot 2016-02-24 at 17 48 30](https://cloud.githubusercontent.com/assets/1375475/13293161/d742ad48-db1e-11e5-9ff3-cd1f980ef803.png)

Adding this in my acceptance.suite.yml:

```yaml
            capabilities:
              elementScrollBehavior: '1'
```
But doesn't seem to do the trick.

I was now trying the advise at https://github.com/SeleniumHQ/selenium/issues/1202#issuecomment-173656799. And is to use:

![screen shot 2016-02-24 at 17 47 02](https://cloud.githubusercontent.com/assets/1375475/13293106/a1da265e-db1e-11e5-8265-b36dae5c8f8b.png)

And I have noticed that despite that the Facebook Webdriver implements the function:

https://github.com/facebook/php-webdriver/blob/community/lib/Interactions/WebDriverActions.php#L170-L186

The Codeception Webdriver module does not implement it.

I was wondering how to implement it. It should be something like adding this:

````php
    public function moveTo($selector)
    {
        $el = $this->findField($selector);
        $this->webDriver->getMouse()->moveToElement($el);
    }
````
at: https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/WebDriver.php

But I'm missing something, because I get: `FATAL ERROR. TESTS NOT FINISHED.
Call to undefined method RemoteMouse::moveToElement() `

Any advise on how to implement this?

Thanks ^_^

**Comment by Naktibalda** [comment]
moveToElement is not a method of RemoteMouse, it is a method of WebDriverActions.

The only method currently using WebDriverActions is dragAndDrop: https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/WebDriver.php#L2005

**Comment by DavertMik** [comment]
@javigomez I hope you can get it implemebted by following an advice of @Naktibalda 
If so, please send PR into 2.1 branch

Btw, In CodeceptJS we have `scrollTo` method. I agree we need to have smeth like it in Codeception

**Comment by javigomez** [comment]
Oh I missed that! thanks @Naktibalda for the advise :sweat_smile: 

Yes, @DavertMik I will try to implement today and I'll send news. 
Naming it `scrollTo` like you do in CodeceptJS sounds to me much better than `moveTo` or `moveToElement`. I will use that name.

**Comment by javigomez** [comment]
Also we could create a function like this in codeception: https://github.com/gterre/stuff/blob/master/JavascriptUtils.java#L155-L174 adding it to the Click command.

So when I do $I->click we always check if the element is clickable before clicking on it, otherwise we raise an error.

**Comment by javigomez** [comment]
#2882 should close this issue
