### ISSUE TITLE
Attach file on 2 two different fields with Selenium WebDriver for Firefox

### ISSUE THREAD

**Issue by SSyar** [Codeception/Codeception#2843]
I have 2 fields to attach files how can i do that
![clipboard01](https://cloud.githubusercontent.com/assets/17178080/13312877/d6396098-dbbb-11e5-8fc8-1c8b6c8aa2d3.png)
i am using, attachfile command twice but not working
$I->attachFile('//input[@type="file"]', 'test_doc_1.docx');
$I->attachFile('//input[@type="file"]', 'test_doc_2.docx');

**Comment by Naktibalda** [comment]
Attach by name or id, not by type.

By name:
```
$I->attachFile('file1', 'test_doc_1.docx');
$I->attachFile('file2', 'test_doc_2.docx');
```

By ID:
```
$I->attachFile('#file1', 'test_doc_1.docx');
$I->attachFile('#file2', 'test_doc_2.docx');
```

**Comment by SSyar** [comment]
Great thanks,,, it worked,, 
i was trying with ID and Name but the syntax was not correct., but you showed the right way..,
