### ISSUE TITLE
Codeception - Laravel 5.1 issue when updating from 2.1.3 to newer.

### ISSUE THREAD

**Issue by erdemkeren** [Codeception/Codeception#2848]
Hello, when I update my codeception copy with a version newer than 2.1.3, my sessions are being lost "between http requests." I store the sessions using redis, and my suite config, Laravel5 block has cleanup: true.

However I need to cleanup database between tests. Not everything between requests.

**Comment by janhenkgerritsen** [comment]
The `cleanup` configuration only affects the database, nothing else.

Can you post your suite config and an example of a test case for which this problem occurs?

**Comment by erdemkeren** [comment]
Sure, But please note that, I can not reproduce my problem when the cleanup configuration is false with 2.1.16. Using 2.1.3; my tests works with both true and false.

```yaml
class_name: ApiTester
modules:
    enabled:
        - Helper\Api
        - Asserts
        - Laravel5:
            environment_file: .env.testing
            cleanup: true
        - REST:
            depends: Laravel5
            environment_file: .env.testing
```

ApiTester.php @ public function haveAccessTo(...), Creates a random user, adds rbac abilities and logins. Sets the given token to HTTP Headers.

AddressResourceCest.php case:
```php
class AddressResourceCest
{
    public function IShallGetAddressList(ApiTester $I)
    {
        $I->wantTo('Get a list of addresses paginated.');

        // Given
        $I->haveAccessTo("view-addresses");
        $I->haveRecord('addresses', [
            "name" => $faker->name(),
            'country_id' => 1
        ]);

        // When
        $I->sendGET($this->endpoint);

        // Then
        $I->seeResponseCodeIs(200);
        // So on...
    }
}
```

Verbose test results:
````
Get a list of addresses paginated. (AddressResourceCest::IShallGetAddressList)
Scenario:
* I grab service "..."
* ...
* I have http header "Accept","application/json"
* I send post "/auth/login",{"name":"uLemke","password":"5%iLR`("}

[Request headers] {"Accept":"application/json"}
  [Request] POST /auth/login {"name":"uLemke","password":"5%iLR`("}
  [Response] {"token":"3ed1e856192b29ef119d8ce13d75ded7d43ffa24"}
  [Headers] {"cache-control":["no-cache"],"content-type":["application/json"],"date":["Fri, 26 Feb 2016 11:35:11 GMT"]}
  [Status] 200

* I grab data from response by json path "token"
* I have http header "X-Authorization","3ed1e856192b29ef119d8ce13d75ded7d43ffa24"

I have record "addresses",{"name":"foo","country_id":792}
* I send get "/address"
  [Request headers] {"Accept":"application/json","X-Authorization":"3ed1e856192b29ef119d8ce13d75ded7d43ffa24"}
  [Request] GET /address
  [Response] {"errors":[{"message":"Undefined or expired token, please login again"}],"type":"AuthenticationException","meta-data":[]}
  [Headers] {"cache-control":["no-cache"],"date":["Fri, 26 Feb 2016 11:35:11 GMT"],"content-type":["application/json"],"access-control-allow-origin":[],"vary":["Origin"]}
  [Status] 401
* I see response code is 200
 FAIL
```

**Comment by janhenkgerritsen** [comment]
I don't see how the `cleanup` setting can have this impact. The only thing this setting does when enabled is starting a database transaction before a test case and rolling back this transaction after a test case.

I don't know how your application works, but do you have in idea how this possibly can lead to your problem? For example, do you use database transactions in the code under test? Are there dependencies between test cases?

To be honest I don't have an idea of what could be the problem, but I have some suggestions of things you can do.

The first suggestion is to see if you can replicate the problem in versions 2.1.4 and 2.1.5 of Codeception. If I know the first version of Codeception where your problem occurs I can look at the changes made in that version and possibly get an idea from that.

The other suggestion is that you try to recreate the issue in a new application with a minimum amount of code. That will make debugging the issue a lot easier.

**Comment by erdemkeren** [comment]
Yes, the problem occurs on every version newer than 2.1.3. My dependency was 
```json
        "codeception/codeception": "*",
```
and I rolled back until my tests work again and it is 2.1.3. I will start with a fresh install of laravel 5.1. now and try to regenerate the same state.

**Comment by erdemkeren** [comment]
Hello again,

Here is what I found. 

I have a special SessionServiceProvider which gets the token from headers instead of the cookies. 

When I return back to the default SessionServiceProvider of Laravel 5.1, everything works as expected. 

But, when I switch to my own SessionServiceProvider, 

```php
<?php

namespace App\Providers;

use App\Http\Middleware\StartSession;
//use Illuminate\Session\Middleware\StartSession;
use Illuminate\Session\SessionServiceProvider as IlluminateSessionServiceProvider;

class SessionServiceProvider extends IlluminateSessionServiceProvider
{
    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        $this->registerSessionManager();

        $this->registerSessionDriver();

        $this->app->singleton(StartSession::class);
    }
}
```
with a start session just extends the default start session class;

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Session\Middleware\StartSession as IlluminateStartSession;

class StartSession extends IlluminateStartSession
{
    //
}

```

tests start to fail because The redis keys are not set as expected. 
However if I test the code manually using my rest client(or a version of codeception earlier than 2.1.4), I can see the keys and values using ```Redis::keys("*")``` and tests are all ```[OK]```.

**Comment by janhenkgerritsen** [comment]
Why are you changing the Session ID with these two lines of code?

```
$httpHeaderAuthorization = $request->headers->get("token");

$session->setId($httpHeaderAuthorization);
```

And I don't get why you extend the `StartSession` middleware class and then replace the body of the overriden methods with the code of the parent's class, instead of just calling `parent::METHOD`. Now some of your code is out of sync with the actual code in the parent class. For example, you are missing some code from the `addCookieToResponse` method.

Even more, I don't get why you should even extend the `StartSession` middleware class, instead of just adding a new middleware of your own that does what you want to achieve.

Maybe I am missing what you are trying to do, so maybe you should explain what you are trying to achieve.

**Comment by erdemkeren** [comment]
I am not changing the session id. I am setting it with the incoming request. It is "start session".

And I am also not missing the ```addCookieToResponse``` method. I am bypassing it.

We are using Laravel as an API and using the headers to share token instead of cookies with the front end application. Front-end application always come with the token header insead of the cookie. 

That is why, when I write tests I say:
```php
$this->haveHttpHeader("token", $token);
```

The only problem is that; when I update from 2.1.3 to newer versions (both prod. code and the new project i built) tests doesn't work.

The prod code works as expected. I can use postman too. However when I use codeception, I can't make it work.

Why don't we create a brand new middleware:

Because we want the exact same session functionality but not using cookies. We want it to work with http headers. The peace of code you see only removes cookie related stuff and instead uses headers. That is all.

**Comment by janhenkgerritsen** [comment]
Ok, thanks for explaining. 

Can you share the project you created to reproduce the problem?

**Comment by erdemkeren** [comment]
Here: https://github.com/erdemkeren/cepttest

**Comment by janhenkgerritsen** [comment]
In your test project you are still using the Laravel StartSession middleware, see [this line](https://github.com/erdemkeren/cepttest/blob/master/app/Http/Kernel.php#L18). If I change that to the correct class the problem seems to be fixed.

I don't know the reason why it worked with older versions of Codeception, but it should not have worked in those versions either :)

Let me know if this indeed fixes your problem.

**Comment by erdemkeren** [comment]
Thanks for being interested. That really made the test project work as expected. However that mistake was special to the project I created for debugging. I am sorry, the same behaviour made me think that I catch it. 

I will be digging more to reproduce the exact same circumstances. And will let you know shortly. Again sorry for occupying you for a false positive.

**Comment by erdemkeren** [comment]
Hello again, I am still debugging (the original code).

Here are the steps followed by the flow after second request. With logs from the functions.

\Illuminate\Session\Store:
```php
    public function isValidId($id)
    {
        return is_string($id) && preg_match('/^[a-f0-9]{40}$/', $id);
    }
```

[2016-03-03 15:35:44] local.INFO: the id: (for token 4e19e330beeb7a51a1604405ce9eda550f15acf1) we return true

---


```php
    public function setId($id)
    {
        if (! $this->isValidId($id)) {
            $id = $this->generateSessionId();
        }

        if($this->isValidId($id)) \Log::info('Set!');

        $this->id = $id;
    }
```
[2016-03-03 15:35:44] local.INFO: Set!  

---

\Illuminate\Auth\EloquentUserProvider:
```php
    public function __construct(HasherContract $hasher, $model)
    {
        $this->model = $model;
        \Log::info("The model for the eloquent user provider is: " . $model);
        $this->hasher = $hasher;
    }
```
[2016-03-03 15:35:44] local.INFO: The model for the eloquent user provider is: App\User  

---

\App\Http\Middleware\Authenticate:
```php
public function handle($request, Closure $next)
    {
        \Log::info("Auth check in action.");
        if (! $this->auth->check()) {...}

        return $next($request);
    }
```
[2016-03-03 15:35:44] local.INFO: Auth check in action.  

---

\Illuminate\Auth\Guard:

[2016-03-03 15:35:44] local.INFO: Guard is looking for login_aacefdcae949a4f77a201267c3f6a043 -> 77  
[2016-03-03 15:35:44] local.INFO: Guard is looking for 77 using Illuminate\Auth\EloquentUserProvider

---

Illuminate\Auth\EloquentUserProvider:  
[2016-03-03 15:35:44] local.INFO: All users are:  
[2016-03-03 15:35:44] local.INFO: a:0:{}  
[2016-03-03 15:35:44] local.INFO: If I try to get the users with DB Facade, all users are: a:0:{}  
[2016-03-03 15:35:44] local.INFO: And the result $user is: null

> The cleanup configuration only affects the database, nothing else.
> 
> Can you post your suite config and an example of a test case for which this problem occurs?

> For example, do you use database transactions in the code under test?

You were right! 
It looks like the user is not in the database when I send the second request. 
And again; you were right: 
The user registrar service which I use to spawn the users is using transactions.

It must be a problem about cascading transactions in the test case.

**Comment by janhenkgerritsen** [comment]
Nested transactions can lead to all sorts of nasty problems with testing. 

Instead of using the cleanup functionality of the Laravel5 module you can try to use the populate and cleanup functionality of the [DB module](http://codeception.com/docs/modules/Db). That does not use transactions.

**Comment by erdemkeren** [comment]
Puff. Now; I tried with no transactions but still no change. 

```php
        $I->wantToTest('I get 401 if I am authenticated but not authorised.');

        // Given
        if(! $I->haveRecord("users", ["name" => "zombie"]))
        $zombieId = $I->haveRecord('users', [
            "name"          => "zombie",
            "email"         => "zombie@dummy.data",
            "created_at"    => \Carbon\Carbon::now(),
            "updated_at"    => \Carbon\Carbon::now(),
        ]);

        $params = [
            "name"     => "zombie",
            "password" => "zombie",
        ];

        $I->haveHttpHeader("Accept", "application/json");
        $I->sendPOST("/auth/login", $params);
        $accessToken = $I->grabDataFromResponseByJsonPath("token");

        // When
        $I->haveHttpHeader("X-Authorization", $accessToken[0]);
        $I->sendGET($this->createEndpoint);

        // Then
        $I->seeResponseCodeIs(403);
    }
```
 Step I see response code is 403
 Fail  Failed asserting that 401 matches expected 403.

(Btw; If it is ok with you, I want to cleanup here a little bit)

**Comment by janhenkgerritsen** [comment]
Yeah cleanup if you want to.

I still think the best course of action is to try to reproduce the problem in a new project with as little code as possible, because I think that is the best way to gain insight into what actually is going wrong.

I cannot really help you any further for now, because I don't know what your application code exactly does.

**Comment by erdemkeren** [comment]
Hello! I am very happy because at last; I am pretty sure that one of our new dependencies (which also made us 'composer update' to get the latest version of Codeception too) is the reason of this issue.

``` "jacquestvanzuydam/laravel-firebird": "dev-5.1-support"  ```

At the service provider \Firebird\FirebirdServiceProvider::class, lines (42:46), is the source of this bug.

```php
    // The database manager is used to resolve various connections, since multiple
    // connections might be managed. It also implements the connection resolver
    // interface which may be used by other components requiring connections.
    $this->app->singleton('db', function($app)
    {
      return new FirebirdDatabaseManager($app, $app['db.factory']);
    });
```

If my version of Codeception is greater than 2.1.3 and I have this package; the same 	un-solicited status is produced. I have already updated the cepttest project too (if you want to check it out)

**Comment by janhenkgerritsen** [comment]
Well, that's a package that is still under development. Even the author states the following on it's Github page:

> This package is still in it's infancy and I wouldn't yet recommend using it for large projects, or without backing up your database regularly.

And the last update is 8 months ago.

I am sorry but I am not going to look further into this issue knowing this. I hope you can find the source of your problems yourself.

**Comment by erdemkeren** [comment]
Ok. Thanks again for the help. I have noticed that and will try to talk to team instead of following the source of the problem.
