### ISSUE TITLE
Doctrine 2 and unit of work

### ISSUE THREAD

**Issue by VincentClair** [Codeception/Codeception#2853]
Hi,
I have a problem with unit of work of Doctrine2 / Symfony3 plugins.

Here is an example of a test that does not work:

``` php
$I->wantTo('remove "permission" action from ROLE_ADMIN');

$adminRoleId = $this->getRoleIdByKey($I, 'ROLE_ADMIN');
$permissionActionId = $this->getPermissionActionId($I, 'permission');

$I->sendDELETE('/roles/' . $adminRoleId . '/permissions/' . $permissionActionId);
$I->seeResponseCodeIs(400);
$I->seeResponseEquals('"permission-action-mandatory"');

// We could not verify that permission is not removed, because Symfony plugin of codeception does not create
// another real request. Requests are simulated with one Symfony instance, so the service of doctrine keep the
// same unit of work: objects are not refreshed between requests. If we made a modification on a object in one
// request, next requests get the same modified object.
$I->sendGET('/roles/' . $adminRoleId . '/permissions');
$I->seeResponseCodeIs(200);
$I->seeResponseContainsJson(['id' => $permissionActionId]);
```

I want to check that an entity could not be deleted. After I made the action and validated that DELETE is refused, I want to check that entity ever existed. But when I get the list, I don't found the NOT DELETED entity.

I suppose that this is is due to two calls to get entities with a relation between entities managed. It is the same unit of work of Doctrine, so a change of an entity is kept during all requests in one test. Is there a way to reset unit of work ?

**Comment by DavertMik** [comment]
@raistlin ping

**Comment by VincentClair** [comment]
Any news please ?

**Comment by raistlin** [comment]
I don't see the problem, and I don't think that not creating a full request is the source of this issue.
Could you verify that if you get the list before this test is run, do you see the NOT DELETED entity?

**Comment by VincentClair** [comment]
I will try to explain better what i feel where the problem comes from. If i well understand the actual process, here are the steps of a Codeception test:
- Initialize modules Doctrine...
- Begin a transaction (to no commit changes from test)
- Run the test. In my example:
    - method `getPermissionActionId` send a request $I->sendGET('/roles/' . $adminRoleId . '/permissions'); to get all permissions for a given role.
    - Doctrine get the role( and his permissions) and put it in the Unit of Work (UoW) - something similar as a cache (Please read http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#synchronization-with-the-database)
    - we get back permissions from requests.
    - then send a request to delete a permission.
    - Doctrine get it and remove it from the role entity in unit of work. As the symfony app is still the same in a test, Doctrine already has the entity in UoW, so it modifies it directly (then flush it, etc.). He try to commit, but get an error and application send a 400 error code. Modified entity stay in UoW.
    - finally, we send a request to check that deletion don't happen with sending a new request to get permissions.
    - Doctrine try to get role entity, but as the UoW is still the same, it get the modified entity with removed permission.
    - test failed
- Rollback the transaction to keep database clean.

All works well in production, as all requests are totally independant, but the test doesn't succeeded as expected.

I see 2 possible points:
- Codeception need to "reset" the UoW between each request ;
- I need to refresh or invalidate the entity in UoW. What is the better place: in the domain service, in the controller, etc. ?

**Comment by VincentClair** [comment]
Ok, as soon as an entity becomes invalid, i think i must detach it from UoW.
`$em->detach($entity);`
It resolve my test

**Comment by raistlin** [comment]
Ok, I see what you mean.

**Comment by raistlin** [comment]
Symfony module has received a nice refactor, @VincentClair could you check if you still have problems?

**Comment by raistlin** [comment]
Please reopen as needed.

**Comment by douglasjam** [comment]
The problem still happens with Codeception 3,  Symfony 4.2 and Doctrine ODM 3.5
