### ISSUE TITLE
[Question] Test Boostrap modals with PhantomJs

### ISSUE THREAD

**Issue by MathieuNls** [Codeception/Codeception#2854]
Hi,

I'm getting started with codeception and phantomjs for acceptance tests. 

Here's my `acceptance.suite.yml`

    class_name: AcceptanceTester
    modules:
        enabled:
            - WebDriver:
                url: http://localhost/
                browser: firefox
                window_size: 1280x1024
                wait: 2s
            - \Helper\Acceptance

And my acceptance test 

    $I = new AcceptanceTester($scenario);
    $I->wantTo('Check that something');
    $I->amOnPage('/');
    $I->click('element that opens a bootstrap modal');
    $I->see("Something on the modal");

I've a phantomjs server started with `./phantomjs --webdriver=4444` and I launch my tests with `php codecept.phar run acceptance`.

However, the test fails with 

     Step  I see "Something on the modal"
     Fail  Failed asserting that   /
    [...]
    --> contains "Something on the modal".

while the screenshot in the `_output` directory shows the modal and `"Something on the modal"`.

Am I doing something wrong?

PS: Here's a [stackoverflow link](http://stackoverflow.com/questions/35582982/test-boostrap-modals-with-codeception-and-phantomjs) if you want to close this *issue* and respond there.

**Comment by DavertMik** [comment]
Some suggestions:

1. don't use phantomjs :)
2. if you use it, please specify 'phantomjs' in config as `browser` so module knew it is not a selenium
3. probably the case is that your modal (it is JS popup, right?) was not rendered in time. So you should put `waitForElement('#modal')` before checking for it

**Comment by DavertMik** [comment]
This issue was moved to http://phptest.club/t/question-test-boostrap-modals-with-phantomjs/1228
