### ISSUE TITLE
Without xdebug "run" command does not print file in which an acceptance step is executed

### ISSUE THREAD

**Issue by sustmi** [Codeception/Codeception#2857]
When I do not have Xdebug extension enabled I cannot see in which file was a step of acceptance test that failed.

Example of output with Xdebug (some strings replaced with placeholders):

```
1) Failed to XXX in YYY (ZZZ.php)
...
Scenario Steps:

 11. $I->seeInFieldByElement("Facebook\WebDriver\Remote\RemoteWebElement",7) at XXX.php:16
 10. $I->amOnPage("XXX") at YYY.php:27
...
```

Without Xdebug extension enabled, I see only:

```
1) Failed to XXX in YYY (ZZZ.php)
...
Scenario Steps:

 11. $I->seeInFieldByElement("Facebook\WebDriver\Remote\RemoteWebElement",7)
 10. $I->amOnPage("XXX")
...
```

The `at XXX.php:123` part is missing.

Is there any reason why do you not use `debug_backtrace()` instead of Xdebug?

Sidenote: I do not need to capture coverage and I have Xdebug disabled for performance reasons.

**Comment by Naktibalda** [comment]
I don't think that it was a bug of Codeception.
Codeception doesn't print location of the step if `file` key in result of [debug_backtrace()](https://www.php.net/debug_backtrace) is missing or empty.
