### ISSUE TITLE
Hooks documentation in 2.2 

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2860]
I've tried to use master branch and discovered a backwards compatibility break:
```
 Argument 1 passed to Codeception\Module\XXXXX::_before() must be an instance of Codeception\TestCase, instance of Codeception\Test\Cept given, called in .../vendor/codeception/codeception/src/Codeception/Subscriber/Module.php on line 58 and defined
```
Please update Hooks documentation and document this BC break.
http://codeception.com/docs/06-ReusingTestCode#Hooks

**Comment by Naktibalda** [comment]
Related issue:

I've used this helper to test exceptions in Cept files:
```
class ExpectedHelper extends \Codeception\Module
{
    protected $test;

    function _before(\Codeception\TestCase $test) {
        $this->test = $test;
    }

    function setExpectedException($exceptionName, $exceptionMessage = '')
    {
        $this->test->setExpectedException($exceptionName, $exceptionMessage);
    }
}
```

After changing `\Codeception\TestCase` to `\Codeception\Test\Test` it fails with:
` Fatal error:  Call to undefined method Codeception\Test\Cept::setExpectedException() in ExpectedHelper.php on line 14`

**Comment by DavertMik** [comment]
I think this can be added as alias to `shim.php`

**Comment by DavertMik** [comment]
> Related issue:

Actually, not. To solve the problem we need a standard way of handling exceptions in tests.

**Comment by Naktibalda** [comment]
@DavertMik This is the main backwards compatibility break for 2.2 and it will probably cause more issues than changing format of configuration in 2.1.

PHPUnit_Framework_TestCase has a number of utility methods, Codeception\TestCase and PHPUnit_Framework_Test have none.

Do you remember what was the original reason for passing the instance of test to the hook?
I have never seen one (other than that ExpectException helper). Maybe it s time to document and give so..
