### ISSUE TITLE
ZF1 not keeping session between scenario steps

### ISSUE THREAD

**Issue by gilacost** [Codeception/Codeception#2862]
I've tried to the same approach that I usually use with laravel module.
This is the test:
![captura de pantalla 2016-03-01 a las 18 12 14](https://cloud.githubusercontent.com/assets/6720169/13435170/43dba46e-dfd9-11e5-861a-7090391bb1b6.png)
This is the sign in function in the Functional Helper:
![captura de pantalla 2016-03-01 a las 18 13 56](https://cloud.githubusercontent.com/assets/6720169/13435194/630edbd0-dfd9-11e5-9f71-3fbf67049e7d.png)
I'm forced to return ZF1 module... I don't know if this is an issue... 
Cheers!

**Comment by Naktibalda** [comment]
Please check if conflicting module (most likely PhpBrowser) is enabled in configuration file of your suite.

**Comment by gilacost** [comment]
Solved.
