### ISSUE TITLE
Running more that one test Throws Registry is already initialized Exception

### ISSUE THREAD

**Issue by gilacost** [Codeception/Codeception#2863]
![captura de pantalla 2016-03-01 a las 18 23 42](https://cloud.githubusercontent.com/assets/6720169/13435468/ce8de6ac-dfda-11e5-9be3-ecb01835c21f.png)

**Comment by Naktibalda** [comment]
Please run Codeception with `-vvv` flag to get a stacktrace.
`codecept run -vvv`

**Comment by gilacost** [comment]
Exception trace:
 () at /var/www/admin/current/vendor/bombayworks/zendframework1/library/Zend/Registry.php:70
 Zend_Registry::setInstance() at /var/www/admin/current/application/Bootstrap.php:9
 Bootstrap->_initRegistry() at /var/www/admin/current/vendor/bombayworks/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php:681
 Zend_Application_Bootstrap_BootstrapAbstract->_executeResource() at /var/www/admin/current/vendor/bombayworks/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php:634
 Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap() at /var/www/admin/current/vendor/bombayworks/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php:598
 Zend_Application_Bootstrap_BootstrapAbstract->bootstrap() at /var/www/admin/current/vendor/bombayworks/zendframework1/library/Zend/Application.php:373
 Zend_Application->bootstrap() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/Module/ZF1.php:131
 Codeception\Module\ZF1->_before() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:58
 Codeception\Subscriber\Module->before() at n/a:n/a
 call_user_func() at /var/www/admin/current/vendor/symfony/event-dispatcher/EventDispatcher.php:171
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /var/www/admin/current/vendor/symfony/event-dispatcher/EventDispatcher.php:43
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:121
 Codeception\PHPUnit\Listener->fire() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:92
 Codeception\PHPUnit\Listener->startTest() at /var/www/admin/current/vendor/phpunit/phpunit/src/Framework/TestResult.php:327
 PHPUnit_Framework_TestResult->startTest() at /var/www/admin/current/vendor/phpunit/phpunit/src/Framework/TestResult.php:552
 PHPUnit_Framework_TestResult->run() at /var/www/admin/current/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
 PHPUnit_Framework_TestCase->run() at /var/www/admin/current/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
 PHPUnit_Framework_TestSuite->run() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:89
 Codeception\PHPUnit\Runner->doEnhancedRun() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/SuiteManager.php:153
 Codeception\SuiteManager->run() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/Codecept.php:203
 Codeception\Codecept->runSuite() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/Codecept.php:172
 Codeception\Codecept->run() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/Command/Run.php:262
 Codeception\Command\Run->runSuites() at /var/www/admin/current/vendor/codeception/codeception/src/Codeception/Command/Run.php:189
 Codeception\Command\Run->execute() at /var/www/admin/current/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /var/www/admin/current/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at /var/www/admin/current/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /var/www/admin/current/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/admin/current/vendor/codeception/codeception/codecept:28

**Comment by Naktibalda** [comment]
If you want a quick solution, call `Zend_Registry::_unsetInstance()` before Zend_Registry::setInstance() in /var/www/admin/current/application/Bootstrap.php

**Comment by Naktibalda** [comment]
I [reproduced](https://github.com/Naktibalda/codeception-zf1-tests/commit/c8341bbbec15cf753b598097168b36450b82f931) and fixed this issue.

**Comment by Naktibalda** [comment]
Merged to 2.1 branch.
