### ISSUE TITLE
REST module is breaking json response.

### ISSUE THREAD

**Issue by cloudEdwards** [Codeception/Codeception#2871]
I am testing my API with the REST module with PHP browser in acceptance testing. Most of the time, these tests are passing. But recently, they stopped passing for me locally, ands continued working in circel ci.
But now, every once is a while, after I push some code, they break again.
The code I push has nothing to do with API's or their tests.
The way the problem manifests is the json object gets broken because in items containing html code, all the opening tags are gone, and this is making the json invalid.
The API them selves are working fine, and spit out valid json when I test it manually, this just happens when running tests.
I just verified that this is also happening on my coworkers machine.

Here is a sample broken json response.
It is valid in the beginning, but breaks right at "price_details".
you can see the opening `<span>` is removed, and all the opening `<li>` are gone as well. The rest of the response is equally broken.
When I test this manually, the json is valid. 
Code examples in next comment

any suggestions or ideas are much appreciated.
Thanks
Cloud

**Comment by cloudEdwards** [comment]
Invalid json response 
`{"ID":31,"authors":["1"],"title":"Exhaustive program","slug":"exhaustive-program","text":"","text_full":"","text_plain":"","location":"Nelson","excerpt":"","address":"444 Baker St","website":"http:\/\/connect.programs.dev?programs=1&program=31","alternate_url":"","phone":"1-234-5678","email":"test@retreat.guru","start":1465516800,"end":1466121600,"price_type":"tiered","prices":"$100.00 - Program Price","teachers":["http:\/\/programs.dev\/teacher\/yogi-bear-test\/","http:\/\/programs.dev\/teacher\/kumare-test\/"],"photo":false,"photo_details":false,"source_url":"http:\/\/programs.dev\/program\/exhaustive-program\/","price_details":"Price<\/span>
$100.00 – Program Price<\/li><\/ul>","price_first":"$100.00","contact":"Program Contact: <\/span>Contact details test.
Email:<\/span> test@retreat.guru<\/a>.
Phone:<\/span> 1-234-5678.","message":"","teacher_details":{"teacher_list":"With Yogi Bear Test and Kumare Test","teacher_objects":[{"ID":2,"post_author":"1","post_date":"2016-03-02 20:25:12","post_date_gmt":"2016-03-02 20:25:12","post_content":"A yogi is a practitioner of yoga. The term yogi is also used to refer specifically to Siddhas, and broadly to refer to ascetic practitioners of meditation in a number of Indian religions including Hinduism, Buddhism, and Jainism.","post_title":"Yogi Bear Test","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"yogi-bear-test","to_ping":"","pinged":"","post_modified":"2016-03-02 20:25:12","post_modified_gmt":"2016-03-02 20:25:12","post_content_filtered":"","post_parent":0,"guid":"http:\/\/programs.dev\/teacher\/yogi-bear-test\/","menu_order":0,"post_type":"teacher","post_mime_type":"","comment_count":"0","filter":"raw","photo_details":false,"slug":"yogi-bear-test","name":"Yogi Bear Test","text_full":"A yogi is a practitioner of yoga. The term yogi is also used to refer specifically to Siddhas, and broadly to refer to ascetic practitioners of meditation in a number of Indian religions including Hinduism, Buddhism, and Jainism."},{"ID":3,"post_author":"1","post_date":"2016-03-02 20:25:12","post_date_gmt":"2016-03-02 20:25:12","post_content":"Test description","post_title":"Kumare Test","post_excerpt":"","post_status":"publish","comment_status":"closed","ping_status":"closed","post_password":"","post_name":"kumare-test","to_ping":"","pinged":"","post_modified":"2016-03-02 20:25:12","post_modified_gmt":"2016-03-02 20:25:12","post_content_filtered":"","post_parent":0,"guid":"http:\/\/programs.dev\/teacher\/kumare-test\/","menu_order":0,"post_type":"teacher","post_mime_type":"","comment_count":"0","filter":"raw","photo_details":false,"slug":"kumare-test","name":"Kumare Test","text_full":"Test description"}]},"date":"June 10 - 17, 2016","registration_action":"
Register now<\/a><\/div>","registration_link":"http:\/\/programs.dev\/program\/exhaustive-program\/?form=1","registration_status":"open","registration_spaces_available":null,"registration_spaces_available_words":null,"registration_bookable":true,"registration_wait_list":false,"date_time":"Some date details","custom":"
Custom field title:<\/span> Custom field value<\/span><\/p>","custom_fields":[{"title":"Custom field title","value":"Custom field value"}],"additional_info":"","categories":[],"meta":{"links":{"self":"http:\/\/programs.dev\/wp-json\/events\/31","collection":"http:\/\/programs.dev\/wp-json\/events"}}}`

**Comment by cloudEdwards** [comment]
Expected json response
`{
"ID": 31,
"authors": [
"1"
],
"title": "Exhaustive program",
"slug": "exhaustive-program",
"text": "",
"text_full": "",
"text_plain": "",
"location": "Nelson",
"excerpt": "",
"address": "444 Baker St",
"website": "http://programs-remote.dev?programs=1&program=31",
"alternate_url": "",
"phone": "1-234-5678",
"email": "test@retreat.guru",
"start": 1465516800,
"end": 1466121600,
"price_type": "tiered",
"prices": "$100.00 - Program Price",
"teachers": [
"http://tests.programs.dev/teacher/yogi-bear-test/",
"http://tests.programs.dev/teacher/kumare-test/"
],
"photo": false,
"photo_details": false,
"source_url": "http://tests.programs.dev/program/exhaustive-program/",
"price_details": "<span class=\"rs-program-label\">Price</span><ul><li>$100.00 &ndash; Program Price</li></ul>",
"price_first": "$100.00",
"contact": "<span class=\"rs-program-label\">Program Contact: </span>Contact details test.<br /> <span class=\"rs-program-label\">Email:</span> <a href=\"mailto:test@retreat.guru\">test@retreat.guru</a>.<br /> <span class=\"rs-program-label\">Phone:</span> 1-234-5678.",
"message": "",
"teacher_details": {
"teacher_list": "With Yogi Bear Test and Kumare Test",
"teacher_objects": [
{
"ID": 2,
"post_author": "1",
"post_date": "2016-03-02 19:36:29",
"post_date_gmt": "2016-03-02 19:36:29",
"post_content": "A yogi is a practitioner of yoga. The term yogi is also used to refer specifically to Siddhas, and broadly to refer to ascetic practitioners of meditation in a number of Indian religions including Hinduism, Buddhism, and Jainism.",
"post_title": "Yogi Bear Test",
"post_excerpt": "",
"post_status": "publish",
"comment_status": "closed",
"ping_status": "closed",
"post_password": "",
"post_name": "yogi-bear-test",
"to_ping": "",
"pinged": "",
"post_modified": "2016-03-02 19:36:29",
"post_modified_gmt": "2016-03-02 19:36:29",
"post_content_filtered": "",
"post_parent": 0,
"guid": "http://tests.programs.dev/teacher/yogi-bear-test/",
"menu_order": 0,
"post_type": "teacher",
"post_mime_type": "",
"comment_count": "0",
"filter": "raw",
"photo_details": false,
"slug": "yogi-bear-test",
"name": "Yogi Bear Test",
"text_full": "A yogi is a practitioner of yoga. The term yogi is also used to refer specifically to Siddhas, and broadly to refer to ascetic practitioners of meditation in a number of Indian religions including Hinduism, Buddhism, and Jainism."
},
{
"ID": 3,
"post_author": "1",
"post_date": "2016-03-02 19:36:29",
"post_date_gmt": "2016-03-02 19:36:29",
"post_content": "Test description",
"post_title": "Kumare Test",
"post_excerpt": "",
"post_status": "publish",
"comment_status": "closed",
"ping_status": "closed",
"post_password": "",
"post_name": "kumare-test",
"to_ping": "",
"pinged": "",
"post_modified": "2016-03-02 19:36:29",
"post_modified_gmt": "2016-03-02 19:36:29",
"post_content_filtered": "",
"post_parent": 0,
"guid": "http://tests.programs.dev/teacher/kumare-test/",
"menu_order": 0,
"post_type": "teacher",
"post_mime_type": "",
"comment_count": "0",
"filter": "raw",
"photo_details": false,
"slug": "kumare-test",
"name": "Kumare Test",
"text_full": "Test description"
}
]
},
"date": "June 10 - 17, 2016",
"registration_action": "<div class=\"rs-registration-open rs-register-link\"><a href=\"http://tests.programs.dev/program/exhaustive-program/?form=1\">Register now</a></div>",
"registration_link": "http://tests.programs.dev/program/exhaustive-program/?form=1",
"registration_status": "open",
"registration_spaces_available": null,
"registration_spaces_available_words": null,
"registration_bookable": true,
"registration_wait_list": false,
"date_time": "Some date details",
"custom": "<p class=\"program-custom\"><span class=\"rs-program-label\">Custom field title:</span> <span>Custom field value</span></p>",
"custom_fields": [
{
"title": "Custom field title",
"value": "Custom field value"
}
],
"additional_info": "<p>Footer for the program page</p>",
"categories": [],
"meta": {
"links": {
"self": "http://tests.programs.dev/wp-json/events/31",
"collection": "http://tests.programs.dev/wp-json/events"
}
}
}`

**Comment by Naktibalda** [comment]
You haven't provided enough information to identify the issue.

Please provide your test code and configuration.
Relevant application code could be useful too.

Have you tried to run your tests with different versions of Codeception?

**Comment by cloudEdwards** [comment]
Hey
Here is the api suite file
`class_name: ApiTester
modules:
    enabled: [PhpBrowser, REST, ApiHelper]
    config:
      PhpBrowser:
          url: http://programs.dev/

# These configurations are needed for codecption 2.1
      REST:
          url: http://programs.dev/wp-json
          depends: PhpBrowser`

**Comment by cloudEdwards** [comment]
here is the test code 
```
<?php
use \ApiTester;

class ProgramsApiCest
{

    private function validateProgramObjects(ApiTester $I)
    {
        $I->seeResponseJsonMatchesXpath('//ID');
        $I->seeResponseJsonMatchesXpath('//authors');
        $I->seeResponseJsonMatchesXpath('//title');
        $I->seeResponseJsonMatchesXpath('//slug');
        $I->seeResponseJsonMatchesXpath('//text');
        $I->seeResponseJsonMatchesXpath('//text_full');
        $I->seeResponseJsonMatchesXpath('//website');
        $I->seeResponseJsonMatchesXpath('//phone');
        $I->seeResponseJsonMatchesXpath('//email');
        $I->seeResponseJsonMatchesXpath('//start');
        $I->seeResponseJsonMatchesXpath('//end');
        $I->seeResponseJsonMatchesXpath('//price_type');
        $I->seeResponseJsonMatchesXpath('//prices');
        $I->seeResponseJsonMatchesXpath('//teachers'); // todo: seed teachers and associate with program to branch into this
        $I->seeResponseJsonMatchesXpath('//photo');
        $I->seeResponseJsonMatchesXpath('//photo_details'); // todo: seed program with photo to branch into this
        $I->seeResponseJsonMatchesXpath('//source_url');
        $I->seeResponseJsonMatchesXpath('//price_details');
        $I->seeResponseJsonMatchesXpath('//location');
        $I->seeResponseJsonMatchesXpath('//contact');
        $I->seeResponseJsonMatchesXpath('//message');
        $I->seeResponseJsonMatchesXpath('//teacher_details');
        $I->seeResponseJsonMatchesXpath('//teacher_details//teacher_list');
        $I->seeResponseJsonMatchesXpath('//teacher_details//teacher_objects');
        $I->seeResponseJsonMatchesXpath('//date');
        $I->seeResponseJsonMatchesXpath('//registration_action');
        $I->seeResponseJsonMatchesXpath('//registration_link');
        $I->seeResponseJsonMatchesXpath('//registration_status');
        $I->seeResponseJsonMatchesXpath('//registration_spaces_available');
        $I->seeResponseJsonMatchesXpath('//date_time');
        $I->seeResponseJsonMatchesXpath('//custom');
        $I->seeResponseJsonMatchesXpath('//additional_info');
    }

    private function validateSingleProgramObjectValues(ApiTester $I)
    {
        $id = $I->grabDataFromResponseByJsonPath('$..ID');
        if ($id[0] != '31'){
            $I->see("JSON response ID is not 31");
        }
        $title = $I->grabDataFromResponseByJsonPath('$..title');
        if ($title[0] != 'Exhaustive program'){
            $I->see("JSON response title is not Exhaustive program");
        }
        $teacher = $I->grabDataFromResponseByJsonPath('$..teachers');
        if ($teacher[0][0] != 'http://programs.dev/teacher/yogi-bear-test/'){
            $I->see("JSON response title is not http://programs.dev/teacher/yogi-bear-test/");
        }
    }

    private function validateProgramObjectValues(ApiTester $I)
    {
        $id = $I->grabDataFromResponseByJsonPath('$..[0]ID');
        if ($id[0] != '43'){
            $I->see("JSON response ID is not 43");
        }
        $title = $I->grabDataFromResponseByJsonPath('$..[0]title');
        if ($title[0] != 'Multi Person Hotel Lodging'){
            $I->see("JSON response title is not Multi Person Hotel Lodging Program");
        }
    }

    /* Test json structure */
    public function validateProgramsList(ApiTester $I)
    {
        $I->wantTo('Validate program response from API');
        $I->sendGET('/events?'.rand());

        $this->validateProgramObjects($I);
        $this->validateProgramObjectValues($I);
    }

    /* test json structure */
    public function validateSingleProgram(ApiTester $I)
    {
        $I->wantTo('Validate program response from API');
        $I->sendGET('/events/31?'.rand());
        $this->validateProgramObjects($I);
        $this->validateSingleProgramObjectValues($I);
    }

    public function validateTeachers(ApiTester $I)
    {
        $I->wantTo('Validate teachers response from API');
        $I->sendGET('/teachers/2?'.rand());


        $I->seeResponseJsonMatchesXpath('//ID');
        $I->seeResponseJsonMatchesXpath('//name');
        $I->seeResponseJsonMatchesXpath('//slug');
        $I->seeResponseJsonMatchesXpath('//text');
        $I->seeResponseJsonMatchesXpath('//text_full');
        $I->seeResponseJsonMatchesXpath('//photo');
        $I->seeResponseJsonMatchesXpath('//photo_details');
        $I->seeResponseJsonMatchesXpath('//source_url');
        $I->seeResponseJsonMatchesXpath('//programs');
        $I->seeResponseJsonMatchesXpath('//meta');
        $I->seeResponseJsonMatchesXpath('//meta/links');
        $I->seeResponseJsonMatchesXpath('//meta/links/self');
        $I->seeResponseJsonMatchesXpath('//meta/links/collection');
        $I->seeResponseJsonMatchesXpath('//programs/ID');
        $I->seeResponseJsonMatchesXpath('//programs/post_title');
        $I->seeResponseJsonMatchesXpath('//programs/guid');

        $id = $I->grabDataFromResponseByJsonPath('$..ID');
        if ($id[0] != '2'){
            $I->see("JSON response ID is not 2");
        }
        $title = $I->grabDataFromResponseByJsonPath('$..name');
        if ($title[0] != 'Yogi Bear Test'){
            $I->see("JSON response name is not Yogi Bear Test");
        }
        $text = $I->grabDataFromResponseByJsonPath('$..text');
        if ($text[0] != 'A yogi is a practitioner of yoga. The term yogi is also used to refer specifically to Siddhas, and broadly to refer to ascetic practitioners of meditation in a number of Indian religions including Hinduism, Buddhism, and Jainism.'){
            $I->see("JSON response text is not what it should be");
        }
        $program_id = $I->grabDataFromResponseByJsonPath('$..programs[0].ID');
        if ($program_id[0] != '28'){
            $I->see('JSON response ID is not 28');
        }

    }

    public function validateCategory(ApiTester $I)
    {
        $I->sendGET('/events?category=plant-medicine');
        $I->seeResponseJsonMatchesJsonPath('$.[0].ID');
        $I->seeResponseJsonMatchesJsonPath('$.[0].title');
        $I->seeResponseJsonMatchesJsonPath('$.[0].slug');
        $I->seeResponseJsonMatchesJsonPath('$.[0].text');
        $I->seeResponseJsonMatchesJsonPath('$.[0].website');
        $I->seeResponseJsonMatchesJsonPath('$.[0].start');
        $I->seeResponseJsonMatchesJsonPath('$.[0].teachers');
        $I->seeResponseJsonMatchesJsonPath('$.[0].source_url');
        $I->seeResponseJsonMatchesJsonPath('$.[0].teacher_details');
        $I->seeResponseJsonMatchesJsonPath('$.[0].date');
        $I->seeResponseJsonMatchesJsonPath('$.[0].registration_status');
        $I->seeResponseJsonMatchesJsonPath('$.[0].categories');
    }

}
```

**Comment by cloudEdwards** [comment]
I haven't tried it in different versions yet. I'll do that as soon as I can

**Comment by DavertMik** [comment]
> The problem is in v 2.0.12
> I just tried it in v 2.1.6, and the api tests worked. 

So can I assume that this issue was fixed in newer version?
