### ISSUE TITLE
Guides - CSS for code

### ISSUE THREAD

**Issue by slowkow** [Codeception/Codeception#2878]
Could I ask you to please fix the CSS on the documentation website?

Here's what the code examples look like for me (Chrome, Firefox, and Safari):

http://codeception.com/docs/03-AcceptanceTests

![03-acceptancetests_-_codeception_-_documentation](https://cloud.githubusercontent.com/assets/209714/13554729/023f18da-e37e-11e5-8154-918e263c3832.png)

To bypass this issue, I'm manually changing the CSS in my browser:

![03-acceptancetests_-_codeception_-_documentation](https://cloud.githubusercontent.com/assets/209714/13554743/6283270e-e37e-11e5-9447-a5c8762b5e35.png)

**Comment by DavertMik** [comment]
THanks, some styles broke because GitHub moved to Jekyll3 with a new markdown parser. Updated them
