### ISSUE TITLE
Code highlight issues in codeception.com

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#2880]
@DavertMik  I just noticed that some css may be broken, see:

![capture 2016-03-02 at 16 31 45](https://cloud.githubusercontent.com/assets/1375475/13606199/6a34887a-e54b-11e5-9ccd-4b9e31d112db.png)

at: http://codeception.com/docs/07-AdvancedUsage

**Comment by DavertMik** [comment]
Thanks. Fixed
