### ISSUE TITLE
PhpBrowser $I->click not sending POST

### ISSUE THREAD

**Issue by cwhsu1984** [Codeception/Codeception#2890]
I write a test for login.

```php
    public function login(AcceptanceTester $I) 
    {   
        $I->wantTo('login as regular user');
        $I->amOnPage('/tw/member/login');
        $I->seeInCurrentUrl('/member/login');
        $I->fillField('email','myname@myapp.com');
        $I->fillField('password','223344');
        $I->click('.button-primary'); // not working
        #$I->click('.submit-circle'); // not working
    }  

```
tests/acceptance.suite.yml

```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
    config:
        PhpBrowser:
            url: 'http://localhost:636'
```

Code of login page

```html
<form class="form form-login" action="/tw/member/login" method="post">
	<input class="input" type="text" name="email" placeholder="email">
	<input class="input" type="password" name="password" placeholder="password">
	<button class="submit-circle button-primary">
            <span class="icon icon-arrow-right-line"></span>
            <span class="text">login</span>
        </button>
</form>

```
codecept run tests/acceptance/BasicCest.php --debug --verbose

```
  [Response] 200
  [Request Cookies] {"my_i18n":"MRTKJfm+SuedYIFE2BO17TSGKDfxztzsNU+/GQ=="}
  [Response Headers] {"Date":["Fri, 11 Mar 2016 03:28:27 GMT"],"Content-Type":["text/html; charset=utf-8"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"Server":["lighttpd"],"Set-Cookie":["PHPSESSID=uqqnc7i8uhubhghtlme3dfldl4; expires=Fri, 18-Mar-2016 03:28:27 GMT; Max-Age=604800; path=/","my_member=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/"],"Expires":["Thu, 19 Nov 1981 08:52:00 GMT"],"Cache-Control":["no-store, no-cache, must-revalidate, post-check=0, pre-check=0"],"Pragma":["no-cache"]}
* I see in current url "/member/login"
* I fill field "email","myname@myapp.com"
* I fill field "password","223344"
* I click ".button-primary"
  [Page] http://localhost/en/member/login
  [Response] 200
  [Request Cookies] {"my_i18n":"MRTKJfm+SuedYIFE2BO17TSGKDfxztzsNU+/GQ==","PHPSESSID":"uqqnc7i8uhubhghtlme3dfldl4"}
  [Response Headers] {"Date":["Fri, 11 Mar 2016 03:28:27 GMT"],"Content-Type":["text/html; charset=utf-8"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"Server":["lighttpd"],"Expires":["Thu, 19 Nov 1981 08:52:00 GMT"],"Cache-Control":["no-store, no-cache, must-revalidate, post-check=0, pre-check=0"],"Pragma":["no-cache"],"Set-Cookie":["my_member=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/"]}
```

It should send a post request to login and get the cookie from server, but that does not happen. I could succeed by using "sendAjaxPostRequest", but that's not what I really want to do. Is there anything wrong with me code? Or a bug of PhpBrowser?

**Comment by Naktibalda** [comment]
Your test certainly makes a request (and it is a shortcoming that Codeception does not display request method, but it probably is POST).

And your test gets a cookie (deleted) in the response:
`"Set-Cookie":["my_member=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/"`

I will try to reproduce your issue in the evening, but I'm pretty sure that it is a bug of your application and not of PhpBrowser.

**Comment by Naktibalda** [comment]
Add `type=submit` attribute to your button.

```html
    <button class="submit-circle button-primary" type=submit>
            <span class="icon icon-arrow-right-line"></span>
            <span class="text">login</span>
        </button>
```

**Comment by cwhsu1984** [comment]
Thanks for you reply. I just try it myself, and I follow your suggestion to add `type=submit`
Well not working...
My code actually looks like this
```
        <button class="submit-circle button-primary" type="submit">                                                                             
            <span class="icon icon-arrow-right-line"></span>
            <span class="text"><?php echo $i18n->LOGIN; ?></span>
        </button>
```
And then I think maybe I should try something else, so I change it like this
```
        <button class="submit-circle button-primary" name="login_button">                                                                       
            <span class="icon icon-arrow-right-line"></span>
            <span class="text"><?php echo $i18n->LOGIN; ?></span>
        </button>
```
Then it works... I could see all my cookies now. So I think it is a kind of bug because the PhpBrowser should report a warning or error when it cannot find the button at `$I->click("button-primary")`.

**Comment by Naktibalda** [comment]
@DavertMik Could you remind us why is click() passing when it matches only non-clickable elements?

https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/InnerBrowser.php#L289

**Comment by edsonmedina** [comment]
@cwhsu1984 Does it work if you use xpath instead of a css selector? 

Ie, something like:

    $I->click("//button[contains(@class, 'button-primary')]");

**Comment by cwhsu1984** [comment]
@edsonmedina  sorry for late reply. I just tried your solution, and it still didn't work. It could click the button, but no request was made.

**Comment by cwhsu1984** [comment]
Hi guys,

any news?

**Comment by Naktibalda** [comment]
Have you added type=submit attribute to your button?

**Comment by cwhsu1984** [comment]
Hi guys,

`$I->click("//button[contains(@class, 'button-primary')]");` would work when the button has `type=submit`.

Thank you!
