### ISSUE TITLE
amOnPage inconsistency within Symfony2 module

### ISSUE THREAD

**Issue by blastedcoder** [Codeception/Codeception#2891]
If I run the following test

    $I->wantToTest('Test the login form is presented for oauth');
        $I->amOnPage('/oauth?client_id=qwerty&redirect_uri=http://localhost&scope=access_to_email photo&response_type=code');
        $I->see('Username');
        $I->see('Password');
        $I->fillField('#username', 'invalid');
        $I->fillField('#password', 'welcome');

When I just have the following config enabled the tests pass as expected

    modules:
    enabled:
        - Db
        - PhpBrowser:
            url: http://127.0.0.1:8001/app_test.php
        - \Helper\Acceptance

As the project is a symfony project I enabled 

            - Symfony2
    config:
        Symfony2:
            var_path: var
            app_dir: app
            environment: test
            debug: false

I have narrowed it down to fact that the $_GET parameters are being dropped by including the following at the top of my controller method

    // @todo-debug ~ added on 11 March 2016
        echo '<pre><b>', __FILE__, ' (', __LINE__, ')</b> [', __METHOD__, ']', PHP_EOL;
        print_r(array($_GET)); echo '</pre>', PHP_EOL;

Without Symfony 2 it prints out as

    Array
    (
        [0] => Array
            (
                [client_id] => qwerty
                [redirect_uri] => http://localhost
                [scope] => access_to_email photo
                [response_type] => code
            )
    )

With it prints out as

    Array
    (
        [0] => Array
            (
            )
    )

**Comment by Naktibalda** [comment]
You made a wrong assumption.

Don't use $_GET in your code.
Retrieve parameters from Request object instead:
` $request->query->get('name');`

**Comment by blastedcoder** [comment]
Within my code it is not using $_GET it does use the $request->query->get('client_id');

I added the debug to illustrate that both methods do not send the data in a consistent way.

Under the bonnet I am using http://oauth2.thephpleague.com/ which is successful in all of the following:

Browser
Remote API tools
Codeception RestApi tests using $I->sendGet
Codeception PhpBrowser tests using $i->amOnPage

It only fails when using Codeception Symfony2 $i->amOnPage as it is constantly catching InvalidClientException where it is unable to find client_id

I have just check the code that throws the exception and it uses the following:

Symfony\Component\HttpFoundation\Request::createFromGlobals

**Comment by Naktibalda** [comment]
I don't use Symfony so I am not an expert, but your code should not be doing that because Codeception is passing a populated Request object.

**Comment by blastedcoder** [comment]
Its not my code its an external component installed into my vendor directory by composer.

I can understand converting the items into a populated Request Object for testing an isolated block of code where you are expecting a populated object and do not want to go through the process of mocking it out.

However for Acceptance tests this does not mimic real world and it also removes functionality when moving from the PhpBrowser Module to Symfony2 Module instead of enhancing it.

Can a config option be added to enable it?

**Comment by Naktibalda** [comment]
I think that it is unlikely, however you can make a copy of Symfony module and Symfony2 connector to tests/_support folder, rename them and use your copy instead of official module.

If you want to give it a go, try to populate superglobals in [Connector\Symfony2:doRequest] (https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Connector/Symfony2.php#L20) method.

doRequest method is very concise for Symfony2 because it simply passes request created by Symfony/BrowserKit to Symfony/HttpKernel.

Other framework connectors have to do more mapping, for example [ZF2](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Connector/ZF2.php#L40).

**Comment by blastedcoder** [comment]
Will do, thanks for you advice.

If it does not work I will revert back to PhpBrowser
