### ISSUE TITLE
@Override annotation in /Codeception/TestCase/Test.php gives error with Doctrine

### ISSUE THREAD

**Issue by aschwin** [Codeception/Codeception#2894]
Hi,

Both _before() and _after() contain DocBlocks with the @Override annotation. At least, Doctrine thinks these are annotations.

Doctrine complains it can not find anything to include.

You might say, it is Doctrine to blame. Well, let me first ask what these annotations are for? Is there any purpose for it? I mean, what is there to override and what mechanism uses this?

Next, maybe anyone has any idea how to circumvent this error if at the Doctrine side it is not solvable?

**Comment by DavertMik** [comment]
Ok, no problem to remove them. They were added in those glory days when comments were just comments...

**Comment by DavertMik** [comment]
However, I'm just curious why Doctrine is parsing your tests...

**Comment by aschwin** [comment]
I guess Doctrine is very greedy in parsing folders for annotations. It's not that I try to test Doctrine's mechanism. I try to mock it. But I guess some parts are still bootstrapped somehow.
