### ISSUE TITLE
Helping with Codeception website

### ISSUE THREAD

**Issue by cjaoude** [Codeception/Codeception#2895]
Hi Davert

If you would repo the Codeception website, I'd be glad to assist with improving it. I've been seeing lots of CSS, responsive issues with the site. Thanks. Codeception is great.

**Comment by DavertMik** [comment]
Sure, please do it's here https://github.com/Codeception/codeception.github.com
Personally I'd like to move out from fixed-length layout, and maybe do some other changes in styles to make it look nicer. I hope you are better designer than me, so you can have your vision how to make it better

Thanks

**Comment by cjaoude** [comment]
ok, cool. will join there.
