### ISSUE TITLE
Problem with PhpBrowser and Guzzle6 connector

### ISSUE THREAD

**Issue by Samorai** [Codeception/Codeception#2896]
Hi.
I have some flow: 
```
$I->amHttpAuthenticated($user, $password);
/** Do something  Need logout. For logout I do: */
$I->amHttpAuthenticated(null, null);
/**Need bearer Authentication*/
$I->amBearerAuthenticated($token);
```
But in result I am not bearer authenticated, I am Http authenticated with null:null credentials.

Connector Guzzle6 has not method to access  protected variable `$requestOptions`;

I purpose change body of method **setAuth** to

```
if (is_null($username) && is_null($password)) {
    unset($this->requestOptions['auth']);
} else {
    $this->requestOptions['auth'] = [$username, $password];
}
```

https://github.com/Codeception/Codeception/blob/2.1.6/src/Codeception/Lib/Connector/Guzzle6.php#L81

**Comment by DavertMik** [comment]
Thanks. I think this can be simplified like:

```php
I purpose change body of method setAuth to

if (!$username) {
    unset($this->requestOptions['auth']);
    return;
}
$this->requestOptions['auth'] = [$username, $password];
```

I will include it into GuzzleConnector
