### ISSUE TITLE
PHPUnit_Runner_Version not found

### ISSUE THREAD

**Issue by iquito** [Codeception/Codeception#2901]
I tried to use Codeception in my project today for the first time, with the following commands:

```
composer require "codeception/codeception:*"
php vendor/bin/codecept bootstrap
php vendor/bin/codecept run
```

This always leads to the following error:

```
PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Runner_Version' not found in /website/vendor/codeception/codeception/src/Codeception/Command/Run.php:134
Stack trace:
#0 /website/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(256): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /website/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(791): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /website/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /website/vendor/symfony/symfony/src/Symfo in /website/vendor/codeception/codeception/src/Codeception/Command/Run.php on line 134
```

I am using Symfony 3.0.3 and PHPUnit 5.2.10 (and Codeception 2.1.7) - the newest versions which exist right now. As described I did not create any tests or configure anything yet, because Codeception is failing before actually running anything.

**Comment by Naktibalda** [comment]
Hi @iquito ,

I have tried to reproduce your issue by repeating your test and it worked without any errors.

```
codeception-test$ php vendor/bin/codecept run
Codeception PHP Testing Framework v2.1.7
Powered by PHPUnit 5.2.10 by Sebastian Bergmann and contributors.

Acceptance Tests (0) ------------------------
---------------------------------------------

Unit Tests (0) ------------------------------
---------------------------------------------

Functional Tests (0) ------------------------
---------------------------------------------


Time: 106 ms, Memory: 6.00Mb

No tests executed!
```

That error is only possible if PHPUnit is not installed.

My only advice is to try again.

**Comment by iquito** [comment]
Thanks for trying!

After looking through all composer autoload files, I found out why it is not working - PHPUnit seems to be one of the only libraries which explicitely tells composer to only include it in the autoload_classmap file (no psr-0/psr-4), and because PHPUnit is not used for production and would only eat up memory in a classmap, I added the /vendor/phpunit directory to `exclude-from-classmap` in composer.json - which works for every library I have _except_ PHPUnit, because of the strange classmap-only autoload settings.

**Comment by allen0817** [comment]
@iquito  is  "classmap" : ["/vendor/phpunit"], ?  I have this problem, too
