### ISSUE TITLE
Feature Request - allow dynamic addition of config to FTP

### ISSUE THREAD

**Issue by rossjohnson90** [Codeception/Codeception#2903]
It would be great to be able to set in config of an FTP module something like
config:
     set: false

Then rather than attempt to connect to the ftp host before starting any test case it waits for you to set the config and then establish the connection.

I would probably go ahead and do it myself and submit a PR to you guys if you think it would be good/useful?

**Comment by DavertMik** [comment]
Not sure what you are trying to achive but yes, you can set config in runtime. 

Use `$this->getModule('FTP')->_reconfigure()` to set new values in FTP config. You can do that from any Helper class

**Comment by rossjohnson90** [comment]
We want to drive our config dynamically so its not ideal to have to have a set of config in the .yml have it connect to that and then reconfigure

**Comment by DavertMik** [comment]
There is also [Params option](http://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Params) for dynamic configuration. Not sure if it helps but the issue I think can be closed
