### ISSUE TITLE
Test site for Symfony 3

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2909]
https://github.com/Codeception/symfony-demo supports Symfony 2.7 and 2.8 only.
We need to upgrade it or to create a new demo site for Symfony 3.

**Comment by DavertMik** [comment]
Symfony says "no" https://github.com/symfony/symfony-demo/blob/master/composer.json#L28

**Comment by DavertMik** [comment]
Personally I'm not happy with thought that we should maintain 2 editions of Symfony demo (

**Comment by raistlin** [comment]
I think we should let current symfony-demo as is. Syfmony 2 should not have many new versions and Symfony is SemVer, so no breaking chagnes will happen on current demo.

And we can create a new demo, and only maintain this new demo.
