### ISSUE TITLE
seeInField in textarea

### ISSUE THREAD

**Issue by artyfarty** [Codeception/Codeception#2921]
Am i misunderstanding something or is seeInField for textarea broken?

https://github.com/Codeception/Codeception/blob/006e8eacee08d8e729608d806dec5ded973f776f/src/Codeception/Module/WebDriver.php#L968-L971
```
                case 'textarea':
                default:
                    $currentValues[] = $el->getAttribute('value');
                    break;
```

Shouldn't it be `getText()` for textarea? In our 2.1.7 and 2.1.6 function looks like this:

```
protected function proceedSeeInField(array $elements, $value)
    {
        ...
        $currentValues = [];
        if (is_bool($value)) {
            $currentValues = [false];
        }
        foreach ($elements as $el) {
            if ($el->getTagName() === 'textarea') {
                $currentValues[] = $el->getAttribute('value');
            } ...
```

The same `$el->getAttribute('value')` explicitly stated for textarea. And well, our tests were failed until i've changed it to getText(). I can submit a PR, but maybe i'm missing something? 

Also, i'm having trouble finding that version of a method in 2.1 branch. Oh. here's the commit https://github.com/Codeception/Codeception/commit/4d2a7c233f646c76efef04d241f5b72cbcef566b#diff-b69c529efcc6368b5c564f8b36665a22

**Comment by artyfarty** [comment]
Oh. I found the ticket #2464. Well, it's broken back now. Or i am seriously missing something

**Comment by artyfarty** [comment]
For the record, we are using selenium webdriver with chromedriver. Maybe chromedriver and firefox behaves differently

**Comment by nsanden** [comment]
Working fine for me with chromedriver

```php
$I = new AcceptanceTester($scenario);
$I->fillField('#box', 'This is a test.');
$I->seeInField('#box', 'This is a test.');
```
`OK (1 test, 1 assertion)`

```text
$ codecept --version
Codeception version 2.1.6
```

chromedriver 2.20
chrome 49

**Comment by artyfarty** [comment]
I've found the difference.

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<textarea id="ta" name="foo" rows="3">bar baz
</textarea>
</body>
</html>
```
`getText` works, `getAttribute` does not.

`getText` doc states:

> Get the visible (i.e. not hidden by CSS) innerText of this element, including sub-elements, **without any leading or trailing whitespace.**

`getAttribute('value')` does not trim whitespaces though.

I'm not sure that `seeInField` should actually trim whitespaces, but it did previously.
