### ISSUE TITLE
Issue with dependency Injection using Yii2 framework

### ISSUE THREAD

**Issue by JavaDevl** [Codeception/Codeception#2924]
I am receiving this error :

`[yii\base\ErrorException] Argument 1 passed to tests\codeception\backend\tostCest::tryToTest() must be an instance of tests\codeception\backend\AcceptanceTester\AdSteps, instance of tests\codeception\backend\AcceptanceTester given`

after Creating a new StepObject  and trying to use it in my Cest class as a dependency injection element:

CestClass:

```
namespace tests\codeception\backend;
use tests\codeception\backend\AcceptanceTester;

class tostCest
{
    // tests
    public function tryToTest(AcceptanceTester\AdSteps $I,$scenario)
    {
        $I->loginAsAdmin();
        $I->wantTo("Hey you");
    }
}

```

StepObject:

```
namespace tests\codeception\backend\AcceptanceTester;
class AdSteps extends \tests\codeception\backend\AcceptanceTester
{
    public function loginAsAdmin()
    {
        $I = $this;
        $I->amOnPage('/admin/login');
        $I->fillField('LoginForm[username]', 'y.awad');
        $I->fillField('LoginForm[password]', '******');
        $I->click('login-button');
    }
}
```

**Comment by Naktibalda** [comment]
@DavertMik  This is not a Yii issue, it is helper injection issue.

**Comment by eXorus** [comment]
I'm closing this issue, feel free to reopen if it is not resolved.
