### ISSUE TITLE
If is popup window opened, function makeScreenshot dont work

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2929]
$I->click('Odeslat žádost o nové heslo');
$I->seeInPopup('Opravdu chcete odeslat žádost o nové heslo?');
$I->wait(1);
$I->makeScreenshot('Screenshot-zakaznici-popup');
$I->cancelPopup();

If is popup window opened, screenshot isnt created and test doesnt work.

[Facebook\WebDriver\Exception\UnexpectedAlertOpenException]
  unexpected alert open: {Alert text : Opravdu chcete odeslat ┼ż├ídost o nov├ę heslo?}

    (Session info: chrome=49.0.2623.87)
    (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 10.0 x86_64) (WARNING: The server did not provide any stacktrace informat
  ion)
  Command duration or timeout: 0 milliseconds: null
  Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
  System info: host: 'Tatason', ip: '10.0.0.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_74'
  Driver info: org.openqa.selenium.chrome.ChromeDriver
  Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),
  userDataDir=C:\Users\Pavel\AppData\Local\Temp\scoped_dir14892_10766}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.
  87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot
  =true, javascriptEnabled=true, cssSelectorsEnabled=true}]
  Session ID: ce3e7e7f994a41745f263719af013adf

**Comment by DavertMik** [comment]
> If is popup window opened, screenshot isnt created and test doesnt work

Yep, it seems logical to me ) I can't see this is a problem. It may be an issue of webdriver but not of Codeception
