### ISSUE TITLE
Apigility support

### ISSUE THREAD

**Issue by artmnv** [Codeception/Codeception#2936]
Hello! In our work we are using Codeception with [Apigility](https://apigility.org/). It is Zend Framework 2 based application for building APIs. The default ZF2 Module doesn't work with Apigility because of some internal differences. We are implemented this module based on ZF2 module. Does you interested in Apigility support? Can we send PR without tests?

Thank you!

**Comment by Naktibalda** [comment]
@artmnv Are you going to maintain it? (Fix bugs, ensure compatibility with new versions of Apigility and dependencies).

Creating some tests would be a good start.

**Comment by artmnv** [comment]
@Naktibalda Thank you for your reply! I can't promise that I'll fix bugs very fast, but I want to try. I can't find tests for ZF2 Module. Are there any?

Maybe we don't need a new module. Can we do some settings to ZF2 module? Or maybe we can do it in REST module. There are three main differences between Apigility and ZF2 modules:

1. You need to json_encode() request content. `$zendRequest->setContent(json_encode($post));`
2. Add headers:
`$zendHeaders->addHeaders(array('Content-Type' => 'application/json'));
$zendHeaders->addHeaders(array('Accept' => 'application/json'));`
Yes we can add this header in every test or cest but I think it is not the best solution in this situation. It's not a setting which can be changed. It's not a coincidence, it's a rule. Requests may be json or xml only.
3. I didn't check but I think Apigility recreates response object so you need to get it again `$zendResponse = $this->application->getResponse();` after application run `$this->application->run();` This is the easiest difference. I think we can move this get in ZF2 module without any problems.

What do you think? What is the best way of doing this? Thank you!

**Comment by Naktibalda** [comment]
First point is not necessary, because REST module automatically encodes request if Content-Type header is set to 'application/json'
Third point doesn't make any difference.

Second point can be achieved with helper methods:
```php
public function sendJsonPost($url, $params = [], $files = [])
{
    $restModule = $this->getModule('REST');
    $restModule->haveHttpHeader('Accept', 'application/json');
    $restModule->haveHttpHeader('Content-Type', 'application/json');
    $restModule->sendPost($url, $params, $files);
}
```

**Comment by jstewmc** [comment]
I'm not sure if I'm supposed to comment on a closed issue or create a new one, but I can attest that @artmnv's third point is an issue. 

In the ZF2 module's connector, `Codeception\Lib\Connector\ZF2.php`, the `doRequest()` method grabs the application's request _after_ the application is created but _before_ the application is run. 

This is a problem when an API Problem response is returned from an action, an MVC event handler, or API Agility itself. The API Problem library will replace the application's _existing_ response.

As a result, the response that's grabbed early in the connector's `doRequest()` method points to nothing, and the response returned by the module is empty.

For example, when running functional tests using the ZF2 module, the response is empty when an MvcEvent::EVENT_ROUTE handler returns a 401 API Problem response:

![problem small](https://cloud.githubusercontent.com/assets/1192893/16699915/429b294e-4514-11e6-8305-3fe67281f96b.png)

However, if you modify the `doRequest()` method to grab the application's response _after_ the application has run, the response is not empty:

![diff](https://cloud.githubusercontent.com/assets/1192893/16699979/a962b502-4514-11e6-9731-0522362726ba.PNG)

![solution small](https://cloud.githubusercontent.com/assets/1192893/16699916/429c698a-4514-11e6-9c4b-3915fe095475.png)

I'm happy to attempt a pull request to make this change. It seems like a relatively simple fix (famous last words haha).

Thank you Codeception team for a great library!
