### ISSUE TITLE
Unicode character support in command line output

### ISSUE THREAD

**Issue by ohfang** [Codeception/Codeception#2937]
`$I->wantTo("中文字符");`

If characters inside `wantTo` is unicode, then the first character won't display correctly in command output.
[see image](http://imgur.com/lrVTsz6)
see the second test in the image? the first character should be "添", but it shows "3?"

**Comment by Naktibalda** [comment]
I failed to reproduce your issue - I tested a number of different versions including 2.0.10, 2.1.7 and 2.2.0-beta and all of them produced correct output.

What version of Codeception are you using? Are you using phar file or installed it with composer?
Is mbstring extension installed?

**Comment by ohfang** [comment]
I use version 2.1.7，mbstring is installed. I use mac and https://github.com/robbyrussell/oh-my-zsh
"中文字符" -> output as "ĸ?文字符"

**Comment by ohfang** [comment]
It maybe caused by the **auto-to-uppercase** of the first character? @Naktibalda

**Comment by Naktibalda** [comment]
I don't think so,

Relevant code:
https://github.com/Codeception/Codeception/blob/7a1066ba6c3298d317e3918a4bd36b84533b601b/src/Codeception/Actor.php#L39
https://github.com/Codeception/Codeception/blob/4ee596129d5d41dc69b0ddf13c162a86037b3b7f/src/Codeception/TestCase/Cest.php#L187

1. It could be a terminal issue, have you checked if it can display character 中?
2. Text in your code example differs from text in the screenshot.

**Comment by Naktibalda** [comment]
@ohfang Could you do some debugging and try to locate where the first character is broken?

**Comment by ohfang** [comment]
OK, I will try.

**Comment by ohfang** [comment]
It's caused by `ucfirst`, here: https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Subscriber/Console.php#L520

`ucfirst` seems not supporting multibyte character: http://stackoverflow.com/questions/2517947/ucfirst-function-for-multibyte-character-encodings

**Comment by Naktibalda** [comment]
Could you replace that line with

```php
->message($inProgress ? $feature : (mb_strtoupper(mb_substr($feature, 0, 1, 'utf-8'), 'utf-8') . mb_substr($feature, 1, null, 'utf-8'))
```

**Comment by ohfang** [comment]
It's working.
#2946

**Comment by Naktibalda** [comment]
Thank you
