### ISSUE TITLE
REST What is the best test approach ?

### ISSUE THREAD

**Issue by AlexandreHagen** [Codeception/Codeception#2944]
Hi 

I'm new in Codeception use, and I have to develop a test protocol for a REST Api. 
I have already set all modules like Symfony2 REST etc... 

My problem is simple. How can I test REST routes from way that tests are not affecting each other and in same time keep tests fast ?!

For example, we want test that route: 
``` /api/spaces/{space}/decisions/{decision}/criterias/{criteria}/comments ```
But to use it, we need data: ```space```, ```decision``` , ```criteria```. 

I check two solutions: 
-  Disable auto clean up in Doctrine Module (it seems not to be recommended). Rename Cests (like 001_SpaceCest.php 002-Decision.php etc.) to execute its in order wanted.  And use "@depends" annotation to skip the rest of tests one failed. 
-  Define for each data needed a StepObject (with Post and Delete methods) to get this data and use its in ```_before ```, ```_after```  methods of my Cests class. 

In the first case testing will not use good practices. In the second case, test like postSpace will be excused a lot of times for a unique ```codecept run```. Because I need it for almost all routes.

I spend much time on the internet to looking for a good practice in use of Codeception with REST Api. But I only find guides to start. Nothing about how approach complex routes. So please I you have ideas, experiences or links about my issue help me.

**Comment by AlexandreHagen** [comment]
Nobody has any suggestions ?

**Comment by raistlin** [comment]
In my own projects I use other approach:

- I setup data.sql with desired data, so clean up is irrelevant for reproduction.
- I name tests with 00X_Test to control order of running tests if needed, just because I know that if test A03 fails, all AXX tests are very likely to fail.
- All tests use data from data.sql only, and if any test need some specific data, I inject them through Doctrine module.

**Comment by AlexandreHagen** [comment]
Thanks @raistlin! 
I will study you approach. 
However could you please tell me how you inject data through Doctrine module ? Are you using REST routes or something else?

**Comment by raistlin** [comment]
I enable Doctrine module on Codeception suite config file. And consume methods from [Doctrine module](http://codeception.com/docs/modules/Doctrine2#.VwyWxybsRhE) like `seeInRepository` or `haveInRepository`.

Sometimes I use  REST to provide data, but it is not really a good practice: if your REST routes to provide data fails, your test will also fail.

**Comment by AlexandreHagen** [comment]
Thanks again @raistlin  a got what I need !
