### ISSUE TITLE
Config option parameter required after update

### ISSUE THREAD

**Issue by aschwin** [Codeception/Codeception#2948]
Hi,

I just ran 'composer update' on my environment and to my surprise my tests didn't work anymore.

Codeception couldn't find a 'config' option. True, since I did not provide it and did not expected too.

So, is this parameter required in future versions or not?

I reverted back to 2.1.x-dev for now.

Thanks.

**Comment by Naktibalda** [comment]
What version was installed by update?

**Comment by aschwin** [comment]
The version that Composer picked for updating "^2.1" was "2.2.0-beta".

**Comment by Naktibalda** [comment]
Please update again, run your tests with -vvv and copy a complete output to this ticket.

**Comment by aschwin** [comment]
The version that Composer picked for updating "^2.1" was "2.1.6". The tests run fine now. No idea what is different now, since "2.1.6" and "2.2.0-beta" are not equal.

**Comment by DavertMik** [comment]
Sorry, there is no stack trace not any additional information to reproduce this issue. So I'm closing it
