### ISSUE TITLE
Suites _bootstrap.php files are not loaded

### ISSUE THREAD

**Issue by bozhidarc** [Codeception/Codeception#2951]
My fixtures and variables are not loaded if they are set in the suite _bootstrap.php file. If I set them in the global _bootstrap file everything works fine.
The problem is that I want to have different codeception.yml files with different _bootstrap files in my suite.
UPDATE:
After more testing I found out that the _bootstrap.php is loaded after the _inject method is called.
Is this done on purpose?

**Comment by DavertMik** [comment]
What version do you use? Bootstrap order was changed in 2.1.7 
https://github.com/Codeception/Codeception/blob/2.1/CHANGELOG.md#217
