### ISSUE TITLE
Clicking in Widget icon

### ISSUE THREAD

**Issue by SSyar** [Codeception/Codeception#2953]
In the following code i want to click on Email Widget icon
There are several button like this,, can some one please help 
```
<div class="widgetBox">
<a onclick="javascript:addToDashboard(28,'widget_email');" href="javascript:void(0);">
    <div class="widget-icon"><img alt="" src="/themes/bravo/img/ico-widget.png" style="width:52px;"></div>
    <div class="widget-data">
        <h1>Email</h1>
        <p>Email</p>
    </div>
</a>
```

```
<div class="widgetBox">
<a onclick="javascript:addToDashboard(22,'widget_lead_distribution');" href="javascript:void(0);">
    <div class="widget-icon"><img alt="" src="/themes/bravo/img/ico-widget.png" style="width:52px;"></div>
    <div class="widget-data">
        <h1>Lead Distribution</h1>
        <p>Lead Distribution</p>
    </div>
</a>
```

**Comment by Naktibalda** [comment]
Are you using WebDriver, PhpBrowser or framework module?
Only WebDriver executes javascript code.

**Comment by SSyar** [comment]
well off course i am on WebDriver

**Comment by DavertMik** [comment]
Try this:

```php
$I->click(Locator::contains('a>div.widget-icon', 'Name'));
```

also check other methods of Locator http://codeception.com/docs/reference/Locator maybe they can help.

**Comment by SSyar** [comment]
@DavertMik can you be more specific about the above command, under my situation .,,

**Comment by raistlin** [comment]
Please read http://codeception.com/docs/reference/Commands#Console 
You can Codeception in interactive mode with `codeception console acceptance`, so you can test different methods until you find the exact method to filter your html/javascript and click or fill your required element.

**Comment by SSyar** [comment]
@raistlin 
can i use console with a single test case? then how ?

**Comment by raistlin** [comment]
I'm not sure, but I think you cant do it. 
But you can copy-paste your single test case lines in console one by one.

**Comment by SSyar** [comment]
one more thing,, 
i open console using _php codecept.phar console acceptance_ then can i manually browse to the element., ! by just using the console's browser ? clicking and simple browsing ??

**Comment by raistlin** [comment]
You can use any `WebDriver` method.
More info [Advanced usage](http://codeception.com/docs/07-AdvancedUsage#Interactive-Console) and [WebDriver](http://codeception.com/docs/modules/WebDriver)

**Comment by SSyar** [comment]
i have started the console but still not able to click on my required widget button which EMail as listed above in the code :/
