### ISSUE TITLE
idea - new function - conditional scenario

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2955]
It will be nice have thist new function in codeception...

Sometime i need test subject, who is on site and sometime isnt.
Right now I must doing in cest file new public function something(AcceptanceTester $I) {} and if this subject isnt on site, this test is failed.

My idea... enabled this (or something similar):

```php
<?php
if ($I->seeLink('something-one')==true)
$I->click('something-one');
$I->makeScreenshot('screenshot-something-one');
$I->comment('And test more things on this link');
else
$I->click('something-two');
$I->makeScreenshot('screenshot-something-two');
$I->comment('And continue in my test case');
```

This will not create fail test, only skip my conditional scenario and continue in testing. Test will be in passed status.

$I->
$I->
$I->

    \ if
        $I->
        $I->
        $I->
       / end IF
$I->
$I->
$I->

**Comment by DavertMik** [comment]
In theory It can be implemented. however I won't do this because conditional tests should be considered as bad practice. 

In case you want to try if-else thing, you should not. Just run 2 similar tests cases for each scenario case.
