### ISSUE TITLE
moveBack(2) not working in 2.2.0 beta

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2956]
$I->moveBack(2); not working in 2.2.0.beta

I must doing (this working).
$I->moveBack(1);
$I->moveBack(1);

I use selenium

**Comment by Naktibalda** [comment]
It does not work in 2.1 either, WebDriver::moveBack() does not take any parameters: https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/WebDriver.php#L1489
