### ISSUE TITLE
Too many connections error when running large test suite (ZF2)

### ISSUE THREAD

**Issue by airdrummingfool** [Codeception/Codeception#2958]
This is similar to #1591 and #2060, but for ZF2. When running a large test suite, I get the following error:

```
 [Zend\Db\Adapter\Exception\RuntimeException] Connect Error: SQLSTATE[08006] [7] FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

Per #1363, I've tried adding 

``` php
'attributes'=> [
    PDO::ATTR_PERSISTENT => true
]
```

to my db config, but that didn't fix it.

I tried to work up a fix for this, but it appears that `$this->db` is never set in `src/Codeception/Module/ZF2.php`, so I'm not sure how to get the DB connection and `disconnect()` it in `_after`.

**Comment by airdrummingfool** [comment]
After doing more digging, I figured out that the correct db config parameter for ZF2 is `driver_options` instead of `attributes`, and now running a large test suite completes with no issues. So the fix is:
```
'driver_options'=> [
	PDO::ATTR_PERSISTENT => true
]
```

I'm leaving this open because the connection behavior is still inconsistent between ZF2 and Laravel/Doctrine/Yii; there should probably be a `disconnect()` in `_after` for ZF2 to match the others. Additionally, `$this->db` isn't set in the ZF2 lib, but perhaps that should be a separate bug(?).

**Comment by Naktibalda** [comment]
`Additionally, $this->db isn't set in the ZF2 lib, but perhaps that should be a separate bug(?).`
It isn't a bug, it is a missing feature.
ZF2 has never had a value assigned to $db property.

You are welcome to fix connection handling and make a pull request.

**Comment by airdrummingfool** [comment]
I see, I was confused by the comments in that file then. As I said, I tried to work up a fix, but got stuck when I couldn't access the db. I tried going through `$this->application` and `$this->client`, but I'm not familiar with ZF2 so I couldn't figure out how to access the driver. If someone can give a hint on how I can access the driver from the ZF2 module then I'll happily send a PR.
