### ISSUE TITLE
CSS or XPath locator is malformed - beta 2.2.0

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2960]
On my site, i have this
```
<li>
<a href="/franchise/">Franšízy</a>
</li>
<li class="active">
<a href="/franchise-branch/">Franšízy - pobočky</a>
</li>
<li>
<a href="/franchise-user/">Franšízy - uživatelé</a>
</li>
```
When i use in my test
$I->click('Franšízy - pobočky');
etc.
$I->click('Franšízy - uživatelé');
Test is failed with this information: CSS or XPath locator is malformed: Franšízy - pobočky
testing with selenium

**Comment by rebajz** [comment]
this help me
$I->click(['link' => 'Franšízy - pobočky']);
$I->click(['link' => 'Franšízy - uživatelé']);

**Comment by Naktibalda** [comment]
I reproduced and fixed this issue.

**Comment by anas-qa** [comment]
@Naktibalda issue is still reproducible for me; simply i am fetching text from specific element and then i `canSee` command to assert.

fetching value from `<div class="packages-pax-input__count"> 0 </div>`
command: `$var = $I->grabTextFrom(div.packages-pax-input__count);`

and then

assertion: `$I->canSee('1', $eee);`

Please advice if i am missing something.

**Comment by Naktibalda** [comment]
Your issue is different because you are using different methods, please raise a new issue.
