### ISSUE TITLE
Test not run when using example annotation

### ISSUE THREAD

**Issue by teeencho** [Codeception/Codeception#2970]
Hi,

I'm giving examples a try, since I have used a similar feature on another framework a while back.
But seems that my sample test is ignored when I try to run it. Removing the @example annotation runs it.

What am I doing wrong?
```
     /**
     * @group example
     * @example ['a', 'b']
     * @example ['c', 'd']
     */
    public function tryExample(AcceptanceTester $I, Example $example){
        $I->comment($example[0]);
        $I->comment($example[1]);
    }

```
I can see that the test is counted though, because the console outputs the amount of tests that the suite has 30:

```
Acceptance (dev, local) Tests (30) --------------------------
Modules: WebDriver, Asserts, Db, \Helper\Acceptance, Filesystem
------------------------------------------------------------
------------------------------------------------------------


Time: 5.43 seconds, Memory: 13.00Mb

No tests executed!
```

And if I remove the ignored test, it outputs 29:

```
Acceptance (dev, local) Tests (29) --------------------------
Modules: WebDriver, Asserts, Db, \Helper\Acceptance, Filesystem
------------------------------------------------------------
------------------------------------------------------------


Time: 5.43 seconds, Memory: 13.00Mb

No tests executed!
```
I'm using Codeception 2.2.0-beta

Thank you.

**Comment by DavertMik** [comment]
The problem here is that you use invalid json - there should be double quotes in it, so examples could be parsed with `json_decode`. Right now I'm working to improve the error output and maybe smarter parsing of annotation

**Comment by teeencho** [comment]
@DavertMik thanks for your response. I found the problem to be the group.

I was running `vendor/bin/codecept run --env dc,dev -g example`, when I run the suite without the group parameter, the example tests run fine.

Reopen or create new issue?

Thank you.

**Comment by DavertMik** [comment]
yes, please reopen
