### ISSUE TITLE
PHPUnit assertArrayHasKey undefined method

### ISSUE THREAD

**Issue by rogoit** [Codeception/Codeception#2973]
Hi,

on a test is the "assertArrayHasKey" PHPUnit assertion not working. Others work fine.

See you
Roland

**Comment by Naktibalda** [comment]
There is no such assertion in [Asserts module](http://codeception.com/docs/modules/Asserts) in the current version of Codeception.

But @DavertMik added it to the next release of 2.2 https://github.com/Codeception/Codeception/commit/7f1773c86f54aab2df14c16fb0331a5136aad145

@DavertMik have you got any objections to merging that commit to 2.1 branch?

**Comment by DavertMik** [comment]
> @DavertMik have you got any objections to merging that commit to 2.1 branch?

No, I can cherry pick it

**Comment by rogoit** [comment]
Thx very much
