### ISSUE TITLE
Problem with g:scenarios - own function not corretly converted

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2974]
When i doing:

```
vendor\bin\codecept g:scenarios acceptance
vendor\bin\codecept g:scenarios acceptance --format html
```

My own function are not visible corretly.
I see this:

```
I login as super admin ""
```
In my test i have this:

```
$I->loginAsSuperAdmin();
```
In my AcceptanceTester.php i have:

```
**
     * $I->loginAsSuperAdmin();
     */
    public function loginAsSuperAdmin()
    {
        $I = $this;
        $I->fillField("username","user-name");
        $I->fillField("password","pass-word");
        $I->click("Log in");
    }
```

My idea is:
when user doing convert to txt or html
line where is own function, replace with functions from own function.

not show
I login as super admin ""
Show:
I fill field 'username','user-name'
I fill field 'password','pass-word'
I click 'Log in' 

I use codeception 2.2.0 beta

**Comment by DavertMik** [comment]
Nope it is expected to work this way. 

When you generate scenario you get a human readable scenario of a test. You are removing most of technical stuff out of it. This way non-tech persons in your team can read them.

So `I login as super admin ""` seems to be in the right place. It doesn't describe *HOW* do you log in as admin, but reader understands that at this test works for logged in user.

If you need more detailed step-by-step tests report use `--html` formatter
