### ISSUE TITLE
accept :: when running tests

### ISSUE THREAD

**Issue by dwenaus** [Codeception/Codeception#2976]
a suggestion: many times I copy tests from the output and then run them in the command line. In the output they have a :: but in the command line it only accepts :. Similarly in the output it uses a forward slash but on the command line it uses a backslash (or vice versa).
would be nice to copy and paste to run tests as is.

**Comment by DavertMik** [comment]
This just been fixed in master branch and in 2.2 version (not in beta)
When a test fails (or you run it in --steps or --debug mode) you will see valid test name, like:

```
Test: tests/cli/RunCest.php:runTestWithAnnotationExamples
``` 

so you just copy its full name and use it with `run`
