### ISSUE TITLE
add to html output link to screenshots

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2977]
If tester use $I->makeScreenshot('some-name');

In html output is now:
```
<tr>
       <td class="stepName ">I make screenshot <span style="color: #732E81">"some-name"</span></td>
      </tr>
```
It will be very cool, if html output file have inside links to screenshots.

something as:
```
<tr>
       <td class="stepName ">I make screenshot <span style="color: #732E81"><a href="./screenshots/some-name" target="blank">"some-name"</a></span></td>
      </tr>
```

And if is scenario in fale status add to the end of line for this scenario link to this fail screenshot (for example \tests\_output\some-nameCept.fail.png or Cest.fail.png)

**Comment by DavertMik** [comment]
Good idea, unfortunately it requires some dramatic changes in core to work this way, and is not planned for nearest future. However, I will think on it. maybe I will come with a nice solution
