### ISSUE TITLE
Please add to documentation on web, how use variable in tests

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2978]
I need use variable in my tests... Right now, i know, how do that...

In: \tests\acceptance\_bootstrap.php create variable as:
define ('MyVariable', "This is my variable?");

In tests (Cept or Cest) use for example
$I->fillField('name',MyVariable);

In \tests\_support\AcceptanceTester.php
you can do same, as in tests ;-)

this will be work in all tests (unit, function, acceptance, etc). (if you add to right _bootstrap.php file in correct folder)

**Comment by DavertMik** [comment]
I think such enhancement can be good thing for [Codeception Cookbook](http://phptest.club/c/codeception/cookbook)

**Comment by DavertMik** [comment]
This issue was moved to http://phptest.club/t/please-add-to-documentation-on-web-how-use-variable-in-tests/1227
