### ISSUE TITLE
In yml - window_size: maximize not working for Firefox

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2983]
In chrome, i dont have this problem, but in FF 45.0.2 i have. But 1-2 times working, many time not working.

in my YML i have:
class_name: AcceptanceTester
modules:
       enabled:
          - WebDriver:
             url: 'http://localhost/'
             browser: firefox
             window_size: maximize
             restart: false
          - \Helper\Acceptance
          - Asserts

  [Facebook\WebDriver\Exception\UnknownServerException]
  this.getChromeWindowFromDocumentWindow(...) is undefined
  Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
  System info: host: 'Tatason', ip: '192.168.141.94', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0'
  Driver info: driver.version: unknown

If i use in test maximizeWindow(), with this i dont have problem, this function working good.

I use codeception 2.2.0

**Comment by Naktibalda** [comment]
It wasn't an issue of Codeception: http://stackoverflow.com/questions/35029386/getting-org-openqa-selenium-webdriverexception-this-getchromewindowfromdocument
