### ISSUE TITLE
how to click exactly the same buttons?

### ISSUE THREAD

**Issue by tomhaoye** [Codeception/Codeception#2984]
using codeception 2.0.9
```html
...
<div class="J_item_form Item-form hidden" style="display: none;">
    <input type="button" value="save" class="btn-save-Item J_btn_save_item">
</div>
...
<div class="J_item_form Item-form hidden" style="display: block;">
    <input type="button" value="save" class="btn-save-Item J_btn_save_item">
</div>
```
except adding id in them, any solution or referece issue? any answer will be appreciated.

**Comment by DavertMik** [comment]
I think I have idea for that but you will need to upgrade to Codeception 2.1.8 :)

The short answer is: "use XPath"

**Comment by tomhaoye** [comment]
@DavertMik thanks a lot, & i have solved it by using executeJS.

**Comment by DavertMik** [comment]
you can't click hidden buttons with selenium native clicks

**Comment by tomhaoye** [comment]
ok,i see. thanks
