### ISSUE TITLE
getMock will be deprecated in PhpUnit 5.4

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2986]
https://github.com/sebastianbergmann/phpunit/commit/5b6283a80cdb98dd482a86eee75f8e6a8f598cd8#diff-511c90242d5589e941582006e0485184R1445
```
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::getMockBuilder() instead
```

Codeception\Util\Stub::doGenerateMock must be updated.

**Comment by DavertMik** [comment]
Looks like we have serious issue here. Did this ever work?

```php
        $testCase = self::extractTestCaseFromArgs($args);
        $class = $testCase instanceof \PHPUnit_Framework_TestCase ? $testCase : new \PHPUnit_Framework_MockObject_Generator;
        $methodName = $isAbstract ? 'getMockForAbstractClass' : 'getMock';

        $mock = call_user_func_array([$class, $methodName], $args);
```

If a testcase is passed we are using it for mocj generation. However, `getMock` and `getMockForAbstractClass` methods in `PHPUnit_Framework_TestCase` are **protected**. How this was expected to be working? 

I blame myself I ever merged PR which added mocking capabilities to `Codeception\Util\Stub` :no_good: It was just wrong by name and design and now we have consequences of it :(

**Comment by DavertMik** [comment]
Nevermind. `getMock` becomes protected in PHPUnit 5.4

**Comment by DavertMik** [comment]
Ok, here is my patch https://github.com/Codeception/Codeception/pull/3093
