### ISSUE TITLE
sendGET changed requested directory

### ISSUE THREAD

**Issue by fanglijun** [Codeception/Codeception#2987]
``` php
        $I->sendGET('employee/ajax-search-employee.html?company_id=mycompany');
        $I->seeResponseIsJson();
        $I->seeResponseContainsJson(['status'=>true]);
        $employees = json_decode($I->grabResponse(), true);
        $employee = $employees['data'][0];

        $I->sendGET('employee/ajax-get-employee-detail.html?employee_id='.$employee['employee_id']);
        $I->seeResponseIsJson();
        $I->seeResponseContainsJson(['status'=>true]);
        $employee = json_decode($I->grabResponse(), true);

```

the second sendGET actually send a request to "/employee/employee/ajax-get-employee-detail.html?employee_id=4a315d4e016d11e6b43a4ca24a88ce71", is this expected?

**Comment by ohfang** [comment]
If I add a slash, and change the second sendGET to `$I->sendGET('/employee/ajax-get-employee-detail.html?employee_id='.$employee['employee_id']);`, it will work as expected.

**Comment by Naktibalda** [comment]
The obvious solution of using leading slash in URL was mentioned in description, so I am closing this issue.
