### ISSUE TITLE
CodeCoverage info not being collected

### ISSUE THREAD

**Issue by axelitus** [Codeception/Codeception#2996]
I began using the new 2.2 version (currently in RC) but the CodeCoverage is not working correctly, it is not collecting any data. It shows 0/ for all Classes/Methods/Lines.

The tests run correctly and they either fail or they pass as expected. I'm running the following command:

```
php vendor\codeception\codeception\codecept --config .codeception.yml run functional,unit --colors --report --html --xml --coverage-xml --coverage-html
```

What am I missing? My code is here: [axelitus/php-flugit@GitHub](https://github.com/axelitus/php-flugit)
Here is the TravisCI log: https://travis-ci.org/axelitus/php-flugit which shows the test results.

**Comment by axelitus** [comment]
I got it working with some changes in the configuration file. I added:
```
coverage:
  enabled: true
  include:
    - src/*
  exclude:
    - tests/*
    - vendor/*
```

I'm guessing I needed to use also the ```--coverage``` option to enable it from command line? I was using only the format options: ```--coverage-html --coverage-xml```

Well, it's working now!

**Comment by axelitus** [comment]
Actually without having it specified in the codeception.yml config file the coverage is not gathered even if I set the --coverage option.

**Comment by Naktibalda** [comment]
It is documented, so it isn't an issue. 

http://codeception.com/docs/11-Codecoverage

>To enable code coverage put these lines in the global configuration file codeception.yml:
```yaml
coverage:
    enabled: true
```

> If you performed configuration steps from above, you are ready to go. All you need is to execute codeception with --coverage option.

**Comment by axelitus** [comment]
Alright, so if I understand correctly coverage should be enabled in config and then on each test run to build coverage? I'm closing this then.

**Comment by crash21** [comment]
Hello,

In 2.2 version even with 4.8 or 5.3 phpunit I get wrong coverage. I don't get any error but coverage is wrong. I use a local vagrant box with php7.

Is it something known or I am doing something wrong?

I use it to test symfony app and with 2.1 version works better (well not 100%% accurate) buth when I change to 2.2 I get all the time:

 Summary:
  Classes:  5.56% (3/54)
  Methods:  0.00% (0/248)
  Lines:    0.00% (0/64889)
