### ISSUE TITLE
ENV or something else?

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#2998]
I dont know, if exist this option in Codeception.

I doing my test for testing in develop server. Here i can doing everything.

But in future i will need doing testing on normal server, where i cannot doing some test, because this will doing change some data...

Is it possible add something before function in test and set this is possible doing in dev server only and this test can doing on both server?

I try add before my one function in test this:

```
class zasilkyPobockaCest
{
    public function _before(AcceptanceTester $I)
    {
        $I->automaticLogin();
        $I->click('Zásilky');
    }
    public function _after(AcceptanceTester $I)
    {
    }
    /**
     * @env onlyOnDev
     */
    public function soukromePodani(AcceptanceTester $I)
    {
        $I->wantTo('bla bla bla);
        $I->comment('bla bla bla');
        $I->fillField('sender_name', 'Bruce');
        $I->fillField('sender_surname', 'Wayne');
        $I->fillField('sender_phone', TestPhone);
        $I->fillField('sender_email', TestMail);
        $I->fillField('sender_street', TestStreet);
        $I->fillField('sender_number', TestStreetNo);
        $I->fillField('sender_town', TestTown);
        $I->fillField('sender_zip', TestZip);
        $I->fillField('order_number', date("smHdmY"));
        $I->click('Uložit');
    }
```
On folder Acceptance i have many cest test, but only this test have added @env onlyOnDev

I doing this:
vendor\bin\codecept run acceptance --env onlyOnDev --html 

But after start test, this will star every test in acceptance folder.
I assumed that it will run only one single test where i have @env onlyOnDev
I am doing something wrong?
I use 2.2.0-RC acceptance test with Selenium

**Comment by rebajz** [comment]
And second question...
is it posible doing something as this in my _bootstrap.php
```
if (test have set @env onlyOnDev)
{define ('Password', "PasswordForDevServer");}
else {define ('Password', "PasswordForNormalServer");}
```

**Comment by sergeyklay** [comment]
You have to use GitHub search
https://github.com/Codeception/Codeception/pull/2855

**Comment by Naktibalda** [comment]
Use groups to run or not run certain tests: http://codeception.com/docs/07-AdvancedUsage#Groups

```php
    /**
     * @group onlyOnDev
     */
    public function soukromePodani(AcceptanceTester $I)
    {
    }
```

When in prod run your tests with --skip-group parameter.

`codecept run --skip-group onlyOnDev`

**Comment by rebajz** [comment]
Thank you, this is what i need ;-)
