### ISSUE TITLE
 WebDriver  Firefox  rebuilding new Windows

### ISSUE THREAD

**Issue by HankShi** [Codeception/Codeception#3001]
Sorry,I am not good at English,But I must need help from this community.I am writing Acceptance Test in CodeCeption....I have problem,when I use  " $I->click('#artList li:nth-child(3) .news-title a')",but WebDriver  Firefox  rebuilding new Windows....So that ,I  operation  next page appear "Link or Button or CSS or XPath element with '.tfoot div.pull-right a:first-child' was not found",because the origin page is old html。。。So,I want know  how resolve this problem？？？ # @Naktibalda 

I have thought about setting the Firefox browser preferences，but accross webdriver open Firefox ,the  Firefox browser preferences is   reduced。。。。 @elazar @tuupola @diszad @samdark @grahamc

**Comment by 28Nupur** [comment]
If I am not wrong do you have a scenario like this:
You clicked on a link for eg: SignIn
This link opens a new window
Now you want some actions to be performed on this newly opened window

If this is your case, then you have to switch to the new window.
Refer this http://toolsqa.com/selenium-webdriver/switch-commands/

Thanks

**Comment by DavertMik** [comment]
This issue was moved to http://phptest.club/t/webdriver-firefox-rebuilding-new-windows/1363
