### ISSUE TITLE
Automatic verification of mocks does not work in 2.2

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#3005]
Mock expectation are verified automatically if the instance of PHPUnit_Framework_TestCase is passed as the last argument to Stub::makeX methods.

It works well in 2.1 because all test formats extend PHPUnit_Framework_TestCase,
in 2.2 Cept and Cest formats no longer extend it, so we have to come up with alternative strategy for mock verification.

**Comment by DavertMik** [comment]
Fuck the mocks )
The most simple solution to me is to have in asserts module `$I->verifyMocks()`

**Comment by Naktibalda** [comment]
It probably needs `$I->registerMock()`

**Comment by DavertMik** [comment]
Good idea. Instead of using `Stub`...

**Comment by Naktibalda** [comment]
`$I->registerMock(Stub::makeEmpty('class', []));`

**Comment by DavertMik** [comment]
I should think on it more. Not sure it even comes to 2.2.0 because it's pretty rare case using Stub:: with mocks inside Cest files. However, I'd integrate them into the scenario rather using of static `Stub` class

**Comment by Naktibalda** [comment]
If you could document this in Release Notes of 2.2, it would be enough to me.
