### ISSUE TITLE
PhpBrowser tests have inconsistent case sensitivity

### ISSUE THREAD

**Issue by jasny** [Codeception/Codeception#3007]
Some tests are case sensitive where others are case insensitive, this gives very unexpected result.

How to reproduce

```php
$I->amOnPage('/');
$I->see('MoRe InFo');
$I->click('MoRe InFo');
```

`$I->see()` will pass, where `$I->click()` will fail (rather unexpectedly).

**Comment by DavertMik** [comment]
`I see` is a very general assertion which checks for everything on a page. It is as wide as possible that's probably why it is case insensitive. However, click requires precise text to match a link. 
Yeah probably you are right and this inconsistency should be solved by I don't see big problem with that for now.
