### ISSUE TITLE
Upload file method for REST api

### ISSUE THREAD

**Issue by sasha-ch** [Codeception/Codeception#3018]
Now I need something like InnerBrowser::attachFile() , but without html form field 
for testing images upload via my rest api endpoint.
There are 
```
CURLOPT_UPLOAD
CURLOPT_INFILESIZE
CURLOPT_INFILE
```
options. But how can I set it from \Module\REST code?

**Comment by Naktibalda** [comment]
Use the third parameter of sendPOST.
http://codeception.com/docs/modules/REST#sendPOST

```php
$I->sendPOST('/upload', [], ['image' => codecept_data_dir('image.jpg')]);
```

**Comment by sasha-ch** [comment]
Thanks.l'll try.
