### ISSUE TITLE
What i must write in my condition for comparison with datas from command line

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3020]
I need to write some condition, where I must compare what I have in command line, but I dont know how to write my condition

in command line I use:
`vendor\bin\codecept run --env chrome --group MyGroup tests/acceptance/basic/ --html --xml`

for example what i need
```
if (here I need your help =="--env chrome")
{something}
```
and second 
```
if (here I need your help 2 =="--group MyGroup")
{something }
```
please help me...

**Comment by Naktibalda** [comment]
You can get the current environment with `$scenario->current('env');` 
http://codeception.com/docs/07-AdvancedUsage#current-values

I don't know an easy way to get current groups.

But you shouldn't using conditions in your tests - if you want to execute parts of your test only in certain environment, you should split that test to two or more and use `@env` and `@group` annotations to ensure that the tests are executed in correct environments.

**Comment by rebajz** [comment]
$scenario->current('env');  will propably work only in Cept test, but I use Cest test :-(

My problem is here...
i doing tests on develop server, where i can doing testing everything what i need. My sites have 3 different domain and somethime i need doing test in one Cest file. In future i will run same tests on normal server. On normal server i cant use some test, because this will change some datas.... 

And second problem... on develop server i have different logins and passwords than on normal server.

I will like conditions something as this:

```
public function myFunction()
{
$I = $this;
if (here I need your help =="--env chromeDEV"
{$passwordForMySite="passwordForDevelop";
$loginForMySite="loginForDevelop";
}
else
{$passwordForMySite="passwordForNormal";
$loginForMySite="loginForNormal";}
$I->fillField(Username,$loginForMySite);
$I->fillField(Password,$passwordForMySite);
$I->click(Log In);
}
```

**Comment by Naktibalda** [comment]
Scenario is accessible in all formats.

http://codeception.com/docs/07-AdvancedUsage#Cest-Classes

> Each public method of Cest (except those starting with _) will be executed as a test and will receive Actor class as the first parameter and **$scenario variable as the second one.**

Using groups is the right solution for your first problem, mark the tests that you want to run in production server  with `@group prod` and run them with `vendor\bin\codecept run --group prod`.

I think that the best solution for your second problem is to create a helper to get username and password from configuration and configure it in suite.yml file.
http://codeception.com/docs/06-ReusingTestCode#Helpers
http://codeception.com/docs/06-ReusingTestCode#Configuration

_support/Helper/Configuration.php
```php
namespace Helper;

class Configuration extends \Codeception\Module
{
    protected $requiredFields = ['username', 'password'];
   
    public function getUsername()
    {
        return $this->config['username'];
    }

    public function getPassword()
    {
        return $this->config['password'];
    }
}
``` 

acceptance.suite.yml
```yaml
modules:
    enabled:
        - WebDriver:
            url: 'http://mysite.com/'
            browser: 'firefox'
        - \Helper\Configuration:
            username: 'loginForDevelop'
            password: 'passwordForDevelop'
```

Test
```php
$I->fillField('Username', $I->getUsername());
$I->fillField('Password', $I->getPassword());
```

**Comment by rebajz** [comment]
Thanks, this working perfectly :+1:
