### ISSUE TITLE
Extensions stop running with Codeception 2.2RC2

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#3024]
I was testing version 2.2RC2 and I got this when running my Testatistics extension https://github.com/redCOMPONENT-COM/teststatistics#teststatistics

The results is:
![screen shot 2016-04-25 at 16 37 40](https://cloud.githubusercontent.com/assets/1375475/14787542/1f60cd48-0b04-11e6-82ad-e222727b70bf.png)

Removing this lines from my `codeception.yml` removes the issue:
![screen shot 2016-04-25 at 16 39 36](https://cloud.githubusercontent.com/assets/1375475/14787613/68ae5dee-0b04-11e6-8065-c9750d0b51e9.png)

I guess  that 2.2 adds some b/c issue for extensions

**Comment by Naktibalda** [comment]
Summary: your issue is that result of `$e->getTest()->toString()` does not match pattern `#\((.*?)\)#`
when $e is an instance of `Codeception\Event\TestEvent`

**Comment by Naktibalda** [comment]
You were affected by the main change of 2.2 - Tests no longer extend PHPUnit_Framework_TestCase, they extend PHPUnit_Framework_Test instead. So you can't use any methods provided by PHPUnit_Framework_TestCase.
toString() is one of them - https://github.com/sebastianbergmann/phpunit/blob/5.3.2/src/Framework/TestCase.php#L291.

**Comment by DavertMik** [comment]
@javigomez test descriptions may change (there is no PSR for them, he-he), so toString is no more returns the `(string)`. Use `Codeception\Test\Descriptor` to get information about tests. Here is Pull Request to your extension https://github.com/redCOMPONENT-COM/teststatistics/pull/2

**Comment by javigomez** [comment]
Thanks ^_^
