### ISSUE TITLE
Laravel4 Connector: false assumption of 'db' existence

### ISSUE THREAD

**Issue by Namek** [Codeception/Codeception#3028]
Method `_after(TestCase $test)` in `codeception\src\Codeception\Module\Laravel4.php` contains following lines:
```php
if ($this->app['db'] && $this->cleanupDatabase()) {
    $this->app['db']->rollback();
}
```

My project does not use Database Service (Elastic Search in place) so I have disabled `DatabaseServiceProvider` in Laravel config. That's why it fails on `if($this->app['db'])` part. From debugging step by step I know that instead of calling `offsetExists` it immediately invokes `offsetGet` in `Illuminate\Container\Container`:
```php
public function offsetGet($key)
{
	return $this->make($key);
}
```

What I get is `ReflectionException` - "Class db does not exist" from `Container::build()`

Same thing happens inside `function _before(TestCase $test)`.

I'm not sure what triggers this error: this module, Laravel, PHP engine or quantum physics.

**Comment by janhenkgerritsen** [comment]
Issue is fixed by #3049 and #3048.
