### ISSUE TITLE
Specify request body for API test

### ISSUE THREAD

**Issue by chriscollinsboxuk** [Codeception/Codeception#3030]
I'm using Codeception to test a REST API application and one of the endpoints is a `DELETE` HTTP request that reads some JSON from the body of the request (i.e. not a parameter, header or file) to determine what needs to be deleted. From reading the documentation and the code, it's not clear how to specify the body of the request: is this possible? If it is, is there any documentation for this?

**Comment by Naktibalda** [comment]
```php
$I->haveHttpHeader('Content-Type', 'application/json'); //to encode automatically
$I->sendDelete('/endpoint', ['id': 5]);
```
or
```php
$I->sendDelete('/endpoint', '{id: 5}');
```

**Comment by chriscollinsboxuk** [comment]
Excellent - the first variation worked for me - incidentally, the second string version did not work. Looks like I was just missing the `Content-Type` header, thanks.
