### ISSUE TITLE
Problem In Cest with makescreenshot in _after hook

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3036]
If i add to _after hook this:
$I->makeScreenshot("Screenshot-".date("Y-m-d-H-m-s")."my-own-name");

This create only onetime screenshot in debug folder and in html output.

In this case, must create x time new screenshots, because name of screenshots are everytime different....

**Comment by DavertMik** [comment]
I'm pretty sure it actually creates a screenshot with the proper date so it should not be the same if the time changed.
