### ISSUE TITLE
Posible error in Gherkin .feature parsing `,` (comma)

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#3037]
I was checking Gherking documentation and they add `,`(comma) in their scenario description
![capture 2016-04-03 at 17 31 29](https://cloud.githubusercontent.com/assets/1375475/14857817/e499e01e-0c9d-11e6-927f-3bf4434a9fa8.png)
see: http://docs.behat.org/en/v3.0/quick_intro_pt1.html#example

But if you add a `,` in Codeception 2.2RC2 and generate `vendor/bin/codecept gherkin:snippets functional` you will get a non valid PHP code:

![screen shot 2016-04-27 at 17 32 53](https://cloud.githubusercontent.com/assets/1375475/14857872/1744e248-0c9e-11e6-91a7-f12a0a29957f.png)

Also happens with strange chars:

![screen shot 2016-04-27 at 17 33 18](https://cloud.githubusercontent.com/assets/1375475/14857897/26d98ab0-0c9e-11e6-90c0-8bd6b3342364.png)

I'm not sure if is really a bug. Because the solution is to the issue is easy: `do not use strange chars in scenario description`. But since I saw it in the Gherkin documentation I wondered if something is missing in the gherkin:snippets generator...

**Comment by DavertMik** [comment]
See the attached PR. Should be fixed now

**Comment by javigomez** [comment]
works:

<img width="1002" alt="screen shot 2016-04-29 at 17 11 33" src="https://cloud.githubusercontent.com/assets/1375475/14920393/8b95601a-0e2d-11e6-82ce-08ebb71105f0.png">

Thanks @DavertMik ^_^

From what I was able to test the feature looks really really cool. Thanks very much.
I'm hesitant to see the Gherkin related docs to do more testing in deep 😄
