### ISSUE TITLE
wrong output when executing .feature test in 2.2RC2

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#3038]
My cart.feature looks like:

```gherkin
Feature: Cart
  In order to buy products
  As a Employee With Login
  I need to be able to put interesting products into the Cart

  Scenario: Buying 2 units of the same product
    Given there is a Vendor Company called "Nike"
    ...
```

When I execute the file I get this:
 
![screen shot 2016-04-27 at 17 51 32](https://cloud.githubusercontent.com/assets/1375475/14858546/c11bf8d6-0ca0-11e6-87f0-e7ccf0bab1f7.png)

Note that the output says:

`I Cart: Buying 2 units of the same product`

This is valid for Cest and Cept files, but not for .feature files. I guess for .feature files it should say:

```
Feature: Cart
Scenario: Buying 2 units of the same product
```

**Comment by DavertMik** [comment]
Well, right now each test is printed in its own line. 
I don't find this would be convenient if some tests will be printed in 2 lines. If you have lots of tests and they are shuffled you will have a mess in console. So This is the way they are displayed now.

You can always turn on verbose output with `--steps` option.

**Comment by javigomez** [comment]
Gotcha. Ok, what about this alternative using just 1 line:

Instead of

```
I Cart: Buying 2 units of the same product
```

What about:

removing `I` when is a .feature:
```
Cart: Buying 2 units of the same product
```

**Comment by DavertMik** [comment]
Sorry, for the new confusing output:

`I` means `Incomplete` there. It is yellow for that reason )

**Comment by DavertMik** [comment]
If you have suggestions how to make it less confusing?

**Comment by javigomez** [comment]
Oh! my fault, now I understand 😅 

I see is the standard in PHPUnit too https://phpunit.de/manual/current/en/incomplete-and-skipped-tests.html

what about adding brackets or parentheses?:

```
(I) Cart: Buying 2 units of the same product
[I] Cart: Buying 2 units of the same product
```
