### ISSUE TITLE
Sending `multipart/form-data` using the REST module

### ISSUE THREAD

**Issue by baig** [Codeception/Codeception#3056]
The following CURL command works:

```
curl -i -X POST -F attributes='{"id":1,"message":"hello world"}' -F file=@/image.png http://some.url.com/v1/images -v
```

How can I send the same information using `sendPOST` in the REST module?

**Comment by Naktibalda** [comment]
Are you using PhpBrowser or framework module?

**Comment by baig** [comment]
I am using the REST module and this POST request is intended to upload a file.

**Comment by Naktibalda** [comment]
You can pass an array of files as the last argument to `sendPOST`:
$_FILES format should work with all modules:
```php
$I->sendPOST('http://some.url.com/v1/images',
    ['attributes' => '{"id":1,"message":"hello world"}]',
    [
       'file' => [
          'name' => 'image.png',
          'tmp_name' => codecept_data_dir('image.png'),
          'size' => filesize(codecept_data_dir('image.png')),
          'type' => 'image/png',
          'error' => 0,
      ],
    ]
);
```

**Comment by baig** [comment]
I didn't know that you have to include `name`, `type`, `size` and all the other information in the files array. It's not documented in the REST module documentation. I was just including the file path and name. It works now. Thanks for your help.

**Comment by Elema82** [comment]
hi @Naktibalda  i try to create a test with:
-  codeception 2.2.10
- guzzlehttp/guzzle 6.2.3
- PhpBrowser
- RestApi

My code is this:
$files = [
            'file' => [
                'name' => 'image.jpg',
                'type' => 'image/jpeg',
                'size' => filesize(codecept_data_dir('image.jpg')),
                'tmp_name' => codecept_data_dir('image.jpg'),
                'error' => 0,
                   ]
        ];

        $I->wantTo('SendPost with $FILE');
        $I->haveHttpHeader("Authorization", "Bearer ".$I->getAccessToken());
        $I->haveHttpHeader('Content-Type', 'multipart/form-data');
        $I->haveHttpHeader("X-Company-Id", 4);

        $I->sendPOST('/tasks/7/attachments', [], $files);
        $I->seeResponseCodeIs(Response::HTTP_CREATED);
        $I->seeResponseIsJson();  

in my controller the variable $files is empty.
but if change the version of guzzle to 5.* run ok and send file on post request

help!

regards

**Comment by Naktibalda** [comment]
Have you tried to use a shorter way?
```php
$files = [
  'file' => codecept_data_dir('image.jpg')
];
$I->sendPOST('/tasks/7/attachments', [], $files);
```

**Comment by Elema82** [comment]
yes, the response is the same, "file is empty"

**Comment by Elema82** [comment]
by the way, if i change the version of guzzle to 5.* the result of post request is ok,  the $file is not empty

**Comment by Naktibalda** [comment]
does it work if you remove `$I->haveHttpHeader('Content-Type', 'multipart/form-data'); ` line?

**Comment by Elema82** [comment]
IDEM, the value of header content-type not modified nothing

**Comment by Naktibalda** [comment]
I am out of ideas, Codeception tests are passing:
https://travis-ci.org/Codeception/Codeception/jobs/225725558#L2394
https://github.com/Codeception/Codeception/blob/2.2.10/tests/unit/Codeception/Module/PhpBrowserRestTest.php#L221-L250

**Comment by Elema82** [comment]
Yes, I already saw these tests. If I solve the problem, I'll let you know. Thank you

**Comment by anas-qa** [comment]
@Naktibalda any fix for this or should i upgrade guzzle as per @Elema82

**Comment by abdullahizzuddiin** [comment]
Any fix for this issue, guys?

@Elema82 do you have any solution without change guzzlehttp version to 5.0?

**Comment by Naktibalda** [comment]
It works for most other people, so if you have difficulties uploading files, you are doing something wrong. Please share your code.

**Comment by abdullahizzuddiin** [comment]
THanks for your response @Naktibalda 

My Env:
```
"php": ">=5.4.0",
"guzzlehttp/guzzle": "^6.2.1",
"codeception/codeception": "^2.3",
"codeception/specify": "^1.0",
"codeception/verify": "^1.0",
```

On my test code file (TestCest.php)
```
    public function testCreate(FreezeTester $I, Example $data)
    {
        $body_params = [
            'account_number' => isset($data['account_number']) ? $data['account_number'] : '3070030364',
        ];
        $file = [
            'credit_receipt_image' => [
                'name' => 'web/bukti.png',
                'type' => 'image/png',
                'error' => UPLOAD_ERR_OK,
                'size' => filesize(codecept_data_dir('web/bukti.png')),
                'tmp_name' => codecept_data_dir('web/bukti.png'),
            ]
        ];
        $user = $this->getLoggedinUser($I, $data);
        $I->wantTo($data['scenario']);
        $I->sendPOST('/refund-transfers', $body_params, $file);
        $I->seeResponseCodeIs($data['expect']['status_code']);
        $I->seeResponseMatchesJsonType($data['expect']['response']);
    }
```

* * *
I use Yii2 for my web api implementation.

```
public function actionCreate()
    {
        try {
            ...
            $body_param = Yii::$app->request->post();
            $credit_receipt_image = UploadedFile::getInstanceByName('file');
            ...
        } catch (\Exception $e) {
            ...
        }
        return $created_refund_transfer;
    }
```

When I inserted the third params (file), `Yii::$app->request->post();` always returned empty. So do with `UploadedFile::getInstanceByName('file');`.

I've tried `$_FILES` but it give same result.

**Comment by Naktibalda** [comment]
Are you using PhpBrowser module or Yii2 module in this freeze.suite.yml ?

**Comment by abdullahizzuddiin** [comment]
I'm not sure. But it is my `freeze.suite.yml` 
```
actor: FreezeTester
modules:
    enabled:
      - Asserts
      - Db:
          ...
      - REST:
          depends: PhpBrowser
          part: Json
      - PhpBrowser:
          url: %DNS%/api/v2
          browser: chrome
          headers:
            Content-Type: 'application/x-www-form-urlencoded'
            api-key: EDdwAw954mv4VyjpXLXZ5pRehJNXNmhsqdMbPFyaDq28aAhz
      - Yii2:
          configFile: tests/common/config/main-local.php
          part: [ORM, email, fixtures]
          cleanup: false
      - DataFactory:
          depends: Yii2
          factories: tests/_support/factories
          cleanup: false
```

**Comment by Naktibalda** [comment]
That content-type header could be messing with file upload. Try removing it.

**Comment by abdullahizzuddiin** [comment]
You are awesome @Naktibalda. It worked. Thanks a lot for your help!
