### ISSUE TITLE
Deprecated Mongo extension

### ISSUE THREAD

**Issue by Orgun109uk** [Codeception/Codeception#3063]
The Lib/Driver/MongoDb.php is using the deprecated Mongo extension in favor of the MongoDB extension.

So in my case when as im using the MongoDB extension i get the following error:

```
Uncaught Error: Class 'MongoClient' not found in .../.composer/vendor/codeception/codeception/src/Codeception/Lib/Driver/MongoDb.php:63
```

**Comment by Orgun109uk** [comment]
See pull request: #3064

**Comment by BonMatts** [comment]
Having the same issue, so updated to 2.2, as the linked PR should have solved the issue. now getting: 

> Fatal error: Class 'MongoDB\Client' not found in /vendor/codeception/codeception/src/Codeception/Lib/Driver/MongoDb.php on line 30

any suggestions?

**Comment by Orgun109uk** [comment]
Hi, this is most likely due to the PHP library being missing?

In codeception it was only added to the dev dependencies, so you would need it in your project's composer package.

```
composer require "mongodb/mongodb=^1.0.0"
```

**Comment by BonMatts** [comment]
thanks, my issue ended up being with my local environment, but this helped me figure it out. :)

**Comment by Orgun109uk** [comment]
No worries, happy to help :)
