### ISSUE TITLE
codeception api testing error 401

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3069]
I'm new to Codeception. I wrote a test case to call a server time api built in Yii2 and see the return code 200. I executed it also in debug mode where I can see the response as expected but it always returns 401.

Here is my GetServerTime.php
```php
<?php
$I = new ApiTester($scenario);
$I->wantTo('check server time');
$I->haveHttpHeader('Content-Type', 'application/x-www-form-urlencoded');
$I->sendGET('http://192.168.1.142/api/server/time',array('service' => "betaserver"));
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
```
I've also used amDigestAuthentication but it didnt work.

Here is my api.suite.dist.yml file:
```yaml
class_name: ApiTester
modules:
    enabled:
        - PhpBrowser:
            url: http://192.168.1.142    
        - REST:
            depends: PhpBrowser
            url: http://192.168.1.142/api/server/time
            part: Json
        - \Helper\Api
```
note that i'm not using any Yii2 configuration, I simply installed Codeception with composer
Here is the response I get 
```
Check server time (GetServerTimeCept)
Scenario:
* I have http header "Content-Type","application/x-www-form-urlencoded"
* I send get "http://192.168.1.142/api/server/time",{"service":"betaserver"}

  [Request headers] {"Content-Type":"application/x-www-form-urlencoded"}
  [Request] GET http://192.168.1.142/api/server/time?service=betaserver
  [Response] 
  [Headers] {"Server":["nginx/1.1.19"],"Date":["Mon, 02 May 2016 11:38:15 GMT"],"Content-Type":["text/html; charset=utf-8"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"X-Powered-By":["PHP/5.5.32-1+deb.sury.org~precise+1"],"Set-Cookie":["PHPSESSID=75kmo4dr54qun8prdtl0rtcup1; path=/; HttpOnly"],"Expires":["Thu, 19 Nov 1981 08:52:00 GMT"],"Cache-Control":["no-store, no-cache, must-revalidate, post-check=0, pre-check=0"],"Pragma":["no-cache"],"WWW-Authenticate":["Digest realm="service",qop="auth",nonce="57273c272d1c12.34670527",opaque="aaabf0d39951f3e6c3e8a7911df524c2""]}
  [Status] 401
* I see response code is 200
 FAIL 

Time: 291 ms, Memory: 13.00Mb

There was 1 failure:

---------
1) Failed to check server time in GetServerTimeCept (tests/api/GetServerTimeCept.php)

 Step  I see response code is 200
 Fail  Failed asserting that 401 matches expected 200.

Scenario Steps:

 3. $I->seeResponseCodeIs(200) at tests/api/GetServerTimeCept.php:6
 2. $I->sendGET("http://192.168.1.142/api/server/time",{"service":"betaserver"}) at tests/api/GetServerTimeCept.php:5
 1. $I->haveHttpHeader("Content-Type","application/x-www-form-urlencoded") at tests/api/GetServerTimeCept.php:4


FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

**Comment by Naktibalda** [comment]
> I executed it also in debug mode where I can see the response as expected but it always returns 401.
It is a bug of your API. It checks authentication headers and returns 401 status, but does not stop execution there.

You have to use `amDigestAuthentication` with correct username and password to authenticate.

**Comment by FaheemSultan** [comment]
i've used amDigestAuthenticate but still 401

<?php
$I = new ApiTester($scenario);
$I->wantTo('check server time');
$I->haveHttpHeader('Content-Type', 'application/x-www-form-urlencoded');
$I->amDigestAuthenticated('betaserver','b3t4');
$I->sendGET('https://dev-tv.dna.fi/api/server/time',array('service'=>'betaserver'));
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();

**Comment by Naktibalda** [comment]
Then it is a bug of your API.

**Comment by FaheemSultan** [comment]
but APi is working fine with test case written in python

**Comment by Naktibalda** [comment]
Is it checking status code?
This is not an issue of Codeception.

**Comment by FaheemSultan** [comment]
yes, the status code i'm getting is 401, you can see on the response i pasted above

**Comment by Naktibalda** [comment]
Can you give me a valid username and password for that api?

**Comment by FaheemSultan** [comment]
you can't acesss my api, its setup is locally for pakistan

**Comment by Naktibalda** [comment]
I can access `https://dev-tv.dna.fi/api/server/time`, it returns Status 401 and empty body.
Are you testing `https://dev-tv.dna.fi/api/server/time` or `http://192.168.1.142/api/server/time`?

**Comment by FaheemSultan** [comment]
i'm testing the 2nd one

**Comment by amjadbooxmedia** [comment]
@Naktibalda Digest authentication is not working for codeception
