### ISSUE TITLE
PSR-2 and _before/_after methods

### ISSUE THREAD

**Issue by petersendidit** [Codeception/Codeception#3071]
https://github.com/Codeception/Codeception/wiki/Codeception-coding-style-standard states that Codeception uses the PSR-2 coding style standards.

How do you resolve the `_before` / `_after` methods with that standard then?

PSR-2 extends PSR-1 which states 
> "Method names MUST be declared in camelCase()." 

http://www.php-fig.org/psr/psr-1/#4-3-methods4

**Comment by MAXakaWIZARD** [comment]
@petersendidit We have not reached full PSR-2 compliance yet, but there are plans for that.

**Comment by DavertMik** [comment]
There is no problem with PSR2. If we follow your logic, any class implementing `__toString`, `__call`, `__sleep`, `__clone`, and especially `__construct`, is not PSR-compatible. Which is simply wrong. 

So there is nothing wrong here to use `_` as a prefix for special methods as far as you follow camel case in naming. PSR could be broken if we've used `_before_all`, or other methods like that, but we don't use underscores to for spaces in methods anywhere. We use underscores only as prefixes.

**Comment by MAXakaWIZARD** [comment]
@DavertMik actually @petersendidit is right. There is clear statement that methods and variables starting with underscore are not allowed. Those magic methods you mentioned are just exception (built-in into language). http://www.php-fig.org/psr/psr-2/#4-3-methods

**Comment by DavertMik** [comment]
> There is clear statement that methods and variables starting with underscore are not allowed.

Actually not. Read carefully:

> Method names SHOULD NOT be prefixed with a single underscore **to indicate protected or private visibility**.

We are not indicating their visibility with prefixes. We indicate their special behavior. Just the way it is in PHP classes. PSR does not contain special mentions for exceptions, so __toString is valid PSR method name with no exception (or at least point me to a place where it is mentioned)

**Comment by MAXakaWIZARD** [comment]
@DavertMik yes, it says `SHOULD`, but anyway `phpcs` will show an alert for such fileds and methods.

**Comment by DavertMik** [comment]
The keyword here is **visibility**.
To me it seems like a bug in PHPCS. If a method is public and starts with `_` it is PSR-compatible.
