### ISSUE TITLE
Codeception not taking `background` into account when listing gherkin:steps

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#3072]
Background feature https://github.com/Codeception/Codeception/blob/2.2-docs/docs/071-BDD.md#background is great.

But when you have an scenario like this:

```
Feature: Dashboard
  In order to view current state of business
  As an owner
  I need to be able to see reports on dashboard

  Background:
    Given I am logged in at Joomla administrator as "administrator" with password "password"

  Scenario: create content
    And I open administrator dashboard page
```

You may want to know where is defined this function:

```php
	/**
	 * @Given I am logged in at Joomla administrator as :arg1 with password :arg2
	 */
	public function iAmLoggedInAtJoomlaAdministratorAsWithPassword($arg1, $arg2)
	{
		throw new \Codeception\Exception\Incomplete("Step `I am logged in at Joomla administrator as :arg1 with password :arg2` is not defined");
	}
```

When using steps you can do:

```shell
$ libraries/vendor/bin/codecept gherkin:steps acceptance
Steps from default context:
+-------------------------------------+---------------------------------------------------+
| Step                                | Implementation                                    |
+-------------------------------------+---------------------------------------------------+
| I open administrator dashboard page | AcceptanceTester::iOpenAdministratorDashboardPage |
+-------------------------------------+---------------------------------------------------+
```

I would like to be able to do the same to know, in witch `Background` file is defined a function.

Is there any way to do that?

**Comment by javigomez** [comment]
Actually Gherkin steps doesn't seem to be properly loaded:

![screen shot 2016-05-03 at 17 35 29](https://cloud.githubusercontent.com/assets/1375475/14988741/830fcd24-1155-11e6-9fba-00b26b0aa598.png)

![screen shot 2016-05-03 at 17 36 24](https://cloud.githubusercontent.com/assets/1375475/14988758/95ba2168-1155-11e6-9dc0-e13d86d307d1.png)

Do I need to add anything in special to _boostrap to load the file @DavertMik?

**Comment by 28Nupur** [comment]
I am facing the same problem where I have the implementation of my function in different context file apart from the acceptance tester. @DavertMik  @javigomez

**Comment by Sereda-Fazen** [comment]
Hi everybody! I have problem with adding Steps in "Acceptance/Step/LoginSteps.php"
What I did:
1. I created a new step in "Acceptance/Step/LoginSteps.php"
2. I added to my acceptance.yml the following : 
gherkin:
    contexts:
        default:
            - Step\Acceptance\LoginSteps
3. I have a scenario 
![image](https://cloud.githubusercontent.com/assets/10231340/19549419/e6443b00-96ac-11e6-834d-2f1129c89b3b.png)
4. This my LoginSteps.php
![image](https://cloud.githubusercontent.com/assets/10231340/19549443/083c3636-96ad-11e6-89ab-f2df512a1bd2.png)

5. When I ran this command - codecept gherkin:steps acceptance
I received next - 
![image](https://cloud.githubusercontent.com/assets/10231340/19549475/2ed1cc20-96ad-11e6-90c1-25063993cf56.png)

But if my scenario in AcceptanceTester is all right

Could you tell me please what I did incorrect?

**Comment by javigomez** [comment]
mmm strange, all seems good. Did you generate the snippets automatically? http://codeception.com/docs/07-BDD#acceptance-testing

Check all Capital letters are in the proper case. Maybe you have one lowercase and the path is not found.

Since this comment doesn't seem a bug, I suggest that you move the discussion to http://phptest.club/

**Comment by Sereda-Fazen** [comment]
Thanks for response) I'll try again generate:snippet automatically, maybe I missed some things .If doesn't change I'll write php test

**Comment by Sereda-Fazen** [comment]
Did it ! But didn't change anything.
But if I copy LoginSteps.php to _support like this

![image](https://cloud.githubusercontent.com/assets/10231340/19596009/2e75cdf6-9795-11e6-8cd2-e4db86ccd7a9.png)

and in config 

gherkin:
    contexts:
        default:
            -  LoginSteps

It works

**Comment by saiedtrife** [comment]
But how can use them later on
