### ISSUE TITLE
Codeception variable output 

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3081]
i'm using these queries to populate and grab data from database, i was wondering how can i see the result of grabFromDatabase on my console or in any file

here are the queries

$this->user->haveInDatabase('VODAd', array('id' => '15', 'ad_source' => 'newrecord', 'status' => '1'));
    $mail=$this->user->grabFromDatabase('VODAd', 'id', array('id' => '1'));

wanna see the content of $mail

**Comment by Naktibalda** [comment]
`codecept_debug($mail);` and run Codeception with -vv flag

**Comment by FaheemSultan** [comment]
thanks
