### ISSUE TITLE
Codeception doesn't throw any error when a condition fails, in earlier version 2.0.13 it throws error.

### ISSUE THREAD

**Issue by 28Nupur** [Codeception/Codeception#3083]
I have my test cases linking with TestRail where after each test execution, I pushed the results to TestRail

In earlier version(2.0.13), I am able to get a blank string for Pass and some junk or ERROR for fail condition.
For instance:: 
$check=$I->canseeElement($element) 
echo $check;exit;
 $check displays blank for pass and ERROR for fail on console. 
Based on this value, I have created a function which post the results in TestRail.

however in the newer version, it always return a blank string even-though it fails.

Can anyone help me, @DavertMik @Naktibalda 

Note :: The same behaviour is shown in beta 2.2 as in 2.0.13 and that what I really want in other versions too

**Comment by Naktibalda** [comment]
I behaviout 2.2.0 beta suits you, my recommendation is to stay on 2.0.13 until 2.2.0 final is released.
