### ISSUE TITLE
Lost session on api test

### ISSUE THREAD

**Issue by rogoit** [Codeception/Codeception#3087]
Hi,

i loose the session in the php application. When i login and run a second test the session is away. What can id do?

See you
;)

**Comment by raistlin** [comment]
Usually session database and all data are lost between tests.

**Comment by rogoit** [comment]
Why and what could be a solution. Tests with session are also important.

**Comment by raistlin** [comment]
What usually is done is make all related requests on same test.
For example, on the same test:
* Login
* Go to profile

On another test:
* Login
* Buy something
* Check that bought order is on profile page

...

**Comment by rogoit** [comment]
This is a api test suite you need a session to get the right requests. We need to be login status or we waste a lot of time to do it every time

**Comment by raistlin** [comment]
API + session sounds weird to me, but it depends on your use case.

* Are you doing integration tests? Like checking that entire system is working well with all pieces enabled.
If it's your case, then your only option is "slow tests" like I told you.

* Are you doing unit/acceptance tests? So you can mock objects/services and speed up a lot of things
Then you can speed up tests by creating fake authentication tokens and inject them in your framework, you will save at least one api call every test.

We need more info to be able to help, but I think your use case should fit in one of previous use cases.

**Comment by rogoit** [comment]
Hi,

i check many api routes in a backend single page application. When i run more than one test the server side session in the application is lost. The slow way is no solution because tests must be fast. Otherwise there will come a lot of problems. But why do i lost the session. Is the php browser so much different? A normal web browser also keep it. Is there any setting i can do in the config. Do the browser close between the tests?

Thx much
Roland
