### ISSUE TITLE
How to save the REST API json response back to a file ?

### ISSUE THREAD

**Issue by bvigneshk** [Codeception/Codeception#3088]
Hi Support,

I am using sendGET(url) and the json response includes 100 parameters.
I want to save that response back to a json file to use for other api calls like sendPUT().

Can you please help me which method I need to use to save the whole json response ?

Thanks,
Vignesh

**Comment by DavertMik** [comment]
Use [grabResponse](http://codeception.com/docs/modules/REST#grabResponse)

```php
$I->sendGET();
$response = $I->grabResponse();
$I->sendPUT('/api/data', $response);
```
If you want to save it to file, just do 

```php
file_put_contents('file.json', $I->grabResponse());
```

Sincerely, your Support :)

**Comment by bvigneshk** [comment]
Thank you for your support, Let me try :+1:

**Comment by bvigneshk** [comment]
As you stated, I am using file_put_contents('file.json', $I->grabResponse());

$I->sendGET();
file_put_contents('file.json', $I->grabResponse());

But the file.json is empty. I am using codeception 2.2 beta - is there any issue related to that or something I am missing ?

Thanks,
Vignesh.

**Comment by bvigneshk** [comment]
I think my sendGet is having problem, let me debug it.

Thanks,
Vignesh
