### ISSUE TITLE
Codeception Json API response

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3091]
i want to check the json response of api, i've seen some function on codeception documentation comparing values, i don't wanna compare values instead i just wanna see if the json response some specific properties or attributes

here is the sample response

```js
{
server: {
currentTime: "Tue, 07 Apr 2015 07:40:29 +0300"
}
}
```
i just want to confirm that the json response contains this server object and current time

how could  i do that

**Comment by DavertMik** [comment]
You can use [JsonPath](http://codeception.com/docs/modules/REST#seeResponseJsonMatchesJsonPath) to do that:

```php
$I->seeResponseJsonMatchesJsonPath('$.server.currentTime');
```

also please check http://codeception.com/docs/modules/REST#seeResponseMatchesJsonType

**Comment by FaheemSultan** [comment]
thanks, i havn't worked in json so i had difficulties understanding documentation
