### ISSUE TITLE
html output file - saved, step by step

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3094]
right now is html file saved after all test are done. Sometime is my test shootdown and html file have 0 kb and i canot read this file....

Is it posible write line to html as step by step? User can read html by refreshing in browser in almost actual situation?

**Comment by DavertMik** [comment]
Probably in your case Codeception stops with fatal errors so no html is written. 

> Is it posible write line to html as step by step? User can read html by refreshing in browser in almost actual situation?

Probably you can use [Logger](http://codeception.com/addons#CodeceptionExtensionLogger) extension for your case, which does just what you need - prints step by step to file. 

As for HTML report, it is pretty complex thing, as valid HTML should contain closing tags, so it is can't be easily appended with new steps.
