### ISSUE TITLE
long command isnt visible all in comand line

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3095]
for example, i need write this:
vendor\bin\codecept run --env DevChrome tests/acceptance/basic/my-own-test-in-codeceptionCest.php --html

but in command line i see only:
vendor\bin\codecept run --env DevChrome tests/acceptance/basic/my-own-test-in-

the rest I must write blindly...
(windows 10, phpstorm or command line)

**Comment by DavertMik** [comment]
I don't think this is an issue of Codeception but the terminal you are using. Sorry, I don't have ideas to help here. Alternative could be:

```
vendor\bin\codecept run --env DevChrome acceptance basic/my-own-test-in-codeceptionCest.php --html
```

But this doesn't help much. You may also write a simple [Robo](http://robo.li) command to run such scripts with requierd parameters.

Sorry, can't help more
