### ISSUE TITLE
grabResponse() in API test have problem with \/

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3096]
Today i doing my first test for API.
In my test i use:
$response = $I->grabResponse();
$I->writeToFile('tests/_data/myfile.json', $response);

When i open my file, in href i have problem with https:\/\/myweb.domain.com\/v3\/consignments\/
Few weeks ago, was problem with \/ in html, i mean, this is same problem....

**Comment by Naktibalda** [comment]
@rebajz Have you figured it out?
This issue lacks an example of contents of the file and a link to HTML issue.
