### ISSUE TITLE
Symfony route tests fail with additional query params

### ISSUE THREAD

**Issue by davidcochrum** [Codeception/Codeception#3097]
`seeCurrentRouteIs()` and `seeInCurrentRoute()` will only match routes which generated URLs match exactly. In our project, we're adding additional query string parameters outside of any defined placeholders on occasion which cause these tests to fail (unnecessarily IMHO).

For instance (where route named `foo` resolves to `/foo` with no placeholders) this test passes:
``` php
$I->amOnPage('/foo');
$I->seeInCurrentRoute('foo');
```
But this test fails:
``` php
$I->amOnPage('/foo?bar');
$I->seeInCurrentRoute('foo');
```

Technically I am still on the route and the Symfony router will choose the correct controller defined by the `foo` route, but the tests themselves doesn't seem to make the same match.

**Comment by raistlin** [comment]
Could you test branch 2.1?

**Comment by raistlin** [comment]
I have been testing with a new application on Symfony 2.8.5, but when I define a route as ```/my/route/{p1}?param={p2}``` or only ```/my/route/{p1}?param``` or even ```/my/route/?param```, Symfony route matcher is unable to match any route, even written the url on the browser, a 404 exception is always returned.

I couldn't find how to enable this kind of route definitions should work at Symfony2 documentation.
So I understand that this kind of feature is not supported.
