### ISSUE TITLE
Implements @conflicts annotation to improve ordering with @depends

### ISSUE THREAD

**Issue by michaelarnauts** [Codeception/Codeception#3098]
There should be a `@conflicts` annotation to indicate that the tests should run *before* the specified test, just like `@depends` indicates that the test should be ran *after* the specified test.

At first, I thought that `@before` and  `@after` could be used for this, but these annotations just invoke the specified functions, they don't change the order in which the tests will run.

Simplified example: I have three tests to add, modify and delete a user.

* I want `addUser` to run first.
* Next, `modifyUser` should run after `addUser`, so I add a `@depends addUser` annotation. It is important however that it is ran *before* `deleteUser`, so I add a `@conflicts deleteUser`.
* `deleteUser` should run after `addUser`, so I also add a `@depends addUser` annotation. It doesn't matter if `modifyUser` succeeded or not.

I can't solve this by adding a `@depends modifyUser` to `deleteUser`, since the `deleteUser` can run fine even if `modifyUser` failed.

```php
    public function addUser(AcceptanceTester $I)
    {
       // ...
    }

    /**
     * @depends addUser
     * @conflicts deleteUser
     */
    public function modifyUser(AcceptanceTester $I)
    {
       // ...
    }

    /**
     * @depends addUser
     */
    public function deleteUser(AcceptanceTester $I)
    {
       // ...
    }
```

**Comment by michaelarnauts** [comment]
@DavertMik what do you think about this, since you wrote the code to do the ordering based on `@depends`.

**Comment by DavertMik** [comment]
I think this approach is conceptually. Tests should be independent and isolated. This is the pattern. You are proposing to have one entity across different tests. You *can* do this now If you don't have shuffle order of tests, but this approach won't be promoted.

`@depends` specifies that test wont be executed if dependent test fails. And that dependent test should be executed before the current one.
