### ISSUE TITLE
autloader not found

### ISSUE THREAD

**Issue by marek-l** [Codeception/Codeception#3099]
While codecept is starting in symfony dir structure with symlink `bin/codecept` then autoloader is not found due to this line: `require_once dirname(__FILE__).'/autoload.php'; ` and it ends with error 
`PHP Fatal error:  Interface 'Symfony\Component\HttpKernel\HttpKernelInterface' not found 

while it is started with: `/vendor/codeception/codeception/codecept run` everything is ok and auloader is found

**Comment by raistlin** [comment]
Could you include what Codeception version are you running?

**Comment by marek-l** [comment]
version 2.1

**Comment by raistlin** [comment]
I couldn't reproduce.

Could you give us exact version of Operating System, PHP and Codeception?

Thanks

**Comment by marek-l** [comment]
Thank you for your willingness, I do not why but after installing `"flow/jsonpath": "^0.3.1"` everything works fine.

have a nice day
