### ISSUE TITLE
Gherkin:steps fails locating the methods

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#3100]
running: `vendor/bin/codecept gherkin:steps acceptance`

I get this table:

![screen shot 2016-05-12 at 15 31 56](https://cloud.githubusercontent.com/assets/1375475/15216245/b167a978-1856-11e6-9144-7ae05e064812.png)

But in reality it should say:

```
- Joomla CMS is installed => AcceptanceTester::joomlaCMSIsInstalled 
- I see administrator dashboard => AcceptanceTester::iSeeAdministratorDashboard 
- I Login into Joomla administrator with username :arg1 and password :arg1 | Step\Acceptance\AdministratorLogin::loginIntoJoomlaAdministratorWithUsernameAndPassword
```

Note that only the last method is defined in `Step\Acceptance\AdministratorLogin` the rest is defined in `AcceptanceTester.php`

Because my files are like this:

Configuration:
![screen shot 2016-05-12 at 15 36 00](https://cloud.githubusercontent.com/assets/1375475/15216411/404922fc-1857-11e6-94bd-33f5503c351a.png)

My AcceptanceTester file:
![screen shot 2016-05-12 at 15 37 27](https://cloud.githubusercontent.com/assets/1375475/15216465/75b2a742-1857-11e6-89c7-4e8b1059fa78.png)

and my Step File:
![screen shot 2016-05-12 at 15 38 01](https://cloud.githubusercontent.com/assets/1375475/15216487/8b8ec47e-1857-11e6-97ac-4dc5bc3c80ff.png)

**Comment by DavertMik** [comment]
Couldn't reproduce. I hope it's not relevant anymore
