### ISSUE TITLE
attachFile not working with PhantomJS

### ISSUE THREAD

**Issue by sibben** [Codeception/Codeception#3101]
Codeception 2.1.8
PhantomJS 1.2.1

`$I->attachFile('input.dz-hidden-input','87rdhr/1.jpg'); `

When i run this, on my Linux machine,  the execution of the test hangs.  Can't even break it with ctlr-C
Test runs fine with Firefox and Selenium

Tried  browser: phantom   and browser: phantomjs in my settings, but no difference
Any ideas?

**Comment by DavertMik** [comment]
Strange. If there was an issue with a module, you would get an error from PhantomJS, so actually the command was executed... My only guess is to provide a valid absolute path for your file. You can use `codecept_data_dir()` function to get the absolute path to data dir:

```
$I->attachFile('input.dz-hidden-input', codecept_data_dir() . '87rdhr/1.jpg');
```

**Comment by sibben** [comment]
When I use the full path  `/var/www/codeception/tests/_data/87rdhr/1.jpg`
I get  _[InvalidArgumentException] file not found or not readable:_
but this is the correct path and permissions are 644, so readable for everyone.
I also tried it without the 87rdhr subdir, that makes no difference
How can I debug this further?

**Comment by DavertMik** [comment]
Try to make this field visible on a webpage itself without executing JS. Maybe in this case it may work...
Actually PhantomJS is pretty unstable thing so If you have persistent errors with it just switch to Selenium, you can run browsers in headless mode by having them running as Docker containers

**Comment by abejfehr** [comment]
I'm trying this in Selenium with precisely this line `$I->attachFile('input[type="file"]',  '/Users/abejfehr/Downloads/bottom.png');` and I'm getting the same error(`[InvalidArgumentException] file not found or not readable:`).

I tried using JavaScript on the previous line to remove the hidden classes from the elements as well and it doesn't seem to have any effect. Is there a debug mode or any way I can see where it's getting to before attaching the file? Should I even see the file picker dialog come up?

**Comment by abejfehr** [comment]
Whoa, it works. The file _must_ be stored in the `tests/_data/` folder, as stated in the comment of the example for `attachFile` [here](http://codeception.com/docs/modules/WebDriver). Very unclear guys.

**Comment by ahmednawazbutt** [comment]
I am having same problem here.
Read and Implemented all of the above commented out methods. None helped me so far.
I am getting:

> [InvalidArgumentException] file not found or not readable:


Scenario Steps:

>  13. $I->attachFile("#directoryuploadform-uploadedfile","/home/offneo/Projects/OINTRANET/Product/Software/common/modules/ofilesgallery/tests/_data/files/flower.jpg") at tests/acceptance/models/FileCest.php:158
> 
> Codeception\Module\WebDriv

> er->attachFile
> /home/offneo/Projects/OINTRANET/Product/Software/common/modules/ofilesgallery/tests/_support/_generated/AcceptanceTesterActions.php:1491
> #3  /home/offneo/Projects/OINTRANET/Product/Software/common/modules/ofilesgallery/tests/acceptance/models/FileCest.php:158
> #4  common\modules\ofilesgallery\tests\models\FileCest->uploadFolderInvalidValues


Here is my code in .cest file

    public function uploadFolderInvalidValues(AcceptanceTester $I)
    {
        $I->wantTo('Submit a Model with invalid values to see errors in submission');
        
        $I->amOnPage(Url::toRoute('/ofilesgallery/file/index'));
        $I->see( T::t('main', 'Files Manager') );
        $I->dontSee( T::t('main', 'No record Found!'), 'div.alert-info' );
        
        $I->click('#btn_upload_directory');
        $I->wait('1');  //  Wait untill the model-popup Apears
        
        $I->see(T::t('main', 'Upload Folder'), 'h4.modal-title');
        
        $I->attachFile('#directoryuploadform-uploadedfile', codecept_data_dir() . 'files/flower.jpg');
        //    [InvalidArgumentException] file not found or not readable:
        $I->fillField('#directoryuploadform-description', '');
        $I->selectOption('#directoryuploadform-idcategory', '1');  //   non-existent value
        
        $I->click(T::t('main', 'Upload Folder'));
        $I->wait('1');
        $I->dontSee(T::t('main', 'Folder to be Uploaded cannot be blank.'), '.help-block');
        $I->see(T::t('main', 'Only files with these extensions are allowed: zip.'));
        $I->dontSee(T::t('main', 'Category cannot be blank.'), '.help-block');
    }
    
Any help is appricaited.

**Comment by Naktibalda** [comment]
@ahmednawazbutt Does your PhantomJS daemon run on the same computer as Codeception?

**Comment by ahmednawazbutt** [comment]
@Naktibalda  I dont know what are you talking about.
Are you asking if I have run the phantom server on same machine as of my code in terminal?
if so, yes both are on same machine.
I am working on a local machine right now.

**Comment by Michex** [comment]
@sibben what helped you? are you done witch this problem? 
I have the same issue, test hangs on attach file on phantomJS browser (on chrome it works fine).

`$I->attachFile("//input[@type='file']", "a.jpg");
`

**Comment by sibben** [comment]
Sorry, @Michex  I don't remember this anymore.  We have had , and still have,  lots of troubles with Codeception
