### ISSUE TITLE
?> is bad practice and should not in doc

### ISSUE THREAD

**Issue by Schrank** [Codeception/Codeception#3110]
I think `?>` is bad practice right before file and, and should therefore not be part of the docs. I would love to send a PR, if you think so too.

Example: http://codeception.com/docs/02-GettingStarted#writing-a-sample-scenario

**Comment by samdark** [comment]
Agree. @DavertMik ?

**Comment by DavertMik** [comment]
> I think ?> is bad practice right before file and, and should therefore not be part of the docs. I would love to send a PR, if you think so too.

Sure. `?>` was done because of code highlighters. `<?` is probably should not used as well If I'm showing only the part of the file but still it is there because of code highlighter.

**Comment by Schrank** [comment]
What are you using? Maybe we find a way to change this :-) If not, close the ticket, nothing to do here. ❤️

**Comment by DavertMik** [comment]
It was GitHub pages with old highlighter. It is much better now so probably I can manage to fix it.
I'm just in a process of updating site so I will leave it opened to try my best to fix it

**Comment by Schrank** [comment]
No need you do it, tell me and you get a PR 🙃

**Comment by DavertMik** [comment]
I think I did it in most guides. If you find some more - please send PR :+1:
