### ISSUE TITLE
Code Coverage not working in 2.2.0-RC2

### ISSUE THREAD

**Issue by crash21** [Codeception/Codeception#3111]
Hello,

In 2.2.0-RC2 version even with 4.8 or 5.3 phpunit I get wrong coverage. I don't get any error but coverage is wrong. I use a local vagrant box with php7.

Is it something known or I am doing something wrong?

I use it to test symfony app and with 2.1 version works better (well not 100%% accurate) but when I change to 2.2 I get all the time:

Summary:
Classes: 5.56% (3/54)
Methods: 0.00% (0/248)
Lines: 0.00% (0/64889)

I test locally in Vagrant nginx- php7-mariadb machine. Here is is my codeception.yml:

    actor: Tester
    coverage:
        enabled: true
        include:
          - src/*
     paths:
        tests: tests
        log: tests/_output
        data: tests/_data
        support: tests/_support
        envs: tests/_envs
    settings:
        bootstrap: _bootstrap.php
        colors: true
        memory_limit: 1024M
    extensions:
       enabled:
            - Codeception\Extension\RunFailed

**Comment by DavertMik** [comment]
There were no line changed in coverage parts of Codeception for 2.2
So I have no clues what may have changed there. 

Did you try both versions on PHP7?

**Comment by crash21** [comment]
Yes same Vagrant machine with same php7 version (latest one), just swapped versions from composer.

**Comment by crash21** [comment]
Even in symfony demo codeception port, with 2.2.0-RC2 coverage not working

**Comment by stromknight** [comment]
i have a same problem, and i work in php7, when i use  codecept,then throw a exception 
<img width="564" alt="bc1b94d9-48db-4829-9247-cbb4e8146f33" src="https://cloud.githubusercontent.com/assets/5847148/15382025/0b4c6cce-1db8-11e6-866e-914b0d3b4c75.png">

**Comment by DavertMik** [comment]
Can this be PHP7 issue?

**Comment by crash21** [comment]
Hello,

Don't think so because when i downgrade to 2.1 codeception, the coverage seems working.

**Comment by Naktibalda** [comment]
I reproduced this issue with PHP 7.0.6

**Comment by Naktibalda** [comment]
@DavertMik I tracked it down to your test format refactoring: https://github.com/Codeception/Codeception/commit/91b4029ace090e408e8a3064aceda36e555c4369

Code coverage works before it, but not after.

**Comment by Naktibalda** [comment]
I used a local code coverage with Cept files only.

I suspect that it returns 0 results, because Cept format no longer extends PHPUnit_Framework_Testcase.

**Comment by Naktibalda** [comment]
2.1:
```
codeception-zf1-tests$ php ../codeception/codecept run tests/functional/REST/GetMethodWithParamsCept.php --coverage
Codeception PHP Testing Framework v2.1.9
Powered by PHPUnit 5.3.4 by Sebastian Bergmann and contributors.

Functional Tests (1) ----------------------------------------------------------------------------------------------------------------------------------
Make get request with parameters (REST/GetMethodWithParamsCept)                                                                                  Ok
-------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 336 ms, Memory: 12.00MB

OK (1 test, 2 assertions)


Code Coverage Report:    
  2016-05-26 21:40:24    
                         
 Summary:                
  Classes: 33.33% (1/3)  
  Methods: 25.00% (1/4)  
  Lines:   22.64% (12/53)

RestController
  Methods: 100.00% ( 1/ 1)   Lines: 100.00% ( 12/ 12)
Remote CodeCoverage reports are not printed to console
```
master:
```
gintas@gintas-laptop:~/workspace/codeception-zf1-tests$ php ../codeception/codecept run tests/functional/REST/GetMethodWithParamsCept.php --coverage
Codeception PHP Testing Framework v2.2.0-RC2
Powered by PHPUnit 5.3.4 by Sebastian Bergmann and contributors.

Functional Tests (1) ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ GetMethodWithParamsCept: Make get request with parameters (0.2s)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 232 ms, Memory: 12.00MB

OK (1 test, 2 assertions)


Code Coverage Report:   
  2016-05-26 21:40:56   
                        
 Summary:               
  Classes:  0.00% (0/3) 
  Methods:  0.00% (0/4) 
  Lines:    0.00% (0/56)

Remote CodeCoverage reports are not printed to console
```

**Comment by Naktibalda** [comment]
@DavertMik I found the issue and cleared the first hurdle, but I don't know what to do with the second one.

The first issue is that Codeception\Test\Feature\CodeCoverage is never used because of mistake in https://github.com/Codeception/Codeception/blob/2.2.0-RC2/src/Codeception/Test/Test.php#L34

'coverage' must be replaced with 'codeCoverage'.

The second issue is that CodeCoverage feature uses `$this->testClassInstance` at https://github.com/Codeception/Codeception/blob/2.2.0-RC2/src/Codeception/Test/Feature/CodeCoverage.php#L26

But $this->testClassInstance is set by Cest format only, Cept and Gherkin must have it too.

**Comment by DavertMik** [comment]
Thanks @Naktibalda for clarifying. I will work on it tomorrow
