### ISSUE TITLE
test run freezes on window.close and recording

### ISSUE THREAD

**Issue by Schrank** [Codeception/Codeception#3113]
I'm running a test on a popup.

``` php
$I->switchToWindow('selectproducts');
$I->see('Select products');
$I->click('Save');
```

The click on Save calls `closeme`.

``` html
<a href="#" onclick="return closeme()"><?php echo $this->__("Save"); ?></a></div>
```

``` js
function closeme() {
    window.close();
    return false;
}
```

This test runs fine as long as `Codeception\Extension\Recorder` is NOT used. I assume the problem is, that the window, the Recorder wants to make a screenshot from is gone.

Is there any workaround to temporarily disable the screenshot for this one step?

**Comment by Naktibalda** [comment]
Since October 2016 Webdriver catches exceptions thrown by takeScreenshot.

 https://github.com/Codeception/Codeception/pull/3534
