### ISSUE TITLE
RunFailed is not thread safe

### ISSUE THREAD

**Issue by neronmoon** [Codeception/Codeception#3115]
I've implemented parallel test running and it works nicely. But if some tests fail, "failed" file will be erased and filled with failed tests of the current thread. 

We need to read and erase the file on "./codecept run", And append line just one if some tests fail (with locks and other thread stuff). 

Also with current implementation, if some test fails with fatal error -- 'failed' file wouldn't be filled

**Comment by DavertMik** [comment]
This why it is an extension that can be easily turned off if it works badly for your case.

Could you patch it and send a Pull Request to fix this issue?

**Comment by neronmoon** [comment]
I'll be my best :)

**Comment by eXorus** [comment]
I'm closing this issue, feel free to reopen if necessary but Codeception doesn't support parallel tests, only with an extension.
