### ISSUE TITLE
DBH Call to a member function execute() on boolean

### ISSUE THREAD

**Issue by rogoit** [Codeception/Codeception#3116]
Hi,

i got this bug. Can anybody help please ;)

Call to a member function execute() on boolean in /projectpath/vendor/codeception/codeception/src/Codeception/Module/Dbh.php on line 121

See you
Roland

**Comment by tomtomsen** [comment]
I think:

it seems like you are generating an invalid query. probably in the criteria parameter of seeInDatabase or dontSeeInDatabase.
But you are right the result of ->prepare($query) should be validated and a different error should get generated.

it seems like Dbh module is deprectated and will be removed in 2.2. so i'm not sure if that fix is relevant?

**Comment by tomtomsen** [comment]
maybe running codeception with the "-vvv" parameter could help you find the error.

**Comment by rogoit** [comment]
So maybe you can tell me how i can get all datasets with a where statement and not only one...that is my problem to do a simple request on the database

**Comment by tomtomsen** [comment]
I'm not sure what you are trying to accomplish. can you explain what you are trying to test?
which method are you using, and how?

**Comment by rogoit** [comment]
Hi,

sure i do an Api Test. I want to read the parameters from an table. Than i will do the api call with this params in a loop and check the response.

Thx

**Comment by raistlin** [comment]
Can you post your test here?

**Comment by rogoit** [comment]
I throw it away but when i use grapFromDatabase i will not get all datasets...like where status = 1...

**Comment by raistlin** [comment]
Thanks @rogoit for reporting, even if it's deprecated, bug fixes are relevant.
Thanks @tomtomsen for research.
