### ISSUE TITLE
Cannot read from/write to MySQL BIT fields

### ISSUE THREAD

**Issue by davidcochrum** [Codeception/Codeception#3118]
We use `BIT(1)` columns in a number of tables for booleans. When attempting to write to one of those fields (using `haveInDatabase()`):
```
[PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'active' at row 1
```

When attempting to verify a record exists matching the boolean value (using `seeInDatabase()`):
```
No matching records found for criteria {"active":0} in table ...
```

Obviously this is a bit of a conundrum and I don't know of any sweeping, reliable solution.

**Comment by DavertMik** [comment]
> Obviously this is a bit of a conundrum and I don't know of any sweeping, reliable solution.

Yes, Codeception is not an ORM so we are not trying to support all RBMS 100%. It's not a core feature. However, I encourage you to contribute. There is a Db module and Mysql Driver in `Codeception\Lib\Driver\Mysql` for it. Please check it out, maybe you will get an idea how to fix it.

Send a pull request then.
