### ISSUE TITLE
[imp] Gherkin:snippets list snippets of one specific .feature file 

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#3119]
Right now we run:

```
tests/vendor/bin/codecept g:snippets acceptance
```

...to get a list of the steps implementing the methods.

It would be a great improvement if we could do instead:

```
tests/vendor/bin/codecept g:snippets tests/my.feature
```

...in order to get a list of were are the methods at the `.feature` file (not all the acceptance suite).

**Comment by edno** [comment]
I've pushed the PR #3212 that implements this request.
