### ISSUE TITLE
Codeception Logs

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3123]
i was wondering if i can get detailed logs of all the tests executed in codeception.. can't seem to find a way or any command to do it.. can anybody help me? i want a seperare log file where i can see the logs

**Comment by Naktibalda** [comment]
There are no logs.
The closest thing you can get is running Codeception with `-vvv` flag (as detailed as possible) and redirecting output to file.

**Comment by DavertMik** [comment]
> i was wondering if i can get detailed logs of all the tests executed in codeception.. can't seem to find a way or any command to do it.. can anybody help me? i want a seperare log file where i can see the logs

You need to install Monolog and enable logging extension http://codeception.com/addons#CodeceptionExtensionLogger

**Comment by FaheemSultan** [comment]
how can i redirect output to any file, or i simply want the console output to copy and re write on another file..how can i do so

**Comment by DavertMik** [comment]
As you'd usually do it in *nix systems:
```
codecept run --no-colors -n > my_output_file.txt
```

**Comment by FaheemSultan** [comment]
let me try it

**Comment by FaheemSultan** [comment]
can you please write the full command here is what i'm using to run now

codecept run -vv tests/api/UserManagamentCest

and also tell the location where this output file is saved

**Comment by DavertMik** [comment]
```
codecept run -vv tests/api/UserManagamentCest -n > /path/to/your/file.log
```
You specify location by yourself. Just provide a filename after `>`

**Comment by FaheemSultan** [comment]
thanks, it worked
