### ISSUE TITLE
Codeception __HALT_COMPILER(); not found

### ISSUE THREAD

**Issue by rogoit** [Codeception/Codeception#3125]
Hi,

when i try to run au cover test this happend

internal corruption of phar "/private/var/tmp/C3yig9xM.tar" (__HALT_COMPILER(); not found)

What can i do i am using a  Apache and everything is up to date

See you
Roland

**Comment by rogoit** [comment]
So here the $tempFile is not written

`protected function retrieveAndPrintHtml($suite)
    {
        $tempFile = tempnam(sys_get_temp_dir(), 'C3') . '.tar';

        $destDir = Configuration::outputDir() . $suite . '.remote.coverage';
        if (is_dir($destDir)) {
            FileSystem::doEmptyDir($destDir);
        } else {
            mkdir($destDir, 0777, true);
        }

        $phar = new \PharData($tempFile);
        var_dump(__FILE__ . ': ', is_file($tempFile)); exit;
        $phar->extractTo($destDir);


        unlink($tempFile);
    }`

var_dump is bool(false)
I try to fix it but still not working

**Comment by Naktibalda** [comment]
Could you give describe the steps necessary to reproduce your issue?

**Comment by rogoit** [comment]
I use a vagrant and run the tests remote from my locale mac.
I test api routes with --coverage --coverage-html

I have this setting
`coverage:
  enabled: true
  c3_url: 'http://www-dev.mydomain.com:8080/'
  remote: false
  whitelist:
      include:
          - _php/*`

So when i use this it is working but all lines on coverage are empty. And when i set remote to true i got this error that can not read from the tar.

**Comment by Naktibalda** [comment]
@rogoit in the code your posted one very important line is missing:
```php
        file_put_contents($tempFile, $this->c3Request('html'));
```
https://github.com/Codeception/Codeception/blob/2.1.8/src/Codeception/Coverage/Subscriber/RemoteServer.php#L40

**Comment by rogoit** [comment]
THX
