### ISSUE TITLE
Codeception Logger

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3127]
i've installed Codeception extension logger to enable logs by this command
composer require monolog/monolog

and edit my codeception.yml as

extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Logger

  when i run any test case it show below error 

 [Codeception\Exception\ConfigurationException]             
  Logger extension requires Monolog library to be installed

**Comment by DavertMik** [comment]
So please install Monolog library :)
Depending on installation type this may differ. For Composer you should just add it to `composer.json`, for phar installation - you should download it manually and require it in `tests/_bootstrap.php`

**Comment by FaheemSultan** [comment]
i've already installed it, see my question.. and i'm not using phar only composer
