### ISSUE TITLE
Db Module doesn't work on big dumps

### ISSUE THREAD

**Issue by dima-stefantsov** [Codeception/Codeception#3128]
I am on windows, using wamp. I actually get system PHP CLI process exception when I try to run "codecept run" with a big dump.sql

When I comment out this line of code of Db Module:
`$sql = preg_replace('%/\*(?!!\d+)(?:(?!\*/).)*\*/%s', "", $sql);`
, it works like it should, no problem.

String of 11MB is too big or something.
Feels like this line is not needed at all. Please fix.

**Comment by Naktibalda** [comment]
This line removes comments from SQL.

**Comment by dima-stefantsov** [comment]
I know :)
But looks like it's not needed. Is it?

**Comment by Naktibalda** [comment]
It may be needed if dump file contains sql statements in multi-line comments.
And this code exists since 1.0.1 so I am not very keen to delete it.

Could you run Codeception with -vvv flag and copy error output including exception message and complete stacktrace?

**Comment by dima-stefantsov** [comment]
Sql in multiline comments... I see. Then it must be implemented in some way.

There are no exceptions and traces. My PHP CLI (php.exe) simply dies with default Windows "application stopped working" if that php code line is present.

It works even with this line, if instead of 11MB dump I pass a short one, few KB.

Actually I usually do restores with
`shell_exec("7z e -so __{$local_db}.7z | mysql -u {$local_user} {$local_pass} {$local_db}");`

1. Is there a way to maybe override "what Db module does to restore dump"? I'd just pass my shell_exec command in there.
2. Can you reproduce fatal php interpreter error if you pass big/huge string into preg_replace? 12MB+

**Comment by Naktibalda** [comment]
I don't use PHP on Windows.
Had no problem with running that preg_replace on a longer string here: https://3v4l.org/j0WGa#tabs

**Comment by DavertMik** [comment]
> Is there a way to maybe override "what Db module does to restore dump"? I'd just pass my shell_exec command in there.


Yes, you can and should do that. Db module can't perform better than mysql istself. So what you need to do is to create a [new helper](http://codeception.com/docs/06-ReusingTestCode#Helpers) `Helper\Db` and implement its logic in `_before` method:

```
function _before()
{
shell_exec("7z e -so __{$local_db}.7z | mysql -u {$local_user} {$local_pass} {$local_db}");
}
```

Also you will need to disable loading dumps in Db module by setting cleanup and populate to false

```
cleanup: false
populate: false
```

> Can you reproduce fatal php interpreter error if you pass big/huge string into preg_replace? 12MB+

No

**Comment by DavertMik** [comment]
Db module may not fit for everyone as all database tasks can be complicated. Sure you are free to extend or replace existing solutions with something that fits you. Db module can be extended, or be configured to use with custom Helper

**Comment by dima-stefantsov** [comment]
Try to pass a string that would actually require replaces, see how it goes: https://3v4l.org/gB8j7

**Comment by dima-stefantsov** [comment]
Fixed this by setting lower recursion limit: **pcre.recursion_limit=10000**

> pcre.recursion_limit integer
> PCRE's recursion limit. Please note that if you set this value to a high number you may consume all the available process stack and eventually crash PHP (due to reaching the stack size limit imposed by the Operating System).

Which means your regex is needlessly complex for my system. It works just as well if instead of 
`$sql = preg_replace('%/\*(?!!\d+)(?:(?!\*/).)*\*/%s', "", $sql);`
 you write it as
`$sql = preg_replace('%/\*(?!!\d+).*?\*/%s', '', $sql);`
(please try it yourself)

Now it works well even without tinkering with recursion_limit.

Please fix.
