### ISSUE TITLE
Codeception Report Generation

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3129]
I need to make a report after execution of all test cases, that how many test cases were executed, how many were passed and failed and things like that,(in csv, .docs or any other file format), i can't seem to find a way to do that in codeception

**Comment by Naktibalda** [comment]
http://codeception.com/docs/02-GettingStarted#Reports
Builtin reporters:
```
--html[=HTML]                    Generate html with results [default: "report.html"]
--xml[=XML]                      Generate JUnit XML Log [default: "report.xml"]
--tap[=TAP]                      Generate Tap Log [default: "report.tap.log"]
--json[=JSON]                    Generate Json Log [default: "report.json"]
```

If none suites your usecase, you can implement your own http://codeception.com/docs/07-AdvancedUsage#Custom-Reporters
