### ISSUE TITLE
Gherkin before and after events

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#3131]
I was looking for a way to run a method after a .feature file ends.

For example, lets say that we have this scenario:

```gherkin
Feature: administrator login
  In order to manage my web application
  As administrator
  I need to be able to login

  Scenario: Successful login
    Given I am registered administrator named "admin01"
    When I login into Joomla Administrator with username "admin01" and password "admin01"
    Then I should see administrator dashboard
```

Once that `administratorLogin.feature` file ends I would like to run a `cleanUp` method that removes the `admin01` user.

I was checking at the docs: https://github.com/Codeception/Codeception/blob/2.2-docs/docs/07-BDD.md but I don't seem to find any thing like that.

I have seen that Behat has `AfterSuite` hooks: http://docs.behat.org/en/v3.0/guides/3.hooks.html. Would be worth to add this kind of hooks to Codeception?

**Comment by DavertMik** [comment]
I think the cleanest way is to use GroupObject here http://codeception.com/docs/08-Customization#Group-Objects

At least I have example just for this case there. Also I think [`_afterSuite`](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module.php#L129) of a Helper should work as well.

---

There is a reason why you should do cleanup before/after suite and not before/after a feature file or a cest file. Codeception tests can be executed in random order so tests from different features will be executed.

**Comment by javigomez** [comment]
Nice. Thanks! I'll test that way.

**Comment by lukewatts** [comment]
Can you explain how to get groups to work with Gherkin feature tests. Those links don;t mention anything in relation to AcceptanceTester or Steps.

**Comment by vitoo** [comment]
@lukewatts 

We link group and feature in codeception.yml 

First enable group 

```
extensions:
    enabled: [Group\Admin]
```

Then link tests to group like this : https://codeception.com/docs/07-AdvancedUsage#Group-Files


```
groups:
  # add 2 tests to db group
  db: [tests/unit/PersistTest.php, tests/unit/DataTest.php]

  # add all tests from a directory to api group
  api: [tests/functional/api]

 # add all tests to Admin group
  admin: [tests]
```
