### ISSUE TITLE
composer.json prevents non-breaking updates

### ISSUE THREAD

**Issue by mindplay-dk** [Codeception/Codeception#3137]
Several requirements [use](https://github.com/Codeception/Codeception/blob/2.1/composer.json#L27) version constraints along the lines of `>=2.5, <3.1`, prevent upgrades with non-breaking changes, e.g. from `3.0` to `3.1`.

The low upper constraint prevents me from upgrading many dependencies that are also dependencies of my own packages. This is problematic.

Any particular reason you should be scared of automatically upgrading to minor releases?

Most of these projects are following SEMVER, so no breaking changes should be present in a minor update - they should contain new features and non-breaking changes only.

I realize there's no guarantee, but most other packages use constraints along the lines of e.g `^3` by now, allowing an easy, direct upgrade-path without (effectively) waiting for your approval.

Please consider changing that?

**Comment by DavertMik** [comment]
It can't be said in general. Lots of projects do introduce deprecation warnings and they can affect the overall execution. Some projects, like PHPUnit do change APIs in minor releases

**Comment by Naktibalda** [comment]
The problem is that PHPUnit turns depreciation warnings to exceptions. So for us the things break on the last minor release (Symfony 2.8.0, Zend MVC 2.7.0, etc). Would it be better to disable Phpunit's warning handling?

**Comment by DavertMik** [comment]
Good idea would be to wrap them inside our deprecation notifications. I
think this can be done for 2.2
31 трав. 2016 р. 09:07 "Gintautas Miselis" <notifications@github.com> пише:

**Comment by mindplay-dk** [comment]
IMO, the reality of using third-party components is that third parties can release breaking changes - if people commit `composer.lock` with their projects, this should not be an issue that breaks published projects; on the other hand, if third-party changes break projects in-development, I'd want to know about it as soon as possible.

If somebody claims to use SEMVER, they should not be releasing breaking changes without a major version increase - if so, that's them breaking their library, and I don't think it's your responsibility to vet every minor release of third-party packages; you can't be the quality police of every vendored package, especially packages that are extremely commonly used.

Just my $.02

**Comment by mindplay-dk** [comment]
Thinking more about this, it seems like the right thing in this situation would actually be a way to formally specify the recommended/tested version of a dependency.

What's really needed here is a new type of package link in `composer.json`, like...

```json
{
    "require": {
        "symfony/console": ">=2.5, ^3.0",
    },
    "recommend": {
        "symfony/console": "^3.0, <3.2",
    }
}
```

The `recommend` package link here is fictive - but something like this would enable us to `require` with a broader version constraint, but `recommend` with a more narrow constraint.

Composer could warn the user when a non-recommended version gets installed - the user could then decide to add a more restrive constraint to their project, or continue with a non-recommended version at their own risk.

What do you think, would this solve the problem? Should we open a feature request against composer?

**Comment by Naktibalda** [comment]
We no longer have any rules preventing non-breaking updates.
