### ISSUE TITLE
Codeception Custom report generation

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3144]
i'm writing test cases against rest api's, i'm using cest classes to represent one single API, i want a custom report but i have no idea how to do it, the sample report i want is

API Name: Class name  (bcz each cest class is representing  a single API)
Test case Executed : e.g 20
Passed Test cases : e.g 10
Failed Test Cases: e.g 
and one line description of every failed test case 

its for a single api or cest class, i want it for every cest class which is executed, can anyone help me

**Comment by DavertMik** [comment]
I think you should ask this at http://phptest.club
Sorry, I need to close it here
