### ISSUE TITLE
Codeception Report

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3145]
how do i get to know which test case is failed or passed, i mean we can see it on the console but i wanna get it through code, here are the few things i wanna know about my test (cest) classes

1) name of class executed
2) no of passed test cases
3) no of failed test cases
4) which test case is passed or failed

i was wondering if i can put any condition in test case or any value that indicates that the test case is passed or failed

**Comment by DavertMik** [comment]
> but i wanna get it through code

Maybe you can do that through Extensions. Check them in Customization section in docs
