### ISSUE TITLE
Not equals arrays is equals (Different order)

### ISSUE THREAD

**Issue by s4urp8n** [Codeception/Codeception#3147]
I write some package to work with arrays. I implement **reverse()** method, and try to test it with codeception. If arrays have same keys and values but different order of elements it is consider as equals - but, i think it is bug

There was 1 failure:

---------
1) Failed to reverse test in ArrCest::reverseTest (tests\unit\\ArrCest.php)

 Step  I assert not equals {"three":3,"two":2,"one":1,"zero":0},{"zero":0,"one":1,"two":2,"three":3}
 Fail  Failed asserting that Array &0 (
    **'zero' => 0
    'one' => 1
    'two' => 2
    'three' => 3**
) is not equal to Array &0 (
    **'three' => 3
    'two' => 2
    'one' => 1
    'zero' => 0**
).

**Comment by Naktibalda** [comment]
assertNotEquals is a wrapper of PHPUnit assertion having the same name: https://github.com/Codeception/Codeception/blob/2.1.9/src/Codeception/Util/Shared/Asserts.php#L48

We can't change its behaviour.

**Comment by s4urp8n** [comment]
Oh, yeah. Sorry! 
I write it to https://github.com/sebastianbergmann/phpunit
