### ISSUE TITLE
Class-name collisions in generated code

### ISSUE THREAD

**Issue by mindplay-dk** [Codeception/Codeception#3149]
I have two helper modules in different namespaces, but they have the same class-name.

This results in a fatal error after `codecept build`:

```
Fatal error: Cannot use Kodus\Database\Test\Support as Support because the name is already in use in C:\workspace\test\kodus-db\tests\_support\_generated\UnitTesterActions.php on line 11
```

Of course, yeah, I could just mangle the class-name in one of them as a work-around, but there goes the reason we had namespaces in the first place...

**Comment by Naktibalda** [comment]
Fixed by  #4614
