### ISSUE TITLE
Double request failed for API test

### ISSUE THREAD

**Issue by shakly** [Codeception/Codeception#3152]
Since i update from version 2.1.7 to 2.1.9, all my test with double request failed.

As exemple : 
```
        $I->wantTo('Login');
        $I->sendPOST('/login', ['username' => 'GoodUsers', 'password' => 'P4ssword']);
        $I->seeResponseCodeIs(200);
        $I->seeResponseIsJson();
        $I->seeResponseContainsJson(['success' => true]);
        $I->seeResponseMatchesJsonType(['data' => ['token' => 'string']]);
        $I->seeResponseContainsJson(['code' => 'S000']);
// The test is OK

        $token = $I->grabDataFromResponseByJsonPath('$..token');
// The value of token is good

// I send token to acces private page
        $I->haveHttpHeader('Authorization', $token[0]);
        $I->sendGET('/users');

// Error, the token is unknow
        $I->seeResponseCodeIs(200);
        $I->seeResponseIsJson();
        $I->seeResponseContainsJson(['success' => true]);
        $I->seeResponseContainsJson(['data' => ['user' => ['userid' => '1', 'username' => 'GoodUsers']]]);
        $I->seeResponseContainsJson(['code' => 'S000']);
```

I have the same error when i registered a user and i try to login with same user.

All was working with version 2.1.7, it might be because of "[ZF2] create new instance of Application for each request" in Changelog but it create problems.

**Comment by Naktibalda** [comment]
How do you validate that token?

**Comment by shakly** [comment]
Very simply,  $I->sendPOST('/login', ['username' => 'GoodUsers', 'password' => 'P4ssword']); add a line in the database and when i call $I->sendGET('/users') i check if the token exist.
In this example the database is empty at the second call as if codeception call rollback on each request.

If it can help, my project is with Symfony.

**Comment by Naktibalda** [comment]
So it isn't a ZF2 project? That change is ZF2 specific.

Codeception does not cleanup database after each request.

**Comment by shakly** [comment]
I know but it's the only think that can explain that bug in the changelog.

One more time i test to force version 2.1.7, it work and come back to 2.1.9 the test failed

**Comment by Naktibalda** [comment]
Could you test it with 2.1.8 too?

**Comment by shakly** [comment]
It failed in 2.1.8

**Comment by Naktibalda** [comment]
@vyarmolenko @raistlin Have you got any ideas what could be causing this?

@shakly Try to add a new parameter to Symfony module in functional.suite.yml
`rebootable_client: false`

**Comment by shakly** [comment]
`rebootable_client: false` dont fix the problem

**Comment by raistlin** [comment]
@Naktibalda No, I have no idea.

@shakly I assume you create the token and  send the new request on the same test. Could you check that token is persisted on TokenStorage?

**Comment by shakly** [comment]
rebootable_client: false dont fix the problem

**Comment by Naktibalda** [comment]
@shakly Could you create a small project to reproduce your issue and publish it on Github?

**Comment by shakly** [comment]
I create a small project : https://github.com/shakly/proofCodeception.git
Use ``` composer init-app ``` to load fixtures

All test are in the api suite.

In version 2.1.7, all test are OK but in version 2.1.9 the second failed
But if i comment first test in version 2.1.7 (GetMeV01), the second failed.

**Comment by raistlin** [comment]
Add 
````
            em_service: 'doctrine.orm.test_entity_manager'
````

To your configuration, but I'm not sure why the alias is not used.

**Comment by shakly** [comment]
I have a fatal error :   
```
[PHPUnit_Framework_AssertionFailedError]                                
Service doctrine.orm.test_entity_manager is not available in container
```
Where should i declare this service ?

**Comment by Naktibalda** [comment]
Are you using Doctrine in your project?

**Comment by shakly** [comment]
Yes, but i use only one entity manager, the default_entity_manager that i override in my config_test.php to use Sqlite database.

**Comment by raistlin** [comment]
Really ````doctrine.orm.default_entity_manager```` is an alias for ````doctrine.orm.test_entity_manager````, just run ```php bin/console debug:container | grep -i entity_manager```

The problem seems to be related to that ```default_entity_manager``` is saved or restored properly because it's a aliased service. I don't have time to look it deeper, but I fear that what's happening is: service ```default_entity_manager``` is saved as an alias for ```test_entity_manager```, ```test_entity_manager``` is recreated, ```default_entity_manager``` is restored as an *alias* for ```test_entity_manager```.

Note: I also had to make some changes on your ````tests/api.suite.yml```` to make it work, like change ````var_path```` to ```app```

**Comment by shakly** [comment]
Ok my bad, i named my connection test in the small project and it's not the same in the real. With the good name it's works !

Thank you for your help
