### ISSUE TITLE
Gherkin snippets error when parsing currency symbols

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#3156]
Not a big issue, but I just spotted that if you have this in your .feature file:

``` gherkin
    Given there is a "football ball" product witch costs "1,5" $
    ...
```

OK: When you run `vendor/bin/codecept g:snippets acceptance` you get:

``` php
    /**
     * @Given there is a :arg1 product witch costs :arg2 $
     */
     public function thereIsAProducWitchCosts($arg1, $arg2)
     {
     }
```

But if you use the `€` symbol instead of `$`

``` gherkin
    Given there is a "football ball" product witch costs "1,5" €
    ...
```

NOT OK: When you run `vendor/bin/codecept g:snippets acceptance` you get:

``` php
    /**
     * @Given there is a :arg1 product witch costs :arg2 €
     */
     public function thereIsAProducWitchCosts?($arg1, $arg2)
     {
     }
```

OK: `$` symbol is ignored
NOT OK: `€` symbol is converted into `?`

**Comment by Naktibalda** [comment]
Please check encoding of your PHP file.
