### ISSUE TITLE
SOAP - PHPBrowser vs SoapClient

### ISSUE THREAD

**Issue by eXorus** [Codeception/Codeception#3157]
Hello,

I'm using SOAP module but I have some issue with some server.

Why do you use PHPBrowser to do SOAP request and not SoapClient from PHP ?

Are you interested to this change ? it will be better implementation I think and we can test SOAP 1.1 and SOAP 1.2.

**Comment by Naktibalda** [comment]
SOAP module is not limited to PhpBrowser, it can use any of the framework modules too.
(I am not familiar with implementation)

**Comment by DavertMik** [comment]
> SOAP module is not limited to PhpBrowser, it can use any of the framework modules too.
(I am not familiar with implementation)

Yes, personally I was running it inside Symfony application and it worked well for me :)

I'm not sure if it is possible to implement SoapClient into SOAP module so that old interfaces would still  work? I mean not to break setup with PhpBrowser or Symfony

**Comment by eXorus** [comment]
I'm using only SOAP module to request external SOAP Server so I'm using only PHPBrowser.
I understand that can be done with WebDriver I don't understand the usage case.
And I don't understand with Symfony how it's work, do you need it to manage model object with SOAP ?

The idea was to have SOAP module without dependency : guzzle, PHPBrowser, WebDriver,... it's only use SoapClient from core PHP.

**Comment by Naktibalda** [comment]
Guzzle is a mandatory dependency of Codeception, so it is always present, as is PhpBrowser which is a part of Codeception.
SoapClient does not belong to core PHP, it belongs to Soap extension and can be missing.
SOAP module can use framework modules in the same way as a REST module, replacing connectors with SoapClient would reduce it's functionality.

**Comment by Naktibalda** [comment]
This question shouldn't be stated as "SoapClient vs PhpBrowser" - SOAP module could use both.

I've never used the SOAP module, how well does it make requests to services that are using complicated WSDL files?

It could be better to leave SOAP request generation and response parsing to SoapClient and use connection module in overriden [__doRequest](http://php.net/manual/en/soapclient.dorequest.php) method
