### ISSUE TITLE
codeception with phpunit 5.4.0 not working

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3160]
codeception 2.2.0-2RC not working with phpunit/phpunit 5.4.0  (today i doing automatic update).
Everytime i have this warning:
[PHPUnit_Framework_Exception]                                              
  Undefined property: Codeception\PHPUnit\Log\JUnit::$attachCurrentTestCase 

last working phpunit/phpunit is 5.3.4

**Comment by DavertMik** [comment]
Thanks. Investigating and fixing this ASAP

**Comment by DavertMik** [comment]
Fixed in 2.2.1. Please update
