### ISSUE TITLE
Bad version constraint for php-code-coverage

### ISSUE THREAD

**Issue by mindplay-dk** [Codeception/Codeception#3164]
Codeception appears to be incompatible with `phpunit/php-code-coverage 4`, yet the package constraint allows this to be installed under PHP 7.

    Fatal error: Class 'PHP_CodeCoverage' not found in /usr/local/bamboo/bamboo-home/xml-data/build-dir/12976130/SCOR-SPB69-TEST/source/vendor/codeception/codeception/src/Codeception/Coverage/Subscriber/Printer.php on line 36

The [constraint](https://github.com/Codeception/Codeception/blob/2.2/composer.json#L22) probably should be changed to `>=2.1.3, <4`

Or?

**Comment by DavertMik** [comment]
Thanks. It is almost fixed. 2.2.1 comes in next hour

**Comment by Naktibalda** [comment]
I wonder if we have more indirect dependencies in the code base.

php-code-coverage was an indirect dependency, pulled in by phpunit. I only added `>=2.1.3` constraint because some code coverage tests were failing with php-code-coverage 2.1.1 in --prefer-lowest build.

**Comment by Naktibalda** [comment]
@DavertMik And 2.1.10 too,right?

**Comment by DavertMik** [comment]
Fixed in 2.2.1. Please update

@Naktibalda yes, releasing this as well
