### ISSUE TITLE
Class 'PHP_CodeCoverage' not found in ... \Codeception\Coverage\Subscriber\Printer, unable to create code coverage

### ISSUE THREAD

**Issue by aedart** [Codeception/Codeception#3165]
In version 2.2.0, you attempt to instantiate a new instance of `PHP_CodeCoverage`. However, this class does not appear to exist in the required version of "phpunit/php-code-coverage".

Think he renamed the class to `\SebastianBergmann\CodeCoverage\CodeCoverage`.
Furthermore, all other PHP Unit related to coverage have also changed

**Comment by DavertMik** [comment]
Yes, PHPUnit 5.4 released today and this was unpredictable break :(
Fixing it now

**Comment by DavertMik** [comment]
Fixed in 2.2.1. Please update

**Comment by aedart** [comment]
Hi again - thanks for fix, I appreciate it a lot :)
