### ISSUE TITLE
Error when running unit test with code coverage

### ISSUE THREAD

**Issue by Henk8** [Codeception/Codeception#3166]
After updating to phpunit 5.4.2 and codecoverage 4.0.0 the following error is given:

Argument 1 passed to PHPUnit_Framework_TestResult::setCodeCoverage() must be an instance of SebastianBergmann\CodeCoverage\CodeCoverage, instance of Codeception\Coverage\DummyCodeCoverage given

The error occurs when running phpunit with the following arguments: --coverage-xml --coverage-html --xml

**Comment by Naktibalda** [comment]
It is fixed by #3163 already
