### ISSUE TITLE
Codecept 2.1.5 and higher issue with Laravel 4.2

### ISSUE THREAD

**Issue by nsmaminebelhassine** [Codeception/Codeception#3167]
We updated our codeception version from 2.1.4 to 2.1.5 ( even 2.1.9 / 2.1.10 ) and we encounter this issue 

> [ErrorException]                                                                                                            
>   Declaration of Illuminate\Console\Application::renderException() should be compatible with Symfony\Component\Console\Application::renderException(Exception $e, Symfony\Component\Console\Output\OutputInterface $output)

> Exception trace:
>  () at /Users/amine/projects/**********/vendor/laravel/framework/src/Illuminate/Console/Application.php:243
>  Illuminate\Exception\Handler->handleError() at phar:///usr/local/bin/codecept/vendor/composer/ClassLoader.php:412
>  Composer\Autoload\includeFile() at phar:///usr/local/bin/codecept/vendor/composer/ClassLoader.php:412
>  Composer\Autoload\includeFile() at phar:///usr/local/bin/codecept/vendor/composer/ClassLoader.php:301
>  Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
>  spl_autoload_call() at /Users/amine/projects/**********/vendor/laravel/framework/src/Illuminate/Foundation/Artisan.php:43
>  Illuminate\Foundation\Artisan->getArtisan() at /Users/amine/projects/**********/vendor/laravel/framework/src/Illuminate/Foundation/Artisan.php:57
>  Illuminate\Foundation\Artisan->__call() at /Users/amine/projects/**********/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:211
>  Illuminate\Foundation\Artisan->call() at /Users/amine/projects/**********/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:211
>  Illuminate\Support\Facades\Facade::__callStatic() at /Users/amine/projects/**********/app/tests/_bootstrap.php:11
>  Illuminate\Support\Facades\Artisan::call() at /Users/amine/projects/**********/app/tests/_bootstrap.php:11
>  include_once() at phar:///usr/local/bin/codecept/src/Codeception/Configuration.php:209
>  Codeception\Configuration::loadBootstrap() at phar:///usr/local/bin/codecept/src/Codeception/Configuration.php:195
>  Codeception\Configuration::config() at phar:///usr/local/bin/codecept/src/Codeception/Command/Run.php:177
>  Codeception\Command\Run->execute() at phar:///usr/local/bin/codecept/vendor/symfony/console/Command/Command.php:256
>  Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:815
>  Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:186
>  Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:117
>  Symfony\Component\Console\Application->run() at phar:///usr/local/bin/codecept/codecept:34
>  require_once() at /usr/local/bin/codecept:7

Any idea ?

**Comment by janhenkgerritsen** [comment]
I am away on holiday, will look at this when I am back home.

**Comment by Naktibalda** [comment]
It looks like a yet another version conflict.

@nsmaminebelhassine Don't use codecept.phar file, install Codeception with composer, installed that way,it will use only compatible Symfony components.

**Comment by nsmaminebelhassine** [comment]
@Naktibalda 👍  it was compatibility issue. I installed codeception using composer and it's working now ( 2.1.10 )
