### ISSUE TITLE
[Codeception 2.2.1] InjectionException with Codeception\TestCase

### ISSUE THREAD

**Issue by eXorus** [Codeception/Codeception#3168]
Hello,

In 2.1.8 this Cest file was working well, now it's broken **[InjectionException] Failed to inject dependencies in instance of 'axisCxfCest'. Class Codeception\TestCase\Cest does not exist** :

```php
use \Step\Api\apiStep;

class testApiCest
{
    public function test(apiStep $I, $scenario, \Codeception\TestCase\Cest $testCase)
    {
        $I->requestSoapProvisioningAPI($testCase);

        $I->callSoapLoginSearch([
            'serviceid' =>  1,
            'loginname' => 'toto',
            ]);
    }
}
```

Accorgind to the changelog I try to change to \Codeception\TestInterface\Cest but I have also an error : 
[InjectionException] Failed to inject dependencies in instance of 'axisCxfCest'. Class Codeception\TestInterface\Cest does not exist

I try also 
[InjectionException] Failed to inject dependencies in instance of 'axisCxfCest'. Failed to resolve dependency 'Codeception\TestInterface'.

Do you have an idea to solve this issue ?

**Comment by Naktibalda** [comment]
Correct name is `Codeception\Test\Cest`
But I don't understand what are you trying to inject here.

**Comment by DavertMik** [comment]
> But I don't understand what are you trying to inject here.

Me too. What are you trying to achieve?

> Correct name is Codeception\Test\Cest

` \Codeception\TestCase\Cest` has its alias to `Codeception\Test\Cest` so its a problem not in naming. 

Please explain what do you want and we will try to help you to achieve that in a more clear way. DI container was too smart in earler versions if it could get this instance for you :)

**Comment by eXorus** [comment]
@Naktibalda if I'm using Codeception\Test\Cest, I have also an error :
[InjectionException] Failed to inject dependencies in instance of 'soapCest'. Failed to create instance of 'Codeception\Test\Cest'. Parameter 'testClass' must have default value.

@DavertMik My usecase is managing different SOAP connexion (2 wsdl) in one test case. I need function to change the endpoint.
```php
public function requestSoapProvisioningAPI ($testcase)
    {
        $endpoint = 'https://api.mycompany.com/services/Provisionning';
        $wsdl = simplexml_load_file('Provisioning.wsdl');
        $schema = $wsdl['targetNamespace'];
        $this->getModule('PhpBrowser')->_reconfigure(array('cert' => ['certprov.cert', 'password']));
        $this->getModule('SOAP')->_reconfigure([
            'endpoint' => $endpoint,
            'schema' => $schema,
            ]);
        $this->getModule('SOAP')->_before($testcase);
    }
public function requestSoapAuthenticateAPI ($testcase)
    {
        $endpoint = 'https://api.mycompany.com/services/Authenticate';
        $wsdl = simplexml_load_file('Authenticate.wsdl');
        $schema = $wsdl['targetNamespace'];
        $this->getModule('PhpBrowser')->_reconfigure(array('cert' => ['certauth.cert', 'password']));
        $this->getModule('SOAP')->_reconfigure([
            'endpoint' => $endpoint,
            'schema' => $schema,
            ]);
        $this->getModule('SOAP')->_before($testcase);
    }
```

I found this code on the internet. I dont understand everything but I think they need to call before to reload the init of SOAP Module.
http://stackoverflow.com/questions/34872451/codeception-soap-namespace

**Comment by eXorus** [comment]
I find another way but it seems very complicated :

In Cest File, I'm using scenario and I'm not injected TestCase :
```php
use \Step\Api\apiStep;

class testApiCest
{
    public function test(apiStep $I, $scenario)
    {
        $I->requestSoapProvisioningAPI($scenario->test);

        $I->callSoapLoginSearch([
            'serviceid' =>  1,
            'loginname' => 'toto',
            ]);
    }
}
```
But property $test is protected in Scenario class so I need to touch the Scenario file pour add public function or change $test to public

**Comment by eXorus** [comment]
Finally I found the better way :)

After _reconfigure() on SOAP, the request is not reconfigured so I implemented onReconfigure() to do the job.

I will send you a PR soon

**Comment by DavertMik** [comment]
Let me do a research, if it is a need for injecting testcase I can probably bring back this functionality. I just didn't have an idea this even can be used this way

**Comment by DavertMik** [comment]
Yes, I think your [PR](https://github.com/Codeception/Codeception/pull/3182) to be much better solution. Thanks!
