### ISSUE TITLE
On POST creation, 201 status with a Location header should not fail

### ISSUE THREAD

**Issue by jterry** [Codeception/Codeception#3171]
In the case of a POST interaction, `InnerBrowser` is aggressively evaluating a redirection response header, and evaluating a response as a failure if the browser is not redirected.

In this particular case, a _Location_ header doesn't indicate a redirection, but instead indicates the location of the created record (defined in boring detail in [RFC2616, 10.2.2](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.2)).

Would there be other issues I'm not seeing by also checking for an HTTP status code of 201 and not interpreting the Location header as a redirect? Even better than that, check for no status code or a [`3xx`](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3) code and then evaluate the purpose of the header?

As a side note, `2.2.1` sees the issue, but `2.1.10` does not.

**Comment by DavertMik** [comment]
Thanks. Probably I encountered this as well. We will try to fix it today

**Comment by jterry** [comment]
Thanks @DavertMik and @Naktibalda! Really enjoying the framework - it's a phenomenal improvement for us consolidating testing.

**Comment by DavertMik** [comment]
Will also merge into 2.2
