### ISSUE TITLE
The "config" option does not exist. 

### ISSUE THREAD

**Issue by Ramk0ff** [Codeception/Codeception#3173]
I've download latest version of codeception (codecept.phar 2.2) and after bootstraping in verbose mode get some errors:

```
[Symfony\Component\Console\Exception\InvalidArgumentException]  
  The "config" option does not exist.                             
                                                                  

Exception trace:
 () at phar:///Users/<username>/job/ecp/<proj_name>/temp/codecept.phar/vendor/symfony/console/Input/Input.php:190
 Symfony\Component\Console\Input\Input->getOption() at phar:///Users/<username>/job/ecp/<proj_name>/temp/codecept.phar/src/Codeception/Command/Build.php:44
 Codeception\Command\Build->execute() at phar:///Users/<username>/job/ecp/<proj_name>/temp/codecept.phar/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///Users/<username>/job/ecp/<proj_name>/temp/codecept.phar/src/Codeception/Command/Bootstrap.php:121
 Codeception\Command\Bootstrap->execute() at phar:///Users/<username>/job/ecp/<proj_name>/temp/codecept.phar/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///Users/<username>/job/ecp/<proj_name>/temp/codecept.phar/vendor/symfony/console/Application.php:815
 Symfony\Component\Console\Application->doRunCommand() at phar:///Users/<username>/job/ecp/<proj_name>/temp/codecept.phar/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///Users/<username>/job/ecp/<username>/temp/codecept.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///Users/<username>/job/ecp/<proj_name>/temp/codecept.phar/codecept:34
 require_once() at /Users/<username>/job/ecp/<username>/temp/codecept.phar:7

bootstrap [-ns|--namespace [NAMESPACE]] [-a|--actor [ACTOR]] [-e|--empty] [--] [<path>]
```

Can you explain what are wrong?
My version PHP - 5.6

**Comment by Ramk0ff** [comment]
Also, I've get the same error when execute build command

**Comment by Naktibalda** [comment]
@DavertMik I think that it has something to do with your build environment.
I reproduced this issue with http://codeception.com/releases/2.2.1/codecept.phar and http://codeception.com/releases/2.2.1/php54/codecept.phar

But I can't reproduce it in my working copy.

**Comment by raistlin** [comment]
I think that it's a version conflict.

**Comment by DavertMik** [comment]
@Naktibalda thanks. I will try to do that.

**Comment by travisdoherty** [comment]
Appears as if the option is removed in 2.2.1  though I did not expect such a version to produce comparability errors. Does codecept subscribe to semantic versioning principals?

**Comment by DavertMik** [comment]
@travisdoherty Sorry. But the issue was not in removal of option. Anyway, 2.2 has some breaking changes but they are considered minor and listed in changelog. What we've seen here is a bug :)

So let me explain. This bug affected phar releases for 2.2.x. Custom Commands PR changed the way CLI application is created and how options are loaded. However, I forgot that for phar we use `package/bin` file instead of `codecept`. So those changes didn't come into Phar and so we had this conflict. Now it is fixed, phars are rebuilt and can be downloaded.

Thanks for report. Sorry for this bug.

**Comment by travisdoherty** [comment]
@DavertMik Confirmed fixed in latest Phar, thanks!
