### ISSUE TITLE
Last dropdown in a form is empty

### ISSUE THREAD

**Issue by crash21** [Codeception/Codeception#3177]
Hello,

I have a weird issue in the latest 2.2 version (well maybe this is happening in older versions as well, I have not tested yet)

So Issue is:

If I have a form with X dropdowns and all of these dropdowns does not have empty field, everytime the last one in the html order is "" when I click the submit button of the form

I have tested it even with 1 or 10 dropdowns, only the last one is getting "" in the post request. 

ie:

    [Parameters] {"form[1]":"","form[_token]":"Z7vieRAH7VWhIzyd_okGxFZMFdmj1s6NRhyHeSkCzPc","notes":"Whatever Notes","product_qty":"10"}

Here form[1] is the only dropdown (and obviously the last)

    [Parameters]  {"form[1]":"1","form[3]":"14","form[5]":"11","form[6]":"15","form[8]":"17","form[10]":"","form[_token]":"lpcbbi7GPoKCBnLcoYmZnMq3KCob3t0fn4_3LFETh9w","notes":"Whatever Notes","product_qty":"10"}

Here form[10] is the last dropdown of the form.

Of course the failing dropdowns does nto have empty value as a default (even when I check this with $I->seeOptionIsSelected, it passes but when it posts something is failing probably)

**Comment by Naktibalda** [comment]
Please add HTML of your form and your test code to your report.

**Comment by DavertMik** [comment]
Not responded. Closing..
