### ISSUE TITLE
Codeception Authentication headers

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3179]
i have a user session id which is stored in the database after user logged in, i want that user id to authenticate (while testing an api) the user using codeception. i don't know where to send this user id (in headers, cookies..?? no idea)... can any help me?

**Comment by Naktibalda** [comment]
How do your normal users authenticate?

**Comment by FaheemSultan** [comment]
with username and pass, i've written some test cases on python and i'm sending this seesion id in cockie, how do i do it with codeception

**Comment by Naktibalda** [comment]
What module are you using for testing? 
If your website sets a cookie, Codeception should be sending it with all following requests automatically.

**Comment by FaheemSultan** [comment]
i'm using Php browser, actually i'm writing test cases for Rest API's, and i need to send this session id with Get,Post,put,del requests, because i dont want to authenticate user every time with username and password

**Comment by Naktibalda** [comment]
Cookies show be handled correctly by the REST module too.
Are you logging-in in every test or in only one test?
