### ISSUE TITLE
Can't use PhpBrowser and WebDriver in different –env

### ISSUE THREAD

**Issue by dima-stefantsov** [Codeception/Codeception#3180]
I have created [a topic in your official community](http://phptest.club/t/using-phpbrowser-and-webdriver-in-different-env/902) a week ago on my issue, but looks like it's pretty dead, so I'll assume this is a bug.

I am trying to run tests through PhpBrowser for fast feedback, and then if it's successful, run it in WebDriver for real testing, though 10x times slower. It worked ok when I was just using one module. When I had to use `Asserts` and `/Helper/Acceptance`, it stopped working. Codeception is acting really weird with how it merges/overrides different configs.

Example command I'm trying to execute:
`codecept run --env phpbrowser --env phantomjs`

PhpBrowser runs fine, then phantomjs tells something like
`[RuntimeException] Call to undefined method AcceptanceTester::waitForText`

It works if I use no other modules but phpbrowser and webdriver. Adding asserts and a helper kills it. Am I doing something wrong? Is this a bug? I have tried countless variants.

**Comment by Naktibalda** [comment]
How do you manage to run test which is using `waitForText` with PHPBrowser?

**Comment by dima-stefantsov** [comment]
From the [topic I linked](http://phptest.club/t/using-phpbrowser-and-webdriver-in-different-env/902/10?u=dima_stefantsov):

![2016 06 07_7 08 10_j3lpyav7 1](https://cloud.githubusercontent.com/assets/1370909/15845737/a015ae5e-2c7e-11e6-9913-6273115297e2.png)

**Comment by DavertMik** [comment]
Maybe this is related to https://github.com/Codeception/Codeception/issues/3292
If so, this should be fixed in 2.2.3

**Comment by dima-stefantsov** [comment]
Looks like it, I definitely experienced different results with different config line positions.
Funny thing, I report early June, no reply. He reports few weeks later, "this is my first priority to work on".
