### ISSUE TITLE
Not provided $_SERVER['SCRIPT_FILENAME'] on mass tests executing

### ISSUE THREAD

**Issue by erickskrauch** [Codeception/Codeception#3181]
Hi. I'm using [Yii2 Advanced app template](https://github.com/yiisoft/yii2-app-advanced) with build in Codeception and try to upgrade from Codeception 2.1.9 to 2.2.1.

All breaking changes was resolved, but something strange behavior happens:

```
root@595c74384624:/var/www/html# ./vendor/bin/codecept run -c tests
Codeception PHP Testing Framework v2.2.1
Powered by PHPUnit 5.4.2 by Sebastian Bergmann and contributors.


[tests\codeception\common]: tests from /var/www/html/tests/codeception/common


Tests\codeception\common.unit Tests (21) -------------------
✔ ... common Unit Tests
------------------------------------------------------------


[tests\codeception\console]: tests from /var/www/html/tests/codeception/console


Tests\codeception\console.unit Tests (1) -------------------
✔ ... console Unit Tests
------------------------------------------------------------


[tests\codeception\api]: tests from /var/www/html/tests/codeception/api


Tests\codeception\api.functional Tests (40) ----------------
✔ ... api Functional tests
------------------------------------------------------------

Tests\codeception\api.unit Tests (51) ----------------------
✔ ComponentTest: Login (0.18s)
E ComponentTest: Renew 
E ComponentTest: Parse token 
E ComponentTest: Get active session 
E ComponentTest: Serialize token 
E ComponentTest: Create token 
E ComponentTest: Get algorithm 
E ComponentTest: Get claims 
E ... and untill the end, all tests will gave Error
------------------------------------------------------------
```

Error is:

```
49) EmailActivationKeyValidatorTest: Validate value
 Test  unit/validators/EmailActivationKeyValidatorTest.php:testValidateValue
                                                                                     
  [yii\base\InvalidConfigException] Unable to determine the entry script file path.  
                                                                                     
#1  /var/www/html/vendor/yiisoft/yii2/web/Application.php:60
#2  /var/www/html/vendor/yiisoft/yii2/base/Application.php:267
#3  /var/www/html/vendor/yiisoft/yii2/base/Object.php:107
#4  /var/www/html/vendor/yiisoft/yii2/base/Application.php:206
#5  yii\base\Application->__construct
#6  /var/www/html/vendor/yiisoft/yii2/di/Container.php:374
#7  /var/www/html/vendor/yiisoft/yii2/di/Container.php:153
#8  /var/www/html/vendor/yiisoft/yii2/BaseYii.php:344
#9  /var/www/html/vendor/yiisoft/yii2-codeception/TestCase.php:123
#10 /var/www/html/vendor/yiisoft/yii2-codeception/TestCase.php:84
```

And if I debug this line, then I see:

![alt](http://dl2.joxi.net/drive/2016/06/06/0004/2001/325585/85/afccc528c3.png)

If I run tests only for one environment (e.g. `./vendor/bin/codecept run unit -c tests/codeception/api`), then all tests pass fine.

What a problem?

**Comment by kossmoss** [comment]
Have same error using Apache/2.2.22. With nginx all tests work well

**Comment by erickskrauch** [comment]
It is not a problem with nginx or apache.
In advanced template this variable is set by `_bootstrap.php` file inside every app folder (e.g. frontend/backend). I can propose, that in Codeception 2.2 was changed behavior of calling `_bootstrap.php` files or this is bug related to `codeception.yml` file with `inlude:` section:

![](http://erickskrauch.ely.by/screenshot-at-12-08-03.png)

**Comment by SteveSimpson** [comment]
I found a fix to the issue, I'm not sure if it will break anything else or not.

app/vendor/codeception/codeception/src/Codeception/Lib/Connector/Yii2.php

Change line 80 ($_SERVER)

```
    public function doRequest($request)
    {
        $_COOKIE = $request->getCookies();
        // was $_SERVER = $request->getServer();
        $_SERVER = array_merge($_SERVER, $request->getServer()); 
```

This is the way it was done in the Yii1.php module and works for me. I've already spent more time than I should of on this one, so I'm going to hand it off.

**Comment by samdark** [comment]
@SteveSimpson how to reproduce the issue starting with bare advanced template? I'm trying hard and have no luck so far.

**Comment by SteveSimpson** [comment]
I did not test with the templates. But I needed a _SERVER variable that was set in config file. It seemed right in line with the open ticket.

If anyone needs the _SERVER variables they will be broken.

**Comment by samdark** [comment]
OK. How to reproduce it w/o template? Could you share a simple test and a set of configs?

**Comment by SteveSimpson** [comment]
I'm not really sure that this is the best way to see / test this issue, but it works. (These are just 2 examples of things that code may need from the web server, they aren't the ones that I'm using.)

Using the basic yii2 template, add the following lines below the other _SERVER variables in
basic/tests/codeception/config/functional.php

$_SERVER['REMOTE_ADDR'] = '1.1.1.1';
$_SERVER['REMOTE_PORT'] = 654321;

then add the test:
basic/tests/codeception/functional/ServerCept.php

<?php

use tests\codeception\_pages\AboutPage;

/* @var $scenario Codeception\Scenario */

$I = new FunctionalTester($scenario);
$I->wantTo('make sure that _SERVER variables are passed to scripts');

AboutPage::openBy($I);

$foo[] = $_SERVER['REMOTE_PORT'];
$foo[] = $_SERVER['REMOTE_ADDR'];





----- Original Message -----

**Comment by SteveSimpson** [comment]
I am just now testing this with the latest codebase ... the whole point at least from my perspective was to be able to pass arbitrary values from the "server" environment.   REMOTE_PORT & REMOTE_ADDR were examples.
