### ISSUE TITLE
How to catch loop redirect in PhpDriver?

### ISSUE THREAD

**Issue by andkirby** [Codeception/Codeception#3184]
I got loop redirect during a test and ran test hangs on.
How to catch it?

Setting max redirects to CURL doesn't help.

**Comment by Naktibalda** [comment]
You have to create your own helper method and setMaxRedirects in it.

```php
class FunctionalHelper extends \Codeception\Module
{
  public function limitRedirectsTo($limit)
  {
    $this->getModule('PhpBrowser')->client->setMaxRedirects($limit);
  }
}
```
Then use it in your tests:
```php
$I-> limitRedirectsTo(5);
```

**Comment by andkirby** [comment]
@Naktibalda, many thanks! It works fine.
