### ISSUE TITLE
Predis\Client not found

### ISSUE THREAD

**Issue by rmrbest** [Codeception/Codeception#3187]
In Redis module, the use of Predis\Client it doesn't exist.

Is anyone that the same thing happen?

Thanks.

Regards,
Raul.

**Comment by Naktibalda** [comment]
"predis/predis" is in require-dev section, so you have to install it yourself if you need it in your project.  
https://github.com/Codeception/Codeception/blob/2.2/composer.json#L46

**Comment by DavertMik** [comment]
Oh, looks like I forgot to add better exception message for this. I think this should be done

**Comment by rmrbest** [comment]
Ok guys, 

Thanks, is solved.

Raul.
