### ISSUE TITLE
Include tests from different folders

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#319]
It's proposed to have an additional config parameter to include tests from other directories, not only for current suite.

```
includes:
  - src/*Bundle/Tests
  - tests/additional
```

In this case we can provide more natural testing for Symfony2 bundles. 
And execute same tests inside of different suites, discussed here: #154 

Pretty simple, yet very helpul feature.

**Comment by skillberto** [comment]
Hello!

I tried to figure how can I run my unit & functional tests from Symfony2 bundles, and acceptance tests from global directory, but I can't solve this.
Could you please tell me the best solution?

The old way:
include:
   - src/*/*Bundle
....
have looked good, but now I have to create a lot's of row for each bundle..

Or do you have a good solution?

Best regards,
Norbert

**Comment by nrobles92** [comment]
So I'm trying to run tests but also trying to keep them separated according to their own module, and in the spirit of full integration actually place them within the php code that its testing. is it possible to run a test with an include statement from the cept or cest file in the suite. To be clear the test code is NOT in the suite only the cept.php file that is using the include statement to get the test.

**Comment by vercotux** [comment]
I'm having a similar issue with Yii2 modules. I want to run the module tests along the main Yii2 app tests (all at once). The first step is simple:

    include:
        - frontend
        - backend
        - common
        - vendor/vercotux/yii2-module

This works beautifully for modules that do not require database access. However everything comes crashing down when a module needs database access. The module obviously cannot include its own db config, so it has to somehow get it from the main app. I've tried many configurations in an attempt to do this but no luck so far. Is this even supported by Codeception or am I just doing it wrong?
