### ISSUE TITLE
new function - grabFile() or something else

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3193]
My situation
I writing tests on my local device (windows) and if is test done, i doing move this test to Jenkis.

Jenkins is installed on some server. On different machine (linux) running java and selenium and browsers.

In my new test with webdriver, i need doing this:
1) in html table i have some strings
2) i click to some button and this doing move this strings to some file and delete previous table 
3) right now i see many files names (by date) with download links to file
4) click to download link, and Chrome doing save file to some dir (on my linux machine is /home/tester/Downloads/, on my local machine with windows is \Users\MyProfile\Downloads\)
5) i need open downloaded file and check, if file contain strings from previous table

My problems:
1) How open downloaded file (linux and windows doing save to different dir)
2) How doing automatically delete file from dir

My idea:
Create to Codeception new option, something as:
grabFile($I->click('Download'));
and tester will have from previous function this two things: file name (for example: myFile.txt) and file contents (for example: this is my string saved in myfile.txt)

Or can somebody help me write script?

I think I'm not only one who needs to test the downloaded file...

**Comment by DavertMik** [comment]
Sorry, this request is not about cahnge in WebDriver. This needs to be implemented in separate module. Currently our code team doesn't have plans for implementing that. However you can have a helper that does it or search for already existing [Codeception Addons](http://codeception.com/addons) if they do something like that
