### ISSUE TITLE
AMQP module should purge some specific queues in tests

### ISSUE THREAD

**Issue by niclopez** [Codeception/Codeception#3195]
Hi Codeception team,

I would like to contribute adding some public methods to AMQP module:

+purgeQueue(String queueName) : void
+purgeAllQueues() : void

With these methods you should "purge" a specific queue whenever necessary. In certain scenarios, the "purge" (true) config param is too general because all queues are purged on every test execution.

You should purge a specific queue in your tests like this:

$I->purgeQueue('some-queue-name');
...
$I->purgeAllQueues();

**Comment by Naktibalda** [comment]
You are welcome to do that.
