### ISSUE TITLE
tearDownAfterClass() not run at end of phpunit test classes

### ISSUE THREAD

**Issue by auxbuss** [Codeception/Codeception#3198]
Version tested: 2.2.1

When porting a large phpunit test suite to codeception, all `tearDownAfterClass()` calls are being made after _all_ tests have run instead of after the completion of tests in a class.

This, of course, causes tests to fail that work fine when run as a class.

**Comment by auxbuss** [comment]
In https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Subscriber/BeforeAfterTest.php, it looks like `beforeClass()` and `afterClass()` have been attached to the wrong event, namely `SuiteEvent`.

**Comment by DavertMik** [comment]
Unlike PHPUnit Codeception doesn't rely on tests order. If you enable `shuffle: true` in configuration all tests from different test cases will be executed in random order. This is why we can't say where testcase class started and where it ended. 

So yes, all beforeClass and afterClass handlers are executed in the very beginning/end of a suite.

Right now I don't see a good way except dirty hooks to make tearDownAfterClass work as you expect. Probably you can have it refactored to move this cleanup things to `tearDown`?
