### ISSUE TITLE
REST module, mark methods

### ISSUE THREAD

**Issue by Dell-** [Codeception/Codeception#3220]
Since, according to the rfc7231 specification, entity creation requests can have the Location header.
I have a proposal to mark these methods with the next tags: @part xml and @part json

\Codeception\Module\REST::stopFollowingRedirects
\Codeception\Module\REST::startFollowingRedirects

**Comment by DavertMik** [comment]
Yes, thanks for creating an issue. Added this to PR https://github.com/Codeception/Codeception/pull/3228
