### ISSUE TITLE
Diff should show only affected lines

### ISSUE THREAD

**Issue by k0pernikus** [Codeception/Codeception#3230]
Given these two strings:
```
$leExpectedXml = <<<XML
<note>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend!</body>
</note>
XML;

$leActualXml = <<<XML
<note>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder
    </heading>
    <body>Don't forget me this weekend!</body>
</note>
XML;
```

and running:

```
$this->assertEquals(
    $leExpectedXml,
     $leActualXml,
     'le xmls should be the same'
);}
```

I get the output:

```
Fail  Failed asserting that two strings are equal. ( -Expected | +Actual ) 
- '<note>
-     <to>Tove</to>
-     <from>Jani</from>
-     <heading>Reminder</heading>
-     <body>Don't forget me this weekend!</body>
- </note>'
+ '<note>
+     <to>Tove</to>
+     <from>Jani</from>
+     <heading>Reminder
+     </heading>
+     <body>Don't forget me this weekend!</body>
+ </note>'
```

I expect it to look like:

```
  --- Expected 
  +++ Actual
  @@ @@
   <note>
       <to>Tove</to>
       <from>Jani</from>
  -    <heading>Reminder</heading>
  +    <heading>Reminder
  +    </heading>
       <body>Don't forget me this weekend!</body>
   </note>
```

I am going to work on a pull request for this as requested by @Naktibalda on [a related stackoverflow question](http://stackoverflow.com/questions/37858060/how-to-get-more-readable-diff-for-codeception-asserteequals-string).

**Comment by DavertMik** [comment]
Yes, that's good idea. Waiting for PR for that. If you will questions on implementation you can ask them here.

**Comment by k0pernikus** [comment]
Thanks @DavertMik, I do have some question, yet not so much about the implementation more in regards of setting up the dev enviorment, please take a look at #3235 and more importantly at #3234.

I *think* I located the issue in how the message is built in the `Subscriber/Console.php`:

```
if ($e instanceof \PHPUnit_Framework_ExpectationFailedException) {
    if ($e->getComparisonFailure()) {
	$comp = $e->getComparisonFailure();
	if ($comp->getDiff()) {
	    $message = $this->message($comp->getMessage())->append(" ( <comment>-Expected</comment> | <info>+Actual</info> ) \n");
	    $message->append("- <comment>" . str_replace("\n", "\n- ", $comp->getExpectedAsString()))->append("</comment>\n");
	    $message->append("+ <info>" . str_replace("\n", "\n+ ", $comp->getActualAsString()))->append("</info>\n");
	}
    }
}
```

I think one ought to use the message from the `$comp->getDiff()` itself and apply coloring as postprocessing. Shouldn't take that long to implement. And I might take some time in tidying up that codebase :)

**Comment by k0pernikus** [comment]
With the updated pull request the example assert now looks somewhat like this:

![selection_208](https://cloud.githubusercontent.com/assets/436935/16180258/91135120-3680-11e6-954e-656a4c0de0b9.png).
