### ISSUE TITLE
Doctrine2 / DataFactory cleanup

### ISSUE THREAD

**Issue by buffcode** [Codeception/Codeception#3233]
Within my acceptance / functional tests I call some actions from a Symfony project which fetches and returns database entries. For this to work, the Doctrine2 module needs to flush the entities created by DataFactory.
This requires `cleanup: false` for Doctrine2 module to disable the transaction mode.
But this also implies that the DataFactory triggers `deleteSaved`, which itself is called after `Doctrine::_after` which again closes the EntityManager.
Therefore all `AbstractStore::delete` calls will fail because of a "The EntityManager is closed" exception by Doctrine.

**Comment by DavertMik** [comment]
Did you try to change the order of modules in list? If DataFactory would be listed before Doctrine its hooks should be executed before.

**Comment by buffcode** [comment]
Changing the order of the modules also gives an error.
With DataFactory being defined before Doctrine, although DataFactory being dependent on Doctrine2, the storage will no be set. Therefore the entity won't be persisted and DataFactory throws an `SaveMethodNotFoundException` exception.
