### ISSUE TITLE
As a developer how do I run the tests locally?

### ISSUE THREAD

**Issue by k0pernikus** [Codeception/Codeception#3234]
I have checked out the codebase and installed all the dependencies via composer. I was expecting the tests to work.

I was surprised that `./codecept run` required a selenium instance and I didn't find it explained anywhere.

Yet even just running the unit tests I get loads of errors:
```
Unit Tests (849) -----------------------------------------------------------------------------------------------------------------------------------------------------------
✔ ModuleContainerTest: Actions explicitly set for not inherited module (0.0s)
E RedisTest: Grab from redis z set all 
E PhpBrowserTest: See in field on radio 
E RedisTest: See in redis existing string with correct value 
✔ GeneratePhpunitTest: Create with suffix (0.7s)
✔ SuiteManagerTest: Run (0.0s)
E PhpBrowserTest: Submit form with multi select 
```

etc. pp. even though I expected them to be green.

How am I supposed to run the tests?

**Comment by k0pernikus** [comment]
I just realized that travis is setup, and hence I added my fork to travis-ci.org and it currently runs a tests against my working branch. So, can it be that the tests are not meant to be run locally? ^^

I don't want to push a commit just to see if the tests are green ;)

**Comment by Naktibalda** [comment]
composer.json can't require existence of http and database daemons.

`php robo.phar test:launch-server` launches 2 `php -S` daemons required by PhpBrowserTest, PhpBrowserRestTest and web suite.
It also tries to launch selenium.jar, but I've never had it in that location.

To run Mysql and Postgresql tests you need to have mysql and postgres daemons running.
But if they aren't running, tests fail gracefully (Skipped).
RedisTest is very new (added in 2.2 only),  and apparently nobody made it fail gracefully yet.

**Comment by k0pernikus** [comment]
Thanks @Naktibalda . These information should be added to either the Readme.md or the `Contributing.md` or maybe there should be some dev docs. As the current `docs` folder seems only to contain information about how to use codecetion and not about how to develop it further.

Regarding robo, there seems that some vendor codebase also has an issue with php7:

```
$ robo
PHP Fatal error:  Uncaught InvalidArgumentException: Expected a string. Got: boolean in /home/philipp/src/codeception/vendor/webmozart/assert/src/Assert.php:133
Stack trace:
#0 /home/philipp/src/codeception/vendor/phpdocumentor/reflection-docblock/src/DocBlock.php(60): Webmozart\Assert\Assert::string(false)
#1 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/Parser/CommandDocBlockParser.php(48): phpDocumentor\Reflection\DocBlock->__construct(false)
#2 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/Parser/CommandInfo.php(462): Consolidation\AnnotatedCommand\Parser\CommandDocBlockParser->parse(false)
#3 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/Parser/CommandInfo.php(168): Consolidation\AnnotatedCommand\Parser\CommandInfo->parseDocBlock()
#4 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/AnnotatedCommandFactory.php(123): Consolidation\AnnotatedCommand\Parser\CommandInfo->hasAnnotation('hook')
#5 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/ in /home/philipp/src/codeception/vendor/webmozart/assert/src/Assert.php on line 133
ERROR: Uncaught InvalidArgumentException: Expected a string. Got: boolean in /home/philipp/src/codeception/vendor/webmozart/assert/src/Assert.php:133
Stack trace:
#0 /home/philipp/src/codeception/vendor/phpdocumentor/reflection-docblock/src/DocBlock.php(60): Webmozart\Assert\Assert::string(false)
#1 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/Parser/CommandDocBlockParser.php(48): phpDocumentor\Reflection\DocBlock->__construct(false)
#2 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/Parser/CommandInfo.php(462): Consolidation\AnnotatedCommand\Parser\CommandDocBlockParser->parse(false)
#3 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/Parser/CommandInfo.php(168): Consolidation\AnnotatedCommand\Parser\CommandInfo->parseDocBlock()
#4 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/AnnotatedCommandFactory.php(123): Consolidation\AnnotatedCommand\Parser\CommandInfo->hasAnnotation('hook')
#5 phar:///usr/bin/robo/vendor/consolidation/annotated-command/src/ 
in /home/philipp/src/codeception/vendor/webmozart/assert/src/Assert.php:133
```

**Comment by Naktibalda** [comment]
I have no issues with Robo version 0.6.1 on PHP 7.0.7

**Comment by Naktibalda** [comment]
Here is a relevant part of Codeception dependency tree:

```
phpunit/phpunit 5.4.6 The PHP Unit Testing framework.
|--phpspec/prophecy ^1.3.1
|  |--phpdocumentor/reflection-docblock ^2.0|^3.0.2
|  |  |--phpdocumentor/reflection-common ^1.0@dev
```

I can't imagine how it could affect Robo.

**Comment by Naktibalda** [comment]
Anyway, it simply runs `php -S 127.0.0.1:8010 -t tests/data/rest` and `php -S 127.0.0.1:8000 -t tests/data/app`.

And, answering your another question, I've never ran entire `unit` suite locally, I only run relevant tests.

**Comment by DavertMik** [comment]
This issue was moved to http://phptest.club/t/as-a-developer-how-do-i-run-the-tests-locally/981

**Comment by DavertMik** [comment]
https://github.com/Codeception/Codeception/tree/2.2/tests

**Comment by DavertMik** [comment]
Not sure if this is complete one but please refer to this guide. Probably it can be improved
