### ISSUE TITLE
How to setup development environment?

### ISSUE THREAD

**Issue by k0pernikus** [Codeception/Codeception#3235]
As a developer I quickly want a state where I can start coding. Since the project lacks a docker-compose setup, I used my local machine and installed dependencies as errors occured, e.g. `php-sqlite3`, `php-bcmath`, and `php-mongodb`.

Yet I soon will forget what I needed to do to get the project started and hence would like, in an ideal world a docker/docker-compose stack, or docs explaining what needs to be installed.

**Comment by DavertMik** [comment]
This issue was moved to http://phptest.club/t/how-to-setup-development-environment/982

**Comment by DavertMik** [comment]
Actually we have docker setup 

http://codeception.com/docs/12-ParallelExecution#Docker
