### ISSUE TITLE
Need .cov file format for being able to merge multiple coverage reports

### ISSUE THREAD

**Issue by delatbabel** [Codeception/Codeception#3245]
phpcov https://github.com/sebastianbergmann/phpcov requires coverage reports that are generated in PHP_CodeCoverage *.cov files.  Running codeception with the --coverage-php option reports:

    [RuntimeException]
    The "--coverage-php" option does not exist.

See also https://github.com/Codeception/Codeception/issues/1679

This should just be a matter of recognising the --coverage-php option and passing it to phpunit.

**Comment by DavertMik** [comment]
Does simple `--coverage` not producing the expected result?
By default PHP report is always printed and saved in `tests/_output/coverage.serialized` which should be compatible with php cov format

**Comment by delatbabel** [comment]
Thanks for the information. I have left the organisation where this was an issue but I will pas it on to them.

**Comment by mikkelcp1** [comment]
It would be nice to be able to work with coverage reports ( per suite and overall ), where you simply want to merge coverage after the coverage is collected per test suite. 

One option: Allow the user to override the '--coverage' flag with a non-default file name, i.e. 'coverage-unit.serialized'. Alternative is to rename file in build script.

Provide a command (like the following quick code taken from phpcov merge) to merge and generate reports only.  Might be helpful for others...

i.e. the following:
`  /**
     * Merges codeception captured Coverage files, so we can see them indiviually or overall
     *  i.e. pass them into SonarQube (unit, intergration, overall)
     * 
     * @param $outfilepath - output coverage file.
     * @param $infilepaths - inputs coverage file(s).
     */
    public function merge(string $outfilepath, array $infilepaths)
    {
        $mergedCoverage = new \SebastianBergmann\CodeCoverage\CodeCoverage;
      
        echo "\n\n";
        
        foreach ($infilepaths as $coverageFile) {
            $contents = file_get_contents($coverageFile);
            $coverage = @unserialize($contents);
            if( $coverage == false)
            {
                $coverage = include "$coverageFile";
            };
            
            if ($coverage === false || !($coverage instanceof \SebastianBergmann\CodeCoverage\CodeCoverage)) {
                echo "'$coverageFile' is not a CodeCoverage serialized file.\n";
                continue;
            }
            else
            {
                echo "Adding Coverage from '$coverageFile'\n";
            }
            $mergedCoverage->merge($coverage);
            unset($coverage);
        }
      
        echo "Writing merged CloverReport to $outfilepath\n";
        $writer = new \SebastianBergmann\CodeCoverage\Report\Clover;
        $writer->process($mergedCoverage, $outfilepath);
        echo "Finished Writing merged CloverReport to $outfilepath\n";
        
        echo "Writing merged Text to $outfilepath.txt\n";
        $writer = new \SebastianBergmann\CodeCoverage\Report\Text(
            //$this->settings['low_limit'],
            //$this->settings['high_limit'],
            //$this->settings['show_uncovered'],
            //false
            );
        file_put_contents(
            "${outfilepath}.txt",
            $writer->process($mergedCoverage, false)
            );
        echo "Finished Writing Text CloverReport to $outfilepath.txt\n";

    }
`
