### ISSUE TITLE
selectOption - select option from different selector

### ISSUE THREAD

**Issue by eXorus** [Codeception/Codeception#3246]
Hello,

Module :  WebDriver
Version : 2.2.1
Browser : Firefox

```html
<select id="select1">
<option value="select1_value1">Value1</option>
<option value="select1_value2">Value2</option>
</select>

<select id="select2">
<option value="select2_value1">Value1</option>
</select>
```

```php
$I->selectOption('#select2', 'Value2');
```

**Actual behaviour**
The value "Value2" in field "#select1" is selected

**Expected behaviour**
Failed to select the value "Value2" because it is not in "#select2" field.

**Comment by eXorus** [comment]
The issue is here in Module/WebDriver.php:selectOption() :

```php
if (key($option) !== 'value') {
    foreach ($option as $opt) {
        try {
            $wdSelect->selectByVisibleText($opt);
            $matched = true;
        } catch (NoSuchElementException $e) {
        }
    }
}
```

SelectOption doesn't care about the selector it take only the value to do the selection.

**Comment by raistlin** [comment]
@eXorus Please add some tests on your branch and submit a pull request.
