### ISSUE TITLE
Get symfony container parameter

### ISSUE THREAD

**Issue by samusenkoiv** [Codeception/Codeception#3251]
I'd be great to be able to grab symfony container parameters. Something like $I->grabContainerParameter($key)

**Comment by raistlin** [comment]
Why do you need grab a parameter while testing?

What's your use case?

**Comment by samusenkoiv** [comment]
e.g. make sure a service is affected by some of attributes.

But since you asked me the question I started having doubts whether this is necessary...
What do you think?

**Comment by raistlin** [comment]
Just because parameters are on container for application use doesn't mean that you as tester need to have access to them.

From my point of view, you as a tester, only need to get the services (class instances) and test they work properly as they are configured on your app.

If you need to test the behavior of your class when some parameter has some specific value, you are not doing a functional or acceptance test: you need a unit test suite.
And unit test suite do not need the framework configuration. You simply instantiate your class to be tested and you inject the 'parameters' at the constructor or set them via setters.

I think that exposing ```getParameter``` method is a bad idea, because some users will start to test behaviors that should be tested on unit suites instead than on functional or acceptance ones.

**Comment by samusenkoiv** [comment]
I think you're right.

**Comment by iquito** [comment]
I think there are valid use cases which need parameter values - in my case for dynamic routes, where route prefixes can be defined in Symfony parameters. I can only do my functional tests if I know what URL to call, and the prefix for that URL is contained in the Symfony configuration of the application. Dynamic routes are generally a valid use case for parameter value access, and probably there are other use cases, especially when testing packages/bundles which are highly configurable by parameter values.

**Comment by raistlin** [comment]
I'm strongly against exposing ```getParameter``` because of my reasons two comments above.

@Codeception/committers What are your thoughts?

**Comment by janhenkgerritsen** [comment]
In the Laravel module I expose the Laravel Application object through a `getApplication` method. This application object is also Laravel's IoC container. This provides a lot of flexibility for the users, which can be helpful in uncommon test scenarios.

**Comment by idchlife** [comment]
I'm testing whether my UserListener service in Symfony2 is doing something when I update some entity. So fields that are should be checked when I update entity are listed in the parameters in config.yml file.
What do you call this test? Integrational? Behaviour? I'm not sure this is unit test but I'm writing one for this case right now!

Actually, to be more clear, I write UserListener that prevents ordinary, not admin user to change users important fields. And I wan't to test if it's working. Create user, call from console, get error 'you are not allowed changing value from console if not root and from web if not admin'.

Sooo I want to test it on first available parameter, which is... Specified in the config.yml in parameters section.

**Comment by djhenk** [comment]
In Symfony, if you want to have the container anyway, you can do:

```
$I->grabService('kernel')->getContainer();
```

There is valid use case for this. I am adding tests to a legacy application that is being migrated to Symfony. There is no clean way to do dependency injection from Codeception to that legacy application, but parts of it are already migrated and need Doctrine. The current workaround in the application is that the Symfony container is added to the legacy container.

This is not a nice solution and we want to refactor it. Before we can refactor it, however, we have to write tests that can handle this situation.

**Comment by ebuildy** [comment]
Use case for me, compare translated strings (check error message is here, if locale is respected etc..).
