### ISSUE TITLE
Codecoverage segfault on acceptance tests

### ISSUE THREAD

**Issue by ivansal** [Codeception/Codeception#3258]
`PHP 7.0.7`
`codeception 2.2.1` 
`PHPUnit 5.3.5-15-ga606146`
`selenium 2.53.0`

When I write in my test `$I->amOnPage('/');` `PHP CLI Server` shuts down with Segmentation fault

**Comment by Naktibalda** [comment]
It is a known issue, wait for xdebug 2.4.1
https://bugs.xdebug.org/view.php?id=1246#c3609
