### ISSUE TITLE
laravel5 + REST + amLoggedAs

### ISSUE THREAD

**Issue by dmoreno** [Codeception/Codeception#3259]
I am using Codeception + Laravel5 module + REST module.

In one of my tests, I have to do two requests with sendPOST method. My problem is, at second time, request is not authenticated. Although I write again "$I->amLoggedAs($user)" before "$I->sendPost(...)".

I am reading the code of Laravel5 module and I see the application is refreshed with second request. If I comment [this line](https://github.com/Codeception/Codeception/blob/2.2.0/src/Codeception/Lib/Connector/Laravel5.php#L89) I dont lose authentication and this test works perfectly. But I understand this application refresh is needed for functional testing.

Recently, @janhenkgerritsen fix a related issue #2904 but I think it is not the same problem. 

How do I keep authentication between requests?

**Comment by janhenkgerritsen** [comment]
I am currently investigating another issue where the Laravel en REST modules are combined, and it is possible that issue is also related to your problem. I just wanted to let you know I am aware of your issue, but that it can take a while before I come up with a solution for the problem

**Comment by dmoreno** [comment]
Ok, @janhenkgerritsen. Thanks for your work in Laravel5 module!

**Comment by janhenkgerritsen** [comment]
@dmoreno Sorry that it took so long for me to look into this issue. But I haven't been able to reproduce this issue myself. Could you first test if this issue still exists with the 2.2 development branch of Codeception? You can use this development branch by specifying `2.2.x-dev` as the version for Codeception in your `composer.json` file.

If the issue still exists, is it possible for you to recreate the issue in a small sample application with the minimal amount of code and upload it to GitHub? That way I can debug the code myself and hopefully find a solution.

**Comment by dmoreno** [comment]
It is still happening in ```2.2.x-dev``` development branch.

I think the issue is easy to get. You need a working Laravel project with user authentication. And the code in test could be:

```javascript
$user = User::find(1);
$I->amLoggedAs($user);
$I->sendPOST('/usr/to/post', []);
$I->sendPOST('/usr/to/post', []);
```

First ```sendPost``` will work, but second don't. With the second request user is not authenticated. I think [something is reinitialized in second request](https://github.com/Codeception/Codeception/blob/fe04a82c36fe87ba031f6127f425338c97db717d/src/Codeception/Lib/Connector/Laravel5.php#L112) and authentication is lost in that moment.

@janhenkgerritsen, have you tried some example similar to this?

**Comment by janhenkgerritsen** [comment]
I could not replicate your issue in [this test project](https://github.com/janhenkgerritsen/codeception-issue-3259).

I added the Sqlite database and .env file to the repository, so after cloning the repo and running `composer install` you should be able to run the test with `codecept run`.

**Comment by dmoreno** [comment]
Hi, @janbogdanski. I'm not familiar with Laravel 5.3 yet. Could you modify your example to use API routes with api middleware? Your POST request is made through web interface.

This way, it would be closer to my case.

**Comment by janhenkgerritsen** [comment]
@dmoreno In that case it would be better if you would setup a minimal test project yourself that  replicates your issue, because it will depend on how you setup authentication for you API.
