### ISSUE TITLE
Getting Some Class Coverage on Acceptance and Functional but 0% on everything else

### ISSUE THREAD

**Issue by Alioo** [Codeception/Codeception#3260]
[Deleted]

**Comment by Naktibalda** [comment]
Your index.php file looks suspicious - it isn't a single point of entry to your website.
You have to include c3.php in every php file which can  be accessed by a browser directly.

**Comment by Alioo** [comment]
@Naktibalda That would make sense, There are a very large amount of pages like that. I guess a sed command could do work on that I'll try it out and see what happens.

**Comment by Alioo** [comment]
@Naktibalda So I added these and that looks to have been the problem, however I had to change remote to true in both codeception.yml and acceptance.suite.yml and now when the suite finishes running and coverage is supposed to start I get this error.

` [UnexpectedValueException]
  internal corruption of phar "/private/var/folders/kz/b_s6x3p95b13ycbh267m2z2r0000gn/T/C3LP0PU2.tar" (__HALT_COMPILER(); not found)`

I read something about adding allowed IP addresses (assuming it needs to be localhost) in my index.php file, does that apply here? (from this ticket https://github.com/Codeception/Codeception/issues/1612)

**Comment by Naktibalda** [comment]
IP advice was specific to Yii framework.
The part which applies to you is to var_dump($contents) in https://github.com/Codeception/Codeception/blob/2.0.9/src/Codeception/Coverage/Subscriber/LocalServer.php#L126

or https://github.com/Codeception/Codeception/blob/2.2.1/src/Codeception/Coverage/Subscriber/LocalServer.php#L132

**Comment by schmunk42** [comment]
Looking into the tar may be helpful, in my case I found PHP error messages there.
