### ISSUE TITLE
Failure screenshot invalid when _after or _failed do some operations

### ISSUE THREAD

**Issue by LeRondPoint** [Codeception/Codeception#3264]
Many of my tests need to do some cleanup on Google Analytics to prevent hitting their services limits.  I do this in _after & _failed methods and the process involves browsing away from the current page.  Therefore, the "Failed test" screenshot is not representative of the actual failure since it is taken after the cleanup, making it useless.

I know my cleanup process is far from ideal but it remains the best way to do it at the moment and I believe it is still a valid use-case.

**Comment by raistlin** [comment]
I suggest you to disable Google Analytics API calls on testing environments, and replace them by a fake service or nothing at all. That way you don't need a cleanup process.

If you *must* maintain that API calls for some good reason, I will try to perform the cleaup on _before method: on _after & _failed you can save required data somewhere and afterwards check in _before if that data exists, perform the cleanup, and erase the data to prevent double cleaning.

**Comment by LeRondPoint** [comment]
Your _cleanup proposal would not work as it would always leave a dangling object (the last run test in the suite).

I'm not a fan of using mock objects in acceptance tests.  Mocking an object when you are trying to be as close to the end user's experience as possible seems to defeat the purpose.

With that said, I did think of an alternative to my cleanup that would allow screenshots to work (making an ajax GET request using executeJS.

Anyways, it remains that I think we need a willFail event that will allow to take the screenshot at the right time (before the tests _failed gets called).

**Comment by LeRondPoint** [comment]
It should be noted that the stack trace is also invalid as it includes the steps from the _failed or _after methods

**Comment by DavertMik** [comment]
Yes, `_after` calls is a part of test scenario the same way as it is for `_before`. Where do you receive a failure btw? You could just wrap your action into try/catch block to prevent it from failing

**Comment by LeRondPoint** [comment]
Sure it's part of the callstack of your application but it has nothing to do with your failure and doesn't help you debug or find the source of the problem at all.

**Comment by DavertMik** [comment]
I think you should just manually call `$I->saveScreenshot` for debugging. That's all I can recommend
