### ISSUE TITLE
Error when composer exec codecept generate:cept acceptance Welcome

### ISSUE THREAD

**Issue by yoongkang0122** [Codeception/Codeception#3275]
Don't know why this exception is throw. I am using Laravel 5.2.*  . 
                                         
 

>  [Symfony\Component\Yaml\Exception\ParseException]   
>   Unable to parse at line 14 (near "    part: ORM").  

Previous Laravel 5.1.* have no this issue

**Comment by Naktibalda** [comment]
It looks like you have a syntax error in your configuration.
Please show your functional.suite.yml

**Comment by yoongkang0122** [comment]
> class_name: AcceptanceTester
> modules:
>     enabled:
>         - PhpBrowser:
>             url: http://localhost/
>         - Laravel5
>             part: ORM
>             cleanup: false # can't wrap into transaction
>         - \Helper\Acceptance

This is the exact copy from Codeception official website

**Comment by yoongkang0122** [comment]
@Naktibalda  I found the issue already.Thanks for pointing it out.
The documentation miss a colon after Laravel5
> - Laravel5:

**Comment by yoongkang0122** [comment]
But another issue is arise after i fixed this issue 

>    [ReflectionException]                              
>     Class \AppBundle\Helper\Functional does not exist

Can you help me? I am new to Codeception

**Comment by janhenkgerritsen** [comment]
I created a pull request (https://github.com/Codeception/codeception.github.com/pull/107) to fix this issue in the documentation.
