### ISSUE TITLE
Yii1 module conflicts with WebDriver

### ISSUE THREAD

**Issue by mariusz-kraj-c** [Codeception/Codeception#3277]
Hi,

I was using codeception 2.1.8 with Yii 1.1.5 but there was problem with switchToIframe method from InnerBrowser and WebDriver. I updated codeception to 2.2.1 ant this came out:

    Yii1 module conflicts with WebDriver

I know that this is the same error, but is there a way to use WebDriver alongside Yii1?

**Comment by Naktibalda** [comment]
Please explain why you need both and give an example of your test.

**Comment by DavertMik** [comment]
I think Yii1 module needs to be parted in the same manner as other framework modules. Anyway, I'd like to see usage examples as well

**Comment by mariusz-kraj-c** [comment]
I want to test my app using selenium and in the same moment i want to initialize Yii with testing config.

**Comment by DavertMik** [comment]
ok, makes sense. Do you use some methods from Yii module or not?

**Comment by Naktibalda** [comment]
It does not make sense.
When using WebDriver, Codeception can not affect configuration of website under test.

**Comment by mariusz-kraj-c** [comment]
@Naktibalda Yes, but sometime i need to use models or services during the test to set some data or find id i could use and for that i need to initialize Yii1 module.

**Comment by Naktibalda** [comment]
You can create your own helper class and use Yii2 module as a dependency: http://stackoverflow.com/questions/37816414/codeception-2-2-api-tests-zf2-and-phpbrowser-module-together

**Comment by mariusz-kraj-c** [comment]
@Naktibalda it work great. Thank you :)

**Comment by DavertMik** [comment]
@Naktibalda i think that's the case for parts. `orm` and `service` should apply to Yii1 as well as it is for Yii2

**Comment by mariusz-kraj-c** [comment]
@DavertMik i also think it would be much better way.

**Comment by Naktibalda** [comment]
@DavertMik What's a point of loading module with no public methods?
The helper is still necessary.
