### ISSUE TITLE
Bootstrap doesn't seem to work (Win7, PHP 7 x64)

### ISSUE THREAD

**Issue by Muzical84** [Codeception/Codeception#3281]
All I'm getting in my command line when I try and run php vendor/bin/codecept bootstrap is the below text:

```bash
dir=$(d=${0%[/\\]*}; cd "$d"; cd "../codeception/codeception" && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/codecept" "$@"
```

I'm running PHP.net's thread-safe 64-bit PHP 7 for Windows, so no cygwin or anything.  PHP is in my path and php --version works.

If I try codecept.bat bootstrap, I get the following:

```bash
@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../codeception/codeception/codecept
php "%BIN_TARGET%" %*
```

Can anyone give some guidance?  What I know about bash scripting would fit on the head of a pin :(
Thanks!

**Comment by Naktibalda** [comment]
@Muzical84 Could you let us know how did you solve this issue?

**Comment by kuflievskiy** [comment]
@Muzical84 @Naktibalda 
Hi, guys! Have you found solution for this problem? 
I am trying to run codeception on Windows. ( virtualbox + vagrant ).

**Comment by kentpachi** [comment]
Same here ,

how did you manage to fix it please ?

**Comment by qamate** [comment]
Try using lower version of PHP. It looks like, this is the reproducable issue with PHP 7.

http://mayurshah.in/1519/getting-error-message-vendor-codecept-generate-acceptance

**Comment by yoyaye** [comment]
No need to use php loader. go to "bin/" and type "codecept bootstrap", but then folder "tests" will be created in "bin"

**Comment by linslin** [comment]
Just use the bat file on windows with backslashes as directory separator and you will be fine:

`vendor\bin\codecept.bat bootstrap`

**Comment by test1git1** [comment]
Hi, I had the same problem. In my case delete php from the begining of the command, and it works. So my command look like
bin\codecept.bat bootstrap --empty

**Comment by JaneMax** [comment]
@linslin also it's works and with simple slashes: `vendor/bin/codecept.bat run`

**Comment by zfk513** [comment]
oh ,thx guys, the official quick start is really bad

**Comment by Yiannistaos** [comment]
This worked for me:

```vendor\\bin\\codecept.bat bootstrap```
