### ISSUE TITLE
Gherkin Method Codeception\Step\Comment::__toString() must return a string value

### ISSUE THREAD

**Issue by bennsel** [Codeception/Codeception#3296]
I want to use the new Gherkin feature, but with my php5.6 and php7 an error occured.

`[PHPUnit_Framework_Exception] Method Codeception\Step\Comment::__toString() must return a string value`

I analyzed it and the function runStep in src/Codeception/Test/Gherkin.php called

`$this->getScenario()->comment(null);`

Then throws the __toString in src/Codeception/Step/Comment.php the exception. 

I fixed it with following code

`return (string)$this->getAction();`

**Comment by wojo1206** [comment]
Experienced the same problem. Your 'fix' @bennsel bannsel works.
