### ISSUE TITLE
[REST] Break on file upload

### ISSUE THREAD

**Issue by VincentClair** [Codeception/Codeception#3298]
Hello,

Before, with version 2.1.8, we could pass a `Symfony\Component\HttpFoundation\File\UploadedFile` as value . Something like:
```
$I->sendPOST('/ui/options/images',
    ['name'  => 'logo'],
    ['image' => new UploadedFile($filePath, $filename, $mimeType, filesize($filePath))]
);
```

Since version 2.2.2, it seems to be broken. I get an error that the value of key image is invalid.
I changed the UploadedFile to the indexed array version and it works.
Is it normal ?

**Comment by DavertMik** [comment]
I never knew `Symfony\Component\HttpFoundation\File\UploadedFile` can be passed, he-he )
It class is not even part of Codeception package so this behavior was not expected. 
But if @Naktibalda will provide a way to do this that would be useful too. Probably we will need to update docs to specify such behavior

**Comment by Naktibalda** [comment]
Anything that's expected by a framework could be passed.
We really need to document file uploads.
