### ISSUE TITLE
Cannot access ZF2 `application` property since 2.1.9.

### ISSUE THREAD

**Issue by airdrummingfool** [Codeception/Codeception#3300]
In 0241b3981ae, @Naktibalda implemented a feature that would create a new Application for each request. A side effect of the implementation is that the `application` property on the ZF2 **module** is now never set or used (it's just `null`). The real `application` is now stored one level down in the ZF2 **connector**: ZF2 module > ZF2 connector > Application (accessible via `getModule('ZF2')->client->application`). Unfortunately, this `application` property is `protected` (the property on the module was `public`), which means it is no longer accessible from other modules.

Previously, I had been using `$this->getModule('ZF2')->application->getServiceManager();` in order to get to the `ServiceManager` for mocking purposes. Example code:
``` php
$emailMock = new EmailNotificationMock();
// replace email service with our mock one
$serviceManager = $this->getModule('ZF2')->application->getServiceManager();
$serviceManager->setAllowOverride(true);
$serviceManager->setService('EmailNotification', $emailMock);
```
However, since I cannot access the `application`, I no longer have access to the `ServiceManager` (it appears I can only use the ZF2 module's `grabServiceFromContainer()` method to access individual services; there is no way to set a service or allow overrides).

Is there a better way to go about mocking out services? If not, can the Connector's `application` property be set to public, or perhaps a way be provided to access the `ServiceManager` through the ZF2 module? I'm happy to submit a PR with some guidance on what an acceptable solution would look like.

**Comment by Naktibalda** [comment]
I think that `addServiceToContainer($name, $service)` method would be a better solution.

If you are going to implement it, please add `@part services` to docblock, like for [grabServiceFromContainer](https://github.com/Codeception/Codeception/blob/2.2.2/src/Codeception/Module/ZF2.php#L154).

**Comment by Naktibalda** [comment]
I am working on it.

**Comment by airdrummingfool** [comment]
Will your solution allow overriding existing services? For example, in my example code I call `setService` on an `EmailNotification` service that already exists. Without `$serviceManager->setAllowOverride(true);`, I get an error message that the service already exists.

**Comment by Naktibalda** [comment]
Yes, it will.

Also I changed my implementation to use ServiceManager service storage instead of implementing my own.

**Comment by airdrummingfool** [comment]
I know this is a few months old, but I finally got to update to the newest version of Codeception, and the fix above works great! Thank you so much @Naktibalda :)
