### ISSUE TITLE
Gherkin - Unable to identify the newly added snippet 

### ISSUE THREAD

**Issue by ShaliniBommareddy** [Codeception/Codeception#3303]
I am using Codeception 2.2.2 
When I try to add a new snippet to an existing snippet list, codeception doesn't identify the newly added snippet unless I remove the _generated folder and 
run "./vendor/bin/codecept build"   and then 
run  the "gherkin:snippets" .

**Comment by DavertMik** [comment]
Sorry, I tried but couldn't reproduce it.
