### ISSUE TITLE
Getting unknown property: yii\rest\UrlRule::host

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#3308]
Extracted from https://github.com/Codeception/Codeception/issues/3213#issuecomment-226421373

Yii REST tests also fails with new codeception:
Output: `[yii\base\UnknownPropertyException] Getting unknown property: yii\rest\UrlRule::host`

Code:
`/vendor/codeception/codeception/src/Codeception/Module/Yii2.php:273`
```php
foreach (Yii::$app->urlManager->rules as $rule) {
    /** @var \yii\web\UrlRule $rule */
    if ($rule->host !== null) {
        $domains[] = $this->getDomainRegex($rule->host);
    }
}
```
`$rule->host` fails because my app config for urlManager is:
```
'rules' => [
    '' => 'default/index',
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['client', 'service', 'template'],
    ],
],
```
and \yii\rest\UrlRule not have "host" attribute.

**Comment by samdark** [comment]
Which "Yii REST tests" are you referring to? How to reproduce the issue?

**Comment by Naktibalda** [comment]
Any tests that are making requests to routes implemented using [Yii REST url rule](http://www.yiiframework.com/doc-2.0/yii-rest-urlrule.html).

**Comment by samdark** [comment]
Fixed by https://github.com/Codeception/Codeception/pull/3315
