### ISSUE TITLE
PHP Fatal error:  Call to undefined method Codeception\Configuration::actions()

### ISSUE THREAD

**Issue by xiaoxing598** [Codeception/Codeception#3310]
I enter the following command in the tests/ directory `codecept run`, Console output is as follows:
```
Codeception PHP Testing Framework v2.0.16
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

Unit Tests (0) ------------------------------
---------------------------------------------

Functional Tests (0) ------------------------
---------------------------------------------

Acceptance Tests (0) ------------------------
---------------------------------------------


Time: 718 ms, Memory: 5.75MB

No tests executed!
```

But when I put the projects and integrate jenkins, I found to perform error occurred using ant.

```
phpunit:
  [phpunit] Codeception PHP Testing Framework v2.2.2
  [phpunit] Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.
  [phpunit] PHP Fatal error:  Call to undefined method Codeception\Configuration::actions() in /var/lib/jenkins/workspace/xxx/vendor/codeception/codeception/src/Codeception/Lib/Generator/Actor.php on line 56
  [phpunit] Result: 255
```

I try to find that a few lines of code error:
```
protected function initializeModules()
    {
        (1) self::$modules = Configuration::modules($this->settings);
        (2) self::$actions = Configuration::actions(self::$modules);

        foreach (self::$modules as $module) {
            $module->_initialize();
        }
    }
```
The strange thing is the code (1) at the line and there is no error, even though they are the same class

**Comment by Naktibalda** [comment]
Hi @xiaoxing598 ,

Have you noticed that you are using 2 different versions of Codeception - 2.0.16 and 2.2.2?
Codeception\Configuration::actions() only exists and is called by 2.0 branch.

It looks like you have Codeception installed in two ways - local composer installation and phar file or global composer installation. Get rid of one installation to solve your problem.
