### ISSUE TITLE
Bootstrapping codeception/base still creates acceptance testing files

### ISSUE THREAD

**Issue by igorsantos07** [Codeception/Codeception#3317]
Self-explanatory: `codeception/base` is not supposed to be used for acceptance testing, but still when you require it and run `vendor/bin/codecept bootstrap` it creates an acceptance suite for us :(

**Comment by DavertMik** [comment]
Good point. Thanks

**Comment by Naktibalda** [comment]
codeception/base was abandoned in December 2019.
