### ISSUE TITLE
[QUESTION] getScenario() from Helper

### ISSUE THREAD

**Issue by eXorus** [Codeception/Codeception#3323]
Hello,

Quick question, is it possible to access to $scenario from Helper class ?

I need to check the $scenario->current('env').

Thanks

**Comment by DavertMik** [comment]
My first idea is to get a `TestInterface` instance in `_before`, and if it implements a `ScenarioDriven` interface you can access a Scenario. Sounds like a dirty hook, but I don't have better ideas now (

**Comment by eXorus** [comment]
Nice trick

_support/Helper/Api.php
```
class Api extends \Codeception\Module
{
    private $env;

    public function _before($test)
    {
        $this->env = $test->getScenario()->current('env');
    }
    public function callAuthenticate()
    {
        if ($this->env == 'v1')
            //do v1 authenticate
        if ($this->env == 'v2')
            //do v2 authenticate
    }
}
```

It's working well.
