### ISSUE TITLE
Fatal warning in Parser::validate

### ISSUE THREAD

**Issue by yuanjiong199** [Codeception/Codeception#3324]
codecept version 2.2.2
execute codecept.phar run command prompt:
[PHPUnit_Framework_Exception]  Undefined variable: output

**Comment by Naktibalda** [comment]
Please run Codeception with `-vvv` flag to get stacktrace. Most likely that warning happens in the code of your application.

**Comment by yuanjiong199** [comment]
My PHP version is 5.6.9, may be related to it

**Comment by yuanjiong199** [comment]
[root@CentOS web]# php codecept.phar run -vvv
Codeception PHP Testing Framework v2.2.2
Powered by PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

Unit Tests (0) -------------------------------------------------------------------------------------------------------------------------------------
Modules: Asserts, \Helper\Unit
----------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

Functional Tests (0) -------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Functional
----------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------

                                     
  [PHPUnit_Framework_Exception (8)]  
  Undefined variable: output         
                                     

Exception trace:
 () at phar:///usr/local/web/codecept.phar/src/Codeception/Subscriber/ErrorHandler.php:60
 Codeception\Subscriber\ErrorHandler->errorHandler() at phar:///usr/local/web/codecept.phar/src/Codeception/Lib/Parser.php:129
 Codeception\Lib\Parser::validate() at phar:///usr/local/web/codecept.phar/src/Codeception/Test/Loader/Cept.php:17
 Codeception\Test\Loader\Cept->loadTests() at phar:///usr/local/web/codecept.phar/src/Codeception/Test/Loader.php:134
 Codeception\Test\Loader->loadTests() at phar:///usr/local/web/codecept.phar/src/Codeception/SuiteManager.php:96
 Codeception\SuiteManager->loadTests() at phar:///usr/local/web/codecept.phar/src/Codeception/Codecept.php:208
 Codeception\Codecept->runSuite() at phar:///usr/local/web/codecept.phar/src/Codeception/Codecept.php:178
 Codeception\Codecept->run() at phar:///usr/local/web/codecept.phar/src/Codeception/Command/Run.php:329
 Codeception\Command\Run->runSuites() at phar:///usr/local/web/codecept.phar/src/Codeception/Command/Run.php:256
 Codeception\Command\Run->execute() at phar:///usr/local/web/codecept.phar/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/web/codecept.phar/vendor/symfony/console/Application.php:815
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/web/codecept.phar/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/web/codecept.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/web/codecept.phar/src/Codeception/Application.php:103
 Codeception\Application->run() at phar:///usr/local/web/codecept.phar/codecept:36
 require_once() at /usr/local/web/codecept.phar:7

run [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]

[root@CentOS web]#

**Comment by Naktibalda** [comment]
Thanks,

it happens in
https://github.com/Codeception/Codeception/blob/2.2.2/src/Codeception/Lib/Parser.php#L129
```php
exec("php -l ".escapeshellarg($file)." 2>&1", $output, $code);
```

I have no idea why it fails for you, it works fine for everybody else:
https://3v4l.org/4PpXa

**Comment by yuanjiong199** [comment]
download codecept 2.1.4 version, it work fine.

**Comment by Naktibalda** [comment]
You can upgrade to 2.1.11, test validation is a new feature of 2.2

**Comment by DavertMik** [comment]
Better to disable linting in `codeception.yml` configuration:

```yml
settings:
    lint: false
```

**Comment by k4kuz0** [comment]
I'd like to weigh in here and just say that the exact same has happened to me, I made a stackoverflow post about it but only just found this.

It happens in the exact same line as well, 129 in Parser.php.

PHP version: 5.6.3
Codeception version: 2.2.2

Full stack trace:

https://gist.github.com/k4kuz0/74c8b11bf424e5d61070da460d93e1ab

**Comment by Naktibalda** [comment]
@k4kuz0 in your log the most important message is 
`PHP Warning:  exec() has been disabled for security reasons`
