### ISSUE TITLE
selectOption doesn't POST back option value when select is array

### ISSUE THREAD

**Issue by demanzonderjas** [Codeception/Codeception#3326]
Hi,

I came across a problem with filling in and POSTing my form through the AcceptanceTester, cause the select value seems to disappear because it is an array (because I would like to have the option of adding multiple selects, so users can select multiple interests):
```php
$I = new AcceptanceTester($scenario);
$I->wantTo('See if interest added via form to user end up in database');
$I->amOnPage('/user/create');
$I->see('Create User');
$I->fillField('name', 'daan');
$I->seeElement('select', ['name' => 'interests[]']);

$option = $I->grabTextFrom('form select[name="interests[]"] option:nth-child(2)');
$I->selectOption('select[name="interests[]"]', $option);
$I->seeInField('select[name="interests[]"]', '2');

$I->click('input[type=submit]');

// after submit, controller routes the user to their own page, with their interests
$I->seeCurrentUrlMatches('/\/user\/daan/');
$I->see('daan');
$I->see('Interest#2');
```
Unfortunately, the Parameters submitted miss the selected Interest-value:
```
[Uri] http://localhost/project-name/user/create
  [Method] POST
  [Parameters] {"name":"daan","description":"","interests":[""],"submit":"Create new user"}
  [Request Headers] []
```
While running it myself through the browser, the script does work. When I remove the brackets [] and say I want to submit one interest, then it does work. So the issue seems to be something with Codeception and posting arrays? Or do I have some fault somewhere?

**Comment by Naktibalda** [comment]
Are you using WebDriver or PhpBrowser in acceptance tests?

**Comment by demanzonderjas** [comment]
Phpbrowser 

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Gintautas Miselis <notifications@github.com> </div><div>Datum:13-07-2016  11:07  (GMT+01:00) </div><div>Aan: Codeception/Codeception <Codeception@noreply.github.com> </div><div>Cc: demanzonderjas <weustenraad@gmail.com>, Author <author@noreply.github.com> </div><div>Onderwerp: Re: [Codeception/Codeception] selectOption doesn't POST back option
  value when select is array (#3326) </div><div>
</div>Are you using WebDriver or PhpBrowser in acceptance tests?

**Comment by Naktibalda** [comment]
@demanzonderjas Please provide a complete HTML of your form.

PhpBrowser has tests for multiple options: https://github.com/Codeception/Codeception/blob/2.2.3/tests/unit/Codeception/Module/TestsForWeb.php#L301

To make them closer to your case, I tested
```php
$this->module->selectOption('select[name="like[]"]', array('eat', 'adult'));
```
and
```php
$option = $this->module->grabTextFrom('form select[name="like[]"] option:nth-child(2)');
$this->module->selectOption('select[name="like[]"]', $option);
```

All tests passed.

**Comment by Naktibalda** [comment]
@demanzonderjas I am closing this ticket because you haven't provided a complete HTML of your form.
