### ISSUE TITLE
An error was encountered when using a method not found in yii2 framework codeception

### ISSUE THREAD

**Issue by xiaoxing598** [Codeception/Codeception#3332]
When I run the test in the project directory when `codecept.phar run unit`, Console gives an error:

```
Codeception PHP Testing Framework v2.2.2
Powered by PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

Unit Tests (2) -----------------------------------------------------------------------------------------------------------------------------------
- EventTest: Event is auditPHP Fatal error:  Call to a member function selectDB() on null in /var/lib/jenkins/workspace/xxx/vendor/yiisoft/yii2-mongodb/Connection.php on line 172
<pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Call to a member function selectDB() on null&#039;

in /var/lib/jenkins/workspace/xxx/vendor/yiisoft/yii2-mongodb/Connection.php:172

Stack trace:
#0 [internal function]: yii\base\ErrorHandler-&gt;handleFatalError()
#1 {main}</pre>
```

Connection.php on line 172 content:  `'mongoDb' => $this->mongoClient->selectDB($name)`

select DB is mongodb extend MongoClient class method, wondering why can not find a test run from the inside of the extension method.

**Comment by xiaoxing598** [comment]
It has confirmed that this problem? It is not a flaw?

**Comment by Naktibalda** [comment]
It hasn't been confirmed.

**Comment by DavertMik** [comment]
I think this is Yii configuration issue and not a Codecepion's one

**Comment by xiaoxing598** [comment]
@DavertMik I also need to provide any necessary configuration information for your reference, if any, please tell me, I hope to help me locate the point of the problem!

**Comment by xiaoxing598** [comment]
This problem can solve some priority, waiting for the actual project write unit tests, progress is now stuck in here.

**Comment by icron** [comment]
You forgot to check for HttpException. It was in the previous version. https://github.com/Codeception/Codeception/commit/080dba649f5dc0f4defa326b0e237a9aa084ad99#comments

**Comment by xiaoxing598** [comment]
@icron You mean to upgrade to the latest YII2 frame can it? I do not quite understand what you mean, describe in detail the trouble, thank you very much!

**Comment by djeux** [comment]
Previously there was a check for HttpExceptions. Now all tests fail if somebody threw a NotFoundHttpException for example, which is intended behavior.

**Comment by icron** [comment]
@djeux  Yes, that's what I mean

**Comment by xiaoxing598** [comment]
@icron This problem has a specific solution for it?

**Comment by samdark** [comment]
I don't get what the problem is. Console is giving an error and continues to the next test. It seems to work as intended, isn't it?

**Comment by xiaoxing598** [comment]
`Call to a member function selectDB() on null`   This tip should not be produced, and this is the problem.

**Comment by djeux** [comment]
```php
$invite = ClientInvite::findByToken($token);

if (null === $invite) {
     throw new NotFoundHttpException("Invite not found");
} else if ($invite->isUsed) {
     throw new ForbiddenHttpException("Token already used");
}
```
Cest
```php
$usedInvite = $I->getFixture('client_invite')->data['used'];
$I->amOnPage(['/site/invite', 'token' => $usedInvite['token']]);
$I->expectTo('see forbidden');

$I->seeResponseCodeIs(403);
```
Works fine in 2.1.11, but fails when it shouldn't in 2.2.3
```
1) ClientInviteCest: Test activate
 Test  functional/ClientInviteCest.php:testActivate

  [yii\web\NotFoundHttpException] Invite not found

Scenario Steps:

 2. $I->amOnPage({"0":"\/site\/invite","token":"FosYsK-EOjEiCqe5aT1X7cdvHBHFsXSO"}) at functional/ClientInviteCest.php:23
 1. // I am going to try and open an invite without one
```

**Comment by samdark** [comment]
Ah. OK. You're expecting it to fail but instead it errors.

**Comment by djeux** [comment]
@samdark I expect it to continue, because NotFoundHttpException is not an exception which should fail a test, but just return a 404 page.

**Comment by samdark** [comment]
It continues after the error but the fact that you expect it to fail and it doesn't isn't right.

**Comment by djeux** [comment]
@samdark Ok, I'll change the text to 
```php
$I->expectTo('receive 404 error and continue');
```
then it should not confuse anyone. But the test should continue after receiving a HttpException like it used to, but it doesn't anymore after the update.
Before there was a check in Lib\Connector\Yii2::doRequest() to check for HttpException, not its gone now after the update.

**Comment by djeux** [comment]
In other words, this part is missing, which handled this case
```php
if ($e instanceof HttpException) {
// we shouldn't discard existing output as PHPUnit preform output level verification since PHPUnit 4.2.
       $app->errorHandler->discardExistingOutput = false;
       $app->errorHandler->handleException($e);
 } elseif ($e instanceof ExitException) {
```

**Comment by samdark** [comment]
Yep. Fixing that.
