### ISSUE TITLE
Using Yii routes in acceptance tests

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#3335]
Yii apps depending on configs produce different urls:

```
index.php?site/vew
/site/view
```

Yii2 module needs special (non-conflicting methods) to get URL from routes, so this urls could be used in acceptance tests

**Comment by DavertMik** [comment]
@notgosu your upcoming PR should include such method

**Comment by samdark** [comment]
What do you mean by "non-conflicting methods"?

**Comment by DavertMik** [comment]
> What do you mean by "non-conflicting methods"?

I mean it shouldn't be `amOnPage` as it is already included in WebDriver and PhpBrowser and using it will trigger module conflict. So something like `getUrlByRoute` would be nice, but much better to have a function which will return url for a route, so it could be used like:

```php
$I->amOnPage(url_for_route(['site/view']))
```

**Comment by DavertMik** [comment]
Should be fixed with:

https://github.com/Codeception/Codeception/pull/3343

By providing `entryScript` and `entryUrl` and using `Yii2` module routes can be accessed like

```php
use yii\helpers\Url as Url;

$I->amOnPage(Url::toRoute('/site/about'));
```
