### ISSUE TITLE
lastInsertId for PostgreSql assumes sequence column is always named 'id'

### ISSUE THREAD

**Issue by Recklys** [Codeception/Codeception#3336]
In the PostgreSql driver the function lastInsertId assumes sequences are named like:
> [table_name]\_id\_seq

 when they're actually named like: 

> [table_name]\_[col_name]\_seq

for SERIAL type columns. I had a lot of trouble using haveInDatabase() with auto-incremented columns since our tables have sequenced primary key fields not named 'id', so the function would throw the error:
> Primary key field project_id is not set for table projects

if I didn't define a value for the PK.  I can't define it without making the tests very brittle, I'd like it to rely on auto-increment.

I have the issue already fixed if you'd be open to a pull request.

**Comment by Naktibalda** [comment]
Thanks, please make a pull request.

**Comment by Naktibalda** [comment]
@Recklys It looks like you forgot to make a pull request.

**Comment by Recklys** [comment]
Sorry, I have it ready but I'm still waiting on approval from my employer :/

**Comment by alexjeen** [comment]
@Recklys Can you please share your fix, because we are running into the same problem here.

**Comment by alexjeen** [comment]
Fixed in Lib/Driver/PostgresSql.php:

    public function lastInsertId($table, $column = false)
    {
        /*
         * We make an assumption that the sequence name for this table
         * is based on how postgres names sequences for SERIAL columns
         */
                
        $sequenceName = $this->getQuotedName($table.'_id_seq');
        $lastSequence = null;

		try {
	        $lastSequence = $this->getDbh()->lastInsertId($sequenceName);
		} catch (\PDOException $e) { }
		
		if(!$lastSequence) {
			$pkName = array_pop($this->getPrimaryKey($table));
	        $sequenceName = $this->getQuotedName($table.'_'.$pkName.'_seq');			
	        $lastSequence = $this->getDbh()->lastInsertId($sequenceName);
		}	
        
        return $lastSequence;
    }

Also, because your PK's are named differently you will need to change the getPrimaryKey method too:

    /**
     * @param string $tableName
     *
     * @return array[string]
     */
    public function getPrimaryKey($tableName)
    {
        if (!isset($this->primaryKeys[$tableName])) {
            $primaryKey = [];
            $query = "SELECT pg_attribute.attname, format_type(pg_attribute.atttypid, pg_attribute.atttypmod) 
	FROM pg_index, pg_class, pg_attribute, pg_namespace 
	WHERE 
	  pg_class.oid = ?::regclass AND 
	  indrelid = pg_class.oid AND 
	  nspname = 'public' AND 
	  pg_class.relnamespace = pg_namespace.oid AND 
	  pg_attribute.attrelid = pg_class.oid AND 
	  pg_attribute.attnum = any(pg_index.indkey)
	 AND indisprimary";
            $stmt = $this->executeQuery($query, [$tableName]);
            $columns = $stmt->fetchAll(\PDO::FETCH_ASSOC);

            foreach ($columns as $column) {
                $primaryKey [] = $column['attname'];
            }
			
            $this->primaryKeys[$tableName] = $primaryKey;
        }

        return $this->primaryKeys[$tableName];
    }

**Comment by Naktibalda** [comment]
Please make a pull request

**Comment by alexjeen** [comment]
PR: https://github.com/Codeception/Codeception/pull/3506

BTW: Thanks for building Codeception, it works very good for our projects.

@Recklys: Your boss should be ashamed for not letting you submit your PR, it helps make a product you use on a daily basis better.
