### ISSUE TITLE
Invalid query parsing from sql file in Postgres

### ISSUE THREAD

**Issue by StalkAlex** [Codeception/Codeception#3354]
I have a db dump, there is query among others which gives error during loading before test.

I checked this query in a console, it executes successfully. All xml code is in quotes as seen, so I guess problem is in line breaks of an xml string.

```
[Codeception\Exception\ModuleException]
  Db: SQLSTATE[42601]: Syntax error: 7 ERROR:  unterminated quoted string at or near "'<?xml vers
  ion="1.0" encoding="UTF-8" standalone="no"?><root>
   <user>
    <firstName>Тест</firstName>
    <middleName>Тестович</middleName>
    <lastName>Тестов</lastName>       
    <phoneNumber>(444) 444-4444</phoneNumber>
   </user>
   ...long text goes here...
    &lt;/br&gt;Исходные данные &#13"
  LINE 2: ...L, NULL, NULL, NULL, NULL, '<?xml version="1.0" encoding="UT...
```

I am using yii2 codeception. This bug makes codeception absolutely unusable in our case.

**Comment by StalkAlex** [comment]
I wrote extra helper module where I overrode _loadDump_ function. 
Here's my example
```php
 protected function loadDump()
    {
        $filePath = Configuration::projectDir() . $this->config['dump'];
        $command = 'psql -U postgres -d predesign < ' . $filePath;
        $result = shell_exec($command);
    }
```
But I get a  lot of duplicates error while populating dump. What else did I forget? Could someone give me a little help explaining it?

**Comment by Naktibalda** [comment]
Hi @StalkAlex,

I have tried to reproduce your issue, but Codeception successfully loads INSERT statement containing that XML string.
I noticed that your gist is not exact match, because text Исходные данные &#13" is missing in it.

Please provide CREATE TABLE statement and exact INSERT statement which is failing.

**Comment by StalkAlex** [comment]
Sorry, here's dump version with error. https://gist.github.com/StalkAlex/e8325910c720a7e0d44e0754737d1e3c
Problem I think in those lines lt that you've mentioned. If remove them, a dump will restore well.
  ```xml<alias>Приложения к эскизному проекту. &lt;/br&gt;Исходные данные &#13;
                (официальные документы, &lt;/br&gt; переданные заказчиком для проектирования объекта)</alias>```

**Comment by Naktibalda** [comment]
@StalkAlex implementing a full blown SQL parser is beyond the scope of Codeception.

To fix that dump, you have to modify it to ensure that ; is not the last character on the line.
(Adding space does not help, because each line is rtrimed.)

For example, change
```xml
<alias>какой-то текст. &lt;/br&gt;Исходные данные &#13;
  (документы, &lt;/br&gt; переданные заказчиком )</alias>
```
to
```xml
<alias>какой-то текст. &lt;/br&gt;Исходные данные &#13; (документы, &lt;/br&gt; переданные заказчиком )</alias>
```

**Comment by StalkAlex** [comment]
@Naktibalda Thanks for the idea, but this dump is quiet big, about 90 Mb space and all of it for documents table mainly,  not sure if it could be done manually.

**Comment by Naktibalda** [comment]
Db module has a populator feature, which can be used to import dump file using pg_restore.

https://codeception.com/docs/modules/Db#Populator
