### ISSUE TITLE
Symfony validator constraints not loaded via annotations.

### ISSUE THREAD

**Issue by benr77** [Codeception/Codeception#3362]
Using Codeception 2.2 and Symfony 3.0.8.

In my Symfony entities I use various validator assertions. E.g.

```
use Symfony\Component\Validator\Constraints as Assert;

class Foo 
{

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_start", type="date", nullable=true)
     * @Assert\Date()
     */
    private $dateStart;

}

```

However, this gives me the following error:

`[Doctrine\Common\Annotations\AnnotationException] [Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\Date" in property AppBundle\Entity\Foo::$dateEnd does not exist, or could not be auto-loaded.`

There are other validator assertions in this file and others that are loaded just fine. Codeception only seems to have a problem with the `@Assert\Date()` annotation.

If I purposefully tweak this annotation to `@ Assert\Date()` (i.e. with a space to turn the annotation in to a simple comment) then codeception runs just fine.

**Comment by phpetra** [comment]
Seems related to this? #3537

**Comment by Naktibalda** [comment]
Solution was proposed in linked issue.
