### ISSUE TITLE
CodeCeption.phar PHPUnit Error

### ISSUE THREAD

**Issue by maxfysho** [Codeception/Codeception#3363]
Hi, 

I just download CodeCeption.phar using the following commands on Amazon Linux EC2:

```
sudo curl -LsS http://codeception.com/codecept.phar -o /usr/local/bin/codecept
sudo chmod a+x /usr/local/bin/codecept
```

and get the following error when trying to run Acceptance tests

```
[ec2-user@ip-172-31-15-19 FYS-WA-RAT]$ codecept run acceptance --env dev
Codeception PHP Testing Framework v2.2.2
Powered by PHPUnit 5.4.6 by Sebastian Bergmann and contributors.
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in phar:///usr/local/bin/codecept/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 383
```

I had been able to successfully run tests on this server when using CodeCeption via Composer defined in the package, but now changing to global command fails.

**Comment by Naktibalda** [comment]
What version of PHP are you using?

**Comment by DavertMik** [comment]
@Naktibalda 
F**k, it was PHP 5.4, 

The line of code is:
```
                [SebastianBergmann\Comparator\Comparator::class]
```

**Comment by Naktibalda** [comment]
@maxfysho if you are using PHP 5.4 or PHP 5.5, please download http://codeception.com/php54/codecept.phar  instead.

**Comment by maxfysho** [comment]
Hey Guys,

You assumed correct, PHP54. I will use the above link and see how we go. 

Thanks

**Comment by maxfysho** [comment]
Confirmed fixed.

**Comment by vcboy** [comment]
thanks
