### ISSUE TITLE
seeResponseContainsJson to be more restrict

### ISSUE THREAD

**Issue by caiquecastro** [Codeception/Codeception#3375]
Is there a method to make a more restrict check against the response. On seeResponseContainsJson method I check if the expected response is returned, but if i want to check if a response does not contain a specific json member, is it possible?

I saw there is a method canSeeResponseEquals, but I need to encode to json before checking.

What's the differente between between the $I->see* and $I->canSee* methods?

**Comment by DavertMik** [comment]
> but if i want to check if a response does not contain a specific json member, is it possible?

No. But you can write your own Helper method to do this check

> What's the differente between between the $I->see* and $I->canSee* methods?

`canSee` assertions won't stop test execution on failure
