### ISSUE TITLE
Acceptance tests code coverage fails

### ISSUE THREAD

**Issue by ivan-atanasov** [Codeception/Codeception#3378]
I am using Laravel5, Codeception 2.2.3, phantomJs 2.1.1

When I run the acceptance tests with --coverage-html I get the following error:

`
  [Facebook\WebDriver\Exception\UnableToSetCookieException]                                                                                                                                                
  {"errorMessage":"Unable to set Cookie","request":{"headers":{"Accept":"application/json","Content-Length":"207","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:4444"},"httpVersion":  
  "1.1","method":"POST","post":"{\"cookie\":{\"name\":\"CODECEPTION_CODECOVERAGE\",\"value\":\"{\\\"CodeCoverage\\\":\\\"tryToOpenModifyListPageWhenNotLoggedIn\\\",\\\"CodeCoverage_Suite\\\":\\\"accept  
  ance\\\",\\\"CodeCoverage_Config\\\":null}\",\"domain\":\"marvel.dev\"}}","url":"/cookie","urlParsed":{"anchor":"","query":"","file":"cookie","directory":"/","path":"/cookie","relative":"/cookie","po  
  rt":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/cookie","queryKey":{},"chunks":["cookie"]},"urlOriginal":"/session/ca24a1e0-537b-11e6-871a-a1e703593448/  
  cookie"}}                                                                                                                                                                                                
`

I found out that if I comment this line:
`
$this->module->setCookie(self::COVERAGE_COOKIE, json_encode($cookie));
`
in startCoverageCollection() method in LocalServer.php, it works, but the coverage is wrong and it is not considering the acceptance tests.

**Comment by Naktibalda** [comment]
Thanks for report, but it is an issue of PhantomJS.
Similar issue https://github.com/Codeception/Codeception/issues/2900 links to https://github.com/ariya/phantomjs/issues/14047 as a possible cause.

**Comment by ivan-atanasov** [comment]
@Naktibalda thanks for the info. I am glad the problem was not me :D Should I close the issue?
