### ISSUE TITLE
codeception 2.2.3 breaks ZF2 tests

### ISSUE THREAD

**Issue by devartbvba** [Codeception/Codeception#3388]
After update to 2.2.3, suddenly all integration tests start failing.

``` bash
 [Error] Call to undefined method AppDataStore\Response\ReplaceResponse::getBody()  
```

It seems that all of the sudden the getBody is being called on the direct responses of the action return instead of the zend response.

Trace for the error is:

``` bash
#1  /vagrant/formservices_app_php/vendor/symfony/browser-kit/Client.php:315
#2  Codeception\Module\REST->sendPOST
#3  /vagrant/formservices_app_php/tests/_support/_generated/ApiTesterActions.php:2926
#4  /vagrant/formservices_app_php/tests/_support/ApiTester.php:39
#5  /vagrant/formservices_app_php/tests/api/AppDataStore/DataStore/ReplaceCest.php:12
#6  /vagrant/formservices_app_php/tests/api/AppDataStore/DataStore/ReplaceCest.php:24
#7  DsTest\Api\AppDataStore\DataStore\ReplaceCest->testSuccess
```

When looking at the file Codeception\Lib\Connector\ZF2 I also see a missing class (Codeception\Lib\Connector\ZF2\PersistentServiceManager)

**Comment by Naktibalda** [comment]
@DavertMik This is a good example of misusing issue template.

@devartbvba Please provide console output including a stack trace and relevant test code.

**Comment by devartbvba** [comment]
Hey, I actually clicked the submit button too fast (which just posts that template), I edited the message

**Comment by Naktibalda** [comment]
It was caused by https://github.com/Codeception/Codeception/pull/3325
@jstewmc have you got any idea how to make it work for @devartbvba ?

**Comment by devartbvba** [comment]
I think that the missing PersistentServiceManager is exactly the problem, we have a response listener that transforms our own response class to a ZF2 response, and I believe the missing PersistentServiceManager makes the listener not being triggered (and hence the getBody is being called on a non-zend response).

**Comment by Naktibalda** [comment]
why is it missing?

**Comment by jstewmc** [comment]
Oh, man. I'm sorry if my change caused you problems. 

At least, it doesn't appear that I broke all of Codeception for ZF2 users. I updated our Codeception version to 2.2.3 and ran our tests in a panic. They continue to run ok, at least. I know that's a small consolation to you, but I breathed a sigh of relief haha!

**Comment by jstewmc** [comment]
I don't know near enough about Zend internals, and I haven't come across a PersistentServiceManager before. However, I'd check if ZF2 does anything special when the application's `getResponse()` method is called.

All I really did was move the definition of a local-variable in a function down a dozen lines or so until _after_ the application's `run()` method. That way, the response sent to Browser-Kit was the application's _actual_ response, not the application's response before the `run()` method was called, which, in some cases, can be different things. 

To me, because the variable is local to the function, it seems unlikely to break other stuff when it's moved, unless Zend is doing something when the response is first gotten (famous last words, of course).

**Comment by devartbvba** [comment]
The missing file/class being used in the ZF2 module is a Codeception class:
Codeception\Lib\Connector\ZF2\PersistentServiceManager

Just open up the Codeception\Lib\Connector\Zf2.php in PHPStorm and you'll quickly see the missing classes (which are being used)...

In 2.2.2 there's a Codeception\Lib\Connector\ZF2\PersistentServiceManager.php, in 2.2.3 the file is gone but it is still being used.

**Comment by Naktibalda** [comment]
Somehow you got it wrong way around, the file was named DoctrineServiceManager until 2.2.2 and I renamed it to PersistentServiceManager in 2.2.3

https://github.com/Codeception/Codeception/commit/becc2b2677f3f8d4c3a946dad3186ee6c5fa3039#diff-1266091170bae6f5d30d72de4a780f3e

**Comment by DavertMik** [comment]
Maybe this was a version conflict? Like you are trying to use Codeception of 2 different versions. This happens if you use Phar + Composer.

**Comment by Naktibalda** [comment]
File issue is irrelevant.
Response listener is a real issue.
