### ISSUE TITLE
How we select the auto suggest or google suggested word in codeception

### ISSUE THREAD

**Issue by Dipalii** [Codeception/Codeception#3407]
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

``` bash
# paste output here
```

> Provide test source code if related

``` php
// paste test
```
### Details
- Codeception version: 
- PHP Version:
- Operating System:
- Installation type: Phar || Composer
- List of installed packages (`composer show`)
- Suite configuration:

``` yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
If there is no such feature in [WebDriver protocol](https://www.w3.org/TR/webdriver1/) then Codeception can't do it either.
