### ISSUE TITLE
PostgreSQL driver fails to find primary key for some tables

### ISSUE THREAD

**Issue by alexjeen** [Codeception/Codeception#3415]
The query to find PostgreSQL primary keys, doesn't always work for us.

So it throws an exception:

    [InvalidArgumentException] Primary key field airport_id is not set for table airports  

We found this query to work better:

    SELECT               
      pg_attribute.attname, 
      format_type(pg_attribute.atttypid, pg_attribute.atttypmod) 
    FROM pg_index, pg_class, pg_attribute, pg_namespace 
    WHERE 
      pg_class.oid = 'TABLENAMEHERE'::regclass AND 
      indrelid = pg_class.oid AND 
      nspname = 'public' AND 
      pg_class.relnamespace = pg_namespace.oid AND 
      pg_attribute.attrelid = pg_class.oid AND 
      pg_attribute.attnum = any(pg_index.indkey)
     AND indisprimary

I found this query here:

http://stackoverflow.com/questions/1214576/how-do-i-get-the-primary-keys-of-a-table-from-postgres-via-plpgsql

**Comment by Naktibalda** [comment]
Current implementation is based on https://wiki.postgresql.org/wiki/Retrieve_primary_key_columns
Could you show CREATE TABLE statement of airports table?
And please explain the difference between queries, I don't use PostgreSQL.

**Comment by DavertMik** [comment]
If you could fix that in `Lib/Driver/PostgreSql.php` and send a Pull Request that would be awesome, because we don't use it actively and didn't see this problems. Codeception is not an ORM so it can't support all SQL dialects perfectly. That's our limitation

**Comment by Naktibalda** [comment]
I need a way to reproduce the issue first.

**Comment by alexjeen** [comment]
Sorry for my late response. It turns out to be db_converter.py problem (we went from MySQL to PostgreSQL) so this issue can be closed.
