### ISSUE TITLE
E_USER_DEPRECATED errors bypass error_level setting

### ISSUE THREAD

**Issue by jstewmc** [Codeception/Codeception#3424]
It appears that Codeception's `Subscriber\ErrorHandler` doesn't respect the `error_level` configuration setting for `E_USER_DEPRECATION` errors.

# Background

After a recent `composer update`, one of our third-party libraries started triggering `E_USER_DEPRECATED` errors. These errors appeared as notifications after our tests. 

I tried setting Codeception's `error_level` to `E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_USER_DEPRECATED` (note the addition of `E_USER_DEPRECATED`). However, the notifications continued to appear.

![config](https://cloud.githubusercontent.com/assets/1192893/17530472/ed2a3812-5e34-11e6-9dbb-2d13e68c34ce.PNG)

![notifications](https://cloud.githubusercontent.com/assets/1192893/17530535/2e5580c6-5e35-11e6-99bd-4df4765cc4fc.PNG)

I added `var_dump(error_reporting())` to my test suite's `_beforeSuite()` and `_afterSuite()` methods. Both methods printed `6143`, the correct value for `E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_USER_DEPRECATED`.

Error reporting appears to be correctly set from start to finish.

# Issue

The issue appears to stem from the `Subscriber\ErrorHandler`. 

As I understand it, setting PHP's error level via [`error_reporting()`](http://php.net/manual/en/function.error-reporting.php) will set the error levels for PHP's _native_ error handler.  However, when you register a _custom_ error handler via the [`set_error_handler()`](http://php.net/manual/en/function.set-error-handler.php) function, the _native_ error handlers will be bypassed for all the _custom_ handler's error types. If you don't specify error types, a _custom_ error handler defaults to `E_ALL | E_STRICT`. 

On line 36 of the `ErrorHandler` object, we correctly set the error reporting level to my configuration setting, `E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_USER_DEPRECATED`. However, on line 41, we register an error handler without specifying the error types. 

![handle](https://cloud.githubusercontent.com/assets/1192893/17530904/d2a8ab16-5e36-11e6-8cc3-9bdd67f3dfb6.PNG)

Now, in the `errorHandler()` method, we do check to be sure the error being handled is one we've set with `error_reporting()`, however, this occurs after the check for `E_USER_DEPRECATED` errors. 

![errorhandler](https://cloud.githubusercontent.com/assets/1192893/17530958/04e94f54-5e37-11e6-8d53-45c7624ba101.PNG)

Even though I've excluded `E_USER_DEPRECATED` errors from Codeception's `error_level` reporting, they are being reported. That's not great.

# Solutions

In my mind, there are two solutions:

## Specify the handler's error types

We could specify the custom error handler's error types when we set it. This would remove the need to check the error types in the `errorHandler()` method.

![solution1](https://cloud.githubusercontent.com/assets/1192893/17531108/cb2b5d42-5e37-11e6-84b5-9545813407d4.PNG)

## Move the E_USER_DEPRECATED check

We could move the E_USER_DEPRECATED check in the `errorHandler` method below the error types check.

![solution2](https://cloud.githubusercontent.com/assets/1192893/17531191/177f96fe-5e38-11e6-8a4e-2b1eedbf0875.PNG)

Either solution fixes the issue.

![success](https://cloud.githubusercontent.com/assets/1192893/17531443/1f7f5686-5e39-11e6-8d95-0ea82c736210.PNG)

# Pull request

The first solution seems more correct. We shouldn't handle events only to not handle them, unless we want to suppress PHP's native error handling. The second solution is definitely a much smaller change. 

I'm happy to make a pull request for either one. I wanted to check with the authors/contributors first, because there is plenty going on in here that I don't understand haha.

**Which solution do you recommend?**

**Comment by Naktibalda** [comment]
I think that this is by design to support [Symfony Depreciations Helper](https://symfony.com/doc/current/components/phpunit_bridge.html#making-tests-fail).

To make your tests pass you have to set environment variable SYMFONY_DEPRECATIONS_HELPER to weak, like [here](https://github.com/Codeception/Codeception/pull/3061/commits/72563aa91fc937def752047410e2342ca4a8433a).

**Comment by jstewmc** [comment]
Oh, cool. Thank you for the suggestion.

I don't use Symfony Deprecations Helper in my project, but I tried setting the `SYMFONY_DEPRECATIONS_HELPER=weak` environment variable in my Codeception bootstrap anyway.

![bootstrap](https://cloud.githubusercontent.com/assets/1192893/17557064/f2260276-5ed2-11e6-8f38-667571dba5d1.PNG)

Unfortunately, it did not fix the issue. 

You're right about supporting Symfony Deprecations Helper in the `ErrorHandler` object. Deprecation errors appear to be special. Their error handler is registered separately than the other error handlers.

![handle](https://cloud.githubusercontent.com/assets/1192893/17557315/eff4b9ba-5ed3-11e6-8288-19b687bc7638.PNG)

It looks like the environment variable only matters if the Symfony PHPUnit Bridge component is installed, though (which makes sense). 

![registerdeprecationerrorhandler](https://cloud.githubusercontent.com/assets/1192893/17557321/f87e182e-5ed3-11e6-8cb8-58353232bcc1.PNG)

I'm not dying to install a library just to turn it off (haha). I think Solution 2 from above (moving the E_USER_DEPRECATED check in `errorHandler()` below the `$errno` check) would fix the issue.  

What do you think?

Oh, and thank you for always being so helpful and responsive with issues. Thank you and the Codeception team for a great testing framework!

**Comment by Naktibalda** [comment]
@raistlin any comments?

**Comment by Naktibalda** [comment]
In my opinion, deprecation messages should always be visible to encourage users to fix them.
However your situation could be improved by removing duplicate messages.

**Comment by jstewmc** [comment]
I'm right there with you. Normally, I want to see deprecation messages.

Unfortunately, these notices are triggered and caused by libraries outside of my control. In this case, I'd just like to turn the notices off, because I can't fix them. 

In my opinion, the Codeception `error_level` configuration setting should be respected for all errors, even `E_DEPRECATION` and `E_USER_DEPRECATION` notices. That way, the user can decide what errors should be visible. That's why I opened the issue and submitted PR #3445. 

If you guys don't agree, it's no big deal. I just saw something I thought I could improve at a difficulty level I figured I could handle haha.

**Comment by wojtas** [comment]
I definitely agree with @jstewmc on this matter. In my case I get a lot of deprecation warnings which are triggered by code I have totally no control over; I think it just pollutes the test report. I think that the user should be able to decide whether he wants to be notified of deprecations while testing or not. In my opinion, moving the aforementioned part of the code in the ErrorHandler::errorHandler method would be the best solution. In such cases, configurability is strongly desirable.

**Comment by Naktibalda** [comment]
I agree that error_level setting should be respected.

@jstewmc I will accept a patch which assigns the result of `eval("return {$this->errorLevel};")` to private property and uses it instead of error_reporting() in `errorHandler`.
