### ISSUE TITLE
Add canSeeAttributeFrom

### ISSUE THREAD

**Issue by jltoo** [Codeception/Codeception#3425]
#### What are you trying to achieve?
Verifying an element property attribute.
Example:
`<li class="active">
<a href="http://qa.test.com/portal/my/info/" data-qaid="portalSettings">SETTINGS</a>
</li>`

I need to verify that the li have an active attribute for class.
$I->canSeeAttributeFrom("$path","$property","$value");
$I->canSeeAttributeFrom("//li[1]","class","active");

**Comment by Naktibalda** [comment]
It can be achieved with [seeElement](http://codeception.com/docs/modules/WebDriver#seeElement)
> Checks that the given element exists on the page and is visible. You can also specify expected attributes of this element.
