### ISSUE TITLE
Support of standard mongodump/mongorestore tools to populate MongoDB database

### ISSUE THREAD

**Issue by GSokol** [Codeception/Codeception#3427]
#### Introduction
In documentation it's told that db dump should be a js file, that could be create, for instance, with RockMongo. This tool is old, not supported and crappy enough to have alternatives. The best way I see is to support also standard mongodump/mongorestore tools.

**Comment by Naktibalda** [comment]
@GSokol Could you implement it?

**Comment by GSokol** [comment]
@Naktibalda in progress

**Comment by GSokol** [comment]
@Naktibalda https://github.com/Codeception/Codeception/pull/3430

**Comment by Naktibalda** [comment]
#3437
