### ISSUE TITLE
PhpBrowser: Dump page contents on "element not found" failure.

### ISSUE THREAD

**Issue by thinkspill** [Codeception/Codeception#3431]
When a `see` assertion fails due to the text not appearing in context, there is (partial) source code output inline with the Codeception test output and reporting, in addition to debuggable source code output in the test logs directory.

When a `see` assertion fails due to an unfound page element, the only debuggable source code output is in the test logs.
#### Examples:

`$I->see("Your account is currently inactiveeee.","#content_col")`

```
Step  See "Your account is currently inactiveeee.","#content_col"
 Fail  Failed asserting that any element by '#content_col' on page /account/
+ <div class="col-sm-9" id="content_col">
[...20 lines of html source...]
contains text 'Your account is currently inactiveeee.'

Scenario Steps:

 10. $I->see("Your account is currently inactiveeee.","#content_col") at tests/accounts/PnpBillsWhenReactivatingCept.php:15
```

`$I->see("Your account is currently inactive.","#missing_element_context")`

```
Fail  Element located either by name, CSS or XPath element with '#missing_element_context' was not found.

Scenario Steps:

 10. $I->see("Your account is currently inactive.","#missing_element_context") at tests/accounts/TestCept.php:15
```
### Changes requested

I would like to have the option to see some page output when the element is missing.
#### Example output of change requested

`$I->see("Your account is currently inactive.","#missing_element_context")`

```
Fail  Element located either by name, CSS or XPath element with '#missing_element_context' was not found.
+ <div class="col-sm-9" id="content_col">
<html>
<body>
[...N lines of html source...]
...does not contain element '#missing_element_context'

Scenario Steps:

 10. $I->see("Your account is currently inactive.","#missing_element_context") at tests/accounts/TestCept.php:15

```
### Benefit of change

This would help with using PhpBrowser-based tests in a more TDD-like fashion. For example, I have a test that hits a route that doesn't exist. The error message for the non-existent route tells me exactly what is needed (add such-and-such route), but in order to see that error message I have to explicitly open the test log file. Showing the page output directly would cut out that step in such cases.
### Details
- Codeception version:  2.2.3
- PHP Version: 7.0.7
- Operating System: Ubuntu 14.04
- Installation type: Composer

**Comment by Naktibalda** [comment]
The negative effect would be that it would dump hundreds or event thousands lines of HTML code on screen.

**Comment by thinkspill** [comment]
I suggest the number of dumped lines is either configurable or matches the 21 lines of output shown when a `see` assertion fails with no element context.

**Comment by DavertMik** [comment]
If a test fails the HTML is saved into the `_output` directory. No need to print all file, just open it inside a browser or editor. PhpBrowser does this by default. If you run test with `-vv` flag you will see a path for an HTML file with a dump
