### ISSUE TITLE
Move mouse to a location, then click there

### ISSUE THREAD

**Issue by thejadmaster** [Codeception/Codeception#3432]
Using WebDriver, I am trying to click on a label that acts as the javascript anchor for a form checkbox (the actual checkbox being hidden and a ::before font element being used to represent the checkbox as checked or not). 

There is a link in this label which is located at the center of the element; the position I assume is targetted by the `click()` method. Due to this, I can't just `click()` on the element, as it will click the link instead of triggering the checkbox.

I envisioned that the solution for this problem would be to `moveMouseOver()`, using coordinates to displace it to the side, then to click... but `click()` does not allow for a click event at the current cursor location, instead requiring a selector to be applied, thus defeating my purpose.

Is there any way to accomplish what I am attempting in the current WebDriver framework in Codeception? I could really use some help on this one.

**Comment by Naktibalda** [comment]
Probably not. But if you manage to find a javascript code to achieve that, use executeJs method to execute it.

**Comment by Naktibalda** [comment]
A [similar issue](http://phptest.club/t/click-on-element-offset/1261/2) was solved using this code.

```php
$I->executeInSelenium(function (RemoteWebDriver $web_driver)
{
    $xpath = WebDriverBy::xpath(FormPage::$Slider);

    $element = $web_driver->findElement($xpath);

    $web_driver->action()->moveToElement($element)->moveByOffset(100, 0)->click()->perform();
});
```

**Comment by petrisorionel** [comment]
@Naktibalda where I set the locator? and also you know something about this Undefined class FormPage ?

**Comment by Naktibalda** [comment]
[clickWithLeftButton](https://codeception.com/docs/modules/WebDriver#clickWithLeftButton) method can be used to achieve this effect now.

**Comment by saiedtrife** [comment]
@Naktibalda : 
it doesn't work for horizontal scroll: I tried: 

```
$I->executeInSelenium(function (\Facebook\WebDriver\Remote\RemoteWebDriver $webdriver){

    $element = $webdriver->findElement(WebDriverBy::xpath('//*[@id="form-calc-1"]/div[3]/span/span[6]'));
    $webdriver->action()->moveToElement($element)->moveByOffset(12,0)->click()->perform();
});
I tried only with click it works fine, but for moving in X or Y axis no luck with different value (12,10,100,100) respectively  , 

Please tell me if I there something wrong with the code
