### ISSUE TITLE
Skip entire suite

### ISSUE THREAD

**Issue by B4rb4ross4** [Codeception/Codeception#3438]
I want to skip an entire test suite.

I have a symfony1 project that i want to test. So i have tests in
`/test/Codeception` 
I also have a Symfony3 application that is integrated into a subfolder
`/symfony3`
 where every Bundle has it's own Codeception tests.

I now have a codeception.yml in the root directory, where I load all Tests from those directories.

Is the a way to configure which suite from which test directory i want to load?

I have a Jenkins server, where I have Selenium not yet configured, but have an acceptance suite that i run locally. On the Jenkins I want to run all suites except the acceptance Tests for now.

Is there a way to configure to exclude all acceptance suites?

* Codeception version: 
* PHP Version: v2.2.4
* Operating System: Linux Mint 17.3 'Rosa'
* Installation type: Composer

```yml
include:
  - symfony3/src/*Bundle
  - test/Codeception

paths:
  log: test/_output
```

**Comment by Naktibalda** [comment]
http://codeception.com/docs/reference/Commands#Run
` --skip (-s)           Skip selected suites (multiple values allowed)`

Try `codecept run -s acceptance`

**Comment by B4rb4ross4** [comment]
Thx btw, worked.
