### ISSUE TITLE
How to enable custom extensions?

### ISSUE THREAD

**Issue by stdex** [Codeception/Codeception#3449]
**Details**

* Codeception version: 2.2.4
* PHP Version: 5.6
* Operating System: Windows
* Installation type: Phar (Run with command php codecept.phar run api -vv)

**Problem 1:**

Need to enable custom extension.

I try:

codeception.yml:
```yml
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\DefineEventsExtension
```

/tests/_bootstrap.php:
```php
<?php
// This is global bootstrap for autoloading
include_once __DIR__.'/_support/Extension/DefineEventsExtension.php';
```

/tests/_support/Extension/DefineEventsExtension.php:

```php
<?php

class DefineEventsExtension extends \Codeception\Extension
{
    // list events to listen to
    public static $events = array(
		'suite.before' => 'beforeSuite',
        'suite.after' => 'afterSuite',
    );

    // methods that handle events

	public function beforeSuite(\Codeception\Event\SuiteEvent $e) {
		var_dump($e->getSettings());
	}
	
    public function afterSuite(\Codeception\Event\SuiteEvent $e) {
		
	}
}
```

Output:

>   [Codeception\Exception\ConfigurationException]
>   Class `Codeception\Extension\DefineEventsExtension` is not defined. Autoload it or include into '_bootstrap.php' file of 'tests' directory

**Comment by Naktibalda** [comment]
You missed namespace declaration in your extension file:
```php
namespace Codeception\Extension;
```

**Comment by stdex** [comment]
Yes. Thanks!
