### ISSUE TITLE
Please stop changing namespaces

### ISSUE THREAD

**Issue by bjcullinan** [Codeception/Codeception#3450]
Every time I update this module the namespaces have changed and I have to go and change a bunch of script files.  Please pick a naming scheme and stick to it.  This is the only module that has problems working after an update.

**Comment by Naktibalda** [comment]
What module? What namespaces? Please be more specific!

**Comment by bjcullinan** [comment]
NVM looks like my libraries are out of date for a while and it was loading old classes.  So much has changed it broke my entire validation script.  Seems like I used to be able to run assertEmpty() in an AFTER_STEP event.  Can you point me to a good example of using modules within the STEP event listener?

**Comment by bjcullinan** [comment]
This would explain my original issue, http://stackoverflow.com/questions/32769128/module-webhelper-could-not-be-found-and-loaded
