### ISSUE TITLE
Enhancement of Assertion Flow and Handling

### ISSUE THREAD

**Issue by B4rb4ross4** [Codeception/Codeception#3454]
I'm a software developer in a company with about 60 employees and we build a webshop around a shitton of webservices. About 3/4 year ago i supposed to use codeception to test various endpoints of our selfmade apis. Now about a year later we have suites running with > 10000 assertions because we have to loop over so much stuff in our api responses.

After a somewhat rocky start i started getting deeper into codeception, so I started to modularize code into own helpers to reduce copying test code over and over.

Now the problem that I'm running into is the nature of codeception that every failed assertion will stop the execution of a test step in a Cest.

WAIT!!

Yes a know about see/can see and how i can get conditional assertions.

But I have either to write a wall of assertions into the Cest methods and write kilometers of jsonpath for every assertion, or I group it into methods that call methods that call methods ..... in Helpers/Modules. That keeps the Cests short and clean and reduces copy code, but has the negative effect of hiding the failure, because the report in the end just shows the message of the failed assertion (which is in most cases kind of messy) and that the assertion that is the top of the assertion tree has failed (and not the actually failed one).

So I came up with some Ideas, how to improve the whole process. But that would be kind of breaking changes (maybe).

So I would want to talk to you guys first and share some ideas (maybe there is an already existing way to achieve the same thing) and maybe we can figure out something cool.

I would be willing to invest a significant time portion into coding myself (in my free time), and if my ideas are crap I would also want to help with other stuff you have in the pipeline (I would be willing to clean up the JsonType mess, it's really barebones and unhandy to use).

If you are interested drop me a message and we can get into chat.

**Comment by Naktibalda** [comment]
Could you share your ideas here?

**Comment by B4rb4ross4** [comment]
Sure I will write them down. Maybe not today, because it's awesome weather outside, but very soon ;)

**Comment by DavertMik** [comment]
Yes, please do. Sounds interesting.

**Comment by Naktibalda** [comment]
@B4rb4ross4 if you take too long, this issue will be closed.

**Comment by B4rb4ross4** [comment]
Give me some more days pls. Was doing some overtime at work the last days ;) I haven't forgotten it.

**Comment by B4rb4ross4** [comment]
I was looking up some stuff thew past few days and that raised some questions:

Why is the default case that an failing assertion ends the complete step. I thought of some cases and in most cases I would want the step not to terminate. If I check a layout for example for text snippets (headlines, buttons, etc.) I would not want the step to end after one fail, because i have to fix the one mistake and run the test again to see the next mistake. But I would run to see all failures and fix all mistakes at the same time.
One case where I definately would want the test to stop if for example the sumbit button for a formular is missing that i I want to submit. If I can't submit the form, I don't need the following assertions to be run.  
I could easily do that with see/canSee for a flat page. But if I have for Example an API I have an tree of arrays, that I want to validate and I don't want the validation of an API endpoint terminate after 1 single failure (e.g. 1 Attribute missing).

I would like to propose to make an failing assertion not terminate a step the default. And make it optional that one assertions terminates the step (with an annotation for example).

One way to achieve that, that came into my mind was to move the exception handling from Scenario->runStep to the XXXTesterActions. 

--> see in followup comment

**Comment by Naktibalda** [comment]
`can` prefix is not limited to See, it can be used with any assertion which is starting with `see`, e.g. `canSeeResponseJsonMatchesJsonPath` and `canSeeXmlResponseIncludes`
