### ISSUE TITLE
Can we use seeElement for verifying an attribute without value?

### ISSUE THREAD

**Issue by jltoo** [Codeception/Codeception#3461]
#### What are you trying to achieve?

Verifying an attribute without any value?

> Provide test source code if related

`<a data-qaid="paginationPrevious" class="previousBtn" disabled="" data-val="0" data-order="2435818">`

``` php
$I->canSeeElement($jobItemPaginationPrevious, ['disabled']);
$I->canSeeElement($jobItemPaginationPrevious, ['disabled'=>'']);
```

I already tried both but it doesn't work.  

Issue Occurs:
-> Using Chrome

Issue doesn't occurs
-> Using FireFox

**Comment by jltoo** [comment]
When i tried to change the single quote to double it now works.

$I->canSeeElement($jobItemPaginationPrevious, ["disabled"=>""]);

**Comment by Naktibalda** [comment]
Probably it is an issue of Selenium.

**Comment by Naktibalda** [comment]
If it works in one browser and not in another, then it isn't an issue of Codeception.
