### ISSUE TITLE
$I->seeLink relative url

### ISSUE THREAD

**Issue by Zillion01** [Codeception/Codeception#3463]
#### Fails on relative URL, works on absolute URL

> Provide console output if related. Use `-vvv` mode for more details.

```bash
#  
 Test  tests/acceptance/x/x/XLatestCest.php:viewLatestEvents
 Step  See link "Show all","/bla/list/"
 Fail  No links containing text 'Show all' and URL '/bla/list/' were found in page /x/x/latest/

```
> Provide test source code if related

```php
// Used to work. In the source code is <a href="/bla/list/">Show all</a>
$I->seeLink('Show all', '/bla/list/');

// It works when using
$I->seeLink('Show all', 'http://x.local/bla/list/');
```
### Details

* Codeception version: 2.2.4
* PHP Version: 5.6.10
* Operating System: Mac OSX 10.11.6
* Installation type: Composer
* List of installed packages 
* Suite configuration:

```yml
# paste suite config here
class_name: AcceptanceTester
modules:

    enabled:
        - WebDriver
        - \Frontend\Helper\Acceptance

    config:
        WebDriver:
            url: 'http://x.local/'
            window_size: 1280x1024
            browser: firefox

**Comment by Naktibalda** [comment]
It used to pass because before #3170, WebDriver::seeLink wasn't checking url at all.

**Comment by Zillion01** [comment]
Thanks for your reaction.

1. Documentation suggests relative links can be used
http://codeception.com/docs/modules/WebDriver#seeLink

2. What would be a good way if seeLink needs an absolute URL, to get a $baseUrl before it. Preferably based on the env.

**Comment by Naktibalda** [comment]
1. No, documentation says that seeLink "matches links with that exact URL",
2. You could create a helper method and use [_getUrl](http://codeception.com/docs/modules/WebDriver#_getUrl).

**Comment by Naktibalda** [comment]
not a bug.

**Comment by yugenekr** [comment]
Hey guys,

I've updated codeception from version 2.2.1 to 2.2.10 and got the same issue.

If it's not a bug in the code, then at least docs are misleading on this question, especially providing an example where relative URL is in the href, but still seeLink() method asserts it's found:

    $I->seeLink('Logout','/logout'); // matches <a href="/logout">Logout</a>

**In reality codeception doesn't work this way, or am I missing a point?**

An example from my setup:

 html:
```
    <li class="active"><a href="/index-test.php/master/apps">Apps</a></li>
```
this test fails:
```
    $I->seeLink('Apps', '/index-test.php/master/apps')
```

The way Codeception interprets this internally:
```
    // Found element href attribute
    ~/.composer/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:937:
string(44) "http://mydomain.dev/index-test.php/master/apps"

    // Passed $url to check
    ~/.composer/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:938:
    string(27) "/index-test.php/master/apps"
```
