### ISSUE TITLE
How to use clickAndHold() method in acceptance tests? 

### ISSUE THREAD

**Issue by skutinandrei** [Codeception/Codeception#3471]
Hello.

I'm trying to include method clickAndHold() from module  \Facebook\WebDriver\Interactions\WebDriverActions. But actually I cant get how to define this action properly. I have tried to declare method in helper class:
```php
class AcceptanceHelper extends \Codeception\Module {

    public function clickAndHold($el)
    {
        $el = $this->getModule('WebDriver')
              ->webDriver->findElement(\WebDriverBy::xpath('//input[@class="email"]'));
        $action = new WebDriverActions($this->getModule('WebDriver')->webDriver);
        $action->clickAndHold($el)->perform();
    }
}
```
But I've got an error:

> Call to a member function hasModule() on null
in /home/askutin/www/selenium2/vendor/codeception/codeception/src/Codeception/Module.php:173

So my question is how to include this action properly to use it in acceptance tests?

**Comment by Naktibalda** [comment]
1. Does your helper override `__construct()` method? (it shouldn't, but it is one way to make that error happen).
2. Why do you use Codeception 2.1? Upgrade to 2.2

**Comment by skutinandrei** [comment]
1. No, it doesn't.
2. I've upgraded to Codeception 2.2 but nothing has changed.

**Comment by Naktibalda** [comment]
Could you share a complete code of your AcceptanceHelper?

**Comment by skutinandrei** [comment]
```
<?php
namespace Codeception\Module;

// here you can define custom actions
// all public methods declared in helper class will be available in $I

class AcceptanceHelper extends \Codeception\Module
{
	public function clickAndHold($el)
    {
        $el = $this->getModule('WebDriver')
              ->webDriver->findElement(\WebDriverBy::xpath($el));
        $action = new WebDriverActions($this->getModule('WebDriver')->webDriver);
        $action->clickAndHold($el)->perform();
    }
}
```

**Comment by Naktibalda** [comment]
And content of your test file (a minimal example to reproduce your issue), please.

**Comment by skutinandrei** [comment]
```
<?php
$I = new AcceptanceTester($scenario);
$I->clickAndHold(''//input[@class='email']'');
```

**Comment by Naktibalda** [comment]
Try to create a new helper using `codecept generate:helper name`, move your method to a new helper and enable helper in the config of your suite.

**Comment by skutinandrei** [comment]
Thank you! Now it works. Also I've imported WebDriverActions module in my helper:
`use Facebook\WebDriver\Interactions\WebDriverActions;`
