### ISSUE TITLE
FillField with Chosen field is removing first character with codeception + PhantomJs

### ISSUE THREAD

**Issue by venkat1101** [Codeception/Codeception#3475]
#### What are you trying to achieve?

I tried using $I->Fillfield() for chosen field running using PhantomJs browser. It has to fill the text in chosen field
#### What do you get instead?

It is filling the given text however first character of the string has been removed which is breaking the test.
### Details
- Codeception version: 2.2.4
- PHP Version: 5.6
- Operating System: Windows
- Installation type: Composer
- List of installed packages (`composer show`)
  codeception/codeception            2.2.4  BDD-style testing framework
  doctrine/instantiator              1.0.5  A small, lightweight utility to ...
  facebook/webdriver                 1.1.3  A PHP client for WebDriver
  fzaninotto/faker                   v1.6.0 Faker is a PHP library that gene...
  guzzlehttp/guzzle                  6.2.1  Guzzle is a PHP HTTP client library
  guzzlehttp/promises                1.2.0  Guzzle promises library
  guzzlehttp/psr7                    1.3.1  PSR-7 message implementation
  league/csv                         6.3.0  Csv data manipulation made easy ...
  league/factory-muffin              v3.0.1 The goal of this package is to e...
  league/factory-muffin-faker        v2.0.0 The goal of this package is to w...
  monolog/monolog                    1.21.0 Sends your logs to files, socket...
  myclabs/deep-copy                  1.5.1  Create deep copies (clones) of y...
  nesbot/carbon                      1.21.0 A simple API extension for DateT...
  phpdocumentor/reflection-common    1.0    Common reflection classes used b...
  phpdocumentor/reflection-docblock  3.1.0  With this component, a library c...
  phpdocumentor/type-resolver        0.2
  phpspec/prophecy                   v1.6.1 Highly opinionated mocking frame...
  phpunit/php-code-coverage          4.0.1  Library that provides collection...
  phpunit/php-file-iterator          1.4.1  FilterIterator implementation th...
  phpunit/php-text-template          1.2.1  Simple template engine.
  phpunit/php-timer                  1.0.8  Utility class for timing
  phpunit/php-token-stream           1.4.8  Wrapper around PHP's tokenizer e...
  phpunit/phpunit                    5.4.8  The PHP Unit Testing framework.
  phpunit/phpunit-mock-objects       3.2.3  Mock Object library for PHPUnit
  phpunit/phpunit-selenium           3.0.2  Selenium Server integration for ...
  psr/http-message                   1.0.1  Common interface for HTTP messages
  psr/log                            1.0.0  Common interface for logging lib...
  sebastian/code-unit-reverse-lookup 1.0.0  Looks up which function or metho...
  sebastian/comparator               1.2.0  Provides the functionality to co...
  sebastian/diff                     1.4.1  Diff implementation
  sebastian/environment              1.3.7  Provides functionality to handle...
  sebastian/exporter                 1.2.2  Provides the functionality to ex...
  sebastian/global-state             1.1.1  Snapshotting of global state
  sebastian/object-enumerator        1.0.0  Traverses array structures and o...
  sebastian/recursion-context        1.0.2  Provides functionality to recurs...
  sebastian/resource-operations      1.0.0  Provides a list of PHP built-in ...
  sebastian/version                  2.0.0  Library that helps with managing...
  squizlabs/php_codesniffer          2.6.2  PHP_CodeSniffer tokenizes PHP, J...
  symfony/browser-kit                v3.1.3 Symfony BrowserKit Component
  symfony/console                    v3.1.3 Symfony Console Component
  symfony/css-selector               v3.1.3 Symfony CssSelector Component
  symfony/dom-crawler                v3.1.3 Symfony DomCrawler Component
  symfony/event-dispatcher           v3.1.3 Symfony EventDispatcher Component
  symfony/finder                     v3.1.3 Symfony Finder Component
  symfony/polyfill-mbstring          v1.2.0 Symfony polyfill for the Mbstrin...
  symfony/translation                v3.1.3 Symfony Translation Component
  symfony/yaml                       v3.1.3 Symfony Yaml Component
  webmozart/assert                   1.1.0  Assertions to validate method in...
- Suite configuration:
  config:
        PhpBrowser:
            url: ''
        WebDriver:
            url: ''
            browser: 'phantomjs'
            window_size: '1366x768' 
            connection_timeout: '3600'
            request_timeout: '3600'
            capabilities:
                unexpectedAlertBehaviour: 'accept'

```
```

**Comment by DavertMik** [comment]
PhantomJS is not maintained, use it at your own risk
