### ISSUE TITLE
Lumen state persists between requests

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#3477]
Lumen 5.2 is stateless and my application is not using sessions,
but, when I make 2 requests in one test, state persists.

Test Code:

```php
$I->sendPost('/login', [
    'username' => 'valid',
    'password' => 'valid',
]);

$I->canSeeResponseCodeIs(HttpCode::OK);
$I->seeAuthentication();

//this request should fail
$I->sendPost('/login', []);

$I->canSeeResponseCodeIs(HttpCode::UNAUTHORIZED);
$I->dontSeeAuthentication();
```

Debug output:
```
 I send post "/login",{"username":"valid","password":"valid"}
  [Request] POST /login {"username":"valid","password":"valid"}
  [Request Headers] []
  [Page] /login
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"cache-control":["no-cache"],"content-type":["application/json"]}
  [Response] {"token":"bf9b8fbd-b9aa-4822-a8cc-0718a7fcb289"}
 I can see response code is 200
 I see authentication

 I send post "/login",[]
  [Request] POST /login []
  [Request Headers] []
  [Page] /login
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"cache-control":["no-cache"],"content-type":["application/json"]}
  [Response] {"token":"78c6c4e2-d700-431f-9624-71cfa2445348"}
 I can see response code is 401
 FAIL

 I don't see authentication
 FAIL
```

Expected result (it happens when I make a second request in separate test):
```
 I send post "/login",[]
  [Request] POST /login []
  [Request Headers] []
  [Page] /login
  [Response] 401
  [Request Cookies] []
  [Response Headers] {"cache-control":["no-cache"],"content-type":["application/json"]}
  [Response] {"error":"incorrect username or password"}
```

**Comment by Naktibalda** [comment]
I think that I could solve my issue by throwing exception in AuthServiceProvider, but I don't know what exception to throw.

**Comment by janhenkgerritsen** [comment]
I don't use Lumen myself, so I can't really think of something that you are doing wrong. I need to look into it by actually trying out some code, but I don't have the time for that right now. I'll add it to my todo list, but I can't say when I will have time for this.

One thing, is this problem purely test related or does it also occur if you make the same requests to the same application?

**Comment by Naktibalda** [comment]
This is test related.
I wanted to test how authentication tokens are handled, but the test passed before I implemented token handling.

I think that it happens because authentication state persist in static properties of facades.

**Comment by janhenkgerritsen** [comment]
I just finished a huge refactoring of the Lumen module, it is more in line with the Laravel5 module now. I tested it with the sample application and everything works, but the Lumen sample application is very minimal. Can you test the refactored module with your application and see if this refactoring fixed your problem and if it might have introduced some other problems?

You can find the refactored code at https://github.com/janhenkgerritsen/Codeception/tree/refactor-lumen-module. Only the module and connector classes were changed:

- [Lumen Module](https://github.com/janhenkgerritsen/Codeception/blob/refactor-lumen-module/src/Codeception/Module/Lumen.php)
- [Lumen Connector](https://github.com/janhenkgerritsen/Codeception/blob/refactor-lumen-module/src/Codeception/Lib/Connector/Lumen.php)

**Comment by janhenkgerritsen** [comment]
Can this be closed?

**Comment by Naktibalda** [comment]
I haven't tested, but I have no problem with closing this issue.
