### ISSUE TITLE
Segmentation fault (Symfony 3)

### ISSUE THREAD

**Issue by jiumon13** [Codeception/Codeception#3478]
I'm wanna to use acceptance and functional tests together. It is not important in the same bundle or not.
If i delete acceptance or functional tests and keep only one kind of tests everything works fine.
But if together - Segmentation fault.

When i run: 
```bash
php vendor/codeception/codeception/codecept run
````

I get this error:
```bash
Segmentation fault.
```

```bash
Codeception PHP Testing Framework v2.2.4
Powered by PHPUnit 5.4.8 by Sebastian Bergmann and contributors.

Acceptance Tests (0) ---------------------------------------------------------
Modules: PhpBrowser, \Helper\Acceptance
------------------------------------------------------------------------------
------------------------------------------------------------------------------

[AppBundle]: tests from /vagrant/src/AppBundle


AppBundle.functional Tests (1) -----------------------------------------------
Modules: Symfony, Doctrine2, \AppBundle\Helper\Functional
------------------------------------------------------------------------------
RecoveryPasswordCest: Try to test
Signature: AppBundle\RecoveryPasswordCest:tryToTest
Test: tests/functional/RecoveryPasswordCest.php:tryToTest
Scenario --
 I am on route "index"
Segmentation fault
```

```php
<?php
namespace AppBundle;

use AppBundle\FunctionalTester;

class RecoveryPasswordCest
{
    public function _before(FunctionalTester $I)
    {
    }

    public function _after(FunctionalTester $I)
    {
    }

    // tests
    public function tryToTest(FunctionalTester $I)
    {
        $I->amOnRoute('index');
    }
}
```
### Details

* Codeception version: 2.2.4
* PHP Version: PHP 7.0.10-1~dotdeb+8.1 (cli) ( NTS )
* Operating System: Debian GNU/Linux 8.2 (jessie)
* Installation type: Composer
* List of installed packages (`composer show`)

---------------------------------------------------

* beberlei/DoctrineExtensions              v1.0.11
* behat/gherkin                            v4.4.1
* behat/transliterator                     v1.1.0
* bugsnag/bugsnag                          v2.9.2
* cocur/slugify                            v2.3
* codeception/codeception                  2.2.4
* detectlanguage/detectlanguage            2.0.1
* doctrine/annotations                     v1.2.7
* doctrine/cache                           v1.6.0
* doctrine/collections                     v1.3.0
* doctrine/common                          v2.6.1
* doctrine/data-fixtures                   v1.2.1
* doctrine/dbal                            v2.5.4
* doctrine/doctrine-bundle                 1.6.4
* doctrine/doctrine-cache-bundle           1.3.0
* doctrine/doctrine-fixtures-bundle        2.3.0
* doctrine/doctrine-migrations-bundle      v1.2.0
* doctrine/inflector                       v1.1.0
* doctrine/instantiator                    1.0.5
* doctrine/lexer                           v1.0.1
* doctrine/migrations                      1.4.1
* doctrine/orm                             v2.5.4
* egeloen/ckeditor-bundle                  4.0.4
* egeloen/http-adapter                     0.8.0
* egeloen/json-builder                     2.0.1
* evolution7/bugsnag-bundle                2.0.0
* exercise/htmlpurifier-bundle             v0.2.3
* ezyang/htmlpurifier                      v4.8.0
* facebook/webdriver                       1.1.3
* friendsofsymfony/jsrouting-bundle        1.6.0
* friendsofsymfony/rest-bundle             2.0.0
* friendsofsymfony/user-bundle             dev-master 147ca68
* fzaninotto/faker                         v1.6.0
* gedmo/doctrine-extensions                v2.4.22
* guzzlehttp/guzzle                        6.2.1
* guzzlehttp/promises                      1.2.0
* guzzlehttp/psr7                          1.3.1
* hautelook/alice-bundle                   v1.3.1
* hwi/oauth-bundle                         dev-master 4f531b3
* igorw/get-in                             v1.0.3
* imagine/imagine                          v0.6.3
* incenteev/composer-parameter-handler     v2.1.2
* jakoch/phantomjs-installer               2.1.1-p06
* jdorn/sql-formatter                      v1.2.17
* jms/aop-bundle                           1.2.0
* jms/cg                                   1.2.0
* jms/di-extra-bundle                      1.7.1
* jms/i18n-routing-bundle                  2.0.0
* jms/metadata                             1.5.1
* jms/parser-lib                           1.0.0
* jms/serializer                           1.3.1
* jms/serializer-bundle                    1.1.0
* knplabs/gaufrette                        0.2.1
* knplabs/knp-markdown-bundle              1.5.1
* knplabs/knp-menu                         v2.1.1
* knplabs/knp-menu-bundle                  2.1.2
* kriswallsmith/assetic                    v1.3.2
* kriswallsmith/buzz                       v0.15
* league/flysystem                         1.0.27
* leezy/pheanstalk-bundle                  3.2.0
* michelf/php-markdown                     1.6.0
* monolog/monolog                          1.21.0
* myclabs/deep-copy                        1.5.1
* nelmio/alice                             2.2.2
* nelmio/api-doc-bundle                    2.13.0
* ocramius/package-versions                1.1.1
* ocramius/proxy-manager                   2.0.3
* oneup/flysystem-bundle                   1.4.1
* paragonie/random_compat                  v2.0.2
* pda/pheanstalk                           v3.1.0
* phpcollection/phpcollection              0.5.0
* phpdocumentor/reflection-common          1.0
* phpdocumentor/reflection-docblock        3.1.0
* phpdocumentor/type-resolver              0.2
* phpoption/phpoption                      1.5.0
* phpspec/prophecy                         v1.6.1
* phpunit/php-code-coverage                4.0.1
* phpunit/php-file-iterator                1.4.1
* phpunit/php-text-template                1.2.1
* phpunit/php-timer                        1.0.8
* phpunit/php-token-stream                 1.4.8
* phpunit/phpunit                          5.4.8
* phpunit/phpunit-mock-objects             3.2.6
* psr/cache                                1.0.1
* psr/http-message                         1.0.1
* psr/log                                  1.0.0
* sebastian/code-unit-reverse-lookup       1.0.0
* sebastian/comparator                     1.2.0
* sebastian/diff                           1.4.1
* sebastian/environment                    1.3.8
* sebastian/exporter                       1.2.2
* sebastian/global-state                   1.1.1
* sebastian/object-enumerator              1.0.0
* sebastian/recursion-context              1.0.2
* sebastian/resource-operations            1.0.0
* sebastian/version                        2.0.0
* sensio/distribution-bundle               v5.0.8
* sensio/framework-extra-bundle            v3.0.16
* sensio/generator-bundle                  v3.0.7
* sensiolabs/security-checker              v3.0.2
* site5/phantoman                          v1.1.6
* sonata-project/admin-bundle              3.x-dev 310dbd3
* sonata-project/block-bundle              3.1.1
* sonata-project/cache                     1.0.7
* sonata-project/classification-bundle     3.x-dev 626597a
* sonata-project/core-bundle               3.1.1
* sonata-project/datagrid-bundle           2.2
* sonata-project/doctrine-extensions       1.0.2
* sonata-project/doctrine-orm-admin-bundle 3.x-dev 68f9804
* sonata-project/easy-extends-bundle       2.1.10
* sonata-project/exporter                  1.7.0
* sonata-project/formatter-bundle          3.x-dev 2a1c58a
* sonata-project/intl-bundle               2.2.4
* sonata-project/media-bundle              3.x-dev e18a645
* sonata-project/notification-bundle       3.x-dev 1915bd6
* stof/doctrine-extensions-bundle          v1.2.2
* swiftmailer/swiftmailer                  v5.4.3
* symfony/assetic-bundle                   v2.8.0
* symfony/monolog-bundle                   2.11.1
* symfony/phpunit-bridge                   v3.1.3
* symfony/polyfill-intl-icu                v1.2.0
* symfony/polyfill-mbstring                v1.2.0
* symfony/polyfill-php56                   v1.2.0
* symfony/polyfill-php70                   v1.2.0
* symfony/polyfill-util                    v1.2.0
* symfony/security-acl                     v3.0.0
* symfony/swiftmailer-bundle               v2.3.11
* symfony/symfony                          v3.1.3
* tt/translations                          dev-master master
* twig/extensions                          v1.3.0
* twig/twig                                v1.24.1
* webmozart/assert                         1.1.0
* willdurand/geocoder                      v3.3.0
* willdurand/geocoder-bundle               4.1.0
* willdurand/jsonp-callback-validator      v1.1.0
* willdurand/negotiation                   v2.0.3
* zendframework/zend-code                  3.0.4
* zendframework/zend-diactoros             1.3.5
* zendframework/zend-eventmanager          3.0.1
* zendframework/zenddiagnostics            v1.0.9

**Suite configuration:**

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: 'http://127.0.0.1:5050'
            headers:
                env: test
        - \Helper\Acceptance
```
```yml
class_name: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: '../../app'
            var_path: '../../var'
            environment: 'test'
        - Doctrine2:
            depends: Symfony
        - \AppBundle\Helper\Functional
```
```codeception.yml
actor: Tester
include:
    - src/AppBundle
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```

**Comment by Naktibalda** [comment]
It is a bug of PHP or more likely of some PHP extension.
You have to inspect core dump file and find what function caused it, then raise an issue in appropriate place.

http://stackoverflow.com/questions/8305866/how-to-analyze-a-programs-core-dump-file-with-gdb

Basically you have to run `gdb php path/to/core/file`
