### ISSUE TITLE
Problem with doctrine connections

### ISSUE THREAD

**Issue by kooso** [Codeception/Codeception#3479]
We are currently using version 2.0 of Codeception, however we want to upgrade to the latest version (2.2) that supports PHPUnit 5.
We have some code we use Doctrine's entity manager for persisting, but for reading we make use of the Doctrine's connection. It seems that in this situation when using Codeception v2.1 and v2.2, the Doctrine's entity manager uses one connection and Doctrine's connection a different one. You can see this repo https://github.com/kooso/codeception_doctrine_bug_example on how to reproduce it. 

Here is the sample output from the example repo above:
- In version [2.0](https://github.com/kooso/codeception_doctrine_bug_example/blob/2.0/mysql.log#L17) all the queries run inside of the same transaction and all works fine
- In version [2.1](https://github.com/kooso/codeception_doctrine_bug_example/blob/2.1/mysql.log#L17) and [2.2](https://github.com/kooso/codeception_doctrine_bug_example/blob/master/mysql.log#L17) (master in that repo), we can see that a new connection happens in the middle causing that the select doesn't see the changes from insert

**Comment by Naktibalda** [comment]
Could you `git bisect` 2.1 branch of Codeception and identify commit which caused this change?

**Comment by kooso** [comment]
Hi, thanks for your fast response.

I just did it and seems to be this commit eedd32cc9412e916a7d973ea454e325270b1d8c2

**Comment by Naktibalda** [comment]
Use the new http://codeception.com/docs/modules/Symfony#persistService method to persist `doctrine.dbal.backend_connection` between requests and/or tests.

**Comment by kooso** [comment]
@Naktibalda that doesn't solve the problem, I just tried in the repo example calling `$this->integration->persistService('doctrine.dbal.backend_connection', true)` from `_before` method and the behaviour its the same, should I call it from somewhere else?

**Comment by Naktibalda** [comment]
Try adding it to [_getEntityManager()]( https://github.com/Codeception/Codeception/blob/2.2.4/src/Codeception/Module/Symfony.php#L199)

**Comment by kooso** [comment]
@Naktibalda that make my tests pass

**Comment by kooso** [comment]
Thanks for all your help @Naktibalda, for now I have my test passing, but the solution is still a little hacky, [here](https://gist.github.com/kooso/9273062aa03c15cdfa3136e7fcd1d6b9) you can see how the solution looks like. It's there a better way to solve it? Makes sense for this module to persist all doctrine connections? or could Symfony module accept a config with services to persist?

**Comment by Naktibalda** [comment]
Please add this service to Symfony module and make a pull request.

**Comment by cs278** [comment]
Just come across this very same issue myself, is there some reason the service is called `doctrine.dbal.backend_connection`? The default Symfony configuration is `doctrine.dbal.default_connection`.

**Comment by Naktibalda** [comment]
![Wistom of the ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

There is no references to this connection name in the code of Doctrine or Symfony modules,
I made that change because @j-velasco asked for it.
