### ISSUE TITLE
Running tests by name includes too many methods

### ISSUE THREAD

**Issue by oehlschl** [Codeception/Codeception#3481]
#### What are you trying to achieve?

The 'Running Tests' documentation [here](http://codeception.com/docs/02-GettingStarted#Running-Tests) states that 'You can execute one test from a test class (for Cest or Test formats)' via `php codecept run tests/acceptance/SignInCest.php:anonymousLogin`.

If I run this command in a file SignInCest.php containing the method 'anonymousLogin', I expect that only this single test will be run, regardless of the names of other test methods. 

#### What do you get instead?

However, since the method name above is passed to PHPUnit's --filter option, it actually functions as a pattern, matching all method names in which it is a substring. For example, the command above would run all of 'anonymousLogin', 'anonymousLoginFromHomepage', and 'nonanonymousLogin' (trivial examples, assuming all of these methods exist in SignInCest.php), when the expectation is that only a single test would be run.

Similarly, in a test class 'MyClass' containing test methods 'new_user' and 'guest_new_user', there is no way to run just the 'new_user' test; `codecept run MyClass:new_user` would run both.

Additionally, there is no way to way to prevent this behavior without changing the source. Test methods could be uniquely identified with a pattern like '/:testMethod$/', as Codeception test signatures are of the format 'ClassName:TestMethod', but ':' is already used to separate the path from the filter [here](https://github.com/Codeception/Codeception/blob/e31097051056e26d2d70e23b4df57a0f6f7df1b0/src/Codeception/Command/Run.php#L347).

Fixing this would admittedly break functionality for users expecting the test method name passed to `codecept run` to function like a pattern, but it would also make running tests by name work as expected and described.

**Comment by oehlschl** [comment]
I would propose either returning `':' . $filter . '$'` from \Codeception\Command\Run::matchFilteredTestName() so that method names are exactly matched, or updating the explode in the same method to instead use the first ':' char only to separate the path and filter strings, allowing the filter to contain additional ':' chars; in the latter case, regex patterns (including exact matches) could actually be used.

Ex:
- `codecept run MyClass::exactMatch$`
- `codecept run MyClass::prefixMatch`
- `codecept run MyClass:containsMatch`
- `codecept run MyClass:suffixMatch$`
- `codecept run :/:.*arbitraryPatternWithDelimiters/`

**Comment by Naktibalda** [comment]
I prefer updating documentation and leaving behaviour unchanged.

**Comment by oehlschl** [comment]
May I ask why? This is an issue in that, as mentioned, it is impossible to
run only one test of that name is included as a substring of another method.

If you don't want to introduce new behavior, can we at least wrap the
filter with ':' and '$' to perform an exact match? That won't introduce
anything new, and it will actually run at most one test as intended.

I can submit another PR for that.

**Comment by Naktibalda** [comment]
It is your second PR that I don't like.
The first PR won't break anything, but documentation needs to be updated to describe pattern matching.

**Comment by oehlschl** [comment]
Thanks; I also prefer the first. I'll drop the second and update the
documentation as well.

**Comment by Naktibalda** [comment]
Thank you

**Comment by oehlschl** [comment]
Updated the PR with documentation and support for leading ^. See #3482.

**Comment by oehlschl** [comment]
FYI, I think this can be closed since #3482 was merged. Thanks all.
