### ISSUE TITLE
Tests failing because of PhantomJS/Selenium screen resolution, is there a way to render everything without setting the screen resolution?

### ISSUE THREAD

**Issue by riyunoa** [Codeception/Codeception#3491]
I have a test failing because of the screen resolution. I'm looking to "see" a link on a vertical navigation menu in this way:
`$I->seeElement('//*[@id="nav"]/li[10]/a');`

I've tested this with both PhantomJS and Selenium. To get around this issue, I set the window_size in acceptance.suite.yml to a larger size (i.e. 1024x768).

Is there a way to make PhantomJS/Selenium render the whole page regardless of the window height set, so the tests don't fail because of scrolling?

**Comment by Naktibalda** [comment]
PhantomJS is dead https://github.com/ariya/phantomjs/issues/15344
