### ISSUE TITLE
Console formatter processes excess tags from debug responses

### ISSUE THREAD

**Issue by Mitrichius** [Codeception/Codeception#3495]
I use REST module and receive xml http responses. Some of them contain <error> tag. And with debug module enabled I see red formatted text in the middle of the http response without error tag itself. This is confusing.
I know tags with such formatting are used to improve readability of console output. But can you output responses in «raw» format?

Codeception version 2.2.4

**Comment by Naktibalda** [comment]
If we did that, we would lose cyan color of debug output.
