### ISSUE TITLE
Laravel 5 - What's required to make Acceptance Testing function?

### ISSUE THREAD

**Issue by ctrlaltdylan** [Codeception/Codeception#3503]
#### What are you trying to achieve?

Trying to create a functional acceptance test suite in codeception for a Laravel 5 application.

#### What do you get instead?

Documentation states it is not recommended, would like to discuss a possible solution.

EDIT - cannot link directly to the section of the documentation, but the page is here: http://codeception.com/docs/modules/Laravel5

**Comment by Naktibalda** [comment]
What is not recommended?

**Comment by ctrlaltdylan** [comment]
http://codeception.com/docs/modules/Laravel5

> You should not use this module for acceptance tests. If you want to use Laravel functionality with your acceptance tests, for example to do test setup, you can initialize the Laravel functionality by adding the following lines of code to your suite _bootstrap.php file:

However, there's some odd behavior even with adding the lines of code to the `_bootstrap.php` file. It would be nice to be able to just use acceptance testing out of the box.

My workaround for now is to create functional and integration tests. The functional tests pretty much replace the need for an acceptance test suite. But it would be great to normalize with the other codeception modules and support acceptance out of the box.

**Comment by Naktibalda** [comment]
Read http://codeception.com/docs/03-AcceptanceTests and choose from PhpBrowser and WebDriver.

**Comment by janhenkgerritsen** [comment]
Like @Naktibalda says, for acceptance tests you should use the PhpBrowser or WebDriver modules.

If you want to use Eloquent to setup your database before acceptance tests you can add the lines of codes to `_bootstrap.php` file.

**Comment by ctrlaltdylan** [comment]
@janhenkgerritsen 

Ah I think I understand - for acceptance tests you shouldn't even automate the login process with `Auth::login($user)`. For a _true_ acceptance test you need to create the user, login and do all of the functions necessary to setup the test *by hand through the web interface* with PhpBrowser, Selenium and the like.

If an action is not possible without some kind of domain level bootstraping, like creating another resource that's not avaiable through the web interface, then it's not possible to acceptance test it.

Is that correct?

**Comment by janhenkgerritsen** [comment]
Yes, for acceptance tests you treat the application as a black box.

But you don't necessarily need to write pure acceptance tests, you could for example create a user in the database and after that test login functionality with an acceptance test. And for this scenario you could add the code from the documentation to the `_bootstrap.php` file. But you have to keep in mind that the code used in the tests is not the same as the code that runs in the application that you test with acceptance tests.

**Comment by ctrlaltdylan** [comment]
Thanks @janhenkgerritsen for the answer. I misunderstood the general purpose of acceptance tests. All is good!

**Comment by symbios-zi** [comment]
@janhenkgerritsen ok. The one question: If should not use module for acceptance tests, how can make auto rollback all changes in database using real database? Should I use native laravel methods to rollback trsnsactions in database?

**Comment by janhenkgerritsen** [comment]
With the Db module you can populate/clean the database for acceptance tests. Check out the documentation at http://codeception.com/docs/modules/Db.
