### ISSUE TITLE
how count visible elements?

### ISSUE THREAD

**Issue by rebas82** [Codeception/Codeception#3517]
in documentation, i see function `seeNumberOfElements`
but in my test, i need count of visible items...

how can I do my function (in acceptanceTester.php)?
in sources of Codeception i see this:
```php
return $this->getScenario()->runStep(new \Codeception\Step\ConditionalAssertion('seeNumberOfElements', func_get_args()));

$counted = count($this->matchVisible($selector));
```
Please help...
thanks

**Comment by Naktibalda** [comment]
WebDriver::seeNumberOfElements matches visible elements only (documentation is lacking).
https://github.com/Codeception/Codeception/blob/2.2.4/src/Codeception/Module/WebDriver.php#L1429

**Comment by rebas82** [comment]
yes, i know. But i dont know how doing my own function, if dont know, how many element is on page. :-(

**Comment by Naktibalda** [comment]
matchVisible is a protected method, so you have to extend WebDriver to get access to it.

**Comment by rebas82** [comment]
this working better, then yestrday idea...
        ```
        $arrayProducts = $I->grabMultiple(XPATH_PRODUCTS_BOX);
        $sumProducts = count($arrayProducts);
        $I->comment("In category $selectCategory is total product: $sumProducts");
        $I->seeNumberOfElements(XPATH_PRODUCTS_BOX, $sumProducts);
        return $sumProducts;
```
