### ISSUE TITLE
Tests from included configs not taken into account in coverage report

### ISSUE THREAD

**Issue by torkiljohnsen** [Codeception/Codeception#3527]
### What are you trying to achieve?

I have split up some of the codebase into separate packages, but still keeping the packages bundled in one repository. At some point they may be completely separated into different repositories, but for now they are not.

When I run codeception I still include the files in all packages in the coverage report.

Directory structure looks something like this:

```
app
└── codeception.yml
└── tests
    └── _output
    └── integration
    └── …etc
packages
└── package_name
    └── codeception.yml
    └── tests
        └── unit
```

This means I am putting unit tests into separate folders within their respective package folders. Each package folder is getting its own `codeception.yml`, its own `tests` folder with its own `tests/unit.suite.yml`. Integration tests are still in the main app folder.

_The problem is that I still want to include the unit tests in the overall coverage report._
### What do you get instead?

Unit tests in packages are executed when I do `codecept run`, but they do not affect coverage at all.

In my codeception.yml file I am including them like this:

``` yml
include:
    - packages/package_name
```

Inside each `package_name` folder there is a separate `codeception.yml` file as you can see, and they all have coverage set to `true` too. I have not set explicit include/exclude flags here though.
### Details
- Codeception version: 2.2.4
- PHP Version: 7.1
- Operating System: OSX
- Installation type: Composer

I have followed the instructions on [customization](http://codeception.com/docs/08-Customization) and how to add paths to other configs that I want to include.

Is this just how Codeception works? That tests added through paths to external configs do not affect overall project coverage?

**Comment by DavertMik** [comment]
Thanks for the report. Yep, looks like code coverage is not playing good with included configs. Probably they should but to be honest it seems low priority issue to me. If you will have a chance to look into it and maybe propose a patch that would be cool.

**Comment by Naktibalda** [comment]
@torkiljohnsen wrote:
> Inside each package_name folder there is a separate codeception.yml file as you can see, and they all have coverage set to true too. **I have not set explicit include/exclude flags here though.**

Setting whitelist include in included package makes it appear in code coverage report.

I tested that with https://github.com/Codeception/Codeception/tree/2.2/tests/data/included
