### ISSUE TITLE
AngularJS module and selectOption

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#3529]
I have a select dropdown that is populated by AngularJS

I'm looking at using the `AngularJS` module and I used the following:

```
$I->selectOption(['model' => 'model.plan'], 'Plan 1');
```

The HTML output is something like this:

```
<select class="form-control" ng-model="model.plan" ng-options="plan.name for plan in selects.plans track by plan.id" name="plan">
    <option value="?" selected="selected"></option>
    <option label="Plan 1" value="1">Plan 1</option>
    <option label="Plan 2" value="2">Plan 2</option>
</select>
```

When i use the above code, I always get the following error:

```
[PHPUnit_Framework_Exception] Array to string conversion
```

Am I using this correctly?

**Comment by Naktibalda** [comment]
Please run codeception with `-vvv` flag and add complete stacktrace to description of your issue.

**Comment by craigwillis85** [comment]
@Naktibalda, I may have found the issue. I'm using `phantomjs` and I'm guessing that even with the AngularJS module enabled, the JS won't be run to populate the select

Is that correct?

**Comment by Naktibalda** [comment]
I don't know.
But even if it is correct "Array to string conversion" shouldn't happen.

**Comment by craigwillis85** [comment]
I get a fairly large selenium log:

    Error: $injector:modulerr
    Module Error

    Failed to instantiate module ng due to:
    TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')

**Comment by DavertMik** [comment]
I think it is something Angular specific. Looks like client side error. Unfortunately I don't know how to help.
