### ISSUE TITLE
How to generate coverage in clover.db format 

### ISSUE THREAD

**Issue by PommeVerte** [Codeception/Codeception#3530]
Hey guys,

I'm currently running various groups of tests separately but I would like to generate a single code coverage report for all tests being run. To accomplish this I'm planning on using ant's `<clover-merge>` but this requires clover `.db` files.

Is there any way to generate these currently using codeception? Alternatively do I have any other options to merge these reports?

Cheers.

**Comment by Naktibalda** [comment]
`--coverage-xml` parameter generates Clover XML file, is it suitable to you?
https://github.com/Codeception/Codeception/blob/2.2.4/src/Codeception/Coverage/Subscriber/Printer.php#L108

**Comment by PommeVerte** [comment]
Unfortunately merging Clover XML files is a bit of a pain with a few gotchas. The ideal situation would have been to be able to generate Clover Registry files (`clover.db`) as these support merging via `clover-merge`.

With that said, very little seems to exist on generating these registry files so I guess I'm out of luck. Will have to code a merge script for XML files.

**Comment by DavertMik** [comment]
We use only code coverage features of PHPUnit, if it doesn't support it Codeception not supports it either.

You can use https://github.com/sebastianbergmann/phpcov to merge codecoverage reports

**Comment by PommeVerte** [comment]
Is it safe to assume that I can generate `coverage.cov`files via `--coverage-php` ?
