### ISSUE TITLE
Can't manually log using the Logger class

### ISSUE THREAD

**Issue by petemolinero** [Codeception/Codeception#3551]
I've required monolog/monolog with composer. I've also added Logger as an extension to `codeception.yml`. I cannot, however, find any way to manually log messages or variables using the Logger class.

Furthermore, when looking at the source code of `Logger.php` I see that the Monolog instance is actually stored inside the `protected` property `logger`.

Is it correct that there is no way to manually (like, during a test) log messages via this class, and that [information saying that you can do that](http://stackoverflow.com/a/21331033/1809762) is incorrect?

**Comment by DavertMik** [comment]
Probably the information is outdated. However, you can update Logger extensions so it could be used to receive log messages

**Comment by Farkie** [comment]
Hey, I've taken a stab at this. Could someone take a look at https://github.com/Farkie/Codeception/pull/1 before I pull it in here? It's essentially now a singleton, and it'll work exactly how you'd expect it to if it was an actual Monolog/Logger.
