### ISSUE TITLE
php parse error in TestRunner.php

### ISSUE THREAD

**Issue by spundertakerks** [Codeception/Codeception#3561]
I try to just run my first acceptance test and get following:

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in phar:///usr/local/bin/codecept/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 383

Codeception vrsion : 2.2.3
PhpVersion : 5.4
PhpUnit : 5.4.7
Installation type: Phar

**Comment by Naktibalda** [comment]
PhpUnit 5.4.7 does not work on PHP 5.4.

Download this phar file instead: http://codeception.com/php54/codecept.phar
