### ISSUE TITLE
[Feature] Include screenshots in reports

### ISSUE THREAD

**Issue by schmunk42** [Codeception/Codeception#3588]
#### What are you trying to achieve?

I want to directly link or see screenshots in the reports, for failed tests and debug screenshots.

### Details

* Codeception version: latest
* PHP Version: n/a

http://stackoverflow.com/questions/27920282/how-to-include-failed-screenshots-into-the-codeception-report

Related: http://phptest.club/t/link-to-screenshot-in-html-report/826

**Comment by DavertMik** [comment]
Done in #3602
