### ISSUE TITLE
[Phalcon] Cannot check headers or grab Content when GET Route returns a File

### ISSUE THREAD

**Issue by kareltrcalek** [Codeception/Codeception#3604]
#### What are you trying to achieve?
I have a GET Route like 
```
GET /project/getfile/token HTTP/1.1
Host: ettest03.cld.ondemand.com
```

 which speaks with 3d platform because it internally knows the link to that file via token provided and downloads that pdf or zip file which is then forwarded as a response of my route /project/getfile/token. Response is Phalcon\Http\Response Type.
Before forwarding the file to the end user (browser) or external platform picking up the fila via route above, I set headers:
 * Content-Type: application/pdf
 * Content-Length: the length of file
 * Cache-Control: no-store

If you call this Route with valid token in browser, you get directly the pdf or whatever file displayed in browser, also with correct headers.
![response_download](https://cloud.githubusercontent.com/assets/22789234/19308102/30a8301e-907e-11e6-8733-c8ab71889ad3.JPG)

If I test this route via Functional Testing, the problem is that I can only check the HTTP Response with _canSeeResponseCodeIs(200)_ and nothing else is working.
 I cannot grab Content, I cannot check the headers used
```
$I->seeHttpHeader('Content-Type', 'application/pdf');
$I->canSeeHttpHeader('Content-Type', 'application/pdf');
$I->grabHttpHeader('Content-Type');
$I->haveHttpHeader('Content-Type', 'application/pdf');
$I->canSeeHttpHeaderOnce('Content-Length');
```

because all this methods return **null**.
I am not really interested in testing the download of that file, because that is done on different level, but I wanna check if the test file (pdf, zip, txt) was sent to end user because I explicitly set all the headers like content-length, content type, cache-control, etc.

 The problem is that the response if that route call is not in $I object at all, no headers, no content, nothing.

#### What do you get instead?
Instead I got from methods mentioned above **null** and I cannot test a single thing coming out from this route with codeception functional tester. I cannot event access the content of response in case I get and send text/plain file.
Of course the whole Cept Test fails.

As you can see in output down here, the content of file is not even assigned to correct value but is somehow flying in between and values like Response Headers and Response are empty (Lorem Ipsum etc is the actual content of the txt file in response forwarded via the route to end user).

> Provide console output if related. Use `-vvv` mode for more details.

```bash
I send get "/project/getfile/57fdfa8c5ac39f0350619041"
  [Request] GET /project/getfile/57fdfa8c5ac39f0350619041
  [Request Headers] []
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.  [Page] /project/getfile/57fdfa8c5ac39f0350619041
  [Response] 200
  [Request Cookies] []
  [Response Headers] []
  [Response]
 I can see response code is 200
 I send get "/project/getfile/57fdfa8c5ac39f0350619042"
  [Request] GET /project/getfile/57fdfa8c5ac39f0350619042
  [Request Headers] []
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.  [Page] /project/getfile/57fdfa8c5ac39f0350619042
  [Response] 200
  [Request Cookies] []
  [Response Headers] []
  [Response]
 I can see response code is 200
```
> Provide test source code if related

```php
$I->sendGET('/project/getfile/' . $token);
$I->canSeeResponseCodeIs(200);
$I->seeHttpHeader('Content-Type', 'application/pdf');
$I->canSeeHttpHeader('Content-Type', 'application/pdf');
$I->grabHttpHeader('Content-Type');
$I->canSeeHttpHeaderOnce('Content-Length');
```
### Details

* Codeception version:  2.2.x-dev
* PHP Version: 7.0
* Operating System: docker container
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        - MongoDb:
            dsn: mongodb://mongo:27017/whateverproject
            populate: false
        - Phalcon:
            bootstrap: '/tests/_bootstrap.php'
            cleanup: true
            savepoints: true
        - REST:
            depends: Phalcon
        - Asserts
        - \Helper\Functional
env:
    travis:
         modules:
            config:
                MongoDb:
                    dsn: mongodb://127.0.0.1:27017/whateverproject
```

**Comment by Naktibalda** [comment]
Is it Phalcon specific or a general problem?
Can you reproduce it with PhpBrowser?

**Comment by kareltrcalek** [comment]
Hi,
 this is not a Phalcon specific problem, the functional tester in codeception uses only external api/route to trigger this functionality without knowing the internal details by calling 
```
$I->sendGET('/project/getfile'. $token);
```

The thing is, how can it be that I cannot access the response details like headers (like described above) if there is a file coming out from route, when I just simply call the GET route? This works perfectly fine with any other responses, like JSON.

**Comment by Naktibalda** [comment]
There are a lot of internal details in https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/Connector/Phalcon.php

**Comment by Naktibalda** [comment]
There is no such issue with PhpBrowser, so it is a Phalcon specific issue.
```
 I send get "http://codeception.com/images/toplogo.png"
 I can see http header "Content-Type","image/png"
 I can see http header once "Content-Length"
 PASSED
```

**Comment by sergeyklay** [comment]
Hello @kareltrcalek,
I'll try to sort out as soon as possible

**Comment by sergeyklay** [comment]
@kareltrcalek,

Unfortunately, I failed to reproduce your issue. At least in my test environment. We have a demo application for testing Phalcon and Codeception integration: [Phalcon Demo Application][demo]. It would be cool if you submit there your PR with the test which you think fails or doesn't finish as expected. It will really help me understand your issue deeper. What do you think, can you create a test to reproduce your issue and submit a PR?

Thanks,

[demo]: https://github.com/Codeception/phalcon-demo

**Comment by kareltrcalek** [comment]
Hi guys, I found the problem, actually it was Phalcon related and now I am able to test above described scenarios without problems. The problem was that I was sending the Phalcon response via send() and not just returning it in my Controller Class (extending from Phalcon/Mvc/Controller) in that action.

 Thank you very much for your help!

**Comment by sergeyklay** [comment]
You're welcome
