### ISSUE TITLE
Yii2 module documentation missmatch

### ISSUE THREAD

**Issue by Oxyaction** [Codeception/Codeception#3613]
Current default setting for `cleanup` option of __Yii2__ module is `false`
while documentation says the opposite.

[actual code](https://github.com/Codeception/Codeception/blob/aee4a74f68b5233c5f826820c78427ec1100e78e/src/Codeception/Module/Yii2.php#L121)
[documentation](https://github.com/Codeception/Codeception/blob/02ee5b75eed804a75c3bfc43b08a3fda25fc4f8a/docs/modules/Yii2.md#config)

**Comment by DavertMik** [comment]
By default all other modules use `cleanup: true` strategy. This should be fixed in code, I think

**Comment by DavertMik** [comment]
Cleanup enabled by default in 2.2.6
