### ISSUE TITLE
Acceptance test for paypal purchase

### ISSUE THREAD

**Issue by abgaryanharutyun** [Codeception/Codeception#3616]
hi everyone , i tried write acceptance test for my site paypal express purchase in my local machine worked fine but in circleci not worked can you help me please can you send me sample example
?
```
$this->executeInSelenium(function(\Facebook\WebDriver\Remote\RemoteWebDriver $webdriver) {
            $handles = $webdriver->getWindowHandles();
            $last_window = end($handles);
            $webdriver->switchTo()->window($last_window);

        });
        $this->click('button#purchase');
```
after click `purchase` button staying in same page

**Comment by DavertMik** [comment]
This issue was moved to http://phptest.club/t/acceptance-test-for-paypal-purchase/1236

**Comment by marciofao** [comment]
This problem seems to persist. I am using this same solution from @abgaryanharutyun and if you var_dump($handles) it seems to detect just only one window.

Also, the link commented where the issue moved is redirecting to somewhere else.

**Comment by Naktibalda** [comment]
phptest.club site has been dead for a few years. Nothing useful was posted to that thread anyway. https://web.archive.org/web/20170427083253/http://phptest.club/t/acceptance-test-for-paypal-purchase/1236

getWindowHandles does not belong to this module, it is a part of [php-webdriver library](https://github.com/php-webdriver/php-webdriver).

Similar issue was discussed at https://github.com/php-webdriver/php-webdriver/issues/553
