### ISSUE TITLE
Conflict class name among suites

### ISSUE THREAD

**Issue by ajiyakin** [Codeception/Codeception#3621]
I have test file with same name for `unit` and my other custom suite name, inside the same project, also it's namespaced (which is of course the namespace would be the same for both unit and my other suite test), so when I try to run the test, error message occurs due to class name has been declared.

### Output console
```bash
PHP Fatal error:  Cannot declare class Developtest\PriceCest, because the name is already in use in develop/tests/unit/PriceCest.php on line 5
```
### Conflict files
- Unit test file: `PriceCest.php` with namespace `Developtest\`
- Another suite name file: PriceCest.php with namespace `Developtest\`

### Details
* Codeception version: 2.2.5
* PHP Version: 7.0.8
* Operating System: Elementary OS (Ubuntu 16.04)
* Installation type: Composer

**Comment by Naktibalda** [comment]
It is your fault, rename one test.
