### ISSUE TITLE
how to click joomla admin [new] button

### ISSUE THREAD

**Issue by adnanasif92** [Codeception/Codeception#3623]
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
What module are you using? WebDriver or PhpBrowser?
Please add relevant parts of HTML to your question.

**Comment by adnanasif92** [comment]
1  Iam using PhpBrowser
2 <div id="toolbar-new" class="btn-wrapper">
	<button class="btn btn-small btn-success" onclick="Joomla.submitbutton('fieldordering.editjobuserfield')">
	<span class="icon-new icon-white"></span>
	**New**</button>
</div>

2.1 this html is outside form element 

3. Tring to click on this using $I->click('New');

**Comment by Naktibalda** [comment]
PhpBrowser does not execute javascript, so clicking that button has no effect.
If you want to test the button itself, you have to use WebDriver.
If you want to test PHP code, you have to find what request is performed by browser after clicking and use [submitForm](http://codeception.com/docs/modules/PhpBrowser#submitForm) method.

**Comment by DavertMik** [comment]
I recommend to ask your Joomla question at http://phptest.club and mention @javigomez there

**Comment by javigomez** [comment]
Naktibalda is right.

@adnanasif92 to use webdriver have a look at this tutorial: http://codeception.com/for/joomla

as DavertMik said, please move your doubts to the http://phptest.club site.

Thanks
