### ISSUE TITLE
$scenario->current('name') is everytime empty

### ISSUE THREAD

**Issue by rebas82** [Codeception/Codeception#3626]
in my cest test i use
$scenario->current('env')
this working perfectly, but when i use
$scenario->current('name')  
this is everytime empty :-(

v.2.2.5

**Comment by Naktibalda** [comment]
Why do you need it?
One way to fix this issue is to remove `$scenario->current('name');` from the docs, have you got a good reason for a fix?

**Comment by rebas82** [comment]
I doing to HTML report fail info with link and screenshot (by comment()  and hook Fail). I will like use saved file from _output (. PNG and. Html),  this file contains: class and test name and string fail.  I know how get class, and don't have test name 😎.  When I don't have test name, I must use makesreenshot() with my own name from_output/debug

**Comment by Naktibalda** [comment]
Do you mean `public function _failed(\Codeception\TestInterface $test, $fail) {}`

Then you can get the test name from `$test->getMetadata()->getName()`

**Comment by Naktibalda** [comment]
Fixed
