### ISSUE TITLE
Creating a dynamic path for output generation

### ISSUE THREAD

**Issue by jltoo** [Codeception/Codeception#3627]
#### What are you trying to achieve?
We are trying to create a single server automation test website which can run a script to their local pc without having the codebase to their local. Since we will have a simultaneous run of scripts, we want to have a dynamic creation of report which will create a new folder for the report upon running of the script.

Current:
It saves to /tests/_output/raw/report

We want:
It saves to /tests/_output/testscript name_date time/report

**Comment by jltoo** [comment]
@Naktibalda here's the configuration we have for the directory of report logs. Is there a way to make it dynamic?

actor: Tester
paths:
    tests: tests
    log: tests/_output/raw
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql

**Comment by DavertMik** [comment]
Right now we don't have it. Please look at [Recorder Extension](https://github.com/Codeception/Codeception/blob/2.2/ext/Recorder.php), it saves screenshots for each test and each step in this test. You can rework it to fit your needs and save and mark screenshots the way you need.
