### ISSUE TITLE
How to create independent suites and run them at once?

### ISSUE THREAD

**Issue by sajti** [Codeception/Codeception#3631]
#### What are you trying to achieve?
I want to create independent suites for the separate parts of my project which needs separate bootstraps. After I write my tests I want to run all of them with one command ("codeception run")

#### What do you get instead?
The suites are not independent in that aspect that they are running in the same and current environment so if I make some "global" changes in one of my suite it is still in effect in the other suite.

For example I want to use some constant with different values in the two different suites but when the second one running the constant is already defined.

* Codeception version: 2.2.5

**Comment by DavertMik** [comment]
It's not an issue of Codeception but limitation of PHP. If you start PHP process once you can't redefine constants afterwards. 

My suggestion to use [Robo](http://robo.li) runner to independently run tests in different processes.

**Comment by DavertMik** [comment]
This issue was moved to http://phptest.club/t/how-to-create-independent-suites-and-run-them-at-once/1245
