### ISSUE TITLE
Allow to check logs during testing

### ISSUE THREAD

**Issue by cb-shenril** [Codeception/Codeception#3639]
This may rather be a module based feature but it would be nice to have a feature to check logs in tests.
The reason is that many developers do not notice PHP warning or feature warning at testing stage.

#### What are you trying to achieve?
Using PSR-3, allow to check logs while testing 
seeNoWarningLog($path=framework_handler)
seeNoErrorLog($path=framework_handler)

seeInLogs($string,$path=framework_handler)

### Details
* Codeception version: 
* PHP Version >= 5.6
* Operating System: All
* Suite configuration: Unit Test , Functional Test

**Comment by Naktibalda** [comment]
Phpunit converts PHP warnings and notices to exceptions.

As for application error logging - shouldn't it manifest in failed tests?
I can't imagine a case when all tests are happily passing, but application is logging error messages.

You are welcome to implement this feature and make a pull request.

**Comment by DavertMik** [comment]
Yep, that sounds a good idea for a module. 3rd party module. You can start it by implementing for your own handler and than share it with community by publishing it on packagist and adding it to [Addons](http://codeception.com/addons) page
