### ISSUE TITLE
What is the replacement for BasePage from yiisoft/yii2-codeception?

### ISSUE THREAD

**Issue by Suseika** [Codeception/Codeception#3640]
In https://github.com/yiisoft/yii2-codeception it says that the package is deprecated and *all features were integrated into Yii2 Codeception module*. But I don't see the functionality that corresponds to `BasePage` from yiisoft/yii2-codeception, i.e. a way to group actions for individual pages in a type-safe manner.

I'm curretnly migrating a project's tests from yiisoft/yii2-codeception to Yii2 Codeception module. We have quite a lot of `BasePage` subclasses. What is recommended to use instead?

**Comment by Suseika** [comment]
I guess http://codeception.com/docs/06-ReusingTestCode#PageObjects is what should be used instead, correct?

**Comment by samdark** [comment]
I think so.
