### ISSUE TITLE
specifying multiple tests to run (ie. for running in parallel on CI)

### ISSUE THREAD

**Issue by dwenaus** [Codeception/Codeception#3647]
#### What are you trying to achieve?

I would like to run more than one test at a time. I am running my tests on CirclCI in 8x parallelism, so I want to run every nth test in a suite. This needs to stay dynamic so I can add more tests or containers. 
#### What do you get instead?

I can only run one test at a time, or I can only run a suite at a time, or I can run a group at a time. There is no way to specify 2+ tests to run at once in one command. Therefore now I run codeception each time to run each test. with 400 tests I'm booting up codeception too often slowing things down.

**Comment by Naktibalda** [comment]
I am right that a better name for your issue would be "Run every Nth test"?

**Comment by dwenaus** [comment]
in one case, yes running every Nth test might be OK. but if we wanted to group tests in 8 buckets to run in parallel we might want to group them so that they all finished at the same time, so then it would be run these arbitrary number of tests.

**Comment by dwenaus** [comment]
One hacky solution I had was to make every test it's own group then you can run multiple groups. But I was just wondering if there was a way to run multiple tests.

**Comment by dwenaus** [comment]
So is there a way to run multiple tests with one command?

**Comment by DavertMik** [comment]
Well, we have a specific chapter about that http://codeception.com/docs/12-ParallelExecution#Step-1-Split-Tests

The idea is to generate a groupfile and load it.

**Comment by Naktibalda** [comment]
What we actually need is something like https://github.com/jwage/phpchunkit
