### ISSUE TITLE
Facilitate partial response match

### ISSUE THREAD

**Issue by MatthewDaize** [Codeception/Codeception#3657]
#### What are you trying to achieve?
Match (partial) contents of a JSON response when testing an API web service.

```
$I->seeResponseContains('"success": "true"');
```

#### What do you get instead?
Matching only works if the entire response matches what is provided. This is misleading considering the function name 'seeResponseContains' implies a partial match.

**Works:**
Response: `{"success":"true","message":"Command successful"}`
Assertion: `$I->seeResponseContains('{"success":"true","message":"Command successful"}');`

**Doesn't work:**
Response: `{"success":"true","message":"Command successful"}`
Assertion: `$I->seeResponseContains(""success":"true"');`

This is important when the response may contain a dynamically generated field (timestamp, status code, message ID) since the response would never match unless you statically set the field value in your application.

### Details

* Codeception version: *2.2.6*
* PHP Version: *5.6.26*
* Operating System: *Fedora 23*
* Installation type: *Composer*

### Proposed Solution

It would be ideal that the `seeResponseContains` and `seeResponseContainsJson` functions execute a partial match instead of a full match. Potentially, a `seeResponseMatches` and `seeResponseMatchesJson` function (or similarly named) would be much more appropriate and more closely describe what they do.

**Comment by eXorus** [comment]
I agree with you the REST module are not ideal.

You can use seeResponseContainsJson with PHP array to do what you want.

**Works:**
Response: {"success":"true","message":"Command successful"}
Assertion: $I->seeResponseContainsJson(['success' => 'true', 'message' => 'Command successful']);

**Works:**
Response: {"success":"true","message":"Command successful"}
Assertion: $I->seeResponseContainsJson(['success' => 'true']);

**Comment by DavertMik** [comment]
`seeResponseContainsJson` is for partial matching...

also for response values can be changed you can use `seeResponseMatchesJsonType`
