### ISSUE TITLE
Symfony network mocks for DNS sensitive tests

### ISSUE THREAD

**Issue by benr77** [Codeception/Codeception#3658]
Symfony supports mocking DNS functions of PHP such as `checkmx()` etc.
https://symfony.com/blog/new-in-symfony-3-1-network-mocking-and-dns-sensitive-tests

Is this also supported in Codeception tests?

**Comment by Naktibalda** [comment]
Try it and see - Codeception should not affect that functionality.

**Comment by DavertMik** [comment]
@benr77 so how it was?

**Comment by DavertMik** [comment]
sorry, looks like it won't work as this feature relies on custom PHPUnit listener added into Symfony Bridge package. Unfortunately Codeception doesn't support PHPUnit listeners as we have our own Helpers and Extensions for that

**Comment by DavertMik** [comment]
I think its [implementation in Symfony is overengineered](https://github.com/symfony/phpunit-bridge/blob/master/SymfonyTestsListener.php). I think it would be nicer to develop a tiny helper/extension which will mock dns requests. Symfony implementation tries to too much and it's hard to see from code where and how it does this.

However, the overall idea of mocking dns requests is as simple as mocking functions. You can use [this package](https://github.com/php-mock/php-mock) to mock them and wrap into a custom Helper.

**Comment by benr77** [comment]
Apologies - super busy and didn't respond back - I had already tried it and it appeared to not work, but I had to move on to other things and didn't have time to check it properly. But yes from my initial attempt it looked like it didn't work.

I will look at the php mock package you suggest - it looks ideal. In a perfect world I wouldn't have two separate solutions (this one and the one in Symfony) but it's not really a problem.

Thanks

**Comment by benr77** [comment]
Ok, tried this and it works easily enough. For reference this is what I have done. Note that the namespace has to match the namespace of the class that calls the DNS function, so in my case it's the Symfony Email Validator.

__In my Helper class:__
```
<?php
namespace Helper;

use phpmock\MockBuilder;

/**
 * Class Functional
 *
 * Here you can define custom actions
 * All public methods declared in helper class will be available in $I
 */
class Functional extends \Codeception\Module
{

	/**
	 * Mock PHP's DNS functions
	 *
	 * This allows us to allow CheckMX validation during tests,
	 * but without a DNS lookup (i.e. we don't need a network)
	 */
	public function mockCheckdnsrr()
	{
		$builder = new MockBuilder();
		$builder
			->setNamespace('Symfony\Component\Validator\Constraints')
			->setName("checkdnsrr")
			->setFunction(
				function ()
				{
					return true;
				}
			);

		$mock = $builder->build();
		$mock->enable();
	}
}
```

__And then in my Cest file__

```
	/**
	 * @param \FunctionalTester $i
	 */
	public function checkEmailValidation(\FunctionalTester $i)
	{
		$i->mockCheckdnsrr();

		// Do test that includes a DNS lookup here
	}
```

The mocked function will continue to be mocked in other tests run in the same execution unless you call `$mock->disable();` explicitly.

**Comment by benr77** [comment]
This now solves my problem that I originally reported over at Symfony itself https://github.com/symfony/symfony/issues/16819

**Comment by DavertMik** [comment]
@benr77 one request for you. Could you post your solution to [PHPTestClub Cookbook](http://phptest.club/c/codeception/cookbook) I think your experience should not be lost and should be shared with others. Copy-pasting your problem and solution would be enough. Thanks.

**Comment by benr77** [comment]
Done.

http://phptest.club/t/mocking-dns-requests-with-codeception-and-symfony/1306
