### ISSUE TITLE
html report have many " in 2.2.6

### ISSUE THREAD

**Issue by rebas82** [Codeception/Codeception#3659]
In my test i have this:
`$I->downloadEmailFromMailtrap(2, 3, 2);`

In html report i see this:
`+ download email from mailtrap """2""","""3""","""2"""`

**Comment by Naktibalda** [comment]
Is it a new issue in 2.2.6 or is it the only version that you have checked?

**Comment by rebas82** [comment]
I mean, this is new in 2.2.6, but i dont know in 100% beacuse in jenkins i use auto upgrade, on local pc i doing upgrade as manual job. On local pc i was have 2.2.4 (now 2.2.6). 2.2.4 dont have this problem in 100%.

**Comment by DavertMik** [comment]
Yep, I did some changes to HTML reporter in 2.2.6 so this can be it. Not sure I touched this part but probably it happened

**Comment by rebas82** [comment]
if i run test with  --html , in html isnt many "
but if i run test with  --html -d, in html is many "

**Comment by DavertMik** [comment]
I'm not sure I can reproduce this. Can you make a screenshot? 
Also could you print the console output of your tests?
