### ISSUE TITLE
click on P tag is not working 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [Codeception/Codeception#3666]
#### What are you trying to achieve?
Click operation on P tag

#### What do you get instead?
P tag has a script to hide and open functionality 

```php
        $I->click('[id="Inactive"]');
	$I->wait(1);
	$I->waitForElementVisible('.inactive-items',5);
```
### Details
HTML and Script 

```
<p class="inactive-action item list-group-item"  id="Inactive">Inactive...</p>
 <div class="inactive-items hidden">
</div>
$('.inactive-action').click(function(){
		    var $elem = $(this);
		    $elem.next().slideToggle('fast', function() {
		    	$elem.next().toggleClass('hidden');
		        if(!$elem.next().hasClass('hidden')){
		            $elem.html('Less...');
		        }
		        else{
		            $elem.html('Inactive...');
		        }              
		      });
		});  

```
Output : [Facebook\WebDriver\Exception\TimeOutException]

**Comment by DavertMik** [comment]
Did you try to wrap your jquery code in 

```
$( document ).ready(
  // your script goes here

)
```

**Comment by ihatecodinglikeking** [comment]
@DavertMik 
yes its inside 
```
$(document).ready(function() {
}):
```

**Comment by krishnatejareddy** [comment]
Finally... 
Its a problem with my jquery.... my be having "ready" two times...
I am not sure about it but I deleted its worked fine... 

@DavertMik  thanks for your help.

**Comment by ihatecodinglikeking** [comment]
Finally... 
Its a problem with my jquery.... my be having "ready" two times...
I am not sure about it but I deleted its worked fine... 

@DavertMik  thanks for your help.
