### ISSUE TITLE
Is There any way to see browser console block 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [Codeception/Codeception#3667]
Hi There,

Is there anyway to see browser console has any errors like:
`Uncaught SyntaxError: Unexpected token ,`

I am running Acceptance Test but My JQuery is not at all working so I want to see Is there any possibility to achieve that ?

**Comment by DavertMik** [comment]
Sorry, right now Codeception doesn't support this. Probably you can google about how you can make this using Selenium Webdriver. Codeception uses facebook/php-webdriver which is very nice and very similar to Java. So Java answer will work for you, you just need to implement a helper.
