### ISSUE TITLE
Typo in source code (possible bug)

### ISSUE THREAD

**Issue by disharmonized** [Codeception/Codeception#3671]
#### What are you trying to achieve?
Understand how jsonType parser is working.

#### What do you get instead?

I get confused while reading source code here:

> https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Util/JsonType.php#L99-L101

There are two identical `if` statements. Why? May be it is typo?

### Details

* Codeception version: 2.2
* PHP Version: 5.6
* Operating System: Ubuntu 16.04
* Installation type: Composer

**Comment by Naktibalda** [comment]
Yes, it seems unnecessary, please remove.

**Comment by DavertMik** [comment]
If Scruinizer was a human he would definitely find me and kill me for these lines. Hopefully it isn't. So I can merge a pull request with a fix to this bug if you send it. Please do so )

**Comment by disharmonized** [comment]
@DavertMik okay, butwhat should i do then: just remove one line?
