### ISSUE TITLE
Chinese tddc in Windows7 environment

### ISSUE THREAD

**Issue by xiaoxing598** [Codeception/Codeception#3674]
The test results and following me on CentOS display is not the same, but also in the Win7 Chinese garbled.

![qq 20161102190958](https://cloud.githubusercontent.com/assets/5615719/19926640/a3669236-a130-11e6-810a-0415486fbf6f.png)

**Comment by Naktibalda** [comment]
Use `--no-ansi` parameter to get output without colour codes.
I can't help with chinese, I think that it is an issue of your terminal.

**Comment by xiaoxing598** [comment]
According to your suggestion now only Chinese garbled, I want to do something about it again from Google!

![qq 20161102203204](https://cloud.githubusercontent.com/assets/5615719/19928902/a37bf68e-a13b-11e6-8ede-b6ef7c25dd18.png)

**Comment by xiaoxing598** [comment]
I tried it and found my terminal to be able to display Chinese characters normally.

![qq 20161102205239](https://cloud.githubusercontent.com/assets/5615719/19929408/33b92bf2-a13e-11e6-8f15-611c30e9d365.png)

**Comment by Naktibalda** [comment]
Are you using UTF-8 or some other charset?
Codeception has UTF-8 hardcoded in many places.

**Comment by xiaoxing598** [comment]
The encoding format in the project is UTF-8, in addition to my terminal there are only two options, in fact, GBK code can also display the Chinese characters and English characters.

![qq 20161103092852](https://cloud.githubusercontent.com/assets/5615719/19953358/e4b58504-a1a7-11e6-8c01-038415db8e38.png)

**Comment by DavertMik** [comment]
Did you try to use ConEmu? Maybe it have more options for terminal encoding?

**Comment by xiaoxing598** [comment]
I think the author should consider supporting international

**Comment by Naktibalda** [comment]
@xiaoxing598 If this issue is Windows specific, then it is unlikely to be an issue of Codeception.
But if you know how to fix it, you are welcome to do a pull request.

**Comment by xiaoxing598** [comment]
ok.thanks!
