### ISSUE TITLE
fail screenshot in html report

### ISSUE THREAD

**Issue by rebas82** [Codeception/Codeception#3677]
1) when i run test by selenium server (chrome), screenshot is only from visible screen. When i run test by phantomjs, screenshot is frome complete page (i can see everything on page).

Is it posible have complete screenshot from selenium server as is from phantomjs?

2) some people dont like screenshots in html report, or have own function for doing fail screenshot (as me). Is it posible doing some settings to YML file, where tester set if they need failscreenshot or not need?

**Comment by eXorus** [comment]
According to the documentation of Selenium it's not possible:
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/TakesScreenshot.html

> For WebDriver extending TakesScreenshot, this makes a best effort depending on the browser to return the following in order of preference:
> 
>     Entire page
>     Current window
>     Visible portion of the current frame
>     The screenshot of the entire display containing the browser

**Comment by DavertMik** [comment]
Thanks @eXorus

**Comment by DavertMik** [comment]
>  Is it posible doing some settings to YML file, where tester set if they need failscreenshot or not need?

It's not possible right now
