### ISSUE TITLE
Codeceptino loaded by composer does not find autoload.php

### ISSUE THREAD

**Issue by julesbl** [Codeception/Codeception#3684]
Installed codeception using composer.

Trying to run from command line using the script in vendor/bin/codecept
php ./vendor/bin/codecept
expected to see command line options
saw this instead

Warning: require_once(/webapps/ssp_dev_php7/vendor/bin/autoload.php): failed to open stream: No such file or directory in/webapps/ssp_dev_php7/vendor/bin/codecept on line 7

Fatal error: require_once(): Failed opening required '/webapps/ssp_dev_php7/vendor/bin/autoload.php' (include_path='.:/usr/local/share/pear70') in /webapps/ssp_dev_php7/vendor/bin/codecept on line 7

Was able to fix by changing line 7
from
require_once __DIR__.'/autoload.php';
to
require_once __DIR__.'/../autoload.php';

Codeception version 2.2.4
Installatino method: Composer

**Comment by eXorus** [comment]
Hello,

I can't reproduce your issue:
```

$ composer require codeception/codeception:2.2.4
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
[...]
Writing lock file
Generating autoload files


$ php ./vendor/bin/codecept
Codeception version 2.2.4

Usage:
  command [options] [arguments]

Options:
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
  -n, --no-interaction   Do not ask any interactive question
  -c, --config[=CONFIG]  Use custom path for config
  -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  bootstrap             Creates default test suites and generates all required files
  build                 Generates base classes for all suites
  clean                 Cleans or creates _output directory
  console               Launches interactive test console
  dry-run               Prints step-by-step scenario-driven test or a feature
  help                  Displays help for a command
  list                  Lists commands
  run                   Runs the test suites
 generate
  generate:cept         Generates empty Cept file in suite
  generate:cest         Generates empty Cest file in suite
  generate:environment  Generates empty environment config
  generate:feature      Generates empty feature file in suite
  generate:groupobject  Generates Group subscriber
  generate:helper       Generates new helper
  generate:pageobject   Generates empty PageObject class
  generate:phpunit      Generates empty PHPUnit test without Codeception additions
  generate:scenarios    Generates text representation for all scenarios
  generate:stepobject   Generates empty StepObject class
  generate:suite        Generates new test suite
  generate:test         Generates empty unit test file in suite
 gherkin
  gherkin:snippets      Fetches empty steps from feature files of suite and prints code snippets for them
  gherkin:steps         Prints all defined feature steps



$ cat ./vendor/bin/codecept 
#!/usr/bin/env php
<?php
/**
 * Codeception CLI
 */

require_once __DIR__.'/autoload.php';
[...]

```

**Comment by Naktibalda** [comment]
@julesbl  `vendor/bin/codecept` is a symlink to `../codeception/codeception/codecept` so that require_once call works correctly.

Do you use an OS which does not support symlinks?

**Comment by julesbl** [comment]
Hi
    Using linux mint on my
        dev machine and its running linux on the server as well.
    Think I know what
        happened, did the composer install on my dev machine and then it
        got ftpd up to the server and the link must have been lost in
        the process.
    Just checked, thats
        what happened.
    Jules
    
    
    On 04/11/16 15:58, Gintautas Miselis
      wrote:
    
    
      @julesbl vendor/bin/codecept
        is a symlink to ../codeception/codeception/codecept
        so that require_once call works correctly.
      Do you use an OS which does not support symlinks?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Codeception/Codeception","title":"Codeception/Codeception","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Codeception/Codeception"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Naktibalda in #3684: @julesbl  `vendor/bin/codecept` is a symlink to `../codeception/codeception/codecept` so that require_once call works correctly.\r\n\r\nDo you use an OS which does not support symlinks?"}],"action":{"name":"View Issue","url":"https://github.com/Codeception/Codeception/issues/3684#issuecomment-258471663"}}}</scrip
 t>
</body>
</html>
</html></blockquote>
    <br>
    <pre class="moz-signature" cols="72">-- 
w34u - Websites Which Work For You
www.w34u.com
www.linkedin.com/in/julianblundell
07833 512221
Company: JB Development Ltd.
Company No: 06604371
</pre>
  </body>
</html>
