### ISSUE TITLE
Allow checking for Exceptions within Unit tests

### ISSUE THREAD

**Issue by CJDennis** [Codeception/Codeception#3685]
#### What are you trying to achieve?
Unit tests for Exceptions

#### What do you get instead?
Ugly code :-)

This is how I've been testing for Exceptions:

```php
  public function testShouldThrowExceptionAttemptingToWriteToNonOpenFile() {
    $file = new File();
    $fe = null;
    try {
      $file->write('Hello');
    }
    catch (Exception $e) {
      $fe = $e;
    }
    $this->assertTrue($fe instanceof FileException);
  }
```

What I would like to do is the following:

```php
  public function testShouldThrowExceptionAttemptingToWriteToNonOpenFile() {
    $this->expectException(new FileException('Invalid file handle', 0), function() {
      $file = new File();
      $file->write('Hello');
    }
  }
```

I've actually been able to achieve this by copying the expectException() function out of codecept.phar and saving it into a trait. I then require the file and use the trait like so:

```php
<?php
require_once('C:/usr/bin/codeceptionExpectException.php');

class FileTest extends \Codeception\Test\Unit {
  use ExpectException;
  // tests
}
```

However, it would be nice if Codeception did this out of the box. Can Exception checking be added to Unit tests too please?

### Details

* Codeception version: 2.2.2
* PHP Version: 5.4.45
* Operating System: Windows XP :-)
* Installation type: Phar

**Comment by Naktibalda** [comment]
You can use PHPUnit's exception functionality in Unit format.

**Comment by Naktibalda** [comment]
https://phpunit.de/manual/4.8/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions

**Comment by CJDennis** [comment]
Thank you for your reply. It was still difficult for me to get it working but I got there in the end. Would you please update the documentation on http://codeception.com/docs/05-UnitTests to make it explicit how to do it? Especially that you can't just use a generic `Exception`, it has to match exactly, e.g. `PHPUnit_Framework_Exception`.

This is the code that finally worked:

```php
<?php
require_once('C:/usr/bin/codeceptionExpectException.php');

class ExceptionalTest extends \Codeception\Test\Unit {
  use ExpectException;

  /**
   * @var \UnitTester
   */
  protected $tester;

  protected function _before() {
  }

  protected function _after() {
  }

  // tests
  public function testShouldExpectAnExceptionByFunction() {
    $this->setExpectedException('PHPUnit_Framework_Exception');
    $inf = 42 / 0;
  }

  /**
   * @expectedException PHPUnit_Framework_Exception
   */
  public function testShouldDetectAnExceptionBecauseOfTheAnnotation() {
    $inf = 42 / 0;
  }

  // My ugly workaround
  public function testShouldDetectAnExceptionByBruteForce() {
    $ex = null;
    try {
      $inf = 42 / 0;
    }
    catch (Exception $e) {
      $ex = $e;
    }
    $this->assertTrue($ex instanceof Exception);
  }

  // My nicer workaround
  public function testShouldDetectAnExceptionUsingTrait() {
    $this->expectException(new Exception('Division by zero', 2), function() {
      $inf = 42 / 0;
    });
  }
}
```

**Comment by DavertMik** [comment]
You can either use PHPUnit's annotations or `expectException`: https://thephp.cc/news/2016/02/questioning-phpunit-best-practices

Or use similar named method from `Asserts` module of Codeception. To access a module you will need to call `$this->tester` inside of `Codeception\Test\Unit`:

```php
class ExceptionalTest extends \Codeception\Test\Unit {

  public function testShouldDetectAnExceptionUsingTrait() {
    $this->tester->expectException(new Exception('Division by zero', 2), function() {
      $inf = 42 / 0;
    });

}
```
As you see small refactoring :)

And don't forget to add `Asserts` module to `unit.suite.yml`

**Comment by pYr0x** [comment]
this should be in docs http://codeception.com/docs/modules/Asserts#expectException

**Comment by theMyth721** [comment]
> Thank you for your reply. It was still difficult for me to get it working but I got there in the end. Would you please update the documentation on http://codeception.com/docs/05-UnitTests to make it explicit how to do it? Especially that you can't just use a generic `Exception`, it has to match exactly, e.g. `PHPUnit_Framework_Exception`.
> 
> This is the code that finally worked:
> 
> ```
> <?php
> require_once('C:/usr/bin/codeceptionExpectException.php');
> 
> class ExceptionalTest extends \Codeception\Test\Unit {
>   use ExpectException;
> 
>   /**
>    * @var \UnitTester
>    */
>   protected $tester;
> 
>   protected function _before() {
>   }
> 
>   protected function _after() {
>   }
> 
>   // tests
>   public function testShouldExpectAnExceptionByFunction() {
>     $this->setExpectedException('PHPUnit_Framework_Exception');
>     $inf = 42 / 0;
>   }
> 
>   /**
>    * @expectedException PHPUnit_Framework_Exception
>    */
>   public function testShouldDetectAnExceptionBecauseOfTheAnnotation() {
>     $inf = 42 / 0;
>   }
> 
>   // My ugly workaround
>   public function testShouldDetectAnExceptionByBruteForce() {
>     $ex = null;
>     try {
>       $inf = 42 / 0;
>     }
>     catch (Exception $e) {
>       $ex = $e;
>     }
>     $this->assertTrue($ex instanceof Exception);
>   }
> 
>   // My nicer workaround
>   public function testShouldDetectAnExceptionUsingTrait() {
>     $this->expectException(new Exception('Division by zero', 2), function() {
>       $inf = 42 / 0;
>     });
>   }
> }
> ```

The documentation doesn't make it clear. expectException is not working for me. But the exception does get thrown in the browser. This is probably the last time I am coding in PHP, so Im not massively fussed, but yes the documentation is not clear
