### ISSUE TITLE
Screenshots and HTML Snapshots in the Html Report are using an absolute path

### ISSUE THREAD

**Issue by Zarradhoustra** [Codeception/Codeception#3702]
#### What are you trying to achieve?
View the screenshots and html snapshot in the HTML Report on remote environment such as a CLI.
#### What do you get instead?
The files are linked as an absolute path.

### Details
* Codeception version: 2.2.6

I think it should use a relative path (./) for the files linked in the HTML Report.

**Comment by DavertMik** [comment]
Yep, I was thinking about it as well :+1:
