### ISSUE TITLE
Is it possible to run some suite tests using selenium web driver?

### ISSUE THREAD

**Issue by toby-griffiths** [Codeception/Codeception#3704]
#### What are you trying to achieve?
I need to run some acceptance tests against the the selenium web driver (with JS support), but don't want to run all the tests using it (for speed).
I want to keep all my acceptance tests in 1 place (suite)

Is there a way to do this, or do I need 2 suites?

**Comment by Naktibalda** [comment]
http://codeception.com/docs/07-AdvancedUsage#Groups

**Comment by toby-griffiths** [comment]
@Naktibalda Thanks, but how go I configure one group to use the WebDriver client & another to use the Symfony one?

**Comment by DavertMik** [comment]
No, it's not. It is a very bad idea. Trust me.
Use different test suites for different kinds of tests. acceptance => selenium, functional => symfony

**Comment by toby-griffiths** [comment]
@DavertMik I thought as much, but thought I'd ask.
