### ISSUE TITLE
Yii2: @webroot dir

### ISSUE THREAD

**Issue by githubjeka** [Codeception/Codeception#3706]
#### What are you trying to achieve?
View page has code:
```
$this->registerJsFile('@web/js/d3Temperature.js',
    ['depends' => [\yii\web\JqueryAsset::className(), \common\assets\D3Asset::className()]]);
```

After run the command:
> codecept run functional

`@webroot` doesn't created, because https://github.com/Codeception/Codeception/blob/5654704dd7dde6d8b891666484c1f00d36b394f0/src/Codeception/Lib/Connector/Yii2.php#L255

#### What do you get instead?

``@webroot`` created

This fix https://github.com/Codeception/Codeception/pull/3387 isn't correct.

**Comment by githubjeka** [comment]
I propose to revert #3387 by https://github.com/yiisoft/yii2-app-basic/pull/95

And delete mockAssetManager:
```php
private function mockAssetManager()
{
    $this->app->set('assetManager', Stub::make('yii\web\AssetManager'));
}
```

Because user-coder may want to check whether there is the necessary asset files in directories, through functional tests. Let he will decide to needs this feature for mock component  in his application youself.

**Comment by samdark** [comment]
Checking files is a job of unit tests.

**Comment by githubjeka** [comment]
I agree but for exampe:
```
$I->amOnPage('/');
$I->openFile(\Yii::$app->assetManager->getPublishedPath('@web/js/my-app'));
$I->seeInThisFile('data-url-create = "site/create"');
```

Are you suppose?

**Comment by samdark** [comment]
Again, this is low level stuff and that's the thing for unit tests (integration tests to be precise). Functional tests are to verify more high-level user interaction scenarios.
