### ISSUE TITLE
how to use selenium grid with codeception

### ISSUE THREAD

**Issue by 28Nupur** [Codeception/Codeception#3723]
Hi all,

I have configured selenium grid with codeception and wants to initiate multiple browser instances so as to run the test classes parallel on a single machine.

Is it possible to provide processes count in codeception? 

Please do let me know how this is possible.

**Comment by Naktibalda** [comment]
Your actual question is "How to run tests in larallel", right?
Please read http://codeception.com/docs/12-ParallelExecution

**Comment by 28Nupur** [comment]
yes this is through Robo task runner... but I want it through selenium grid with multiple thread of browsers open in single machine so that my multiple classes get executed

**Comment by ksiv** [comment]
28Nupur, selenium grid just a single-entrypoint it won't split any test for you. you need a parallelization support on the side of a framework. You could try Robo if you a Robo expert.

**Comment by 28Nupur** [comment]
@Naktibalda 
I have installed the latest version of codeception and Robo tak runner 0.7.0

I am trying to execute my feature files parallel but I am unable to do. I did try to install Robo latest version but there was some abstract class error.

Please suggest some work around

@ksiv :: I am able to run the cept and cest file via ROBO but not features file. Please suggest any work around.

Thanks in advance

**Comment by ksiv** [comment]
@28Nupur, Sorry I could not help you with Robo. I tried it last month even download link on the Robo site did not wrong. 2. http://codeception.com/install instruction has an option to rebuild phar with Robo. "robo build:phar" doesn't work out of the box (You need to understand robo config).  We decided to abandon our attempt on Robo. Our current implementation is custom parser that runs several streams like 
codecept run suite_name /Folder1
codecept run sute_name /Folder2 
I do hope @Naktibalda will provide a useful instruction for you and our team will use it in the future.
Our current fighting point is c3 remote coverage. :-)

**Comment by 28Nupur** [comment]
Thanks @ksiv  for your response.
@Naktibalda  please help us in this regard.

~Nupur

**Comment by Naktibalda** [comment]
I still can't help you.
