### ISSUE TITLE
Yii2: $enableCsrfValidation of Request

### ISSUE THREAD

**Issue by githubjeka** [Codeception/Codeception#3732]
I try to run a functional test:
```php
        $I->haveRecord(Person::class, $createdUser);
        $I->sendAjaxPostRequest(['/person/delete', 'id' => $createdUser['id']]);
        $I->dontSeeRecord(Person::class, $createdUser);
```

Step `"Don't see record" failed.` 
All the fault of `\yii\web\Request::$enableCsrfValidation = true`.

Now I can fix it via:
1) config.test.php
```php
        'request' => [
            'enableCsrfValidation' => false,
        ],
```
probably it's bad for Acceptance tests.

2) 
```php
        $I->haveRecord(Person::class, $createdUser);
        \Yii::$app->request->enableCsrfValidation = false;
        $I->sendAjaxPostRequest(['/person/delete', 'id' => $createdUser['id']]);
        $I->dontSeeRecord(Person::class, $createdUser);
```
Redundantly...

@samdark and others what you think about mock enableCsrfValidation for Yii2?

**Comment by samdark** [comment]
Either you're turning it off or you're passing correct token. Mocking it makes no sense to me.

**Comment by githubjeka** [comment]
Ok, Thanks
