### ISSUE TITLE
Before annotation doesn't work when beforeMethod has example

### ISSUE THREAD

**Issue by hsb1007** [Codeception/Codeception#3733]
#### What are you trying to achieve?

I am doing API testing and would like to have Login call for some of the action. But login test has some examples to test different scenario

#### What do you get instead?

[InjectionException] Failed to inject dependencies in instance of 'EggpondApiBundle\UserCest'. Failed to create instance of 'Codeception\Example'. Parameter 'data' must have default value.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

/**
     * User Login test
     * @example { "email":"xxx@mailinator.com", "password":"wrongPassword", "status":"400", "expected" :false }
     * @example { "email":"xxx@mailinator.com", "password":"testest", "status":"200", "expected":true }
     * @example { "email":"xxxx@mail.co", "password":"obviouslyWrong", "status":"400","expected":false }
     * @before registerUserTest
     */
    public function loginUserTest(ApiTester $I, Example $example) { }

/**
     * @before loginUserTest
     */
    public function getUserTest(ApiTester $I) { }

```php
// paste test
```
### Details

* Codeception version:  2.2.6
* PHP Version:   5.6
* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by DavertMik** [comment]
Don't use it this way :) In this case I don't even know *how* Codeception should behave. If you need something to be happened before a test, it shouldn't be another test. In your case you will need general `login` method and use it in test and in `before`
