### ISSUE TITLE
Ability to send body content with POST/PUT requests for REST module

### ISSUE THREAD

**Issue by subdee** [Codeception/Codeception#375]
It seems that an extra parameter could be useful for the sendPOST and sendPUT methods, that allows for form fields to be posted in the body content of the request and not as parameters.

Something like this maybe:

``` php
$I->sendPOST('path', array('field' => 'value'), array(), true);
```

where the fields and values would be sent as the body of the request if the fourth parameter ($includeInBody) is true.

Unless there is already a way to do that and I couldn't figure it out.

**Comment by davidjeddy** [comment]
I too ran into something like this. In order to pass content-Body I could not use the send parameter of sendPUT as the query string. We had to create the entire URL in the first param with the second param acting as the body content.
