### ISSUE TITLE
Html report in Jenkins is everytime only as text

### ISSUE THREAD

**Issue by rebas82** [Codeception/Codeception#3761]
When i open html report created in Jenkins, this report is only as text.

If i download this report to local machine, and open it, html report is correctly styled.

**Comment by Naktibalda** [comment]
It looks like an issue of  Jenkins.
Probably you configured report incorrectly.

Please provide more information.

**Comment by DavertMik** [comment]
You need HTML Publisher plugin for Jenkins to see html reports formatted correctly
