### ISSUE TITLE
pg_put_line function is not supported by HHVM

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#3768]
#### What are you trying to achieve?

Run Codeception tests on HHVM

#### What do you get instead?

```
- PostgresTest: Get primary column throws exception if table has composite primary key

Fatal error: Call to unimplemented native function pg_put_line() in /home/travis/build/Naktibalda/Codeception/src/Codeception/Lib/Driver/PostgreSql.php on line 102
```
### Details

https://travis-ci.org/Naktibalda/Codeception/builds/177809795#L1500
https://github.com/PocketRent/hhvm-pgsql/blob/master/README.md#differences-from-zend

**Comment by DavertMik** [comment]
Looks like this was fixed somehow :)

**Comment by Naktibalda** [comment]
I provided an alternative dump file with INSERT statements instead of CSV data.
