### ISSUE TITLE
Not getting all methods from the module

### ISSUE THREAD

**Issue by Airidas10** [Codeception/Codeception#3774]
Hello, I am new to codeception and I am trying to test my forms in a Laravel 5.2 project. 

I run this test:

`/**`
     `* @before logInSuperAdmin`
     `*/`
    `public function` `test_create_new_user_form_fails_without_required_name_input_front_end(Form_back_endTester $I)`
    `{`
        `$I->amOnPage('/admin/user/create');`
        `$I->fillField('name', '');`
        `$I->fillField('email', 'user@example.com');`
        `$I->fillField('password', 'password');`
        `$I->fillField('password_confirmation', 'password');`
        `$I->click('Create');`
        `$I->seeFormHasErrors();`
    `}`

So, I expect an error, because I did not provide a name.
However, I get this:

`[RuntimeException] Call to undefined method Form_back_endTester::seeFormHasErrors`

My form_back_end.suite.yml looks like this:

`class_name: Form_back_endTester`
`modules:`
    `enabled:`
        `- Db:` 
          `cleanup: false`
          `populate: false`
        `- Laravel5:`
            `part: ORM`
            `environment_file: .env.testing`
            `cleanup: false`
        `- \Helper\Functional`
        `- PhpBrowser:`
            `url: '<my_url>'`
            `depends: Laravel5`

So, I include a Laravel5 module and, as the documentation says, I should be able to use seeFormHasErrors() method, but I don't. That happened to me with some other modules and methods too. I ran codecept build as well. 
My understanding is, if I include a module, I should be able to use all the "actions", as they are defined in the docs. Am I failing to understand something? If yes, please help me figure it out :)

**Comment by janhenkgerritsen** [comment]
This happens because your suite configuration file contains the line `part: ORM`, because of this line only the methods of the Laravel5 module related to the database are included, such as `haveRecord`, `seeRecord`, etc. If you remove that line all methods will be included.

**Comment by Airidas10** [comment]
Yup, that fixed it, thanks :) 

I guess it also explains all the other issues of the same nature that I had.. :)
