### ISSUE TITLE
Unable to set base host url with subfolder using amOnUrl

### ISSUE THREAD

**Issue by venkat1101** [Codeception/Codeception#3782]
I want to access new application available in sub folder (http://localhost/test). So I am using amOnUrl() to go that page with absolute url of new application. However if I need to access some other page in that application with amOnPage('/users/add'), it is trying to open the page 'http://localhost/users/add' instead of 'http://localhost/test/users/add'.  It seems amOnUrl is setting only host as base host. Can someone tell me how I can set sub folder also as base host. 

Codeception : 2.2.5
Webdriver: PhantomJs V2.1
Php: 5.6

**Comment by Naktibalda** [comment]
Better 4 years later than never :)

`amOnUrl` executes this code:
```php
    $host = Uri::retrieveHost($url);
    $this->_reconfigure(['url' => $host]);
```

You could create your own method in helper class:

```php
public function amOnUrlWithPath($url)
{
        $this->_reconfigure(['url' => $url]);
        $this->debugSection('Base URL', $url);
        $this->webDriver->get($url);
}
```
