### ISSUE TITLE
--skip-test is not working

### ISSUE THREAD

**Issue by brutuscat** [Codeception/Codeception#379]
I'm trying to skip some groups since I have some dependencies broken (please vote for a fix https://bugs.php.net/bug.php?id=65066)

So while I'm getting apache in my CI server, I need to skip some tests that I know are never going to work because of the PHP built-in server issue.

So I have a test created like so:

```
codecept generate:cept api CreateEmail
```

Then in the test

```
<?php
$scenario->group('nophpserver');
$I = new ApiGuy($scenario);
$I->wantTo('create an email');
// And so on...
```

And I'm running Codeception like this:

```
php vendor/codeception/codeception/codecept run -sg nophpserver
```

Or like this

```
php vendor/codeception/codeception/codecept run --skip-group nophpserver
```

None of them work. The test is NEVER filtered OUT.

**Comment by bellmon** [comment]
Hi.
I faced with the problem of --skip-group functionality
Is it possible to skip multiple groups?At once
For example I run the command :
php vendor/bin/codecept run acceptance tests/acceptance/airbags/ --env barnbrookrealty,staging --skip-group=contactUs,detailView
Also I tried to change the name of my groups to :
php vendor/bin/codecept run acceptance tests/acceptance/airbags/ --env barnbrookrealty,staging --skip-group=contact_us,detail_view
And I still can't skip those two groups.

Composer file :
{
    "require": {
        "phpunit/phpunit": "4.*",
        "codeception/codeception": "2.2.*",
        "captbaritone/mailcatcher-codeception-module": "1.*",
        "guzzlehttp/guzzle": "5.3.0",
        "symfony/console": "3.3",
        "site5/phantoman": "^1.1",
        "ychabaniuk/server-runner": "1.0.3"
    },
    "autoload": {
        "psr-4": {"App\\": "app/"}
    }
}

Acceptance yml. file :
class_name: AcceptanceTester

modules:
    enabled:
#        - PhpBrowser:
#            url: http://www.barnbrookrealty.com.staging
#            curl:
#                CURLOPT_TIMEOUT: 35000
        - WebDriver:
            url: http://www.barnbrookrealty.com.staging
            browser: phantomjs
        - \Helper\Acceptance

extensions:
    enabled:
        - Ychabaniuk\ServerRunner\ServerRunner
    config:
        Ychabaniuk\ServerRunner\ServerRunner:
            serverFolder: 'libs/server/'
            driverFolder: 'libs/driver/'
            debug: false
env:
    barnbrookrealty:
        modules:
            config:
                PhpBrowser:
                    url: http://www.barnbrookrealty.com.staging
# browser specific environments
    chrome:
        modules:
            config:
                WebDriver:
                    url: http://www.barnbrookrealty.com.staging
                    browser: chrome
                    delay: 1000

    firefox:
        modules:
            config:
                WebDriver:
                    url: http://www.barnbrookrealty.com.staging
                    browser: firefox

    phantomjs:
        modules:
            config:
                WebDriver:
                    browser: phantomjs
                    window_size: 1366x768
#                    delay: 700
                    capabilities:
                        unexpectedAlertBehaviour: 'accept'
