### ISSUE TITLE
Initialize loadedFixtures in Codeception\Module\Yii2::_after

### ISSUE THREAD

**Issue by MuratYMT** [Codeception/Codeception#3794]
Add 
`$this->loadedFixtures = [];`
after 
`foreach($this->loadedFixtures as $fixture) {
     $fixture->unloadFixtures();
}`
for clear loadedFixtures after each test

**Comment by samdark** [comment]
http://yiiframework.ru/forum/viewtopic.php?f=33&t=41129

**Comment by samdark** [comment]
Seems to be valid. @DavertMik ?
