### ISSUE TITLE
redis auth

### ISSUE THREAD

**Issue by evan2579429110** [Codeception/Codeception#3799]
我需要配置redis,但是当我发现如果redis设置了密码，将无法连接到，也无法从官网得到有效的解决方法，并没有auth配置

- Redis:
                  host: '127.0.0.1'
                  port: 6379
                  database: 0
                  cleanupBefore: 'never'

**Comment by evan2579429110** [comment]
看了一下配置，在predis里是有的，codeception官方可能去掉了，希望能够加上

**Comment by Naktibalda** [comment]
Google translate:

> I need to configure redis, but when I found that if redis set up a password, will not be able to connect to the official website can not be an effective solution, and no auth configuration

> Look at the configuration, there are predis Lane, codeception official may be removed, hoping to add

**Comment by DavertMik** [comment]
English please. We can't understand nor solve your issue, please ask someone to explain everything in details we need to understand and resolve the issue. Thanks

**Comment by evan2579429110** [comment]
I want to configure redis，but I found after the redis configure the password,Codeception input password options are not there.I saw the redis configuration in the website,as follows 
Redis:
host: ‘127.0.0.1’
port: 6379
database: 0
cleanupBefore: ‘never’ 
I saw redis in the codeception predis from predis, I think its may be removed by the offcial, if there is no this feature,I hope to add it, if there is hope to notes in the redis module of oficial website  , thank you
