### ISSUE TITLE
REST::seeResponseContainsJson fails with null keys

### ISSUE THREAD

**Issue by igorsantos07** [Codeception/Codeception#381]
I was trying to test a complex object returned from my API that has some nulled fields (such as `updated_date`) but it was always failling. After some investigation I noticed that the `arrayIntersectAssocRecursive` skips null values and that's probably what's creating the failure, since the return of that method is the same array, but with those null keys removed - breaking the comparison.

I have little idea of what do there, afraid of breaking other stuff as I have no experience with Codecept internals... Any idea?

**Comment by jvalecillos** [comment]
This is now present in 2.0.11 but it wasn't a version before (a month ago).
