### ISSUE TITLE
Grab multiple rows from a database

### ISSUE THREAD

**Issue by RebOOter** [Codeception/Codeception#3813]
I'm trying to add some object with parameters which depends on some tables in a database. For example, let's call the object – 'car' and one of parameters call 'type'. The 'type' can't be managed from UI, it's already filled in the database. When I generate the 'car' I should take one of parameters from the database. Of course, I can look at the database manually and write my faker method to generate the 'type' but it's not very good solution because that data can be changed. In this case, I should take all available types from the database and select one of them.

Unfortunately, the Codeception don't have a method to get more than one row from a database. If I use `$I->grabFromDatabase('types', 'id');`, I'll always get the first row. I write my own method in new module for getting multiple rows, but I think it would be great to have this method in the Codeception 'from the box'.

If you need more abstract reason, I can tell the case by another words: when we should generate an object for test(s) but data of this object is depends from outside source (that can be changed) we must generate fake data using this source without duplicating this in the code.

**Comment by DavertMik** [comment]
Please send a pull request with your implementation!

**Comment by RebOOter** [comment]
I don't think that my solution is perfect :)

Let me show the code here before I send pull request.

```
public function grabMultiplyFromDatabase($table, $column, array $criteria = [])
    {
        $query      = $this->getModule('Db')->driver->select($column, $table, $criteria);
        $parameters = array_values($criteria);
        $this->debugSection('Query', $query);
        if (!empty($parameters)) {
            $this->debugSection('Parameters', $parameters);
        }
        $sth = $this->getModule('Db')->driver->executeQuery($query, $parameters);
        return $sth->fetchAll(\PDO::FETCH_COLUMN, 0);
    }

```
It's the same like method ```protected function proceedSeeInDatabase($table, $column, $criteria)``` in src/Codeception/Module/Db.php with one different in the return.

This code can be optimised for main Db module but it may require some refactoring in Db.php

Should I send pull request just with this function? Excuse my disturbing you, it will be my first serious pull request on the GitHub :)

**Comment by hubbyist** [comment]
'grabSetFromDatabase' from database may be a better name for the function which implies dataset ''grabDatasetFromDatabase' is long IMO. Or may be simply 'grabRowsFromDatabase' will be better.
