### ISSUE TITLE
c3: documentation

### ISSUE THREAD

**Issue by ksiv** [Codeception/Codeception#3814]
#### What are you trying to achieve?
get acceptance coverage
#### What do you get instead?
Fatal error OOM

Caused by preposition that there is not project with coverage enabled consume more than 384M mem in php footprint.

`    if ((integer)ini_get('memory_limit') < 384) {
        ini_set('memory_limit', '384M');
    }`

**Comment by Naktibalda** [comment]
@ksiv What do you want to get documented? 
You are welcome to contribute to documentation at https://github.com/Codeception/c3

Provided code is from the old version of c3, please upgrade to 2.0.8.

If you need a higher memory limit, it is up to you to raise it.
