### ISSUE TITLE
Can't override capabilities in configuration

### ISSUE THREAD

**Issue by mpgo13** [Codeception/Codeception#3820]
#### What are you trying to achieve?

Overriding capabilities in configuration file.

`codecept run -o "config: modules: \Helpers\MyWebDriver: capabilities: build: 1234"`

My goal is to have kind-of parameters for configuration files. I know that I can only override the global codeception.yml file, which works for a simple level like 'config: key: value', but not for a deeper level than that (as in the example above).

#### What do you get instead?

Actual Result is configuration doesn't get overrided.

### Details

* Codeception version: 2.2.6
* PHP Version: 7.0.11
* Operating System: MacOS Sierra
* Installation type: Phar

**Comment by DavertMik** [comment]
did you try:

```
codecept run -o "modules: config: \Helpers\MyWebDriver: capabilities: build: 1234"
```
?

**Comment by mpgo13** [comment]
@DavertMik yes, i tried many combinations, the only thing that worked was 

```
codecept run -o "modules: config:  \Helper\AlexWebDriver:   capabilities:    build: '1234'"
``` 

(by indenting with spaces). This seems to allow yaml to parse it correctly. It produces PHP warnings though:

```
Notice: Uninitialized string offset: 0 in /myproject/codeception/codeception/src/Codeception/Command/Run.php on line 406
```

**Comment by DavertMik** [comment]
Thanks for the report, that looks like a bug. I will try to fix that

**Comment by mpgo13** [comment]
thank you @DavertMik, works now 👍
