### ISSUE TITLE
Codeception 2.2 - How to skip/ignore a scenario from feature file? Is there any tags like @skip, @ignore or @incomplete?

### ISSUE THREAD

**Issue by rajabhaskar** [Codeception/Codeception#3823]
#### What are you trying to achieve?
I want to skip the BDD-Gherkin scenarios form feature files. Below is one scenario I have tried with @skip and @ignore /@incomplete (Just tried, I am not sure whether this is the correct way or not. I used to try them like this in cucumber BDD) but found that they are still running and the tags I used are not working. 

Feature: test.feature
  **@Skip @incomplete @ignore**
  Scenario: Regular user login
    Given I am on "/landing_page"
    When I login with "valid_user"
    Then I see element "#logo"

### Details
Need a way to skip tests in feature files. I am not using any cests or cepts in my project. I'm completely relaying on BDD feature files. 

* Codeception version: 2.2.1
* PHP Version: 7.0.7
* Operating System: Windows

**Comment by DavertMik** [comment]
Those tags can only assign test to the group. So marking them as @skip doesnt make a trick. However, you can executive tests without that group:

codecept run --skip-group skip

**Comment by rajabhaskar** [comment]
Thank you @DavertMik ... closing the ticket
