### ISSUE TITLE
Codeception recorder extension cannot record third-party modals

### ISSUE THREAD

**Issue by alex-celentano** [Codeception/Codeception#3833]
I used codeception recorder to make screenshots of third-party windows, e.g Facebook, Google+ authorization pop-ups

In 50% cases I get error logs which are saying that system couldn't make a screen in case, and It was at the moment of appearing an authorization pop-up

An in other 50% cases codeception cannot run tests steps after It didn't pass the step of making screen

Setup is very simple, I just enabled recorder in config file via the offical documentation

* Codeception version: the latest
* PHP Version: 5.4
* Operating System: Ubuntu (the latest)
* Installation type: Phar

**Comment by DavertMik** [comment]
Yep, the recorder extension is pretty simple and I didn't try this on such heavy cases. 
Sorry I don't think I will improve it to work for this things. If you know how you can improve it, please send PR

**Comment by alex-celentano** [comment]
Found this issue -> https://github.com/Codeception/Codeception/issues/2209, that's exactly my case and almost the same errors. 

Think there is no possible solution at the time

**Comment by DavertMik** [comment]
Sorry I couldn't reproduce issue. For my case window was opened in separate window but tests continued to go at the previous window. Can you provide me example to reproduce as well as the selenium/browser you use

**Comment by Naktibalda** [comment]
This issue was waiting for additional information for 4 years.
