### ISSUE TITLE
Unit Suite - incrementing count

### ISSUE THREAD

**Issue by josephzidell** [Codeception/Codeception#3835]
#### What are you trying to achieve?
The ability to see how far along the unit suite is. I want to number each test case starting from 1.

#### What do you get instead?
Just a list, and it's hard to tell how far along it is.

> Current output

```bash
Unit Tests (913) -------------------------------------------
Modules: Asserts, DataHelper, Db, FactoryHelper, UnitHelper
------------------------------------------------------------
✔ AbcTestCase: Invoke inventory (0.61s)
✔ AbcTestCase: Invoke order (0.13s)
✔ AbcTestCase: Push tracking number (0.32s)
✔ AbcTestCase: Push one order mutiple line items (1.33s)
✔ AbcTestCase: Push mutiple tracking numbers (9.06s)
✔ DefTestCase: Execute ebay (2.91s)
```
> Desired output

```bash
Unit Tests (913) -------------------------------------------
Modules: Asserts, DataHelper, Db, FactoryHelper, UnitHelper
------------------------------------------------------------
✔ 1. AbcTestCase: Invoke inventory (0.61s)
✔ 2. AbcTestCase: Invoke order (0.13s)
✔ 3. AbcTestCase: Push tracking number (0.32s)
✔ 4. AbcTestCase: Push one order mutiple line items (1.33s)
✔ 5. AbcTestCase: Push mutiple tracking numbers (9.06s)
✔ 6. DefTestCase: Execute ebay (2.91s)
```
### Details

* Codeception version: 2.2.7
* PHP Version: 5.6
* Operating System: Win 10
* Installation type: Composer
* List of installed packages (`composer show`): N/A
* Suite configuration: Unit, Acceptance

The numbers would left-pad according to the number of digits in the total test count. I can provide a PR if this is approved.

**Comment by DavertMik** [comment]
I don't know how useful can that be... Isn't the end report XX tests passed, YY tests failed, not enough?

**Comment by josephzidell** [comment]
The entire suite takes about 15-20 minutes, and often someone is waiting for it to complete. (We are working on infrastructure changes to improve that speed, but that's a side point)

**Comment by edno** [comment]
I agree with @DavertMik not sure how it will benefit to others. But this can also be done using a custom helper.

**Comment by josephzidell** [comment]
That would suffice. I'll give it a shot. Thanks for your help.
