### ISSUE TITLE
Db::seeInDatabase declaring not null as condition 

### ISSUE THREAD

**Issue by fabianofa** [Codeception/Codeception#3841]
#### What are you trying to achieve?
I'm trying to use Db::seeInDatabase method to assert if a row exists, where the column is not null.

#### What do you get instead?
I tried using:
```
$I->seeInDatabase("table", ["ID" => 1, "STATUS" => 1, "DATE_STATUS !=" => null]);
$I->seeInDatabase("table", ["ID" => 1, "STATUS" => 1, "DATE_STATUS IS NOT NULL"]);
$I->seeInDatabase("table", ["ID" => 1, "STATUS" => 1, "DATE_STATUS IS NOT NULL" => ""]);
```

But nothing work so far except variations of 
`[PDOException] SQLSTATE[HY000]: General error: 904 OCIStmtExecute: ORA-00904: "DATE_STATUS ...": invalid identifier`

How do I use the `IS NOT NULL` clausule with Db::seeInDatabase?
### Details

* Codeception version: 2.2
* PHP Version: 7.0.13
* Operating System: Windows 8.1 x86
* Installation type: Phar

**Comment by Naktibalda** [comment]
Use [grabFromDatabase](http://codeception.com/docs/modules/Db#grabFromDatabase) and `assertNotNull`

**Comment by fabianofa** [comment]
Thank you.

**Comment by adyna23** [comment]
Can you please write exactly the code how do you use grabFromDatabase and assertNotNull together?I need to use grabFromDatabase where a column is null.Thanks

**Comment by Naktibalda** [comment]
My suggestion was to grab by another field and then check if the status field is null.
