### ISSUE TITLE
[functional] Error 1305 SAVEPOINT LEVEL1 does not exist

### ISSUE THREAD

**Issue by slinstj** [Codeception/Codeception#3847]
#### What are you trying to achieve?
Run **functional** tests using Yii2 module

#### What do you get instead?
![selection_002](https://cloud.githubusercontent.com/assets/412490/21299508/861dcc72-c583-11e6-98c0-8a7eb9babb83.png)

#### Additional Info:
#3651 seems related
#3520 seems to resolve only **unit** suite

The only thing that makes the test to work is set `cleanup: false` in Yii2 module (or get rid of the transactions but it is out of cogitation)

### Details

* Codeception version: 2.2.6
* PHP Version: 7.0.1
* Operating System: Mint 18
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        - Yii2
```

**Comment by Naktibalda** [comment]
@slinstj This isn't a bug of Codeception - mysql does not support nested transactions, so your only options are: 
a) cleanup: false in Yii2 module 
b) get rid of the transactions in application code.

If you have another solution, you are welcome to propose it.

**Comment by slinstj** [comment]
Thanks @Naktibalda. As afore mentioned, I was already using the `cleanup: false`.
