### ISSUE TITLE
can anyone tell me how to run acceptance in safari??? I am able to run in chrome, phantom and firefox 

### ISSUE THREAD

**Issue by rajabhaskar** [Codeception/Codeception#3850]
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
  [Facebook\WebDriver\Exception\UnknownServerException]
  The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't
   create a new driver instance for Capabilities [{browserName=safari, handle
  sAlerts=true, unexpectedAlertBehaviour=accept}]
  Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00
  :58'
  System info: host: 'MSI-VIZ-DHP-046', ip: '192.168.180.21', os.name: 'Windo
  ws 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
  Driver info: driver.version: unknown

```
> Provide test source code if related

```php
I am trying like below....

Running server as
java -jar vendor/selenium/selenium-server/selenium-server-standalone-2.53.0.jar -Dwebdriver.safari.driver=vendor/selenium/safaridriver/selenium-safari-driver-2.29.1.jar


and running acceptance as 
codecept run acceptance Landing.feature --skip-group skip -vvv --html
```
### Details

* Codeception version: 
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by edno** [comment]
More likely a php-webdriver issue, see facebook/php-webdriver#345

**Comment by DavertMik** [comment]
Thanks @edno 
Probably it's even more general selenium issue :(

**Comment by rajabhaskar** [comment]
@DavertMik @edno Does this mean Codeception won't work in Safari? Sorry if I misunderstood your answers. I just wanted to run my suite in safari browser. Below is my acceptance.yml file configuration

`modules:
    enabled:
        - WebDriver
        - \Helper\Acceptance
        - \Helper\Locator
        - \Helper\User
        - \Helper\TestData
    config:
        WebDriver:
            url: 'https://www.abc.com'
            browser: safari
            wait: 2
            window_size: maximize
            clear_cookies: false
            capabilities:
                  unexpectedAlertBehaviour: 'accept'
                  handlesAlerts: true`
