### ISSUE TITLE
Find nth link

### ISSUE THREAD

**Issue by gimler** [Codeception/Codeception#3853]
#### What are you trying to achieve?
I have a list of buttons and must click the nth button.

Workaround:
```
$this->click("form:nth-child(1) input[name=form_edit]");
```

I would prefer to find all buttons by 'form_edit' and then use the nth.

Is there a function in WebDriver Module to find elements by selector?

**Comment by DavertMik** [comment]
> Is there a function in WebDriver Module to find elements by selector?

Yes, but the implementation you look for can be made in a custom helper using [_findElements](http://codeception.com/docs/modules/WebDriver#_findElements) method. This should return an array of `RemoteWebElement` instances of facebook/webdriver. You can match the exact one you need and click it

**Comment by gimler** [comment]
Thanks. Problem with `_findElements` is that they don't match `name` attribute.

So i must use this workaround ;(
```
/**
 * Find all matching elements
 * @param $locator
 * @return []
 */
public function findElements($locator)
{
    $elements = $this->webDriverModule->_findElements($locator);
    if (empty($elements))
    {
        $elements = $this->webDriverModule->_findElements('[name=' . $locator . ']');
    }

    return $elements;
}
```
