### ISSUE TITLE
Looking for a way to match some JSON from response.

### ISSUE THREAD

**Issue by mcblum** [Codeception/Codeception#3854]
#### What are you trying to achieve?
Basically I am trying to evaluate the response JSON from our API calls. However, I don't care about a lot of the fields (such as created_at, updated_at).

#### What do you get instead?
Instead of only caring about the JSON I mentioned, `$I->seeResponseContainsJson` evaluates the entire object and fails if I don't mention columns like created_at or stuff we may not really care about at that time.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
- Expected | + Actual
@@ @@
'slug' => 'street-photography'
-        'client_id' => 1
-        'row_order' => 2
+        'client_id' => '1'
+        'row_order' => 1
+        'updated_at' => '2016-12-20 10:03:06'
+        'created_at' => '2016-12-20 10:03:06'
)
'message' => 'Your section has been created.'
)

```
> Provide test source code if related

```php
public function create_a_new_section( CoreTester $I ) {
		// auth header
		$I->haveHttpHeader( 'Authorization', 'Bearer ' . Fixtures::get( 'admin_token' ) );

		$data = [
			'gallery_id' => 1,
			'title'      => 'Street Photography',
		];

		$I->sendPOST( $this->endpoint, $data );

		$I->seeResponseCodeIs( 200 );
		$I->seeResponseContainsJson( [
			'section' => [
				'id'         => 2,
				'title'      => 'Street Photography',
				'gallery_id' => 1,
				'slug'       => 'street-photography',
				'client_id'  => 1,
				'row_order'  => 2
			],
			'message' => 'Your section has been created.'
		] );
	}
```
### Details

* Codeception version: latest
* PHP Version: 7
* Operating System: MacOS running a VM
* Installation type: Composer

Thank you for your work on Codeception! It's truly transformed the way I build applications and there are users everywhere not seeing errors because of what you do.

**Comment by Naktibalda** [comment]
Your test failed because the type of 'client_id' didn't match, you got string instead of integer.

**Comment by mcblum** [comment]
@Naktibalda are you saying that the `+` lines don't cause a fail? I actually corrected that first and still got the same error only with just the `+` lines and not the `client_id` line. Let me re-run just to be 100% sure.

**Comment by Naktibalda** [comment]
And more importantly row_order field got a different value than expected - 1 instead of 2.

The extra fields are irrelevant, the diff output does not represent operation of `seeResponseContainsJson` method.

**Comment by mcblum** [comment]
@Naktibalda You're right -- even though I had corrected both of those issues, it must not have been at the same time. Tests now passing. Sorry for my error.

Also, is it an internal issue or maybe a SQLite issue that columns marked as integers return as strings?

**Comment by Naktibalda** [comment]
It is a PDO thing or Sqlite driver thing.
