### ISSUE TITLE
May I use wildcard in verify point?

### ISSUE THREAD

**Issue by giang-hai-nguyen** [Codeception/Codeception#3871]
Hi guys,
Thanks for great tool.
I am facing the problem that is dynamic data. I want to use wildcard to cover the case but i don't know how.
For example: 
I want to check header: 'Content-Disposition' with value "attachment; filename=FileName-20161226.zip".
So i used $I->seeHttpHeader('Content-Disposition',"attachment; filename=FileName-20161226.zip");
However it will fail in other day when file name is changed.
Is there any way to cover it. Thanks

**Comment by Naktibalda** [comment]
Generate expected value dynamically:
```php
$I->seeHttpHeader('Content-Disposition', 'attachment; filename=FileName-' . date('Ymd') . '.zip');
```

**Comment by giang-hai-nguyen** [comment]
Thanks for response.
But it is just an example. Is there any way to cover all cases??
