### ISSUE TITLE
dontSeeFileFound method doesn't work

### ISSUE THREAD

**Issue by ostojicmilica** [Codeception/Codeception#3877]
#### What are you trying to achieve?
I try to test if file exists in filesystem. I include Filesystem module for that. When I use **seeFileFound** method everything looks fine, but if I use **dontSeeFileFound** it always return success.

#### What do you get instead?

I get success as an output when I check for same file when I use **seeFileFound** and **dontSeeFileFound** methods, but first one is good second one is not.

### Details

* Codeception version: 
* PHP Version: 7.0
* Operating System: Ubuntu 16.04 LTS
* Installation type: Phar || Composer
* Framework: Laravel

```yml
# paste suite config here
```
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - \Helper\Functional
        - Asserts
        - Db
        - Cli
        - Filesystem

        - Laravel5:
            environment_file: .env.testing

**Comment by Naktibalda** [comment]
`doesn't work` means `doesn't search in path`.
