### ISSUE TITLE
Functional Test Mockery

### ISSUE THREAD

**Issue by pollend** [Codeception/Codeception#3878]
#### What are you trying to achieve?
I'm trying to use mockery to mock a call from a recapcha service in Laravel. Laravel seems to be using the the non mocked object for some reason. Unit test function correctly so I'm not sure what is wrong. 

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```php

    public  function  tryRegister(FunctionalTester $I){
        //arrange
        $I->disableEvents();
        $user = $I->factory()->instance(User::class);
        $new_password = str_random(10);

        // prevent validation error on captcha
        \NoCaptcha::shouldReceive('verifyResponse')
            ->once()
            ->andReturn(true);
        // provide hidden input for your 'required' validation
        \NoCaptcha::shouldReceive('display')
            ->zeroOrMoreTimes()
            ->andReturn('<input type="hidden" name="g-recaptcha-response" value="1" />');


        //act
        $I->amOnPage(route('auth.register'));
        $I->fillField("username",$user->username);
        $I->fillField("name",$user->name);
        $I->fillField("email",$user->email);
        $I->fillField("password",$new_password);
        $I->fillField("password_confirmation",$new_password);
        $I->click('Register');
        $I->seeCurrentRouteIs('auth.login');
        //$I->seeEventTriggered(UserRegistered::class);

        //assert
        $registered_user = \UserRepo::findByField('email',$user->email)->first();
        $I->assertFalse(\Auth::check());
        $I->assertTrue($user->name == $registered_user->name);
        $I->assertTrue($user->username == $registered_user->username);
        $I->assertTrue($user->email == $registered_user->email);
        $I->assertTrue(\Hash::check($new_password,$registered_user->password));
    }
```

* Codeception version: Codeception version 2.2.7
* PHP Version: Zend Engine v3.0.0
* Operating System:Ubuntu
* Installation type:  Composer
* List of installed packages (`anhskohbo/no-captcha                  2.2.0              No CAPTCHA reCAPTCHA For Laravel.
aws/aws-sdk-php                       3.20.11            AWS SDK for PHP - Use Amazon Web Services in your PHP project
barryvdh/laravel-debugbar             v2.3.0             PHP Debugbar integration for Laravel
barryvdh/laravel-ide-helper           v2.2.2             Laravel IDE Helper, generates correct PHPDocs for all Facade classes, to improve auto-completion.
barryvdh/reflection-docblock          v2.0.4             
behat/gherkin                         v4.4.5             Gherkin DSL parser for PHP 5.3
classpreloader/classpreloader         3.1.0              Helps class loading performance by generating a single PHP file containing all of the autoloaded files for a specific...
codeception/codeception               2.2.7              BDD-style testing framework
dnoegel/php-xdg-base-dir              0.1                implementation of xdg base directory specification for php
doctrine/annotations                  v1.3.0             Docblock Annotations Parser
doctrine/cache                        v1.6.1             Caching library offering an object-oriented API for many cache backends
doctrine/collections                  v1.3.0             Collections Abstraction library
doctrine/common                       v2.6.2             Common Library for Doctrine projects
doctrine/dbal                         v2.5.5             Database Abstraction Layer
doctrine/inflector                    v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
edvinaskrucas/notification            5.1.1              Package for Laravel for helping to manage flash / instant notifications / messages.
fabpot/goutte                         v3.2.0             A simple PHP Web Scraper
facebook/webdriver                    1.2.0              A PHP client for WebDriver
fzaninotto/faker                      v1.5.0             Faker is a PHP library that generates fake data for you.
gitonomy/gitlib                       v0.1.8             Library for accessing git
guzzle/guzzle                         v3.9.3             PHP HTTP client. This library is deprecated in favor of https://packagist.org/packages/guzzlehttp/guzzle
guzzlehttp/guzzle                     6.2.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1             Guzzle promises library
guzzlehttp/psr7                       1.3.1              PSR-7 message implementation
hamcrest/hamcrest-php                 v1.2.2             This is the PHP port of Hamcrest Matchers
ikkentim/wikiclone                    v0.4               Create GitHub wiki mirrors with ease.
intervention/image                    2.3.8              Image handling and manipulation library with support for Laravel integration
invisnik/laravel-steam-auth           dev-master cff5702 Laravel Steam Auth
jakub-onderka/php-console-color       0.1                
jakub-onderka/php-console-highlighter v0.3.2             
jenssegers/agent                      v2.4.0             Desktop/mobile user agent parser with support for Laravel, based on Mobiledetect
jeremeamia/SuperClosure               2.3.0              Serialize Closure objects, including their context and binding
knplabs/github-api                    1.7.1              GitHub API v3 client
laravel/framework                     v5.2.45            The Laravel Framework.
laravel/socialite                     v2.0.20            Laravel wrapper around OAuth 1 & OAuth 2 libraries.
league/commonmark                     0.13.0             Markdown parser for PHP based on the CommonMark spec
league/factory-muffin                 v3.0.1             The goal of this package is to enable the rapid creation of objects for the purpose of testing.
league/factory-muffin-faker           v1.0.0             The goal of this package is to wrap faker to make it super easy to use with factory muffin.
league/flysystem                      1.0.32             Filesystem abstraction: Many filesystems, one API.
league/flysystem-aws-s3-v3            1.0.13             Flysystem adapter for the AWS S3 SDK v3.x
league/fractal                        0.13.0             Handle the output of complex data structures ready for API output.
league/oauth1-client                  1.7.0              OAuth 1.0 Client Library
maknz/slack                           1.7.0              A simple PHP package for sending messages to Slack, with a focus on ease of use and elegant syntax. Includes Laravel ...
mastergalen/adsense-ads               v0.1.3             Display Adsense ads in your application.
maximebf/debugbar                     v1.13.0            Debug bar in the browser for php application
michelf/php-markdown                  1.7.0              PHP Markdown
mobiledetect/mobiledetectlib          2.8.24             Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-Agent string combined with sp...
mockery/mockery                       0.9.7              Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or any other...
monolog/monolog                       1.22.0             Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.1.0             CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
mtdowling/jmespath.php                2.4.0              Declaratively specify how to extract elements from a JSON document
nesbot/carbon                         1.21.0             A simple API extension for DateTime.
nikic/php-parser                      v2.1.1             A PHP parser written in PHP
paragonie/random_compat               v1.4.1             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common       1.0                Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.1              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information th...
phpdocumentor/type-resolver           0.2.1              
phpspec/prophecy                      v1.6.2             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             2.2.4              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.2              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     1.0.8              Utility class for timing
phpunit/php-token-stream              1.4.9              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       4.8.31             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          2.3.8              Mock Object library for PHPUnit
predis/predis                         v1.1.1             Flexible and feature-complete Redis client for PHP and HHVM
prettus/l5-repository                 2.6.6              Laravel 5 - Repositories to  the database layer
prettus/laravel-validation            1.1.4              Laravel Validation Service
psr/http-message                      1.0.1              Common interface for HTTP messages
psr/log                               1.0.2              Common interface for logging libraries
psy/psysh                             v0.7.2             An interactive shell for modern PHP.
sebastian/comparator                  1.2.2              Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.1              Diff implementation
sebastian/environment                 1.3.8              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    1.2.2              Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1              Snapshotting of global state
sebastian/recursion-context           1.0.2              Provides functionality to recursively process PHP variables
sebastian/version                     1.0.6              Library that helps with managing the version number of Git-hosted PHP projects
spatie/db-dumper                      1.5.1              Dump databases
spatie/laravel-backup                 3.10.2             A Laravel 5 package to backup your application
swiftmailer/swiftmailer               v5.4.4             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                   v3.2.1             Symfony BrowserKit Component
symfony/class-loader                  v3.2.1             Symfony ClassLoader Component
symfony/console                       v3.0.9             Symfony Console Component
symfony/css-selector                  v3.0.9             Symfony CssSelector Component
symfony/debug                         v3.0.9             Symfony Debug Component
symfony/dom-crawler                   v3.0.9             Symfony DomCrawler Component
symfony/event-dispatcher              v2.8.15            Symfony EventDispatcher Component
symfony/finder                        v3.0.9             Symfony Finder Component
symfony/http-foundation               v3.0.9             Symfony HttpFoundation Component
symfony/http-kernel                   v3.0.9             Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.3.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.3.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.3.0             Symfony utilities for portability of PHP codes
symfony/process                       v3.0.9             Symfony Process Component
symfony/routing                       v3.0.9             Symfony Routing Component
symfony/translation                   v3.0.9             Symfony Translation Component
symfony/var-dumper                    v3.0.9             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.2.1             Symfony Yaml Component
tightenco/mailthief                   v0.3.3             A fake Mailer for Laravel applications that takes the pain out of testing mail.
vlucas/phpdotenv                      v2.4.0             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.2.0              Assertions to validate method input/output with nice error messages.
weidner/goutte                        dev-master 929d474 Laravel 5 package for Gouette, a simple PHP Web Scraper
`)
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - Laravel5:
            environment_file: .env.testing
        - \Helper\FactoryHelper
        - \Helper\Functional
        - Asserts
```

**Comment by janhenkgerritsen** [comment]
The test methods like `shouldReceive` on the facades rely on the testing framework that is included with Laravel, they are not supported by Codeception.

What you can do with Codeception is add a mock object to the service container with methods like `haveInstance` and `haveBinding` from the Laravel5 module.

**Comment by pollend** [comment]
I've been trying this:
>         $mail = \Mockery::mock(Mailer::class);
>         $mail->shouldReceive("send")->with(\Mockery::any(),\Mockery::any(),\Mockery::any())->once();
>         $I->getApplication()->instance('mailer',function() use($mail){return $mail;});

I'm actually kind of stumped at this point.
