### ISSUE TITLE
Safari Driver Freezes Everytime (Safari v10)

### ISSUE THREAD

**Issue by mattmorgante** [Codeception/Codeception#3879]
Hello, 

I'm trying to run my tests in Safari v10, but the page freezes upon opening. There is no interaction at all, and this happens for all tests. I have tried a variety of different configurations and installation options, and have had no success. 

> output 
$ codecept run tests/acceptance/searchKmCept.php --env safari -vvv
Codeception PHP Testing Framework v2.2.7
Powered by PHPUnit 5.6.1 by Sebastian Bergmann and contributors.

Acceptance (safari) Tests (1) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: WebDriver, \Helper\Acceptance
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
searchKmCept: Select a double dropdown
Signature: searchKmCept
Test: tests/acceptance/searchKmCept.php
Scenario --
 I am on page "/"
  [GET] http://gaspedaal.nl/
 I click "Akkoord"
  Unable to retrieve Selenium logs : The command 'GET /session/32EA3106-08A3-4624-8B7F-BAA9EF76A75A/log/types' is not implemented.
  Command duration or timeout: 5 milliseconds
  Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
  System info: host: 'Matts-MBP.ws2.tem.nl', ip: '10.41.1.177', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_111'
  Driver info: org.openqa.selenium.safari.SafariDriver
  Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=11602.3.12.0.1, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, cssSelectorsEnabled=true}]
  Session ID: 32EA3106-08A3-4624-8B7F-BAA9EF76A75A
  Screenshot and page source were saved into '/Users/m.morgante/automotive/tests/_output/' dir
 ERROR

> Provide test source code if related

### Details

* Codeception version: 2.2 (dev-master) 
* PHP Version: 7.0.8
* Operating System: OSX El Capitan 10.11.6
* Safari version: 10.0.2 (has SafariWebDriver pre-installed). 
* Selenium Version: Selenium build info: version: '3.0.1', revision: '1969d75'
* Installation type: Composer
* List of installed packages (`composer show`)
$ composer show
behat/gherkin                         v4.4.5             Gherkin DSL parser for PHP 5.3
classpreloader/classpreloader         3.0.0              Helps class loading performance by generating a single PHP file containing all of the autoloaded files for a specific use case
codeception/codeception               2.2.7              BDD-style testing framework
codeception/robo-paracept             dev-master f07b157 Codeception Parallel Execution Tasks via Robo Task Runner
consolidation/annotated-command       2.2.2              Initialize Symfony Console commands from annotated command class methods.
consolidation/log                     1.0.3              Improved Psr-3 / Psr\Log logger based on Symfony Console components.
consolidation/output-formatters       3.1.5              Format text by applying transformations provided by plug-in formatters.
consolidation/robo                    1.0.5              Modern task runner
container-interop/container-interop   1.1.0              Promoting the interoperability of container objects (DIC, SL, etc.)
dnoegel/php-xdg-base-dir              0.1                implementation of xdg base directory specification for php
doctrine/inflector                    v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                    1.2.0              A PHP client for WebDriver
fzaninotto/faker                      v1.6.0             Faker is a PHP library that generates fake data for you.
guzzlehttp/guzzle                     6.2.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   1.3.0              Guzzle promises library
guzzlehttp/psr7                       1.3.1              PSR-7 message implementation
hamcrest/hamcrest-php                 v1.2.2             This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
jeremeamia/SuperClosure               2.2.0              Serialize Closure objects, including their context and binding
laravel/framework                     v5.3.18            The Laravel Framework.
laravel/homestead                     v4.0.2             A virtual machine for web artisans.
league/container                      2.2.0              A fast and intuitive dependency injection container.
league/flysystem                      1.0.28             Filesystem abstraction: Many filesystems, one API.
mockery/mockery                       0.9.5              Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or any other testing framework. Its...
monolog/monolog                       1.21.0             Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.1.0             CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
myclabs/deep-copy                     1.5.4              Create deep copies (clones) of your objects
nesbot/carbon                         1.21.0             A simple API extension for DateTime.
nikic/php-parser                      v2.1.1             A PHP parser written in PHP
paragonie/random_compat               v2.0.2             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common       1.0                Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.1              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a Doc...
phpdocumentor/type-resolver           0.2.1
phpspec/prophecy                      v1.6.1             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             4.0.1              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.1              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     1.0.8              Utility class for timing
phpunit/php-token-stream              1.4.8              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.6.1              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.4.0              Mock Object library for PHPUnit
phpunit/phpunit-selenium              3.0.2              Selenium Server integration for PHPUnit
psr/http-message                      1.0.1              Common interface for HTTP messages
psr/log                               1.0.2              Common interface for logging libraries
psy/psysh                             v0.7.2             An interactive shell for modern PHP.
ramsey/uuid                           3.5.1              Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
sebastian/code-unit-reverse-lookup    1.0.0              Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.0              Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.1              Diff implementation
sebastian/environment                 1.3.8              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    1.2.2              Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1              Snapshotting of global state
sebastian/object-enumerator           1.0.0              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           1.0.2              Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.0              Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer               v5.4.3             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                   v3.2.0             Symfony BrowserKit Component
symfony/console                       v3.1.8             Symfony Console Component
symfony/css-selector                  v3.1.5             Symfony CssSelector Component
symfony/debug                         v3.1.8             Symfony Debug Component
symfony/dom-crawler                   v3.1.5             Symfony DomCrawler Component
symfony/event-dispatcher              v3.2.1             Symfony EventDispatcher Component
symfony/filesystem                    v3.2.1             Symfony Filesystem Component
symfony/finder                        v3.1.8             Symfony Finder Component
symfony/http-foundation               v3.1.5             Symfony HttpFoundation Component
symfony/http-kernel                   v3.1.5             Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.3.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.2.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.2.0             Symfony utilities for portability of PHP codes
symfony/process                       v3.1.8             Symfony Process Component
symfony/routing                       v3.1.5             Symfony Routing Component
symfony/translation                   v3.1.5             Symfony Translation Component
symfony/var-dumper                    v3.1.5             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.1.5             Symfony Yaml Component
victorjonsson/markdowndocs            1.3.7              Command line tool for generating markdown-formatted class documentation
vlucas/phpdotenv                      v2.4.0             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.2.0              Assertions to validate method input/output with nice error messages.

* Suite configuration:
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
        - \Helper\Acceptance
    config:
      WebDriver:
          url: 'http://gaspedaal.nl'
          port: 4445
          browser: firefox
          javascriptEnabled: true
env:
  safari:
    modules:
      config:
        WebDriver:
          browser: 'safari'

[SafariFreezeExample.zip](https://github.com/Codeception/Codeception/files/675632/SafariFreezeExample.zip)

**Comment by edno** [comment]
Not a Codeception issue, already discussed in #3850

**Comment by mattmorgante** [comment]
Thanks for your response Greg. I have of course read that thread, but do you think you could point me in the direction of a possible solution instead of providing the same comment? I have been unable to get codeception and safari to work compatibly no matter the version, and I feel as though the configuration is not documented sufficiently

**Comment by edno** [comment]
@mattmorgante, this issue has nothing to do with Codeception configuration, so documentation will  not help. If you want to know more, and maybe find a way to get it sorted then have a look at the links on the other thread.

**Comment by mattmorgante** [comment]
I understand why you think it's not your problem, but the questions from various people on stackoverflow and the amount of time I have already wasted on this implies that codeception's integration with selenium-server could be clarified in the documentation.
