### ISSUE TITLE
`example` and `depends` tags can't get used at the same time on functional tests.

### ISSUE THREAD

**Issue by Faryshta** [Codeception/Codeception#3888]
#### What are you trying to achieve?

Use the `example` and `depends` tags for tests.

#### What do you get instead?

The test with the `depends` tag gets skipped.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
DependsCest: Example pass | true
Signature: frontend\tests\functional\DependsCest:examplePass
Test: tests/functional/DependsCest.php:examplePass
Scenario --
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=tecnocen_yasalte_test'
 PASSED 

DependsCest: Depends skip
Signature: frontend\tests\functional\DependsCest:dependsSkip
Test: tests/functional/DependsCest.php:dependsSkip
Scenario --
 SKIPPED: Dependent test for frontend\tests\functional\DependsCest:examplePass not found 
```
Notice how `examplePass` was run right before `dependsSkip`.

> Provide test source code if related

https://github.com/Faryshta/codecept-depends-bug/blob/master/frontend/tests/functional/DependsCest.php

### Details

* Codeception version: 2.2.7
* PHP Version: 7.1
* Operating System: ubuntu 14.04
* Installation type: Composer
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        - Filesystem
        - Yii2
```
I created this repo to check the issue https://github.com/Faryshta/codecept-depends-bug/blob/master/frontend/tests/functional/DependsCest.php follow the regular yii2 installation with composer using the `create-project` command, run `php init` on the root of the clone and then run

`./vendor/bin/codecept run -c frontend/ functional DependsCest -vvv`

**Comment by Faryshta** [comment]
also this only affects functional suite AFAIK api suite works perfectly with the exact same code.

**Comment by edno** [comment]
It might be fixed by the same fix as for #3862. Can you check it?

**Comment by Faryshta** [comment]
how can i check it? i tried `composer update` but doesn't change `codeception/base` at all.

**Comment by edno** [comment]
You need to update manually the file that has been fixed as per instruction given in #3862

**Comment by Faryshta** [comment]
@edno I checked it and it works but I also noticed another thing.

If a test have two `example` cases, one passing and the other doesn't. It will count as a full pass. I made a commit on my repo.

https://github.com/Faryshta/codecept-depends-bug/blob/master/frontend/tests/functional/DependsCest.php

**Comment by Faryshta** [comment]
maybe i should make a new issue for that and close this one?

**Comment by edno** [comment]
Just tried a similar example to yours, and I got the correct behaviour:
![Results](https://cloud.githubusercontent.com/assets/324670/21616750/1291cac6-d1e3-11e6-8132-7b46482a0ef0.png)
Here the code used:
````php
/**
      * @example {"key": true}
      * @example {"key": false}
      */
     public function partial(\FunctionalTester $I, Example $e)
     {
         $I->assertTrue($e['key']);
     }
```

You should ensure that `expect_that` behaves as expected.

**Comment by Faryshta** [comment]
Thanks @edno, This issue is solved, i will write again when I find a way to update codeception/base without manual edition
