### ISSUE TITLE
codeception.com’s server DNS address could not be found

### ISSUE THREAD

**Issue by dmitry-php** [Codeception/Codeception#3891]
Hi!
I'm trying to download codeception.phar (and reach the site)

Instead I get codeception.com’s server DNS address could not be found

**Comment by villeneuve-michael** [comment]
Yeah it's been down since at least 12 hours, don't know what's going on. Probably in vacation!

**Comment by tiger-seo** [comment]
yeah, @DavertMik  is on a vacation till 8th of January :(

**Comment by nvp2211** [comment]
I checked the whois look up, the domain was expired on December 27th, 2016. It was renewed on Jan 2nd, 2017. It means the domain is renewed after it expired. I am worry about the case that someone else took the domain...

**Comment by delatbabel** [comment]
# whois codeception.com
Updated Date: 2016-01-04T02:55:22Z
Registrar Registration Expiration Date: 2016-12-27T01:08:50Z
... etc
Registrant Name: Mihail Bodnarchuk
... etc

So it still appears to be alive and registered to the correct person, but probably suspended for payment expiry.  Hopefully it can be sorted out soon.

**Comment by laszlof** [comment]
The domain is in clientHold status, which likely means the bill hasnt been paid for its renewal. Depending on the registrar, they'll typically hold a domain for 30-60 days before allowing it to be registered by someone else. The owner shouldnt be at any risk of losing it as long as they promptly renew it upon returning from vacation.

**Comment by rewbrennon** [comment]
Still down, does anyone have Mihail contacts?

**Comment by nvp2211** [comment]
@rewbrennon I searched on Google Domains and saw admin contact information there, but don't know that is his or not. I'll try to contact him with the email provided.

**Comment by sergeyklay** [comment]
Fixed. Thanks

**Comment by DanielRuf** [comment]
The domain is not working again.
