### ISSUE TITLE
Yii2 Funtional Test App Advanced Failure.

### ISSUE THREAD

**Issue by cjtterabyte** [Codeception/Codeception#3897]
Hi, i have yii2 advadnced template, run test failure:

Test Config Steps:

1.- Create Database yii2advanced_test.
2.- Config Mysql Conection [common/config/test.php].
3.- Execute yii_test migrate.
4.- composer exec codecept build
5.- composer exec codecept run -- -c frontend --debug

Output Debug:
```
Codeception PHP Testing Framework v2.2.7
Powered by PHPUnit 5.7.5 by Sebastian Bergmann and contributors.
[1mFrontend\tests.functional Tests (12) [22m--------------------------------------------------------------------------------------------------------------------------------------------
Modules: [32mFilesystem, Yii2, Asserts[39m
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[35;1mAboutCest:[39;22m Check about
Signature: [32mfrontend\tests\functional\AboutCest:checkAbout[39m
Test: [32mtests\functional\AboutCest.php:checkAbout[39m
[33mScenario --[39m
[36m  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=yii2advanced_test'[39m
[1m I [22mam on route "site/about"
[36m  [Request Headers] [][39m
[31;1m ERROR [39;22m

[35;1mContactCest:[39;22m Check contact
Signature: [32mfrontend\tests\functional\ContactCest:checkContact[39m
Test: [32mtests\functional\ContactCest.php:checkContact[39m
[33mScenario --[39m
[36m  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=yii2advanced_test'[39m
[1m I [22mam on page ["site\/contact"]
[36m  [Request Headers] [][39m
[36m  [yii\base\ErrorException:256] unserialize('O:23:"yii\\base\\ErrorException":8:{s:10:"' . "\0" . '*' . "\0" . 'message";s:9368:"Exception (Invalid Configuration) \'yii\\base\\InvalidConfigException\' with message \'The directory does not exist: ./assets\' 
  
  in C:\\app_server_webs\\webs\\yii2-chktime-core\\vendor\\yiisoft\\yii2\\web\\AssetManager.php:213
```
### Details

* Codeception version: "codeception/base": "^2.2.3", "codeception/verify": "~0.3.1",
* PHP Version: 5.6.6. Apache: 2.4.
* Operating System: Windows 10 Home 64 Bits.
* Installation type: Composer
* List of installed packages (`composer show`):
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "dev-master",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1",
        "cjtterabytesoft/yii2-adminlte-advanced": "dev-master"
    },
* Suite configuration:
codeception.yml:
#global codeception file to run tests from all apps
include:
    - common
    - frontend
    - backend
paths:
    log: console/runtime/logs
settings:
    colors: true
```

**Comment by samdark** [comment]
Create assets directory under webroot and make sure web server has permissions to write to it. It's in the error message btw.
