### ISSUE TITLE
HTML autocomplete breaks acceptance login

### ISSUE THREAD

**Issue by NerdsvilleCEO** [Codeception/Codeception#3909]
#### What are you trying to achieve?
Login using an email field which has autocomplete

#### What do you get instead?
Error saying that email field is required unless I remove the autocomplete attribute

**Comment by Naktibalda** [comment]
It doesn't look like an issue of Codeception to me.

**Comment by NerdsvilleCEO** [comment]
It is possible this is a ghostjs issue then :) thanks!
