### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by rogoit** [Codeception/Codeception#3915]
I want to test a slider for a price selection on a ecommerce project. Sinple i want to push left mouse button down and want to move 30px to left. But i do not know how to do this in javascript. I think there could be a second way with executejs.  This information is for the background.

So i try to do it with drag and drop. But when i run the test i get

` [Facebook\WebDriver\Exception\UnknownCommandException] POST /session/4f9f5c73-1d3a-5740-8ce4-ef6fc5cc445b/moveto did not match a known command
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'`

It is codeception 2.2.6 and selenium server 3.0.1

Any ideas how to fix the drag and drop and how i can test a price slider?

**Comment by DavertMik** [comment]
Could you provide some sort of HTML or JS code? 
There are different drag and drop implementations with different support inside a browser. There is nothing like general advice for this case.

**Comment by edno** [comment]
It's surprising that you get such error. Are you using [WebDriver actions](https://github.com/facebook/php-webdriver/blob/community/lib/Interactions/WebDriverActions.php)?
```php
$this->getModule('WebDriver')->webDriver->actions()->dragAndDropBy($element, 0, 30)->perform();
```

**Comment by Naktibalda** [comment]
@rogoit You used a driver which had no support for Actions API (it was Firefox, right?).

It appears that Action API is finally supported by Marionette, please upgrade Selenium and geckodriver and try again.
https://github.com/SeleniumHQ/selenium/issues/2285#issuecomment-287584656

**Comment by DanielJaron** [comment]
@edno I haven't really figured out, how can I use WebDriver actions.
Could you give a hint?

**Comment by edno** [comment]
@DanielJaron - WebDriver action is an API used for creating complex interaction, eg drag and drop.
For usage, just call the accessor `action()` from your WebDriver instance and chain the action method/s and conclude with the method `perform()` for triggering the action/s.

I recommend you to have a look at the code of the functional tests from [WebDriverActionsTest.php](https://github.com/facebook/php-webdriver/blob/community/tests/functional/WebDriverActionsTest.php) for getting some examples.

> [WebDriver API documentation](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html)

> [PHP implementation](https://github.com/facebook/php-webdriver/blob/community/lib/Interactions/WebDriverActions.php)
