### ISSUE TITLE
Documentation for groups doesn't mention that directories can be specified as well as individual php files

### ISSUE THREAD

**Issue by Suseika** [Codeception/Codeception#3919]
https://github.com/Codeception/Codeception/blob/master/docs/07-AdvancedUsage.md#group-files

It is not clear from the documentation that I can create a group by specifying directories as well as test files, like this:

```yml
groups:
  slow: [ tests/unit/externalApi/requests ]
```

If I didn't try that, I'd never know that's possible.

I suggest mentioning this feature in the documentation.

**Comment by DavertMik** [comment]
Thanks, that should be done.
