### ISSUE TITLE
yii2 codeception ltrim in getFixture

### ISSUE THREAD

**Issue by kvelaro** [Codeception/Codeception#3923]
Try to run acceptance test with fixtures.
In config enabled Db module and pointed path to dump, filled username and password.
In backend/tests/acceptance directory have TasksCest.php file which declared as follow:

```php
<?php
use tests\fixtures\TasksFixture;
class TaskCest {
    use yii\test\FixtureTrait;
    public function fixtures() {
      return ['tasks' => TasksFixture::className()];
    }.....
```

in fixtures directory I have TasksFixture.php class which declared as follow:

```php
<?php
namespace tests\fixtures;

use yii\test\ActiveFixture;

class TasksFixture extends ActiveFixture {
    public $tableName = 'task';
    public $dataFile = '@tests/fixtures/data/tasks.php';
}
```

I have tasks.php file which return array. 
When I run codecept it stupidly returns me following error
1) TaskCest: Get fixture

```
 Test  tests/acceptance/TaskCest.php:getFixture
                                                                                    
  [yii\base\ErrorException] ltrim() expects parameter 1 to be string, object given  

-vvv
[yii\base\ErrorException] ltrim() expects parameter 1 to be string, object given  

/home/nginx/www/planning-back/vendor/codeception/codeception/src/Codeception/Lib/Di.php:123
/home/nginx/www/planning-back/vendor/codeception/codeception/src/Codeception/Lib/Di.php:123
/home/nginx/www/planning-back/vendor/codeception/codeception/src/Codeception/Test/Cest.php:136
/home/nginx/www/planning-back/vendor/codeception/codeception/src/Codeception/Test/Cest.php:148
/home/nginx/www/planning-back/vendor/codeception/codeception/src/Codeception/Test/Cest.php:82
/home/nginx/www/planning-back/vendor/codeception/codeception/src/Codeception/Test/Test.php:90
/home/nginx/www/planning-back/vendor/phpunit/phpunit/src/Framework/TestSuite.php:728
/home/nginx/www/planning-back/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:98
/home/nginx/www/planning-back/vendor/codeception/codeception/src/Codeception/SuiteManager.php:154
/home/velaro/.config/composer/vendor/codeception/codeception/src/Codeception/Codecept.php:183
/home/velaro/.config/composer/vendor/codeception/codeception/src/Codeception/Codecept.php:152
/home/velaro/.config/composer/vendor/codeception/codeception/src/Codeception/Command/Run.php:282
/home/velaro/.config/composer/vendor/symfony/console/Command/Command.php:255
/home/velaro/.config/composer/vendor/symfony/console/Application.php:829
/home/velaro/.config/composer/vendor/symfony/console/Application.php:191
/home/velaro/.config/composer/vendor/symfony/console/Application.php:122
/home/velaro/.config/composer/vendor/codeception/codeception/src/Codeception/Application.php:103
/home/velaro/.config/composer/vendor/codeception/codeception/codecept:34
```

What can be wrong? What I doing wrong?

**Comment by samdark** [comment]
Are you going to finish description of the issue?

**Comment by kamilmiem** [comment]
I guess I have explained. Something missing?

**Comment by samdark** [comment]
Yes. Code, for example...

**Comment by kamilmiem** [comment]
yii2 advanced template

.
codeception.yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'xxx'
            user: 'xxx'
            password: 'xxx'
            dump: tests/_data/xxx.sql
            populate: false #for now
            cleanup: false #for now

tests/
acceptance.suite.yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - REST:
            depends: PhpBrowser
            url: http://xxx/
        - Db
        - Asserts
        - \Helper\Auth
        - \Helper\Acceptance
        - Yii2:
            entryScript: index-test.php
            part: fixtures
    config:
        \Helper\Auth:
            domain: 'xxx'
            login: 'xxx'
            pass: 'xxx'
        Yii2:
          configFile: 'config/main-test.php'

tests/_bootstap.php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

require(__DIR__ . '/../../vendor/autoload.php');
require(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');

Yii::setAlias('@tests', dirname(__DIR__) . '/tests');
Yii::setAlias('@common', dirname(dirname(__DIR__)) . '/common');

tests/acceptance/_bootstrap.php
$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/../../../common/config/main.php'),
    require(__DIR__ . '/../../../common/config/main-local.php'),
    require(__DIR__ . '/../../config/main.php'),
    require(__DIR__ . '/../../config/main-local.php'),
    require(__DIR__ . '/../../config/main-test.php')
);
$application = new yii\web\Application($config);

tests/acceptance/TaskCest.php
<?php
use tests\fixtures\TasksFixture;
class TaskCest {
    use yii\test\FixtureTrait;
    public function fixtures() {
        return [
            'tasks' => TasksFixture::className()
        ];
    }
}

tests/fixtures/TaskFixture.php
<?php
namespace tests\fixtures;

use yii\test\ActiveFixture;

class TasksFixture extends ActiveFixture {
    public $tableName = 'task';
    public $dataFile = '@tests/fixtures/data/tasks.php';
}

tests/fixtures/data/tasks.php
<?php
//$faker = Faker\Factory::create();
return [
    'task0' => [
        'title' => 'task0',
        'description' => 'task0',
        'priority' => 'middle',
        'status' => 'assigned',
        'updated_by' => null,
        'updated_at' => null,
        'created_at' => null,
        'assignee' => 'velaro',
        'extra_type' => 'common',
        'parent_id' => null
    ]
];

**Comment by comm1x** [comment]
Up.
Also http://stackoverflow.com/questions/41610365/codeception-acceptance-test-with-fixtures-in-yii2

**Comment by comm1x** [comment]
Ситуация немного глумная, опишу на русском.

Codeception при запуске Cest-тестов берет все public-методы класса и вызывает их, передавая первым аргументом `\FunctionalTester $I`.
Когда мы пытаемся подгружать фикстуры через `FixtureTrait`, мы подключаем этот трейт к Cest-классу, который также содержит public-методы. И как вы уже поняли, codeception распознает эти public-методы трейта как тесты, и пытается вызвать. И почти все методы вызываются без ошибок (fixtures globalFixtures loadFixtures unloadFixtures getFixtures), за исключением одного:

```
    public function getFixture($name)
    {
        if ($this->_fixtures === null) {
            $this->_fixtures = $this->createFixtures(array_merge($this->globalFixtures(), $this->fixtures()));
        }
        $name = ltrim($name, '\\');

        return isset($this->_fixtures[$name]) ? $this->_fixtures[$name] : null;
    }
```

Вот здесь-то в `$name` и попадает `\FunctionalTester $I` и генерируется ошибка о том, что пришел object, вместо string.
-----------------------------------
Поверхностное решение, которое первым приходит в голову - создавать в отдельном классе свой fixture-loader, который бы использовал FixtureTrait, и далее его подключать в Cest-классы избегая public-методов.

Поверхностное решение в рамках фреймворка - хз.

**Comment by comm1x** [comment]
```
class FixtureLoader
{
    use \yii\test\FixtureTrait;
}

abstract class ApiCest
{
    /**
     * @var FixtureLoader
     */
    private $fixtureLoader;

    public function __construct()
    {
        $this->fixtureLoader = new FixtureLoader();
    }

    public function fixtures()
    {
        return [];
    }

    public function _before(\FunctionalTester $I)
    {
        $this->fixtureLoader->loadFixtures();
    }

    public function _after(\FunctionalTester $I)
    {
        $this->fixtureLoader->unloadFixtures();
    }
}
```

**Comment by Naktibalda** [comment]
The answer on StackOverflow was to not use traits in tests class, because all public methods of Cest class are executed as tests.
