### ISSUE TITLE
[Symfony\Component\Debug\Exception\FatalThrowableError]     Call to undefined function env() 

### ISSUE THREAD

**Issue by AjithLalps** [Codeception/Codeception#3928]
i want to run codeception on my project using yii2 advanced template

while using this command composer exec codecept run, showing [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to undefined function env() .

-oputput

Codeception PHP Testing Framework v2.2.7
Powered by PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to undefined function env()                         
                                                           

run [-o|--override OVERRIDE] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]

### Details

* Codeception version: 2.0
* PHP Version:5.6
* Operating System:linux mint cenemmon 18
* Installation type: Composer
* List of installed packages 

  "require-dev": {
    "yiisoft/yii2-debug": "^2.0.0",
    "yiisoft/yii2-gii": "^2.0.0",
    "yiisoft/yii2-codeception": "^2.0.0",
    "yiisoft/yii2-faker": "^2.0.0",
    "codeception/codeception": "^2.0",
    "codeception/specify": "^0.4.3",
    "codeception/verify": "^0.3.0"
  },
  "suggest": {
    "trntv/yii2-debug-xhprof": "dev-master@dev"
  },
  "config": {
    "process-timeout": 1800
  },
  "extra": {
    "asset-installer-paths": {
      "npm-asset-library": "vendor/npm",
      "bower-asset-library": "vendor/bower"
    }
  },
  "repositories": {
    "packagist": {
      "url": "https://packagist.org",
      "type": "composer"
    }
  }
}

**Comment by Naktibalda** [comment]
Please run Codeception with `-vvv` flag and provide the stacktrace.
