### ISSUE TITLE
How to specify the php version when starting the command

### ISSUE THREAD

**Issue by xiaoxing598** [Codeception/Codeception#3933]
I have multiple versions of php installed in the same system, I would like to execute the command manually or a configuration to specify, select a version I should use.

I tried the following approach, but without success:
```
/usr/local/php7/bin/php vendor/bin/codecept -v
```

**Comment by Naktibalda** [comment]
It is a question for maintainers or users of your operating system/distribution, not Codeception.

I run Codeception with different versions of PHP this way:
`php-5.6 codecept`, `php-7.0 codecept`, `hhvm codecept`

**Comment by ashnazg** [comment]
`/usr/local/php7/bin/php vendor/codeception/codeception/codecept`

The `codecept` file in `vendor/bin` is a shell script rather than PHP script.  Have PHP call the one in `vendor/codeception/codeception`, as it _is_ a PHP script.

I had to learn to do this for phpunit (using PHP to run the specific PHP script that underlies the shell script) back when I was first learning to step-debug in Eclipse.

**Comment by Naktibalda** [comment]
What OS do you use?
`vendor/bin/codecept` is a symlink to `vendor/codeception/codeception/codecept` on Linux.
```
ll vendor/bin/codecept
lrwxrwxrwx 1 owner group 35 Dec  9 16:07 vendor/bin/codecept -> ../codeception/codeception/codecept
```

**Comment by ashnazg** [comment]
Ah, didn't realize composer did it that way on *nix.  I'm stuck on Windows, hence that `vendor/bin/codecept` being a BAT file.

On Linux, I'm able to successfully use both commands (php calling codecept in each of those locations).

**Comment by xiaoxing598** [comment]
I got the problem to get this result:
```
[xxx@xxx ad]$ /usr/local/php7/bin/php vendor/bin/codecept -v
dir=$(d=${0%[/\\]*}; cd "$d"; cd "../codeception/base" && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
	# Cygwin paths start with /cygdrive/ which will break windows PHP,
	# so we need to translate the dir path to windows format. However
	# we could be using cygwin PHP which does not require this, so we
	# test if the path to PHP starts with /cygdrive/ rather than /usr/bin
	if [[ $(which php) == /cygdrive/* ]]; then
		dir=$(cygpath -m "$dir");
	fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/codecept" "$@"
[xxx@xxx ad]$
```
