### ISSUE TITLE
[Feature request] Executes the given callback within the context of a node

### ISSUE THREAD

**Issue by tortuetorche** [Codeception/Codeception#3936]
Hi folks,

#### What are you trying to achieve?

> Executes the given callback within the context of a node/element.
> -- <cite>Capybara doc</cite>

> Sometimes you may wish to perform several operations while scoping all of the operations within a given selector. For example, you may wish to assert that some text exists only within a table and then click a button within that table.
> -- <cite>Laravel Dusk doc</cite>

Here a sample:
```php
$I->amWithin('.table', function ($table) {
    $table->see('Hello World');
    $table->click('Delete');
});
```
See: 
* http://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FSession%3Awithin
* https://laravel.com/docs/5.4/dusk#scoping-selectors

#### What do you get instead?

I didn't find any Codeception actions to achieve this feature.

Cheers,
Tortue Torche

**Comment by DavertMik** [comment]
Yep, we [have it in CodeceptJS](http://codecept.io/basics/#within) btw :)

This feature can be implemented but requires a deep look into the WebDriver module. Unlike Dusk we have lots of methods and many lines of code and everything needs to be taken into account when doing a feature like narrowing the search scope. 

Let me think on it

**Comment by DavertMik** [comment]
To be honest it is not hard to implement that technically, but there are problems in displaying the results for such execution. You'd expect the output to look like:

```
within #form
  I click 'xx'
  I fill field 'yyy'
  I see 'zzz'
```

however, that doesn't fit into lots of cases: printing HTML report, using it inside Gherkin scenarios, using it inside pageobjects, etc. This feature can be easily implemented if this would be considered as one step:

```
I execute in context '#form', function
```

but I don't know how valuable would be that output information.
So the question is to implement it partly (in a bad way) or redesign the output to support this one feature.

**Comment by tortuetorche** [comment]
Hi Michael,

Thank you for your response, I understand your concern about the output information issue.
Maybe, as a first try, the `$I->amWithin()`/`within()` feature could be an extension or an hidden API method like [`_findElements()`](http://codeception.com/docs/modules/WebDriver#_findElements) method?

Have a good day,
Tortue Torche

**Comment by DavertMik** [comment]
hi @tortuetorche , hey team, I have some ideas with the cleanest implementation.

```php
$I->performOn('#xxxx', ['see' => 'xxx', 'seeElement' => 'zzzz']);
$I->performOn('xxxx', ElementActions::build()->see('xxxx')->click('zzzz'));
$I->performOn('xxxx', (new ElementActions())->click('zzzz'));

$I->performOn('xxx', function(ElementActions $I) {
  $I->see('xxxx');
  $I->click('zzzz');
}); 
// in all this cases second parameter will be array of parameters
```

This produced following output:

```
I perfrom on 'xxx', {see: 'xxx', seeElement: 'zzzz'}
```

This feature won't introduce new changes in reporters, steps, into the Codeception core. 
This why I like it for simplicity. For WebDriver it is also possible to set a timeout (wait for element xxx to appear on page before running additional actions).

Right now I think this feature can be implemented for WebDriver. 
This will improve performance for calls like 

```php
$I->waitForElement('#xxxx');
$I->click('#xxxx');
```

Not sure if it should be extended to PhpBrowser/Frameworks.
Also it is questionable which actions should be allowed inside an element.

**Comment by Naktibalda** [comment]
The callback way looks the most natural to me.

**Comment by sergeyklay** [comment]
Agree with @Naktibalda

**Comment by DavertMik** [comment]
> The callback way looks the most natural to me.

The problem with callback that you can't get a function body inside an output, so it probably won't be as nice. But if a scenario inside a function is long then it probably shouldn't even be included in output.

The array syntax would be good for cases described above:

```php
$I->performOn('#modal', ['see' => 'Are you sure you want to delete this?']);
```

which will wait for modal to appear and then check the text inside it.
