### ISSUE TITLE
selectOption doesn't work - WebDriver.

### ISSUE THREAD

**Issue by Xeyos88** [Codeception/Codeception#3938]
I can not select an option of a select statement.
Use WebDriver.

The output of the test tells me that the selection is carried out but then it does not.

```html
<select name="type" required="required" id="type" class="form-control">
    <option value="0"></option>
    <option value="1">Operation</option>
    <option value="2">Test</option>
    <option value="3">Simulation</option>
</select>
```

```php
$I->selectOption("form select[name=type]", 'Test');
$I->seeOptionIsSelected("form select[name=type]", 'Test');
```
i try too:
```php
$option = $I->grabTextFrom('form select[name=type] option:nth-child(3)');
$I->selectOption("form select[name=type]", $option);
```
Output:
>Couldn't see option is selected "form select[name=type]","Test"
>13. I see option is selected "form select[name=type]","Test" \\in RED
>12. I select option "form select[name=type]","Test"

I try by value too, but the result is the same. I the screenshot of output(i use Selenium) the select is ever empty.

**Comment by Naktibalda** [comment]
What browser do you use?

**Comment by Xeyos88** [comment]
Firefox in a VM Centos 7.

**Comment by DavertMik** [comment]
Do you use some select enhancements like jquery select or bootstrap select?

**Comment by Xeyos88** [comment]
Bootstrap select. Now i solved the test with click on select element and pressKey function, but selectOption is more simple and correct.

**Comment by edno** [comment]
For Bootstrap you can see the solution proposed by @DavertMik: http://phptest.club/t/webdriver-selectoption-in-bootstrap-select/1345

**Comment by DavertMik** [comment]
@Xeyos88 

`selectOption` can't be used with JS-customized selects, so whenever you use some enhancement you need to include some hook, to test it. See link above

**Comment by mbrodala** [comment]
The link above is dead, here's a working one: https://flowfx.de/blog/testing-bootstrap-select-dropdown-field-with-selenium-python/

Relevant quote:

> How it does works
> I don't remember where I got the idea to my solution, but it's simple and obvious. It selects the dropdown menu, and then types in the text that I want to click. Then hits enter and voilá, the desired option is selected.
> ```python
> from selenium.webdriver.common.keys import Keys
> dropdown = browser.find_element_by_id('surface')
> dropdown.send_keys('Hard')
> dropdown.send_keys(Keys.ENTER)
> ```

Translated to CodeCeption:

```php
$I->executeInSelenium(function (RemoteWebDriver $webDriver): void  {
    $dropdown = $webDriver->findElement(WebDriverBy::id('surface'));
    $dropdown->sendKeys('Hard');
    $dropdown->sendKeys(WebDriverKeys::RETURN_KEY); // Notice that ::ENTER_KEY does not work
});
```

And this does indeed seem to work, the select option stays selected.
