### ISSUE TITLE
Suggested way to share step/page objects between multiple projects

### ISSUE THREAD

**Issue by B4rb4ross4** [Codeception/Codeception#3943]
We have a base application that is in every installation extended by a customization.
In the customization most things from the base Application can be extended or changed.

I want to test the application with every customization with codeception. So I would create a basic Set of step/page objects. And this set I would extend in the test case of a customized application.

Is there a suggested way, how i can share this basic Test logic between the projects.
Should I just create an own composer package and share that, or is there an other suggested codeception way?

PS: I use the latest codeception version.

**Comment by Naktibalda** [comment]
Yes, reusing code via composer is the best way.
