### ISSUE TITLE
codeception db module return unique violation in primary key

### ISSUE THREAD

**Issue by kamilmiem** [Codeception/Codeception#3947]
#### What are you trying to achieve?

Trying to test system with acceptance tests, with db module turned on and populate and cleanup params active

#### What do you get instead?

I get unique violation, when I try to insert new record from my method

# paste output here

```
[error][yii\db\IntegrityException] PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "event_pkey"
DETAIL:  Key (id)=(1) already exists. in
```

```php
codecept run acceptance EventsCest:add
```
### Details
Yii2
Postgres 9.4

```yml
dump:....
populate: true
cleanup: true
```
In dump I have structure and data [create table.... create sequence, insert into...]

At each test run, codeception db module cleans up tables, then populates [fills] from dump. 
Then it runs cest class with specified method. In that method I just send query to create new Event without id specified, but it returns above specified errror.

As I guess, its seems that db module does not see newly created records from dump. Maybe its connection problem or something else?

**Comment by Naktibalda** [comment]
Exception is thrown by Yii framework, so it isn't an issue of Db module.

**Comment by kamilmiem** [comment]
Problem seems to have gone :)
I modified dump, erased explicitly set ids. I don't fill id in INSERT INTO statement.

Question is: What's logical difference between them? Cause I don't see it.
