### ISSUE TITLE
Laravel Seeds

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#3948]
I received a report that seeds in Laravel5 module behave in a strange way. They are always created before each test but never reverted. And yes:

https://github.com/codeception/codeception/blob/2.2/src/Codeception/Module/Laravel5.php#L173

Here the options I see: 
* run seeds at the beginning of a test, reset them in the end of a test
* run seeds inside a transaction at the beginning of a test, transaction will revert them
* run seeds before suite and reuse them across tests...

Or maybe I don't understand something about Laravel seeders...

**Comment by janhenkgerritsen** [comment]
The default value for the config variable in the line you reference is `false`, so the database seed command will only run when the user explicitly sets this config variable to `true`.

I'll try to look at this issue this week, but it is highly likely that the report you received is wrong. From the top of my head I don't believe there is any other code related to the database seeds in the Laravel5 module than the line you referenced.

If the person that reported the issue to you is sure there is a problem with the Laravel5 module I'd like to have some more information.

**Comment by DavertMik** [comment]
Yes, it's about that seeder option in config only. It's not a critical bug but I don't understand how the seeds are expected to be used in this implementation. As I said, it has no meaning, running seeds before each test without reverting them

**Comment by janhenkgerritsen** [comment]
This issue should be fixed by the referenced commit.
