### ISSUE TITLE
How should I test results of asynchronous processes?

### ISSUE THREAD

**Issue by Revisor** [Codeception/Codeception#3966]
#### What are you trying to achieve?
- An action on my web site (eg. new user registration) adds a job to an asynchronous queue.
- The job is picked up by another process a small while later and a registration email is sent
- I want to check that the email was sent and that it contains a certain text (eg. the user's name) (via Mailcatcher)
- The delay between adding the job and processing it/sending the email is unpredictable and variable
- I use `PhpBrowser` for tests

The above test works if I force the job to be processed synchronously (immediately), but I'd like to test the web site under conditions as similar to production as possible.

How would you solve it?

1. A very naive solution:
X = Maximum accepted delay
- Wait for X seconds, then check the email

This is what `Codeception\Module\WebDriver::wait()` does and it's sweet and simple.

2. A naive solution
- Ask in short intervals, whether the email was sent
- Until X seconds run out
- Is something like that even viable in Codeception? Asking for an assertion repeatedly but not failing the test if the assertion is not true (yet)

3. Probing in the dark solution
- Register all asynchronous assertions as promises instead of testing them on the spot
- At the end of the test wait until they are all resolved or until time runs out

4. ?

Thanks for your ideas.

**Comment by Naktibalda** [comment]
3. ends in the same way as 2.

Use a loop in your helper method, don't call phpunit assertions until it is over.

**Comment by Revisor** [comment]
I went for solution 2 and implemented it like this:

AcceptanceTester:
``` php
/**
 * Try the assertion until it succeeds or the time runs out
 *
 * This method is meant to test asynchronous actions which the tests must
 * wait for.
 *
 * @param callable $callable  The assertion
 * @param array    $arguments Assertion arguments
 * @param float    $timeout   How long we should wait for the result
 *
 * @throws
 */
public function tryUntil(callable $callable, $arguments = array(), $timeout = 10.0)
{
    $until = microtime(true) + $timeout;
    do {
        $exception = null;
        try {
            call_user_func_array($callable, $arguments);
            return;
        } catch (\Exception $exception) {
            // We work with the exception further below
        }
        
        // Repeat 20 times per second
        usleep(50000);
        
    } while (microtime(true) < $until);
    
    if ( ! is_null($exception)) {
        throw $exception;
    }
}
```

The usage is quite readable:

``` php
$I->tryUntil([$I, 'seeInLastEmailTo'], [$recipientEmail, $expectedString]);
```

What do you think?

One disadvantage is that this generates a lot of steps in the tests, so for example if this assertion fails, the last shown steps are not helpful, it's just this one repeating a lot of times.

**Comment by Revisor** [comment]
The above solution works for us. I'm closing this issue.
