### ISSUE TITLE
Drop support of old php versions

### ISSUE THREAD

**Issue by gimler** [Codeception/Codeception#3972]
Drop support for old php versions 5.4 and 5.5. Both versions are not supported any more see http://php.net/supported-versions.php.

**Comment by Naktibalda** [comment]
Scheduled for 3.0

**Comment by gimler** [comment]
Please add a Milestone

**Comment by DavertMik** [comment]
I think 5.6 can be dropped by that time as well. All other frameworks/tools follow the same path so we probably can do that to

**Comment by Naktibalda** [comment]
What time? Do you want to drop support for PHP 5.6 this year?
I can only agree with that if we make 2.2 or 2.3 an LTS version.

**Comment by DavertMik** [comment]
Technically there is no reason dropping 5.6 at this moment. I was just about following the PHPUnit / Symfony. If you think 5.6 is important to keep support, let's do that. Much better than maintaining 2 version branches :confused:

**Comment by Naktibalda** [comment]
PHPUnit and Symfony have LTS versions, PHPUnit 4.8 which runs on PHP 5.3 is still supported:
https://github.com/sebastianbergmann/phpunit/blob/4.8/ChangeLog-4.8.md

**Comment by gimler** [comment]
phpunit 6 drop support for php5.6 see https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0

**Comment by samdark** [comment]
If there's no technical reason then why should older versions support be dropped? If the goal is to encourage PHP 7 usage, just advertise it like "Requires PHP 5.3+, works best with PHP 7". That's it.

**Comment by DavertMik** [comment]
> If there's no technical reason then why should older versions support be dropped?

Looks like we got one:

> phpunit 6 drop support for php5.6

And yes, we can't support both PHPUnits in core as in 6.0 they changed all internal class names, and probably some other architecture changes as well.

Let's look into other option. If we split modules out of core, we can make them compatible with Codeception 2.2/3.0 and support PHP >= 5.4. However, the Codeception core 3.0 will require PHP7 only.

There are no so much fixes into the core, so I think this should work fine.

**Comment by samdark** [comment]
Symfony is going PHP 7 only in November this year. Laravel is, as always, faster in adopting new things. It's jumping PHP 7 wagon and dropping old versions even earlier.

**Comment by samdark** [comment]
Yii 2.0 isn't going to require PHP 7 but it works perfect with it so should not be the problem if updated. Yii Old 1.1 is constantly patched to be PHP 7 compatible as well.

**Comment by vaneatona** [comment]
I would like to weigh in and look to keep at much compatibility with php 5.6 as possible. I just got my team to adopt this testing framework.

**Comment by orlangur** [comment]
> @Naktibalda commented on Feb 1
> PHPUnit 4.8 which runs on PHP 5.3 is still supported

LOL :) You wrote it two days before the "PHPUnit 4.8 has reached End of Life as of February, 3 2017 and will no longer receive bug fixes".

I don't think any PHP version support shall be dropped until there is a good reason to do so.

Does PHP 5.4, 5.5 support cause some troubles, like not allowing to move forward/increase maintenance efforts?

**Comment by Naktibalda** [comment]
My point was that PHPUnit and Symfony maintain multiple branches, so they can drop support more easily than Codeception which maintains only one.
Support for PHP 5.4 and 5.5 requires to keep compatibility with PHPUnit 4 and Guzzle 5.

**Comment by orlangur** [comment]
@Naktibalda, ok, I was not aware of PHP < 5.6 support dropped in [PHPUnit 5.4](https://github.com/sebastianbergmann/phpunit/blob/5.4.0/composer.json#L23) already :)

**Comment by Naktibalda** [comment]
Not a bug.
