### ISSUE TITLE
Use params from console in the tests.

### ISSUE THREAD

**Issue by yuriy-chabaniuk** [Codeception/Codeception#3974]
It is not issue. It is just question, because of I didn't find it in documentation and somewhere else. 

Is it any way to put custom params when run tests from console and use this param in the test. 

For example:
```
$ codecept run acceptance --site-id=20 
```

And then use this param in the test
```
$I = new AcceptanceTester($scenario);
$I->wantTo('Check Sorting Functionality');
$siteID = $I->getParam('site-id');
```

Or something else. 

If there is no this functionality please show me where it could be added and I will send pull request. 

Thank you.

**Comment by StalkAlex** [comment]
Have you seen Environments part? http://codeception.com/docs/07-AdvancedUsage Usually env vars are used for such cases.

**Comment by yuriy-chabaniuk** [comment]
Yep I did. Using environvent require me modify config file *.yml (add new env and parameters) any time I want to test new site or something. 

Original issue is that I have some script:
```
$I = new AcceptanceTester($scenario);
.....
$I->amOnPage('/');
.....
$I->fillField('.site-id-input','123456');
.....
```

And I want to run this test for any new site without updating tests at all. 
Something like this:
```
$I = new AcceptanceTester($scenario);
.....
$I->amOnPage('/');
.....
$I->fillField('.site-id-input',$I->getParam('site-id'));
.....
```


I see following plan for this: 

1. Run test like this
php codecept run -p "site-id: 123456, group: admin"

I will send PR to add this functionality as I see it.

**Comment by yuriy-chabaniuk** [comment]
I added PR for it https://github.com/Codeception/Codeception/pull/3978

**Comment by DavertMik** [comment]
Thanks for the proposals, but we already have lots of way to achieve similar behavior. Adding another one will confuse users

**Comment by yuriy-chabaniuk** [comment]
Hi Michael. I have another question for you.

I  have some task to compare multiple rows from DB.
For example:
I want to fetch 50 rows from one table , 50 rows from another table. And
then make some comparition.
I DB module I see method `grabFromDatabase` , but this method allow as
fetch only one column from very first row.

Does it make sense to add bit more functionality to fetch multiple rows
from db in DB module. ? Or it doesn't follow Codeception philosophy and
makes no sense.

Will you just advice to use PDO in my tests instead of DB module ?


2017-02-04 1:32 GMT+02:00 Michael Bodnarchuk <notifications@github.com>:
