### ISSUE TITLE
@depends with return statement #903

### ISSUE THREAD

**Issue by Fuin** [Codeception/Codeception#3981]
So I was wondering if the issue [#903](https://github.com/Codeception/Codeception/issues/903) was solved about the passing Objects only between two tests via the return statement

Because I tried it with passing a cookie only between two tests 

    public function rememberMyLogin(\Step\Acceptance\Login $I)
    {
        $I->wantTo('remember my Login');
        $I->amOnPage(HomePage::$URL);
        $I->openLoginLayer();
        $I->waitForElementVisible(LoginPage::$loginEmailField);
        $I->fillField(LoginPage::$loginEmailField, 'email@email.com');
        $I->fillField(LoginPage::$loginPasswordField, 'password');
        $I->click(LoginPage::$loginMemorizePasswordCheckbox);
        $I->click(LoginPage::$loginSignInButton);
        $I->waitForElementVisible(ProfilePage::$profileContactDataLink);
        $I->waitForAllModulesLoaded();
        $I->seeCookie('remember_me');
        $I->amOnUrl($URL);
        $I->amOnUrl(HomePage::$URL);
        $I->waitForElementVisible(ProfilePage::$profileHeadline);
        $I->see('Profile');
        $I->seeCookie('remember_me');
        $cookie = $I->grabCookie('remember_me');
        return $cookie;
    }

    /**
     * @param \Step\Acceptance\Login $I
     *
     * @depends rememberMyLogin
     */
    public function rememberMyLogin2(\Step\Acceptance\Login $I, $cookie)
    {
        $I->wantTo('test if I am still logged in after restart the browser');
        $I->setCookie('remember_me', $cookie);
        $I->amOnPage(HomePage::$URL);
        $I->waitForElementVisible(ProfilePage::$profileHeadline);
        $I->see('Data');
    }

and I get an ` [Facebook\WebDriver\Exception\UnknownServerException] java.util.HashMap cannot be cast to java.lang.String ` Error
and it says that $cookie is of Codeception\Scenario

Is there any way to pass an Object only between two tests, rather than putting it in a Class Variable?

**Comment by DavertMik** [comment]
> Is there any way to pass an Object only between two tests, rather than putting it in a Class Variable?

No. Class variables are ok :)
As you see, your code doesn't look common to Codeception. What you are trying to do is to reuse cookies. I think you should use [sessionSnapshot](http://codeception.com/docs/06-ReusingTestCode#Session-Snapshot) feature. If it doesn't work for you, I'd recommend to write a helper based on this method.

Anyway, the logic behind saving/restoring cookies should be moved out from tests (as it is not a part of test scenario) and moved to Helper/Module level.
