### ISSUE TITLE
HTTP/Network monitor in PHPbrowser

### ISSUE THREAD

**Issue by mrmxs** [Codeception/Codeception#3984]
Can you help me with this task?
>Test somehow gets information about all loads and async requests during page is loading. Then it checks if some of them has error status (404, dead CSS links, icons, etc).

_For example, this is screenshot from Chrome's Network tool. And I mark errors I want to catch._
![image](https://cloud.githubusercontent.com/assets/16657160/22566460/09637c52-e99d-11e6-9aca-b63eb2ca8a23.png)

This Chrome's tool has an option to save current log in standard _HAR_ data format. I assume it would be great to get such output in tests automatically.

I use `PHPBrowser` (for multiple of quick tests), but unfortunately I can't find any features to work with HAR here.

Now I found that `PhantomJS` provides Network monitoring. I wrote simple script which returnes HAR for given URL. And I execute it in tests. That is my only solution.

So I wonder if there is a better and easier solution?

**Comment by Naktibalda** [comment]
PhpBrowser does not fetch resources and does not execute javascript, so no AJAX requests too.

**Comment by mrmxs** [comment]
Ok, thank you)
