### ISSUE TITLE
Add option cleanup for DataFactory module

### ISSUE THREAD

**Issue by alexpts** [Codeception/Codeception#3987]
I suggest add option 'cleanup' for DataFactory module. Default value is TRUE.
For set 'cleanup' to FALSE module don`t need remove models on '_after' hook.

In my case other module wrap test on transaction on '_before' hook and rollback db on '_after' hook.

It will possible ьore flexibility to customize the database cleanup and config via other molules.

Now already have problem with orm module:
```php
if ($this->ormModule->_getConfig('cleanup')) {
    return; // don't delete records if ORM is set with cleanup
}
```

After add `clenup` option:
```php
if (!$this->config['cleanup']) {
    return;
}
```

**Comment by DavertMik** [comment]
Sorry, I didn't understand the problem.

The DataFactory depends on ORM module (Laravel, Yii2, Doctrine), with `cleanup` option.
When ORM config have `cleanup: true`, DataFactory won't perform a cleanup by itself. In other cases it will. 

So cleanup option of DataFactory depends on cleanup option in a module it uses

**Comment by alexpts** [comment]
I need disable cleanup for ORM module (Yii2) and DataFactory.

**Comment by DavertMik** [comment]
so how records be cleared between tests?

Actually, don't ask me, just do whatever you want. 1) [extend DataFactotry](http://codeception.com/docs/06-ModulesAndHelpers#Extending-a-Module) in Helper, 2) change `_after` method, include your helper instead of DataFactory.

**Comment by alexpts** [comment]
Another module clears the database between tests.

1) I've already done so, but it seemed to me this way is not very correct
I'm worried that in future versions of changed behavior and inheritance I lose backward compatibility.

Also I noticed that you can move make object $story to new method

```php
protected function getStore() 
{
    return $this->ormModule instanceof DataMappe
        ? new RepositoryStore($this->ormModule->_getEntityManager())
        : new ModelStore()
}
```

**Comment by DavertMik** [comment]
> Also I noticed that you can move make object $story to new method

Yep. Things like a good idea. 

Ok, if you can please make PR with this change and adding a cleanup option which is `false` by default. Thanks

**Comment by alexpts** [comment]
Ok, Thanks!
By default cleanup option will set to true for save current behavior. 

I will prepare PR and close this issue after add prepare.

**Comment by alexpts** [comment]
I prepared PR - https://github.com/Codeception/Codeception/pull/3996
