### ISSUE TITLE
Custom Html report generation 

### ISSUE THREAD

**Issue by aditya-** [Codeception/Codeception#400]
sir is there any way to customize generated html report .. like this :: 
php codecept.phar run acceptance finalCept.php --debug --html

i want to include my testing report in my web application ... like showing failed scenarios ..etc

i want to customize generated html report .. 
how to customize generated html report ... where to edit code 

@DavertMik and @Codeception .. please suggest

**Comment by mkatuah** [comment]
how we can change pathe of report and how i can make the  report name  dynamic

**Comment by aWuttig** [comment]
@mkatuah 
`codecept run acceptance --html && mv report.html acceptance.html`
