### ISSUE TITLE
$I->switchToIframe() raises InvalidSelectorException

### ISSUE THREAD

**Issue by mpgo13** [Codeception/Codeception#4001]
#### What are you trying to achieve?

Switch to parent frame by $I->switchToIframe();

#### What do you get instead?

Getting a InvalidSelectorException, see https://github.com/Codeception/Codeception/commit/ed549a9d2c5b6d4ccf940a6dcfa671cd042e8f99#commitcomment-20773990

**Comment by DavertMik** [comment]
Sorry for the regression. Forgot to add `return` while small refactoring.
