### ISSUE TITLE
Different configurations in suite.yml

### ISSUE THREAD

**Issue by floxiann** [Codeception/Codeception#4003]
Tell me please.
There suite acceptanceMonolith, its configuration http://prntscr.com/e5ifz8 (host and password to the database) depends on the Url in codeception.yml file, you need to realize this relationship. How is it better to do? Maybe it's possible to do so: to create a file with the urls and appropriate access to the database and before you run the test to change the configuration file in suite.yml Extension suite.before, but how?

**Comment by Naktibalda** [comment]
You could use [Environments](http://codeception.com/docs/07-AdvancedUsage#Environments) feature to make Codeception use different urls and different database settings.
