### ISSUE TITLE
Potentially using wrong vendor library because of namespace?

### ISSUE THREAD

**Issue by robsch** [Codeception/Codeception#4004]
I'm not sure if this is a bug or if I do anything wrong. So apologize if I'm to blame.

So, what might be wrong is the following:

I use composer in my PHP project, so there is vendor folder. I'm using Guzzle in version 6.2.2 which can be found in vendor/guzzlehttp/guzzle.

I've created a single test. This test tests my PHP code, which in turn uses the Guzzle library. The test then fails with a message 

> [GuzzleHttp\Exception\ServerException] Server error response [url] login [status code] 503 [reason phrase] Service Unavailable

and that is because the parameter _base_uri_ isn't evaluated.

I finally found out that Codeception is using it's own Guzzle library in codecept.phar (version 5.3.1, right?) instead of the one in my vendor folder when I call ```./codecept.phar run``` in the project folder. In this older version the parameter is called _base_url_ (url instead of uri), so that's why the test doesn't work. 

However, I have codeception also as a "require-dev" in the vendor folder so I can start it also on the command line with  ```php /var/www/html/my-project/vendor/codeception/codeception/codecept -c /var/www/html/my-project/codeception.yml run```

I think it has something to do with namespacing. My code declares ```use GuzzleHttp\Client;```. I guess this leads to the usage of the internal Guzzle when codecept.phar is used. And I think this shouldn't be the case with a 'normal' composer setup project (all is out of the box, no special configurations for paths).

Can you optimize this? Or do I have to do things differently?

* Codeception version: 2.2.8
* PHP Version: 7.0
* Operating System: Fedora
* Installation type: Phar & Composer

Reference
* base_url in 5.3: http://docs.guzzlephp.org/en/5.3/clients.html#creating-a-client 
* base_uri 6.2.2: http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client

**Comment by Naktibalda** [comment]
Your problem is that you use a phar file and have the same libraries installed in vendor dir.
Solution is to stop using phar and run local codeception.

This issue should be fixed or improved by #3997

**Comment by robsch** [comment]
@Naktibalda Thank you for this hint!
