### ISSUE TITLE
Console completion

### ISSUE THREAD

**Issue by gdscei** [Codeception/Codeception#4006]
It would be great to add autocompletion in bash for commands, and arguments to those commands (suites, tests).

There's a drop-in package available for Symfony Console apps: https://github.com/stecman/symfony-console-completion
It would be great though to configure this so suites & tests (maybe even groups?) had autocompletion too.

**Comment by gdscei** [comment]
@DavertMik I'll be glad to contribute to get this done. How do you suggest I put a library like symfony console completion in composer? As a suggestion or a required composer package? 
If I put it as a suggestion, I'd probably have to create a seperate package/extension for codeception, to not get class not found errors (or nasty `if(class_exist())`, but that doesn't seem like the right way to go...)

**Comment by Naktibalda** [comment]
It is a small package, adding it as required dependency should be fine.
