### ISSUE TITLE
the mailer's class always replace as "Codeception\\Lib\\Connector\\Yii2\\TestMailer"

### ISSUE THREAD

**Issue by JunelanMe** [Codeception/Codeception#4011]
#### What are you trying to achieve?
Run in YII_ENV_TEST mode , The function in mailer componets should be trigger as like in dev mode
```
namespace app\common\components;
app/componets/mailer.php
{
........................
public function sendMail($titile ,$ email)
{
do some mail control here
}
....................
}

the the controller.php use the action as following
yii->mailer->sendMail("send a mail to you " , 'hello@mail.com')

```

#### What do you get instead?

```
The mailer's class  always replace as " Codeception\\Lib\\Connector\\Yii2\\TestMailer"

"ret":100000,"message":"Calling unknown method: Codeception\\Lib\\Connector\\Yii2\\TestMailer::sendMail()","data":[],"returned":0}

I debug in vendor .  I found the class in mailer always replace as ""{ret":100000,"message":"Calling unknown method: Codeception\\Lib\\Connector\\Yii2\\TestMailer::sendMail()","data":[],"returned":0}" 

and the "class" is not in         
$allowedOptions = [
            'htmlLayout',
            'textLayout',
            'messageConfig',
            'messageClass',
            'useFileTransport',
            'fileTransportPath',
            'fileTransportCallback',
            'view',
            'viewPath',
        ];
![qq 20170210182244](https://cloud.githubusercontent.com/assets/11918045/22824031/2fe213a0-efc1-11e6-84a2-d0d1cf4d1671.png)

https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/Connector/Yii2.php

```
> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:  Codeception PHP Testing Framework v2.2.4
* PHP Version:Powered by PHPUnit 4.8.27 by Sebastian Bergmann and contributors.
* Operating System: CentOS Linux release 7.3.1611 (Core)
* Installation type: Phar || Composer ,by Composer
* List of installed packages (`composer show`)
specification to describe web services, operations/actions and models enabli...
* Suite configuration:

```yml
# paste suite config here
```

**Comment by DavertMik** [comment]
> The function in mailer componets should be trigger as like in dev mode

Nope, they should not. Test mode is not the same as development, development is not as production. The goal of running test is to validate that email can be actually created and dispatched to mailer component. However, it won't check if it was actually delivered because it depends on your production/staging configuration. 

To test emails use MailCatcher or MailTrap for acceptance tests, so you could check that emails are sent as they are supposed to.
