### ISSUE TITLE
SOAP - Unable to assign headers to root Header

### ISSUE THREAD

**Issue by kurbar** [Codeception/Codeception#4017]
I'm trying to apply some headers the to root `Header` element in `Envelope` but the current `haveSoapHeader` method does not support it. I can only make nested headers with it.

For example:

```
$this->getModule('SOAP')->haveSoapHeader('Header', array(
	'Heb' => 'RA21',
	'To' => '::RA002',
	'Action' => 'Send',
	'MessageID' => uniqid(),
));
```

Results in
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Header xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
		<Header>
			<Heb>RA21</Heb>
			<To>::RA002</To>
			<Action>Send</Action>
			<MessageID>58a2df9885338</MessageID>
		</Header>
	</soapenv:Header
	<soapenv:Body xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"</soapenv:Body>
</soapenv:Envelope>
```

I would need those headers to be under `soapenv:Header` and not nested in it.

Is it possible to do with the SOAP module?

* Codeception version: 1.8
* PHP Version: 5.3
* Operating System: CentOS
* Installation type: Composer

**Comment by Naktibalda** [comment]
`xmlRequest` is a public property, you could implement your own helper method similar to [haveSoapHeader](https://github.com/Codeception/Codeception/blob/1.8/src/Codeception/Module/SOAP.php#L107-L115).

**Comment by kurbar** [comment]
Hah, why didn't I think of it. Worked like a charm! Many thanks on the tip :)

In case if anyone wishes to use it as well, I made it a quick and dirty one:
```php
public function addRootHeader($name, $value)
	{
		/** @var \DOMDocument $request */
		$request = $this->getModule('SOAP')->xmlRequest;

		$header = $request->documentElement->getElementsByTagNameNS('http://schemas.xmlsoap.org/soap/envelope/', 'Header')->item(0);
		$newHeader = $request->createElement($name, $value);
		$header->appendChild($newHeader);
	}
```
