### ISSUE TITLE
Unable to upload file using attachfile function  when remote is Phantomjs

### ISSUE THREAD

**Issue by samiullah** [Codeception/Codeception#4024]
#### What are you trying to achieve?
I am trying to upload a file using attachFile function. I have Phantomjs remote.
#### What do you get instead?
I am not able to see file getting upload in screenshot

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
Have you set `browser: phantomjs` in WebDriver configuration?

**Comment by Naktibalda** [comment]
Related issue #1823

`browser: phantomjs` fixes file uploads when PhantomJS is running on the same machine, you may need to remove it to make file uploads work with remote PhantomJS.

**Comment by heykarthikwithu** [comment]
i have codeception version 2.2.4

i have commented `$el->setFileDetector(new \LocalFileDetector);`
but was facing with 
```
 [Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
```

**Comment by Naktibalda** [comment]
You need `LocalFileDetector` to upload file to remote PhantonJS.
`UselessFileDetector` only works with local PhantomJS.

**Comment by Naktibalda** [comment]
Please let us know if you managed to solve this issue.

**Comment by heykarthikwithu** [comment]
Actually @Naktibalda i want to mention one more point here...

we were able to do file upload with phanomjs which is running locally, 
we aren't able to do file upload with Remote phantomjs... which is running in the different instance..

**Comment by Naktibalda** [comment]
It is an issue of PhantonJS: https://github.com/ariya/phantomjs/issues/13302#issuecomment-158628631

> If your PhantomJS actually runs on a different machine, regardless of which remote driver you use you need to make sure that the files are actually available on the remote server on the path that you are sending.
