### ISSUE TITLE
seeResponseMatchesJsonType Error 

### ISSUE THREAD

**Issue by matheusmpinheiro** [Codeception/Codeception#4034]
Hey guys, I'm trying to do an acceptance test in an API, however I'm getting an error while using 'seeResponseMatchesJsonType' to verify the JSON output.

Here is the JSON output
```
{
  "data": {
    "G": {
      "id": 1,
      "key": "G",
      "name": "Test",
      "segments": {
        "1": {
          "id": 1,
          "code": "1",
          "name": "result1",
        },
        "2": {
          "id": 2,
          "code": "2",
          "name": "result2",
        }
      }
    }
}
```
Here is the code (I didn't include all the attributes just for test purpose)
```
$I->seeResponseIsJson();
$I->seeResponseMatchesJsonType([
	'data' => [[
		'id' => 'string',
	]],
]);
```
This is what I'm getting:
`Key `0` doesn't exist in {"G":{"id":1,"key":"G","name":"Test","segments":{"1":{"id":1,"code":"1","name":"result1"},"2":{"id":2,"code":"2","name":"result2"}}}...`

Does anyone have any idea why it's happening? I'm new to Acceptance tests with Codeception, hope I've provided all information you need to help me.

**Comment by Naktibalda** [comment]
It happens because you have key "G" in "data" and your JsonType definition doesn't expect it.

**Comment by matheusmpinheiro** [comment]
Thank you.
