### ISSUE TITLE
How close automatic opened print window?

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#4036]
I need your help.

I testing one page, where i click to button (i must send form). After click to button is automatically opened new printing window. How close printing window, or set not open this window in Selenium webdriver?

Because test waiting to close printing window. When i doing click, test doing next step and continue with scenario.

**Comment by Naktibalda** [comment]
Try pressing Escape key.

Helper method:
```php
public function pressEscapeKey()
{
    $escapeKey = \Facebook\WebDriver\WebDriverKeys::ESCAPE;
    $this->getModule('WebDriver')->webDriver->getKeyboard()->sendKeys([$escapeKey]);
}
```
