### ISSUE TITLE
Crash with "set_time_limit"

### ISSUE THREAD

**Issue by punchi** [Codeception/Codeception#4037]
#### What are you trying to achieve?
Run a test with "set_time_limit"

#### What do you get instead?
"Maximum execution time of 10 seconds exceeded"

> Provide test source code if related

```php
    public function __construct()
    {
        set_time_limit(60);
    }
```
### Details

* Codeception version: 2.2.9
* PHP Version: 5.6.14
* Operating System: Windows 7 || Ubuntu 14.04.1 LTS
* Installation type: Phar

It's easy to test, just write "set_time_limit(X);" and wait X seg. after Codeception execute that instruction, and on any test posterior test, the Fatal error will appear. #

**Comment by punchi** [comment]
The fix was:
```php
        if (\App::environment('local', 'testing')) {
            //set_time_limit(0); ???
        } else {
            set_time_limit(60);
        }
```
Not too elegant but... well... works

**Comment by Naktibalda** [comment]
Probably it is a time limit enforced by Phpunit.

**Comment by Naktibalda** [comment]
@punchi I have tried to reproduce your issue with no success.
I only got `PHP Fatal error:  Maximum execution time of 10 seconds exceeded` when I explicitly set `set_time_limit(10)`.
When I set time limit to 60, I got error after 60 seconds.
When I didn't set a limit, Codeception haven't impose any limit.

Probably time limit is reduced by your application code or by your framework.
