### ISSUE TITLE
Laravel4 module support in codeception 2.2

### ISSUE THREAD

**Issue by hootener** [Codeception/Codeception#4042]
I'm upgrading to codeception 2.2 from a legacy 2.1.x setup to leverage many of the new features in Codeception 2.2 -- most importantly environment variable support in *.yml configuration files.

The application is written in Laravel4 and I don't see that changing anytime soon. However, the Laravel4 module was removed in codeception 2.2. 

The changelog for codeception 2.2 states that Laravel 4 support was 'moved to packages' is there a laravel 4 package for codeception 2.2 somewhere that I just can't seem to find? Is there some other method to make use of codeception 2.2 for testing my Laravel 4 app?

**Comment by janhenkgerritsen** [comment]
Where did you read that the Laravel 4 support was moved to packages? As far as I can see the changelog only mentions that the Laravel 4 module is removed in Codeception 2.2.0, or did I miss something?

The Laravel 4 module was dropped because it depended on older versions of the Symfony components that caused a lot of issues. If you want to use Codeception with a Laravel 4 application I'm afraid you will have to keep using Codeception 2.1.

**Comment by hootener** [comment]
Regarding the packages comment, this changelog:

https://github.com/Codeception/codeception.github.com/blob/master/_posts/2016-06-03-codeception-2.2-is-here.markdown

Seen here: http://codeception.com/06-03-2016/codeception-2.2-is-here.html

> Please also note that Dbh and Laravel4 module were removed from core package and moved into separate packages.

**Comment by janhenkgerritsen** [comment]
Ah ok, I was not aware of that. But I can tell you that this is not true for the Laravel 4 module.

@DavertMik What do you want to do with this?

**Comment by hootener** [comment]
The easiest thing is just to remove it from the blog post, I'd imagine. 

Personally Laravel 4 support in 2.2 would be awesome, but I get why it isn't there. With the update of Laravel 4 to 4.2.11 (which allows php7 compatibility) is there any chance that the issues with symfony can be addressed and allow the module to be functional again in 2.2? That may be a dumb question, I have no idea, just throwing that out there for you all to consider.

**Comment by janhenkgerritsen** [comment]
With that update they did increase the Symfony components version to 2.7.*, so in theory that should make it possible to make the old Laravel 4 module work again with Codeception 2.2. However, I don't think we should add it back to the core again, but maybe we can create a separate package for this.

**Comment by hootener** [comment]
Would love to see Laravel4 back in however you all decide to do it. Thanks for even considering it.

**Comment by DavertMik** [comment]
@hootener sorry, module won't be added, as we can't take a responsibility to maintain it. However, you can try to copy a module https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/Laravel4.php and its connector https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Connector/Laravel4.php test it and release it as a 3rd-party package. I think they should work with Codeception 2.2 and latest Laravel, but I can't be sure. Ping me if you will have further questions.
