### ISSUE TITLE
Two groups in single cest file

### ISSUE THREAD

**Issue by Periyasamy025** [Codeception/Codeception#4053]
I want run single group in cest file
/**
 * @group admin
 */
$I = new AcceptanceTester($scenario);
$I->wantToTest('admin area');
$I->wantTo('ensure Toupper form works');
$I->amOnPage('toupper.html');
$I->see('Convert Me!');
$I->fillField('string', "Convert me to upper");
$I->click('Convert');
$I->amOnPage('toupper.php');
$I->see('To Upper!');
$I->click('Back to form');
$I->see('Convert Me!');
$I->fillField('string', '');
$I->click('Convert');
$I->amOnPage('toupper.php');
$I->see('No string entered');

/**
 * @group dummy
 */
$I->wantToTest('dummy area');
$I->wantTo('ensure Toupper form works');
$I->amOnPage('toupper.html');
$I->see('Convert Me!');
$I->fillField('string1', "Convert me to upper");
$I->click('Convert');
$I->amOnPage('toupper.php');
$I->see('To Upper!');
$I->click('Back to form');
$I->see('Convert Me!');
$I->fillField('string', '');
$I->click('Convert');
$I->amOnPage('toupper.php');
$I->see('No string entered');

**Comment by Naktibalda** [comment]
Just split it to two files.

**Comment by DavertMik** [comment]
According to the code you are using Cept format. In Cest there is no line like `$I = new AcceptanceTester($scenario);`


So better idea is to use Cest format: codeception.com/docs/07-AdvancedUsage#Cest-Classes
