### ISSUE TITLE
c3 No test but positiv code coverage

### ISSUE THREAD

**Issue by astridx** [Codeception/Codeception#4069]
#### What are you trying to achieve?
I make my first steps with code coverage and c3.php.
I want to start with the acceptance tests. For testing reasons I deleted all feature files. But when I run the test with 
`vendor/bin/codecept run acceptance --coverage-html
`
I saw a coverage coverage of 33% for methodes and 89% for lines .

![c3](https://cloud.githubusercontent.com/assets/9974686/24147833/5ddd3868-0e3c-11e7-9ecc-e3954022cdcf.png)

How is this possible?

#### My test configuration

vendor/bin/codecept config:validateValidating global config... Ok

Codeception Config:

Array
(
    actor => Tester
    paths => Array
        (
            tests => tests
            log => tests/_output
            data => tests/_data
            support => tests/_support
            envs => tests/_envs
        )

    settings => Array
        (
            bootstrap => _bootstrap.php
            colors => 1
            memory_limit => 1024M
            strict_xml => 
            lint => 1
            backup_globals => 1
        )

    extensions => Array
        (
            enabled => Array
                (
                    0 => Codeception\Extension\RunFailed
                )

            config => Array
                (
                )

            commands => Array
                (
                )

        )

    modules => Array
        (
            config => Array
                (
                    Db => Array
                        (
                            dsn => 
                            user => 
                            password => 
                            dump => tests/_data/dump.sql
                        )

                )

        )

    coverage => Array
        (
            enabled => 1
            include => Array
                (
                    0 => plugins/content/agpaypal/*.php
                )

            c3_url => http://localhost/joomla/plugins/content/agpaypal/agpaypal.php
        )

    namespace => 
    include => Array
        (
        )

    reporters => Array
        (
            xml => Codeception\PHPUnit\Log\JUnit
            html => Codeception\PHPUnit\ResultPrinter\HTML
            tap => PHPUnit_Util_Log_TAP
            json => PHPUnit_Util_Log_JSON
            report => Codeception\PHPUnit\ResultPrinter\Report
        )

    groups => Array
        (
        )

    params => Array
        (
        )

    gherkin => Array
        (
        )

)

Directories:
codecept_root_dir()   /var/www/html/joomla/
codecept_output_dir() /var/www/html/joomla/tests/_output/
codecept_data_dir()   /var/www/html/joomla/tests/_data/

Available suites: unit, acceptance, functional
Validating suite unit... Ok
Validating suite acceptance... Ok
Validating suite functional... Ok

**Comment by Naktibalda** [comment]
Probably you get some code coverage because your `c3_url` is included to code coverage.

**Comment by astridx** [comment]
Thank you very much. That was the solution. I was not aware, that it was not allowed to include the c3.php in one of my test files.
