### ISSUE TITLE
No way to use helpers/modules inside dataprovider methods

### ISSUE THREAD

**Issue by Morjodrom** [Codeception/Codeception#4087]
**What are you trying to achieve?**
Need to populate dataprovider with data from a database. 

**What do you get instead?**
Unfortunately, it's not possible as neither _inject method is called before the dataproviders nor the Actor or Scenario is accessible in it.

Perhaps, it's a bad testing pattern to use DB in dataprovider, but I think it's rather ubiquitous use case for them. So, it'd be nice to see such a feature in the framework or at least mention in the docs that such approach is discouraged.

**Comment by edno** [comment]
Yes, this is currently a known limitation. Please see my comment in #4008.

For solving both use cases, we should change the sequence for loading test cases in Codeception. 
@DavertMik, what do you about processing `@example` and `@dataprovider` at the end of event `beforeSuite`?

In short term, I can extend the [dataprovider module](https://github.com/edno/codeception-dataprovider) with a new annotation `@usemodule`. This will allows to use `@dataprovider` processed by the module instead of core Codeception,  hence it will make the extension compatible again with current version of Codeception. 
@Fuin and @Morjodrom, would that be useful for you?

**Comment by Fuin** [comment]
For me it would be totally useful, your answer in #4008 sadly wont work for me ;)
But if you could adjust it like that I can work with it.

**Comment by Morjodrom** [comment]
@edno , thank you!
I made a workaround with custom singleton DB connection, rather dirty way, but quick. I like the idea of following the vanilla codeception for this case, hence, if you feel like improving [Dataprovider Module](https://github.com/edno/codeception-dataprovider), I'd be glad to test it in my environment and use before it's implemented in the framework.  But now it's not extremely crucial for me.

**Comment by keithcrooks** [comment]
Did anything progress with this?

I have some helpers to create common Stubs. These work fine in the test methods. However, as above, these cannot be used in the data provider methods.

I was hoping to move some of the code out of the tests and into the data providers to keep the tests focused. However, I have encountered the issue above.

**Comment by darkbluesun** [comment]
+1 this would be super useful

**Comment by mlambley** [comment]
Yes please! I'm hitting this issue right now.
I have a module which does various things including fetching data, and it is used by all of my cests.
I can call it everywhere except from within my data providers.

**Comment by mikolajzieba** [comment]
Is there any possibility for that to be implemented in the future or everyone should look for workaround on this?

**Comment by mlambley** [comment]
@mikolajzieba Using [Extensions](https://codeception.com/docs/08-Customization#Extension) greatly enhances the functionality of codeception cests. 

Further to this, you can hack together your own [cest loader](https://codeception.com/docs/07-AdvancedUsage#Formats). Given that the loader is where the data provider function is called, you may be able to do something there. It's how I got my code to work.

Aside from those, only a significant overhaul will change anything. Currently the data provider helps to builds the tests, then the modules are loaded, then the tests are run. I wouldn't hold my breath that this will change anytime soon.

**Comment by weeg** [comment]
You can use callback and pass the $I variable at runtime.

```php
protected function dataProvider(): array
{
    return [
        [
            'productIds' => function (MyTester $I) {
                return [
                   $I->getProductIdBySku('my-product-sku-1')
                ];
            },
            'productSkus' => [
                'my-product-sku-2',
            ],
        ],
    ];
}
```

And use like this:
```php
/**
 * @dataProvider dataProvider
 */
public function testRequests(MyTester $I, Example $testData): void
{
    $I->requestProducts(
        productIds: $testData['productIds']($I),
        productSkus: $testData['productSkus'],
    );
}
```

**Comment by Naktibalda** [comment]
It is possible to use actor object in data provider since #6696 (Probably 5.1.0)
