### ISSUE TITLE
No _after hook call between @dataprovider iterations in Cest

### ISSUE THREAD

**Issue by Morjodrom** [Codeception/Codeception#4094]
It's rather expected behaviour for _after to be called between iterations of dataprovider examples (such order is implemented in PhpUnit tearDown). 
Unfortunately, _after is being called after all the bunch of data iterated with the test method, so, side effects are not cleared.

Unit tests run
Codeception version 2.2.10
CentOS with php 5.6
All the dependencies are up to date.

**Comment by fffilimonov** [comment]
I'm running Codeception 2.3.7
And see result of _after in Cest after each dataset.
Maybe, you have no _after hook in failed case?
