### ISSUE TITLE
[Yii2Module] It would be great if Yii2Module would have not only $this->app but $this->container too

### ISSUE THREAD

**Issue by antonmarin** [Codeception/Codeception#4095]
#### What are you trying to achieve?
call `$this->container` to get container 

#### What do you get instead?
have to use Yii::$container or `$this->app` service locator

Part of Codeception\Module\Yii2
```php
 $this->app = $this->client->getApplication();
```

**Comment by samdark** [comment]
Makes sense. Would you like to send a pull request?

**Comment by alexkart** [comment]
Could you please explain, where you want to call `$this->container`?

**Comment by antonmarin** [comment]
Same as $this->app

**Comment by alexkart** [comment]
In a unit test?

**Comment by antonmarin** [comment]
Do you use $this->app in unit test? Integrational

**Comment by alexkart** [comment]
You mean acceptance? You can't use $this->app in acceptance tests either.
If you want someone to add this feature you need to provide more information and example code.

**Comment by antonmarin** [comment]
No. I mean Integration.
https://en.wikipedia.org/wiki/Integration_testing

**Comment by SamMousa** [comment]
I think this should be closed. The module moved away from having a separate reference to the application and instead now uses `Yii::$app()` directly or indirectly everywhere.
