### ISSUE TITLE
Error Use CodeCeption with Selenium in PHP 7.1.1

### ISSUE THREAD

**Issue by MemoChou** [Codeception/Codeception#4103]
#### What are you trying to achieve?
Use CodeCeption with Selenium in PHP7. Just visit a website (Ex:google.com) and got an error even though chrome webdriver did start.

#### What do you get instead?
Selenium got an error regard to json_decode response.

> [Facebook\WebDriver\Exception\WebDriverException]
>   JSON decoding of remote response failed.
>   Error code: 4
>   The response: ''

and with --debug options:

> Exception trace:
>  () at /home/quangtd/Projects/gate-autotest/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:292
>  Facebook\WebDriver\Remote\HttpCommandExecutor->execute() at /home/quangtd/Projects/gate-autotest/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:535
>  Facebook\WebDriver\Remote\RemoteWebDriver->execute() at /home/quangtd/Projects/gate-autotest/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
>  Facebook\WebDriver\Remote\RemoteExecuteMethod->execute() at /home/quangtd/Projects/gate-autotest/vendor/facebook/webdriver/lib/WebDriverOptions.php:68
>  Facebook\WebDriver\WebDriverOptions->deleteAllCookies() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:368
>  Codeception\Module\WebDriver->_after() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:68
>  Codeception\Subscriber\Module->after() at n/a:n/a
>  call_user_func() at /home/quangtd/Projects/gate-autotest/vendor/symfony/event-dispatcher/EventDispatcher.php:174
>  Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /home/quangtd/Projects/gate-autotest/vendor/symfony/event-dispatcher/EventDispatcher.php:43
>  Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:126
> Codeception\PHPUnit\Listener->endTest() at /home/quangtd/Projects/gate-autotest/vendor/phpunit/phpunit/src/Framework/TestResult.php:399
>  PHPUnit_Framework_TestResult->endTest() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/Test/Test.php:112
>  Codeception\Test\Test->run() at /home/quangtd/Projects/gate-autotest/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
>  PHPUnit_Framework_TestSuite->run() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:106
>  Codeception\PHPUnit\Runner->doEnhancedRun() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
>  Codeception\SuiteManager->run() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/Codecept.php:184
>  Codeception\Codecept->runSuite() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/Codecept.php:153
>  Codeception\Codecept->run() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/Command/Run.php:366
>  Codeception\Command\Run->runSuites() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/Command/Run.php:293
>  Codeception\Command\Run->execute() at /home/quangtd/Projects/gate-autotest/vendor/symfony/console/Command/Command.php:265
>  Symfony\Component\Console\Command\Command->run() at /home/quangtd/Projects/gate-autotest/vendor/symfony/console/Application.php:826
>  Symfony\Component\Console\Application->doRunCommand() at /home/quangtd/Projects/gate-autotest/vendor/symfony/console/Application.php:189
>  Symfony\Component\Console\Application->doRun() at /home/quangtd/Projects/gate-autotest/vendor/symfony/console/Application.php:120
>  Symfony\Component\Console\Application->run() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/src/Codeception/Application.php:103
>  Codeception\Application->run() at /home/quangtd/Projects/gate-autotest/vendor/codeception/codeception/package/bin:37
>  require() at phar:///usr/local/bin/codecept/autoload.php:12
>  require_once() at /usr/local/bin/codecept:5

> Provide test source code if related
I just use composer install codeception, create an acceptance test then edit only 2 files
acceptance.suite.yml

```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://google.com/
            browser: chrome
        - \Helper\Acceptance
```
TestCept.php
```php
<?php

$I = new AcceptanceTester($scenario);
$I->wantTo('Check chrome');
$I->amOnPage('/chrome');
```
That's all. Run the command "codeception run" and got the above error.

### Details
* Codeception version: 2.2.0
* PHP Version: 7.1.1
* Operating System: Ubuntu 14.04
* Installation type: Phar || Composer

**Comment by Naktibalda** [comment]
Please provide the log of Selenium

**Comment by MemoChou** [comment]
Here's the selenium log:
> Apr 05, 2017 8:22:13 AM org.openqa.grid.selenium.GridLauncher main
INFO: Launching a standalone server
08:22:14.297 INFO - Java: Oracle Corporation 24.121-b00
08:22:14.298 INFO - OS: Linux 3.13.0-115-generic amd64
08:22:14.323 INFO - v2.39.0, with Core v2.39.0. Built from revision ff23eac
08:22:14.548 INFO - Default driver org.openqa.selenium.iphone.IPhoneDriver registration is skipped: registration capabilities Capabilities [{platform=MAC, browserName=iPhone, version=}] does not match with current platform: LINUX
08:22:14.548 INFO - Default driver org.openqa.selenium.iphone.IPhoneDriver registration is skipped: registration capabilities Capabilities [{platform=MAC, browserName=iPad, version=}] does not match with current platform: LINUX
08:22:14.548 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match with current platform: LINUX
08:22:14.642 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
08:22:14.643 INFO - Version Jetty/5.1.x
08:22:14.659 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
08:22:14.659 INFO - Started HttpContext[/selenium-server,/selenium-server]
08:22:14.660 INFO - Started HttpContext[/,/]
08:22:14.765 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@7803e4a4
08:22:14.765 INFO - Started HttpContext[/wd,/wd]
08:22:14.774 INFO - Started SocketListener on 0.0.0.0:4444
08:22:14.775 INFO - Started org.openqa.jetty.jetty.Server@1690d0ea
08:22:18.772 INFO - Executing: [new session: Capabilities [{browserName=chrome}]] at URL: /session)
08:22:18.810 INFO - Creating a new session for Capabilities [{browserName=chrome}]
Starting ChromeDriver 2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3) on port 20725
Only local connections are allowed.
08:22:21.770 INFO - Done: /session
08:22:21.916 INFO - Executing: [implicitly wait: 0] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/timeouts/implicit_wait)
08:22:21.940 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/timeouts/implicit_wait
08:22:21.943 INFO - Executing: [fetching available log types] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log/types)
08:22:21.965 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log/types
08:22:21.967 INFO - Executing: [fetching logs for: browser] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log)
08:22:21.970 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log
08:22:21.972 INFO - Executing: [fetching logs for: driver] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log)
08:22:21.976 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log
08:22:21.977 INFO - Executing: [fetching logs for: client] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log)
08:22:21.978 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log
08:22:22.015 INFO - Executing: [fetching logs for: server] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log)
08:22:22.015 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log
08:22:22.017 INFO - Executing: [take screenshot] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/screenshot)
08:22:22.357 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/screenshot
08:22:22.367 INFO - Executing: [get page source] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/source)
08:22:22.377 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/source
08:22:22.383 INFO - Executing: [get: http://gate-beta.evolable.asia/login] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/url)
08:22:23.303 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/url
08:22:23.310 INFO - Executing: [fetching available log types] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log/types)
08:22:23.329 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log/types
08:22:23.331 INFO - Executing: [fetching logs for: browser] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log)
08:22:23.343 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log
08:22:23.345 INFO - Executing: [fetching logs for: driver] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log)
08:22:23.348 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log
08:22:23.350 INFO - Executing: [fetching logs for: client] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log)
08:22:23.350 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log
08:22:23.353 INFO - Executing: [fetching logs for: server] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log)
08:22:23.353 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/log
08:22:23.354 INFO - Executing: [take screenshot] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/screenshot)
08:22:23.519 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/screenshot
08:22:23.522 INFO - Executing: [get page source] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/source)
08:22:23.533 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/source
08:22:23.538 INFO - Executing: [delete all cookies] at URL: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/cookie)
08:22:23.800 INFO - Done: /session/6d8c3324-5c48-43db-841b-69b86eacaff2/cookie

**Comment by MemoChou** [comment]
Here's my output for now
[output.txt](https://github.com/Codeception/Codeception/files/895013/output.txt)

**Comment by Naktibalda** [comment]
I think that important bit is 

04:22:32.96 WARNING - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Exception: no such window: target window already closed

Most likely it is an issue of chromedriver.
You can try to report it at https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by MemoChou** [comment]
I think the problem is php7 did not return the value the same way it use with php 5.5 in the command $this->curl = curl_init(), the library it use is HttpCommandExecutor.php; 
@Naktibalda: Yeah, you're right but after retesting without the chrome window closed, i still see json return the respond == null.

**Comment by Naktibalda** [comment]
What version of Selenium are you using? Is it really 2.39.0? Try to upgrade.

**Comment by Naktibalda** [comment]
@MemoChou Have you tried to use a newer version of Selenium?
