### ISSUE TITLE
seeLinks() Relative URLs Check

### ISSUE THREAD

**Issue by yugenekr** [Codeception/Codeception#4107]
Hey guys,

I'd like to re-open a question stated in  [this request](https://github.com/Codeception/Codeception/issues/3463)

I've updated codeception from version 2.2.1 to 2.2.10 and got the same issue.

If it's not a bug in the code, then at least docs are misleading on this question, especially providing an example where relative URL is in the href, but still seeLink() method asserts it's found:

    $I->seeLink('Logout','/logout'); // matches <a href="/logout">Logout</a>

**In reality codeception doesn't work this way, or am I missing a point?**

An example from my setup:

 html:
```
    <li class="active"><a href="/index-test.php/master/apps">Apps</a></li>
```
this test fails:
```
    $I->seeLink('Apps', '/index-test.php/master/apps')
```

The way Codeception interprets this internally:
```
    // Found element href attribute
    ~/.composer/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:937:
string(44) "http://mydomain.dev/index-test.php/master/apps"

    // Passed $url to check
    ~/.composer/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:938:
    string(27) "/index-test.php/master/apps"
```

Thanks.

**Comment by Naktibalda** [comment]
Documentation of `seeLink` is shared with other modules, because it is documented in the [interface](https://github.com/Codeception/Codeception/blob/2.2.10/src/Codeception/Lib/Interfaces/Web.php#L317-L331).

It appears that browser drivers automagically transform relative urls to full urls.

>On `<a href=…>` and `<img src=…>` Selenium prefers the longer-form full URL when a relative URI is specified. https://github.com/SeleniumHQ/selenium/issues/2301

Patches are welcome.

**Comment by gdscei** [comment]
@Naktibalda Would you prefer a change to the function to make it support relative urls, or rather create a seperate function (something like seeUrlInLink)?

**Comment by Naktibalda** [comment]
I totally agree that it is a bug, it just hasn't reached the top of my priority list yet.

I think that it should be fixed by making `$url` parameter absolute.
