### ISSUE TITLE
Problem with session in one Cest file

### ISSUE THREAD

**Issue by tasselchof** [Codeception/Codeception#4112]
Hello!

I have a problem with each test after second one. I am running suit:

[02:59 AM]-[vagrant@o]-[/home/dev/application]-[git master] 
$ ./vendor/bin/codecept run ProductsApiFunctional ShopCrudCest
Codeception PHP Testing Framework v2.2.10
Powered by PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

ProductsApiFunctional Tests (2) -----------------------------------------------------------------------------------------------------------------------------------------------
✔ ShopCrudCest: Get shops (3.21s)
E ShopCrudCest: Create shop 
E ShopCrudCest: Create shop (1.88s)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Second one is failed because of:

1) ShopCrudCest: Create shop
 Test  codeception/ProductsApiFunctional/ShopCrudCest.php:createShop
                                                                                                               
  [PHPUnit_Framework_Exception] session_regenerate_id(): Cannot regenerate session id - session is not active  

Which is coming from Zend Framework Session manager.

Who faced the issue like this?

**Comment by Naktibalda** [comment]
Are you using ZF2 module?

**Comment by Naktibalda** [comment]
[regenerateId](https://github.com/zendframework/zend-session/blob/release-2.7.3/src/SessionManager.php#L321-L328)
```php
    public function regenerateId($deleteOldSession = true)
    {
        if ($this->sessionExists()) {
            session_regenerate_id((bool) $deleteOldSession);
        }
        return $this;
    }
```

You got this particular message, because `sessionExists` returns true even [when the session is not active](https://github.com/zendframework/zend-session/blob/release-2.7.3/src/SessionManager.php#L87-L100).

Anyway, even if the session was active, you would probably get a "headers already sent" error.
It is a general issue with framework modules that they run in a single process and PHP functions that are setting headers can't be tested.

A workaround is to add condition to your code to skip regenerateId() call in the test environment.

**Comment by tasselchof** [comment]
Got it, maybe it's because of authentication - inside the adapters I have session regeneration.

About "headers already sent" - this was in pure PHPUnit tests (without codeception), but fixed by just adding ob_start(); before code.

**Comment by tasselchof** [comment]
> You got this particular message, because sessionExists returns true even when the session is not active.

I check just now - it's like this, because (session_status() == PHP_SESSION_ACTIVE) is true. I added check in session manager:

`if ($this->sessionExists()) {
            try {
                session_regenerate_id((bool)$deleteOldSession);
            } catch (\PHPUnit_Framework_Exception $e) {
                var_dump($this->sessionExists());
                die();
            }
        }`

And it's outputting true.

The problem is coming from the adapter of ZfcUser (I stopped using this module, but adapter is left), [here](https://github.com/ZF-Commons/ZfcUser/blob/1.x/src/ZfcUser/Authentication/Adapter/Db.php) it has this regenerate session id: 

`// regen the id
        $session = new SessionContainer($this->getStorage()->getNameSpace());
        $session->getManager()->regenerateId();`

So the right solution here is to disable this for test environment?

**Comment by Naktibalda** [comment]
It is a solution that works.

One alternative I can imagine (but I've never used it myself), is to set `session.use_cookies` to 0 to avoid issues with cookies.
And please try to remove session_write_close from [ZF2::_after](https://github.com/Codeception/Codeception/blob/2.2.10/src/Codeception/Module/ZF2.php#L126) and see if it helps

**Comment by tasselchof** [comment]
> And please try to remove session_write_close from ZF2::_after and see if it helps

This helped. Maybe to make correction and remove this from codeception ZF2 module? I don't this session_close() is needed here.

**Comment by Naktibalda** [comment]
Does #1486 make sense to you?

@FnTm  Have you got any objections to reverting your change or alternative ideas for solving regenerateId issue?

**Comment by tasselchof** [comment]
I can't confirm #1486 - my application changing session configuration in module bootstrap (with standard config).

**Comment by FnTm** [comment]
@Naktibalda No objections from me, haven't been working with PHP for a couple of years now, so lost touch with the tools. Do what need to be done :)
