### ISSUE TITLE
AMQP methods without declared parameters are inconvenient to use

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#4139]
I have tried to use AMQP module today.
After typing `$I->declareExchange()` I discovered that it has no parameters.

Documentation states that
> This is an alias of method `queue_declare` of `PhpAmqpLib\Channel\AMQPChannel`.

And the code is simply 
```php
public function declareQueue()
{
    return call_user_func_array([$this->connection->channel(), 'queue_declare'], func_get_args());
}
```

This could be convenient for original developer of these methods, but it is very unfriendly to new users (like me).
It would be much more convenient to use if all parameters were declared.
#3988 @erikverheij

**Comment by erikverheij** [comment]
Hi Naktibalda, I used this approach to make sure this code doesn't need to be updated when the API of `PhpAmqpLib` changes. On the other hand our IDEs cannot provide meaningful suggestions / autocomplete. Perhaps you could file a PR to implement all of the arguments if you like to have this functionallity.

**Comment by Naktibalda** [comment]
#4156
