### ISSUE TITLE
$scenario->current('name') returns Null

### ISSUE THREAD

**Issue by Fuin** [Codeception/Codeception#4144]
In my StepObject I want to make a screenshot every time before I click on the login-Button for debugging reasons
I have several tests which are doing the login action so in order to get a screenshot for every single test and to know from which test that screenshot is I want to include the name of the test to the name
Currently it looks like this

```
$I = $this; 
$scenario = $I->getScenario();
 $name = $scenario->current('name');
 $I->makeScreenshot('login_Data_' . $name);

```

it looks like current('name') always returns NULL so the name is not added and the screenshot is getting overwritten every time a new one is taken.

**Comment by Naktibalda** [comment]
Try to use `$this->getMetadata()->getName()`

#3626

**Comment by Fuin** [comment]
It doesnt work, I get an exception 

[RuntimeException] Call to undefined method Step\Acceptance\Login::getMetadata

**Comment by Naktibalda** [comment]
OK, it is a good reason to fix it
