### ISSUE TITLE
When an unexpected exception occurs, no backtrace is available

### ISSUE THREAD

**Issue by mytskine** [Codeception/Codeception#4145]
I want to see where in my PHP code an unexpected exception occured.

When a test throws an unexpected exception, the test is immediately marked with E/Error, then at the bottom of the report, are displayed the scenario steps and the call trace. Unfortunately, the stack trace is totally irrelevant.

Sample result:
```
1) SessionCest: Check send messages
 Test  tests/functional/SessionCest.php:checkSendMessages

  [yii\base\ErrorException] Trying to get property of non-object  

Scenario Steps:

 7. $I->click("Send messages") at tests/functional/SessionCest.php:279
 6. [...]

#1  [...]/vendor/yiisoft/yii2/base/InlineAction.php:57
#2  [...]/vendor/yiisoft/yii2/base/InlineAction.php:57
#3  [...]/vendor/yiisoft/yii2/base/Controller.php:156
#4  [...]/vendor/yiisoft/yii2/base/Module.php:523
#5  [...]/vendor/yiisoft/yii2/web/Application.php:102
#6  [...]/vendor/symfony/browser-kit/Client.php:315
#7  [...]/backend/tests/_support/_generated/FunctionalTesterActions.php:919
#8  [...]/backend/tests/functional/SessionCest.php:279
```
There is no mention of the file where the exception occured, which is into `[...]/common/models/`.

I'm running Coception tests in Yii applications from the CLI codecept. As far as I know, Yii is only relevant because it converts PHP errors into exceptions.

I'll add a PR for this.

**Comment by Naktibalda** [comment]
Please run codeception with `-vvv` to get a full stacktrace.

**Comment by mytskine** [comment]
`-vvv` doesn't help, neither does `-d`. Sorry I forgot to mention this in the ticket.

Here is what I get with `-vvv`:
```
 I am on page ["\/session\/send-messages"]
  [Request Headers] []
 ERROR 

SessionCest: [...]
```
No stack trace of the exception in the upper part. At the end of the report, I get the same useless stack trace that does not relate to the real error.

In Codeception's source, the exception can be found with `FailEvent.getFail()` which is an Exception. But this exception's `getTrace()` is wrong, as displayed above. The right information is only in `getFile()` and `getLine()`. I don't know why the trace is wrong, it might be Yii2 or PHPUnit's doing.

**Comment by Naktibalda** [comment]
I think that this is a Yii specific issue.

**Comment by mytskine** [comment]
You're right, this is specific to Yii2. I just tried to reproduce it on a simple, non-Yii2 code, and the stack trace was right.

**Comment by Naktibalda** [comment]
@mytskine Since your issue is specific to Yii, solution affecting all exceptions is unnecessary.
How about implementing a Yii specific improvement in [Yii2 connector](https://github.com/Codeception/Codeception/blob/2.2.10/src/Codeception/Lib/Connector/Yii2.php#L140-L153)?

Catch `yii\base\ErrorException` and throw a better exception or add location to exception message.

**Comment by SamMousa** [comment]
I think nowadays the whole stacktrace is logged in debug output. This can be closed.
