### ISSUE TITLE
Multi Session Issue

### ISSUE THREAD

**Issue by yugenekr** [Codeception/Codeception#4157]
#### What are you trying to achieve?
In versions before 2.2.10 (sorry, don't have exact previous version number with working behavior), friends windows would be switched automatically, so all main actor window elements would become reachable after a friend has done the actions. Here's [an example](https://github.com/yugenekr/Codeception/blob/test-friends-issue/tests/web/FriendsCept.php) of what I mean - the last line is added to the current codeception test to show the desired (and previously working) functionality:
```php
$I = new WebGuy($scenario);
$I->wantTo('call friends to try multi session');
$I->amOnPage('/info');
$jon = $I->haveFriend('jon');
$jon->does(function (WebGuy $I) {
    $I->amOnPage('/');
    $I->seeInCurrentUrl('/');
});
$I->seeInCurrentUrl('/info');
$I->see('Don\'t do that at home');
```
The same behavior is shown in [the docs](http://codeception.com/docs/03-AcceptanceTests#Multi-Session-Testing)

#### What do you get instead?

```
1) FriendsCept: Call friends to try multi session
 Test  tests/web/FriendsCept.php
 Step  See "Don't do that at home"
 Fail  Failed asserting that  on page /info
--> Welcome to test app!
More info
Test Link
Test
Document-Relative Link
Some text with formatting
on separate lines
Link Text A wise man said: "debug!" Please don't provide us any personal information. Array ( )
--> contains "don't do that at home".

Scenario Steps:

 7. $I->see("Don't do that at home") at tests/web/FriendsCept.php:11
 6. $I->seeInCurrentUrl("/info") at tests/web/FriendsCept.php:10
 5. // --- JON FINISHED
 4. $I->seeInCurrentUrl("/") at tests/web/FriendsCept.php:8
 3. $I->amOnPage("/") at tests/web/FriendsCept.php:7
 2. // JON DOES ---
```

Now main actor window elements are reachable again if to add `$friend->leave()` before that, thus  in case it's needed, a friend has to be re-initialized again, which is not always convenient.

Is it an intentional behavior? Which way can browser windows be switched without making a friend to leave?

Thank you

**Comment by Naktibalda** [comment]
@DavertMik It looks like this issue was caused by your `performOn` change.
