### ISSUE TITLE
[SemaphoreCI] Run WebDriver tests using Selenium 3 

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#4161]
SemaphoreCI build runs WebDriver tests using selenium-server-standalone-2.51.0.
https://semaphoreci.com/codeception/codeception/branches/2-2/builds/393

It is time to upgrade and start using Selenium 3.

**Comment by nlubisch** [comment]
Im working with Selenium 3 right now with some simple tests and it works properly for my case!

**Comment by Zeika** [comment]
For last version of selenium try to use geckodriver
https://github.com/mozilla/geckodriver/releases
java -jar -Dwebdriver.gecko.driver=geckodriver selenium-server-standalone-3.3.1.jar

**Comment by DavertMik** [comment]
For all this evening I couldn't launch tests on Selenium + Geckodriver. 
Firefox + Selenium + Gecko look completely incompatible with each other.

Geckodriver v.0.15 can be used with Selenium 3.3.1 but not with 3.4
I tried different versions of gecko and seleniu but still no luck
probably I need firefox newer than 52.0.2 but I don't want to install it manually on CI server

**Comment by DavertMik** [comment]
I keep receiving this:

```
  [Facebook\WebDriver\Exception\UnknownServerException] setWindowRect
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'semaphore-1703', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-32-generic', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.j6toymLeqPMD, rotatable=false, timeouts={implicit=0.0, page load=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.0.1, platformVersion=3.13.0-32-generic, moz:processID=29531.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
Session ID: ea31a481-1397-49e4-91ba-0b15dc3978ea  
                                                                                                                                                                                                       
``````

while running latest Gecko driver (0.16.1) and Selenium 3.4.0 on Firefox 52.0.1

**Comment by DavertMik** [comment]
Selenium 3.3 with Geckodriver 0.15

```                                                                                                                                                      
  [Facebook\WebDriver\Exception\UnknownCommandException] mouseMoveTo
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'semaphore-1703', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-32-generic', java.version: '1.8.0_121'
Driver info: driver.version: RemoteWebDriver  
```

:angry: :angry: :imp: :angry:

**Comment by Naktibalda** [comment]
The same error happens with Selenium 3.4.1 and Geckodriver 0.16

Have you got a Chrome browser there?

**Comment by DavertMik** [comment]
Yes, but I think we still need to have Firefox tested :|

**Comment by Naktibalda** [comment]
It is an issue of Firefox.
I like Firefox as a user, but it is a regular PITA for testing.

Would it be possible to test old Firefox with Selenium 2 and new Chrome with Selenium 3 on separate builds?

**Comment by DavertMik** [comment]
This will require additional negotiations with Semaphore CI. I will try
