### ISSUE TITLE
MongoDB module legacy condition result is wrong

### ISSUE THREAD

**Issue by retnek** [Codeception/Codeception#4174]
If on the server installed both mongo extension (legacy mongo and mongodb) the legacy check condition returns true.

in Driver\MongoDb.php 98 line:
```php
$this->legacy = class_exists('\\MongoClient') && strpos(\MongoClient::VERSION, 'mongofill') === false;
```

I think should be better solution for test extension loaded state, something like this:
```php
$this->legacy = extension_loaded('mongodb') === false;
```

**Comment by Naktibalda** [comment]
Please make a pull request.
