### ISSUE TITLE
There is no _generated \ AcceptanceTesterActions file

### ISSUE THREAD

**Issue by Lipsec** [Codeception/Codeception#4176]
Hello! I do not have the AcceptanceTesterActions.php file. Can I generate it manually without using the "codecept build" command? I can not find the file for copying.

**Comment by Naktibalda** [comment]
Why can't you run `codecept build`?

Content of the file depends on enabled modules, you would have to create a wrapper for each method manually.

**Comment by Lipsec** [comment]
I'm afraid to break the existing settings.

**Comment by Naktibalda** [comment]
Make a backup before running it.

The only files overriden by `codecept build` are Actions files.
`codecept build` only creates `_support/AcceptanceTester.php` file if it doesn't exist yet.

**Comment by Lipsec** [comment]
Ok, thank you!
