### ISSUE TITLE
Undefined property: Codeception\Lib\Driver\MySql::$sqlToRun

### ISSUE THREAD

**Issue by karthikbadarinath** [Codeception/Codeception#4177]
#### What are you trying to achieve?
I was running some unit tests for our project with some new changes to the fixtures. If there is something wrong with it, I was expecting to show the actual query that caused the issue.

#### What do you get instead?
I am getting `Undefined property: Codeception\Lib\Driver\MySql::$sqlToRun`

#### Solution that I found
**Replace** 

```throw new ModuleException(__CLASS__, $e->getMessage() . "\nSQL query being executed: " . $this->driver->sqlToRun);```

**with** 

```throw new ModuleException(__CLASS__, $e->getMessage() . "\nSQL query being executed: " . implode("\n", $this->sql));```

in **src\Codeception\Module\Db.php** line no. 299. If you guys are OK with the solution, I could raise a PR

#### Output
```
1) FeedComponentTestCase: Invoke inventory
 Test  tests\unit\components\FeedComponentTestCase.php:testInvokeInventory

  [PHPUnit_Framework_Exception] Undefined property: Codeception\Lib\Driver\MySql::$sqlToRun

#1  C:\wamp\www\project_alpha\vendors\codeception\codeception\src\Codeception\Module\Db.php:299
#2  C:\wamp\www\project_alpha\vendors\codeception\codeception\src\Codeception\Module\Db.php:242
#3  Codeception\Subscriber\Module->before
#4  C:\wamp\www\project_alpha\vendors\symfony\event-dispatcher\EventDispatcher.php:174
#5  C:\wamp\www\project_alpha\vendors\symfony\event-dispatcher\EventDispatcher.php:43
#6  C:\wamp\www\project_alpha\vendors\phpunit\phpunit\src\Framework\TestResult.php:386
#7  C:\wamp\www\project_alpha\vendors\phpunit\phpunit\src\Framework\TestResult.php:628
#8  C:\wamp\www\project_alpha\vendors\phpunit\phpunit\src\Framework\TestCase.php:860
#9  C:\wamp\www\project_alpha\vendors\phpunit\phpunit\src\Framework\TestSuite.php:722
#10 C:\wamp\www\project_alpha\vendors\codeception\codeception\codecept:36
```
#### Details
```
* Codeception version: 2.2.10
* PHP Version: 5.6.16
* Operating System: Windows 10 / CentOS 7
* Installation type: Composer
```

**Comment by Naktibalda** [comment]
Thanks,

this issue is fixed already, but it hasn't been released yet #4120

**Comment by josephzidell** [comment]
I've seen this bug in the past

**Comment by josephzidell** [comment]
@Naktibalda what's the ETA on release date/schedule?

**Comment by Naktibalda** [comment]
This week.
