### ISSUE TITLE
Incorrect value of MongoDb database name

### ISSUE THREAD

**Issue by retnek** [Codeception/Codeception#4179]
When you are using the [MongoDb cloud](https://www.mongodb.com/cloud), may have more complex connection string than like this: `"mongodb://localhost:27017/mongo_test_db"`

If we have any option parameter in the dns, the dbName will be weird and unusable.
Example taken from the related [mongoDb documentation](https://docs.mongodb.com/manual/reference/connection-string/):
`mongodb://db1.example.net,db2.example.net:2500/somedb?replicaSet=test&connectTimeoutMS=300000` parses `somedb?replicaSet=test&connectTimeoutMS=300000` as a database name.

in Driver\MongoDb.php line 101
In my opinion would be something like this:
```php
$this->dbName = preg_replace('/\?.*/', '', substr($dsn, strrpos($dsn, '/') + 1));
```

**Comment by Naktibalda** [comment]
Fixed by #4186
