### ISSUE TITLE
tests run not sorted by suite naming

### ISSUE THREAD

**Issue by Faza-MBiZ** [Codeception/Codeception#4180]
#### What are you trying to achieve?
I am running codeception from inside a docker container of my application,

I need the test run to be ordered by suite names, eg:

```bash
$ ./vendor/bin/codecept config:validate
Available suites: 000_master, 001_user, 002_company, carts
Validating suite 000_master... Ok
Validating suite 001_user... Ok
Validating suite 002_company... Ok
Validating suite carts... Ok
```

#### What do you get instead?
instead codecept runs the unordered suites :

```bash
$ ./vendor/bin/codecept config:validate
Available suites: 002_company, carts, 001_user, 000_master
Validating suite 002_company... Ok
Validating suite carts... Ok
Validating suite 001_user... Ok
Validating suite 000_master... Ok
```

in codeception 2.0 there were sorting in place: https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/TestLoader.php#L115

but in 2.2.10 I see that the sortByName() were not called by Symfony\Component\Finder\Finder object at https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Configuration.php#L248

also in codeception 2.2 README.md it stated that there should be a 
> "TestLoader" as one of The most important classes where defined in root of Codeception.
but its not there.

i have created a pull request for this, 

### Details
* Codeception version: 2.2.10
* PHP Version: 7.0.17 (cli) (built: Mar 17 2017 22:53:03) ( NTS )
* Operating System: Linux 4.4.0-72-generic x86_64
* Installation type: Composer

**Comment by Naktibalda** [comment]
Test Loader is here: https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Test/Loader.php
