### ISSUE TITLE
HTML Report: Wrong number of failed scenarios

### ISSUE THREAD

**Issue by mpgo13** [Codeception/Codeception#4192]
#### What are you trying to achieve?

See correct number of failed scenarios: For two subsequential `canSee` fails, I expect that the report only counts it as one failure.

#### What do you get instead?

Too many failed scenarios

Reproducible Example:
```
class TestCest
{
    public function testA(AcceptanceTester $I)
    {
      $I->amOnUrl("http://www.google.com");
      $I->canSee("apple");
      $I->canSee("banana");
    }

    public function testB(AcceptanceTester $I)
    {
      $I->assertTrue(true);
    }
}
```

![image](https://cloud.githubusercontent.com/assets/1078584/25731708/01f05aa8-318c-11e7-8a5c-78f84deeaa22.png)

![image](https://cloud.githubusercontent.com/assets/1078584/25731716/17eb0614-318c-11e7-864d-e959c23be7fa.png)

### Details

* Codeception version: 2.2.10
* PHP Version: 7.0.17
* Operating System: Mac OS
* Installation type: Composer

**Comment by Naktibalda** [comment]
Many improvements to html report were made over 2 years.
Probably this issue was fixed.
