### ISSUE TITLE
page object vs g:scenarious

### ISSUE THREAD

**Issue by rebas82** [Codeception/Codeception#4204]
in my test, i use page objects.
when i doing:
codecept g:scenarios acceptance --format html

in output is only: I click "CrmCustomersPage::BUTTON_ADD"

It will be nice have in output: I click Add

**Comment by DavertMik** [comment]
Yes, probably. However, there are no active plans for the improvement of `generate:scenarios`
Use html reporter instead or send a Pull Request to make this enhancement.
