### ISSUE TITLE
[yii2] unloading fixtures only if `cleanup` configuration equals true.

### ISSUE THREAD

**Issue by Faryshta** [Codeception/Codeception#4207]
#### What are you trying to achieve?

after setting up `cleanup: false` configuration for the yii2 module still unloads fixtures and that might cascade on other operations

```php
$I->haveFixtures(['store' => StoreFixture::class]);
$model = new Sale(['store_id' => 1]);
$this->assertTrue($model->save());
```

I expect that sale to be available after the test ends to be handled on other tests.

#### What do you get instead?

The fixtures always unload after every test so it means any foreign key will either cascade the delete to the store record or throw a db exception.

* Codeception version: 2.2.6 exact commit https://github.com/Codeception/Codeception/commit/080dba649f5dc0f4defa326b0e237a9aa084ad99#diff-938f756d763fc21aace78bb43ea26870R154

`$fixture->unloadFixtures();` must only be called if `$this->config['cleanup']` equals true.

**Comment by samdark** [comment]
@Faryshta how about a pull request?
