### ISSUE TITLE
How to use phpunit.xml 

### ISSUE THREAD

**Issue by coooooder-luo** [Codeception/Codeception#4215]
#### i want set ‘convertNoticesToExceptions’ and  ‘convertWarningsToExceptions’ but can't work
now i wnat use phpunit.xml in codeception
how to use it?
i can't find in docs [http://codeception.com/docs/05-UnitTests](codeception) 
😢  hope you can help me  , and thanks you 

1. set codeception.yml settings:
```bash
...
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    convertWarningsToExceptions: false
    convertNoticesToExceptions: false
...
```
and run

```
codecept build
codecept run unit
```
my test code :
```php
$arr = [0];
$I->assertEmpty($arr[1]);
```
outputs:
```
[PHPUnit_Framework_Exception] Undefined offset: 1
ERRORS!
Tests: 1, Assertions: 1, Errors: 1.
```

* Codeception version: 
* PHP Version: 5.6.12
* Operating System:windows
* Installation type: Composer

**Comment by Naktibalda** [comment]
phpunit.xml isn't used by Codeception, these options would have to be implemented as Codeception options, but I don't think that they will ever be, because they encourage sloppy coding.

**Comment by coooooder-luo** [comment]
ok , i got it.
this phenomenon exists in my project.
how to ignore them ?? (Notice, Warning Level)
ps: i like codeception and i want to use it in  my project. 😃

**Comment by Naktibalda** [comment]
Write a more defensive code, put `$I->assertArrayHasKey(1, $arr);` before `assertEmpty`.

Use `if (isset(...))` and/or `if (array_key_exists(...))` in your application code.

**Comment by coooooder-luo** [comment]
thx.. :handshake: 
my application has too many "sloppy coding"   😂 
may be i can use codeception in another application.

have a nice day!

**Comment by exteon** [comment]
I too wasted 6 hours of my day to find codeception doesn't support this. Disappointingly, I find out a testing framework cannot be used to test sloppy code. Ironical, isn't it. I just wished you had put this evangelism in bold in the documentation... "Do not use this tool to help rewrite sloppy code, you can only use it afterwards". Rhetorical question: if I am to rewrite my code to not generate notices, evangelism says I should use an automated testing tool and throw in some minimal tests to make sure I don't break anything in the process of rewriting everything. Which one not to use?

**Comment by Naktibalda** [comment]
@exteon try to use error_level configuration parameter: https://codeception.com/docs/04-FunctionalTests#Error-Reporting

**Comment by exteon** [comment]
I take back my rant; I only wish it popped out more in the documentation. I had already found it in the code. Speaking of sloppy coding: error_level: 0 won't work because of the boolean test on error_level.
