### ISSUE TITLE
End test printer event is not called if previous test failed

### ISSUE THREAD

**Issue by SvetlanaZem** [Codeception/Codeception#4223]
1) Create test suite where the first test will fail with `cURL error 7: Failed to connect to localhost port 80: Connection refused`, because no web server is running.

```
<?php
class MyPageCrudCest
{
    function viewPage(AcceptanceTester $I)
    {
        $I->amOnPage('/test.php');
    }

    function updatePage(AcceptanceTester $I)
    {
        // empty test
    }
}
```

2) Implement custom ResultPrinter and override `startTest` and `endTest` methods.
```
class PhpStorm_Codeception_ReportPrinter extends PHPUnit_TextUI_ResultPrinter
{
    public function startTest(PHPUnit_Framework_Test $test)
    {
        $testName              = \Codeception\Test\Descriptor::getTestAsString($test);
        $this->write("\nSTARTED: $testName\n");
    }

    public function endTest(PHPUnit_Framework_Test $test, $time)
    {
        $testName              = \Codeception\Test\Descriptor::getTestAsString($test);
        $this->write("\nENDED: $testName\n");

    }
}
```

3) Execute tests with custom result printer.

I expect to see both tests started and ended
```
STARTED: MyPageCrudCest: View page

ENDED: MyPageCrudCest: View page

STARTED: MyPageCrudCest: Update page

ENDED: MyPageCrudCest: Update page
```

#### What do you get instead?
The second test is started but not ended.
```
STARTED: MyPageCrudCest: View page

ENDED: MyPageCrudCest: View page

STARTED: MyPageCrudCest: Update page
```

### Details

* Codeception version: 2.2.11 (the issue is not reproducible with 2.2.10)
* PHP Version: 7.1.1
* Installation type: Composer

**Comment by Naktibalda** [comment]
Does it even run the second test?

Probably this issue was caused by d24aa1e4f66d5165ece1efe0f7c44ba044d5e34a.

I have very limited time to work on Codeception (and a lot more to support it online), but I will try to look into this issue tonight.

**Comment by SvetlanaZem** [comment]
@Naktibalda You are right, it looks like the second test is not executed at all.
