### ISSUE TITLE
Automatic scrollTo?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4231]
Following up on https://github.com/Codeception/Codeception/issues/2840 I'm wondering if it would be possible to add the `scrollTo` action automatically to the `click` action, if necessary?

The current status is that `scrollTo` is implemented (see other issue), but you have to call it manually each time when clicking an element below the fold, right?
````php
$I->scrollTo($button);
$I->click($button);
````
So what I'm suggesting is to perform a check for "clickability" on each call of `click`, and in case, call `scrollTo` with the same selector used for `click`.

This shouldn't harm anybody, since I can't see any reason why a user would deliberately want to click on an element which is not clickable...

**Comment by Naktibalda** [comment]
Use [clickWithLeftButton](clickWithLeftButton) method instead.
It moves mouse the the target element before clicking it.

**Comment by ThomasLandauer** [comment]
Sounds good, but I'm getting this error:  
`[Facebook\WebDriver\Exception\UnknownCommandException] mouseMoveTo`

**Comment by Naktibalda** [comment]
Are you using Firefox?

**Comment by ThomasLandauer** [comment]
Yes. But I just checked with Chrome: No error, but the element isn't scrolled into view (i.e. not the button gets the click, but an overlay toolbar).

**Comment by Naktibalda** [comment]
If you want to modify a method, modify `clickWithLeftButton`, not `click`.
 But please add a failing test to https://github.com/Codeception/Codeception/blob/2.2/tests/web/WebDriverTest.php first.

**Comment by DavertMik** [comment]
> So what I'm suggesting is to perform a check for "clickability" on each call of click, and in case, call scrollTo with the same selector used for click.

Every WebDriver command takes its time, so adding useless check can slow down tests. Especially if it happens to such common action like `click`.

**Comment by ThomasLandauer** [comment]
OK, I see your point. So what's the current best-practice for dealing with "sticky" navbars, like e.g. mentioned here?: http://stackoverflow.com/questions/23458359/codeception-acceptance-test-fails-because-of-bottom-navigation

**Comment by DavertMik** [comment]
By using `scrollTo`, I guess

**Comment by ThomasLandauer** [comment]
I just created a test for the "sticky bar" issue. The test is failing with Firefox (i.e. wrong link gets actually clicked). In Chrome, the test gives an error:

>  Element ... is not clickable at point (101, 618). Other element would receive the click:

Do you know how I can commit it directly from NetBeans? Do I have to create a branch of my repository on GitHub first (something like `ThomasLandauer:patch-6`)?

**Comment by Naktibalda** [comment]
Create a branch in your local working copy and push it to your fork.

**Comment by ThomasLandauer** [comment]
Thanks! I hope it worked ;-) See https://github.com/Codeception/Codeception/pull/4248

**Comment by voku** [comment]
@ThomasLandauer I have the same problem currently with Chromium 77 + Codeception 3.1.2 ... How did you solve the problem?

**Comment by XedinUnknown** [comment]
Also having this problem. Scrolling needs to happen not only on `click()`, but on all interactions with UI elements, like `checkOption()` or `fillField()`. Is there any way to do that now?
