### ISSUE TITLE
JsonPath fails in 2.2.12

### ISSUE THREAD

**Issue by garyblankenship** [Codeception/Codeception#4237]
#### What are you trying to achieve?
JsonPath related method failing in codecept 2.2.12, working in 2.2.11.

#### What do you get instead?
See output below.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 Step  Don't see response json matches json path "$.error"
 Fail  JSON response is not an array: true
```
> Provide test source code if related
Response: true

```php
$I->dontSeeResponseJsonMatchesJsonPath('$.error');
```
### Details

* Codeception version: 2.2.12, flow/jsonpath 0.3.4
* PHP Version: 7.1
* Operating System: linux
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
Does your API actually return `true`?

**Comment by garyblankenship** [comment]
for this specific endpoint it does, yes.

**Comment by Naktibalda** [comment]
OK, so more specifically this issue affects `dontSeeResponseJsonMatchesJsonPath` and `dontSeeResponseMatchesJsonType` when response is a scalar value.

**Comment by Naktibalda** [comment]
@garyblankenship thanks for early warning, 2.2.12 wasn't out yet when you raised this issue.
