### ISSUE TITLE
Explain more questions in the docs

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4238]
I have some questions, to which I can't find an answer. If you help me in finding answers, I'll include them in the docs:

1. Selenium: Is it possible to reuse a browser window? (i.e. prevent Selenium from opening a new window for each test)
1. PhantomJS: How can you get some information about the page that PhantomJS really "sees"? Is there a way to "log" something to the Codeception output (i.e. terminal window)? Screenshot kinda works, but I'm wondering if there is an easier way...
1. Is it possible to check if an element has focus? See https://stackoverflow.com/questions/44096567/codeception-check-if-element-has-focus/
1. What's the way to go if a page contains some JavaScript (i.e. acceptance test), but I also need to check what's going on in the database (i.e. functional test)?

Thanks! :-)

**Comment by Naktibalda** [comment]
1. set `restart: false` - http://codeception.com/docs/modules/WebDriver#Configuration
2. Use Recorder extension - http://codeception.com/extensions#CodeceptionExtensionRecorder
3. I don't know, check if facebook php-webdriver can do that, or if there is a javascript code which can do that.
4. Db module

**Comment by ThomasLandauer** [comment]
Thanks!

* ad 1. OK, but it's not possible to leave the window open when all tests are finished an re-use it for the next `codecept run`?

* ad 1. Is there a specific reason why it's set to `false` for the internal tests?: https://github.com/Codeception/Codeception/blob/2.2/tests/web.suite.yml#L9

* ad 2. See https://github.com/ThomasLandauer/Codeception/commit/9f0c75b94a64d84b90ab28bc9b7aa6fb176148f9 and https://github.com/ThomasLandauer/Codeception/commit/733c79725493bd55932ed84ca1bb1421204c6068  
Other than that, there's no way to log/output something?

* ad 3. Is PhantomJS also using [facebook/php-webdriver](https://github.com/facebook/php-webdriver)? Or just Selenium?

* ad 4. See https://github.com/ThomasLandauer/Codeception/commit/228b538cf90ed83d459ce99f34818e42ec2c299f

**Comment by Naktibalda** [comment]
2. What else do you want to log?
3. It is another way around, php-webdriver talks to Selenium (and to PhantomJS which implements Selenium API).

**Comment by ThomasLandauer** [comment]
2. It looks like PhantomJS gets stuck on some error in my JavaScript. Is there a way to debug this, or find the error?
3. OK, so it's either:
    `Codeception -> facebook/php-webdriver -> PhantomJS`
    or
    `Codeception -> facebook/php-webdriver -> Selenium`
    But never:
    `Codeception -> facebook/php-webdriver -> Selenium -> PhantomJS`
    Right?

**Comment by ThomasLandauer** [comment]
3. The answer must be YES, since you can't run both Selenium Server and PhantomJS simultaneously :-) So if I'm just using PhantomJS, I don't even have to install Selenium Server?  
I keep wondering why you always call it "*Selenium* WebDriver"...  
I'm going to edit the docs to make it clear that for Selenium and PhantomJS it's an **OR** and not an **AND** :-)

**Comment by Naktibalda** [comment]
`Selenium WebDriver` is a thing: http://www.seleniumhq.org/projects/webdriver/

**Comment by DavertMik** [comment]
> OK, but it's not possible to leave the window open when all tests are finished an re-use it for the next codecept run?

No

>  Is there a specific reason why it's set to false for the internal tests?: https://github.com/Codeception/Codeception/blob/2.2/tests/web.suite.yml#L9

To isolate test cases from each other.

> So if I'm just using PhantomJS, I don't even have to install Selenium Server?
I keep wondering why you always call it "Selenium WebDriver"...

So the answer is:

* WebDriver is a protocol for interacting a browser
* ChromeDriver, GeckoDriver implements WebDriver
* Selenium is a server implementing this protocol shares this across different browsers

**Comment by ThomasLandauer** [comment]
OK, so it's?:
`Codeception -> facebook/php-webdriver -> Chrome/Gecko Driver -> Selenium Server`

And:  
`Codeception -> PhantomJS`? So there's no facebook/php-webdriver or any other "translator" involvedin this case?

**Comment by ThomasLandauer** [comment]
Just did some housekeeping of all my pull requests ;-) I'm collecting all open questions here:

1. If Firefox doesn't work (see https://github.com/Codeception/Codeception/pull/4233#issuecomment-303247954 ), wouldn't it be better to change the browser to Chrome here: https://github.com/Codeception/Codeception/blob/2.3/tests/web.suite.yml#L7

1. Do you have an URL for the glue framework?

1. What does this mean (on https://github.com/Codeception/Codeception/blob/2.3/tests/README.md ):
    > For regression testing, and real world HTML page examples that you can add a html page into `tests/data/app/view/form/exampleX.php` file and add its name to routes.

1. Following up on https://github.com/Codeception/Codeception/pull/4236/commits/733c79725493bd55932ed84ca1bb1421204c6068#r117868990  
Well, to me it's confusing to have one part of the docs living in `.md` files, and another part living in `.php` files!  
But if you don't want to change this: Could you at least include a (large) warning at the top of all files like ` Codeception/docs/modules/WebDriver.md`, explaining that it's not a good idea to edit them, since they are generated from their `.php` source?

1.  What does this mean on http://codeception.com/docs/modules/Db   
    > That's why this module was added to the global configuration file `codeception.yml`. To have your database properly cleaned you should configure it to access the database.
    
    Do you mean: Configuration has to be done in `codeception.yml`? Or that it's enabled by default (was not the case for me!)?

**Comment by Naktibalda** [comment]
> Codeception -> PhantomJS? So there's no facebook/php-webdriver or any other "translator" involved in this case?

facebook/php-webdriver is still there, PhantomJS replaces `Selenium Server -> Chrome/Gecko Driver -> Browser` part, because it is a browser which acts as a Selenium server when launched using `--webdriver` option.

1. Related ticket https://github.com/Codeception/Codeception/issues/4161
2. This? https://github.com/Codeception/Codeception/blob/2.3/tests/data/app/glue.php
5. There used to be a configuration section for Db module in generated codeception.yml file, but @DavertMik removed it few months ago.

**Comment by Naktibalda** [comment]
`3.` I don't know what that sentence means, but it is easier to add a new view file to form directory than to it's parent, because it isn't necessary to create a route and a controller class.

**Comment by ThomasLandauer** [comment]
PhantomJS: Oh boy, I thought I had it ;-)  
So correct is: `Codeception -> facebook/php-webdriver -> PhantomJS`?  
So Selenium and PhantomJS both offer the same API, called "Selenium Webdriver". And facebook/php-webdriver is a translator between PHP (=Codeception) to this API? => Is that it??

1. I saw the ticket :-) So you mean we should wait what the outcome is there?

2. I wanted to add a link for "glue microframework", to maybe find some docs about routing parameters etc. Is this single .php-file the entire framework? Where did you grab it from?

3. I deleted it, see https://github.com/ThomasLandauer/Codeception/commit/59fdfe4040b2025d0960664518d73031d3dd4f80

5. I deleted it, see https://github.com/ThomasLandauer/Codeception/commit/c4c96d3d76a67b58102dc5c88512244dde89383c

**Comment by ThomasLandauer** [comment]
* Could you give me a hint on that?: https://github.com/Codeception/Codeception/issues/4231#issuecomment-303144413  
    I've cloned Codeception/Codeception into NetBeans, modified some files - and now I'm stuck :-(

**Comment by ThomasLandauer** [comment]
Another question:

1. "General" methods like `wantTo` are documented nowhere? I think there should be a dedicated page for these in the docs.

1. Am I right that Codeception cannot be run without any module? The framework itself brings just some "lightweight" functionality, the real power is in the modules?
