### ISSUE TITLE
Suggestion: Write $I in lowercase: $i

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4256]
I suggest changing all code examples to writing`$i` instead of `$I`.

Advantages of lowercase `i`:

1. Easier to read: `I` might be misread as lowercase `L` or roman numeral for 1.
2. Easier to type: No shift-key required
3. `$i` follows camelCase rules, `$I` doesn't. camelCase is the de-facto standard for PHP, even on the PSR-2 page, all variables are written in camelCase, see http://www.php-fig.org/psr/psr-2/

In contrast, I can't see any advantage of uppercase `$I`.

**Comment by Naktibalda** [comment]
`I` means `me`, `i` is just a bad naming.

**Comment by DavertMik** [comment]
Because in English a sentence starts with a capital letter.
And Codeception is about writing readable code.

But sure, if PSR-2 matters more to you, you can use `$i`. However, we will use `$I` as default

**Comment by ThomasLandauer** [comment]
Sorry, but the english sentence argument doesn't make any sense. There's absolutely no way you can justify the upper/lower-case of `amOnPage` (and all other methods) with english language rules.

So the relevant reference is not natural language, but other PHP code. And in this regard Codeception is the only library (that I know of) that uses upper case variables.
