### ISSUE TITLE
Wrong documentation of InnerBrowser::haveHttpHeader()

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4257]
See https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Lib/InnerBrowser.php#L283

The function is called `haveHttpHeader()`, but the example in the code block reads:
```php
$I->setHeader('X-Requested-With', 'Codeception');
```

I don't change anything, since I don't know what the intended name is. But I must say that `haveHttpHeader()` is a **really bad** name for an action, cause "have" sounds like an assertion! Any name starting with "set" is certainly better.

**Comment by Naktibalda** [comment]
In Codeception assertions start with `see`,
`have` methods are used to setup preconditions.

Another example is [Db::haveInDatabase](https://github.com/Codeception/Codeception/blob/2.3.1/src/Codeception/Module/Db.php#L397)

**Comment by DavertMik** [comment]
We have another strange naming which is `expect`, you expect this to be assertion but it is a comment :laughing: :rofl: #self-irony

But for `have` it's totally fine as it describes what you have in the beginning. For preconditions we use 2 prefixes: `have` and `am`, so ths scenario would follow Arrange-Act-Assert syntax:

```php
// arrange
$I->haveUser('davert');
$I->haveProduct('iPhone');
$I->amLoggedAsAdmin();
$I->amOnPage('/users/davert');

// act
$I->click('Add Product');
$I->selectOption('iPhone');

// assert
$I->see('iPhone', '.products');
```

Something like that

**Comment by ThomasLandauer** [comment]
Please fix the **error** that I mentioned in the first sentence!

For the question if "have" and "expect" are good names, I'll start a new issue :-)

**Comment by ThomasLandauer** [comment]
Was fixed with https://github.com/Codeception/Codeception/pull/4347
