### ISSUE TITLE
Add assertion to check HTTP headers

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4258]
I can't find any assertion to check if an HTTP header has an expected value in a functional test.

In a PHPUnit test that extends Symfony's `WebTestCase`, you can do:
```php
$this->assertTrue(
    $client->getResponse()->headers->contains(
        'Content-Type',
        'text/javascript; charset=UTF-8'
    )
);
```

I can't even find a method to get the full HTTP response. Since the PhpBrowser Module uses Guzzle, it should be possible to implement something like `getResponse()`?

**Comment by Naktibalda** [comment]
You could use [REST module](http://codeception.com/docs/modules/REST#seeHttpHeader) for that.
Don't forget to configure it with:
```
REST:
  depends: Symfony
```

**Comment by ThomasLandauer** [comment]
Thanks, I'll take a look!

But I have a general question in advance: Can you combine any module with any other? Don't some of them have the same methods, so that they'd override each other? => This should be explained somewhere :-)

**Comment by Naktibalda** [comment]
No, only some modules, like REST and Doctrine can depend on others to get their work done.
There is a ConflictsWithModule interface too, so you can't have WebDriver and some framework module enabled at the same time, and you can't have two framework modules enabled.
Also REST conflicts with SOAP.

It's documented somewhere.

**Comment by ThomasLandauer** [comment]
> It's documented somewhere.

Well, that's not the best sign, if not even you do know where that documentation is ;-)

Seriously, @DavertMik I'd suggest to add a new section to every module's documentation, namely "Compatible with", followed by a bulleted list of compatible modules, with links to them. Can/will you invent a system that somehow generates this list automatically? Or should I start manually?

I would locate it between the "Status" and the "Config" section.

BTW: Is "Status" really necessary anymore? As far as I can see, most are stable anyway. All others could include a red warning bar at the top. Then "Status" could be renamed to "Maintainer" and moved to a sidebar.

**Comment by Naktibalda** [comment]
What do you mean by "compatible"? That they do not conflict?

**Comment by ThomasLandauer** [comment]
Yes.

**Comment by Naktibalda** [comment]
That's the default relation between modules.
There are only 2 groups of modules that conflict:
a) framework modules + WebDriver.
b) REST with SOAP.

All other combinations are allowed.

**Comment by ThomasLandauer** [comment]
Well, if it's that easy, I'll do it manually :-) See https://github.com/Codeception/Codeception/pull/4266/commits/694e5c40e9cd3f4bfcf122b77e3d95a86802f4d3 for an example. Any objections anybody? ;-)

But while I'm at it, I'd also like to include the info, for which suite the module is meant. Let me guess: The framework modules for `functional.suite.yml` only? And the others?

**Comment by Naktibalda** [comment]
I think that this commit is completely unnecessary, because it generally doesn't make sense to enable 2 framework modules at the same time.
In theory it is possible to run the same tests with framework module and WebDriver. But I don't use WebDriver, so I've never done that. I've seen a ticket opened by person who was having difficulties few weeks ago, probably it is still open.
However I created a test suite for webservice implemented using one framework and then switched to another.

Yes, the distinction between acceptance and functional is that acceptance should be using WebDriver or PhpBrowser and functional - framework module. Both can have any other modules enabled. Unit suite shouldn't use any modules other than Asserts, but Asserts isn't necessary in Unit format.

**Comment by ThomasLandauer** [comment]
I'm not sure we're talking about the same thing. Do you mean this commit?: https://github.com/Codeception/Codeception/pull/4266/commits/694e5c40e9cd3f4bfcf122b77e3d95a86802f4d3

=> The important message is that you can combine it with all other modules, like Asserts or Doctrine. I certainly don't want to talk anybody into using two framework modules in parallel! Did I create that impression anywhere?

Thanks for the rest, but this part I don't understand: "but Asserts isn't necessary in Unit format". There's no need to activate the Asserts module in `unit.suite.yml`?

**Comment by Naktibalda** [comment]
Unit format extends PHPUnit_Framework_Testcase so it inherits all Phpunit assertions.

Yes, it's the same commit. I don't like `This module is compatible with all other Codeception modules, except` bit because I think that it is backwards, like adding `at peace with` paragraph to pages of all countries in Wikipedia.

**Comment by ThomasLandauer** [comment]
Yeah, you're right. I don't like that too. But what do you suggest? Right now, there are 31 modules. Do you want to explicitely list every ~26 to which the current module *is* compatible?

**Comment by Naktibalda** [comment]
No, that's what you wanted originally.
I think that `conflicts with` should be enough for modules that have conflicts. It could come with explanation why these modules have conflict.

**Comment by ThomasLandauer** [comment]
Well, "conflicts with" is basically the same as "compatible with all except" - what follows is a list of non-compatible.  
But OK. There are more important things than that - so let's not discuss this forever. I'll come up with a general explanation of the module system (somewhere in Introduction or so), and include some sentence like: "In general, all modules are compatible with each other. If not, it's explained on the module page."
