### ISSUE TITLE
Easy way to set `HTTP_HOST` for functional tests with symfony missing.

### ISSUE THREAD

**Issue by c33s** [Codeception/Codeception#4260]
#### What are you trying to achieve?
i am trying to functional test a symfony application where the routes only listen to specific domains, lets say `example.com`. i simply want to run `$I->amOnPage('/');` and get the 

symfony2 routing.yml
```
mybundle:
    resource: "@MyBundle/Resources/config/routing.yml"
    host: example.com
```
#### What do you get instead?
so a `$I->amOnPage('/');` leads to a 404 because it is accessed with `http://localhost`.

### What i found out
as workaround i can change all urls to also listen to localhost.

```
mybundle:
    resource: "@MyBundle/Resources/config/routing.yml"
    host:     "{hostname}"
    defaults: { hostname: example.com }
    requirements:
        hostname:     example.com|localhost
```
which is a little bit overkill to do this for all routes and maybe also have negative sideeffects.

the correct solution for the symfony browser would be setting the `HTTP_HOST`:

https://stackoverflow.com/a/10677520
```
class AgencyControllerTest extends WebTestCase
{
    public function testShowFoo()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/', array(), array(), array(
            'HTTP_HOST'       => 'foo.domain.dev',
            'HTTP_USER_AGENT' => 'Symfony/2.0',
        ));

        $this->assertGreaterThan(0, $crawler->filter('html:contains("Text of foo domain")')->count());
    }
}
```

searching this repo i found that the yii framework had a similar issue, which was fixed:

https://github.com/Codeception/Codeception/pull/2350/files
```
     public function _createClient()
     {
         $this->client = new Yii1Connector();
+        $this->client->setServerParameter("HTTP_HOST", parse_url($this->config['url'], PHP_URL_HOST));
         $this->client->appPath = $this->config['appPath'];
         $this->client->url = $this->config['url'];
         $this->client->appSettings = [
```

so it looks like this is done somewhere here for symfony as the `SymfonyConnector` extends `\Symfony\Component\HttpKernel\Client`:
https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Module/Symfony.php#L185
```
    /**
     * Initialize new client instance before each test
     */
    public function _before(\Codeception\TestInterface $test)
    {
        $this->persistentServices = array_merge($this->persistentServices, $this->permanentServices);
        $this->client = new SymfonyConnector($this->kernel, $this->persistentServices, $this->config['rebootable_client']);
    }
```
for now i havn't found/verified the exact location where same client as in the `WebTestCase` is created.

if i set the url in `functional.suite.yml` under  `Symfony2` i would assume it sets the `HTTP_HOST` but it does nothing.
```
actor: FunctionalTester
modules:
    enabled:
        - Symfony2:
#            url: 'http://example.com/'
```
also tried 
```
        - PhpBrowser:
            url: 'http://example.com'
```
but this only leads in accessing the real webserver or the local webserver if i use a domain which points to localhost.

what helps is using a similar helper descibed in https://github.com/Codeception/Codeception/issues/2717#issue-126400964

Functional.php
```
<?php
namespace Helper;

class Functional extends \Codeception\Module
{
    public function setHost($host)
    {
        $this->getModule('Symfony2')->client->setServerParameter('HTTP_HOST', $host);
    }
```
```
<?php

/**
 * @group frontpage
 */

class BasicCest
{
    public function _before(FunctionalTester $I)
    {
        $I->setHost('example.com');
    }
```

but doing this for each cest is not that what i am looking for, i would like to set it globaly.

adding it to the frontpage group `_before` also doesn't work, because the client is not initialized yet:

```
<?php
namespace Group;

use \Codeception\Event\TestEvent;

class Frontpage extends \Codeception\Platform\Group
{
    public static $group = 'frontpage';

    public function _before(TestEvent $e)
    {
        $this->getModule('Symfony2')->client->setServerParameter('HTTP_HOST', 'example.com');
    }
}
```

as i said i would wish to simply set the url setting for my symfony module so it correctly sets the `HTTP_HOST` for the client.

if i missed something in the docs, please point me the way, it this is currently not possible, i would be happy to see this feature soon in codeception

### Details

* Codeception version: 2.3.1
* PHP Version: 7.1.4
* Operating System: Windows 
* Installation type: Phar

**Comment by Naktibalda** [comment]
Have you tried to use `$I->amOnPage('http://example.com');`?

**Comment by c33s** [comment]
@Naktibalda 
no havn't tried it. yes this works.
from the testing point of view it feels more explicit to use ``$I->amOnPage('http://example.com'); from the UX view i would prefer to set it globally, from the UX and consistency point of view it looks odd that i can set it for yii but can't set it for symfony.

**Comment by Naktibalda** [comment]
Parameters are module specific, so somebody would have to add a `url` parameter to `Symfony` module and all other framework modules separately.

**Comment by c33s** [comment]
can you point me the way where these parameters are set and where the parameters are assigned to the symfony crawler?

**Comment by Naktibalda** [comment]
I don't know anything about `Symfony\Component\HttpKernel\Client`.

Laravel connector uses it too and it implements url parameter, look at Laravel [connector](https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Lib/Connector/Laravel5.php#L79-L85) and module to see how it is implemented.

**Comment by c33s** [comment]
thanks for the hints, i had a look at it and i should be able to add this feature.

but i will be able to start at the earliest in 6 weeks time. will you accept a PR?

some notes i made for myself and for the interested:

createClient -> Test Client //symfony createClient static method
Symfony\Bundle\FrameworkBundle\Client extends BaseClient 
BaseClient -> Client
Symfony\Component\HttpKernel\Client  extends BaseClient
BaseClient -> Client
Symfony\Component\BrowserKit\Client
```
    public function setServerParameters(array $server)
    public function setServerParameter($key, $value)
    public function getServerParameter($key, $default = '')
```

https://symfony.com/doc/current/testing.html
```
$client = static::createClient(array(), array(
    'HTTP_HOST'       => 'en.example.com',
    'HTTP_USER_AGENT' => 'MySuperBrowser/1.0',
));
```
->
adapt symfony connector
https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Lib/Connector/Symfony.php

constructor of symfony connector similar to laravel connector
```
        $components = parse_url($this->app['config']->get('app.url', 'http://localhost'));
        if (array_key_exists('url', $this->module->config)) {
            $components = parse_url($this->module->config['url']);
        }
        $host = isset($components['host']) ? $components['host'] : 'localhost';
        parent::__construct($this->app, ['HTTP_HOST' => $host]);
```

after parent:construct
```
$this->setServerParameter('HTTP_HOST', $urlFromConfig)
```
or
```
$this->setServerParameters($fullConfigArray)
```

maybe add `server` to the symfony module config, so every server options can be set from the config.

**Comment by krukru** [comment]
@c33s you said that you can change the host for Yii2, but I am having trouble finding out how to do so. Could you help me out?

**Comment by c33s** [comment]
@krukru should be automatically be pulled from the config. from the code i quoted above i assume it is simply the `url` from the config.

`functional.suite.yml`
```
modules:
    enabled:
        - Symfony2:
            url: 'http://example.com/'
```
in symfony this value is not passed to the client. in the code i quoted above it looks like this value is also set as host for the client used in the yii framework. so it should work by simply setting the `url` value

**Comment by rajkumar7it74** [comment]
Hi, can I use PHP variable or PHP constant (having url value) in place of url. I want that it should automatically picked the value from Environment variables. 

Thanks

**Comment by c33s** [comment]
@rajkumar7it74 maybe you should open a different issue. maybe something like "use environment variables in config".

**Comment by c33s** [comment]
@rajkumar7it74 
is that what you need? http://codeception.com/03-05-2016/codeception-2.2.-upcoming-features.html
according this post codeception is already able to use environment variables for config.

> Codeception 2.2 will allow you to use parameter in configuration files populated from environment variables, yaml configs or .env files. You can use parametrized vars in suite configs, by wrapping them in % placeholder, and adding one or several parameter providers using the params key in global config

**Comment by izac1** [comment]
At Yii2 dont grap HTTP_HOST from config , only can set this var. on _bootstrap.php

**Comment by Naktibalda** [comment]
I think that it is no longer possible to set HTTP_HOST in any modules after recent symfony/browserkit updates. There was a related ticket somewhere.

**Comment by c33s** [comment]
> There was a related ticket somewhere.

@Naktibalda  would be nice to link such a ticket and post the parts here why it is not possible any more

**Comment by Naktibalda** [comment]
#1650

**Comment by c33s** [comment]
https://github.com/symfony/symfony/pull/26244

**Comment by c33s** [comment]
@Naktibalda  is this the right PR which is resulting in the break, i posted above?

**Comment by Naktibalda** [comment]
Yes

**Comment by c33s** [comment]
@Naktibalda maybe you want to add some info/thoughts to https://github.com/symfony/symfony/issues/32791

**Comment by toby-griffiths** [comment]
Anyone coming across this, you can resolve this by adding a custom helper to add the host header before each test…

```php
<?php

declare(strict_types=1);

namespace App\Tests\Support\Helper;

use Codeception\Module\Symfony;
use Codeception\TestInterface;

class DynamicHosts extends \Codeception\Module
{
    protected array $requiredFields = ['host'];


    public function _before(TestInterface $test)
    {
        $symfonyModule = $this->getModule('Symfony');
        assert($symfonyModule instanceof Symfony);

        $symfonyModule->haveHttpHeader('host', $this->config['host']);
    }
}
```

```yaml
actor: ApiTester
modules:
    enabled:
        - Asserts
        - REST:
              depends: 'Symfony'
              url: '/api'
              shortDebugResponse: 300
        - Symfony:
              app_path: 'src'
              environment: 'test'
        - '\App\Tests\Support\Helper\DynamicHosts':
              host: 'custom.host.com'

**Comment by c33s** [comment]
@toby-griffiths thanks for your neat code! researching how to do that with the current symfony and codeception versions was on my todo list. your post was very welcome :D

my adption of  your code into an `$I->amOnHost()` method:

`tests/_support/Helper/Functional.php`:
```php
<?php

namespace Tests\Helper;

use Codeception\Module\Symfony;

class Functional extends \Codeception\Module
{
    public function amOnHost(string $host): void
    {
        $symfony = $this->getModule('Symfony');
        assert($symfonyModule instanceof Symfony);
        $symfony->haveHttpHeader('host', $host);
    }
}
```

usable like that:
```php
<?php

namespace Tests\Functional;

final class ExampleCest
{
    public function ExampleTestCest(FunctionalTester $I): void
    {
        $I->amOnHost('example.com');
        $I->amOnPage('/');
        $I->see('...');
    }
}
```

**Comment by toby-griffiths** [comment]
Ah yes, of course.  I've not got to the point where I'm testing different host's config yet, but this will help when I do.  Thanks @c33s .
