### ISSUE TITLE
Possible bug in Phalcon Connector

### ISSUE THREAD

**Issue by yambug** [Codeception/Codeception#4264]
https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Lib/Connector/Phalcon.php#L129-L131

`ReflectionProperty::getValue($obj);`

```php
$cookiesProperty = new ReflectionProperty($di['cookies'], '_cookies');
$cookiesProperty->setAccessible(true);
$cookies = $cookiesProperty->getValue($di['cookies']);
```
My English is bad,but I still want to tell you that you should check it twice.
Because I found It had worked with wrong.

**Comment by Naktibalda** [comment]
@yambug Could you provide an example when this code doesn't work?

**Comment by DavertMik** [comment]
@sergeyklay we need your extrasensory skills to understand or close this issue

**Comment by yambug** [comment]
@Naktibalda I opened the issue because I found there was a syntax error. I was looking at the source code, so I saw these lines. I know ReflectionProperty:: getValue (). This method needs to pass in an object instance, or else it will be wrong. But I do have no examples, because I haven't actually used them yet. Again, sorry, because I am not good at using English expression, and finally there is, I am not sure whether these lines really have problems, but I hope to communicate with you.

**Comment by sergeyklay** [comment]
I'll take a look asap

**Comment by sergeyklay** [comment]
@yambug 

```php
use ReflectionProperty;
use Phalcon\Http\Cookie;
use Phalcon\Di\FactoryDefault;
use Phalcon\Http\Response\Cookies as ResponseCookies;

$di = new FactoryDefault();

$cookies = new ResponseCookies();
$cookies->setDI($di);
$cookies->useEncryption(false);
$cookies->set('remember-me', 'some value', time() + 15 * 86400);

$di['cookies'] = $cookies;

$cookiesProperty = new ReflectionProperty($di['cookies'], '_cookies');
$cookiesProperty->setAccessible(true);
$cookies = $cookiesProperty->getValue($di['cookies']);

var_dump(is_array($cookies)); // TRUE
var_dump($cookies['remember-me'] instanceof Cookie); // TRUE
```

Could you please explain your problem a bit more?

**Comment by yambug** [comment]
@sergeyklay 
###This is an example of reflectionProperty
```
class Str
{
    public $length  = 5;
}

// Create an instance of the ReflectionProperty class
$prop = new ReflectionProperty('Str', 'length');

// Print out basic information
printf(
    "===> The%s%s%s%s property '%s' (which was %s)\n" .
    "     having the modifiers %s\n",
        $prop->isPublic() ? ' public' : '',
        $prop->isPrivate() ? ' private' : '',
        $prop->isProtected() ? ' protected' : '',
        $prop->isStatic() ? ' static' : '',
        $prop->getName(),
        $prop->isDefault() ? 'declared at compile-time' : 'created at run-time',
        var_export(Reflection::getModifierNames($prop->getModifiers()), 1)
);

// Create an instance of Str
$obj= new Str();

// Get current value
printf("---> Value is: ");
var_dump($prop->getValue($obj));

// Change value
$prop->setValue($obj, 10);
printf("---> Setting value to 10, new value is: ");
var_dump($prop->getValue($obj));

// Dump object
var_dump($obj);
```
I don't see how you can instantiate ReflectionProperty with an object instance.

**Comment by Naktibalda** [comment]
@yambug ReflectionProperty works with instances.
A similar code is used in https://github.com/Codeception/Codeception/blob/2.3.2/src/Codeception/Util/ReflectionHelper.php#L19-L23
And it works, I am 100% sure about that.
