### ISSUE TITLE
Suggestion: New chapter "IDE integration" in the docs

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4270]
What about a tutorial on how to configure some popular IDE's for work with Codeception? I could provide NetBeans explanation. Probably an own "Guides" page would be the best place? Can I create one myself?

**Comment by DavertMik** [comment]
Yes, please. That would be great. 
I think we can handle writing PHPStorm chapter as well.

**Comment by ThomasLandauer** [comment]
OK. Can/should I create the page myself (where)? Or will you give me a blank file - something like `13-IDEIntegration.md`?

**Comment by DavertMik** [comment]
Probably you can... But how about making this inside `Getting Started` chapter? I think it will be a good guide for newbies

**Comment by ThomasLandauer** [comment]
Let's see the content first, and decide then where to place it :-)

I have some questions/problems with NetBeans:

1. It is possible to run *all* tests (Ctrl+F6). But Strg+F6 ("Test File") is not working as I would have expected. I get the error `Test file for the selected source file was not found.` From that I'm infering that the idea would be to select a source file (no test!) and then run its *associated* test file. I have no idea how this "association" is defined/infered. Do you? For acceptance and functional tests it's probably hopeless, since there's no 1:1 relation between source files to test files. But maybe for unit tests?

1. When running a single test method (right-click, then "Run Focused Test Method"), this command gets issued:
    ```bash
    "C:\...\bin\codecept.bat" "--ansi" "--no-interaction" "run" "src/AppBundle/Tests/functional/AbcCest.php:tryIndex" "--xml=C:\Users\...\Temp\nb-codeception-log.xml"
    ```
    which leads to this error:
    ```bash
    [RuntimeException] Suite 'src/AppBundle/Tests/functional/AbcCest.php:tryIndex' could not be found
    ```
    I guess the problem is that `-c src/AppBundle` is missing. Is this Symfony-specific? And is it a NetBeans or a Codecption bug?

1. Bug: `[ConnectionException]`s are not correctly reported to NetBeans. Details: When the Selenium Server is not started, in NetBeans "Test Results" window (which is the one that's comming up when you start the tests), 100% are green. You have to manually open the "Output" window to see that all acceptance tests gave an error.  
On the other hand, if Codeception throws a `[RuntimeException]` it is communicated correctly to NetBeans (resulting in the test file being marked as "Failed").

**Comment by ThomasLandauer** [comment]
Point 2 is obsoleted by https://github.com/Codeception/codeception.github.com/pull/139/commits/dbb3eb4ef7a6d836655fa272f28dc0dd8fc87f3b

**Comment by DavertMik** [comment]
Sorry, I don't use Netbeans so can't say anything here. It is cool to show how to use Codeception with Netbeans with, as it is free IDE. However, I'm not sure of their level of support and integration. You might try to connect with them and ask questions there.

**Comment by ThomasLandauer** [comment]
I just created `13-IDEIntegration.md`, see https://github.com/Codeception/Codeception/pull/4302/commits

I think it's better to have a separate page (not included in `Getting Started`), cause IDE integration is certainly an advanced feature! Nobody is going to set this up, before he has taken a thorough look into Codeception itself. If you think it's that important, you could add a link on the `Getting Started` page.

To the questions above:

* `1.` is not that important, so I didn't mention it.

* For `3.` I filed an issue: https://netbeans.org/bugzilla/show_bug.cgi?id=270802

**Comment by hellboy81** [comment]
How can I  speicify XML report file location?

I.e. instead of `file:///tmp/nb-codeception-log.xml` write to `_output` dir of Test Files directory.

Netbeans under Suse Linux is used.
