### ISSUE TITLE
Suggestion: Support wildcards in criteria in grabFromRepository/grabFromDatabase

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4274]
Suggestion: Make `grabFromRepository()` (Doctrine Module) and/or `grabFromDatabase()` (Db Module) accept more general criteria, e.g. `LIKE` or `<=`.

The `<=` question has been asked before at https://github.com/Codeception/Codeception/issues/1019 - but I can't see how to write a Helper for this :-(

**Comment by DavertMik** [comment]
Good suggestion. Now we need someone who could implement this :muscle:
