### ISSUE TITLE
Symfony/console 3.3.0 broke `--xml` and other parameters with optional default value

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#4277]
https://travis-ci.org/Codeception/Codeception/jobs/237467274#L2737

```
1) IncludedCest: Run included with xml output
 Test  tests/cli/IncludedCest.php:runIncludedWithXmlOutput
 Step  See file found "report.json","tests/_output"
 Fail  File "report.xml" not found at ""

Scenario Steps:
 4. $I->seeFileFound("report.xml") at tests/cli/IncludedCest.php:42
 3. $I->amInPath("_log") at tests/cli/IncludedCest.php:41
 2. $I->executeCommand("run --xml") at tests/cli/IncludedCest.php:40
 1. $I->amInPath("tests/data/included") at tests/cli/IncludedCest.php:16
```

https://github.com/symfony/console/blob/master/CHANGELOG.md#330

> [BC BREAK] Input::getOption() no longer returns the default value for options with value optional explicitly passed empty

**Comment by DavertMik** [comment]
Ok, I will try to fix that today and release a new version quickly

**Comment by magroski** [comment]
Any progress on this issue?

**Comment by Naktibalda** [comment]
3.3.0-beta was released on the 1st of March,
3.3.0-rc1 - 2 weeks ago.
We need a build with unstable dependencies to get early warning about such changes in the future.

**Comment by Naktibalda** [comment]
1st of May, not March.

**Comment by acuthbert** [comment]
Just in case this issue is breaking deployments and have just skimmed the detail here - the fastest workaround is just to supply the default values to your switches explicitly - that'll get things moving again. For me this was changing --xml to --xml report.xml
