### ISSUE TITLE
Empty values for headers are skipped

### ISSUE THREAD

**Issue by tobiastom** [Codeception/Codeception#4287]
#### What are you trying to achieve?
I'm trying to set a `DNT` header to the value of `0`, as it is described in the specification:

    $I->haveHttpHeader('DNT', '0');

#### What do you get instead?
The `DNT` header is not set to the server as it is skipped.

### Details
The problem is in this line of code: https://github.com/Codeception/Codeception/blob/b54eaf4007484f36145c1dc8c64da1874adbc340/src/Codeception/Lib/InnerBrowser.php#L156-L158.

The string value `0` is evaluated as false and will not be send.
A possible solution would be to check if the value is a string, and if it is use it anyway. I could create a pull request for this, if it is an acceptable fix for you.

**Comment by Naktibalda** [comment]
To behave in the same way as set_cookie function that condition should be `if($val === null || $val === '') { continue; }`
https://github.com/php/php-src/blob/430eea84b84a8c9d733a38cafaa32d494cadf13b/ext/standard/head.c#L127

Please make a pull request.
