### ISSUE TITLE
seeLink does not count against assertions

### ISSUE THREAD

**Issue by c33s** [Codeception/Codeception#4298]
creating functional test with symfony2 module a admin backend. assertions with `seeLink` which are fulfilled does not count against assertion count.

##### Correct Assertions Count
```
$I->login('jill', '456');
$I->see('Media');
OK (1 test, 1 assertion)
```

##### Correct Assertions Count
```
$I->login('jill', '456');
$I->see('Media');
$I->see('User');
OK (1 test, 2 assertions)
```
##### Incorrect Assertions Count
```
$I->login('jill', '456');
$I->see('Media');
$I->see('User');
$I->seeLink('Gallery');
OK (1 test, 2 assertions)
```
##### Incorrect Assertions Count
```
$I->login('jill', '456');
$I->see('Media');
$I->see('User');
$I->seeLink('Gallery');
$I->seeLink('Galleryyy');
FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
```

so if the test is a failure it is added to the assertion count. if it is ok, it does not count up.

### Details

* Codeception version: 2.3.3
* PHP Version: 7.1
* Operating System: Win
* Installation type: Phar

**Comment by Naktibalda** [comment]
I will fix it this week.

**Comment by DavertMik** [comment]
My patch should fix this...
