### ISSUE TITLE
more detailed html report for unit tests

### ISSUE THREAD

**Issue by pYr0x** [Codeception/Codeception#4304]
#### What are you trying to achieve?
a html report for unit tests.
you should be able to click on the table rows and expand the row and see details (assertion) of the tests

#### What do you get instead?
a table row with the testname only.
the html report should be the same as on qunitjs. you see the message that you set on the assertion.

`php codecept run --steps --xml --html`

```php
        $k = new Koloniezahl([
            300
        ]);
        $k->setErgebnis(3500);

        $this->tester->assertEquals('nio', $k->getBewertung(), "ist nicht in Ordnung");
```
### Details

* Codeception version: 2.2.x
* PHP Version: 7
* Operating System: windows
* Installation type: Composer

**Comment by Naktibalda** [comment]
Solution: use Cest format and Asserts module.

**Comment by DavertMik** [comment]
Well, this is a good proposal. I think we can work on this.

**Comment by DavertMik** [comment]
Implemented in https://github.com/Codeception/phpunit-wrapper/pull/12 by @fffilimonov 
Please make sure you use PHPUnit 7.0 installations to get this patch
