### ISSUE TITLE
How to connect external modules to tests on Yii2

### ISSUE THREAD

**Issue by Joldyzzz** [Codeception/Codeception#4317]
We are moving the project to Yii2, codefile on yii2 is configured.
All configs of the web application and connection to the database are configured.

Simple functional tests work, for example:

```php
$I->amOnRoute('site/login');
$I->see('Login', 'h1');
````

We changed the authorization method in YII itself, the external module Client_authorize is called in the afterLogin method.

Client_authorize is our old authorization module. The test refuses to see it, throws an exception "[Error] Class 'Client_authorize' not found".

**Comment by samdark** [comment]
@DavertMik could you clarify it?

**Comment by Naktibalda** [comment]
It looks like an autoloading issue to me.

**Comment by Joldyzzz** [comment]
If in the file "_bootstrap.php" write:

```php
include ROOT. 'modules/authorize/client_authorize.php';
```
or

```php
Autoload :: addNamespace('', '/vagrant/modules/authorize/');
Autoload :: load(Client_authorize::class);
```


Then, when the test is run, the contents of the file "client_authorize.php"

**Comment by Joldyzzz** [comment]
Codeception for a short opening tag "<?" gives an error if you add php "<?php" everything is fine.
