### ISSUE TITLE
Symfony 4.0

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#4318]
Symfony 4.0 will be released later this year, and it will come with a new set of breaking changes.

We have to review deprecation messages in Symfony 3.3 and prepare for 4.0 releases.

One example of breaking change is #4316
> Setting the "doctrine" pre-defined service is deprecated since Symfony 3.3 and won't be supported anymore in Symfony 4.0
> Setting the "doctrine.orm.default_entity_manager" pre-defined service is deprecated since Symfony 3.3 and won't be supported anymore in Symfony 4.0

The likely effect is that Doctrine module will no longer be able to integrate with Symfony module.

**Comment by Naktibalda** [comment]
That change looks the most dangerous.

Others should not affect Codeception.
`symfony/console`
> The "ConsoleEvents::EXCEPTION" event is deprecated since Symfony 3.3 and will be removed in 4.0. Listen to the "ConsoleEvents::ERROR" event instead.

`symfony/dependencyinjection`
> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0.

> Relying on its factory's return-type to define the class of service "%s" is deprecated since Symfony 3.3 and won't work in 4.0. Set the "class" attribute to "%s" on the service definition instead.

`\Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension`
>Passing four arguments to the %s::__construct() method is deprecated since Symfony 3.3 and will be disallowed in Symfony 4.0. The new constructor only accepts three arguments.

`symfony/process`
> Not inheriting environment variables is deprecated since Symfony 3.3 and will always happen in 4.0. Set "Process::inheritEnvironmentVariables()" to true instead.

**Comment by tacman** [comment]
To avoid the deprecation errors, set this in the suite settings:

    error_level: "E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_USER_DEPRECATED"

**Comment by Naktibalda** [comment]
Deprecation is not a problem, removal of the feature in 4.0 will be a problem.

**Comment by tacman** [comment]
Yeah, I just posted that because our Jenkins tests were failing because of
them, and for now at least that silences the errors.  It also allows us to
do 'codecept run && something else'.

**Comment by muzfr7** [comment]
I'm also getting same deprecation notices while running codeception unit tests:

```
Setting the "doctrine" pre-defined service is deprecated since Symfony 3.3 and won't be supported anymore in Symfony 4.0
```
```
Setting the "doctrine.orm.default_entity_manager" pre-defined service is deprecated since Symfony 3.3 and won't be supported anymore in Symfony 4.0
```

**Comment by thejahweh** [comment]
Is there any progress on updating to symfony 4?

**Comment by VolCh** [comment]
I am waiting to merge and(or) tag https://github.com/stecman/symfony-console-completion/pull/79 https://github.com/facebook/php-webdriver/pull/489 https://github.com/sebastianbergmann/phpunit/pull/2822 to continue https://github.com/Codeception/Codeception/pull/4580

**Comment by Naktibalda** [comment]
@VolCh Could you test [persistService](http://codeception.com/docs/modules/Symfony#persistService) and Doctrine integration with Symfony 4.0?

**Comment by VolCh** [comment]
@Naktibalda https://github.com/Codeception/symfony-demo/pull/9 it seems that Doctrine integration works as usually in standard Symfony Demo.

I'll try add some other tests at the evening (UTC+03). Do you have another suggestions? Or feel free to add you tests.

**Comment by Naktibalda** [comment]
I meant http://codeception.com/docs/modules/Doctrine2

**Comment by VolCh** [comment]
https://github.com/Codeception/symfony-demo/pull/9/commits/ff05a335eba433ba7c2d12f532ccc3f09232f00c

**Comment by Naktibalda** [comment]
What version of symfony/dependency-injection have you got installed?

Relevant code in 3.4: https://github.com/symfony/dependency-injection/blob/3.4/Compiler/AutowirePass.php#L295-L305
and master: https://github.com/symfony/dependency-injection/blob/master/Compiler/AutowirePass.php#L243-L245

My suggestions for tests:
a) multiple HTTP requests in one test
b) test if Codeception can see a new record created by earlier request.

**Comment by VolCh** [comment]
With symfony/dependency-injection:v4.0.0-RC2 `\Codeception\Module\Doctrine2::grabEntityFromRepository()` works.

Suite config is:
```yaml
actor: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: 'src'
            environment: 'tests'
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - \App\Tests\Helper\Functional
```

**Comment by VolCh** [comment]
Added https://github.com/Codeception/symfony-demo/pull/9/commits/59373f42770642c3e94917a947b4ad8ff21f554b

**Comment by Naktibalda** [comment]
I am a bit surprised that it didn't cause any issues.
