### ISSUE TITLE
Change Module Config per Test

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4326]
Since the `cleanup` option of the Doctrine Module defaults to `true`, each test is always being wrapped in a transaction.  
I'm suggesting to start this transaction only when a *write* action is performed on the database - not for `SELECT` only.

My scenario / use case:  
1. I'm checking if the entity is not present in the database (`dontSeeInRepository()`)
1. I'm creating the entity through a command-line call (PHP's `exec()`)
1. I'm checking if the entity is present  (`seeInRepository()`)

With the `cleanup` option being absent (i.e. `true`), Codeception hangs at step 2 with this error message:
```
SQLSTATE[HY000]: General error: 5 database is locked
```
I'm guessing this is because of the transaction, since it works fine, as soon as I set `cleanup` to `false`

**Comment by Naktibalda** [comment]
Your step 2. makes a non-reversible change to database content.

**Comment by Naktibalda** [comment]
A problem with your suggestion is that it is impossible to start a transaction before write when that write is performed by command line command or by application code.

You are welcome to come-up with a different workaround, e.g. helper methods for starting and rolling back transactions, but please don't touch `cleanup` option.

**Comment by ThomasLandauer** [comment]
Yeah, you're right, I certainly missed the fact that most write actions are not performed by Codeception but by the application, so Codeception cannot determine when it would be a good time to start the transaction. Sorry!

But still, the fact that I don't like is that `cleanup` is a *global* setting. What about some way to set (i.e. override) this on a per-test-base? Something like `$I->dontStartTransaction()`?

**Comment by DavertMik** [comment]
@ThomasLandauer the problem is that

> $I->dontStartTransaction()

will be already already a transaction :upside_down_face: 

Doctrine2 module can be reconfigured inside a Helper. In `_before` method you can change configuration of a Doctrine2, so to disable transaction based on a name of a test. This helper should be registered before Doctrine2 so changes could be applied

**Comment by ThomasLandauer** [comment]
@DavertMik OK, cool! :-) I think this should be explained somewhere! (like all "magic" things which happen under the hood) Maybe at http://codeception.com/docs/modules/Doctrine2 ?

So what are the steps?

1. Create a file in `_support/Helper` and call it something like `Transaction.php`
1. Have a `_before()` method in this file?
1. What is the method supposed to look like? How can you access the test name? And how can you modify the transaction setting?
1. Register it in `acceptance.suite.yml` and/or `functional.suite.yml`, above Doctrine

**Comment by DavertMik** [comment]
My suggestion with Helpers was not very clear. Yes, it is too magical. How about using GroupObjects? 
http://codeception.com/docs/08-Customization#Group-Objects

For instance, you can make `@group notransaction` and inside a GroupObject get a Doctrine2 module and reconfigure it to skip the cleanup. This is the cleanest current solution.

Also I'm working on more explicit way to redefine current settings for a test.
This will be possible with a new `@init` annotation:

```php
/*
 * @init Doctrine2 noTransactions
 */
function testDoctrine()
{
}

protected function noTransactions(Doctrine2 $module)
{
   $module->_reconfigure(['cleanup' => false);
}
```

Does it feel better?

**Comment by ThomasLandauer** [comment]
About the initial transaction issue:  
After some thinking I now found the core of the problem: People don't know about the transaction at all! So before telling them how to turn it off, we should tell them that it actually **is** turned on :-)  
Suggestion: In `--debug` mode, under the line with the loaded modules `Modules: Symfony, Doctrine2, WebDriver, Asserts, \Helper\Acceptance`, include a note that Doctrine is (or not) running in transaction mode (I'll come up with a better wording). Show this note always if any database module is loaded.  
What about that?

`@init`:  
Yeah, that's cool! :-) Two further ideas about that:
* Allow enabling/disabling of entire modules too.
* Allow reconfigure of `codeception.yml` too.

Syntax: What about `noTransactions(Doctrine)` instead of `Doctrine noTransactions`? This would show clearer that Doctrine is being passed as parameter to the `noTransactions` function. Plus it would make things possible (if not now, then maybe in the future) like: `changeWhatever(Doctrine, Symfony, WebDriver)`.  
And finally I must say that I don't like annotations. I guess the con's are well-known (no syntax highlighting; looks like a comment; hard to handle if you have more than 1 sort of annotations,...). But I must admit that I don't have a better suggestion :-( The only alternative I could think of would be a yaml file in which you'd have to list all affected test functions. This could even allow wildcards, e.g. disable transaction for all tests beginning with `nt`. But that's probably overkill... :-)

**Comment by DavertMik** [comment]
> Suggestion: In --debug mode, under the line with the loaded modules Modules: Symfony, Doctrine2, WebDriver, Asserts, \Helper\Acceptance, include a note that Doctrine is (or not) running in transaction mode (I'll come up with a better wording). Show this note always if any database module is loaded.
What about that?

Good idea. Coming with PR! :running_man: 

> @init:
Yeah, that's cool! :-) Two further ideas about that:

Please let's discuss them in #4343 
I will post reply there.
