### ISSUE TITLE
Out of memory exits 0

### ISSUE THREAD

**Issue by josephzidell** [Codeception/Codeception#4328]
#### What are you trying to achieve?
See failing tests with exit code 1.

#### What do you get instead?
Codeception exited 0 even though there was an error. PHP ran out of memory, yet exited with status code 0, causing GitLab to mark the build as passing.
> Provide console output if related. Use `-vvv` mode for more details.

    Running with gitlab-ci-multi-runner 9.1.1 (6104325)
    
    << Skipping setup code for docker >>
    
    $ php -v
    PHP 5.6.24 (cli) (built: Jul 21 2016 14:53:01)
    
    << More skip >>
    
    $ ./vendors/bin/codecept -d run unit
    Codeception PHP Testing Framework v2.3.3
    Powered by PHPUnit 5.7.20 by Sebastian Bergmann and contributors.
    
      [Db] Connected to phpunit
      [Db] Connected to phpunit
    
    Unit Tests (1166) ------------------------------------------
    Modules: Asserts, DataHelper, Db, OtherHelper, FactoryHelper, UnitHelper
    ------------------------------------------------------------
    
    << Skip 110 passing tests >>
    
    ✔ ProductUpdatedEventTest: Create order without event (0.32s)
    PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 910950400 bytes) in /builds/developers/core-test/some/file.php on line 326
    
    Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 910950400 bytes) in /builds/developers/core-test/some/file.php on line 326
    <pre>Xyz Object
    
    << Skip 46,000 lines >>

### Details

* Codeception version: 2.3.3
* PHP Version: 5.6.24
* Operating System: CentOS
* Installation type: Composer
* List of installed packages (`composer show`): N/A
* Suite configuration: N/A

I can provide more info if needed.

**Comment by Naktibalda** [comment]
It looks like a bug of PHP to me, Codeception can't possibly intercept fatal error.

**Comment by Naktibalda** [comment]
I was wrong about intercepting, Codeception actually intercepts it with shutdown handler,
but it does not set status code.

However I have only got status 255 on "Allowed memory size exhausted" error.

```
- ConfigTest: Throws exception if config section does not existPHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2000000001 bytes) in /.../tests/unit/ConfigTest.php on line 13



FATAL ERROR. TESTS NOT FINISHED.
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2000000001 bytes)
in /.../tests/unit/ConfigTest.php:13

$ echo $?
255
```

Relevant code is [here](https://github.com/Codeception/Codeception/blob/2.3.3/src/Codeception/Subscriber/ErrorHandler.php#L78-L102).

exit(1) in shutdown handler does not change status code.

**Comment by josephzidell** [comment]
Both `exit()` and a Fatal Error trigger the shutdown handler. I'm surprised PHP itself doesn't set the exit status code in this case. [Here's](https://stackoverflow.com/a/35230174) a StackOverflow indicating it's still an open bug in PHP.

**Comment by josephzidell** [comment]
Would a `return 1;` help?

**Comment by Naktibalda** [comment]
Stackoverflow question that you linked says that PHP always returns status 255 for Fatal Errors.
It should be fine with your CI system, shouldn't it?

PHP always returns non-zero status for out of memory errors https://3v4l.org/40n37
I don't know what's so special about your system that it returns 0.
