### ISSUE TITLE
Register Codeception on Cloudflare

### ISSUE THREAD

**Issue by MetalArend** [Codeception/Codeception#4349]
The Codeception website can be terribly slow sometimes. I was wondering if it could help if you put it behind Cloudflare - you could gain a lot of speed from caching the documentation pages with a free account.

**Comment by Naktibalda** [comment]
I haven't noticed any performance issues.

**Comment by MetalArend** [comment]
Sometimes it keeps loading for 10 or 15 seconds, as only website loading at that moment. Not sure however if it is loading assets or simply trying to resolve DNS. I'll keep an eye on it.

**Comment by DavertMik** [comment]
Please send this complaint to GitHub
Codeception is hosted as codeception.github.io so the availability of the site should be the same as for this page.

**Comment by MetalArend** [comment]
I don't think the issue is with GitHub Pages, but most likely with the Codeception.com domain. I just tried loading the http://codeception.com/docs/06-ReusingTestCode page, and it was again extremely slow to respond (and I don't use the word extremely easily). It did load the assets and the page itself in 1,5 seconds, but it took very long to even respond. I try to keep my developer tools open in the hopes to record a complete load profile sometime.

Btw, Cloudflare is probably not the only option, depending on what DNS settings you are using right now, it should be easy enough to have https support and complete caching anywhere. As you already have a custom domain, I guess you're not even catching from the GitHub Pages everytime. I just see such a huge difference with the Codeception pages, that I'm even skipping the official documentation in my Google results, but it's the only site I'm having troubles with. And I see a lot of GitHub Pages these days, so there should be other comparable profiles of webpages.

**Comment by DavertMik** [comment]
Ok, thanks for the investigation. I think I should change my domain registrar (I was thinking to do that for a while).
