### ISSUE TITLE
404 on link for custom command example

### ISSUE THREAD

**Issue by krukru** [Codeception/Codeception#4355]
The page is http://codeception.com/docs/08-Customization#Custom-Commands

When clicking on the link `Please see a complete example`, the link leads to an gist that cannot be found. 

The link to the gist: https://gist.github.com/sd-tm/37d5f9bca871c72648cb

**Comment by Naktibalda** [comment]
that gist probably contained this file: https://github.com/Codeception/Codeception/blob/5fd8a31f7023c4840284388f0c3a44567caf4a01/tests/data/claypit/MyCustomCommand.php

**Comment by DavertMik** [comment]
We should update the docs. Thanks for noticing
