### ISSUE TITLE
global state not cleaned up between tests in Cest

### ISSUE THREAD

**Issue by VSilantyev** [Codeception/Codeception#4357]
I'm expecting that global state (global variables) should be cleaned up between tests.

I see that in Cest global variables remains between tests.

```php
class IsolationCest
{

    public function writeGlobal(\CodeGuy $I)
    {
        global $myNiceGlobal;
        $myNiceGlobal = "hello";
    }

    public function readGlobal(\CodeGuy $I)
    {
        global $myNiceGlobal;
        $I->assertEmpty($myNiceGlobal);
    }

}
```

```bash
vendor/bin/codecept run tests/unit/IsolationCest.php 
Codeception PHP Testing Framework v2.2.12
Powered by PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

Unit Tests (2) ----------------------------------------------------------------------------------------------------------------------------------------
✔ IsolationCest: Write global (0.00s)
✖ IsolationCest: Read global (0.01s)
-------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 922 ms, Memory: 22.00MB

There was 1 failure:

---------
1) IsolationCest: Read global
 Test  tests/unit/IsolationCest.php:readGlobal
 Step  Assert empty "hello"
 Fail  Failed asserting that a string is empty.

```

### Details

* Codeception version: 2.2.12
* PHP Version: PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
* Operating System: ubuntu 16.04
* Installation type: Composer

Is this expected behavior? I think global variables should be cleaned up between tests, like in phpunit.

**Comment by DavertMik** [comment]
Cleaning up global variables can reduce the execution speed. 
So this is turned off by default

**Comment by VSilantyev** [comment]
Is there a way to turn it on?

**Comment by Naktibalda** [comment]
Add 
```yml
settings:
  backup_globals: true
```
to codeception.yml
http://codeception.com/docs/reference/Configuration

I checked the code earlier and it looks like this setting is turned on [by default](https://github.com/Codeception/Codeception/blob/2.3.3/src/Codeception/Configuration.php#L92).

**Comment by VSilantyev** [comment]
I've just tested it. It does not work. I did a quick look across the code, looks like this setting affects only phpunit-based ..Test tests, not Cest.

**Comment by DavertMik** [comment]
Yes, technically Cest classes are not extended from `PHPUnit\Framework\TestCase`, so to be lightweight, and have its features cut. Please use Test\Unit format and not Cest for such cases. 

You know, for acceptance/functional tests it is not so common to use globals anywhere....
