### ISSUE TITLE
Access the session in acceptance tests

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4362]
I'm trying to access a PHP session, by using the Symfony-integrated functions: https://symfony.com/doc/current/components/http_foundation/sessions.html

The session is created by the app (i.e. through the browser), and I want to access its values in a Cest file like this:

```php
$session = $I->grabService('session');     
$data = $session->get('login');
codecept_debug($data);
```

I don't get any output, even though the session does exist, and the `login` attribute is present.

The cause of the problem seems to be that when I do `$session->getName();` in the Cest file, I get `MOCKSESSID`, while the "real" session name is `PHPSESSID`.

Oddly enough, wenn I do `$I->grabCookie('PHPSESSID');`, I get the name of the "real" session file on my hard drive. So the cookie seems to be present and Codeception knows about it. So why can't I access the `PHPSESSID` session then?

Thanks!!

**Comment by DavertMik** [comment]
> The session is created by the app (i.e. through the browser), and I want to access its values in a Cest file like this:
> $session = $I->grabService('session');     
> $data = $session->get('login');

This is technically impossible. Your browser session is managed by PHP running in a webserver, while tests run in a different process. There will be no real session in acceptance tests.

**Comment by ThomasLandauer** [comment]
I've found a workaround! See https://stackoverflow.com/a/44780255/1668200

**Comment by Naktibalda** [comment]
It only works if your website is running on the same computer.

**Comment by mamaly12** [comment]
For the Accessing your application session via PHP Browser you need to create session in your acceptance code again:
1. use ob_start (); in order to flush the buffer.
2. create a sessionId
3. check if session_status() == PHP_SESSION_ACTIVE destroy it:  session_destroy();
4. set sessionId with: session_id command
5. use session_start(); to start your session
