### ISSUE TITLE
Sometimes during tests running, one test stucks after passed previous test

### ISSUE THREAD

**Issue by TheodorL93** [Codeception/Codeception#4371]
Hi,
When I'm running my tests, sometimes one of them will not start till I will not press some keyboard button in the console window, after this action tests will continue properly.

If I will not press some key then tests will stuck up  to timeout. Then I have error:
`Session not started or terminated`

Reproduce % for this issue is about 5%...

What could be the reason for my problem? Have somebody idea how solve it?

### Details
* Codeception version: 
* PHP Version: 2.3.3
* Operating System: Windows 10
* Selenium Chrome Driver

**Comment by Naktibalda** [comment]
You aren't using [pauseExecution](http://codeception.com/docs/modules/WebDriver#pauseExecution), are you?

**Comment by TheodorL93** [comment]
No, I'm not using pauseExecution...

**Comment by Naktibalda** [comment]
It is on you to figure it out.
You could try to use one of the tools recommended in https://stackoverflow.com/questions/3847745/systrace-for-windows to check what Codeception is doing when it is stuck.

Or you could use xdebug [execution trace](https://xdebug.org/docs/execution_trace) or [profiling](https://xdebug.org/docs/profiler) capabilities to check what PHP function is taking so long.

**Comment by Naktibalda** [comment]
Another option is to check the output of Selenium.

**Comment by TheodorL93** [comment]
Thank you Naktibalda, but now I have bigger problem

```
 /bin/bash -l -c "php codecept.phar run -c firstTest"
stdin: is not a tty
Codeception PHP Testing Framework v2.3.3
```
After all tests session is not finished

How resolve "stdin: is not a tty"?
Maybe some solution for this? :(

**Comment by Naktibalda** [comment]
I googled it up and it appears to be printed by bash, because it doesn't like the way you run it.
https://stackoverflow.com/a/26187244/366348

**Comment by TheodorL93** [comment]
No :( `stdin: is not a tty` not solved problem with stuck session, probably this is some deeper problem... 

It's not working if test are running for local website using BrowserstackDriver, but after tests on external page, session is finished properly (using browserstack also and this same configuration).

**Comment by Naktibalda** [comment]
Not a bug.
