### ISSUE TITLE
Laravel 5 unit testing issues

### ISSUE THREAD

**Issue by krtorio** [Codeception/Codeception#4375]
#### What are you trying to achieve?

1. generate phpunit test using the "composer exec codecept g:phpunit unit " instruction in the quick start guide http://codeception.com/for/laravel 
2. run unit test using environment file .env.testing

#### What do you get instead?
1. See console output below:

```bash
# composer exec codecept g:phpunit unit User
[Symfony\Component\Console\Exception\CommandNotFoundException]
  The namespace "g" is ambiguous.
  Did you mean one of these?
      generate
      gherkin
```

2. Codeception uses .env file instead.
Issue only appears on unit test suite, functional suite works ok.

### Details

* Codeception version:  1.2.2
* PHP Version: 7.0.13
* Operating System: windows 8
* Installation type: Composer
* List of installed packages (`composer show`):

behat/gherkin                         v4.4.5  Gherkin DSL parser for PHP 5.3
codeception/codeception               2.3.3   BDD-style testing framework
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base d...
doctrine/inflector                    v1.1.0  Common String Manipulations ...
doctrine/instantiator                 1.0.5   A small, lightweight utility...
erusev/parsedown                      1.6.2   Parser for Markdown.
facebook/webdriver                    1.4.1   A PHP client for Selenium We...
fzaninotto/faker                      v1.6.0  Faker is a PHP library that ...
guzzlehttp/guzzle                     6.3.0   Guzzle is a PHP HTTP client ...
guzzlehttp/promises                   v1.3.1  Guzzle promises library
guzzlehttp/psr7                       1.4.2   PSR-7 message implementation...
hamcrest/hamcrest-php                 v1.2.2  This is the PHP port of Hamc...
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
laravel/framework                     v5.4.28 The Laravel Framework.
laravel/tinker                        v1.0.1  Powerful REPL for the Larave...
league/flysystem                      1.0.40  Filesystem abstraction: Many...
mockery/mockery                       0.9.9   Mockery is a simple yet flex...
monolog/monolog                       1.23.0  Sends your logs to files, so...
mtdowling/cron-expression             v1.2.0  CRON for PHP: Calculate the ...
myclabs/deep-copy                     1.6.1   Create deep copies (clones) ...
nesbot/carbon                         1.22.1  A simple API extension for D...
nikic/php-parser                      v3.0.6  A PHP parser written in PHP
paragonie/random_compat               v2.0.10 PHP 5.x polyfill for random_...
phpdocumentor/reflection-common       1.0     Common reflection classes us...
phpdocumentor/reflection-docblock     3.1.1   With this component, a libra...
phpdocumentor/type-resolver           0.2.1
phpspec/prophecy                      v1.7.0  Highly opinionated mocking f...
phpunit/php-code-coverage             4.0.8   Library that provides collec...
phpunit/php-file-iterator             1.4.2   FilterIterator implementatio...
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.9   Utility class for timing
phpunit/php-token-stream              1.4.11  Wrapper around PHP's tokeniz...
phpunit/phpunit                       5.7.21  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.4.3   Mock Object library for PHPUnit
psr/http-message                      1.0.1   Common interface for HTTP me...
psr/log                               1.0.2   Common interface for logging...
psy/psysh                             v0.8.8  An interactive shell for mod...
ramsey/uuid                           3.6.1   Formerly rhumsaa/uuid. A PHP...
sebastian/code-unit-reverse-lookup    1.0.1   Looks up which function or m...
sebastian/comparator                  1.2.4   Provides the functionality t...
sebastian/diff                        1.4.3   Diff implementation
sebastian/environment                 2.0.0   Provides functionality to ha...
sebastian/exporter                    2.0.0   Provides the functionality t...
sebastian/global-state                1.1.1   Snapshotting of global state
sebastian/object-enumerator           2.0.1   Traverses array structures a...
sebastian/recursion-context           2.0.0   Provides functionality to re...
sebastian/resource-operations         1.0.0   Provides a list of PHP built...
sebastian/version                     2.0.1   Library that helps with mana...
stecman/symfony-console-completion    0.7.0   Automatic BASH completion fo...
swiftmailer/swiftmailer               v5.4.8  Swiftmailer, free feature-ri...
symfony/browser-kit                   v3.3.2  Symfony BrowserKit Component
symfony/console                       v3.3.2  Symfony Console Component
symfony/css-selector                  v3.3.2  Symfony CssSelector Component
symfony/debug                         v3.3.2  Symfony Debug Component
symfony/dom-crawler                   v3.3.2  Symfony DomCrawler Component
symfony/event-dispatcher              v3.3.2  Symfony EventDispatcher Comp...
symfony/finder                        v3.3.2  Symfony Finder Component
symfony/http-foundation               v3.3.2  Symfony HttpFoundation Compo...
symfony/http-kernel                   v3.3.2  Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.4.0  Symfony polyfill for the Mbs...
symfony/process                       v3.3.2  Symfony Process Component
symfony/routing                       v3.3.2  Symfony Routing Component
symfony/translation                   v3.3.2  Symfony Translation Component
symfony/var-dumper                    v3.3.2  Symfony mechanism for explor...
symfony/yaml                          v3.3.2  Symfony Yaml Component
tijsverkoyen/css-to-inline-styles     2.2.0   CssToInlineStyles is a class...
vlucas/phpdotenv                      v2.4.0  Loads environment variables ...
webmozart/assert                      1.2.0   Assertions to validate metho...

* Suite configuration:

```yml
# paste suite config here

actor: UnitTester
modules:
    enabled:
        - Laravel5:
            environment_file: .env.testing
        - Asserts
        - \Helper\Unit

```

**Comment by Naktibalda** [comment]
1. `generate:phpunit` command has been removed since Codeception 2.3.0. Please use `g:test` instead.

**Comment by krtorio** [comment]
Ok thanks, can we still be able to create phpunit tests in codeception or do we go back to php artisan?

Also, issue number 2 was solved by inserting $app->loadEnvironmentFrom('.env.testing'); in CreatesApplication trait.  Still wondering why I had to do this since this was a fresh install done yesterday.

**Comment by Naktibalda** [comment]
Codeception still runs PHPUnit tests, but you have to use other tools for creating them.
If you are only going to run these tests with Codeception, it is better to use Test format - it has all the features of PHPUnit TestCase but is integrated with Codeception better.

**Comment by DavertMik** [comment]
Removed `g:phpuni` from docs
