### ISSUE TITLE
ModuleContainer::includeMethodAsAction $module::$excludeActions is optional

### ISSUE THREAD

**Issue by CactusCoder** [Codeception/Codeception#4381]
#### What are you trying to achieve?
Call includeMethodAsAction() on a controller without an $excludeActions property.

#### What do you get instead?
Fatal error.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
PHP Fatal error:  Uncaught Error: Access to undeclared static property: Codeception\Extension\Recorder::$excludeActions in phar:///usr/local/bin/codecept/src/Codeception/Lib/ModuleContainer.php:164
```
> Provide test source code if related

```php
// paste test
```
### Details
First line in [ModuleContainer::includeMethodAsAction](https://github.com/Codeception/Codeception/blob/2.3.3/src/Codeception/Lib/ModuleContainer.php#L164) should check for existence of $module::$excludeActions before accessing it.

* Codeception version: 
2.3
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
Please make a pull request.

**Comment by CactusCoder** [comment]
I'll have to learn how to do this - will be back.
