### ISSUE TITLE
Chrome drops support for added credentials

### ISSUE THREAD

**Issue by Fuin** [Codeception/Codeception#4384]
https://www.chromestatus.com/feature/5669008342777856

Is there going to be a Codeception solution for this?

In Selenium you can go to a page with the htacces embedded in the url and then go to the page you want to test, but as far as I can see Codeceptions amOnPage etc. is always referring to the base url in the acceptance suite.

**Comment by Naktibalda** [comment]
You missed `in subresource requests` part.
Is there a Codeception problem?

**Comment by Fuin** [comment]
No, but its a general problem for acceptance tests and as its going to be a permanent thing for chrome, and maybe later other browsers as well, I was just wondering if there will be a Codeception solution for this issue. 
like: 
$I->haveAuthentification('username', 'password');

The bottom part I was just wondering how to face this without writing a helper ;)

**Comment by DavertMik** [comment]
>  I was just wondering if there will be a Codeception solution for this issue.

Do you know how this can be solved?

**Comment by Fuin** [comment]
As far as I see now you need to insert the authentification only once at the beginning of the tests and it stays active as long as the browser is opened. 
So I added a 
$I->executeInSelenium( ->get('username:password@webpage')) 
$I->amOnPage('webpage')
at the beginning of one test and the they are all going through smoothly. 
There surely can be a better way to implement this, like putting these two together in one function, or just add the authentification to the config and modify amOnPage to check if there is an authentification and then go through these two steps at the beginning.
