### ISSUE TITLE
Chrome Issue - you are using an unsupported command-line flag ignore-certificate-errors

### ISSUE THREAD

**Issue by nick2060** [Codeception/Codeception#4388]
I'm trying to get my UI tests running on my machine (Macbook Pro running OS 10.12 MacOS Seirra) but whenever I try to run a test using selenium webdriver on chrome, I get the error - you are using an unsupported command-line flag ignore-certificate-errors selenium.

This wasn't something I manually did - is this something that comes in place when using codeception? How can I fix it?

**Comment by Naktibalda** [comment]
Sorry for late response, have you figured it out?

**Comment by wenJanus** [comment]
I have the same issue, when i use WebDriver in chrome.

**Comment by Naktibalda** [comment]
You have to upgrade chromedriver to v2.28 or newer.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1745

**Comment by huzhaoliang** [comment]
using 2.9 still has same issue on mac os

**Comment by SeanWinterborne** [comment]
Can also confirm for windows, this problem is occurring with version 2.9 but using version 2.28 is completely fine.
