### ISSUE TITLE
`browser` option of WebDriver Module is irrelevant when using ChromeDriver

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4398]
When connecting to ChromeDriver directly (i.e. without Selenium Server), the `browser` option of `WebDriver` in `acceptance.suite.yml` doesn't have any effect. Even if I put `firefox` in there, I still get Chrome executed.

The real bug is that it's not possible to just omit this option - I get:

    WebDriver module is not configured!
    Options: browser, url are required

So I'm suggesting to update the checks for those two options, and only throw an error if they are *really* required.

### Details
* Codeception version: 2.3.4

**Comment by DavertMik** [comment]
>  I'm suggesting to update the checks for those two options, and only throw an error if they are really required.

Yes, they are. 
For example, PhantomJS also ignores the `browser` parameter but when the browser is specified to `phantomjs` we can add some logic, for most cases there are special exceptions, like "Not for PhantomJS"

Probably at one point, we may need some Chrome-specific logic. In this case, we must know that we are running in Chrome browser and we won't be able to get this information anywhere other than `browser` config. 

So I suggest to keep it as it is.
