### ISSUE TITLE
Bug: Stub method invoke count test not working

### ISSUE THREAD

**Issue by enumag** [Codeception/Codeception#440]
This test should fail because the method is called only one time but is expected to be called two times. However the test won't fail in current stable version (I didn't try dev).

Similarly `Stub::once(...)` won't fail if never called.

``` php
<?php

use Codeception\Util\Stub;

class Foo
{
    public function method() {}
}

class ExampleTest extends \Codeception\TestCase\Test
{

    public function testSomething()
    {
        $foo = Stub::makeEmpty('Foo', array(
            'method' => Stub::exactly(2, function () {}),
        ));

        $foo->method();
    }

}
```

**Comment by neoascetic** [comment]
As for me, Mockery is too verbose. Especially when comparing with Stub.

**Comment by neoascetic** [comment]
Agrh, why none told me I need to call `$mock->__phpunit_verify();` manually? Should this be in the docs, @DavertMik, shouldn't it?

**Comment by enumag** [comment]
@neoascetic I believe that the fact that you need to call it manually is a bug. It would be better if Codeception called it by itself. Anyway I've switched to Mockery long time ago.

**Comment by Naktibalda** [comment]
To make verification working automatically you have to pass an instance of PhpUnit_Framework_TestCase as the last argument to Stub::makeX() method.
$this works in all test formats in Codeception 2.1.

```php

class ExampleTest extends \Codeception\TestCase\Test
{

    public function testSomething()
    {
        $foo = Stub::makeEmpty('Foo', array(
            'method' => Stub::exactly(2, function () {}),
        ), $this);

        $foo->method();
    }

}
```
