### ISSUE TITLE
when can I use services in Zf3 in codeception?

### ISSUE THREAD

**Issue by ahadyekta** [Codeception/Codeception#4404]
in zf2 page it is said that : "Note: services part and Doctrine integration is not compatible with ZF3 yet"
When do you estimate that the capability will be ready to use?

**Comment by Naktibalda** [comment]
When somebody volunteers to implement or, if it doesn't happen, then never.

Related ticket  #4181

**Comment by krezia** [comment]
Hi, 

i am trying also to run my previously written for ZF3 codeception test on ZF3 (after migration). Is there a way to hep with the service provider for ZF3?

**Comment by Naktibalda** [comment]
Fixed by #5566
