### ISSUE TITLE
Codeception testing REST API with PhpBrowser doesnt correctly test redirects

### ISSUE THREAD

**Issue by nekyian** [Codeception/Codeception#4412]
#### What are you trying to achieve?
I have a number of REST API routes that return 301 header and correct URL for the resource, when URL parameteres validation fails. In postman I get the correct response.
#### What do you get instead?
In Codeception it automatically follows the redirect and reports wrong code 200 when 301 is expected

PS: I am using 	$I->stopFollowingRedirects() but above described pattern still occurs.

**Comment by Naktibalda** [comment]
Please run your test with `-vv` flag and copy the output to this issue.

**Comment by Naktibalda** [comment]
@nekyian please provide more information.
