### ISSUE TITLE
How to separate string and integer

### ISSUE THREAD

**Issue by Paintras** [Codeception/Codeception#4418]
Hello guys,
I've run into problem today. I got element with specific HTML code:
<|td class="price" id="total_price" colspan="2">
    <|strong> 249,00<|/strong> 
    <|strong>Kč<|/strong>
<|/td>

I want to grab integer 249, but it doesnt work when I use grabValue() function and print it out via expect(), it wrote "I expect " with nothing like its null ( I am printing variable loaded with grabValue ) . Value is clearly whole:  <|strong> 249,00
<|/strong> <|strong>Kč<|/strong>
So how do I separate string "Kč" and integer 249,00 ? ( 249 even ) Choosing only <|strong>249,00<|/strong> selector does not work. Do I have to separate these two via some custom function in php or does codeception have some smarter solution for this? (or do I missing something trivial here ?))
Thank you all for help
Cheers

**Comment by Paintras** [comment]
Well i figured way around it. I grabbed whole string from *td* and than used preg_split method with regex /,[0-9]{2} Kč/ to cut off thing that i dont need and than cast first index of array from string to get value that I want. I will wait if someone got some easier solution inside codeception and than I will close this issues.

**Comment by Naktibalda** [comment]
Why don't you grab the first `<strong>` item?

**Comment by Paintras** [comment]
That was the first thing that has came to my mind my code was like this
$myVar = $I->grabValueFrom("#firstStrongSelector");
$I->expect($myVar);
this returned null
when I tried to cast it it returned 1
Is there something stupid that I am missing ?

**Comment by Paintras** [comment]
Oh I think I get it i should grab text and than cast it so 499,00 would be 499 integer ?

**Comment by Naktibalda** [comment]
Could you show an actual selector?

**Comment by Paintras** [comment]
#total_price > strong:nth-child(1)

**Comment by Paintras** [comment]
Next thing I have bumped into is ( not really a codeception issue ) that both my solution above and grabing text and casting it works for 3 digits integers. but with 4 or more digits it trims the last 3 off.

**Comment by Naktibalda** [comment]
Probably because you use thousands separators. e.g `1 234,99`.
Remove spaces before casting.

**Comment by Paintras** [comment]
Oh never heard that  number format can be seen as separeted by white space. I will use replace method. Thank you much sir, always helpfull.

**Comment by Paintras** [comment]
Closing issues. Solution was that thing that I wanted to grab was not a value, but a string with separator. I've needed to grab text and than use $myValue = (int)str_replace(' ','',$myString); Than I've gotten my int value that I could use.
