### ISSUE TITLE
XPaths not passing capital letters

### ISSUE THREAD

**Issue by Tro95** [Codeception/Codeception#442]
The xpaths are being converted to lower-case before being matched in all of my tests. Normally with wouldn't have been an issue, but I'm now trying to identify an image by its `src` attribute which can and will contain upper-case characters. I've tried `lower-case()` and `upper-case()` xpath functions, however these have both failed leaving me to believe that Codeception doesn't support xpaths 2.0, and the only available 'hack' for xpaths 1.* involves the `translate()` function which requires upper-case characters itself (being converted to lower on execution).

I can find a few other dirty hacks to resolve this issue for myself, however converting all xpath expressions to lower-case before execution is likely to cause issues with other people at some point and should probably be resolved.

EDIT: Some xpaths are resolving upper-case characters in some positions, but not all. It seems to be converting them to lower-case inside functions and after my `@src` tag.

**Comment by RobQuistNL** [comment]
Is this still relevant?

**Comment by tommyd3mdi** [comment]
Switched to different projects, not for me at least.
