### ISSUE TITLE
How to: code coverage without blacklists

### ISSUE THREAD

**Issue by CJDennis** [Codeception/Codeception#4427]
I've had issues with Codeception versions that have blacklist support removed so I no longer try to use any version after Codeception v2.2.6.

If I have 10 different classes and a separate test class for each, how can I run just one of the test classes without all the other classes being marked in red because no tests exercised them? With blacklists this is easy and is the default behaviour.

I'm also trying to introduce Codeception at work, and we have about 10 000 PHP files. The latest Codeception simply doesn't work on that many files without blacklists as it tries to include every single file in the report. I have no idea if it's capable of finishing because I don't have that much patience when I'm trying to make a quick change.

This is my default setup for code coverage with blacklists:
```
coverage:
    enabled: true
    blacklist:
        include:
            - tests/*
```

Is there anyway of getting the latest Codeception to replicate this behaviour?

**Comment by Naktibalda** [comment]
If I remember correctly, blacklist functionality was removed from Codeception, because it was removed from Php_Code_Coverage library.

We still have exclude option in whitelist http://codeception.com/docs/11-Codecoverage#Configuration

**Comment by CJDennis** [comment]
As fas as I remember, blacklists and whitelists work in the opposite way. With blacklists I can get a report of only those files that were exercised. With whitelists, all files are included, whether they're exercised or not. I can list certain files to exclude, but not 10 000 of them, especially when I want to separately exercise them in other tests. I can't keep changing the configuration file every time I need to run a different test. The same configuration should work for all tests.

Can you give me a .yml configuration to replicate the old behaviour for the latest Codeception?

**Comment by Naktibalda** [comment]
No, I can't.
