### ISSUE TITLE
[WebDriver] getCapabilities method does not exist in facebook/webdriver < 1.3.0

### ISSUE THREAD

**Issue by daudmalik06** [Codeception/Codeception#4435]
#### Acceptance testing 

Hello in codeception version 2.3 , you guys have changed the `_before` method of 
[Codeception/src/Codeception/Module/WebDriver.php](https://github.com/Codeception/Codeception/blob/2.3.4/src/Codeception/Module/WebDriver.php#L415-L418)

```
 $test->getMetadata()->setCurrent([
            'browser' => $this->webDriver->getCapabilities()->getBrowserName(),
            'capabilities' => $this->webDriver->getCapabilities()->toArray()
        ]);

```
and in the requirements of codeception you can find 
`facebook/webdriver: >=1.0.1 <2.0`

but if you check the `facebook/webdriver:1.2` 
you will not find any `getCapabilities` method in `php-webdriver/lib/Remote/RemoteWebDriver.php`

this will raise an error during run time as 
` Call to undefined method Facebook\WebDriver\Remote\RemoteWebDriver::getCapabilities()`

if some one is using  `facebook/webdriver:1.2` 

so i think this should be changed in composer 
what do you think ?
if yes i can make a pull request

### Details

* Codeception version: 2.3.4
* PHP Version:7.1.7
* Operating System: windows
* Installation type: Composer

**Comment by Naktibalda** [comment]
Codeception 2.3 still supports PHP 5.4.

The last version of `facebook/webdriver` which supported PHP 5.4 was 1.1.3.
I think that the right solution would be to fix `_before` to work with 1.1.3, even if it disables capabilities feature for PHP 5.4

**Comment by daudmalik06** [comment]
yeah it can be or may be change composer.json to restrict usage of `facebook/webdriver`
 to `facebook/webdriver:>1.3`

**Comment by Naktibalda** [comment]
Setting `>1.3` is not possible in Codeception 2.3, because it raises minimum required version of PHP to 5.5
