### ISSUE TITLE
Redundant query to main page

### ISSUE THREAD

**Issue by vitalyzhakov** [Codeception/Codeception#4441]
#### What are you trying to achieve?
Only 1 query to webserver

#### What do you get instead?
Firstly, query to main page, secondly test executed.

#### Сonsole output

```bash
EmailCest: Ensure view track works
Signature: EmailCest:ensureViewTrackWorks
Test: tests/api/EmailCest.php:ensureViewTrackWorks
Scenario --
  [Request Headers] []
  [Page] /
  [Response] 404
  [Request Cookies] {"CODECEPTION_CODECOVERAGE":"{"CodeCoverage":"ensureLinksRedirectWorks","CodeCoverage_Suite":"api","CodeCoverage_Config":null}"}
  [Response Headers] {"Server":["nginx/1.10.3"],"Date":["Thu, 10 Aug 2017 06:38:13 GMT"],"Content-Type":["text/html; charset=UTF-8"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"]}
  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22ensureLinksRedirectWorks%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=webeqstatweb6622n2; path=/","CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22ensureViewTrackWorks%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; path=/; httponly"]
 I send get "/email/vt?communicationTaskRK=123456"
  [Request] GET http://webeqstatweb6622n2:40015/email/vt?communicationTaskRK=123456
  [Request Headers] []
  [Page] http://webeqstatweb6622n2:40015/email/vt?communicationTaskRK=123456
  [Response] 200
  [Request Cookies] {"CODECEPTION_CODECOVERAGE":"{"CodeCoverage":"ensureViewTrackWorks","CodeCoverage_Suite":"api","CodeCoverage_Config":null}"}
  [Response Headers] {"Server":["nginx/1.10.3"],"Date":["Thu, 10 Aug 2017 06:38:13 GMT"],"Content-Type":["text/html; charset=UTF-8"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"X-Backend-Server":["0c915310913d"],"X-Project":["eqstat"]}
  [Response] 
  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22ensureLinksRedirectWorks%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=webeqstatweb6622n2; path=/","CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22ensureViewTrackWorks%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; path=/; httponly"]
 I see response code is 200
  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22ensureLinksRedirectWorks%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=webeqstatweb6622n2; path=/","CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22ensureViewTrackWorks%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; path=/; httponly"]
 I see in collection "emailViewTrack",{"communicationTas...}
  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22ensureLinksRedirectWorks%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=webeqstatweb6622n2; path=/","CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22ensureViewTrackWorks%22%2C%22CodeCoverage_Suite%22%3A%22api%22%2C%22CodeCoverage_Config%22%3Anull%7D; path=/; httponly"]
 PASSED 
```
#### Test source code

```php
public function ensureViewTrackWorks(ApiTester $I)
    {
        $I->sendGET('/email/vt?communicationTaskRK=123456');
        $I->seeResponseCodeIs(\Codeception\Util\HttpCode::OK);
        $I->seeInCollection('emailViewTrack', [
            'communicationTaskRK' => 123456,
        ]);
    }
```
### Details

* Codeception version: 2.3.4
* PHP Version: 7.1.5
* Operating System: Debian 8
* Installation type: Composer
#### List of installed packages (`composer show`)
behat/gherkin                      v4.4.5 Gherkin DSL parser for PHP 5.3
bower-asset/bootstrap              v3.3.7 The most popular front-end framew...
bower-asset/jquery                 2.2.4 
bower-asset/jquery.inputmask       3.3.7  Inputmask is a javascript library...
bower-asset/punycode               v1.3.2
bower-asset/raven-js               3.12.2
bower-asset/yii2-pjax              v2.0.6
cebe/markdown                      1.1.2  A super fast, highly extensible m...
codeception/c3                     2.0.12 CodeCoverage collector for Codece...
codeception/codeception            2.3.4  BDD-style testing framework
doctrine/instantiator              1.1.0  A small, lightweight utility to i...
domru/request                      1.0    Request
ezyang/htmlpurifier                v4.9.3 Standards compliant HTML filter w...
facebook/webdriver                 1.4.1  A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.0  Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1 Guzzle promises library
guzzlehttp/psr7                    1.4.2  PSR-7 message implementation that...
mito/yii2-sentry                   1.0.2  Yii 2 extension for Sentry
mongodb/mongodb                    1.1.2  MongoDB driver library
myclabs/deep-copy                  1.6.1  Create deep copies (clones) of yo...
phar-io/manifest                   1.0.1  Component for reading phar.io man...
phar-io/version                    1.0.1  Library for handling version info...
phpdocumentor/reflection-common    1.0    Common reflection classes used by...
phpdocumentor/reflection-docblock  3.2.2  With this component, a library ca...
phpdocumentor/type-resolver        0.3.0 
phpspec/prophecy                   v1.7.0 Highly opinionated mocking framew...
phpunit/php-code-coverage          5.2.2  Library that provides collection,...
phpunit/php-file-iterator          1.4.2  FilterIterator implementation tha...
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  1.0.9  Utility class for timing
phpunit/php-token-stream           2.0.0  Wrapper around PHP's tokenizer ex...
phpunit/phpunit                    6.2.4  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       4.0.4  Mock Object library for PHPUnit
psr/http-message                   1.0.1  Common interface for HTTP messages
psr/log                            1.0.2  Common interface for logging libr...
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method...
sebastian/comparator               2.0.0  Provides the functionality to com...
sebastian/diff                     1.4.3  Diff implementation
sebastian/environment              3.1.0  Provides functionality to handle ...
sebastian/exporter                 3.1.0  Provides the functionality to exp...
sebastian/global-state             2.0.0  Snapshotting of global state
sebastian/object-enumerator        3.0.3  Traverses array structures and ob...
sebastian/object-reflector         1.1.1  Allows reflection of object attri...
sebastian/recursion-context        3.0.0  Provides functionality to recursi...
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in f...
sebastian/version                  2.0.1  Library that helps with managing ...
sentry/sentry                      1.6.2  A PHP client for Sentry (http://g...
stecman/symfony-console-completion 0.7.0  Automatic BASH completion for Sym...
symfony/browser-kit                v3.3.6 Symfony BrowserKit Component
symfony/console                    v3.3.6 Symfony Console Component
symfony/css-selector               v3.3.6 Symfony CssSelector Component
symfony/debug                      v3.3.6 Symfony Debug Component
symfony/dom-crawler                v3.3.6 Symfony DomCrawler Component
symfony/event-dispatcher           v3.3.6 Symfony EventDispatcher Component
symfony/finder                     v3.3.6 Symfony Finder Component
symfony/polyfill-mbstring          v1.4.0 Symfony polyfill for the Mbstring...
symfony/process                    v3.3.6 Symfony Process Component
symfony/yaml                       v3.3.6 Symfony Yaml Component
theseer/tokenizer                  1.1.0  A small library for converting to...
webmozart/assert                   1.2.0  Assertions to validate method inp...
yiisoft/yii2                       2.0.12 Yii PHP Framework Version 2
yiisoft/yii2-bootstrap             2.0.6  The Twitter Bootstrap extension f...
yiisoft/yii2-composer              2.0.5  The composer plugin for Yii exten...
yiisoft/yii2-debug                 2.0.9  The debugger extension for the Yi...
yiisoft/yii2-mongodb               2.1.4  MongoDB extension for the Yii fra...

#### Suite configuration:

```yml
actor: ApiTester
coverage:
    remote: false
modules:
    enabled:
        - REST:
            depends: PhpBrowser
            url: http://%SERVICE_NAME%:%CONTAINER_PORT%
        - MongoDb:
            dsn: "mongodb://%MONGO_ADDRESS%/eqstat"
            populate: false
            cleanup: false
```

**Comment by Naktibalda** [comment]
Does it cause any issues to you?

Request is made here:
https://github.com/Codeception/Codeception/blob/2.3.4/src/Codeception/Coverage/Subscriber/LocalServer.php#L159
in order to ensure that code coverage cookies are set to correct domain name.

**Comment by vitalyzhakov** [comment]
Thanks for fast answer!

bq. Does it cause any issues to you?
Yes, my application does not have `/` page, request to this URL records error.

Also, I think, it may increase test time significantly.

bq. in order to ensure that code coverage cookies are set to correct domain name
But I see request per each test.

**Comment by Naktibalda** [comment]
#4577
