### ISSUE TITLE
Wrong link to download codecept.phar

### ISSUE THREAD

**Issue by mariorez** [Codeception/Codeception#4443]
#### What are you trying to achieve?
Download the `codecept.phar` for PHP-5 from "[Installation - PHAR for PHP 5.4+](http://codeception.com/thanks_php5)" page by clicking in "**Click here**" link.

#### What do you get instead?
This link has downloaded the `codecept.phar`  for **PHP-7** instead.

**Comment by Naktibalda** [comment]
Thanks, I updated the links.
