### ISSUE TITLE
Multiple global variables in cest tests

### ISSUE THREAD

**Issue by Paintras** [Codeception/Codeception#4452]
Good day,
So I got multiple function withing my cest file. I want to run them on they own or as a whole and I want them to share global variables like like $failCount, ( I run codeception commands like $I->click() in try and when it give me exception the tests doesnt end, but increment $failCount instead ) $aCount ( number of $I->click() per tests) etc.
I have get them globally via _inject method:
```php
protected $aCount;
protected $aCountTotal;
protected $delayAfterTest;
protected $notAfter;

protected function _inject($aCount = 0,$aCountTotal = 0, $delayAfterTest = 4, $notAfter = false)
{
    $this->aCount = $aCount;//<a> count for one section of test
    $this->aCountTotal = $aCountTotal;//total <a> count
    $this->delayAfterTest = $delayAfterTest;//delay between sections of test ( not needed )
    $this->notAfter = $notAfter;//after a whole test is done this bool redirects us to summary of test
}
```
I know that if I want like like 10 globally variables, passing them all in _inject is not a good solution. I cannot include _bootstrap file in my cest test. Is there some other way to get global variables that I can work with them in whole test ?

example:
at the end of every section of test or after running whole cest I call _after method to get output summary of test(tests).
```php
public function _after(AcceptanceTester $I)
{
    if(!$this->notAfter)//prints summary of test section
    {
        $this->aCountTotal += $this->aCount;
        $I->expect("So far you have clicked on {$this->aCountTotal} of 89 <a>");
        $I->dontSee("#404");
        $I->wait($this->delayAfterTest);
    }
    else//prints summary of whole test
    {
        $totalVisible = 66;
        print("You have clicked on {$this->aCountTotal} of 89 <a> on home screen");
        print("\n23 of them are not visible");
        print("\nSo you have clicked on {$this->aCountTotal} of {$totalVisible} <a> that are visible");
        print("\nTwo of elements that are not present in the tests are Inveo Reference and mobile toggle search\n");
    }
}
```

BTW: there are just few variables implemented in solution posted above.
Thank you for all kind of help on how to improve my code.

**Comment by Paintras** [comment]
Thing that I was looking for was making public static variable and than call self::$myVar every time I need it. Is it secure to use static in simple tests like this ? I will wait if someone will write some better solution. If not issue would be closed.

**Comment by DavertMik** [comment]
I think you should make a helper and make those variables as public
Then inject a helper and get access to them. 

Moreover I think all your logic, like:

```php
    if(!$this->notAfter)//prints summary of test section
    {
        $this->aCountTotal += $this->aCount;
        $I->expect("So far you have clicked on {$this->aCountTotal} of 89 <a>");
        $I->dontSee("#404");
        $I->wait($this->delayAfterTest);
    }
    else//prints summary of whole test
    {
        $totalVisible = 66;
        print("You have clicked on {$this->aCountTotal} of 89 <a> on home screen");
        print("\n23 of them are not visible");
        print("\nSo you have clicked on {$this->aCountTotal} of {$totalVisible} <a> that are visible");
        print("\nTwo of elements that are not present in the tests are Inveo Reference and mobile toggle search\n");
    }
```

should be a part of a Helper
