### ISSUE TITLE
Grab selectors from all <a> on a page

### ISSUE THREAD

**Issue by Paintras** [Codeception/Codeception#4458]
Hello,
I am looking for particular things, but finding just workaround. The things is i wanna grab all selector from all <a> elements on page. I have been trying grabMutiple() and _findElements, but it seems that they dont work that way. grabMutiple was seems to be most reasonable function to use but if I call grabMultiple('a','selector/css/xpath') it returns null. Isnt selector an attribute ?
Thank you for suggestion.

**Comment by DavertMik** [comment]
Write your own implementation using Helpers. You can use WebDriver API or BrowserKit API to do that
