### ISSUE TITLE
Code coverage is not working in 2.2.* branch

### ISSUE THREAD

**Issue by pavel-mailpoet** [Codeception/Codeception#4465]
#### What are you trying to achieve?

I am trying to get code coverage.

#### What do you get instead?

No code coverage report whatsoever.

So I created an empty folder with `composer.json` in it. There is only one requirement:
```json
{
  "require-dev": {
    "codeception/codeception": "2.2.*"
  }
}
```
Then I run these commands and before running the last one I update the config to enable code coverage as you can see in the details bellow.
```bash
$ composer install
$ ./vendor/bin/codecept bootstrap
$ ./vendor/bin/codecept generate:test unit A
$ ./vendor/bin/codecept run unit ATest --coverage
```

You can see the output here:
```
$ ./vendor/bin/codecept run unit ATest --coverage -vvv
Codeception PHP Testing Framework v2.2.12
Powered by PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

  Rebuilding UnitTester...

Unit Tests (1) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Asserts, \Helper\Unit
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ ATest: Me (0.01s)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 134 ms, Memory: 8.00MB

OK (1 test, 0 assertions)
```

But if I update the required version of Codeception to 2.3 it starts working:
```
$ vim composer.json
$ composer update
$ ./vendor/bin/codecept run unit ATest --coverage
Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

Unit Tests (1) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ ATest: Me (0.01s)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 729 ms, Memory: 12.00MB

OK (1 test, 0 assertions)


Code Coverage Report:
  2017-08-23 08:09:14

 Summary:
  Classes:        (0/0)
  Methods:        (0/0)
  Lines:          (0/0)

Remote CodeCoverage reports are not printed to console
```

### Details

* Codeception version: 2.2.12
* PHP Version: 
PHP 7.1.8 (cli) (built: Aug 14 2017 09:55:36) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
* Operating System: MacOS
* Installation type: Composer
* Suite configuration: default configuration 

### Config file

It is the config file which was generated by codeception bootstrap command with the only change which is enabling the coverage.

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
```

**Comment by pavel-mailpoet** [comment]
I found out that if I go to this line: https://github.com/Codeception/Codeception/blob/42e44f0693c3d6fc3f2f2cba349687ab4b489308/src/Codeception/Command/Run.php#L260

And change it to: `$userOptions['coverage'] = true;` the coverage is generated in version 2.2.12

**Comment by Naktibalda** [comment]
2.2 branch won't be fixed.

**Comment by Naktibalda** [comment]
The line that you changed isn't actually executed if you specify `--coverage` option, it is only used when you specify a format specific option, e.g. `--coverage-html`, but you haven't used such option in your example. Also that code hasn't changed in 2.3 branch.

Most likely you have some kind of configuration error, code coverage worked in 2.2 branch, when it was supported.

**Comment by pavel-mailpoet** [comment]
I understand what you're saying, but I don't see how it should be my config. The config is just autogenerated with no modifications. And the same config works for 2.3 branch.
