### ISSUE TITLE
makeScreenshot() does not make screenshot in with certain strings

### ISSUE THREAD

**Issue by Paintras** [Codeception/Codeception#4467]
Hello guys,
So I have been using makeScreenshot() method to get screen after exception is thrown and I wanted to get name of my .jpg as accurate as possible. I thought that i will get name of my screenshot in this format "y/m/d h:i:s Exception{x}" So i tried this just for testing: 
$shot = date("Y/m/d")  . "Exception" .  $failCount;
print($shot);
$I->makeScreenshot($shot);

It does not save any .jpg to my debug folder. If I call this method with just plain string no dateTime with same format it also does no make screenshot. Is there some character count limitation or some forbidden chars that i cannot use in this method. How to workaround it ?
Thank for all possible help.

**Comment by Naktibalda** [comment]
i think that it is mostly limited by your filesystem.
`/` is a well known directory separator, so there is no surprise that you can't use it in a filename.
Using `:` could cause issues too.

Don't use any separators or use a safe separator like `-`.

**Comment by Paintras** [comment]
Thank you!!!
Problem was in separator. Closing issue.
