### ISSUE TITLE
Regex format in grabFromCurrentURL()

### ISSUE THREAD

**Issue by Paintras** [Codeception/Codeception#4470]
Hello,
I got very simple question. 
$I->amOnPage("/nabytek");
print($I->grabFromCurrentURL('#[a-z]{0,7}#'));
$I->pauseExecution();

Why is this not working ? I've tried different delimiters with no luck. It always says: a regex parameter is required or that it doesnt match pattern.

Thank you for help

**Comment by Naktibalda** [comment]
What is missing in documentation is that there must be a subpattern/capturing group in the pattern.
So your code should be
```php
$I->grabFromCurrentURL('#([a-z]{0,7})#')
```
