### ISSUE TITLE
CSS or XPath locator is malformed

### ISSUE THREAD

**Issue by Anasf** [Codeception/Codeception#4474]
@Naktibalda following up on my comment posted on https://github.com/Codeception/Codeception/issues/2960#issuecomment-325919313

Fetching text from specific element and then i `canSee` command to assert.

fetching value from `<div class="className"> 0 </div>`
command: `$var = $I->grabTextFrom(className);`

and then

assertion: $I->canSee('0', $var);

console is showing: `CSS or XPath locator is malformed`

**Comment by Naktibalda** [comment]
It is equivalent to `$I->canSee('0', ' 0 ')`, right?
' 0 ' is not a valid selector.

Correct assertion is `$I->canSee('0', '.className');`

**Comment by Anasf** [comment]
ooh! right right! i misunderstand the command `canSee`

Apologies for that, Thanks!

Hence closing.
