### ISSUE TITLE
Cannot unset variables from a Stub

### ISSUE THREAD

**Issue by timbroder** [Codeception/Codeception#4489]
#### What are you trying to achieve?

1. Create a Stub object
1. Set a variable on it. Either from when I define the stub, or later on in a test
1. `unset()` that variable (happens in the code under test)
1. See that the variable has been unset 

#### What do you get instead?

The variable is hanging around in the Stub's `_values`

```
  #_values: array:1 [
    "hello" => "world"
  ]
```

> Provide console output if related. Use `-vvv` mode for more details.

```bash
php codecept run unit Codeception/Util/StubTest::testUnsettingEmpty
Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

Unit Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✖ StubTest: Unsetting empty (0.02s)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 201 ms, Memory: 13.25MB

There was 1 failure:

---------
1) StubTest: Unsetting empty
 Test  tests/unit/Codeception/Util/StubTest.php:testUnsettingEmpty
Failed asserting that true is false.
#1  /Users/timbroder/workspace/tim/codeception/mine/tests/unit/Codeception/Util/StubTest.php:429
#2  StubTest->testUnsettingEmpty
#3  /Users/timbroder/workspace/tim/codeception/mine/codecept:36

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
```
> Provide test source code if related

Add the following test to `StubTest`

```php
    public function testUnsettingEmpty()
    {
        $dummy = Stub::makeEmpty('DummyClass');
        $this->assertInstanceOf('DummyClass', $dummy);

        $dummy->hello = 'world';
        $this->assertEquals('world', $dummy->hello);

        unset($dummy->hello);
        $this->assertFalse(isset($dummy->hello));
        $this->assertNotEquals('world', $dummy->hello);
    }
```
### Details

* Codeception version: 
* PHP Version: 2.3.5
* Operating System: OSX 10.12.6
* Installation type: Composer
* List of installed packages [gist](https://gist.githubusercontent.com/timbroder/c1228c77713d87509a74b69f94f0de68/raw/d2ef8a716e35be4082dd727ad79be21e9959c045/gistfile1.txt "gist")
* Suite configuration: Using Codeceptions tests

**Comment by Naktibalda** [comment]
You reported a bug in DummyClass.

This happens because DummyClass has magic __set method, but no __unset.
https://github.com/Codeception/Codeception/blob/2.3/tests/data/DummyClass.php#L47

Adding `__unset` to DummyClass makes your test pass:
```php
    public function __unset($name) {
        if ($this->__isset($name)) {
            unset($this->properties[$name]);
        }
    }
```
