### ISSUE TITLE
Custom Framework Connector Docs?

### ISSUE THREAD

**Issue by kzap** [Codeception/Codeception#4492]
#### What are you trying to achieve?
Create a custom connector and module for my framework for integration testing

#### What do you get instead?
I can not find any reliable docs on how to do this aside from trying to read the existing Framework modules and connectors

Why was the documentation regarding the Universal connector and how to integrate a framework that is not supported removed in this commit? https://github.com/Codeception/Codeception/commit/51aa385bc69cb326af58a9a3ff94c5f60ccc7114#diff-e21e3d58bf4fe280214e66d78895ae62

I can not find that it was moved elsewhere. I really could use a guide on how to integrate with an application in the most basic way.

The most recent I could find was:
- http://codeception.com/docs-1.8/05-FunctionalTests
- http://codeception.com/01-24-2013/connecting-php-frameworks-1.html

Thank you

**Comment by DavertMik** [comment]
@kzap sorry, there is no general advice on implementing custom connector. Universal connector is the shittiest thing you can ever imagine for integration :) Frameworks are so custom and they can be so complicated so we can't provide any actionable advice that would fit to everyone.

The one I can propose to you: select the framework which is more close to yours and check its connector. 
If you use HttpFoundation component of Symfony, check Symfony and Silex integration. If you have DI and ActiveRecord - check Yii2 or Phalcon connectors, etc. 

Just look into all connectors and find the most suitable one. Start by customizing it...
Generally you need to handle requests into a framework inside `doRequest` method. However, there are lots of edge cases like dealing with sessions, headers, database, which must be overridden by the connector.

**Comment by Naktibalda** [comment]
@kzap if you have any issues with implementation, you are welcome to ask for help.

**Comment by kzap** [comment]
I was able to make my implementation work but I wish it was easy available in the docs the information here and the one that was removed from 1.8

I will agree that the UniversalConnector is not ideal but its a starting point and that matters :)

Please consider for docs if possible

**Comment by Naktibalda** [comment]
You are welcome to contribute that kind of documentation.

**Comment by StalkAlex** [comment]
@kzap could you give some information how you managed to include custom connector into Codeception, please?
