### ISSUE TITLE
Different directory structure for tests

### ISSUE THREAD

**Issue by enumag** [Codeception/Codeception#4507]
I'd like to have tests outside of the normal tests directory to keep them together with the bundles. Something like this:

```
src/
    Bundle/
        ClientBundle/
            Entity/
            Controller/
            Tests/
                Unit/
                Functional/
                Acceptance/
        ProductBundle/
            Entity/
            Controller/
            Tests/
                Unit/
                Functional/
                Acceptance/
```

Is somethink like this possible with Codeception? Or is it a bad idea for some reason?

**Comment by Naktibalda** [comment]
This was removed from http://codeception.com/for/symfony after it was announced that Symfony is getting rid of bundles in 4.0

https://github.com/Codeception/codeception.github.com/blob/e222ac8b15f97b83342c7a74000b6fd79086aa65/for/symfony.md#running-it-all-together

To execute all tests at once with codecept run you should include bundle configurations into global configuration file codeception.yml in the root of a project:
```yml
include:
    - src/*Bundle
```
Then running codeception tests from root directory will execute tests from all bundles as well as acceptance tests.

**Comment by enumag** [comment]
@Naktibalda 

> Symfony is getting rid of bundles in 4.0

What? Where can I read more about this? Bundles are a natural thing to use when you have a large application and need to split it to some smaller units. What should I use instead for splitting the app?

**Comment by Naktibalda** [comment]
http://fabien.potencier.org/symfony4-monolith-vs-micro.html#bundle-less-applications
http://fabien.potencier.org/symfony4-directory-structure.html

Please read other blog posts as well.

**Comment by enumag** [comment]
@Naktibalda Thanks for the links. But from that it is really unclear how to split the application without bundles. I mean this is not good:

```
src/
    Entity/
        100+ entities
    Controller/
        200+ conttrollers
```

Even this doesn't feel good because the unrelated contexts are not separated.

```
src/
    Entity/
        Client/
           ~10 entities
        Product/
           ~10 entities
    Controller/
        Client/
           ~10 controllers
        Product/
           ~10 controllers
```

And if I go this way I'm pretty much back to bundles with the disadvantage of not having separate configuration for each bundle:

```
src/
    Client/
        Entity/
            ~10 entities
        Controller/
            ~10 controllers
    Product/
        Entity/
           ~10 entities
        Controller/
           ~10 controllers
```

Any recommendations which way to go?

**Comment by Naktibalda** [comment]
I don't use Symfony framework, you have to ask Symfony guys.
For now you can use `include` option to run all your tests.

**Comment by enumag** [comment]
Alright, thanks!
