### ISSUE TITLE
Yii2. Resetting app instance between requests causing problem for mocking

### ISSUE THREAD

**Issue by StalkAlex** [Codeception/Codeception#4508]
Let's say I have registration process for users. There is also side module in system let's call it "checker", it checks some specific files that user upload during registration, this is time consuming process.

I have several functional tests with different scenarios for registration process. During those tests I want to mock this dependency, but behavior of this dependency should be changed in each test. I can mock it in test config now. But it will be same for all suite.

Here's almost working example:
```php
//begin test
//mocking checker
Yii::$app->set('checker', new SpecificScenarioTestChecker());
$I->amOnPage('first');
//some checks
$I->amOnPage('second');
//more checks
//end test
```

Problem of this code lays in second request, it doesn't use mocked version anymore. This [line](https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Lib/Connector/Yii2.php#L167) causing this problem, it changes app instance that was configured during test initialization to null value after first request, then it being initialized again with file config only values [here](https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Lib/Connector/Yii2.php#L53)

Is there any other solutions to this problem or can it be refactored/improved somehow?

**Comment by samdark** [comment]
If behavior is to be changed for each test it makes sense to mock it each time right in the test method.

**Comment by StalkAlex** [comment]
@samdark this is a problem and this is what I wanted to achieve. I showed the way how I thought it should be working, but it's not. Please show me how.

**Comment by samdark** [comment]
Do it in the test itself, not in the init sequence.

**Comment by StalkAlex** [comment]
@samdark yes, that was example from the test itself, it's not working.  What do you mean?

**Comment by StalkAlex** [comment]
@samdark sorry your advice sounds strange, because that's I what created issue about, you either didn't read carefully or I didn't describe enough to be understood. But either way problem still exists, dynamically mocked components work only for a half of ONE test, for the first request only then it "magically" disappers inside Codeception process. It's strange and not expected behaviour. I did a research, found line that causing this problem. So pease at least do not close issue, maybe someone else know the workaround no matter would it be fixed or not within Codeception itself.

**Comment by Naktibalda** [comment]
Looks like a valid issue to me.

**Comment by StalkAlex** [comment]
Any news on this? @Naktibalda  @DavertMik 

Is there any temporary solutions at least?

**Comment by StalkAlex** [comment]
My idea is preserve not only [db](https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Lib/Connector/Yii2.php#L69) instance and then restore it, but do same thing with all components. Is it ok, @samdark @Naktibalda?

**Comment by SamMousa** [comment]
@StalkAlex in the latest version(s) we no longer reset the application between each request.
Instead only the request component and the response component are reset (and optionally components you configure).

Could you confirm this bug can be closed?
