### ISSUE TITLE
`see` assertion fails when source code contains `<` in JS code

### ISSUE THREAD

**Issue by tobias-kuendig** [Codeception/Codeception#4509]
When asserting `$I->canSee('XYZ');` in an acceptance test using PhpBrowser the assertion returns `false` even though the page contains `XYZ`. 

The problem in my case was that my page contained code simillar to the following:

```html
<script>
    if (a <= b) {
        // ...
    }
</script>
<p>XYZ</p>
```

When the `getNormalizedResponseContent` gets called, [all HTML tags are removed with `strip_tags`](https://github.com/Codeception/Codeception/blob/758dd0d30fa7dd08b3eec6e444a162985b09c708/src/Codeception/Lib/InnerBrowser.php#L1880). `strip_tags` interprets the `<=` itself as a start tag and removes everything that follows the operator. Because of this problem the `XYZ` text cannot be found since it is removed from the response content.

I suggest removing the `script` tags manually before using `strip_tags`. For possible solutions see https://stackoverflow.com/a/22782081.

**Comment by DavertMik** [comment]
Interesting issue and looks like a nice solution. Could you prepare a patch and a test for this case?

**Comment by tobias-kuendig** [comment]
Sure, see https://github.com/Codeception/Codeception/pull/4510
