### ISSUE TITLE
Add ordering for suites

### ISSUE THREAD

**Issue by LiamBest** [Codeception/Codeception#451]
I need to run suites in a certain order, however there does not appear to be functionality for this.

I have the same issue with the tests.. but I get around it by naming the files in a certain way.

(Relates to: https://github.com/Codeception/Codeception/issues/418)

**Comment by wasmithee** [comment]
Can we use @depends annotations across multiple CEST classes?

**Comment by buffcode** [comment]
I think it is kind of useful when thinking of "fast-fail".
In our CI system we run all suites, but unit tests are much faster the the acceptance tests.

I would like to order the `unit` suite first, so any failure aborts further load-intensive tests as they might or might not produce correct results, based on the correctness of the units.

**Comment by Ryuske** [comment]
I have the same use-case as @buffcode. I would like the tests to fail as quickly as possible. So my ideal order would be unit -> api -> functional -> acceptance. It's literally just so I waste the least amount of time possible waiting for tests to finish if one of them is going to fail.

**Comment by Faryshta** [comment]
It also makes sense for dependencies

If the unit test `UserTest:testCreate` fails, the api test `ProfileCest:register` will fail too.

**Comment by nicholascus** [comment]
I have usecase for that too. I have module level tests which restore database dumps, which are shared across multiple test classes. I want all tests working on the same database dump to be executed in one go, on top of that I would love to have option to randomize order in the group. 

I haven't been looking at how that's implemented in Codeception yet, but I'll get to that for sure in the nearest couple of months.

**Comment by ebuildy** [comment]
As a developer, we want save time, using ``fast-fail``, when we are working on a particular feature, we want to run in priority tests influenced by this feature.

Also, we want to run "heavy" tests at the end.

End, we may want run suites in a particular order "register" / "login" because we are lazy to make SQL dump ^^

**Comment by matthiasnoback** [comment]
Talking with @DavertMik I learned about this solution to determine the order of the suites to run:

```bash
vendor/bin/codecept run unit,integration,functional
```

Personally, I like to combine this with using `@group` annotations above test/cest classes to run tests from all suites that are in the same group (i.e. the feature I'm working on):

```bash
vendor/bin/codecept run unit,integration,functional -g [name-of-the-group]
```

Combined with `--fail-fast`, this can give you quite a fast feedback loop.
