### ISSUE TITLE
Interface 'PHPUnit_Framework_Test' not found

### ISSUE THREAD

**Issue by damian-sikora-droptica** [Codeception/Codeception#4513]
For PHPUnit 6 following change has been made some time ago:
https://github.com/sebastianbergmann/phpunit/commit/2614932462c37a4c01b052bca724a122ee3320dc#diff-85a1dcc52183a520481ce1e1ed774651

In Codeception code this change is not applied and following error appears:
```
Fatal error: Interface 'PHPUnit_Framework_Test' not found in /<composer_path>/vendor/codeception/codeception/src/Codeception/TestInterface.php on line 7
ERROR: Interface 'PHPUnit_Framework_Test' not found 
in /<composer_path>/vendor/codeception/codeception/src/Codeception/TestInterface.php:7
```

* Codeception version: 2.3.5
* PHP Version: 7
* PHPUnit: 6.2.4

**Comment by Naktibalda** [comment]
We've got it covered [here](https://github.com/Codeception/Codeception/blob/2.3/shim.php#L30).
```php
class_alias('PHPUnit\Framework\Test', 'PHPUnit_Framework_Test');
```
The only reason for it to have no effect I can imagine is that you have class `PHPUnit_Framework_TestCase` defined in your code base.

**Comment by damian-sikora-droptica** [comment]
Yes, it is really working correctly. I am setting up robo-paracept and the autoload.php from codeception was not loaded in robo file so the shim.php file was not included.
Thanks for the answer
