### ISSUE TITLE
YII2 + REQUEST_URI

### ISSUE THREAD

**Issue by eymerich** [Codeception/Codeception#4514]
I'm experiencing troubles when I need to use uri parameter from Request:
[yii\base\InvalidConfigException] Unable to determine the request URI. 

Looking at YII2 module I noticed that server variables are build in _before method, is there a motive why REQUEST_URI is not configured there?
https://github.com/Codeception/Codeception/blob/4e747f41438921488128a60f9dee2153c26b6666/src/Codeception/Module/Yii2.php#L176-L181

I mean a line of the kind:
`'REQUEST_URI'     => parse_url($entryUrl, PHP_URL_PATH) ?: '/',`

**Comment by Naktibalda** [comment]
REQUEST_URI is set in doRequest method of Yii2 connector: https://github.com/Codeception/Codeception/blob/4e747f41438921488128a60f9dee2153c26b6666/src/Codeception/Lib/Connector/Yii2.php#L108

**Comment by samdark** [comment]
What type of test are you trying? How is it configured?

**Comment by eymerich** [comment]
I'm working on tests for our portal based on YII2 advanced template, we have started with Unit Tests so I stumbled upon this issue.

**Comment by SamMousa** [comment]
@eymerich have these issues been resolved in the latest codeception version(s)?

**Comment by eymerich** [comment]
@SamMousa sorry for the late answer, seems like it's resolved, perhaps @cccaballero wants to keep it open or open a new issue.
