### ISSUE TITLE
How do I get metadata from my interface?

### ISSUE THREAD

**Issue by xiaoxing598** [Codeception/Codeception#4515]
How do I get the metadata returned by the interface?

```
$this->I->wantTo('接口正常返回');
$this->I->sendGET('/api/classifications');
$this->I->seeResponseJsonMatchesJsonPath('$.return_msg.rows[*].name');
```
JsonPath can only determine whether a path exists, but can not determine the corresponding value of the path, and whether the same expectations.

**Comment by Naktibalda** [comment]
You can use [seeResponseContainsJson](http://codeception.com/docs/modules/REST#seeResponseContainsJson) and [seeResponseMatchesJsonType](http://codeception.com/docs/modules/REST#seeResponseMatchesJsonType) methods for validating values.

If you want to retrieve value for using elsewhere in your test, then use [grabDataFromResponseByJsonPath](http://codeception.com/docs/modules/REST#grabDataFromResponseByJsonPath) method.

**Comment by xiaoxing598** [comment]
But seeResponseContainsJson can only match all the text, I just want to match a value inside is not correct, not just it exists or not.

Would you like to give me a demonstration of your usage?
