### ISSUE TITLE
Codeception BDD Tabular - Got failed "[PHPUnit\Framework\Exception] Undefined variable: node"

### ISSUE THREAD

**Issue by anhvuong123** [Codeception/Codeception#4533]
Hi everyone,
I've tried to work with Table BDD as CodeCeption mention. But get the exception when running is "[PHPUnit\Framework\Exception] Undefined variable: node". 
![codecepttabular](https://user-images.githubusercontent.com/30453490/30778299-4a5e4680-a0fc-11e7-9ddd-3d3803d66889.png)

### Please help me via the case. 
Here're the steps that I define & run:
===
Step1: php codecept.phar bootstrap
Step3: php codecept.phar generate:feature acceptance 3_TabularBasic
Step4: I put into the generated file "3_TabularBasic.feature" follow to example http://codeception.com/docs/07-BDD#Tables:
Feature: Feature Tabular
  In order to work with Tabular feature of CodeCeption.
  As a customer
  I want to be able to view multi-books. 
Scenario: Test Tabular
  Given i have products in my cart
    | name         | category    | price  |
    | Harry Potter | Books       | 5      |
    | iPhone 5     | Smartphones | 1200   |
    | Nuclear Bomb | Weapons     | 100000 |

Step4: Put the code mention in http://codeception.com/docs/07-BDD#Tables into the file "AcceptanceTester.php"
/**
     * @Given i have products in my cart
     */
    public function iHaveProductsInCart(\Behat\Gherkin\Node\TableNode $products)
    {
        // iterate over all rows
        foreach ($node->getRows() as $index => $row) {
            if ($index === 0) { // first row to define fields
                $keys = $row;
                continue;
            }
            $this->haveRecord('Product', array_combine($keys, $row));
        }
    }

Step5: php codecept.phar gherkin:snippets acceptance 3_TabularBasic.feature
==> Then, got an exeption: "[PHPUnit\Framework\Exception] Undefined variable: node" 

### Details

* Codeception version: 2.3.5
* PHP Version: 7.1.9
* Operating System: Windows10
* Installation type: Phar

**Comment by Naktibalda** [comment]
Please run your test with -vvv flag to get a complete stacktrace.

**Comment by anhvuong123** [comment]
Hi Naktibalda,

I follow to your suggest and get the log. Please help me to take a look cia the case. Many thanks

C:\Users\Administrator\Desktop\Prepare for Automation Tasks Java_24_08_2017\Project3>php codecept.phar run acceptance 3_TabularBasic.feature -vvv
Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

  Rebuilding AcceptanceTester...

Acceptance Tests (1) ---------------------------------------------------------------------------------------------------
Modules: PhpBrowser, \Helper\Acceptance
------------------------------------------------------------------------------------------------------------------------
Feature Tabular: Test Tabular
Signature: 3_TabularBasic:Test Tabular
Test: tests\acceptance\3_TabularBasic.feature:Test Tabular
Scenario --
 In order to work with Tabular feature of CodeCeption.
 As a customer
 I want to be able to view multi-books.
 Given i have products in my cart
   | name         | category    | price  |
   | Harry Potter | Books       | 5      |
   | iPhone 5     | Smartphones | 1200   |
   | Nuclear Bomb | Weapons     | 100000 |
 ERROR

------------------------------------------------------------------------------------------------------------------------


Time: 1.24 seconds, Memory: 14.00MB

There was 1 error:

---------
1) Feature Tabular: Test Tabular
 Test  tests\acceptance\3_TabularBasic.feature:Test Tabular

  [PHPUnit\Framework\Exception] Undefined variable: node


Scenario Steps:

 4. // I want to be able to view multi-books.
 3. // As a customer
 2. // In order to work with Tabular feature of CodeCeption.

C:\Users\Administrator\Desktop\Prepare for Automation Tasks Java_24_08_2017\Project3\tests\_support\AcceptanceTester.php:139
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/Test/Gherkin.php:142
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/Test/Gherkin.php:88
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/Test/Test.php:87
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestSuite.php:744
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/PHPUnit/Runner.php:106
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/SuiteManager.php:157
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/Codecept.php:188
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/Codecept.php:157
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/Command/Run.php:341
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/vendor/symfony/console/Command/Command.php:264
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/vendor/symfony/console/Application.php:874
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/vendor/symfony/console/Application.php:228
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/vendor/symfony/console/Application.php:130
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/src/Codeception/Application.php:103
phar://C:/Users/Administrator/Desktop/Prepare for Automation Tasks Java_24_08_2017/Project3/codecept.phar/codecept:36
C:\Users\Administrator\Desktop\Prepare for Automation Tasks Java_24_08_2017\Project3\codecept.phar:7


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

**Comment by nshelms** [comment]
You have your steps mixed up. `codecept gherkin:snippets` should be used to retrieve what you would paste in AcceptanceTester.php (unless it exists). If it already exists then the output should read `All Gherkin steps are defined. Exiting...`

I just tried running your sample example. Everything seemed to work fine. However my php version was 7.1.8. Check to make sure your indentation is correct inside your feature file. It should look like the following:
```
Feature: 3_TabularBasic
  In order to work with Tabular feature of CodeCeption.
  As a customer
  I want to be able to view multi-books.
  
  Scenario: Test Tabular
  
  Given i have products in my cart
    | name | category | price |
    | Harry Potter | Books | 5 |
    | iPhone 5 | Smartphones | 1200 |
    | Nuclear Bomb | Weapons | 100000 |
```

**Comment by anhvuong123** [comment]
Thank nshelms,

It is resolved.

**Comment by anhvuong123** [comment]
Thank nshelms and Naktibalda for valuable suggestion

**Comment by anhvuong123** [comment]
Thank nshelms and Naktibalda for valuable suggestion
