### ISSUE TITLE
Codeception not able to load  Class 'Phalcon\Mvc\MongoCollection' using Phalcon Loader

### ISSUE THREAD

**Issue by bkvaiude** [Codeception/Codeception#4536]
Hello Guys,

I'm using PHP7 and phlacon3.2.2 for my project.
I have written few test cases for the model and run them using following steps

> `vendor/bin/codecept generate:test unit Timezone`

> `vendor/bin/codecept run unit`

> Unit Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> - TimezoneTest: Some featurePHP Fatal error:  Class 'XXX\Models\Timezone' not found in /home/xx/Documents/projects/xxx/tests/unit/TimezoneTest.php on line 17

> Fatal error: Class 'xx\Models\Timezone' not found in /home/xxx/Documents/projects/xxx/tests/unit/TimezoneTest.php on line 17

Don't know the reason. Then loaded the class using `require` function and got following output

> Codeception PHP Testing Framework v2.3.5

> Powered by PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

> PHP Fatal error:  Class 'Phalcon\Mvc\MongoCollection' not found in /home/xxx/Documents/projects/falcon/app/models/Timezone.php on line 5

> Fatal error: Class 'Phalcon\Mvc\MongoCollection' not found in /home/xxx/Documents/projects/falcon/app/models/Timezone.php on line 5

I was hoping that phalcon will load the classes using loader (at beginning level), but it was not working in that way.

I would appreciate the help and guidance on this issue.

**Comment by Naktibalda** [comment]
Unless your project uses composer autoloader, you have to set up it manually.

To achieve that you have to [enable bootstrap files](http://codeception.com/docs/reference/Configuration) by adding
```yml
settings:
    bootstrap: _bootstrap.php
```
to codeception.yml file.
Then create _bootstrap.php files in tests directory and in each suite and finally include and setup the loader in tests/unit/_bootstrap.php file.

**Comment by bkvaiude** [comment]
Thanks. After updating the config yml files, it started working. But got the new issue.

I'm using the MongoDB and PostgresSql for a project, but now unit test looks for the database on the postgres DB server.

I have written the test cases for the MongoDB model

then later I tried to comment all reference to postgres database and test the MongoDB Model

```
root@098ca66ed23b:/var/www/html# vendor/bin/codecept run unit --steps
Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

Unit Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
E TimezoneTest: Get source (0.00s)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 138 ms, Memory: 10.00MB

There was 1 error:

---------
1) TimezoneTest: Get source
 Test  tests/unit/Model/TimezoneTest.php:testGetSource
                                                 
  [Error] Class 'App\Models\Timezone' not found  
                                                 

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
zend_mm_heap corrupted
root@098ca66ed23b:/var/www/html# 
```

If I tried to run test without namespace (which is working into the phalcon controller)
```
Unit Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
E TimezoneTest: Get source (0.00s)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 123 ms, Memory: 10.00MB

There was 1 error:

---------
1) TimezoneTest: Get source
 Test  tests/unit/Model/TimezoneTest.php:testGetSource
                                                           
  [Error] Class 'App\Test\Unit\Models\Timezone' not found  
                                                           

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
zend_mm_heap corrupted

```

Can you please guide me to write a unit test case for MongoDB model in phalcon3.2.2?

**Comment by Naktibalda** [comment]
You still have autoloading issue.

@sergeyklay Can you help here?

**Comment by bkvaiude** [comment]
Hey Guys,

Sorry for bothering you.
Thanks for your quick help.
I was expecting that all phalcon framework classes are automatically available at Test Class level.
Unfortunately, it doesn't work in that way, I will appreciate if you comment on that.

I have explicitly added the entry in the `config/loader.php`

```
$loader->registerNamespaces([
    'Phalcon' => BASE_PATH.'/vendor/incubator/Library/Phalcon/',
    'App\Models' => $config->application->modelsDir
]);
```
