### ISSUE TITLE
How to run Phantomjs or Selenium Server by Codeception (without run them by command line directly)

### ISSUE THREAD

**Issue by anhvuong123** [Codeception/Codeception#4538]
Hi everyone,

I've tried with cmd to start Phantomjs or seleniumserver first, then run codeception. Everything is good.
But i wonder if it has the way to run them once time as the way codeception start Phantomjs or selenium server then run test for convenient (without start them by open cmd, then call codeception to make 2 steps).

Please help me via the case if you have any better solution.

Many thanks

**Comment by DavertMik** [comment]
Use RunProcess extension http://codeception.com/extensions#RunProcess
