### ISSUE TITLE
Use "click" over a ext button don't work

### ISSUE THREAD

**Issue by ignachiou** [Codeception/Codeception#4552]
#### What are you trying to achieve?

I'm trying to save an ext form clicking this "guardar" button.

#### What do you get instead?
The button could not be located. This is the button I should click http://take.ms/oirny , http://take.ms/KTPSF 

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
http://take.ms/pZh1l
```
> Provide test source code if related

```php
<?php

$name = 'Carolina';

class ContactCrudCest
{
    public function _before(AcceptanceTester $I)
    {
		$I->am('Tester');
		$I->wantTo('Add a new contact');
		$I->lookForwardTo('Create a new contact in Alegra');
		$I->amGoingTo('Login into my account');
		$I->amOnPage('/user/login');
		$I->see('ingresa');
		$I->fillfield('#email','salvador.salvatierra@alegra.com');
		$I->fillfield('#password','20197850');
		$I->click('#submit');
		$I->see('Inicio');
    }

    public function _after(AcceptanceTester $I)
    {
    }

    // tests
    public function addContact(AcceptanceTester $I)
    {
		$I->amGoingTo('Entrar al formulario de contacto');
		$I->amOnPage('/client/add');
		$I->see('Nuevo Contacto');
		$I->fillField('#addClient [name="name"]','Carolina');
		$I->fillField('#addClient [name="identification"]','20197850');
		$I->fillField('#addClient [name="email"]','salvador.salvatierra@alegra.com');
		$I->click('#clientIsClientCheckBox-inputEl');
		//$I->canSeeCheckboxIsChecked('#clientIsClientCheckBox-inputEl');
		$I->see('Guardar');
		$I->click('Guardar');//don't find it
		//$I->canSee('Carolina');
']);
		//$I->canSee('Carolina');
    }
	
	public function editContact(AcceptanceTester $I)
	{
		$I->amGoingTo('Editar un contacto');
		$I->amOnPage('/client/edit/id/711');
		$I->see('Editar contacto');
		$I->fillField('#addClient [name="identification"]','3135987');
		$I->click('Guardar'); //dont find it
	}
}
```
### Details

* Codeception version: 2.3.5
* PHP Version: 5.6.24
* Operating System: Win 7
* Installation type: Phar 
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            browser: chrome 
            url: https://app.alegra.com
            restart: true
        - \Helper\Acceptance
```

**Comment by Naktibalda** [comment]
Hint: it is possible that the button is not visible in the Chrome window during testing, try to put `$I->scrollTo('Guardar);` before `click`.
(Similar issue in https://github.com/Codeception/Codeception/issues/4231#issuecomment-303144413)

If this doesn't help, then it is likely to be an issue of Selenium or ChromeDriver. Try using a different browser to check if you get the same error.

**Comment by ignachiou** [comment]
It's ok now, so to use "click" the element should be at the screen literally. Another thing, I use "click" over a checkbox, but I cannot check if the checkbox is checked, what could be the reason if the "click" action works before the checked function? you can see it at the code above.

**Comment by Naktibalda** [comment]
Don't click checkboxes, use `checkOption` instead.
