### ISSUE TITLE
Extending the Examples class

### ISSUE THREAD

**Issue by DreadCube** [Codeception/Codeception#4554]
Hello guys. Is it possible to extend the Examples class? Or do i have to use the @dataprovider (Would also be possible, but not so cool)? Because i have some placeholder values that i need to parse dynamically in runtime:

Example:

`* @example { "MyData": "${\"placeholder\"}$"  }`
`*/`
`public function myTest(Actor $I, \mycustompath\Example $Example) {`
`// Doo Something with $Example`
`}`

**Comment by Naktibalda** [comment]
> Is it possible to extend the Examples class?

Probably not.

**Comment by DavertMik** [comment]
Example value can be get from `$scenario->current()` array:

```php
public function myTest(Actor $I,\Codeception\Scenario $scenario) {
    new \MyExample($scenario->current('example'));
}
```

**Comment by DreadCube** [comment]
Thanks for the answer. Could working for me ;-)
