### ISSUE TITLE
Help needed with dataProvider

### ISSUE THREAD

**Issue by pixelive** [Codeception/Codeception#4555]
#### What are you trying to achieve?
Im using the dataProvider tag to do test for multiple pages. But having some trouble using the helper functions within the dataProvider method. Is this possible? And are there any events fired before the dataProvider method, something like _inject or _before? Looks like the dataProvider method is the first method which is called in my setup.

And are there any alternatives for the dataProvider? I want the use it to retrieve some pages from a database. I have multiple tests using the same provider but it looks a bit slow to me because the tests has to navigate forward and backward through the pages.

So:

Page 1 method 1
Page 2 method 1
Page 1 method 2
Page 2 method 2

Would be faster to have something like:

Page 1 method 1
Page 1 method 2
Page 2 method 1
Page 2 method 2

This prevents the test to navigate on each loop and test. Is this possible?

Simplified example:

```
<?php
   /**
    * @dataprovider pageProvider
    */
    public function checkTitle(AcceptanceTester $I, \Codeception\Example $example)
    {
        $I->amOnPage($example['url']);
        $I->seeInTitle($example['title']);
    }

    /**
     * @dataprovider pageProvider
     */
     public function checkH1(AcceptanceTester $I, \Codeception\Example $example)
     {
         $I->amOnPage($example['url']);
         $I->see($example['title'], 'h1');
     }

    /**
     * @return array
     */
    protected function pageProvider() 
    {
        // Cant use a helper here? and no events fired..?
        return [
            ['url'=>"/", 'title'=>"Welcome"],
            ['url'=>"/info", 'title'=>"Info"],
            ['url'=>"/about", 'title'=>"About Us"],
            ['url'=>"/contact", 'title'=>"Contact Us"]
        ];
    }
```

### Details

* Codeception version: 2.3.6
* PHP Version: 7.0
* Installation type: Composer

**Comment by DavertMik** [comment]
Looks like dataProviders are not a good solution for you. 
In your case I'd just use `foreach` with `canSee` to fail silentely on issues.

```php
foreach ($this->pages as $url => $title) {
        $I->amOnPage($url);
        $I->canSeeInTitle($title);   
}
```

**Comment by pixelive** [comment]
@DavertMik but then you wont get a detailed log with "Page -> Test name" right? And how can we use helper methods within dataProvider?
