### ISSUE TITLE
No docker container builds for 2.3

### ISSUE THREAD

**Issue by JGladykowski-modus** [Codeception/Codeception#4559]
There are no docker container builds for 2.3.6 https://hub.docker.com/r/codeception/codeception/builds/
Latest tag points to 2.2 https://hub.docker.com/r/codeception/codeception/builds/bdhmr9njwacsk4837l6jimn/

You can check it by trying to use updateInDatabase method, from 2.3.6 when using latest image

Did not leave comment there, as comments section looks dead.

**Comment by DavertMik** [comment]
Thanks for pointing out. This should be a top priority to fix.

**Comment by DavertMik** [comment]
Thanks, the image has been rebuilt. Documentation updated https://hub.docker.com/r/codeception/codeception/
