### ISSUE TITLE
InjectionException with step object

### ISSUE THREAD

**Issue by BeardedVage** [Codeception/Codeception#4567]
#### But I got the InjectionException  
 
> There are console output
Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 6.4.0 by Sebastian Bergmann and contributors.

                                                                               
  [Codeception\Exception\InjectionException]                                   
  Failed to inject dependencies in instance of 'CreateUserCest'. Failed to cr  
  eate instance of 'Step\Acceptance\LoginStep'. Failed to create instance of   
  'Codeception\Scenario'. Failed to resolve dependency 'Codeception\TestInter  
  face'.                                                                       
                                                                               

Exception trace:
 () at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/Lib/Di.php:119
 Codeception\Lib\Di->injectDependencies() at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/Test/Cest.php:48
 Codeception\Test\Cest->preload() at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/SuiteManager.php:242
 Codeception\SuiteManager->configureTest() at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/SuiteManager.php:109
 Codeception\SuiteManager->addToSuite() at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/SuiteManager.php:102
 Codeception\SuiteManager->loadTests() at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/Codecept.php:187
 Codeception\Codecept->runSuite() at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/Codecept.php:179
 Codeception\Codecept->run() at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/Command/Run.php:341
 Codeception\Command\Run->execute() at /var/www/QA-auto/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /var/www/QA-auto/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /var/www/QA-auto/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /var/www/QA-auto/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /var/www/QA-auto/vendor/codeception/codeception/src/Codeception/Application.php:103
 Codeception\Application->run() at /var/www/QA-auto/vendor/codeception/codeception/package/bin:36
 require() at phar:///var/www/QA-auto/codecept.phar/autoload.php:12
 require_once() at /var/www/QA-auto/codecept.phar:5

> There are my step object
```php
<?php
namespace Step\Acceptance;
use Page\General;
use Page\Login;

class LoginStep extends \AcceptanceTester
{
    public function loginToInstance($username = null, $password = null)
    {
        $username = 'test';
        $password = 'test2';
        $I = $this;
        $I->fillField(Login::$emailField, $username);
        $I->fillField(Login::$passwordField, $password);

        $I->click(Login::$submitButton);
        $I->waitForElementNotVisible(Login::$loginForm, 20);
        $I->waitForElementNotVisible(General::$preloader, 20);
    }
}
```
> And Cest
```php
<?php
use Page\General;
use Step\Acceptance\LoginStep;

class CreateUserCest
{
    /**
     * @var \Step\Acceptance\LoginStep
     */
    private $loginStep;

    function _inject(\Step\Acceptance\LoginStep $loginStep)
    {
        $this->loginStep = $loginStep;
    }

    public function _before(\AcceptanceTester $I)
    {
        $I->amOnPage('/');
        $this->loginStep->loginToInstance();
        $this->loginStep>waitForLogin();
    }

    public function createUser(\AcceptanceTester $I) 
    {
        $I->see('Hello');
    }
}
```
### Details

* Codeception version: 2.3.6
* PHP Version: 7.2
* Operating System: Last stable Ubuntu
* Installation type: Phar
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Asserts
        - Helper\AcceptanceHelper
        #- Db
    config:
        WebDriver:
            host: chrome
            browser: 'chrome'
            port: 4444
            restart: true
            url: localhost
```

**Comment by BeardedVage** [comment]
Also, If I don't use _inject() - it's works

```
<?php
use Page\General;
use Step\Acceptance\LoginStep;

class CreateUserCest
{
    public function _before(\AcceptanceTester $I, LoginStep $loginStep)
    {
        $I->amOnPage('/');
        $loginStep->loginToInstance();
        $loginStep->waitForLogin();
    }

    public function createUser(\AcceptanceTester $I) 
    {
        $I->see('Hello');
    }
}
```php

**Comment by Naktibalda** [comment]
Similar to #4325

**Comment by Naktibalda** [comment]
I don't think that it makes sense to inject Step object using _inject method.

Step object is an Actor, and Actor is supposed to be used in a single test method only. Codeception creates new instance of actor for every method in Cest class.

Also it is very simple to create a new instance of Actors in Cest, all you need is Scenario object that you always get.

```php
    public function createUser(\AcceptanceTester $I, \Codeception\Scenario $scenario) 
    {
        $loginStep = new LoginStep($scenario);
    }
```
