### ISSUE TITLE
[DOC] Update install page

### ISSUE THREAD

**Issue by nymo** [Codeception/Codeception#4569]
The phar file behind the download button is not compatible with PHP < 7. There is another download link for PHP 5.4 and up to 5.5.9. You should update this for 5.6 aswell and make it more clear that the file behind the download button is only compatible with PHP > 5.6.x

**Comment by Naktibalda** [comment]
In which page?

**Comment by nymo** [comment]
On this one http://codeception.com/install. Also the badge in the top right corner with the requirements could be changed to minimum requirements.

**Comment by DavertMik** [comment]
Thanks. Improved that!
