### ISSUE TITLE
Missing `return` in WebDriver->waitForJS

### ISSUE THREAD

**Issue by j03k64** [Codeception/Codeception#4572]
I want to wait for the script execute and get the value back.

Is there a reason that there is no `return` here?: https://github.com/Codeception/Codeception/blob/d3332831fa87641680c1b5eb2647f68b2b6ec200/src/Codeception/Module/WebDriver.php#L2456

According to the [selenium docs](http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp) it does return a value.

Added the `return` locally and it works as expected.

**Comment by DavertMik** [comment]
> I want to wait for the script execute and get the value back.

waiters to not return values. Maybe in your case, you should use `executeScript`. It won't continue until script finishes...

**Comment by jpirkey** [comment]
That is what I am doing currently to get around this issue, but `executeScript` method doesn't have a timeout parameter on it.

I guess what I was trying to accomplish is something like this:

```php
$this->executeJS($script, $timeout);
```

and if the script doesn't complete executing before the timeout is reached, then it would throw an error.  Is that not needed?

**Comment by Naktibalda** [comment]
`waitForJS` takes condition as a parameter and that condition is evaluated many times.

If you want to execute some slow running code, then just let `executeJS` run.  
If you want to wait for some asynchronous code to finish, then you can achieve what you want by combining `waitForJS` and `executeJS`.
