### ISSUE TITLE
Install templates Docs are incomplete

### ISSUE THREAD

**Issue by EstebanSerfe** [Codeception/Codeception#4573]
#### What are you trying to achieve?
If I want to personalize the Install process and use personalized generators for my specific project, the documentation does not indicates where to create those files.
http://codeception.com/docs/08-Customization#Installation-Templates

#### What do you get instead?
 - Where do I create the templates for the install so can be tracked inside the project? Inside _support folder?

**Comment by Naktibalda** [comment]
Anywhere you like as long as it can be autoloaded.

**Comment by DavertMik** [comment]
> Template class should be placed in Codeception\Template namespace so Codeception could locate them by class name

You should create a class inside this namespace. You can either add it to composer.json into autoload section (see Composer docs) or put it into `_support/Codeception/Template` (as `_support` represents root namespace)

**Comment by Naktibalda** [comment]
Isn't it a bit self-defeating to put template to _support? If it exists, the tests are already initialized so there is no need for template.

**Comment by DavertMik** [comment]
yeah, no purpose actually :(
but maybe it could be used for other purposes... Not sure, I just provided a possible option
