### ISSUE TITLE
After update to version 2.3.6 can not run codeception

### ISSUE THREAD

**Issue by mklemarczyk** [Codeception/Codeception#4583]
#### What are you trying to achieve?
Run codeception from console

Previous version (2.2.12) works without any problems.

#### What do you get instead?
Error on command ``` PS F:\Web\root-users\meeting\scripts> ..\..\.tools\Codeception\codecept ```:
```
Parse error: syntax error, unexpected '?' in phar://F:/Web/root-users/.tools/Codeception/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 845
```

### Details

* Codeception version: 2.3.6
* PHP Version: 5.6.31
* Operating System: Windows 10
* Installation type: Phar
* List of installed packages (`composer show`): Only codecept phar
* Suite configuration: NONE, just running help menu

**Comment by Naktibalda** [comment]
You upgraded to phar file which requires PHP 7.0
Try to use this file instead: http://codeception.com/releases/2.3.6/php54/codecept.phar

**Comment by mklemarczyk** [comment]
I updated using the ```codecept self-update``` command. Can you fix this please?

**Comment by Naktibalda** [comment]
No, I can't. It would require to move all phar files around and it would still break things for other people.

I am actually surprised that it took 5 months for someone to report this issue.

**Comment by DavertMik** [comment]
@mklemarczyk please use either new PHP (which is recommended by PHP community)
or install PHP 5.6 compatible phar version http://codeception.com/php5/codecept.phar
also Composer install is preferred as well, at least you will be sure that dependencies won't break

**Comment by martinberlin** [comment]
I just want to add that this is wrongly documented on the Website: 
2.4
Requires: PHP 5.4 and higher + CURL

It says nowhere that requires PHP 7.0

**Comment by Naktibalda** [comment]
Actually it should say "PHP 5.6 and higher".

Version lines have 2 links, example: 2.4.4, for PHP 5.6

Second link supports older versions of PHP, first link requires higher version than second.
so if second link is "for PHP 5.6", then the first link is for "PHP 7.0+"
If second link is "for PHP 5.4-5.5", the the first link is for "PHP 5.6+".

You are welcome to make suggestion how to describe version requirements better.
Anyway, it is better to use composer than phar files.

**Comment by Naktibalda** [comment]
https://github.com/Codeception/Codeception/pull/5098
