### ISSUE TITLE
WebProfiler error with Symfony 3.4

### ISSUE THREAD

**Issue by tacman** [Codeception/Codeception#4585]
#### What are you trying to achieve?

Run tests with Symfony 3.4 (Beta 1)

#### What do you get instead?

1) AACest: Critical path
 Test  tests/functional/AACest.php:criticalPath
                                                                                                                                      
  [Twig_Error_Loader] Template "__string_template__250d9bae23fbb2d2b06a4bc9bc6d564c83b8477ad762c17b007bf89aca57be94" is not defined.  
                                                                                                                                      

Scenario Steps:

(removed, not relevant, happens on every page that submits a form).

```bash
#1  /var/www/platform/vendor/twig/twig/lib/Twig/Loader/Chain.php:86
#2  /var/www/platform/vendor/twig/twig/lib/Twig/Environment.php:270
#3  /var/www/platform/vendor/twig/twig/lib/Twig/Environment.php:350
#4  /var/www/platform/vendor/twig/twig/lib/Twig/Environment.php:328
#5  /var/www/platform/vendor/symfony/symfony/src/Symfony/Bridge/Twig/DataCollector/TwigDataCollector.php:66
#6  /var/www/platform/vendor/symfony/symfony/src/Symfony/Bridge/Twig/DataCollector/TwigDataCollector.php:70
#7  /var/www/platform/vendor/symfony/symfony/src/Symfony/Bridge/Twig/DataCollector/TwigDataCollector.php:73
#8  /var/www/platform/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php:121
#9  /var/www/platform/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php:117
#10 Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelTerminate


```

If I remove these lines from ProfilerListener.php, the error goes away.  So the issue isn't with the tests, but rendering the twig that the profiler needs.

```php

        // save profiles
        foreach ($this->profiles as $request) {
            $this->profiler->saveProfile($this->profiles[$request]);
        }
```

### Details

* Codeception version: 
* PHP Version: 7.1
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by DavertMik** [comment]
@VolCh hey, maybe you have some thoughts about this?

**Comment by tacman** [comment]
config_dev.yml:

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

**Comment by tacman** [comment]
Is anyone else seeing this problem?  @VolCh -- you said you were able to re-produce it, any ideas of what the issue is?

**Comment by VolCh** [comment]
I try reproduce it, but in my simplest Symfony Flex app submit works.

**Comment by tacman** [comment]
I updated to Symfony 3.4-BETA 3 this morning, and am no longer getting the error, so I'll close this.
