### ISSUE TITLE
Why is dontSeeInpopUp Gone?

### ISSUE THREAD

**Issue by kpascal** [Codeception/Codeception#4588]
#### What are you trying to achieve?

I want dontSeeInPopUp back in source code so I can use it 

#### What do you get instead?
no such function found

### test steps

>  $I->dontSeeInPopup("Your email will be re-sent shortly.");
>   $I->acceptPopup();
>   $I->wait(1);

#### Console Output

> Time: 59.31 seconds, Memory: 12.75MB
> 
> There was 1 error:
> 
> ---------
> 1) AccountViewEmailHistoryTabCest: Test verify the resend link is not displaying as the customersetting
>  Test  tests\cc\sdfdfCest.php:AccountView
> 
>   [RuntimeException] Call to undefined method CcTester::dontSeeInPopup
> 

```
#### Source Code

There is no source code in vendor, however I have this working in one of my local helpers


```

> public function dontSeeInPopup($text) {
>         $alert = $this->getModule('WebDriver')->webDriver->switchTo()->alert();
>         try {
>             $this->assertNotContains($text, $alert->getText());
>         } catch (\PHPUnit_Framework_AssertionFailedError $e) {
>             $alert->dismiss();
>             throw $e;
>         }
>     }

```


### Details

* Codeception version:  2.3.6
* PHP Version: 5.6.29
* Operating System: windows server 2008

**Comment by DavertMik** [comment]
well, I assume it was in old Selenium module and was not reimplemented in WebDriver module.

yeah, I like your implementation. Could you send Pull Request?

**Comment by kpascal** [comment]
Created the PR

https://github.com/Codeception/Codeception/pull/4589
