### ISSUE TITLE
Some functionality requires register_argc_argv

### ISSUE THREAD

**Issue by CJDennis** [Codeception/Codeception#4595]
#### What are you trying to achieve?
Code coverage of functional tests by using `c3.php`.
#### What do you get instead?
Lots of errors

```
PHP Notice:  Undefined index: argv in phar://C:/usr/bin/codecept.phar/src/Codeception/Application.php on line 137
PHP Notice:  Undefined index: argv in phar://C:/usr/bin/codecept.phar/src/Codeception/Command/SelfUpdate.php on line 44
```

Changing `register_argc_argv = On` in `php.ini` and restarting the server fixes this error, however, this setting is not recommended in either production or development environments.

Setting `register_argc_argv = On` doesn't completely fix the issue, however.

```
PHP Notice:  Undefined offset: 0 in phar://C:/usr/bin/codecept.phar/src/Codeception/Command/SelfUpdate.php on line 44
```

### Details

* Codeception version: 2.3.6
* PHP Version: 5.5.9
* Operating System: Windows 10
* Installation type: manual

This issue was mentioned as an aside in #531.

**Comment by Naktibalda** [comment]
@CJDennis register_argc_argv=On is absolutely necessary for running Codeception, but it shouldn't be necessary for c3.
I fixed warnings and added setting check to Application::run, but I haven't tested c3, so I will be waiting for your feedback.

**Comment by CJDennis** [comment]
@Naktibalda Thanks! I'll let you know when I've tested it.
