### ISSUE TITLE
Db-Module: MySQL SSL connection

### ISSUE THREAD

**Issue by bangertz** [Codeception/Codeception#4602]
I am missing the SSL option for the connection with the Db-Module. Is it planned or already possible? I rewrote the constructor in "Codeception\Lib\Driver\Db" for a test. The connection worked perfectly.

```php
public function __construct( $dsn, $user, $password )
{
    $this->dbh = new \PDO( $dsn, $user, $password, [
        \PDO::MYSQL_ATTR_SSL_KEY    => '/path/to/client-key.pem',
        \PDO::MYSQL_ATTR_SSL_CERT   => '/path/to/client-cert.pem',
        \PDO::MYSQL_ATTR_SSL_CA     => '/path/to/ca-cert.pem',
    ] );
    
    $this->dbh->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);

    $this->dsn = $dsn;
    $this->user = $user;
    $this->password = $password;
}
```

But no parameter is provided for the additional options. I did not succeed in extending the module/driver. Has anyone a tip or an idea to solve the problem?

**Comment by DavertMik** [comment]
> I am missing the SSL option for the connection with the Db-Module. Is it planned or already possible?

No. Not planned. Not possible. Yet.

Please send a pull request with the update to Db module.
`ssl_key`, `ssl_cert`, `ssl_ca` should be added as config parameters to Db.
