### ISSUE TITLE
Integration of appium driver 

### ISSUE THREAD

**Issue by laurainwebo** [Codeception/Codeception#4605]
The appium driver located at https://github.com/tajawal/codeception-appium works pretty well with codeception. Could this be added to the repo? The https://github.com/appium/php-client is required as well but the two together are a very cool add-on to codeception.

**Comment by Naktibalda** [comment]
I can exist as independent package just fine.
The only place where it needs to be added is http://codeception.com/addons

**Comment by DavertMik** [comment]
Thanks for pointing to this repo! Could you add this package to the Addons page as @Naktibalda proposed?

I didn't try this repo so I can't recommend it but if you say it works for you, it's really cool. For more professional Appium testing consider using CodeceptJS http://codecept.io/mobile/

**Comment by laurainwebo** [comment]
I've contacted the author of the driver (https://github.com/Meabed), he will be adding it to codeception's addons soon I hope, this is a very cool driver and has helped me to automate my appium testing within the codeception framework.

**Comment by Naktibalda** [comment]
He created a pull request yesterday: https://github.com/Codeception/codeception.github.com/pull/148

**Comment by laurainwebo** [comment]
Great!
