### ISSUE TITLE
Check if codeception acceptance is running

### ISSUE THREAD

**Issue by Henk8** [Codeception/Codeception#4606]
#### What are you trying to achieve?
I want to check if codeception acceptance test is running so I can do some additional stuff.

#### What do you get instead?
I cant check if codeception is running.

I want to check in the application if codeception is running. I have tried to define a variable in acceptance/_bootstrap.php but that defined variable is not present in the code.

How can I check if codeception acceptance is running?

**Comment by Naktibalda** [comment]
You could use [setCookie](http://codeception.com/docs/modules/WebDriver#setCookie) method to set some cookie in your tests and check for its presence in application code.

**Comment by Henk8** [comment]
I already tried that, but once again the cookie is not set in my application.

**Comment by Naktibalda** [comment]
I suggested a different thing, please follow the link.

**Comment by Henk8** [comment]
Sorry forgot to mention, I already used $->setCookie, but the test fails.

 I set cookie "PHPSESSID","el4ukv0kqbvoirg7nkp4dncpk3"


To downstream: {"sessionId":"e100d2f086966eef511f91b1ac7e63cb","status":20,"value":{"message":"unable to set cookie\n  (Session info: chrome=62.0.3202.75)\n  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64)"}}

**Comment by Naktibalda** [comment]
Does it work if you `setCookie` after first `amOnPage` call?
And please don't use PHPSESSID as a cookie name, it is a really bad example.

**Comment by Henk8** [comment]
That was it. Thanks!
