### ISSUE TITLE
codeception 2.2.12 API testing with REST - someone pls help me with Basic Authorization?

### ISSUE THREAD

**Issue by Sashan777** [Codeception/Codeception#4608]
![image](https://user-images.githubusercontent.com/31503247/32534564-452055f8-c467-11e7-8da7-112813616a21.png)

i try to set Header with haveHttpHeader(...) then sendGET(http//...) but response still is 401? What is wrong with my work? im newbie with that... <<< some1 plz help!

![image](https://user-images.githubusercontent.com/31503247/32534541-2c4b6b80-c467-11e7-8d70-93e831aab189.png)

**Comment by Naktibalda** [comment]
Have you tried to use amHttpAuthenticated method?

**Comment by Sashan777** [comment]
that's my settings and test-fails 
![image](https://user-images.githubusercontent.com/31503247/32541617-3978cea0-c481-11e7-858e-ecb5a53d2077.png)

![image](https://user-images.githubusercontent.com/31503247/32541560-098d9c66-c481-11e7-85d5-1bc0923a8e48.png)

![image](https://user-images.githubusercontent.com/31503247/32541598-29bb62b6-c481-11e7-954e-9eecc42100a9.png)

**Comment by Sashan777** [comment]
![image](https://user-images.githubusercontent.com/31503247/32541724-a10a4c6a-c481-11e7-9379-2218a168bb83.png)

**Comment by Naktibalda** [comment]
If you see correct authentication header in the logs, then it is most likely to be an issue of your app.

Don't use both `amHttpAuthenticated` and `setHeader` in the test - pick one.

**Comment by Sashan777** [comment]
Ok! When i run test like this - 
![image](https://user-images.githubusercontent.com/31503247/32544211-eaa15196-c488-11e7-9b9d-b63d46f642e7.png)
i'll get logs
![image](https://user-images.githubusercontent.com/31503247/32544324-3633abf4-c489-11e7-8e19-ebc471c2d236.png)

![image](https://user-images.githubusercontent.com/31503247/32544347-4ab5f442-c489-11e7-8115-74c3bfba3286.png)

**Comment by Naktibalda** [comment]
That's good. Curl error 28 is a timeout and the test took 30 seconds, so it looks like your API takes very long time to respond.

**Comment by Naktibalda** [comment]
Add `timeout: 60` option to PhpBrowser configuration to make curl wait longer.

**Comment by Sashan777** [comment]
ok! thanks Naktibalda!
