### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by subdesign** [Codeception/Codeception#461]
Can I use some kind of conditions in Codeception? What I mean I explain in an example: 
I want to test Datatables pagination links, but if there are only few records, I have one page link (1), and no 2nd page anchor link. I tried to use php if statement like

```
if( $I->see('2', 'a') ) {}
```

but no result, drops the default fail message. Maybe there is a better solution for this decision making.

**Comment by mbaric** [comment]
Ok here is what has been tested and proven on real sites. All the credits to @KofRiv [ORGINAL PAGE][1]

In `tests/_support/AcceptanceHelper.php` add additional method

    function seePageHasElement($element)
    {
        try {
            $this->getModule('WebDriver')->seeElement($element);
        } catch (\PHPUnit_Framework_AssertionFailedError $f) {
            return false;
        }
        return true;
    }

Then to test in your acceptance test use:

    if ($I->seePageHasElement("input[name=address]")) {
        $I->fillField("input[name=address]", "IM");
    }

And that's it :)



  [1]: http://phptest.club/t/conditional-logic-in-tests/447/6
