### ISSUE TITLE
Class 'PHPUnit\Framework\ExceptionWrapper' not found

### ISSUE THREAD

**Issue by elimentz** [Codeception/Codeception#4618]
#### What are you trying to achieve?

Trying to run my unit tests. If they pass, everything is well. If the tests fail, an exception is thrown

#### What do you get instead?

```bash
$ sudo vendor/bin/codecept run unit Services/Html/MyTest.php -vvv
PHP Warning:  Class 'PHPUnit\Framework\ExceptionWrapper' not found in /var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php on line 25
PHP Stack trace:
PHP   1. {main}() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:0
PHP   2. require_once() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:7
PHP   3. include_once() /var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php:45
PHP   4. class_alias() /var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php:25

Warning: Class 'PHPUnit\Framework\ExceptionWrapper' not found in /var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php on line 25

Call Stack:
    0.0001     365608   1. {main}() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:0
    0.0018     393048   2. require_once('/var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php') /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:7
    0.0753    2958504   3. include_once('/var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php') /var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php:45
    0.0929    3738248   4. class_alias() /var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php:25

Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Unit Tests (1) 
- MyTest: Index
  [Database] Transaction started


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'PHPUnit\Framework\ExceptionWrapper' not found

```

Test details are irrelevant, any test failure will cause the exception. If the tests do not fail, everything works as expected

### Details

* Codeception version: 2.3.6
* PHPUnit version: 6.4.4
* PHP Version: 7
* Operating System: Ubuntu 16
* Installation type:  Composer
* Suite configuration: irrelevant, no changes were made

**Comment by Naktibalda** [comment]
This could be a new incompatibility introduced by PHPUnit. Try to downgrade PHPUnit by a few patch releases or to 6.3.* by setting appropriate constraint in composer.json to avoid error until it is fixed.

**Comment by Naktibalda** [comment]
I've looked at PHPUnit repo and I haven't found any relevant changes in it.

Check if you have got src/Framework/ExceptionWrapper.php in Phpunit dir.

Try to reinstall dependencies with composer.

**Comment by elimentz** [comment]
@Naktibalda The file actually exists in the vendor directory, so that should not be a problem. I managed to get it working again using codeception 2.2.* and PhpUnit ~5.0. However, that's a significant downgrade and I would rather not stay on this version for too long

**Comment by Naktibalda** [comment]
Please investigate it more. It is likely to be something very specific.

You downgraded way too much.
Codeception 2.3 works fine with PHPUnit 6.

**Comment by elimentz** [comment]
I didn't want to downgrade so much, but any other combination gave me version conflicts for some reason. I changed it back to the latest versions, but things have actually gotten worse now.. I now get the following error:

```


10:10 PM]-[vagrant@vagrant]-[/var/www/vagrant/htdocs]-[git develop]
$ sudo vendor/bin/codecept run unit Services/Html/HomeViewFactoryTest.php -vvv
PHP Warning:  include_once(/var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php): failed to open stream: No such file or directory in /var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php on line 45
PHP Stack trace:
PHP   1. {main}() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:0
PHP   2. require_once() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:7

Warning: include_once(/var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php): failed to open stream: No such file or directory in /var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php on line 45

Call Stack:
    0.0002     365608   1. {main}() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:0
    0.0032     393048   2. require_once('/var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php') /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:7

PHP Warning:  include_once(): Failed opening '/var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php' for inclusion (include_path='.:/usr/share/php') in /var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php on line 45
PHP Stack trace:
PHP   1. {main}() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:0
PHP   2. require_once() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:7

Warning: include_once(): Failed opening '/var/www/vagrant/htdocs/vendor/codeception/codeception/shim.php' for inclusion (include_path='.:/usr/share/php') in /var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php on line 45

Call Stack:
    0.0002     365608   1. {main}() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:0
    0.0032     393048   2. require_once('/var/www/vagrant/htdocs/vendor/codeception/codeception/autoload.php') /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:7

PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Runner_Version' not found in /var/www/vagrant/htdocs/vendor/codeception/codeception/src/Codeception/Command/Run.php:236
Stack trace:
#0 /var/www/vagrant/htdocs/vendor/symfony/console/Command/Command.php(240): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/vagrant/htdocs/vendor/symfony/console/Application.php(860): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/vagrant/htdocs/vendor/symfony/console/Application.php(218): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/vagrant/htdocs/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Co in /var/www/vagrant/htdocs/vendor/codeception/codeception/src/Codeception/Command/Run.php on line 236

Fatal error: Uncaught Error: Class 'PHPUnit_Runner_Version' not found in /var/www/vagrant/htdocs/vendor/codeception/codeception/src/Codeception/Command/Run.php on line 236

Error: Class 'PHPUnit_Runner_Version' not found in /var/www/vagrant/htdocs/vendor/codeception/codeception/src/Codeception/Command/Run.php on line 236

Call Stack:
    0.0002     365608   1. {main}() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:0
    0.2822    5010384   2. Codeception\Application->run() /var/www/vagrant/htdocs/vendor/codeception/codeception/codecept:36
    0.2822    5010384   3. Codeception\Application->run() /var/www/vagrant/htdocs/vendor/codeception/codeception/src/Codeception/Application.php:103
```

I checked the codeception dir: shim.php is actually not there. It is there in the repository, so I'm guessing this is not normal? I tried removing the entire `vendor/` directory and installing every package again (after clearing composer cache) but the error keeps occurring (the error in this comment)

**Comment by elimentz** [comment]
I will also add that I recently upgraded to Vagrant 2.0.1. This might be relevant since every now and then, if I run composer update, I will get a notification that there is no composer.json file in the directory - even though I just ran the command successfully like 15 seconds earlier and never changed dirs.

**Comment by DavertMik** [comment]
I assume you may have globally installed PHPUnit (with vagrant maybe?) and files are conflicting.
Anyway, there should not be any other PHPUnit in visible scope except one installed by Codeception dependency.

**Comment by elimentz** [comment]
I highly doubt it. This is a new VM with only one project and I never install packages globally.

**Comment by Naktibalda** [comment]
It looks like you have a problem with disappearing files.

**Comment by elimentz** [comment]
Just that one particular file? That would be strange, no? My app runs just fine, no problems there. 

I added the `shim.php` file manually with the code from the repository, and then I get the same error as I mentioned in my initial message.

**Comment by Naktibalda** [comment]
It started with ExceptionWrapper.php, then you had shim.php missing and composer.json went missing a few times too.

I am pretty sure that it is a vagrant issue.

**Comment by elimentz** [comment]
To be fair, both the `ExceptionWrapper.php1 and the `Runner\Version.php` file actually exist, they are not missing. For some reason, the classes can't be loaded.

I downgraded to Vagrant 1.9.8 and reinstalled my composer dependencies after clearing the cache. Unfortunately, it did not solve the problem: `shim.php` is still missing.

**Comment by Naktibalda** [comment]
PHPUnit_Runner_Version error is a consequence of missing shim.php

Obviously missing shim.php file isn't a bug of Codeception.

**Comment by DavertMik** [comment]
Yes, so mysterious... shim.php was introduced in Codeception 2.2. Maybe by any chance you use outdated version?

**Comment by elimentz** [comment]
But it should be included after installing the package, no? I can create it manually but that should never be the case, it should be there automatically!

And even if I do create it myself, the initial error (`ExceptionWrapper not found`) still occurs, so there is still something wrong here.

**Comment by DavertMik** [comment]
It should be INSIDE a package. Just as all other files we have

**Comment by DavertMik** [comment]
Here is is included https://github.com/Codeception/Codeception/blob/2.3/autoload.php#L45

**Comment by elimentz** [comment]
@DavertMik I understand, this is what I mean. I should be found in the `vendor/codeception/codeception` dir, but it is not. Not unless I put it there myself.

**Comment by elimentz** [comment]
@DavertMik I checked my `composer.lock` file to see if it was outdated, but clearly not:

```
{
            "name": "codeception/codeception",
            "version": "2.3.6",
            "source": {
                "type": "git",
                "url": "https://github.com/Codeception/Codeception.git",
                "reference": "c3dd3b5d9e0b1ea6c2fcca52457736dc756716f8"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/Codeception/Codeception/zipball/c3dd3b5d9e0b1ea6c2fcca52457736dc756716f8",
                "reference": "c3dd3b5d9e0b1ea6c2fcca52457736dc756716f8",
                "shasum": ""
            },
        },
```

I even downloaded the zip file to make sure, but the file was included. It almost seems as if it's being deleted by some sort of script?

**Comment by Naktibalda** [comment]
@elimentz have you solved this problem?

**Comment by elimentz** [comment]
Sadly no. I tried upgrading my Vagrant and VMware fusion pro, so far no luck. Can't even get my VM started anymore... Not sure how much help you guys can still be though

**Comment by Ard-Jan** [comment]
I had the same problem. The problem occurs when you are calling a function with the parameter null, when the function expects a specific type. Downgrading phpunit to 6.3.1 solved the problem for me.

I created a small example to explain the problem.

```php
<?php

/**
 * Class Account
 */
class Account
{
    /** @var \stdClass */
    protected $name;

    /**
     * @param \stdClass $name;
     */
    public function setTest(\stdClass $name)
    {
        $this->name = $name;
    }
}
?>
```

```php
<?php

use PHPUnit\Framework\TestCase;

/**
 * Class AccountTest
 */
class AccountTest extends TestCase
{
    public function testSetName()
    {
        $account = new Account();
        $account->setTest(null);
    }
}
?>
```
When i run this with phpunit 6.4.4 i get:
```
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught Error: Class 'PHPUnit\Framework\ExceptionWrapper' not found in */vendor/phpunit/phpunit/src/Framework/TestResult.php:745
Stack trace:
...
```
When i run this with phpunit 6.3.1 i get:
```
PHPUnit 6.3.1 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 1.44 seconds, Memory: 18.00MB

There was 1 error:

1) *\AccountTest::testSetName
TypeError: Argument 1 passed to *\Account::setTest() must be an instance of stdClass, null given, called in */AccountTest.php on line 15
```

**Comment by Ard-Jan** [comment]
I created an issue here: https://github.com/sebastianbergmann/phpunit/issues/2885

**Comment by Naktibalda** [comment]
@Ard-Jan how do you run phpunit?
Do you run `./vendor/bin/phpunit` ?

**Comment by elimentz** [comment]
@Naktibalda I downgraded back to version 6.3.1 as suggested by @Ard-Jan. I am now able to run my unit tests again. Unfortunately the `shim.php` file is still missing if I do a new installation of the package

**Comment by Naktibalda** [comment]
@elimentz have you tried to clear ~/.composer/cache directory?

**Comment by elimentz** [comment]
I ran composer clear-cache before my previous run and manually removed the directory just now. Same result: file is missing

**Comment by Naktibalda** [comment]
Any chance that you are using composer proxy like https://toranproxy.com/ ?

**Comment by elimentz** [comment]
Nope

**Comment by dreanmer** [comment]
i'm with the same problem, missing shim.php then created it manually from the source and now WxceptionWrapper not found.

macOs High Sierra
vagrant: 2.0.1 (using nfs)
vm distro: ubuntu
codeception: 2.3.6
phpunit: 6.4.4

**Comment by Preclowski** [comment]
In my case that problem occurs when I include file which does not exists. I spend few hours to fix this. Interesting this is that it works (simply fail test) on local environment, and throw mentioned exception in docker environment.
