### ISSUE TITLE
Conection refused to selenium-server by using acceptance test

### ISSUE THREAD

**Issue by makoeppel** [Codeception/Codeception#4619]
#### What are you trying to achieve?
I want to setup some basic acceptance test for my webproject. For this I run 
`java -jar -Dwebdriver.chrome.driver=chromedriver selenium-server-standalone-3.4.0.jar` and then 
`./vendor/bin/codecept run acceptance --steps`. 

#### What do you get instead?
On my Mac this runs without problems but on my Ubuntu 16.04.2 LTS I got the error: Connect to localhost:4887 [localhost/127.0.0.1] failed: Connection refused. I tested this with selenium-server-standalone-3.7.1.jar and with all chromedrivers >=  60.0.3112.0. After using -vvv I got this information:

```bash
Exception trace:
 () at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:114
 Facebook\WebDriver\Exception\WebDriverException::throwException() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:320
 Facebook\WebDriver\Remote\HttpCommandExecutor->execute() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:535
 Facebook\WebDriver\Remote\RemoteWebDriver->execute() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
 Facebook\WebDriver\Remote\RemoteExecuteMethod->execute() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/facebook/webdriver/lib/WebDriverOptions.php:68
 Facebook\WebDriver\WebDriverOptions->deleteAllCookies() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:495
 Codeception\Module\WebDriver->_after() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:66
 Codeception\Subscriber\Module->after() at n/a:n/a
 call_user_func() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/symfony/event-dispatcher/EventDispatcher.php:212
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/symfony/event-dispatcher/EventDispatcher.php:44
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:131
 Codeception\PHPUnit\Listener->fire() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:117
 Codeception\PHPUnit\Listener->endTest() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/phpunit/phpunit/src/Framework/TestResult.php:408
 PHPUnit\Framework\TestResult->endTest() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/Test/Test.php:109
 Codeception\Test\Test->run() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/phpunit/phpunit/src/Framework/TestSuite.php:744
 PHPUnit\Framework\TestSuite->run() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:106
 Codeception\PHPUnit\Runner->doEnhancedRun() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
 Codeception\SuiteManager->run() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/Codecept.php:188
 Codeception\Codecept->runSuite() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/Codecept.php:157
 Codeception\Codecept->run() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/Command/Run.php:420
 Codeception\Command\Run->runSuites() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/Command/Run.php:347
 Codeception\Command\Run->execute() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/src/Codeception/Application.php:103
 Codeception\Application->run() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/vendor/codeception/codeception/package/bin:36
 require() at phar:///home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/codecept.phar/autoload.php:12
 require_once() at /home/mkoeppel/Dokumente/Software/Codeception-Tests/codeception/codecept.phar:5
```

So I first thought this can be a problem with function `deleteAllCookies()` so I set clear_cookies: false but then I got:

```bash
[Facebook\WebDriver\Exception\UnknownServerException] unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"7577.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.4.0-97-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 44 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'blabla', ip: '123456789', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-97-generic', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, chrome={userDataDir=/tmp/.com.google.Chrome.xa6eNq}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=59.0.3071.115, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7cdd3f0374cd58e7204547ba7021c826  
```

> My test source code is

```php
<?php


/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void comment($description)
 * @method \Codeception\Lib\Friend haveFriend($name, $actorClass = NULL)
 *
 * @SuppressWarnings(PHPMD)
*/
class AcceptanceTester extends \Codeception\Actor
{
    use _generated\AcceptanceTesterActions;

    public function loginPage()
    {
        $I = $this;
        $I->amOnPage(\Page\Acceptance\LoginPage::$URL);
        $I->see(\Page\Acceptance\LoginPage::$LoginButton);
        $I->click(\Page\Acceptance\LoginPage::$LoginButton);
        $I->fillField(\Page\Acceptance\LoginPage::$LoginUserField, \Page\Acceptance\LoginPage::$name);
        $I->fillField(\Page\Acceptance\LoginPage::$LoginPasswordField, \Page\Acceptance\LoginPage::$password);
        $I->click(\Page\Acceptance\LoginPage::$LoginSubButton);
    }

    public function dashboardPage()
    {
        $I = $this;
        $I->amOnPage(\Page\Acceptance\DashboardPage::$URL);
        $I->see(\Page\Acceptance\DashboardPage::$ChangeButton);
        $I->click(\Page\Acceptance\DashboardPage::$ChangeButton);
        $I->see(\Page\Acceptance\DashboardPage::$DashboardButton);
        $I->click(\Page\Acceptance\DashboardPage::$DashboardButton);
        $I->see(\Page\Acceptance\DashboardPage::$DashboardTitle);
    }

    public function orderProduct()
    {
        $I = $this;
        $I->amOnPage(\Page\Acceptance\ProductOrderPage::$URL);
        $I->see(\Page\Acceptance\ProductOrderPage::$WhatsNewButton);
        $I->click(\Page\Acceptance\ProductOrderPage::$WhatsNewButton);
        $I->see(\Page\Acceptance\ProductOrderPage::$HoodiesButton);
        $I->click(\Page\Acceptance\ProductOrderPage::$HoodiesButton);
        $I->see(\Page\Acceptance\ProductOrderPage::$ExampleProduct);
        $I->click(\Page\Acceptance\ProductOrderPage::$ExampleProduct);
    }

    public function logoutPage()
    {
        $I = $this;
        $I->amOnPage(\Page\Acceptance\LogoutPage::$URL);
        $I->see(\Page\Acceptance\LogoutPage::$ChangeButton);
        $I->click(\Page\Acceptance\LogoutPage::$ChangeButton);
        $I->see(\Page\Acceptance\LogoutPage::$LogoutButton);
        $I->click(\Page\Acceptance\LogoutPage::$LogoutButton);
    }
    public function loginAdmin()
    {
        $I = $this;
        $I->amOnPage(\Page\Acceptance\AdminLoginPage::$URL);
        $I->fillField(\Page\Acceptance\AdminLoginPage::$LoginUserField, \Page\Acceptance\AdminLoginPage::$name);
        $I->fillField(\Page\Acceptance\AdminLoginPage::$LoginPasswordField, \Page\Acceptance\AdminLoginPage::$password);
        $I->click(\Page\Acceptance\AdminLoginPage::$LoginSubButton);
    }
}

```
### Details

* Codeception version: 2.3.6.0
* PHP Version: 7.0.22-0
* Operating System: Ubuntu 16.04.2 LTS
* Installation type: Phar || Composer (I tried both)
* List of installed packages:
behat/gherkin                      v4.4.5  Gherkin DSL parser for PHP 5.3
codeception/codeception            2.3.6   BDD-style testing framework
doctrine/instantiator              1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.4.1   A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1  Guzzle promises library
guzzlehttp/psr7                    1.4.2   PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.7.0   Create deep copies (clones) of your objects
phar-io/manifest                   1.0.1   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1   Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.1.1   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.4.0   
phpspec/prophecy                   v1.7.2  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          5.2.3   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  1.0.9   Utility class for timing
phpunit/php-token-stream           2.0.1   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    6.4.4   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       4.0.4   Mock Object library for PHPUnit
psr/http-message                   1.0.1   Common interface for HTTP messages
psr/log                            1.0.2   Common interface for logging libraries
sebastian/code-unit-reverse-lookup 1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.0   Provides the functionality to compare PHP values for equality
sebastian/diff                     2.0.1   Diff implementation
sebastian/environment              3.1.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0   Snapshotting of global state
sebastian/object-enumerator        3.0.3   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
stecman/symfony-console-completion 0.7.0   Automatic BASH completion for Symfony Console Component based applications.
symfony/browser-kit                v3.3.10 Symfony BrowserKit Component
symfony/console                    v3.3.10 Symfony Console Component
symfony/css-selector               v3.3.10 Symfony CssSelector Component
symfony/debug                      v3.3.10 Symfony Debug Component
symfony/dom-crawler                v3.3.10 Symfony DomCrawler Component
symfony/event-dispatcher           v3.3.10 Symfony EventDispatcher Component
symfony/finder                     v3.3.10 Symfony Finder Component
symfony/polyfill-mbstring          v1.6.0  Symfony polyfill for the Mbstring extension
symfony/process                    v3.3.10 Symfony Process Component
symfony/yaml                       v3.3.10 Symfony Yaml Component
theseer/tokenizer                  1.1.0   A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.2.0   Assertions to validate method input/output with nice error messages.
* Suite configuration: 

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
             url: 'http://magento2-demo.nexcess.net/'
             browser: chrome # 'chrome' or 'firefox'
            clear_cookies: false/true
```

**Comment by Naktibalda** [comment]
Does it work with Firefox?

**Comment by makoeppel** [comment]
Yes with firefox (geckodriver) it is working.

**Comment by Naktibalda** [comment]
It is probably an issue of chromedriver, you can report it at https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by makoeppel** [comment]
I reported it there https://bugs.chromium.org/p/chromedriver/issues/detail?id=2131

**Comment by makoeppel** [comment]
There was no problem with the chromedriver. Unfortunately I didn't released the my Chrome Version is not updated. That's why I used an older version of chromedriver which wasn't compatible with the Codeception version.
