### ISSUE TITLE
Override the Codeception Dependency Injector

### ISSUE THREAD

**Issue by Sarke** [Codeception/Codeception#4625]
Is there a way to override the DI in Codeception to use another one?  For my use case, the Yii2 one, so I can use aliases.

It would be use full for a couple of reasons:

1. For example, I can set an alias so the "Guzzle" dependency actually loads GuzzleFake instead.

2. I can centralize my dependencies in the source and use the same container for the Codeception tests.

If only 1 was a concern, we could think about extending the existing DI in Codeception, but I think it would be very useful to be able to resuse the dependencies from the software.  For example, the Symfony DI also allows for YAML and XML definitions of the dependencies, which would mean you don't need to redefine them in Codeception.

Currently the workaround seems to simply be to not use the Codeception dependency injection and instead load up the one from another library.  Which of course means we don't get the nice method DI in Cest files.

Or am I missing something, if it is possible?

**Comment by DavertMik** [comment]
Codeception's DI is not like that. Most of the dependencies like Guzzle, WebDriver, etc are hardcoded. 
The DI is used to instantiate modules, tests, actors, pageobjects. It knows only how to inject each other.
Also there is no DI configuration, injection happens only by class name.
While it looks really simple that works and there is no big reason to replace this naive DI with something bigger. At least the feature you ask is not about DI but about rewriting the implementation of Guzzle connector. And yes, it's pretty hard to make it so we are not goind to do it anytime soon :(

What you can actually do is to extend require module and replace the dependencies manually
