### ISSUE TITLE
Db Mobule: haveInDatabase() support for SQL functions

### ISSUE THREAD

**Issue by pohnean** [Codeception/Codeception#4643]
I'm using MySQL 5.7 with a GEOMETRY column and it's currently impossible to insert test data using `$I->haveInDatabase` to insert the value `POINT(:lng, :lat)`.

I'm proposing a method similar to how Yii deals with this:
```
$I->haveInDatabase('places', [
  'id' => 1,
  'location' => new DbExpression('POINT(103, 1)')
]
```
Having this will also open up possibilities like uuid generation:
```
$I->haveInDatabase('places', [
  'uuid' => new DbExpression('UUID()'),
]
```
which is annoying to because you need another library to do it now.

**Comment by DavertMik** [comment]
This looks like pretty rare case.

If you need this, please create your own method or extend the Db module: http://codeception.com/docs/06-ModulesAndHelpers#Accessing-Other-Modules
