### ISSUE TITLE
Add DataFactory Module support for factory-muffin-faker: ^2.0 or drop it requirements

### ISSUE THREAD

**Issue by Insolita** [Codeception/Codeception#4646]
https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Module/DataFactory.php#L154
As fact "league/factory-muffin-faker" - is simple wrapper for "frazinotto/faker" and it versions strictly depends on faker versions.  And also league/factory-muffin can be used without factory-muffin-faker, so is not neccessary to check. The contents of this module does not depend on this library.

**Comment by DavertMik** [comment]
Makes sense. Can you update the requirements and send a pull request?

**Comment by Insolita** [comment]
ok

**Comment by Naktibalda** [comment]
@DavertMik All examples use Faker but there is no instruction how to install it.
I think that it is a problem.

**Comment by Naktibalda** [comment]
Since Codeception 4.0, league/factory-muffin-faker is an explicit composer dependency of codeception/module-datafactory: https://github.com/Codeception/module-datafactory/blob/master/composer.json
