### ISSUE TITLE
[RFC] re-run failed tests

### ISSUE THREAD

**Issue by mhanysz** [Codeception/Codeception#465]
When I use Codeception to test my application it often happens that more than one test is failing. After changing the code in order to fix the errors, I often find myself in a situation where I only want to run the previously failed tests as I am not 100% sure if all errors are fixed. At the moment the only option I know of is to name each testfile individually which is pretty hard for more than one failing test (mainly because I name my tests after what they do, so a typical name is EditXYAndCheckZCept.php).

What I am proposing is to introduce a command line option like -f or --failed that only rund the tests that failed in the last run.
For example I start a whole suite with `php codecept.phar run api` and 5 of 42 test fail. After that I change the code to fix the errors and need to test it again.
Instead of re-running each test separately with `php codecept.phar run api someVeryLongTestNameThatDescribesWhatIsDone1Cept.php` and `php codecept.phar run api someVeryLongTestNameThatDescribesWhatIsDone2Cept.php` and so on, I would like to do something like `php codecept.phar run --failed` to re-run all previously failed tests.

I think this would be a nice and handy feature because it would save a lot of time that would be needed to re-run the whole suite and also saves a lot of typing to re-run each failed test individually.
What are your thoughts about that?

Best regards,

**Comment by jerclarke** [comment]
For anyone who, like me, stumbles on to this ticket from Google, this should be built into current versions, the docs for the enabled-by-default Runfailed extension are here:

https://codeception.com/extensions#RunFailed
