### ISSUE TITLE
Acceptance test failed to get html body on remote url

### ISSUE THREAD

**Issue by mfk** [Codeception/Codeception#4652]
Hi guys,

i'm trying to run some acceptance tests on my testing server. this is based on a different url then localhost, but the problem is that the webdriver can't get the html.

selenium server is up, chrome driver works well but i can't test nothing from my testing server.

```php
actor: AcceptanceTester
modules:
  enabled:
    - WebDriver:
        url: TESTING_URL
        window_size: maximize
        browser: chrome
        capabilities:
          chromeOptions:
        #    args: ["--headless", "--disable-gpu"]
            args: ['--ignore-ssl-errors=true', '--ssl-protocol=TLSv1']
```
this is what i get:

```html
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>
```
is there something i've done wrong?

Thanks a lot!

**Comment by Naktibalda** [comment]
Could it be caused by a firewall?

**Comment by mfk** [comment]
I think I have a SSL problem. I can't get any content from pages with SSL. How can i fix this? any ideeas?

**Comment by Naktibalda** [comment]
It probably is an issue of chromedriver.

**Comment by STFdevelopers** [comment]
Did you solve it? @mfk 
I did in my java test:

```
ChromeOptions options = new ChromeOptions();
options.addArguments("--headless");
options.setAcceptInsecureCerts(true);
```
And now, it runs properly

**Comment by kelunik** [comment]
I have a similar problem, but only in `--headless` more. Without `--headless` everything works fine. I have `--ignore-certificate-errors` as an additional argument.

**Comment by kadnan** [comment]
@mfk did you find solution?

**Comment by kelunik** [comment]
`--allow-insecure-localhost` fixed it for me.

**Comment by kadnan** [comment]
@kelunik It does not work for me.

**Comment by abdullohhabib** [comment]
@mfk could you tell me how you eventually solve your problem? right now, I deal with the same thing but I got nowhere to get set up
