### ISSUE TITLE
[Yii2] Cookie signing

### ISSUE THREAD

**Issue by SamMousa** [Codeception/Codeception#4656]
#### What are you trying to achieve?
I'd like to use `$I->setCookie()` without disabling Yii's cookie validation.

#### What do you get instead?
The Yii request object filters unsigned cookies.

### Details
This could be solved by overriding `setCookie` in the Yii2 module:
````
public function setCookie($name, $val, array $params = [])
    {
        // Sign the cookie.
        if ($this->app->request->enableCookieValidation) {
            $val = Yii::$app->getSecurity()->hashData(serialize([$name, $val]), $this->app->request->cookieValidationKey);
        }
        parent::setCookie($name, $val, $params);
    }
````

The issue is not a technical one, but more a philosophical one: Do we want to support these security features during testing? In my opinion disabling them increases changes of a misconfiguration ending up in production somewhere.

**Comment by samdark** [comment]
Yes. Would be good if it will work out of the box.

**Comment by SamMousa** [comment]
See PR
