### ISSUE TITLE
Last test is always skipped with message "Dependent test for TEST not found"

### ISSUE THREAD

**Issue by ulmink** [Codeception/Codeception#4661]
Hello,

I am using AcceptanceTester with PhpBrowser. Tests are placed in multiple files. Most tests have dependency on Cest tests for authorization (customer, admin)
```
class CustomerAuthCest {
    function loginCustomer(AcceptanceTester $I) {}
}

class AdminAuthCest {
    function loginAdmin(AcceptanceTester $I) {}
}

class AdminPages {
    /**
     * @depends AdminAuthCest:loginAdmin 
     */
    function testProfile(AcceptanceTester $I) {}
}

class CustomerPages {
    /**
     * @depends CustomerAuthCest:loginCustomer 
     */
    function testProfile(AcceptanceTester $I) {}
}
```

When my test suite misses AdminAuthCest.php:
- (OK) related dependent tests are skipped, e.g. AdminPages:testProfile
- (KO) CustomerPages:testProfile is skipped too with message *Dependent test for CustomerAuthCest:loginAdmin not found* (no matter whether it has @depends annotation or not)

### Details

* Codeception version: 2.3.6
* PHP Version: 7.0
* Installation type: Phar

p.s. it looks close to https://github.com/Codeception/Codeception/issues/4598

**Comment by Naktibalda** [comment]
Yes, it is that issue.
Wait for 2.3.7 (@DavertMik promised to release it today)
