### ISSUE TITLE
Wrong signature in DummyCodeCoverage::stop

### ISSUE THREAD

**Issue by Lepsh14eG** [Codeception/Codeception#4663]
Need to add 4th parameter "$ignoreForceCoversAnnotation = false" in DummyCodeCoverage::stop method for keeping signature from "SebastianBergmann\CodeCoverage\CodeCoverage"

**Comment by Naktibalda** [comment]
Please make a pull request.

**Comment by mindplay-dk** [comment]
It's been [fixed](https://github.com/Codeception/Codeception/commit/4ca1316294e9a13030bc99695241a29571f4638c) in `master` already, can we get a release up pls? This is breaking all our builds 😐

**Comment by jasonbahl** [comment]
Our builds are broken as well. 

![screen shot 2017-12-07 at 11 10 48 am](https://user-images.githubusercontent.com/1260765/33731113-4e90d31c-db3f-11e7-8e22-effa12c02385.png)

**Comment by jairusmartin** [comment]
As a temporary fix, I am specifying "phpunit/php-code-coverage": "5.2".

**Comment by Naktibalda** [comment]
Fixed since 2.3.7
