### ISSUE TITLE
Click link identified by href

### ISSUE THREAD

**Issue by JonoB** [Codeception/Codeception#467]
It may be that you have multiple links on a page, all with the same text, but different href's. For example, you have something like this in a table:

``` html
<a href="items/1/edit" class="btn">Edit</a>
<a href="items/2/edit" class="btn">Edit</a>
```

Currently (unless I am missing something), it is not possible to select which of these links you want to click.

The `seeLink()` method can specify which href you want to target (`seeLink('Edit', 'items/1/edit`)`, but I can't see a way to  specify a more precise click

**Comment by TomaszKane** [comment]
OK, but this is confusing when method seeLink()
> I see link "a","/promotion/update?id=1" ~OK

works and click()

> I click {"link":"/promotion/update?id=1"} ~not found on page
> I click "//a[@href='/promotion/update?id=1']" ~not found on page
> I click "a[href='/promotion/update?id=1']" ~not found on page

doesn't...

**Comment by jairusmartin** [comment]
What does one do if they have this:
`<a href="/site/index"><span class="glyphicon glyphicon-home"></span>&nbsp;Home</a>`

**Comment by marafee1243** [comment]
@jairusmartin  Have found any solution for that. I am currently looking for it.

**Comment by Ragazzo** [comment]
@DavertMik can you check that please?

**Comment by jairusmartin** [comment]
It appears the search text must match exactly after the tags have been removed.
Like this: `I->click(' Home')`

In short, for test ability, it is better to use CSS for appearance and not use white space characters.
