### ISSUE TITLE
execution does not stop when doing CTRL + C

### ISSUE THREAD

**Issue by ctrl-f5** [Codeception/Codeception#4678]
#### What are you trying to achieve?

stop codeception execution with CTRL+C in bash

#### What do you get instead?

continued codeception execution

### Details

* Codeception version: 2.3.6
* PHP Version: 7.0.26
* Operating System: linux
* Installation type: Composer

**Comment by DavertMik** [comment]
Please update PHP.

**Comment by Naktibalda** [comment]
@davertMik what version of PHP solves this issue?

**Comment by ctrl-f5** [comment]
pcntl has been in PHP since V4.....

this has nothing to do with php itself, it's a userland implementation issue.

**Comment by Naktibalda** [comment]
Original issue: #3607

**Comment by Naktibalda** [comment]
According to #3907 upgrading to PHP 7.1 should solve your issue.
