### ISSUE TITLE
I cannot create an Screenshot inside a folder.

### ISSUE THREAD

**Issue by Malavos** [Codeception/Codeception#4679]
Hello everyone,

I am trying to make a simple screenshot in codeception, with an absolute path:

`$I->makeScreenshot('C:/test/logged/');`

The problem is, the folder is not created and the screenshot is not saved. If I try to save it simply as 

`$I->makeScreenshot('logged/');`

It will correctly save to the output folder, but that's not what I want. I am aiming to provide a solution to create a folder with the test name and a timestamp, dynamically. How can I achieve that?

I took a look at #707, but I can't see to find the solution to the problem on it - there is no indication on the docs or on that issue on how to solve my problem.

**Comment by Malavos** [comment]
@SamMousa  could you give me a hand with that? 🥇

**Comment by SamMousa** [comment]
@Malavos why me?

**Comment by Malavos** [comment]
@SamMousa  Just looked for the last to make a commit on the project!  😆 

Do you know how to make screenshots to a folder? Or where can I look into this?

**Comment by SamMousa** [comment]
> @SamMousa Just looked for the last to make a commit on the project!  :laughing:

That's not acceptable. Please do not ping randomly people with whom you've had no interaction.
I will now unsubscribe from this issue, good luck with your problem.

**Comment by Malavos** [comment]
@SamMousa  Weird. I was just asking for help. Looked for someone active, and found you. I see users do it all the time. Be it in other open source projects I contribute to, like Unreal Engine, MahApps or Boleto.net.

Don't be mad because of it. Someone just asked for help from someone their thought could help. Pinging is not a invasion of your privacy or anything, no need to get mad over it.

But it's okay, thanks anyway

**Comment by Malavos** [comment]
Closing the issue. I implemented my own method with node to create a folder and save a screenshot to it.

If anyone wanna check what I did, see [this package for future reference.](https://www.npmjs.com/package/mkdirp)
