### ISSUE TITLE
Codeception FillField not working

### ISSUE THREAD

**Issue by GoutamNaikGaonkar** [Codeception/Codeception#4689]
$this->I->fillField(['css' => 'form[name=booking__search] input[name=sPhrase]'],$matches[0]);

The value passed is like NUR-11620
but in browser it inputs like NUR-11

**Comment by Naktibalda** [comment]
ChromeDriver has quite a few issues like this, usually related to VNC, remote X, etc.
The first one is exact match:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1509&q=key%206&colspec=ID%20Status%20Pri%20Owner%20Summary
https://bugs.chromium.org/p/chromedriver/issues/detail?id=677&q=key%206&colspec=ID%20Status%20Pri%20Owner%20Summary
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1627&q=key%206&colspec=ID%20Status%20Pri%20Owner%20Summary
https://bugs.chromium.org/p/chromedriver/issues/detail?id=707&q=key%206&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by Naktibalda** [comment]
Issue with character `6` has been reported before: #4022
