### ISSUE TITLE
How to stop test suite execution from test itself using GracefulTermination() ?

### ISSUE THREAD

**Issue by JGladykowski-modus** [Codeception/Codeception#4690]
In some edge case, I want to stop execution of test suite completely, from the `AcceptanceTester` class. I found `GracefulTermination()` for this in [GracefulTermination.php](https://github.com/Codeception/Codeception/blob/3.0/src/Codeception/Subscriber/GracefulTermination.php) but it needs instance of `SuiteEvent`. 

Is it possible to do this ?

**Comment by saiedtrife** [comment]
Will I have similar problem.

I just use the function with php:
`die(); `

I know is not the best solution but it works for me.

**Comment by JGladykowski-modus** [comment]
Thank you @saiedtrife . I use same as a temporary workaround, and also quit web driver first. But it would be much more elegant to use this built-in method.

**Comment by abdrmdn** [comment]
But was this ever done?

**Comment by Naktibalda** [comment]
I looked into this and I think that using die() is the best option.

The easiest way would be to emit SIGTERM or SIGINT event, but I have no idea how to do that.

The second easiest way would be to call `stopOnError(true)` and `stopOnFailure(true)` and throw exception, but modules don't receive SuiteEvent object in beforeSuite hook. It requires a small code change in \Codeception\Subscriber\Module class to pass SuiteEvent to beforeSuite.

It should be possible to use `die()` and avoid `COMMAND DID NOT FINISH PROPERLY.` method by retrieving EventDispatcher from test Metadata and emitting SUITE_AFTER event before die(), but it can have all kinds of unintended consequences.
