### ISSUE TITLE
seeEmailIsSent() not working with Symfony command

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4698]
When using Codeception to test a Symfony command (i.e. `php bin/console app:my_command`), the `seeEmailIsSent()` assertion gives me:

> You must perform a request before using this method.

This does make some sense, since there was no actual request made. However, the email (of course) is being sent by Symfony. So it would be nice if `seeEmailIsSent()` would work in the CLI context too.

* Codeception version: 2.3.7

**Comment by DavertMik** [comment]
We can't hook into an external process to check an email...
