### ISSUE TITLE
PHPUnit 6.5 support

### ISSUE THREAD

**Issue by chris1312** [Codeception/Codeception#4715]
#### What are you trying to achieve?

Utilize latest PHPUnit version in my project together with Codeception.

#### What do you get instead?

I cannot install latest PHPUnit version because it requires `phpunit/phpunit-mock-objects: ^5.0.4` when Codeception supports only `<5.0`.

### Details

* Codeception version: v2.3.6
* PHP Version: 7.2
* Operating System: Ubuntu 16.0.4
* Installation type: Composer
* Suite configuration: (not relevant for this case)

**Comment by Naktibalda** [comment]
This ticket should be named PHPUnit 6.5 support.
Requirement for mock objects was bumped in 6.5.0 version.

**Comment by chris1312** [comment]
@Naktibalda @DavertMik Thank you!
