### ISSUE TITLE
beforeClass/afterClass

### ISSUE THREAD

**Issue by marabesi** [Codeception/Codeception#4725]
#### What are you trying to achieve?

Hello, guys sorry for opening such simple thread but I tried to use the annotations `beforeClass` and `afterClass` as described [here](https://github.com/Codeception/Codeception/issues/1002) but without success.

The method doesn't get executed.

What is working though is the `_after` and `_before` methods.

**Comment by DavertMik** [comment]
Yes, the mentioned issue is like 3 years old so I don't think it's relevant.

beforeClass and afterClass are implemented (somehow) but are not recommended. It's better to move that logic to a Helper class or a GroupObject. This way you could separate a setup from the testcase
