### ISSUE TITLE
code sniffer

### ISSUE THREAD

**Issue by rebas82** [Codeception/Codeception#4727]
Hi, i use code sniffer and php inspection in ide php storm.

In file \tests\_support\ApiTester.php

```
<?php

use \Codeception\Actor;

/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void comment($description)
 * @method \Codeception\Lib\Friend haveFriend($name, $actorClass = NULL)
 *
 * @SuppressWarnings(PHPMD)
*/
class ApiTester extends Actor
{
    use _generated\ApiTesterActions;

   /**
    * Define custom actions here
    */
}
```

Code sniffer have problem with this line:
class AcceptanceTester extends Actor

warning is: phpcs: PSR1.Classes.ClassDeclaration.MissingNamespace: Each class must be in a namespace of at least one level (a top-level vendor name)

What namespace use? Or what can i do?

**Comment by Naktibalda** [comment]
http://codeception.com/docs/reference/Configuration
`namespace`: set a namespace for tests. All new tests and support classes will be generated under that namespace. 

As for existing files, you will have to update the actor file and all test files manually or by using refactoring tools of your IDE.

**Comment by rebas82** [comment]
thanks, working.
