### ISSUE TITLE
Compatibility issue with laravel 5.5

### ISSUE THREAD

**Issue by shawnspaul** [Codeception/Codeception#4736]
#### What are you trying to achieve?
composer create-project laravel/laravel="5.5.0" project

codeception didn't seem to like phpUnit 6.5. I was prompted to use phpUnit 4.8.2 - 6.0. I down-graded and that got rid of the phpUnit issue. But codeception also doesn't seem to like symfony/event-dispatcher 4.0.3

I ended up reverting to laravel 5.4.30 and codeception downloaded successfully.

Full error below:

#### What do you get instead?
$ composer require "codeception/codeception"
Using version ^2.3 for codeception/codeception
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install codeception/codeception 2.3.7
    - Conclusion: don't install codeception/codeception 2.3.6
    - Conclusion: don't install codeception/codeception 2.3.5
    - Conclusion: don't install codeception/codeception 2.3.4
    - Conclusion: don't install codeception/codeception 2.3.3
    - Conclusion: don't install codeception/codeception 2.3.2
    - Conclusion: don't install codeception/codeception 2.3.1
    - Installation request for phpunit/phpunit-mock-objects (locked at 5.0.6) -> satisfiable by phpunit/phpunit-mock-objects[5.0.6].
    - Conclusion: remove symfony/event-dispatcher v4.0.3
    - Installation request for codeception/codeception ^2.3 -> satisfiable by codeception/codeception[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7].
    - Conclusion: don't install symfony/event-dispatcher v4.0.3
    - codeception/codeception 2.3.0 requires symfony/event-dispatcher >=2.7 <4.0 -> satisfiable by symfony/event-dispatcher[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2, v3.4.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.0, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.1, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.10, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.11, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.12, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.13, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.14, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.15, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.16, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.17, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.18, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.19, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.2, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.20, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.21, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.22, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.23, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.24, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.25, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.26, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.27, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.28, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.29, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.3, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.30, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.31, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.32, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.33, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.4, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.5, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.6, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.7, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.8, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.9, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.0, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.1, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.2, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.3, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.4, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.5, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.6, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.7, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.8, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.0.9, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.0, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.1, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.10, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.2, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.3, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.4, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.5, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.6, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.7, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.8, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.1.9, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.0, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.1, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.10, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.11, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.12, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.13, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.14, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.2, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.3, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.4, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.5, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.6, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.7, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.8, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.2.9, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.0, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.1, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.10, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.11, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.12, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.13, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.14, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.15, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.2, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.3, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.4, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.5, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.6, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.7, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.8, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.3.9, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.4.0, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.4.1, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.4.2, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v3.4.3, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.0, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.1, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.10, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.11, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.12, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.13, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.14, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.15, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.16, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.17, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.18, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.19, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.2, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.20, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.21, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.22, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.23, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.24, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.25, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.26, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.27, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.28, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.29, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.3, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.30, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.31, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.32, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.33, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.34, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.35, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.36, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.37, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.38, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.39, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.4, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.40, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.5, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.6, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.7, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.8, v4.0.3].
    - Can only install one of: symfony/event-dispatcher[v2.7.9, v4.0.3].
    - Installation request for symfony/event-dispatcher (locked at v4.0.3) -> satisfiable by symfony/event-dispatcher[v4.0.3].

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
The next release (2.3.8) will support PhpUnit 6.5
If you want it now, set version constraint to "dev-2.3"

symfony/event-dispatcher v4.0.3 is supported since 2.3.7
https://github.com/Codeception/Codeception/blob/2.3.7/composer.json#L29

**Comment by zelf** [comment]
Hey, downgrade to phpunit 6.4.4 it will work until the next codeception update.

**Comment by Naktibalda** [comment]
Codeception 2.3.8 was released 3 days ago, it is compatible with PhpUnit 6.5
