### ISSUE TITLE
Codeception no such session issue

### ISSUE THREAD

**Issue by GoutamNaikGaonkar** [Codeception/Codeception#4738]
I am getting the following issue while running the test suite

[Facebook\WebDriver\Exception\NoSuchDriverException]
  no such session
    (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 3.16.0-4-amd64 x86_64)

[Facebook\WebDriver\Exception\UnrecognizedExceptionException]
  chrome not reachable
    (Session info: chrome=63.0.3239.132)
    (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 3.16.0-4-amd64 x86_64)

**Comment by dekar91** [comment]
I have the sa,e problem. Have you found a solution?

**Comment by GoutamNaikGaonkar** [comment]
Yes.. Please restart selenium and it should work..
