### ISSUE TITLE
Use method from _support\Helper\Functional.php in @prepare annotation?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4740]
Is it possible to call a method from the helpers file inside a `@prepare` annotation, or can you only call methods in the very same (Cest) file?

* Codeception version: 2.3.7

**Comment by DavertMik** [comment]
Yes, you can. Within prepare you specify a method, where you declare which classes you need. If you set a class as a argument it will be injected into a method so you can use its method:

```php
function prepareHelper(\Helper\Function $myHelper)
{
    $this->myHelper->doSmth();
}
```

**Comment by ThomasLandauer** [comment]
OK, so what you're saying is:
```php
// MyCest.php

/**
 * @prepare prepareHelper
**/
public function tryWhatever (FunctionalTester $I)
{
}

private function prepareHelper(\Helper\Functional $myHelper)
{
    $myHelper->doSmth(); // you just mistyped this line, didn't you?
}
```
But `prepareHelper()` still needs to be in the same Cest file as `tryWhatever()`? This is exactly my question: Would it be possible to move `prepareHelper()` itself into `\Helper\Functional`? And then reference it with something like `@prepare \Helper\Functional::prepareHelper`?

Reason: If you have 15 Cest files that need the same `@prepare`-thing, it would be nice to just declare it once.

**Comment by DavertMik** [comment]
>  you just mistyped this line, didn't you?
Yes!

> But prepareHelper() still needs to be in the same Cest file as tryWhatever()

Yes

>  And then reference it with something like @prepare \Helper\Functional::prepareHelper?

Not possible now

> Reason: If you have 15 Cest files that need the same @prepare-thing, it would be nice to just declare it once.

I think you should take a look into GroupObjects then

**Comment by ThomasLandauer** [comment]
OK, thanks :-)

Here's the link: http://codeception.com/docs/08-Customization#Group-Objects
