### ISSUE TITLE
Update Docker to use PHP 7.2

### ISSUE THREAD

**Issue by lougreenwood** [Codeception/Codeception#4742]
#### What are you trying to achieve?

Use the official Docker image to test code written with PHP 7.2

https://hub.docker.com/r/codeception/codeception/

#### What do you get instead?

various errors, e.g:

`  [ParseError] syntax error, unexpected '?'` (Docker image uses PHP 7.0, which does not support nullable return types)

#### Notes
* PHP 7.2 does not yet have support from XDebug, so if the Docker image for Codeception requires XDebug, then PHP 7.1 is the latest version which the Docker image can be updated to.
* XDebug will support PHP 7.2 in it's upcoming 2.6 release - https://xdebug.org
* In any case, PHP 7.0 (which the Docker image currently uses) is no longer "actively supported" by the PHP project: http://php.net/supported-versions.php

**Comment by DavertMik** [comment]
@schmunk42 can you handle that?

**Comment by samdark** [comment]
2.3

**Comment by schmunk42** [comment]
Currently available in `2.3` and `latest`, see https://hub.docker.com/r/codeception/codeception/tags/

**Comment by schmunk42** [comment]
@DavertMik Since DockerHub is an automated build, it might make sense to add some Docker compatibility info to the README. Ie. version `2.3.8` or `2.4.0` will be based on PHP 7.2.
