### ISSUE TITLE
Commands shortcuts

### ISSUE THREAD

**Issue by Ragazzo** [Codeception/Codeception#475]
Would be great if Codeception will have some command shortcuts, or will understand commands if they are not fully written, like composer do.
for example in composer we can:

``` php
php composer.phar self-u
php composer.phar ins
```

if we will have this in Codeception or some shortcuts it will be cool, like this:
- generate:pageobject -> gpo
- generate:cest -> gct
- generate:cept ->gcp
  ...
  and other.

p.s. very tired to write this long commands )

**Comment by DexterHD** [comment]
I try to rewrite @kuntashov autocomplete and make in more powerful.
https://github.com/DexterHD/codecept-bash-completion
Now it actual for Codeception 2.0.11 and I will try to keep it up to date.

**Comment by tiger-seo** [comment]
:+1:

**Comment by sagikazarmark** [comment]
@DexterHD I added your completion file to this package:
https://launchpad.net/~sagikazarmark/+archive/ubuntu/development/+sourcepub/4943789/+listing-archive-extra

**Comment by DexterHD** [comment]
@sagikazarmark Cool :+1:
