### ISSUE TITLE
Symfony deprecation warning on `grabService()`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4752]
This might be related to https://github.com/Codeception/Codeception/issues/4318

When calling `$I->grabService()` in a functional test, I'm getting this message:

> The "XY" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead

* Codeception version: 2.3.7

**Comment by Naktibalda** [comment]
a) it isn't an issue,
b) have you tested if it works with Symfony 4.0 ?

**Comment by ThomasLandauer** [comment]
b) No, I haven't. The message is from Symfony 3.4.3. Do you think it will "disappear" in Symfony 4.0?

**Comment by Naktibalda** [comment]
At least it didn't break Doctrine module.

**Comment by ThomasLandauer** [comment]
Finally fixed in Codeception 3.1.2 via https://github.com/Codeception/Codeception/pull/5706
