### ISSUE TITLE
Module for MailCatcher?

### ISSUE THREAD

**Issue by ebuildy** [Codeception/Codeception#4754]
I use MailCatcher in all my projects and plan to write a small helper for this, is a Codeception module planed to handle it?

#### What are you trying to achieve?

I want to use MailCatcher (https://mailcatcher.me/) as much seamless as possible.

#### What do you get instead?

I must use REST module to handle it.

**Comment by DavertMik** [comment]
We have MailCatcher module available as a standalone package. See it here: http://codeception.com/addons

It has a different maintainer so for any issues please contact https://github.com/captbaritone/codeception-mailcatcher-module
