### ISSUE TITLE
runShellCommand within transaction in SQLite?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4756]
When doing [runShellCommand](http://codeception.com/docs/modules/Cli.html#runShellCommand) within a transaction (i.e. `Doctrine2: cleanup: true` in functional.suite.yml) with an SQLite database, I'm getting this error (after the execution hangs for several seconds):

> SQLSTATE[HY000]: General error: 5 database is locked

I'm guessing that the transaction blocks access to the database file, and therefore the shell command can't access it, right?

Is this a bug? Is there a workaround? Or is it just bad luck? ;-)

* Codeception version: 2.3.7

**Comment by DavertMik** [comment]
>  Or is it just bad luck

Yeah, just this :)

Sorry not aware of how to solve this but I won't consider this to be a common issue.
