### ISSUE TITLE
Functional tests in Yii2 throws error: ini_set(): A session is active. You cannot change the session module's ini settings at this time

### ISSUE THREAD

**Issue by StalkAlex** [Codeception/Codeception#4759]
#### What are you trying to achieve?
Run functional tests previously worked before PHP 7.2 update. First form submit throws this error.

#### What do you get instead?
```bash
[yii\base\ErrorException] ini_set(): A session is active. You cannot change the session module's ini settings at this time
```
### Details

* Codeception version: 2.3.7
* PHP Version: 7.2
* Operating System: Docker, Alpine
* Installation type: Composer

**Comment by StalkAlex** [comment]
Here's related info. https://bugs.php.net/bug.php?id=75227

**Comment by StalkAlex** [comment]
@samdark  here's [exact](https://github.com/yiisoft/yii2/blob/master/framework/web/Session.php#L481) line causing problem, I just suppressed errors adding '@' symbol before `ini_set` and problem has gone, if this solution is ok, I can make a PR. I don't think it will change much, due to information above this line doesn't do anything indeed even before php 7.2

**Comment by bscheshirwork** [comment]
@StalkAlex  pls see changelog of php7.2 - some functional will be changed.

@samdark may be we can use `$this->getIsActive()` for all `ini_set` functions?

**Comment by StalkAlex** [comment]
> some functional will be changed
@bscheshirwork what do you mean?

**Comment by bscheshirwork** [comment]
This behavior is correct for 7.2. 
Now we need 
first
configure session
second
start session

**Comment by StalkAlex** [comment]
agree, but It can produce some amout of changes.

**Comment by samdark** [comment]
> may be we can use $this->getIsActive() for all ini_set functions?

**Comment by StalkAlex** [comment]
ok, I'm open to make those changes.

**Comment by bscheshirwork** [comment]
I think we need changes like 
https://github.com/yiisoft/yii2/blob/1bc17a3d22cae876df66486306cc9e4e8effa970/framework/web/Session.php#L203-L205
```
            $this->close();
            $this->setId($sessionId);
            $this->open();
```
for example
https://github.com/yiisoft/yii2/blob/1bc17a3d22cae876df66486306cc9e4e8effa970/framework/web/Session.php#L414-L426
```php
    public function setUseCookies($value)
    {
        $this->close();
        if ($value === false) {
            ini_set('session.use_cookies', '0');
            ini_set('session.use_only_cookies', '0');
        } elseif ($value === true) {
            ini_set('session.use_cookies', '1');
            ini_set('session.use_only_cookies', '1');
        } else {
            ini_set('session.use_cookies', '1');
            ini_set('session.use_only_cookies', '0');
        }
        $this->open();
    }
```
