### ISSUE TITLE
Yii2 behaviors aren't executed for haveRecord() method

### ISSUE THREAD

**Issue by uaoleg** [Codeception/Codeception#4762]
#### What are you trying to achieve?
I'm trying to create a test AR:

        $I->haveRecord(EmailContact::class, [
            'address'   => 'test1@email.com',
        ]);

The thing is that `EmailContact` AR has behavior for `address` attribute which converts it before save (encrypts) and after find (decrypts). So I expect that `haveRecord()` method will run behaviors as simple `save()` does.

    /**
     * Returns a list of behaviors that this component should behave as
     * @return array
     */
    public function behaviors()
    {
        return [
            [
                'class' => \common\behaviors\AesBehavior::class,
                'key' => \yii::$app->params['aes.key'],
                'attributes' => ['address'],
            ]
        ];
    }

#### What do you get instead?
AR behaviors are not executed

### Details

* Codeception version:
* PHP Version: v2.3.6
* Operating System: Windows 10
* Installation type: Composer

**Comment by bscheshirwork** [comment]
This line is the culprit
```php
        $record = new $model;
```
https://github.com/Codeception/Codeception/blob/be8a6a5c642f267650f56a00931640e46f880e07/src/Codeception/Module/Yii2.php#L484-L494
https://github.com/Codeception/Codeception/blob/be8a6a5c642f267650f56a00931640e46f880e07/src/Codeception/Module/Yii2.php#L410-L412

solution is
```php
        $record = Yii::createObject($model);
```

**Comment by samdark** [comment]
I'd not expect so. We're not saving anything so I don't think any behaviors should run.

**Comment by bscheshirwork** [comment]
`$record->save(false);` also can't run validation

**Comment by samdark** [comment]
Why do we need validation when getting a mock-record?

**Comment by uaoleg** [comment]
I'm just wondering why it's a mock-record? This method allows to save a real DB-record (using transaction) which will be removed after test run

**Comment by samdark** [comment]
I mean we know what we're doing here so extra validation doesn't make much sense.

**Comment by uaoleg** [comment]
But it's not about validation, it's about behaviors that perform preprocessing of attributes' values

**Comment by samdark** [comment]
Right. Fix merged.

**Comment by DiscipleOfShinku** [comment]
> Why do we need validation when getting a mock-record?

If a model has `default` rules it can cause problems.
