### ISSUE TITLE
Couldn't parse test '/var/www/html/projects/php/iceshop/dev/tests/codeception/tests/acceptance/FrontendUserCept.php'  sh: 1: php: not found 

### ISSUE THREAD

**Issue by tonpascual** [Codeception/Codeception#4766]
on vendor/codeception/codeception/src/Codeception/Lib/Parser.php

    public static function validate($file)
    {
        $config = Configuration::config();
        if (empty($config['settings']['lint'])) { // lint disabled in config
            return;
        }
        if (!function_exists('exec')) {
            //exec function is disabled #3324
            return;
        }
        exec("php -l " . escapeshellarg($file) . " 2>&1", $output, $code);
        if ($code !== 0) {
            throw new TestParseException($file, implode("\n", $output));
        }
    }

This will cause an issue if you are running e.g. compiled from source php 

> exec("php -l " . escapeshellarg($file) . " 2>&1", $output, $code);

**Comment by Naktibalda** [comment]
You can set `lint: false` in `settings` section of codeception.yml, if you don't have php executable.
http://codeception.com/docs/reference/Configuration#Global-Configuration

**Comment by tonpascual** [comment]
tnks, this is now fixed
