### ISSUE TITLE
FATAL ERROR. TESTS NOT FINISHED. Maximum execution time of 1 second exceeded

### ISSUE THREAD

**Issue by Roobix13** [Codeception/Codeception#4771]
Getting this error after test. Not one test, it fails at different tests each time.
If anyone had the same troubles or knows why this is triggered please let me know.

```php
FATAL ERROR. TESTS NOT FINISHED.
Maximum execution time of 1 second exceeded
in /Users/userName/Development/foldername/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:274
```
### Details

* Codeception version: latest
* PHP Version: 5.6.10
* Operating System: MacOS
* Installation type: Composer
* List of installed packages:

behat/gherkin                      v4.4.5  Gherkin DSL parser for PHP 5.3
codeception/codeception            2.3.6   BDD-style testing framework
codeception/verify                 0.4.0   BDD assertion library for PHPUnit
codeception/visualception          0.0.1
doctrine/instantiator              1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.4.1   A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1  Guzzle promises library
guzzlehttp/psr7                    1.4.2   PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.7.0   Create deep copies (clones) of your objects
phpdocumentor/reflection-common    1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  3.2.2   With this component, a library can provide support for annotations via DocBlocks or otherwise re...
phpdocumentor/type-resolver        0.3.0
phpspec/prophecy                   v1.7.2  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          4.0.8   Library that provides collection, processing, and rendering functionality for PHP code coverage ...
phpunit/php-file-iterator          1.4.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  1.0.9   Utility class for timing
phpunit/php-token-stream           1.4.11  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.7.23  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.4   Mock Object library for PHPUnit
psr/http-message                   1.0.1   Common interface for HTTP messages
psr/log                            1.0.2   Common interface for logging libraries
sebastian/code-unit-reverse-lookup 1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator               1.2.4   Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.3   Diff implementation
sebastian/environment              2.0.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 2.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state             1.1.1   Snapshotting of global state
sebastian/object-enumerator        2.0.1   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context        2.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
stecman/symfony-console-completion 0.7.0   Automatic BASH completion for Symfony Console Component based applications.
symfony/browser-kit                v3.3.12 Symfony BrowserKit Component
symfony/console                    v3.3.12 Symfony Console Component
symfony/css-selector               v3.3.12 Symfony CssSelector Component
symfony/debug                      v3.3.12 Symfony Debug Component
symfony/dom-crawler                v3.3.12 Symfony DomCrawler Component
symfony/event-dispatcher           v3.3.12 Symfony EventDispatcher Component
symfony/finder                     v3.3.12 Symfony Finder Component
symfony/polyfill-mbstring          v1.6.0  Symfony polyfill for the Mbstring extension
symfony/process                    v3.3.12 Symfony Process Component
symfony/yaml                       v3.3.12 Symfony Yaml Component
webmozart/assert                   1.2.0   Assertions to validate method input/output with nice error messages.

class_name: AcceptanceTester
modules:
  enabled:
      - WebDriver
      - \Helper\Acceptance
      - VisualCeption
      - Asserts
  config:
    WebDriver:
      url: 'https://www.website.com/'
      browser: 'chrome'
      window_size: 1280x1280
    VisualCeption:
      referenceImageDir: '/Users/riacoveciu/Projekte/test_one/tests/_data/VisualCeption'
      maximumDeviation: 5                                   # deviation in percent
      saveCurrentImageIfFailure: true                       # if true, VisualCeption saves the current
      report: true
env:
  production:
      modules:
        config:
          WebDriver:
            url: '
  devnet:
      modules:
        config:
          WebDriver:
            url: 
  dev:
      modules:
        config:
          WebDriver:
            url: 
  web-ctest:
      modules:
        config:
          WebDriver:
            url: 
  web-itest:
      modules:
        config:
          WebDriver:
            url:

**Comment by Naktibalda** [comment]
Search for `set_time_limit(1);` in your code.

**Comment by Roobix13** [comment]
@Naktibalda I did found `set_time_limit(1);` in my code. What should i change it to ?

**Comment by Naktibalda** [comment]
Remove it or at least use a feature flag to prevent it running in tests.

**Comment by Naktibalda** [comment]
Have you just changed 1 to 0?
0 is fine, but something is setting a limit to 1 and it isn't Codeception.

**Comment by Roobix13** [comment]
So i have a set_time_limit in my code set at 1. And another one i found set at 0. I guess the default one. So yes i think the set_time_limit(1) is giving me problems. Thank you.
