### ISSUE TITLE
How about more verbose in error reporting about outputDir?

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4772]
#### What are you trying to achieve?
I can see in acceptance test with coverage (-vvv) in response of browser (mothership of c3.php reported)
```sh
Fatal error: Uncaught Codeception\Exception\ConfigurationException: Path for output is not writable. Please, set appropriate access mode for output path. in phar:///var/www/html/codecept.phar/src/Codeception/Configuration.php on line <i>531</i>
```
I have 4 included = 1+4+4 places of set config (main, suite, actor)

what about tell me how `$dir` is not writable?
https://github.com/Codeception/Codeception/blob/be8a6a5c642f267650f56a00931640e46f880e07/src/Codeception/Configuration.php#L529-L533

### Details

* Codeception version:2.3
* PHP Version:7.2.1
* Operating System:alpine3.7
* Installation type: Phar

**Comment by Naktibalda** [comment]
I agree that it would be better to throw specific exception if mkdir or chmod failed instead of suppressing and ignoring warning.

**Comment by Naktibalda** [comment]
#5247 add path of output directory to exception message
