### ISSUE TITLE
Mockery Mocking Hard Dependencies

### ISSUE THREAD

**Issue by tecbeast42** [Codeception/Codeception#4773]
#### What are you trying to achieve?
I want to mock a hard dependencies with mockery and the mockery module for codeception. 

[Mockery Docs](http://docs.mockery.io/en/latest/cookbook/mocking_hard_dependencies.html)

This requires phpunit annotations to prevent class conflicts. I can add them if I use the codeception Test format.

Sadly if i try to execute the test alone it throws:
`PHP Fatal error:  Class 'Codeception\Test\Unit' not found in /var/www/html/tests/unit/CertificateRefresherTest.php on line 12`

If i  run all tests it will be ignored in the run.
The test passes without the annotations.

```
<?php

use App\Certificate;
use App\CertificateRefresher;
use App\Frontend\Api;
use Mockery;

/**
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
class CertificateRefresherTest extends \Codeception\Test\Unit
{

    public function _before()
    {
        Artisan::call('migrate:fresh');
    }

    // tests
    public function test_it_should_try_to_refresh_a_certificate_Via_frontend_api()
    {
        $expiredCertificate = new Certificate(
            [
                'certCache' => ['validTo_time_t' => time()],
                'domains' => ['test.de']
            ]
        );

        $apiMock = Mockery::mock('overload:App\Frontend\Api');

        $this->assertTrue($expiredCertificate->needs_refresh, 'Certificate should need refreshing');
        $this->assertFalse($expiredCertificate->was_refreshed, 'Certificate was not refreshed yet');
        $apiMock->shouldReceive('renewCertificates')
            ->with(['test.de'])
            ->once()
            ->andReturn('Successfully refreshed');

        (new CertificateRefresher($expiredCertificate))->refresh();

        $this->assertTrue($expiredCertificate->was_refreshed, 'Certificate was refreshed');
    }
}
```

### Details

* Codeception version: 2.3.7
* PHP Version: 7.2.1
* Operating System: Unix
* Installation type: Composer
* Suite configuration:

```yml
# Codeception Test Suite Configuration
#
# Suite for unit (internal) tests.

class_name: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
        - Laravel5
        - Mockery
```

**Comment by tmoitie** [comment]
Hi, did you ever resolve this @tecbeast42 ?

**Comment by daison12006013** [comment]
@Naktibalda I don't know why this post is closed, do we have any solutions on this problem?

**Comment by Naktibalda** [comment]
I don't think that this is an issue of Codeception.

**Comment by Naktibalda** [comment]
I had to use search for "Codeception MockeryModule" and the 3rd result was identical issue at
https://github.com/Codeception/MockeryModule/issues/8
