### ISSUE TITLE
amOnUrl is not working

### ISSUE THREAD

**Issue by nothing2everything** [Codeception/Codeception#4781]
#### What are you trying to achieve?
$I->amOnUrl("https://www.google.co.in");
#### What do you get instead?
[PHPUnit\Framework\Exception] array_key_exists() expects parameter 2 to be array, null given
> Provide console output if related. Use `-vvv` mode for more details.

```bash
VanityDomainsCest: Verify delete vanity domain
Signature: VanityDomainsCest:testDeleteVanityDomain
Test: tests/acceptance/VanityDomainsCest.php:testDeleteVanityDomain
Scenario --
Stopping trim-db-clickhouse ... done
Removing trim-db-clickhouse ... done
Creating trim-db-clickhouse ... 
Creating trim-db-clickhouse ... done
Starting trim-db-clickhouse ... done
Starting trim-redis ... 
Starting trim-redis ... donedone
Starting trim-db-mysql ... done
Starting trim-phearjs ... e ... done
Starting trim-gsb ... donee ... 
Starting trim-phearjs ... done
 I am on url "https://www.google.com"
  [Selenium browser Logs]  EMPTY 
  [Selenium driver Logs]  EMPTY 
  [Selenium client Logs] 
  15:02:42.141 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Executing: [delete all cookies])
  15:02:42.180 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [delete all cookies]
  15:02:42.181 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Executing: [delete session: c663f6ed33fddd5f2304f2e5f47c826c])
  15:02:42.285 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [delete session: c663f6ed33fddd5f2304f2e5f47c826c]
  15:07:03.685 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Executing: [new session: Capabilities {browserName: chrome}])
  15:07:04.319 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [new session: Capabilities {browserName: chrome}]
  15:07:04.324 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Executing: [maximise window])
  15:07:04.432 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [maximise window]
  15:07:12.405 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Executing: [fetching available log types])
  15:07:12.407 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [fetching available log types]
  15:07:12.408 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Executing: [fetching logs for: browser])
  15:07:12.411 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [fetching logs for: browser]
  15:07:12.412 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Executing: [fetching logs for: driver])
  15:07:12.415 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [fetching logs for: driver]
  15:07:12.417 INFO - org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Executing: [fetching logs for: client])
  
  [Selenium server Logs] 
  15:07:03.685 INFO - Executing: [new session: Capabilities {browserName: chrome}])
  15:07:03.686 INFO - Creating a new session for Capabilities {browserName: chrome}
  15:07:04.318 INFO - Detected dialect: OSS
  15:07:04.319 INFO - Done: [new session: Capabilities {browserName: chrome}]
  15:07:04.324 INFO - Executing: [maximise window])
  15:07:04.432 INFO - Done: [maximise window]
  15:07:12.405 INFO - Executing: [fetching available log types])
  15:07:12.407 INFO - Done: [fetching available log types]
  15:07:12.408 INFO - Executing: [fetching logs for: browser])
  15:07:12.411 INFO - Done: [fetching logs for: browser]
  15:07:12.412 INFO - Executing: [fetching logs for: driver])
  15:07:12.415 INFO - Done: [fetching logs for: driver]
  15:07:12.417 INFO - Executing: [fetching logs for: client])
  15:07:12.417 INFO - Done: [fetching logs for: client]
  
  Screenshot and page source were saved into '/home/sushil/gravity4/codeception/tests/_output/' dir
 ERROR 

-------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 9.19 seconds, Memory: 12.00MB

There was 1 error:

---------
1) VanityDomainsCest: Verify delete vanity domain
 Test  tests/acceptance/VanityDomainsCest.php:testDeleteVanityDomain
                                                                                                
  [PHPUnit\Framework\Exception] array_key_exists() expects parameter 2 to be array, null given  
                                                                                                

Scenario Steps:

 1. $I->amOnUrl("https://www.google.com") at tests/acceptance/VanityDomainsCest.php:903

/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:83
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:461
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:353
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:456
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Module.php:122
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:862
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Step.php:260
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Scenario.php:72
/home/sushil/gravity4/codeception/tests/_support/_generated/AcceptanceTesterActions.php:262
/home/sushil/gravity4/codeception/tests/acceptance/VanityDomainsCest.php:903
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Lib/Di.php:127
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Test/Cest.php:136
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Test/Cest.php:148
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Test/Cest.php:82
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Test/Test.php:87
/home/sushil/gravity4/codeception/vendor/phpunit/phpunit/src/Framework/TestSuite.php:744
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:106
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Codecept.php:188
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Codecept.php:179
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Command/Run.php:347
/home/sushil/gravity4/codeception/vendor/symfony/console/Command/Command.php:252
/home/sushil/gravity4/codeception/vendor/symfony/console/Application.php:938
/home/sushil/gravity4/codeception/vendor/symfony/console/Application.php:240
/home/sushil/gravity4/codeception/vendor/symfony/console/Application.php:148
/home/sushil/gravity4/codeception/vendor/codeception/codeception/src/Codeception/Application.php:108
/home/sushil/gravity4/codeception/vendor/codeception/codeception/codecept:42
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:
* PHP Version: 7.0.22
* Operating System: Ubuntu 16.04
* Installation type: Composer
* List of installed packages (`composer show`)
sushil@codebox:~/gravity4/codeception$ composer show
behat/gherkin                      v4.4.5 Gherkin DSL parser for PHP 5.3
codeception/codeception            2.3.7  BDD-style testing framework
doctrine/instantiator              1.0.5  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.5.0  A PHP client for Selenium WebDriver
flow/jsonpath                      0.3.4  JSONPath implementation for parsing, searching and flattening arrays
guzzlehttp/guzzle                  6.3.0  Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1 Guzzle promises library
guzzlehttp/psr7                    1.4.2  PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.7.0  Create deep copies (clones) of your objects
phar-io/manifest                   1.0.1  Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1  Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1  Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.2.0  With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information t...
phpdocumentor/type-resolver        0.4.0 
phpspec/prophecy                   1.7.3  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          5.3.0  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  1.0.9  Utility class for timing
phpunit/php-token-stream           2.0.2  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    6.4.4  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       4.0.4  Mock Object library for PHPUnit
psr/http-message                   1.0.1  Common interface for HTTP messages
psr/log                            1.0.2  Common interface for logging libraries
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.2  Provides the functionality to compare PHP values for equality
sebastian/diff                     2.0.1  Diff implementation
sebastian/environment              3.1.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0  Snapshotting of global state
sebastian/object-enumerator        3.0.3  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1  Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
symfony/browser-kit                v3.4.3 Symfony BrowserKit Component
symfony/console                    v3.4.3 Symfony Console Component
symfony/css-selector               v3.4.3 Symfony CssSelector Component
symfony/debug                      v3.4.3 Symfony Debug Component
symfony/dom-crawler                v3.4.3 Symfony DomCrawler Component
symfony/event-dispatcher           v3.4.3 Symfony EventDispatcher Component
symfony/finder                     v3.4.3 Symfony Finder Component
symfony/polyfill-mbstring          v1.6.0 Symfony polyfill for the Mbstring extension
symfony/process                    v3.4.3 Symfony Process Component
symfony/yaml                       v3.4.3 Symfony Yaml Component
theseer/tokenizer                  1.1.0  A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.2.0  Assertions to validate method input/output with nice error messages.
* Suite configuration:

```yml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
  enabled: [WebDriver, Db]
  config:
    WebDriver:
      url: 'http://local.tr.im'
      browser: 'firefox'
      clear_cookies: true
      request_timeout: '300'
      wait: 0
      window_size: maximize
      capabilities:
        #unexpectedAlertBehaviour: 'accept'

env:
  chrome:
    modules:
      config:
        WebDriver:
          browser: 'chrome'
          clear_cookies: true
          request_timeout: '300'
          wait: 0
          window_size: maximize
          capabilities:
            #unexpectedAlertBehaviour: 'accept'

  firefox:
    # nothing  changed
```

**Comment by Naktibalda** [comment]
You have empty `capabilities:` setting, so yaml parser sets it to null.

Commenting out `capabilities:` line in both places should fix this issue.

**Comment by nothing2everything** [comment]
Awesome! Thanks. :+1:
