### ISSUE TITLE
coverage problem: last line in "Not Executed" code in "if" mark as "Executed"

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4782]
#### What are you trying to achieve?
all  line mark as "Not Executed"
#### What do you get instead?
![peek 2018-01-25 12-59](https://user-images.githubusercontent.com/5769211/35382256-a88ca970-01cf-11e8-9980-675c94f3ed64.gif)

### Details

* Codeception version:2.3
* PHP Version:7.2.1
* Operating System:alpine3.7
* Installation type: Phar (c3.php) & Composer

**Comment by Naktibalda** [comment]
Please raise an issue with xdebug: https://bugs.xdebug.org/
