### ISSUE TITLE
test are not running and giving error

### ISSUE THREAD

**Issue by flik** [Codeception/Codeception#4783]
#### What are you trying to achieve?
I am running a basic test case.

#### What do you get instead?
dev@development:/var/www/htdocs/mweb/codeception-zf-tutorial$ ./vendor/bin/codecept --run
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR in /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 15
PHP Stack trace:
PHP   1. {main}() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/codecept:0
PHP   2. require_once() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/codecept:7
PHP   3. require_once() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/autoload.php:19
PHP   4. ComposerAutoloaderInitcc1760b027486efc8c6010b57fbd7353::getLoader() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/autoload.php:7
PHP   5. composerRequirecc1760b027486efc8c6010b57fbd7353() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/composer/autoload_real.php:56

> Provide console output if related. Use `-vvv` mode for more details.
dev@development:/var/www/htdocs/mweb/codeception-zf-tutorial$ ./vendor/bin/codecept --run -vvv
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR in /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 15
PHP Stack trace:
PHP   1. {main}() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/codecept:0
PHP   2. require_once() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/codecept:7
PHP   3. require_once() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/autoload.php:19
PHP   4. ComposerAutoloaderInitcc1760b027486efc8c6010b57fbd7353::getLoader() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/autoload.php:7
PHP   5. composerRequirecc1760b027486efc8c6010b57fbd7353() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/composer/autoload_real.php:56

```bash
dev@development:/var/www/htdocs/mweb/codeception-zf-tutorial$ ./vendor/bin/codecept --run -vvv
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR in /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 15
PHP Stack trace:
PHP   1. {main}() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/codecept:0
PHP   2. require_once() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/codecept:7
PHP   3. require_once() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/codeception/codeception/autoload.php:19
PHP   4. ComposerAutoloaderInitcc1760b027486efc8c6010b57fbd7353::getLoader() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/autoload.php:7
PHP   5. composerRequirecc1760b027486efc8c6010b57fbd7353() /mnt/hgfs/mweb/codeception-zf-tutorial/vendor/composer/autoload_real.php:56

```
opening a url

```php
 public function tryToTest(AcceptanceTester $I)
    {
		$I->wantTo('check login page');
		$I->amOnUrl('http://darw-bo.moveon-ui.com/');
		$I->see('Email');
   }
```
### Details

* Codeception version:  "codeception/codeception": "^2.3"
* PHP Version: PHP 5.3.14 (cli) (built: Dec 10 2013 15:24:07)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`) 
{
    "require": {
        "doctrine/orm": "*",
        "guzzlehttp/guzzle": "~6.0"
    },
    "require-dev": {
        "codeception/codeception": "^2.3"
    }
}

* Suite configuration:

``` yml
actor: FunctionalTester
class_name: TestGuy
modules:
    enabled: [ZF1, Db]
        # add a framework module here
        - \Helper\Functional



```

**Comment by Naktibalda** [comment]
Codeception 2.3 does not run on PHP 5.3
