### ISSUE TITLE
Does the if function work in codepcetion ?

### ISSUE THREAD

**Issue by Roobix13** [Codeception/Codeception#4793]
I am a bit confused, to understand why i will explain the problem im having.

**Problem** 

Users enters a number, then there is a 'check' method to see if the number ( in this case room ) is available.  
I made a simple if  function but codeception just stops at the condition.
After the if condition, which results in true, it should chose another floor and pick another room to check if that is available. 

`$I->wantTo('Pick a available room');

        $I->selectOption('body > div.mfp-wrap.mfp-close-btn-in.mfp-auto-cursor.mfp-desired-room.mfp-ready > div > div.mfp-content > div > div > div > div.mod-desired-room__filter > div.js-build-desired-level-select > div.input-select > select','1. Etage');

        $I->fillField('body > div.mfp-wrap.mfp-close-btn-in.mfp-auto-cursor.mfp-desired-room.mfp-ready > div > div.mfp-content > div > div > div > div.mod-desired-room__filter > div.js-build-desired-choose-room > div.grid.js-desired-room-choose > div > div > div:nth-child(1) > div > input[type="text"]','107');
        $this->checkFavRoom($I);

        if ($I->see('ENTSCHULDIGUNG'))
        {
            $I->selectOption('body > div.mfp-wrap.mfp-close-btn-in.mfp-auto-cursor.mfp-desired-room.mfp-ready > div > div.mfp-content > div > div > div > div.mod-desired-room__filter > div.js-build-desired-level-select > div.input-select > select','2. Etage');
            $I->fillField('body > div.mfp-wrap.mfp-close-btn-in.mfp-auto-cursor.mfp-desired-room.mfp-ready > div > div.mfp-content > div > div > div > div.mod-desired-room__filter > div.js-build-desired-choose-room > div.grid.js-desired-room-choose > div > div > div:nth-child(1) > div > input[type="text"]','214');
            $this->checkFavRoom($I);

        }`

**Shell output with -vvv**

```
 I select option "body > div.mfp-wrap.mfp-close-btn-in.mfp-auto-cursor.mfp-desired-room.mfp-
 ready > div > div.mfp-content > div...","1. Etage"

 I fill field "body > div.mfp-wrap.mfp-close-btn-in.mfp-auto-cursor.mfp-desired-room.mfp-ready > div > div.mfp-content > div > div >...","107"

 I click "body > div.mfp-wrap.mfp-close-btn-in.mfp-auto-cursor.mfp-desired-room.mfp-ready > div > div.mfp-content > div > div > div > div...."

 I see "ENTSCHULDIGUNG"

 PASSED
```

**Comment by Naktibalda** [comment]
`see` is not a condition - it is an assertion. If `see` fails, it throws exception and execution of test stops.
If it succeeds, it doesn't return anything.

Using `if` in test is a bad practice (if it actually is a test), you should have 2 separate tests - one when room is available and another when it isn't.

**Comment by Roobix13** [comment]
Okay that does make sense. 
Thank you.

**Comment by Naktibalda** [comment]
Don't run tests on live database.
Run tests on test database that you man mend in any way you like with Db module.

**Comment by DavertMik** [comment]
...and don't use IFs inside tests. Tests should be predictable. 
If your tests will fail you won't know is the problem in code, in room, or in moon phase. That's why run tests on predefined set of data. This way passing of a test will depend on the codebase only.
