### ISSUE TITLE
Allow ability to specify consistent random seed when tests are shuffled

### ISSUE THREAD

**Issue by acorncom** [Codeception/Codeception#4795]
#### What are you trying to achieve?
When I run tests with `shuffle: true` set for my various test suites, the tests run shuffled as desired (thanks very much!). However, the tests shuffle every time. If my test suite has implicit dependencies between various tests and fails in one configuration, it would be nice to be able to run the test suite in the same order again to track down my issue. Sometimes with flakey tests, it's only in a certain configuration that I can see the problem.

In Rails, their test runner incorporates a `--seed` option to allow re-running a test suite in the same order (see below). This seed is also printed to the console on each test run which makes it easy to replicate bugs when tests are shuffled.

```
$ bin/rails test -h
minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
```

Any chance we'd be able to add that type of setup here?  Thanks!

**Comment by Naktibalda** [comment]
Seed functionality was implemented by https://github.com/Codeception/Codeception/pull/5192
It is documented at https://codeception.com/docs/07-AdvancedUsage#Shuffle
