### ISSUE TITLE
Empty array is removed in body parameters for sendPUT request.

### ISSUE THREAD

**Issue by vitalyspirin** [Codeception/Codeception#4800]
#### What are you trying to achieve?
 I am trying to pass to Yii2 parameters (in JSON format as body of PUT request) including empty array:

$I->sendPUT($this->url,  ['name' => 'jason', 'categories' => []]);

#### What do you get instead?

'Categories' parameter is completely removed. On the Yii2 side I see only:

array(1) {
  ["name"]=>
  string(5) "jason"
}

As I see the problem is in Codeception function PhpSuperGlobalsConverter::replaceSpaces() which uses function http_build_query() to filter out spaces and dots to work around some PHP bug related to $_GET.

Is it possible to add a check, for example, inside Codeception\Lib\Connector\Yii2::doRequest() not to transform parameters if method is not GET/POST or if request content type is 'json'?

### Details

* Codeception version: 2.3.8

* PHP Version: PHP 7.1.12-3+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Dec 14 2017 15:58:40) ( NTS )

* Operating System:  Ubuntu 14.04.5 LTS

* Installation type: Phar || Composer

* List of installed packages (`composer show`)
aws/aws-sdk-php                      3.52.2             AWS SDK for PHP - Use Amazon Web Services in your PHP project
behat/gherkin                        v4.4.5             Gherkin DSL parser for PHP 5.3
bower-asset/bootstrap                v3.3.7            
bower-asset/inputmask                3.3.11            
bower-asset/jquery                   3.2.1             
bower-asset/punycode                 v1.3.2            
bower-asset/swagger-ui               v3.9.3            
bower-asset/typeahead.js             v0.11.1           
bower-asset/yii2-pjax                2.0.7.1           
cebe/markdown                        1.1.2              A super fast, highly extensible markdown parser for PHP
codeception/base                     2.3.8              BDD-style testing framework
codeception/specify                  0.4.6              BDD code blocks for PHPUnit and Codeception
codeception/stub                     1.0.1              Flexible Stub wrapper for PHPUnit's Mock Builder
codeception/verify                   0.3.3              BDD assertion library for PHPUnit
composer/semver                      1.4.2              Semver library that offers utilities, version constraint parsing and val...
doctrine/annotations                 v1.6.0             Docblock Annotations Parser
doctrine/instantiator                1.1.0              A small, lightweight utility to instantiate objects in PHP without invok...
doctrine/lexer                       v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent...
ezyang/htmlpurifier                  v4.9.3             Standards compliant HTML filter written in PHP
flow/jsonpath                        0.3.4              JSONPath implementation for parsing, searching and flattening arrays
friendsofphp/php-cs-fixer            v2.10.0            A tool to automatically fix PHP code style
fzaninotto/faker                     v1.7.1             Faker is a PHP library that generates fake data for you.
gecko-packages/gecko-php-unit        v3.1               Additional PHPUnit asserts and constraints.
guzzlehttp/guzzle                    6.3.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                  v1.3.1             Guzzle promises library
guzzlehttp/psr7                      1.4.2              PSR-7 message implementation that also provides common utility methods
mtdowling/jmespath.php               2.4.0              Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                    1.7.0              Create deep copies (clones) of your objects
paragonie/random_compat              v2.0.11            PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                     1.0.1              Component for reading phar.io manifest information from a PHP Archive (P...
phar-io/version                      1.0.1              Library for handling version information and constraints
php-cs-fixer/diff                    v1.2.1             sebastian/diff v2 backport support for PHP5.6
phpdocumentor/reflection-common      1.0.1              Common reflection classes used by phpdocumentor to reflect the code stru...
phpdocumentor/reflection-docblock    4.3.0              With this component, a library can provide support for annotations via D...
phpdocumentor/type-resolver          0.4.0             
phpspec/php-diff                     v1.1.0             A comprehensive library for generating differences between two hashable ...
phpspec/prophecy                     1.7.3              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage            5.3.0              Library that provides collection, processing, and rendering functionalit...
phpunit/php-file-iterator            1.4.5              FilterIterator implementation that filters files based on a list of suff...
phpunit/php-text-template            1.2.1              Simple template engine.
phpunit/php-timer                    1.0.9              Utility class for timing
phpunit/php-token-stream             2.0.2              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      6.5.6              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects         5.0.6              Mock Object library for PHPUnit
psr/http-message                     1.0.1              Common interface for HTTP messages
sebastian/code-unit-reverse-lookup   1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                 2.1.3              Provides the functionality to compare PHP values for equality
sebastian/diff                       2.0.1              Diff implementation
sebastian/environment                3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state               2.0.0              Snapshotting of global state
sebastian/object-enumerator          3.0.3              Traverses array structures and object graphs to enumerate all referenced...
sebastian/object-reflector           1.1.1              Allows reflection of object attributes, including inherited and non-publ...
sebastian/recursion-context          3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations        1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                    2.0.1              Library that helps with managing the version number of Git-hosted PHP pr...
swiftmailer/swiftmailer              v5.4.9             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                  v4.0.4             Symfony BrowserKit Component
symfony/console                      v4.0.4             Symfony Console Component
symfony/css-selector                 v4.0.4             Symfony CssSelector Component
symfony/dom-crawler                  v4.0.4             Symfony DomCrawler Component
symfony/event-dispatcher             v4.0.4             Symfony EventDispatcher Component
symfony/filesystem                   v4.0.4             Symfony Filesystem Component
symfony/finder                       v4.0.4             Symfony Finder Component
symfony/options-resolver             v4.0.4             Symfony OptionsResolver Component
symfony/polyfill-mbstring            v1.7.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php70               v1.7.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72               v1.7.0             Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                      v4.0.4             Symfony Process Component
symfony/stopwatch                    v4.0.4             Symfony Stopwatch Component
symfony/yaml                         v4.0.4             Symfony Yaml Component
theseer/tokenizer                    1.1.0              A small library for converting tokenized PHP source code into XML and po...
vitalyspirin/yii2-simpleactiverecord 1.0.3              Extension of Yii2 ActiveRecord with added automatically generaged valida...
webmozart/assert                     1.3.0              Assertions to validate method input/output with nice error messages.
yii2mod/yii2-swagger                 1.1.1              Swagger Documentation Generator for Yii2 Framework
yiisoft/yii2                         dev-master ada9022 Yii PHP Framework Version 2
yiisoft/yii2-bootstrap               2.0.7              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer                2.0.5              The composer plugin for Yii extension installer
yiisoft/yii2-debug                   2.0.13             The debugger extension for the Yii framework
yiisoft/yii2-faker                   2.0.3              Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                     2.0.6              The Gii extension for the Yii framework
yiisoft/yii2-swiftmailer             2.0.7              The SwiftMailer integration for the Yii framework
zircote/swagger-php                  2.0.13             Swagger-PHP - Generate interactive documentation for your RESTful API us...

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    memory_limit: 1024M
    colors: true
modules:
    config:
        Yii2:
            configFile: 'config/test.php'
            cleanup: false


actor: ApiTester
modules:
    enabled:
        - Asserts
        - Yii2:
            part: orm
        - REST:
            depends: Yii2
    config:
        - Yii2

```

**Comment by Naktibalda** [comment]
You can json_encode your request body to prevent any modifications:
```php
$I->sendPUT($this->url, json_encode(['name' => 'jason', 'categories' => []]));
```

**Comment by Mo7amed3la2** [comment]
### You should set  $I->haveHttpHeader('Content-Type', 'application/json');   before send any request else git
because the request execute throw execute method in  Codeception\Module\REST
it  call $parameters = $this->encodeApplicationJson($method, $parameters);
and in encodeApplicationJson check if http method != GET and have haveHttpHeader('Content-Type', 'application/json') he well convert parameters to json
