### ISSUE TITLE
PHPUnit 7 support

### ISSUE THREAD

**Issue by chris1312** [Codeception/Codeception#4805]
#### What are you trying to achieve?

Utilize latest PHPUnit version in my project together with Codeception.

#### What do you get instead?

I cannot install latest PHPUnit version because it requires phpunit/phpunit-mock-objects: ^6.0 when Codeception supports only <6.0.

### Details

* Codeception version: v2.3.8
* PHP Version: 7.1
* Operating System: Ubuntu 16.0.4
* Installation type: Composer
* Suite configuration: (not relevant for this case)

**Comment by Naktibalda** [comment]
It is work in progress - #4799
You are welcome to contribute.
