### ISSUE TITLE
In AngularJS module working only selector Model

### ISSUE THREAD

**Issue by rebas82** [Codeception/Codeception#4808]
I know, in CodeceptJS is posibble use model, repeater, binding.

Is there a plan to extend these options (repeater, binding) even in codeception?

(I dont like protractor)

**Comment by DavertMik** [comment]
No, there are no real plans for improving AngularJS module. 
But you can do it by yourself. Add `repeater` or `binding` the way the model was added:

See this line https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Module/AngularJS.php#L139

And send a Pull Request!
