### ISSUE TITLE
No tests executed!  - Unit Testing

### ISSUE THREAD

**Issue by Roobix13** [Codeception/Codeception#4826]
I wanted to start with starting unit tests.

When i run 

`php ./vendor/bin/codecept run acceptance `- everthing works fine, but when i try to run
`php ./vendor/bin/codecept run suit with` this test case: 

```
<?php

use login\LoginFormCest;

abstract class LoginFormTest extends PHPUnit\Framework\TestCase

{
    /**
     * @var \UnitTester
     */
    protected $tester;
    
    protected function _before()
    {
    }

    protected function _after()
    {
    }

    // tests
    public function testSomeFeature()
    {
       $foo = true;
       $this->assertTrue($foo);
    }
}

```
i get as an output

`No tests executed!`

EDIT:

`$this->assertTrue($foo);` **It says**  

> Method 'assertTrue' not found in LoginFormTest

EDIT2:

Invalidating Cache and Restart, solved the first EDIT problem.

**Comment by Naktibalda** [comment]
Why is your class `abstract`?
Try extending `\Codeception\Test\Unit` instead of `PHPUnit\Framework\TestCase`

**Comment by Roobix13** [comment]
@Naktibalda 
When removing `abstract ` i get the following error message in IDE

> Class must be declared abstract or implement methods 'count', 'run'

Switching to `\Codeception\Test\Unit` did not work.

**Comment by Naktibalda** [comment]
ignore IDE error.

**Comment by Roobix13** [comment]
@Naktibalda  
When switching to `class Test extends \Codeception\Test\Unit` the assertions are not found.
Same Terminal output. Showing 2 Unit Tests

**Comment by Naktibalda** [comment]
What can't find assertions? PHP or IDE? Ignore IDE #4801

**Comment by Roobix13** [comment]
PHP can't find the assertion. @Naktibalda 
I am ignoring the IDE message.

**Comment by Naktibalda** [comment]
Generate a new test file using this command `./vendor/bin/codecept generate:test unit Login`
Does it have the same issue?

**Comment by Roobix13** [comment]
Yes @Naktibalda 
![bildschirmfoto 2018-02-21 um 15 18 48](https://user-images.githubusercontent.com/27815032/36484767-9bb7c288-171a-11e8-802b-0a5d03704259.png)

**Comment by Naktibalda** [comment]
What was the cause?

**Comment by Roobix13** [comment]
@Naktibalda  I don't know, I gave up.

**Comment by olegpro** [comment]
I have the same problem:
![2018-03-07_11-17-29](https://user-images.githubusercontent.com/1092443/37083769-3e38fcc8-21f9-11e8-9030-55159db38d97.png)

In this case, if you repeat the hierarchy of classes used in codeception, then everything works fine:
![2018-03-07_11-19-06](https://user-images.githubusercontent.com/1092443/37083902-a2bec61e-21f9-11e8-8ec4-f382853e9207.png)
