### ISSUE TITLE
Codeception 2.4 will be installed to PHP 5.4

### ISSUE THREAD

**Issue by nojimage** [Codeception/Codeception#4837]
#### What are you trying to achieve?

I try codeception install on PHP 5.4

```bash
composer require --dev codeception/codeception
```

#### What do you get instead?

In PHP 5.4 it will be installed despite being unable to use Codeception 2.4.

I thinks should be change php version in composer.json, like `"php": ">=5.6.0 <8.0",`

**Comment by DavertMik** [comment]
Yes. Thanks looks like I forgot to update composer.json
