### ISSUE TITLE
Drag and drop on a field that changes when hovered over.

### ISSUE THREAD

**Issue by Jacek-fstack** [Codeception/Codeception#4840]
#### What are you trying to achieve?
Drag and drop on a field that changes when hovered over.
I'm using a locator that's 'before' -> test passes, but I can see in the screenshot I made after, that it was not dropped, and it's still in a 'drag' mode (everything is a bit greyed out)
When I'm using the locator that shows after I hover over the field, it cannot find the field in the first place.
When I'm using a locator that's common to both states (other attributes), same case as in the first one.

Chrome driver 2.33.506092
codeception 2.3.7

Any ideas how to handle such a field?

Thank you

**Comment by Naktibalda** [comment]
No, I have no ideas.
