### ISSUE TITLE
running single scenario off a feature file with group parameters is not working

### ISSUE THREAD

**Issue by abdullah-jubayer** [Codeception/Codeception#4867]
#### What are you trying to achieve?
Lets say I have a feature file (automated_tests/bdd/MYBDD/Test.feature) containing the following lines: 
`
Feature: MYBDD

    @test
    Scenario Outline: Test One
        Given I open my browser
        And I type the url <url>
        Then I see the title <title>

        Examples:
            | url                    | title             |
            | "sample_site_one.com"  | "sample_site_one" |
            | "sample_site_two.com"  | "sample_site_two" |
`
Now I run this feature file "codecept run bdd automated_tests/bdd/MYBDD/Test.feature"
and it failed in one of the examples: 
And the failed file generated is the following: 

automated_tests/bdd/MYBDD/Test.feature:Test One | "sample_site_one.com", "sample_site_one"

Now I want to run this failed test case with a group parameter

codecept run bdd --group bdd_automation --override "groups: bdd_automation: automated_tests/_output/failed"

#### What do you get instead?

It does not run any test with the group param however when I update the failed file to the following: 

automated_tests/bdd/MYBDD/Test.feature

then it runs the entire feature with however many scenarios there. 

I tested with Cest tests and it works with the group param and running one specific failed test. 

Anyone has a clue on whats going on?  I know cucumber has a feature where you can run test by line number but I guess codeception doesnot support that yet

* Codeception version: 2.3.5
* PHP Version: 5.6.28
* Operating System: Centos
* Installation type: Composer

**Comment by Naktibalda** [comment]
Fixed by  #5524
