### ISSUE TITLE
phpunit-wrapper error in 2.4.0

### ISSUE THREAD

**Issue by matjanis** [Codeception/Codeception#4873]
I get errors after update to Codeception 2.4.0. They appear randomly - test can finish with success and fail in the second try. Downgrading to 2.3.9 fixed issue.
### Details

* Codeception version: 2.4.0
* PHP Version: 7.0
* Operating System: Ubuntu 16.04.3
* Installation type: Composer

Error: https://screencast.com/t/BLOss7jAk

**Comment by matjanis** [comment]
'PHP Fatal error: Uncaught Error: Class 'PHPUnit\Util\Log\Symfony\Component\Yaml\Dumper' not found in /var/www/html/app-ats/vendor/codeception/phpunit-wrapper/src/phpunit5-loggers.php:431 Stack trace: #0 /var/www/html/app-ats/vendor/phpunit/phpunit/src/Framework/TestResult.php(349): PHPUnit\Util\Log\TAP->addFailure(Object(Codeception\Test\Cest), Object(PHPUnit\Framework\ExpectationFailedException), 0.0034241676330566) #1 /var/www/html/app-ats/vendor/codeception/codeception/src/Codeception/Test/Feature/ErrorLogger.php(23): PHPUnit\Framework\TestResult->addFailure(Object(Codeception\Test\Cest), Object(PHPUnit\Framework\ExpectationFailedException), 0.0034241676330566) #2 /var/www/html/app-ats/vendor/codeception/codeception/src/Codeception/Test/Test.php(107): Codeception\Test\Test->errorLoggerEnd('fail', 0.0034241676330566, Object(PHPUnit\Framework\ExpectationFailedException)) #3 /var/www/html/app-ats/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult)) #4 /var/w in /var/www/html/app-ats/vendor/codeception/phpunit-wrapper/src/phpunit5-loggers.php on line 431'

**Comment by Naktibalda** [comment]
It is a failure in addFailure :)

**Comment by DavertMik** [comment]
Thanks, patches merged and new versions are released
