### ISSUE TITLE
does not support Zend Expressive v3

### ISSUE THREAD

**Issue by svycka** [Codeception/Codeception#4877]
Zend Expressive v3 was released and would be nice to have support for latest version :)

**Comment by Naktibalda** [comment]
Sorry, it is on you to make it work.

We haven't managed to get testsuite working with zend-expressive 2.2 by making semi-random changes at https://github.com/Naktibalda/codeception-zend-expressive-tests/issues/7

**Comment by svycka** [comment]
@Naktibalda take a look at https://github.com/Naktibalda/codeception-zend-expressive-tests/pull/9 should fix https://github.com/Naktibalda/codeception-zend-expressive-tests/issues/7 at least locally fixed

**Comment by svycka** [comment]
for now, I have created a module for Zend Expressive 3 https://github.com/svycka/codeception-zend-expressive-module
@Naktibalda any plans to support it directly in `Codeception`?

**Comment by Naktibalda** [comment]
Is Zend Expressive 3 so different that it requires a different module?
If you can make necessary modifications while keeping backwards compatibility with Zend Expressive 2, please make a pull request.
If not, please explain what has changed so much.

**Comment by svycka** [comment]
With some work, it should be possible to make it work not much changed.

Most relevant changes are that `pipeline.php` and `routes.php` now return callable see https://github.com/zendframework/zend-expressive-skeleton/blob/3.0.0/public/index.php#L26-L27 but I guess this can be solved with simple if statement also emitters have been moved to separate package `zendframework/zend-httphandlerrunner` may be a problem but I guess also can be done and that's it. Unless I missed something.

But I needed it now so I can't wait for new releases I have a bad experience with Codeception PR being merged https://github.com/Codeception/Codeception/pull/4798 :D this would be bigger PR so I expect even more time required to merge :D

If I find the time I will create PR if someone won't do it before me, just don't know when since this module works for me now

**Comment by DavertMik** [comment]
@svycka sorry, we are really busy right now and we just can't get into ZE things really fast. If you'd like I can make you a maintainer of Zend Expressive module and grand you some privileges so you can make your PRs pass faster. So you could do whatever it takes )

If you are interested we can discuss the details in Slack https://join.slack.com/t/codeception/shared_invite/enQtMzE2MzgxNzM1OTUzLTcwMmMxZjMxYTdkMzljMzNjNmNiNWQ0NGNjNTY0MjJlNWNjOTI0ZWU0Mjg4YmE5NTI0MmMwNDZmNzRhOTZmNWE

**Comment by svycka** [comment]
@DavertMik joined, ping me when you can

**Comment by sleitz** [comment]
Did something arise from your Slack meeting?
