### ISSUE TITLE
How to save the debug information to a file in API test

### ISSUE THREAD

**Issue by zeeshanyshaikh** [Codeception/Codeception#4879]
I want all the additional information of REST which is shown in the console using debug option to save in a file

As shown in below screenshot (found at https://codeception.com/08-09-2013/codeception-1-6-5-minor.html)
![image](https://user-images.githubusercontent.com/6223015/37527781-d9c3284c-2958-11e8-90b8-ab289815b9bc.png)

I want GET, COOKIES, STATUS, HEADERS, and RESPONSE. I can get Headers and Response by *grabHttpHeader* and *grabResponse* methods respectively. How to achieve other pieces of stuff?

**Comment by Naktibalda** [comment]
How about redirecting output to file?

`codecep run >file`
