### ISSUE TITLE
Array to string conversion in ErrorHandler

### ISSUE THREAD

**Issue by schmunk42** [Codeception/Codeception#4885]
#### What are you trying to achieve?

Running tests and looking at reports.

#### What do you get instead?

```bash
FAIL 

In ErrorHandler.php line 83:
                              
  Array to string conversion  
```

This happens occasionally in our CI and the underlying cause might be a timeout.
Nonetheless the testing framework should not exit with an error.

After digging around this might coming from PHPunit 7, which introduced type declarations.

Related:
- https://github.com/sebastianbergmann/phpunit/commit/600613d1bf2143c4a00f3c35dee36cb76959e3a4#diff-5bccad7b01ef6ba170aed6efecb57e9e
- https://github.com/Codeception/Codeception/pull/4817
- https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Subscriber/ErrorHandler.php#L83

### Details

* Codeception version: 2.4.0 (phunit 7.0.2)
* PHP Version: 7.2
* Operating System: Arch Linux
* Installation type: Composer

**Comment by Naktibalda** [comment]
Array to string conversion happened somewhere else, ErrorHandler only intercepted this error.
