### ISSUE TITLE
Typo in yii2 module docs

### ISSUE THREAD

**Issue by nick-denry** [Codeception/Codeception#4886]
Hi!

A little typo in yii2 docs. 

Fix typo at line 104, missing close square bracket.

PR https://github.com/Codeception/Codeception/pull/4882

**Comment by nick-denry** [comment]
Will it also be fixed at https://codeception.com/docs/modules/Yii2#URL ?

**Comment by samdark** [comment]
Eventually yes.

**Comment by nick-denry** [comment]
Thanks.
