### ISSUE TITLE
The data provider specified for ... is invalid

### ISSUE THREAD

**Issue by okneloper** [Codeception/Codeception#4887]
Trying to set up a dataProvider as per the documentation, but getting this error: 
`The data provider specified for ExampleTest::testEmail is invalid.`

[Documentation](https://codeception.com/docs/07-AdvancedUsage) says the dataProvider method should be `protected`, but having it `protected` cause the above error. Making it public, however, works.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
$ codecept run unit ExampleTest

==== Redirecting to Composer-installed version in vendor/codeception ====
Codeception PHP Testing Framework v2.4.1
Powered by PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Unit Tests (2) ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ ExampleTest: Phone (0.02s)
✖ PHPUnit_Framework_Warning: Warning (0.00s)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 5.38 seconds, Memory: 14.00MB

There was 1 failure:

---------
1) PHPUnit_Framework_Warning: Warning
 Test  vendor/phpunit/phpunit/src/Framework/Warning.php:Warning
The data provider specified for ExampleTest::testEmail is invalid.
Trying to invoke protected method ExampleTest::emailsProvider() from scope ReflectionMethod

FAILURES!
Tests: 2, Assertions: 1, Failures: 1.

```
> Provide test source code if related

```php
class ExampleTest extends \Codeception\Test\Unit
{
    public function testPhone()
    {
        $this->assertTrue(true);
    }

    /**
     * @dataProvider emailsProvider
     */
    public function testEmail($example)
    {
        $this->assertTrue(false);
    }

    protected function emailsProvider()
    {
        return [
            [
                'email' => 'email1',
                'validates' => false,
            ]
        ];
    }
}

```
### Details

* Codeception version: 2.4.x-dev (2.4.0 doesn't work (#4864))
* PHP Version: 5.6.24
* Operating System: Linux/Debian 8
* Installation type: Composer

```yml
settings:
    bootstrap: _bootstrap.php
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```

**Comment by edno** [comment]
@okneloper - You're using Unit tests, and if I am not wrong, their behaviour is based on PHPUnit.
The annotations *example* and *dataprovider* documented in https://codeception.com/docs/07-AdvancedUsage#Examples refer to function test (Cest).
In the case of unit tests, the dataprovider must be public. You can refer to PHPUnit documentation: https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers

**Comment by okneloper** [comment]
Yeah, that makes sense, must be the reason (neither of `dataProvider` and `dataprovider` worked for me though).

Can this be flagged in the documentation explicitly in the dataproviders section, as I was just googling `codeception dataprovider` and got to this page:
https://codeception.com/docs/07-AdvancedUsage

Took a while to figure this out, so having it in the docs could save someone some time.

**Comment by edno** [comment]
@DavertMik - If okay with you I suggest to modify the documentation for **Advanced Usage**.
The current structure is the following:
- Cest Classes
- Dependency Injection
 -- Examples _(for unkown reason it is a 2nd level)_
 -- Before/After Annotations _(for unkown reason it is a 2nd level)_

New proposal:
- Cest Classes
- Dependency Injection
- Example Annotation
- Dataprovider Annotations
  _This section will cover both Unit and Cest_
- Before/After Annotations

**Comment by okneloper** [comment]
Thanks a bunch! It makes much more sense now!
