### ISSUE TITLE
Detect usage of codecpt_debug option

### ISSUE THREAD

**Issue by Sarke** [Codeception/Codeception#4892]
Sometimes I will use `codecpt_debug` when troubleshooting why a test fails.  However, if I leave the codecpt_debug function in the code, it will still pass the tests, but then on the deployment it will error because of "function not found".

This happened today.

I was thinking some sort of flag we can enable when running CI/CD so that it will fail if that function is used in the code.

Because having the tests pass and deploy a code that won't run is a big issue IMO, although a bonehead and uncommon one.

**Comment by DavertMik** [comment]
I agree. I think this can be done by static analysis tools.

**Comment by DavertMik** [comment]
But can't be done inside the framework... Sorry.

**Comment by Sarke** [comment]
@DavertMik What do you mean it can't be done inside the framework?

Just set some static property when Codeception is run, then check for said variable inside `codecpt_debug`.

**Comment by Naktibalda** [comment]
@Sarke it won't help with the case when Codeception is not installed.

**Comment by Sarke** [comment]
@Naktibalda that's exactly the situation I want to prevent.

Pass a flag to Codeception during CI testing that basically just causes `codecpt_debug` to throw an exception every time, making sure the build doesn't pass.

**Comment by Naktibalda** [comment]
You are welcome to make a pull request.

In functional tests you would have to set that flag in all connectors: https://github.com/Codeception/Codeception/tree/2.4/src/Codeception/Lib/Connector
just before application code is invoked and unset the flag right after.
Example of such place in code: https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Lib/Connector/Laravel5.php#L111

I doubt that it is possible to do the same thing for unit tests.
