### ISSUE TITLE
Cannot 'see' text in js of a html

### ISSUE THREAD

**Issue by JunelanMe** [Codeception/Codeception#4914]
#### What are you trying to achieve?
see something( js content) in html
#### What do you get instead?
I can not see that text 
  

> Provide console output if related. Use `-vvv` mode for more details.
The part of the html like below . I want to assert someting of the js.

![pic](https://user-images.githubusercontent.com/11918045/38286211-a8c1e45c-37f6-11e8-83ea-86fd86446437.png)

I view the code that script replace as '' in this issue https://github.com/Codeception/Codeception/pull/4510 
 But if I want to assert the text of js . How can I do it  ? 
```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.4.0
* PHP Version: 7.0
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
Use seeInSource method instead.
