### ISSUE TITLE
Add a function on the REST module which validates if a returned status code is a 200 level code.

### ISSUE THREAD

**Issue by dotsonjb14** [Codeception/Codeception#4932]
The idea of limiting a response check to one status code is very limiting when dealing with restful APIs that can have multiple successful status codes. Even exposing the status code to let us make these checks ourselves would help out a lot.

I would be cool with making this change, but want to make sure it fits with what codeception is trying to accomplish.

**Comment by Naktibalda** [comment]
seeResponseCodeIsSuccessful was implemented by #5030 in June 2018
