### ISSUE TITLE
Response is null for json format

### ISSUE THREAD

**Issue by amarox** [Codeception/Codeception#4942]
#### What are you trying to achieve?
testing rest action for Yii2

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
run functional BasketCest -c frontend --debug
Cannot load Xdebug - it was already loaded
Codeception PHP Testing Framework v2.4.1
Powered by PHPUnit 7.1.2 by Sebastian Bergmann and contributors.

Frontend\tests.functional Tests (1) --------------------------------------------
Modules: \frontend\tests\Helper\Functional, Filesystem, Yii2, REST
--------------------------------------------------------------------------------
BasketCest: Try add to basket
Signature: frontend\tests\functional\BasketCest:tryAddToBasket
Test: tests/functional/BasketCest.php:tryAddToBasket
Scenario --
  Destroying application
  Starting application
  [Fixtures] Loading fixtures
  [Fixtures] Done
 I grab record "modules\catalog\models\Product",{"id":1}
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=mariadb;dbname=test'
  [Database] Transaction started for: mysql:host=mariadb;dbname=test
 I am on route "online-shop/product",{"slug":"mokasiny-zenskie-respect","id":1}
  [Request Headers] []
  [yii\web\Session::open] 'Session started'
  
  [Page] /detail/mokasiny-zenskie-respect-1/
  [Response] 200
  [Request Cookies] []
  [Response Headers] []
 I see response code is 200
 I send get "shop/basket/add/",{"product_id":1,"offer_id":15,"link":"/link-u...}
  [Request] GET /shop/basket/add/?product_id=1&offer_id=15&link=%2Flink-url
  [Request Headers] []
  
  [Page] /shop/basket/add/?product_id=1&offer_id=15&link=%2Flink-url
  [Response] 200
  [Request Cookies] {"_csrf":"8e1e478c17d49a52accfa311f1939fe203570ea63bbeb6b498264a84e0a03f98a:2:{i:0;s:5:"_csrf";i:1;s:32:"p3pAG55sLq2g060WgBqedyzFj-qT_lc4";}"}
  [Response Headers] []
  [Response] 
 I see response code is 200
 I see response is json 
 FAIL 

  [Database] Transaction cancelled; all changes reverted.
  Suite done, restoring $_SERVER to original
--------------------------------------------------------------------------------


Time: 1.94 seconds, Memory: 20.00MB

There was 1 failure:

---------
1) BasketCest: Try add to basket
 Test  tests/functional/BasketCest.php:tryAddToBasket
 Step  See response is json 
 Fail  response is empty
Failed asserting that '' is not equal to "".

Scenario Steps:

 6. $I->seeResponseIsJson() at tests/functional/BasketCest.php:34
 5. $I->seeResponseCodeIs(200) at tests/functional/BasketCest.php:33
 4. $I->sendGET("shop/basket/add/",{"product_id":1,"offer_id":15,"link":"/l...}) at tests/functional/BasketCest.php:31
 3. $I->seeResponseCodeIs(200) at tests/functional/BasketCest.php:27
 2. $I->amOnRoute("online-shop/product",{"slug":"mokasiny-zenskie-respect",...}) at tests/functional/BasketCest.php:25
 1. $I->grabRecord("modules\catalog\models\Product",{"id":1}) at tests/functional/BasketCest.php:22


FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
  Destroying application

```
> Provide test source code if related

```php
$product = $I->grabRecord(Product::class, ['id' => 1]);
        $I->amOnRoute('online-shop/product', [
            'slug' => $product->slug,
            'id' => $product->id
        ]);
        $I->seeResponseCodeIs(200);
        $I->sendGET("shop/basket/add/", [
            'product_id' => $product->id,
            'offer_id' => 15,
            'link' => "/link-url/fuck",
        ]);
        $I->seeResponseCodeIs(200);
        $I->seeResponseIsJson();
```
### Details

* Codeception version: 2.4.1
* PHP Version: 7.2.1
* Operating System: Debian
* Installation type: Composer
* List of installed packages (`composer show`)
amarox/assets-builder                 0.5.2              Php assets build system
behat/gherkin                         v4.5.1             Gherkin DSL parser for PHP 5.3
bower-asset/admin-lte                 v2.3.11           
bower-asset/autonumeric               1.9.46            
bower-asset/backbone                  1.3.3             
bower-asset/backbone.localstorage     2.0.0             
bower-asset/bootstrap                 v3.3.7            
bower-asset/bootstrap-daterangepicker v2.1.27           
bower-asset/bootstrap-less            3.3.4             
bower-asset/bootstrap-select          v1.11.2           
bower-asset/bootstrap3-dialog         v1.35.4           
bower-asset/font-awesome              5.0.8             
bower-asset/fontawesome               v4.7.0            
bower-asset/inputmask                 3.3.11            
bower-asset/jquery                    2.2.4             
bower-asset/jquery-pjax               v2.0.1            
bower-asset/jquery-treegrid           0.3.0             
bower-asset/jquery-ui                 1.12.1            
bower-asset/jquery.cookie             v1.4.1            
bower-asset/jquery.scrollto           2.1.2             
bower-asset/moment                    2.21.0            
bower-asset/normalize-less            dev-master cf34639
bower-asset/owl.carousel              2.3.2             
bower-asset/punycode                  v1.3.2            
bower-asset/typeahead.js              v0.11.1           
bower-asset/underscore                1.8.3             
bower-asset/x-editable                1.5.1             
bower-asset/yii2-pjax                 2.0.7.1           
cebe/markdown                         1.1.2              A super fast, highly extensible markdown parser for PHP
codeception/base                      2.4.1              BDD-style testing framework
codeception/phpunit-wrapper           7.1.0              PHPUnit classes used by Codeception
codeception/specify                   1.1                BDD code blocks for PHPUnit and Codeception
codeception/stub                      1.0.2              Flexible Stub wrapper for PHPUnit's Mock Builder
codeception/verify                    1.0.0              BDD assertion library for PHPUnit
components/backbone                   1.2.0              Give your JS App some Backbone with Models, Views, Collections, and Events.
components/underscore                 1.8.3              JavaScript's functional programming helper library.
deployer/recipes                      6.0.2              3rd party deployer recipes
doctrine/instantiator                 1.1.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
egulias/email-validator               2.1.3              A library for validating emails against several RFCs
extead/yii2-autonumeric               dev-master 9f28033 Input format extension for Yii 2.0 based on autoNumerical plugin
ezyang/htmlpurifier                   v4.10.0            Standards compliant HTML filter written in PHP
guzzlehttp/guzzle                     6.3.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1             Guzzle promises library
guzzlehttp/psr7                       1.4.2              PSR-7 message implementation that also provides common utility methods
intervention/image                    2.4.1              Image handling and manipulation library with support for Laravel integration
kartik-v/bootstrap-fileinput          v4.4.7             An enhanced HTML 5 file input for Bootstrap 3.x with features for file preview for many file types, multiple selection, ajax uploads, ...
kartik-v/yii2-date-range              v1.6.9             An advanced Yii 2 date range picker input for based on bootstrap-daterangepicker plugin.
kartik-v/yii2-dialog                  v1.0.3             An asset bundle for bootstrap3-dialog for Yii 2.0 framework.
kartik-v/yii2-dynagrid                v1.4.8             Turbo charge the Yii 2 GridView with personalized columns, page size, and themes.
kartik-v/yii2-field-range             v1.3.2             Easily manage Yii 2 ActiveField ranges (from/to) with Bootstrap 3 addons markup and more
kartik-v/yii2-grid                    v3.1.7             Yii 2 GridView on steroids. Various enhancements and utilities for the Yii 2.0 GridView widget.
kartik-v/yii2-helpers                 v1.3.6             A collection of useful helper functions for Yii Framework 2.0
kartik-v/yii2-krajee-base             v1.8.9             Base library and foundation components for all Yii2 Krajee extensions.
kartik-v/yii2-sortable                v1.2.0             Create sortable lists and grids using HTML5 drag and drop API for Yii 2.0.
kartik-v/yii2-widget-activeform       v1.4.9             Enhanced Yii2 active-form and active-field with full bootstrap styling support (sub repo split from yii2-widgets).
kartik-v/yii2-widget-colorinput       v1.0.3             An enhanced Yii 2 widget encapsulating the HTML 5 color input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-datetimepicker   v1.4.4             Enhanced Yii2 wrapper for the bootstrap datetimepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-fileinput        v1.0.6             An enhanced FileInput widget for Bootstrap 3.x with file preview, multiple selection, and more features (sub repo split from yii2-widg...
kartik-v/yii2-widget-select2          v2.1.1             Enhanced Yii2 wrapper for the Select2 jQuery plugin (sub repo split from yii2-widgets).
kriswallsmith/assetic                 v1.4.0             Asset Management for PHP
leandrogehlen/yii2-treegrid           dev-master a98305d Extension for Yii2 Framework to work with jQuery TreeGrid
matthiasmullie/minify                 1.3.59             CSS & JavaScript minifier, in PHP. Removes whitespace, strips comments, combines files (incl. @import statements and small assets in C...
matthiasmullie/path-converter         1.1.1              Relative path converter
myclabs/deep-copy                     1.7.0              Create deep copies (clones) of your objects
nesbot/carbon                         1.25.0             A simple API extension for DateTime.
oyejorge/less.php                     v1.7.0.14          PHP port of the Javascript version of LESS http://lesscss.org (Originally maintained by Josh Schmidt)
phar-io/manifest                      1.0.1              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       1.0.1              Library for handling version information and constraints
phpcollection/phpcollection           0.5.0              General-Purpose Collection Library for PHP
phpdocumentor/reflection-common       1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in...
phpdocumentor/type-resolver           0.4.0             
phpoption/phpoption                   1.5.0              Option Type for PHP
phpspec/php-diff                      v1.1.0             A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/prophecy                      1.7.5              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             6.0.3              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     2.0.0              Utility class for timing
phpunit/php-token-stream              3.0.0              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       7.1.2              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          6.1.1              Mock Object library for PHPUnit
psr/http-message                      1.0.1              Common interface for HTTP messages
sebastian/code-unit-reverse-lookup    1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                  2.1.3              Provides the functionality to compare PHP values for equality
sebastian/diff                        3.0.0              Diff implementation
sebastian/environment                 3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state                2.0.0              Snapshotting of global state
sebastian/object-enumerator           3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector            1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context           3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
sentry/sentry                         1.8.4              A PHP client for Sentry (http://getsentry.com)
swiftmailer/swiftmailer               v6.0.2             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                   v4.0.8             Symfony BrowserKit Component
symfony/console                       v4.0.8             Symfony Console Component
symfony/css-selector                  v4.0.8             Symfony CssSelector Component
symfony/dom-crawler                   v4.0.8             Symfony DomCrawler Component
symfony/event-dispatcher              v4.0.8             Symfony EventDispatcher Component
symfony/finder                        v4.0.8             Symfony Finder Component
symfony/polyfill-mbstring             v1.7.0             Symfony polyfill for the Mbstring extension
symfony/process                       v3.4.8             Symfony Process Component
symfony/translation                   v4.0.6             Symfony Translation Component
symfony/yaml                          v4.0.8             Symfony Yaml Component
theseer/tokenizer                     1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
unclead/yii2-multiple-input           2.14.0             Widget for handle multiple inputs for an attribute of Yii2 framework model
vlucas/phpdotenv                      v2.4.0             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.3.0              Assertions to validate method input/output with nice error messages.
yiisoft/jquery                        2.1.1              jQuery JavaScript Library
yiisoft/jquery-pjax                   v2.0.5             pushState + ajax = pjax, a forked maintainted by the Yii Framework core developers
yiisoft/yii2                          2.0.15.1           Yii PHP Framework Version 2
yiisoft/yii2-bootstrap                2.0.8              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer                 2.0.6              The composer plugin for Yii extension installer
yiisoft/yii2-debug                    2.0.13             The debugger extension for the Yii framework
yiisoft/yii2-gii                      2.0.6              The Gii extension for the Yii framework
yiisoft/yii2-queue                    2.0.2              Yii2 Queue Extension which supported DB, Redis, RabbitMQ, Beanstalk and Gearman
yiisoft/yii2-redis                    2.0.8              Redis Cache, Session and ActiveRecord for the Yii framework
yiisoft/yii2-sphinx                   2.0.10             Sphinx full text search engine extension for the Yii framework
yiisoft/yii2-swiftmailer              2.1.0              The SwiftMailer integration for the Yii framework

* Suite configuration:

```yml
suite_namespace: frontend\tests\functional
actor: FunctionalTester
modules:
    enabled:
        - \frontend\tests\Helper\Functional
        - Filesystem
        - Yii2
        - REST:
            url: /
            depends: Yii2
            part: Json
```

I found problem.
https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Lib/Connector/Yii2.php#L207

`$content` for json response format is empty.

```php
if ($response->format == 'json') {
   $content = json_encode($response->data);
}
```
is working

**Comment by SamMousa** [comment]
In line 182 the response is sent, which causes Yii to prepare it (formatting data and storing it in content).
In your debug output it also shows no response headers, but the `JsonResponseFormatter` adds a `Content-Type` header.
This leads me to believe that there is actually something happening in your application causing it to not send the response.

If possible please create a minimal test case PR at https://github.com/Codeception/yii2-tests; that way we can fix your issue and prevent future regression.
