### ISSUE TITLE
_inject method in AcceptanceTester isn't called

### ISSUE THREAD

**Issue by matheusab** [Codeception/Codeception#4947]
#### What are you trying to achieve?
I'm trying to inject a PageObject into an Actor class through its _inject method.

#### What do you get instead?
_inject method isn't called, therefore the PageObject isn't injected

### Details
When using StepObjects (which extend my AcceptanceTester actor), the StepObject's _inject method is called and the PageObjects are injected.
However, when using a Cest format test, the AcceptanceTester's _inject method isn't called. 
Is this the expected behavior?
Thanks.

* Codeception version: 2.4.1
* PHP Version: 7.2.3
* Operating System: Windows 10
* Installation type:  Composer
* List of installed packages (`composer show`)
behat/gherkin                      v4.5.1             Gherkin DSL parser for PHP 5.3
codeception/codeception            2.4.1              BDD-style testing framework
codeception/phpunit-wrapper        7.1.0              PHPUnit classes used by Codeception
codeception/stub                   1.0.2              Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.1.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.5.0              A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.4.2              PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.7.0              Create deep copies (clones) of your objects
phar-io/manifest                   1.0.1              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1              Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.4.0
phpspec/prophecy                   1.7.5              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          6.0.3              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  2.0.0              Utility class for timing
phpunit/php-token-stream           3.0.0              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.1.3              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       6.1.1              Mock Object library for PHPUnit
psr/http-message                   1.0.1              Common interface for HTTP messages
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.3              Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.0              Diff implementation
sebastian/environment              3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0              Snapshotting of global state
sebastian/object-enumerator        3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
symfony/browser-kit                v4.0.8             Symfony BrowserKit Component
symfony/console                    v4.0.8             Symfony Console Component
symfony/css-selector               v4.0.8             Symfony CssSelector Component
symfony/dom-crawler                v4.0.8             Symfony DomCrawler Component
symfony/event-dispatcher           v4.0.8             Symfony EventDispatcher Component
symfony/finder                     v4.0.8             Symfony Finder Component
symfony/polyfill-mbstring          v1.7.0             Symfony polyfill for the Mbstring extension
symfony/process                    v4.0.8             Symfony Process Component
symfony/yaml                       v4.0.8             Symfony Yaml Component
theseer/tokenizer                  1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
trf4/testes-eproc-classes-base     dev-master 369a074 Cont\m classes de uso comum/de aux\lio a testes de aceita\\o/funcionais do eproc.
webmozart/assert                   1.3.0              Assertions to validate method input/output with nice error messages.

**Comment by xethub** [comment]
This basically blocks in Acceptance Testing every logic class that depend on ui navigation. I can not write any Visitor that depend in the constructor on the AcceptanceTester and that is the place where it belongs in any logically state of the art development possibility:

```php
<?php

class MenuManager {
   public function sticky(AcceptanceTester $I, WebDriverElement $container): StickyMenuVisitor {
     ...
   }
   public function sidebar(AcceptanceTester $I,  WebDriverElement $container): SiderBarVisitor {
     ...
   }
   ...
}

class SiderBarVisitor {
   public function add(AcceptanceTester $I, $type): void {
     ...
   }
   public function platform(AcceptanceTester $I, $type): void {
     ...
   }
   ...
}
```

When you try to simulate this it even getting worse (as you need event bridges), also other internal classes are not available through the injection, I have not find anyway how to getting the AcceptanceTester god object into dependency injection

please fix this :pray:

**Comment by Naktibalda** [comment]
It would be great if you coud set the version of codeception to `"codeception/codeception": "dev-inject-dependencies-to-actor as 5.0.0"` and check if it works for you.
