### ISSUE TITLE
RunProcess extension enchancement

### ISSUE THREAD

**Issue by JackRobbers** [Codeception/Codeception#4953]
Some suggestions for improvement to the RunProcess extension. Would these be welcome in codeception? If so, I can implement them.

RunProcess currently runs its configured commands for every suite. It would be useful to be able to run commands for each test i.e if each test requires a clean database state.

RunProcess currently uses the 'sleep' config option to ensure that processes are fully started. Some processes exit rather than running indefinitely. A per command 'wait' option could be used to configure whether to wait for a process to exit. The default would be to not wait

 
Possible configuration format for these enhancements:
```
extensions:
  enabled:
    - Codeception\RunProcess:
           suite:
              -php -S 127.0.0.1:8000
              -java -jar selenium-server.jar
           test:
               ./wipeDatabase.sh
                  wait: true


```

**Comment by DavertMik** [comment]
> RunProcess currently runs its configured commands for every suite. It would be useful to be able to run commands for each test i.e if each test requires a clean database state.

Let's not overcomplicate that. `RunProcess` is a sample extension and you can implement your own which acts the way you need to. So If you need a per test process execution - just make another extension 😎 

And yes, you can publish them at our Addons page
