### ISSUE TITLE
Total execution time increases to hours if machine is kept in sleep in state and tests are paused

### ISSUE THREAD

**Issue by samiullah** [Codeception/Codeception#4959]
```bash
# paste output here
```
> Provide test source code if related

Time: 9.21 hours, Memory: 84.25MB

```php
// paste test
```
### Details

* Codeception version: 2.2.1
* PHP Version: 7
* Operating System: OSX 10.x
* Installation type:  Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
Is it an issue?
Have you got any ideas how to fix it?

**Comment by DavertMik** [comment]
I can't even imagine how long your tests will take if you turn off your machine!

**Comment by DavertMik** [comment]
Sorry, the amount of time is not an issue in such case. As it's not very common for test machines to be put to sleep while running tests. If you do that often that's strange )
