### ISSUE TITLE
Transaction is not closing after empty test if using fixtures [Yii]

### ISSUE THREAD

**Issue by yuriypanas** [Codeception/Codeception#4963]
#### What are you trying to achieve?
Closing transaction after test

#### What do you get instead?
If test contains fixtures but do not use it inside test or do not use database inside test it starts transaction and does not close it. It breaks next test.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
-
Modules: Yii2, Asserts
--------------------------------------------------------------------------------------------------------------------------------
- TransactionTest: Transaction
  Destroying application
  Starting application
  [Fixtures] Loading fixtures
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=test'
  [Fixtures] Opened database connection: mysql:host=localhost;dbname=test
  [Fixtures] Closing database connection: mysql:host=localhost;dbname=test
  [Fixtures] Done
✔ TransactionTest: Transaction (0.03s)
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=mysql-server;dbname=projectx_test'
  [Database] Transaction started for: mysql:host=localhost;dbname=test
  Destroying application
  Suite done, restoring $_SERVER to original
--------------------------------------------------------------------------------------------------------------------------------


Time: 630 ms, Memory: 12.00MB

OK (1 test, 0 assertions)
```
> Provide test source code if related

```php
class TransactionTest extends \Codeception\Test\Unit
{
    /**
     * @var \api\tests\UnitTester
     */
    protected $tester;

    public function _fixtures()
    {
        return [
            'user' => [
                'class' => UserFixture::class,
                'dataFile' => codecept_data_dir() . 'user.php'
            ],
        ];
    }

    public function testTransaction()
    {

    }
}
```
### Details

* Codeception version: 2.4.1
* PHP Version: 7.1.16
* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
almasaeed2010/adminlte             v2.4.3             AdminLTE - admin control panel and dashboard that's based on Bootstrap 3
behat/gherkin                      v4.5.1             Gherkin DSL parser for PHP 5.3
bower-asset/bootstrap              v3.3.7
bower-asset/inputmask              3.3.11
bower-asset/jquery                 3.2.1
bower-asset/punycode               v1.3.2
bower-asset/typeahead.js           v0.11.1
bower-asset/yii2-pjax              2.0.7.1
cebe/markdown                      1.1.2              A super fast, highly extensible markdown parser for PHP
cebe/yii2-gravatar                 1.1                Gravatar Widget for Yii 2
codeception/base                   2.4.1              BDD-style testing framework
codeception/phpunit-wrapper        7.1.1              PHPUnit classes used by Codeception
codeception/specify                0.4.6              BDD code blocks for PHPUnit and Codeception
codeception/stub                   1.0.2              Flexible Stub wrapper for PHPUnit's Mock Builder
codeception/verify                 0.3.3              BDD assertion library for PHPUnit
composer/ca-bundle                 1.1.1              Lets you find a path to the system CA bundle, and includes a fallback...
composer/installers                v1.5.0             A multi-framework Composer library installer
dmstr/yii2-adminlte-asset          2.6.0              AdminLTE backend theme asset bundle for Yii 2.0 Framework
doctrine/instantiator              1.1.0              A small, lightweight utility to instantiate objects in PHP without in...
domnikl/statsd                     2.9.0              a PHP client for statsd
ezyang/htmlpurifier                v4.10.0            Standards compliant HTML filter written in PHP
firebase/php-jwt                   v4.0.0             A simple library to encode and decode JSON Web Tokens (JWT) in PHP. S...
fortawesome/font-awesome           v4.7.0             The iconic font and CSS framework
fzaninotto/faker                   v1.7.1             Faker is a PHP library that generates fake data for you.
geoip2/geoip2                      v2.9.0             MaxMind GeoIP2 PHP API
guzzlehttp/guzzle                  6.3.3              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.4.2              PSR-7 message implementation that also provides common utility methods
intervention/image                 2.4.1              Image handling and manipulation library with support for Laravel inte...
jean85/pretty-package-versions     1.1                A wrapper for ocramius/pretty-package-versions to get pretty versions...
mailfire/php-sdk                   0.1.26             Mailfire PHP SDK
maxmind-db/reader                  v1.3.0             MaxMind DB Reader API
maxmind/web-service-common         v0.5.0             Internal MaxMind Web Service API
mobiledetect/mobiledetectlib       2.8.31             Mobile_Detect is a lightweight PHP class for detecting mobile devices...
myclabs/deep-copy                  1.7.0              Create deep copies (clones) of your objects
nette/bootstrap                    v2.4.5             🅱 Nette Bootstrap: the simple way to configure and bootstrap your ...
nette/di                           v2.4.11            💎 Nette Dependency Injection Container: Flexible, compiled and ful...
nette/finder                       v2.4.1             Nette Finder: Files Searching
nette/neon                         v2.4.2             Nette NEON: parser & generator for Nette Object Notation
nette/php-generator                v3.0.4             🐘 Nette PHP Generator: generates neat PHP code for you. Supports n...
nette/robot-loader                 v3.0.3             🍀 Nette RobotLoader: high performance and comfortable autoloader t...
nette/utils                        v2.5.2             🛠 Nette Utils: lightweight utilities for string & array manipulati...
nikic/php-parser                   v3.1.5             A PHP parser written in PHP
npm-asset/jquery                   2.2.4
ocramius/package-versions          1.3.0              Composer plugin that provides efficient querying for installed packag...
phar-io/manifest                   1.0.1              Component for reading phar.io manifest information from a PHP Archive...
phar-io/version                    1.0.1              Library for handling version information and constraints
php-amqplib/php-amqplib            v2.7.2             Formerly videlalvaro/php-amqplib.  This library is a pure PHP impleme...
phpdocumentor/reflection-common    1.0.1              Common reflection classes used by phpdocumentor to reflect the code s...
phpdocumentor/reflection-docblock  4.3.0              With this component, a library can provide support for annotations vi...
phpdocumentor/type-resolver        0.4.0
phpspec/php-diff                   v1.1.0             A comprehensive library for generating differences between two hashab...
phpspec/prophecy                   1.7.6              Highly opinionated mocking framework for PHP 5.3+
phpstan/phpdoc-parser              0.2                PHPDoc parser with support for nullable, intersection and generic types
phpstan/phpstan                    0.9.2              PHPStan - PHP Static Analysis Tool
phpunit/php-code-coverage          6.0.4              Library that provides collection, processing, and rendering functiona...
phpunit/php-file-iterator          1.4.5              FilterIterator implementation that filters files based on a list of s...
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  2.0.0              Utility class for timing
phpunit/php-token-stream           3.0.0              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.1.4              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       6.1.1              Mock Object library for PHPUnit
psr/http-message                   1.0.1              Common interface for HTTP messages
psr/log                            1.0.2              Common interface for logging libraries
rmrevin/yii2-fontawesome           2.17.1             Asset Bundle for Yii2 with Font Awesome
roave/security-advisories          dev-master d3268ea Prevents installation of composer packages with known security vulner...
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.3              Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.0              Diff implementation
sebastian/environment              3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0              Snapshotting of global state
sebastian/object-enumerator        3.0.3              Traverses array structures and object graphs to enumerate all referen...
sebastian/object-reflector         1.1.1              Allows reflection of object attributes, including inherited and non-p...
sebastian/recursion-context        3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP...
squizlabs/php_codesniffer          3.2.3              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects v...
swiftmailer/swiftmailer            v5.4.9             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                v4.0.9             Symfony BrowserKit Component
symfony/console                    v4.0.9             Symfony Console Component
symfony/css-selector               v4.0.9             Symfony CssSelector Component
symfony/dom-crawler                v4.0.9             Symfony DomCrawler Component
symfony/event-dispatcher           v4.0.9             Symfony EventDispatcher Component
symfony/finder                     v4.0.9             Symfony Finder Component
symfony/polyfill-mbstring          v1.8.0             Symfony polyfill for the Mbstring extension
symfony/yaml                       v4.0.9             Symfony Yaml Component
theseer/tokenizer                  1.1.0              A small library for converting tokenized PHP source code into XML and...
twilio/sdk                         5.18.0             A PHP wrapper for Twilio's API
webmozart/assert                   1.3.0              Assertions to validate method input/output with nice error messages.
wisembly/elephant.io               v3.3.1             Send events to a websocket real time engine though PHP
yiisoft/yii2                       2.0.15.1           Yii PHP Framework Version 2
yiisoft/yii2-bootstrap             2.0.8              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer              2.0.6              The composer plugin for Yii extension installer
yiisoft/yii2-debug                 2.0.13             The debugger extension for the Yii framework
yiisoft/yii2-faker                 2.0.4              Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                   2.0.7              The Gii extension for the Yii framework
yiisoft/yii2-redis                 2.0.8              Redis Cache, Session and ActiveRecord for the Yii framework
yiisoft/yii2-swiftmailer           2.0.7              The SwiftMailer integration for the Yii framework
* Suite configuration:

```yml
actor: UnitTester
bootstrap: false
modules:
    enabled:
        - Yii2:
            part: [orm, email, fixtures]
            cleanup: true
            transaction: true
        - Asserts
```

**Comment by SamMousa** [comment]
This is strange; in your config you have `cleanup: true`.
Transactions and fixtures are 2 different things.

In your case the order would be:
1. Load fixtures.
2. Register transaction handler
3. Run empty test
4. Unregister connection open handler
5. Rollback transactions
6. Unload fixtures.

But your log out put shows something else, it also shows 2 different database connections, this gives me the feeling what you've posted is an incorrect / incomplete "minimal" sample.

Could you create a PR here https://github.com/Codeception/yii2-tests containing a minimal test case? 
That way we can not only resolve the issue but also prevent regression in the future.

**Comment by yuriypanas** [comment]
Added to my TransactionTest test when I used fixture
```bash
-
Modules: Yii2, Asserts
----------------------------------------------------------------------------------------------------------------------
- TransactionTest: Test with fixture
  Destroying application
  Starting application
  [Fixtures] Loading fixtures
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=test'
  [Fixtures] Opened database connection: mysql:host=localhost;dbname=test
  [Fixtures] Closing database connection: mysql:host=localhost;dbname=test
  [Fixtures] Done
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=test'
  [Database] Transaction started for: mysql:host=localhost;dbname=test
✔ TransactionTest: Test with fixture (0.06s)
  [Database] Transaction cancelled; all changes reverted.
  Destroying application
- TransactionTest: Empty test  Destroying application
  Starting application
  [Fixtures] Loading fixtures
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=test'
  [Fixtures] Opened database connection: mysql:host=localhost;dbname=test
  [Fixtures] Closing database connection: mysql:host=localhost;dbname=test
  [Fixtures] Done
✔ TransactionTest: Empty test (0.00s)
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=test'
  [Database] Transaction started for: mysql:host=localhost;dbname=test
  Destroying application
  Suite done, restoring $_SERVER to original
```
Code:
```php
class TransactionTest extends \Codeception\Test\Unit
{
    /**
     * @var \api\tests\UnitTester
     */
    protected $tester;

    public function _fixtures()
    {
        return [
            'user' => [
                'class' => UserFixture::class,
                'dataFile' => codecept_data_dir() . 'user.php'
            ],
        ];
    }

    public function testTestWithFixture()
    {
        $this->tester->grabFixture('user', 1);
    }

    public function testEmptyTest()
    {

    }
}
```
In first test case everything goes like you mention.

**Comment by SamMousa** [comment]
Can you add the next test as well? So I can see exactly where it breaks.

**Comment by yuriypanas** [comment]
I guess I know the reason.

When test starts it registers event on open db connection.
Module/Yii2.php Line: 327
```php
Event::on(Connection::class, Connection::EVENT_AFTER_OPEN, function (Event $event) {
```
If I do not use db connection inside test it does not open.
But after test unloadFixtures() runs
Module/Yii2.php Line: 310 
which opens db connection and after that Event handler started transaction.

**Comment by SamMousa** [comment]
Definitely something going on. Can you create a minimal test case in the codeception/yii2-tests repo?

**Comment by yuriypanas** [comment]
> Before unloading fixtures it unregisters the handler check the rollback function

I can't find when it unregistered handler.
Could you please show?

> Can you create a minimal test case in the codeception/yii2-tests repo?
I can't do it now. Sorry. Will do it later

**Comment by yuriypanas** [comment]
I see method _after()

Line 306: $this->rollbackTransactions(); 
does not run because $this->transaction is empty

After that runs $fixture->unloadFixtures(); which opens db connection

Am I right?

**Comment by SamMousa** [comment]
It always runs

**Comment by yuriypanas** [comment]
I can't find the code which unregistered the handler.
Could you please show it?

**Comment by yuriypanas** [comment]
I made some debug.
Edited file Module/Yii2.php method _after()

```php
    public function _after(TestInterface $test)
    {
        $_SESSION = [];
        $_FILES = [];
        $_GET = [];
        $_POST = [];
        $_COOKIE = [];
        $_REQUEST = [];

        $this->rollbackTransactions();
echo "debug: before unloadFixtures\n";
        if ($this->config['cleanup']) {
            foreach ($this->loadedFixtures as $fixture) {
                $fixture->unloadFixtures();
            }
            $this->loadedFixtures = [];
        }
die;
        if ($this->client->getApplication()->has('session', true)) {
            $this->client->getApplication()->session->close();
        }

        parent::_after($test);
    }
```
Place line
echo "debug: before unloadFixtures\n";
and
die;

And I run test with only one empty test.
This is result
```bash
- TransactionTest: Empty test
  Destroying application
  Starting application
  [Fixtures] Loading fixtures
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=test'
  [Fixtures] Opened database connection: mysql:host=localhost;dbname=test
  [Fixtures] Closing database connection: mysql:host=localhost;dbname=test
  [Fixtures] Done
✔ TransactionTest: Empty test (0.02s)
debug: before unloadFixtures
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=localhost;dbname=test'
  [Database] Transaction started for: mysql:host=localhost;dbname=test
PHP Fatal error:  Uncaught RuntimeException: Command Did Not Finish Properly in /var/www/juliadates/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
```

And I see that the code with unloading fixtures opens db connection and starts transaction.

**Comment by yuriypanas** [comment]
I try to add unregistered handler code to method _after() and it helps
```php
public function _after(TestInterface $test)
    {
        $_SESSION = [];
        $_FILES = [];
        $_GET = [];
        $_POST = [];
        $_COOKIE = [];
        $_REQUEST = [];

        $this->rollbackTransactions();

        Event::off(Connection::class, Connection::EVENT_AFTER_OPEN);

        if ($this->config['cleanup']) {
            foreach ($this->loadedFixtures as $fixture) {
                $fixture->unloadFixtures();
            }
            $this->loadedFixtures = [];
        }

        if ($this->client->getApplication()->has('session', true)) {
            $this->client->getApplication()->session->close();
        }

        parent::_after($test);
    }
```
In this case transcation does not start

**Comment by SamMousa** [comment]
Line 431..  Maybe unregister is failing, but it should always be called there

**Comment by yuriypanas** [comment]
I guess you told about this file
https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Module/Yii2.php

But I use this one (codeception/base)
https://github.com/Codeception/base/blob/2.4/src/Codeception/Module/Yii2.php
and it does not contain line
```php
Event::off(Connection::class, Connection::EVENT_AFTER_OPEN, [$this, 'connectionOpenHandler']);
```
I use codeception/base according yii app template
https://github.com/yiisoft/yii2-app-advanced/blob/master/composer.json

**Comment by SamMousa** [comment]
Then close this issue; you're not using latest version...

**Comment by epifrin** [comment]
Should I use codeception/codeception instead?

**Comment by yuriypanas** [comment]
Should I use codeception/codeception instead?
I use last version of codeception/base.

**Comment by samdark** [comment]
@DavertMik would you please clarify it?

**Comment by andymitrich** [comment]
Up! It's too annoying, guys. 

```[yii\db\Connection::open] 'Opening DB connection: ...
  [Database] Transaction started for: ...
  Destroying application
AuthCest: Login a registered user with wrong password
Signature: api\tests\AuthCest:testLoginWithWrongPassword
Test: tests/api/AuthCest.php:testLoginWithWrongPassword
Scenario --
  Destroying application
  Starting application
  [Fixtures] Loading fixtures
  [yii\db\Connection::open] 'Opening DB connection: ...
  [Fixtures] Opened database connection: ...
```
