### ISSUE TITLE
Composer warning "Adding phpunit/phpunit as a dependency is discouraged in favor of Symfony's PHPUnit Bridge"

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4974]
When installing Codeception in Symfony 4 with `composer require "codeception/codeception" --dev`, I'm getting this warning from composer:
> Adding phpunit/phpunit as a dependency is discouraged in favor of Symfony's PHPUnit Bridge.

Plus this hint:
> Instead:
    1. Remove it now: composer remove --dev phpunit/phpunit
    2. Use Symfony's bridge: composer require --dev phpunit

**Comment by Naktibalda** [comment]
Thanks for raising an issue in Symfony repository, I'm closing this issue now, because it isn't our issue.
