### ISSUE TITLE
Preferred way to start Codeception is now `./vendor/bin/codecept`?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4975]
The docs are inconsistent about the CLI command to run Codeception:
* https://codeception.com/quickstart says `./vendor/bin/codecept`. This works for me in Symfony 4, but not in Symfony 3.
* https://codeception.com/for/symfony says `php bin/codecept`. This works in Symfony 3, but not in Symfony 4.
* `bin/codecept` (don't know where I've got that from) works in Symfony 3, but not in Symfony 4.

So what's the best way now? How can people find out? I'll update the docs if you tell me.

**Comment by Naktibalda** [comment]
`vendor/bin/` is a default composer location for executable files.
I wasn't aware that something creates files in `bin/`, probably installer of some package does that.

**Comment by johannesschobel** [comment]
Hey @ThomasLandauer ,

i think, this also depends on the OS you are working on, right?
On *nix OS you may simply call `/vendor/bin/codecept run ...` but on Windows you need to call `call /vendor/bin/codecept run ... ` (notice the `call` before).

**Comment by ThomasLandauer** [comment]
@Naktibalda: In my Symfony 3 project, I don't even have a `vendor/bin` directory. I have a file `bin/codecept`, and it is a symlink to `vendor/codeception/codeception/codecept`. This was certainly installed that way by Codeception itself.

@DavertMik: The docs should be (a) consistent and (b) work out of the box (i.e. copy-paste) for *new* installations. So let's go for `./vendor/bin/codecept`?

**Comment by johannesschobel** [comment]
hey @ThomasLandauer ,

on my windows dev machine i cannot run `./vendor/bin/codecept ...` in order to run a specific command. I need to use the `call` keyword before the actual command.. So for me (on Windows) it would look like this:
```

**Comment by SamMousa** [comment]
@ThomasLandauer I think you have a `bin-dir` config in your composer.json.

https://getcomposer.org/doc/articles/vendor-binaries.md#vendor-binaries-and-the-vendor-bin-directory
