### ISSUE TITLE
Run Tests from Various Folders

### ISSUE THREAD

**Issue by johannesschobel** [Codeception/Codeception#4982]
Dear @DavertMik , contributors and community,

thank you so much for this awesome project! I really like the approach of having **one** testing framework that serves all different kind of "testing layers" (e.g., unit, functional, acceptance, ...) :+1: 

#### Problem Description:

For now, our application uses `PHPUnit` to run its tests. The project structure is as follows (simplified):
```bash
\
|- app\
|--- modules
|----- authentication
|----- product
|----- user
```

Each `module`, in turn, has its own models, and is testable on its own (at least for the `Unit` level!). This means, that there is a `tests` folder in each `module`, like so:

```bash
\
|- app\
|--- modules
|----- authentication
|------- tests
|--------- TestIfUserCanLogin.php
|--------- TestIfUserCanLogout.php
|--------- TestIfUserIsConfirmed.php
|----- product
|------- tests
|----- user
|------- tests
```

#### What are you trying to achieve?

Now I would like to have **one** single `codeception.yml` file in my root directory to "include" all tests that are "scattered" around my project. How can I achieve this?

I thought, I may want to use the **One Runner for Multiple Applications** (https://codeception.com/docs/08-Customization#One-Runner-for-Multiple-Applications)[https://codeception.com/docs/08-Customization#One-Runner-for-Multiple-Applications] approach.. But I am not sure, if this is the case for me, because the `modules` are not really "standalone applications".

Furthermore, this would result in a huge "overload" in re-configuring all the dedicated `codeception.yml` files for each module again, right?! What if i want to store my `.env.testing` environment in the root-level of my project?

Is there a better approach for my problem?
I found a similar issue https://github.com/Codeception/Codeception/issues/4884 here, but no answer...

Thank you so much for your time and help!
Cheers,
Johannes 

### Details

* Codeception version: 2.4.1
* PHP Version: 7.2.1
* Operating System: Windows 
* Installation type: Composer
* List of installed packages (`composer show`): Mostly Laravel stuff

**Comment by johannesschobel** [comment]
I am closing this one.. it is not solved, but it is something I can work with ;) respective PR helps solving a lot of problems in these scenarios!

**Comment by DavertMik** [comment]
Thanks! And thanks for awesome PR!

**Comment by johannesschobel** [comment]
You are welcome :)
