### ISSUE TITLE
Use Artisan Commands

### ISSUE THREAD

**Issue by johannesschobel** [Codeception/Codeception#4983]
Dear @DavertMik and @janhenkgerritsen specifically,

thank you for this awesome package.. Really like it because of its clean and easy to use API. Really good work guys (and girls) out there!

I recently stumbled upon the following issue, i would like to share with you guys..

#### What are you trying to achieve?

I develop a Laravel application and i provide some self-developed commands. These commands, in turn, may be called via `php artisan your:custom:command` from within the `Laravel` framework. I use these commands to "bootstrap" modules (e.g., auto-generate code, ...). While this works fine and saves a lot of time, i would like to provide my own `Artisan` command to fully bootstrap the `Test` setup required for `Codeception` to properly work..

As outlined in #4982 (an issue opened by me ;) ), i described my project structure (which consists of several modules. The modules, however, must be coordinated by one single `master codeception.yml` file!).

For each of these modules, i would like to automatically generate the suits `A`, `B` and `C` (depending on the user that executes the command!). In this case, i would need to call your commands. However, currently, `Codeception` does not offer `Artisan` commands for Laravel. How can i still call your commands from `Laravel` internally? Because using your commands would save me a crap ton of time as they already work as expected ;)

Is there a "wrapper" for the `Codeception` commands to be used in `Laravel's Artisan` commands? If you, how? ;)

Cheers and all the best,
Johannes

**Comment by DavertMik** [comment]
Hey, did you check `callArtisan` command from module? https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Module/Laravel5.php#L434

Also, we don't have active Laravel module maintainer as Jan-Henk resigned. If you are interested to help us improving this module - you are welcome to contribute!

**Comment by johannesschobel** [comment]
Dear @DavertMik ,

thank you for your answer.. I already found the `callArtisan` command in respective module. However, as far as i have understood, this "only" allows to call an existing `Artisan` command..

What i would like to do:
I would like to call your default `codeception` commands (e.g., `call vendor/bin/codecept -c app/module/XXX/Tests g:suite api`) to be called from a Laravel application.

That is, basically, the other way around ;)

**Comment by DavertMik** [comment]
Ah, I see it. Well it turns out that you need to implement them yourself as Laravel package. 
We do something similar for Robo https://robo.li/tasks/Testing/#codecept

**Comment by johannesschobel** [comment]
Oh wow.. That is some nice reference to look into :) thanks mate!

Cheers
