### ISSUE TITLE
Override parameter doesnt work as expected

### ISSUE THREAD

**Issue by matjanis** [Codeception/Codeception#4999]
I want to override settings from acceptance.suite.yml

Setting from the override parameter is applied as first and is overidden by setting from acceptance.suite.yml. (-o "modules: config: WebDriver: url: 'https://google.pl'" to be specific). 

* Codeception version: 2.3.9
* PHP Version: 7.1
* Operating System: MacOS
* Installation type: Composer

**Comment by aurum86** [comment]
I think I have a fix for this issue. Will provide a pull request soon.

**Comment by eXorus** [comment]
Old issues, I'm closing it.
