### ISSUE TITLE
PHPUnit Assertions

### ISSUE THREAD

**Issue by johannesschobel** [Codeception/Codeception#5002]
Dear @DavertMik and community,

I am trying to migrate my tests from PHPUnit to Codeception CESTs because of its awesome functional and acceptance tests (:+1: ). However, i recently stumbled upon the following issue - maybe you can help me with this?

Consider the following minimal example:
```php
class UserManagerCest 
{
    /**
     * @param UnitTester $I
     */
    public function test_if_only_users_are_returned(UnitTester $I)
    {
        $users = ... // get all users from the database here

        $I->assertContainsOnlyInstancesOf(
            User::class,
            $users
        );
    }
```

However, this fails, because the `UnitTester` does **not** inherit the required `assertContainsOnlyInstancesOf()` method. Same with many other functions `PHPUnit` offers (cf. [this link here](https://phpunit.readthedocs.io/en/7.1/assertions.html))

What do you suggest to get these `PHPUnit`-based assertions? I need them because otherwise all my tests will fail, because I also heavily rely on the `assertJson...()` and other functions..

Thanks in advance for your time and effort,
Cheers!

**Comment by johannesschobel** [comment]
Oh.. damn.. I forgot to post my `unit.suite.yml` file..
Here is the config:
```yml
actor: UnitTester
modules:
    enabled:
        - Asserts
        - \App\tests\Helper\Unit
```

**Comment by fishfacemcgee** [comment]
@johannesschobel Is `UserManagerCest` extending anything? In your example, it's not.

**Comment by johannesschobel** [comment]
Hey guys..
I ran into another issue with this, as i tried to do the following:

```php
class UserManagerCest extends PHPUnit\Framework\TestCase\TestCase
```

This way, the required methods are available.. However, if i execute the test, codeception tries to execute all (!) methods that are defined within `TestCase`, as the `CEST` automatically executes all methods..

How can I use the default PHPUnit assertions in combination with Codeceptions CESTs? Any suggestions? Or am i missing something?

**Comment by Naktibalda** [comment]
If you want all PhpUnit assertions, why don't you stick with Test format?

**Comment by johannesschobel** [comment]
@Naktibalda I could.. However, this is purely because of aesthetics and "same-style-policy", haha.. Because the `Acceptance` and `Functional` Tests both use `Cest` format, so why not the `Unit` Tests?
The `AcceptanceTester` and `FunctionalTester` can be used within the actual test-method as `$I`, the `UnitTester`, however, must be called as `$this->tester`..

**Comment by johannesschobel** [comment]
I thought about adding a property `protected $usePHPUnitTo` to my `Tester` classes.. So i can call it like so:
```php
$I->usePHPUnitTo->CustomPHPUnitFunction();
```
however, this may also be some quircks mode :laughing:

**Comment by DavertMik** [comment]
PHPUnit assertions are actually static methods of `PHPUnit\Framework\Assert`. You can call them from anywhere. 

My opinion: PHPUnit has too much default assertions and I don't think we should bring all of them on board. But if you wish to, create your helper method and call the corresponding static method from  `PHPUnit\Framework\Assert`

**Comment by johannesschobel** [comment]
Hey @DavertMik thank you very much for your suggestions.. actually, that is what I did for now :)

Have a nice weekend
