### ISSUE TITLE
Api testing with Symfony 4.1 "Environment variable not found:" Error

### ISSUE THREAD

**Issue by sela** [Codeception/Codeception#5010]
#### What are you trying to achieve?
I try to test an GET REST API and use         
```
   $I->sendGET('http://localhost:8000/api/displays');
```
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Test  tests/api/DisplayControllerCest.php:tryToTest

  [Symfony\Component\DependencyInjection\Exception\EnvNotFoundException] Environment variable not found: "CORS_ALLOW_ORIGIN".


Scenario Steps:

 2. $I->sendGET("http://localhost:8000/api/displays") at tests/api/DisplayControllerCest.php:18
 1. $I->haveHttpHeader("X-Requested-With","Codeception") at tests/api/DisplayControllerCest.php:17

/Users/sela/PhpstormProjects/ziggy/vendor/symfony/dependency-injection/EnvVarProcessor.php:77
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/dependency-injection/Container.php:398
/Users/sela/PhpstormProjects/ziggy/var/cache/test/ContainerPx938UN/srcTestDebugProjectContainer.php:2046
/Users/sela/PhpstormProjects/ziggy/var/cache/test/ContainerPx938UN/srcTestDebugProjectContainer.php:1899
/Users/sela/PhpstormProjects/ziggy/var/cache/test/ContainerPx938UN/srcTestDebugProjectContainer.php:1386
/Users/sela/PhpstormProjects/ziggy/var/cache/test/ContainerPx938UN/srcTestDebugProjectContainer.php:1396
/Users/sela/PhpstormProjects/ziggy/var/cache/test/ContainerPx938UN/srcTestDebugProjectContainer.php:1376
/Users/sela/PhpstormProjects/ziggy/var/cache/test/ContainerPx938UN/srcTestDebugProjectContainer.php:473
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/event-dispatcher/EventDispatcher.php:145
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:267
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:136
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/http-kernel/HttpKernel.php:125
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/http-kernel/HttpKernel.php:66
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/http-kernel/EventListener/ExceptionListener.php:63
/Users/sela/PhpstormProjects/ziggy/vendor/friendsofsymfony/rest-bundle/EventListener/ExceptionListener.php:41
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:104
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/event-dispatcher/EventDispatcher.php:212
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/event-dispatcher/EventDispatcher.php:44
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:141
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/http-kernel/HttpKernel.php:219
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/http-kernel/HttpKernel.php:77
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/http-kernel/Kernel.php:188
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/http-kernel/Client.php:68
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Lib/Connector/Symfony.php:54
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/browser-kit/Client.php:349
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:193
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:125
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Module/REST.php:597
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Module/REST.php:459
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Step.php:264
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Scenario.php:72
/Users/sela/PhpstormProjects/ziggy/tests/_support/_generated/ApiTesterActions.php:2726
/Users/sela/PhpstormProjects/ziggy/tests/api/DisplayControllerCest.php:18
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Lib/Di.php:127
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Test/Cest.php:138
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Test/Cest.php:150
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Test/Cest.php:82
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Test/Test.php:89
/Users/sela/PhpstormProjects/ziggy/vendor/phpunit/phpunit/src/Framework/TestSuite.php:776
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/phpunit-wrapper/src/Runner.php:114
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Codecept.php:189
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Codecept.php:158
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Command/Run.php:466
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Command/Run.php:361
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/console/Command/Command.php:251
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/console/Application.php:886
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/console/Application.php:262
/Users/sela/PhpstormProjects/ziggy/vendor/symfony/console/Application.php:145
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/src/Codeception/Application.php:108
/Users/sela/PhpstormProjects/ziggy/vendor/codeception/codeception/codecept:42


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

Remaining deprecation notices (1)
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.4.2
* PHP Version: 7.1.6
* Operating System: Mac High Sierra
* Installation type:  Composer
* List of installed packages (`composer show`)
behat/gherkin                       v4.5.1             Gherkin DSL parser for PHP 5.3
codeception/codeception             2.4.2              BDD-style testing framework
codeception/phpunit-wrapper         7.1.3              PHPUnit classes used by Codeception
codeception/stub                    2.0.1              Flexible Stub wrapper for PHPUnit's Mo...
creof/doctrine2-spatial             1.2.0              Doctrine2 multi-platform support for s...
creof/geo-parser                    2.1.0              Parser for geography coordinate strings
creof/wkb-parser                    v2.3.0             Parser for well-known binary (WKB/EWKB...
creof/wkt-parser                    2.2.0              Parser for well-known text (WKT) objec...
doctrine/annotations                v1.6.0             Docblock Annotations Parser
doctrine/cache                      v1.7.1             Caching library offering an object-ori...
doctrine/collections                v1.5.0             Collections Abstraction library
doctrine/common                     v2.8.1             Common Library for Doctrine projects
doctrine/dbal                       v2.7.1             Database Abstraction Layer
doctrine/doctrine-bundle            1.9.1              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.3              Symfony Bundle for Doctrine Cache
doctrine/doctrine-migrations-bundle v1.3.1             Symfony DoctrineMigrationsBundle
doctrine/inflector                  v1.3.0             Common String Manipulations with regar...
doctrine/instantiator               1.1.0              A small, lightweight utility to instan...
doctrine/lexer                      v1.0.1             Base library for a lexer that can be u...
doctrine/migrations                 v1.7.2             Database Schema migrations using Doctr...
doctrine/orm                        v2.6.1             Object-Relational-Mapper for PHP
egulias/email-validator             2.1.4              A library for validating emails agains...
exsyst/swagger                      v0.4.0             A php library to manipulate Swagger sp...
facebook/webdriver                  1.6.0              A PHP client for Selenium WebDriver
friendsofsymfony/rest-bundle        2.3.1              This Bundle provides various tools to ...
friendsofsymfony/user-bundle        v2.1.2             Symfony FOSUserBundle
guzzlehttp/guzzle                   6.3.3              Guzzle is a PHP HTTP client library
guzzlehttp/promises                 v1.3.1             Guzzle promises library
guzzlehttp/psr7                     1.4.2              PSR-7 message implementation that also...
jdorn/sql-formatter                 v1.2.17            a PHP SQL highlighting library
jms/metadata                        1.6.0              Class/method/property metadata managem...
jms/parser-lib                      1.0.0              A library for easily creating recursiv...
jms/serializer                      1.12.1             Library for (de-)serializing data of a...
jms/serializer-bundle               2.4.1              Allows you to easily serialize, and de...
myclabs/deep-copy                   1.8.0              Create deep copies (clones) of your ob...
nelmio/api-doc-bundle               dev-master 662db56 Generates documentation for your REST ...
nelmio/cors-bundle                  1.5.4              Adds CORS (Cross-Origin Resource Shari...
nikic/php-parser                    v4.0.2             A PHP parser written in PHP
ocramius/package-versions           1.3.0              Composer plugin that provides efficien...
ocramius/proxy-manager              2.1.1              A library providing utilities to gener...
paragonie/random_compat             v2.0.12            PHP 5.x polyfill for random_bytes() an...
phar-io/manifest                    1.0.1              Component for reading phar.io manifest...
phar-io/version                     1.0.1              Library for handling version informati...
phpcollection/phpcollection         0.5.0              General-Purpose Collection Library for...
phpdocumentor/reflection-common     1.0.1              Common reflection classes used by phpd...
phpdocumentor/reflection-docblock   4.3.0              With this component, a library can pro...
phpdocumentor/type-resolver         0.4.0
phpoption/phpoption                 1.5.0              Option Type for PHP
phpspec/prophecy                    1.7.6              Highly opinionated mocking framework f...
phpunit/php-code-coverage           6.0.5              Library that provides collection, proc...
phpunit/php-file-iterator           1.4.5              FilterIterator implementation that fil...
phpunit/php-text-template           1.2.1              Simple template engine.
phpunit/php-timer                   2.0.0              Utility class for timing
phpunit/php-token-stream            3.0.0              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     7.1.5              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        6.1.2              Mock Object library for PHPUnit
psr/cache                           1.0.1              Common interface for caching libraries
psr/container                       1.0.0              Common Container Interface (PHP FIG PS...
psr/http-message                    1.0.1              Common interface for HTTP messages
psr/log                             1.0.2              Common interface for logging libraries
psr/simple-cache                    1.0.1              Common interfaces for simple caching
sebastian/code-unit-reverse-lookup  1.0.1              Looks up which function or method a li...
sebastian/comparator                3.0.0              Provides the functionality to compare ...
sebastian/diff                      3.0.0              Diff implementation
sebastian/environment               3.1.0              Provides functionality to handle HHVM/...
sebastian/exporter                  3.1.0              Provides the functionality to export P...
sebastian/global-state              2.0.0              Snapshotting of global state
sebastian/object-enumerator         3.0.3              Traverses array structures and object ...
sebastian/object-reflector          1.1.1              Allows reflection of object attributes...
sebastian/recursion-context         3.0.0              Provides functionality to recursively ...
sebastian/resource-operations       1.0.0              Provides a list of PHP built-in functi...
sebastian/version                   2.0.1              Library that helps with managing the v...
sensio/framework-extra-bundle       dev-master 50e8b72 This bundle provides a way to configur...
swiftmailer/swiftmailer             v6.0.2             Swiftmailer, free feature-rich PHP mailer
symfony/apache-pack                 v1.0.1             A pack for Apache support in Symfony
symfony/asset                       v4.1.0             Symfony Asset Component
symfony/browser-kit                 v4.1.0             Symfony BrowserKit Component
symfony/cache                       v4.1.0             Symfony Cache component with PSR-6, PS...
symfony/config                      v4.1.0             Symfony Config Component
symfony/console                     v4.1.0             Symfony Console Component
symfony/css-selector                v4.1.0             Symfony CssSelector Component
symfony/debug                       v4.1.0             Symfony Debug Component
symfony/dependency-injection        v4.1.0             Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.1.0             Symfony Doctrine Bridge
symfony/dom-crawler                 v4.1.0             Symfony DomCrawler Component
symfony/dotenv                      v4.1.0             Registers environment variables from a...
symfony/event-dispatcher            v4.1.0             Symfony EventDispatcher Component
symfony/filesystem                  v4.1.0             Symfony Filesystem Component
symfony/finder                      v4.1.0             Symfony Finder Component
symfony/flex                        v1.0.80
symfony/form                        v4.1.0             Symfony Form Component
symfony/framework-bundle            v4.1.0             Symfony FrameworkBundle
symfony/http-foundation             v4.1.0             Symfony HttpFoundation Component
symfony/http-kernel                 v4.1.0             Symfony HttpKernel Component
symfony/inflector                   v4.1.0             Symfony Inflector Component
symfony/intl                        v4.1.0             A PHP replacement layer for the C intl...
symfony/lts                         dev-master 6de50b2 Enforces Long Term Supported versions ...
symfony/maker-bundle                v1.5.0             Symfony Maker helps you create empty c...
symfony/options-resolver            v4.1.0             Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.5             A pack for the Doctrine ORM
symfony/phpunit-bridge              v4.1.0             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu           v1.8.0             Symfony polyfill for intl's ICU-relate...
symfony/polyfill-mbstring           v1.8.0             Symfony polyfill for the Mbstring exte...
symfony/polyfill-php72              v1.8.0             Symfony polyfill backporting some PHP ...
symfony/process                     v4.1.0             Symfony Process Component
symfony/profiler-pack               v1.0.3             A pack for the Symfony web profiler
symfony/property-access             v4.1.0             Symfony PropertyAccess Component
symfony/property-info               v4.1.0             Symfony Property Info Component
symfony/routing                     v4.1.0             Symfony Routing Component
symfony/security                    v4.1.0             Symfony Security Component
symfony/security-bundle             v4.1.0             Symfony SecurityBundle
symfony/stopwatch                   v4.1.0             Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.2.2             Symfony SwiftmailerBundle
symfony/templating                  v4.1.0             Symfony Templating Component
symfony/translation                 v4.1.0             Symfony Translation Component
symfony/twig-bridge                 v4.1.0             Symfony Twig Bridge
symfony/twig-bundle                 v4.1.0             Symfony TwigBundle
symfony/validator                   v4.1.0             Symfony Validator Component
symfony/var-dumper                  v4.1.0             Symfony mechanism for exploring and du...
symfony/web-profiler-bundle         v4.1.0             Symfony WebProfilerBundle
symfony/web-server-bundle           v4.1.0             Symfony WebServerBundle
symfony/yaml                        v4.1.0             Symfony Yaml Component
theseer/tokenizer                   1.1.0              A small library for converting tokeniz...
twig/twig                           v2.4.8             Twig, the flexible, fast, and secure t...
webmozart/assert                    1.3.0              Assertions to validate method input/ou...
willdurand/jsonp-callback-validator v1.1.0             JSONP callback validator.
willdurand/negotiation              v2.3.1             Content Negotiation tools for PHP prov...
zendframework/zend-code             3.3.0              provides facilities to generate arbitr...
zendframework/zend-eventmanager     3.2.1              Trigger and listen to events within a ...
zircote/swagger-php                 2.0.13             Swagger-PHP - Generate interactive doc...
* Suite configuration:

```yml
class_name: ApiTester
modules:
    enabled:
        - Symfony:
            app_path: src
            environment: test
        - REST:
            url: /v1
            depends: Symfony
        - Doctrine2:
            depends: Symfony
        - \Helper\Api
#    enabled:```

**Comment by mvaljento** [comment]
@sela Did you ever find a solution to this? I'm having the same issue with my API tests in Symfony 4.1 and the latest version of Codeception.

Thanks for any help!

**Comment by sela** [comment]
I managed to use some stuff with codeception though not sure if it was for this one. Send me your code and I'll check my code at work in a few hours.

**Comment by sela** [comment]
> @sela Did you ever find a solution to this? I'm having the same issue with environment variables in my API tests in Symfony 4.1 and the latest version of Codeception.
> 
> Thanks for any help!

I managed to use some stuff with codeception though not sure if it was for this one. Send me your code and I'll check my code at work in a few hours.

**Comment by sela** [comment]
@mvaljento I managed to use some stuff with codeception though not sure if it was for this one. Send me your code and I'll check my code at work in a few hours.

**Comment by mvaljento** [comment]
@sela Thanks very much for your offer, but I just got it working. I'm not sure what I was missing but i re-created the API test suite, removed all the database related stuff for now, and the env variables seem to be loading properly..

**Comment by sschueller** [comment]
For anyone who runs into this issue. Make sure you have 

```
