### ISSUE TITLE
Extend CEST class and overwrite just one test

### ISSUE THREAD

**Issue by amirduran** [Codeception/Codeception#5019]
#### What are you trying to achieve?
Is it possible to extend CEST class and just overwrite one test from it?

For example let say I have the following code: 

```
<?php

class LoginCest
{
    public function login(ApiTester $I)
    {
        //Perform test 1
    }

    public function resetPassword(ApiTester $I)
    {
        //Perform test 2
    }

}
```

Now let say that I have the same application deployed but for another company which wants additional login fields. I would like to overwrite login method from `LoginCest` class and just overwrite `login` test. Something like this:

```
<?php

class LoginCestExtended extends LoginCest
{
    
    public function login(ApiTester $I)
    {
        //Perform test 1 but with additional fields
    }
    
}
```

Now when running `codecpt run` for a first customer/client the following two tests will be executed: `login` and `resetPassword` from class `LoginCest` class, but when I run `codecept run` for a second client again two tests should be executed but second one should be from class `LoginCestExtended`. Is this possible?

**Comment by Naktibalda** [comment]
require_once can be used in the cest file.
Another option is to use namespace for your tests and configure autoloading in composer.json

**Comment by amirduran** [comment]
Maybe I didn't explain well what is what I want to achieve.

Let's say I have two customers/clients using my application. 

**Client A** has standard application where let's say during registration process user has to give Firstname, Lastname and email.

**Client B** has standard application too but wit a registration process which is slightly changed from the application of the client A (let's say client B wants that user during registration process also enters his nickname). Also client B wants some functionality to export some CSV data which is not present in application of client A.

Idea is to have something like "core/base" tests (just standard CEST classes) which can be overwritten if any clients wants something additional (child classes that are extending core tests and just overwriting specific methods (tests) from base classes)

When deploying my applications for client A and client B respectively here is something that I want to do: 

**Test for client A:**
* Execute test that will check whether Registration process works good -> 
Let say that I've implemented `RegistrationCest` class that has multiple tests inside, for example: test1, test2, test3.
* Execute test that will check whether the login is working correctly -> This is also CEST class that has multiple tests inside.

**Test for client B:** 
* Execute test that will check whether Registration process works good (but this test should be a different one from client A because we have to check whether nickname is saved in DB) -> Good candidate for extending `RegistrationCest` where I can overwrite just for example `test1` from that class and preserve all other tests from parent class.

Here is a maybe folder structure so you have better understanding: 

/base-core-tests
-----`RegistrationCest` (there are 3 tests here: `test1, test2, test3`)
-----`LoginCest` (there are 5 tests here: `test1, test2, test3, test4, test5`)

/extended-test
-----ExtendedRegistrationCest (I overwritten `test1` in this class)
-----CsvExportCest (only one test `test1`)

Codeception should do the following steps:

1.) Are there any tests in `extended-test` folder. If yes, run all overwritten tests from child class (in this case `test1` from child class `ExtendedRegistrationCest` and all other tests from parent class in this case `test2`, `test3` from `RegistrationCest`)
2.) Are there any tests present that should be executed just for this client. In this case yes `CsvExportCest` should be executed because this functionality is available only for client A.
2.) All `base-core-tests` that are not overwritten in `extended-test` folder should be executed normally. In this case execute all 5 tests from `LoginCest` class). So login functionality is equal to all clients and core test could be executed. 

This way I would be able to overwrite any base/core test for a specific client which gives me ability not to duplicate tests for every single client and I could add new tests that would be executed only for this specific client.

What you wrote is really helpful but is there a way I don't have to explicitly call any of these test: 

For example I don't want to write: `codecept run api ExtendedLoginCest` but I want to write just `codecept run api` and that codeception executes tests in order that I wrote above?

**Comment by mlambley** [comment]
What I like about the cest class instantiation is that it's just `new $className()` with no params, no interfaces to implement, no class you need to extend. Just kept simple, clean and flexible. All of the things you've described require some sort of smarts which will restrict this simple flexibility.

Could you have separate tests? I would think that if you have two different workflows they should be separately tested. Perhaps loginClientA($I) and loginClientB($I) which will simulate the different login processes?

Your common tests can exist in a base file which is outside of your suite folder. Have something like:
```php
//suite/ClientACest.php
class ClientACest extends \My\Other\Namespace\ClientTests
{
    //Implement new / override existing tests
}

//suite/ClientBCest.php
class ClientBCest extends \My\Other\Namespace\ClientTests
{
    //Implement new / override existing tests
}

//path/to/other/folder/ClientTests.php
namespace My\Other\Namespace
class ClientTests
{
    //Common tests which are outside of the suite folder
}
```

That way, class ClientTests itself never gets run by Codeception. You just have two different cests for two different workflows which share common code.

**Comment by amirduran** [comment]
Thank you for your answers. I think I will create my own fork where I will implement small changes in [Loader](https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Test/Loader.php) class, and that should then support my scenario.
