### ISSUE TITLE
Expand makeScreenshot() functionality to make full sceen screenshot

### ISSUE THREAD

**Issue by petrisorionel** [Codeception/Codeception#5026]
#### What are you trying to achieve?

I'm trying to make a full page screenshot.

### Details

* Codeception version: 2.3
* PHP Version: 7.0
* Operating System: MAC OS
* Installation type: Composer

From what I see in takeScreenshot() function is used Chrome library to make the screenshot, it is possible to find another way to make a full page screenshot?

**Comment by NWayne** [comment]
+1

**Comment by petrisorionel** [comment]
@Naktibalda, i don’t need another way, I need (also some other people, i think) to see the full page when I make a screenshot, right now it is only a part from the page that not include the url, setting bar from the browser and other things.

**Comment by Naktibalda** [comment]
Do you actuall mean "full screen"? 
"Full page" means "everything I see when scrolling down the page" for other people.

Selenium can't do that.
It can either take screenshot of "the current viewport" which is implemented as takeScreenshot function that you are already using or a screenshot of specified html element, which isn't currently supported by facebook/php-webdriver. 

To get a shot of fullscreen you would have to use some operating system specific utility program.

**Comment by petrisorionel** [comment]
@Naktibalda sorry, full screen. I try with takeScreenshot but don't make a full screen screenshot.
My tests are running inside a Docker container and this is command that I'm using to start Selenium

`#!/bin/bash

#Start Selenium server
xvfb-run --server-args="-screen 0, 1024x768x24" java -Dwebdriver.chrome.driver=chromedriver2.40_linux -Dselenium.LOGGER.level=WARNING -jar selenium-server-standalone-3.9.1.jar \
    & export SEL_PID=$!

# Give selenium time to start up
sleep 60`

You know a way how to do that?

**Comment by Naktibalda** [comment]
no, I don't.
