### ISSUE TITLE
The phalcon app failed when running the codeception tests

### ISSUE THREAD

**Issue by Rasul999** [Codeception/Codeception#5036]
According to the instructions, he created a bootstrap phalcon-project, added it to the modules I run the code codecept run functional -d At start of functional tests there is an error:

`PHP Fatal error: Cannot declare class phpMorphy_Exception, because the name is already in use in /home/hyber/test/backend/library/library/Service/phpmorphy/src/common.php on line 35`

functional.suite.yml:

    actor: FunctionalTester
    modules:
    
    enabled:

    - Phalcon:                       
        bootstrap: 'config/bootstrap.php'
        cleanup: true
        savepoints: true
    - Asserts
    # add a framework module here
    - \Helper\Functional

config/bootstrap.php:

    error_reporting(E_ALL);

    try {

    $config = include __DIR__ . "/config.php";
    include __DIR__ . "/loader.php";
    $di = new \Phalcon\DI\FactoryDefault();
    include __DIR__ . "/services.php";

    return new \Phalcon\Mvc\Application($di);

    } catch (\Phalcon\Exception $e) {

    echo $e->getMessage();

    } catch (PDOException $e){

    echo $e->getMessage();

    }

Codeception v2.4.1
PHP 7.2.5
Ubuntu 18.04

please help!

**Comment by Naktibalda** [comment]
It wasn't an issue of Codeception.
