### ISSUE TITLE
Call to a member function resetApplication() on null

### ISSUE THREAD

**Issue by igorvolnyi** [Codeception/Codeception#5038]
#### What are you trying to achieve?
Run acceptance test: codeception run acceptance LoginCest

#### What do you get instead?
Call to a member function resetApplication() on null

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Error: Call to a member function resetApplication() on null in /var/www/nginx/my-project/vendor/codeception/base/src/Codeception/Module/Yii2.php on line 364
```
> Provide test source code if related

```php
<?php

use yii\helpers\Url;

class LoginCest
{
    public function ensureThatLoginWorks(AcceptanceTester $I)
    {
        $I->amOnPage(Url::toRoute('/site/login'));
        $I->see('Login', 'h1');

        $I->amGoingTo('try to login with correct credentials');
        $I->fillField('input[name="LoginForm[username]"]', 'admin');
        $I->fillField('input[name="LoginForm[password]"]', 'admin');
        $I->click('login-button');
        $I->wait(2); // wait for button to be clicked

        $I->expectTo('see user info');
        $I->see('Logout');
    }
}

```
### Details

* Codeception version: 2.4.2
* PHP Version: 7.2.6
* Operating System: Linux Arch x86_64
* Installation type: Composer
* List of installed packages (`composer show`)

behat/gherkin                       v4.5.1   Gherkin DSL parser for PHP 5.3
bower-asset/bootstrap               v3.3.7  
bower-asset/inputmask               3.3.11  
bower-asset/jquery                  3.2.1   
bower-asset/jquery-ui               1.12.1  
bower-asset/punycode                v1.3.2  
bower-asset/typeahead.js            v0.11.1 
bower-asset/yii2-pjax               2.0.7.1 
cebe/markdown                       1.1.2    A super fast, highly extensible markdown parser for PHP
codeception/base                    2.4.2    BDD-style testing framework
codeception/phpunit-wrapper         7.1.4    PHPUnit classes used by Codeception
codeception/specify                 0.4.6    BDD code blocks for PHPUnit and Codeception
codeception/stub                    2.0.1    Flexible Stub wrapper for PHPUnit's Mock Builder
codeception/verify                  0.3.3    BDD assertion library for PHPUnit
doctrine/instantiator               1.1.0    A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1   Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
egulias/email-validator             2.1.4    A library for validating emails against several RFCs
ezyang/htmlpurifier                 v4.10.0  Standards compliant HTML filter written in PHP
facebook/webdriver                  1.6.0    A PHP client for Selenium WebDriver
fzaninotto/faker                    v1.7.1   Faker is a PHP library that generates fake data for you.
guzzlehttp/psr7                     1.4.2    PSR-7 message implementation that also provides common utility methods
kartik-v/bootstrap-fileinput        v4.4.8   An enhanced HTML 5 file input for Bootstrap 3.x with features for file preview for many file types, multiple selection, ajax uploads, and more.
kartik-v/bootstrap-star-rating      4.0.3    A simple yet powerful JQuery star rating plugin for Bootstrap.
kartik-v/dependent-dropdown         v1.4.8   A multi level dependent dropdown JQuery plugin that allows nested dependencies.
kartik-v/yii2-krajee-base           v1.8.9   Base library and foundation components for all Yii2 Krajee extensions.
kartik-v/yii2-widget-activeform     v1.4.9   Enhanced Yii2 active-form and active-field with full bootstrap styling support (sub repo split from yii2-widgets).
kartik-v/yii2-widget-affix          v1.0.0   A scrollspy and affixed enhanced navigation to highlight page sections (sub repo split from yii2-widgets)
kartik-v/yii2-widget-alert          v1.1.1   A widget to generate alert based notifications using bootstrap-alert plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-colorinput     v1.0.3   An enhanced Yii 2 widget encapsulating the HTML 5 color input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-datepicker     v1.4.3   Enhanced Yii2 wrapper for the bootstrap datepicker plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widget-datetimepicker v1.4.4   Enhanced Yii2 wrapper for the bootstrap datetimepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-depdrop        v1.0.4   Widget that enables setting up dependent dropdowns with nested dependencies (sub repo split from yii2-widgets)
kartik-v/yii2-widget-fileinput      v1.0.6   An enhanced FileInput widget for Bootstrap 3.x with file preview, multiple selection, and more features (sub repo split from yii2-widgets)
kartik-v/yii2-widget-growl          v1.1.1   A widget to generate growl based notifications using bootstrap-growl plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-rangeinput     v1.0.1   An enhanced Yii 2 widget encapsulating the HTML 5 range input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-rating         v1.0.3   A Yii2 widget for the simple yet powerful bootstrap-star-rating plugin with fractional rating support (sub repo split from yii2-widgets)
kartik-v/yii2-widget-select2        v2.1.1   Enhanced Yii2 wrapper for the Select2 jQuery plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widget-sidenav        v1.0.0   An enhanced side navigation menu styled for bootstrap (sub repo split from yii2-widgets)
kartik-v/yii2-widget-spinner        v1.0.0   A widget to render animated CSS3 loading spinners with VML fallback for IE (sub repo split from yii2-widgets)
kartik-v/yii2-widget-switchinput    v1.3.1   A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes & radios as toggle switchinputes (sub repo split from yii2-widgets)
kartik-v/yii2-widget-timepicker     v1.0.3   Enhanced Yii2 wrapper for the bootstrap timepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-touchspin      v1.2.1   A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes & radios as toggle touchspines (sub repo split from yii2-widgets)
kartik-v/yii2-widget-typeahead      v1.0.1   Enhanced Yii2 wrapper for the Twitter Typeahead plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widgets               v3.4.0   Collection of useful widgets for Yii Framework 2.0 extending functionalities for Bootstrap
myclabs/deep-copy                   1.8.1    Create deep copies (clones) of your objects
phar-io/manifest                    1.0.1    Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                     1.0.1    Library for handling version information and constraints
phpdocumentor/reflection-common     1.0.1    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.0    With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver         0.4.0
phpspec/php-diff                    v1.1.0   A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/prophecy                    1.7.6    Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           6.0.5    Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           1.4.5    FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template           1.2.1    Simple template engine.
phpunit/php-timer                   2.0.0    Utility class for timing
phpunit/php-token-stream            3.0.0    Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     7.1.5    The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        6.1.2    Mock Object library for PHPUnit
psr/http-message                    1.0.1    Common interface for HTTP messages
sebastian/code-unit-reverse-lookup  1.0.1    Looks up which function or method a line of code belongs to
sebastian/comparator                3.0.1    Provides the functionality to compare PHP values for equality
sebastian/diff                      3.0.1    Diff implementation
sebastian/environment               3.1.0    Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  3.1.0    Provides the functionality to export PHP variables for visualization
sebastian/global-state              2.0.0    Snapshotting of global state
sebastian/object-enumerator         3.0.3    Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector          1.1.1    Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context         3.0.0    Provides functionality to recursively process PHP variables
sebastian/resource-operations       1.0.0    Provides a list of PHP built-in functions that operate on resources
sebastian/version                   2.0.1    Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer             v6.0.2   Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                 v4.1.0   Symfony BrowserKit Component
symfony/console                     v4.1.0   Symfony Console Component
symfony/css-selector                v4.1.0   Symfony CssSelector Component
symfony/dom-crawler                 v4.1.0   Symfony DomCrawler Component
symfony/event-dispatcher            v4.1.0   Symfony EventDispatcher Component
symfony/finder                      v4.1.0   Symfony Finder Component
symfony/polyfill-ctype              v1.8.0   Symfony polyfill for ctype functions
symfony/polyfill-mbstring           v1.8.0   Symfony polyfill for the Mbstring extension
symfony/process                     v4.1.0   Symfony Process Component
symfony/yaml                        v4.1.0   Symfony Yaml Component
theseer/tokenizer                   1.1.0    A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                    1.3.0    Assertions to validate method input/output with nice error messages.
yiisoft/yii2                        2.0.15.1 Yii PHP Framework Version 2
yiisoft/yii2-bootstrap              2.0.8    The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer               2.0.6    The composer plugin for Yii extension installer
yiisoft/yii2-debug                  2.0.13   The debugger extension for the Yii framework
yiisoft/yii2-faker                  2.0.4    Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                    2.0.7    The Gii extension for the Yii framework
yiisoft/yii2-jui                    2.0.7    The Jquery UI extension for the Yii framework
yiisoft/yii2-swiftmailer            2.1.1    The SwiftMailer integration for the Yii framework

* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://my-project.local:80/
            browser: firefox
        - Yii2:
            part: [orm, fixtures]
            entryScript: index-test.php
```

**Comment by vitorarantes** [comment]
Same problem here!

Codeception version: 2.4.2
PHP Version: 7.2.6
Operating System: Ubuntu 16.04
Yii version: 2.0.15.1

went back to Codeception version 2.4.0 and works just fine.

**Comment by mircloudadic** [comment]
Same problem here!

**Comment by igorvolnyi** [comment]
> but now it adds another one...
It's not added. It is another bug. It happens when you use fixtures and something is wrong with them. If you use Yii2 try to load fixtures using command line:

`./yii fixture/load [--namespace='name\space\of\your\fixtures'] <FixtureName>`

It will show you where exactly is the problem in your fixture.

**Comment by Naktibalda** [comment]
If this issue still exists, please raise a new issue at https://github.com/Codeception/module-yii2/issues
