### ISSUE TITLE
Unable to write test cases for hidden and read only elements in selenium 2 module 

### ISSUE THREAD

**Issue by aditya-** [Codeception/Codeception#504]
Dear sir ,

I am writing acceptance tests using codeception  with selenium 2 . I am almost able to write test cases all the types ... except readonly , and hiddent elements .. actually its very important from .. here i am facing mainly two issue .. please help ...

1.Unable to write test cases for elements declared as read only 

see the following code .. actually i need to fill that field .. due to read only its not filled .. i need to alter this in code .. 

<div id="time_limit" class="input-append ">
                <input class="input-medium no-margin hasDatepicker" data-format="hh:mm:ss" readonly="readonly" value="00:20" name="QuizProperty[time_limit]" id="QuizProperty_time_limit" >    
                </div>

2.Some elemnts by default hiddent ... on place of mouse (hover) those are visible like delete buttons .. etc .. after placing mouse only they are visible .. 

.hidden {
    display: none;
    visibility: hidden;
}

.onhover > ul {
    display: none;
}

Please suggest me how to write test cases for this read only and hidden elements .. Actually its very important for me 

@DavertMik  and @tiger-seo  @Ragazzo please help

**Comment by kjnanda** [comment]
codeception `moveMouseOver`  function is not working in firefox but the same works fine in chrome browser. Do anyone have any idea? Or is there any workaround possible?

**Comment by Naktibalda** [comment]
@kjnanda Please upgrade to the latest versions of Firefox, Selenium and Geckodriver.
Marionette implemented action commands just a month or so ago. (I still don't get a relationship between Marionette and Geckodriver).
