### ISSUE TITLE
Better error message when cest data providers return nothing

### ISSUE THREAD

**Issue by mlambley** [Codeception/Codeception#5042]
#### What are you trying to achieve?
If for whatever reason no data is returned by a cest data provider, say the database isn't configured correctly or I've accidentally filtered out all the data, then I'd like to be informed as such.

#### What do you get instead?
An error message which doesn't explain what happened:
```
[InjectionException] Failed to inject dependencies in instance of 'MyCest'. 
Failed to create instance of 'Codeception\Example'. Parameter 'data' must have default value.
```

There are two possibilities here. One option is to throw an exception if a data provider returns no data. I don't think this is a good idea though. It's possible for a test to refer to a data provider which returns no data, but not have a \Codeception\Example parameter, and still work. This option will break those tests.

The other option is, if we're unable to instantiate \Codeception\Example, throw an error which says something similar to:
```
Could not load example data for the test 'testSchema' in the instance of 'MyCest'. 
Data provider '_dataProvider' did not return any data.
```

```php
<?php
class MyCest
{
    /**
     * @dataProvider _dataProvider
     */
    public function testSchema(AcceptanceTester $I, \Codeception\Scenario $S, Codeception\Example $data)
    {
        //Stuff
    }

    public function _dataProvider()
    {
        return array();
    }
}
```
### Details
* Codeception version: 2.4

**Comment by eXorus** [comment]
I'm closing this issue, feel free to reopen if it is still a need.

**Comment by natsu90** [comment]
The documentation said to write `#[DataProvider('pageProvider')]` instead and I have been wondering what went wrong, what a waste of day

**Comment by Naktibalda** [comment]
@natsu90 Attributes had been introduced in Codeception 5.
