### ISSUE TITLE
Handling testing environments that use a subdomain prefix

### ISSUE THREAD

**Issue by JeramyK** [Codeception/Codeception#5047]
#### What are you trying to achieve?
A single command to run tests on all subdomains within a selected development environment that uses domain prefix for identification.

#### What do you get instead?
I can get it working by duplicating all of my tests within separate folders, but suspect there is a better way. Perhaps the ability to pass a variable from the execution command to the Cest?

### Details
I am trying to simplify my codeception testing. I have 26 subdomains and several testing environments. I have my Test Suite Configuration configured with my base-url, example.com. In each Cest I use amOnSubdomain to set the subdomain for the site, $I->amOnSubdomain(subsite); which gives me subsite.example.com

The problem I am running into is that my test environments are essentially a subdomain of each subdomain. So prod is subsite.example.com but if I want to run the tests against my Dev environment I need dev.subsite.example.com, and staging would be staging.subsite.example.com.

What I do now is create separate folders within Acceptance for production, and for each test environment. I copy each Cest file into each environment folder and modify the amOnSubdomain within each to match the environment. Each Cest is identical aside from the additional 'dev', 'test', or 'sandbox' in the subdomain for the test environments. I then can call each environment using the folder structure in the Codeception command, codecept run tests/acceptance/prod etc. This isn't the most efficient for long-term maintenance.

I know that the Environment configuration 'env:' allows you to set environment specific settings. It seems the right place to handle this, but setting the environment URL to something like test.example.com of course causes environment subdomain 'test' to be overwritten by the site subdomain when amOnSubdomain is called. I do not see another way to pass the environment subdomain through these settings. What I really need is to be able to set the environment URL to env.{{subdomain}}.example.com allowing {{subdomain}} to be replaced by the subdomain in the Cest.

Alternatively, a way to pass the environment variable from the execution command so that I can add it to the subdomain within the Cest file. I did see a PR that looked like it would meet my needs but it was rejected: https://github.com/Codeception/Codeception/pull/3978.

I am assuming that there is a way to do this that I just haven't figured out yet.

* Codeception version: 2.4.2
* PHP Version: 7.1.16
* Operating System: OSX 10.13.5
* Installation type: Composer
* Suite configuration:

actor: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - \Helper\Acceptance:
            depends: PhpBrowser
    config:
        WebDriver:
            browser: chrome
            window_size: false # disabled in ChromeDriver
            restart: false
            wait: 5
            port: 9515
            url: 'https://example.com/'
        PhpBrowser:
            url: 'https://example.com/'

**Comment by ssh6** [comment]
\\assuming url is the baseurl.com
   \\ subdomain is subdomain.baseurl.com
   \\ environment variable is dev.subdomain.baseurl.com

use the environment flag as the variable.  



Ex:

In acceptance.suite.yml, 

env:
    dev:

    test:


In your cest file, in the class definition
    const website = "subdomain";

In your test file, in the functions
change the declaration to include scenario
(AcceptanceTester $I, \Codeception\Scenario $scenario)

Then in the function itself, 

        $domain = $scenario->current('env');
        if (is_null($domain)) {
                $I->amOnSubdomain(self::website);
        } else {
                $I->amOnSubdomain($domain . "." . self::website);
        }

**Comment by JeramyK** [comment]
Ah I see, and then you should be able to run the command as:
`php vendor/bin/codecept run acceptance --env dev`
That will make `$scenario->current('env')` return 'dev' in your example, allowing you to concatenate it with your website const giving you the expected dev.subdomain.baseurl.com Nice!
