### ISSUE TITLE
Acceptance tester action seeInDatabase appears to be flaky

### ISSUE THREAD

**Issue by aricl** [Codeception/Codeception#5054]
#### What are you trying to achieve?

To check to see if at least one row in a table contains the correct column value. The row is definitely written/updated correctly because an assertion for a 200 response code for the request that results in the write/update returns true.

This seems to happen in any acceptance that is run that contains this command.

#### What do you get instead?

The command `$I->seeInDatabase()` does not output the correct result all the time. Sometimes it correctly finds that at least one row contains the correct column value. Sometimes it does not, and the test fails.

The offending line of code is:
```php
$I->seeInDatabase(
    'table',
    [
        'a_boolean_flag_column' => 0,
        'a_text_column' => 'some text',
    ]
);
```
### Details

* Codeception version: 2.4.3
* PHP Version: 5.6.36
* Operating System: Ubuntu
* Installation type: Composer

**Comment by DavertMik** [comment]
> The row is definitely written/updated correctly because an assertion for a 200 response code for the request that results in the write/update returns true.

I wouldn't take that to the bank.... 

> The command $I->seeInDatabase() does not output the correct result all the time. Sometimes it correctly finds that at least one row contains the correct column value. Sometimes it does not, and the test fails.

It appears that you have synchronization issue and that happens in acceptance tests. If you try to slow down the test (maybe by adding sleep(500)) you will probably see that tests pass. Try it. If it is so, the problem is not in Codeception )

**Comment by aricl** [comment]
> The row is definitely written/updated correctly because an assertion for a 200 response code for the request that results in the write/update returns true.

Ok, I will also add that the database table in question also has the inserted/update row in it. The 200 response is only returned after the transaction is committed to the database, so I can't see how this can be a synchronization issue. My apologies, I should have stated that in the original issue posting.

**Comment by johannesschobel** [comment]
Hey @aricl , maybe this is related to your issue? https://github.com/Codeception/Codeception/issues/5051
Problem here is, that the environment is differently created, so it writes the data - but into a "wrong" database..

**Comment by aricl** [comment]
Hi @johannesschobel, thanks for the extra info! As far as I can tell this is not the same issue. I checked the environment that test was running in, and found that it was 'test', which is the environment which I  was expecting. This means that the command 'seeInDatabase()' should be querying the corresponding database table in my 'test' environment that the whole test is using.
