### ISSUE TITLE
haveInDatabase tester method fails using sqlite database

### ISSUE THREAD

**Issue by chippyash** [Codeception/Codeception#5055]
Trying to use haveInDatabase method to insert a record for a test.

Method fails with error: 'Primary key field _ROWID_ is not set for table Products'

```bash
vendor/bin/codecept -vvv run database
Codeception PHP Testing Framework v2.4.2
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

  [Db] Connected to 
  [Db] Connected to 

Database Tests (5) ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Asserts, \Helper\Database, Db
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ ProductsTest: Products gateway can be constructed (0.01s)
✔ ProductsTest: Products gateway is centred on the products table (0.00s)
- ProductsTest: You can get a product availability indicator | #0  [Query] INSERT INTO "Products" ("Product_Code", "savailable", "srequests", "calculation_rating") VALUES (?, ?, ?, ?)
  [Parameters] ["abc",0,0,1]
E ProductsTest: You can get a product availability indicator | #0 (0.00s)
✔ ProductCodeTest: Producttype is a stringtype (0.00s)
✔ ProductCodeTest: Producttype has max fifteen characters (0.00s)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 1.56 seconds, Memory: 15.50MB

There was 1 error:

---------
1) ProductsTest: You can get a product availability indicator | #0
 Test  tests/database/Data/Db/TableGateway/ProductsTest.php:testYouCanGetAProductAvailabilityIndicator
                                                                                      
  [InvalidArgumentException] Primary key field _ROWID_ is not set for table Products  
                                                                                      
/vendor/codeception/codeception/src/Codeception/Module/Db.php:459
```
> Provide test source code if related

```php
/**
     * @dataProvider productAvailabilityProvider
     */
    public function testYouCanGetAProductAvailabilityIndicator($sAvailable, $sRequests, $requirement, $result)
    {
        $this->tester->haveInDatabase(
            'Products',
            [
                'Product_Code' => 'abc',
                'savailable' => $sAvailable,
                'srequests' => $sRequests,
                'calculation_rating' => 1
            ]
        );
        $this->tester->haveInDatabase('product_rating', ['rating' => 1, 'requirement' => $requirement]);

        $this->assertEquals($result, $this->sut->getAvailability(new ProductCode('abc')));
    }
```

I've debugged into `vendor/codeception/codeception/src/Codeception/Module/Db.php` and can see that the line:
`$primaryKey = $this->driver->getPrimaryKey($table);` at L449 is returning '_ROWID_' instead of the declared 'id' primary key column as declared in the table create statement.

```sql
create table Products
(
  id integer primary key,
  Product_Code varchar(15) default '' not null,
  savailable int default '0' not null,
  srequests int default '0' not null,
  calculation_rating varchar(3) default 'A' not null,
  constraint Product_Code unique (Product_Code)
);
```

### Details
Codeception version 2.4.2
PHP 5.6.31 
Linux Mint 18.01
Installation type: Composer
* List of installed packages (`composer show`)
aws/aws-sdk-php                     3.61.7  AWS SDK for PHP - Use Amazon Web Services in your PHP project
behat/gherkin                       v4.5.1  Gherkin DSL parser for PHP 5.3
chippyash/assembly-builder          2.0.0   Lightweight functional assembly builder pattern with Scala like For Comprehension
chippyash/builderpattern            3.0.1   Builder Pattern
chippyash/identity                  1.0.4   Class Identity Management
chippyash/monad                     2.0.1   Functional programming Monad support
chippyash/record-status             1.0.2   Class Status Management
chippyash/slim-symfony-dic          3.0.0   Symfony 2 DIC integration for the Slim Framework 3
chippyash/strong-type               5.0.0   Strong type support. For when you absolutely want to know what you are getting
chippyash/validation                2.0.0   comprehensive function based validation routines
chippyash/zend-acl-xml-builder      3.0.0   Configuration of Zend 2 Acl instances using XML
codeception/codeception             2.4.2   BDD-style testing framework
codeception/phpunit-wrapper         6.0.9   PHPUnit classes used by Codeception
codeception/stub                    2.0.1   Flexible Stub wrapper for PHPUnit's Mock Builder
container-interop/container-interop 1.2.0   Promoting the interoperability of container objects (DIC, SL, etc.)
doctrine/annotations                v1.4.0  Docblock Annotations Parser
doctrine/cache                      v1.6.2  Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.4.0  Collections Abstraction library
doctrine/common                     v2.7.3  Common Library for Doctrine projects
doctrine/dbal                       v2.5.13 Database Abstraction Layer
doctrine/inflector                  v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 v1.5.0  Database Schema migrations using Doctrine DBAL
facebook/webdriver                  1.6.0   A PHP client for Selenium WebDriver
freetimers/core-lib-acl             0.0.30  ACL library classes
freetimers/core-lib-auth            0.1.10  Authentication library classes
freetimers/core-lib-aws             0.0.9   Freetimers integration to AWS SDK
freetimers/core-lib-mvc             0.0.47  MVC library classes
freetimers/core-lib-user            0.0.8   User Identity library classes
freetimers/core-lib-version         0.0.2   Application versioning
guzzlehttp/guzzle                   6.3.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises                 v1.3.1  Guzzle promises library
guzzlehttp/psr7                     1.4.2   PSR-7 message implementation that also provides common utility methods
mikey179/vfsStream                  v1.6.5  Virtual file system to mock the real file system in unit tests.
monolog/monolog                     1.23.0  Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php              2.4.0   Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                   1.7.0   Create deep copies (clones) of your objects
myclabs/php-enum                    1.6.1   PHP Enum implementation
nikic/fast-route                    v1.3.0  Fast request router for PHP
ocramius/proxy-manager              1.0.2   A library providing utilities to generate, instantiate and generally operate with Object Proxies
paragonie/random_compat             v2.0.15 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common     1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   3.3.2   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver         0.4.0  
phpspec/prophecy                    1.7.6   Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           4.0.8   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           1.4.5   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template           1.2.1   Simple template engine.
phpunit/php-timer                   1.0.9   Utility class for timing
phpunit/php-token-stream            1.4.12  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     5.7.27  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        3.4.4   Mock Object library for PHPUnit
pimple/pimple                       v3.2.3  Pimple, a simple Dependency Injection Container
psr/cache                           1.0.1   Common interface for caching libraries
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/http-message                    1.0.1   Common interface for HTTP messages
psr/log                             1.0.2   Common interface for logging libraries
psr/simple-cache                    1.0.1   Common interfaces for simple caching
sebastian/code-unit-reverse-lookup  1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator                1.2.4   Provides the functionality to compare PHP values for equality
sebastian/diff                      1.4.3   Diff implementation
sebastian/environment               2.0.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  2.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state              1.1.1   Snapshotting of global state
sebastian/object-enumerator         2.0.1   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context         2.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations       1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                   2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
slim/slim                           3.10.0  Slim is a PHP micro framework that helps you quickly write simple yet powerful web applications and APIs
slim/twig-view                      1.2.0   Slim Framework view helper built on top of the Twig templating component
symfony/browser-kit                 v3.4.11 Symfony BrowserKit Component
symfony/config                      v2.8.41 Symfony Config Component
symfony/console                     v2.8.41 Symfony Console Component
symfony/css-selector                v3.4.11 Symfony CssSelector Component
symfony/debug                       v3.0.9  Symfony Debug Component
symfony/dependency-injection        v2.8.41 Symfony DependencyInjection Component
symfony/dom-crawler                 v3.4.11 Symfony DomCrawler Component
symfony/event-dispatcher            v3.2.14 Symfony EventDispatcher Component
symfony/expression-language         v2.8.41 Symfony ExpressionLanguage Component
symfony/filesystem                  v3.0.9  Symfony Filesystem Component
symfony/finder                      v3.4.11 Symfony Finder Component
symfony/polyfill-ctype              v1.8.0  Symfony polyfill for ctype functions
symfony/polyfill-mbstring           v1.8.0  Symfony polyfill for the Mbstring extension
symfony/process                     v3.4.11 Symfony Process Component
symfony/yaml                        v2.8.34 Symfony Yaml Component
true/punycode                       v2.1.1  A Bootstring encoding of Unicode for Internationalized Domain Names in Applications (IDNA)
twig/twig                           v1.35.3 Twig, the flexible, fast, and secure template language for PHP
vlucas/phpdotenv                    v2.4.0  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                    1.3.0   Assertions to validate method input/output with nice error messages.
zendframework/zend-authentication   2.6.0   provides an API for authentication and includes concrete authentication adapters for common use case scenarios
zendframework/zend-cache            2.8.2   Caching implementation with a variety of storage options, as well as codified caching strategies for callbacks, classes, and output
zendframework/zend-code             2.6.3   provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-config           3.2.0   provides a nested object property based user interface for accessing this configuration data within application code
zendframework/zend-crypt            3.2.1  
zendframework/zend-db               2.9.3   Database abstraction layer, SQL abstraction, result set abstraction, and RowDataGateway and TableDataGateway implementations
zendframework/zend-escaper          2.6.0   Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
zendframework/zend-eventmanager     3.2.1   Trigger and listen to events within a PHP application
zendframework/zend-filter           2.8.0   provides a set of commonly needed data filters
zendframework/zend-http             2.8.0   Provides an easy interface for performing Hyper-Text Transfer Protocol (HTTP) requests
zendframework/zend-i18n             2.9.0   Provide translations for your application, and filter and validate internationalized values
zendframework/zend-json             3.1.0   provides convenience methods for serializing native PHP to JSON and decoding JSON to native PHP
zendframework/zend-loader           2.6.0   Autoloading and plugin loading strategies
zendframework/zend-mail             2.10.0  Provides generalized functionality to compose and send both text and MIME-compliant multipart e-mail messages
zendframework/zend-math             3.1.0   Create cryptographically secure pseudo-random numbers, and manage big integers
zendframework/zend-mime             2.7.1   Create and parse MIME messages and parts
zendframework/zend-permissions-acl  2.6.1   Provides a lightweight and flexible access control list (ACL) implementation for privileges management
zendframework/zend-serializer       2.9.0   provides an adapter based interface to simply generate storable representation of PHP types by different facilities, and recover
zendframework/zend-servicemanager   3.3.2   Factory-Driven Dependency Injection Container
zendframework/zend-session          2.8.5   manage and preserve session data, a logical complement of cookie data, across multiple page requests by the same client
zendframework/zend-stdlib           3.2.0   SPL extensions, array utilities, error handlers, and more
zendframework/zend-uri              2.6.1   A component that aids in manipulating and validating » Uniform Resource Identifiers (URIs)
zendframework/zend-validator        2.10.2  provides a set of commonly needed validators

* Suite configuration:

```yml
actor: DatabaseTester
modules:
  enabled:
    - Asserts
    - \Helper\Database
    - Db:
  config:
    Db:
      dbtype: PDO_Sqlite
      dbfile: tests/_spool/test.sqlite
      dsn: 'sqlite:tests/_spool/test.sqlite'
      user: ''
      password: ''
      dump: 'tests/_data/unittestdb.sql'
      populate: true
      cleanup: true
```

**Comment by Naktibalda** [comment]
I wrote a long post about why this is such an odd issue, and then I looked at Db module and realized that it supresses PDOExceptions on insert:
https://github.com/Codeception/Codeception/blob/2.4.2/src/Codeception/Module/Db.php#L441

Because $lastInsertId is 0, wrong branch of addInsertedRow is executed and produces misleading exception.

Check the message of PDOException and see if it helps to solve your issue.
Please share it with us.

Suppression of PDOException was implemented 4 years ago: https://github.com/Codeception/Codeception/pull/1406
I think that it would be useful to log exception message using codecept_debug() function, so it would appear in debug output.

More information about ROWID and how I came up with this conclusion below.

------------------------

I tried to reproduce your issue, but all my tests passed.

Test code: https://github.com/Codeception/Codeception/commit/ac5d7661b36e7a1eed94446b27f13d9339c559a5
Build results: https://travis-ci.org/Codeception/Codeception/jobs/400155146#L2020

ROWID is a property that most of sqlite tables have: https://www.sqlite.org/lang_createtable.html#rowid

Your error ('Primary key field ROWID is not set for table Products') is thrown in the [branch of code](https://github.com/Codeception/Codeception/blob/2.4.2/src/Codeception/Module/Db.php#L455-L463) which is executed only when the table has a composite primary key or lastInsertId() method returned 0 after insert.
Composite primary key theory can be eliminated for multiple reasons:
a) There is no such key in your table,
b) When `_ROWID_` is returned, it is the only element of array - https://github.com/Codeception/Codeception/blob/2.4.2/src/Codeception/Lib/Driver/Sqlite.php#L57

So the question is how did you manage to make lastInsertId to return 0 after insert to Products table?

**Comment by chippyash** [comment]
Ok - tried all the debug stuff, that didn't give anything.  No PDO exception being thrown.

However, when I run the insert statement manually I see

[SQLITE_CONSTRAINT_NOTNULL]  A NOT NULL constraint failed (NOT NULL constraint failed:

This is for another column in table. Codecept is obviously not catching such errors and reporting them

If you add another column say:
'''sql
prod_code varchar(15) not null,
'''
which is not being referenced in the insert statement and rerun tests, I surmise they will fail with the no __ROWID__ message, and probably no error output to show what really went wrong.

Thanks for your help, at least I know what to work around now.

**Comment by Naktibalda** [comment]
PDO exception message is printed in debug output since this change: https://github.com/Codeception/Codeception/pull/5198/commits/288c714b18d7a36b49300ba75a7e60bf2b1125a4
