### ISSUE TITLE
php-webdriver methods needs to use in Codeception Acceptance testing

### ISSUE THREAD

**Issue by aditya-** [Codeception/Codeception#506]
Dear sir

I am writing acceptance  test cases in codeception using selenium2 module ..

i seen this module: 

https://github.com/facebook/php-webdriver

most of the methods are useful to me ..    public function maximize() ..etc
i want to use these methods in my test cases alogn with codeception ..

How to include these files and 
How to use this methos in codeception test cases 

right now i included all class files .. but still i am unable to access the methods .. how to access these methods ..

**Comment by adneneBen** [comment]
Dear people
I'm new in codeception and i wrote a test for a drag and drop.
$I->dragAndDrop('//*[@id="treeContentSource"]/div[1]', '//*[@id="treeContentDestination"]');
the problem is that sometimes the test passes and sometimes it fails.
have you any idea about it ?
thanks

**Comment by jeremykid** [comment]
Dear
I want to test a table which tbody use name="ui-sortable".
I have tried $I->dragAndDrop('//*[@id="aq_options_table"]/tbody/tr[1]', '//*[@id="aq_options_table"]/tbody/tr[3]'); 
However it is failed. Does codeception has other ways to test?
