### ISSUE TITLE
Store dynamic variables between Cest classes

### ISSUE THREAD

**Issue by Nedreow** [Codeception/Codeception#5067]
I am trying to write a large acceptance tes, divided into multiple Cest classes to keep things organised. The problem is that the acceptance test requires the account created in the create account part of the test.

Is there a way to store the dynamically generated details (e-mail, password and username) between the classes and reuse them?

**Comment by DavertMik** [comment]
The simplest way would be to use public static variables of some class...
Probably a helper class can be a thing here
