### ISSUE TITLE
Support for Other Browsers

### ISSUE THREAD

**Issue by jheyjheyjhey** [Codeception/Codeception#5071]
I just want to clarify the status for the following browsers: 

* Firefox
* Internet Explorer
* Microsoft Edge

It seems that Chrome is the only browser capable of running tests without any problem.

Thanks.

**Comment by sasha-ch** [comment]
+1 to question.

**Comment by Naktibalda** [comment]
Codeception does not support or not support browsers directly, browser integration is implemented by Selenium.

Outdated status page: https://www.seleniumhq.org/about/platforms.jsp#browsers
Links to various browser drivers: https://www.seleniumhq.org/projects/webdriver/
