### ISSUE TITLE
docker 'latest' tag is not up to date

### ISSUE THREAD

**Issue by webward09** [Codeception/Codeception#5080]
#### What are you trying to achieve?
Use the latest docker container, 2.4.4

#### What do you get instead?
codeception/codeception:latest gives me codeception 2.3.9

**Comment by MindTooth** [comment]
Belive this still holds true.  Latest is 3.1.2 released 14 days ago, and last image is built two months age.

**Comment by Naktibalda** [comment]
Duplicate of #5728
