### ISSUE TITLE
file upload tests with Lumen module

### ISSUE THREAD

**Issue by retnek** [Codeception/Codeception#5081]
#### What are you trying to achieve?

I want to send a file to my endpoint in a functional tests through REST module (depends to Lumen).

#### What do you get instead?

I've got an unexpected validation error (Lumen's common file upload validation error)

```php
// in the target controller method
$this->validate($request, [
    'title' => 'required',
    // this file upload validation will be failed
    'list' => 'required|mimes:csv,txt'
]);
```

```php
$I->sendPOST('/any/endpoint', ['title' => 'anystring'], [
    'list' => new \Illuminate\Http\UploadedFile(
        codecept_data_dir('file.csv'),
        'file.csv',
        'text/csv',
        filesize(codecept_data_dir('file.csv')),
        UPLOAD_ERR_OK,
        true
    )
]);
// it will be 422 instead of 200
$I->seeResponseCodeIs(200);
```

### Details

* Codeception version: 2.4.4
* PHP Version: 7.1.5
* Operating System: Mac OS
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - Lumen
        - REST:
            depends: Lumen
        - Filesystem
        - Asserts
```

I've sucessfully investigate this issue. The Codeception\Lib\Connector\Lumen does not contain that functions which are Codeception\Lib\Connector\Laravel5 has, which are required to sucessfully validate file uploads without HTTP. If I copy `filterFiles` and `convertToTestFiles` functions from Laravel5 connector into Lumen, the test will be success.

**Comment by Naktibalda** [comment]
> If I copy filterFiles and convertToTestFiles functions from Laravel5 connector into Lumen, the test will be success.

Please make a pull request.
