### ISSUE TITLE
Dry-run does not use memory limit from codeception.yml

### ISSUE THREAD

**Issue by JGladykowski-modus** [Codeception/Codeception#5090]
We use dry-run, to detect any fatal errors in code, before actual testrun.

When running dry run in docker container:
`docker-compose run --rm codecept dry-run acceptance`

we will hit memory limit 128M 

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 69632 bytes)`

But in codeception.yml memory limit is set to 1024M and when running tests (real run, not dry), `print_r(ini_get('memory_limit'));` report indeed 1024 , while in dry run 128M.

_Codeception PHP Testing Framework v2.3.9
Powered by PHPUnit 6.5.7_ 

Current workaround:
In first test we added: `ini_set('memory_limit','1024M');`

**Comment by Naktibalda** [comment]
It has nothing to do with docker.

`dry-run` command is completely independent of `run` command and does not support majority of options.

`memory_limit` option is set by Codecept::run method: https://github.com/Codeception/Codeception/blob/2.4.4/src/Codeception/Codecept.php#L145-L148

`run` command executes `Codecept::run`: https://github.com/Codeception/Codeception/blob/2.4.4/src/Codeception/Command/Run.php#L352-L355
`dry-run` does something completely different: https://github.com/Codeception/Codeception/blob/2.4.4/src/Codeception/Command/DryRun.php#L76-L91
