### ISSUE TITLE
Docs: change domain example in Coverage page

### ISSUE THREAD

**Issue by szpakucjusz** [Codeception/Codeception#5099]
Hello, I couldn't find contact so I write here.
In this link:
https://codeception.com/docs/11-Codecoverage
are examples for .dev domain:
"...note: we can’t have multiple c3_url on same host difference only by port. Please, use alias of domain (i.e.  frontend.dev:8000,backend.dev:8080) instead...."
I suggest to change them to another because .dev domain in chrome browser are currently "blocked" and it can be confused for new users. 
https://medium.engineering/use-a-dev-domain-not-anymore-95219778e6fd

**Comment by Naktibalda** [comment]
@szpakucjusz You can update https://github.com/Codeception/Codeception/blob/2.4/docs/11-Codecoverage.md yourself and make a pull request.

**Comment by szpakucjusz** [comment]
Ok, I will try.
