### ISSUE TITLE
"Undefinied offset" error when generating code coverage

### ISSUE THREAD

**Issue by mikolajzieba** [Codeception/Codeception#5100]
#### What are you trying to achieve?
Run tests with code coverage generation

#### What do you get instead?
```bash
Remote CodeCoverage reports are not printed to console


In File.php line 285:
                         
  Undefined offset: 573  
                         
```
#### How to reproduce it
I have a test file "573Cept.php" in my test suite. When I changed it name to Ticket573Cept.php, codecoverage has generated without error.

### Details

* Codeception version: 2.4.0
* PHP Version: 7.1.3
* Operating System: Docker Linux
* Installation type: Composer

**Comment by Naktibalda** [comment]
It is an issue of php-code-coverage,
I guess that the error happened in this line: https://github.com/sebastianbergmann/php-code-coverage/blob/6.0.7/src/Report/Html/Renderer/File.php#L285
```php
if ($lineCss == 'covered-by-large-tests' && $testData[$test]['size'] == 'medium') {
```

`$testData[$test]` is used in 4 places in that file.

Workaround is obvious, so it is very unlikely that somebody will fix this issue.
