### ISSUE TITLE
looping through DOM 

### ISSUE THREAD

**Issue by Roobix13** [Codeception/Codeception#5106]
I want to close some divs while codepcetion sees them in DOM.

The code will explain it better.
```
    $I->wantTo('Remove the information notices');
    $divToClose = '.mod-notification.auto-init';
    $divCloseButton = '.mod-notification__close';

    do{
        $I->click($divCloseButton);
    }while($I->seeElementInDOM($divToClose));
```

Problem is, there are 2 divs that need to be closed, while it only closes one.

It kind of ignores the loop. Here is the output.

>  Scenario --
>  I click ".mod-notification__close"
>  I see element in dom ".mod-notification.auto-init"
>  PASSED

And i can confirm that in the Browser it only removes one div. Not two.

**Comment by freiondrej** [comment]
Hello @Roobix13,

this is most probably caused by the fact that `$I->seeElementInDOM()` doesn't return a boolean value, it performs an assertion instead. So while it looks to be true (I see element in dom ".mod-notification.auto-init"), it doesn't mean it returns `true` so the `do {}` block is only executed once.

**Comment by Roobix13** [comment]
@freiondrej  Yes i did notice that after a while.
here is how i solved it, if anyone is interested.

```
        $I->wantTo('Remove the information notices');

        $counterButton = 1;

        $arrayProducts = $I->grabMultiple(' .mod-headline-h1.mod-headline-h1--booking .mod-notification');
        $sumProducts = count($arrayProducts);

        $closeButtonClass = 'mod-notification__close';

        do{
            $closeButton = '/html/body/div/main/div/div[1]/div['.$counterButton.']/button';

            $I->click($closeButton);
            $counterButton++;
        } while($counterButton <= $sumProducts);

        $I->dontSeeElementInDOM($closeButtonClass);
```
