### ISSUE TITLE
How to read background request in selenium with codeception

### ISSUE THREAD

**Issue by karolitgrupa** [Codeception/Codeception#5112]
I have problem with selenium and codeception (PHP). 
I need tool or possibility in java script, which can read ajax requests which are send on the background of my web application which I testing and I want to redirect this request to other application endpoint, where i can save this to database by my php controller. 
I can't change application code, i must use codeception with selenium only .
Until then, I have not found any useful solution

Maybe you knows any possibilities to resolve this problem

**Comment by Naktibalda** [comment]
Codeception and Selenium can't do this.
