### ISSUE TITLE
Implementing 'seeFullUrlEquals' as Helper

### ISSUE THREAD

**Issue by Roobix13** [Codeception/Codeception#5115]
I have a class in Helper called Url

which has the following.

```
namespace Helper;

class Url 
{
    public function seeFullUrlEquals($expected)
    {
        $actual = $this->getModule('WebDriver')->webDriver->getCurrentURL();
        $this->assertEquals($expected, $actual);
    }
    
}
```

Taken From

https://github.com/Codeception/Codeception/issues/3558

Issues:

It doesn't find find `$this->getModule `or `$this->assertEquals`.

If i extend the class to Unit it does find hem.

Which Leads me to my  second Issue.

While the first Issuse is solved, now it wont find -`>webDriver->`

> Field 'webDriver' not found in \Codeception\Module

At this point my newbie knobelnde stops. So i'm here. 

EDIT extending to ` Module\CodeHelper` does Solver the problem.

Running 

$url = new Url();
$url->seeFullUrlEquals('https://some-website.com/foo/bar');

I get this output.

> FATAL ERROR. TESTS NOT FINISHED.
> Class 'Codeception\Module\CodeHelper' not found

**Comment by Roobix13** [comment]
Solved. 

$url = $I->grabFromCurrentUrl('~(\d+)~');

**Comment by Naktibalda** [comment]
Helper class must extend `\Codeception\Module` as documented in `https://codeception.com/docs/06-ModulesAndHelpers#Helpers`

**Comment by Roobix13** [comment]
```
class Url extends \Codeception\Module
{

    public function seeFullUrlEquals($expected)
    {
        $actual = $this->getModule('WebDriver')->webDriver->getCurrentURL();
        $this->assertEquals($expected, $actual);
    }

}
```

Same error 

> Field 'webDriver' not found in \Codeception\Module

**Comment by Naktibalda** [comment]
Don't instantiante helpers, enable them in suite configuration as documented.

**Comment by Roobix13** [comment]
Thank you a lot.
