### ISSUE TITLE
PHP7.2 POST incorrect (non existent) when having duplicate input name element

### ISSUE THREAD

**Issue by Michal-sk** [Codeception/Codeception#5119]
#### What are you trying to achieve?
submit a form with two same name inputs.
```
<form id="form" action="/index.php" method="post">
<input type="text" id="originator" class="alpha form-control" name="form[origin]" value="thisshouldbeinpost" placeholder="Afzender" maxLength="18">
<select id="originator" name="form[origin]" disabled>
<option value="one">one</option>
<option value="two">two</option>
<option value="tree">tree</option>
</select>
<input type="submit">
</form>
```

#### What do you get instead?
Codeception does not seem to submit the `form[origin]` value. I use xdebug and see in the `POST` request made by codeception that the `POST` does not containt the form[origin].

When i remove the second `disabled` select element. I do get the value. So it seems that because the second `<select>` element is there and is disabled. There is nothing being posted.

**This does work in PHP7.0. In PHP7.0 this tests did not fail and worked. But we are trying to migrate to PHP7.2. And on PHP7.2 this fails and the behaviour described above happens.**

### Details

* Codeception version: 2.4.5
* PHP Version: PHP 7.2.7
* Operating System: Macos
* Installation type: Composer

**Comment by Naktibalda** [comment]
Which module do you use in your tests?

**Comment by Michal-sk** [comment]
PhpBrowser and Db

**Comment by Naktibalda** [comment]
Probably it is a difference between symfony/browser-kit 3.4 and 4.1.

**Comment by Michal-sk** [comment]
Same happens when i downgrade to: Codeception 2.3.9

Worked with PHP7.0, does not with PHP7.2

**Comment by Michal-sk** [comment]
I think this is related to `symfony/dom-crawler` `Form.php`. Thats the component extracting the fields it seems

**Comment by Michal-sk** [comment]
/Users/michal/projects/frontend/dashboard/vendor/symfony/dom-crawler/Form.php:465

Which reverse to https://github.com/symfony/symfony/issues/11689. This does look like a similair issue. investigating

**Comment by Naktibalda** [comment]
This is an issue of `symfony/dom-crawler`
@Michal-sk You raised pull request to `symfony/dom-crawler` repo, which was closed automatically.
But you never raised pull request to `symfony/symfony` as suggested by the bot.
