### ISSUE TITLE
$I->fillField with characters ^ failed

### ISSUE THREAD

**Issue by hive-4-apps** [Codeception/Codeception#5121]
#### What are you trying to achieve?
I´m using wp-browser project and I´m trying to test a log in function.

    `$member_1_password = $I->executeJS('return jQuery("#pass1-text").val()');
     ...
    $this->goToSignInPage( $I );
    $I->fillField("wgs_f_email", $this->members[0]['email']);
    $I->fillField("wgs_f_password", $member_1_password );
    $I->scrollTo("#btn_submit");
    $I->click("Sign in");
    $I->wait(2);        
    $I->see("You are logged in. You can now access all the contents.");`

It works except when the password contains the char **^**, that works manually but not inside this test.  It seems to remove this char so the test is wrong. I detected this with the function **debug_log** in wordpress to display the password insertion.

#### What do you get instead?
The password with any chars should work with `$I->fillField()`.

### Details

* Codeception version: 2.4.0
* PHP Version: 7.0.29
* Operating System: Window10/Chrome 
* Installation type: WP-Browser Composer

**Comment by Naktibalda** [comment]
It is probably an issue of chromedriver - it has many of issues with sendKeys function which is used by Codeception's fillField.

https://bugs.chromium.org/p/chromedriver/issues/list?can=1&q=sendKeys&colspec=ID+Status+Pri+Owner+Summary&cells=ids

**Comment by DavertMik** [comment]
If you have issues entering such values via fillField using ChromeDriver, use jQuery instead to populate field value. This is not an elegant solution but it will work
