### ISSUE TITLE
Webdriver module: seeInCurrentUrl($uri), seeCurrentUrlEquals($uri), seeCurrentUrlMatches($uri), dontSeeInCurrentUrl($uri), dontSeeCurrentUrlEquals($uri) and dontSeeCurrentUrlMatches($uri) use URI instead of URL

### ISSUE THREAD

**Issue by ivantion** [Codeception/Codeception#5122]
#### What are you trying to achieve?
There is an element on the page that I am testing that opens a new tab with another subdomain. I want to verify that the correct URL was opened in the new tab.

#### What do you get instead?
Because the method seeCurrentUrlEquals uses function _currentUri to do the assertion, I get no match. I resorted to using seeLink instead for now, but it is far from ideal.

> Provide console output if related. Use `-vvv` mode for more details.
```bash
Failed asserting that two strings are equal.
```
> Provide test source code if related
```php
$I->amPage("http://google.com");
$I->click("Contact support");
// support.google.com opens in a new tab
$I->switchToNextTab();
// curent URI is "/"
$I->seeCurrentUrlEquals("support.google.com");
```
#### Proposed solution
Add function _getCurrentUrl() that does not strip the domain from the `return` like _getCurrentUri() does:
```php
    /**
     * Url of currently opened page.
     * @return string
     * @api
     * @throws ModuleException
     */
    public function _getCurrentUrl()
    {
        $url = $this->webDriver->getCurrentURL();
        if ($url == 'about:blank' || strpos($url, 'data:') === 0) {
            throw new ModuleException($this, 'Current url is blank, no page was opened');
        }
        return $url;
    }
```
and update seeInCurrentUrl($uri), seeCurrentUrlEquals($uri), seeCurrentUrlMatches($uri), dontSeeInCurrentUrl($uri), dontSeeCurrentUrlEquals($uri) and dontSeeCurrentUrlMatches($uri)

**Comment by DavertMik** [comment]
Yeah, you are right. It's using URI because we are bound to the domain set in the configuration.
So for your specific case, I'd recommend creating a custom helper method that uses WebDriver API to check the subdomain. It's not that complicated.
