### ISSUE TITLE
Building _generated/* on test start

### ISSUE THREAD

**Issue by matjanis** [Codeception/Codeception#5129]
Hey,
is there a possibility to turn off automatic build (I mean files in _generated) on test start? 
I want to run build manually on every repository update, not on every test start.
Thanks ;)

**Comment by Naktibalda** [comment]
Use undocumented option `--no-rebuild`

**Comment by Naktibalda** [comment]
I think that it is the only one, I added it to documentation in linked pull request.

You can double check by comparing https://github.com/Codeception/Codeception/blob/2.4.5/src/Codeception/Command/Run.php#L122-L203 to https://github.com/Codeception/Codeception/blob/2.4.5/src/Codeception/Command/Run.php#L58-L87
