### ISSUE TITLE
Insert in database without quotes (SQL keyword)

### ISSUE THREAD

**Issue by vitoo** [Codeception/Codeception#5162]
Hi

how can i insert in database without quote

example with oracle :  

` $I->haveInDatabase('mytable',  ['mydate' => 'sysdate' ] );
`

Give me the query :

`insert into mytable (mydate) values ('sysdate') 
`
Which lead to an error 

the correct query is without quote

`insert into mytable (mydate) values (sysdate)
`

Thanks for your help

**Comment by Naktibalda** [comment]
`haveInDatabase` can't be used for executing raw queries.
If you really need it you will have to implement a custom [helper method](https://codeception.com/docs/06-ModulesAndHelpers#Helpers) for that.
```php
function executeQuery($query, $parameters = null)
{
    $this->getModule('Db')->driver->executeQuery($query, $parameters);
}
```

**Comment by vitoo** [comment]
Yes i've finally used  this helper https://gist.github.com/agarzon/686e477949311ae215ce
