### ISSUE TITLE
Public functions missing from AcceptanceTesterActions.php

### ISSUE THREAD

**Issue by axeaxel** [Codeception/Codeception#5167]
#### What are you trying to achieve?
I am trying to use waitForText as I am using amOnPage from the AcceptanceTesterActions.php

It happens that the AcceptanceTesterActions has some missing public functions , all that have the wait in use and some others also.

#### What do you get instead?
I have the following error;
 [RuntimeException] Call to undefined method AcceptanceTester::waitForText

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# [RuntimeException] Call to undefined method AcceptanceTester::waitForText
```
> Provide test source code if related

```php
$I = new AcceptanceTester($scenario);
$I->wantTo('Login and check functionality');

//Login
$I->amOnPage('/user/account/login');
$I->waitForText('login');
```
### Details

* Codeception version: 2.4.6
* PHP Version: 7.2.4
* Operating System: Windows
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
behat/gherkin                      v4.5.1 Gherkin DSL parser for PHP 5.3
doctrine/instantiator              1.1.0  A small, lightweight utility to instantiate objects in PHP without invok...
facebook/webdriver                 1.6.0  A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.3  Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1 Guzzle promises library
guzzlehttp/psr7                    1.4.2  PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.8.1  Create deep copies (clones) of your objects
phar-io/manifest                   1.0.3  Component for reading phar.io manifest information from a PHP Archive (P...
phar-io/version                    2.0.1  Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1  Common reflection classes used by phpdocumentor to reflect the code stru...
phpdocumentor/reflection-docblock  4.3.0  With this component, a library can provide support for annotations via D...
phpdocumentor/type-resolver        0.4.0
phpspec/prophecy                   1.8.0  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          6.0.7  Library that provides collection, processing, and rendering functionalit...
phpunit/php-file-iterator          2.0.1  FilterIterator implementation that filters files based on a list of suff...
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  2.0.0  Utility class for timing
phpunit/php-token-stream           3.0.0  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.3.5  The PHP Unit Testing framework.
psr/http-message                   1.0.1  Common interface for HTTP messages
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2  Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.1  Diff implementation
sebastian/environment              3.1.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0  Snapshotting of global state
sebastian/object-enumerator        3.0.3  Traverses array structures and object graphs to enumerate all referenced...
sebastian/object-reflector         1.1.1  Allows reflection of object attributes, including inherited and non-publ...
sebastian/recursion-context        3.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-hosted PHP pr...
symfony/browser-kit                v4.1.4 Symfony BrowserKit Component
symfony/console                    v4.1.4 Symfony Console Component
symfony/css-selector               v4.1.4 Symfony CssSelector Component
symfony/dom-crawler                v4.1.4 Symfony DomCrawler Component
symfony/event-dispatcher           v4.1.4 Symfony EventDispatcher Component
symfony/finder                     v4.1.4 Symfony Finder Component
symfony/polyfill-ctype             v1.9.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.9.0 Symfony polyfill for the Mbstring extension
symfony/process                    v4.1.4 Symfony Process Component
symfony/yaml                       v4.1.4 Symfony Yaml Component
theseer/tokenizer                  1.1.0  A small library for converting tokenized PHP source code into XML and po...
webmozart/assert                   1.3.0  Assertions to validate method input/output with nice error messages.

* Suite configuration: 

```yml
# actor: Tester
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
    - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
coverage:
    enabled: true
```

**Comment by Naktibalda** [comment]
Please provide content of acceptance.suite.yml file.

**Comment by axeaxel** [comment]
Thank you for reply:
Here is my acceptance.suite.yml

class_name: AcceptanceTester
modules:
  enabled:
  - Helper\Acceptance
  - PhpBrowser:
      url: 'http://secureportal/'
      browser: firefox

**Comment by Naktibalda** [comment]
`PhpBrowser` module has no such method, `waitForText` exists in `WebDriver` module only.

**Comment by axeaxel** [comment]
Thank you, that was it. Now I have another issue but it's different. Thank you one more time!
