### ISSUE TITLE
Trying to fill a redactor-editor redactor-placeholder in my acceptance test

### ISSUE THREAD

**Issue by axeaxel** [Codeception/Codeception#5169]
#### What are you trying to achieve?

I am trying to fill a textarea for a message.

The field look like this:

![image](https://user-images.githubusercontent.com/43213449/45539823-b58a8680-b802-11e8-8669-9e42b52d5995.png)

I tried with fillField but it does not work.

What is the best way to fill this textarea?

**Comment by axeaxel** [comment]
The actual part where it needs the text I think is between <p></p> in the redactor part.

**Comment by Naktibalda** [comment]
What error do you get when you use fillField?
And please show your fillField line of test code.

**Comment by axeaxel** [comment]
Sorry for that, so I have:

`$I->fillField('//*[@id="message-body"]','This is a test');`

and I get this:

 [Facebook\WebDriver\Exception\UnrecognizedExceptionException] Element \<textarea id="message-body" class="ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-minlength" name="message"> could not be scrolled into view

**Comment by Naktibalda** [comment]
Right, it fails because textarea is hidden.

I will leave this issue to someone else.

**Comment by axeaxel** [comment]
I used the xPath for that and it worked. Closing it now.
