### ISSUE TITLE
How to attach file from an explorer window after clicking on the attach files button

### ISSUE THREAD

**Issue by axeaxel** [Codeception/Codeception#5176]
#### What are you trying to achieve?
I am trying to attach a file after the user clicks the attach file button.
After that, an explorer window is opend and I have to browse in to the location of the file. 

I have my file in tests/_data folder

#### What do you get instead?

[InvalidArgumentException] File does not exist: C:\Users\alex0T\myproject\tests/_data\/tests/_data/Testdocument.txt

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 [InvalidArgumentException] File does not exist: C:\Users\alex\myproject\tests/_data\/tests/_data/Testdocument.txt

```
`$I->attachFile('/html/body/div[6]/div/div/div[2]/div/form/fieldset/div[8]/div/div/div/div[2]/button', '/tests/_data/Testdocument.txt');`

### Details

* Codeception version: 2.4.6
* PHP Version: 7.2.4
* Operating System: Windows 10
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
behat/gherkin v4.5.1 Gherkin DSL parser for PHP 5.3
doctrine/instantiator 1.1.0 A small, lightweight utility to instantiate objects in PHP without invok...
facebook/webdriver 1.6.0 A PHP client for Selenium WebDriver
guzzlehttp/guzzle 6.3.3 Guzzle is a PHP HTTP client library
guzzlehttp/promises v1.3.1 Guzzle promises library
guzzlehttp/psr7 1.4.2 PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy 1.8.1 Create deep copies (clones) of your objects
phar-io/manifest 1.0.3 Component for reading phar.io manifest information from a PHP Archive (P...
phar-io/version 2.0.1 Library for handling version information and constraints
phpdocumentor/reflection-common 1.0.1 Common reflection classes used by phpdocumentor to reflect the code stru...
phpdocumentor/reflection-docblock 4.3.0 With this component, a library can provide support for annotations via D...
phpdocumentor/type-resolver 0.4.0
phpspec/prophecy 1.8.0 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage 6.0.7 Library that provides collection, processing, and rendering functionalit...
phpunit/php-file-iterator 2.0.1 FilterIterator implementation that filters files based on a list of suff...
phpunit/php-text-template 1.2.1 Simple template engine.
phpunit/php-timer 2.0.0 Utility class for timing
phpunit/php-token-stream 3.0.0 Wrapper around PHP's tokenizer extension.
phpunit/phpunit 7.3.5 The PHP Unit Testing framework.
psr/http-message 1.0.1 Common interface for HTTP messages
sebastian/code-unit-reverse-lookup 1.0.1 Looks up which function or method a line of code belongs to
sebastian/comparator 3.0.2 Provides the functionality to compare PHP values for equality
sebastian/diff 3.0.1 Diff implementation
sebastian/environment 3.1.0 Provides functionality to handle HHVM/PHP environments
sebastian/exporter 3.1.0 Provides the functionality to export PHP variables for visualization
sebastian/global-state 2.0.0 Snapshotting of global state
sebastian/object-enumerator 3.0.3 Traverses array structures and object graphs to enumerate all referenced...
sebastian/object-reflector 1.1.1 Allows reflection of object attributes, including inherited and non-publ...
sebastian/recursion-context 3.0.0 Provides functionality to recursively process PHP variables
sebastian/resource-operations 1.0.0 Provides a list of PHP built-in functions that operate on resources
sebastian/version 2.0.1 Library that helps with managing the version number of Git-hosted PHP pr...
symfony/browser-kit v4.1.4 Symfony BrowserKit Component
symfony/console v4.1.4 Symfony Console Component
symfony/css-selector v4.1.4 Symfony CssSelector Component
symfony/dom-crawler v4.1.4 Symfony DomCrawler Component
symfony/event-dispatcher v4.1.4 Symfony EventDispatcher Component
symfony/finder v4.1.4 Symfony Finder Component
symfony/polyfill-ctype v1.9.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring v1.9.0 Symfony polyfill for the Mbstring extension
symfony/process v4.1.4 Symfony Process Component
symfony/yaml v4.1.4 Symfony Yaml Component
theseer/tokenizer 1.1.0 A small library for converting tokenized PHP source code into XML and po...
webmozart/assert 1.3.0 Assertions to validate method input/output with nice error messages.
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
    - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
coverage:
    enabled: true
```

**Comment by axeaxel** [comment]
The button that opens the explorer window looks like this:

![image](https://user-images.githubusercontent.com/43213449/45742747-8dc86380-bbf2-11e8-90da-6af2d4d4fb89.png)

I have used the xPath as I can't find a better way to click on the button and attach the file, I know that codeception accepts:

I.attachFile('Avatar', 'data/avatar.jpg');
I.attachFile('form input[name=avatar]', 'data/avatar.jpg');

How can I apply it for my example? 

Thank you!

**Comment by axeaxel** [comment]
I am clicking first time on the button and then trying to attach the file but it's not working at all, it says that the test is PASSED.

`//Attach a file
$I->click('/html/body/div[6]/div/div/div[2]/div/form/fieldset/div[8]/div/div/div/div[2]/button');
$I->wait(3);
$I->attachFile('/html/body/div[6]/div/div/div[2]/div/form/fieldset/div[8]/div/div/div/div[2]/button', 'Testdocument.txt');
$I->wait(10);`

Any ideas?

**Comment by Naktibalda** [comment]
All that `attachFile` does is locate form element and sends key presses of file name to it.
If you want to make your test fail, submit the form and see if there are no error messages in the next page.

Attaching file to button seems wrong, you have to attach to input type=fiile

**Comment by axeaxel** [comment]
Yes, failing with that one when I am doing it:
`$I->attachFile('input[@type="file"]', 'Testdocument.txt');`

 Step  Attach file "input[@type="file"]","Testdocument.txt"
 Fail  Field by name, label, CSS or XPath element with 'input[@type="file"]' was not found.

**Comment by Naktibalda** [comment]
I'm a bit rusty on frontend development, how does your file upload works if you have no input field with type=file?
Please link me to the relevant documentation.

**Comment by axeaxel** [comment]
No worries, I am trying to get this one working so I am considering anything that I can use.
So I thin that the Angular ng-file-upload directive creates one on the fly to use, because when I try in the console $('input[type=file]') and pressing the button , it finds one.

**Comment by axeaxel** [comment]
So now my button looks like this, I have an ID on it, but I still can't attach any files using attachFile one:

![image](https://user-images.githubusercontent.com/43213449/46197522-fd7cd380-c301-11e8-84e6-cadbc73f92e4.png)

**Comment by Naktibalda** [comment]
Very old support ticket, there was no bug reported.

**Comment by Reshma-Intellipharm** [comment]
> So now my button looks like this, I have an ID on it, but I still can't attach any files using attachFile one:
> 
> ![image](https://user-images.githubusercontent.com/43213449/46197522-fd7cd380-c301-11e8-84e6-cadbc73f92e4.png)
