### ISSUE TITLE
Unable to upload binary using Rest put

### ISSUE THREAD

**Issue by ruudboon** [Codeception/Codeception#5188]
I would like to add a test to my rest api where I upload files using a put request containing the binary of the file and not as a Multipart post/put.
```
PUT UPLOAD_URL HTTP/1.1
Authorization: Bearer AUTH_TOKEN
Content-Length: CONTENT_LENGTH
Content-Type: CONTENT_TYPE

BINARY_FILE_DATA
```
This method works fine in for example Postman but I'm unable to implement it in Codeception.
Would it be possible to add a parameter to the Rest module that allows us to upload a file this way?

**Comment by Naktibalda** [comment]
Have you tried to set the second parameter of sendPut to a string containing contents of that file?

**Comment by ruudboon** [comment]
@Naktibalda I did but then I show up empty on the other side.
Expecting mime type image/png got application/x-empty"

**Comment by ruudboon** [comment]
My test looks something like this 
```
        $image = codecept_data_dir('white-1920x1080.png');
        $imagedata = fopen($image, 'rb');
        $size = filesize($image);
        $contents = fread($imagedata, $size);
        fclose($imagedata);

        $I->sendPUT('/files/upload", $contents);
```

**Comment by ruudboon** [comment]
@Naktibalda Yeah tried that at first but was not sure if file_get_contents would do some weird encoding. Header was already in but forgot to copy it in example.
```
 $I->haveHttpHeader('Content-Type','application/x-binary');

        $I->sendPUT('/files/'.$data["id"]."/upload", file_get_contents(codecept_data_dir('white-1920x1080.png')));
        $I->seeResponseCodeIs(200);
```

**Comment by Naktibalda** [comment]
Your test code is good now, so it is an issue of app or framework code.

Your error message crearly said, that your app is expecting `image/png`, why are you setting `Content-Type` to `application/x-binary` ?

**Comment by Naktibalda** [comment]
@ruudboon Have you solved this issue?

I've looked at the code of Phalcon connector,
it implements raw body functionality by stubbing `getRawBody` method of [request object](https://github.com/Codeception/Codeception/blob/2.5.1/src/Codeception/Lib/Connector/Phalcon.php#L112).
Were you using that method in your code?

**Comment by ruudboon** [comment]
@Naktibalda No unfortunately not. 
I'm using a raw input. Something like this:
```
$hSource = fopen("php://input", "rb");
        if (!$hSource) {
            return $this->onNoDataProvided();
        }

        $mime = mime_content_type($hSource);
        if (!$item->isMimeAllowed($mime)){
            throw new Exception(ErrorCodes::POST_DATA_INVALID, 'Expecting mime type '.$item->getMime().' got '.$mime);
        }
        fclose($hSource);

```

**Comment by Naktibalda** [comment]
It is impossible to test this code using any framework module,
Your options are:
1. Use PhpBrowser module to make a real HTTP request,
2. Modify your code to use getRawBody method of request object.

**Comment by ruudboon** [comment]
@Naktibalda Hmm I see. Thnx!! Didn't realise that. Probably I want to stay with php//input because I'm expecting large files. But will try testing this with the PhpBrowser.
