### ISSUE TITLE
`seeResponseCodeIs()` in WebDriver with ChromeDriver?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5190]
It has been asked before if it's possible to get the HTTP status code with WebDriver: https://github.com/Codeception/Codeception/issues/739

The answer was no, cause Selenium can't access the status code. And it looks like they're not going to change this: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141

So what I'm asking: Would it be possible with ChromeDriver standalone?

**Comment by Naktibalda** [comment]
> So what I'm asking: Would it be possible with ChromeDriver standalone?

No, it is impossible, because `facebook/php-webdriver` does not provide such functionality.
https://github.com/facebook/php-webdriver/issues/470
