### ISSUE TITLE
wrong php minimum version for codeception between 2.1.7 and 2.4.1

### ISSUE THREAD

**Issue by comhon-project** [Codeception/Codeception#5199]
### What are you trying to achieve?
I'm trying to include codeception dependency with composer for a php version `5.5.9`
### Details
codeception composer file between version `2.1.7` and `2.4.1` indicate `php: >=5.4.0` but in fact `php 5.6` is required due to phpunit (from version `5.0.0`) dependency that depend itself on `myclabs/deep-copy`

the problem is that in myclabs there is the file deep_copy.php that have following code 
```
use function function_exists;
```
this fonctionnality appear only on php 5.6

* Codeception version: between version `2.1.7` and `2.4.1`
* List of installed packages : only Codeception/Codeception (and there dependencies)

### Expected
composer files should indicate `php: >=5.6`

**Comment by comhon-project** [comment]
but composer automatically install newer version of phpunit.  
for example when I install codeception version `2.4.1` phpunit version `7.1.5` is installed.  
perhaps it should be indicated a max version of phpunit instead of increase php version ?

**Comment by Naktibalda** [comment]
You only get phpunit 7.1.5 because you are using version of PHP which supports that version of phpunit.

Codeception 2.4.1 is compatible with PhpUnit 5, 6 and 7.

**Comment by Naktibalda** [comment]
Also if 2.4.1 is wrong, nobody is going patch that version, you will only get a patch as 2.4.6.

**Comment by comhon-project** [comment]
ok, thanks for your quick answers, I close the issue
