### ISSUE TITLE
Custom generators

### ISSUE THREAD

**Issue by josephzidell** [Codeception/Codeception#5203]
#### What are you trying to achieve?
The generators are so helpful, but they follow a certain coding style. In order to avoid complexity in supporting multiple styles, how does one go about customizing a generator templates? For example, how would I override the template for cest? https://github.com/Codeception/Codeception/blob/2.5/src/Codeception/Lib/Generator/Cest.php#L13-L28

In my case, I'd want a declare statement, along with docblocks and return types. 

#### What do you get instead?
A default template that must be modified by hand each time it is used.

* Codeception version: 2.5.0

**Comment by Naktibalda** [comment]
There is no way to change templates of test files generated by Codeception.

You could use file templates provided by your IDE.

**Comment by alexkuc** [comment]
Even though it is not possible to override class directly, I found a workaround. You can create a [custom command](https://codeception.com/docs/08-Customization#Custom-Commands). Apparently, if you register it with _exactly the same_ command name as the template you are trying to override, e.g. `generate:cest`, custom command will override the built-in. It's a little verbose but it gets the job done.
