### ISSUE TITLE
The populator command did not end successfully

### ISSUE THREAD

**Issue by darkkiller1406** [Codeception/Codeception#5208]
#### What are you trying to achieve?

I try loading the dump into my database in Codeception, but it not working.

#### What do you get instead?

Data not imported into the database.

My issues
> [RuntimeException]
  The populator command did not end successfully:
    Exit code: 127
    Output:

My code
> Db:
         dsn: 'mysql:host=localhost;dbname=db_name'
         user: 'root'
         password: ''
         populate: true # load dump before all tests
         cleanup: true # load dump for each test
         dump: 'tests/_data/dump.sql'
         populator: 'mysql -u $user -h $host $dbname < $dump'
### Details

* Codeception version: 2.4
* PHP Version:  7.1.3
* Installation type: Composer

**Comment by loks15** [comment]
use this command ./vendore/bin/codecept run -vvv --debug

instead of vardump() use this function 
codecept_debug(  );

**Comment by darkkiller1406** [comment]
> sh: 1: mysql: not found

In DbPopulator.php line 90:

  [RuntimeException]
  The populator command did not end successfully:
    Exit code: 127
    Output:


Exception trace:
 Codeception\Lib\DbPopulator->run() at /application/vendor/codeception/codeception/src/Codeception/Module/Db.php:621
 Codeception\Module\Db->loadDumpUsingPopulator() at /application/vendor/codeception/codeception/src/Codeception/Module/Db.php:612
 Codeception\Module\Db->_loadDump() at /application/vendor/codeception/codeception/src/Codeception/Module/Db.php:268

I have the following error when running the test

**Comment by Naktibalda** [comment]
You have no `mysql` client installed on the computer where you are running your tests.
Install it or don't use populator configuration: https://codeception.com/docs/modules/Db#Dump

**Comment by szabozoltan69** [comment]
Also a problem can be, if php and postgresql is in a different docker container. Then php can not run pg-related steps.
