### ISSUE TITLE
seeResponseContainJson

### ISSUE THREAD

**Issue by tasselchof** [Codeception/Codeception#5212]
#### What are you trying to achieve?

I try to check response containing Json, this is my array:

```php
 $transactionUpdate
        = [
            'currencyValue'   => 1,
        ];
```

#### What do you get instead?

My API returning float value, but codeception combating it like a string

```bash
-    'currencyValue' => 1
+    'currencyValue' => '1.00'
```

And test is failing.

**Comment by bscheshirwork** [comment]
So... You float value can't equials to your integer value?

Try to compare to float value? Something like this
```
 $transactionUpdate
        = [
            'currencyValue'   => (float) 1,
        ];
```

**Comment by Naktibalda** [comment]
@tasselchof I've tried to reproduce your issue, but had no luck - `1` matches `1.0` to me.

Please run Codeception with `-vv` flag and double check response of your API.
