### ISSUE TITLE
Screen capture on failing acceptance test - text issue

### ISSUE THREAD

**Issue by naveen-goalous** [Codeception/Codeception#5215]
#### What are you trying to achieve?
Running acceptance test.
#### What do you get instead?
Screen capture on failing acceptance test is writing garbage text.
see this: ![userinboxmessagecest createusersinboxmessage fail](https://user-images.githubusercontent.com/17561832/46542940-5558a300-c8dd-11e8-9343-dfe4a57faa31.png)

**Comment by Naktibalda** [comment]
Most likely it is an issue of your browser.

**Comment by naveen-goalous** [comment]
@josephzidell - content="text/html; charset=UTF-8" in meta tag.
