### ISSUE TITLE
Array-parameters are passed incorrectly

### ISSUE THREAD

**Issue by OGribiennikov** [Codeception/Codeception#5223]
#### I have environment params:
    // file env.yml
    products:
      booking:
        - 123456
        - 234567
        - 345678

#### Then I use them in the acceptance.suite.yml
    modules:
      enabled:
        - ...
        - \Helper\Acceptance
      config:
          // ......
        \Helper\Acceptance:
          products:
             booking:
               %products.booking%

#### Then in the test I try to get those params:
    class SomeCest
    {
        /** @var Acceptance */
        protected $helper;

        public function _inject(Acceptance $helper)
        {
            $this->helper = $helper;
        }

        // tests
        public function tryToTest(AcceptanceTester $I)
        {
            $products = $this->helper->_getConfig('products');
            codecept_debug($products['booking']);
        }
    }

#### But in the console I see the following:
    PHP Notice:  Array to string conversion in .../vendor/codeception/codeception/src/Codeception/Util/Template.php on line 83
    Array
    (
      [0] => Array
    )

#### The reason is:
The method `\Codeception\Util\Template::produce` tries to replace a parameter's placeholder with an array:
```    
$result = str_replace($this->placeholderStart . $placeholder . $this->placeholderEnd, $value, $result);
```
where `$value` is my array from the environment.

#### So I'm forced to use this configuration (in the acceptance.suite.yml):
      products:
        booking:
          - %products.booking.0%
          - %products.booking.1%
          - %products.booking.2%

But this is inconvenient and not the Feng Shui.

Could you fix this issue?
Or is there some other way to pass array in the test?
Thank you.

P.S. Non-array parameters are passed normal.

**Comment by Naktibalda** [comment]
`booking: "%products.booking%"` will be rendered as `booking: [123456, 234567, 345678]` in Codeception 5
