### ISSUE TITLE
`seeEmailIsSent()` not working when email is sent by a Symfony/Doctrine entity listener

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5252]
When using an [Entity Listener](https://symfony.com/doc/current/bundles/DoctrineBundle/entity-listeners.html) to send an email, `seeEmailIsSent()` doesn't notice it. When I do the same email command in the controller, it works.

The actual email delivery works in both cases (as shown by mailcatcher).

### Details

* Codeception version: 2.5.1
* PHP Version: 7.2

**Comment by picoss** [comment]
I've had the same issue trying to test emails sent from a doctrine entity listener.

The only way I've found to get sent emails from profiler is to persist the `Swift_Plugins_MessageLogger` plugin.

```php
<?php
namespace App\Tests\Helper;

class Symfony extends \Codeception\Module\Symfony
{
    /**
     * {@inheritdoc}
     */
    public function _initialize()
    {
        parent::_initialize();
        $this->persistService('swiftmailer.mailer.default.plugin.messagelogger', true);
    }
}
```

As far as I understand, Symfony and Doctrine doesn't share the same container when using both Symfony and Doctrine2 modules in codeception.
Persisting `Swift_Plugins_MessageLogger` service will share this service between Symfony and Doctrine2.

Not sure it's the right solution, but it works for me.

**Comment by ThomasLandauer** [comment]
@TavoNiievez Do you have an idea for Symfony Mailer?

**Comment by TavoNiievez** [comment]
I am taking this into account now, thank you. At the moment I am making [small progress](https://github.com/Codeception/symfony-demo/pull/24) correcting the CI server to be able to test any changes that I make and so that the changes are not merged with the CI failing.

**Comment by TavoNiievez** [comment]
@ThomasLandauer Can you confirm if after sending the email you do [some kind of redirection](https://symfony.com/doc/4.2/email/testing.html#problem-the-collector-doesn-t-contain-the-email)?

**Comment by ThomasLandauer** [comment]
More details: The controller is an api, it just persists the incoming data, then:
```php
return new Response('OK'); // This is not packed in an HTML skeleton to prevent the Symfony toolbar from loading - but this shouldn't make a difference in TEST environment
```
The entity listener kicks in `postPersist`; it sends the email with Symfony Mailer, writes this fact to the entity and persists it again.

In Codeception I'm doing:
```php
$I->sendPOST('/api/...');
$I->seeEmailIsSent();
```
And the error message I'm getting is:
```
Failed asserting that 0 is greater than 0.
```
The workaround I'm using right now: With `$I->grabEntityFromRepository(...)` I check if the "emailed" flag (from the listener) is set. This works fine.

Contrary to what I said above, I cannot get it to work anymore if I move the email sending code from the listener to the controller! So maybe the cause of the problem is that I'm using `sendPOST()` from REST module, and `seeEmailIsSent()` from Symfony module can't "access" that? If this is the case => Any ideas for a solution?

**Comment by ThomasLandauer** [comment]
Closing this, as it was transferred to https://github.com/Codeception/module-symfony/issues/90
