### ISSUE TITLE
How to use mutation testing?

### ISSUE THREAD

**Issue by voku** [Codeception/Codeception#5258]
#### What are you trying to achieve?

I try to use mutation testing, but I can't find any solution that works with Codeception. Has someone a idea?

Info: for "infection" there is a not merged pull request -> (pull: https://github.com/infection/infection/pull/457) (issues: https://github.com/infection/infection/issues/45)

**Comment by Naktibalda** [comment]
I am not aware of any working solutions.

**Comment by Fenikkusu** [comment]
The PR you referenced should work (though a little out dated). It was working fine the last I worked on it. Need to get on that again...crud...

**Comment by voku** [comment]
@Fenikkusu It would be awesome, if you can take a look at this feature, again... thanks for your work! :+1:

**Comment by Naktibalda** [comment]
Codeception support was implemented by https://github.com/infection/infection/pull/800
