### ISSUE TITLE
Run IHM tests with webservice assertions in Codeception

### ISSUE THREAD

**Issue by nounnoune** [Codeception/Codeception#5260]
I would like to run IHM tests, verify some values comming from a webservice in the testing framework Codeception.

**I don't want to test the webservice**, I just need it to verify that values which are displayed on the screen are correct (the same as in the data returned by the web service).

My question is: How can I do to do assertions without testing the webservice, to compare what is displayed to what is in database in the same feature ?

Do I have to use several actors ? how many yml files do I need ?

Thanks

**Comment by Naktibalda** [comment]
Nobody wanted to answer questions.
This is not a bug report.
