### ISSUE TITLE
When codeception will be SOLID?

### ISSUE THREAD

**Issue by eniuz** [Codeception/Codeception#5267]
#### What are you trying to achieve?
SOLID code with yii and codeception
#### What do you get instead?
code that is not solid
> Provide console output if related. Use `-vvv` mode for more details.
sorry. I can't do that due to contract enclosure 
```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.5.0
* PHP Version: 7.2
* Operating System: Centos
* Installation type: Phar || Composer Composer
* List of installed packages (`composer show`) no way!
* Suite configuration:

```yml
# paste suite config here lol 
```
Just working with yii2 and codeception. My intent was to exchange typehint for FunctionalTester to Codeception\Actor. I'm still investigating it but as far as I can see in your docs you encurage people to typehint based on concretions. Is there any chance to have dependency inversion applied to generated classes?

**Comment by SamMousa** [comment]
Codeception generates the `FunctionalTester` class to provide you with code completion based on your configuration (modules can add extra features to your tester).
Your test classes are dependent on a correctly configured (and thus concrete) functional tester, so typehinting a generic actor won't help.

**Comment by eniuz** [comment]
I'm forced to use concretion over abstraction. What if I wanted to replace this with ease? Thanks for the answer
