### ISSUE TITLE
Problem with duplicate failed images when you have multiple environments.

### ISSUE THREAD

**Issue by annapetrai** [Codeception/Codeception#5274]
Hello, I have the following problem with codeception I want the image in failed to be unique for each browser that I am using that does not happen is there a workaround for it.

**Comment by annapetrai** [comment]
The problem lies in the fact that the image is not parametrized based on environment.

**Comment by reinholdfuereder** [comment]
@Naktibalda Can it be that this was actually fixed by @Tenzian via https://github.com/Codeception/Codeception/pull/5294 about a month later? => If so, would you mind resolving this issue?

**Comment by Naktibalda** [comment]
@annapetrai this issue was fixed, please reopen the ticket if you still have this issue after upgrading Codeception and phpunit-wrapper.
