### ISSUE TITLE
Codeception updation issue

### ISSUE THREAD

**Issue by GoutamNaikGaonkar** [Codeception/Codeception#5279]
#### What are you trying to achieve?
Trying to update my codeception version
currently with codeception version 2.3.2 and docker version 3.14.0-helium my test suite was working fine
but with latest version of docker selenium my test suite is failing
so i want to update my codeception version to latest since my codeception version is old
when replaced my codecept the phar file with version above 2.3.2(say 2.4.0) and tried to run my test but getting this error

#### What do you get instead?
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in phar:///home/mfc-team23/codeception/codecept.phar/vendor/phpunit/phpunit/src/Util/Printer.php on line 147
PHP Stack trace:
PHP   1. {main}() /home/mfc-team23/codeception/codecept.phar:0
PHP   2. require_once() /home/mfc-team23/codeception/codecept.phar:5
PHP   3. include_once() phar:///home/mfc-team23/codeception/codecept.phar/autoload.php:25
PHP   4. Codeception\PHPUnit\Init::init() phar:///home/mfc-team23/codeception/codecept.phar/shim.php:5
PHP   5. require_once() phar:///home/mfc-team23/codeception/codecept.phar/vendor/codeception/phpunit-wrapper/src/Init.php:12
PHP   6. class_exists() phar:///home/mfc-team23/codeception/codecept.phar/vendor/codeception/phpunit-wrapper/src/shim.php:44
PHP   7. spl_autoload_call() phar:///home/mfc-team23/codeception/codecept.phar/vendor/codeception/phpunit-wrapper/src/shim.php:44
PHP   8. Composer\Autoload\ClassLoader->loadClass() phar:///home/mfc-team23/codeception/codecept.phar/vendor/codeception/phpunit-wrapper/src/shim.php:0
PHP   9. Composer\Autoload\includeFile() phar:///home/mfc-team23/codeception/codecept.phar/vendor/composer/ClassLoader.php:301

* Codeception version: 2.4.0
* PHP Version: 5.6.38
* Operating System: Linux
* Installation type: Phar

**Comment by Naktibalda** [comment]
You got a phar file which requires PHP 7.0

Please go to https://codeception.com/builds and click on `for PHP 5.6" link next to version number that you want to download.

**Comment by GoutamNaikGaonkar** [comment]
Thanks @Naktibalda
