### ISSUE TITLE
Document that Doctrine's `cleanup: true` (to rollback the transaction) doesn't really work in acceptance test

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5286]
I'm observing that `cleanup: false` in `acceptance.suite.yml` is being ignored: Although I am getting this in the terminal:

> [Database] Transaction cancelled; all changes reverted.

...in fact, I see that the changes which the app made, are persisted in the database.

I'm figuring this is due to the fact that Codeception uses a different connection to the database than the browser/app; as explained at https://github.com/Codeception/Codeception/issues/4301#issuecomment-306122184

Is this true?

If yes, what's the purpose of having `cleanup: true` in an acceptance test at all?? If there is none, this should be explained in the docs.

**Comment by Naktibalda** [comment]
Label: rethorical

**Comment by Naktibalda** [comment]
Documentation doesn't say that Doctrine module works in Acceptance tests.
Acceptance in Codeception means PhpBrowser and WebDriver modules.

Doctrine module only integrates with Symfony and ZF2 modules out of the box.
Integration with other modules is user's responsibility.

**Comment by Naktibalda** [comment]
Yes

**Comment by Naktibalda** [comment]
Please make a pull request.

**Comment by ThomasLandauer** [comment]
Done :-)

**Comment by chucky2305** [comment]
Hello, any reasons why Thomas` additional documentations are not merged yet? I stepped into the same trap today. I guess the documentation will prevent others from stepping into the same trap

**Comment by chucky2305** [comment]
Sorry, i thought there was one.

**Comment by ThomasLandauer** [comment]
Sorry guys, looks like I only did the commit, and forgot to press the final "Create Pull Request" button ;-) Here it is (finally): https://github.com/Codeception/Codeception/pull/5734

**Comment by ThomasLandauer** [comment]
Finally closed by https://github.com/Codeception/module-doctrine2/pull/2
