### ISSUE TITLE
Test Suite while running fails in between

### ISSUE THREAD

**Issue by GoutamNaikGaonkar** [Codeception/Codeception#5287]
#### What are you trying to achieve?

Trying to run my automation suite with latest versions of codeception version 2.5.1 and selenium docker version 3.141.59-bismuth

#### What do you get instead?

The test suite after running few test cases fails in between giving the following error

[Facebook\WebDriver\Exception\NoSuchDriverException] invalid session id
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 3.16.0-4-amd64 x86_64)

* Codeception version: 2.5.1
* PHP Version: 5.6.38
* Operating System: Linux
* Installation type: Phar
* selenium docker version: 3.141.59-bismuth

**Comment by Naktibalda** [comment]
Probably it is an issue of Chrome or chromedriver.

**Comment by matvey88** [comment]
@GoutamNaikGaonkar @Naktibalda, hi! 
For me, helped to fix this error, it is a change size of the /dev/shm in docker container. 
Try `docker run --shm-size=2gb` your command   
More info https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container
