### ISSUE TITLE
C3 issue with API call example  test?

### ISSUE THREAD

**Issue by delboy1978uk** [Codeception/Codeception#5289]
#### What are you trying to achieve?
I have an API endpoint that I have tested and passing. I then created an example page showing how to configure a guzzle client to connect to my API and make the call. The test passes locally and coverage is generated. 
#### What do you get instead?
On Travis, for some reason I started getting C3 not found. I then went to the hassle of making a fake ssl certificate and going through stunnel in order to make sure both local and travis tests were both running on https. Once I got that working, I started getting the same error again. 

> Provide console output if related. Use `-vvv` mode for more details.
Here is the build where I got things working again but this time using using https, https://www.travis-ci.org/delboy1978uk/oauth2-api/jobs/462479593. As you can see I get the error below:
```
[PHPUnit\Framework\Exception]                                                
  file_get_contents(https://awesome.scot:8443/c3/report/clear): failed to ope  
  n stream: HTTP request failed!
```
The test looked like this:
```php
$I = new AcceptanceTester($scenario);
$I->wantTo("Check client_credentials client can call the API and fetch data");
$I->amOnPage('/website/client-credentials-example');
$I->seeResponseCodeIs(200);
$I->see('BoneMVC App');
$I->see('Web App');
$I->see('Android App');
```
I tried just out of interest taking it out of an acceptance test and just sticking it in an API test instead:
```php
    public function tryToCallAPIWithClientCredentialsGrant(ApiTester $I)
    {
        $I->wantTo('Call the /website/client-credentials-example endpoint and get served');
        $I->sendGET('/website/client-credentials-example');
        $I->seeResponseIsJson();
        $I->seeResponseCodeIs(200);
    }
```
Other tests started passing again, until it hit the new test, after which, every other test failed with  a cURL timeout https://www.travis-ci.org/delboy1978uk/oauth2-api/jobs/462495570:
```
[GuzzleHttp\Exception\ConnectException] cURL error 28: Operation timed out after 30000 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```
The actual endpoint being tested is here https://github.com/delboy1978uk/oauth2-api/blob/master/src/App/Controller/OfficialWebAppController.php#L24-L50 

```php
            $apiKeys = Registry::ahoy()->get('apiKeys');
            $options = $apiKeys['clientCredentials'];
            $provider = new SelfSignedProvider($options);
            $accessToken = $provider->getAccessToken('client_credentials', ['scope' => ['admin']]);
            $request = $provider->getAuthenticatedRequest('GET', $options['host'] . '/client', $accessToken);
            $response = $provider->getResponse($request);
            $data = \json_decode($response->getBody()->getContents());
            $response = new JsonResponse($data);
            return $response;
```
### Details

* Codeception version: 2.5.1
* PHP Version: 7.1 & 7.2
* Operating System: Travis builds https://www.travis-ci.org/delboy1978uk/oauth2-api/
* Installation type: Composer
* List of installed packages See build log in Travis
* Suite configuration:

```yml
actor: ApiTester
modules:
  enabled:
  - REST:
      url: https://apache
      depends: PhpBrowser
      part: Json
env:
  travis:
    modules:
      enabled:
      - REST:
          url: https://awesome.scot:8443
          depends: PhpBrowser
          part: Json
```
Could it be because code coverage would be triggered twice? Once to begin with for the example endpoint but then the call inside too?

If you need to see anything else all the code is here https://github.com/delboy1978uk/oauth2-api. 
A last thought, I remember a time when I didn't need this C3 file? Is it necessary with Travis or have I just need to reconfigure my setup?

**Comment by Fenikkusu** [comment]
1) Did you add codeception/c3 to composer.json dev dependencies? IE:  `"codeception/c3": "2.*",`
2) Did you include ./c3.php in your index.php? IE:
```php
//Load Codeception Testing File, If Exists (Not In Production)
if (file_exists(__DIR__ . '/../c3.php') && getenv('ENV_APPLICATION_ENV') !== 'production') {
    require_once __DIR__ . '/../c3.php';
}
```
3) Did you install composer in your pipeline using dev dependencies?

**Comment by delboy1978uk** [comment]
1 && 3) Indeed! https://www.travis-ci.org/delboy1978uk/oauth2-api/jobs/462495571#L541 You can see C3 is up to date.
```
  - Installing codeception/c3 (2.4.1): Downloading (100%)
[codeception/c3] c3.php is already up-to-date
```
2) Yes! https://github.com/delboy1978uk/oauth2-api/blob/master/public/index.php#L51-L58
```php
/*
 * code coverage for travis
 */
if (APPLICATION_ENV == 'travis') {
    require_once APPLICATION_PATH . '/c3.php';
    ini_set('error_log', '/home/travis/build/delboy1978uk/oauth2-api/data/logs/error_log');
    ini_set('sendmail_path', '/usr/local/bin/mhsendmail');
}
```

**Comment by delboy1978uk** [comment]
i now use docker on travis so i don't need c3 anymore, closing this issue
