### ISSUE TITLE
Tests can passed with failed assertion in a mocked method

### ISSUE THREAD

**Issue by schmitty42** [Codeception/Codeception#5293]
When doing asserts inside a mocked method (using AspectMock), if the calling code is inside a try/catch block that catches the core Exception or Throwable class the test will pass.

```
testCest: Test with catch
Signature: testCest:testWithCatch
Test: tests/unit/testCest.php:testWithCatch
Scenario --
 I assert equals 0,0
 I assert equals 0,0
 I assert equals 1,1
 I assert equals 1,0
  Array
  (
      [0] => Catching test failure
      [1] => Failed asserting that 0 matches expected 1.
  )
  
 I assert equals 2,2
 I assert equals 2,0
  Array
  (
      [0] => Catching test failure
      [1] => Failed asserting that 0 matches expected 2.
  )
  
 PASSED 

```
Simple repo that duplicates the bug:
https://github.com/schmitty42/codeception-example

### Details

* Codeception version: 2.5.1
* PHP Version: 7.1.16
* Installation type: Composer

**Comment by Naktibalda** [comment]
Sorry, it is a problem of your code, which is untestable, there is nothing we can do about it.
Catch more specific exceptions in your code.

If you know how to fix it, you are welcome to make a pull request.

You want testing framework which isn't based on exceptions, so you want framework which isn't based on PhpUnit.
