### ISSUE TITLE
[Yii2] [Exception] No content was sent from Yii application / Header already send

### ISSUE THREAD

**Issue by Julian-B90** [Codeception/Codeception#5296]
#### What are you trying to achieve?

Execute tests with PageCache (https://github.com/yiisoft/yii2/blob/master/framework/filters/PageCache.php)

#### What do you get instead?

`[Exception] No content was sent from Yii application`

You can find and Example Test with the Bug in this repo https://github.com/Codeception/yii2-tests/pull/6

### Details

* Codeception version: 2.5.1
* PHP Version: PHP 7.0.27 (cli) (built: Feb 17 2018 02:11:11) ( NTS )
* Operating System: Docker (php:7.0.27-fpm-jessie)
* Installation type: Composer
* List of installed packages  [removed by Sam]

**Comment by samdark** [comment]
Yes. Seems to be valid.

**Comment by SamMousa** [comment]
The fix has been merged with Yii, could you test it Julian?

**Comment by Julian-B90** [comment]
@SamMousa thank you very much now all the tests are running :-)
