### ISSUE TITLE
Can't generate acceptance test, during quick start on VM

### ISSUE THREAD

**Issue by stonetwig** [Codeception/Codeception#530]
I were just trying out the Codeception testing suite since we thought we need better testing, specially selenium tests. So I downloaded the phar archive and began to run the quick start instructions available on http://codeception.com/quickstart.

The problem occurs when I have created a new suite and were going to generate an acceptance test. It just gives me an error:

  [Exception]
  Suite acceptance was not loaded
I have tried to google around to find any solution or to see if anybody have had the same exception raised but it seems that I am alone. What am I doing wrong? Or if I am not doing anything wrong, as it seems this may be some kind of bug.

The commands that I ran:

wget http://codeception.com/codecept.phar
php codecept.phar bootstrap
php codecept.phar generate:cept acceptance Welcome
Please, would someone try and guide me where to go now. How can I create a new acceptance test?

It says "Suite acceptance" so I tried to add an argument with the name "WebGuy" as it seems to be the name of the suite? But if I try to alter the number of commands it just gives me:

  [RuntimeException]
  Too many arguments.

Running on ubuntu parallel virtual server

**Comment by takenotetyping** [comment]
Thanks whatknows!

**Comment by Onyedikachi** [comment]
@whatknows  Thanks, It works perfectly.

**Comment by btoone** [comment]
Oddly using lower case instead of the caps used on the site worked for me `php vendor/bin/codecept generate:cest acceptance first`.

**Comment by mohsinr** [comment]
100% for me too, as soon as I used `acceptance` in small caps as @btoone shared above. It worked for me too! Thank you @btoone Brandon
