### ISSUE TITLE
PHPUnit 7.5.0

### ISSUE THREAD

**Issue by josephzidell** [Codeception/Codeception#5311]
#### What are you trying to achieve?
Access to new asserts in PHPUnit 7.5.0: `assertIsArray()`, `assertIsBool()`, etc.

I can create a PR, but want to make sure about the correct steps:
- Adds methods to `Codeception\Util\Shared\Asserts`?

Does anything need to be done in [phpunit-wrapper](https://github.com/Codeception/phpunit-wrapper)?

**Comment by Naktibalda** [comment]
If your test class extends `\Codeception\Test\Unit` or `\PhpUnit\Framework\TestCase`,
you can access all assertions using `$this->assertXxxx()` syntax, e.g. `$this->assertIsBool();`

**Comment by DavertMik** [comment]
If you would like to add this PR please do it backward compatible. 
So instead of using PHPUnit's assertions to reimplement them in `Codeception\Util\Shared\Asserts` with the same signatures.

**Comment by Naktibalda** [comment]
Implemented in Codeception 2.6: https://github.com/Codeception/Codeception/commit/cfe341a34af0fe5dd0c6db98d0edf9610275a46d
