### ISSUE TITLE
Inject classes to custom Command constructor

### ISSUE THREAD

**Issue by Shiriaev** [Codeception/Codeception#5317]
#### What are you trying to achieve?
I try to create new CLI command. whitch generates Cest from Swagger schema. When I add constructor with classes injection to command class, i have error: 

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function Swagger\Magento2TestGenerator::__construct(), 1 passed in C:\os\domains\democept.loc\democept\vendor\codeception\codeception\src\Codeception\Application.php on line 63 and exactly 3 expected in C:\os\domains\democept.loc\democept\tests\_support\Swagger\Magento2TestGenerator.php on line 27`

I think its happend becouse we have instantiation Command childs classes in vendor\codeception\codeception\src\Codeception\Application.php on line 63:

`$this->add(new $commandClass($commandName));`

How can I inject my classes?

* Codeception version: latest
* PHP Version: 7.1
* Operating System: Windows 10/Openserver
* Installation type: Composer

**Comment by Naktibalda** [comment]
It is impossible to pass any other parameters to Command, Command class must instantiate dependencies by itself.
