### ISSUE TITLE
Update Docker to use PHP 7.3

### ISSUE THREAD

**Issue by OneEyedSpaceFish** [Codeception/Codeception#5325]
#### What are you trying to achieve?
Run tests in latest stable 7.3 php version

#### What do you get instead?
PHP 7.2 :)

This issue is pretty self explanatory.
Hopefully the migration should be easy enough as it would only contain updating the `docker from` to 7.3-cli, and pushing the new image to DockerHub.

This would need some testing locally, but the list of breaking changes for 7.3 were slim, so it's likely that everything will work out of the box as is. Obviously this will need checking first.

In terms of composer, the yml file already contains a `>=5.6.0 <8.0` constraint, so 7.3 version should already be included in there.

**Comment by Carsak** [comment]
Does this issue actual?

**Comment by OneEyedSpaceFish** [comment]
> Does this issue actual?
No. I've been on holiday.
That being said the docker image still doesn't build tho due to: #5384
Closing the issue now.
