### ISSUE TITLE
Update symfomy-demo to Symfony 4.2, show coverage

### ISSUE THREAD

**Issue by tacman** [Codeception/Codeception#5337]
#### What are you trying to achieve?

Issues are not enabled for the codeception/symfony-demo, so I'm posting here.  It'd be GREAT to have a working example.

A working demo version of Symfony with Codeception

#### What do you get instead?

composer.lock is out of date.  Running with coverage doesn't show anything, possibly a configuration issue.

```bash
git clone git@github.com:Codeception/symfony-demo.git
cd symfony-demo
composer install
# Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

composer update
bin/console --version
#  Symfony 4.2.2 (env: dev, debug: true)
bin/console server:start 

bin/codecept
# bash: bin/codecept: No such file or directory
# documentation isn't correct.  Flex needs to copy the file to /bin, or change the documentation

# now open php storm and run any test with coverage:

Powered by PHPUnit 6.5.13 by Sebastian Bergmann and contributors.
PHP Fatal error:  Declaration of Codeception\PHPUnit\FilterTest::accept() must be compatible with PHPUnit\Runner\Filter\NameFilterIterator::accept(): bool in /var/www/symfony-demo/vendor/codeception/codeception/src/Codeception/PHPUnit/FilterTest.php on line 31
PHP Stack trace:
PHP   1. {main}() /tmp/ide-codeception.php:0
PHP   2. Codeception\Application->run($input = *uninitialized*, $output =

```

```php
// paste test
```
### Details

* Codeception version: 

vendor/bin/codecept --version
Codeception 2.3.9

* PHP Version: 7.2
* Operating System: Ubuntu
* Installation type: Phar || Composer
* List of installed packages (`composer show`)

composer show
behat/gherkin                       v4.4.5            Gherkin DSL parser for PHP 5.3
codeception/codeception             2.3.x-dev a310433 BDD-style testing framework
codeception/stub                    1.0.4             Flexible Stub wrapper for PHPUnit's Mock Builder
composer/ca-bundle                  1.1.3             Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/semver                     1.4.2             Semver library that offers utilities, version constraint parsing and validation.
composer/xdebug-handler             1.3.1             Restarts a process without xdebug.
dama/doctrine-test-bundle           v4.0.2            Symfony 2/3 bundle to isolate doctrine database tests and improve test performance
doctrine/annotations                v1.6.0            Docblock Annotations Parser
doctrine/cache                      v1.8.0            Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.5.0            Collections Abstraction library
doctrine/common                     v2.10.0           PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflect...
doctrine/data-fixtures              v1.3.1            Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.9.2            Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle            1.10.1            Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.5             Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle   3.1.0             Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle v1.3.2            Symfony DoctrineMigrationsBundle
doctrine/event-manager              v1.0.0            Doctrine Event Manager component
doctrine/inflector                  v1.3.0            Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.1.0             A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1            Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 v1.8.1            Database Schema migrations using Doctrine DBAL
doctrine/orm                        v2.6.3            Object-Relational-Mapper for PHP
doctrine/persistence                v1.1.0            The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                 v1.0.0            Doctrine Reflection component
egulias/email-validator             2.1.7             A library for validating emails against several RFCs
erusev/parsedown                    1.7.1             Parser for Markdown.
ezyang/htmlpurifier                 v4.10.0           Standards compliant HTML filter written in PHP
facebook/webdriver                  1.6.0             A PHP client for Selenium WebDriver
friendsofphp/php-cs-fixer           v2.14.0           A tool to automatically fix PHP code style
guzzlehttp/guzzle                   6.3.3             Guzzle is a PHP HTTP client library
guzzlehttp/promises                 v1.3.1            Guzzle promises library
guzzlehttp/psr7                     1.5.2             PSR-7 message implementation that also provides common utility methods
jdorn/sql-formatter                 v1.2.17           a PHP SQL highlighting library
monolog/monolog                     1.24.0            Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                   1.8.1             Create deep copies (clones) of your objects
ocramius/package-versions           1.3.0             Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager              2.1.1             A library providing utilities to generate, instantiate and generally operate with Object Proxies
pagerfanta/pagerfanta               v2.0.1            Pagination for PHP 5.3
paragonie/random_compat             v9.99.99          PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                    1.0.1             Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                     1.0.1             Library for handling version information and constraints
php-cs-fixer/diff                   v1.3.0            sebastian/diff v2 backport support for PHP5.6
phpdocumentor/reflection-common     1.0.1             Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.0             With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocB...
phpdocumentor/type-resolver         0.4.0            
phpspec/prophecy                    1.8.0             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           5.3.2             Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           1.4.5             FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template           1.2.1             Simple template engine.
phpunit/php-timer                   1.0.9             Utility class for timing
phpunit/php-token-stream            2.0.2             Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     6.5.13            The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        5.0.10            Mock Object library for PHPUnit
psr/cache                           1.0.1             Common interface for caching libraries
psr/container                       1.0.0             Common Container Interface (PHP FIG PSR-11)
psr/http-message                    1.0.1             Common interface for HTTP messages
psr/log                             1.1.0             Common interface for logging libraries
psr/simple-cache                    1.0.1             Common interfaces for simple caching
ralouphie/getallheaders             2.0.5             A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup  1.0.1             Looks up which function or method a line of code belongs to
sebastian/comparator                2.1.3             Provides the functionality to compare PHP values for equality
sebastian/diff                      2.0.1             Diff implementation
sebastian/environment               3.1.0             Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  3.1.0             Provides the functionality to export PHP variables for visualization
sebastian/global-state              2.0.0             Snapshotting of global state
sebastian/object-enumerator         3.0.3             Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector          1.1.1             Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context         3.0.0             Provides functionality to recursively process PHP variables
sebastian/resource-operations       1.0.0             Provides a list of PHP built-in functions that operate on resources
sebastian/version                   2.0.1             Library that helps with managing the version number of Git-hosted PHP projects
sensio/framework-extra-bundle       v5.2.4            This bundle provides a way to configure your controllers with annotations
sensiolabs/security-checker         v4.1.8            A security checker for your composer.lock
swiftmailer/swiftmailer             v6.1.3            Swiftmailer, free feature-rich PHP mailer
symfony/asset                       v4.2.2            Symfony Asset Component
symfony/browser-kit                 v4.2.2            Symfony BrowserKit Component
symfony/cache                       v4.2.2            Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                      v4.2.2            Symfony Config Component
symfony/console                     v4.2.2            Symfony Console Component
symfony/contracts                   v1.0.2            A set of abstractions extracted out of the Symfony components
symfony/css-selector                v4.2.2            Symfony CssSelector Component
symfony/debug                       v4.2.2            Symfony Debug Component
symfony/debug-bundle                v4.2.2            Symfony DebugBundle
symfony/dependency-injection        v4.2.2            Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.2.2            Symfony Doctrine Bridge
symfony/dom-crawler                 v4.2.2            Symfony DomCrawler Component
symfony/dotenv                      v4.2.2            Registers environment variables from a .env file
symfony/event-dispatcher            v4.2.2            Symfony EventDispatcher Component
symfony/expression-language         v4.2.2            Symfony ExpressionLanguage Component
symfony/filesystem                  v4.2.2            Symfony Filesystem Component
symfony/finder                      v4.2.2            Symfony Finder Component
symfony/flex                        v1.1.8            Composer plugin for Symfony
symfony/form                        v4.2.2            Symfony Form Component
symfony/framework-bundle            v4.2.2            Symfony FrameworkBundle
symfony/http-foundation             v4.2.2            Symfony HttpFoundation Component
symfony/http-kernel                 v4.2.2            Symfony HttpKernel Component
symfony/inflector                   v4.2.2            Symfony Inflector Component
symfony/intl                        v4.2.2            A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/monolog-bridge              v4.2.2            Symfony Monolog Bridge
symfony/monolog-bundle              v3.3.1            Symfony MonologBundle
symfony/options-resolver            v4.2.2            Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.5            A pack for the Doctrine ORM
symfony/phpunit-bridge              v4.2.2            Symfony PHPUnit Bridge
symfony/polyfill-apcu               v1.10.0           Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype              v1.10.0           Symfony polyfill for ctype functions
symfony/polyfill-intl-icu           v1.10.0           Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring           v1.10.0           Symfony polyfill for the Mbstring extension
symfony/polyfill-php70              v1.10.0           Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72              v1.10.0           Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                     v4.2.2            Symfony Process Component
symfony/profiler-pack               v1.0.4            A pack for the Symfony web profiler
symfony/property-access             v4.2.2            Symfony PropertyAccess Component
symfony/routing                     v4.2.2            Symfony Routing Component
symfony/security-bundle             v4.2.2            Symfony SecurityBundle
symfony/security-core               v4.2.2            Symfony Security Component - Core Library
symfony/security-csrf               v4.2.2            Symfony Security Component - CSRF Library
symfony/security-guard              v4.2.2            Symfony Security Component - Guard
symfony/security-http               v4.2.2            Symfony Security Component - HTTP Integration
symfony/stopwatch                   v4.2.2            Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.2.5            Symfony SwiftmailerBundle
symfony/translation                 v4.2.2            Symfony Translation Component
symfony/twig-bridge                 v4.2.2            Symfony Twig Bridge
symfony/twig-bundle                 v4.2.2            Symfony TwigBundle
symfony/validator                   v4.2.2            Symfony Validator Component
symfony/var-dumper                  v4.2.2            Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                v4.2.2            A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle         v4.2.2            Symfony WebProfilerBundle
symfony/web-server-bundle           v4.2.2            Symfony WebServerBundle
symfony/yaml                        v4.2.2            Symfony Yaml Component
theseer/tokenizer                   1.1.0             A small library for converting tokenized PHP source code into XML and potentially other formats
twig/extensions                     v1.5.4            Common additional features for Twig that do not directly belong in core
twig/twig                           v2.6.0            Twig, the flexible, fast, and secure template language for PHP
vlucas/phpdotenv                    v2.5.2            Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                    1.4.0             Assertions to validate method input/output with nice error messages.
white-october/pagerfanta-bundle     v1.2.3            Bundle to use Pagerfanta with Symfony2
zendframework/zend-code             3.3.1             provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-eventmanager     3.2.1             Trigger and listen to events within a PHP application

* Suite configuration:

```yml
# paste suite config here
```

**Comment by tacman** [comment]
I'll give it a try.  I'm not particularly good with git forks and such.

**Comment by Naktibalda** [comment]
I updated dependencies and enabled code coverage in configuration: https://github.com/Codeception/symfony-demo/pull/13
