### ISSUE TITLE
Doctrine `grabEntitiesFromRepository` with parameter `not null`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5347]
It would be nice if Doctrine's `grabEntitiesFromRepository()` and `grabEntityFromRepository()` would offer a way to use `IS NOT NULL` as criteria.

Should I could come up with a pull request for this? It would be just another `elseif` here: https://github.com/Codeception/Codeception/blob/2.5/src/Codeception/Module/Doctrine2.php#L533

But the harder question is: How do we write it in PHP? `IS NULL` is already implemented as `array('field' => null)`. Any suggestions for the negation?

BTW: `null` isn't documented at all - I would do that too.

**Comment by ThomasLandauer** [comment]
Or maybe a more general approach would be better which also covers other comparison operators like `<` and `>=` and `!=`?

**Comment by alexkunin** [comment]
This could be implemented like this:

1. In Doctrine2.php:

```php
   // ...
} elseif (is_callable($val)) {
    $val($qb);
} else {
   // ...
```

2. Later in tests:

```php
$es = $this->grabEntitiesFromRepository(Entity::class, [
    'field1' => 'some value',
    'field2' => 'some other value',
    function ($qb) { $qb->andWhere('s.field3 IS NOT NULL'); },
]);

// or, somewhere in utility class, or UnitTester, etc.:
class TestUtils {
    public static function isNotNull($field) {
        function ($qb) use ($field) { $qb->andWhere("s.$field IS NOT NULL"); },
    }
}

// and later in tests:
$es = $this->grabEntitiesFromRepository(Entity::class, [
    'field1' => 'some value',
    TestUtils::isNotNull('field3'),
]);
```

As you can see it is very flexible, and allows user to implement any criteria.

Alias `s` can be added to documentation, or passed as parameter. Also, one can use `QueryBuilder::getRootAliases`, but with that code becomes somewhat bloated.

Also, one could pass instance of `Doctrine\ORM\Query\Expr\Base` as field value, but callback seems to be easier to use.

One caveat is that `is_callable` could false-positive on a legit field value (maybe somebody has real string value like "is_string" or "trim" in DB). So, more strict `$val instance of \Closure` might work better, but this limits usage to closures only, and static class members will need to be wrapped in `function (...) { ... }`.
