### ISSUE TITLE
Difficulties asserting Symfony's session flash message

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5351]
When trying to assert a flash message (see https://symfony.com/blog/new-in-symfony-3-3-improved-flash-messages ), in a functional test I'm observing this behavior:

This works:
```php
$I->see('Sorry');
```

But this doesn't:
```php
$I->see('Sorry', ['css'=>'body']);
```

When running the test with `--debug` flag, I can see that the flash message is included in the logged page source (blue font in console).  
However, when Codeception prints the error message ('Failed asserting that any element by '"css":"body"' on page...'), the flash message is *not* included in the printed page source (white font in console).

This makes me *suspect* that: In the case when no CSS selector is given (`$I->see('Sorry');`), Codeception just searches the page source it already has. But when a CSS selector is given (`$I->see('Sorry', ['css'=>'body']);`), Codeception re-requests the page, and on this second request the flash message is not shown anymore.  
I didn't verify this assumption.

I'm not sure if this is related to https://github.com/Codeception/Codeception/issues/2123

**Comment by TavoNiievez** [comment]
hey @ThomasLandauer is this specific to phpbrowser or does it also happen in webdriver?

**Comment by ThomasLandauer** [comment]
Sorry, took me a while to set this up...  
Result: In an acceptance test (chrome with chromedriver) it works correctly!
