### ISSUE TITLE
FTP module

### ISSUE THREAD

**Issue by kardagan** [Codeception/Codeception#5363]
Hi,

The FTP module require "phpseclib/phpseclib": "0.3.6" and phpseclib is now in 2.0.13.
In this version \Net_SFTP and \Crypt_RSA don't exist animore, remplaced by phpseclib\Crypt\RSA and phpseclib\Net\SFTP.

I see 3 way to fix it : 
- juste remplace classes but will not work anymore for those who use the old version.
- add version in config to know witch class to use (my prefered)
- create a new ftp module

what's your opinion ?

**Comment by Naktibalda** [comment]
Thanks for raising this issue.
The first option would be the best if we could change version constraint in composer.json, but it isn't there, so this option is the worst.

It looks like API hasn't changed, so we only need to change 3 places - where 2 classes you mentioned above are used and `NET_SFTP_LOCAL_FILE` constant.
It would be the best ot check existence of the classes.

```php
if (class_exists('Net_SFTP')) {
    $this->ftp = new \Net_SFTP($this->config['host'], $this->config['port'], $this->config['timeout']);
} elseif (class_exists('phpseclib\Net\SFTP')) {
    $this->ftp = new \phpseclib\Net\SFTP($this->config['host'], $this->config['port'], $this->config['timeout']);
} else {
    throw ModuleException('phpseclib/phpseclib library is not installed');
}

```
And update docblock to use the latest version of phpseclib.

**Comment by kardagan** [comment]
I've make the PR : https://github.com/Codeception/Codeception/pull/5364
