### ISSUE TITLE
Symfony panther

### ISSUE THREAD

**Issue by kardagan** [Codeception/Codeception#5365]
Hi,

I would like to use https://github.com/symfony/panther in my tests, how to do it ?

Have you somethings in progress ? if not where to start, ? build a copy of symfony module, make a conf to symfony module to inject panther ?

**Comment by Naktibalda** [comment]
It looks like competitor of Codeception to me.

Using it in a module doesn't make much sence to me, but you could make your Test classes extend `PantherTestCase` if you want to try it out.

**Comment by kardagan** [comment]
for me it's not a competitor of Codeception, juste a new web-renderer with javascript execution

**Comment by Naktibalda** [comment]
It doesn't execute javascript, it uses Selenium or ChromeDriver through php-webdriver library, which is the same as Codeception WebDriver module.

Symfony Panther provides functionality similar to Symfony, WebDriver and PhpBrowser modules.
