### ISSUE TITLE
Jquery Colorbox  : Unable to fill fields in pop up window .. pop action using Colorbox

### ISSUE THREAD

**Issue by aditya-** [Codeception/Codeception#537]
Dear Team,

I am doing acceptance tests using selenium 2 ..we are  using Jquery Colorbox for pop up action in our application

Recently i found a thing that i was unable to fill fields in pop up window .. 

Using codeception i achieved 85% automation for my application ..Really great framework.. but i tired to finish this action but every time it was failing

I tried executeJs scenario for accessing element though JavaScript  it was failed ..
I even tried moveMouseOver and JavaScript manipulate method suggested by @wyhmichael  ..

Here is that link : https://github.com/Codeception/Codeception/issues/504

**Comment by santosh092585** [comment]
Really its great....guys can you help me same problem in java platform..actually i unable to understand in php framework

**Comment by santosh092585** [comment]
actually i am working in selenium with java. but unable to do operation on jquery colorbox page.

**Comment by aditya-** [comment]
@santosh092585 codeception based on Facebook webdriver which was created from Selinum bindings only. For your issue I've assigned to my friend who is working on Selenium2. I will get back to you if any update is there. meanwhile you can check these links : http://stackoverflow.com/questions/19403949/how-to-handle-pop-up-in-selenium-webdriver-using-java
http://stackoverflow.com/questions/14939298/handling-a-popup-window-using-selenium
