### ISSUE TITLE
stdout codecept run

### ISSUE THREAD

**Issue by aWuttig** [Codeception/Codeception#5378]
We try to use codeception to monitor some basic features of our application. For this we use zabbix and call codeception via externalScript.

How can we achieve that codeception only returns 0 or 1 as stdout. Zabbix do not need any more informations. Should we wrap the codecept run call with some other command?

**Comment by Naktibalda** [comment]
You could redirect output and print the exit code. (0 means success)
```bash
codecept run >/dev/null ; echo $?
```

**Comment by aWuttig** [comment]
@Naktibalda fantastic! thank you!
