### ISSUE TITLE
Both option --silent, and extension SimpleReporter's silent reconfigure don't work

### ISSUE THREAD

**Issue by Shardj** [Codeception/Codeception#5381]
I've been trying to silence codeceptions default output and replace it with my own because the default output for tests using @dataprovider isn't good enough, so I've implemented a custom extension extending SimpleReporter. This is listed under the Codeception documentation https://codeception.com/extensions

In the _initialize() function in the SimpleReporter extension you see this line `$this->_reconfigure(['settings' => ['silent' => true]]); // turn off printing for everything else` however, this doesn't turn off printing for anything. The config is being correctly applied, I've checked with xdebug, it's just the config never used. This is pretty well documented behavior, and the whole point of this extension is to override default output, so I'm surprised this isn't working as intended. Please do tell me if I've missed something here.

Interestingly running with --silent does seem to half work, it silences everything apart from a `[+]` or `[-]` echoed for each test. Then times and such at the bottom. Example:

```
[+] [+] [+] [+] [+] [+] [+] [+] [+] [+] [+] [+] [+] [-] [+]

Time: 5.06 seconds, Memory: 22.00MB

There was 1 failure:

---------
```

**Comment by kaktusas2598** [comment]
I am having the same issue. I would like to disable Console subscriber, so it doesn't print any output. I want to print output only using custom reporter extension, but like for this person, only "--silent" CLI option seems to work.

**Comment by Shardj** [comment]
@kaktusas2598 I've figured out that using --ext {ext_name} works (mostly), but that isn't really good enough, I need this extension used every time the suite of tests are run and I don't want to type in --ext every time.

**Comment by Shardj** [comment]
@kaktusas2598 Previously I was enabling the extension with {suitname}.suite.yml and trusting _support to autoload it (which it did, xdebug confirmed that). But apparently whatever that is doing is fucking broken (excuse the language, this has been frustrating), so here's the alternative and my reasoning that took me there:

Okay, I figured the issue must've been that the file was being loaded too late since --ext worked (mostly), so I spent the last half an hour doing trial and error how to set up a _bootstrap.php file to autoload as soon as codeception starts instead of my current _support autoloading. Since there's no documentation on this it is a fucking pain in the ass to figure out and I don't know if any of this is correct.

So you need two _bootstrap.php files minimum for some reason, one goes in your codecept directory, this has to `include` the filepath to your extension, then you need a _bootstrap.php file in each of your suite directories (unit, acceptance, whatever) those ones are empty, don't ask me why you need them or why they're empty because I don't know, it doesn't work without them. Then you need to point your top level codeception.yml file to the main _bootstrap.php file with

```
settings:
    bootstrap: _bootstrap.php
```

Your extension is now being autoloaded by this weird bootstrap.php setup. Now for more weirdness. Next we need to enable the extension, but hey guess what, you can't enable extensions on a per suite basis unlike the non working previous method I was using, you can't use your {suitname}.suite.yml files for this, you have to put them in the top level codeception.yml file too! Make sure to get the namespace right. And I hope you don't mind all of your suites having the same extensions.

```
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\CustomReporter
```

**Comment by Shardj** [comment]
@DavertMik got any ideas of how to get around this? Or if you have an example of an implementation of SimpleReporter that silences correctly that would be great. I'm struggling to find documentation that accurately describes how extensions are supposed to be implemented, the documentation is a bit lax here https://codeception.com/extensions#simplereporter

**Comment by Shardj** [comment]
Okay autoloading in composer removes the need for the pointless _bootstrap files which is nice. Still have the issue that you can only enable extensions for every actor at once.

**Comment by Naktibalda** [comment]
In Codeception 5.0 [SimpleReporter ](https://github.com/Codeception/Codeception/blob/11dca7f51bed01ec9800dd4110bd56b6772fd49e/ext/SimpleReporter.php) was cleaned up and doesn't print any test summary,
here is full output:
![image](https://user-images.githubusercontent.com/395992/174831274-3e2a7c03-9a7b-4dd7-9d27-7f6c1bedfda2.png)
