### ISSUE TITLE
Missing 2.5.3 and 2.5.4 tagged image from docker registry

### ISSUE THREAD

**Issue by OneEyedSpaceFish** [Codeception/Codeception#5384]
There's been a release 9 days ago, yet there's no tagged image under that version in docker hub.

**Comment by OneEyedSpaceFish** [comment]
Okay so, this seems to persist. 2.5.4 is missing from the registry too.

@Naktibalda @DavertMik 
Is there something I could help out with by any chance?

**Comment by dmartinhorodrigues** [comment]
The problem persists with the 2.5.5 release, there's no tag update in docker hub since v2.5.2.

**Comment by OneEyedSpaceFish** [comment]
@dmartinhorodrigues 
@DavertMik 
@Naktibalda 

Okay, so I've pushed my own cc builds until this is sorted.
All missing versions had been built and pushed there.

[temp-repo](https://hub.docker.com/r/oneeyedspacefish/codeception)

I'll leave this there as long as I can, but keep in mind that this is only a temporary repo, and it only should be used till the main one has been fixed.
(I've got no access to do that)

**Comment by niclashoyer** [comment]
3.0.0 is also missing :disappointed:

**Comment by OneEyedSpaceFish** [comment]
@niclashoyer Yeah, every version is missing since  2.5.3 it seems.
I created my own temporary repo while I'm waiting for someone to have a look at the official docker-hub account as I've got no access.

Feel free to use mine until there's a fix:
https://hub.docker.com/r/oneeyedspacefish/codeception

**Comment by OneEyedSpaceFish** [comment]
Closing this issue, new build `3.0.1` is now available in the official repo.
