### ISSUE TITLE
Running single codeception test by annotated id

### ISSUE THREAD

**Issue by aWuttig** [Codeception/Codeception#5400]
We annotated our test methods with:

`@group test_id_<timestamp>`

and then we run them by 

`codecept run -g test_id_<timestamp>`

to run a single test. Running it with ClassName::MethodName is often not suitable...

If we also use the `@depends` annotation this will not work anymore, because only the test with the group id will be executed and skipped, because the dependent test is not part of the group.

My question is. Has codeception some annotation like @test_id: 123456 to call: 

`codecept run --test_id 123456`

**Comment by Naktibalda** [comment]
> Has codeception some annotation like @test_id: 123456 to call:

No
