### ISSUE TITLE
Can't fill field with my text

### ISSUE THREAD

**Issue by HenrikasB** [Codeception/Codeception#5407]
#### What are you trying to achieve?
Trying to create a test which select specific input and writes my text.
#### What do you get instead?
Receiving an error in the step where I try to select and write text
> Provide console output if related. Use `-vvv` mode for more details.

```bash
[PHPUnit\Framework\Exception] Array to string conversioon
```

```php
 public function successTest(AcceptanceTester $I) {
        $I -> wantTo("Created test case for login");
        $I->amOnPage('link');
        $I->see("PRISIJUNGTI");
//        $I->click('input.form-control');
        $I->fillField('.form-control','myText');
    }
```

**Comment by Naktibalda** [comment]
@HenrikasB Please run this test with `-vvv` parameter and provide a stacktrace.

**Comment by Naktibalda** [comment]
HenrikasB solved this issue by changing selector parameter to something else.
No useful debugging information was provided.
