### ISSUE TITLE
tearDownAfterClass called multiple times with every suite

### ISSUE THREAD

**Issue by exteon** [Codeception/Codeception#5416]
#### What are you trying to achieve?

For each Test\Unit class, I expect tearDownAfterClass is called once after the tests are run.

#### What do you get instead?

If there are multiple unit suites defined, for the classes in the first suite, tearDownAfterClass is called after the first suite is run and again after the second suite is run.

I think it has something to do with the hooks piling up in Codeception\Event\SuiteEvent\BeforeAfterTest and never cleaned up. Probably should be cleaned up at the end of the suite.

**Comment by Naktibalda** [comment]
It took one line of code to fix this issue :)
