### ISSUE TITLE
shouldReport method is missing for Laravel5 connector ExceptionHandlerDecorator

### ISSUE THREAD

**Issue by xevsy** [Codeception/Codeception#5432]
#### What are you trying to achieve?

https://github.com/Codeception/Codeception/commit/fbd197a32a4d4f5024afa4d1f027a8cde1ec2129
This part is missing 

Can you please include it to version 2.6

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by xuanquynh** [comment]
I have been waiting for the new release of codeception that is Compatible with Laravel 5.8.

**Comment by fbidu** [comment]
Just ran into this issue! +1

**Comment by Naktibalda** [comment]
2.5.5 was released today.
