### ISSUE TITLE
Possibility to use PhpBrowser in unit testing

### ISSUE THREAD

**Issue by exteon** [Codeception/Codeception#5434]
We would see a great benefit if, for test uniformisation, we could use the PhpBrowser functions in unit testing to verify the HTML output (possibly fragments) of procedurally run code. At this moment we use a helper based on DOMDocument to validate HTML output of tested functions.

So it would be nice if in some future we would have a way to load a HTML page/fragment (as string) into PhpBrowser, with possibly a way to set context (at least base href) which would enable a mixed unit/functional mode.

**Comment by Naktibalda** [comment]
All HTML verification happens in InnerBrowser class which is extended by PhpBrowser and all framework modules.
Look at framework modules for ideas how to integrate your codebase to it.

**Comment by exteon** [comment]
Thanks, we did look at it, but there appears no easy way to circumvent the `$client ` - driven content (and all the assumptions it relies on), so the shortest way between here and there would be to make a whole dummy client / client wrapper, which seems very counter-intuitive. Also it is not clear to us how it would help us parse fragments without rewriting a lot of functionality, so it looks much more productive for us to just go to `Symfony\Component\DomCrawler`  directly. It would be nicer though if the PhpBrowser/InnerBrowser could be driven by content so that the same methods (and hence the test code, i.e. assertions etc) would be consistent and maintained in the same place.
