### ISSUE TITLE
Should installation create `.yaml` or `.yml` files?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5438]
After running `composer require codeception/codeception --dev` I'm getting this output in the console:

>  Bootstrapping Codeception 
File codeception.yaml created       <- global configuration
tests/unit created                  <- unit tests
tests/unit.suite.yaml written       <- unit tests suite configuration
tests/functional created            <- functional tests
tests/functional.suite.yaml written <- functional tests suite configuration
tests/acceptance created            <- acceptance tests
tests/acceptance.suite.yaml written <- acceptance tests suite configuration

However, the actual name of the mentioned files is `.yml`, not `.yaml`. Is this just an error in the output? Or are there cases where the files are called actually `.yaml`?

* Codeception version: 2.5.4

**Comment by Naktibalda** [comment]
I have no idea how you got `yaml` in the output.

[The code](https://github.com/Codeception/Codeception/blob/2.5/src/Codeception/Template/Bootstrap.php#L47) says .yml
and I got this output `tests/unit.suite.yml written       <- unit tests suite configuration`

**Comment by ThomasLandauer** [comment]
Hm, good question ;-)  
I found this in the [changelog of 2.5.1](https://github.com/Codeception/Codeception/commit/e0a658c64e98811a6fd4f6aa7c3222e0609066a9#diff-ce6b4955d5f2dd95de28330bbfb2f96bR26):
> Use `*.yaml` for params loading

What does it mean?
I'm using Symfony (which switched to `*.yaml` recently).

**Comment by DavertMik** [comment]
I think I pointed to *.yaml as a format here. 
But yeah, we still use .yml by default.

**Comment by Naktibalda** [comment]
Your output came from this symfony recipe file: https://github.com/symfony/recipes-contrib/blob/master/codeception/codeception/2.3/post-install.txt

**Comment by Naktibalda** [comment]
> > Use *.yaml for params loading
>
> What does it mean?

https://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Parameters
