### ISSUE TITLE
 Improvement in reading the .yml parameters

### ISSUE THREAD

**Issue by rafiuskss** [Codeception/Codeception#5443]
#### What do you get instead?

* PHP Version:7.3
* Operating System:W10
* Installation type: Composer
* List of installed packages (`composer show`)

Dear, I've lost two hours to solve a white space problem at the end of a last parameter. If you can add a "trim ()" after reading the parameters, it would be helpful. Thankful.

**Comment by Naktibalda** [comment]
Probably it isn't going to happen.

**Comment by Naktibalda** [comment]
If you strongly believe that your yaml file was parsed incorrectly, raise an issue of symfony/yaml component at https://github.com/symfony/symfony/issues

**Comment by rafiuskss** [comment]
Yes it was analyzed my dear, but the question is that at the end of the parameter a blank could easily go unnoticed and until the uauario identifies it was gone a long time.

**Comment by Fenikkusu** [comment]
Yaml files allow the strings to be quoted. Perhaps a good habit to get into, as then the value in the quotes are loaded.

```yaml
value:
  subvalue: 'some-value'
```

http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html

**Comment by rafiuskss** [comment]
Obrigado cara, nem me atentei nisso. Essa opção resolve.
