### ISSUE TITLE
Standardizing Framework Modules

### ISSUE THREAD

**Issue by Fenikkusu** [Codeception/Codeception#5446]
Something I've been pondering lately. One of the things that I like about Codeception is that most everything is the same regardless of which module you use. There are however instances where it is not. For example, in Phalcon, there is the method `grabServiceFromDi` method, but in Laravel, it is `grabService`.  I think that we should create a new interface to the effect of `MvcFrameworkModuleInterface` that defines all the common functionality among MVC like `grabRecord`, `grabServiceFromDi`, etc. Alternatively, having multiple interfaces like `HasModelInterface`, `HasDependencyInjectorInterface`, etc might work as well. 

I work with a number of different projects that are each based on different frameworks, and I often have to go back to the documentation and check which method to use. If such interfaces were made, and subsequently enforced, then each Module would effectively be the same, preventing the need for such changes.

Additionally, if someone were to suddenly change the framework (as I am currently having to do on a project), there would be less need to update/change the testing since it would effectively be the same.

I'd be interested to hear anyone else's thoughts on this.

**Comment by Naktibalda** [comment]
If portability is important, you should avoid using framework specific methods and use only methods of [Web]](https://github.com/Codeception/Codeception/blob/2.5/src/Codeception/Lib/Interfaces/Web.php) interface.

`grabRecord` method is defined in existing [ActiveRecord](https://github.com/Codeception/Codeception/blob/2.5/src/Codeception/Lib/Interfaces/ActiveRecord.php) interface which is implemented by Laravel5, Lumen, Phalcon and Yii2 modules.

**Comment by DavertMik** [comment]
I got your point, here are my thoughts. 
Unlike `haveRecord`, `seeRecord`, etc get service from a container is always framework dependent. You can't port a specific part from one framework to another as DI container and services will be absolutely different. I agree that documentation and method naming is different but implementation is absolutely different as well, the service returned can't be standardized across frameworks.

However, if you want, you can try to create this interface across frameworks and provide corresponding implementations to framework modules.
