### ISSUE TITLE
unitTest initialize yaf framework

### ISSUE THREAD

**Issue by yucuifang** [Codeception/Codeception#5453]
I am trying to initialize yaf framework in tests/unit/_bootstarp.php ,but I get the following wrong tips,how can I fix it?

![image](https://user-images.githubusercontent.com/41798238/55076579-c761b600-50d0-11e9-94fa-5275d55e82f8.png)

Here is my source code in tests/unit/_bootstarp.php:
![image](https://user-images.githubusercontent.com/41798238/55077112-ed3b8a80-50d1-11e9-8fc7-51b11fe93e3c.png)

**Comment by Naktibalda** [comment]
Yaf autoloader tries to load dependency of Codeception and fails. 
You have to make it collaborate with composer's autoloader by either making it have lower precedence or by making it fail gracefully when he can't find class.

It is up to you to figure out how to do that.

**Comment by yucuifang** [comment]
> Yaf autoloader tries to load dependency of Codeception and fails.
> You have to make it collaborate with composer's autoloader by either making it have lower precedence or by making it fail gracefully when he can't find class.
> 
> It is up to you to figure out how to do that.

But when I try to load composer's autoloader and yaf autoloader together in my own project not codeception, they collaborate well, no matter who's precedence  higher.
It just doesn't work in codeception，I really don't know how to fix it.

**Comment by Naktibalda** [comment]
Right, yaf autoloader uses `include` which emits E_WARNING on failure.
It does not affect your application code, but PHPUnit/Codeception is less forgiving.

Try to disable warning with [error_level ](https://codeception.com/docs/04-FunctionalTests#Error-Reporting) setting - `error_level: "E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING"`.

Please let me know if it works.

**Comment by yucuifang** [comment]
> Right, yaf autoloader uses `include` which emits E_WARNING on failure.
> It does not affect your application code, but PHPUnit/Codeception is less forgiving.
> 
> Try to disable warning with [error_level ](https://codeception.com/docs/04-FunctionalTests#Error-Reporting) setting - `error_level: "E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING"`.
> 
> Please let me know if it works.

Thanks，I have tried to add the following code before I new Yaf Application, but it still doesn't work.
![image](https://user-images.githubusercontent.com/41798238/55204059-a9976c80-5208-11e9-8323-62f220963a08.png)

**Comment by Naktibalda** [comment]
Try to make a config change.

**Comment by yucuifang** [comment]
> Try to make a config change.

It  works when I add the following config:
![image](https://user-images.githubusercontent.com/41798238/55327273-49305580-54bc-11e9-8028-0056220cb260.png)
Thanks a lot!
