### ISSUE TITLE
Codeception exit code breaking Bitbuckets CI Pipeline

### ISSUE THREAD

**Issue by Robdebert** [Codeception/Codeception#5459]
_This ticket continues on https://github.com/Codeception/Codeception/issues/14 Where which is closed._

There might also be a problem with bitbuckets CI-pipelines.
The pipeline build says"ok" (green), although Codeception found errors.

I guess bitbucket pipelines are checking if anything returns the exit-code "2" and otherwise everything is ok for them.

Could there also be an option to set the exit-code to 2 instead of 1? Something like "--convert_warnings_to_errors" ? The --no-exit parameter was already included by the previous issue, to not exit with an error. but here i need to force an error, when codeception found anything

**Comment by Naktibalda** [comment]
Have you tried to use `codecept run || (exit 2)` to change exit code?

**Comment by Robdebert** [comment]
Yes. But does not seem to work either.
Also i was not able to find any documentatino for the Bitbucket-Pipeline to this issue.

![image](https://user-images.githubusercontent.com/1737455/72888776-877a5800-3d0e-11ea-8102-828c059968f2.png)

**Comment by Robdebert** [comment]
**Solution: This worked for me**, when i try to run codeception acceptance tests using the bitbucket pipeline:

`codecept run --debug  || exit 255`


Thanks a lot for that hint @Naktibalda
