### ISSUE TITLE
phpunit-report.xml file is not generated

### ISSUE THREAD

**Issue by mkoitz** [Codeception/Codeception#5460]
#### What are you trying to achieve?
I am trying to generate the phpunit-report.xml file as report.xml to be used by sonar-parser.

#### What do you get instead?
the file is not generated, but the console output states that it is generated. 

> Provide console output if related. Use `-vvv` mode for more details.

```bash
> @php vendor/bin/codecept run -vvv unit,functional --steps --phpunit-xml=report.xml --coverage --coverage-xml
Codeception PHP Testing Framework v2.5.5
Powered by PHPUnit 7.5.1 by Sebastian Bergmann and contributors.
...
- PHPUNIT-XML report generated in file:///Users/user/worspace/tests/_output/report.xml
...
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.5.5
* PHP Version:
PHP 7.2.15 (cli) (built: Feb 26 2019 10:43:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.2.15, Copyright (c) 1999-2018, by Zend Technologies

* Operating System: MacOS 10.14.3 (18D109)
* Installation type: Composer
* List of installed packages (`composer show`)
aws/aws-sdk-php                    3.82.3             AWS SDK for PHP - Use Amazon Web Services in your PHP project
behat/gherkin                      v4.5.1             Gherkin DSL parser for PHP 5.3
cakephp/core                       3.7.1              CakePHP Framework Core classes
cakephp/utility                    3.7.0              CakePHP Utility classes such as Inflector, String, Hash, and Security
codeception/codeception            2.5.5              BDD-style testing framework
codeception/phpunit-wrapper        7.5.0              PHPUnit classes used by Codeception
codeception/stub                   2.0.4              Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/cache                     v1.8.0             Caching library offering an object-oriented API for many cache backends
doctrine/dbal                      v2.9.1             Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/event-manager             v1.0.0             Doctrine Event Manager component
doctrine/instantiator              1.1.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.6.0              A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.3              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.5.2              PSR-7 message implementation that also provides common utility methods
league/climate                     3.4.1              PHP's best friend for the terminal. CLImate allows you to easily output colored text, special formats, and more.
league/container                   3.2.2              A fast and intuitive dependency injection container.
league/flysystem                   1.0.49             Filesystem abstraction: Many filesystems, one API.
league/flysystem-aws-s3-v3         1.0.21             Flysystem adapter for the AWS S3 SDK v3.x
masterminds/html5                  2.4.0              An HTML5 parser and serializer.
meng-tian/async-soap-guzzle        v0.2.4             An asynchronous SOAP client build on top of Guzzle.
meng-tian/php-async-soap           1.0.2              Interface for asynchronous SOAP client.
meng-tian/php-soap-interpreter     1.0.2              A PHP library for interpreting SOAP messages.
meng-tian/soap-http-binding        0.2.3              A PHP library for binding SOAP messages to PSR-7 HTTP messages.
monolog/monolog                    1.24.0             Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php             2.4.0              Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                  1.8.1              Create deep copies (clones) of your objects
nicolab/php-ftp-client             v1.4.1             A flexible FTP and SSL-FTP client for PHP. This lib provides helpers easy to use to manage the remote files.
paragonie/random_compat            v9.99.99           PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                   1.0.3              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1              Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a D...
phpdocumentor/type-resolver        0.4.0             
phpseclib/phpseclib                2.0.13             PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpspec/prophecy                   1.8.0              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          6.1.4              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          2.0.2              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  2.0.0              Utility class for timing
phpunit/php-token-stream           3.0.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.5.1              The PHP Unit Testing framework.
predis/predis                      v1.1.1             Flexible and feature-complete Redis client for PHP and HHVM
psr/container                      1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                   1.0.1              Common interface for HTTP messages
psr/log                            1.1.0              Common interface for logging libraries
querypath/querypath                3.0.5              HTML/XML querying (CSS 4 or XPath) and processing (like jQuery)
ralouphie/getallheaders            2.0.5              A polyfill for getallheaders.
roave/security-advisories          dev-master ac7afca Prevents installation of composer packages with known security vulnerabilities: no API, simply require it
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2              Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.1              Diff implementation
sebastian/environment              4.0.1              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0              Snapshotting of global state
sebastian/object-enumerator        3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.1              Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
seld/cli-prompt                    1.0.3              Allows you to prompt for user input on the command line, and optionally hide the characters they type
squizlabs/php_codesniffer          3.4.0              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
symfony/browser-kit                v4.2.1             Symfony BrowserKit Component
symfony/console                    v4.2.1             Symfony Console Component
symfony/contracts                  v1.0.2             A set of abstractions extracted out of the Symfony components
symfony/css-selector               v4.2.1             Symfony CssSelector Component
symfony/dom-crawler                v4.2.1             Symfony DomCrawler Component
symfony/event-dispatcher           v4.2.1             Symfony EventDispatcher Component
symfony/finder                     v4.2.1             Symfony Finder Component
symfony/polyfill-ctype             v1.10.0            Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.10.0            Symfony polyfill for the Mbstring extension
symfony/process                    v4.2.1             Symfony Process Component
symfony/yaml                       v4.2.1             Symfony Yaml Component
theseer/tokenizer                  1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
vlucas/phpdotenv                   v2.5.1             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                   1.4.0              Assertions to validate method input/output with nice error messages.
zendframework/zend-diactoros       1.8.6              PSR HTTP Message implementations
* Suite configuration:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
include: .
settings:
    bootstrap: ../__bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: false
    include:
      - ./src/*
```

**Comment by Naktibalda** [comment]
> codeception/phpunit-wrapper 7.5.0 PHPUnit classes used by Codeception

Upgrade `codeception/phpunit-wrapper` library, this feature was implemented in 7.6.0 version,
but the last version is 7.7.1, so upgrade to it instead.
