### ISSUE TITLE
Is it possible to fill in data providers dynamically in Codeception?

### ISSUE THREAD

**Issue by codemark135** [Codeception/Codeception#5475]
I am trying to fetch the data from other site and use it in a data provider.
If possible, it would be the best if I could use the test in same Cest for data gathering (maybe even _before method) . Afterwards,  the results from that test could be injected into data provider and used in different test. Of course, @depends annotation would be used, so second test would not start executing without first one is totaly executed.

So what I need looks something like this:

/**
     * @return array
     */
    protected function affiliateFeedProvider()
    {
        return [
            ['type' => 't1',           'link1' => DynamicalFetchedElement[1]],
            ['type' => 't2',           'link2' => DynamicalFetchedElement[2]],
            ['type' => 't3',           'link3' => DynamicalFetchedElement[3]],
            ['type' => 't4',           'link4' => DynamicalFetchedElement[4]],
      
Afterwards, the DynamicalFetchedElement[n] would be provided into tests using example['link1'], ..etc

#### What do you get instead?

It seems to me that currently all data in provider must be staticaly inserted since the tests in Cest wont even start if the data provider is not provided with values in moment of execution start.  Have I concluded correctly?

Is there some workaround for this? Maybe using Helper class?

Thx!

**Comment by Naktibalda** [comment]
This is the same issue as #5549
You correctly identified that data providers are executed at very early phase of test execution.

Proposed workaround is to move data gathering code from test method to data provider itself.
