### ISSUE TITLE
chromedriver not working with codeception

### ISSUE THREAD

**Issue by jesxs** [Codeception/Codeception#5487]
#### What are you trying to achieve?
I'm trying to make automatic tests with php, and from the codeception website I did read that you can use chromedriver directly with codeception, without using Selenium.

#### What do you get instead?
While running chromedriver, and executing my test I get the following error

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Acceptance Tests (1) ---------------------------------------------------------------------------------------------------
FirstCest: Login successfully
Signature: FirstCest:loginSuccessfully
Test: tests\acceptance\FirstCest.php:loginSuccessfully
Scenario --
 ERROR

------------------------------------------------------------------------------------------------------------------------


Time: 1.11 seconds, Memory: 8.00 MB

There was 1 error:

---------
1) FirstCest: Login successfully
 Test  tests\acceptance\FirstCest.php:loginSuccessfully
                                                                                                        
  [Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: 'unhandled request'

                                                                                                        
#1  D:\Programas\xampp\htdocs\autTest\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:298
#2  D:\Programas\xampp\htdocs\autTest\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php:126
#3  D:\Programas\xampp\htdocs\autTest\vendor\symfony\event-dispatcher\EventDispatcher.php:212
#4  D:\Programas\xampp\htdocs\autTest\vendor\symfony\event-dispatcher\EventDispatcher.php:44

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

```

### Details

* Codeception version: 
* PHP Version: 
* Operating System: Windows 10
* Installation type: Composer
* List of installed packages (`composer show`)
behat/gherkin                      v4.6.0  Gherkin DSL parser for PHP 5.3
codeception/codeception            2.5.5   BDD-style testing framework
codeception/phpunit-wrapper        7.7.1   PHPUnit classes used by Codeception
codeception/stub                   2.1.0   Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.2.0   A small, lightweight utility to instantiate objects in PHP without invo...
facebook/webdriver                 1.6.0   A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1  Guzzle promises library
guzzlehttp/psr7                    1.5.2   PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.9.1   Create deep copies (clones) of your objects
phar-io/manifest                   1.0.3   Component for reading phar.io manifest information from a PHP Archive (...
phar-io/version                    2.0.1   Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1   Common reflection classes used by phpdocumentor to reflect the code str...
phpdocumentor/reflection-docblock  4.3.0   With this component, a library can provide support for annotations via ...
phpdocumentor/type-resolver        0.4.0
phpspec/prophecy                   1.8.0   Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          6.1.4   Library that provides collection, processing, and rendering functionali...
phpunit/php-file-iterator          2.0.2   FilterIterator implementation that filters files based on a list of suf...
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  2.1.1   Utility class for timing
phpunit/php-token-stream           3.0.1   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.5.9   The PHP Unit Testing framework.
psr/http-message                   1.0.1   Common interface for HTTP messages
ralouphie/getallheaders            2.0.5   A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup 1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2   Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.2   Diff implementation
sebastian/environment              4.1.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0   Snapshotting of global state
sebastian/object-enumerator        3.0.3   Traverses array structures and object graphs to enumerate all reference...
sebastian/object-reflector         1.1.1   Allows reflection of object attributes, including inherited and non-pub...
sebastian/recursion-context        3.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.1   Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1   Library that helps with managing the version number of Git-hosted PHP p...
symfony/browser-kit                v4.2.7  Symfony BrowserKit Component
symfony/console                    v4.2.7  Symfony Console Component
symfony/contracts                  v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/css-selector               v4.2.7  Symfony CssSelector Component
symfony/dom-crawler                v4.2.7  Symfony DomCrawler Component
symfony/event-dispatcher           v4.2.7  Symfony EventDispatcher Component
symfony/finder                     v4.2.7  Symfony Finder Component
symfony/polyfill-ctype             v1.11.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.11.0 Symfony polyfill for the Mbstring extension
symfony/process                    v4.2.7  Symfony Process Component
symfony/yaml                       v4.2.7  Symfony Yaml Component
theseer/tokenizer                  1.1.2   A small library for converting tokenized PHP source code into XML and p...
webmozart/assert                   1.4.0   Assertions to validate method input/output with nice error messages.

* Suite configuration:

```yml
actor: AcceptanceTester
modules:
      enabled:
        - WebDriver:
             url: 'http://192.168.1.213/ASTechOLE/login.php'
             window_size: false # disabled in ChromeDriver
             port: 9515
             browser: chrome
             capabilities:
                 "goog:chromeOptions": # additional chrome options
        - \Helper\Acceptance
```

**Comment by Naktibalda** [comment]
How do you start ChromeDriver?
Leading / is not necessary in path parameter on Windows.

**Comment by jesxs** [comment]
@Naktibalda I do `$ ./vendor/bin/chromedriver.exe --url-base=/wd/hub/`
(I copied the exe into there)

**Comment by Naktibalda** [comment]
Try `./vendor/bin/chromedriver.exe --url-base=wd/hub/`

**Comment by jesxs** [comment]
@Naktibalda That actually did something, I saw chrome opening at least, but it closed and gave me this error:

```
[Facebook\WebDriver\Exception\SessionNotCreatedException] session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)
```

**Comment by jesxs** [comment]
@Naktibalda yep, somehow my chrome updated. I'm going to download the correct version from chromedriver

**Comment by jesxs** [comment]
@Naktibalda Now it seems to work. But the same test which was working with phpbrowser now it doesnt really work. When it clicks 'login' it stays on the same page
