### ISSUE TITLE
Can I use while inside a test?

### ISSUE THREAD

**Issue by jesxs** [Codeception/Codeception#5490]
#### What are you trying to achieve?
I'm doing a test for a web app. The application consists on 3 checkboxes, and 1 button to go to the next question. So what I'm trying to do is to do a while loop so while there is a checkbox available, it clicks it and clicks the "next" button.

#### What do you get instead?
When it gets to the while, the test "pass" and it just finish, without executing the actual code inside the condition.

> Provide test source code if related

```php
  $I->waitForElementNotVisible('//*[@id="oleWaitMessage"]', 200);
        $I->wait(3);

        while ($I->seeElement('//*[@id="rb_0"]')){
        $I->wait(1);
            //Click answer
        $I->waitForElement('//*[@id="rb_0"]', 30);
        $I->wait(1);
        $I->click('//*[@id="rb_0"]');
        $I->wait(1);

        //click next
        $I->waitForElementClickable('//*[@id="oleNextItemBtn"]', 30); // secs
        $I->click('//*[@id="oleNextItemBtn"]');
        }
        
```

**Comment by Naktibalda** [comment]
`seeElement` throws exection if element does not exists.

Since version 3.0.0, you can use `tryTo` prefix for actions in condintions:
https://codeception.com/docs/03-AcceptanceTests#AB-Testing

```php
while ($I->tryToSeeElement('//*[@id="rb_0"]')){
```

**Comment by jesxs** [comment]
@Naktibalda That was useful, thanks
