### ISSUE TITLE
How can I run multiple instances of a test with different data?

### ISSUE THREAD

**Issue by jesxs** [Codeception/Codeception#5491]
#### What are you trying to achieve?
I already have a test which logs in into my webapp and answers some forms and submits it. I need to try how many resources the webapp can handle so I need to test it with more people.
For that I need different credentials for each instance which I have, I'm thinking about an array of user:password and a for loop, but I'm not really sure. 
My biggest concern is how to run multiple instances of the same test with different user:password for each one of them. Also the browser need to be separated because I guess the sessions would affect each other.

Also I'm using chromedriver without selenium.

I'd appreciate any suggestion about this.

Thanks in advance.

**Comment by cjshowalter** [comment]
Have you looked into data providers yet? https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers

**Comment by Naktibalda** [comment]
> I need to try how many resources the webapp can handle

Codeception is not a load testing tool.
Use JMeter or Gatling instead.
