### ISSUE TITLE
WebDriver Doesn't respond in else condition

### ISSUE THREAD

**Issue by KamranMdShaikh** [Codeception/Codeception#5504]
#### What are you trying to achieve?
         I am trying to achieve "Unsuccessful Printout" by using following code.
#### What do you get instead?
        The ChromeDriver runs well through if condition.
          I can not set else if condition.
> Provide console output if related. Use `-vvv` mode for more details.

Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 24827
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
May 11, 2019 1:20:05 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//H1[text()='Your Account Has Been Created!']"}
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-J8EUN83', ip: '192.168.1.116', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 74.0.3729.6 (255758eccf3d24..., userDataDir: C:\Users\Kamran\AppData\Loc...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:56893}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 74.0.3729.131, webStorageEnabled: true}
Session ID: 91d8f9dfe009205ffc254b20c990c8e1
*** Element info: {Using=xpath, value=//H1[text()='Your Account Has Been Created!']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at DemoOpenCart_RegisterNewAccount.main(DemoOpenCart_RegisterNewAccount.java:34)

```bash
# paste output here
``` no out put. driver doesn't work. it stuck here.
> Provide test source code if related

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class DemoOpenCart_RegisterNewAccount {

	public static void main(String[] args) throws InterruptedException {


		
		//webdriver name == test
		
		WebDriver test =new ChromeDriver();
		test.get("https://demo.opencart.com/");
		test.findElement(By.xpath("//SPAN[@class='caret']")).click();
		test.findElement(By.xpath("//A[@href='https://demo.opencart.com/index.php?route=account/register'][text()='Register']")).click();
		Thread.sleep(1000);
		test.findElement(By.xpath("//INPUT[@id='input-firstname']")).sendKeys("Zaman");
		test.findElement(By.xpath("//INPUT[@id='input-lastname']")).sendKeys("Chowdhury");
		test.findElement(By.xpath("//INPUT[@id='input-email']")).sendKeys("zamanhasan00001@gmail.com");
		
		test.findElement(By.xpath("//INPUT[@id='input-telephone']")).sendKeys("01715678910");
		test.findElement(By.xpath("//INPUT[@id='input-password']")).sendKeys("123456");
		test.findElement(By.xpath("//INPUT[@id='input-confirm']")).sendKeys("123456");
		
		
		test.findElement(By.cssSelector("#content > form > fieldset:nth-child(3) > div > div > label:nth-child(1) > input[type=\"radio\"]")).click();
		Thread.sleep(500);
		test.findElement(By.cssSelector("#content > form > div > div > input[type=\"checkbox\"]:nth-child(2)")).click();
		test.findElement(By.xpath("//INPUT[@type='submit']")).click();
		
// code runs successfully until if condition,  U may change sendkeys value of email address. 
// but else condition doesn't work when if condition doesn't match.
	
		if(test.findElement(By.xpath("//H1[text()='Your Account Has Been Created!']")) != null)
			System.out.println("Successful");

		else if(test.findElement(By.xpath("//*[@id=\"account-register\"]/div[1]")) != null)
				System.out.println("unuccessful");

		Thread.sleep(1500);
		test.close();
	}
}




```php
// paste test
```
### Details

* Codeception version:
Eclipse IDE for Java Developers
Version: 2019-03 (4.11.0)
Build id: 20190314-1200
* PHP Version: WebDriver
[New Text Document.txt](https://github.com/Codeception/Codeception/files/3167856/New.Text.Document.txt)
[New Text Document.txt](https://github.com/Codeception/Codeception/files/3167857/New.Text.Document.txt)

* Operating System: Windows 10
* Installation type: 
```yml
# paste suite config here
```

**Comment by KamranMdShaikh** [comment]
// code runs successfully until if condition,  U may change sendkeys value of email address. 
// but else condition doesn't work when if condition doesn't match.

**Comment by Naktibalda** [comment]
You aren't using Codeception
