### ISSUE TITLE
PhpStorm shows "multiple definitions exist" for MockObject because of class_aliases in shim.php

### ISSUE THREAD

**Issue by pgl** [Codeception/Codeception#5508]
#### What are you trying to achieve?

Write unit tests in PhpStorm with type-hinted mocks via inline annotations.

#### What do you get instead?

"Multiple definitions exist for class MockObject".

![image](https://user-images.githubusercontent.com/1181139/57847294-643df700-77d6-11e9-8050-d71e52aa8a52.png)

This seems to be because of `shim.php`:

![image](https://user-images.githubusercontent.com/1181139/57847165-17f2b700-77d6-11e9-9ff4-982b67244fd5.png)

It seems that with the new version of Codeception, `shim.php` is maybe no longer needed? I fixed this locally by just commenting out every line in that file and the unit tests run fine.

### Details

* Codeception version: 3.0
* PHP Version: 7.3
* Operating System: Windows
* Installation type: Phar

**Comment by Naktibalda** [comment]
This issue will definitelly be resolved in Codeception 4.0, because support for PHPUnit 5 and 6 will be dropped. It could be solved earlier by releasing codeception/stub 3.0 (or 4.0 for consistency).
https://github.com/Codeception/Stub/pull/12
