### ISSUE TITLE
Acceptance test closing randomly

### ISSUE THREAD

**Issue by jesxs** [Codeception/Codeception#5509]
I'm making parallel tests with Robo and Codecept, and sometimes they close randomly for no reason.
I get no errors, they are just running normally and close

**Comment by Naktibalda** [comment]
What do you mean by `close`?

**Comment by jesxs** [comment]
I'm using chromedriver, so chrome tabs just close

**Comment by Naktibalda** [comment]
How do you know that the test wasn't completed successfuly?

**Comment by Naktibalda** [comment]
Not enough information.
