### ISSUE TITLE
WebDriver tests refer to deprecated methods

### ISSUE THREAD

**Issue by edno** [Codeception/Codeception#5515]
Similar to #5492, I've just spotted some deprecation warnings in https://semaphoreci.com/codeception/codeception/branches/pull-request-5514/builds/1

```
6x DEPRECATION: Stub::once is deprecated in favor of \Codeception\Stub\Expected::once
5x DEPRECATION: Stub::atLeastOnce is deprecated in favor of \Codeception\Stub\Expected::atLeastOnce
DEPRECATION: Stub::exactly is deprecated in favor of \Codeception\Stub\Expected::exactly
```

I'll push a PR this week for getting rid of these deprecated Stub methods in Codeception tests.

**Comment by Naktibalda** [comment]
They are our own deprecation warning, so whoever dares to remove those deprecated methods, will have to update all tests that this change will break.

**Comment by edno** [comment]
@Naktibalda - The idea is not to remove the deprecated methods, but rather update tests so they don't use deprecated methods.

**Comment by Naktibalda** [comment]
It returned to bite me.
I deleted Codeception\Util\Stub in 5.0 branch, tests of all modules will be updated to use Codeception\Stub in order to support Codeception 5.0.
