### ISSUE TITLE
@codingStandardsIgnoreFile is specified too late in generated code

### ISSUE THREAD

**Issue by Majkl578** [Codeception/Codeception#5516]
According to [this comment](https://github.com/squizlabs/PHP_CodeSniffer/issues/2505#issuecomment-493802134) in my CodeSniffer issue, `@codingStandardsIgnoreFile` annotation needs to be specified on first two lines of the file in order to exclude the file from processing. Since Codeception places this on 6th line, the file is still being processed.

Applies to both Codeception 2.x and 3.0.

**Comment by Naktibalda** [comment]
Better late than never :) This issue will be fixed in Codeception 5.0.7.

Thank you for raising this ticket.
