### ISSUE TITLE
Error: Array to string conversion in selectOption (waitForElement works fine)

### ISSUE THREAD

**Issue by vlad88sv** [Codeception/Codeception#5517]
#### What are you trying to achieve?
select an option in a `select` element

#### What do you get instead?
Error: Array to string conversion 
> Provide console output if related. Use `-vvv` mode for more details.
```bash
  [PHPUnit\Framework\Exception] Array to string conversion  
                                                            

Scenario Steps:

 77. $I->selectOption({"css":"[name="provision.keys.feature_keys[1].value.value"]"},10) at tests/acceptance/SmartPbxCest.php:136
 76. $I->waitForElement({"css":"[name="provision.keys.feature_keys[1].value.value"]"},1) at tests/acceptance/SmartPbxCest.php:134
 75. $I->selectOption({"css":"[name="provision.keys.feature_keys[1].type"]"},"parking") at tests/acceptance/SmartPbxCest.php:133
 74. $I->selectOption({"css":"[name="provision.keys.feature_keys[0].type"]"},"presence") at tests/acceptance/SmartPbxCest.php:131
 73. $I->click({"css":"a[data-section="featureKeys"]"}) at tests/acceptance/SmartPbxCest.php:129
 72. $I->click({"css":"li.tabs-main-selector:nth-child(2) > a:nth-child(1)"}) at tests/acceptance/SmartPbxCest.php:128
```

> Provide test source code if related

```php
        $I->waitForElement(['css' => '[name="provision.keys.feature_keys[1].value.value"]'], 1);
        $I->selectOption(['css' => '[name="provision.keys.feature_keys[1].value.value"]'], 10);
```
### Details

* Codeception version: 3.0.1
* PHP Version: PHP 7.2.17-0ubuntu0.19.04.1 (cli) (built: Apr 18 2019 18:01:25) ( NTS )
* Operating System: Ubuntu 19.04
* Installation type: Phar
* List of installed packages (`composer show`): nothing installed
* Suite configuration:

```yml
actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
    step_decorators: ~        
```

**Comment by vlad88sv** [comment]
![image](https://user-images.githubusercontent.com/91489/58133657-976ef480-7be1-11e9-9dbb-bf1dd515eb1e.png)

Testing selector in Firefox console

**Comment by vlad88sv** [comment]
Never mind, tested the selector in FF and discovered that there was 4 matching objects to that selector, fine tuning the selector to match only 1 object fixed the problem.

Could I suggest to improve the error message to reflect the actual issue? - like "_More than 1 object matched the selector_"

**Comment by Naktibalda** [comment]
Could you run that test with `-vvv` flag and provide stacktrace?

**Comment by vlad88sv** [comment]
Hi, problem was solved, thank you :) :+1:
