### ISSUE TITLE
Conditional Webdriver::amOnPage()

### ISSUE THREAD

**Issue by krukru** [Codeception/Codeception#5528]
#### What are you trying to achieve?
I am creating selenium acceptance tests using the Webdriver Module. 
I would like to have a method similar to `\Codeception\Module\WebDriver::amOnPage()`, but to only trigger the action if the browser is not currently on that very same page.

For example, if the browser is on page /foo, then I would like for subsequent call to amOnPage('/foo') to just skip and not refresh the page.

#### What do you get instead?
Calling `amOnPage` multiple times in a row will perform multiple refreshes. While this is good default behaviour, I would like for a smarter way to refresh only if needed. 

This is important for me, since my Actor class has a lot of actions, each of them starting with `amOnPage('something')`. Calling these actions multiple times performs multiple refreshes, when in fact I don't wish the refresh to happen. Removing `amOnPage` alltogether seems wrong, since then the command will not work without "remembering" to navigate to the correct page (and sometimes you cannot know which page is correct).

Does selenium even support this kind of pattern and how could I create a helper for myself using codeception to refresh only if I am not on the requested page?

**Comment by DavertMik** [comment]
Write a custom helper with a method `openPageIfNotThereYet` or something like this. https://codeception.com/docs/06-ModulesAndHelpers#Accessing-Other-Modules

Access WebDriver module, where you can get browser instance and check for URL and open current page.

**Comment by krukru** [comment]
Thanks for the answer @DavertMik. 

Giving this issue further thought, I think that `amOnPage` methods should not be in Actor/Step classes. They should be in Test classes and then there is no need for such a conditional amOnPage method. Allow me to explain.

At first glance it would seem logical to keep it part of the step action, because obviously the action will not work if the browser is not on the correct page. It makes things simpler. There are examples on [reusing test code](https://codeception.com/docs/06-ReusingTestCode.html) that are putting `amOnPage` in Actor/Step actions and suggesting that it is a valid approach.

But then again, the action might not work anyways, if for example the user has not previously logged in. We don't see authentication logic included in these actions, and correctly so - since they do not belong there.

For the same reason I think that page navigation seems is a provisioning step that should be independent of the action itself. The Test class should be responsible for making sure all prerequisites are satisfied (logging in, navigating to the correct page/section, and any other things). 

Then there is no need for `openPageIfNotThereYet` because the Test class is responsible for navigation (which can again be abstracted behind a Page class) and will do it only once. 
The fact that no one else has requested such a selenium method is an indicator that it is probably not a good idea.
