### ISSUE TITLE
Code coverage not being generated for subdomains (acceptance suite)

### ISSUE THREAD

**Issue by maksimovic** [Codeception/Codeception#5536]
#### What are you trying to achieve?

I'm trying to get code coverage for our entire suite of acceptance tests, which consists of tests doing their work across several subdomains (admin, api, ussd, mobi etc).

#### What do you get instead?

Code coverage is created only for the subdomain configured in `WebDriver` module's section, or for the one for which the `c3_url` is configured (if different from `WebDriver/url`).

Note that c3.php is included in every subdomain's code: each `index.php` of a subdomain is including a `common.php` which includes `c3.php`.

I've created a dummy test whitelisting only index files from 2 subdomains to show it in pictures.

Example 1:
- `c3_url: https://admin-test.mysite.com`
- Running an acceptance test that's visiting `admin-test` and `ussd-test` subdomains.
- Result: Code coverage generated only for requests hitting `https://admin-test.mysite.com`:

<img width="947" alt="Screenshot_2019-06-06_at_14_54_51" src="https://user-images.githubusercontent.com/1126226/59034394-427edf80-886b-11e9-848e-3c2839f6b3d7.png">

Example 2:
- `c3_url: https://ussd-test.mysite.com`
- Running the same acceptance test from Example 1
- Result: Code coverage generated only for requests hitting `https://ussd-test.mysite.com`:

<img width="942" alt="Screenshot_2019-06-06_at_14_53_33" src="https://user-images.githubusercontent.com/1126226/59034416-4ad71a80-886b-11e9-95ae-3f3dc35cea23.png">

...and so on, you get the pattern: code coverage doesn't get generated for other subdomains.

### Summary:
Code coverage is not triggered at all for those other subdomains. I can see that pages load fast on a subdomain not being examined for code coverage (`--steps`), while the pages being examined by code coverage are slow as expected.

I expected code coverage to work regardless of subdomains that are being tested. Okay, maybe tell Codeception that `c3_url` is "this" one so it can do it's work there without confusion, but when performing requests within the tests - why not do the same thing to all (sub)domains instead of just 1?

### Details

* Codeception version: v3.0.1
* PHP Version: 7.2.17
* Operating System: Ubuntu 18.04.1 LTS
* Installation type: Composer

**Comment by maksimovic** [comment]
I did manage to create a workaround, by adding a `coverage/cookie_domain` config option to the suite, and then, if set, using that domain for setting a cookie in `\Codeception\Coverage\Subscriber\LocalServer::startCoverageCollection`. If a cookie is set as `.mydomain.com` then it works.

However, it's not a long term solution, as we wouldn't like to use a forked version of Codeception...

**Comment by Naktibalda** [comment]
Please make a pull request.

**Comment by Naktibalda** [comment]
Fixed by #5539
