### ISSUE TITLE
Where to place testing functions in Codeception

### ISSUE THREAD

**Issue by cosinus90** [Codeception/Codeception#5545]
Hi, I'd like to write functions for testing action, first is the DB&cookie preparation

> // $this could be $I I don't know
> 			$this->setCookie('testing', 342842934);	
> 			$tables = ['in_users', 'in_channels'];
> 			foreach($tables as $table)
> 			{
> 				$this->runSqlQuery("DROP TABLE IF EXISTS insta_test.$table");
> 				$this->runSqlQuery("CREATE TABLE insta_test.$table LIKE insta.$table;"); 
> 			}		
> 

and the second is a login function in order to not repeat the same code in tests

> 	function login(&$I, $email, $password, $role)
> 	{
> 		$I->amOnPage('/login');
> 		$I->fillField('#_email', 'test@test.ee');
> 		$I->fillField('#_password', '22222222');
> 		$I->fillField('#_role_'.$role, $role);
> 		$I->click('.submit-login');
> 		
> 	}
> 

I tried to place them in a trait that is supposed to be used by Cest, but it not works, Acceptance Helper is too the wrong location, so how can I be DRY in Codeception? Thanks.

**Comment by alexkunin** [comment]
I place things like this to `tests/_support/Helper/Acceptance.php`, its header says:

```php
// here you can define custom actions
// all public methods declared in helper class will be available in $I
```

You say helper is the wrong location? Why?

**Comment by alexkunin** [comment]
@cosinus90 I might see why you have troubles. Here is an example of code I'm adding to helper, it might help you:

```php
public function createAdminAccount(array $data): void
    {
        /** @var Symfony $symfony */
        $symfony = $this->getModule('Symfony');

        /** @var Doctrine2 $doctrine2 */
        $doctrine2 = $this->getModule('Doctrine2');

        /** @var UserPasswordEncoder $encoder */
        $encoder = $symfony->grabService('kernel')->getContainer()->get(UserPasswordEncoder::class);

        $user = new Administrator();

        $password = $encoder->encodePassword(
            new AdministratorSecurityUser($data['name'], null, $data['password'], $data['roles']),
            $data['password']
        );

        $doctrine2->persistEntity($user, ['password' => $password] + $data);
    }
```

So, I'm pulling modules using `$this->getModule()` and then I use them instead of `$I`. In the example above things like `$I->grabService()` and `$I->persistEntity()` (defined in Symfony and Doctrine2 modules respectively and usually available within your acceptance tests as part of `$I`) are transformed into `$symfony->grabService()` and `$doctrine2->persistEntity()`. I guess this should work with any other module too.

**Comment by cosinus90** [comment]
Oh, yes, thanks, I found the solution. tests/_support/Helper/Acceptance.php is correct location, I just need to pass WebGuy variable to the function to use it there.
