### ISSUE TITLE
PHAR file (v3.0.2) includes old PHPUnit version 6.5.x

### ISSUE THREAD

**Issue by reinholdfuereder** [Codeception/Codeception#5561]
https://codeception.com/changelog mentions PHPUnit 8.x

#### What do you get instead?

PHPUnit 6.5.14 (like in Codeception 2.5.6)

```php /mnt/data/Kunden/xortex/components/codeception/3.0.2/codecept.phar run -vvv whatever
Codeception PHP Testing Framework v3.0.2
Powered by PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
...
```

### Details

* Codeception version: 3.0.2
* PHP Version: 7.2.19
* Operating System: Ubuntu 18.04
* Installation type: Phar

**Comment by Naktibalda** [comment]
Use composer instead :)

We haven't changed the build process in 3.0.

Currently we build 2 phar files - targetting PHP 5.6.0 and 7.0.0
Building phar files is the slowest part of release process, so adding 3 more versions to support PHP 7.1, 7.2 and 7.3 is not an option.

Adding more versions of phar file would negatively affect release frequency.
It would be possible to add one more build, but the most likely solution of this ticket is that next year Codeception 4 will provide phar files for PHP 7.1 and 7.3.

**Comment by reinholdfuereder** [comment]
Ad "use composer": ;-)

Thanks for the enlightenment/explanation: this delay is (at least for the time being) no problem at all for us...

**Comment by DavertMik** [comment]
Yeah, phar targets php 7 so far.
People who use phar version don't really care of PHPunit version and not usually care upgrading to latest php as well 😉
