### ISSUE TITLE
[Doctrine2] Query parameter name clashing under certain circumstances

### ISSUE THREAD

**Issue by alexkunin** [Codeception/Codeception#5580]
In recent pull requests (#5543, #5579) I have fixed few things, and I think these changes also introduced rare but possible bug: when `Doctrine2` builds select query, parameter name generation is quirky, and under certain circumstances can lead to name clashing, which looks like false negative assertion.

There are two situations that can lead to that:

1. Entity with relation:
* entity has relation, e.g. `assoc`
* related entity has field, e.g. `val`
* entity has field with name `assocval`

2. Entity with embeddable:
* entity has embeddable, e.g. `embed`
* embeddable has field, e.g. `val`
* entity has field with name `embedval`

Similar things happen in both cases if user refers to both fields in a query because code in `Doctrine2` that generates parameter name looks like this:

```php
$paramname = str_replace(".", "", "${alias}_$key");
```

So, dot is 'swallowed', and that leads to name clash. Doctrine does not choke on that because it just sees second assignment to parameter with same name, but resulting DQL checks different fields against same value, which is almost guaranteed to result in false negative result. See below for sample DQL.

I'm quite embarrassed to be the one who is responsible for that bug. The only thing that makes me feel not that bad is that related code was largely not working neither with associations nor with embeddables, and now it works with both, though under rather artificial conditions it leads to the bug in question.

So, the fix is not hard, I can do it and prepare a pull request.

But testing is hard. Well, I can write a test (already did), but it makes sense only with this particular rare case which happens due to unfortunate way of generating parameter names. When that name generation code is fixed, test won't make any sense.

So, include the test anyway? Maybe with some comment about what it does. Or don't include the test?

Another question. Which one is better:

1. To fix name clashing by better name generation? Like replacing dot with double underscore. This one is tricky because I'm pretty sure some curious user will find a way to make same name clashing.

2. Same as p.1, but add unique prefix or suffix. Well, a bit trickier to make it fail like in p.1, but still possible.

3. Just use unique value with index like `param0`, `param1`, etc. Or even use positional parameters (`?1) instead of names ones (`:param`). I prefer this one, but it will generate DQLs which will be harder to debug, e.g.:

```sql
-- Current and readable (also showcases name clash I'm talking about):
 SELECT s FROM EntityWithEmbeddable s WHERE s.embed.val = :s_embedval AND s.embedval = :s_embedval

-- Proposed:
 SELECT s FROM EntityWithEmbeddable s WHERE s.embed.val = ?1 AND s.embedval = ?2
```

In this particular case two parameters is not a problem, but if a dozen -- that will be hard to debug. Not that it needs much debugging, though...

**Comment by Naktibalda** [comment]
Option 3 seems easier to implement than 2, and if it completely eliminates the issue, then go for it.
User would still see key-value pairs in action line `I see in repository User {"name": "John", ...}`,

**Comment by alexkunin** [comment]
Ok, thanks for explanations, I have implemented the fix using positional parameters -- yep, I believe this completely eliminates the problem. Though, I probably should wait until #5579 is merged, as the fix includes commit from that pull request.

If you want to preview the fix, see last two commits on this branch: https://github.com/alexkunin/Codeception/tree/doctrine2-parameter-name-clash-fix -- one for test case (will fail), and another one with the fix (makes tests green).

**Comment by alexkunin** [comment]
@Naktibalda, thank you for merging my previous pull request. See #5584 for the fix I was talking about. Again, I believe no documentation changes are needed, and I can't see how the fix can break backward compatibility.

**Comment by alexkunin** [comment]
Thanks for merging PR, closing this issue.

**Comment by Naktibalda** [comment]
Please add "Fixes #XXXX" to description of pull request next time and Github will close the issue automatically.

**Comment by alexkunin** [comment]
OK, noted, thanks.
