### ISSUE TITLE
[Doctrine2] Integrate fixtures

### ISSUE THREAD

**Issue by alexkunin** [Codeception/Codeception#5594]
Doctrine has some mechanisms to load fixtures (specific fixture format, suitable for Doctrine -- classes that implement certain interface, all nicely bundled in official package `doctrine/data-fixtures`; same package is used as part official fixtures bundle for Symfony). I think it would be nice to have this functionality in `Doctrine2` module out of the box. The code is quite simple, but might be tedious to add to every project again and again:

```php
$loader = new \Doctrine\Common\DataFixtures\Loader();
$loader->addFixture($fixture);
	
$purger = new \Doctrine\Common\DataFixtures\Purger\ORMPurger($this->em);
$executor = new \Doctrine\Common\DataFixtures\Executor\ORMExecutor($this->em, $purger);
$executor->execute($loader->getFixtures());
```

I have prepared some sample implementation here: https://github.com/alexkunin/Codeception/commit/a839aa7b41b31e303252f58d055c60d5f9a18e53. It includes simple test, but lacks documentation at this point, and also might need a check if Doctrine fixtures package is actually installed.

What do you think? Worth adding to core Codeception repo?

What about method name, `haveFixtureLoaded`? I've seen `haveFixtures` somewhere, not sure which one is better. Also, maybe two methods, one for single fixture, another one for array? Or just detect argument type and use plural in method name?

**Comment by alexkunin** [comment]
Ah, forgot one thing: maybe also add a configuration option to load certain fixtures before all tests? Would be nice to have.

**Comment by Naktibalda** [comment]
Yii2 modules has [haveFixtures](https://codeception.com/docs/modules/Yii2#Fixtures)

**Comment by alexkunin** [comment]
Yep, Yii2 specific fixtures. Doctrine has own fixtures. I can't see how a Doctrine or Doctrine+Symfony user can use Yii2 fixtures.

**Comment by Naktibalda** [comment]
I just wanted to show the existing method that you've seen somewhere.

Since we have a precedent, it is hard to say no in this case.
I'm sure that @DavertMik is happy to add more features too.

**Comment by alexkunin** [comment]
Ah, I see now, sorry for misunderstanding.

So, I guess this feature would be a welcome addition. I'll get back to you when I have some more or less complete implementation then, and then we'll see if anything is missing or does not follow Codeception guidelines.

**Comment by DavertMik** [comment]
I agree, doctrine fixtures is very nice to have. I think we won't have conflicts with Yii2 so method have Fixtures should be fine.

So absolute green light from me. Please do the implementation. This should be really great feature

**Comment by alexkunin** [comment]
See PR above.

I can't repeat Yii functionality as Doctrine has different approach to fixtures. So, for now only `haveFixtures()` method is added, and its signature is different from Yii's. Also, added docs which clearly (I hope so) explain how to use that method. Also added tests, of course.
