### ISSUE TITLE
What is the purpose of Subscriber\ErrorHandler? Can we document it?

### ISSUE THREAD

**Issue by Slamdunk** [Codeception/Codeception#5595]
Hi, whenever using a simple `var_dump($var);exit;` in a test to do a trivial debugging, the output of a run is bloated by `ErrorHandler::shutdownHandler` output, that is registered as a shutdown function in the `SUITE_BEFORE` event.

```
$ vendor/bin/codecept run common/tests/unit/MyTest.php 
Codeception PHP Testing Framework v2.4.5
Powered by PHPUnit 7.5.6 by Sebastian Bergmann and contributors.

Common\tests\_support.unit Tests (1) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- MyTest: What
int(1)

PHP Fatal error:  Uncaught RuntimeException: Command Did Not Finish Properly in ./vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in ./vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php on line 101

Fatal error: Uncaught RuntimeException: Command Did Not Finish Properly in ./vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in ./vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php on line 101
```

What is the exact purpose of this?
Is all my code converts errors to exceptions, could I get rid of this handler?
Would you accept a PR to avoid subscribing this listener with a proper config in the `codeception.yml` file?

**Comment by Naktibalda** [comment]
https://github.com/Codeception/Codeception/pull/4604

> I have been working on getting my testing setup within a CI. I was looking at the output of one such run when I realized that the test did not appear to be finishing, but was not giving any errors. After digging into it, I learned that one of my Junior Developers created a new class following some of the legacy code in the system. They put includes inside a class file (rather than relying on the PSR-4 Autoloader). One of these includes was a script to check a user's login/session and redirecting them to the homepage if they weren't logged in. Because a call to exit without params is equivalent to exit(0), my CI system thought that the test completed succesfully when it didn't actual do so.

**Comment by Naktibalda** [comment]
Enduring some extra noise when debugging is nothing compared to difficulty of tracking down misterious die which is killing your tests and making them appear successful.

It was a common issue before introduction of this feature.

**Comment by Slamdunk** [comment]
> Enduring some extra noise when debugging is nothing compared to difficulty of tracking down misterious die which is killing your tests and making them appear successful.

Of course this is a precious feature.

I would like to improve this by:

1. Adding tests for the entire registered shutdown function: it should be trivial with an external process
1. Reducing the output: the current exception outputs 12 lines while just 1 could achieve the same goal

I see #4604 got merged without any test: please avoid untested feature, especially for such brittle and important features.

Thank you for your quick and kind reply, I'll propose some PR as soon as I can
