### ISSUE TITLE
Please fix the website - bad version of PHP is displayed as minimal

### ISSUE THREAD

**Issue by mklemarczyk** [Codeception/Codeception#5600]
The website
https://codeception.com/install
is pointing that PHP 5.4+ is minimal required version for major release.

According to composer package the minimal version is 5.6.
See composer install log for installing composer: "^3.0"

```
    - codeception/codeception 3.0.3 requires php >=5.6.0 <8.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - codeception/codeception 3.0.2 requires php >=5.6.0 <8.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - codeception/codeception 3.0.1 requires php >=5.6.0 <8.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - codeception/codeception 3.0.0 requires php >=5.6.0 <8.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - Installation request for codeception/codeception ^3.0 -> satisfiable by codeception/codeception[3.0.0, 3.0.1, 3.0.2, 3.0.3].
```

Entire log is available on https://travis-ci.com/trogon/otus-pdf/jobs/217938526

Actually support was dropped without any notice in version https://packagist.org/packages/codeception/codeception#2.4.2

**Comment by Naktibalda** [comment]
Install page shows that the minimal required version is 5.6 now.
