### ISSUE TITLE
Module\Cli::runShellCommand should fail if expected failing command isn't failing

### ISSUE THREAD

**Issue by Slamdunk** [Codeception/Codeception#5603]
Hi, currently calling `runShellCommand` expecting a failing command, doesn't fail if the command isn't failing:

https://github.com/Codeception/Codeception/blob/feb566a9dc26993611602011ae3834d8e3c1dd7f/src/Codeception/Module/Cli.php#L52-L54

This looseness can be dangerous and lead to false negative tests.

I suggest to always expect a zero result code for expected successful command, and always expect non-zero result code for expected failing command, but of course this would be a BC break.

What do you think?

Reference:
1. https://github.com/Codeception/Codeception/pull/5601#discussion_r305738335
1. https://github.com/Codeception/Codeception/issues/1603
1. https://github.com/Codeception/Codeception/pull/1604 /cc @DevShep

**Comment by Naktibalda** [comment]
I think that this is a bad idea.
If you expect command to fail, use `seeResultCodeIs` assertion.

**Comment by Slamdunk** [comment]
> I think that this is a bad idea.

May I ask you why?

Take the point of view of a new Codeception user.
He writes a test like this:

```php
class MyCest
{
    public function test(\CliGuy $I)
    {
        $I->executeCommand('/bin/true');
        $I->executeCommand('/bin/false');
    }
}
```
And the test fails, correctly.
Now he writes another test:
```php
class MyCest
{
    public function test(\CliGuy $I)
    {
        $I->executeFailCommand('/bin/true');
        $I->executeFailCommand('/bin/false');
    }
}
```
And now the test passes: this is counter-intuitive.
`seeResultCodeIs` should be used to check the *exact* exit code, not a general pass-or-fail command.

The test environment should be as strict as possible, with one and only one execution and expectation path.

To my eyes, the current `executeFailCommand` is confusing, if you don't like to alter its behavior at least we should rename it to `executeSuccessOrFailCommand`, or something else that ensure the user understands what it does.

**Comment by Naktibalda** [comment]
`executeCommand` and `executeFailCommand` aren't methods of [Cli module](https://codeception.com/docs/modules/Cli#runShellCommand),
they are methods of [CliHelper](https://github.com/Codeception/Codeception/blob/3.0/tests/support/CliHelper.php#L27-L34) used in Codeception test suite

Documentation of [runShellCommand](https://codeception.com/docs/modules/Cli#runShellCommand)
doesn't say that setting second argument to true means `expect failing command`.

> Executes a shell command. Fails If exit code is > 0. You can disable this by setting second parameter to false.

So you want to update documentation and behaviour for not particularly good reason.
It isn't good enough for backwards compatibility break.

You are welcome to make `executeFailCommand` fail if exit code is zero.

**Comment by Naktibalda** [comment]
This proposal was rejected.
