### ISSUE TITLE
codeception/base tags aren't aligned with codeception/codeception ones

### ISSUE THREAD

**Issue by Slamdunk** [Codeception/Codeception#5604]
At the date of writing this Issue, `codeception/codeception` is at `3.0.3` while `codeception/base` is at `3.0.0`:

---
https://packagist.org/packages/Codeception/Codeception
![immagine](https://user-images.githubusercontent.com/152236/61714385-fa544780-ad5a-11e9-8871-0d86a2365cb8.png)
---
https://packagist.org/packages/Codeception/Base
![immagine](https://user-images.githubusercontent.com/152236/61714413-0b9d5400-ad5b-11e9-87b4-b723069a36da.png)
---

**Comment by Naktibalda** [comment]
@DavertMik it looks like a packagist issue to me, because releases exists in Github.

**Comment by erickskrauch** [comment]
It's not a packagist issue, but the error in [composer.json](https://github.com/Codeception/base/blob/db982eb1fe5ad9914acce3a152c98db7e77655fe/composer.json#L33) (trailing comma).

**Comment by Naktibalda** [comment]
@erickskrauch Thanks for spotting that.

It happens because build process [removes the last dependency](https://github.com/Codeception/Codeception/blob/3.0/RoboFile.php#L888).
I think that the simplest fix is to move `hoa/console` to penultimate line.

**Comment by Slamdunk** [comment]
@erickskrauch nice catch.

@Naktibalda running `composer update` against an invalid file produces an error with an exit code of 1.

Why 

https://github.com/Codeception/Codeception/blob/7e0e69832fc3af1d5526d8a8c23f2b6744144f23/RoboFile.php#L897

didn't block the build?

**Comment by Naktibalda** [comment]
It looks like it is noones responsibility to throw exception.
[taskComposerUpdate::run](https://github.com/consolidation/Robo/blob/954f17bfbdd78b829c0eae88055a0446ba589aed/src/Task/Composer/Update.php#L38) calls [executeCommand](https://github.com/consolidation/Robo/blob/de60f778574bd5eccc08c10e06a870c3392fe1dc/src/Common/ExecCommand.php#L140) which calls [execute](https://github.com/consolidation/Robo/blob/de60f778574bd5eccc08c10e06a870c3392fe1dc/src/Common/ExecTrait.php#L390-L399).
`execute` catches all exceptions and returns `ResultData` object, `executeCommand` converts it to `Result`, `run` simply returns it. exit code isn't checked anywhere.

@DavertMik Can you comment on this? Is there a way to make failing commands fail?

**Comment by Slamdunk** [comment]
From https://robo.li/getting-started/#tasks
```
Global StopOnFail

There is a global stopOnFail method as well, that can be used to stop a command on first failure of a task.

$this->stopOnFail(true);
```

**Comment by Naktibalda** [comment]
Thanks, I will test it before releasing the next version.

**Comment by Naktibalda** [comment]
I had a different issue this time, but stopOnFail worked.
3.1.0 version of codeception/base is visible in packagist: https://packagist.org/packages/codeception/base#3.1.0

**Comment by Slamdunk** [comment]
Thank you
