### ISSUE TITLE
Writing CakePHP Unit Tests?

### ISSUE THREAD

**Issue by rooseveltrp** [Codeception/Codeception#561]
Hi,

Codeception is the coolest kid on the block when it comes to testing. I am having loads of fun with Codeception and CakePHP... specifically Acceptance tests. However, my luck with CakePHP and Codeception Unit testing hasn't been that good.

CakePHP on its own has good support for Unit Testing but I prefer to use Codeception to house both acceptance and unit tests. Besides... codeception's methods are more human :tongue:

Does anyone have any idea how to test the CakePHP models using Codeception's CodeGuy? Here is a sample class I am working on but for obvious reasons it is not working.

When testing the CakePHP models using CodeGuy, I want the models to be able to connect to the CakePHP database and perform regular operations it does in a CakePHP environment.

```PHP
<?php
use Codeception\Util\Stub;

App::uses("Log", "Model");

class LogTest extends \Codeception\TestCase\Test
{
   /**
    * @var \CodeGuy
    */
    protected $codeGuy;

    public $Log = null;

    protected function _before()
    {
        $this->Log = ClassRegistry::init('Log');
    }

    protected function _after()
    {
    }

    public function testLogStart(){
        $this->Log->logStart();
        $this->assertEquals(count($this->Log->action_log), 2);
    }
}
```

**Comment by jadb** [comment]
There is now an official (alpha) release of the CakePHP 3 module for Codeception.

http://github.com/cakephp/codeception

@DavertMik how can we get it added to the Addons section of the website?

**Comment by rupaheizu** [comment]
Hi guys, made a tool in testing controllers, still needs improvement though.

https://github.com/hkzpjt/cakeception

**Comment by DavertMik** [comment]
@jadb @rupaheizu sorry, I missed your comments. I'm putting your integration modules to Addons section and will do some promotion on twitter

**Comment by jadb** [comment]
@DavertMik thanks! :)

**Comment by mtpultz** [comment]
Did a CakePHP 2.x version of a module ever happen?

**Comment by agarzon** [comment]
@mtpultz https://github.com/hkzpjt/cakeception (linked in http://codeception.com/addons)
