### ISSUE TITLE
How we can load the codeignitor model in unit test?

### ISSUE THREAD

**Issue by adnansiddiq** [Codeception/Codeception#5610]
I have installed the codeception in codeignior and test run easily no issue but i have not loaded the model in unit test.

**Comment by Naktibalda** [comment]
How do you load it in application code?
In unit tests it would be the best to avoid dependencies on framework and only instantiate classes that you need for your test to pass.

**Comment by Naktibalda** [comment]
CodeIgniter framework is not supported.
There was a third party module for CodeIgniter 2.1 https://github.com/luka-zitnik/CodeIgniterModule
but it doesn't even support PHP 7.

So it is up to you to figure out how to test it.
