### ISSUE TITLE
Support MYSQL_ATTR_INIT_COMMAND

### ISSUE THREAD

**Issue by tadasauciunas** [Codeception/Codeception#5612]
#### What are you trying to achieve?

`MYSQL_ATTR_INIT_COMMAND` Should be supported when creating a PDO connection for initial queries like `SET NAMES utf8` which are commonly used

**Comment by Naktibalda** [comment]
`SET NAMES utf8` was commonly used in old versions of PHP.
`charset=utf8` can be specified in DSN since PHP 5.3.6: https://www.php.net/manual/en/ref.pdo-mysql.connection.php

**Comment by tadasauciunas** [comment]
`SET NAMES utf8` is still necessary in still cases, even in modern php versions. 
Passing the charset inside the dsn is possible, but having the freedom to pass other initializing queries via MYSQL_ATTR_INIT_COMMAND adds more flexibility.
