### ISSUE TITLE
Codeception 3.0.3 breaks trait on UnitHelper

### ISSUE THREAD

**Issue by gnumoksha** [Codeception/Codeception#5618]
#### What are you trying to achieve?
Call `$this->tester->fooMethod()` within an unit test file.

#### What do you get instead?

```
[RuntimeException] Call to undefined method Tests\Foo\UnitTester::fooMethod
```

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 3.0.3
* PHP Version: PHP 7.2.19 (cli) (built: Jun 11 2019 02:28:31) ( NTS ) 
* Operating System: Debian running on docker container
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
I doubt that this issue is version related.
Is the module, where this method is defined, enabled in unit.suite.yml?
Try running `codecept build`.

**Comment by gnumoksha** [comment]
Hi. This was not codeception fault indeed. I've changed the path for an old module and the tests started failing, I think this was a problem with the autoloader
