### ISSUE TITLE
Provide a second codeception.phar with Verify/Specify included

### ISSUE THREAD

**Issue by mikehaertl** [Codeception/Codeception#5620]
#### What are you trying to achieve?

Use Specify and Verify with the global `codeception.phar`.

#### What do you get instead?

Codeception/Specify and Codeception/Verify are not included and I can not add them because the app I want to test has a fixed set of composer packages that I can not modify just for testing.

### Details

There's already issue #1200 and #1658 where this was discussed. I understand that adding the above packages may lead to conflicts. 

Would it be an option to provide a second `.phar` archive that contains the above 2 packages (and maybe even more)?

This way a developer could choose which one is best for his purposes.

**Comment by Naktibalda** [comment]
I think that this is a rare edge case and it isn't worth the effort.
If you need such phar file, build it yourself.

Instructions how to build your own phar file from https://github.com/Codeception/Codeception/issues/2124#issuecomment-142232225
```
git clone https://github.com/Codeception/Codeception/
cd Codeception
composer require guzzlehttp/guzzle 5.3.*
wget http://robo.li/robo.phar
php -d phar.readonly=0 robo.phar build:phar
```

Replace `composer require guzzlehttp/guzzle 5.3.*` with packages that you want to add to your phar.

Note. [build:phar](https://github.com/Codeception/Codeception/blob/3.0.3/RoboFile.php#L169) currently targets PHP 7.0.0, if you want to target a different version of PHP, comment that line out or specify a version at [this line](https://github.com/Codeception/Codeception/blob/3.0.3/RoboFile.php#L148).

**Comment by mikehaertl** [comment]
@Naktibalda Thanks, actually that's what I wanted to try but couldn't find any documentation (and neither any code) how to build the phar. So I will try this now.

Maybe it's worth to add some notes to the docs, how to get your own phar?

**Comment by alexkunin** [comment]
Well, there is https://github.com/Codeception/Codeception/blob/3.0/RELEASE.md -- it does not specifically say how to build only .phar, but it does that among other things, and gives some useful hints re how things are built and released.

**Comment by mikehaertl** [comment]
Ok, that should be fine. Closing this then. Thanks.

**Comment by Naktibalda** [comment]
Apparently there is low demand for custom phar files, but separating `buildPhar` from `buildPhar7` (for PHP 7.0), would make it easier to target different versions of PHP.

**Comment by kk738** [comment]
What I found really wierd is this sentence in the docu:

> For this case we have a stand-alone project Specify (**which is included in the phar package**) for writing specifications inside unit tests:

on https://codeception.com/docs/05-UnitTests

is it included or not??

**Comment by Naktibalda** [comment]
That text hasn't been updated for at least 6 years.

If Specify library wasn't included to phar file in 2019 then it definitelly isn't included now.

**Comment by kk738** [comment]
I have to deel with a server which has no internet and therefore wanted to go with the phar solution.
But I think it will be easier to install the dependencies on a machine with internet and just copy the vendor folder to the offline machine then ...
