### ISSUE TITLE
Access to helpers over http

### ISSUE THREAD

**Issue by akimsir** [Codeception/Codeception#5637]
#### What are you trying to achieve?
Reuse helpers code base in other test frameworks over http

#### What do you get instead?
Nothing)

What is easiest way to achieve this?

#### Example
I send http request to /test/helper?heleprName=createEntity&helperArgs=1 
this request should invoke codeception helper createEntity(1) and send back result

**Comment by Naktibalda** [comment]
Codeception is not an http daemon, it is up to you to implement such functionality if you want it.
