### ISSUE TITLE
Add flag to suppress Artifacts reporting in 3.0

### ISSUE THREAD

**Issue by Slamdunk** [Codeception/Codeception#5646]
Hi, commit https://github.com/Codeception/Codeception/commit/cca5463cdefd12120783bca94081496f02f226e9#diff-cddc2fb9d072ba8acaf613bd6b2d14f6R368 introduced `Artifacts` printing when tests fail.

I have to say that even though this is a useful new features to be active by default, a lot of time they may be noisy and may bring no value while TDDing, so it would be nice to have a flag to disable that particular output from `Subscriber\Console::printReports` method.

**Comment by DavertMik** [comment]
I agree. Can you submit PR with `--no-artifacts` flag. Seems fine for me

**Comment by Slamdunk** [comment]
It would be a pleasure for me.
But there are no tests for that feature, I wouldn't add test for something I didn't write nor I'd like to propose the pr without tests, so I don't know very well how to behave.

May I ask you why that feature was accepted without tests?

**Comment by Naktibalda** [comment]
> ay I ask you why that feature was accepted without tests?

@DavertMik implemented it, so it must be good :)

**Comment by Slamdunk** [comment]
> @DavertMik implemented it, so it must be good :)

I'm sure you're just kidding, but for newcomers I prefer to drop a clear statement about this reply: no-one is good enough to write code without tests, because no-one can foresee the future and so no-one is able to know why and how the present code will be changed or adapt to changes in the future; tests are the only way to know it when it will be needed to be known.

**Comment by Naktibalda** [comment]
It looks like particular commit was committed straight to 3.0 branch, so there was never a pull request for it.

But if you want to help keep code quality high, please stick around and review some pull requests.

**Comment by Slamdunk** [comment]
Well if so I suggest to activate right now a branch protection rule:

![image](https://user-images.githubusercontent.com/152236/63242455-bbc98400-c257-11e9-8e9e-6996a324588d.png)

This is an awesome and business critical library which needs strict quality requirements, in my humble opinion.
