### ISSUE TITLE
[Doctrine2] Configurable property access

### ISSUE THREAD

**Issue by alexkunin** [Codeception/Codeception#5647]
Currently `Doctrine2` uses Reflection API to set properties of entities directly, without using setters. This should not be a problem in most cases, but it might be a show stopper for someone who has some fancy logic in setter -- maybe some type conversion, or validation, etc. Also, arguable one of the most widespread ways of using Doctrine is as ORM module of Symfony, which almost always means heavy usage of getters and setters via `symfony/property-access` package.

The PR below addresses this issue by abstracting away entity creation and modification, and then providing two implementations -- one using Reflection API and another using `symfony/property-access`. It also introduces new module configuration option (defaults to Reflection API), and module API method to dynamically change property access strategy for current test.

So, this is somewhat an edge case, but if encountered, not being able to use setters might prevent someone to use `Doctrine2` module altogether.

**Comment by DavertMik** [comment]
Ok, I reviewed the PR without seeing this issue. Ok, that really seems like an edgecase and it is hard to understand its use case without understanding underlying functionality. 

I think we need to extend a Data chapter https://codeception.com/docs/09-Data a section about Doctrine? It should include full cycle of data management in Doctrine:

* initializing
* creating
* updating
* deleting
* cleanup

etc.  If you could write about Doctrine usage in this chapter that will help everyone to establish good practices running tests, with doctrine, understand its internals and use cases.

**Comment by alexkunin** [comment]
I agree, this PR solves rather rare problem, which became even more rare when recursive entity creation PR was accepted -- that's because most of custom getters/setters are used in relations.

So, this edge case is might be not worth adding to core library, maybe it's not worth implementing altogether. It was just rather simple (PR is massive because I have added setters and getters to test entities, which is not strictly needed), and what it does is the following:

- extracts interface from already existing property accessor class
- adds another implementation which uses Symfony component
- adds configuration property to select interface implementation (either by alias or by class name)
- adds a method to change that setting dynamically

That's it, pretty simple. I can make changes much less "noisy" to make PR look simpler (and shorter). Or maybe it's not worth effort at all, as nobody asked for that kind of functionality.

As for the rest of your comment, that seems like a different thing to me, probably deserves separate issue. I could try write that part of the docs, but I'm not a native English speaker, and also I do not understand all parts of `Doctrine2` yet (e.g. did not use fake repos, cleanup functionality seems to be broken). I'm trying to say I might be wrong person for the job, though not saying I can't do it.

**Comment by DavertMik** [comment]
Sure, this is a different issue, but by writing up the docs, we could explain different purposes and use cases, so we can clarify the usage. This is required for merging this PR. 

> As for the rest of your comment, that seems like a different thing to me, probably deserves separate issue. I could try write that part of the docs, but I'm not a native English speaker, and also I do not understand all parts of Doctrine2 yet (e.g. did not use fake repos, cleanup functionality seems to be broken). I'm trying to say I might be wrong person for the job, though not saying I can't do it.

Well, you ARE the right person for a job. I started Doctrine helper in 2012 and as you may guess lots of things changed since that time. For instance, fake repos and cleanup may be totally broken by now :upside_down_face: 

You are using Doctrine daily nowadays and probably you can help others start using Doctrine module! As we didn't have any dedicated guide for it yet. 

As for English... It's ok to have limited and simple English. For all the time maintaining Codeception I receive pull requests fixing typos and miswording. That is how you know that your text is read and your posts really matter :+1: So again, I'd ask you to write a better guide. Then we will see if the corresponding PR is needed or not.

**Comment by alexkunin** [comment]
After giving it another (and another, and another) thought, I conclude this is far beyond my capabilities, and I'll pass the honor of writing docs to anyone more suitable. Though, happy to answer questions within me expertise, of course.
