### ISSUE TITLE
[Doctrine2] var_export does not handle circular references after extractPrimaryKey under certain circumstances

### ISSUE THREAD

**Issue by Basster** [Codeception/Codeception#5663]
#### What are you trying to achieve?

Hands down, I have a pretty complex Entity structure:

```php

/** @Entity **/
class A {}

/** @Entity **/
class B {}

/** @Entity **/
class C{}

/** @Entity **/
class D {
    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="A", inversedBy="as")
     */
    private $a;

    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="B", inversedBy="bs")
     */
    private $b;

    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="C", inversedBy="cs")
     */
    private $c;
}
```
All `ManyToOne` relations are bidirectional!

Now I try to  (pretty simplified):

```php
$a = new A();
$b = new B();
$c = new C();
$d = new D($a, $b, $c);

$I->haveInRepository($d, ['a' => $a, 'b' => $b, 'c' => $c]);
``` 
`haveInRepository` is working correctly, *but* the debug line right before the `return` utilizes a `var_export` to display the primary keys and fails with `var_export does not handle circular references`!

### Details

* Codeception version: 3.1.0
* PHP Version: 7.3
* Operating System: doesn't matter
* Installation type: Composer
* List of installed packages: doesn't matter
* Suite configuration: doesn't matter

**Comment by javabudd** [comment]
Can confirm, this is happening after updating to 3.1.0
