### ISSUE TITLE
[Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.

### ISSUE THREAD

**Issue by zabolonkovd4** [Codeception/Codeception#5665]
#### What are you trying to achieve?
I am trying to run simple acceptance test LoginCept.php to test my site which is on 127.0.0.1:8080 using php yii serve command. Also I am using Selenium-Server v.3.141.59. Trying to use latest versions. 

#### What do you get instead?
Looks like selenium can't get session.

Here's the selenium server log:

>16:20:07.113 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
16:20:07.170 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2019-08-24 16:20:07.202:INFO::main: Logging initialized @236ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:20:07.341 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
16:20:07.397 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444

Here's my long long output when I run ./vendor/bin/codecept run acceptance ./tests/acceptance/LoginCept.php -vvv

>[Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: '\<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
\<html>\<head>
\<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">
\<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
\<title>ERROR: The requested URL could not be retrieved\</title>
\<style type="text/css">\\</style>
\</head>\<body id=ERR_CONNECT_FAIL>
\<div id="titles">
\<h1>ERROR\</h1>
\<h2>The requested URL could not be retrieved\</h2>
\</div>
\<hr>
\<div id="content">
\<p>The following error was encountered while trying to retrieve the URL: \<a href="http://127.0.0.1:4444/wd/hub/session">http://127.0.0.1:4444/wd/hub/session\</a>\</p>
\<blockquote id="error">
\<p>\<b>Connection to 127.0.0.1 failed.\</b>\</p>
\</blockquote>
\<p id="sysmsg">The system returned: \<i>(111) Connection refused\</i>\</p>
\<p>The remote host or network may be down. Please try the request again.\</p>
\<p>Your cache administrator is \<a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20HTTP-squid.lab14.ptri.dom%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Sat,%2024%20Aug%202019%2013%3A42%3A06%20GMT%0D%0A%0D%0AClientIP%3A%20192.168.110.40%0D%0AServerIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0APOST%20%2Fwd%2Fhub%2Fsession%20HTTP%2F1.1%0AProxy-Authorization%3A%20Basic%20ZGl6OlphYm9sb25rb3ZkNA%3D%3D%0D%0AProxy-Connection%3A%20Keep-Alive%0D%0AContent-Type%3A%20application%2Fjson%3Bcharset%3DUTF-8%0D%0AAccept%3A%20application%2Fjson%0D%0AContent-Length%3A%2049%0D%0AHost%3A%20127.0.0.1%3A4444%0D%0A%0D%0A%0D%0A">root\</a>.\</p>
\<br>
\</div>
\<hr>
\<div id="footer">
\<p>Generated Sat, 24 Aug 2019 13:42:06 GMT by HTTP-squid.lab14.ptri.dom (squid/3.5.20)\</p>
\
\</div>
\</body>\</html>'

That's LoginCept.php code which I'm trying to run:
```php
/** @var $scenario \Codeception\Scenario */
$I = new AcceptanceTester($scenario);
$I->wantTo('ensure that search works');
$I->amOnPage('/');
$I->see('Найти');
$I->fillField('input[name=text]', 'Codeception');
if(method_exists($I, 'wait')) {
    $I->wait(1);
}
$I->click('button[type=submit]');
if(method_exists($I, 'wait')) {
    $I->wait(1);
}
$I->seeInCurrentUrl('/search/?text=Codeception');
$I->see('Codeception - BDD-style PHP testing');
<?php 

```
### Details

* Codeception version: 2.4.0 
* PHP Version: 7.0.27-0+deb9u1
* Operating System: Linux Debian
* Installation type: Phar || Composer
* Suite configuration:

This is my yml file for acceptance tests.
```yml
class_name: AcceptanceTester
modules:
  enabled:
    - WebDriver
    #    - AcceptanceHelper

  config:
    WebDriver:
      url: 'https://127.0.0.1:8080'
      browser: firefox
      restart: true
      window_size: 1024x768
```

Thanks for helping everyone!

**Comment by Naktibalda** [comment]
It looks like your firefox is configured to use proxy server.

```
<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:4444/wd/hub/session">http://127.0.0.1:4444/wd/hub/session\</p>
<blockquote id="error">
<p><b>Connection to 127.0.0.1 failed.</b></p>
</blockquote>
<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>
<p>The remote host or network may be down. Please try the request again.</p>
```

```
Generated Sat, 24 Aug 2019 13:42:06 GMT by HTTP-squid.lab14.ptri.dom (squid/3.5.20)
```

**Comment by zabolonkovd4** [comment]
Yes, I am under proxy and 127.0.0.1 is in an exception in firefox browser. How should I configure that? Sorry for wasting your time.

**Comment by zabolonkovd4** [comment]
Also, if I open the link http://127.0.0.1:4444/wd/hub/session I get the JSON output 

>sessionId | null
-- | --
value |  
error | "unknown command"
message | "Unable to find command matching GET to /session"
stacktrace | ""
status | 9

**Comment by zabolonkovd4** [comment]
Removed all global proxy settings in system. Here's different error:
>[Facebook\WebDriver\Exception\SessionNotCreatedException] Unable to create new service: GeckoDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'astra', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.3-1-generic', java.version: '1.8.0_152-release'
Driver info: driver.version: unknown 

I'll try to downgrade geckodriver.

**Comment by zabolonkovd4** [comment]
Moved geckodriver exec file in /usr/bin directory. It works, but I still need configure proxy for automation access to such site google.com for example. In codeception/webdriver docs I only found  option to set http_proxy and http_proxy_port. How can I set username and password?

**Comment by zabolonkovd4** [comment]
Browser open the page and instantly close this with an error:
>[PHPUnit\Framework\Exception] Undefined index: ELEMENT

**Comment by Naktibalda** [comment]
> [PHPUnit\Framework\Exception] Undefined index: ELEMENT

`facebook/php-webdriver` isn't defensive enough,
this error happens when Selenium server returns unexpected response.
Please check output of geckodriver and Selenium.

**Comment by zabolonkovd4** [comment]
Some JS error, can't found the solution. 
>12:46:16.856 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
12:46:16.913 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2019-08-27 12:46:16.945:INFO::main: Logging initialized @234ms to org.seleniumhq.jetty9.util.log.StdErrLog
12:46:17.082 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
12:46:17.135 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
12:46:26.257 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "proxy": {
    "httpProxy": "192.168.10.1:8080",
    "proxyType": "manual"
  }
}
12:46:26.259 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1566899186269   geckodriver     INFO    geckodriver 0.21.0
1566899186275   geckodriver     INFO    Listening on 127.0.0.1:23710
1566899186409   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.iPaezoRbHUod"
JavaScript error: jar:file:///usr/lib/firefox/omni.ja!/components/addonsInfo.js, line 91: SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead
1566899187895   Marionette      INFO    Listening on port 40709
1566899187919   Marionette      INFO    Proxy settings initialised: {"proxyType":"manual","httpProxy":"192.168.10.1:8080"}
12:46:27.956 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
12:46:27.982 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 0dfa31cb-1374-4f22-979d-3369be52494d (org.openqa.selenium.firefox.GeckoDriverService)
1566899188109   addons.xpi      WARN    Exception running bootstrap method shutdown on activity-stream@mozilla.org: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIObserverService.removeObserver]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://activity-stream/lib/SnippetsFeed.jsm :: uninit :: line 185"  data: no] Stack trace: uninit()@resource://activity-stream/lib/SnippetsFeed.jsm:185
onAction()@resource://activity-stream/lib/SnippetsFeed.jsm:201
_middleware/</<()@resource://activity-stream/lib/Store.jsm:49
Store/this[method]()@resource://activity-stream/lib/Store.jsm:28
uninit()@resource://activity-stream/lib/Store.jsm:151
uninit()@resource://activity-stream/lib/ActivityStream.jsm:300
uninit()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///usr/lib/firefox/browser/features/activity-stream@mozilla.org.xpi!/bootstrap.js:73
shutdown()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///usr/lib/firefox/browser/features/activity-stream@mozilla.org.xpi!/bootstrap.js:169
callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4436
observe()@resource://gre/modules/addons/XPIProvider.jsm:2287
GeckoDriver.prototype.quit()@driver.js:3300
despatch()@server.js:293
execute()@server.js:267
onPacket/<()@server.js:242
onPacket()@server.js:241
_onJSONObjectReady/<()@transport.js:500
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
12:46:28.661 INFO [ActiveSessions$1.onStop] - Removing session 0dfa31cb-1374-4f22-979d-3369be52494d (org.openqa.selenium.firefox.GeckoDriverService)

**Comment by zabolonkovd4** [comment]
By the way, a lot of comments on this exception 
>PHPUnit\Framework\Exception] Undefined index: ELEMENT

advice me to switch to chrome driver.

**Comment by reinholdfuereder** [comment]
@zabolonkovd4 I think you will have to be patient, because using (semi-up-to-date) Firefox via Codeception depends on implementation of W3C protocol for PHP WebDriver (bindings), see e.g.:
* #4898
* https://github.com/facebook/php-webdriver/issues/469
* https://github.com/facebook/php-webdriver/issues/657 ... thus there is definitely hope ;-)

**Comment by rvinicius396g** [comment]
solutions ?
