### ISSUE TITLE
assertAttributeEquals

### ISSUE THREAD

**Issue by suprim1** [Codeception/Codeception#5668]
how to check assertAttributeEquals in codeception?

```php
        $offersCompositeMock = Stub::make(OffersComposite::class);
        $responseComposite = new ResponseComposite();
        $responseComposite->add($offersCompositeMock);
        $I->assert ?????
        //PhpUnit
        $this->assertAttributeEquals($offersCompositeMock, 'children', $responseComposite);
```

**Comment by reinholdfuereder** [comment]
I think/guess `assertAttributeEquals` also should not be added (anymore), because PHPUnit itself also deprecated it in v7.5 according to https://github.com/sebastianbergmann/phpunit/blob/8.0.0/ChangeLog-7.5.md:

> Using [it] will trigger a deprecation warning in PHPUnit 8 and in PHPUnit 9 [it] will be removed.
