### ISSUE TITLE
Upgrade phpunit in .phar release to 8.0

### ISSUE THREAD

**Issue by mikehaertl** [Codeception/Codeception#5676]
#### What are you trying to achieve?

I want to use pcov for code coverage.

#### What do you get instead?

pcov is only supported since phpunit 8.0

### Details

* Codeception version: 3.0.3 and 3.1.0
* PHP Version: 7.3
* Operating System: Linux
* Installation type: Phar
* List of installed packages (`composer show`)
* Suite configuration: none

### Suggested solution

Create a new phar release that contains phpunit 8.

**Comment by reinholdfuereder** [comment]
See #5561

**Comment by mikehaertl** [comment]
Ok, makes sense. I've switched to composer install now, too. The main reason I used the phar was, because I wanted clear separation of codeception packages from my project packages. There's a way to do this as I showed in #5677.
