### ISSUE TITLE
Document an alternative way for global installation

### ISSUE THREAD

**Issue by mikehaertl** [Codeception/Codeception#5677]
I prefer a global installation of codeception because I want a complete separation of the composer packages from my project and from codeception itself.

So far for global installation is only described for the PHAR installation. But I found this setup very inflexible and the PHAR also seems to include an outdated phpunit (#5676).

I suggest, that yet another way for global installation should be documented. I had success with the following steps:

```
mkdir ~/codeception
cd ~/codeception
composer require codeception/codeception --dev
sudo mv vendor /usr/local/include/codecept
sudo ln -s /usr/local/include/codecept/bin/codecept /usr/local/bin
```

Now `codecept` can be used system wide.

----
**UPDATE**

The same can be achieved with a single composer command using env vars:

```
COMPOSER_BIN_DIR=/usr/local/bin \
COMPOSER_VENDOR_DIR=/usr/local/include/codeception \
composer global require codeception/codeception
```

**Comment by Naktibalda** [comment]
Could you show any other project documenting this way of installation?

Another way to install Codeception globally that we don't explicitly document, but which is used nevertheless is `composer global require codeception/codeception`

**Comment by mikehaertl** [comment]
> Could you show any other project documenting this way of installation?

No, because I had to figure this out myself (because, you know, ... it's not documented yet :wink: ). One could argue about the installation paths but I'd say `/usr/local/include/codecept` and `/usr/local/bin/codecept` are apropriate.

Maybe `phpunit` is a good comparison. I've installed it as `apt` package and it uses `/usr/share/php/PHPUnit`  for the libraries and puts the executable to `/usr/bin/phpunit`. So an alternative path could be `/usr/share/php/Codecept`. But it could conflict with libraries installed with the system's package manager. So I chose the `/usr/local/` prefix to be safe.

I've also tried `composer global require codeception/codeception` with the official `composer` docker image: It installed everything to `/tmp/vendor` but after installation `codecept` was still not available as global shell command. So you'd either have to copy it to your search path or create a symlink from `/tmp/vendor/bin/codecept` to `/usr/bin/codecept`. But I find the `/tmp` directory is inapropriate for system wide libraries and binaries.

**Comment by mikehaertl** [comment]
I found that with composer's env vars the installation can also be run in a single command:

```
COMPOSER_BIN_DIR=/usr/local/bin \
COMPOSER_VENDOR_DIR=/usr/local/include/codeception \
composer global require codeception/codeception
```

This installs codeception to `/usr/local/include/codeception` and creates a symlink for the executable in `/usr/local/bin/codecept`.

**Comment by DavertMik** [comment]
Sorry, @mikehaertl we will get more problems with such kind of installation. 

* not everyone uses Linux
* not everyone uses the same file structure as yours, 
* keeping codeception global means you need to update it manually, which also a problem

It's great this works for you but we can't document unreliable setup.

**Comment by mikehaertl** [comment]
Hmm, ok. To be honest I find this decision a bit weird.

> not everyone uses Linux

I can't see why that's a reason not to document global installation on Linux. Most developers *do* use Linux. It's only a matter of adding a note.

> not everyone uses the same file structure as yours,

It's not *my* file structure - it's the standard directory structure you find on almost every Linux/Unix system since decades.

> keeping codeception global means you need to update it manually, which also a problem

I find it problematic to mix test libraries with your productive code. I want to keep both separate. Like many developers I use docker images and create specific test images. You *always* have the problem of keeping codeception up to date. I can't see why that's an argument that you don't even want to add a note how to install it globally.

The situation right now, if you want global installation: You have to use the `.phar` file. But this comes with an outdated phpunit and you can't easily add other composer packages you might need for testing. I find this quite unsatisfactory.

**Comment by mikehaertl** [comment]
@DavertMik One more thing: All the points you mentioned also apply to the [existing docs](https://codeception.com/install) for global phar installation:

> **Install Phar Globally**
> sudo curl -LsS https://codeception.com/codecept.phar -o /usr/local/bin/codecept
> sudo chmod a+x /usr/local/bin/codecept
> Execute it as codecept

What's the big difference to my suggestion?
