### ISSUE TITLE
Config failed

### ISSUE THREAD

**Issue by CtrlShiftN** [Codeception/Codeception#5693]
![image](https://user-images.githubusercontent.com/22751603/65481192-a848b300-debe-11e9-87de-be6c6afcefd6.png)
Here are my issues! First, it does not have color, the result is a little bit ugly. Second, when I tried to config it, first, it can not recognize class from other dir (Ex: 

> **common/tests/unit**

 can not find class on 

> **common/components/detector**

) then, after I tried my best to fix it, It can not recognize **Yii**. After **Yii** recognized, **_getDB()_** is _Null_ now. How can I fix this?

**Comment by CtrlShiftN** [comment]
Here is what I did. Now what should I did to fix this?
![image](https://user-images.githubusercontent.com/22751603/65481509-d4186880-debf-11e9-96e4-b92fa93a7420.png)

**Comment by Naktibalda** [comment]
What version of Codeception was that?
GetDb() on null issue was reported multiple times before: https://github.com/Codeception/Codeception/search?q=getDB+on+null&type=Issues
And there were multiple attempts to fix it in different ways.
