### ISSUE TITLE
Question about comment in package/Compiler.php

### ISSUE THREAD

**Issue by wyhmichael** [Codeception/Codeception#570]
Hey team,

There's comment at line 92 in package/Complier.php, saying

```
 //do not use compressFiles as it has issue with temporary file when adding large amount of files
```

but the following line is still using:

``` php
$phar->compressFiles(\Phar::GZ);
```

and I did get errors when building phar

```
Uncaught exception 'BadMethodCallException' with message 'unable to create temporary file'
```

beside, I tried to change `compressFiles` into `compress`, then I got the different error

```
include(phar:///Users/michaelwang/code/Codeception/package/codecept.phar/index.php): failed to open stream: phar error: "index.php" is not a file in phar
```

at last, I remove the line to not use compress at all, and got the phar built successfully.

so I got a little confused here, is the compress function necessary here? or it's just optional to minimize the file size?

thx

**Comment by tkn98** [comment]
I could fix this by increasing the file-limit to 500000 https://rtcamp.com/tutorials/linux/increase-open-files-limit/
