### ISSUE TITLE
Unable to generate remote coverage

### ISSUE THREAD

**Issue by paoloacruz** [Codeception/Codeception#5700]
#### What are you trying to achieve?
I'm trying to generate a coverage using remote testing

#### What do you get instead?
 [UnexpectedValueException]
  phar error: "/tmp/C3jXHtez.tar" is a corrupted tar file (checksum mismatch of file "<!DOCTYPE html> <html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" ")

> Provide console output if related. Use `-vvv` mode for more details.
Exception trace:
 () at phar:///usr/local/bin/codecept/src/Codeception/Coverage/Subscriber/RemoteServer.php:55
 PharData->__construct() at phar:///usr/local/bin/codecept/src/Codeception/Coverage/Subscriber/RemoteServer.php:55
 Codeception\Coverage\Subscriber\RemoteServer->retrieveAndPrintHtml() at phar:///usr/local/bin/codecept/src/Codeception/Coverage/Subscriber/RemoteServer.php:33
 Codeception\Coverage\Subscriber\RemoteServer->afterSuite() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/codecept/vendor/symfony/event-dispatcher/EventDispatcher.php:212
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/codecept/vendor/symfony/event-dispatcher/EventDispatcher.php:44
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at phar:///usr/local/bin/codecept/src/Codeception/SuiteManager.php:160
 Codeception\SuiteManager->run() at phar:///usr/local/bin/codecept/src/Codeception/Codecept.php:193
 Codeception\Codecept->runSuite() at phar:///usr/local/bin/codecept/src/Codeception/Codecept.php:160
 Codeception\Codecept->run() at phar:///usr/local/bin/codecept/src/Codeception/Command/Run.php:496
 Codeception\Command\Run->runSuites() at phar:///usr/local/bin/codecept/src/Codeception/Command/Run.php:391
 Codeception\Command\Run->execute() at phar:///usr/local/bin/codecept/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:228
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/codecept/src/Codeception/Application.php:107
 Codeception\Application->run() at phar:///usr/local/bin/codecept/codecept:38
 require_once() at /usr/local/bin/codecept:7

### Details

* Codeception version: 3.0.3
* PHP Version: 7.1
* Installation type: Phar 
* List of installed packages (`composer show`)
amnuts/opcache-gui                v2.2.2    A clean, effective and responsive interface for Zend OPcache, with real(ish)-time monitoring, filtering and the ability to invalidate files
colinmollenhour/credis            1.7       Credis is a lightweight interface to the Redis key-value store which wraps the phpredis library when available for better performance.
elasticsearch/elasticsearch       v2.3.0    PHP Client for Elasticsearch
endroid/qrcode                    1.5.7     Endroid QR Code
facebook/graph-sdk                5.4.4     Facebook SDK for PHP
filp/whoops                       2.1.0     php error handling for cool kids
geoip2/geoip2                     v2.3.3    MaxMind GeoIP2 PHP API
google/apiclient                  1.1.7     Client library for Google APIs
guzzlehttp/guzzle                 6.2.2     Guzzle is a PHP HTTP client library
guzzlehttp/promises               v1.3.1    Guzzle promises library
guzzlehttp/psr7                   1.4.0     PSR-7 message implementation that also provides common utility methods
guzzlehttp/ringphp                1.1.0     Provides a simple API and specification that abstracts away the details of HTTP into a single PHP function.
guzzlehttp/streams                3.0.0     Provides a simple abstraction over streams of data
hybridauth/hybridauth             v2.6.0    Open source social sign on PHP library.
linfo/linfo                       v3.0.0    App and library for easily parsing and displaying system information of the host, like network/torrents/cpu/memory/usb/pci/sound cards/filesystems/raid array/ipmi...
maxmind-db/reader                 v1.1.0    MaxMind DB Reader API
maxmind/web-service-common        v0.0.4    Internal MaxMind Web Service API
monolog/monolog                   1.18.1    Sends your logs to files, sockets, inboxes, databases and various web services
oyejorge/less.php                 v1.7.0.10 PHP port of the Javascript version of LESS http://lesscss.org
paragonie/random_compat           v2.0.1    PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pear/net_url2                     v2.2.0    Class for parsing and handling URL. Provides parsing of URLs into their constituent parts (scheme, host, path etc.), URL generation, and resolving of relative URLs.
psr/http-message                  1.0.1     Common interface for HTTP messages
psr/log                           1.0.0     Common interface for logging libraries
ramsey/uuid                       3.3.0     Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
react/promise                     v2.5.0    A lightweight implementation of CommonJS Promises/A for PHP
sabre/dav                         3.1.2     WebDAV Framework for PHP
sabre/event                       3.0.0     sabre/event is a library for lightweight event-based programming
sabre/http                        4.2.1     The sabre/http library provides utilities for dealing with http requests and responses.
sabre/uri                         1.1.0     Functions for making sense out of URIs.
sabre/vobject                     4.0.3     The VObject library for PHP allows you to easily parse and manipulate iCalendar and vCard objects
sabre/xml                         1.4.1     sabre/xml is an XML library that you may not hate.
symfony/console                   v3.0.3    Symfony Console Component
symfony/css-selector              v3.0.3    Symfony CssSelector Component
symfony/event-dispatcher          v3.0.3    Symfony EventDispatcher Component
symfony/finder                    v3.0.3    Symfony Finder Component
symfony/polyfill-mbstring         v1.1.1    Symfony polyfill for the Mbstring extension
symfony/process                   v3.0.3    Symfony Process Component
symfony/var-dumper                v3.0.3    Symfony mechanism for exploring and dumping PHP variables
tijsverkoyen/css-to-inline-styles 1.5.5     CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when you're sending emails.
vrana/adminer                     v4.2.4    Database management in a single PHP file.
zendframework/zendframework1      1.12.17   Zend Framework 1

* Suite configuration:

**api.suite.yml**
```yml
actor: ApiTester
modules:
    enabled:
        - \Helper\Api
        - REST:
            url: 'http://local.ecomv4.com/'
            depends: PhpBrowser
            part: Json
```

**codeception.yml**
```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: true
    c3_url: 'http://local.ecomv4.com'
    include:
        - website/controllers/*
        - website/lib/Website/*
        - website/lib/Object/*
        - modules/api/controllers/WebserviceController.php
    low_limit: 30
    high_limit: 70
    show_uncovered: false
    show_only_summary: false

```

**Comment by Naktibalda** [comment]
Have you included c3.php in the code of your website as documented in https://github.com/Codeception/c3/ ?

**Comment by paoloacruz** [comment]
Hi,

Yes I did. Actually I'm running an api test but on my local do i still have to use remote coverage?

sample of my testing.

    public function testxxx(ApiTester $I)
    {
        $I->haveHttpHeader('Content-Type', 'application/x-www-form-urlencoded');
        $I->sendPOST('/xxx/yyy', [
          'param1' => 'xxx|222|xxx'
        ]);
        $I->seeResponseIsJson();
        $I->seeResponseContains('"result1":"xxxx"');
    }

**Comment by Naktibalda** [comment]
If you are using PhpBrowser module, you need `c3`.

**Comment by Naktibalda** [comment]
There was something wrong with c3.php file on that site.
