### ISSUE TITLE
Question: how should i configure Doctrine2 with Db module?

### ISSUE THREAD

**Issue by Sentoki** [Codeception/Codeception#5716]
#### What are you trying to achieve?
Try test some service that get EntityManager as constructor parameter.

#### What do you get instead?
Tests use developer database instead of test database from unit.suite.yml.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
$ vendor/bin/codecept run -vvv
Codeception PHP Testing Framework v3.1.1
Powered by PHPUnit 8.4.1 by Sebastian Bergmann and contributors.
Running with seed: 


  [Connecting To Db] {"config":{"populate":false,"cleanup":false,"reconnect":false,"waitlock":0,"dump":null,"populator":null,"dsn":"sqlite:tests/_data/wtf.sqlite","user":"without it i see exception","password":"without it i see exception"},"options":[]}
  [Db] Connected to default 

App\Tests.unit Tests (1) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Asserts, \App\Tests\Helper\Unit, Db, Symfony, Doctrine2
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- FirstTest: Some feature2019-10-13T15:28:16+07:00 [debug] "START TRANSACTION"
  [Database] Transaction started
2019-10-13T15:28:16+07:00 [debug] SELECT NEXTVAL('vehicle_id_seq')
2019-10-13T15:28:16+07:00 [debug] INSERT INTO vehicle (id, name, max_speed, created) VALUES (?, ?, ?, ?)
2019-10-13T15:28:16+07:00 [debug] SELECT v0_.id AS id_0, v0_.name AS name_1, v0_.max_speed AS max_speed_2, v0_.created AS created_3 FROM vehicle v0_ WHERE v0_.name = ? LIMIT 1
✖ FirstTest: Some feature (0.04s)
2019-10-13T15:28:16+07:00 [debug] "ROLLBACK"
  [Database] Transaction cancelled; all changes reverted.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DEPRECATION: Calling the "Codeception\Lib\Connector\Symfony::getInternalResponse()" method before the "request()" one is deprecated since Symfony 4.1 and will throw an exception in 5.0. /home/egor/PhpstormProjects/symfony_4_codeception/vendor/symfony/browser-kit/Client.php:219


Time: 156 ms, Memory: 20.00 MB

There was 1 failure:

---------
1) FirstTest: Some feature
 Test  tests/unit/FirstTest.php:testSomeFeature
Failed asserting that 100.0 matches expected 20.

```
unit.suite.yml
```yml
actor: UnitTester
modules:
    enabled:
        - Asserts
        - \App\Tests\Helper\Unit
        - Db:
            dsn: 'sqlite:tests/_data/wtf.sqlite'
            user: 'without it i see exception'
            password: 'without it i see exception'
        - Symfony:
            app_path: 'src'
        - Doctrine2:
            depends: Symfony
            cleanup: true

```
.env
```
APP_ENV=dev
APP_SECRET=zzzzz
DATABASE_URL=pgsql://postgres:123456@127.0.0.1:5432/symfony_4_codeception

```

### Details

* Codeception version: 3.1.1
* PHP Version: 7.3.10-1
* Operating System: ubuntu18.04.1
* Composer
* ```
$ composer show
behat/gherkin                       v4.6.0     Gherkin DSL parser for PHP 5.3
codeception/codeception             3.1.1      BDD-style testing framework
codeception/phpunit-wrapper         8.0.4      PHPUnit classes used by Codeception
codeception/stub                    3.5.0      Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/annotations                v1.8.0     Docblock Annotations Parser
doctrine/cache                      v1.8.0     Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.6.2     PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                     v2.11.0    PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support...
doctrine/data-fixtures              v1.3.2     Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.9.2     Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle            1.11.2     Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.5      Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle   3.2.2      Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle v2.0.0     Symfony DoctrineMigrationsBundle
doctrine/event-manager              v1.0.0     Doctrine Event Manager component
doctrine/inflector                  v1.3.0     Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.2.0      A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      1.1.0      PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 2.1.1      PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and e...
doctrine/orm                        v2.6.4     Object-Relational-Mapper for PHP
doctrine/persistence                1.1.1      The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                 v1.0.0     Doctrine Reflection component
facebook/webdriver                  1.7.1      A PHP client for Selenium WebDriver
guzzlehttp/guzzle                   6.3.3      Guzzle is a PHP HTTP client library
guzzlehttp/promises                 v1.3.1     Guzzle promises library
guzzlehttp/psr7                     1.6.1      PSR-7 message implementation that also provides common utility methods
hoa/consistency                     1.17.05.02 The Hoa\Consistency library.
hoa/console                         3.17.05.02 The Hoa\Console library.
hoa/event                           1.17.01.13 The Hoa\Event library.
hoa/exception                       1.17.01.16 The Hoa\Exception library.
hoa/file                            1.17.07.11 The Hoa\File library.
hoa/iterator                        2.17.01.10 The Hoa\Iterator library.
hoa/protocol                        1.17.01.14 The Hoa\Protocol library.
hoa/stream                          1.17.02.21 The Hoa\Stream library.
hoa/ustring                         4.17.01.16 The Hoa\Ustring library.
jdorn/sql-formatter                 v1.2.17    a PHP SQL highlighting library
myclabs/deep-copy                   1.9.3      Create deep copies (clones) of your objects
nikic/php-parser                    v4.2.4     A PHP parser written in PHP
ocramius/package-versions           1.5.1      Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager              2.2.3      A library providing utilities to generate, instantiate and generally operate with Object Proxies
phar-io/manifest                    1.0.3      Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                     2.0.1      Library for handling version information and constraints
phpdocumentor/reflection-common     2.0.0      Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.2      With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver         1.0.1      A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                    1.9.0      Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           7.0.8      Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           2.0.2      FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template           1.2.1      Simple template engine.
phpunit/php-timer                   2.1.2      Utility class for timing
phpunit/php-token-stream            3.1.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     8.4.1      The PHP Unit Testing framework.
psr/cache                           1.0.1      Common interface for caching libraries
psr/container                       1.0.0      Common Container Interface (PHP FIG PSR-11)
psr/http-message                    1.0.1      Common interface for HTTP messages
psr/log                             1.1.0      Common interface for logging libraries
ralouphie/getallheaders             3.0.3      A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup  1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator                3.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                      3.0.2      Diff implementation
sebastian/environment               4.2.2      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  3.1.2      Provides the functionality to export PHP variables for visualization
sebastian/global-state              3.0.0      Snapshotting of global state
sebastian/object-enumerator         3.0.3      Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector          1.1.1      Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context         3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations       2.0.1      Provides a list of PHP built-in functions that operate on resources
sebastian/type                      1.1.3      Collection of value objects that represent the types of the PHP type system
sebastian/version                   2.0.1      Library that helps with managing the version number of Git-hosted PHP projects
symfony/browser-kit                 v4.3.5     Symfony BrowserKit Component
symfony/cache                       v4.3.5     Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts             v1.1.7     Generic abstractions related to caching
symfony/config                      v4.3.5     Symfony Config Component
symfony/console                     v4.3.5     Symfony Console Component
symfony/css-selector                v4.3.5     Symfony CssSelector Component
symfony/debug                       v4.3.5     Symfony Debug Component
symfony/dependency-injection        v4.3.5     Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.3.5     Symfony Doctrine Bridge
symfony/dom-crawler                 v4.3.5     Symfony DomCrawler Component
symfony/dotenv                      v4.3.5     Registers environment variables from a .env file
symfony/event-dispatcher            v4.3.5     Symfony EventDispatcher Component
symfony/event-dispatcher-contracts  v1.1.7     Generic abstractions related to dispatching event
symfony/filesystem                  v4.3.5     Symfony Filesystem Component
symfony/finder                      v4.3.5     Symfony Finder Component
symfony/flex                        v1.4.6     Composer plugin for Symfony
symfony/framework-bundle            v4.3.5     Symfony FrameworkBundle
symfony/http-foundation             v4.3.5     Symfony HttpFoundation Component
symfony/http-kernel                 v4.3.5     Symfony HttpKernel Component
symfony/maker-bundle                v1.13.0    Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                        v4.3.5     A library to manipulate MIME messages
symfony/orm-pack                    v1.0.6     A pack for the Doctrine ORM
symfony/polyfill-intl-idn           v1.12.0    Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring           v1.12.0    Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.12.0    Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73              v1.12.0    Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                     v4.3.5     Symfony Process Component
symfony/routing                     v4.3.5     Symfony Routing Component
symfony/service-contracts           v1.1.7     Generic abstractions related to writing services
symfony/stopwatch                   v4.3.5     Symfony Stopwatch Component
symfony/var-exporter                v4.3.5     A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/yaml                        v4.3.5     Symfony Yaml Component
theseer/tokenizer                   1.1.3      A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                    1.5.0      Assertions to validate method input/output with nice error messages.
zendframework/zend-code             3.4.0      Extensions to the PHP Reflection API, static code scanning, and code generation
zendframework/zend-eventmanager     3.2.1      Trigger and listen to events within a PHP application

```

**Comment by Naktibalda** [comment]
What do you actually want to do?

Configuring Db module does not make your app code to use that database, you
must configure your app to use that database using whatever configuration
method your framework provides.

Doctrine2 module doesn't really mix with Db module, pick one.

In order for Db module to see changes made by Doctrine2 or app code and
vice versa, transaction flag must be turned off in Doctrine2 module, so you
loose automatic rollback at the end of test feature.

**Comment by Sentoki** [comment]
I try use test database for tests instead of my local developer database, that local copy of production. So i should use enviroments unstead of configuring it in unit.suite.yml ?

**Comment by Naktibalda** [comment]
Yes, that's right.
