### ISSUE TITLE
Can't click on item from list

### ISSUE THREAD

**Issue by Gadzillion** [Codeception/Codeception#5730]
#### What are you trying to achieve?

I want to click on every button in list.

#### What do you get instead?

  [Error] Call to a member function click() on string  

```
  [Selenium browser Logs] 
  16:35:34.139 SEVERE - https://www.nespresso.com/ru/ru/ 0:0 Uncaught (in promise)
  16:35:34.667 SEVERE - https://fonts.googleapis.com/css?family=NespressoLucas - Failed to load resource: the server responded with a status of 400 ()
  16:35:34.703 SEVERE - https://fonts.googleapis.com/css?family=NespressoLucas - Failed to load resource: the server responded with a status of 400 ()
  16:35:34.829 SEVERE - https://fonts.googleapis.com/css?family=NespressoLucas - Failed to load resource: the server responded with a status of 400 ()
  16:35:38.194 WARNING - webpack-internal:///./Javascript.SDK/Common/Logging/LogManager.ts 37:20 "LogManager was not instantiated before (in entry file). Using dummy."
  16:35:38.194 WARNING - webpack-internal:///./Javascript.SDK/Common/Logging/LogManager.ts 53:16 "DummyLogger trackEvent"
  16:35:40.400 WARNING - https://www.nespresso.com/ru/static/version1571692910/frontend/Mygento/nespresso/ru_RU/jquery/jquery-migrate.min.js 7:265 "JQMIGRATE: jQuery.attrFn is deprecated"
  16:35:45.978 SEVERE - https://www.nespresso.com/ru/ru/coffee-capsules/original 0:0 Uncaught (in promise)
  16:35:50.304 WARNING - webpack-internal:///./Javascript.SDK/Common/Logging/LogManager.ts 37:20 "LogManager was not instantiated before (in entry file). Using dummy."
  16:35:50.305 WARNING - webpack-internal:///./Javascript.SDK/Common/Logging/LogManager.ts 53:16 "DummyLogger trackEvent"
  
  [Selenium driver Logs]  EMPTY 
  Screenshot and page source were saved into '/home/hamster/Desktop/regressio/tests/_output/' dir

```

#### Related test source code

```
$elements = $I->grabMultiple('.action.delete');
foreach($elements as $element) {
      $element->click();
}
```
print_r($elements);

```
Array
(
    [0] => 
    [1] => 
    [2] => 
)
```

### Details

* Codeception version: 3.1.2
* PHP Version: 7.2.23
* Operating System: Linux Mint
* Installation type: Composer

**Comment by Naktibalda** [comment]
`grabMultiple` returns text of matching HTML elements,

Use [_findElements](https://codeception.com/docs/modules/WebDriver#_findElements) method which is only available in helper functions.

**Comment by Naktibalda** [comment]
`click` method of WebDriver module does not accept RemoteWebElement as parameter.
Try calling `click` method of the element itself: `$element->click()`

**Comment by Gadzillion** [comment]
@Naktibalda , thx 2nd time, but ...
```
        /**
         * @var $element \WebDriverElement
         */
        foreach($elements as $element) {
            $I->wait(4);
            $element->click();
            $this->waitForLoader($loaderLoc);
        }
```
i modified code like you say, but i forgot to say that when i click delete button, one item from the list disappear and when i try to do second click i get an error.

#### [Facebook\WebDriver\Exception\StaleElementReferenceException] stale element reference: element is not attached to the page document

How can i solve this problem without updating the page and using _findElements in cycle ?

**Comment by Naktibalda** [comment]
Are you sure that clicking the page does not reload the page?

You could go back to `grabMultiple` and use it to grab ids of all buttons, ids would be usable even if the page is reloaded:

```php
$elementIds = $I->grabMultiple('.action.delete', 'id');
foreach ($elementIds as $elementId) {
    $I->click('#' . $elementId);
}

**Comment by Gadzillion** [comment]
@Naktibalda thx u a lot, it's worked

```
        $elementIds = $I->grabMultiple('.action.delete', 'data-cart-item');
        foreach ($elementIds as $elementId) {
            $I->wait(4);
            $I->click('a[data-cart-item="' . $elementId . '"]');
            $this->waitForLoader($loaderLoc);
        }
```

I wish I could unify that. Thanks for the answers, I didn't know that _findElements needed a page refresh to work.

**Comment by Gadzillion** [comment]
@Naktibalda How can i catch my own exception, on this function, if method expectedException() is deprecated ?

**Comment by Naktibalda** [comment]
If you can't catch exception, you got its name wrong.

**Comment by Gadzillion** [comment]
@Naktibalda thx u
