### ISSUE TITLE
Where is the docs repo now? Are we still able to make PRs to it?

### ISSUE THREAD

**Issue by AndrewFeeney** [Codeception/Codeception#5731]
#### What are you trying to achieve?

Make a pull request to the docs.

#### What do you get instead?

Not sure where to find them now

### Details

* Codeception version: 4.0

**Comment by Naktibalda** [comment]
Please make a pull request to https://github.com/Codeception/codeception.github.com/

**Comment by AndrewFeeney** [comment]
@Naktibalda Thanks!
