### ISSUE TITLE
Document `pause()`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5739]
The new (cool!) `pause()` function isn't documented at all in https://codeception.com/docs/modules/WebDriver

I saw the docs at https://codeception.com/docs/02-GettingStarted#Interactive-Pause but it should be explained in the supported modules' docs too!

**Comment by ThomasLandauer** [comment]
Since the removal of `pauseExecution()` isn't mentioned anywhere in Codeception docs, I explained it at https://stackoverflow.com/q/58738611/1668200

**Comment by DavertMik** [comment]
It is not a part of a module so can't be documented there. But probably it can be mentioned in the beginning of a reference

**Comment by ThomasLandauer** [comment]
I see your point. My point is:
* `pauseExecution()` used to be at https://codeception.com/docs/modules/WebDriver - and now it's suddenly gone.
* Usually, anything you need inside a test is documented on the module's page. "Generic" functions like `see()` are inherited into each module docs. So I'd expect this to be true for "super-generic" functions like `pause()` too.

What do you mean by "in the beginning of a reference"?

**Comment by Naktibalda** [comment]
`see` is not generic, WebDriver has it's own definition of `see` - https://github.com/Codeception/Codeception/blob/3.1.2/src/Codeception/Module/WebDriver.php#L928-L937
PhpBrowser and framework modules actually inherit `see` and other standard assertion methods from InnerBrowser class.
Other modules have no `see` method.
