### ISSUE TITLE
Explain how to exit the interactive shell (`pause()`)

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5740]
When starting the interactive shell, it should also be explain how to exit it:

> Type in commands to try them, ENTER to continue, TAB to auto-complete

It looks like typing "exit" exits the interactive console and continues with the test, right? So maybe:

> Type in commands to try them, ENTER to continue, TAB to auto-complete, 'exit' to leave the console

I noticed that pressing Ctrl+C quits the Codeception run completely, but leaves the browser window (in acceptance test) open. Is there a command to gracefully stop the test and close the browser?

https://github.com/Codeception/Codeception/blob/9c69ec708f15140be20341d342c330d68fb04197/src/Codeception/Lib/Actor/Shared/Pause.php#L26

**Comment by Naktibalda** [comment]
There is no such explanation anymore since hoa/console was replaced by PsySH in #6385
