### ISSUE TITLE
How can I call `pause()` from a Helper?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5741]
I have `class Acceptance extends \Codeception\Module` in `/tests/_support/Helper/Acceptance.php`. How can I call the new `pause()` function from within a function there?

`$this->getModule('WebDriver')->pause()` is not working.

If you tell me, I'll come up with a commit to explain it at https://codeception.com/docs/06-ModulesAndHelpers#Helpers

**Comment by Naktibalda** [comment]
`pause` method does not belong to `WebDriver` method, it belongs to `Actor` class, so you can call it as `$I->pause()` in the test and as `$this->pause()` in `AcceptanceTester` class which extends `Actor`.

**Comment by ThomasLandauer** [comment]
As shown at https://codeception.com/docs/06-ModulesAndHelpers#Helpers my Helper class extends `\Codeception\Module`. Is this outdated?

**Comment by Naktibalda** [comment]
No, it is correct.
I don't think that it is possible to call `pause` from Helper class.

**Comment by ThomasLandauer** [comment]
Hm, bad news :-( And since you just changed the architecture, you're probably not so eager to change it again? ;-)

Anyway, since `pauseExecution()` did work in Helpers before, this is now somewhat of a step back. If `pause()` is not so easy to implement there, maybe you could bring back `pauseExecution()` for that purpose? Should I open a feature request? For what?

Short-term: If `pause()` is not available, this should be mentioned at https://codeception.com/docs/06-ModulesAndHelpers#Helpers I will make a PR for that. Which methods does it also apply too? I guess `retry()`? Any others?

**Comment by Naktibalda** [comment]
Pause is implemented as a trait and has no dependencies, so you can try to use that trait in your helper class.

```php
namespace Helper;

use Codeception\Lib\Actor\Shared\Pause;

class Acceptance extends \Codeception\Module
{
    use Pause;

    public function myFunction()
    {
        $this->pause();
    }
}
```
