### ISSUE TITLE
Fail  Form field by Label or CSS element with was not found.

### ISSUE THREAD

**Issue by corpsameer** [Codeception/Codeception#5755]
#### What are you trying to achieve?
I am trying to write acceptance test for successful login to the website. The test is always failing.
#### What do you get instead?
The acceptance test always fails in PHPBrowser with following error message:
Form field by Label or CSS element with '#email_address' was not
found.
> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
1) SigninCest: Login success
  Test  tests/acceptance/SigninCest.php:loginSuccess
  Step  Fill field "#email_address","sagarwal@claytonkendall.com"
  Fail  Form field by Label or CSS element with '#email_address' was not
found.

Scenario Steps:

  3. $I->fillField("#email_address","sagarwal@claytonkendall.com") at
tests/acceptance/SigninCest.php:14
  2. $I->see("Welcome, Guest") at tests/acceptance/SigninCest.php:13
  1. $I->amOnPage("/login") at tests/acceptance/SigninCest.php:12

Artifacts:

Html:
/var/www/html/oscr/test_cases/tests/_output/SigninCest.loginSuccess.fail.html
Response:
/var/www/html/oscr/test_cases/tests/_output/SigninCest.loginSuccess.fail.html

FAILURES!
Tests: 2, Assertions: 3, Failures: 1.
```
> Provide test source code if related

```php
// paste test
<?php 

class SigninCest
{
    public function _before(AcceptanceTester $I)
    {
    }

    // tests
    public function loginSuccess(AcceptanceTester $I)
    {
        $I->amOnPage('/login');
        $I->see('Welcome, Guest');
        $I->fillField("#email_address", "sagarwal@claytonkendall.com");
        $I->fillField("#password", "Test@123");
        $I->click("Login");
    }
}
```
### Details

* Codeception version: 3.1.2
* PHP Version: 7.2.12
* Operating System: Ubuntu 16.04
* Installation type: Composer
* List of installed packages (`composer show`)
behat/gherkin                      v4.6.0     Gherkin DSL parser for PHP 5.3
codeception/codeception            3.1.2      BDD-style testing framework
codeception/phpunit-wrapper        8.0.4      PHPUnit classes used by
Codeception
codeception/stub                   3.5.0      Flexible Stub wrapper for
PHPUnit's Mock Builder
facebook/webdriver                 1.7.1      A PHP client for Selenium
WebDriver
guzzlehttp/guzzle                  6.4.1      Guzzle is a PHP HTTP
client library
guzzlehttp/promises                v1.3.1     Guzzle promises library
guzzlehttp/psr7                    1.6.1      PSR-7 message
implementation that also provides common utility methods
hoa/consistency                    1.17.05.02 The Hoa\Consistency library.
hoa/console                        3.17.05.02 The Hoa\Console library.
hoa/event                          1.17.01.13 The Hoa\Event library.
hoa/exception                      1.17.01.16 The Hoa\Exception library.
hoa/file                           1.17.07.11 The Hoa\File library.
hoa/iterator                       2.17.01.10 The Hoa\Iterator library.
hoa/protocol                       1.17.01.14 The Hoa\Protocol library.
hoa/stream                         1.17.02.21 The Hoa\Stream library.
hoa/ustring                        4.17.01.16 The Hoa\Ustring library.
myclabs/deep-copy                  1.9.3      Create deep copies
(clones) of your objects
phar-io/manifest                   1.0.3      Component for reading
phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1      Library for handling
version information and constraints
phpdocumentor/reflection-common    2.0.0      Common reflection classes
used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.2      With this component, a
library can provide support for annotations via DocBlocks or otherwise
retrieve information tha...
phpdocumentor/type-resolver        1.0.1      A PSR-5 based resolver of
Class names, Types and Structural Element Names
phpspec/prophecy                   1.9.0      Highly opinionated mocking
framework for PHP 5.3+
phpunit/php-code-coverage          7.0.8      Library that provides
collection, processing, and rendering functionality for PHP code
coverage information.
phpunit/php-file-iterator          2.0.2      FilterIterator
implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1      Simple template engine.
phpunit/php-timer                  2.1.2      Utility class for timing
phpunit/php-token-stream           3.1.1      Wrapper around PHP's
tokenizer extension.
phpunit/phpunit                    8.4.3      The PHP Unit Testing
framework.
psr/container                      1.0.0      Common Container Interface
(PHP FIG PSR-11)
psr/http-message                   1.0.1      Common interface for HTTP
messages
ralouphie/getallheaders            3.0.3      A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup 1.0.1      Looks up which function or
method a line of code belongs to
sebastian/comparator               3.0.2      Provides the functionality
to compare PHP values for equality
sebastian/diff                     3.0.2      Diff implementation
sebastian/environment              4.2.2      Provides functionality to
handle HHVM/PHP environments
sebastian/exporter                 3.1.2      Provides the functionality
to export PHP variables for visualization
sebastian/global-state             3.0.0      Snapshotting of global state
sebastian/object-enumerator        3.0.3      Traverses array structures
and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1      Allows reflection of
object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0      Provides functionality to
recursively process PHP variables
sebastian/resource-operations      2.0.1      Provides a list of PHP
built-in functions that operate on resources
sebastian/type                     1.1.3      Collection of value
objects that represent the types of the PHP type system
sebastian/version                  2.0.1      Library that helps with
managing the version number of Git-hosted PHP projects
symfony/browser-kit                v4.3.8     Symfony BrowserKit Component
symfony/console                    v4.3.8     Symfony Console Component
symfony/css-selector               v4.3.8     Symfony CssSelector Component
symfony/dom-crawler                v4.3.8     Symfony DomCrawler Component
symfony/event-dispatcher           v4.3.8     Symfony EventDispatcher
Component
symfony/event-dispatcher-contracts v1.1.7     Generic abstractions
related to dispatching event
symfony/finder                     v4.3.8     Symfony Finder Component
symfony/polyfill-ctype             v1.12.0    Symfony polyfill for ctype
functions
symfony/polyfill-mbstring          v1.12.0    Symfony polyfill for the
Mbstring extension
symfony/polyfill-php73             v1.12.0    Symfony polyfill
backporting some PHP 7.3+ features to lower PHP versions
symfony/process                    v4.3.8     Symfony Process Component
symfony/service-contracts          v1.1.8     Generic abstractions
related to writing services
symfony/yaml                       v4.3.8     Symfony Yaml Component
theseer/tokenizer                  1.1.3      A small library for
converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.5.0      Assertions to validate
method input/output with nice error messages.

* Suite configuration:

```yml
# paste suite config here
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://172.21.9.160
        - \Helper\Acceptance
    step_decorators: ~
```

```HTML page source

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>Login</title>
                <base href="https://172.21.9.160/">
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Deka Lash" />
<meta name="description" content="-" />
<meta name="robots" content="noindex" />
<meta property="og:site_name" content="Deka Lash" />
<meta property="og:title" content="Login" />
<meta property="og:description" content="-" />
<meta property="og:type" content="product" />
<meta property="og:url" content="" />

<link rel="canonical" href="https://172.21.9.160/login.php" /> 
<link rel="stylesheet" type="text/css" href="templates/default/css/content.css?v=1568831599">
<link rel="stylesheet" type="text/css" href="templates/dekalash/css/content.css?v=1525788367">
<link rel="stylesheet" type="text/css" href="templates/default/css/pages/login.css?v=1568831599">
<link rel="stylesheet" type="text/css" href="templates/dekalash/css/pages/login.css?v=1525788367">
<link rel="stylesheet" type="text/css" href="includes/js/magiczoom/magiczoom.css?v=1525788366">
<link rel="stylesheet" type="text/css" href="templates/default/css/jquery-ui-plugins.css?v=1525788367">
<link rel="stylesheet" type="text/css" href="templates/default/css/jquery-ui.css?v=1525788367">
<link rel="stylesheet" type="text/css" href="includes/lytebox/lytebox.css?v=1525788366">
<link rel="stylesheet" type="text/css" href="includes/js/jquery/plugins/autocomplete/css/jquery.autocomplete.css?v=1525788366"><script src="/includes/lytebox/lytebox.js?v=1551098193" defer></script>
<script src="/includes/js/jquery/dist/jquery.min.js?v=1525788366"></script>
<script src="/js/functions.js?v=1573829339"></script>
<script src="/includes/js/jquery/dist/jquery-ui.min.js?v=1525788366"></script>
<script src="/includes/js/jquery/src/jquery.form.min.js?v=1525788366"></script>
<script src="/js/docready.js?v=1569416986"></script>
<script src="/includes/js/jquery/plugins/shadow/jquery.dropshadow.min.js?v=1525788366"></script>
<script src="/includes/js/jquery/plugins/mousewheel/jquery.mousewheel.min.js?v=1525788366"></script>
<script src="/includes/js/magiczoom/magiczoom.js?v=1525788366" defer></script>
<script src="/includes/js/jquery/plugins/autocomplete/jquery.autocomplete.min.js?v=1525788366"></script>
<script src="/includes/js/jquery/plugins/password/password.js?v=1525788366"></script>
</head>
<body style="behavior: url(includes/csshover.htc);" class="BODYSTYLE body-login-page " onload="document.login.email_address.focus();">
            <script>
            //<![CDATA[
                var client_code = "dekalash";
                var rush_site = false;
                var mobile_version = false;
                var customer_id = -685271039;
                var client_country = 223;
                var client_private = true;

                if (!window.console) {
                    console = {
                        log: function() {},
                        info: function() {}
                    };
                }
            //]]>
            </script><div class="divTestMode">*** You are in test mode ***</div><!-- RequireJS -->
<script src="/js/AMD/require.js" data-main=""></script>
<script>
require.config({"baseUrl":"\/js\/AMD","urlArgs":"v=1573758114","paths":{"jquery":"jquery-1.8.0","jquery-ui":"jquery-ui-1-11-stable\/ui"}});
</script>
<!-- /RequireJS --><div class="body-wrapper"><div class="body-header">
    <div class="header-bar">
        <div class="container">
            <ul class="menu-links">
                <li><a href="index.php">Home</a></li>
                                    <li><a href="login.php">My Account</a></li>
                                <li><a href="shipping_map.php">Shipping</a></li>
                <li><a href="faq.php">FAQ</a></li>
                                    <li><a href="free_downloads.php">Free Downloads</a></li>
                                                    <li><a href="help.php">Help</a></li>
                                <li><a href="contact_us.php">Contact</a></li>
                                    <li><a href="login.php">Login</a></li>
                            </ul>

            <!-- Template templates/dekalash/xtpl/boxes/shopping_cart.xtpl --><div class="shopping-cart">
    <a href="checkout.php" class="checkout-button">Checkout</a>
    <a href="https://172.21.9.160/shopping_cart.php" title="My Cart" class="link">
        <img src="/templates/dekalash/site_images/cart-icon.png" class="icon" alt="Shopping Cart" />
        <span class="label">My Cart&nbsp;&nbsp;&nbsp;(0 items)&nbsp;&nbsp;&nbsp;$0.00</span>
    </a>
</div>
        </div>
    </div>
    
    <div class="header-logo-container">
        <a class="home-link" href="index.php">
            <img src="templates/dekalash/site_images/logo.png" alt="Logo" />
        </a>

        <div class="welcome-box">
                            Welcome, guest (<a href="login.php">Log In</a>)
                    </div>

        <div class="search-container">
<form name="xml_search" action="filter.php" method="get" role="search">
	<input type="text" id="search_autocomplete" name="filter_search" class="search-input" value="" placeholder="ENTER SEARCH TERMS" aria-label="Search">
    <input type="submit" id="xml_search_btn" value="search" class="button">
</form>

<script type="text/javascript">
$(function() {
	bindAutoComplete();
});
</script>

</div>
    </div>

    <div id="top-menu-wrapper">
        </div>    
</div>
<div class="body-content"><div class="body-content-left"></div><div class="body-content-main " role="main">
<form name="login" id="login" method="post" action="https://172.21.9.160/login.php?action=process">
    <div class="page-heading">Welcome!</div>

    <div class="page-content">
        <div class="registered-customer">
            <div class="customer-heading">Login</div>
            <div class="field-container">
                <label for="email_address">E-Mail Address</label>
                <input type="text" name="email_address" id="email_address" />            </div>
            <div class="field-container">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" />            </div>
            <a href="https://172.21.9.160/password_forgotten.php" class="forgot-password">
                <u>What if I forgot my password?</u>
            </a><br><br>
            <input type="submit" class="button login-button" value="Login" />
                <div class="login-sso" style="text-align:center;">
        <a class="sso-link" href="https://172.21.9.160/sso_idp_login.php?auth=8">
            <img src="templates/dekalash/banners/single-sign-on-btn-8.png">
        </a>
    </div>
        </div>
        <hr>
        <div class="new-customer">
            <div class="customer-heading">New Customer?</div>
            <a href="https://172.21.9.160/create_account.php"
               class="button register-button" rel="nofollow">Register</a>
        </div>
    </div>
</form>
                                </div> <!-- close "body-content-main" -->
                                <div class="body-content-right">                                </div> <!-- close "body-content-right" -->                                </div> <!-- close "body-content" -->
                                <div class="body-footer" role="contentinfo" aria-label="footer"><ul class="links-list">
    <li class="first"><a href="index.php">Home</a></li>
    <li><a href="shipping_map.php">Shipping</a></li>
    <li><a href="faq.php">FAQ</a></li>
    <li><a href="free_downloads.php">Free Downloads</a></li>
    <li><a href="help.php">Help</a></li>
    <li><a href="contact_us.php">Contact Us</a></li>
    <li><a href="login.php">Log In</a></li>
</ul>

<div class="copyright">
    &copy2019 <a class="footer" href="http://www.claytonkendall.com" title="Clayton Kendall" target="_blank">
    Clayton Kendall, Inc.
</a> All Rights Reserved.
</div>                                </div> <!-- close "body-footer" -->
                            </div> <!-- close "body-wrapper" -->            <script>

            //<![CDATA[

            if (typeof console != "undefined") {
                console.info("DEBUG: without logged OSCR errors");
            }
            //]]>

            </script></body></html>

```

**Comment by Naktibalda** [comment]
You said this on Slack:
> For some strange reason, the html file which is generated as artifacts after failure, shows only the first form and not the second form. This is why the test case code is not able to locate elements in the second form.
