### ISSUE TITLE
How to get framework module in GroupObject

### ISSUE THREAD

**Issue by gnumoksha** [Codeception/Codeception#5756]
#### What are you trying to achieve?
Execute Phalcon ORM operation inside a [GroupObject](https://codeception.com/docs/08-Customization#Group-Objects).

#### What do you get instead?

```bash
1) SomeControllerTest: Invalid request should fail | #0
 Test  tests/Functional/Infra/Http/Phalcon/Controller/Foo/SomeControllerTest.php:testInvalidRequestShouldFail
                                                                                                                       
  [Phalcon\Mvc\Model\Exception] A dependency injector container is required to obtain the services related to the ORM  
                                                                                                                       
#1  phalcon/mvc/model.zep:145
#2  /var/www/modules/Foo/src/Populator/FooPopulator.php:25
#3  /var/www/modules/Foo/tests/SomeFixture.php:24
#5 /var/www/modules/Foo/tests/storage/support/Group/SomeGroup.php:36
```

Which means Phalcon was not bootstrapped yet.

### Details

* Codeception version: 3.1.2
* PHP Version: 7.2.22
* Operating System: debian inside docker container
* Installation type: Composer
* List of installed packages:
* Suite configuration:

**Comment by Naktibalda** [comment]
Not enough information here.

This error happens during test run, so all modules must be initialized already.
Have you enabled Phalcon module in suite configuration file?
