### ISSUE TITLE
Symfony 5 components aren't allowed

### ISSUE THREAD

**Issue by dant89** [Codeception/Codeception#5758]
Trying to upgrade a project to use Symfony 5 but the master composer version limits of `codeception/codeception` do not allow this.

The 4.0 Symfony components were allowed with https://github.com/Codeception/Codeception/commit/08c717d371cd70b42fed58c85b5637d31f9c138c#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780 but it will likely need more changes.

**Comment by Naktibalda** [comment]
I attempted to do it earlier and it failed badly.
https://travis-ci.org/Codeception/Codeception/builds/615450284

There are at least a few backwards incompatible changes, so it is likely that a new major version (5.0) of Codeception will be required.
You are welcome to try to fix all incompatibilities.

**Comment by DavertMik** [comment]
@dant89 sorry, upgrading to Symfony 5 is not happening auto-magically. We need to rewrite the core to use next version of Symfony Components. 

Codeception 5.0 will support Symfony 5:
https://codeception.com/10-22-2019/codeception-4.0-and-beyond.html

**Comment by Naktibalda** [comment]
I am working on it: #5765
