### ISSUE TITLE
seeResponseContainsXml in REST module

### ISSUE THREAD

**Issue by FnTm** [Codeception/Codeception#576]
I have come to a point, where I would need this kind of functionality. Now the real question here is, how detailed should it be?

I see that `seeResponseContainsJson` helper has a lot of potential, and very little code to make it happen correctly. The problem with implementing this sort of thing with xml is the way xml naturally parses in PHP. If we really want to see if the response contains some arbitray xml, I see a couple of ways to do this:

- Recursive xpath. We pass in some arbitrary php array, which could also be multi dimensional, and then parse it to an xpath selector. At a first glance, this seems to be a viable option. 
- Simply allow checking against an xpath selector. This would be a VERY simple fix, and I think should be implemented in either case, since it takes a lot of repeated code out of the tests. 
- Custom xml to array parsing, and then comparing with the array provided. This could be the hardest of them all, since as far as I know, xml won't map to a plain array as nicely as `json_decode` makes it. Therefore a somewhat complex php should be used, and if we go for the easier cases, we should probably get rid of such features as xml attributes etc. If we want to keep them, the input parameters would become MUCH more complex.

Does anyone have any ideas on how this should be implemented? I have my own ideas, but ill hold them back for a while, if someone has any suggestions regarding this.

**Comment by DavertMik** [comment]
In 2.1 there are plenty of new XML validators added. You can also load only `XML` part of module with

```
    config:
          REST:
               part: xml
```
