### ISSUE TITLE
Can not stub a private method

### ISSUE THREAD

**Issue by annechko** [Codeception/Codeception#5767]
The documentation says: Properties and methods can be set as a second parameter. Even protected and private properties can be set.

So I'm trying to stub a private method and get this error:

"Trying to configure method "privateMethodName" which cannot be configured because it does not exist, has not been specified, is final, or is static"

```bash
Trying to configure method "privateMethodName" which cannot be configured because it does not exist, has not been specified, is final, or is static

WARNINGS!

```
Is it possible to stub private methods via Codeception or did I get something wrong?

Additional test would look something like this: (it does not pass for now)

```php
class DummyClass
{
    // added these 2 methods in Codeception/tests/data/DummyClass.php

    private function callPrivateMethodInside()
    {
        return $this->privateMethodName();
    }

    private function privateMethodName()
    {
        return 1;
    }
}

// and test inside Codeception/tests/unit/Codeception/Util/StubTest.php

public function testStubPrivateMethods()
{
    $tester = Stub::construct(
        DummyClass::class,
        [],
        [
            'privateMethodName' => 2,
        ]
    );
    $this->assertEquals(2, $tester->callPrivateMethodInside());
}
```
### Details

* Codeception version: Codeception 3.1.2
* PHP Version: PHP 7.2.25 (cli) (built: Nov 20 2019 18:42:58) ( ZTS MSVC15 (Visual C++ 2017) x64 )
* Operating System: Windows 8.1
* Installation type: Composer
* List of installed packages (`composer show`) 
behat/gherkin                      v4.6.0     Gherkin DSL parser for PHP 5.3
codeception/codeception            3.1.2      BDD-style testing framework
codeception/phpunit-wrapper        8.0.5      PHPUnit classes used by Codeception
codeception/stub                   3.0.0      Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.3.0      A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.7.1      A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.4.1      Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1     Guzzle promises library
guzzlehttp/psr7                    1.6.1      PSR-7 message implementation that also provides common utility methods
hoa/consistency                    1.17.05.02 The Hoa\Consistency library.
hoa/console                        3.17.05.02 The Hoa\Console library.
hoa/event                          1.17.01.13 The Hoa\Event library.
hoa/exception                      1.17.01.16 The Hoa\Exception library.
hoa/file                           1.17.07.11 The Hoa\File library.
hoa/iterator                       2.17.01.10 The Hoa\Iterator library.
hoa/protocol                       1.17.01.14 The Hoa\Protocol library.
hoa/stream                         1.17.02.21 The Hoa\Stream library.
hoa/ustring                        4.17.01.16 The Hoa\Ustring library.
myclabs/deep-copy                  1.9.3      Create deep copies (clones) of your objects
phar-io/manifest                   1.0.3      Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1      Library for handling version information and constraints
phpdocumentor/reflection-common    2.0.0      Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.2      With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in...
phpdocumentor/type-resolver        1.0.1      A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                   1.9.0      Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          7.0.10     Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          2.0.2      FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1      Simple template engine.
phpunit/php-timer                  2.1.2      Utility class for timing
phpunit/php-token-stream           3.1.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    8.0.0      The PHP Unit Testing framework.
psr/container                      1.0.0      Common Container Interface (PHP FIG PSR-11)
psr/http-message                   1.0.1      Common interface for HTTP messages
ralouphie/getallheaders            3.0.3      A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup 1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.2      Diff implementation
sebastian/environment              4.2.3      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.2      Provides the functionality to export PHP variables for visualization
sebastian/global-state             3.0.0      Snapshotting of global state
sebastian/object-enumerator        3.0.3      Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1      Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.1      Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1      Library that helps with managing the version number of Git-hosted PHP projects
symfony/browser-kit                v4.4.0     Symfony BrowserKit Component
symfony/console                    v4.4.0     Symfony Console Component
symfony/css-selector               v4.4.0     Symfony CssSelector Component
symfony/dom-crawler                v4.4.0     Symfony DomCrawler Component
symfony/event-dispatcher           v4.4.0     Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7     Generic abstractions related to dispatching event
symfony/finder                     v4.4.0     Symfony Finder Component
symfony/polyfill-ctype             v1.12.0    Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.12.0    Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.12.0    Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                    v4.4.0     Symfony Process Component
symfony/service-contracts          v2.0.0     Generic abstractions related to writing services
symfony/yaml                       v4.4.0     Symfony Yaml Component
theseer/tokenizer                  1.1.3      A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.6.0      Assertions to validate method input/output with nice error messages.

* Suite configuration:

```yml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests.

actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
error_level: E_ERROR
```

**Comment by Naktibalda** [comment]
> Properties and methods can be set as a second parameter. Even protected and private properties can be set.

The first statement makes a clear distinction between properties and methods, the second statement only states that private **properties** can be set. There was no promise to be able to set private methods.

`codeception\stub` relies on PHPUnit mocking functionality: https://github.com/Codeception/Stub/blob/master/src/Stub.php#L597-L600 , PHPUnit has never been able to mock private methods: https://travis-ci.org/Codeception/Stub/jobs/617608575#L287

`codeception/stub` can't do this, look for other mocking libraries.
