### ISSUE TITLE
[Question] Is it possible to generate test results xml report split per specified groups?

### ISSUE THREAD

**Issue by mlukjanska25f** [Codeception/Codeception#5769]
#### What are you trying to achieve?

Having tests annotated by groups eg group1, group2 etc, is it possible to generate during the tests run a separate report for each group's tests eg report_group1.xml, report_group2.xml etc

#### What do you get instead?

single report.xml

**Comment by Naktibalda** [comment]
No, there can only be a single report.xml file per test run.
