### ISSUE TITLE
Test abstract class - Stub::make error

### ISSUE THREAD

**Issue by pelcomppl** [Codeception/Codeception#5774]
Hi
I want to test abstract class methods.
I used this code:
```
public function _before(UnitTester $I)
    {
        $mac= new class extends MyAbstractController
        {
            public function __construct()
            {
                parent::__construct('', '');
            }
        };
        $this->dataController = Stub::make($mac);
    }
```
to mock this class, but stub returns error:

> [ParseError] syntax error, unexpected '@', expecting '{'
> #1  PHPUnit\Framework\MockObject\Generator->getMock

What is wrong in this code?
Or is another way to Stub abstract class?

**Comment by Naktibalda** [comment]
It looks like an issue of PHPUnit\Framework\MockObject\Generator::getMock method.

**Comment by Naktibalda** [comment]
This is a limitation of `PHPUnit\Framework\MockObject\Generator::getMock` and it can't be fixed by Codeception.
