### ISSUE TITLE
Support Symfony5

### ISSUE THREAD

**Issue by geoalex89** [Codeception/Codeception#5775]
#### Require codeception with symfony 5

When you will foresee to give support for symfony 5?

Thanks!

**Comment by Naktibalda** [comment]
As soon as 4.0.0 is released.
Symfony 5 support is merged to 4.0 branch already, #5776
4.0.0 depends on #5750 and then it can be released as soon as announcement is finished.

**Comment by geoalex89** [comment]
Yes, I knew about symfony 5 support was merged in branch 4.0.0.
So, I've tried to install codeception branch 4.0.0 `composer require codeception/codeception:4.0.* --dev` with `"minimum-stability": "dev"`.
But in that branch codeception requiere the following package: `codeception/module-filesystem` then this package require `symfony/finder` < 5.0.
The console output:
```bash
Problem 1
    - codeception/module-filesystem dev-master requires symfony/finder >=2.7 <5.0 -> no matching package found.
    - codeception/module-filesystem 1.0.1 requires symfony/finder >=2.7 <5.0 -> no matching package found.
    - codeception/module-filesystem 1.0.0 requires symfony/finder >=2.7 <5.0 -> no matching package found.
    - codeception/codeception 4.0.x-dev requires codeception/module-filesystem *@dev -> satisfiable by codeception/module-filesystem[1.0.0, 1.0.1, dev-master].
    - Installation request for codeception/codeception 4.0.* -> satisfiable by codeception/codeception[4.0.x-dev].
```

**Comment by Naktibalda** [comment]
Try again.

**Comment by scaytrase** [comment]
When 4 is planned to arrive?

**Comment by geoalex89** [comment]
> Try again.
Nice, it works!
Thank you @Naktibalda!
