### ISSUE TITLE
[PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'PRIMARY' in 'where clause'

### ISSUE THREAD

**Issue by chadicus** [Codeception/Codeception#5778]
#### What are you trying to achieve?
I am using the `Db` module with a mariadb database. 
#### What do you get instead?
I receive an error stating `Unknown column 'PRIMARY'` 
The issue stems from the Mysql driver building the following query
`SHOW KEYS FROM `my_table` where key_name = "PRIMARY"`
Maria db does not treat double quotes as string literals.
By changing the query to 
`SHOW KEYS FROM `my_table` where key_name = 'PRIMARY'`
using single quotes the issues is resolved. This should not affect mysql db users as single quotes are string literals

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 3.1.2
* PHP Version: 7.0
* Operating System: Unbuntu
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
@chadicus I merged pull request to module-db.
It can be used with Codeception 4.
To start using it now, you have to change version of codeception/codeception to `4.0.x-dev`, run `composer update` and `codecept init upgrade4`.

4.0.0 should be released within days.

**Comment by chadicus** [comment]
@Naktibalda does this mean the pull request for v3 will not be merged and released?

**Comment by Naktibalda** [comment]
I would prefer to avoid making another release of 3.1

**Comment by chadicus** [comment]
That's disappointing as my team has a rather large scale project using v3.

**Comment by Naktibalda** [comment]
Upgrade to v4 should be straightforward, the only difference is that modules must be installed as separate packages.

**Comment by chadicus** [comment]
@Naktibalda  we'll try the upgrade to v4. Hopefully a stable version will be released soon.

**Comment by Naktibalda** [comment]
Codeception 4 was released last Friday, please upgrade.
