### ISSUE TITLE
How to work with RunProcess?

### ISSUE THREAD

**Issue by TsarS** [Codeception/Codeception#5784]
#### What are you trying to achieve?
I'm trying to start selenium.jar
#### What do you get instead?

```bash
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in D:\Dev\OSPanel\domains\site\vendor\codeception\codeception\ext\RunProcess.php on line 80 and defined in D:\Dev\OSPanel\domains\site\vendor\symfony\process\Process.php:140
Stack trace:
#0 D:\Dev\OSPanel\domains\site\vendor\codeception\codeception\ext\RunProcess.php(80): Symfony\Component\Process\Process->__construct('java -jar ../ap...', 'D:\\Dev\\OSPanel\\...', NULL, NULL, NULL)
```

    class_name: AcceptanceTester
    modules:
        enabled:
               - WebDriver:
                    url: 'http://site'           
                    window_size: false
                    port: 9515
                    browser: chrome
                    capabilities:
                   "goog:chromeOptions":
               - \Helper\Acceptance
    extensions:
       enabled:
               - Codeception\Extension\RunProcess: 
                     0: java -jar ../app/tests/selenium.jar
                     sleep: 5

* Codeception version: 4
* PHP Version: 7.3
* Operating System: Windows
* Installation type: Composer

**Comment by Naktibalda** [comment]
This means that RunProcess and RunBefore extensions are incompatible with Symfony 5 and they have no tests.
In order to get it working quickly, restrict version of `symfony/process` to `4.4`

**Comment by Naktibalda** [comment]
@TsarS since we have no tests for this extension and I have no time to implement them now,
coult you set the version of codeception to `dev-issue-5784` and check if it works?
