### ISSUE TITLE
Work with actual symfony/finder

### ISSUE THREAD

**Issue by Eugentis** [Codeception/Codeception#5787]
#### What are you trying to achieve?
I would like to install codeception for my system with latest libs.
I have symfony/finder v.5.0.1
Why do you have restriction like 
```symfony/finder: >=2.7 <5.0 ```
?

#### What do you get instead?
Problem 1
    - Conclusion: don't install codeception/codeception 3.1.2
    - Conclusion: don't install codeception/codeception 3.1.1
    - Conclusion: remove symfony/finder v5.0.1
...

### Details
* Codeception v.3.1.2
* PHP v.7.4.0
* Linux on docker container
* Installation type: Composer

**Comment by jraller** [comment]
The 4.0.0 release should support this. There are several issues like #5775 that discuss this, and you can monitor https://github.com/Codeception/Codeception/milestone/40 to see the progress toward releasing 4.0.0

**Comment by Naktibalda** [comment]
4.0.0 was released last night and it supports Symfony 5.
