### ISSUE TITLE
Regression in latest release: Failed opening required 'phar://codecept.phar/vendor/codeception/codeception/app.php' / 4.4-dev served from https://codeception.com/codecept.phar

### ISSUE THREAD

**Issue by ottok** [Codeception/Codeception#5795]
#### What are you trying to achieve?

I have been using Codecept successfully for a long time. Using exactly same steps as before, the latest release has now started to fail.

Before:
```
codecept --config=/usr/share/seravo/tests/codeception/seravo.yml build
Building Actor classes for suites: acceptance
 -> AcceptanceTesterActions.php generated successfully. 174 methods added
\AcceptanceTester includes modules: Asserts, \Helper\SeravoAcceptance, WebDriver
```

Update and result started to fail:
```
curl -fsSL https://codeception.com/codecept.phar -o /usr/local/bin/codecep
chmod +x /usr/local/bin/codecept

codecept --config=/usr/share/seravo/tests/codeception/seravo.yml build
PHP Warning:  require_once(phar://codecept.phar/vendor/codeception/codeception/app.php): failed to open stream: phar error: invalid url or non-existent phar "phar://codecept.phar/vendor/codeception/codeception/app.php" in /usr/local/bin/codecept on line 5
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/codecept:0
PHP Fatal error:  require_once(): Failed opening required 'phar://codecept.phar/vendor/codeception/codeception/app.php' (include_path='.:/usr/share/php') in /usr/local/bin/codecept on line 5
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/codecept:0
```

Seems to happen on any command:
```
codecept --version
PHP Warning:  require_once(phar://codecept.phar/vendor/codeception/codeception/app.php): failed to open stream: phar error: invalid url or non-existent phar "phar://codecept.phar/vendor/codeception/codeception/app.php" in /usr/local/bin/codecept on line 5
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/codecept:0
PHP Fatal error:  require_once(): Failed opening required 'phar://codecept.phar/vendor/codeception/codeception/app.php' (include_path='.:/usr/share/php') in /usr/local/bin/codecept on line 5
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/codecept:0

strings /usr/local/bin/codecept | grep -m 1 -F "const VERSION"
const VERSION = '4.4-dev';
```

The version of Codecept that still worked was 3.1.2.

The problems seems to be that URL https://codeception.com/codecept.phar  leaks the dev version?

### Details
* PHP Version: 7.3
* Operating System: Ubuntu 18.04

**Comment by ottok** [comment]
Oneliner to repeat: 
```
curl -Ls https://codeception.com/codecept.phar -o - | strings | grep -m 1 -F "const VERSION"
const VERSION = '4.4-dev';
```

**Comment by Naktibalda** [comment]
Actually your problem is that the file is named `codecept`.
It doesn't matter what the file is named, it loads the code from file named `codecept.phar`.

You are welcome to tell me how to improve 
https://github.com/Codeception/codeception.github.com/blob/master/package/stub.php#L5
to make it load from the current file name.

**Comment by ottok** [comment]
Yes, but the root cause is that https://codeception.com/codecept.phar servers the development version 4.4-dev and not the latest release 3.1.2.

Command `curl -Ls https://codeception.com/codecept.phar -o - | strings | grep -F "3.1.2"` should return a match but it does not. The thing that serves https://codeception.com/codecept.phar is either misconfigured, or the supply chain has been hacked to serve something else than it should?

**Comment by Naktibalda** [comment]
https://codeception.com/codecept.phar contains 4.0.0 release, the announcement will be published as soon as it is finished.

**Comment by ottok** [comment]
Indeed, that explains it:
```
$ curl -Ls https://codeception.com/codecept.phar -o - | strings | grep -F "const VERSION"
const VERSION = '4.4-dev';
    const VERSION = "4.0.0";
    const VERSION_NOT_SUPPORTED = 505;
```

I recommend you don't publish new versions before you have announced them.. anyway, this is now explained and I will close this issue once I have figured out how to change our code to be compatible with the 4.0 release, and document it here for others to see (as they will get the same error message).

**Comment by DavertMik** [comment]
@ottok sorry for this issue. We run unsynchronized in this release and yes, sorry for that. 

There was a post announcing that 4.0 will have lots of breaking changes and that it comes soon, so it was possible that if you download composer.phar from a bleeding edge, one day you might face them. You may use the latest 3.1 build which should work perfectly for you: 

https://codeception.com/releases/3.1.2/codecept.phar

As of 4.0 the build process for Phar is different as it is not bound to Codeception version anymore, we just regularly pick up module updates from different repos. So the process of packaging phar has changed and it might not be flawless as it was not battle-tested yet.

Again, sorry for this break.

**Comment by ottok** [comment]
In 3.1.2 we have:
```
require_once 'phar://codecept.phar/autoload.php';
require_once 'phar://codecept.phar/codecept';
```

In 4.0.0 there will be:
```
require_once 'phar://codecept.phar/vendor/codeception/codeception/app.php';
```

This seems to break the binary if it has not the appendix `.phar`:
```
$ curl -fsSL https://codeception.com/codecept.phar -O
$ chmod +x codecept.phar
$ ./codecept.phar --version
Codeception 4.0.0

$ mv codecept.phar codecept
$ ./codecept --version
PHP Warning:  require_once(phar://codecept.phar/vendor/codeception/codeception/app.php): failed to open stream: phar error: invalid url or non-existent phar "phar://codecept.phar/vendor/codeception/codeception/5
PHP Stack trace:
PHP   1. {main}() /data/home/vagrant/codecept:0
PHP Fatal error:  require_once(): Failed opening required 'phar://codecept.phar/vendor/codeception/codeception/app.php' (include_path='.:/usr/share/php') in /data/home/vagrant/codecept on line 5
PHP Stack trace:
PHP   1. {main}() /data/home/vagrant/codecept:0
```

The solution seems to be that the filename *must* be `codecept.phar` but if invoked via symlink then users can keep to use the old binary name:
```
$ ./codecept --version
=> failure
$ mv codecept codecept.phar
$ ln -s codecept.phar codecept
$ ./codecept --version
Codeception 4.0.0
```

**Comment by Naktibalda** [comment]
It wasn't a regression, but I fixed it anyway.
