### ISSUE TITLE
codecept run suites in sequence fails depending on order of suites

### ISSUE THREAD

**Issue by BobRay** [Codeception/Codeception#5805]
#### What are you trying to achieve?

run codecept integration,unit

#### What do you get instead?
Fatal error, undefined variable

### Details

These are successful:

codecept run integration
codecept run unit
codecept run unit,integration

This fails:

codecept run integration,unit

At the end of the integration test  (there is only one), it appears that tearDownAfterClass is run an extra time. I can see output from the first run -- all normal. Then it runs again and fails because an important variable is not set. 

I can fix this problem by wrapping the code in setupBeforeClass and tearDownAfterClass like so:

```
if( isset($variable) && $variable instanceof MyClass) {

}

```

That seems to indicate that the methods are being called an extra time with that variable no longer set. With the wrapping, all the actions in both methods are completed correctly and all tests pass regardless of which order the suites run in.

* Codeception version: latest
* PHP Version: latest
* Operating System: Windows 10
* Installation type: Composer

**Comment by Naktibalda** [comment]
If the issue was that `tearDownAfterClass` is executed twice, wouldn't it happen when only integration suite is executed?

Please provide a minimal reproduction scenario with one integration test and one unit test containing the smallest amount of code necessary to reproduce your issue.

**Comment by BobRay** [comment]
I see what's happening.  The integration test have the two afterClass functions, the unit test does not.  If the integration test is run first, those two functions hang around and are called before and after the unit tests even though the unit test does not contain those functions. In that setting, they crash. 

I added an echo statement. Here are the abbreviated results:

**λ codecept run integration,unit**                                                                   
Codeception PHP Testing Framework v2.3.9                                                          
Powered by PHPUnit 6.5.14 by Sebastian Bergmann and contributors.                                 
                                                                                                  
**Integration setUpBeforeClass running**
Integration Tests (10) ---------------------------------------------------------------------------

+ CustomSearchClassTest: Some feature (0.05s)                                                     
+ CustomSearchClassTest: Test_initialize (0.03s)                                                  
+ CustomSearchClassTest: Test_find chunks (0.33s)                                                 
+ CustomSearchClassTest: Test_find plugins (0.18s)                                                
+ CustomSearchClassTest: Test_find resources (0.19s)                                              
+ CustomSearchClassTest: Test_find snippets (0.19s)                                               
+ CustomSearchClassTest: Test_find templates (0.19s)                                              
+ CustomSearchClassTest: Test_find tvrs (0.30s)                                                   
+ CustomSearchClassTest: Test_find users (0.18s)                                                  
+ CustomSearchClassTest: Test_find user profiles (0.22s)                                          
**Integration tearDownAfterClass running[2019-12-27 17:07:26]** 
                                                                                                  
**Integration setUpBeforeClass running**
Unit Tests (9) -----------------------------------------------------------------------------------
+ ModxTest: Init (0.03s)                                                                          
+ ModxTest: Some feature (0.03s)                                                                  
+ ModxTest: Another feature (0.04s)                                                               
+ TestProcessorWithoutMODXTest: Init (0.01s)                                                      
+ TestProcessorWithoutMODXTest: Test_resource get query (0.01s)                                   
+ TestProcessorWithoutMODXTest: Test_get strpos all (0.00s)                                       
+ TestProcessorWithoutMODXTest: Test_get name field (0.00s)                                       
+ TestProcessorWithoutMODXTest: Test_get action (0.01s)                                           
+ TestProcessorWithoutMODXTest: Test_get content field (0.00s)                                    
**Integration tearDownAfterClass running**
------------------------------------------------------------

**Comment by Naktibalda** [comment]
There is an existing issue #5416

**Comment by BobRay** [comment]
> There is an existing issue #5416

That's it exactly. Feel free to mark this as a duplicate and/or close it.
