### ISSUE TITLE
Wrong step in in failures when error occurs. 

### ISSUE THREAD

**Issue by ruudboon** [Codeception/Codeception#5820]
#### What are you trying to achieve?
Display list of errors and failures

#### What do you get instead?
List of errors and failures failures containing wrong step information

Codeception 4.0.2
Related to https://github.com/Codeception/Codeception/pull/4654

**Comment by ruudboon** [comment]
<img width="1074" alt="Screenshot 2020-01-16 at 11 21 56" src="https://user-images.githubusercontent.com/7444246/72516743-7931c500-3852-11ea-84af-bc27abca0b41.png">

**Comment by Naktibalda** [comment]
@ruudboon What's the state of this issue?

**Comment by ruudboon** [comment]
@Naktibalda I think this is still occurring. Not sure when I have time to write tests for this.
