### ISSUE TITLE
codeception + symfony - New services cannot be grabbed

### ISSUE THREAD

**Issue by elzozo13** [Codeception/Codeception#5828]
I have the following setup:

Symfony 5 project, with codeception 4.

I am trying to create a test for a newly created service. The problem is that I receive the error below when I try to test it.

    Test  tests/integration/Shop/NewServiceCest.php:testSomething
    Step  Grab service "App\Service\NewService"
    Fail  Service App\Service\NewService is not available in container

The service code is below (is basically empty):

    <?php
    
    namespace App\Service;
    
    class NewService
    {
    
        public function __construct()
        {
    
        }
    
    }

The test code is below (again, basically empty):

    <?php
    
    namespace App\Tests\Integration\New;
    
    use App\Exception\NewException;
    use App\Service\NewService;
    use App\Tests\IntegrationTester;
    
    class NewServiceCest {
    
        private NewService $newService;
    
        public function _before(IntegrationTester $i) {
            $this->newService = $i->grabService(NewService::class);
        }
    
        public function testSomething(IntegrationTester $i) {
            // $i->expectThrowable(NewException::class, $this->newService->doStuff('invalidArgument'));
        }
    }

Integration tests yml:

    actor: IntegrationTester
    modules:
        enabled:
            - Symfony:
                  app_path: 'src'
                  environment: 'test'
            - Doctrine2:
                  depends: Symfony
                  cleanup: true
                  dump: 'tests/_data/integration.sql'
                  populate: true
                  reconnect: true
            - \App\Tests\Helper\Integration
            - Asserts

I have tried to clear cache, recreate it etc. everything I could think of from cli, including (current path is project dir):

    $./bin/console c:c
    $./bin/console c:c --env=test
    $rm -rf var (this should do nothing but still tried it)
    $rm -rf tests/_support/_generated
    $./bin/console cache:warmup --env=test
    $./vendor/bin/codecept build

When I ran the test, same issue.

What did make it work, was to inject the service somewhere (for example in a controller), execute the controller, then use ./vendor/bin/codecept build. After I did those steps the test worked as expected. The obvious problem with this is that I am trying to create a pipeline for deploy where I raise a test environment (clean, on the fly before deploying to servers), run tests, and ensure everything is fine. Injecting all services somewhere just to be able to build is not an option (but I am opened to any cli options, including running most commands).

Even more strange is that after I did this, now the test works as expected even after I clean caches (var and _generated). Is like it would save something in a different place that I can't seem to find (can't find any relevant configs regarding this and google and bing fail me).

So... why is this happening, and how can I reliably make it work?

**Comment by Naktibalda** [comment]
I am not an expert in Symfony, but I think that your services could be private: https://symfony.com/doc/current/service_container.html#public-versus-private-services

> From Symfony 4.0, every service defined is private by default.
> 
> What does this mean? When a service is public, you can access it directly from the container object, which can also be injected thanks to autowiring. This is mostly useful when you want to fetch services lazily:

> As a best practice, you should only create private services, which will happen automatically. And also, you should not use the $container->get() method to fetch public services.
> 
> But, if you do need to make a service public, override the public setting:
```yml
# config/services.yaml
services:
    # ... same code as before

    # explicitly configure the service
    Acme\PublicService:
        public: true
```

**Comment by monotonesol** [comment]
Probably you have some additional configuration for the test env in your Symfony app, by default https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing it should be accessible

**Comment by Naktibalda** [comment]
module-symfony uses some special test container, if it is available: https://github.com/Codeception/module-symfony/commit/1d4cdae7f75cd5ad1a9db938602746af4786b7ae

**Comment by elzozo13** [comment]
> 
> 
> I am not an expert in Symfony, but I think that your services could be private: https://symfony.com/doc/current/service_container.html#public-versus-private-services
> 
> > From Symfony 4.0, every service defined is private by default.
> > What does this mean? When a service is public, you can access it directly from the container object, which can also be injected thanks to autowiring. This is mostly useful when you want to fetch services lazily:
> 
> > As a best practice, you should only create private services, which will happen automatically. And also, you should not use the $container->get() method to fetch public services.
> > But, if you do need to make a service public, override the public setting:
> 
> ```yaml
> # config/services.yaml
> services:
>     # ... same code as before
> 
>     # explicitly configure the service
>     Acme\PublicService:
>         public: true
> ```

Hello, sorry for delayed answer. Services are not private (if they were private nothing would've fixed it except making them public). The problem seems to be the fact that if the service is not used anywhere (as is the case with first case in ttd methodology) it is not added at all in the container. I worked around the issue by just injecting the service in a dummy command but is... dirty.

**Comment by ThomasLandauer** [comment]
* This also happens in Symfony 4
* See https://stackoverflow.com/a/63131476/1668200 for a solution
* I just added a hint to Codeception's error message: https://github.com/Codeception/module-symfony/pull/20

As a "final" solution: Would it be possible that Codeception sets every service to `public`? Or just injects *everything* in the test container?

**Comment by TavoNiievez** [comment]
more information about this.

This bug related to 'all services as public' [was described](https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing) when Symfony 4.1 was released.
In my applications, I was not able to replicate it since -at some point- I added a `services_test.yaml` file just for the `test` environment which explicitly makes the services public by default:
```yaml
# config/services_test.yaml

services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Intangible\Service\MyService: '@App\Intangible\Service\MyService'

```

In the same way, the Symfony documentation [suggests](https://symfony.com/doc/current/testing.html#accessing-the-container) creating this file and making public the services that are required.
What I'm trying to say is that this 'public services' behavior (or aliases, if that's the case) should be explicitly added by the user...

I agree to add a more descriptive message, like the one suggested by @ThomasLandauer .

**Comment by ThomasLandauer** [comment]
@TavoNiievez I agree. Telling people what do to is enough - probably better than messing with their config ;-)

I updated it to mention `_test` explicitly: https://github.com/Codeception/module-symfony/pull/20/commits/38d59328a70e4210149fcfc5ad0be10f6d46e8a9

So once this gets merged, this issue can be closed.
