### ISSUE TITLE
Selenium Browser Logs are no longer available in Codeception 4 report

### ISSUE THREAD

**Issue by wonderas** [Codeception/Codeception#5836]
Selenium browser Logs are no longer available in Codeception 4 report

In latest Codeception 3.1.2 version and all earlier versions, Selenium Browser Logs were displaying in the console. This is very important information when debugging failures.

Since Codeception 4 was released, Selenium Browser Logs no longer available in console. 

![Console log](https://user-images.githubusercontent.com/6833517/73742295-ffe80c80-4743-11ea-9cf1-c8a2b3a2d75e.png)

**Comment by Naktibalda** [comment]
Try setting `debug_log_entries: 15` parameter in WebDriver configuration
or change version constraint of `codeception/module-webdriver` to `dev-display-selenium-logs` and test the patch.

**Comment by wonderas** [comment]
debug_log_entries: 15 did the trick (I assume the number can by any to restrict maximum log entries)

**Comment by Naktibalda** [comment]
Problem solved, there was the change and documentation was update to indicate that no logs are displayed by default.
(Documentation on site will be updated later)
