### ISSUE TITLE
attachFile function in codeception stop working after LibZip update.

### ISSUE THREAD

**Issue by resworld** [Codeception/Codeception#5838]
#### What are you trying to achieve?
Attach a single file from _data dir into a field. File is accessable into the system.

#### What do you get instead?
It doesn't attach, but not even error is shown. Next test for Success message from "Successful uploaded file" is missing in next step.
In screenshot we've seen that field is empty and doesn't have filename included.

Console output:
```bash
   I attach file "//input[@name="sFile"]","File_to_Upload.csv"
   I click "//button[contains(@class,"itcss-button primary large")]"
   I wait for text "Successful uploaded file"
  [Selenium browser Logs]  EMPTY
  [Selenium driver Logs]  EMPTY
  Screenshot and page source were saved into '/application/./tests/Codeception/_output/' dir
 ERROR
```

### Details

What we have noticed so far:
Everything in code side is correct as it was working before couple of days, so we have found that libzip5 is updated (libzip5-1.6.1-1.el7.remi.x86_64) although php-zip extension:
```bash
Zip version => 1.17.1
Libzip headers version => 1.6.0
Libzip library version => 1.6.1
```
When we downgrade it with 1.5.* version it works as before, but we like to have up-to-date extension installed on the system:

```bash
   I attach file "//input[@name="sFile"]","File_to_Upload.csv"
   I click "//button[contains(@class,"itcss-button primary large")]"
   I wait for text "Successful uploaded file"
   I click "//button[contains(@class,"itcss-button primary large")]"
   I wait for text "Your page was successfully configured.",5
   I click "//div[@id="breadcrumb"]/a[contains (text(),"Done")]"
 PASSED
```

* Codeception version: Tested on 2.5.6 and 3.1.2
* PHP Version: 7.2.27
* Operating System: CentOS 7
* Installation type: Composer

**Comment by HotPepp3r** [comment]
+1 same issue

**Comment by Naktibalda** [comment]
Codeception attachFile doesn't do much - [it types filename into file field](https://github.com/Codeception/module-webdriver/blob/1.0.2/src/Codeception/Module/WebDriver.php#L1700-L1719).

More likely this is an issue of Selenium or specific browser driver.

**Comment by resworld** [comment]
We have used ChromeDriver, but do you think there may be a relation between libzip and webdriver ? As I mention it works back again when we downgrade the library to 1.5.* version.
Here is the chromedriver version included:
ChromeDriver 2.34.522913 (36222509aa6e819815938cbf2709b4849735537c)

**Comment by Naktibalda** [comment]
I looked for relevant issues and discovered that all Selenium clients zip files before uploading them.
The relevant code is in php-webdriver library: https://github.com/php-webdriver/php-webdriver/blob/e5299c385a61bee12bdbb6c17dce46381d8e3016/lib/Remote/RemoteWebElement.php#L486-L513

It uses ZipArchive class, but there is no new issues raised at https://bugs.php.net/search.php?cmd=display&search_for=ZipArchive&order_by=ts1&direction=ASC&limit=30&status=Open&reorder_by=ts1

A good start of investigation would be to test if ZipArchive creates non-empty zip file in your system,
also try to upgrade `php-zip` package.

**Comment by resworld** [comment]
@Naktibalda thanks, truly problem was in file you mention : RemoteWebElement.php and with new zip module we have to use it differently. I've changed line 493 with:
```bash
        $temp_zip = sys_get_temp_dir().'/WebDriverZip'.uniqid();
```
Now it works fine for us.

**Comment by Naktibalda** [comment]
It doesn't look like correct solution.
What's wrong with the file created by tempnam?

**Comment by rusakov92** [comment]
Hello, @Naktibalda I've had a look at the method and here is what I found if you look at the [code](https://github.com/php-webdriver/php-webdriver/blob/e5299c385a61bee12bdbb6c17dce46381d8e3016/lib/Remote/RemoteWebElement.php#L486-L513) you can see that the second parameter when you open the file path with ZipArchive you can specify to create it if it does not exist with option `ZipArchive::CREATE`.

```php
        // Create a temporary file in the system temp directory.
        $temp_zip = tempnam(sys_get_temp_dir(), 'WebDriverZip');
        $zip = new ZipArchive();
        if (($errorCode = $zip->open($temp_zip, ZipArchive::CREATE)) !== true) {
            throw new WebDriverException(sprintf('Error creating zip archive: %s', $errorCode));
        }
```

So this code `(new ZipArchive())->open('/tmp/file/path', ZipArchive::CREATE)` is actually correct and can be used as @resworld suggested. [Example 2](https://www.php.net/manual/en/ziparchive.open.php) from PHP documentation.

Looks like in the new versions of the ZIP module it does additional checks if we pass a file path that actually exists because in our case method `$zip->open()` returned error code 19 or `ZipArchive::ER_NOZIP`, and I think it is because the empty file does not include all correct headers specifying that this file is an archive file.

So if we alter the code like this it should not introduce any BC:
```php
        // Create a temporary file in the system temp directory.
        $temp_zip = sys_get_temp_dir().DIRECTORY_SEPARATOR.uniqid('WebDriverZip');
        $zip = new ZipArchive();
        if (($errorCode = $zip->open($temp_zip, ZipArchive::CREATE)) !== true) {
            throw new WebDriverException(sprintf('Error creating zip archive: %s', $errorCode));
        }
```

**Comment by Naktibalda** [comment]
Please make pull request to https://github.com/php-webdriver/php-webdriver/

**Comment by akocherhan** [comment]
Please use `ZipArchive::CREATE | ZipArchive::OVERWRITE` instead of the `ZipArchive::CREATE` - fixed a similar issue for me.

**Comment by Naktibalda** [comment]
This issue was fixed by https://github.com/php-webdriver/php-webdriver/pull/748 in php-webdriver 1.8.0

@akocherhan  If you want to make that change, please raise new pull request to php-webdriver repository.
