### ISSUE TITLE
Can you fix your garbage broken installation instructions?

### ISSUE THREAD

**Issue by ahnbizcad** [Codeception/Codeception#5840]
#### What are you trying to achieve?
installing this

#### What do you get instead?
not installing this

> Provide console output if related. Use `-vvv` mode for more details.
how about you write documentation that works instead?

```bash
# paste output here
composer is broken af
```
> Provide test source code if related
no, you.

```php
// paste test
```
### Details

* Codeception version:
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by ahnbizcad** [comment]
i'm not your debugger.

fix your code.

**Comment by Naktibalda** [comment]
This is the worst bug report ever:
What instructions?
What have you done?
What output have you got?

**Comment by ahnbizcad** [comment]
starting from the homepage.

https://codeception.com/quickstart

`composer require "codeception/codeception" --dev`

that in no way leads to the next step

`php vendor/bin/codecept bootstrap`


Then additional installation is interspersed throughout the dosc.

`codecept init upgrade4`

This adds more stuff to composer.json file, leading one to think they need to run composer install. but in reality, things already got installed by simply running the command.
So the additional side effective of adding things to the composer.json file is very misleading.

If I follow through and have composer install the additional packages added to the composer json file, it actually breaks the installation.

Doing an actual installation plus "staging" things to be installed by composer is very misleading.

Running various CLI installation commands shows no indication of whether it did anything, or if it did, what was changed, if doing so i idempotent, etc.

From a fresh slate, you actually can't install via composer.
nor phar. The only way i got it to work was via downloading the curl binary directly...

This leads to development restrictions because now the entry point in running this software is obscured and not debuggable.
