### ISSUE TITLE
pressKey returns Array to string conversion

### ISSUE THREAD

**Issue by michalper** [Codeception/Codeception#5848]
#### What are you trying to achieve?
$I->pressKey('.select2-input', 'pro');

#### What do you get instead?
Array to string conversion

> Provide console output if related. Use `-vvv` mode for more details.

```bash
michalper@ST000156 sportsadminv3 % php vendor/bin/codecept run acceptance -g failed1 -vvv
Codeception PHP Testing Framework v4.1.0
Powered by PHPUnit 9.0.1 by Sebastian Bergmann and contributors.
Running with seed: 

[Groups] failed1 

  [Connecting To Db] {"config":{"populate":false,"cleanup":false,"reconnect":false,"waitlock":0,"dump":null,"populator":null,"dsn":"mysql:host=localhost;dbname=head","user":"root","password":"root"},"options":[]}
  [Db] Connected to default head

Acceptance Tests (1) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: WebDriver, \Helper\Acceptance, Db, DbHelper, Laravel5
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  [RunProcess] Starting exec docker run --net=host -e TZ="Europe/Warsaw" selenium/standalone-chrome
AddParticipantToStageCest: Add participant to stage
Signature: Tests\Acceptance\Season\AddParticipantToStageCest:addParticipantToStage
Test: tests/acceptance/competition/AddParticipantToStageCest.php:addParticipantToStage
Scenario --
  [Database] Transaction started
 I login as admin 
   I am on page "/auth/logout"
  [GET] http://dev.statscore.com/auth/logout
   I wait for element visible "#loginform"
   I fill field "email","*********"
   I fill field "password","*********"
   I click "#login"
   I wait for element "#content-header > h1",10
 I am on page "/sportsadmin/stages/76523/participants/create"
  [GET] http://dev.statscore.com/sportsadmin/stages/76523/participants/create
 I click ".select2-container"
 I wait for element visible ".select2-input",20
 I press key ".select2-input","pro"
 I make screenshot "AddParticipantToStageCest_2020-02-13T13:06:23+01:00"
  [Screenshot Saved] file:///Users/michalper/web/sportsadminv3/tests/_output/debug/AddParticipantToStageCest_2020-02-13T13:06:23+01:00.png
  Screenshot and page source were saved into '/Users/michalper/web/sportsadminv3/tests/_output/' dir
 ERROR 

  [Database] Transaction cancelled; all changes reverted.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 14.89 seconds, Memory: 30.00 MB

There was 1 error:

---------
1) AddParticipantToStageCest: Add participant to stage
 Test  tests/acceptance/competition/AddParticipantToStageCest.php:addParticipantToStage
                                               
  [ErrorException] Array to string conversion  
                                               

Scenario Steps:

 11. $I->makeScreenshot("AddParticipantToStageCest_2020-02-13T13:06:23+01:00") at tests/_support/Helper/AcceptanceCest.php:11
 10. $I->pressKey(".select2-input","pro") at tests/acceptance/competition/AddParticipantToStageCest.php:31
 9. $I->waitForElementVisible(".select2-input",20) at tests/acceptance/competition/AddParticipantToStageCest.php:30
 8. $I->click(".select2-container") at tests/acceptance/competition/AddParticipantToStageCest.php:29
 7. $I->amOnPage("/sportsadmin/stages/76523/participants/create") at tests/acceptance/competition/AddParticipantToStageCest.php:27
 6. $I->waitForElement("#content-header > h1",10) at tests/_support/AcceptanceTester.php:83

/Users/michalper/web/sportsadminv3/vendor/sentry/sentry/src/ErrorHandler.php:379
/Users/michalper/web/sportsadminv3/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebElement.php:333
/Users/michalper/web/sportsadminv3/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:2902
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Step.php:266
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Scenario.php:76
/Users/michalper/web/sportsadminv3/tests/_support/_generated/AcceptanceTesterActions.php:2826
/Users/michalper/web/sportsadminv3/tests/acceptance/competition/AddParticipantToStageCest.php:31
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Lib/Di.php:127
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Test/Cest.php:138
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Test/Cest.php:150
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Test/Cest.php:82
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Test/Test.php:88
/Users/michalper/web/sportsadminv3/vendor/phpunit/phpunit/src/Framework/TestSuite.php:597
/Users/michalper/web/sportsadminv3/vendor/codeception/phpunit-wrapper/src/Runner.php:117
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/SuiteManager.php:161
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Codecept.php:196
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Codecept.php:163
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Command/Run.php:503
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Command/Run.php:397
/Users/michalper/web/sportsadminv3/vendor/symfony/console/Command/Command.php:255
/Users/michalper/web/sportsadminv3/vendor/symfony/console/Application.php:1012
/Users/michalper/web/sportsadminv3/vendor/symfony/console/Application.php:272
/Users/michalper/web/sportsadminv3/vendor/symfony/console/Application.php:148
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/src/Codeception/Application.php:117
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/app.php:46
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/app.php:47
/Users/michalper/web/sportsadminv3/vendor/codeception/codeception/codecept:7

Artifacts:

Png: /Users/michalper/web/sportsadminv3/tests/_output/Tests.Acceptance.Season.AddParticipantToStageCest.addParticipantToStage.fail.png
Html: /Users/michalper/web/sportsadminv3/tests/_output/Tests.Acceptance.Season.AddParticipantToStageCest.addParticipantToStage.fail.html

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
  [Db] Disconnected from default
```
> Provide test source code if related

```php
<?php

namespace Tests\Acceptance\Season;

use AcceptanceTester;
use Exception;
use Facebook\WebDriver\WebDriverKeys;
use Helper\Acceptance;
use Helper\AcceptanceCest;

/**
 * Class AddParticipantToStageCest
 * @package Tests\Acceptance\Season
 */
class AddParticipantToStageCest extends AcceptanceCest
{
    private const URL = '/sportsadmin/stages/76523/participants/create';

    /**
     * @param AcceptanceTester $I
     * @throws Exception
     */
    public function addParticipantToStage(AcceptanceTester $I): void
    {
        $I->loginAsAdmin()
            ->amOnPage(static::URL);

        $I->click('.select2-container');
        $I->waitForElementVisible('.select2-input', Acceptance::DEFAULT_TIMEOUT);
        $I->pressKey('.select2-input', 'pro');
        $I->waitForElementVisible('.select2-result-label', Acceptance::DEFAULT_TIMEOUT);
        $I->pressKey('.select2-input', WebDriverKeys::ENTER);
        $I->submitForm('.form-horizontal', []);
        $I->waitForElementVisible('.alert-success', Acceptance::DEFAULT_TIMEOUT);

        $I->see('Participant has been added to stage', '.alert-success');
    }
}
```
### Details

* Codeception version: 4.1.0
* PHP Version: 7.4.2
* Operating System: Mac OS
* Installation type: Composer
* List of installed packages (`composer show`)
aws/aws-sdk-php                     3.133.13           AWS SDK for PHP - Use Amazon Web Services in your PHP project
barryvdh/laravel-debugbar           v3.2.8             PHP Debugbar integration for Laravel
barryvdh/laravel-ide-helper         v2.6.6             Laravel IDE Helper, generates correct PHPDocs for all Facade classes, to improve auto-completion.
barryvdh/reflection-docblock        v2.0.6            
beberlei/assert                     v3.2.7             Thin assertion library for input validation in business models.
behat/gherkin                       v4.6.0             Gherkin DSL parser for PHP 5.3
cakephp/chronos                     1.3.0              A simple API extension for DateTime.
clue/stream-filter                  v1.4.1             A simple and modern approach to stream filtering in PHP
codeception/codeception             4.1.0              BDD-style testing framework
codeception/lib-asserts             1.11.0             Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser        1.3.0              Parent library for all Codeception framework modules and PhpBrowser
codeception/module-db               1.0.1              WebDriver module for Codeception
codeception/module-laravel5         1.0.0              Codeception module for Laravel 5 framework
codeception/module-webdriver        1.0.2              WebDriver module for Codeception
codeception/phpunit-wrapper         9.0.0              PHPUnit classes used by Codeception
codeception/stub                    3.6.1              Flexible Stub wrapper for PHPUnit's Mock Builder
composer/ca-bundle                  1.2.6              Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer                   1.9.3              Composer helps you declare, manage and install dependencies of PHP projects. It ensures you have the right stack everywhere.
composer/semver                     1.5.1              Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses              1.5.2              SPDX licenses list and validation library.
composer/xdebug-handler             1.4.0              Restarts a process without Xdebug.
davejamesmiller/laravel-breadcrumbs 5.3.2              A simple Laravel-style way to create breadcrumbs.
docraptor/docraptor                 1.3.0              A wrapper for the DocRaptor HTML to PDF/XLS service.
doctrine/cache                      1.10.0             PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and ...
doctrine/dbal                       v2.10.1            Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/event-manager              1.1.0              The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                  1.3.1              Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.3.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      1.2.0              PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression       v2.3.0             CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator             2.1.16             A library for validating emails against several RFCs
facade/ignition-contracts           1.0.0              Solution contracts for Ignition
filp/whoops                         2.7.1              php error handling for cool kids
guzzlehttp/guzzle                   6.5.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                 v1.3.1             Guzzle promises library
guzzlehttp/psr7                     1.6.1              PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php               v2.0.0             This is the PHP port of Hamcrest Matchers
jean85/pretty-package-versions      1.2                A wrapper for ocramius/package-versions to get pretty versions strings
justinrainbow/json-schema           5.2.9              A library to validate a json schema.
laracasts/presenter                 0.2.2              Simple view presenters
laravel/framework                   v6.15.1            The Laravel Framework.
laravel/horizon                     v3.6.1             Dashboard and code-driven configuration for Laravel queues.
laravelcollective/html              v6.0.3             HTML and Form Builders for the Laravel Framework
league/commonmark                   1.3.0              Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and Github-Flavored Markdown (GFM)
league/flysystem                    1.0.64             Filesystem abstraction: Many filesystems, one API.
markbaker/complex                   1.4.7              PHP Class for working with complex numbers
markbaker/matrix                    1.2.0              PHP Class for working with matrices
maximebf/debugbar                   v1.15.1            Debug bar in the browser for php application
mockery/mockery                     1.3.1              Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                     2.0.2              Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php              2.5.0              Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                   1.9.5              Create deep copies (clones) of your objects
nesbot/carbon                       2.30.0             An API extension for DateTime that supports 281 different languages.
ocramius/package-versions           1.5.1              Composer plugin that provides efficient querying for installed package versions (no runtime IO)
opis/closure                        3.5.1              A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
paragonie/random_compat             v9.99.99           PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                    1.0.3              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                     2.0.1              Library for handling version information and constraints
php-amqplib/php-amqplib             v2.11.0            Formerly videlalvaro/php-amqplib.  This library is a pure PHP implementation of the AMQP protocol. It's been tested against RabbitMQ.
php-http/client-common              2.1.0              Common HTTP Client implementations and tools for HTTPlug
php-http/curl-client                2.0.0              PSR-18 and HTTPlug Async client with cURL
php-http/discovery                  1.7.4              Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                    2.1.0              HTTPlug, the HTTP client abstraction for PHP
php-http/message                    1.8.0              HTTP Message related tools
php-http/message-factory            v1.0.2             Factory interfaces for PSR-7 HTTP Message
php-http/promise                    v1.0.0             Promise used for asynchronous HTTP requests
php-webdriver/webdriver             1.8.0              A PHP client for Selenium WebDriver. Previously facebook/webdriver.
phpdocumentor/reflection-common     2.0.0              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   5.0.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a Doc...
phpdocumentor/type-resolver         1.0.1              A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoffice/phpspreadsheet            1.10.1             PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpoption/phpoption                 1.7.2              Option Type for PHP
phpseclib/phpseclib                 2.0.23             PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpspec/prophecy                    v1.10.2            Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           8.0.0              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           3.0.0              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                 3.0.0              Invoke callables with a timeout
phpunit/php-text-template           2.0.0              Simple template engine.
phpunit/php-timer                   3.0.0              Utility class for timing
phpunit/php-token-stream            4.0.0              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     9.0.1              The PHP Unit Testing framework.
predis/predis                       v1.1.1             Flexible and feature-complete Redis client for PHP and HHVM
psr/container                       1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-client                     1.0.0              Common interface for HTTP clients
psr/http-factory                    1.0.1              Common interfaces for PSR-7 HTTP message factories
psr/http-message                    1.0.1              Common interface for HTTP messages
psr/log                             1.1.2              Common interface for logging libraries
psr/simple-cache                    1.0.1              Common interfaces for simple caching
ralouphie/getallheaders             3.0.3              A polyfill for getallheaders.
ramsey/uuid                         3.9.2              Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
roave/security-advisories           dev-master 0365bf2 Prevents installation of composer packages with known security vulnerabilities: no API, simply require it
sebastian/code-unit-reverse-lookup  2.0.0              Looks up which function or method a line of code belongs to
sebastian/comparator                4.0.0              Provides the functionality to compare PHP values for equality
sebastian/diff                      4.0.0              Diff implementation
sebastian/environment               5.0.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  4.0.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state              4.0.0              Snapshotting of global state
sebastian/object-enumerator         4.0.0              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector          2.0.0              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context         4.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations       3.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/type                      2.0.0              Collection of value objects that represent the types of the PHP type system
sebastian/version                   3.0.0              Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                       1.7.2              JSON Linter
seld/phar-utils                     1.0.2              PHAR file format utilities, for when PHP phars you up
sentry/sentry                       2.3.1              A PHP SDK for Sentry (http://sentry.io)
statscore/apiclient                 1.3                STATSCORE API Client package
statscore/pushmessage               2.4.0              Creating and validating Push Messages
studio/laravel-totem                v6.0.2             A Laravel package to manage your cron jobs through a beautiful dashboard
swiftmailer/swiftmailer             v6.2.3             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                 v5.0.4             Symfony BrowserKit Component
symfony/console                     v4.4.4             Symfony Console Component
symfony/css-selector                v3.1.10            Symfony CssSelector Component
symfony/debug                       v4.4.4             Symfony Debug Component
symfony/dom-crawler                 v5.0.4             Symfony DomCrawler Component
symfony/error-handler               v4.4.4             Symfony ErrorHandler Component
symfony/event-dispatcher            v4.4.4             Symfony EventDispatcher Component
symfony/event-dispatcher-contracts  v1.1.7             Generic abstractions related to dispatching event
symfony/filesystem                  v4.4.4             Symfony Filesystem Component
symfony/finder                      v4.4.4             Symfony Finder Component
symfony/http-foundation             v4.4.4             Symfony HttpFoundation Component
symfony/http-kernel                 v4.4.4             Symfony HttpKernel Component
symfony/inflector                   v5.0.4             Symfony Inflector Component
symfony/mime                        v5.0.4             A library to manipulate MIME messages
symfony/options-resolver            v4.4.4             Symfony OptionsResolver Component
symfony/polyfill-ctype              v1.14.0            Symfony polyfill for ctype functions
symfony/polyfill-iconv              v1.14.0            Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn           v1.14.0            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring           v1.14.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.14.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73              v1.14.0            Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-uuid               v1.14.0            Symfony polyfill for uuid functions
symfony/process                     v4.4.4             Symfony Process Component
symfony/property-access             v5.0.4             Symfony PropertyAccess Component
symfony/property-info               v5.0.4             Symfony Property Info Component
symfony/routing                     v4.4.4             Symfony Routing Component
symfony/serializer                  v5.0.4             Symfony Serializer Component
symfony/service-contracts           v2.0.1             Generic abstractions related to writing services
symfony/translation                 v4.4.4             Symfony Translation Component
symfony/translation-contracts       v2.0.1             Generic abstractions related to translation
symfony/var-dumper                  v4.4.4             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                        v5.0.4             Symfony Yaml Component
theseer/tokenizer                   1.1.3              A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles   2.2.2              CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when...
vlucas/phpdotenv                    v3.6.0             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
watson/rememberable                 3.2.1              Query caching for Laravel 5
webmozart/assert                    1.6.0              Assertions to validate method input/output with nice error messages.

* Suite configuration:

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
  enabled:
    - WebDriver:
        url: 'http://dev.statscore.com/'
        window_size: false
        log_js_errors: true
        port: 4444
        browser: chrome
        capabilities:
          chromeOptions:
            args: ["--window-size=1600,900", "--headless"]
    - \Helper\Acceptance
    - Db
    - DbHelper
    - Laravel5:
        part: ORM
        environment_file: .env
  config:
    Db:
      dsn: 'mysql:host=localhost;dbname=head'
      user: 'root'
      password: 'root'
      populate: false
      cleanup: false
extensions:
  enabled:
    - Codeception\Extension\RunProcess:
        0: exec docker run --net=host -e TZ="Europe/Warsaw" selenium/standalone-chrome
        sleep: 7 # wait 7 second for processes to boot
```

**Comment by Naktibalda** [comment]
It is a known issue of php-webdriver https://github.com/php-webdriver/php-webdriver/issues/758
It is already fixed and will be released as php-webdriver/webdriver 1.8.1

**Comment by michalper** [comment]
Ok, thanks for your information. 
Waiting for 1.8.1.

**Comment by OndraM** [comment]
Php-webdriver 1.8.1 which includes the fix has just been released :rocket:
