### ISSUE TITLE
Missing 'tests' directory in archive files

### ISSUE THREAD

**Issue by duongdominhchau** [Codeception/Codeception#5850]
When I download the source code using the button **Download ZIP** button or from **Assets** of latest release, the extracted directory doesn't have the directory `tests`. With that directory missing `composer install` will throw out an error. Using `git clone` doesn't have this problem.

**Comment by Naktibalda** [comment]
That's intentional, https://github.com/Codeception/Codeception/blob/4.0/.gitattributes#L37-L46

**Comment by duongdominhchau** [comment]
Can I ask how to build/use the tarball from release page? Because without `tests` directory I can't run `codecept` directly or `composer install`. I'm sorry if this is a dumb question, because I am not familiar with the ecosystem of PHP.

**Comment by Naktibalda** [comment]
Nobody uses these tarballs directly, install Codeception using `composer require --dev codeception/codeception`.

**Comment by duongdominhchau** [comment]
Thank you.
