### ISSUE TITLE
PS1 namespace standards broken by Tester classes extending Actor

### ISSUE THREAD

**Issue by Pi-George** [Codeception/Codeception#5853]
Example of a generic Tester file:

```
<?php

use Codeception\Actor;

/**
 * Manages generic internal endpoint integration test functions and header state
 */
class InternalEndpointTester extends Actor
{
    use _generated\InternalEndpointTesterActions;
}
```

If you try to give it a namespace then Cest's are unable to find the class:

```
Pi\Codeception\Api\SitesCest:validateAndNormaliseBaseUrlFailProtocolsTest
Class 'InternalEndpointTester' not found
```

I haven't dug into the code, but I presume this is because whatever DI is being used on the Cest functions doesn't consider that the needed class may not have a base namespace.

**Comment by Naktibalda** [comment]
Better later than never.

This issue had an obvious solution - you had to update your Cest files to use namespaced Tester class.

It is possible that Codeception will generated namespaced testers by default when #5727 is implemented.

**Comment by Naktibalda** [comment]
I just stumbled upon related issue that I raised myself 3 years ago: https://github.com/Codeception/Codeception/issues/4874

**Comment by Pi-George** [comment]
That is a rather obvious solution isn't it... hah, well thanks
