### ISSUE TITLE
SelectOption is not selecting the Options from the dropdown

### ISSUE THREAD

**Issue by barkave** [Codeception/Codeception#5859]
#### What are you trying to achieve?
I have the dropdown with label name as Data Asset
2.I have to select the values from the dropdown.
Below is the code 

I.selectOption("demo-simple-select1","hadoopdb")

I am getting the error Element is not found by text\xpath/css

Note :  I.click("demo-simple-select1") is working, that is drop down Opens ,

Below is the js code.
   <InputLabel id="demo-simple-select-label">Data Asset</InputLabel>
                                    <Select
                                        labelId="demo-simple-select-label"
                                        id="demo-simple-select1"
                                        name="dataAsset"
                                        value={dataSource}
                                        onChange={(e) => {
                                            setDataSource(e.target.value)
                                            props.getDataBases(e.target.value)
                                        }}
                               
#### What do you get instead?
I am getting element is not found by text\xpath/css

As i am new to testing codecept.it will be great if someone helps

**Comment by Naktibalda** [comment]
If this is an issue of CodeceptJs, please raise it at https://github.com/Codeception/CodeceptJS/issues
