### ISSUE TITLE
How about branch 4.1 ?

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#5861]
I can see tag 4.1.1 and 4.1.0
I can see branch  4.1.0 and 4.0
I can't see common branch for 4.1

This is in 4.0 now?

**Comment by Naktibalda** [comment]
Yes, 4.0 is still an active branch.

**Comment by Naktibalda** [comment]
4.1 is the default branch now.
4.0 branch was reset to match 4.0.3 release.
