### ISSUE TITLE
Ambiguous and missing step definitions

### ISSUE THREAD

**Issue by matthiasnoback** [Codeception/Codeception#5864]
I recently ran into a surprising issue with running Gherkin scenarios with Codeception. Codeception would not run my step definition and after some debugging I figured out that there was another step definition whose pattern matched the current step. When using Behat I would get an exception at that point saying that the step was ambiguous; Behat can't decide which step definition to run. Codeception however just runs the first step definition with a matching pattern (https://github.com/Codeception/Codeception/blob/4.0/src/Codeception/Test/Gherkin.php#L129). I think it would be very useful if it would also throw an exception in that situation. What are your thoughts? I'd be happy to provide a PR for it.

There's one downside: we would have to try all known step definitions to figure out how many of them match, e.g.

```php
$matches = [];
$foundMatchingStepDefinition = false;

foreach ($this->steps as $pattern => $context) {
    $matches = [];
    if (!preg_match($pattern, $stepText, $matches)) {
        continue;
    }
    if ($foundMatchingStepDefinition) {
        throw new AmbiguousStep('...'); // this one is new
    }
    $foundMatchingStepDefinition = true;
    array_shift($matches);
    if ($hasPyStringArg) {
        // get rid off last fake argument
        array_pop($matches);
    }
    if ($stepNode->hasArguments()) {
        $matches = array_merge($matches, $stepNode->getArguments());
    }
}
if (!$foundMatchingStepDefinition) {
    throw new MissingStepDefinition('...'); // this one too
}
call_user_func_array($context, $matches); // execute the step
```

Another issue that we can solve here is for missing step definitions to fail hard instead of showing "I" for "incomplete". I think it's more appropriate.

**Comment by Naktibalda** [comment]
You are welcome to raise a pull request.

It would be great if you could create tests for both cases in https://github.com/Codeception/Codeception/blob/4.0/tests/cli/GherkinCest.php

**Comment by matthiasnoback** [comment]
Okay, thanks!

**Comment by DavertMik** [comment]
Yeah, I agree. 
But the exception might break compatibility for current runs so maybe a better way would be to provide some config parameter. 

But for sure Codeception should at least notify (very loudly) about same definitions.
Thanks, @matthiasnoback
