### ISSUE TITLE
facebook/webdriver is abandoned

### ISSUE THREAD

**Issue by akrz** [Codeception/Codeception#5865]
![image](https://user-images.githubusercontent.com/1325627/75892036-72b1d980-5e0f-11ea-9f0b-fa7620132df4.png)

https://github.com/php-webdriver/php-webdriver is suggested as replacement

**Comment by Naktibalda** [comment]
Upgrade to Codeception 4 and codeception/module-webdriver 1.0.1 or newer: https://github.com/Codeception/module-webdriver/commit/51f95403af8a5d29f5e5a163491f8000b012c88e
