### ISSUE TITLE
Multiple applications autoloading problem

### ISSUE THREAD

**Issue by benr77** [Codeception/Codeception#5872]
#### What are you trying to achieve?

Use the multiple apps setup as described on this page
https://codeception.com/docs/08-Customization#One-Runner-for-Multiple-Applications

I want to run all tests across all applications.

I have the following directory structure

```
├── apps
│   ├── app1
│          └── codeception.yml
│   └── app2
│          └── codeception.yml
├── packages
├── tests
├── vendor
├── codeception.yml
├── composer.json
```

The root `codeception.yml` contains the following

```
include:
    - apps/app1
    - apps/app2

paths:
    output: tests/_output
    log: tests/_output
```

#### What do you get instead?

When I run tests I get lots of class not found errors. This is because the `composer.json` in the root only includes development and testing tools such as Codeception, PhpStan, ECS etc.

Codeception is using the autoloading from the root of the repository, and not using the autoloading from `app1` and `app2` etc

The only way I can get it to work is add the packages from each individual application in to the root `composer.json` so that all dependencies are found using the root level autoloading. This doesn't feel good though.

Is it possible to get Codeception to use the autoloading from `app1` when running test suites from `app1` etc?

Any advice on how to run this set up would be appreciated. 

### Details

* Codeception version: 4.1.1
* PHP Version: 7.4
* Operating System: Linux
* Installation type: Composer

**Comment by Naktibalda** [comment]
You could find this Composer plugin useful: https://github.com/wikimedia/composer-merge-plugin

**Comment by benr77** [comment]
Thank you for that - looks interesting. I'm already using something similar I think
https://github.com/symplify/monorepo-builder#1-merge-local-composerjson-to-the-root-one

By suggesting this tool are you implying that I need to have all the dependencies installed in the root composer.json in order for Codeception to work correctly?

**Comment by Naktibalda** [comment]
> By suggesting this tool are you implying that I need to have all the dependencies installed in the root composer.json in order for Codeception to work correctly?

Yes, that's right.

**Comment by benr77** [comment]
Ok thanks for your help. I have decided to not attempt to combine the Codeception tests of the two apps. 

Merging the composer dependencies of two totally separate apps doesn't feel right at all - I could easily end up depending on a package that isn't even in the composer.json of the application etc. 

It also means I have to use the exact same package versions between the two apps which might not suit requirements etc.
