### ISSUE TITLE
Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by voku** [Codeception/Codeception#5875]
#### What are you trying to achieve?

Running ```codecept.phar build``` after upgrading from v3 ⇉ v4

#### What do you get instead?

```bash
Function ReflectionType::__toString() is deprecated File:phar:///home/foo/bar/Framework/thirdparty/codecept.phar/vendor/codeception/codeception/src/Codeception/Lib/Generator/Actions.php Line:226
```

### Details

* Codeception version: 4.1.2
* PHP Version: 7.4
* Operating System: Ubuntu 18.04
* Installation type: Phar

**Comment by Naktibalda** [comment]
Thanks for report, this issue was introduced by #5862
