### ISSUE TITLE
A void function must not return a value error since 4.1.2

### ISSUE THREAD

**Issue by Jamesking56** [Codeception/Codeception#5877]
Caused by #5862 

#### What are you trying to achieve?

Return types on generated actions for methods that return `void` should not use `return` since you cannot return a `void`:

```php
public function voidMethod(): void {
    $this->getScenario()->runStep(new \Codeception\Step\Action('voidMethod', func_get_args()));
}
```

#### What do you get instead?

```php
public function voidMethod(): void {
    return $this->getScenario()->runStep(new \Codeception\Step\Action('voidMethod', func_get_args()));
}
```

This causes PHP errors:

```
Fatal error:  A void function must not return a value
```
### Details

* Codeception version: 4.1.2
* PHP Version: 7.3.15
* Operating System: Ubuntu 18.04.3
* Installation type: Composer

**Comment by Jamesking56** [comment]
Upgrading my project to 4.1.3 still has this problem. This needs reopening.

**Comment by Venorcis** [comment]
> Upgrading my project to 4.1.3 still has this problem. This needs reopening.

Can confirm, still getting "A void function must not return a value in /var/www/html/tests/_support/_generated/ApiTesterActions.php line 5361"

**Comment by Naktibalda** [comment]
Have you ran `codecept build` after upgrade?

**Comment by Jamesking56** [comment]
Yeah @Naktibalda. `codecept build` always runs successfully but running tests crashes with the fatal error in `4.1.3` but doesn't crash after applying patch from #5880
