### ISSUE TITLE
"codeception.com/builds" website causes confusion with respect to 4.x versions

### ISSUE THREAD

**Issue by reinholdfuereder** [Codeception/Codeception#5879]
https://codeception.com/builds shows "only" 4.0 section and latest version/release "4.0.20200314 for PHP 7.2+", although I guess this is the latest release 4.1.2 and thus should be named "4.1.2.20200314 for PHP 7.2+" or so?

I think that these 3 pages should be consistent with respect to versions:
* https://codeception.com/builds
* https://codeception.com/changelog
* https://github.com/Codeception/Codeception/releases

**Comment by Naktibalda** [comment]
I renamed recent modules to 4.1, updated build script and published a new build: https://codeception.com/builds

Also I changed the default branch of this repo to 4.1
