### ISSUE TITLE
[DONE] Replace Travis by Github Actions

### ISSUE THREAD

**Issue by eXorus** [Codeception/Codeception#5890]
**25 modules updates:** (All core modules 26 - WebDriver)
- [x] module-amqp: https://github.com/Codeception/module-amqp/pull/1
- [x] module-asserts: https://github.com/Codeception/module-asserts/pull/2
- [x] module-datafactory: https://github.com/Codeception/module-datafactory/pull/1
- [x] module-doctrine2: https://github.com/Codeception/module-doctrine2/pull/8
- [x] module-filesystem: https://github.com/Codeception/module-filesystem/pull/2
- [x] module-lumen: https://github.com/Codeception/module-lumen/pull/3
- [x] module-mezzio: https://github.com/Codeception/module-mezzio/pull/5
- [x] module-phalcon: https://github.com/Codeception/module-phalcon/pull/4
- [x] module-phpbrowser: https://github.com/Codeception/module-phpbrowser/pull/2
- [x] module-redis: https://github.com/Codeception/module-redis/pull/2
- [x] module-sequence: https://github.com/Codeception/module-sequence/pull/1
- [x] module-symfony: https://github.com/Codeception/module-symfony/pull/6
- [x] module-yii2: https://github.com/Codeception/module-yii2/pull/6
- [x] module-apc: https://github.com/Codeception/module-apc/pull/2
- [x] module-cli: https://github.com/Codeception/module-cli/pull/1
- [x] module-db: https://github.com/Codeception/module-db/pull/6
- [x] module-ftp: https://github.com/Codeception/module-ftp/pull/2
- [x] module-laravel5: https://github.com/Codeception/module-laravel5/pull/7
- [x] module-memcache: https://github.com/Codeception/module-memcache/pull/1
- [x] module-mongodb: https://github.com/Codeception/module-mongodb/pull/2
- [x] module-phalcon4: https://github.com/Codeception/module-phalcon4/pull/6
- [x] module-queue: https://github.com/Codeception/module-queue/pull/3
- [x] module-rest: https://github.com/Codeception/module-rest/pull/3
- [x] module-soap: https://github.com/Codeception/module-soap/pull/2
- [x] module-zf2: https://github.com/Codeception/module-zf2/pull/8

**What has been done?**
- Replace Travis by Github Actions (all tests 🆗 if Travis was ok)
- Add PHP 7.4 tests
- Replace the badge in the Readme
- Command: composer install --prefer-dist --no-progress --no-interaction --no-suggest
- Added composer require phpunit/phpunit "<=8.5.2" --no-update --ignore-platform-reqs sometimes because 8.5.3 added a BC.
- Use the last version of actions/checkout@v2
- Use the last version of shivammathur/setup-php@v2
- Update composer with "codeception/codeception": "^4.0"
- Reference this issue: See https://github.com/Codeception/Codeception/issues/5890

Could be done later:
- Remove semaphoreci by Github Actions for WebDriver
- Fix failed tests, or skipped tests: amqp, lumen, db, ftp, 
- Fix all deprecated in Codeception modules: asserts, lumen, phalcon, sf, yii2, db, laravel5, zf2
- Fix warning in composer.json
- Use GitHub Actions to update the doc
- Use GitHub Actions for Codeception main repository
- ...

**Comment by eXorus** [comment]
Hello @Naktibalda and @DavertMik 

I have finished to upgrade all the repositories of Codeception to migrate to Github Actions.

**Comment by Slamdunk** [comment]
Awesome work!

Could we test the outcome *before* merging the PR? I think that needs a setting to be activated somewhere, right?

**Comment by eXorus** [comment]
@Slamdunk Thanks

No GitHub Actions is activated by default I think.
You only need to merge it on master to activate it.

You can see the result before merging on my fork, for example for module DB:
https://github.com/eXorus/module-db/actions

**Comment by eXorus** [comment]
@Naktibalda or @DavertMik 
I know it's a lot of work to check and merge all the PR, but it was also a lot of work for me.

**Comment by DavertMik** [comment]
I think I merged all of them expect marked ones

* asserts - have conflicts
* mongodb - marked as draft
* phalcon4 (merged) but static analysis failing bacuse of actor files

**Comment by eXorus** [comment]
@DavertMik  Thanks for all your merge
- asserts => fixed
- mongodb => fixed
- phalcon4 => yes it was already the case before my work

**Comment by eXorus** [comment]
Thanks @DavertMik and @Naktibalda 
25 modules merged
