### ISSUE TITLE
Step decorator functions are undefined in Acceptance Test

### ISSUE THREAD

**Issue by MF-Billings** [Codeception/Codeception#5893]
#### What are you trying to achieve?

use tryTo and retry functions

#### What do you get instead

  [RuntimeException] Call to undefined method Step\Acceptance\Admin::tryToSeeElement

I also have the same issue when trying to use retry()

> Provide console output if related. Use `-vvv` mode for more details.

```bash
$ vendor/bin/codecept run acceptance modules/prevent/ResourcesCest.php --debug
Codeception PHP Testing Framework v3.1.2
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Running with seed:

Acceptance Tests (1) -------------------------------------------------------------------------------------------------------------------------------Modules: WebDriver, Db, \Helper\Acceptance
----------------------------------------------------------------------------------------------------------------------------------------------------ResourcesCest: Add resource
Signature: Tests\Acceptance\Modules\Prevent\ResourcesCest:addResource
Test: tests\acceptance\modules\prevent\ResourcesCest.php:addResource
Scenario --
 I load session snapshot "login__admin"
 I am on page "/auth/logout"
 I am on page "/auth/login"
 I click "Login"
 I see "Users"
 I save session snapshot "login__admin"
  [Snapshot] Saved "login__admin" session snapshot
 I login as admin
   I load session snapshot "login__admin"
  [Snapshot] Restored "login__admin" session snapshot
 I am on page "/prevent/config"
 I am on page "/prevent/config"
  [Selenium server Logs]
  18:54:32.738 INFO - Capabilities are: {
    "browserName": "chrome",
    "chromeOptions": {
      "w3c": false,
      "binary": ""
    }
  }
  18:54:32.740 INFO - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
  18:54:35.847 INFO - Detected dialect: OSS
  18:54:35.876 INFO - Started new session a8c67a79317a779175a83996f8f51555 (org.openqa.selenium.chrome.ChromeDriverService)

  [Selenium driver Logs]
  18:54:35.304 SEVERE - Timed out receiving message from renderer: 0.100

  18:54:35.405 SEVERE - Timed out receiving message from renderer: 0.100

  18:54:37.33 SEVERE - Timed out receiving message from renderer: 0.100

  18:54:38.121 SEVERE - Timed out receiving message from renderer: 0.100

  18:54:38.634 SEVERE - Timed out receiving message from renderer: 0.100

----------------------------------------------------------------------------------------------------------------------------------------------------


Time: 6.83 seconds, Memory: 16.25MB

There was 1 error:

---------
1) ResourcesCest: Add resource
 Test  tests\acceptance\modules\prevent\ResourcesCest.php:addResource

  [RuntimeException] Call to undefined method Step\Acceptance\Admin::tryToSeeElement


Scenario Steps:

 12. $I->amOnPage("/prevent/config") at tests\acceptance\modules\prevent\ResourcesCest.php:18
 11. $I->amOnPage("/prevent/config") at tests\acceptance\modules\prevent\ResourcesCest.php:12
 10. $I->loadSessionSnapshot("login__admin") at tests\_support\AcceptanceTester.php:31
 9. $I->saveSessionSnapshot("login__admin") at tests\_support\AcceptanceTester.php:44
 8. $I->see("Users") at tests\_support\AcceptanceTester.php:42
 7. $I->click("Login") at tests\_support\AcceptanceTester.php:40

ERRORS!
Tests: 1, Assertions: 1, Errors: 1.
  [Db] Disconnected from default

```
> Provide test source code if related

```php
namespace Tests\Acceptance\Modules\Prevent;

use Step\Acceptance\Admin;

class ResourcesCest
{
	public function _before(Admin $I)
	{
		$I->loginAsAdmin();
		$I->amOnPage('/prevent/config');
	}

	// tests
	public function addResource(Admin $I)
	{
		$I->amOnPage('/prevent/config');

		if ($I->tryToSeeElement('div.sidebar-toggler')) {
			codecept_debug('I saw the thing!');
			$I->click('div.sidebar-toggler');
		}
		codecept_debug('I didnt saw the thing!');
	}
}
```
### Details

* Codeception version: 3.1.2
* PHP Version: 5.6
* Operating System: Windows 10
* Installation type: Composer
* List of installed packages
alchemy/zippy                      0.3.5              Zippy, the archive manager companion
behat/gherkin                      v4.6.0             Gherkin DSL parser for PHP 5.3
box/spout                          v2.7.3             PHP Library to read and write spreadsheet files (CSV, XLSX and ODS), in a fast and scala...
codeception/codeception            3.1.2              BDD-style testing framework
codeception/phpunit-wrapper        6.0.17             PHPUnit classes used by Codeception
codeception/stub                   2.1.0              Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/collections               v1.4.0             Collections Abstraction library
doctrine/instantiator              1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constr...
facebook/webdriver                 1.7.1              A PHP client for Selenium WebDriver
firebase/php-jwt                   v5.0.0             A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to th...
fzaninotto/faker                   v1.8.0             Faker is a PHP library that generates fake data for you.
google/recaptcha                   1.1.2              Client library for reCAPTCHA, a free service that protect websites from spam and abuse.
guzzle/guzzle                      v3.9.3             PHP HTTP client. This library is deprecated in favor of https://packagist.org/packages/g...
guzzlehttp/guzzle                  6.4.1              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.6.1              PSR-7 message implementation that also provides common utility methods
guzzlehttp/ringphp                 1.1.0              Provides a simple API and specification that abstracts away the details of HTTP into a s...
guzzlehttp/streams                 3.0.0              Provides a simple abstraction over streams of data
hoa/consistency                    1.17.05.02         The Hoa\Consistency library.
hoa/console                        3.17.05.02         The Hoa\Console library.
hoa/event                          1.17.01.13         The Hoa\Event library.
hoa/exception                      1.17.01.16         The Hoa\Exception library.
hoa/file                           1.17.07.11         The Hoa\File library.
hoa/iterator                       2.17.01.10         The Hoa\Iterator library.
hoa/protocol                       1.17.01.14         The Hoa\Protocol library.
hoa/stream                         1.17.02.21         The Hoa\Stream library.
hoa/ustring                        4.17.01.16         The Hoa\Ustring library.
intervention/image                 2.2.2              Image handling and manipulation library with support for Laravel integration
league/csv                         8.2.3              Csv data manipulation made easy in PHP
mobiledetect/mobiledetectlib       2.7.1              Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-...
monolog/monolog                    1.21.0             Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression          v1.0.3             CRON for PHP: Calculate the next or previous run date and determine if a CRON expression...
myclabs/deep-copy                  1.7.0              Create deep copies (clones) of your objects
nesbot/carbon                      1.18.0             A simple API extension for DateTime.
omnipay/authorizenet               2.3.1              Authorize.Net gateway for the Omnipay payment processing library
omnipay/common                     v2.5.1             Common components for Omnipay payment processing library
onelogin/php-saml                  3.1.1              OneLogin PHP SAML Toolkit
paragonie/random_compat            v2.0.12            PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pear/archive_tar                   1.4.2              Tar file management class
pear/console_getopt                v1.4.1             More info available on: http://pear.php.net/package/Console_Getopt
pear/ole                           dev-master 29a37bb More info available on: http://pear.php.net/package/OLE
pear/pear                          dev-master d346efa This is the definitive source of PEAR's core files.
pear/pear-core-minimal             v1.10.1            Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception                v1.0.0             The PEAR Exception base class.
pear/spreadsheet_excel_writer      dev-master e731e23 More info available on: http://pear.php.net/package/Spreadsheet_Excel_Writer
pear/structures_graph              v1.1.1             More info available on: http://pear.php.net/package/Structures_Graph
pear/xml_util                      v1.3.0             Methods to work with XML documents
phpcompatibility/php-compatibility 9.1.1              A set of sniffs for PHP_CodeSniffer that checks for PHP cross-version compatibility.
phpdocumentor/reflection-common    1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  3.3.2              With this component, a library can provide support for annotations via DocBlocks or othe...
phpdocumentor/type-resolver        0.4.0
phpoffice/phpexcel                 1.8.1              PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet e...
phpspec/prophecy                   1.9.0              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          4.0.8              Library that provides collection, processing, and rendering functionality for PHP code c...
phpunit/php-file-iterator          1.4.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  1.0.9              Utility class for timing
phpunit/php-token-stream           1.4.12             Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.7.27             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.4              Mock Object library for PHPUnit
psr/http-message                   1.0.1              Common interface for HTTP messages
psr/log                            1.0.0              Common interface for logging libraries
ralouphie/getallheaders            3.0.3              A polyfill for getallheaders.
react/promise                      v2.5.1             A lightweight implementation of CommonJS Promises/A for PHP
robrichards/xmlseclibs             3.0.3              A PHP library for XML Security
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator               1.2.4              Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.3              Diff implementation
sebastian/environment              2.0.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 2.0.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state             1.1.1              Snapshotting of global state
sebastian/object-enumerator        2.0.1              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context        2.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
setasign/fpdf                      1.8.1              FPDF is a PHP class which allows to generate PDF files with pure PHP. F from FPDF stands...
setasign/fpdi                      v2.1.0             FPDI is a collection of PHP classes facilitating developers to read pages from existing ...
setasign/fpdi-fpdf                 v2.0.0             Kind of metadata package for dependencies of the latest versions of FPDI and FPDF.
squizlabs/php_codesniffer          2.9.2              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defi...
swiftmailer/swiftmailer            v5.0.2             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                v3.4.35            Symfony BrowserKit Component
symfony/config                     v2.6.13            Symfony Config Component
symfony/console                    v3.4.35            Symfony Console Component
symfony/css-selector               v3.4.35            Symfony CssSelector Component
symfony/debug                      v3.4.35            Symfony Debug Component
symfony/dom-crawler                v3.4.35            Symfony DomCrawler Component
symfony/dotenv                     v3.4.21            Registers environment variables from a .env file
symfony/event-dispatcher           v2.8.11            Symfony EventDispatcher Component
symfony/expression-language        v2.8.2             Symfony ExpressionLanguage Component
symfony/filesystem                 v2.8.14            Symfony Filesystem Component
symfony/finder                     v3.4.35            Symfony Finder Component
symfony/http-foundation            v3.4.9             Symfony HttpFoundation Component
symfony/polyfill-ctype             v1.12.0            Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.8.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php70             v1.8.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/process                    v3.4.21            Symfony Process Component
symfony/translation                v2.6.13            Symfony Translation Component
symfony/validator                  v2.8.26            Symfony Validator Component
symfony/yaml                       v3.4.35            Symfony Yaml Component
twig/twig                          v1.16.0            Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                   1.5.0              Assertions to validate method input/output with nice error messages.
zendframework/zend-authentication  2.2.4              provides an API for authentication and includes concrete authentication adapters for com...
zendframework/zend-code            2.2.4              provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-escaper         2.2.4
zendframework/zend-eventmanager    2.2.4
zendframework/zend-ldap            2.2.4              provides support for LDAP operations including but not limited to binding, searching and...
zendframework/zend-server          2.2.4
zendframework/zend-soap            2.2.4
zendframework/zend-stdlib          2.2.4
zendframework/zend-uri             2.2.4              a component that aids in manipulating and validating » Uniform Resource Identifiers (URIs)
zendframework/zend-validator       2.2.4              provides a set of commonly needed validators

* Suite configuration:

```yml
#acceptance.suite.yml
actor: AcceptanceTester
modules:
    config:
        Db:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_DATABASE%'
            user: "%DB_USERNAME%"
            password: "%DB_PASSWORD%"
    enabled:
        - WebDriver:
            url: %URL%
            browser: chrome
        - Db
        - \Helper\Acceptance
    step_decorators:
        - \Codeception\Step\Retry
        - \Codeception\Step\TryTo
```

I've tried running codecept build but neither retry nor tryTo methods end up included in the AcceptanceTester.

**Comment by rene-hermenau** [comment]
Same issue here. TryTo methods are not generated!
