### ISSUE TITLE
Codeception 4.1 (phar) and PhpStorm = Fatal Error

### ISSUE THREAD

**Issue by voku** [Codeception/Codeception#5899]
#### What are you trying to achieve?

Running ```codecept.phar``` in PhpStorm after upgrading from v3 ⇉ v4

PS: already reported here: https://youtrack.jetbrains.com/issue/WI-52048 ... so maybe we can close this issue ⇾ I just wanted to inform you, that it seems like a breaking change to change the "autoload"-file-path

#### What do you get instead?

```bash
/usr/bin/php7.2 /tmp/ide-codeception.php run --report -o "reporters: report: PhpStorm_Codeception_ReportPrinter" --no-interaction unit -c /home/lmoelleken/vdmg/codeception.yml App/modules/FooBarUnitCest.php
PHP Warning:  require_once(phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/autoload.php): failed to open stream: phar error: "autoload.php" is not a file in phar "/home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar" in /tmp/ide-codeception.php on line 21
PHP Fatal error:  require_once(): Failed opening required 'phar:///home/lmoelleken/vdmg/Framework/thirdparty/codecept.phar/autoload.php' (include_path='.:/usr/share/php') in /tmp/ide-codeception.php on line 21

Process finished with exit code 255
```

### Details

* Codeception version: 4.1.2
* PHP Version: 7.4
* Operating System: Ubuntu 18.04
* Installation type: Phar
* PhpStorm 2019.3.4

**Comment by Naktibalda** [comment]
Phar structure has changed in Codeception 4,
if they must require autoload.php, correct path is phar://codecept.phar/vendor/codeception/codeception/autoload.php
