### ISSUE TITLE
does DB module support dynamic configuration so far?

### ISSUE THREAD

**Issue by wyhmichael** [Codeception/Codeception#590]
I'm trying to call the following method in my tests from my helper class which does seem to work for me

``` php
public function configDbConn($params)
{
   $this->getModule('Db')->_reconfigure($params);
}
```

after calling the method, the db is still the one I set in the suite.yml file

I checked the db module class, seems like $driver is only create once in `_initialize`, and didn't find anything updating it when calling `_reconfigure`

**Comment by rogoit** [comment]
Not working for me ;(
