### ISSUE TITLE
[Error] Class 'WebDriverBy' not found after updating codeception to 4.1.4

### ISSUE THREAD

**Issue by kjnanda** [Codeception/Codeception#5906]
After I update the codeception to its latest version I am facing this issue with `WebDriverBy` class.

One of my codeception test file has below code:

<pre>$optionDivColor = $I->executeInSelenium(function(\Facebook\WebDriver\Remote\RemoteWebDriver $webdriver) {
   return $webdriver->findElement(WebDriverBy::cssSelector('.rtm-media-options '))->getCSSValue('color');
   });</pre>

Using the above code, I am trying to get the css property of the mentioned class and then I am fetching the color of it.

This is working fine with codeception 2.5.4 where I have not updated the packages but after updating the dependencies, I get the following message for `/facebook/webdriver` package:

This package is abandoned and no longer maintained. The author suggests using the `php-webdriver/webdriver` package instead.

So I updated my composer.json file and below is the code of my composer.json file.
<pre>
{
    "require-dev": {
        "lucatume/wp-browser": "*",
        "codeception/module-webdriver": "*",
        "codeception/module-asserts": "*",
        "php-webdriver/webdriver": "*"
    }
}
</pre>
### Details

* Codeception version: 4.1.4
* PHP Version: 7.3.0
* Operating System: MAC OSX
* Installation type: Composer 
* List of installed packages (`composer show`)

<pre>
antecedent/patchwork               2.1.12   Method redefinition (monkey-patching) functionality for PHP.
behat/gherkin                      v4.6.2   Gherkin DSL parser for PHP 5.3
codeception/codeception            4.1.4    BDD-style testing framework
codeception/lib-asserts            1.12.0   Assertion methods used by Codeception core and Asserts module
codeception/module-asserts         1.2.1    Codeception module containing various assertions
codeception/module-webdriver       1.0.7    WebDriver module for Codeception
codeception/phpunit-wrapper        9.0.2    PHPUnit classes used by Codeception
codeception/stub                   3.6.1    Flexible Stub wrapper for PHPUnit's Mock Builder
composer/ca-bundle                 1.2.7    Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer                  1.10.5   Composer helps you declare, manage and install dependencies of PHP projects. It ensures you have the right st...
composer/semver                    1.5.1    Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses             1.5.3    SPDX licenses list and validation library.
composer/xdebug-handler            1.4.1    Restarts a process without Xdebug.
cweagans/composer-patches          1.6.7    Provides a way to patch Composer packages.
dg/mysql-dump                      v1.5.1   MySQL database dump.
doctrine/inflector                 1.3.1    Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator              1.3.0    A small, lightweight utility to instantiate objects in PHP without invoking their constructors
gettext/gettext                    v4.8.2   PHP gettext manager
gettext/languages                  2.6.0    gettext languages with plural rules
gumlet/php-image-resize            1.9.2    PHP class to re-size and scale images
guzzlehttp/psr7                    1.6.1    PSR-7 message implementation that also provides common utility methods
hautelook/phpass                   0.3.5    Portable PHP password hashing framework
illuminate/contracts               v7.8.1   The Illuminate Contracts package.
illuminate/support                 v7.8.1   The Illuminate Support package.
justinrainbow/json-schema          5.2.9    A library to validate a json schema.
lucatume/wp-browser                2.4.7    WordPress extension of the PhpBrowser class.
mck89/peast                        v1.10.3  Peast is PHP library that generates AST for JavaScript code
mikemclin/laravel-wp-password      2.0.1    Laravel package that checks and creates WordPress password hashes
mustache/mustache                  v2.13.0  A Mustache implementation in PHP.
myclabs/deep-copy                  1.9.5    Create deep copies (clones) of your objects
nb/oxymel                          v0.1.0   A sweet XML builder
nesbot/carbon                      2.32.2   An API extension for DateTime that supports 281 different languages.
phar-io/manifest                   1.0.3    Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1    Library for handling version information and constraints
php-webdriver/webdriver            1.8.2    A PHP client for Selenium WebDriver. Previously facebook/webdriver.
phpdocumentor/reflection-common    2.1.0    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  5.1.0    With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve inform...
phpdocumentor/type-resolver        1.1.0    A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoption/phpoption                1.7.3    Option Type for PHP
phpspec/prophecy                   v1.10.3  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          8.0.1    Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          3.0.1    FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.0.0    Invoke callables with a timeout
phpunit/php-text-template          2.0.0    Simple template engine.
phpunit/php-timer                  3.1.4    Utility class for timing
phpunit/php-token-stream           4.0.0    Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    9.1.3    The PHP Unit Testing framework.
psr/container                      1.0.0    Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0    Standard interfaces for event handling.
psr/http-message                   1.0.1    Common interface for HTTP messages
psr/log                            1.1.3    Common interface for logging libraries
psr/simple-cache                   1.0.1    Common interfaces for simple caching
ralouphie/getallheaders            3.0.3    A polyfill for getallheaders.
rmccue/requests                    v1.7.0   A HTTP library written in PHP, for human beings.
sebastian/code-unit                1.0.1    Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.0    Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.0    Provides the functionality to compare PHP values for equality
sebastian/diff                     4.0.0    Diff implementation
sebastian/environment              5.1.0    Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.0    Provides the functionality to export PHP variables for visualization
sebastian/global-state             4.0.0    Snapshotting of global state
sebastian/object-enumerator        4.0.0    Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.0    Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.0    Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.0    Provides a list of PHP built-in functions that operate on resources
sebastian/type                     2.0.0    Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.0    Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                      1.7.2    JSON Linter
seld/phar-utils                    1.1.0    PHAR file format utilities, for when PHP phars you up
symfony/console                    v5.0.7   Symfony Console Component
symfony/css-selector               v5.0.7   Symfony CssSelector Component
symfony/event-dispatcher           v5.0.7   Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v2.0.1   Generic abstractions related to dispatching event
symfony/filesystem                 v3.4.39  Symfony Filesystem Component
symfony/finder                     v5.0.7   Symfony Finder Component
symfony/polyfill-ctype             v1.15.0  Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.15.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.15.0  Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                    v4.4.7   Symfony Process Component
symfony/service-contracts          v2.0.1   Generic abstractions related to writing services
symfony/translation                v5.0.7   Symfony Translation Component
symfony/translation-contracts      v2.0.1   Generic abstractions related to translation
symfony/yaml                       v5.0.7   Symfony Yaml Component
theseer/tokenizer                  1.1.3    A small library for converting tokenized PHP source code into XML and potentially other formats
vlucas/phpdotenv                   v3.6.3   Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
voku/portable-ascii                1.4.10   Portable ASCII library - performance optimized (ascii) string functions for php.
vria/nodiacritic                   0.1.2    Tiny helper function that removes all diacritical signs from characters
webmozart/assert                   1.8.0    Assertions to validate method input/output with nice error messages.
wp-cli/cache-command               v2.0.3   Manages object and transient caches.
wp-cli/checksum-command            v2.0.3   Verifies file integrity by comparing to published checksums.
wp-cli/config-command              v2.0.5   Generates and reads the wp-config.php file.
wp-cli/core-command                v2.0.8   Downloads, installs, updates, and manages a WordPress installation.
wp-cli/cron-command                v2.0.4   Tests, runs, and deletes WP-Cron events; manages WP-Cron schedules.
wp-cli/db-command                  v2.0.6   Performs basic database operations using credentials stored in wp-config.php.
wp-cli/embed-command               v2.0.4   Inspects oEmbed providers, clears embed cache, and more.
wp-cli/entity-command              v2.0.7   Manage WordPress comments, menus, options, posts, sites, terms, and users.
wp-cli/eval-command                v2.0.6   Executes arbitrary PHP code or files.
wp-cli/export-command              v2.0.3   Exports WordPress content to a WXR file.
wp-cli/extension-command           v2.0.9   Manages plugins and themes, including installs, activations, and updates.
wp-cli/i18n-command                v2.2.2   Provides internationalization tools for WordPress projects.
wp-cli/import-command              v2.0.2   Imports content from a given WXR file.
wp-cli/language-command            v2.0.5   Installs, activates, and manages language packs.
wp-cli/maintenance-mode-command    v2.0.2   Activates, deactivates or checks the status of the maintenance mode of a site.
wp-cli/media-command               v2.0.7   Imports files as attachments, regenerates thumbnails, or lists registered image sizes.
wp-cli/mustangostang-spyc          0.6.3    A simple YAML loader/dumper class for PHP (WP-CLI fork)
wp-cli/package-command             v2.0.6   Lists, installs, and removes WP-CLI packages.
wp-cli/php-cli-tools               v0.11.11 Console utilities for PHP
wp-cli/rewrite-command             v2.0.4   Lists or flushes the site's rewrite rules, updates the permalink structure.
wp-cli/role-command                v2.0.3   Adds, removes, lists, and resets roles and capabilities.
wp-cli/scaffold-command            v2.0.8   Generates code for post types, taxonomies, blocks, plugins, child themes, etc.
wp-cli/search-replace-command      v2.0.6   Searches/replaces strings in the database.
wp-cli/server-command              v2.0.4   Launches PHP's built-in web server for a specific WordPress installation.
wp-cli/shell-command               v2.0.4   Opens an interactive PHP console for running and testing PHP code.
wp-cli/super-admin-command         v2.0.3   Lists, adds, or removes super admin users on a multisite installation.
wp-cli/widget-command              v2.1.0   Adds, moves, and removes widgets; lists sidebars.
wp-cli/wp-cli                      v2.4.1   WP-CLI framework
wp-cli/wp-cli-bundle               v2.4.0   WP-CLI bundle package with default commands.
wp-cli/wp-config-transformer       v1.2.6   Programmatically edit a wp-config.php file.
zordius/lightncandy                v1.2.5   An extremely fast PHP implementation of handlebars ( http://handlebarsjs.com/ ) and mustache ( http://mustach..
</pre>

* Suite configuration:

```
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WPWebDriver
        - Asserts
    config:
        WPWebDriver:
            browser: 'chrome'
            url: 'http://automation.me/'
            adminUsername: ''
            adminPassword: ''
            adminPath: '/wp-admin'
```
-----
![javalnanda_krupa___Krupa_GitHub_Projects_rtMedia_tests_codeception_and_New_Issue_·_lucatume_wp-browser](https://user-images.githubusercontent.com/15173772/80467085-fc3adf00-895a-11ea-82de-2ced91568a5d.png)

----

Can someone please help me how can I resolve this? Or what is missing from my end?

Many Thanks,
Krupa

**Comment by Naktibalda** [comment]
[That class](https://github.com/php-webdriver/php-webdriver/blob/master/lib/WebDriverBy.php) is namespaced,
so you need `use Facebook\WebDriver\WebDriverBy;` at the top of your test file.
