### ISSUE TITLE
Error installing Codeception

### ISSUE THREAD

**Issue by jenvigo** [Codeception/Codeception#5908]
#### What are you trying to achieve?
run php vendor/bin/codecept bootstrap in Bash through an SSH session. I am using "domain@da05:~/domains/qms.domain.com.pe/public_html$ chmod 700 vendor/bin/codecept bootstrap".

#### What do you get instead?
chmod: cannot access 'bootstrap': No such file or directory

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
chmod: cannot access 'bootstrap': No such file or directory
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 4.1
* PHP Version: 7.3.16
* Operating System: Debian 4.9
* Installation type: Phar || **Composer**
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
`bootstrap` is a parameter, why are you trying to chmod it? :)

**Comment by jenvigo** [comment]
I had that suggestion from a colleague who manages the servers. :)

But after a few thousand attempts I think my problem is solved. 
Instead of using "composer require "codeception/codeception" --dev" I used 

`composer.phar require "codeception/codeception"`

And now it works, Can you maybe help me understanding the reason?
Thanks for the quick response @Naktibalda
