### ISSUE TITLE
PSR-*

### ISSUE THREAD

**Issue by Jeckerson** [Codeception/Codeception#5912]
#### What are you trying to achieve?
Is there are plans to Codeception be PSR compliant? 
For example methods like `_before()`, `_after()` (PSR-12). Folders structure (PSR-4), etc.

**Comment by aleksblendwerk** [comment]
I would like to see this as well.

Related when it comes to the folders structure: https://github.com/Codeception/Codeception/issues/5727.

**Comment by Naktibalda** [comment]
There are no plans to change naming of special methods.

There is an old excuse that using underscore in method names is not forbidden by PSR-12.

> Property names MUST NOT be prefixed with a single underscore **to indicate protected or private visibility**. That is, an **underscore prefix explicitly has no meaning**

Underscore in the name of Codeception methods does not mean that their visibility is private or protected, it is used to differentiate test methods from supporting methods.
