### ISSUE TITLE
Upgrade official docker image to use PHP 7.4

### ISSUE THREAD

**Issue by hallids** [Codeception/Codeception#5914]
#### What are you trying to achieve?
Use PHP 7.4 language features in unit tested code in the official docker image.

#### What do you get instead?

Language features that are new in PHP 7.4 cause a syntax error because they are being run in a docker image based on PHP 7.3 (`FROM php:7.3-cli` in `Dockerfile`)

For example, this code
```php
private static Logger $logger;
```

Produces this error:
```
 [ParseError] syntax error, unexpected 'Logger' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
```

### Details

* Codeception version: 4.1
* PHP Version: N/A
* Operating System: Docker for WIndows
* Installation type: Docker
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: UnitTester
modules:
    enabled:
        - \Helper\Unit
```

**Comment by Naktibalda** [comment]
Fixed by #5917
Please test codeception/codecetion:4.1.5
