### ISSUE TITLE
Need a way to force a click

### ISSUE THREAD

**Issue by jeffschaefer1** [Codeception/Codeception#5925]
#### What are you trying to achieve?
Click a button that isn't a traditional link or form
#### What do you get instead?

[TestRuntimeException] Button is not inside a link or a form

I see the other issues and pull requests related to this and it seems like there must be some other way to click on something? Maybe something lower level than the click() function? Otherwise, I don't understand how this is being used on real websites that have all kinds of situations that don't conform to this basic model. In my case the website I am testing uses javascript to trigger a modal after a button-like span is clicked.
Let me know if there is some other way to force codeception to trust me and just click where I say.

* Codeception version:
* PHP Version: 7.2.9
* Operating System: Linux
* Installation type:  Composer
* List of installed packages (`composer show`)
* Suite configuration:

**Comment by Naktibalda** [comment]
That error only happens if you use module which doesn't support Javascript - PhpBrowser or one of framework modules.

To test complex frontend, use a real browser via [WebDriver module](https://codeception.com/docs/modules/WebDriver)

**Comment by jeffschaefer1** [comment]
Thanks for clearing up my confusion!
