### ISSUE TITLE
Remove class_alias Symfony\Component\EventDispatcher\Event

### ISSUE THREAD

**Issue by qRoC** [Codeception/Codeception#5927]
By [adding](https://github.com/Codeception/Codeception/blob/4.1/shim.php#L41) a class alias in the Symfony space, you violating work in other packages that use this class to check the version.

Example:
[enqueue/async-event-dispatcher](https://github.com/php-enqueue/async-event-dispatcher/blob/master/AsyncEventDispatcher.php#L7)

**Comment by Naktibalda** [comment]
Sorry about that, that's the only way to support Symfony 3 and Symfony 5 in the same codebase.

You are asking to drop support for Symfony <4.3 or <5. It will probably happen in the next major release of Codeception (so Codeception 5), but there aren't any plans to make it happen soon.

The alternative is to ask `enqueue/async-event-dispatcher` to drop support for Symfony 4.

**Comment by qRoC** [comment]
I do not ask to drop support. It’s possible to just make a basic class instead of using class_alias.

**Comment by UniverseOfMadness** [comment]
Hi. [Symfony itself](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L70) uses that kind of logic. It does not seem to break anything but shows false deprecations for Symfony 5.1. Maybe it could be possible to [use this](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L77) to detect Symfony version and add/not add alias?

**Comment by Naktibalda** [comment]
This alias will be removed in Codeception 5.0.0 #6067
