### ISSUE TITLE
Documentation - the "assertion spaces" for amOnPage and sendPOST should be more clearly separate

### ISSUE THREAD

**Issue by yourpropertyexpert** [Codeception/Codeception#5939]
#### What are you trying to achieve?

I was running a series of related tests, some of which used amOnPage, others of which use sendPOST.

I was trying to run $I->see after each sendPOST to check the returns.

#### What do you get instead?

The $I->see was applying the assertion to the previously run amOnPage, not the sendPOST.

This is almost certainly correct behaviour, but wasn't obvious from the documentation.

### Details

* Codeception version: 4
* PHP Version: 7.3
* Operating System: Alpine
* Installation type: Composer
* List of installed packages (`composer show`)

    	"codeception/codeception": "^4.0",
        "codeception/module-phpbrowser": "^1.0.0",
        "codeception/module-asserts": "^1.0.0",
        "codeception/module-webdriver": "^1.0.0",
        "codeception/module-rest": "^1.0.0"

* Suite configuration:

Any :-)

**Comment by Naktibalda** [comment]
`amOnPage` and `sendPOST` are not documented in the same place.  
`sendPOST` belongs to REST module, `amOnPage` belongs to WebDriver, PhpBrowser or one of framework modules.

Also read comments in https://github.com/Codeception/module-rest/issues/4

**Comment by yourpropertyexpert** [comment]
I know they are documented in the same place.

But the problem is that this isn't obvious to someone reading the WebDriver documentation... and if you are (as I am) running a mixed set of tests, the Assertions appear to run... they are just based on the previous call...

All I'm asking for is a line in the documentation for WebDriver that says this...

**Comment by Naktibalda** [comment]
sendPOST isn't mentioned at all in https://codeception.com/docs/modules/WebDriver

Are you asking  for "Warning! Methods not mentioned on this page can't inspect current page and vice verse."?

**Comment by yourpropertyexpert** [comment]
> Are you asking for "Warning! Methods not mentioned on this page can't inspect current page and vice verse."?

Yes :-)

Exactly that....
