### ISSUE TITLE
Suggestion: add a -v option to "codecept init"

### ISSUE THREAD

**Issue by yourpropertyexpert** [Codeception/Codeception#5940]
#### What are you trying to achieve?

I run Codeception within a CI system that works as follows:

- Spin up a set of "docker servers" (including Selenium and a Codeception)
- On one, run concept init to create a framework (codecept init)
- Pull a set of Codeception tests from a git repo
- Run them (codecept run)

#### What do you get instead?

On each CI run (of which there are many every day), I get about 20 lines of stuff telling me how to configure Codeception  :-)

> Provide console output if related. Use `-vvv` mode for more details.

```bash

6 | Let's prepare Codeception for acceptance testing
7 | Create your tests and run them in real browser
8 |  
9 | Ensure that you have Selenium Server and ChromeDriver installed before running tests
10 | Created test directories inside at tests
11 | Acceptance helper has been created in tests/_support/Helper
12 | AcceptanceTester actor has been created in tests/_support
13 | Actions have been loaded
14 | Created global config codeception.yml inside the root directory
15 | Created a demo test LoginCest.php
16 |  
17 | INSTALLATION COMPLETE
18 |  
19 | Next steps:
20 | 1. Launch Selenium Server and webserver
21 | 2. Edit tests/LoginCest.php to test login of your application
22 | 3. Run tests using: codecept run
23 |  
24 | HINT: Add '\Codeception\Step\Retry' trait to AcceptanceTester class to enable auto-retries
25 | HINT: See https://codeception.com/docs/03-AcceptanceTests#retry
26 | Happy testing!

Given that this is all running in a CI (many times a day), I would like an option to suppress this...

... ideally a -v option to "codecept init."

```
### Details

* Codeception version: 4.0.0
* PHP Version: 7.3
* Operating System: Alpine Linux
* Installation type: Composer
* List of installed packages (`composer show`):

"codeception/codeception": "^4.0",
  "codeception/module-phpbrowser": "^1.0.0",
  "codeception/module-asserts": "^1.0.0",
  "codeception/module-webdriver": "^1.0.0",
  "codeception/module-rest": "^1.0.0"

* Suite configuration:

N/A - this happens prior to suite ingestion.

**Comment by Naktibalda** [comment]
I think that your problem us that you run `codecept init` when you don't need it.
Just commit codecept.yaml and suite configuration files to the same repository as tests.

**Comment by yourpropertyexpert** [comment]
> I think that your problem is that you run `codecept init` when you don't need it.
> Just commit codecept.yaml and suite configuration files to the same repository as tests.

Thanks for the suggestion.

Sadly, in Codeception 4.0, that gives 

> Module \Helper\Acceptance could not be found and loaded  


Never mind. This isn't urgent. I can simulate a -v by cunning use of shell scripts :-)

**Comment by Naktibalda** [comment]
`\Helper\Acceptance` is part of test suite, commit it too.

**Comment by yourpropertyexpert** [comment]
Excellent. I'm not running with everything I need.

Thank you.
