### ISSUE TITLE
AssertEquals true to false passes

### ISSUE THREAD

**Issue by noname1706** [Codeception/Codeception#5941]
#### What are you trying to achieve?

Trying to fail test when asserting equals between true and false.
#### What do you get instead?

The test passes.

> Provide test source code if related

```php
public function someTest(AcceptanceTester $I, $scenario)
    {
        $scenario->assertEquals(true, false);
    }
```
### Details

* Codeception version: 4.1.6
* PHP Version: PHP 7.4.4 (cli) (built: Mar 20 2020 14:24:19) ( NTS )
* Operating System: Debian GNU/Linux 9
* Installation type: Phar
* List of installed packages (`composer show`)
behat/gherkin                      v4.6.2  Gherkin DSL parser for PHP 5.3
codeception/codeception            4.1.6   BDD-style testing framework
codeception/lib-asserts            1.12.0  Assertion methods used by Codeception core and A...
codeception/lib-innerbrowser       1.3.1   Parent library for all Codeception framework mod...
codeception/module-asserts         1.2.1   Codeception module containing various assertions
codeception/module-phpbrowser      1.0.0   Codeception module for testing web application o...
codeception/module-rest            1.2.0   REST module for Codeception
codeception/module-webdriver       1.1.0   WebDriver module for Codeception
codeception/phpunit-wrapper        9.0.2   PHPUnit classes used by Codeception
codeception/stub                   3.6.1   Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.3.1   A small, lightweight utility to instantiate obje...
flow/jsonpath                      0.5.0   JSONPath implementation for parsing, searching a...
guzzlehttp/guzzle                  6.5.5   Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1  Guzzle promises library
guzzlehttp/psr7                    1.6.1   PSR-7 message implementation that also provides ...
justinrainbow/json-schema          5.2.10  A library to validate a json schema.
myclabs/deep-copy                  1.10.1  Create deep copies (clones) of your objects
phar-io/manifest                   1.0.3   Component for reading phar.io manifest informati...
phar-io/version                    2.0.1   Library for handling version information and con...
php-webdriver/webdriver            1.8.2   A PHP client for Selenium WebDriver. Previously ...
phpdocumentor/reflection-common    2.2.0   Common reflection classes used by phpdocumentor ...
phpdocumentor/reflection-docblock  5.1.0   With this component, a library can provide suppo...
phpdocumentor/type-resolver        1.3.0   A PSR-5 based resolver of Class names, Types and...
phpspec/prophecy                   v1.10.3 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          8.0.2   Library that provides collection, processing, an...
phpunit/php-file-iterator          3.0.3   FilterIterator implementation that filters files...
phpunit/php-invoker                3.0.2   Invoke callables with a timeout
phpunit/php-text-template          2.0.2   Simple template engine.
phpunit/php-timer                  5.0.1   Utility class for timing
phpunit/php-token-stream           4.0.3   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    9.2.5   The PHP Unit Testing framework.
psr/container                      1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0   Standard interfaces for event handling.
psr/http-message                   1.0.1   Common interface for HTTP messages
ralouphie/getallheaders            3.0.3   A polyfill for getallheaders.
sebastian/code-unit                1.0.5   Collection of value objects that represent the P...
sebastian/code-unit-reverse-lookup 2.0.2   Looks up which function or method a line of code...
sebastian/comparator               4.0.3   Provides the functionality to compare PHP values...
sebastian/diff                     4.0.2   Diff implementation
sebastian/environment              5.1.2   Provides functionality to handle HHVM/PHP enviro...
sebastian/exporter                 4.0.2   Provides the functionality to export PHP variabl...
sebastian/global-state             4.0.0   Snapshotting of global state
sebastian/object-enumerator        4.0.2   Traverses array structures and object graphs to ...
sebastian/object-reflector         2.0.2   Allows reflection of object attributes, includin...
sebastian/recursion-context        4.0.2   Provides functionality to recursively process PH...
sebastian/resource-operations      3.0.2   Provides a list of PHP built-in functions that o...
sebastian/type                     2.1.1   Collection of value objects that represent the t...
sebastian/version                  3.0.1   Library that helps with managing the version num...
symfony/browser-kit                v5.1.2  Symfony BrowserKit Component
symfony/console                    v5.1.2  Symfony Console Component
symfony/css-selector               v5.1.2  Symfony CssSelector Component
symfony/deprecation-contracts      v2.1.2  A generic function and convention to trigger dep...
symfony/dom-crawler                v5.1.2  Symfony DomCrawler Component
symfony/event-dispatcher           v5.1.2  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v2.1.2  Generic abstractions related to dispatching event
symfony/finder                     v5.1.2  Symfony Finder Component
symfony/polyfill-ctype             v1.17.1 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.17.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn          v1.17.1 Symfony polyfill for intl's idn_to_ascii and idn...
symfony/polyfill-intl-normalizer   v1.17.1 Symfony polyfill for intl's Normalizer class and...
symfony/polyfill-mbstring          v1.17.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.17.0 Symfony polyfill backporting some PHP 7.2+ featu...
symfony/polyfill-php73             v1.17.1 Symfony polyfill backporting some PHP 7.3+ featu...
symfony/polyfill-php80             v1.17.1 Symfony polyfill backporting some PHP 8.0+ featu...
symfony/process                    v5.1.2  Symfony Process Component
symfony/service-contracts          v2.1.2  Generic abstractions related to writing services
symfony/string                     v5.1.2  Symfony String component
symfony/yaml                       v5.1.2  Symfony Yaml Component
theseer/tokenizer                  1.1.3   A small library for converting tokenized PHP sou...
webmozart/assert                   1.9.0   Assertions to validate method input/output with ...

* Suite configuration:
```yml
actor: AcceptanceTester
modules:
    enabled:
            - PhpBrowser:
                url: https://test.com
            - REST:                                             
                depends: PhpBrowser                             
                url: https://test.com                      
                shortDebugResponse: 300                                    
    step_decorators: ~
```

**Comment by Naktibalda** [comment]
You are the first person to call `assertEquals` on `$scenario`.

Correct way would be to enable Asserts module and call `$I->assertEquals()`

**Comment by noname1706** [comment]
> You are the first person to call `assertEquals` on `$scenario`.
> 
> Correct way would be to enable Asserts module and call `$I->assertEquals()`

Yes, thank you very much. Sorry. 
By the way before Codeception 4 "Asserts" was enabled by default or I mixed something again?

**Comment by Naktibalda** [comment]
> By the way before Codeception 4 "Asserts" was enabled by default or I mixed something again?

It is enabled by default in unit suite.
