### ISSUE TITLE
Error after new release of php-code-coverage

### ISSUE THREAD

**Issue by bzawada** [Codeception/Codeception#5949]
After upgrade of composer packages at my project, I encountered error while running codeception with coverage:
` vendor/bin/codecept run unit --coverage-html --coverage-xml --coverage-text --no-colors --coverage --phpunit-xml`

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function SebastianBergmann\CodeCoverage\CodeCoverage::__construct(), 0 passed in ./vendor/codeception/codeception/src/Codeception/Coverage/Subscriber/Printer.php on line 37 and exactly 2 expected in ./vendor/phpunit/php-code-coverage/src/CodeCoverage.php:118

I see that today the 9.0.0 version of php-code-coverage was released, so it seems like some integration issue between php-code-coverage and codeception.

**Comment by Sweetchuck** [comment]
As a workaround:
`composer require --dev 'phpunit/phpunit:^8.0'`

**Comment by NicolasCARPi** [comment]
This issue can be seen here: https://travis-ci.org/github/Codeception/phpunit-wrapper/jobs/716331041#L677
The error is here: https://github.com/Codeception/Codeception/blob/4.1/src/Codeception/Coverage/Subscriber/Printer.php#L37
phpunit's [constructor](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/CodeCoverage.php#L133) needs a [Driver](https://github.com/sebastianbergmann/php-code-coverage/tree/master/src/Driver) and a [Filter](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Filter.php).

**Comment by burned42** [comment]
Also affected by this. The problem seems to be the major release 9.0 of https://github.com/sebastianbergmann/php-code-coverage changing the mentioned constructor signature. So a more specific workaround (keeping phpunit 9) for now would be

`composer require --dev 'phpunit/php-code-coverage:^8.0'`

PHPUnit is not a direct dependency of this project but gets pulled in via `codeception/phpunit-wrapper`, but the affected Class is used directly in this code base, so I'm not sure where/how this should be solved. Is `codeception/phpunit-wrapper` the place where a fix for such differences between PHPUnit versions can/should be implemented?

**Comment by simonhammes** [comment]
> Also affected by this. The problem seems to be the major release 9.0 of https://github.com/sebastianbergmann/php-code-coverage changing the mentioned constructor signature. So a more specific workaround (keeping phpunit 9) for now would be
> 
> `composer require --dev 'phpunit/php-code-coverage:^8.0'`

Thank you very much!   
I have created a PR: https://github.com/Codeception/phpunit-wrapper/pull/81

**Comment by jirehnimes** [comment]
Hi guys, encountered the same issue. I can't execute the workaround of installing `phpunit/php-code-coverage:^8.0`.

```
Problem 1
    - Conclusion: don't install phpunit/php-code-coverage 8.0.2
    - Conclusion: don't install phpunit/php-code-coverage 8.0.1
    - phpunit/phpunit 9.3.7 requires phpunit/php-code-coverage ^9.1.1 -> satisfiable by phpunit/php-code-coverage[9.1.x-dev].
    - phpunit/phpunit 9.3.7 requires phpunit/php-code-coverage ^9.1.1 -> satisfiable by phpunit/php-code-coverage[9.1.x-dev].
    - phpunit/phpunit 9.3.7 requires phpunit/php-code-coverage ^9.1.1 -> satisfiable by phpunit/php-code-coverage[9.1.x-dev].
    - Can only install one of: phpunit/php-code-coverage[9.1.x-dev, 8.0.0].
    - Can only install one of: phpunit/php-code-coverage[8.0.0, 9.1.x-dev].
    - Can only install one of: phpunit/php-code-coverage[8.0.0, 9.1.x-dev].
    - Installation request for phpunit/php-code-coverage ^8.0 -> satisfiable by phpunit/php-code-coverage[8.0.0, 8.0.1, 8.0.2].
    - Installation request for phpunit/phpunit (locked at 9.3.7, required as ^9.3) -> satisfiable by phpunit/phpunit[9.3.7].
```

Here's a part of my composer.json

```
    "require-dev": {
        "codeception/codeception": "^4.1",
        "codeception/module-asserts": "^1.2",
        "codeception/module-laravel5": "^1.1",
        "codeception/module-phpbrowser": "^1.0.0",
        "codeception/module-rest": "^1.2",
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/php-code-coverage": "9.1.x-dev",
        "phpunit/phpunit": "^9.3"
    },
```

**Comment by jirehnimes** [comment]
Able to fix it by removing all codeception related packages and installed "phpunit/phpunit:^8.0".

**Comment by Naktibalda** [comment]
@jirehnimes  You couldn't downgrade php-code-coverage because you had a locked version of phpunit which is incompatible with php-code-coverage 8.
An easier solution was to delete composer.lock file.

**Comment by jirehnimes** [comment]
@Naktibalda I actually deleted the lock file at first then installing downgrade of phpunit and php-code-coverage but still same error happens. I believe one of the codeception packages is blocking it or possibly did a mistake along the way. But now I'm able to run the code coverage after the steps I did.

**Comment by BrunoSpy** [comment]
As stated by @Naktibalda here https://github.com/Codeception/phpunit-wrapper/pull/81#issuecomment-679010557 : you need to remove the "phpunit/phpunit" line from your composer.json.

**Comment by jirehnimes** [comment]
@BrunoSpy I see. Thanks for this reference!

**Comment by Naktibalda** [comment]
There is a weird issue that new php-code-coverage generates Clover report which doesn't separate namespace from class name:  
Expected Result:
```xml
<class name="BillEvans" namespace="Jazz\Pianist">
```
Actual Result:
```xml
<class name="Jazz\Pianist\BillEvans" namespace="global">
```

I have no time to investigate it now, so I will patch the test to get it passing.

**Comment by Naktibalda** [comment]
Another pull request to make c3 library compatible with php-code-coverage 9: https://github.com/Codeception/c3/pull/59
