### ISSUE TITLE
Suggestion: Replace 'generate' with 'make' for code generation

### ISSUE THREAD

**Issue by TavoNiievez** [Codeception/Codeception#5951]
```diff
- vendor/bin/codecept generate:cest Functional ResetPasswordCest
+ vendor/bin/codecept make:cest Functional ResetPasswordCest
```
It's shorter and more comfortable, plus it means the same.

**Comment by DavertMik** [comment]
`make` is more laravel-style thing,
`generate` is more commonly used...

Current behavior is short enough, as you can use shortcut:

```
codecept g:cest
```

However, there should be one way of doing things and switching from one to another for no big reason can be problematic for the big project.

**Comment by TavoNiievez** [comment]
Thanks for your answer.
In fact, I was thinking of Symfony and its [MakerBundle](https://github.com/symfony/maker-bundle).
I didn't really know the shortcut 'g'. That fixes this issue!
Again, thank you very much. 👍
