### ISSUE TITLE
PHP Fatal error: The modifiers of the trait method assertInternalType() are changed, but this method does not exist

### ISSUE THREAD

**Issue by cougargit** [Codeception/Codeception#5958]
Codeception PHP Testing Framework v4.1.7
Powered by PHPUnit 9.3.8 by Sebastian Bergmann and contributors.
Running with seed: 

PHP Fatal error:  The modifiers of the trait method assertInternalType() are changed, but this method does not exist. Error in vendor/codeception/module-asserts/src/Codeception/Module/Asserts.php on line 11

**Comment by Naktibalda** [comment]
This issue was fixed by release of codeception/module-asserts 1.3.0, please upgrade.
