### ISSUE TITLE
PHP Fatal error:  The modifiers of the trait method assertInternalType() are changed, but this method does not exist. 

### ISSUE THREAD

**Issue by hadouke** [Codeception/Codeception#5959]
#### What are you trying to achieve?
Run tests suite 
#### What do you get instead?
Error on startup
> Provide console output if related. Use `-vvv` mode for more details.
PHP Fatal error:  The modifiers of the trait method assertInternalType() are changed, but this method does not exist. Error in ../vendor/codeception/module-asserts/src/Codeception/Module/Asserts.php on line 11

### Details

* Codeception version: v4.1.7
* PHP Version: 7.2
* Operating System: Linux
* Installation type:  Composer
```

**Comment by Naktibalda** [comment]
This issue was fixed by release of codeception/module-asserts 1.3.0, please upgrade.
