### ISSUE TITLE
Improve require-dev handling of codeception modules

### ISSUE THREAD

**Issue by simonberger** [Codeception/Codeception#5960]
I noticed a much higher amount of analyzed package versions (200 - 300k !) while testing composer.json. This is caused by 
```
"require": {
    "codeception/codeception": "*@dev"
}
```
in several codeception modules. I created [this issue in codeception-db](https://github.com/Codeception/module-db/issues/10). @Naktibalda correctly pointed me to the dev requirements of codeception as the reason for this strange requirement + conflict combination.
The reason for the much higher amount of versions going into consideration for the final versions are the many symfony (and more) requirements in the codeception releases 1 - 3.

I hope this situation can be improved for the many users requiring codeception and face a decreased composer performance.

The first idea I thought of uses a second composer.json (`COMPOSER=composer-dev.json composer install`) in the codeception project for the dev requirements. But after fixing the requirements in the codeception modules this most likely ends up in circular dependency again.

**Comment by Naktibalda** [comment]
Modules that are used in the tests of codeception/codeception must have version constraint of  "codeception/codeception" set to "*@dev" or codeception/codeception won't be able to install them in branch builds.

https://github.com/Codeception/Codeception/runs/1504318795?check_suite_focus=true

```
  Problem 1
    - codeception/module-cli[dev-master, 1.0.4, ..., 1.1.0] require codeception/codeception ^4.0 -> satisfiable by codeception/codeception[4.0.0, ..., 4.1.x-dev] from composer repo (https://repo.packagist.org) but codeception/codeception[dev-github-actions] from root package repo has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
    - codeception/module-cli[1.0.0, ..., 1.0.3] require php >=5.6.0 <8.0 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires codeception/module-cli *@dev -> satisfiable by codeception/module-cli[dev-master, 1.0.0, ..., 1.1.0].
```
