### ISSUE TITLE
How to list valid elements and locators for a page?

### ISSUE THREAD

**Issue by earljwagner** [Codeception/Codeception#5963]
#### What are you trying to achieve?

I'm using Codeception with WebDriver and PhantomJS to run an acceptance test for a Gravity Forms form in Wordpress.

I'm finding the locators to use for various fields by trial and error. It's especially challenging when fields appear on the page in response to actions and there's a delay.

Codeception provides support to save screenshots between steps.

Is there similar functionality to have Codeception print all of the valid fields and locators that are scriptable at any given step?

**Comment by Naktibalda** [comment]
No, Codeception does not provide such function.

This is frontend functionality, try using tools available in your browser https://stackoverflow.com/a/30381787/366348
