### ISSUE TITLE
PageObject methods

### ISSUE THREAD

**Issue by ijakparov** [Codeception/Codeception#5968]
I don't understand when I should use methods in pageobjects. Should they have $I->see() or not. I can write all methods in cest, why shoud do something in pageobject?

**Comment by reinholdfuereder** [comment]
Page objects are a broadly accepted and extremely recommended approach in order to have readable, understandable and especially also maintainable test code.

See:
* https://martinfowler.com/bliki/PageObject.html
* https://github.com/SeleniumHQ/selenium/wiki/PageObjects
