### ISSUE TITLE
Document installation of hoa/console

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5971]
On `$I->pause();` in an acceptance test, I'm getting:
> [Exception] Hoa Console is not installed. Please add `hoa/console` to composer.json

Is this just some (private) problem with my installation, or is this error really the only "documentation" on how to install `hoa/console`?

https://codeception.com/changelog says for 3.0.1:
> Removed hoa/console dependency from codeception/base package.

So this means it's not installed by default anymore (why?) but the user has to install it manually?

So I'd say this needs to be explained at https://codeception.com/docs/02-GettingStarted#Interactive-Pause The best way is probably:
```bash
composer require-dev hoa/console
```
Right?

**Comment by Naktibalda** [comment]
`Hoa/console` is listed in `suggests` section of [composer.json](https://github.com/Codeception/Codeception/blob/4.1/composer.json#L47), but it is bundled with phar files.

**Comment by ThomasLandauer** [comment]
You mean, it is included if you download the `phar` version of Codeception? => I assumed this when writing https://github.com/Codeception/codeception.github.com/pull/329

**Comment by Naktibalda** [comment]
I merged https://github.com/Codeception/codeception.github.com/pull/329
