### ISSUE TITLE
Make new command 'codecept refresh'

### ISSUE THREAD

**Issue by ghost** [Codeception/Codeception#5972]
**Achievement:**
Get a command that runs `codecept clean` and then `codecept build`.
```
vendor/bin/codecept refresh
```
**Note:** this would be helpful when developing modules and extensions for Codeception since rebuilding `Actions` is a very common task.

**Comment by Naktibalda** [comment]
Very few people develop modules and extensions for Codeception.
It you run `codecept clean && codecept build` very often, create shell alias for that command.
