### ISSUE TITLE
Documentation: Best way to assert "static" pages (like e.g. robots.txt)

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5973]
What's the best way to assert "static" pages/assets - stuff like `robots.txt` or `favicon.ico` or `sitemap.xml`?

I'm doing it this way in an acceptance test with REST module enabled:
```php
public function tryRobotsTxt(AcceptanceTester $I)
{
    $I->sendGET('/robots.txt');
    $I->seeResponseCodeIs(200);
    $I->seeHttpHeader('Content-Type', 'text/plain');
    $I->seeResponseContains('http://www.robotstxt.org/');
    $I->seeResponseContains('Sitemap:');
    $I->seeResponseContains('User-agent: *');
}
```
Rationale: Since we're talking to robots/spiders, meta data like response code or HTTP headers might be more important than on "regular" pages?

* Is this the best way or do you have other ideas?
* Since this is a special case, it would be nice to document it. Maybe another heading at the bottom of https://codeception.com/docs/03-AcceptanceTests ?

**Comment by Naktibalda** [comment]
I don't see anything special about testing responses of static files.
