### ISSUE TITLE
Difference between sendPOST, sendAjaxPostRequest, submitForm

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5977]
#### What are you trying to achieve?

I'm trying to use `sendPOST()` or `sendAjaxPostRequest()` in a functional test to submit a Symfony form. But I can't get Symfony's `$form->isSubmitted()` to kick in; i.e. the controller behaves as if the form wasn't submitted.  
When I use the same data array with `submitForm()`, it works fine.

Aren't those 3 methods supposed to all do the same? The submitted content (HTTP body) looks identical to me. Maybe I'm missing some detail? Any hints maybe?

### Details

* Codeception version: codeception/codeception 4.1.7

**Comment by Naktibalda** [comment]
It would be better to ask Symfony people about Form isSubmitted method.

**Comment by ThomasLandauer** [comment]
I found it :-)
The equivalent to ...
```php
$I->submitForm(['css'=>'form[name="form"]'], [
    'form[task]' => '',
]);
```
...is not (as I thought):
```php
$I->sendPOST('/test-form', [
    'form[task]' => '',
]);
```
... but rather:
```php
$I->sendPOST('/test-form', [ // or $I->sendAjaxPostRequest(...
    ['form' => [
        'form[task]' => '',
    ]
]);
```
I'd like to document this at (e.g.) https://codeception.com/docs/modules/Symfony#sendAjaxPostRequest
So in which cases is the (there mentioned) way...
```php
$I->sendAjaxPostRequest('/updateSettings', array('notifications' => true));
```
the right thing to do, and in which cases "my" way (with the additional array wrapped around it)?

And how can you check the full request (i.e. HTTP headers and body) that Codeception actually sends to the framework?

**Comment by Naktibalda** [comment]
So your problem was that parameters didn't match field names of the form.

Run Codeception with `-vv` or `-vvv` parameter to see what requests it is
making.

**Comment by Naktibalda** [comment]
Another thing to look at is generated HTML of the form, what do the field names look like in the form?

**Comment by ThomasLandauer** [comment]
This is my HTML:
```html
<input type="text" id="form_task" name="form[task]" required="required" novalidate="novalidate" class="form-control">
```
So in my mind, my first attempt from above should work - don't you think?:
```php
$I->sendPOST('/test-form', [
    'form[task]' => '',
]);
```

This is what `-vv` gives me for `submitForm()`:
```
 I submit form {"css":"form[name="form"]"},{"form[task]":""}
  [Uri] http://localhost/test-form
  [Method] POST
  [Parameters] {"form[task]":""}
  [Request Headers] []
  [Page] http://localhost/test-form
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"cache-control":["max-age=0, must-revalidate, private"],"date":["Fri, 18 Sep 2020 06:57:45 GMT"],"content-type":["text/html; charset=UTF-8"],"x-debug-token":["a11e12"],"x-robots-tag":["noindex"],"expires":["Fri, 18 Sep 2020 06:57:46 GMT"]}
  [User] anon. []
```
... for `sendAjaxPostRequest()`:
```
I send ajax post request "/test-form",{"form[task]":""}
  [Request Headers] []
  [Page] /test-form
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"cache-control":["max-age=0, must-revalidate, private"],"date":["Fri, 18 Sep 2020 06:59:07 GMT"],"content-type":["text/html; charset=UTF-8"],"x-debug-token":["f5aebb"],"x-robots-tag":["noindex"],"expires":["Fri, 18 Sep 2020 06:59:07 GMT"]}
  [User] anon. []
```
... and for `sendPOST()`:
```
I send post "/test-form",{"form[task]":""}
  [Request] POST /test-form {"form[task]":""}
  [Request Headers] []
  [Page] /test-form
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"cache-control":["max-age=0, must-revalidate, private"],"date":["Fri, 18 Sep 2020 06:59:54 GMT"],"content-type":["text/html; charset=UTF-8"],"x-debug-token":["75b6f0"],"x-robots-tag":["noindex"],"expires":["Fri, 18 Sep 2020 06:59:54 GMT"]}
  [User] anon. []
  [Response] <form name="form" method="post">
  <div class="form-group"><label for="form_task" class="required">Task</label><input type="text" id="form_task" name="form[task]" required="required" class="form-control" /></div></form>
```
So in all three cases I cannot see the actual request body - looks like there is no way to get this (=>feature request?)

What is the additional "wrapping" array `['form' => [` actually doing behind the scenes?

**Comment by Naktibalda** [comment]
The difference between PhpBrowser and Symfony module is that Symfony module doesn't make a real HTTP request, but assigns parameters to Symfony Request object: https://github.com/symfony/browser-kit/blob/v5.1.5/AbstractBrowser.php#L373

Parameters must look as if they were parsed by PHP already.
`form[task]` is parsed as an array, so the `form` in parameters must be an array:
```php
$I->sendPOST('/test-form', [
    'form' => [
        'task' => '',
    ]
]);
```

**Comment by Naktibalda** [comment]
Documentation pull request was merged.
