### ISSUE TITLE
`sendAjaxPostRequest` demands unnecessary `amOnPage`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5979]
When I start a functional test with
```php
$I->sendAjaxPostRequest(...);
```
...I'm getting the error message:
> [LogicException] The page history is empty.

So I'm forced to add a `$I->amOnPage($wherever);` before it. However, since `sendAjaxPostRequest()` gets an url as argument, it doesn't make any difference whatever I put into `amOnPage()`. So I'm suggesting to remove this requirement.

**Comment by Naktibalda** [comment]
I think that the idea was that `sendAjax` methods simulate what the browser does after the page is loaded.
If you want to make requests without loading the page, use REST module instead.
