### ISSUE TITLE
Show test results after graceful stop of tests execution

### ISSUE THREAD

**Issue by cebe** [Codeception/Codeception#5996]
#### What are you trying to achieve?

Since  #1286  it is possible to stop test execution by hitting Ctrl+C on a running test suite.
However, the test result summary is not going to be displayed for the tests that have already finished.

So for a long running test suite the time waited for the suite to finish is wasted because the result is lost.

Would be great to have available results shown in this case (not sure if that is possible though).

**Comment by Naktibalda** [comment]
According to https://github.com/Codeception/Codeception/issues/3607 graceful termination does not work with PHP 7.

**Comment by Naktibalda** [comment]
Ah, it is working again since PHP 7.1 and https://github.com/Codeception/Codeception/pull/3907

**Comment by Naktibalda** [comment]
@cebe What result are you looking for?
I got this output after terminating test execution:

> ✔ GenerateTestTest: Valid php (0.06s)
> E GeneratePageObjectTest: Create for suite with namespace (0.09s)
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> WARNING: Environments are not configured tests/data/claypit/tests/skipped/NoEnvironmentCept.php
> 
> 
> Time: 00:06.718, Memory: 18.00 MB
> 
> There was 1 error:
> 
> ---------
> 1) GeneratePageObjectTest: Create for suite with namespace
>  Test  tests/unit/Codeception/Command/GeneratePageObjectTest.php:testCreateForSuiteWithNamespace
> 
>   [RuntimeException]
> 
> ---------------------------
> TESTS EXECUTION TERMINATED
> ---------------------------
> 
> 
> #1  /c/Projects/codeception-v4/tests/unit/Codeception/Command/BaseCommandRunner.php:93
> #2  /c/Projects/codeception-v4/tests/unit/Codeception/Command/GeneratePageObjectTest.php:61
> #3  /c/Projects/codeception-v4/app.php:46
> #4  /c/Projects/codeception-v4/app.php:47
> #5  /c/Projects/codeception-v4/codecept:7
> 
> ERRORS!
> Tests: 61, Assertions: 131, Errors: 1, Skipped: 3.
> run with `-v` to get more info about skipped or incomplete tests
> 


`Tests: 61, Assertions: 131, Errors: 1, Skipped: 3.` is the test result summary, right?

pcntl extension is required for graceful termination.

**Comment by cebe** [comment]
Interesting, I did not see the error summary last time I tried. Could be related to `pcntl` extension, need to check that.

**Comment by cebe** [comment]
Unable to reproduce the issue :man_shrugging:
