### ISSUE TITLE
Multiple namespaces in suite

### ISSUE THREAD

**Issue by stdex** [Codeception/Codeception#6001]
Is any way to create multiple namespaces inside one suite?

File structure like this:

```
tests
├── api
│   ├── v1
│   └── v2
```

Namespaces:
Tests\api\v1
Tests\api\v2

And run it like:
vendor\bin\codecept run api
vendor\bin\codecept run api/v2

**Comment by Naktibalda** [comment]
You can run tests from any directory by path - `codecept run tests/api/v2`
