### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by scottynorris** [Codeception/Codeception#6006]
#### What are you trying to achieve?

**Use populator with db module.** 

I'm very confused now, because **where is the database running**? On some server created within mysqli on terminal, on the selenium server at port 4444 or my original MAMP server on 8889?

I have installed mysql using homebrew and created a user with all privileges called root _(which matches user on my MAMP db because I don't know what's talking to what anymore)._

Any assistance will be greatly appreciated. It seems I'm able to log into the db but there's some privileges problem. Is this supposed to be in the  .yml populator config somehow?

#### What do you get instead?

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Administrators-MacBook-Pro:fragrantmandarin.com administrator$ php vendor/bin/codecept run acceptance --steps --debug
Codeception PHP Testing Framework v4.1.8
Powered by PHPUnit 9.4.2 by Sebastian Bergmann and contributors.
Running with seed: 


  [Connecting To Db] {"config":{"populate":true,"cleanup":true,"reconnect":false,"waitlock":0,"dump":"tests/_data/dump.sql","populator":"mysql -u $user -h $host $dbname < $dump","dsn":"mysql:host=127.0.0.1;port=8889;dbname=xustfimb_fm","user":"root","password":"<secret>"},"options":[]}
  [Db] Connected to default xustfimb_fm
  [Db] Executing Populator: `mysql -u root -h 127.0.0.1 xustfimb_fm < tests/_data/dump.sql`
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

In DbPopulator.php line 108:
                                                    
  [RuntimeException]                                
  The populator command did not end successfully:   
    Exit code: 1                                    
    Output:                                         
                                                    

Exception trace:
  at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/module-db/src/Codeception/Lib/DbPopulator.php:108
 Codeception\Lib\DbPopulator->runCommand() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/module-db/src/Codeception/Lib/DbPopulator.php:95
 Codeception\Lib\DbPopulator->run() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/module-db/src/Codeception/Module/Db.php:688
 Codeception\Module\Db->loadDumpUsingPopulator() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/module-db/src/Codeception/Module/Db.php:679
 Codeception\Module\Db->_loadDump() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/module-db/src/Codeception/Module/Db.php:297
 Codeception\Module\Db->populateDatabases() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/module-db/src/Codeception/Module/Db.php:449
 Codeception\Module\Db->_beforeSuite() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:38
 Codeception\Subscriber\Module->beforeSuite() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/symfony/event-dispatcher/EventDispatcher.php:230
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/symfony/event-dispatcher/EventDispatcher.php:59
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/src/Codeception/Event/DispatcherWrapper.php:22
 Codeception\SuiteManager->dispatch() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/src/Codeception/SuiteManager.php:159
 Codeception\SuiteManager->run() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/src/Codeception/Codecept.php:208
 Codeception\Codecept->runSuite() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/src/Codeception/Codecept.php:162
 Codeception\Codecept->run() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/src/Codeception/Command/Run.php:511
 Codeception\Command\Run->runSuites() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/src/Codeception/Command/Run.php:405
 Codeception\Command\Run->execute() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/symfony/console/Application.php:920
 Symfony\Component\Console\Application->doRunCommand() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/symfony/console/Application.php:266
 Symfony\Component\Console\Application->doRun() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/symfony/console/Application.php:142
 Symfony\Component\Console\Application->run() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/src/Codeception/Application.php:117
 Codeception\Application->run() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/app.php:46
 {closure}() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/app.php:47
 require() at /Applications/MAMP/htdocs/fragrantmandarin.com/vendor/codeception/codeception/codecept:7

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]




COMMAND DID NOT FINISH PROPERLY.
  [Db] Disconnected from default

```
> Provide test source code if related

```php
// Not necessary
```
### Details

Codeception version: 4.1.8

PHP Version: 7.4.5

Operating System: Mac os Catalina 10.15.7

Installation type: Phar || Composer

List of installed packages (composer show)

Suite configuration:
behat/gherkin                      v4.6.2    Gherkin DSL parser for PHP 5.3
codeception/codeception            4.1.8     BDD-style testing framework
codeception/lib-asserts            1.13.1    Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser       1.3.3     Parent library for all Codeception framework modules and PhpBrowser
codeception/module-asserts         1.3.0     Codeception module containing various assertions
codeception/module-db              1.0.1     WebDriver module for Codeception
codeception/module-phpbrowser      1.0.1     Codeception module for testing web application over HTTP
codeception/module-webdriver       1.1.2     WebDriver module for Codeception
codeception/phpunit-wrapper        9.0.5     PHPUnit classes used by Codeception
codeception/stub                   3.7.0     Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.3.1     A small, lightweight utility to instantiate objects in PHP without in...
ezsql/ezsql                        4.0.10    Advance database access library. Make interacting with a database rid...
guzzlehttp/guzzle                  7.2.0     Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.4.0     Guzzle promises library
guzzlehttp/psr7                    1.7.0     PSR-7 message implementation that also provides common utility methods
league/oauth2-client               2.5.0     OAuth 2.0 Client Library
league/oauth2-google               3.0.2     Google OAuth 2.0 Client Provider for The PHP League OAuth2-Client
myclabs/deep-copy                  1.10.1    Create deep copies (clones) of your objects
nikic/php-parser                   v4.10.2   A PHP parser written in PHP
paragonie/random_compat            v9.99.100 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                   2.0.1     Component for reading phar.io manifest information from a PHP Archive...
phar-io/version                    3.0.2     Library for handling version information and constraints
php-webdriver/webdriver            1.8.3     A PHP client for Selenium WebDriver. Previously facebook/webdriver.
phpdocumentor/reflection-common    2.2.0     Common reflection classes used by phpdocumentor to reflect the code s...
phpdocumentor/reflection-docblock  5.2.2     With this component, a library can provide support for annotations vi...
phpdocumentor/type-resolver        1.4.0     A PSR-5 based resolver of Class names, Types and Structural Element N...
phpmailer/phpmailer                v6.1.8    PHPMailer is a full-featured email creation and transfer class for PHP
phpspec/prophecy                   1.12.1    Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          9.2.0     Library that provides collection, processing, and rendering functiona...
phpunit/php-file-iterator          3.0.5     FilterIterator implementation that filters files based on a list of s...
phpunit/php-invoker                3.1.1     Invoke callables with a timeout
phpunit/php-text-template          2.0.3     Simple template engine.
phpunit/php-timer                  5.0.2     Utility class for timing
phpunit/phpunit                    9.4.2     The PHP Unit Testing framework.
psr/container                      1.0.0     Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0     Standard interfaces for event handling.
psr/http-client                    1.0.1     Common interface for HTTP clients
psr/http-message                   1.0.1     Common interface for HTTP messages
ralouphie/getallheaders            3.0.3     A polyfill for getallheaders.
sebastian/cli-parser               1.0.1     Library for parsing CLI options
sebastian/code-unit                1.0.7     Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3     Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.5     Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.1     Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.3     Diff implementation
sebastian/environment              5.1.3     Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.3     Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.1     Snapshotting of global state
sebastian/lines-of-code            1.0.1     Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.3     Traverses array structures and object graphs to enumerate all referen...
sebastian/object-reflector         2.0.3     Allows reflection of object attributes, including inherited and non-p...
sebastian/recursion-context        4.0.3     Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3     Provides a list of PHP built-in functions that operate on resources
sebastian/type                     2.3.0     Collection of value objects that represent the types of the PHP type ...
sebastian/version                  3.0.2     Library that helps with managing the version number of Git-hosted PHP...
stripe/stripe-php                  v7.61.0   Stripe PHP Library
symfony/browser-kit                v5.1.7    Symfony BrowserKit Component
symfony/console                    v5.1.7    Symfony Console Component
symfony/css-selector               v5.1.7    Symfony CssSelector Component
symfony/deprecation-contracts      v2.2.0    A generic function and convention to trigger deprecation notices
symfony/dom-crawler                v5.1.7    Symfony DomCrawler Component
symfony/event-dispatcher           v5.1.7    Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v2.2.0    Generic abstractions related to dispatching event
symfony/finder                     v5.1.7    Symfony Finder Component
symfony/polyfill-ctype             v1.18.1   Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.18.1   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer   v1.18.1   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.18.1   Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.18.1   Symfony polyfill backporting some PHP 7.3+ features to lower PHP vers...
symfony/polyfill-php80             v1.18.1   Symfony polyfill backporting some PHP 8.0+ features to lower PHP vers...
symfony/process                    v5.1.7    Symfony Process Component
symfony/service-contracts          v2.2.0    Generic abstractions related to writing services
symfony/string                     v5.1.7    Symfony String component
symfony/yaml                       v5.1.7    Symfony Yaml Component
theseer/tokenizer                  1.2.0     A small library for converting tokenized PHP source code into XML and...
twbs/bootstrap                     v4.5.3    The most popular front-end framework for developing responsive, mobil...
webmozart/assert                   1.9.1     Assertions to validate method input/output with nice error messages.

```yml
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: 'http://localhost:8888'
            browser: chrome
        - \Helper\Acceptance
        - Db:
            dsn: 'mysql:host=127.0.0.1;port=8889;dbname=xustfimb_fm'
            user: 'root'
            password: '<secret>'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            populator: 'mysql -u $user -h $host $dbname < $dump'

extensions:
    enabled:
        - Codeception\Extension\RunProcess:
            - chromedriver

step_decorators: ~       
```

**Comment by DavertMik** [comment]
Sorry, we don't know where your database is running :( 
Please try to execute command `mysql -u $user -h $host $dbname < $dump'` manually in console (passing in required parameters) and check why it not works. Maybe MySQL is on the wrong port. Anyway, it is not related to Codeception itself
