### ISSUE TITLE
Codeception : Javascript Error : missing ) after argument list on WebDriver : Chrome Driver

### ISSUE THREAD

**Issue by nasirzawar** [Codeception/Codeception#6012]
I want to make custom method of executeJS and added code in helper class:
Helper Class Function : Acceptance

    public function fillInDynamicField($selector , $value)
           {
               $webDriver = $this->getModule('WebDriver');
               return $webDriver->executeJS('$(' . $selector . ').val(' . $value . ')');
           }

Cest File : 
        
    $I->fillInDynamicField('\'input[name*="stock"]\'' , "Testing Automation RV 2");

When I run this it gives an error missing ) after argument list.

 Test  tests\acceptance\addinventoryproductionCest.php:AddInventory2

  [Facebook\WebDriver\Exception\JavascriptErrorException] javascript error: missing ) after argument list
  (Session info: chrome=86.0.4240.111)

Need a solution. Waiting for reply. Thanks in advance.

* Codeception version:
* PHP Version: Latest
* Operating System: Windows 10
* Installation type: Phar

**Comment by Naktibalda** [comment]
The problem with your code was that you added escaped quotes around selector, but missed them around value,
so generated Javascript looked like this:
```js
$('input[name*="stock"]').val(Testing Automation RV 2)
```
