### ISSUE TITLE
Could someone point me in the right direction?

### ISSUE THREAD

**Issue by Raghu-Kanchiraju** [Codeception/Codeception#6013]
#### What are you trying to achieve?
I am trying to write some unit tests for my Phalcon-PHP 7.4 project using Codeception.

#### What do you get instead?
I am stuck with 'Class not found' errors and I am not getting anywhere.

> Provide console output if related. Use `-vvv` mode for more details.

```
Codeception PHP Testing Framework v4.1.9
Powered by PHPUnit 9.4.2 by Sebastian Bergmann and contributors.
Running with seed:


Unit Tests (1) -------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Phalcon4, Asserts, \Helper\Unit
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
E LocationTest: Some feature (0.05s)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 00:00.554, Memory: 10.00 MB

There was 1 error:

---------
1) LocationTest: Some feature
 Test  tests/unit/LocationTest.php:testSomeFeature

  [Error] Class 'XxModel' not found

#1  /data/XXX/api/app/Models/CstCustomerLocation.php:3
#2  /data/XXX/vendor/composer/ClassLoader.php:444
#3  /data/XXX/vendor/composer/ClassLoader.php:322
#4  Composer\Autoload\ClassLoader->loadClass
#5  /data/XXX/tests/unit/LocationTest.php:25

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```
> Provide test source code if related

```php
namespace XX\Tests\Unit;

// require_once "api/vendor/autoload.php";

class LocationTest extends \Codeception\Test\Unit
{
    /**
     * @var \UnitTester
     */
    protected $tester;
    
    protected function _before()
    {
    }

    protected function _after()
    {
    }

    // tests
    public function testSomeFeature()
    {
        // require_once __DIR__ . '/../../api/app/Models/XxModel.php';
        $cst = new \XX\Models\XXXLocation();
    }
}
```
### Details

* Codeception version: 4.1.9
* PHP Version: 7.4.10
* Operating System: Debian GNU/Linux 10 (buster)
* Installation type: Composer

**Comment by Fenikkusu** [comment]
Are you using `\Phalcon\Loader` to autoload your classes? If so, you'll likely want to make sure that your loader is in it's own file (IE: `phalcon_loader.php`) and then have your codeception bootstrap or in the `files` section of `composer.json`. While a bit outdated, you can look at https://gitlab.com/twistersfury/phalcon-template for an example.

**Comment by Raghu-Kanchiraju** [comment]
> Are you using `\Phalcon\Loader` to autoload your classes? If so, you'll likely want to make sure that your loader is in it's own file (IE: `phalcon_loader.php`) and then have your codeception bootstrap or in the `files` section of `composer.json`. While a bit outdated, you can look at https://gitlab.com/twistersfury/phalcon-template for an example.

Thanks for the reply @Fenikkusu.
Just as soon as I posted this issue, I was able to figure out the problem and I resolved it. Turns out the class that I am trying to use does not belong to any namespace (code is at least 5 years old). So I modified the code and voila! It worked. Thank you once again for trying to help.
