### ISSUE TITLE
Environment variables does not loaded properly when Dotenv v5 installed

### ISSUE THREAD

**Issue by retnek** [Codeception/Codeception#6014]
Hey,

I've experienced a Dotenv incompatibility issue with Dotenv v5. If you use the latest dotenv (5.2.0) with the latest codeception (4.1.9) your config variables (like %SOMETHING%) will not be translated. 
In Dotenv v5 environment variables are not automatically attached into $_SERVER.
in ParamsLoader.php 119:
```php
$repository = \Dotenv\Repository\RepositoryBuilder::createWithNoAdapters()
    ->addAdapter(\Dotenv\Repository\Adapter\EnvConstAdapter::class)
    ->make();
$dotEnv = \Dotenv\Dotenv::create($repository, codecept_root_dir(), $this->paramStorage);
...
$dotEnv->load();
return $_SERVER;
```
After $dotEnv->load(); $_SERVER has same content as before. In order to achieve this we have to add ServerConstAdapter as well:
```php
$repository = \Dotenv\Repository\RepositoryBuilder::createWithNoAdapters()
    ->addAdapter(\Dotenv\Repository\Adapter\EnvConstAdapter::class)
    ->addAdapter(\Dotenv\Repository\Adapter\ServerConstAdapter::class)
    ->make();
```

Cheers!

**Comment by Naktibalda** [comment]
Please raise pull request.

**Comment by 4selin** [comment]
+1

PR #6015 works for me

thank you @retnek
