### ISSUE TITLE
Idea: Create a Roadmap for Codeception (any version)

### ISSUE THREAD

**Issue by TavoNiievez** [Codeception/Codeception#6020]
What i am proposing is to simply enable the Projects tab, [as is done in CodeceptJS](https://github.com/codeceptjs/CodeceptJS/projects/7).
A simple and updated way to know:

- If it is confirmed that an issue will be worked on.
- What priority has the issue.
- What is the status of that issue/PR. Maybe `Planned` or `In Progress`, or `Ready to Launch`.

This of course accompanied by the corresponding milestone tags.

It would be good to know what things the team will give priority to implement in the present or future, and i think it may be better than opening an individual issue, as [was done here](https://github.com/Codeception/Codeception/issues/3976).

**Comment by Naktibalda** [comment]
There is no team, no plans and no roadmap.

**Comment by TavoNiievez** [comment]
I'm sorry
