### ISSUE TITLE
Flow/JsonPath is abandoned in favour of  softcreatr/jsonpath

### ISSUE THREAD

**Issue by Ravetracer** [Codeception/Codeception#6021]
As the title mentions, when using jsonpath, the mentioned package is abandoned in favour of softcreatr/jsonpath.

Follow up of this change is that the new package deprecates the call to `data()` in favour of `getData()`.

Here's the output of the test suite.

```bash
1461x DEPRECATION: Calling JSONPath::data() is deprecated, please use JSONPath::getData() instead. /application/vendor/softcreatr/jsonpath/src/JSONPath.php:190
```

Usage is in 
codeception/module-rest/src/Codeception/Util/JsonArray.php:90

Namespaces hasn't changed.

### Details

* Codeception version: 4.1.9
* PHP Version: 7.4
* PHPUnit: 9.4.2

**Comment by TavoNiievez** [comment]
See https://github.com/Codeception/module-rest/issues/24

**Comment by ThomasLandauer** [comment]
@Ravetracer The package dependency has been updated in https://github.com/Codeception/module-rest/pull/35. Is the deprecation (`data()`) still there? If yes, please change the title of this issue accordingly, so it doesn't get lost. Or open a new issue at https://github.com/Codeception/module-rest/issues

**Comment by Ravetracer** [comment]
Thank you. 
I'll close this issue and will open a new one in the respective module repository because the warning still rises with the updated libs.
