### ISSUE TITLE
wait() in new WebDriver module waits 1000 times more

### ISSUE THREAD

**Issue by artyfarty** [Codeception/Codeception#603]
subj.
Selenium2 `wait()`s milliseconds. WebDriver waits seconds.

same for `wairForJs`

**Comment by bologer** [comment]
@DavertMik is it possible to make `wait()`  for longer then `1000` seconds? I would like to be able to wait for an hour or so.

**Comment by Naktibalda** [comment]
It is just usleep() - make your own helper function.

**Comment by bologer** [comment]
@Naktibalda thanks, I will try that
