### ISSUE TITLE
Is it possible to call `_reconfigure()` from *within* a test?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6033]
Is there a way to get this example at https://codeception.com/docs/06-ModulesAndHelpers#Runtime-Configuration working from *within* a test:
```php
$this->getModule('PhpBrowser')->_reconfigure(array('url' => 'http://localhost/admin'));
```
i.e. something like `$I->...`?

**Comment by Naktibalda** [comment]
If you want to change `url` setting, this is exactly what [amOnUrl](https://github.com/Codeception/module-phpbrowser/blob/1.0.2/src/Codeception/Module/PhpBrowser.php#L156-L168) does.
If you want to change another parameter, then you have to implement your own helper method.
