### ISSUE TITLE
Is it possible to get the browser name (WebDriver) or the environment name from within a test?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6035]
In an acceptance test with WebDriver, I'd like to get the name of the browser or the [environment](https://codeception.com/docs/07-AdvancedUsage#Environments) - is this possible?

**Comment by Naktibalda** [comment]
Browser name is [stored in metadata](https://github.com/Codeception/module-webdriver/blob/1.1.4/src/Codeception/Module/WebDriver.php#L455), so you can use
```php
$scenario->getMetadata()->getCurrent('browser');
```

You can get a list of current environments using 
```php
$scenario->getMetadata()->getEnv();
```

**Comment by ThomasLandauer** [comment]
OK, great!

I'm thinking about ways to make this more obvious for users.
1. The right syntax is `$scenario->current('browser')` , see https://codeception.com/docs/07-AdvancedUsage#Current-values - right?
2. Would it have any downsides to *always* inject `\Codeception\Scenario $scenario`? I mean, in (auto-)generated Cest files, examples, etc.
3. `codecept_debug($scenario->current('browser'));` leads to memory overflow, so it looks like `codecept_debug()` is not compatible with it. Is this a bug or intended behavior?

**Comment by Naktibalda** [comment]
1. Yes.
2. It is one of those cases when only 1 out of 1000 needs it but you want to enforce it on everyone.
3. Please do some basic debugging and check what you get back.

**Comment by Naktibalda** [comment]
Ah, do you even set browser parameter in suite configuration?
It is required by Selenium, but probably unnecessary when chromedriver or geckodriver is used directly.

**Comment by ThomasLandauer** [comment]
2. I wouldn't call it "enforce" but rather say it gives users the chance to discover what this is about ;-) But I guess we all agree that this is mainly useful in WebDriver  - so I added it there in https://github.com/Codeception/module-webdriver/pull/37 to improve discoverability.

3. Don't know what you mean. Yes, I have a `browser` set in `acceptance.suite.yml`. What I mean: If there's a chance to "fix" this, I'll open an issue. If not, I'll add a short note to https://codeception.com/docs/07-AdvancedUsage#Current-values that the entire `$scenario` thing is not working with `codecept_debug()`.
Just tried `codecept_debug($scenario->current('modules'));` in a functional test, and I'm getting:

> In Output.php line 68:
  [Symfony\Component\ErrorHandler\Error\OutOfMemoryError]                                       
  Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 803213312 bytes)

**Comment by Naktibalda** [comment]
> That the entire $scenario thing is not working with codecept_debug().

This is wrong, it certainly works with codecept_debug.
I tested `codecept_debug($scenario->current('modules'));` in Codeception unit suite and it produced less than 16 kilobytes of text.
`codecept_debug($scenario->current(null));` produced less than 18k
and `codecept_debug($scenario);` produced 24 megabytes of output.

Probably you have some memory consuming module enabled, or print_r on your machine tries to print recursion.

**Comment by ThomasLandauer** [comment]
@Naktibalda Hm. With this in a **functional** test:
```php
public function tryScenario(FunctionalTester $I, \Codeception\Scenario $scenario)
{
    codecept_debug($scenario->current('modules'));
}
```
...I'm still getting the same as above:
> In Output.php line 68:                                                                                                
  [Symfony\Component\ErrorHandler\Error\OutOfMemoryError]                                       
  Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 803213312 bytes)

I tried to check in a **unit** test, as you say, but couldn't even figure out how to inject the `Scenario`. This is not working - what's the right way to do it? (=> should be mentioned at https://codeception.com/docs/07-AdvancedUsage#Get-Scenario-Metadata)
```php
public function testScenario(\UnitTester $I, \Codeception\Scenario $scenario)
{
    codecept_debug($scenario->current('modules'));
}
```

**Comment by Naktibalda** [comment]
Most likely because you have Symfony module enabled.
