### ISSUE TITLE
Can I see JavaScript errors in Webdriver?

### ISSUE THREAD

**Issue by Luc45** [Codeception/Codeception#6037]
#### What are you trying to achieve?

I want to see JavaScript errors when running webdriver tests.

#### What do you get instead?

Tests are failing on an AJAX request, and I can't see JavaScript errors. I can't open the DevTools Console tab in CI, and I can't read the JavaScript errors to assert they are empty from the test itself.

**Comment by Naktibalda** [comment]
No, you can't.

Duplicate of https://github.com/Codeception/module-webdriver/issues/25

**Comment by Luc45** [comment]
Thanks @Naktibalda :+1:

**Comment by kaliberx** [comment]
@Luc45 did you try this? ```$jsErrors = $I->executeJS('return window.jsErrors');```

**Comment by SOHELAHMED7** [comment]
@kaliberx 

Thanks. That helped.

Though I would like to add that more precise way would be:

```js
window.jsErrors = []; 
window.onerror = function(message, source, lineno, colno, error) { window.jsErrors.push(message); };
```
