### ISSUE TITLE
Some REST module methods should be in InnerBrowser (?) (and some are missing)

### ISSUE THREAD

**Issue by TavoNiievez** [Codeception/Codeception#6038]
While writing https://github.com/Codeception/module-symfony/pull/45 ,
I noticed that for some functions, including `seeEmailIsSent`, you need to stop the redirects:
 

> If your app performs a redirect after sending the email, you need to suppress this using REST Module's [stopFollowingRedirects](https://codeception.com/docs/modules/REST#stopFollowingRedirects) [[SF Module](https://github.com/Codeception/module-symfony/blob/b65b2c709c8d3474e5f820909d7d7679e147de7a/src/Codeception/Module/Symfony.php#L520)]

So...

#### 1. Why are these functions specific to the REST module?:
```php
    public function stopFollowingRedirects()
    {
        $this->client->followRedirects(false);
    }

    public function startFollowingRedirects()
    {
        $this->client->followRedirects(true);
    }
```

#### 2. These two simple call functions are duplicated in both modules...?:

- setServerParameters() [[InnerBrowser](https://github.com/Codeception/lib-innerbrowser/blob/fd921e089147057b456ca3660de72112167e40a4/src/Codeception/Lib/InnerBrowser.php#L2047)] [[REST](https://github.com/Codeception/module-rest/blob/beeb5a91a97d042273bf10f00063e9b8f541879a/src/Codeception/Module/REST.php#L1617)]
- haveServerParameter() [[InnerBrowser](https://github.com/Codeception/lib-innerbrowser/blob/fd921e089147057b456ca3660de72112167e40a4/src/Codeception/Lib/InnerBrowser.php#L2061)] [[REST](https://github.com/Codeception/module-rest/blob/beeb5a91a97d042273bf10f00063e9b8f541879a/src/Codeception/Module/REST.php#L1629)]

#### 3. There is a `public` method in AbstractBrowser, but in InnerBrowser it is `private`...?

- getCrawler() [[AbstractBrowser](https://github.com/symfony/browser-kit/blob/2bfe32e6d61bb2ce98fa478702ffb2b92dafff29/AbstractBrowser.php#L207)] [[InnerBrowser](https://github.com/Codeception/lib-innerbrowser/blob/fd921e089147057b456ca3660de72112167e40a4/src/Codeception/Lib/InnerBrowser.php#L290)]

And, there are some methods from the public API of AbstractBrowser that are simply 'missing':

- followMetaRefresh()
- **followRedirect()**
- **foward()**
- getCookieJar()
- getHistory()
- getMaxRedirects()
- getRequest()
- getResponse()
- getServerParameter()
- insulate()
- isFollowingRedirects()
- **reload()**
- **restart()**
- **setMaxRedirects()**

<details>
<summary>I would like to make special mention to <b>followRedirect(). Clic to see.</b></summary>

<br/>
Codeception has functions to stop the next redirect 'stopFollowingRedirects()', or re-enable the next redirect 'startFollowingRedirects()'. <br/><br/>But, if i use 'stopFollowingRedirects' to stop the redirect, i don't have available the function that allows me to fire the redirect after executing my assertions. <br/><br/>'startFollowingRedirects' simply re-enables the next redirect that <b>might occur</b>, but <b>does not execute the pending one</b>. This function is performed by 'followRedirect'
<hr/>
</details>

<details>
<summary>And a special mention to <b>forward(). Clic to see.</b></summary>

<br/>
Codeception offers a method to go to the previous page 'moveBack()'... <br/><br/>But then it is not possible for me to go forward in the history.
<hr/>
</details>

With some it could be argued that, although they are `public` in AbstractBrowser, their use is intended to be 'internal', like...

- getInternalRequest()
- getInternalResponse()

#### 4. ...But except for those, how to identify them? Which ones are `really missing` and **which ones can be contributed**?

Lastly, there's this duplicated method...

- getRunningClient() [[REST](https://github.com/Codeception/module-rest/blob/beeb5a91a97d042273bf10f00063e9b8f541879a/src/Codeception/Module/REST.php#L162)] [[InnerBrowser](https://github.com/Codeception/lib-innerbrowser/blob/fd921e089147057b456ca3660de72112167e40a4/src/Codeception/Lib/InnerBrowser.php#L298)]

#### 5. It is `private` in InnerBrowser, but `protected` in the REST Module, is there any inheritance intent for this?

Thanks in advance.

**Comment by Naktibalda** [comment]
1. Probably because somebody wanted this functionality in REST module. Look at Blame.
2. Let me guess. Somebody decided 3 years later, that another name is more appropriate.
3. I don't remember any intention to expose methods of AbstractBrowser.
4. So none of them are missing.

**Comment by TavoNiievez** [comment]
> 2. Let me guess. Somebody decided 3 years later, that another name is more appropriate.

It is exactly the same name and code, but i got your point.


> 4. So none of them are missing.

So how do i use `->followRedirect()` to execute pending redirects in my tests?
```php
	$I->amOnPage('/register');
	$I->stopFollowingRedirects();
	$I->submitForm('form=name[register_form]', [
		'register_form[email]' => 'john_doe@gmail.com',
		'register_form[password]' => '123456'
	]);
	$I->seeEmailIsSent(1);
	// I can't make the following assertions because i stopped the redirect.
	$I->expect('to be redirected to the login page');
	$I->seeResponseCodeIsSuccessful();
	$I->seeCurrentUrlEquals('/login');
	$I->see('Login');
```
`->startFollowingRedirects()` just enable the next redirect that may occur.

**Comment by Naktibalda** [comment]
Well, nobody asked for that until now.

followRedirects doesn't make much sense in context of REST module and I wasn't aware that somebody is using stopRedirects for Symfony email assertions.

**Comment by Naktibalda** [comment]
I wrote that start/stop FollowingRedirects should be in InnerBrowser 5 years ago: https://github.com/Codeception/Codeception/pull/2598#issuecomment-163905864

**Comment by DavertMik** [comment]
> 1. Why are these functions specific to the REST module?:

For PhpBrowser and Frameworks module I don't assume that someone needs to stop redirects. That's why. In REST you may have more control over requests.

Yeah, I'm also not so sure that this is the huge issue we should discuss. But if you know a better idea on how to restructurize the code , I'm open to it.

**Comment by TavoNiievez** [comment]
The easiest way would be to make `getRunningClient()` `public` in InnerBrowser or REST, which would allow anyone to execute the non-wrapper methods that they need...

The other solution would involve moving methods between modules and creating wrappers for any of the methods mentioned in item 3. At the moment adding followRedirect() and moveFoward() would be enough to close this issue.
