### ISSUE TITLE
Use of undefined constant XDEBUG_CC_UNUSED

### ISSUE THREAD

**Issue by NeilJ247** [Codeception/Codeception#6040]
#### What are you trying to achieve?

Run tests in codeception using code coverage

#### What do you get instead?

The following error is being produced since yesterday:

```bash
In ErrorHandler.php line 83:
                                                                               
  Use of undefined constant XDEBUG_CC_UNUSED - assumed 'XDEBUG_CC_UNUSED' (this will throw an Error in a future version of PHP)                                                                                                        
```

Not 100% sure why this is all of a sudden failing as there are no changes to xdebug and travis builds have been passing this week.  This is the docker image being used https://hub.docker.com/layers/php/library/php/7.4-fpm-alpine/images/sha256-c3b668772e5a3557921e368a7f2ec57ff6c5441af49ed8e562bdb4781a2b7ff2?context=explore

### Details

* Codeception version: 4.1.12
* PHP Version: 7.4 (Docker alpine latest image - 7.4)
* Operating System: Alpine
* Installation type: Composer

**Comment by Naktibalda** [comment]
Any chance that you upgraded to Xdebug 3?

**Comment by NeilJ247** [comment]
Not intentionally unless the 7.4 image has but I dont see it since the last update was 22 days ago

**Comment by NeilJ247** [comment]
I think pecl might be installing v3 by default

```
yes | pecl install xdebug
```

**Comment by NeilJ247** [comment]
Yup that is the issue:

```
bash-5.0# pecl list | grep xdebug
xdebug  3.0.0   stable
```

**Comment by cyrusssschen** [comment]
@NeilJ247 Got the same issue. Did we fix this?

**Comment by rvuong** [comment]
Hi,

Same to me. Can't figure out how to downgrade xdebug. I'm using the PHP-FPM:7.2 Docker image on which I install xdebug with PECL:

Here's the Dockerfile:
```
FROM php:7.2-fpm

# Various installs
# ...

# Install Xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug
# RUN pecl install xdebug-3.0 && docker-php-ext-enable xdebug

# ...
```

```
# php -v
PHP 7.2.31 (cli) (built: Jun  9 2020 15:23:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v3.0.0, Copyright (c) 2002-2020, by Derick Rethans
```

When I run PHPUnit (Symfony 5.2 PHPUnit Bridge), I've got the same error:
```
# ./vendor/bin/simple-phpunit -c phpunit.xml.dist 
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

Testing Project Test Suite
Use of undefined constant XDEBUG_CC_UNUSED - assumed 'XDEBUG_CC_UNUSED' (this will throw an Error in a future version of PHP)
```

Any help would be welcome

**Comment by rvuong** [comment]
And I had to add the following to the `phpunit.xml`:
```
    <php>
        ...
        <env name="XDEBUG_MODE" value="coverage"/>
    </php>
```

**Comment by NeilJ247** [comment]
> @NeilJ247 Got the same issue. Did we fix this?

No.  I tried to downgrade XDEBUG using pecl like @rvuong but couldn't get it to work.  So I upgraded dev packages in composer such as phpunit, codeception etc. and tried again.  But then I was presented with another error where it was trying to collecting code coverage.  I can't remember the exact error but it was something to do with an array instead of an object being passed.

**Comment by derekrprice** [comment]
I'm seeing this too, with php:7.4-fpm.  Pinning xdebug 2.9.8 via `pecl install xdebug-2.9.8` fixed it for me.

**Comment by Pictor13** [comment]
Another option is to use [a more specific docker tag](https://hub.docker.com/_/php?tab=tags&page=1&ordering=last_updated&name=7.4.12) to select the precise PHP version that is desired (the `7.4.12`; XDebug 3 comes from the `7.4.13`).

This should prevent your code to break, as long as you are not ready to upgrade *php* and *xdebug*.

Or, yes, specifying the version (`xdebug-2.9.8`) to Pecl allows to reinstall the desired version in your own project Dockerfile.
