### ISSUE TITLE
Submitt button for register doesn't react in laravel system (auth)

### ISSUE THREAD

**Issue by comprog-ux** [Codeception/Codeception#6068]
We have taking over a laravel system where the original programmer aren't available anymore.
Like to have register user to function but no response.

Nothing happends except that it feels the click as normal, changes color a little and lowers a millimeter.
Part of register.blade.php:

                           <div class="form-group">
                                <div class="col-sm-12">
                                    <div style="margin: 0 auto; width: 304px;">
                                        <div ng-model="auth.recaptcharesponse" vc-recaptcha key="'{{_(env('RECAPTCHA_PUBLIC_KEY'))}}'"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary" ng-click="register();">
                                        <i class="fa fa-btn fa-user margin-right-5"></i>{{_('Register')}}
                                    </button>
                                </div>
                            </div>
                            <div class="form-group margin-top-20">
                                <div class="col-md-12 text-center">
                                    <a ui-sref="auth.login">{{_('Already menber, login instead')}} &raquo;</a>
                                </div>
                            </div>
                   

Where to look and for what? Regards, Ralph in Sweden

### Details

* Codeception version: Laravel 8
* PHP Version: 7.4
* Operating System: Ubuntu
* Installation type: Phar || Composer-laravel
* List of installed packages (`composer show`) :+1: 
barryvdh/laravel-cors                 v0.8.2  Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
classpreloader/classpreloader         3.1.0   Helps class loading performance by generating a single PHP file containing all of the autoloaded files for a...
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base directory specification for php
doctrine/annotations                  v1.3.1  Docblock Annotations Parser
doctrine/cache                        v1.6.1  Caching library offering an object-oriented API for many cache backends
doctrine/collections                  v1.3.0  Collections Abstraction library
doctrine/common                       v2.6.2  Common Library for Doctrine projects
doctrine/dbal                         v2.5.5  Database Abstraction Layer
doctrine/inflector                    v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
firebase/php-jwt                      v4.0.0  A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
fzaninotto/faker                      v1.6.0  Faker is a PHP library that generates fake data for you.
garetjax/phpbrowscap                  2.0     Standalone replacement for php's native get_browser() function
guzzlehttp/guzzle                     6.2.2   Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1  Guzzle promises library
guzzlehttp/psr7                       1.3.1   PSR-7 message implementation
hamcrest/hamcrest-php                 v1.2.2  This is the PHP port of Hamcrest Matchers
hisorange/browser-detect              2.0.2   Browser & Mobile detection package for Laravel 4-5.
hisorange/traits                      1.0.0   Useful PHP traits.
jakub-onderka/php-console-color       0.1    
jakub-onderka/php-console-highlighter v0.3.2 
jenssegers/optimus                    v0.2.2  Id obfuscation based on Knuth's integer hash method
jeremeamia/SuperClosure               2.3.0   Serialize Closure objects, including their context and binding
laravel/framework                     v5.3.28 The Laravel Framework.
laravel/passport                      v1.0.17 Laravel Passport provides OAuth2 server support to Laravel.
lcobucci/jwt                          3.2.1   A simple library to work with JSON Web Token and JSON Web Signature
league/event                          2.1.2   Event package
league/flysystem                      1.0.32  Filesystem abstraction: Many filesystems, one API.
league/oauth2-server                  5.1.3   A lightweight and powerful OAuth 2.0 authorization and resource server library with support for all the core...
maatwebsite/excel                     2.1.24  An eloquent way of importing and exporting Excel and CSV in Laravel 4 with the power of PHPExcel
mobiledetect/mobiledetectlib          2.8.24  Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-Agent string combine...
mockery/mockery                       0.9.7   Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or ...
monolog/monolog                       1.22.0  Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.1.0  CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
myclabs/deep-copy                     1.5.5   Create deep copies (clones) of your objects
nesbot/carbon                         1.21.0  A simple API extension for DateTime.
nikic/php-parser                      v3.0.2  A PHP parser written in PHP
paragonie/random_compat               v2.0.4  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pda/pheanstalk                        v3.1.0  PHP client for beanstalkd queue
phpdocumentor/reflection-common       1.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.1   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve infor...
phpdocumentor/type-resolver           0.2.1  
phpoffice/phpexcel                    1.8.1   PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpseclib/phpseclib                   2.0.4   PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpspec/prophecy                      v1.6.2  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             4.0.4   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.8   Utility class for timing
phpunit/php-token-stream              1.4.9   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.7.5   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.4.3   Mock Object library for PHPUnit
psr/http-message                      1.0.1   Common interface for HTTP messages
psr/log                               1.0.2   Common interface for logging libraries
psy/psysh                             v0.8.0  An interactive shell for modern PHP.
ramsey/uuid                           3.5.2   Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique ...
sebastian/code-unit-reverse-lookup    1.0.0   Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.2   Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.1   Diff implementation
sebastian/environment                 2.0.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    2.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1   Snapshotting of global state
sebastian/object-enumerator           2.0.0   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           2.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
sentry/sentry                         1.6.1   A PHP client for Sentry (http://getsentry.com)
sentry/sentry-laravel                 0.5.0   Laravel integration for Sentry (https://sentry.io)
stripe/stripe-php                     v4.3.0  Stripe PHP Library
swiftmailer/swiftmailer               v5.4.5  Swiftmailer, free feature-rich PHP mailer
symfony/console                       v3.1.8  Symfony Console Component
symfony/css-selector                  v3.1.8  Symfony CssSelector Component
symfony/debug                         v3.1.8  Symfony Debug Component
symfony/dom-crawler                   v3.1.8  Symfony DomCrawler Component
symfony/event-dispatcher              v3.2.1  Symfony EventDispatcher Component
symfony/finder                        v3.1.8  Symfony Finder Component
symfony/http-foundation               v3.1.8  Symfony HttpFoundation Component
symfony/http-kernel                   v3.1.8  Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.3.0  Symfony utilities for portability of PHP codes
symfony/process                       v3.1.8  Symfony Process Component
symfony/psr-http-message-bridge       v1.0.0  PSR HTTP message bridge
symfony/routing                       v3.1.8  Symfony Routing Component
symfony/translation                   v3.1.8  Symfony Translation Component
symfony/var-dumper                    v3.1.8  Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.2.1  Symfony Yaml Component
tecnickcom/tcpdf                      6.2.12  TCPDF is a PHP class for generating PDF documents and barcodes.
tijsverkoyen/css-to-inline-styles     2.2.1   CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline ...
vlucas/phpdotenv                      v2.4.0  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.2.0   Assertions to validate method input/output with nice error messages.
xinax/laravel-gettext                 4.0.4   Adds localization support to laravel applications in an easy way using Poedit and GNU gettext.
zendframework/zend-diactoros          1.3.7   PSR HTTP Message implementations

* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
Not enough information here.
It looks like you are reporting behaviour of the browser, so I guess that you are using WebDriver module, is that right?
This is a frontend issue, so it probably is irrelevant that you are using Laravel in backend.

Please provide your test code and relevant part of generated HTML code, not the template.

**Comment by eXorus** [comment]
I'm closing this issue, feel free to reopen if needed.
