### ISSUE TITLE
Class "PHP_Token_NAME_QUALIFIED" not found in phar

### ISSUE THREAD

**Issue by zdenekgebauer** [Codeception/Codeception#6074]
#### What are you trying to achieve?
run tests with code coverage on PHP8 
```
c:\bin\php8\php.exe build/codecept.phar run unit --html report-coverage.html --coverage-html
```

#### What do you get instead?
PHP Fatal error:  Uncaught Error: Class "PHP_Token_NAME_QUALIFIED" not found in phar:..... build/codecept.phar/vendor/phpunit/php-token-stream/src/Token/Stream.php:182

### Details

* Codeception version: 4.1.3
* PHP Version: 8.0
* Operating System: Windows, Linux
* Installation type: Phar

Maybe problem with incompatible version of  phpunit?

**Comment by Naktibalda** [comment]
4.1.3 was released last March, download the latest phar file from https://codeception.com/codecept.phar  and try again.

**Comment by zdenekgebauer** [comment]
I'm sorry for typo, I tested latest codecept.phar 4.1.13

**Comment by Naktibalda** [comment]
The phar file is buit for PHP 7.2, so bundled version of PHPUnit does not receive much love.
The error happens in abandoned library https://github.com/sebastianbergmann/php-token-stream

It would be much better to install codeception using composer and get the latest versions of all dependencies.
