### ISSUE TITLE
PHP `const` not working in Interactive Pause

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6086]
When doing this in the Interactive Pause:
```php
seeElement(self::FOO);
```
... I'm getting:

> syntax error Undefined class constant 'FOO'

My `const` is defined in the very Cest file, and it happens no matter if it's `private` or `public`.

If this is a known limitation of the Pause, I'll mention it at https://codeception.com/docs/02-GettingStarted#Interactive-Pause near

> Inside Interactive Pause you can use the entire power of the PHP interpreter: variables, functions, etc.

**Comment by Naktibalda** [comment]
This issue will be fixed in 5.0.0
