### ISSUE TITLE
Website: Union types are being rendered as table in parameters list

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6104]
Example: https://codeception.com/docs/modules/Symfony#grabParameter

The docblock at https://github.com/Codeception/module-symfony/blob/master/src/Codeception/Module/Symfony/ParameterAssertionsTrait.php#L20 says `@return mixed|null`, and this is being rendered as a table on the page:

| return mixed | null |
| -- | -- |

**Comment by burned42** [comment]
I created https://github.com/Codeception/util-robohelpers/pull/2 which should resolve this issue :)
