### ISSUE TITLE
Depreciation notices on a fresh install

### ISSUE THREAD

**Issue by TerjeBr** [Codeception/Codeception#6109]
I have just installed codeception on a fresh php 5 project, and I get these depreciation warnings:
```
  1x: The "Codeception\PHPUnit\Listener" class implements "PHPUnit\Framework\TestListener" that is deprecated Use the `TestHook` interfaces instead.
    1x in Application::run from Codeception

  1x: The "PHPUnit\TextUI\ResultPrinter" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "Codeception\PHPUnit\ResultPrinter\UI".
    1x in Application::run from Codeception

  1x: The "PHPUnit\Runner\BaseTestRunner" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "Codeception\PHPUnit\NonFinal\TestRunner".
    1x in Application::run from Codeception

  1x: The "PHPUnit\Framework\TestSuite" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "Codeception\Suite".
    1x in Application::run from Codeception
```

**Comment by Naktibalda** [comment]
We have no choice but to use these classes that are now declared internal, until someone comes up with a way to drop dependency on PHPUnit.
This message means that PHPunit is permitted to break interfaces in minor versions.

PHPUnit\Framework\TestListener was deprecated in [PHPUnit 9](https://github.com/sebastianbergmann/phpunit/blob/9.5/src/Framework/TestListener.php), but it is no longer deprecated in [PHPUnit 10](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestListener.php). Last time I checked listeners worked with PHPUnit 10. We will fix them when they stop working.
