### ISSUE TITLE
Misleading naming scheme for `haveInDatabase`. Suggestion!

### ISSUE THREAD

**Issue by rene-hermenau** [Codeception/Codeception#6114]
`haveInDatabase()` is described as 

**Inserts an SQL record into a database. This record will be erased after the test.**

The name `insertInDatabase()` would be much more clearer.
Any chance to refactor that method name and deprecate the old one?

All other names reflect better what the method does like `updateInDatabase()` 

So, what's the reason for that misleading name?

**Comment by Naktibalda** [comment]
Duplicate of #4268
