### ISSUE TITLE
 Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by zdenekgebauer** [Codeception/Codeception#6122]
#### What are you trying to achieve?
Run acceptance test with Webdriver (selenium)

#### What do you get instead?
PHP Fatal error:  Uncaught Error: Call to undefined method ReflectionUnionType::getName() in ..... vendor\codeception\codeception\src\Codeception\Lib\Generator\Actions.php:228
 
### Details
* Codeception version: 4.1.18
* PHP Version: 8.0
* Operating System: Windows
* Installation type: Composer

**Comment by Naktibalda** [comment]
It seems that you have some helper method with union return type - `public function foo(): int|float`

If you want a quick fix, remove that return type.

**Comment by zdenekgebauer** [comment]
Thank you, it is solved.

**Comment by Naktibalda** [comment]
It must be fixed properly.
