### ISSUE TITLE
Using strtotime inside data providers

### ISSUE THREAD

**Issue by uaoleg** [Codeception/Codeception#6134]
#### What are you trying to achieve?
I'm using @dataProvider method and returning values based on `strtotime()`, e.g. `strtotime('-1 minute')` 
I'm expecting to get -1 minute from the moment when the test case was executed

#### What do you get instead?

I'm getting -1 minute from the moment when the first test (not even from this file) was executed

```php
    protected function dataProviderMissedCalls(): array
    {
        return [

            // Missed calls less than 5 minutes and more than 1 day ago
            [
                'missedCallsCount' => 0,
                'totalCallsCount' => 2,
                'calls' => [
                    [
                        'userPhonetExt' => '1',
                        'timeDial'      => strtotime('-1 minutes'),
                        'timeBridge'    => null,
                        'timeHangup'    => strtotime('-1 minutes'),
                    ],
                    [
                        'userPhonetExt' => '2',
                        'timeDial'      => strtotime('-2 days'),
                        'timeBridge'    => null,
                        'timeHangup'    => strtotime('-2 days'),
                    ],
                ],
            ],
        ];
    }

```
### Details

* Codeception version: 2.5.6
* PHP Version: 7.3
* Operating System: Windows
* Installation type: Composer

**Comment by Naktibalda** [comment]
That's right, data providers are executed when the list of tests to be executed is prepared.
This is not a bug.

**Comment by uaoleg** [comment]
@Naktibalda now I see, thank you. Could you suggest what is the common practice for such a case? In data provider return a string `'timeDial' => '-1 minutes'` and convert it to timestamp inside a test?
