### ISSUE TITLE
Codeception is not compatible with php 7.0 anymore in 4.1.19...

### ISSUE THREAD

**Issue by ArtemGoutsoul** [Codeception/Codeception#6153]
#### What are you trying to achieve?
Run codeception on php7.0

#### What do you get instead?
```bash
  Codeception PHP Testing Framework v4.1.19
  Powered by PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
  PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in ......./codeception/_support/_generated/AcceptanceTesterActions.php on line 24
  Process exited with code 255
```

### Details

* Codeception version: 4.1.19
* PHP Version: 7.0.33
* Operating System: Linux (Docker container)
* Installation type: Composer

Regression possibly caused by https://github.com/Codeception/Codeception/commit/853f6944653e2adcfebfe208760b83d57e93db74

Would be good to bump the major or at least minor version, if such a serious change is made such as dropping whole php version compatibility. Backward compatibility drop in 4.1.18 -> 4.1.19 was a surprise.

**Comment by Naktibalda** [comment]
Thanks for report.

Fixed in 4.1.20
