### ISSUE TITLE
Mocks give "must be an instance of" error when using type hinting

### ISSUE THREAD

**Issue by bigtunacan** [Codeception/Codeception#6160]
#### What are you trying to achieve?

Create Stub object and run assertion on function that accepts stub object as param

I'm trying to use mocks in my test suite, but I'm also introducing type hinting to functions.  When passing a mock or stub object as a parameter to a function with type hinting PHP raises a TypeError.

```php
public static function isValid(App\Models\EntryModel $model)
```

#### What do you get instead?

> Argument 1 passed to App\Helpers\EntryValidator::isValid() must be an instance of App\Helpers\App\Models\EntryModel, instance of Mock_EntryModel_1c319aaf given

#### Test source code

```php
$fwa = Stub::make('App\Models\EntryModel', ['NAME' => 'bigtunacan'], $this);
$this->assertTrue(\App\Helpers\EntryValidator::isValid($fwa));
```
### Details

* Codeception version: 4.1.20
* PHP Version: 7.2
* Operating System: MacOS
* Installation type: Composer

**Comment by Naktibalda** [comment]
It looks like you have a simple namespace resolution issue.

Your helper has `namespace App\Helpers` at the top of the file, but you use relative class name in the typehint so they get concatenated.

Try to change the signature to `public static function isValid(\App\Models\EntryModel $model)`  - you need a leading backslash there.

Alternatively you can add `use App\Models\EntryModel;` at the top and change signature to `public static function isValid(EntryModel $model)`.

**Comment by bigtunacan** [comment]
Thank you!
