### ISSUE TITLE
Incorrect documentation for WordPress: local env file is ignored

### ISSUE THREAD

**Issue by Germain-Italic** [Codeception/Codeception#6166]
Following steps straight from https://codeception.com/for/wordpress does not work.

Fortunately I found this comment which helped me solve the issue: https://github.com/lucatume/wp-browser/issues/466#issuecomment-716500785

The tutorial should be updated to reflect this fix.

**Comment by Naktibalda** [comment]
That page was removed today by https://github.com/Codeception/codeception.github.com/pull/483
It was replaced by redirect to https://github.com/lucatume/wp-browser
