### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method

### ISSUE THREAD

**Issue by Inexperience101** [Codeception/Codeception#6167]
Hi Just wondering if anyone has an idea how to resolve

Current Website not working after updating a plugin 
I cant quite figure out where the issue is or what to do - very little knowledge of webdeveloping/coding

The Issue seems to be with Cornerstone - have tried rollback but not working still as it needs newest version
Keep getting this message when I try to activate the plugin.

Fatal error: Uncaught Error: Call to undefined method ReflectionType::getName() in /home/physi238/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php:106 Stack trace: #0 [internal function]: Themeco\Cornerstone\Plugin->Themeco\Cornerstone\{closure}(Object(ReflectionParameter)) #1 /home/physi238/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php(117): array_map(Object(Closure), Array) #2 /home/physi238/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php(137): Themeco\Cornerstone\Plugin->create('\\Themeco\\Corner...') #3 /home/physi238/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php(73): Themeco\Cornerstone\Plugin->resolve('\\Themeco\\Corner...') #4 /home/physi238/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php(44): Themeco\Cornerstone\Plugin->setup_services('is_admin') #5 /home/physi238/public_html/wp-content/plugins/cornerstone/includes/boot.php(27): Themeco\Cornerstone\Plugin->initialize(Array) #6 /home/physi238/public in /home/physi238/public_html/wp-content/plugins/cornerstone/includes/classes/Plugin.php on line 106

I am using Wordpress with ThemeX 
It has also prompted a php update but when I click it it says to ignore - is this causing the issue.

Any help in right direction would be great

**Comment by Naktibalda** [comment]
Do you run it on PHP 5 or PHP 7.0?
ReflectionType::getName method was implemented in PHP 7.1.0 - https://www.php.net/manual/en/class.reflectionnamedtype.php

P.S. Asking offtopic questions in unrelated Github repository is a bad practice.
