### ISSUE TITLE
Ability to merge code coverage reports from separated tests executions

### ISSUE THREAD

**Issue by xepozz** [Codeception/Codeception#6217]
#### What are you trying to achieve?

I want to see code coverage for any test suites.

For example, my CI configured like the following (it's abstract code):
```
codecept run unit --coverage-html={output dir}
docker-compose up -d database
docker-compose exec php ./bin/console migrations:up
codecept run functional --coverage-html={output dir}
php -S 127.0.0.1 public/index.php
codecept run acceptance --coverage-html={output dir}
```

After these commands I get only last report from `codecept run acceptance --coverage-html={output dir}`.
It sucks, because I losing previous reports.

I found https://github.com/sebastianbergmann/phpcov package that can merge php-like reports.
Can you support php-like reports to be able to use this package or make your own implementation for html, xml, text and other reports?

### Details

* Codeception version: 4.1.6
* PHP Version: 7.4
* Operating System: Linux
* Installation type: Composer
* List of installed packages (`composer show`): it's trade secret
* Suite configuration: any configuration

**Comment by Naktibalda** [comment]
phpcov uses code coverage reports in Clover format.
You can generate them by using `--coverage-xml` option.
