### ISSUE TITLE
[QUESTION] PHP8 support

### ISSUE THREAD

**Issue by neoacevedo** [Codeception/Codeception#6240]
Does Codeception will support for PHP8?

> codeception/codeception[2.2.3, ..., 2.4.1] require php >=5.4.0 <8.0 -> your php version (8.0.8) does not satisfy that requirement.

**Comment by DavertMik** [comment]
Hey, current version of Codeception is 4.1.21
Please update to latest Codeception for PHP 8 support

It's not that hard, we keep backwards compatibility and for 3.x to 4.x migration we prepared an upgrade script.

See https://codeception.com/04-24-2019/codeception-3.0.html
https://codeception.com/12-18-2019/codeception-4.html

**Comment by neoacevedo** [comment]
Ok thank you.
