### ISSUE TITLE
`humbug/phar-updater` is abandoned

### ISSUE THREAD

**Issue by TavoNiievez** [Codeception/Codeception#6247]
See https://github.com/humbug/phar-updater/issues/59 .

https://github.com/Codeception/Codeception/blob/3d76fcc7bd60219103d881ed4ada232144c6467c/src/Codeception/Command/SelfUpdate.php#L83-L106

Alternative: https://github.com/consolidation/self-update .

**Comment by Naktibalda** [comment]
I think it was already abandoned when we started using it.

**Comment by DavertMik** [comment]
Wow, consolidation is another organization I belong to :smile: 
Let's use that one, why not?

**Comment by Naktibalda** [comment]
> Let's use that one, why not?

It is too simplistic even when compared to humbug/phar-updater.

1. We would need a different build process, so it would only work for Codeception 5.
2. consolidation/self-update would tie phar builds to releases of codeception/codeception again.
3. consolidation/self-update takes the latest release in chronological order, maintenance release of Codeception 4 would break self-update for Codeception 5.
4. We would lose capability to provide different builds for different versions of PHP.

We can always fork humbug/phar-updater if we need to update it. It isn't much bigger than consolidation/self-update.

**Comment by Naktibalda** [comment]
Codeception 5 can use maintained fork https://github.com/laravel-zero/phar-updater

**Comment by TavoNiievez** [comment]
LGTM
