### ISSUE TITLE
No coverage report

### ISSUE THREAD

**Issue by psk88** [Codeception/Codeception#6248]
#### What are you trying to achieve?

Get code coverage and success after tests

#### What do you get instead?

I get Ok by tests, but don't see statistics coverage, empty artifacts, don't see error and gitlab job failed

#### Command run

```
 $ docker exec ${COMPOSE_PROJECT_NAME} vendor/bin/codecept run --coverage-xml --coverage-html
 Codeception PHP Testing Framework v4.1.20
 Powered by PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
```

#### Result

![codecept](https://user-images.githubusercontent.com/20301307/131619443-d44edddb-dfef-49b9-8378-574ac577c2c3.png)

 
### Details

* Codeception version: 4.1.20
* PHP Version: PHP 7.3.27
* Operating System: Debian GNU/Linux 10 (buster)
* Installation type: Composer
* List of installed packages (`composer show`)
behat/gherkin                            v4.8.0      Gherkin DSL parser for PHP
bower-asset/inputmask                    3.3.11     
bower-asset/jquery                       3.5.1      
bower-asset/punycode                     v1.3.2     
bower-asset/swagger-ui                   v3.48.0    
bower-asset/yii2-pjax                    2.0.7.1    
cebe/markdown                            1.2.1       A super fast, highly extensible markdown parser for PHP
clue/stream-filter                       v1.5.0      A simple and modern approach to stream filtering in PHP
codeception/c3                           2.6.4       CodeCoverage collector for Codeception
codeception/codeception                  4.1.22      BDD-style testing framework
codeception/lib-asserts                  1.13.2      Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser             1.5.0       Parent library for all Codeception framework modules and PhpBrowser
codeception/module-rest                  1.2.7       REST module for Codeception
codeception/module-yii2                  1.1.2       Codeception module for Yii2 framework
codeception/phpunit-wrapper              9.0.6       PHPUnit classes used by Codeception
codeception/stub                         3.7.0       Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/annotations                     1.13.2      Docblock Annotations Parser
doctrine/instantiator                    1.4.0       A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                           1.2.1       PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
ezyang/htmlpurifier                      v4.13.0     Standards compliant HTML filter written in PHP
genxoft/yii2-oas3                        v0.2-stable Yii2 Open Api Swagger 3 integration
guzzlehttp/promises                      1.4.1       Guzzle promises library
guzzlehttp/psr7                          1.8.2       PSR-7 message implementation that also provides common utility methods
http-interop/http-factory-guzzle         1.0.0       An HTTP Factory using Guzzle PSR7
jean85/pretty-package-versions           2.0.4       A library to get pretty versions strings of installed dependencies
justinrainbow/json-schema                5.2.11      A library to validate a json schema.
kotchuprik/yii2-odnoklassniki-authclient v1.2.4     
linslin/yii2-curl                        1.5.0       Easy and nice cURL extension with RESTful support for Yii2
macfly/pinpoint-plugin-core              0.0.0       Pinpoint core plugin component for PHP
myclabs/deep-copy                        1.10.2      Create deep copies (clones) of your objects
nikic/php-parser                         v4.12.0     A PHP parser written in PHP
notamedia/yii2-sentry                    1.7.0       Yii2 logger for Sentry
opis/closure                             3.5.5       A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
phar-io/manifest                         2.0.3       Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                          3.1.0       Library for handling version information and constraints
php-http/client-common                   2.3.0       Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                       1.14.0      Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                         2.2.0       HTTPlug, the HTTP client abstraction for PHP
php-http/message                         1.11.1      HTTP Message related tools
php-http/message-factory                 v1.0.2      Factory interfaces for PSR-7 HTTP Message
php-http/promise                         1.1.0       Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common          2.2.0       Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock        5.2.2       With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver              1.4.0       A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                         1.13.0      Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                9.2.6       Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                3.0.5       FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                      3.1.1       Invoke callables with a timeout
phpunit/php-text-template                2.0.4       Simple template engine.
phpunit/php-timer                        5.0.3       Utility class for timing
phpunit/phpunit                          9.5.9       The PHP Unit Testing framework.
pinpoint-apm/pinpoint-php-aop            v2.0.1      A simple Aop library via php-parse
psr/cache                                3.0.0       Common interface for caching libraries
psr/container                            1.1.1       Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                     1.0.0       Standard interfaces for event handling.
psr/http-client                          1.0.1       Common interface for HTTP clients
psr/http-factory                         1.0.1       Common interfaces for PSR-7 HTTP message factories
psr/http-message                         1.0.1       Common interface for HTTP messages
psr/log                                  1.1.4       Common interface for logging libraries
ralouphie/getallheaders                  3.0.3       A polyfill for getallheaders.
sebastian/cli-parser                     1.0.1       Library for parsing CLI options
sebastian/code-unit                      1.0.8       Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup       2.0.3       Looks up which function or method a line of code belongs to
sebastian/comparator                     4.0.6       Provides the functionality to compare PHP values for equality
sebastian/complexity                     2.0.2       Library for calculating the complexity of PHP code units
sebastian/diff                           4.0.4       Diff implementation
sebastian/environment                    5.1.3       Provides functionality to handle HHVM/PHP environments
sebastian/exporter                       4.0.3       Provides the functionality to export PHP variables for visualization
sebastian/global-state                   5.0.3       Snapshotting of global state
sebastian/lines-of-code                  1.0.3       Library for counting the lines of code in PHP source code
sebastian/object-enumerator              4.0.4       Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector               2.0.4       Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context              4.0.4       Provides functionality to recursively process PHP variables
sebastian/resource-operations            3.0.3       Provides a list of PHP built-in functions that operate on resources
sebastian/type                           2.3.4       Collection of value objects that represent the types of the PHP type system
sebastian/version                        3.0.2       Library that helps with managing the version number of Git-hosted PHP projects
sentry/sdk                               3.1.0       This is a metapackage shipping sentry/sentry with a recommended HTTP client.
sentry/sentry                            3.3.0       A PHP SDK for Sentry (http://sentry.io)
softcreatr/jsonpath                      0.7.2       JSONPath implementation for parsing, searching and flattening arrays
symfony/browser-kit                      v5.3.4      Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/console                          v5.3.7      Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                     v5.3.4      Converts CSS selectors to XPath expressions
symfony/deprecation-contracts            v2.4.0      A generic function and convention to trigger deprecation notices
symfony/dom-crawler                      v5.3.7      Eases DOM navigation for HTML and XML documents
symfony/event-dispatcher                 v5.3.7      Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts       v2.4.0      Generic abstractions related to dispatching event
symfony/finder                           v5.3.7      Finds files and directories via an intuitive fluent interface
symfony/http-client                      v5.3.7      Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts            v2.4.0      Generic abstractions related to HTTP clients
symfony/options-resolver                 v5.3.7      Provides an improved replacement for the array_replace PHP function
symfony/polyfill-ctype                   v1.23.0     Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme           v1.23.1     Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer         v1.23.0     Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                v1.23.1     Symfony polyfill for the Mbstring extension
symfony/polyfill-php73                   v1.23.0     Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                   v1.23.1     Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-uuid                    v1.23.0     Symfony polyfill for uuid functions
symfony/service-contracts                v2.4.0      Generic abstractions related to writing services
symfony/string                           v5.3.7      Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/yaml                             v5.3.6      Loads and dumps YAML files
theseer/tokenizer                        1.2.1       A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                         1.10.0      Assertions to validate method input/output with nice error messages.
yiisoft/yii2                             2.0.42.1    Yii PHP Framework Version 2
yiisoft/yii2-authclient                  2.1.8       External authentication via OAuth and OpenID for the Yii framework
yiisoft/yii2-composer                    2.0.10      The composer plugin for Yii extension installer
yiisoft/yii2-debug                       2.1.13      The debugger extension for the Yii framework
yiisoft/yii2-httpclient                  2.0.13      HTTP client extension for the Yii framework
zircote/swagger-php                      3.0.4       swagger-php - Generate interactive documentation for your RESTful API using phpdoc annotations

* Suite configuration:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed

settings:
    memory_limit: 1024M
    colors: true
    error_level: 'E_ALL'
    
bootstrap: _bootstrap.php
    
coverage:
    enabled: true
    low_limit: 50
    high_limit: 90
    include:
        - modules/*.php
    exclude:
        - modules/*/tests/*
    remote_context_options:
        ssl:
            verify_peer_name: false

suites:
    v1:
        actor: ApiTester
        path: ../modules/v1/tests
        modules:
            config:
                Yii2:
                    configFile: 'config/test_v1.php'
                    cleanup: false
            enabled:
                - REST:
                    url: /v1
                    depends: Yii2
                - \Helper\Api
                - \Helper\SmokeApi
    v2:
        actor: ApiTester
        path: ../modules/v2/tests
        modules:
            config:
                Yii2:
                    configFile: 'config/test_v2.php'
                    cleanup: false
            enabled:
                - REST:
                    url: /v2
                    depends: Yii2
                - \Helper\Api
                - \Helper\SmokeApi

```

**Comment by psk88** [comment]
Can be closed, not enough memory for container and docker killed process

**Comment by delboy1978uk** [comment]
@psk88 how could you tell that? and how would you fix it?
