### ISSUE TITLE
Cli suite does not work.

### ISSUE THREAD

**Issue by terabytesoftw** [Codeception/Codeception#6249]
#### What are you trying to achieve?
- Install Suite Cli.
- Steps:
- `composer require --dev codeception/module-cli`
- `vendor/bin/codecept generate:suite cli`
- `vendor/bin/codecept generate:cest cli Tests`
- `vendor/bin/codecept run cli`

#### What do you get instead?
```shell
1) testsCest: Tests php unit
 Test  tests\cli\testsCest.php:testsPhpUnit
  [RuntimeException] Call to undefined method Simple\App\Tests\CliTester::runShellCommand
```
```php
<?php

namespace Simple\App\Tests;

use Simple\App\Tests\CliTester;

class TestsCest
{
    public function testPhpUnit(CliTester $I): void
    {
        $I->runShellCommand('phpunit');
    }
}
```

**Comment by Naktibalda** [comment]
You must enable Cli module in tests/cli.suite.yml file as documented in [Getting Started](https://codeception.com/docs/02-GettingStarted#Actors) page.

```yaml
modules:
    enabled:
        - Cli
```

**Comment by terabytesoftw** [comment]
> You must enable Cli module in tests/cli.suite.yml file as documented in [Getting Started](https://codeception.com/docs/02-GettingStarted#Actors) page.
> 
> ```yaml
> modules:
>     enabled:
>         - Cli
> ```

yes, if I have the configuration file ready, i use namespace, i have also tried it without it and it does not work. 

```yml
actor: CliTester
modules:
    enabled:
        - \Simple\App\Tests\Helper\Cli
```

**Comment by Naktibalda** [comment]
Just add that ` - Cli` line.

**Comment by terabytesoftw** [comment]
Thks. 👍
