### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [Codeception/Codeception#6253]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Naktibalda** [comment]
We had no security issues until August and now we have second report.

Please contact me by email naktibalda@gmail.com

**Comment by JamieSlome** [comment]
@Naktibalda - also feel free to view the report directly [here](https://huntr.dev/bounties/03e33ea0-c699-493b-9ee5-a4861d726e6f/).

**Comment by Naktibalda** [comment]
I marked report as invalid

> Description
> 
> Insecure randomness errors occur when a function that can produce predictable values is used as a source of randomness in security-sensitive context. This code uses the rand() function to generate "unique" identifiers for the receipt pages it generates.
> 
> In this case the function that generates weak random numbers is rand() in [Run.php at line 306](https://github.com/Codeception/Codeception/blob/f0a5ba54594f61f1236702f1533554360f8a086e/src/Codeception/Command/Run.php#L306).

My response:

> Context is not security-sensitive, random number generator is used to randomize execution order of tests in test suite. https://github.com/Codeception/Codeception/blob/76ed7815922df2b958a5a8368acbb3532f7652eb/src/Codeception/SuiteManager.php#L102
