### ISSUE TITLE
Report tests time is another.

### ISSUE THREAD

**Issue by andrew-svirin** [Codeception/Codeception#6256]
When I run tests in console, I get executed time: Time: 00:07.014
![image](https://user-images.githubusercontent.com/16819743/134664991-683006f0-f47b-4007-ba3b-751cf916adf3.png)

But in xml report I get total time: 1.204731
![image](https://user-images.githubusercontent.com/16819743/134665013-37392721-0aa1-42a8-96fc-408b66c52357.png)

How in xml have spent time like in console ?

**Comment by Oldman1873** [comment]
![DuckDuckGo Logo- Dax Solo](https://user-images.githubusercontent.com/96936265/147847233-113218d3-c163-49ea-a815-f3465999ca2e.jpg)

**Comment by Naktibalda** [comment]
It is simply impossible to have total execution time in JUnit report file because there is no such feature in JUnit format.
