### ISSUE TITLE
Expose PHPUnit's --disable-coverage-ignore option

### ISSUE THREAD

**Issue by CJDennis** [Codeception/Codeception#6258]
I have a large codebase with a high number of used/unreachable lines. To remove them from the coverage report, I have used the `@codeCoverageIgnore*` annotations, which Codeception honours. However, after a code change, I'd like to be able to run a coverage report while not ignoring coverage to make sure that code is still not being executed in those blocks.

PHPUnit already has a `--disable-coverage-ignore` option. Please expose this functionality in Codeception and add it to the list of options under `codecept run --help`.

**Comment by Naktibalda** [comment]
New setting could be implemented in https://github.com/Codeception/Codeception/blob/5.0-test-runner/src/Codeception/Coverage/PhpCodeCoverageFactory.php (If the link stops working try [5.0 branch](https://github.com/Codeception/Codeception/blob/5.0/src/Codeception/Coverage/PhpCodeCoverageFactory.php)

PHPUnit 10 way for setting this option:
```
if ($this->configuration->disableCodeCoverageIgnore()) {
    CodeCoverage::instance()->disableAnnotationsForIgnoringCode();
} else {
    CodeCoverage::instance()->enableAnnotationsForIgnoringCode();
}
```

More settings can be found in https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/TestRunner.php
