### ISSUE TITLE
Add links to runner output that open the file directly in my IDE

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6259]
I started implementing what I suggested at https://github.com/Codeception/Codeception/discussions/6208 :

First step: The line https://github.com/Codeception/Codeception/blob/4.1/src/Codeception/Subscriber/Console.php#L360 needs to be replaced by something like:
```php
->append(codecept_absolute_path(Descriptor::getTestFileName($failedTest)))
```
My plan would be to define a new configuration parameter in `codeception.yml`, following phpstan's format (see https://phpstan.org/user-guide/output-format#opening-file-in-an-editor):
```yaml
editorUrl: 'phpstorm://open?file=%%file%%&line=%%line%%'
```
And if this parameter is present, replace the value of "Test" here:
```
1) FooCest: Try bar
 Test  tests/functional/FooCest.php:tryBar
 Step  See whatever
 Fail  Number of elements counted differs from expected range
Failed asserting that false is true.
```
...with the clickable link.

Questions:
1. How can I access a configuration parameter from there?
2. How can I access the failing line number? If that's not so easy, let's just omit it for now - a link to just the *file* is still better than nothing ;-)

**Comment by Naktibalda** [comment]
> 1. How can I access a configuration parameter from there?

You get all settings from `settings` section of codeception.yaml file in `$this->options`  when `codeception run` command is used.  `codecept dry-run` doesn't get them, so it is always necessary to check if `$this->options['editorUrl']` is set before using it.


> 2. How can I access the failing line number?

`$failEvent->getFail()` returns exception.
You can use `getFile` and `getLine` methods to find the origin place of exception, but it won't be in the test file.
You could iterate stack trace retuned by $failEvent->getFail()->getTrace ` and find the first row matching the name of test file.
