### ISSUE TITLE
sendPatch uses HTML query string request body instead of JSON

### ISSUE THREAD

**Issue by merrillh** [Codeception/Codeception#6260]
#### What are you trying to achieve?
send a PATCH request with a json body to an api route

        $I->sendPatch("/api/admins/$this->admin_id/employees/$this->emp_id", [
            "emp_id" =>  "$this->emp_id",
            "admin_id" => "$this->admin_id",
            "employee_group_hash" => [
                "in_person" => "false",
                "remote" => "true",
                "online" => "true",
            ]
        ]);

#### What do you get instead?
Request body is sent as an HTML query string

> Provide console output if related. Use `-vvv` mode for more details.
         [Response] php://input
         'emp_id=12345678&admin_id=11111111&employee_group_hash%5Bin_person%5D=false&employee_group_hash%5Bremote%5D=true&employee_group_hash%5Bonline%5D=true'

### Details

Need to have json set before sendPatch, otherwise it sends request body as a param string, even though the config should be set to JSON

        $I->haveHttpHeader('Content-Type', 'application/json');

         [Response] php://input
         '{"emp_id":"12345678","admin_id":"11111111","employee_group_hash":{"in_person":"false","remote":"true","online":"true"}}'

* Codeception version: 4.1
* PHP Version: 7.4.3
* Operating System: Windows 10 WSL 2
* Installation type: Composer
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - REST:
            url: http://app.test/
            depends: PhpBrowser
            part: Json
```

* List of installed packages (`composer show`)
behat/gherkin                      v4.8.0  Gherkin DSL parser for PHP
codeception/codeception            4.1.22  BDD-style testing framework
codeception/lib-asserts            1.13.2  Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser       1.5.1   Parent library for all Codeception framework modules and PhpBrowser
codeception/module-asserts         1.3.1   Codeception module containing various assertions
codeception/module-db              1.1.0   DB module for Codeception
codeception/module-phpbrowser      1.0.2   Codeception module for testing web application over HTTP
codeception/module-rest            1.3.1   REST module for Codeception
codeception/phpunit-wrapper        9.0.6   PHPUnit classes used by Codeception
codeception/stub                   3.7.0   Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.4.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
guzzlehttp/guzzle                  7.3.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.5.0   Guzzle promises library
guzzlehttp/psr7                    2.1.0   PSR-7 message implementation that also provides common utility methods
justinrainbow/json-schema          5.2.11  A library to validate a json schema.
myclabs/deep-copy                  1.10.2  Create deep copies (clones) of your objects
nikic/php-parser                   v4.13.0 A PHP parser written in PHP
phar-io/manifest                   2.0.3   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    3.1.0   Library for handling version information and constraints
phpdocumentor/reflection-common    2.2.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  5.2.2   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        1.5.1   A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                   1.14.0  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          9.2.7   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          3.0.5   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.1   Invoke callables with a timeout
phpunit/php-text-template          2.0.4   Simple template engine.
phpunit/php-timer                  5.0.3   Utility class for timing
phpunit/phpunit                    9.5.10  The PHP Unit Testing framework.
psr/container                      1.1.1   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0   Standard interfaces for event handling.
psr/http-client                    1.0.1   Common interface for HTTP clients
psr/http-factory                   1.0.1   Common interfaces for PSR-7 HTTP message factories
psr/http-message                   1.0.1   Common interface for HTTP messages
ralouphie/getallheaders            3.0.3   A polyfill for getallheaders.
sebastian/cli-parser               1.0.1   Library for parsing CLI options
sebastian/code-unit                1.0.8   Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3   Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.6   Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.2   Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.4   Diff implementation
sebastian/environment              5.1.3   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.3   Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.3   Snapshotting of global state
sebastian/lines-of-code            1.0.3   Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.4   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.4   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.4   Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3   Provides a list of PHP built-in functions that operate on resources
sebastian/type                     2.3.4   Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.2   Library that helps with managing the version number of Git-hosted PHP projects
softcreatr/jsonpath                0.7.5   JSONPath implementation for parsing, searching and flattening arrays
symfony/browser-kit                v5.3.4  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/console                    v5.3.7  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.3.4  Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      v2.4.0  A generic function and convention to trigger deprecation notices
symfony/dom-crawler                v5.3.7  Eases DOM navigation for HTML and XML documents
symfony/event-dispatcher           v5.3.7  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.4.0  Generic abstractions related to dispatching event
symfony/finder                     v5.3.7  Finds files and directories via an intuitive fluent interface
symfony/polyfill-ctype             v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.23.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer   v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/service-contracts          v2.4.0  Generic abstractions related to writing services
symfony/string                     v5.3.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/yaml                       v5.3.6  Loads and dumps YAML files
theseer/tokenizer                  1.2.1   A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.10.0  Assertions to validate method input/output with nice error messages.

**Comment by Naktibalda** [comment]
Not a bug, this is expected behaviour.

You must set `Content-Type: application/json` header if you want to get parameters encoded to JSON automatically.

If you don't want to call `haveHttpHeader` in every test, you can set it in configuration as documented in https://codeception.com/docs/modules/REST#Example

```yaml


modules:
   enabled:
       - REST:
           depends: PhpBrowser
   config:
       PhpBrowser:
           headers:
               Content-Type: application/json
```

Alternatively you can encode parameters in any way you like and pass a string as a second parameter to`sendPatch` method.
```php
$I->sendPatch($url, json_encode([...]));
```

**Comment by Naktibalda** [comment]
Since codeception/module-rest 1.4.1 you can use `sendPatchAsJson` to avoid any ambiguity.

You have to add these additional lines to your suite configuration file:

```yaml
step_decorators:
    - \Codeception\Step\AsJson
```

https://github.com/Codeception/module-rest/releases/tag/1.4.1
