### ISSUE TITLE
Useless shortlink in deprecation warning for settings.bootstrap

### ISSUE THREAD

**Issue by DBX12** [Codeception/Codeception#6270]
#### What are you trying to achieve?
Learn about correctly removing the `settings.bootstrap` property from the codeception.yml config file. I expected to be redirected to the appropriate codeception docs section.

#### What do you get instead?
A (for me) useless Russian website.

#### How to reproduce?
Configure the `bootstrap` setting as shown below and run the tests. You should get a message like this:

> DEPRECATION: 'settings: bootstrap: _bootstrap.php' option is deprecated! Replace it with: 'bootstrap: _bootstrap.php' (not under settings section). See https://bit.ly/2YrRzVc

Or see the link in the code here https://github.com/Codeception/Codeception/blob/76ed7815922df2b958a5a8368acbb3532f7652eb/src/Codeception/Configuration.php#L259

### Details

* Codeception version: 4.1.22

```yml
# several config options
settings:
    bootstrap: _bootstrap.php
# several other config options
```

----

**Edit:** I know how where to move the bootstrap to fix my config, my issue is rather the link not pointing to the docs.

**Comment by Naktibalda** [comment]
Fixed in linked pull request
