### ISSUE TITLE
Deprecated PHP 8.1

### ISSUE THREAD

**Issue by Igor100** [Codeception/Codeception#6288]
./vendor/bin/codecept run
Codeception PHP Testing Framework v4.1.22
Powered by PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

PHP Deprecated:  Return type of Codeception\Test\Test::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/codeception/codeception/src/Codeception/Test/Test.php on line 138

Deprecated: file_put_contents(): Passing null to parameter #3 ($flags) of type int is deprecated in vendor/codeception/codeception/src/Codeception/Command/Shared/FileSystem.php on line 51

**Comment by Naktibalda** [comment]
Fixed by https://github.com/Codeception/Codeception/pull/6252 , not released yet.

**Comment by Naktibalda** [comment]
Please upgrade to 4.1.23
