### ISSUE TITLE
Is not updated phar for release 4.1.23

### ISSUE THREAD

**Issue by liborm85** [Codeception/Codeception#6289]
#### What are you trying to achieve?

Download last release 4.1.23 from phar url https://codeception.com/codecept.phar

#### What do you get instead?

From url https://codeception.com/codecept.phar is downloaded 4.1.22 version.

```bash
php codecept.phar --version
Codeception 4.1.22
```

### Details

irrelevant

**Comment by Naktibalda** [comment]
Fixed

https://github.com/Codeception/codeception.github.com/commit/63ee7c0529c85d91188b4de6ccbc6e8d7fd4c569

**Comment by Naktibalda** [comment]
Please update with the latest phar file containing 4.1.26
