### ISSUE TITLE
Example class throws E_DEPRECATED warning in PHP 8.1

### ISSUE THREAD

**Issue by fabacino** [Codeception/Codeception#6291]
#### What are you trying to achieve?

Running a test using the `Codeception\Example` class with PHP 8.1

#### What do you get instead?

```bash
❯ vendor/bin/codecept run
Codeception PHP Testing Framework v4.1.23
Powered by PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Fatal error: During inheritance of ArrayAccess: Uncaught PHPUnit\Framework\Exception: Return type of
Codeception\Example::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(
mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress
the notice at vendor/codeception/codeception/src/Codeception/Example.php:27

/home/www/http/vendor/composer/ClassLoader.php:571
/home/www/http/vendor/composer/ClassLoader.php:428
 in /home/www/http/vendor/codeception/codeception/src/Codeception/Example.php on line 6
```

Adding the `#[\ReturnTypeWillChange]` attribute to the `offsetExists` method fixes the issue. The same error appears for the other interface methods in `Example` as well. I can PR if appreciated.

Related issue: https://github.com/Codeception/Codeception/issues/6288

### Details

* Codeception version: 4.1.23
* PHP Version: 8.1
* Operating System: Linux
* Installation type: Composer

**Comment by Naktibalda** [comment]
`Not compatible` is a bit harsh, it throws E_DEPRECATED in PHP 8.1

You must have some setting enabled that converts deprecation messages to exceptions.

Please raise PR.

**Comment by fabacino** [comment]
That's true, no offense meant. I've rephrased the title.
