### ISSUE TITLE
Compatibility phar package with PHP 8.1

### ISSUE THREAD

**Issue by liborm85** [Codeception/Codeception#6305]
#### What are you trying to achieve?

Codeception from phar package (https://codeception.com/codecept.phar) runned on PHP 8.1 throw deprecated warnings.

I think the problem is in phar packaging where third-party libraries have phpdocs removed including attributes `#[\ReturnTypeWillChange]`.

#### What do you get instead?

Example:
```bash
php codecept.phar --version
```

Output:
```bash
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar://D:/QCM/codecept-issue/phar/codecept.phar/vendor/symfony/console/Helper/HelperSet.php on line 104

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar://D:/QCM/codecept-issue/phar/codecept.phar/vendor/symfony/console/Helper/HelperSet.php on line 104
Codeception 4.1.27
```

### Details

* Codeception version: 4.1.27
* PHP Version: 8.1.0
* Operating System: Windows 10
* Installation type: Phar

**Comment by Naktibalda** [comment]
Most likely you will have to wait for Codeception 5.

**Comment by Naktibalda** [comment]
Yesterday I though that you asked for a phar build targetted to PHP 8.1,

You are right that this is a fault of stripping comments from packed files.

**Comment by Naktibalda** [comment]
I raised pull request to fix stripping https://github.com/consolidation/robo/pull/1084

**Comment by liborm85** [comment]
Thank you for fix. I will wait for the release of version.

**Comment by liborm85** [comment]
Updated. It works ok. Thanks.
