### ISSUE TITLE
Codeception code coverage fails due to missed unit test cases execution

### ISSUE THREAD

**Issue by michel-cetina** [Codeception/Codeception#6309]
#### What are you trying to achieve?
I want to see that my code is 100% covered by unit tests.
#### What do you get instead?
Code coverage is under 100% due to missing unit tests cases not executed or partially executed.
### Details

* Codeception version: 4.1.23
* PHP Version: 8.1.0
* Operating System: Alpine Linux 3.15
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration: ~

We already did some debugging and found the issue in the following file: **vendor/codeception/codeception/src/Codeception/Suite.php**, it seems that in some cases the output of spl_object_hash is equal but not strictly equal when comparing different objects. The snippet below contains a sample of two hashes that we found to be clashing from different methods of the same unit test class.

Unfortunately we haven't found the time to investigate why PHP behaves in such a way, but we do know that if we use the strict comparison in the in_array function this issue can not longer be reproduced. I've created a snipped that could clarify the hash clash a bit better [here](http://sandbox.onlinephpfunctions.com/code/fa953f15588b92481b4d71019cf5c04b08923848).

`
class Suite extends \PHPUnit\Framework\TestSuite
{
    protected $modules;
    protected $baseName;

    public function reorderDependencies()
    {
        $tests = [];
        foreach ($this->tests as $test) {
            $tests = array_merge($tests, $this->getDependencies($test));
        }

        $queue = [];
        $hashes = [];
        foreach ($tests as $key => $test) {
            $x = $key;
            // In array is being executed without the $strict flag making the following hashes to clash
           // 0000000000000e130000000000000000 == 0000000000000e060000000000000000
            if (in_array(spl_object_hash($test), $hashes)) {
                continue;
            }
            $hashes[] = spl_object_hash($test);
            $queue[] = $test;
        }
        $this->tests = $queue;
    }
`

**Comment by Naktibalda** [comment]
I released 4.1.28 with your patch.

**Comment by michel-cetina** [comment]
Thank you for the quick response, have a great day ahead!
