### ISSUE TITLE
can't get remote coverage,c3tmp is empty

### ISSUE THREAD

**Issue by jingyuezijing** [Codeception/Codeception#6338]
#### What are you trying to achieve?
I want to get apitest codecoverage depends phpbrowser
#### What do you get instead?

coverage :remote:enable,_output has no c3tmp dir
c3.php enable debug: can see the c3tmp dir,bug it is empty ：
Undefined index: HTTP_X_CODECEPTION_CODECOVERAGE in <b>/www/c3.php</b> on line <b>126</b><br />
> Provide console output if related. Use `-vvv` mode for more details.
![image](https://user-images.githubusercontent.com/77383326/151651369-17468970-d195-4944-807a-0c1718a37c8f.png)

![image](https://user-images.githubusercontent.com/77383326/151651354-3f0e794f-d331-4254-8b54-69b3c3b2e6b9.png)

```bash
[InvalidArgumentException] Invalid json: <br />
<b>Notice</b>:  Undefined index: HTTP_X_CODECEPTION_CODECOVERAGE in <b>/www/c3.php</b> on line <b>126</b><br />
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:3.1.3
* PHP Version:7.4.3nts
* Operating System:
* Installation type: Composer
* List of installed packages (`composer show`)
behat/gherkin                          v4.9.0
bower-asset/bootstrap              v3.4.1
bower-asset/inputmask              3.3.11
bower-asset/jquery                   3.6.0
bower-asset/punycode               v1.3.2
bower-asset/yii2-pjax              2.0.7.1
cebe/markdown                        1.2.1
codeception/c3                          2.6.4
codeception/codeception            3.1.3
codeception/phpunit-wrapper        8.1.4
codeception/stub                   3.7.0
doctrine/annotations               1.13.2
doctrine/instantiator              1.4.0
doctrine/lexer                     1.2.2
egulias/email-validator            3.1.2
ezyang/htmlpurifier                v4.14.0
facebook/webdriver                 1.7.1
fakerphp/faker                     v1.18.0 
flow/jsonpath                      0.5.0
graylog2/gelf-php                  1.7.1
guzzlehttp/guzzle                  6.5.5
guzzlehttp/promises                1.5.1 
guzzlehttp/psr7                    1.8.3
hoa/consistency                    1.17.05.02
hoa/console                        3.17.05.02
hoa/event                          1.17.01.13 
hoa/exception                      1.17.01.16
hoa/file                           1.17.07.11 The
hoa/iterator                       2.17.01.10
hoa/protocol                       1.17.01.14
hoa/stream                         1.17.02.21
hoa/ustring                        4.17.01.16
jasig/phpcas                       1.3.8
markbaker/complex                  1.5.0 
mongodb/mongodb                    1.2.0
myclabs/deep-copy                  1.10.2
opis/closure                       3.6.3
paragonie/constant_time_encoding   v2.5.0 
paragonie/random_compat            v9.99.100 
pear/net_dns2                      v1.5.2 
phar-io/manifest                   2.0.3 
phar-io/version                    3.1.0 
phpdocumentor/reflection-common    2.2.0
phpdocumentor/reflection-docblock  5.3.0  
phpdocumentor/type-resolver        1.6.0
phpoffice/phpexcel                 1.8.2
phpoffice/phpspreadsheet           1.4.1
phpspec/php-diff                   v1.1.3 
phpspec/prophecy                   v1.15.0 
phpunit/php-code-coverage          7.0.15     
phpunit/php-file-iterator          2.0.5
phpunit/php-text-template          1.2.1
phpunit/php-timer                  2.1.3
phpunit/php-token-stream           4.0.4
phpunit/phpunit                    8.5.23
psr/cache                          1.0.1
psr/container                      1.1.2
psr/http-message                   1.0.1
psr/log                            1.1.4 
psr/simple-cache                   1.0.1
ralouphie/getallheaders            3.0.3
sebastian/code-unit-reverse-lookup 1.0.2      
sebastian/comparator               3.0.3
sebastian/diff                     3.0.3 
sebastian/environment              4.2.4 
sebastian/exporter                 3.1.4
sebastian/global-state             3.0.1
sebastian/object-enumerator        3.0.4 
sebastian/object-reflector         1.1.2
sebastian/recursion-context        3.0.1
sebastian/resource-operations      2.0.2
sebastian/type                     1.1.4
sebastian/version                  2.0.1
swiftmailer/swiftmailer            v6.3.0 
symfony/browser-kit                v4.2.4 
symfony/console                    v4.4.37
symfony/css-selector               v4.4.37
symfony/deprecation-contracts      v2.5.0
symfony/dom-crawler                v4.4.37
symfony/event-dispatcher           v4.4.37    
symfony/event-dispatcher-contracts v1.1.11
symfony/finder                     v4.4.37
symfony/polyfill-ctype             v1.24.0
symfony/polyfill-iconv             v1.24.0
symfony/polyfill-intl-idn          v1.24.0
symfony/polyfill-intl-normalizer   v1.24.0
symfony/polyfill-mbstring          v1.24.0 
symfony/polyfill-php72             v1.24.0
symfony/polyfill-php73             v1.24.0
symfony/polyfill-php80             v1.24.0
symfony/process                    v4.4.37
symfony/service-contracts          v2.5.0
symfony/yaml                       v4.4.37
theseer/tokenizer                  1.2.1     
webmozart/assert                   1.10.0
yiisoft/yii2                       2.0.43
yiisoft/yii2-bootstrap             2.0.11
yiisoft/yii2-composer              2.0.10 
yiisoft/yii2-debug                 2.1.18
yiisoft/yii2-faker                 2.0.5
yiisoft/yii2-gii                   2.1.4
yiisoft/yii2-mongodb               2.1.12
yiisoft/yii2-redis                 2.0.17
yiisoft/yii2-swiftmailer           2.1.3
zircote/swagger-php                2.0.16

* Suite configuration:
api.suite.yml
![image](https://user-images.githubusercontent.com/77383326/151651420-317547c5-26a1-46a4-8254-4fdbc9b5724d.png)
codeception.yml
![image](https://user-images.githubusercontent.com/77383326/151651539-37b9d4ad-222e-49d2-af85-c3a78d3f8ab3.png)

index.php include c3
![image](https://user-images.githubusercontent.com/77383326/151651460-08ee0ece-13bc-4abe-b869-5b46d3f03861.png)

**Comment by Naktibalda** [comment]
You got `Undefined index: HTTP_X_CODECEPTION_CODECOVERAGE in /www/c3.php on line 126` because you commented out lines 34-36 of c3.php

These lines help to differentiate requests to c3.php from requests to your application.

**Comment by jingyuezijing** [comment]
close
