### ISSUE TITLE
can’t get remote coverage depends phpbrowser

### ISSUE THREAD

**Issue by jingyuezijing** [Codeception/Codeception#6356]
#### What are you trying to achieve?
I want to get apitest codecoverage depends phpbrowser

What do you get instead?

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# In RemoteServer.php line 57:
                                                                                                                                                 
  [UnexpectedValueException]                                                                                                                     
  phar error: "C:\Users\Administrator\AppData\Local\Temp\C3B85.tmp.tar" is a corrupted tar file (checksum mismatch of file "<!doctype html><ht   
  ml lang="en"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" conte") 
```
![image](https://user-images.githubusercontent.com/77383326/152737301-d5bde57c-7300-48c0-889b-afa88f7ed4de.png)

> Provide test source code if related

```php

 php vendor/codeception/codeception/codecept run tests/api/serverconfigCest.php -vvv --coverage --coverage-text --coverage-html
```
### Details

* Codeception version:
* PHP Version: 
* Operating System: win 10
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

codeception.yml
![image](https://user-images.githubusercontent.com/77383326/152737047-c277e320-3617-4d6a-b324-bb8ad9f8cca2.png)
api.suite.yml
![image](https://user-images.githubusercontent.com/77383326/152737079-237bc833-a1b4-4c68-9ef0-aa684f1c2943.png)
index.php include c3.php
![image](https://user-images.githubusercontent.com/77383326/152737128-ec4efe41-a2a0-4eb5-9be7-01a68809aedf.png)

**Comment by Naktibalda** [comment]
You get HTML back, so c3.php is not loaded or it isn't working.

**Comment by jingyuezijing** [comment]
@Naktibalda  ths for reply
I  use --coverage-xml ,has no errors,but xml has no content;
when I use  remote:false, I can  get coverage correctly,so c3.php is loaded and working；
when I use  remote：true，has erros，Where else can I check？

**Comment by Naktibalda** [comment]
`remote: false` reads coverage results from local file, so it doesn't make HTTP request to `https://domain/index.php/c3/report/xml`
