### ISSUE TITLE
Can I add custom option to command?

### ISSUE THREAD

**Issue by andrew-svirin** [Codeception/Codeception#6360]
I try to run something like this `codecept run --case=case15` where `case15` will be applied to filter data from dataProvider.
How can I make optional filter data provider or add custom option to `run` command?

**Comment by Naktibalda** [comment]
You can't add a custom option to `run` command, but I think that it is a bug of Codeception that it is impossible to filter by data provider names.

**Comment by Naktibalda** [comment]
Thanks for reminding me, I had `@todo` to fix data provider filter.

**Comment by andrew-svirin** [comment]
Thank you.
