### ISSUE TITLE
can't install codeception into php 8.0.10 project

### ISSUE THREAD

**Issue by mbolisov** [Codeception/Codeception#6361]
codeception require php 5.6.0 <=> 8.0 6 but my work project have 8.0.10 

is it worth waiting for the update

**Comment by Naktibalda** [comment]
Codeception 4.1 is compatible with PHP 8.0 and 8.1

**Comment by mbolisov** [comment]
@Naktibalda My Error message 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeception/codeception[4.1.0, ..., 4.1.8] require php >=5.6.0 <8.0 -> your php version (8.0.10) does not satisfy that requirement.

**Comment by Naktibalda** [comment]
Probably you have another problem which prevents installation of codeception/codeception [4.1.9,...,4.1.29]
