### ISSUE TITLE
[5.0-RC1] Recorder Extension throws error

### ISSUE THREAD

**Issue by romanmartushev** [Codeception/Codeception#6417]
#### What are you trying to achieve?
Run tests using Recorder Extension

#### What do you get instead?

[TypeError] str_pad(): Argument 1 ($string) must be of type string, int given

### Details

* Codeception version: 5.0.0-RC1
* PHP Version: 8.0.7

### Solution
paramaters passed to str_pad in Recorder.php extension need to match correct types.

**Comment by Naktibalda** [comment]
thanks for report, I will release a new version soon.
