### ISSUE TITLE
Improve the experience for multi-application setups / monorepos (PR included)

### ISSUE THREAD

**Issue by calvinalkan** [Codeception/Codeception#6434]
#### What are you trying to achieve?

Assuming the following directory structure of a monorepo:

```
├── packages
│   ├── package-a
           └── src
           └── tests
           └── codeception.yml
    └── package-b
           └── src
           └── tests
│          └── codeception.yml
├── vendor
├── codeception.yml
├── composer.json
```

Each package follows a similar structure and has a unit, functional, and browser test suite.

What I want to do now is run **all tests** for all packages by their suite. (groups are not an option here)

This is not possible currently and complicates managing our monorepo a lot.
The only way to achieve something similar right now is to exclude all suites except the one we want to run. This is not maintainable.

Ideally, there would be a way to apply to run a selected set of suites for all packages.

The multi-application analogy to `vendor/bin/codecept run unit` basically.

**Comment by Naktibalda** [comment]
Fixed in [4.2.0](https://github.com/Codeception/Codeception/releases/tag/4.2.0)
