### ISSUE TITLE
[RuntimeException] Call to undefined method ApiTester::amOnUrl

### ISSUE THREAD

**Issue by pthreat** [Codeception/Codeception#6451]
#### What are you trying to achieve?
Run an API test with a different URL

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
[RuntimeException] Call to undefined method ApiTester::amOnUrl
```
![image](https://user-images.githubusercontent.com/8527076/166292225-69920f28-2a41-4e9f-8980-34033d027661.png)

**Comment by DavertMik** [comment]
`amOnUrl` is not a method of REST helper but WebDriver
you can't use it in context of API testing.

just use `sendGet()` with a full URL (with HTTP:// or https:// protocol) in it

**Comment by Naktibalda** [comment]
PhpBrowser module provides `amOnUrl` too. It must be enabled in api.suite.yml file

https://codeception.com/docs/modules/PhpBrowser#Example-acceptancesuiteyml
