### ISSUE TITLE
Skipped tests are being printed as if they were failures in standard output

### ISSUE THREAD

**Issue by Sir-G** [Codeception/Codeception#6460]
#### What are you trying to achieve?
Skipped tests to be printed in standard output as yellow **S**

#### What do you get instead?
Skipped tests are printed in standard output just as a failure would.

### Details

* Codeception version: 5.0 (RC1, RC2, RC3)
* PHP Version: 8.1.6
* Operating System: Docker hosted in linux
* Installation type: Composer

**Comment by Naktibalda** [comment]
Fixed by https://github.com/Codeception/Codeception/pull/6457 already, not released yet.
