### ISSUE TITLE
Upgrade official docker image to use PHP 8+

### ISSUE THREAD

**Issue by AudriusPa** [Codeception/Codeception#6465]
#### What are you trying to achieve?

Run dockerized codeception on PHP 8.0-8.1

#### What do you get instead?

Language features that are new in PHP 8.0-8.1 cause a syntax error because they are being run in a docker image based on PHP 7.4 (FROM php:7.4-cli in Dockerfile).

Tests get syntax errors when run in docker

### Details

- Codeception version: 4.1
- PHP Version: N/A
- Operating System: Docker for MacOS
- Installation type: Docker
- List of installed packages (composer show): N/A
- Suite configuration: N/A

Codeception 4.1 is updated to use PHP 8+, but its docker image is not. Please update docker image to support PHP 8.0-8.1

**Comment by Naktibalda** [comment]
"Official docker image" was a drive by contribution and it regularly falls into disrepair.  
The publishing process stopped working a year ago.

@schmunk42 Can you fix it?

**Comment by o-perator** [comment]
when it will be possible to use the official image codeception with php 8.1?

**Comment by schmunk42** [comment]
> I submitted Docker Open Source Community Application to get automated builds working.

Cool. I just came back from vacation, let me know when the automated builds are ready and there's still an open task.

**Comment by Naktibalda** [comment]
Nothing happened. I'm pretty sure that @DavertMik submitted request before too, so it seems unlikely that we will get free builds.

I built and published `5.0.0` and `latest` tags manually and added some instructions how to use docker image to README https://hub.docker.com/r/codeception/codeception

Further suggestions how to improve docker description are welcome.

**Comment by schmunk42** [comment]
The build process could be moved to GitHub actions, looks like there's still no auto-build from DockerHub.
