### ISSUE TITLE
ENV values in files overrides system values

### ISSUE THREAD

**Issue by sokil** [Codeception/Codeception#6473]
#### What are you trying to achieve?

I have application built as docker image and run inside some orchestrator. This orchestrator passes env variables with database connection params to app.

Due to modern principles of running apps this application does not contain any concrete configuration inside image, only some defaults, even for dev and test stages. It even has no pre-configured stages inside, just long list of env vars.

So this app need to use env variables from system, and for those which not set it may use some defaults in .env files. 

In codeception v.5 this behavior was broken.

In `\Codeception\Lib\ParamsLoader::loadDotEnvFile` variables from file populated with override flag:
```
        if (class_exists(SymfonyDotenv::class)) {
            $symfonyDotEnv = new SymfonyDotenv();
            $values = $symfonyDotEnv->parse(self::getFileContents($file), $file);
            $symfonyDotEnv->populate($values, true);
            return $values;
        }
```

This is wrong behavior, because system env is more priore than values commited in file. System envs must be used to override defaults in file.

If some legacy application (not in docker) stores it's real database connection params in this files, behavior with more proir system envs does not broke it, but gives ability to override this values by setting them in `.bashrc`.

I can't change this behavior by setting `env` param in `codeception.yml` like this:

```yml
params:
    - .env
    - .env.test
    - env
```

or this

```yml
params:
    - env
    - .env
    - .env.test
```

This `env` parameter injected by function `\Codeception\Lib\ParamsLoader::loadEnvironmentVars`

```
    private static function loadEnvironmentVars(): array
    {
        return $_SERVER;
    }
```

If it stands first in list, it fill be overriden by dotenv files. if it stands last, it used already overriden `$_SERVER`.

My proposal is not to override existing env vars by files:
```
$symfonyDotEnv->populate($values, false);
```

In this case i may get any behavior by changing positions of params files.

#### What do you get instead?

Can not have behavior where system environment is prior to values in .env files

### Details

* Codeception version: 5.0.0-RC3
* PHP Version: 8.1.1
* Operating System: Linux
* Installation type: Composer
* Suite configuration:

```yml
params:
    - .env
    - .env.test
    - env
```

**Comment by Naktibalda** [comment]
Yes, it looks like unexpected change,

@mkilmanas Did you have a reason to set `$overrideExistingVars` parameter to `true`?

**Comment by mkilmanas** [comment]
I don't have any good reason for that specific parameter - and if that overrides true env vars, then that's certainly not intended.

The problem I was fixing (https://github.com/Codeception/Codeception/commit/e4b675441760379b105385966c1d8d8beaf9a7ef) was that values from .env files were not being populated to $_ENV at all. If this part still works with `$overrideExistingVars = false` then I have no problem with such change.

**Comment by sokil** [comment]
Yes, this part will work, but only for environment variables not defined previously.

If env defined in system, value from dotenv will not be populated
If env defined in some dotenv file in `params` but not in system env vars it will be populated and overwritten by next dotenv file

**Comment by sokil** [comment]
Thank you!
