### ISSUE TITLE
can't install codeception into php 8.1 project 

### ISSUE THREAD

**Issue by mbolisov1337** [Codeception/Codeception#6479]
When I try install codeception 4.2 via composer Ii get this 
```
codeception/codeception[4.2.0, ..., 4.2.x-dev] require symfony/finder >=2.7 <6.0 -> found symfony/finder[v2.7.0-BETA1, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.8 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

```

Then I install codeception 5.0.0 RC-2
Then try bootstrap and get

```
  Module Asserts is not installed.                   
  Use Composer to install corresponding package:     
                                                     
  composer require codeception/module-asserts --dev  
```

try install this module

```
codeception/module-phpbrowser 1.0.2 requires codeception/codeception ^4.0 -> found codeception/codeception[4.0.0, ..., 4.2.x-dev] but it conflicts with your root composer.json require (5.0.0-RC2).

``` 

then I try install php browser : 3.0.0 which works with codeception 5.0.0 and get
 
 ```
 - codeception/module-asserts 1.3.1 requires codeception/lib-asserts ^1.13.1 -> found codeception/lib-asserts[1.13.1, 1.13.2] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
 ```
 
 And  codeception/lib-asserts[1.13.0, ..., 1.13.1] require php >=5.6.0 <8.0 -> your php version (8.1.6) does not satisfy that requirement

**Comment by Naktibalda** [comment]
You need a newer version of module-asserts too.
Majority of modules have 3.0 version compatible with Codeception 5.

**Comment by mbolisov1337** [comment]
thank you so much, that's problem solved, and it was my mistake because i was distracted tomorrow 
But
I have a new one 
```
File codeception.yml created       <- global configuration
PHP Fatal error:  Uncaught Error: Interface "Codeception\Lib\Interfaces\Web" not found in /var/www/vendor/codeception/lib-innerbrowser/src/Codeception/Lib/InnerBrowser.php:43

```

The Interface folder doesn't have the couple of interfaces 
<img width="208" alt="image" src="https://user-images.githubusercontent.com/106742502/174977523-37851f31-36b1-4c04-b902-feb29e857fa1.png">

**Comment by Naktibalda** [comment]
Update codeception/lib-innerbrowser to the latest version (3.1.2).

Don't use codeception.phar to run modules installed using composer.
