### ISSUE TITLE
 undefined method Timer::resourceUsage()

### ISSUE THREAD

**Issue by zdenekgebauer** [Codeception/Codeception#6484]
```bash
FATAL ERROR. TESTS NOT FINISHED.
Uncaught Error: Call to undefined method SebastianBergmann\Timer\Timer::resourceUsage() in phar: .... codecept.phar/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:410
```
### Details

* Codeception version: 4.2.1
* PHP Version: 8
* Operating System: Linux
* Installation type: Phar

**Comment by Naktibalda** [comment]
I guess that you have incompatible version of PHPUnit installed using composer.

Uninstall PHPUnit or install Codeception using composer.

If it doesn't help, please run Codeception with `-vvv` parameter and provide full stack  trace.
