### ISSUE TITLE
Add Db module alternative that integrates with PHPUnit's DbUnit extension

### ISSUE THREAD

**Issue by elazar** [Codeception/Codeception#650]
PHPUnit has a [DbUnit extension](https://github.com/sebastianbergmann/dbunit) that provides [much of the same functionality](http://phpunit.de/manual/current/en/database.html) as the existing Codeception Db module. The difference is that it's invoked through code rather than configuration, enabling the developer to implement things like connections to multiple databases (see #301) or varying data sets between tests. Codeception could potentially support a module apart form Db that wraps DbUnit to offer this alternative functionality.

Example use case: I'm currently writing functional tests for a REST API backed by a MySQL database. Only being allowed one data set can make it difficult to iteratively develop tests for an existing codebase. For example, in testing search functionality where I want to perform an assertion against record counts to ensure that I got back the expected number of results, adding additional records for new tests can cause such assertions to fail.

Codeception's [own documentation](http://codeception.com/docs/09-Data) maintains that tests should not affect each other, yet only allows for one data set for all tests; these two situations seem to be in contradiction or at best in conflict with each other. Being able to have a separate data set per test would remove this difficulty and make tests more atomic.

Disclaimer: I am currently a maintainer of DbUnit, having received merge rights following [my presentation](http://matthewturland.com/slides/phpunit-db/) on the subject at SunshinePHP 2013.

**Comment by javigomez** [comment]
The link in the previous comment is wrong, it should link to http://codeception.com/addons

**Comment by DavertMik** [comment]
Yes, the 3rd-party module is welcome.
