### ISSUE TITLE
[Error] Class "Codeception\PHPUnit\Constraint\JsonContains" not found 

### ISSUE THREAD

**Issue by mbolisov1337** [Codeception/Codeception#6501]
Hello, I have an another one problem.

Now, when I try to use `seeResponseContainsJson($json)` I get `[Error] Class "Codeception\PHPUnit\Constraint\JsonContains" not found `

I am try git clone module rest and copy JsonContains class into Constraint directory, but it doesn't have result.

when I try to upgrade module-rest to 3.1.0 version I get 
``` 
  - codeception/lib-web[1.0.0, ..., 1.0.1] require guzzlehttp/psr7 ^2.0 -> found guzzlehttp/psr7[dev-master, 2.0.0-beta1, ..., 2.4.x-dev (alias of dev-master)] but the package is fixed to 1.9.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

when I am update guzzle http I get
```
 Problem 1
    - Root composer.json requires socialconnect/http-client ^1.0 -> satisfiable by socialconnect/http-client[1.0.0].
    - socialconnect/http-client 1.0.0 requires guzzlehttp/psr7 ^1.6 -> found guzzlehttp/psr7[1.6.0, ..., 1.x-dev] but it conflicts with your root composer.json require (2.1).

```

and social connect doesn't have any another versions

**Comment by Naktibalda** [comment]
get rid of socialconnect/http-client, use guzzle/guzzle v7 instead, it supports PSR-18 since December 2018.

**Comment by Naktibalda** [comment]
Alternatively, you can use Codeception 4.
