### ISSUE TITLE
Data provider accessing test class properties

### ISSUE THREAD

**Issue by W0rma** [Codeception/Codeception#6514]
#### What are you trying to achieve?

I have some cests were data providers access properties of the cest class:

```php
use Codeception\Attribute\DataProvider;
use Codeception\Example;

class FooCest
{
    private int $foo;

    public function _before(): void
    {
        $this->foo = SomeOtherClass::getFoo();
    }

    #[DataProvider('_getExamples')]
    public function testSomething(FunctionalTester $I, Example $example): void
    {

    }

    private function _getExamples(): iterable
    {
        yield ['foo' => $this->foo];
    }
}
```

This worked fine in `codeception/codeception:5.0.0-RC5`.

However it stopped working in `5.0.0-RC6`:

```
[Error] Typed property FooCest::$foo must not be accessed before initialization
```

I get the same error if I use the `dataProvider` annotation.

I know that `5.0.0-RC6` contains some changes regarding data providers.
Could these changes be related to this error?

### Details

* Codeception version: 5.0.0-RC6
* PHP Version: 8.0.21
* Operating System: Linux
* Installation type: Composer

**Comment by Naktibalda** [comment]
It is completely unexpected that `_before` could be executed before data provider, I will investigate it later.

**Comment by Naktibalda** [comment]
I tested all the way to 4.0.3, data provider has never worked the way you described.

I could guess that you started getting Type Error because you upgraded to PHP 8 and changed `private $foo;` to `private int $foo;`  untyped property doesn't cause type error and has `null` value.
