### ISSUE TITLE
ErrorException: Argument 1 passed to 

### ISSUE THREAD

**Issue by cmodijk** [Codeception/Codeception#652]
I just insalled the codeception with composer and I get the following error during my functional tests.

```
ErrorException: Argument 1 passed to Symfony\Component\HttpKernel\Profiler\Profiler::loadProfileFromResponse() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Symfony\Component\BrowserKit\Response given, called in /vendor/codeception/codeception/src/Codeception/Module/Symfony2.php on line 150 and defined
```

**Comment by JarJak** [comment]
Same problem with Codeception 2.1.2

**Comment by raistlin** [comment]
I could only reproduce this bug when in a Cept file, a call to something that needs the profiler is called before a request has been performed.

I think we can response a bit cleaner message, something like: "You must perform a request before using this action"
