### ISSUE TITLE
[QUESTION] How do you handle v4 support now that v5 is out

### ISSUE THREAD

**Issue by calvinalkan** [Codeception/Codeception#6532]
I could not find anything regarding support for version 4 of Codeception now that version 5 is released (great job btw).

What are your thoughts on this?

Are you still willing to merge fixes/improvements that I would provide targeting 4.X branches?

Or is codeception4 completely dead in your eyes?

I'm asking because the entire WordPress ecosystem (that does testing) cant upgrade because we have not yet been able to get wp-browser compatible with Codeception.

Tracking the issue here https://github.com/lucatume/wp-browser/issues/571

**Comment by DavertMik** [comment]
Sure Codeception 5 is not for everyone as it targets PHP 8+ and PHPUnit 9+
so if you need a patch release send a pull request to 4.x branch and ping us that you need to get a new release done
but I hope that's a temporary measure

**Comment by calvinalkan** [comment]
@DavertMik sure, I'm still finding some bugs related to multi-app setups. I suppose they are also present in v5.

Would submitting a PR to 4.X work for you and you can cherry-pick the fix later to v5?

`I hope that's a temporary measure`

So do I, but you know, PHP7.4 is bleeding edge tech in the WordPress world :D

**Comment by DavertMik** [comment]
Sure thing, thank you!
If possible, create 2 pull requests so we could adopt those patches to v5 faster

**Comment by calvinalkan** [comment]
> Sure thing, thank you! If possible, create 2 pull requests so we could adopt those patches to v5 faster

Great, let's start with https://github.com/Codeception/Codeception/issues/6532#issuecomment-1202340528 if you agree on it being an issue.
