### ISSUE TITLE
[QUESTION] How to mock chain of methods with \Codeception\Test\Unit

### ISSUE THREAD

**Issue by dmamchyts** [Codeception/Codeception#6551]
Hi, thank you for your awesome instrument.

About problem.
We use symfony + doctrine. We have next code:
```
    public function addLevelComplete(UserProgress $userProgress, ApiLevelCompleteRequest $request): UserProgress
    {
        if ($request->is_rare) {
            $userProgress->addLevelRareComplete($request->id);
        } else {
            $userProgress->addLevelComplete($request->id);
        }

        $qb = $this->em->createQueryBuilder()
            ->update(UserProgress::class, 'up')
            ->set('up.levels', ':levels')
            ->set('up.levelsRare', ':levelsRare')
            ->set('up.updatedAt', ':now')
            ->where('up.id = :id')
            ->setParameter(':levels', $userProgress->getLevels())
            ->setParameter(':levelsRare', $userProgress->getLevelsRare())
            ->setParameter(':now', new \DateTimeImmutable())
            ->setParameter(':id', $userProgress->getId());

        $qb->getQuery()->execute();

        return $userProgress;
    }
```

Do you have any ideas about how it possible?
Variant with nested `$this->makeEmpty(XXX, ['set' => $this->makeEmpty(XXX, ...])` - is  terrible.

PS. Ideal variant - http://docs.mockery.io/en/latest/reference/demeter_chains.html

**Comment by Naktibalda** [comment]
Why do you even use QueryBuilder to update database when you have entity?

`$this->em->flush();` would save all changes automatically.

**Comment by dmamchyts** [comment]
> `$userProgress` - can be restored entity from Redis cache (it's mean entity without `persist`)

**Comment by Naktibalda** [comment]
Since this is Codeception, it would be better to use a functional test and check if database content was updated.

If `Stub` class doesn't do what you need, you can use `$this->createMock()` or any other mocking library, nobody is working on improving Stub.
