### ISSUE TITLE
Impossible to create a custom module that supports both Codeception v4 and v5

### ISSUE THREAD

**Issue by Jamesking56** [Codeception/Codeception#6565]
#### What are you trying to achieve?

We currently have a custom module to add Mailcatcher support to Codeception. It currently supports Codeception v3 and v4 but we're trying to change it to support v4 and v5. However, we're hitting a problem with the `$config` property in `Module.php` requiring the same typing for Codeception v5.

https://github.com/captbaritone/codeception-mailcatcher-module/pull/89#issuecomment-1230692853

#### What do you get instead?

```
PHP Fatal error:  Type of Codeception\Module\MailCatcher::$config must be array (as in class Codeception\Module) in /home/runner/work/codeception-mailcatcher-module/codeception-mailcatcher-module/src/Module/MailCatcher.php on line 439
```

https://github.com/captbaritone/codeception-mailcatcher-module/runs/8077107653?check_suite_focus=true

**Comment by Naktibalda** [comment]
Sorry, won't fix it, things must be broken sometimes.
