### ISSUE TITLE
`[Seed] #` is not output when `--shard` is passed as an argument

### ISSUE THREAD

**Issue by StuTheWebGuy** [Codeception/Codeception#6589]
#### What are you trying to achieve?

We recently began using `--shard` to split our tests into chunks. We also use `shuffle: true` in our `codeception.yml` to randomise the order of our tests. It appears that shuffling works with sharding, as our tests are now successfully running in parallel but also executed in a random order.

However `[Seed] #` in the command output isn't being displayed ([likely due to this change made in March 2022](https://github.com/Codeception/Codeception/pull/6399/files#diff-679315e7522d54c644bf4e9595ecff235f6f02c5620bd27e0e0987a753245c9dR421-R422)). Why was this change introduced, if shard and shuffle still appear to work well together?

It would be very handy to get the seed for recreating test orders, particularly when the run has failed and we need to diagnose the issue.

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
$ XDEBUG_MODE=coverage ./vendor/bin/codecept run --shard 1/4 --coverage --coverage-cobertura=coverage_1.xml
Codeception PHP Testing Framework v5.0.3 https://helpukrainewin.org/
[Shard 1/4] Running subset of tests
Tests.Functional Tests (355) -------------------------------
```

We would expect to see `[Seed]` above or below where the `[Shard 1/4]` line currently is.

Without passing `--shard`, `[Shard 1/4]` is replaced with `[Seed]` in the output.

### Details

* Codeception version: 5.0.3
* PHP Version: 8.0.18
* Operating System: Ubuntu 20.04.4 -based Docker image (`thecodingmachine/php:8.0-v4-fpm-node14@sha256:bd9c375ad81eeb405d359cad2dde83cd583cfc1c1dc8df62b4b0a04aa48a336b`
* Installation type: Composer

**Comment by Naktibalda** [comment]
> Why was this change introduced, if shard and shuffle still appear to work well together?

That change was the implementation of `--shard` option.

The linked code disables `shuffle: true` in codeception.yml, but it was overlooked that `shuffle: true` can be set in suite.yml too.
