### ISSUE TITLE
Can't detect emails sent in Symfony

### ISSUE THREAD

**Issue by CJDennis** [Codeception/Codeception#6598]
I know this is a known issue that Codeception can't detect emails sent in Symfony. Is there a timeline for this to be fixed? I'm currently having to switch to PHPUnit just for this one type of test.

**Comment by Naktibalda** [comment]
I wasn't aware that it is a known issue.

The only open email related issue at https://github.com/Codeception/module-symfony/issues/90 says that email testing doesn't work when emails are sent in listeners.

**Comment by Naktibalda** [comment]
It isn't a know issues and therefore there is no timeline to fix it.

I'm closing this issue as a duplicate of linked module-symfony issue.
