### ISSUE TITLE
 Cannot access protected property Codeception\Step\Action::$arguments

### ISSUE THREAD

**Issue by mbolisov1337** [Codeception/Codeception#6599]
hello, I am trying to write my own custom logger into working chat. I am try to get url from failed test

What I do 

```
 $failedTest = $event->getTest();
        $trace = array_reverse($failedTest->getScenario()->getSteps());
        foreach ($trace as $step)
        {
            dump($step->arguments);
        }

```
what I get 

` Cannot access protected property Codeception\Step\Action::$arguments`

can i open access ?

**Comment by Naktibalda** [comment]
Have you found `getArguments` method? :)
