### ISSUE TITLE
Facebook\WebDriver unknown command:   wd/hub/session

### ISSUE THREAD

**Issue by donytos** [Codeception/Codeception#6627]
#### after starting the codecept it gave me this erorr instead

> Provide console output if related. Use `-vvv` mode for more details.
![er1](https://user-images.githubusercontent.com/57417682/212952828-bceef7c3-f5e6-425b-b270-a6e21bbf1c8c.png)
![er2](https://user-images.githubusercontent.com/57417682/212952835-9bf3a179-1b00-4c64-8e94-12b9c6aa1c9a.png)

those are my chromedriver.service and chromedriver.sh

![service](https://user-images.githubusercontent.com/57417682/212953773-3379bd3c-13d1-48f2-94d4-bb3bac24d02e.png)
![sh](https://user-images.githubusercontent.com/57417682/212953777-195da99e-42a5-4a2b-8246-4a67c6334f04.png)

```bash
# paste output here
```
> Provide test source code if related

```php




```
### Details

* Codeception version: 4.4.2
* PHP Version: 7.3.33
* Operating System: centos7
* Installation type: Phar || Composer
* List of installed packages: composer v:2.2.18
* Suite configuration:

```yml

![yml](https://user-images.githubusercontent.com/57417682/212958151-b561e5ef-148b-4cf8-9f92-736c80600bcb.png)

```

**Comment by Naktibalda** [comment]
Try to start chromedriver without `--url-base` parameter.

**Comment by donytos** [comment]
@Naktibalda it gave me the same issue.
I tried to remove the parameter and also tried to use the --silent. 
But nothing change

EDIT: this is the yml, don't know why the img is unavailable 

![yml](https://user-images.githubusercontent.com/57417682/212975439-3d26e11b-8c1b-4246-baf1-e26dae14cf6e.png)

**Comment by Naktibalda** [comment]
It seems that chromedriver ignores `--url-base` parameter.

Are you using a recent version of chromedriver?
Check chromedriver logs.

Try setting WebDriver path parameter to `/` to get rid of `/wd/hub/`


```yaml
modules:
  enabled:
     - WebDriver:
         path: "/"
```

**Comment by donytos** [comment]
Yes, thank you.
The path parameter helped me now everything works fine.
Abt the chromedriver version is the 109.0.5414.74


i'm closing the issue thank you again.
