### ISSUE TITLE
undefined method assertObjectNotHasAttribute()  

### ISSUE THREAD

**Issue by zdenekgebauer** [Codeception/Codeception#6636]
#### What do you get instead?
                                                                                           
  [Error] Call to undefined method PHPUnit\Framework\Assert::assertObjectNotHasAttribute()  

### Details

* Codeception version: 5.0.8
* PHP Version: 8.1
* Operating System: Windows
* Installation type: Composer, with "codeception/module-asserts" : "^3.0",

**Comment by Naktibalda** [comment]
That method no longer exists in PHPUnit 10, update your tests to use `$I->assertTrue(property_exists($object, "property"));`

**Comment by zdenekgebauer** [comment]
This is possible solution. 

The problem is that AbstractAsserts class still contains methods assertObjectHasAttribute and assertObjectNotHasAttribute. These methods should internally use your solution with property_exists instead of calling a non-existent method from phpunit. Or these methods should be removed entirely.

**Comment by Naktibalda** [comment]
I was working on it :)

**Comment by zdenekgebauer** [comment]
Thank you
