### ISSUE TITLE
Symfony. Call to undefined method CutStub::find(). Shuffle problem.

### ISSUE THREAD

**Issue by K0rINf** [Codeception/Codeception#6647]
#### What are you trying to achieve?

I have a simple ReadCest with symfony and doctrine. 

In it, I create an entity via $I->haveInRepository, then I check the request to read this entity by id.
$I->sendGet('/deal/' . static::$dealId);
$I->seeResponseCodeIsSuccessful();

#### What do you get instead?
If run only this one test, then it works as it should.

```bash
php vendor/bin/codecept run api ReadCest 
OK (1 test, 1 assertions)
```
But, if i run all tests i get error

```bash
[Error] Call to undefined method Symfony\Component\VarDumper\Caster\CutStub::find()
```
The problem does not occur if the test is executed first. But if the test is not executed first, then an error occurs.

> Provide test source code if related

```php
<?php

namespace App\Tests;

use App\Entity\Deal;

class ReadCest
{
    private static int $dealId;
 
   // tests
    public function tryToTest(ApiTester $I): void
    {
        static::$dealId = $I->haveInRepository(Deal::class, [
            'clientId' => 'test',
            'createdBy' => 1
        ]);

        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGet('/deal/' . static::$dealId);
        $I->seeResponseCodeIsSuccessful();
        $I->seeResponseIsJson();
    }
}

```
### Details

* Codeception version:
* PHP Version: 8.1.3
* Operating System: Alpine 3.15
* Installation type: Composer
* List of installed packages (`composer show`)
/var/www/html # composer show               
codeception/codeception                        5.0.9
codeception/lib-asserts                        2.1.0                     
codeception/lib-innerbrowser                   3.1.3 
codeception/lib-web                            1.0.1                     
codeception/lib-xml                            1.0.1                     
codeception/module-asserts                     3.0.0              
codeception/module-doctrine2                   3.0.1                     
codeception/module-phpbrowser                  3.0.0                  
codeception/module-rest                        3.3.2                     
codeception/module-symfony                     3.1.1                
codeception/stub                               4.1.0                     
doctrine/annotations                           1.13.3                    
doctrine/cache                                 2.2.0                     
doctrine/collections                           2.1.2                   
doctrine/common                                3.4.3                 
doctrine/data-fixtures                         1.6.3                  
doctrine/dbal                                  3.6.0                     
doctrine/deprecations                          v1.0.0             
doctrine/doctrine-bundle                       2.8.3            
doctrine/doctrine-fixtures-bundle              3.4.2        
doctrine/doctrine-migrations-bundle            3.2.2                     
doctrine/event-manager                         1.2.0         
doctrine/inflector                             2.0.6                
doctrine/instantiator                          1.5.0              
doctrine/lexer                                 1.2.3                  
doctrine/migrations                            3.6.0             
doctrine/orm                                   2.14.1              
doctrine/persistence                           3.1.4                     
doctrine/sql-formatter                         1.1.3                    
symfony/*                                  v5.4.21                   
* Suite configuration:

```yml
actor: ApiTester
modules:
  enabled:
    - \App\Tests\Helper\Api
    - Symfony:
        app_path: 'src'
        environment: 'test'
    - REST:
        url: /v1/deal/api/
        depends: Symfony
        part: Json
    - Doctrine2:
        depends: Symfony
        cleanup: true
        purge_mode: 2
    - Asserts

```

**Comment by Naktibalda** [comment]
Please provide stack trace of exception, run codeception with `-vvv` parameter to get the full stacktrace.

**Comment by K0rINf** [comment]
I found problem in my controller. Him use query_filter_config_converter from artprima/query-filter-bundle.
