### ISSUE TITLE
Deprecation warning on Unit test when test helper is used

### ISSUE THREAD

**Issue by erickskrauch** [Codeception/Codeception#6665]
#### What are you trying to achieve?

I'm trying to cover my project with PHPStan static analysis. Some of my Unit tests are rely on injected tester helper (https://codeception.com/docs/UnitTests#interacting-with-the-framework). My tests are look like this:

```php
/**
 * @property \App\tests\UnitTester $tester
 */
final class SendDelayedMessageTest extends Unit {
}
```

But when I run PHPStan on PHP 8.2, I receive such errors:

```
 ------ ------------------------------------------------------------------------------------------
  Line   SendDelayedMessageTest.php
 ------ ------------------------------------------------------------------------------------------
  30     Access to an undefined property App\tests\unit\SendDelayedMessageTest::$tester.
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property
  52     Access to an undefined property App\tests\unit\SendDelayedMessageTest::$tester.
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property
 ------ ------------------------------------------------------------------------------------------
```

I've raised an [issue in PHPStan](https://github.com/phpstan/phpstan/issues/9319), but author said, that the problem in Codeception. For a long time I wasn't able to catch a deprecation warning and so I couldn't understand why assigning a test helpter didn't cause an warning. But than I found that `error_level` is overriden [here](https://github.com/Codeception/Codeception/blob/ed4af7fd4103cdd035916fbb8f35124edd2d018b/src/Codeception/Subscriber/ErrorHandler.php#L89) and by default it comes from suite as `E_ALL & ~E_STRICT & ~E_DEPRECATED`.

When I set my suite configuration like so:

```
suite_namespace: App\tests\unit
error_level: E_ALL
convert_deprecations_to_exceptions: true
```

The output has changed and I finally cought the deprecation:

```
  Creation of dynamic property App\tests\unit\SendDelayedMessageTest::$tester is deprecated  
```

#### What I suggest

The solution is simple: add `AllowDynamicProperties` attribute to the [`Unit`](https://github.com/Codeception/Codeception/blob/ed4af7fd4103cdd035916fbb8f35124edd2d018b/src/Codeception/Test/Unit.php#L26) class.

**Comment by AdrienHt** [comment]
Why did you not declare the tester property into the Unit class ?

**Comment by erickskrauch** [comment]
Because it is configurable:
https://github.com/Codeception/Codeception/blob/1998a287a3d7f2771c9591aef1c528d9d44cc4b4/src/Codeception/Test/Unit.php#L84-L86

**Comment by AdrienHt** [comment]
thanks :)
