### ISSUE TITLE
PHPUnit 10.3 incompatibility - Access of private method

### ISSUE THREAD

**Issue by codedge** [Codeception/Codeception#6680]
#### What are you trying to achieve?

I run test with expectation inside and what to get these tests green.

#### What do you get instead?

I run 
```
CODECEPTION_SUITE=Unit ./vendor/bin/codecept run Unit --html=${CODECEPTION_SUITE}_report.html --xml=${CODECEPTION_SUITE}_report.xml
```

I receive 

```
------------------------------------------------------------
In JUnitReporter.php line 250:
                                                                               
  Call to private method PHPUnit\Framework\TestCase::hasExpectationOnOutput()  
   from scope Codeception\Reporter\JUnitReporter                               
```

This is due to https://github.com/Codeception/Codeception/blob/5.0/src/Codeception/Reporter/JUnitReporter.php#L250 accessing a private method.

### Details

* Codeception version: 5.0.10
* PHP Version: 8.2
* Operating System: Linux
* Installation type: Composer
* List of installed packages (`composer show`)

**Comment by Clasyc** [comment]
Same problem.

**Comment by tecbird** [comment]
+1
