### ISSUE TITLE
Codeception 5.0.11 is incompatible to PHPUnit 10.4 

### ISSUE THREAD

**Issue by ramalama** [Codeception/Codeception#6700]
#### What are you trying to achieve?
running composer update should not break my test.

#### What do you get instead?
After upgrading from phpunit 10.3.2 => 10.4 my tests break. 
Downgrading to 10.3.5 and the tests run fine. 
Codeception 5.0.11 is not compatible to 10.4, since 10.4 (at least) renamed Methods in Framework/MockObject/Generator/Generator. 

> Provide console output if related. Use `-vvv` mode for more details.
TypeError : call_user_func_array(): Argument #1 ($callback) must be a valid callback, class PHPUnit\Framework\MockObject\Generator\Generator does not have a method "getMock"
 C:\Users\david\odrive\HiDrive (WebDAV)\public\Eigener Code\anmeldeformular\vendor\codeception\stub\src\Stub.php:448
 C:\Users\david\odrive\HiDrive (WebDAV)\public\Eigener Code\anmeldeformular\vendor\codeception\stub\src\Stub.php:418
 C:\Users\david\odrive\HiDrive (WebDAV)\public\Eigener Code\anmeldeformular\vendor\codeception\stub\src\Stub.php:220

### Details

* Codeception version: 5.0.11
* PHP Version: 8.2
* Operating System: Win 11
* Installation type: Composer
* List of installed packages (`composer show`)

**Comment by Naktibalda** [comment]
Fixed in Codeception/Stub [4.1.2](https://github.com/Codeception/Stub/releases/tag/4.1.2) thanks to @W0rma
