### ISSUE TITLE
I am unable to upgrade Codeception from 4.2 to 5.0+

### ISSUE THREAD

**Issue by wongjessica** [Codeception/Codeception#6706]
#### What are you trying to achieve?
- My codeception code for an acceptance automation test that previously worked in September, is no longer working. Chromedriver and Selenium seem to be okay, but the problem is, the test loads the website but then freezes as if it doesn't read the next few lines of code.
- So, I am trying to upgrade Codeception from 4.2 to 5.0+ to hopefully resolve this issue.
#### What do you get instead?
- The codeception version stays the same.
> Provide console output if related. Use `-vvv` mode for more details.

```bash
$ vendor/bin/codecept --version
Codeception 4.2.2

composer self-update

composer require codeception/codeception --prefer-stable --prefer-dist

composer global require codeception/codeception

$ vendor/bin/codecept --version
Codeception 4.2.2
```
### Details

* Codeception version: 4.2.2
* PHP Version:
- $ php -v
PHP 7.4.33 (cli) (built: Nov  2 2022 16:00:55) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
Note: I understand that I need at least 8.0 for Codeception 5 but I don't know how to upgrade the PHP version via console for the project.
* Operating System: Windows 10 Enterprise
* Installation type: Composer
* List of installed packages (`composer show`):
behat/gherkin                      v4.9.0  Gherkin DSL parser for PHP
codeception/codeception            4.2.2   BDD-style testing framework
codeception/lib-asserts            1.13.2  Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser       1.5.1   Parent library for all Codeception framework modules and PhpBrowser
codeception/module-asserts         1.3.1   Codeception module containing various assertions
codeception/module-phpbrowser      1.0.3   Codeception module for testing web application over HTTP
codeception/module-webdriver       2.0.4   WebDriver module for Codeception
codeception/phpunit-wrapper        9.0.9   PHPUnit classes used by Codeception
codeception/stub                   4.0.2   Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.5.0   A small, lightweight utility to instantiate objects in PHP without invoking their ...
guzzlehttp/guzzle                  7.7.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises                2.0.0   Guzzle promises library
guzzlehttp/psr7                    2.5.0   PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.11.1  Create deep copies (clones) of your objects
nikic/php-parser                   v4.16.0 A PHP parser written in PHP
phar-io/manifest                   2.0.3   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    3.2.1   Library for handling version information and constraints
php-webdriver/webdriver            1.14.0  A PHP client for Selenium WebDriver. Previously facebook/webdriver.
phpunit/php-code-coverage          9.2.26  Library that provides collection, processing, and rendering functionality for PHP ...
phpunit/php-file-iterator          3.0.6   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.1   Invoke callables with a timeout
phpunit/php-text-template          2.0.4   Simple template engine.
phpunit/php-timer                  5.0.3   Utility class for timing
phpunit/phpunit                    9.6.9   The PHP Unit Testing framework.
psr/container                      1.1.2   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0   Standard interfaces for event handling.
psr/http-client                    1.0.2   Common interface for HTTP clients
psr/http-factory                   1.0.2   Common interfaces for PSR-7 HTTP message factories
psr/http-message                   2.0     Common interface for HTTP messages
ralouphie/getallheaders            3.0.3   A polyfill for getallheaders.
sebastian/cli-parser               1.0.1   Library for parsing CLI options
sebastian/code-unit                1.0.8   Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3   Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.8   Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.2   Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.5   Diff implementation
sebastian/environment              5.1.5   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.5   Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.5   Snapshotting of global state
sebastian/lines-of-code            1.0.3   Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.4   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.4   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.5   Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3   Provides a list of PHP built-in functions that operate on resources
sebastian/type                     3.2.1   Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.2   Library that helps with managing the version number of Git-hosted PHP projects
symfony/browser-kit                v5.4.21 Simulates the behavior of a web browser, allowing you to make requests, click on l...
symfony/console                    v5.4.24 Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.4.21 Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      v2.5.2  A generic function and convention to trigger deprecation notices
symfony/dom-crawler                v5.4.25 Eases DOM navigation for HTML and XML documents
symfony/event-dispatcher           v5.4.22 Provides tools that allow your application components to communicate with each oth...
symfony/event-dispatcher-contracts v2.5.2  Generic abstractions related to dispatching event
symfony/finder                     v5.4.21 Finds files and directories via an intuitive fluent interface
symfony/polyfill-ctype             v1.27.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.27.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer   v1.27.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.27.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.27.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.27.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v5.4.24 Executes commands in sub-processes
symfony/service-contracts          v2.5.2  Generic abstractions related to writing services
symfony/string                     v5.4.22 Provides an object-oriented API to strings and deals with bytes, UTF-8 code points...
symfony/yaml                       v5.4.23 Loads and dumps YAML files
theseer/tokenizer                  1.2.1   A small library for converting tokenized PHP source code into XML and potentially ...

* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        #- PhpBrowser:
        - WebDriver:
            url: ((do not want to show))
            window_size: maximize
            port: 4444
            browser: chrome
        - \Helper\Acceptance
```

Any help will be appreciated and I will gladly put more information if needed, thank you.

**Comment by Naktibalda** [comment]
Since you are using composer. you have to update version constraints in your composer.json file.
