### ISSUE TITLE
Out of memory issue with PHPUnit 10.4.1

### ISSUE THREAD

**Issue by laoneo** [Codeception/Codeception#6707]
Since I'v updated the dependencies on my larger project and PHPUnit got lifted to version 10.4.1, I get out of memory errors as the memory limit is constantly increasing with big steps. No clue if this is a PHPUnit or Codeception issue, but I'm reporting it here for now.
As soon as I stick to [version 10.3.4](https://github.com/Digital-Peak/DPDocker/commit/e1666f907b9b4a46edb2d3de7d413eedbf856244) in my composer.json, it starts working normally and memory is around 60MB for 2'500 tests, while with PHUnit 10.4.1 it went quickly over 3'000MB. That's why I did a custom reporter as mentioned [here](https://github.com/Codeception/Codeception/issues/6628#issuecomment-1788605579) which displays the memory consumption.

Is somebody else also getting this issue? If not, I will be happy to close this issue as it is probably with my docker setup only.

**Comment by kaktusas2598** [comment]
My code coverage also started timing out when I upgraded from Codecption 4 to 5

**Comment by laoneo** [comment]
In your dev dependencies, try to stick the PHPUnit version to 10.3.4, as I did [here](https://github.com/Digital-Peak/DPDocker/commit/e1666f907b9b4a46edb2d3de7d413eedbf856244). Does that help?

**Comment by kaktusas2598** [comment]
@laoneo I'm afraid we are still on PHPUnit 9.6.13

**Comment by DavertMik** [comment]
Thanks for sharing this. I don't think we can do anything about it, I hope the issue was resolved by more modern PHPUnit versions
