### ISSUE TITLE
"No primary site exists" only when running unit tests - Craft 4 Pro.  No issues with functional and acceptance tests in same environment

### ISSUE THREAD

**Issue by tommydaltondev** [Codeception/Codeception#6730]
Codeception throws "No primary site exists" only when running unit tests. Functional and acceptance tests continue to work as they did. Not a multi-site craft install and site handle is default.

Codeception 4.2.2 (PHPUnit 9.6.16) and Craft CMS Pro 4.7.0 PHP version 8.1.26.
Craft CMS version

Linux 6.5.11-linuxkit

* Codeception version: 4.2.2 
* PHP Version: 8.1.26.
* Operating System: Linux 6.5.11-linuxkit
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:
unit.suite.yml

```yml

actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
        - \craft\test\Craft
    step_decorators: ~

**Comment by Naktibalda** [comment]
It is an issue of \craft\test\Craft module.

**Comment by Naktibalda** [comment]
It is unusual to enable framework modules in unit suite.
It makes all your tests not unit tests, are you sure that you need it there?

**Comment by Naktibalda** [comment]
It is a Craft CMS issue, please contact Craft CMS community for support and/or read the code of craft\test\Craft.
