### ISSUE TITLE
Using Symfony 7 Clock ClockSensitiveTrait causes a LogicException

### ISSUE THREAD

**Issue by AchillesKal** [Codeception/Codeception#6731]
Hey!

I am trying to upgrade to Symfony7, but my Codeception tests that use the Symfony ClockSensitiveTrait  are failing:
```
There was 1 error:
1) FirstCest: Save clock before test
 Test  tests/Unit/FirstCest.php:saveClockBeforeTest
                                                                                                  
  [LogicException] Method Class defined in annotation but does not exist in Tests\Unit\FirstCest  
                                                                                                  
#1  /app/vendor/bin/codecept:119
```

It seems that Symfony Clock, uses some annotations that are causing the problem:
```
/**
 * @beforeClass
 *
 * @before
 *
 * @internal
 */
public static function saveClockBeforeTest(bool $save = true): ClockInterface
```

I ran some PHPUnit tests with that same `ClockSensitiveTrait` but they seem to work properly.

I am not sure on which side the issue might be, but I'm kindly posting it here.

### Details

* Codeception version: 5.1
* PHP Version: 8.3.2
* Installation type:  Composer

**Comment by Naktibalda** [comment]
Don't use traits in Cest format - all public methods of Cest class are executed as test cases.

Use traits in Helper or Tester classes (see tests/Support directory), then you can methods using `$I->mockTime()` syntax.

Another option is to change visibility of trait methods to private or protected.
https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.visibility

**Comment by AchillesKal** [comment]
Yes, my bad! It works perfectly!

Thank you for your fast and incredibly helpful response!
