### ISSUE TITLE
Can I change the format of the exception display?

### ISSUE THREAD

**Issue by adiafora** [Codeception/Codeception#6737]
#### What are you trying to achieve?
If, as a result of the test, an exception was throw that was not caught, then all the data on the exception in the Artifacts block will be displayed. It can be a lot of lines, and they are very inconvenient to read in the console.

#### What do you get instead?
I want to get less data on exceptions - only the message and the class in which the exception was thrown. Or I want to control the output of this data.

![2024-02-19_12-14-30](https://github.com/Codeception/Codeception/assets/53189193/4a907c8e-40cd-4f17-8ae7-a733e0b5342f)

### Details

* Codeception version: 5.0.13
* PHP Version: 8.2
* Operating System: Ubuntu 22.04.3 LTS
* Installation type: Composer

**Comment by Naktibalda** [comment]
Not an issue of Codeception.

Stacktrace of that exception is in response of your application.
You have to change how your application or framework handles uncaught exceptions.

**Comment by adiafora** [comment]
> Not an issue of Codeception.
> 
> Stacktrace of that exception is in response of your application. You have to change how your application or framework handles uncaught exceptions.

Thanks
