### ISSUE TITLE
How to use _bootstrap.php for sharing data?

### ISSUE THREAD

**Issue by CMCDragonkai** [Codeception/Codeception#676]
I get that _bootstrap.php is used for sharing data between tests and also autoloading. But how do you actually use it to share data?

When I put variables in it, I can't seem to access it in any of the tests. I'm talking about unit tests specifically.

I can't declare classes inside of them since this causes a class redeclaration error since it's ran multiple times.

Is this where you put fixtures? So I tried adding data to the fixtures in _bootstrap.php, but I couldn't get the fixtures out of them inside my unit tests.

Where do I go about implementing fixtures that are just an array of data, nothing related to the database.

Furthermore is there any reason to put in Composer's autoloader into the _bootstrap. The tests seem to work fine autoloading properly without the need to add Composer's autoloader.

**Comment by drake-p** [comment]
I have the exact same scenario as @agarzon, except that I *am* running acceptance tests, not unit tests.

    // _bootstrap.php
    use Codeception\Util\Fixtures;
    Fixtures::add('username', 'tombombadil');

    // xxxCept.php
    $username = Fixtures::get('username');

I am still getting the `Class 'Fixtures' not found` error.  Am I missing a step?

**Comment by drake-p** [comment]
Not sure if this is the proper solution, but apparently I was just missing a `use` statement in my cept:

    // xxxCept.php
    use Codeception\Util\Fixtures;
    $username = Fixtures::get('username');

The error went away (as one would expect) and I had access to everything I'd defined in my bootstrap.

**Comment by agarzon** [comment]
@drake-p dra My solution was to use a helper: https://github.com/leewillis77/codeception-config-helper

**Comment by Naktibalda** [comment]
@DavertMik I think that content of _bootstrap.php should be updated to be more correct.
It survived almost unchanged since the initial commit: https://github.com/Codeception/Codeception/commit/111d08289a16493068c9d62b7b6c6c58daffc758#diff-18f2da2f2bb13d95f932d238c2992aa9R72

**Comment by philip** [comment]
For those stumbling into this issue wondering why simple variable definitions aren't working, note that constants do work fine. 

I'm new here and don't know the benefit of using Fixtures instead of constants, but simply defining a constant in _bootstrap.php makes it available to your tests. So something like:
```
 // _bootstrap.php
define('GREETING', 'Hello World');
// xxxCept.php
$I->haveHttpHeader('WHATSAYYOU', GREETING);
```
