### ISSUE TITLE
Coverage time issues after updating codeception from 4 to 5

### ISSUE THREAD

**Issue by ReynaldBarbeaut** [Codeception/Codeception#6772]
Since we updated codeception version from 4.2.2 to 5.1.2 we go an issue while launching tests with coverage.
For no particular reasons tests executing were 2 times longer than before. For example one which took 1s previously would take 2s now. 
My guess is this is an issue related to latests phpunit version. We downgraded phpunit version to 9.6.13 and now it's working well.
But in the future we would need to also update phpunit.
Could you help?

**Comment by DavertMik** [comment]
@ReynaldBarbeaut As you said, this was affected by PHPUnit version, and we have no impact on it. What Codeception can do only is maintaining compatibility with different PHPUnit versions, so it's a great news you could downgrade PHPUnit and get desired result.

However, I would suggest creating a minimal reproducible example and asking that question in PHPUnit repo (if you find out that is fully by PHPUnit nature), however there might be issue in how Codeception uses code coverage from PHPUnit... Anyway, we need a breakdown on this issue to be able to resolve this.

I'm closing this as we suggested that it is PHPUnit related and we currently don't have resources to investigate it further
