### ISSUE TITLE
Request, Please make real parallelization, its possible trough https://github.com/amphp/parallel-functions

### ISSUE THREAD

**Issue by valerian12** [Codeception/Codeception#6773]
We wait real parallelization since its possible, parallelMap works great, it's not good when in 2024 test framework can't run tests in real parallell, shards it's not a solution since it can't orchestrate fully all tests by run time.
Sorry for my english.
Have a good day.

**Comment by DavertMik** [comment]
Does PHP support parallel processing?

**Comment by valerian12** [comment]
https://github.com/amphp/parallel-functions solves the issue

**Comment by DavertMik** [comment]
No, it's not
Sorry, seems you don't understand what parallelization is and how it differs from asynchronicity. These are set of tools for async tasks. 

I investigated all possible options and there is no way to implement native non-flaky parallelization in PHP as there is no official way of doing so. There are exotic ways of pthreads or amphp but they won't fit for everyone, they are unstable and they will introduce a lot of complexity into the codebase even to run on simplest cases.

Unfortunately, in current architecture and in current state of PHP native parallelization is not possible.
