### ISSUE TITLE
Test description "wantTo()" does not work with PHPUnit tests

### ISSUE THREAD

**Issue by asengerdmk** [Codeception/Codeception#6800]
#### What are you trying to achieve?
I want to describe my test cases using PHPUnit tests with codeception.
Using `$I->wantTo('...')` in a Foo**Cest**.php  file works.

#### What do you get instead?
Going through the PHPUnit docs of codeception: https://codeception.com/docs/UnitTests#Creating-a-Test
mentions that I can use the UnitTester as class property instead of injecting it as `$I`.

`$this->tester->wantTo('...')` does not work. The console output `vendor/bin/codecept run Unit` does not print the description but rather the function name.

The first problem occurs when checking for this regex: https://github.com/Codeception/Codeception/blob/main/src/Codeception/Lib/Parser.php#L29
and the second problem is that Test.php files do net get parsed by this method.

### Details

* Codeception version: 5.1.2
* PHP Version: 8.1
* Operating System: Ubuntu 22.04
* Installation type: Composer

**Comment by Naktibalda** [comment]
See https://github.com/Codeception/Codeception/issues/6076#issuecomment-762260883 

Won't fix.
