### ISSUE TITLE
Update a record in DB

### ISSUE THREAD

**Issue by jonhkr** [Codeception/Codeception#710]
Is there a way to use the db driver in tests? I need to make a update on the database to continue testing but I didn't find a way of doing it using modules.

Anyone know if there is a feature to do that?

**Comment by Suseika** [comment]
@DavertMik Why is there no built-in way for updating or deleting a record, but there are ways for selecting and inserting records?

**Comment by Naktibalda** [comment]
Because inserting and selecting is much more important in tests.
