### ISSUE TITLE
How to count number of rows in table?

### ISSUE THREAD

**Issue by oliwier-insided** [Codeception/Codeception#717]
```
    $rows = $I->executeInSelenium(function(RemoteWebDriver $webDriver) use ($I) {
        //$rows = $webDriver->findElements('//*[@id="content"]/table/tbody');
        //$rows = $webDriver-> ('count(//*[@id="content"]/table/tbody/tr)');
        $rows = $webDriver->findElements(WebDriverBy::xpath('//*[@id="content"]/table/tbody/tr'));
        return count($rows);
    });
```

How do I assert that rows = 2? Cause what I get back is the Maybe object. 

Thx for any tips!

**Comment by tabascoterrier** [comment]
For any other future Googlers, the clean way would be to use `seeNumberOfElements`

```php
$I->seeNumberOfElements('tbody tr', 2);
```

https://codeception.com/docs/modules/WebDriver#seeNumberOfElements

**Comment by jim-crawford** [comment]
@tabascoterrier I am one of those very googlers from the future. (well, its the future now, im not in 2020 from 2022) but thanks for the clean method!
