### ISSUE TITLE
$I->fillField fails if submit button isn't there

### ISSUE THREAD

**Issue by andheiberg** [Codeception/Codeception#782]
https://github.com/Codeception/Codeception/issues/185

$I->fillField('#f-this-error', 'Test New');

Gives this error:

```
Behat\Mink\Exception\ElementException: Exception thrown by (//html/descendant-or-self::*[@id = 'f-this-error'])[1]
Form submit button for field with xpath "(//html/descendant-or-self::*[@id = 'f-this-error'])[1]"not found.
```

**Comment by chetanakambad** [comment]
There was 1 failure:

---------
1) Failed to log in as regular user in SigninCept (C:\xampp\htdocs\yii\basic\tests\acceptance\SigninCept.php)
Couldn't fill field "username","admin":
Form field by Label or CSS 'username' was not found on page.

Scenario Steps:
2. I fill field "username","admin"
1. I am on page "/login"


FAILURES!
Tests: 1, Assertions: 0, Failures: 1.
give soln.

**Comment by yvoloshin** [comment]
I've just had the exact problem described by @AndreasHeiberg. I solved it by moving the Submit button inside the form, between form_widget and form_end.  The code that renders the form now looks like this:
```
{{ form_start(edit_form) }}
{{ form_widget(edit_form) }}
 <div class="row">
    <input type="submit" value="Update" class="btn btn-custom" />
 </div>
 {{ form_end(edit_form) }}`
```

I'm using Codeception 1.8.0. Would be very useful if this quirk was included in the Codeception documentation!
