### ISSUE TITLE
Explain errors in Doctrine2

### ISSUE THREAD

**Issue by iniweb** [Codeception/Codeception#84]
I think Codeception must tell readable errors, if table doesn't have record, because current error, not correct, for example:

```php
public function insertAndGetRecord(CodeGuy $I)
{
    $I->expect('Object would be added in database, ParamGroup table.');

    $paramGroup = new $this->entityClass;

    $I->persistEntity($paramGroup, array('title' => 'Just title'));

    $I->seeInRepository('CatalogBundle:ParamGroup', array('title' => 'test'));
}
```

This test by steps return:

```bash
Running Codeception\TestCase\Cest::insertAndGetRecord
Scenario:

I expect Object would be added in database, ParamGroup table.
* I persist entity "CatalogBundle\Entity\ParamGroup",{"title":"Just title"}
* I see in repository "CatalogBundle:ParamGroup",{"title":"test"}
  ERROR

Time: 1 second, Memory: 32.50Mb

There was 1 error:

---------
1) Codeception\TestCase\Cest::insertAndGetRecord
ReflectionException: Property repositories does not exist
```

If i make correct test where both titles will be equal, all is ok.

And i don't get, how i should understand, what exactly i doing wrong by "ReflectionException"...

**Comment by zbateson** [comment]
Hi @iniweb - I'm cleaning up old Codeception issues.  This one's a couple years old - if it's still an issue please leave a comment and let me know, and I'll be happy to reopen and look after it.

Thank you
