### ISSUE TITLE
REST module CURL Options

### ISSUE THREAD

**Issue by jonphipps** [Codeception/Codeception#841]
I'd like to set the CURL option in the REST module to not follow redirects so that I can test the redirect headers:

``` php
$I = new ApiGuy($scenario);
$I->wantTo('check a request for redirect to html');
$I->haveHttpHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
$I->sendHEAD("Elements/c");
$I->seeResponseCodeIs(301);
```

But setting:

``` yaml
REST:
  curl:
    CURLOPT_FOLLOWLOCATION: false
```

...has no effect on the REST module and `curl` doesn't seem to be a real option.
Is there a way to set this option in this module? Or is there a simple way to do an http `HEAD` request in PhpBrowser?

**Comment by rajkumar7it74** [comment]
Hi, can i use PHP variable or PHP constant in place of url in config of PhpBrowser.

Thanks

**Comment by Naktibalda** [comment]
@rajkumar7it74 Read http://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Parameters
