### ISSUE TITLE
Location of bootstrap.php.cache in Symfony2

### ISSUE THREAD

**Issue by ghost** [Codeception/Codeception#858]
Hi guys,

I just started to implement Codeception into my app. Everything seems to be working fine but when it comes to unit tests it fails.

I have installed Codeception into a bundle. But now Codeception is telling me that it is not able to find the bootstrap.php.cache-file. Of course it is not able to because the Symfony2-module of Codeception is searching in the project directory for it which is the folder where Codeception has been installed to (in my case: a bundle!). 

My work-around: symbolic link from bundle to the app-folder. That is definitely not want I want as a Symfony2-User! Am I doing something wrong?

Best regards,
Dennis

**Comment by ravindrakhokharia** [comment]
@dennito try providing the var_path - as below 
        Symfony2:
            var_path: '../../../app'
            app_path: '../../../app'

It will get the exact path to the bootstrape cache.

**Comment by ravindrakhokharia** [comment]
@DavertMik 

Looking from the Symfony2.php module class for symfony2, 
var_path is used in _initialize routine, which will be useful for the path to bootstrape cache.
app_path is used in the getKernelClass() which is searching for the Kernel file

So i would rather suggest to use the specific config names, like cache_path, and kernel_path
Thanks !
