### ISSUE TITLE
RFC: Better documentation

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#860]
This is a place where you can ask for MORE documentation. If something is unclear to you, or you have ideas what can be documented better - please post your suggestions here, so I could improve docs when I have time.

**Comment by Naktibalda** [comment]
#3458

**Comment by DavertMik** [comment]
Issue is closed. 
Create new Issues with proposals, send pull requests, or write your own advices in [Codeception Cookbook](http://phptest.club/c/codeception/cookbook)
