### ISSUE TITLE
Incorrect replace in Db module

### ISSUE THREAD

**Issue by Lambik** [Codeception/Codeception#888]
Hi,

I think in the Db module _initialize() there is a small regex error:

    $sql = preg_replace('%/\*(?!!\d+)(?:(?!\*/).)*\*/%s', "", $sql);

Should probably be

    $sql = preg_replace('%/\*(!?!\d+)(?:(?!\*/).)*\*/%s', "", $sql);

Because the first does not match this line:

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;

While the second line does.

However, I only know mysql, so maybe the regex is correct for other sql variants.

**Comment by Naktibalda** [comment]
It isn't an error, conditional comments contain code and it is meant to be executed if version of mysql server is equal or newer than specified version.
