### ISSUE TITLE
Configuration initial browser size

### ISSUE THREAD

**Issue by sebastianneubert** [Codeception/Codeception#899]
Hi,

I found the option to resize the browser window (chrome) with the methods:

``` php
$I->maximizeWindow();
$I->resizeWindow(400,200);
```

That's cool and works.
Is there a possibility to set a initial window size in the configuration.yml? I prefer to run all functional tests in a maximized window and don't want to setup each test via setUp().

Greets
Sebastian

**Comment by dkotin** [comment]
currently not working 
```
"errorMessage":"Element is not currently interactable and may not be manipulated" 
```

**Comment by petrisorionel** [comment]
I try to use $I->maximizeWindow(); and Chrome window don't maximize.

I use this in _before() also in a test case.
