### ISSUE TITLE
Can't launch tests with chrome-driver

### ISSUE THREAD

**Issue by maxibello** [Codeception/Codeception#908]
I make a symlink /usr/bin/google-chrome to the actual Chrome binary.
But when I run the tests I get an error:

```
  [UnhandledWebDriverError]                                                                          
  The path to the driver executable must be set by the webdriver.chrome.driver system property; for  
   more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version ca  
  n be downloaded from http://chromedriver.storage.googleapis.com/index.html  
```

What's wrong?

**Comment by learntech123** [comment]
Hi,

Could anyone help me with my chrome issue.

I am able to launch chrome browser. But it just opens and gets terminated. It's giving some unsupported warning in chrome. Please check the attached screen sheet.

And my acceptancesuite.yml file code is 


class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://localhost:81/proj
            browser: 'chrome'
        - \Helper\Acceptance

and I am using the below command to run selenium
java -jar s.jar -Dwebdriver.chrome.driver=C:\BhavyaGowda\Codeception\Codeceptionpractice\chromedriver.exe

and using the below command to run the test
php codecept.phar run tests\acceptance\loginCept.php

Downloaded chromedriver form the link http://chromedriver.storage.googleapis.com/index.html
And my system is 64 bit windows. And I could not see any chrome driver for 64 bit. So downloaded the driver for 32 bit. Just wondering if that is the problem.

Pl advise me to resolve

![chromeerror](https://cloud.githubusercontent.com/assets/14229462/10814628/e121c690-7e8b-11e5-869e-cad2d4f2f451.png)

**Comment by SamMousa** [comment]
For me it works without selenium, using the `--url-base` param:
````
chromedriver --url-base=wd/hub
````
````
WebDriver:
#            url: 'http://localhost:12345'
            url: 'http://192.168.37.2:12345'
            browser: phantomjs
            host: '192.168.37.1'
````
