### ISSUE TITLE
global module config in sf2-app

### ISSUE THREAD

**Issue by dennito** [Codeception/Codeception#926]
hey folks,

I am trying to configure my modules on a global scale. It's a Symfony2-App where I want to have my tests separated in bundles. I have my global codeception.yml in ./app/config and my tests are in ./Tests/Appname/BundleName each created through the bootstrap command. Due to the similarity of the module configs in the bundles I want to have ONE global config for them so I don't need to edit every config manually. But unfortunately it does not work if I put all the module config stuff into the global codeception.yml in ./app.config - the tests are always failing if I do so. Is there any solution for this problem? Would be very thankful for every hint! thanks in advance!

Cheers!
Dennis

**Comment by raistlin** [comment]
http://codeception.com/09-04-2015/using-codeception-for-symfony-projects.html
