### ISSUE TITLE
Missing font on 2.0 beta

### ISSUE THREAD

**Issue by Phil-Barker** [Codeception/Codeception#931]
I'm not sure if this is something I've done but running with the --codecoverage-html option I get the following error

```
[ErrorException]
  copy(phar:///projects/xxx.dev/codecept.phar/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/Template/fonts/gl
  yphicons-halflings-regular.eot): failed to open stream: phar error: "vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/Tem
  plate/fonts/glyphicons-halflings-regular.eot" is not a file in phar "/projects/despatchbaypro.dev/codecept.phar"
```

**Comment by sas05** [comment]
failed to open stream: phar error: "vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/Template/fonts/glyphicons-halflings-regular.woff2" is not a file in phar

still having the same problem Codeception version 2.0.13
