### ISSUE TITLE
Facebook Module: amOnPage calls not working in haveTestUserLoggedInOnFacebook()

### ISSUE THREAD

**Issue by whatknows** [Codeception/Codeception#947]
I believe there is either an error in a method of the Facebook module, or with me.

I am running the sample acceptance test provided in the Facebook module doc, and get an exception here:
```
$I->haveTestUserLoggedInOnFacebook(); // so that facebook will not ask us for login and password
```
 
I think the trouble is in these three lines:
```
        $phpBrowser->amOnPage('https://www.facebook.com/');
        $phpBrowser->amOnPage($this->grabFacebookTestUserLoginUrl());
        $phpBrowser->seeCurrentUrlMatches('~/profile.php~');
```
Instead of hitting Facebook's server, the first and last line above hit:
http://localhost:8000/?_fb_noscript=1
http://localhost:8000/checkpoint/test-user-login/100008053842420/?_fb_noscript=1

Clearly those calls are being rewritten to use the localhost in my acceptance.suite.yml, but I don't know what to do about it. Is this a bug? Or a configuration error on my part?

**Comment by JarJak** [comment]
There is a need to implement new Facebook SDK in Facebook Driver:
https://github.com/facebook/facebook-php-sdk-v4
For now Facebook module is not even working (old URLs etc.) and the 5.0 version of SDK does not even have FacebookSession class.

**Comment by Naktibalda** [comment]
You are the best candidate to implement it.
