### ISSUE TITLE
How to generate code coverage as .clover

### ISSUE THREAD

**Issue by nexik** [Codeception/Codeception#969]
I need this format for scrutinizer code coverage upload

docs for code coverag in scrutinizer:

```
phpunit --coverage-clover=coverage.clover
wget https://scrutinizer-ci.com/ocular.phar
php ocular.phar code-coverage:upload --format=php-clover coverage.clover
```

I looks like the coverage.xml is not supported :(

**Comment by Faryshta** [comment]
which were the commands used to create and upload the file with codeception?
