### ISSUE TITLE
pgsql with schemas?

### ISSUE THREAD

**Issue by rzmz** [Codeception/Codeception#970]
Suppose I have a database with schemas not named "public"? How to use for an example:

$I->haveInDatabase('schema.table', $data); ?

Right now the SQL is (thanks to method getQuotedName($name) in PostgreSQL driver) something like: 

INSERT INTO "schema.table" (...

And I get an error: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "schema.table" does not exist.

Any ideas?

**Comment by Naktibalda** [comment]
Fixed by #1487
