### ISSUE TITLE
Wrong values for select

### ISSUE THREAD

**Issue by Koudy** [Codeception/Codeception#984]
Why I can't test select with values ​​that are not among the options? Get error:
```
Input "Form[field_name]" cannot take "" as a value (possible values: one, two).
```
User can make it through firebug or simply pass the request. How do I test it?

**Comment by zbateson** [comment]
Hi @Koudy - I noticed there hasn't been a response on this issue for a while - if you're still having an issue, please leave a comment and we can reopen it.
