### ISSUE TITLE
haveInDatabase can't delete inserted data without id

### ISSUE THREAD

**Issue by ninboy** [Codeception/Codeception#989]
The Db module right now can insert data on the database under the premise that it can delete the data after the tests are done. This is not true if you have a table that doesn't have an "id" column, or if the type of the column is not an integer.

Right now you can test this if you create a table with an UUID as a primary key. In Postgres the haveInDatabase will fail and make the testing stop completely (because the database fails) and the data will be added to the table.

On the Db Module source (https://github.com/Codeception/Codeception/blob/master/src/Codeception/Module/Db.php#L213) you can see that it cast the type

``` php
$lastInsertId = (int) $this->driver->lastInsertId($table);
$this->insertedIds[] = array('table' => $table, 'id' => $lastInsertId);
```

And on the driver source you can see it deletes based on an 'id' column that may not be present (https://github.com/Codeception/Codeception/blob/master/src/Codeception/Lib/Driver/Db.php#L139)

``` php
$query = "delete from $table where id = $id";
```

Instead of deleting exactly what you passed, like this:

``` php
$query = "delete from $table where data1 = $data1 and data2 = $data2 ...";
```

I propose some changes:
1) Passing an argument to make it _not_ delete the data. I don't think this is the solution, though.
2) Making it delete the exact same record that was added. This could be made changing the deleteQuery to use all the data you initially used instead of supposing there is an 'id'. This could break previous tests that are already using this, so I don't think this is the solution either.
3) Passing an additional argument to make it delete _exactly_ what it created. If this argument is false (default) it will do the same that is doing right now, but if it's true it will try to delete using the data that you passed. This way all the tests that already rely on this can continue to do so and the original problem can be addressed.

I can send a pull request fixing this, but I will need feedback from the project managers to know which one is the best solution.

**Comment by erdemkeren** [comment]
Dead link: http://codeception.com/docs/03-ModulesAndHelpers#Extension-options

**Comment by Naktibalda** [comment]
The original link pointed to http://web.archive.org/web/20140428045400/http://codeception.com/docs/03-ModulesAndHelpers#Extension-options

Up to date link is http://codeception.com/docs/06-ReusingTestCode#Additional-options
