### ISSUE TITLE
No Console Output

### ISSUE THREAD

**Issue by tamitutor** [Codeception/Codeception#991]
Greetings,

I love your framework, thank you very much!  However, I'm running into an issue seeing any console output.  On my local development box I see output but on our ec2 server instance there is none.  

On the server, I've combed through the php.ini and am not seeing anything settings-wise that could effect this.  The following little script also sends output to the shell--again on the server:

<?php
    print("This should print");
    echo "on the command line";
?>

So if I can printf/echo out to console the above why is Codeception silent?  

FYI--This IS what I'm seeing when running codeception...

#########BEGINNING OF OUTPUT#########
Codeception PHP Testing Framework v1.8.5
Powered by PHPUnit 3.7.37 by Sebastian Bergmann.
#########ENDING OF OUTPUT#########

"php codecept.phar run --steps" doesn't change the above...

**Comment by Naktibalda** [comment]
Not reproduced
